### ISSUE TITLE
Simplify boolean expression inspection should not modify PSI

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1000]
See https://github.com/intellij-rust/intellij-rust/commit/e0962ec008e9ed9f8031ecd3d12ca57be1b20fbb

The problem is that inspection tries to change PSI. I've disabled the inspection by default for now. 

This can be hacked around by coping the PSI node, like we do in the intention, but I wonder if this can be done more efficiently, without coping? What if we parametrize the simplification function with the return value, such that it returns `Unit` in query mode and `RsExpr` in execute mode? 

cc @slavam2605

**Comment by matklad** [comment]
:100:0

**Comment by slavam2605** [comment]
@matklad Should it be closed?

**Comment by matklad** [comment]
Indeed!
