### ISSUE TITLE
"Click to see difference" is hard to read, the output is printed in a single line

### ISSUE THREAD

**Issue by demurgos** [intellij-rust/intellij-rust#10000]
## Environment

* **IntelliJ Rust plugin version:** 0.4.186.5143-222
* **Rust toolchain version:** 1.66.1
* **IDE name and version:** IntelliJ IDEA Ultimate 2022.3.1
* **Operating system:** Linux

## Problem description

When a standard `assert_eq!` fails, the "Click to see difference" button opens a view with a single line. This makes it hard to compare differences when the types get long (e.g. large nested structs):

![image](https://user-images.githubusercontent.com/2262218/213293473-561d7a3a-ef81-464e-ae92-bf7e70ae4d32.png)

<details>
<summary>Content of the bottom panel</summary>

```
Left:  Listing { offset: 0, limit: 10, count: 1, is_count_exact: false, items: [Some(ShortGame { id: GameId(782c158d-720f-44d3-88cd-83b49fbfceac), created_at: Instant(2021-01-01T00:00:02Z), key: None, owner: ShortUser { id: UserId(00000000-0000-0000-0001-00 ...

Right: Listing { offset: 0, limit: 10, count: 1, is_count_exact: false, items: [Some(ShortGame { id: GameId(782c158d-720f-44d3-88cd-83b49fbfceac), created_at: Instant(2021-01-01T00:00:02Z), key: None, owner: ShortUser { id: UserId(00000000-0000-0000-0001-00 ...

<Click to see difference>

thread 'test_create_game' panicked at 'assertion failed: `(left == right)`
  left: `Listing { offset: 0, limit: 10, count: 1, is_count_exact: false, items: [Some(ShortGame { id: GameId(782c158d-720f-44d3-88cd-83b49fbfceac), created_at: Instant(2021-01-01T00:00:02Z), key: None, owner: ShortUser { id: UserId(00000000-0000-0000-0001-000000000001), display_name: UserDisplayName("Alice") }, channels: Listing { offset: 0, limit: 1, count: 1, is_count_exact: false, items: [ShortGameChannel { key: GameChannelKey("main"), is_enabled: true, revision: ShortGameRevision { version: SimpleSemVer { major: 2, minor: 0, patch: 0 }, git_commit_ref: None, build: ShortGameBuild { main_locale: FrFr, display_name: GameDisplayName("Sous la colline"), description: GameDescription("Aidez Igor"), icon: Some(Blob { id: BlobId(49dece1e-33a4-4435-83e6-e655d07f8b88), media_type: MediaType("image/png"), byte_size: 80805, digest: BlobDigest { sha2_256: DigestSha2([252, 174, 213, 36, 109, 8, 49, 34, 23, 86, 186, 185, 242, 173, 210, 78, 27, 133, 112, 245, 42, 50, 0, 221, 71, 138, 67, 9, 40, 43, 209, 160]), sha3_256: DigestSha3([176, 2, 106, 8, 1, 6, 123, 167, 108, 110, 26, 191, 141, 195, 140, 191, 86, 254, 2, 180, 170, 1, 47, 213, 133, 87, 252, 190, 93, 179, 66, 158]) } }), i18n: {EnUs: ShortGameBuildI18n { display_name: Some(GameDisplayName("Under the hill")), description: Some(GameDescription("Help Igor")), icon: Some(Blob { id: BlobId(f0f41695-8d5b-48e7-9fa6-d1d6e1c2db0a), media_type: MediaType("image/png"), byte_size: 75043, digest: BlobDigest { sha2_256: DigestSha2([68, 237, 213, 133, 24, 126, 228, 208, 251, 119, 99, 122, 255, 219, 33, 232, 174, 218, 153, 204, 9, 217, 210, 46, 47, 219, 203, 41, 61, 42, 48, 158]), sha3_256: DigestSha3([177, 20, 21, 42, 144, 214, 187, 131, 184, 108, 104, 75, 63, 83, 121, 85, 165, 62, 106, 52, 136, 204, 194, 113, 108, 120, 123, 232, 232, 86, 218, 18]) } }) }} } } }] } })] }`,
 right: `Listing { offset: 0, limit: 10, count: 1, is_count_exact: false, items: [Some(ShortGame { id: GameId(782c158d-720f-44d3-88cd-83b49fbfceac), created_at: Instant(2021-01-01T00:00:02Z), key: None, owner: ShortUser { id: UserId(00000000-0000-0000-0001-000000000001), display_name: UserDisplayName("Alice") }, channels: Listing { offset: 0, limit: 1, count: 1, is_count_exact: false, items: [ShortGameChannel { key: GameChannelKey("main"), is_enabled: true, revision: ShortGameRevision { version: SimpleSemVer { major: 1, minor: 0, patch: 0 }, git_commit_ref: None, build: ShortGameBuild { main_locale: FrFr, display_name: GameDisplayName("Sous la colline"), description: GameDescription("Aidez Igor"), icon: Some(Blob { id: BlobId(49dece1e-33a4-4435-83e6-e655d07f8b88), media_type: MediaType("image/png"), byte_size: 80805, digest: BlobDigest { sha2_256: DigestSha2([252, 174, 213, 36, 109, 8, 49, 34, 23, 86, 186, 185, 242, 173, 210, 78, 27, 133, 112, 245, 42, 50, 0, 221, 71, 138, 67, 9, 40, 43, 209, 160]), sha3_256: DigestSha3([176, 2, 106, 8, 1, 6, 123, 167, 108, 110, 26, 191, 141, 195, 140, 191, 86, 254, 2, 180, 170, 1, 47, 213, 133, 87, 252, 190, 93, 179, 66, 158]) } }), i18n: {} } } }] } })] }`', crates/services/tests/game.rs:348:3
```

</details>

This is not a severe bug but it's a somewhat frustrating quality of life issue. When using the "Click to see difference" feature in TypeScript (with chaijs assertions) it's very helpful as the output is formatted with newlines. However when I switch to Rust, the diff feature is basically useless with the standard `assert_eq!`. Either the output is short so I can directly compare in the bottom panel, or the output is very long but printed as a single line so it's very hard to compare.

I understand that fixing this issue may be a bit complex as it depends on the builtin Rust test framework, but it would be great if there was a way to improve the situation. The best solution may be to use the pretty-printed debug formatting (`{:#?}`, but it may require some specific integration. Another solution would be to have a "prettify" feature in the diff viewer that could reformat the output using some heuristics. It doesn´t need to get new lines perfectly as long as it uses the same formatting for the left and right sides.

## Steps to reproduce

1. Write a test comparing types with a long `Debug` view using the standard `assert_eq!` macro. Here is an example using two vecs with 32 elements:
   ```rust
   #[test]
   pub fn test_vec_eq() {
     let actual = {
       let mut arr = ["foo"; 32];
       arr[20] = "bar";
       arr.to_vec()
     };
     let expected = ["foo"; 32].to_vec();
     assert_eq!(actual, expected);
   }
   ```
2. Execute the test through the IDE
3. In the failed test details, select "\<Click to see difference>"
4. The diff view opens, but it formats everything on a single line for both sides:
   
   ![image](https://user-images.githubusercontent.com/2262218/213295391-0daeea42-5a8e-4a7a-8415-d16afd4555dd.png)

**Comment by Undin** [comment]
Described behaviour is expected. The plugin is not supposed to format output of `assert_eq` macro. And in your case, `assert_eq` provides one line output for each item. It's quite convenient - you know that the plugin doesn't change output, so you may produce your pretty text for it and get the expected result. I don't expect any changes in this behaviour.

Also, you can make soft wrap of lines in diff view. Click the settings icon in the middle of the toolbar at the top and choose `Soft-wrap` option

<img width="1188" alt="Screenshot 2023-01-18 at 22 25 01" src="https://user-images.githubusercontent.com/2539310/213298260-54c236a4-bf24-495d-b20b-8332f76f6952.png">

**Comment by demurgos** [comment]
Okay, thank you for the explanation. It means that if I want to have a multiline output by default, I should handle it at the Rust level.

I also searched for a Soft-wrap mode but somehow missed it, now I feel a bit silly for missing it. It should already help a lot
