### ISSUE TITLE
incorrect unused import in tests mod

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#10015]
## Environment

* **IntelliJ Rust plugin version:** 0.4.187.5153-223-nightly
* **Rust toolchain version:** rustc 1.68.0-nightly (4c83bd03a 2023-01-19)
* **IDE name and version:** Clion 2022.3.1
* **Operating system:** Archlinux

## Problem description
https://github.com/Sherlock-Holo/http_dir/blob/master/src/serve_file/mod.rs#L155

this mod is a unit test mod, all `use` entires are used, but intellij-rust thinks all of them are unused

![image](https://user-images.githubusercontent.com/10096425/213724061-5fefd579-185c-468b-aefc-0811dc3251ac.png)

when use Ctrl+Alt+L will remove them and make the codes broken

**Comment by afetisov** [comment]
FYI, you can use `Ctrl + Alt + Shift + L` (`Reformat File` action) to open a more detailed formatting menu. You can disable `Optimize Imports` there, so that reformatting doesn't remove them. I believe the setting is saved for all other reformat actions.

Anyway, unused import detection in the plugin is quite unreliable. I suggest disabling the inspection and relying on the external linter.

**Comment by Sherlock-Holo** [comment]
> FYI, you can use `Ctrl + Alt + Shift + L` (`Reformat File` action) to open a more detailed formatting menu. You can disable `Optimize Imports` there, so that reformatting doesn't remove them. I believe the setting is saved for all other reformat actions.
> 
> Anyway, unused import detection in the plugin is quite unreliable. I suggest disabling the inspection and relying on the external linter.

removing unused import is a helpful feature for me when rewrite my project, without it i have to remove them manually

**Comment by Sherlock-Holo** [comment]
@Undin @afetisov 
is there any progress about this problem?

the nightly version 0.4.189.5212-223-nightly still has these problem

**Comment by dima74** [comment]
Minimal example:
```toml
[dependencies]
tokio = { version = "1", features = ["macros", "rt" ] }
```
```rust
use inner::func;
mod inner {
    pub fn func() {}
}

#[tokio::test]
async fn test1() {
    func()
}
```
It doesn't happen with `rt-multi-thread` feature instead of `rt`
