### ISSUE TITLE
Persistant Rust Settings

### ISSUE THREAD

**Issue by michaelyang02** [intellij-rust/intellij-rust#10013]
## Environment

* **IntelliJ Rust plugin version:** 0.4.186.5143-223
* **Rust toolchain version:** 1.66.1
* **IDE name and version:** PyCharm 2022.3.1 (Professional Edition)
* **Operating system:** Pop!_OS 22.04 LTS x86_64

## Problem description
Improvement/Feature

Currently, rust-related settings do not persist through new projects. This includes but is not limited to:
- External Linters > External tool / On the fly
- Rustfmt > Use Rustfmt instead of built-in formatter

## Steps to reproduce
1. Create new project
2. Change above settings
3. Create another new project
4. Settings reverted to the default

**Comment by Undin** [comment]
The same option to adjust default project settings is also available via `File | New Projects Setup | Settings for New Projects`
