### ISSUE TITLE
Broken colors on Ubuntu with the latest update

### ISSUE THREAD

**Issue by botev** [intellij-rust/intellij-rust#1002]
I've just updated the plugin and the color scheme on the IntelliJ `Run` console are gone. This was working correctly with the previous version. This is despite that the run command has `--color=always`. Screen shot below:

![screenshot from 2017-02-13 15 00 57](https://cloud.githubusercontent.com/assets/1889878/22888374/5b42d3fc-f1fd-11e6-8454-978f9b3ab857.png)

**Comment by la10736** [comment]
I guess is a #988 's duplicate

**Comment by alygin** [comment]
As a temporary workaround, try to add the environment variable `TERM=linux` to the run configuration.

**Comment by matklad** [comment]
Should be closed now for real, thanks for the report!
