### ISSUE TITLE
Allow disabling gutter icons 

### ISSUE THREAD

**Issue by afetisov** [intellij-rust/intellij-rust#10036]
## Environment

* **IntelliJ Rust plugin version:** 0.4.187.5153-223-nightly
* **Rust toolchain version:** 1.66.1 (90743e729 2023-01-10) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.3.1 (CL-223.8214.51)
* **Operating system:** Linux 5.4.0-137-generic
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.macros.proc

## Problem description

Intellij has a menu `Settings > Editor > General > Gutter Icons`, which allows to disable different kinds of gutter icons for different languages. Rust plugin currently has no options in this menu, and all icons are always enabled.

**Comment by Undin** [comment]
Wow
I didn't know about such settings.

BTW you can copy a settings path via `Copy Preferences Path` action from context menu of the corresponding item. It saves a lot of time when I create issues

<img width="320" alt="image" src="https://user-images.githubusercontent.com/2539310/215345574-c14cfeb8-1cf2-42c2-acfb-d6c3a76156ff.png">
