### ISSUE TITLE
Several papercuts

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1007]
* tmod, tfn and frends should not be available inside the function, especially after `.`:

```
fn read_door_id() -> String {
    let mut buff = String::new();
    ::std::io::stdin().read_line(&mut buff).unwrap();
    buff.t
}
```

* nested postfix match should work

```
    match a {
        _ => b.ma
    }
```

**Comment by alygin** [comment]
It should be possible to bind code templates to patterns from `RsKeywordCompletionContributor`. Is it?

**Comment by matklad** [comment]
>It should be possible to bind code templates to patterns from RsKeywordCompletionContributor. Is it?

Yes, though I think usually that's handled by live templates (see how Kotlin expands `for` and `iter`)

This issue is about postfix templates: we expand `a.match` to 

```
match a {
    _ => 
}
```

but the nested one just spectacular breaks the code around :(

**Comment by mkaput** [comment]
Possibly, but you would loose configurability provided by intellij. 

The other way is better: you can bridge `RsContextType.isInContext` methods with completion counterparts, which should be the case here (current implementations aren't polished a lot)

**Comment by matklad** [comment]
Will leave this beautifully weird piece valid of Rust here:

```Rust
fn main() {
    match match match match match () {
        _ => {}
    } {
        _ => {}
    } {
        _ => {}
    } {
        _ => {}
    } {
        _ => {}
    }
}
```

**Comment by matklad** [comment]
fixed in https://github.com/intellij-rust/intellij-rust/commit/44ff6f209905c7185419afc89bc07537e5bb4266 and https://github.com/intellij-rust/intellij-rust/commit/95de08ed03ade84a02967466a7830ed53dcd9be2

**Comment by alygin** [comment]
`main` is not available at the file level now :(
