### ISSUE TITLE
Some debugger settings are cleared on restart

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#10089]
## Environment

* **IntelliJ Rust plugin version:** 0.4.189.5188-231-nightly
* **Rust toolchain version:** 1.69.0-nightly (001a77fac 2023-01-30) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2023.1 EAP Ultimate Edition (IU-231.6471.13)
* **Operating system:** macOS 12.5.1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.emulate.terminal

## Problem description

It happens at least with:
1. Break on panic
2. Do not step into stdlib

## Steps to reproduce
1. Enable checkboxes 
2. Restart IDE
3. Open settings. See disabled checkboxes

**Comment by Kobzol** [comment]
When I launch CLion from the development environment (`Run CLion`), no debugger options are saved (GDB/LLDB renderers, break on panic). When I launch a "normal" CLion (`2022.3.1`), it works.

Maybe something in #7489 broke the serialization. I wonder if I have to make `RsStepFilterSettings` serializable somehow?

**Comment by ortem** [comment]
@Kobzol Thanks for checking this out. I've added a comment to the corresponding code review
