### ISSUE TITLE
Don't scroll to the end on build

### ISSUE THREAD

**Issue by kryptan** [intellij-rust/intellij-rust#1008]
This may sound like a silly issue but every time I build a project **Run** window with the build log scrolls down to the end. However, I want to start fixing errors starting from the first one, not from the last. I have to manually scroll to the top after each build which is very annoying because there are usually many errors. I have not found a way to disable this behavior; there is a "Scroll to the end" switch but it always gets automatically enabled on each build.

**Comment by alygin** [comment]
I'm not sure if it's possible to prevent output scrolling, but you can use the `Up/Down the stack trace` commands (it's cmd + alt + up/down on Mac) that will guide you through all the compiler messages, automatically scrolling the output and positioning the cursor to the correct place in the source code.

**Comment by matklad** [comment]
Should be closed by https://github.com/intellij-rust/intellij-rust/pull/1985
