### ISSUE TITLE
Plugin settings are not permanent

### ISSUE THREAD

**Issue by sebastian0x62** [intellij-rust/intellij-rust#10100]
## Environment

* **IntelliJ Rust plugin version:** 0.4.187.5175-231
* **Rust toolchain version:**
* **IDE name and version:** GoLand
* **Operating system:** Windows 11

## Problem description

Settings for the Rust plugin for "External Linters" and "Rustfmt" are only temporary set. After a while my changes are unchecked.

**Comment by rust1248** [comment]
They are set for the current project only, if you want them to beapplied to new projects, you can go to `File > New Projects Setup > Setting for New Projects...` and change it from there

**Comment by sebastian0x62** [comment]
I had to switch projects quite often. Good point the settings were just change by switching to a new projects. Thank you. I changed that and will keep an eye on it.
