### ISSUE TITLE
Sea_orm code completion not working when in another crate.

### ISSUE THREAD

**Issue by wyatt-herkamp** [intellij-rust/intellij-rust#10127]
## Environment

* **IntelliJ Rust plugin version:** 0.4.189.5208-223-nightly
* **Rust toolchain version:** 1.67.1 (d5a82bbd2 2023-02-07) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2022.3.2 (CL-223.8617.54)
* **Operating system:** Windows 11 10.0
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr, org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.macros.proc

## Problem description
Code completing and text highlighting is not working for sea_orm if the code is in another crate. 
[Example Project](https://github.com/wyatt-herkamp/intellij_rust_bug/)

## Steps to reproduce

As you can see inside the lib.rs the text highlighting is not working 
![img](https://user-images.githubusercontent.com/11785959/219055692-e34435a8-3f22-47c1-95e5-0d83eec76a70.png)

The autocomplete is not working for the functions derived from sea_orm in the other crate
![img_1](https://user-images.githubusercontent.com/11785959/219055712-65feaae6-0116-4953-ad40-8e72deffaa86.png)

If we go into the database_helpers module inside the entities crate. All the features are working. 
![img_2](https://user-images.githubusercontent.com/11785959/219055735-2c7b9823-634f-4292-b87b-b781e48da972.png)

The text highlighting and autocomplete is working for functions you made in the entities crate.
![img_3](https://user-images.githubusercontent.com/11785959/219055756-08bc4a88-3f88-482a-ae48-16289f111ebb.png)

**Comment by billy1624** [comment]
Hey @wyatt-herkamp, I believe this has something to do with intellij's Rust analyzer but feel free to ping me if you need my help.

Cheers,
Maintainer of SeaORM :)

**Comment by wyatt-herkamp** [comment]
As a note this error is not present in https://rust-analyzer.github.io/

![](https://user-images.githubusercontent.com/11785959/219091481-4335d77d-a237-4800-a89b-2fbd25349c9a.png)

**Comment by wyatt-herkamp** [comment]
> Hey @wyatt-herkamp, I believe this has something to do with intellij's Rust analyzer but feel free to ping me if you need my help.
> 
> Cheers, Maintainer of SeaORM :)

Yeah, I only noticed it when using SeaORM. So it was easier to use it for the example.

**Comment by wyatt-herkamp** [comment]
## Environment

* **IntelliJ Rust plugin version:** 0.4.193.5312-231-nightly
* **Rust toolchain version:** 1.68.1 (8460ca823 2023-03-20) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2023.1.1 (CL-231.8109.222)
* **Operating system:** Windows 11.0
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr, org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.ide.intentions.macros.function-like, org.rust.macros.proc

It has seemed to start working recently. Closing the issue.

**Comment by billy1624** [comment]
Thanks for the updates! @wyatt-herkamp

**Comment by Xiaobaishushu25** [comment]
hello ,i also meet this question,Could you please take a look？this is my environment
- IntelliJ Rust plugin version: 0.4.196.5423-231

- Rust toolchain version: 1.72.0-nightly (b2b34bd83 2023-06-06)

- IDE name and version: CLion 2023.1.3

- Operating system: Windows 10.0

**-  Macro expansion: enabled ？？sorry ,I've been searching for a long time but dont konw how to enabled Macro expansion.**

- Additional experimental features: org.rust.macros.proc.attr, org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.ide.intentions.macros.function-like, org.rust.macros.proc

I downloaded your instance code，clion cant autocomplete：
![image](https://github.com/intellij-rust/intellij-rust/assets/76581880/71dfa3ac-c278-44a1-a20a-b07ea7b228ad)
It cannot even prompt for UserEntity.and no text highlighting:
![image](https://github.com/intellij-rust/intellij-rust/assets/76581880/a96bd3f5-3125-4b93-b534-452e690d9361)
but Vscode can autocomplete：
![image](https://github.com/intellij-rust/intellij-rust/assets/76581880/38053c78-297e-4157-99da-98639e65cdd1)
How can I solve this problem? It has made the experience of writing rust very poor! Thank you for reading

**Comment by Xiaobaishushu25** [comment]
> hello ,i also meet this question,Could you please take a look？this is my environment
> 
> * IntelliJ Rust plugin version: 0.4.196.5423-231
> * Rust toolchain version: 1.72.0-nightly (b2b34bd83 2023-06-06)
> * IDE name and version: CLion 2023.1.3
> * Operating system: Windows 10.0
> 
> **- Macro expansion: enabled ？？sorry ,I've been searching for a long time but dont konw how to enabled Macro expansion.**
> 
> * Additional experimental features: org.rust.macros.proc.attr, org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.ide.intentions.macros.function-like, org.rust.macros.proc
> 
> I downloaded your instance code，clion cant autocomplete： ![image](https://user-images.githubusercontent.com/76581880/247022125-71dfa3ac-c278-44a1-a20a-b07ea7b228ad.png) It cannot even prompt for UserEntity.and no text highlighting: ![image](https://user-images.githubusercontent.com/76581880/247022493-a96bd3f5-3125-4b93-b534-452e690d9361.png) but Vscode can autocomplete： ![image](https://user-images.githubusercontent.com/76581880/247023167-38053c78-297e-4157-99da-98639e65cdd1.png) How can I solve this problem? It has made the experience of writing rust very poor! Thank you for reading

thank you ，i have konw the reason，because my rust toolchain version is  1.72.0-nightly (b2b34bd83 2023-06-06),i switch it to
 stable-x86_64-pc-windows-gnu unchanged - rustc 1.70.0 (90c541806 2023-05-31) ,now it can work normally！
