### ISSUE TITLE
When resolving external crates, use dependency information

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1015]
Rust has an awesome library/module split at the language level, which allows for linking in two versions of the same library. 

That is, `extern crate foo;` can resolve to different crates depending on which crate this declaration is in. 

Precise dependency DAG is available in `cargo metadata`, but we just lump all external crates to a global namespace: https://github.com/intellij-rust/intellij-rust/blob/723969c995e7991e1bc002454656f1cdb27edd2f/src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt#L84

This causes a trouble if, for example, there are two hypers in the dependency graph, and we resolve to the wrong one and produce false positive error annotations because some functions have changed arity. 

@alygin you might be interested in this bug :)

**Comment by alygin** [comment]
Yeah, I thought of this problem while refactoring `CargoWorkspace` deserialization. It really can lead to incorrect annotations. I'll tackle it, though I need to gain better understanding of how arbitrary path resolve works first.

**Comment by matklad** [comment]
>I need to gain better understanding of how arbitrary path resolve works first.

When resolving a path you just call recursively into resolving external crate: https://github.com/intellij-rust/intellij-rust/blob/43c775bd16e8e6793657c07f7fe29d28c0d10396/src/main/kotlin/org/rust/lang/core/resolve/ResolveEngine.kt#L206

**Comment by alygin** [comment]
> `extern crate foo;` can resolve to different crates depending on which crate this declaration is in.

Is there a way to get the name of the crate a given file belongs to? There's `RsCompositeElement.crateRoot`, but it only allows to get the crate's root file name which is of no help for this task.

**Comment by matklad** [comment]
This is the function that maps files to `Target`s: https://github.com/intellij-rust/intellij-rust/blob/b467a49b08ae011863c7e264be5f69d58a3b5df2/src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt#L89

Crate name in general depends on who's asking: inside the crate, it has no name, outside the crate it's name depends on the `--extern NAME=PATH` flag passed to `rustc`.
