### ISSUE TITLE
Plugin does not know about latest crate versions

### ISSUE THREAD

**Issue by AndreKR** [intellij-rust/intellij-rust#10199]
## Environment

* **IntelliJ Rust plugin version:** 0.4.179.4903-221
* **Rust toolchain version:** 1.69.0-nightly
* **IDE name and version:** CLion 2022.1.3
* **Operating system:** Windows 7

## Problem description
When I activate the autocompletion for the crate version, the latest versions don't show up:
![image](https://user-images.githubusercontent.com/1188538/222931338-96e26f86-ce89-48fa-bfa3-49cd8145401a.png)

`reqwest`'s latest version at this point is [0.11.14](https://docs.rs/reqwest/0.11.14/reqwest/).

If I type that manually, it shows the inspection warning "No version matching 0.11.14 found for crate reqwest":

![image](https://user-images.githubusercontent.com/1188538/222931404-d7b32215-7a23-4cfc-9111-0dce52afe4bf.png)

After disabling `org.rust.crates.local.index` I get the latest versions, but I don't get the autocompletion in long form `<crate> = { version = "...", features = [...] }` items.

This affected almost every dependency in my project.

**Comment by vlad20012** [comment]
Hi!
Do you use a new "Cargo's sparse protocol"?

**Comment by orium** [comment]
I think that's the reason.  I've the same problem after I enabled cargo's sparse protocol.  Note that it should become the default protocol in rust 1.70, unless issues with it are found.
