### ISSUE TITLE
Show length of vec and slice in debugger

### ISSUE THREAD

**Issue by ivan-aksamentov** [intellij-rust/intellij-rust#10209]
## Environment

* **IntelliJ Rust plugin version:** 0.4.189.5234-223
* **Rust toolchain version:** 1.67.1-x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.3.2  Build #CL-223.8617.54, built on January 25, 2023
* **Operating system:** Ubuntu 20.04

## Problem description

Debugging of arrays, vectors and slices, especially of the buffer overruns, is difficult without knowing size of the buffer.

In intellij-rust debugger, it seems to be difficult or impossible to retrieve length of a `vec` or a slice, which makes for a very weak dev experience.

Please consider improving of how containers are rendered:

 - display length of a container 
 - display capacity of a container where possible 

Additionally, consider improving debugging experience around watch exressions:

 - allow for evaluating methods on a container where possible (e.g. `vec.len()`)
 - allow for evaluating iterator expressions (e.g. `vec.iter().filter().collect()`)

## Steps to reproduce

Consider this Rust code:

```rust
fn hello(b: &[i64]) -> Vec<i64> {
  let c: Vec<i64> = b.iter().map(|x| x * 2).collect();
  let lb = b.len();
  let lc = c.len();
  println!("{c:?} {lb} {lc}"); // line 5
  c
}


fn main() {
  let a = vec![0, 2, 5];
  hello(&a);
}
```

Set breakpoint on line 5. And start debugging.

![03](https://user-images.githubusercontent.com/9403403/223089398-003bcbec-5ea8-4327-915d-0dca894265cc.png)

Note that the length or capacity of vec `c` is not shown, unless `c.len` is added to watches.
Adding this expression to watches is okay, but is not convenient when debugging across multiple functions, where a variable being tracked can have different names, or when multiple variables needs attention. The watch window get cluttered quickly with red error messages of variables which are out of scope.  

Note that there is no way to see the length of slice `b`, even by adding a watch. The `.len` does not appear in the list of fields (I guess slice doesn't have it).

Add expression `hello(&c)` (function call), note that the result (a vec) is shown, but in a format that is different from the other vectors, which is confusing.

Add expressions `b.len()` and `c.len()`. Note the error "Could not find function". Note that the result of a call to `hello(&c)` is correctly displayed as  we discovered above, but the calls to any  methods of vec or slice are not.

In the settings we can toggle between bundled renderers and Rust compiler's renderers, but they show the same thing.

Here is the screenshot:

![000](https://user-images.githubusercontent.com/9403403/223090432-a71dd015-afe6-4757-9968-ab0b8d033725.png)

Compare to VSCode's rust-lang.rust-analyzer + ms-vscode.cpptools. It has similar problems with  methods in watch expressions, but at least it shows the length in the variables themselves:

![0001](https://user-images.githubusercontent.com/9403403/223091357-bce522aa-d04b-4267-9a29-30e7f29490fb.png)

Compare to CLion C++, where `std::vector::size()` evaluates correctly:

![00001](https://user-images.githubusercontent.com/9403403/223098468-52810952-8621-4b50-aa53-f88719366f9b.png)

![00002](https://user-images.githubusercontent.com/9403403/223098482-1e7e078e-032b-4da5-b23a-cb1130d250bc.png)

**Comment by ortem** [comment]
@ivan-aksamentov Please try selecting Bundled LLDB in the debugger [settings](https://www.jetbrains.com/help/clion/configuring-debugger-options.html#select-debugger) and let us know if it solves the issue.

Unfortunately, when using GDB, it is an old and well-known problem that CLion cannot show values' summaries (e.g. vector length) together with values' children (e.g. vector elements): https://youtrack.jetbrains.com/issue/CPP-15217

**Comment by ortem** [comment]
@ivan-aksamentov Regarding your question about evaluating iterator (and other) expressions.

Expression evaluation in the debuggers does not support method calls so far. Unfortunately, this cannot be implemented properly until the Rust compiler emits enough debug information about traits: https://github.com/rust-lang/rust/issues/33014. Thus, the issue has to be fixed on the compiler side before implementing this functionality in the debuggers and IDEs.

**Comment by ivan-aksamentov** [comment]
@ortem Thanks Artem! :)

Switching "Default" toolchain's "Debugger" field to "Bundled LLDB" helped! It took me a second to realize that the "size=123" is now shown to the right of the variable type (which gets quite long for vectors, overflows and requires horizontal scrolling). But that's fine. Both vecs and slices show their size now, so my immediate problem is solved.

In terms of UX, I would never guess that CMake toolchains (or, rather, what I thought they are) affect Rust, and I am a little confused as to which exact toolchain Rust uses (I have multiple). I guess it's the "Default" one.

I can think of these improvements:

 - Make toolchain selection more explicit, or at least mention somewhere that "Toolchain" page is relevant for Rust as well (perhaps with a link to it), to increase discoverability
 - Where possible, group all the Rust-related pages, including debugger or toolchain selection, to a separate section in settings, to avoid confusion
 - Ideally, I'd expect Rust to not depend on CMake toolchains, but to have a similar, but separate configuration for things like enforcing a particular rust toolchain version (https://github.com/intellij-rust/intellij-rust/issues/9820) and target architecture (https://github.com/intellij-rust/intellij-rust/issues/5183), so that one ccould select them for a given debug/run configuration.

Thanks again!

**Comment by ortem** [comment]
@ivan-aksamentov Thank you for the comprehensive feedback and great improvement ideas! In fact, not depending on the CLion toolchain and providing Rust-specific debugger settings is one of the priority tasks right now. The process is somehow described already in the [IJ Rust documentation](https://plugins.jetbrains.com/plugin/8182-rust/docs/switching-debuggers-and-renderers.html), but there is room for UX improvements indeed.
