### ISSUE TITLE
Working behind proxy

### ISSUE THREAD

**Issue by Liano** [intellij-rust/intellij-rust#1021]
Hello,
It seems that working behind proxy is not supported, am I wrong?
When I add dependency, they don't get downloaded, moreover the auto-completion is not working with the new dependencies, Although proxy setting is set in intellij idea.
I am on WINDOWS 8.1
Thanks in advance.

**Comment by alygin** [comment]
Hi Liano! Could you try to execute the action `Refresh Cargo project` manually after adding new dependencies? The problem might be that it doesn't trigger automatically.

**Comment by matklad** [comment]
Also it might be the case that you need to configure Cargo itself to work with proxy. See `[http]` key here: http://doc.crates.io/config.html#configuration-keys

**Comment by minecrawler** [comment]
It's a Cargo problem! Refer to rust-lang/cargo#636

**Comment by Liano** [comment]
Thank you for your feedback, I will try your recommendations and post asap.
Thanks again.

**Comment by matklad** [comment]
Hopefully this was fixed by configuring Cargo proxy!

**Comment by lilianmoraru** [comment]
I was planning to open an issue like that(I had this issue for months but decided now to report it...).
In my case, I don't have cargo configured in a special way.
At work, I am behind a proxy that requires authentication.
The terminal exports "http_proxy" and "https_proxy" and cargo works without problems.
In IntelliJ, I have the proxy configured(it can update the IntelliJ-Rust plugin for example) but cargo doesn't pick it up. It is configured the same way the web-browsers are configured - in IntelliJ I have to set "Automatic proxy configuration URL" and give it the path to a file on a server.
In the terminal I guess that it works because I use `cntlm` which authenticates me, then I set `http_proxy` and `https_proxy` to `localhost`.

**Comment by matklad** [comment]
When creating a Cargo process in `org.rust.cargo.toolchain.RustToolchain#cargo`, we need to check the proxy settings and setup envirionment variables:

```
    HttpConfigurable ideHttpProxySettings = HttpConfigurable.getInstance();
    if (ideHttpProxySettings.USE_HTTP_PROXY && isNotEmpty(ideHttpProxySettings.PROXY_HOST))
```

**Comment by anton-okolelov** [comment]
Could I grab it?

**Comment by matklad** [comment]
@anton-okolelov sure, the only problem is that I don't know how to test this properly. If you have a proxy setup and can verify that this solution actually works, that'd be super great!

**Comment by lilianmoraru** [comment]
I forgot to mention, this works now...

**Comment by anton-okolelov** [comment]
Yes, I can setup proxy, no problem with it

**Comment by matklad** [comment]
@lilianmoraru hm, nobody has fixed it as far as I know... @anton-okolelov could you then check if it is indeed still an issue then?

**Comment by lilianmoraru** [comment]
@matklad I think you fixed it a few months ago.
I vaguely remember a refactoring Pull Request from you that fixed the issue.

**Comment by anton-okolelov** [comment]
Okay, I'll check whether it is fixed :)

**Comment by anton-okolelov** [comment]
I added incorrect proxy to ~/.profile
```
export http_proxy=http://193.124.44.150:65233/
export https_proxy=$http_proxy
```
then logout and login
(this ip and port are bad, non working proxy)

And when I added dependency to cargo.toml, intellij-rust couldnt download files. 
After removing incorrect http_proxy / https_proxy variables and relogin, IDE downloaded dependencies successfully.
So it uses environment variables http_proxy / https_proxy when invokes cargo. 

But it doesn't use IDE proxy settings: Appearance & Behavior -> System Settings -> HTTP Proxy. You can set any values there, it doesn't work on cargo downloading process.

**Comment by anton-okolelov** [comment]
Probably we need to do some fixes here:
1) pass IDE proxy settings to cargo. I mean no just to execute "cargo" command, but execute with variables, like "http_proxy=blabla cargo" (for Linux and similar systems). Not sure about Windows way to pass variables.
2) When something goes wrong with downloading external dependencies, IDE should output error message, not just do nothing.

**Comment by lilianmoraru** [comment]
@anton-okolelov At work I use `Automatic proxy configuration URL`, where I give it a file from the internal network and it takes care of setting the proxy.
`http_proxy` would not work for this case.
Shouldn't there be an API in IntelliJ(I've set the proxy inside IntelliJ, it seems to know how to use it correctly and because of that I can update IntelliJ, the plugins, etc...)?

**Comment by matklad** [comment]
Yeah, we have an API for getting a proxy info: https://github.com/intellij-rust/intellij-rust/issues/1021#issuecomment-304652762.

I think we need to setup Cargo's env vars here: https://github.com/intellij-rust/intellij-rust/blob/3c948dd52b61a6e537b0465a29e64326e48ec397/src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt#L106-L110

**Comment by lilianmoraru** [comment]
I am sorry I have mislead you guys.
I just reinstalled my Linux dev machine and I hit these issues again.
The solution I applied now and the one that I applied back then was that I added a bunch of proxy settings in `/etc/environment`, which `IntelliJ Rust`(or `cargo`?) correctly picked up(it did not pick the IntelliJ Proxy Settings though).

**Comment by anton-okolelov** [comment]
@lilianmoraru Yes, IntelliJ Rust successfully picks up linux environment variables, but it also must be able to pick up intelliJ Proxy Settings. As @matklad said, we can pass those settings  [here](https://github.com/intellij-rust/intellij-rust/blob/3c948dd52b61a6e537b0465a29e64326e48ec397/src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt#L106-L110)
