### ISSUE TITLE
LLDB debugger - add pretty printer for NaiveDate

### ISSUE THREAD

**Issue by Jiri42** [intellij-rust/intellij-rust#10219]
## Environment

* **Intellij-Rust plugin version: v0.4.189.5234-223**
* **Rust version:1.67.1**
* **IDE name and version: Goland 2022.3**
* **Operating system: OSX**

## Description
Hi guys, at first I have to thank you for rust plugin, it is really great. I want to add pretty print for chrono structures to make my debugging easier. I found [https://github.com/intellij-rust/intellij-rust/issues/3639](https://github.com/intellij-rust/intellij-rust/issues/3639) where it is solved for GDB debugger. As I understand Goland uses LLDB so I updated llbd files, but it does not work for me.

## Steps to reproduce
I added     
`CHRONO_NAIVE_DATE = "ChronoNaiveDate"`
on the line 51  then
`CHRONO_NAIVE_DATE_REGEX = re.compile(r"^chrono::naive::date::NaiveDate$")`
on the line 110  and
`RustType.CHRONO_NAIVE_DATE: CHRONO_NAIVE_DATE_REGEX,`
on th line 149 among into `STD_TYPE_TO_REGEX` dict in`rust_types.py`

Then I added
```
def ChronoNaiveDateProvider(valobj, _dict):
    # type: (SBValue, dict) -> str
    return "someDate"
```
at the bottom of file `lldb_providers.py`

And then I added:
```
    if rust_type == RustType.CHRONO_NAIVE_DATE:
        return ChronoNaiveDateProvider(valobj, dict)
```

into to the method `def summary_lookup(valobj, dict):` on the line 82 in `lldb_lookup.py `. 

Then I debug this rust code in Golad:
```
fn main() {
  let  r = 0..5;
  let a = chrono::NaiveDate::default();
  let b = chrono::NaiveDate::MIN;
  let c = chrono::NaiveDate::MAX;

  println!(); // here is debug break point
}
```

And nothing has changed in NaiveDate debug description. 

To make sure that I am updating correct files. I also tried to update existing `StdRangeSummaryProvider` to:
```
def StdRangeSummaryProvider(valobj, _dict):
    # type: (SBValue, dict) -> str
    return "someRangeSummary"
```
This works and I see "someRangeSummary" additional debug info.

Can you please help me what I need to do to make it running also for NaiveDate structs. Thank you a lot.

**Comment by Jiri42** [comment]
Thank you a lot @ortem, it works. Below is description how to setup pretty print for basic Chrono structs:
 
add
```
    CHRONO_NAIVE_DATE = "ChronoNaiveDate"
    CHRONO_NAIVE_TIME = "ChronoNaiveTime"
    CHRONO_NAIVE_DATE_TIME = "ChronoNaiveDateTime"
    CHRONO_DATE_TIME = "ChronoDateTime"
```
below https://github.com/intellij-rust/intellij-rust/blob/4cc94bc94af0692c106a464fbdb35707efe139ca/prettyPrinters/rust_types.py#L50

then add
```
    RustType.CHRONO_NAIVE_DATE: re.compile(r"^chrono::naive::date::NaiveDate$"),
    RustType.CHRONO_NAIVE_TIME: re.compile(r"^chrono::naive::time::NaiveTime$"),
    RustType.CHRONO_NAIVE_DATE_TIME: re.compile(r"^chrono::naive::datetime::NaiveDateTime$"),
    RustType.CHRONO_DATE_TIME: re.compile(r"^chrono::datetime::DateTime<.+>$"),
```
below https://github.com/intellij-rust/intellij-rust/blob/4cc94bc94af0692c106a464fbdb35707efe139ca/prettyPrinters/rust_types.py#L112

then add
```
# ---------------------------------------------------------------------------------------------
# Chrono lib providers (https://github.com/chronotope/chrono)
# ---------------------------------------------------------------------------------------------

import datetime
import math


def div_mod_floor(a, b):
    return math.floor(a / b), math.floor(a % b)


def ChronoNaiveDateProvider(valobj, _dict):
    # type: (SBValue, dict) -> str
    ymdf = valobj.GetChildMemberWithName("ymdf").GetValueAsSigned()
    year = ymdf >> 13
    day_of_year = (ymdf & 8191) >> 4
    date = datetime.date(year - 1, 12, 31) + datetime.timedelta(days=day_of_year)
    return '{:%Y-%m-%d}'.format(date)


def ChronoNaiveTimeProvider(valobj, _dict):
    # type: (SBValue, dict) -> str
    origin_secs = valobj.GetChildMemberWithName("secs").GetValueAsUnsigned()
    nanos = valobj.GetChildMemberWithName("frac").GetValueAsUnsigned()
    (mins, sec) = div_mod_floor(origin_secs, 60)
    (hour, minutes) = div_mod_floor(mins, 60)
    (micro, _) = div_mod_floor(nanos, 1000)
    return '{:02d}:{:02d}:{:02d}.{:06d}Z'.format(hour, minutes, sec, micro)


def ChronoNaiveDateTimeProvider(valobj, _dict):
    # type: (SBValue, dict) -> str
    date = ChronoNaiveDateProvider(valobj.GetChildMemberWithName("date"), _dict)
    time = ChronoNaiveTimeProvider(valobj.GetChildMemberWithName("time"), _dict)
    return '\"{}T{}\"'.format(date, time)


def ChronoDateTimeProvider(valobj, _dict):
    # type: (SBValue, dict) -> str
    datetime = ChronoNaiveDateTimeProvider(valobj.GetChildMemberWithName("datetime"), _dict)
    return datetime

```
on the bottom of [lldb_formatters](https://github.com/intellij-rust/intellij-rust/tree/4cc94bc94af0692c106a464fbdb35707efe139ca/prettyPrinters/lldb_formatters)/lldb_providers.py /

finaly add 
```
    register_providers(RustType.CHRONO_NAIVE_DATE, summary=ChronoNaiveDateProvider)
    register_providers(RustType.CHRONO_NAIVE_TIME, summary=ChronoNaiveTimeProvider)
    register_providers(RustType.CHRONO_NAIVE_DATE_TIME, summary=ChronoNaiveDateTimeProvider)
    register_providers(RustType.CHRONO_DATE_TIME, summary=ChronoDateTimeProvider)
```
in https://github.com/intellij-rust/intellij-rust/blob/4cc94bc94af0692c106a464fbdb35707efe139ca/prettyPrinters/lldb_formatters/__init__.py#L64

Here is print screen how it looks:

![debugger_out](https://user-images.githubusercontent.com/127349046/224504780-0b53886f-b725-4e97-8a88-beec60107855.png)


Btw @ortem, one thing little bit bothers me. E.g in native time you see that 1970 is in white color and rest is green. It would be nice to have it unified. As hot fix for DateTime I put it into quotes so it looks as string. Thank you a lot guys for your help and also for adding pretty print for strings and vectors in v191, it helps me a lot :)

**Comment by ortem** [comment]
@Jiri42 I'm glad that it helped!

The rendering with white and green colours is strange indeed. It looks like CLion tries to render the first part as a number and the rest as text. I'll take a deeper look. Thanks for pointing this out!

**Comment by Jiri42** [comment]
Great, thank you @ortem . BTW will Goland also effected by this change?

**Comment by Undin** [comment]
> Great, thank you @ortem . BTW will Goland also effected by this change?

@Jiri42 Yep. Native debugging support plugin that you use in GoLand to debug Rust, and CLion share some code and the fix belongs to this part

**Comment by ortem** [comment]
We have discussed this with the team and decided to include pretty printers for `chrono` data types. Although we still focus on the Rust standard library types, this particular case still looks appropriate for the following reasons:
* the pretty printers implementation for `chrono` data types looks straightforward and robust
* the internal implementation of `chrono`'s data types doesn’t seem to change often

Therefore, @Jiri42 you are welcome to open a PR with your changes for LLDB.

Also, @kingsimmy thank you for the initial implementation and feel free to open a PR with GDB pretty printers as well.

**Comment by Jiri42** [comment]
Cool, I will look on it during some weekend.

**Comment by kobe-reygel** [comment]
@artemmukhin @Jiri42 did the chrono pretty print for LLDB ever make it into the plugin?

I'm looking at the same problem right now, the chrono::naive::date::NaiveDate still displays as 'ymdf'

**Comment by Jiri42** [comment]
Hi @artemmukhin, currently it seems that I have time to implement this change. But recently [RustRover](https://www.jetbrains.com/rust/)  was announced. Does it even make it sense to implement it? Will it be migrated also into RustRover? I also want to add more debug providers (eg. rust_decimals) in future. Will it be migrated in RustRover or you are planning to implement more native debug providers? Thanks
