### ISSUE TITLE
Automatically insert `>` after `::<`

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1022]

**Comment by la10736** [comment]
If there is no too much pressure about this feature I can take care of it.

**Comment by matklad** [comment]
>If there is no too much pressure about this feature I can take care of it.

Sure! Although there's a change that it would be more complicated than it seams. Somewhat similar https://github.com/intellij-rust/intellij-rust/pull/923 turned out to be pretty complicated.

**Comment by matklad** [comment]
closed by https://github.com/intellij-rust/intellij-rust/pull/1142
