### ISSUE TITLE
Zero is not recognized as a valid value in toml

### ISSUE THREAD

**Issue by kryptan** [intellij-rust/intellij-rust#1027]
This is valid Toml:
```
opt-level = 0
```

It is accepted by cargo but toml plugin thinks it's invalid (\<value\> expected, got '0'). Other numbers work fine.

**Comment by matklad** [comment]
Hm, are you using the latest published version of the TOML plugin? This should work with the latest version (there only two published versions). This indeed was a bug, but it was fixed long ago, even when TOML was a separate repository.

**Comment by kryptan** [comment]
The issue was that I had https://plugins.jetbrains.com/plugins/nightly/8195 set up as a repository which probably had wrong version of the plugin (0.0.2.16). I removed that repository, removed Toml plugin and installed 0.0.1.SNAPSHOT. Now it works correctly.
