### ISSUE TITLE
TOML plugin should be compatible with canonical TOML grammar

### ISSUE THREAD

**Issue by himikof** [intellij-rust/intellij-rust#1028]
Now that there is a ABNF TOML [grammar](https://github.com/toml-lang/toml/blob/master/toml.abnf) upstream, TOML plugin grammar should be updated.

Related to #1027.

**Comment by matklad** [comment]
Working on TOML plugin right now. And of course grammar differs from speck!

**Comment by matklad** [comment]
closed by #1978
