### ISSUE TITLE
Can't resolve screeps-game-api::Room

### ISSUE THREAD

**Issue by ozkriff** [intellij-rust/intellij-rust#10296]
## Environment

* **IntelliJ Rust plugin version:** 0.4.191.5293-231
* **Rust toolchain version:** 1.62.0 (a8314ef7d 2022-06-27) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2023.1 RC (CL-231.8109.141)
* **Operating system:** Linux 5.4.0-144-generic
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr, org.rust.ide.intentions.macros.function-like, org.rust.macros.proc

## Steps to reproduce

1) Cargo.toml:

```toml
[dependencies]
screeps-game-api = "0.10.0"
```

2) main.rs

```rust
use screeps::{game, Room}; // fails to find `Room` here

fn main() {
    let spawn = game::spawns().values().next().unwrap(); // `spawn` is correctly inferred as `StructureSpawn`
    let room = spawn.room().unwrap(); // the `room` is <unknown>
    let room_name = room.name();
}
```

![image](https://user-images.githubusercontent.com/662976/227994088-1161f4c2-3bf6-463d-b54e-ac0a8594ee12.png)

Probably related to wasm_bindgen heavy use in the dependency.

Originally reported on [the Rust Community Discord server](https://discord.com/channels/273534239310479360/335502067432947748/1089931044096057425).

**Comment by vlad20012** [comment]
```toml
[dependencies]
wasm-bindgen = "0.2.84"
```

```rust
use wasm_bindgen::prelude::wasm_bindgen;

#[wasm_bindgen] // The macro is not expanded
extern "C" {
    pub type Room;

    #[wasm_bindgen(final)]
    pub fn create_construction_site();
}

fn main() {}
```
