### ISSUE TITLE
Support unstable cargo features

### ISSUE THREAD

**Issue by melvyn2** [intellij-rust/intellij-rust#10341]
## Environment

* **IntelliJ Rust plugin version:** 0.4.191.5293-231
* **Rust toolchain version:** rustc 1.70.0-nightly (3a8a131e9 2023-04-02)
* **IDE name and version:** CLion 2023.1
* **Operating system:** macOS 12.5.1

## Problem description
No simple way to enable command-line cargo features. For example, the [`artifact-dependencies`](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#artifact-dependencies) feature requires `-Z bindeps` as a cargo flag. I can manually pass this flag to run configurations, but syncing the cargo project always fails and breaks IDE integrations: 
```rust
Execution failed (exit code 101).
/Users/-/.cargo/bin/cargo metadata --verbose --format-version 1 --all-features --filter-platform x86_64-apple-darwin
stdout : error: failed to load manifest for workspace member `(project path)`

Caused by:
  failed to parse manifest at `(project path)/Cargo.toml`

Caused by:
  `artifact = …` requires `-Z bindeps` (testlib)

stderr : 
```

## Steps to reproduce
For the example of artifact dependencies:
1. Create a new Rust/Cargo project in the IDE
2. In the new Cargo.toml, add `ripgrep = { verion = "13", artifact = "bin" }` to the dependencies section
3. Click reload cargo project button
4. See errors on cargo project load

**Comment by ozkriff** [comment]
You can use `.cargo/config.toml` to [enable the unstable features](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html?highlight=feature#unstable-features):

```toml
[unstable]
bindeps = true
```

And `rust-toolchain.toml` like this to specify the nightly toolchain:

```toml
[toolchain]
channel = "nightly"
```
