### ISSUE TITLE
Rust Plugin Recompiles Everything Even With No Changes

### ISSUE THREAD

**Issue by helios2k6** [intellij-rust/intellij-rust#10346]
## Environment

* **IntelliJ Rust plugin version:** 0.4.192.5324-231
* **Rust toolchain version:** 1.68.2 (9eb3afe9e 2023-03-27) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2023.1.1 (CL-231.8109.222)
* **Operating system:** Linux 6.2.6-76060206-generic
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.macros.proc

## Problem description
Rust plugin recompiles the entire project every time, even if no changes are made

## Steps to reproduce
1/ Create a workspace with multiple sub-projects.
2/ I also have build.rs scripts that generate grpc clients and servers via tonic.
3/ Build the project.
4/ Change nothing.
5/ Build the project again.
6/ Observe that the plugin builds everything from scratch again.
7/ Observe that if you run `cargo build` from the command line, this behavior is not exhibited.

**Comment by helios2k6** [comment]
Is there any news on this? It appears that the plugin runs `cargo clean` before every project build when this isn't necessary. I'd like to not have to switch to my terminal to build the project.

**Comment by sburton84** [comment]
Just noticed this has started happening for me as well, after updating my CLion IDE, and it makes the IDE borderline unusable if I can't build a project without it rebuilding *everything*.

**Comment by sburton84** [comment]
Although the above reporter mentions seeing this issue in CLion 2023.1.1, it seems that for me the issue only started on upgrade to 2023.1.2, and downgrading back to 2023.1.1 seems to fix it for me.

**Comment by lkt** [comment]
It's also reproducible on IDEA 2023.1.2 with Rust plugin 0.4.195.5408-231

**Comment by danielnorberg** [comment]
Same here with `IntelliJ IDEA 2023.1.3 (Ultimate Edition), Build #IU-231.9161.38` and `org.rust.lang (0.4.196.5423-231)`.
