### ISSUE TITLE
Cannot find declaration to go to for i64 methods

### ISSUE THREAD

**Issue by cs-cordero** [intellij-rust/intellij-rust#10372]
## Environment

* **IntelliJ Rust plugin version:** 0.4.192.5324-231
* **Rust toolchain version:** 1.69.0 (84c898d65 2023-04-16) x86_64-apple-darwin
* **IDE name and version:** CLion 2023.1.1 (CL-231.8109.222)
* **Operating system:** macOS 12.6.5
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr, org.rust.macros.proc

## Problem description
The plugin cannot find common declarations related to the `i64` type, specifically functions like the `signum` or `is_positive` function which was introduced in 1.47.0

## Steps to reproduce
Open a new Rust project and type the following.
```
let foo: i64 = 5;
foo.signum();
foo.is_positive();
```

Then try to see what the return type of `signum` or `is_positive` is through following the declaration.  You get a "Cannot find declaration to go to".

**Comment by cs-cordero** [comment]
This seems to affect other methods thare are defined from `int_macros.rs` from core.

**Comment by w-ensink** [comment]
I have a similar problem with `i16::MAX`. It gives the error that it's private, but it compiles just fine.
<img width="465" alt="Scherm­afbeelding 2023-04-28 om 13 46 49" src="https://user-images.githubusercontent.com/46427708/235139466-0a9f3a30-0fc2-474b-9e33-9654e22b0308.png">

**Comment by mili-l** [comment]
Relate to #10228

**Comment by cs-cordero** [comment]
Hi all - it seems that on plugin version `0.4.200.5421-232`, this issue is fixed.  Not sure which change from the patch notes/changelog ended up fixing it but thanks for the fix either way.

**Comment by Maksim20023** [comment]
Hi! The issue was fixed in the Rust plugin 0.4.199 version. Please see  #10688
