### ISSUE TITLE
union field write is safe

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#10370]
## Environment

* **IntelliJ Rust plugin version:** 0.4.194.5344-231-nightly
* **Rust toolchain version:** rustc 1.71.0-nightly (c609da59d 2023-04-18)
* **IDE name and version:** Clion 2023.1.1
* **Operating system:** Archlinux

## Problem description

```rust
union TTT {
    v1: [u8; 2],
    v2: u16,
}

fn test() {
    let ttt = TTT { v2: 10 };
    ttt.v1 = [1, 1];
}
```

union field write is safe, but intellij-rust doesn't think so

![image](https://user-images.githubusercontent.com/10096425/233781257-04989e28-6dca-438d-851e-7b3e14a9aa45.png)

**Comment by vlad20012** [comment]
The bug has been introduced in #10268
