### ISSUE TITLE
Use different icon for `mod.rs` files

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1038]
In structure view, it's difficult to spot `mod.rs` file (unlike, say `__init__.py`). We could use a different icon for it I think...

**Comment by mkaput** [comment]
Do we really need to differentiate `mod.rs`? Anyway I'll try to come up with something :)

**Comment by matklad** [comment]
Yep, I think we do. When I exploring some big module in `Project View` ([this one](https://github.com/rust-lang/cargo/tree/master/src/cargo/core), for example), I am very interested in the root module, because it contains all the API. And it's not easy to find this module because it can be buried somewhere between `m`s and `n`s. It's interesting than in python you don't have the problem because `__init__.py` is always first alphabetically.

**Comment by alygin** [comment]
Shouldn't we also do the same with `lib.rs`/`main.rs` in the source root?

**Comment by mkaput** [comment]
I'd highlight `build.rs`, but I am not sure whether `lib.rs/main.rs` is not to much.

Regarding `mod.rs`, maybe there is possibility to move it to the top of file list?

**Comment by mkaput** [comment]
I think we could roll our own Project View (or how it's called, I mean something like Android or Rails one) which could move `mod.rs` to the top
