### ISSUE TITLE
Incorrect treatment of cfg attributes with features

### ISSUE THREAD

**Issue by afetisov** [intellij-rust/intellij-rust#10394]
## Environment

* **IntelliJ Rust plugin version:** 0.4.194.5353-231-nightly
* **Rust toolchain version:** 1.69.0 (84c898d65 2023-04-16) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2023.1.1 (CL-231.8109.222)
* **Operating system:** Linux 5.4.0-146-generic
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.macros.proc

## Steps to reproduce

```rust
#[cfg(feature = "boo")]
   // ^^^^^^^^^^^^^^^ Malformed `feature` attribute input 
   // The following are the possible correct uses #[feature(name1, name2, ...)]
fn f() {}
```

**Comment by vlad20012** [comment]
Ook, it doesn't seem to be fixed in the latest nightly plugin. Need to investigate
