### ISSUE TITLE
Error spans get messed up

### ISSUE THREAD

**Issue by afetisov** [intellij-rust/intellij-rust#10401]
## Environment

* **IntelliJ Rust plugin version:** 0.4.194.5355-231-nightly
* **Rust toolchain version:** 1.69.0 (84c898d65 2023-04-16) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2023.1.1 (CL-231.8109.222)
* **Operating system:** Linux 5.4.0-146-generic
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr, org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.ide.intentions.macros.function-like, org.rust.macros.proc, org.rust.coverage.source, org.rust.ssr

## Problem description

Sometimes during editing I get the error spans that are all wrong. Like, literally in random places. The errors are returned by external linter.

![Screenshot](https://user-images.githubusercontent.com/12111996/234932794-f2175efe-e7e6-4b3f-be54-6d361df17cec.png)

I don't remember seeing such errors until this week. Could it be caused by a nightly update a couple of days ago?

I don't have a reproducing example, unfortunately, since this error seems to happen sporadically sometime after working with a project for a while.

**Comment by mchernyavsky** [comment]
Probably the bug was introduced in https://github.com/intellij-rust/intellij-rust/pull/7509.
