### ISSUE TITLE
can't complete the .await

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#10407]
## Environment

* **IntelliJ Rust plugin version:** 0.4.194.5363-231-nightly
* **Rust toolchain version:** rustc 1.71.0-nightly (87b1f891e 2023-04-29)
* **IDE name and version:** CLion 2023.1.2
* **Operating system:** Archlinux

## Problem description

![image](https://user-images.githubusercontent.com/10096425/235364411-99fa2ae7-fc34-462d-a18f-906732b622a2.png)

the completion list doesn't have the `.await` element, when calling an async function

## Steps to reproduce

1. write a normal async function
2. call it in an async context, such as in an async function
3. wait the completion list have the `.await`

**Comment by vlad20012** [comment]
It looks like the bug was introduced in #9315
