### ISSUE TITLE
Borrow checker is not correct in editor

### ISSUE THREAD

**Issue by Janekdererste** [intellij-rust/intellij-rust#10448]
## Environment

* **IntelliJ Rust plugin version:** 0.4.193.5352-231
* **Rust toolchain version:** 1.71.0-nightly (2f6bc5d25 2023-05-09) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2023.1.2 (CL-231.8770.66)
* **Operating system:** Windows 11.0
* **Macro expansion:** disabled

## Problem description
I see `Use of moved value` and `Cannot move` errors in the code editor, but the code is fine and `cargo build` compiles without errors. 
![image](https://github.com/intellij-rust/intellij-rust/assets/8005495/052dc1dd-5eb1-4011-8256-fa4e643fc35a)

## Steps to reproduce

Open my [project](https://github.com/Janekdererste/rust_q_sim) in Clion and open any file for example [this one](https://github.com/Janekdererste/rust_q_sim/blob/main/src/simulation/network/link.rs)

**Comment by v0y4g3r** [comment]
Looks duplicate with #10427

**Comment by Janekdererste** [comment]
@v0y4g3r yes, that's exaclty the same error. Thanks for pointing me to that issue. 

Closign this issue because it is a duplicate of #10427
