### ISSUE TITLE
List of contexts where autocomplete is not expected?

### ISSUE THREAD

**Issue by nathanaeljones** [intellij-rust/intellij-rust#1046]
Over time, IntelliJ-Rust has been autocompleting in fewer and fewer contexts. Is there a list of known expected failure contexts? (In regards to correct, compiling code only).

**Comment by nathanaeljones** [comment]
Here's one I'm pretty sure about. 

```
let a: Vec<String> = Vec::new();
a.
  ^ caret here
```
This definitely used to work for me. Now I just get "lambda/let/match/par" for everything. (Using IDEA 2016.3.5 on Ubuntu 14, with rust nightly-2017-03-04).

**Comment by matklad** [comment]
That happens to work on my machine, so there's something specific in your setup that causes the failure. 

Specifically, with `nightly-2017-03-04` and IntelliJ Rust 0.1.0.1698 I do a `cargo new --bin`,  import the project and paste

```Rust
fn main() {
    let a: Vec<String> = Vec::new();
    a.
}
```

IntelliJ spends some time indexing standard library, and after that completion of `Vec` methods is available. 


The most likely cause of failure is that IntelliJ Rust fails to find the standard library. Could you check that the path to stdlib in `Settings > Language & Frameworks > Rust` looks reasonable? 


Currently, we setup standard library when you open a first Rust file in the IDE: we execute `rustup component add rust-src` and then `rustc --print sysroot`.

**Comment by nathanaeljones** [comment]
Thanks! I opened https://github.com/intellij-rust/intellij-rust/issues/1070 about that issue. I now have stdlib working again. But I'm still not getting autocomplete for most variables.

For example:

```
 let h = HashMap::new();
 h.insert("a", "b");
 let value =  h.get("a").unwrap().< autocomplete fails here
```

Is this expected? Perhaps only one level of generics are supported?

**Comment by matklad** [comment]
>Is this expected? Perhaps only one level of generics are supported?

Yes, this is currently expected. We don't yet infer generic arguments from usage. That is, we can't infer from `.insert("a", "b")` that it is an `<String, String>` hash map

**Comment by nathanaeljones** [comment]
> We don't yet infer generic arguments from usage. 

I don't get autocomplete even if I define the type explicitly, though.

```
 let h: HashMap<&'static str, &'static str> = HashMap::new();
 h.insert("a", "b");
 let value =  h.get("a").unwrap().< autocomplete fails here
```
