### ISSUE TITLE
Cannot config rust library

### ISSUE THREAD

**Issue by XiuyeXYE** [intellij-rust/intellij-rust#1048]
![qq 20170303095328](https://cloud.githubusercontent.com/assets/16207730/23535141/8b439412-fff7-11e6-8417-eaf18de2222d.png)
Can you help me?

**Comment by matklad** [comment]
Hm, you are using rustup, so it should be configured automatically when you open any Rust file. 

The UI here is definitely confusing though!

**Comment by XiuyeXYE** [comment]
I solved this problem,though the library path cannot be set yet.
I config the relative paths of the compiler and tools and library of rust correctly in the root path(directory).
It can automatically find the compiler and library to compile successfully,though writing codes is without tips.
The root path like this:

├─bin
├─etc
│  └─bash_completion.d
├─lib
│  ├─cargo
│  └─rustlib
│      └─i686-pc-windows-msvc
│          └─lib
└─share
