### ISSUE TITLE
thread_local variable can't use code complete

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#10507]
## Environment

* **IntelliJ Rust plugin version:** 0.4.196.5395-231-nightly
* **Rust toolchain version:** rustc 1.71.0-nightly (a2b1646c5 2023-05-25)
* **IDE name and version:** Clion 2023.1.3
* **Operating system:** Archlinux

## Problem description
![image](https://github.com/intellij-rust/intellij-rust/assets/10096425/c07aa8c3-6a8d-4d4a-bbb6-b9a8b7a53a35)
I define a thread-local variable, but the `RUNTIME` can't use code complete, the intellij-rust event doesn't know that is a variable

also the type hint is wrong, and if I don't use `std::cell::RefCell`, instead

```rust
use std::cell::RefCell;

thread_local! {
    static RUNTIME: RefCell<Option<Runtime>> = RefCell::new(None);
}
```

it will tell me `RefCell` is an unused import

## Steps to reproduce

1. use `thread_local` macro to define a tls variable
2. just use it

**Comment by Maksim20023** [comment]
Hi! Could you please specify if the issue still occurs on the latest Rust plugin version?

**Comment by Sherlock-Holo** [comment]
issue is fixed :)
