### ISSUE TITLE
Something in the plugin reload the entire workspace/context every few keystrokes and move the cursor

### ISSUE THREAD

**Issue by keltia** [intellij-rust/intellij-rust#10555]
## Environment

* **IntelliJ Rust plugin version:** 0.4.194.5382-223
* **Rust toolchain version:** 1.70.0 (90c541806 2023-05-31) x86_64-pc-windows-msvc
* **IDE name and version:** GoLand 2022.3.4 (GO-223.8836.56)
* **Operating system:** Windows 10 10.0
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr

## Problem description

I am trying to write some Rust code and every few keystrokes, the plugin decides to reload the cargo projet, re-read all workspaces, rust-std lib (which is annoying enough because it slows everything down) and more annoyingly it MOVES the cursor to some random location in the code.  Which means you end up writing part of a sentence at some place and the read at another random location for no reason, as if reloading everything wasn't enough.

BTW Notice I'm still using 2022.2.3 because the problem is even worse in 2023.1.*.

## Steps to reproduce

The code by itself is simple enough and I'm not sure it is relevant but here it is.  Sometimes cursor will go to `#klass` inside the macro, sometimes just at the end of the file, etc.  No pattern I can see.

I  have a short video showing this: https://www.dropbox.com/scl/fi/lgp4oc02cg3uiu5mb1z39/IMG_9580.MOV?dl=0&rlkey=nvbmudbir5i7kyqdlg5jytx0j

**Basically it makes GoLang+Rust unusable**.

```
use proc_macro::{TokenStream};
use quote::quote;
use syn::{Expr, Attribute, Meta, parse_macro_input, DeriveInput, AttrStyle, ExprLit};

/// Most basic proc_macro ever: use as a template.
///
#[proc_macro_attribute]
pub fn runnable(attr: TokenStream, input: TokenStream) -> TokenStream {
    dbg!(&attr, &input);

    let attr: ExprLit = parse_macro_input!(attr);
    let func: String = attr.lit.try_into().unwrap();

    let klass = attr.to_string();
    let outer = quote!(
        impl Runnable for #klass {
        fn run(
            &mut self,
            input: Receiver<String>,
        ) -> (Receiver<String>, JoinHandle<Result<()>>) {
            let (stdout, stdin) = channel::<String>();

            let msg = self.msg.clone();
            let h = thread::spawn(move || {
                trace!("in runnable::{}", stringfy!(#klass));

                // Add our message
                //
                for data in input {
                    let data = self.#func(data);
                    if stdout.send(data).is_err() {
                        break;
                    }
                }
                Ok(())
            });
            (stdin, h)
        }
    });
    eprintln!("{:#?}", outer.to_string());
    outer.into()
}
```

**Comment by s0xzwasd** [comment]
Logs upload id: 2023_06_05_nUMfbHF29cDsQ4UxPBBbk8

**Comment by mili-l** [comment]
Hello @keltia , thanks for the report, could you check your Cargo [settings](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-project-settings.html#cargo-settings) on 
`Settings | Build, Execution, Deployment | Build Tools` and choose the `External changes` option.
<img width="374" alt="Screenshot 2023-06-12 at 13 18 45" src="https://github.com/intellij-rust/intellij-rust/assets/1213122/62bd9927-cff6-4c2b-8d97-92e1f42691c5">

**Comment by keltia** [comment]
@mili-l hello, thanks for the answer, it was "Any changes" on the macOS machine here I changed it.  This evening I'll see on the windows machine (where the issue is much worse).

**Comment by keltia** [comment]
It seems to have stopped the madness, thanks @mili-l

**Comment by keltia** [comment]
There is the question of why it is thinking the build scripts were modified when they weren't... :)
