### ISSUE TITLE
`rust-analyzer-proc-macro-srv` API breakage

### ISSUE THREAD

**Issue by Veykril** [intellij-rust/intellij-rust#10566]
I feel like we should inform you about this here as well, some months ago we started adding a version check to the proc-macro server so that we can add more functionality without breaking support for older servers as long as the client supports it (as our proc-macro server protocol is rather rigid). See the corresponding PR here https://github.com/rust-lang/rust-analyzer/pull/14070

The toolchain distributed `rust-analyzer-proc-macro-srv` component has this rolled out now on recent nightlies now (~1-2 week old as of posting). I think if a "client" (intellij in this case) does not know of this versioning things might start breaking for you as the server itself only supports the latest version. The only thing that really changed right now for version 2 is that the protocol now encodes the open and close span for groups separately, instead of assigning one to both.

(If you want we can keep this open after you've implemented this as a tracking issue for me to post whenever a new version gets added)

**Comment by vlad20012** [comment]
Hi! Thank you so much for the information! I'll take a look soon

**Comment by HTG-YT** [comment]
That is due to Fleet using an outdated build of Rust-Analyzer, which is incompatible with the Proc Macro Server on Nightly,

**Comment by HTG-YT** [comment]
cc @vlad20012 any roadmap to fix this? This issue seems to cause trouble with many people (especially procedural macros are quite common in my opinion) so this breakage is quite major.

**Comment by vlad20012** [comment]
@HTG-YT, yep, the fix is on the way

**Comment by Veykril** [comment]
Oh apologies, I just realized forgot to link the PR for version 2 on the r-a side https://github.com/rust-lang/rust-analyzer/pull/14572.
