### ISSUE TITLE
serde_with macro expand failed

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#10573]
## Environment

* **IntelliJ Rust plugin version:** 0.4.197.5408-231-nightly
* **Rust toolchain version:** rustc 1.72.0-nightly (37998ab50 2023-06-11)
* **IDE name and version:** 2023.1.3
* **Operating system:** Archlinux

## Problem description
![image](https://github.com/intellij-rust/intellij-rust/assets/10096425/e4ecb08e-6aaa-408d-8b9c-a8ee5444ae92)

it seems intellij-rust expand the `serde_as` attr macro failed, that make the IDE report `use std::net::Ipv4Addr` `DisplayFromStr` and `Deserialize` is unused

## Steps to reproduce
```rust
use std::net::Ipv4Addr;
use serde_with::{serde_as, DisplayFromStr};
use serde::Deserialize;

#[serde_as]
#[derive(Debug, Deserialize)]
pub struct Config {
    pub tun_name: String,

    #[serde_as(as = "DisplayFromStr")]
    pub local_ipv4: Ipv4Addr,
}
```

try this codes with `serde` and `serde_with` 3.0.0 version

**Comment by vlad20012** [comment]
Perhaps it's related to the nightly version of the Rust toolchain and recent changes with its macro expander: #10566?
