### ISSUE TITLE
Marco expansion of RTIC doesn't work

### ISSUE THREAD

**Issue by stonefoxes** [intellij-rust/intellij-rust#10582]
## Environment

* **IntelliJ Rust plugin version: 0.4.196.5423-231**
* **Rust toolchain version: rustc 1.72.0-nightly (6bba06146 2023-06-16)**
* **IDE name and version: CLion 2023.1.3**
* **Operating system: Manjaro 23**

## Problem description
Autocomplete and type inference don't work for [RTIC](https://github.com/rtic-rs/rtic), while rust-analyzer handles it without problems. `org.rust.macros.proc.attr` enabled. Tests performed inside this function:
```rust
#[task(priority=1, shared = [test_uint, test_bool])]
    async fn task1(_cx: task1::Context) {
        let uint = _cx.shared.test_uint;
        defmt::info!("Hello from task1!");
    }
```
CLion:
![image](https://github.com/intellij-rust/intellij-rust/assets/35688470/04063fd1-e0ab-438b-9fbd-8aa547eebc36)  
VSCode:  
![image](https://github.com/intellij-rust/intellij-rust/assets/35688470/67f8b4a2-2c69-4ee6-8a66-27494da4fc8b)

## Steps to reproduce
- `git clone https://github.com/stonefoxes/macro_expansion_issue_example/`
- `cd macro_expansion_issue_example`
- `rustup target add thumbv7em-none-eabihf`
- `cargo build`
- type `_cx.` in `task1` of `minimal.rs`
- result: no autocompletion
- look at `uint` in `task1` of `minimal.rs`
- result: no type inference

**Comment by HTG-YT** [comment]
This seems to be related to #10573, where I also encountered a similar issue to that with syntax highlighting completely broken.

**Comment by stonefoxes** [comment]
> This seems to be related to #10573, where I also encountered a similar issue to that with syntax highlighting completely broken.

I think, that problem persists for a couple of years at least, according to #4021

**Comment by Maksim20023** [comment]
Duplicated #4021

**Comment by stonefoxes** [comment]
@Maksim20023 sorry for the duplicate, thank you.
