### ISSUE TITLE
Copy path no longer includes the workspace's path. 

### ISSUE THREAD

**Issue by Jezza** [intellij-rust/intellij-rust#10600]
## Environment

* **IntelliJ Rust plugin version: 0.4.196.5423-231**
* **Rust toolchain version: 1.70.0**
* **IDE name and version: IntelliJ IDEA 2023.1.2 (Ultimate Edition)**
* **Operating system: 5.10.0-11-amd64**

```
IntelliJ IDEA 2023.1.2 (Ultimate Edition)
Build #IU-231.9011.34, built on May 16, 2023
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.10.0-11-amd64

Non-Bundled Plugins:
    org.rust.lang (0.4.196.5423-231)
    today.movatech.plugins.jsonnet (2023.1.2)
    com.intellij.nativeDebug (231.8770.15)
    org.asciidoctor.intellij.asciidoc (0.38.17)
    deno (231.8109.91)
    dev.blachut.svelte.lang (231.8770.15)
    mobi.hsz.idea.gitignore (4.5.0)
    com.dmarcotte.handlebars (231.8770.3)

Kotlin: 231-1.8.21-IJ9011.34
Current Desktop: XFCE
```

## Problem description

Copy path no longer includes the whole workspace's path.  

The same for `Ctrl + Shift + Alt + C`, which copies the content root's path, and appends the column and row.
It no longer does that.

Both of these methods were _really_ useful in pointing people to specific files.
It's no longer possible to do that.

I'm assuming it has something to do with workspaces having a content root based on each crate, rather than the root of the workspace.

If the change was done intentionally, I'd love for an option to be added to configure it. (I'm more than happy to add the option if someone points me in the direction.)

## Steps to reproduce

1. Create a rust workspace.  
2. Import it as a module within intellij.  
3. Right click a file within one of the subcrates, and hit `Copy Path/Reference`.
4. Observe that the `From Content Root` option only contains the crate's path, not the workspaces.
5. You can also open a file and hit `Ctrl + Shift + Alt + C` and it'll copy the file's path, and append the column and row.
6. Observe that it only copies the crate's path.

Example showing the `Copy Path/Reference` problem.
If you have multiple crates, then giving someone a path "lib.rs" is basically useless.
![image](https://github.com/intellij-rust/intellij-rust/assets/4224088/bbf3a573-2fda-4a3d-84fa-083e386dbf06)

The `Ctrl + Shift + Alt + C` action is a bit harder to demonstrate, but thankfully IntelliJ prints out what it has copied to the clipboard.
Again, in this case, it's basically useless.
![image](https://github.com/intellij-rust/intellij-rust/assets/4224088/e3847e6c-bdf1-4e6f-98d5-843aab3c9271)

**Comment by Maksim20023** [comment]
Hi! Thank you for the report.
It appears that the such behavior is related to IntelliJ IDEA issue and it's already known to us [IDEA-316752](https://youtrack.jetbrains.com/issue/IDEA-316752/Copy-Reference-on-a-line-in-Editor-no-longer-copies-Path-From-Content-Root-instead-it-copies-the-path-from-the-parent-root-e.g.) You can subscribe to this issue to stay informed, vote and share additional information.
If you have any further suggestions, please feel free to reach out.
