### ISSUE TITLE
cargo project does not work when using nightly features

### ISSUE THREAD

**Issue by webern** [intellij-rust/intellij-rust#10626]
## Environment

* **IntelliJ Rust plugin version:** 0.4.186.5143-222
* **Rust toolchain version:** 1.72.0-nightly (6bba06146 2023-06-16) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.2.4 (CL-222.4345.21)
* **Operating system:** Linux 5.15.0-75-generic
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr, org.rust.cargo.features.settings.gutter, org.rust.macros.proc

## Problem description

How do I tell the cargo project that I want to use nightly with `-Zbindeps`?

The project described by the `Cargo.toml` file below builds with `cargo build -Zbindeps`.

However the Rust plugin cannot index it:

![image](https://github.com/intellij-rust/intellij-rust/assets/6260372/1cff8143-61fc-4821-8d23-762127710d60)

```text
Execution failed (exit code 101).
/home/brigmatt/.cargo/bin/cargo metadata --verbose --format-version 1 --all-features --filter-platform x86_64-unknown-linux-gnu
stdout : error: failed to parse manifest at `/home/brigmatt/repos/untitled3/Cargo.toml`

Caused by:
  `artifact = …` requires `-Z bindeps` (ripgrep)

stderr : 
```

## Steps to reproduce

Create a Rust project with this `Cargo.toml`

```toml
[package]
name = "anything"
version = "0.1.0"
edition = "2021"

[dependencies]
ripgrep = { version = "13", artifact = "bin" }
```

**Comment by Maksim20023** [comment]
Hi! Thank you for reporting the issue.
Unfortunately, at the moment there is no way to specify an unstable flag for the Cargo project. But we already have a feature  request https://github.com/intellij-rust/intellij-rust/issues/9752 
Feel free to subscribe on it to stay informed and vote (click the emoji button in the bottom-left corner of the GitHub post).
If you have any further suggestions, please feel free to reach out.

**Comment by webern** [comment]
Closing this as there is a way to pass these with configuration:

```toml
[unstable]
bindeps = true
```

![image](https://github.com/intellij-rust/intellij-rust/assets/6260372/52106a58-f75a-4ead-8186-58e4071f6038)


![image](https://github.com/intellij-rust/intellij-rust/assets/6260372/daba3d99-9b7e-4eb9-ac34-89c8c83ce7e2)
