### ISSUE TITLE
Failed to expand the macro: internal error: expansion file not found, but cache has valid expansion

### ISSUE THREAD

**Issue by ForsakenHarmony** [intellij-rust/intellij-rust#10624]
## Environment

* **IntelliJ Rust plugin version:** 0.4.198.5419-232-nightly
* **Rust toolchain version:** 1.70.0-nightly (900c35403 2023-03-08) aarch64-apple-darwin
* **IDE name and version:** CLion 2023.2 EAP (CL-232.8296.18)
* **Operating system:** macOS 13.4.1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr, org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.ide.intentions.macros.function-like, org.rust.mir.borrow-check, org.rust.macros.proc, org.rust.ssr

## Problem description
Some macros don't want to expand?

I've already set the timeout in the registry to 20 seconds, the macro previously expanded with 10 seconds.

I don't see any logs about macro expansion

## Steps to reproduce
Try expanding this macro: https://github.com/swc-project/swc/blob/ed9a4ae5bc73b54641fc3f60843eb96c8cff6145/crates/swc_ecma_visit/src/lib.rs#L537

I'm working on https://github.com/vercel/turbo trying to implement the `Visit` trait the macro generates, but it doesn't seem to expand so intellij-rust doesn't give me any code completion and says I need to import it

**Comment by vlad20012** [comment]
Hi!
I'm not dure what exactly caused the macro expansion error, but there is a chance that invalidating caches can help you.
Could you please press `Ctrl + Shift + A`, then type "Invalidate Caches ...", then check "Clear file system cache and Local History" checkbox and press "Invalidate and Restart" button?

**Comment by ForsakenHarmony** [comment]
@vlad20012 tried invalidating multiple times and even manually deleted the rust cache files in the IDE directory

never with "Clear file system cache" though, just tried it and it doesn't seem to change anything

**Comment by vlad20012** [comment]
Okaay, let's try another option: `Ctrl`+`Shift`+`A` -> "Registry..." -> find `org.rust.macros.proc.timeout` and increase it to `10000`

**Comment by ForsakenHarmony** [comment]
@vlad20012 I've already set that to `20000` as mentioned in my original post 🙈

**Comment by vlad20012** [comment]
@ForsakenHarmony Ooook, `Help | Edit Custom Properties` -> add `idea.max.intellisense.filesize=10000`, restart the IDE

**Comment by ForsakenHarmony** [comment]
@vlad20012 yes that does seem to fix it

would be good to check for timeout and the filesize (if that's possible) and improve the error message
