### ISSUE TITLE
Project Sync environment variables

### ISSUE THREAD

**Issue by ark0f** [intellij-rust/intellij-rust#10638]
## Environment

* **IntelliJ Rust plugin version:** 0.4.197.5401-231
* **Rust toolchain version:** nightly-2023-04-25
* **IDE name and version:** CLion 2023.1.4
* **Operating system:** macOS 13.4.1

## Problem description
Same as https://github.com/intellij-rust/intellij-rust/issues/8503 but for project sync

**Comment by Maksim20023** [comment]
Hi! Thank you for reaching us
It seems that this feature request duplicates an existing [GitHub 9752](https://github.com/intellij-rust/intellij-rust/issues/9752).
Feel free to subscribe on it to stay informed and vote (click the emoji button in the bottom-left corner of the GitHub post). If you have any further suggestions, please reach out.
