### ISSUE TITLE
Making rust test menu better - edit configuration

### ISSUE THREAD

**Issue by fulara** [intellij-rust/intellij-rust#1064]
This is just a cosmetic - making life better change proposal. 

Rust supports now the incremental build. 
To enable incremental one has to set the enviromental variable CARGO_INCREMENTAL to 1.
To my knowledge Current way of 'Right click' -> Run test, creates new configuration not basing on anything. Because of that everytime i Use run testi have to go through cumbersome menu to set cargo incremental.

Proposed solutions - All of them are not ideal:
1) Enable paste in into the Env Variables - Probably a Quick fix -  This at least would make it less painful to copy the CARGO_INCREMENTAL into the configs that I want to have this variable.
2) Everytime you do a 'run test' it does a clone of current configuration instead of creating blank one.

Also,  is there any reason why the additional arguments field is so small? I can never read arguments and have to copy them into notepad. Yea there is a way to open the params into menu but I dont think thats ideal

**Comment by matklad** [comment]
Thanks for the report! It should be possible to tweak environment variables in the default configuration:

![default](https://cloud.githubusercontent.com/assets/1711539/23861825/4b0a6ccc-081c-11e7-9540-52b22cdf7e09.png)

**Comment by fulara** [comment]
Looks great! Looking forward to using it :)

**Comment by matklad** [comment]
You can always grab the latest build off master from https://teamcity.jetbrains.com/repository/download/IntellijIdeaPlugins_Rust_CurrentIdea_TestsRust/.lastSuccessful/intellij-rust-0.1.0.%7Bbuild.number%7D.zip. 

The fix will be in nightly later today and in alpha the next monday.

**Comment by fulara** [comment]
Woo! thanks. 
Just tried it out. Works perfectly.
I also see that you sneaked in the change about width of the Edit boxes in the config window ^_^.
