### ISSUE TITLE
Rework Rust settings UI

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1069]
The settings in `Settings > Language & Frameworks > Rust` are mighty confusing because of the path to standard library handling.

There are two cases. If user uses `rustup`, and we should probably just hide this field altogether and show a warning if we failed to retrieve the library. 

If user avoids rustup, then we must show this field and allow it to be configurable.

**Comment by vn971** [comment]
> we should probably just hide this field altogether

It would probably be good to tell the user that IDEA auto-configured itself using `rustup` though. Other than that, seems cool!

**Comment by matklad** [comment]
New settings look like this:

![new_settings](https://cloud.githubusercontent.com/assets/1711539/24800719/f3fa5e14-1ba9-11e7-929d-0f2c45cc8701.png)


There's configuration option for standard library location in case you don't use `rustup`, but there's a `Download via rustup` link underneath it. Also, the field is now automatically updated if you switch to rustup-enabled toolchain.

**Comment by vn971** [comment]
@matklad the best solution probably, thanks!
