### ISSUE TITLE
How can I disable lambda/let/match/par?

### ISSUE THREAD

**Issue by nathanaeljones** [intellij-rust/intellij-rust#1071]
When autocomplete fails, I'm instead presented with a list of 4 patterns - lambda, let, match, and par. 

Since it is difficult to predict when autocomplete fails, the actual effect of a series of keystrokes stops being deterministic. 

I would like to avoid accidentally invoking these all the time. Is there a way to turn them off?

**Comment by alygin** [comment]
Yes, there's a special preferences section for that: Preferences -> Editor -> General -> Postfix Completion. Find the "Rust" tree node and deselect templates you want to turn off.

**Comment by nathanaeljones** [comment]
Perfect, thanks!
