### ISSUE TITLE
cargo check doesn't display colored messages

### ISSUE THREAD

**Issue by lilianmoraru** [intellij-rust/intellij-rust#1072]
Running `cargo check`(now in Rust 1.16) with `--color=always`, displays everything in red(compilation messages, warnings, errors...).

**Comment by alygin** [comment]
What OS do you use? Such behaviour is expected on Windows because cargo and rustc don't emit correct ansi codes for msys terminals. You can find more details in #646, and here's the [issue for Stebalien/term](https://github.com/Stebalien/term/issues/58).

**Comment by alygin** [comment]
Oh, and on other platforms we don't colorize output for `cargo check`. As far as I remember, it didn't emit colors in the past. But it does now, so we can treat it as a color supporting command.

**Comment by lilianmoraru** [comment]
To answer to the question: it is Linux(the OS).

**Comment by alygin** [comment]
Yeah, I should've guess that. Just forgot that we deliberately excluded `cargo check` from the white list of colorizable commands.
