### ISSUE TITLE
problems with Rust plugin

### ISSUE THREAD

**Issue by zsmax** [intellij-rust/intellij-rust#10728]
## Environment

* **IntelliJ Rust plugin version:** 0.4.198.5409-231
* **Rust toolchain version:** 1.71.0 (8ede3aae2 2023-07-12) aarch64-apple-darwin
* **IDE name and version:** WebStorm 2023.1.4 (WS-231.9225.18)
* **Operating system:** macOS 13.4.1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr

## Problem description
The Rust plugin is broken. Infinity "Analyzing..." after restarting IDE. Same result even after restarting macOS & reinstall the Rust plugin. 

<img width="485" alt="Знімок екрана 2023-07-23 о 22 29 12" src="https://github.com/intellij-rust/intellij-rust/assets/43723372/6a09798f-7a2c-44a2-9b07-98a1747fa62f">

Autocomplete, refactoring, and even the context menu aren't working.
Some items refer not to their origins.

<img width="494" alt="Знімок екрана 2023-07-23 о 22 32 39" src="https://github.com/intellij-rust/intellij-rust/assets/43723372/2efc2567-1d38-452c-b7e0-af18a34fd1a6">
 
Some undefined behavior in the Impl block

<img width="511" alt="Знімок екрана 2023-07-23 о 22 49 16" src="https://github.com/intellij-rust/intellij-rust/assets/43723372/6bbc3d25-5078-46b9-8aab-4e0a2c236e3a">
<img width="470" alt="Знімок екрана 2023-07-23 о 22 49 27" src="https://github.com/intellij-rust/intellij-rust/assets/43723372/2a85bec4-daec-4829-9bcd-5c31f95fd1fa">

## Steps to reproduce
Sometimes it works, sometimes it does not. I haven't some schema to reproduce this behavior.

**Comment by Maksim20023** [comment]
Hi! Thank you for the report!
To investigate the issue, could you please send me logs ( [Help | Collect Logs and Diagnostic Data](https://www.jetbrains.com/help/webstorm/remote-development-troubleshooting.html#support))? Please remember that `idea.log` might contain sensitive information (e.g local paths). You can upload your logs to our https://uploads.jetbrains.com/. Uploaded files will only be accessible to JetBrains employees, and we guarantee the privacy of the data. And as a primary troubleshooting step, please try to perform [Invalidate caches](https://www.jetbrains.com/help/clion/invalidate-caches.html) with the checked "Clear file system cache and Local History" option.
