### ISSUE TITLE
cannot get impl methods and tests for dependant local cates at the same time in executable crate

### ISSUE THREAD

**Issue by alexiwalker** [intellij-rust/intellij-rust#10732]
## Environment

* **IntelliJ Rust plugin version:** 0.4.198.5409-231
* **Rust toolchain version:** 1.65.0
* **IDE name and version:** CLion 2023.1.5
* **Operating system:** Linux (Fedora 38)

## Problem description

attaching an executable (crateA) and a local crate it depends on / uses (crateB) to the plugin's cargo list causes methods in impl blocks in crateB to not be recognised / cannot find declaration to go to. Including only crateA in the plugins cargo list causes these methods to appear, but any tests implemented in crateB cannot be recognised as runnable by the IDE

## Steps to reproduce

a minimal version of this issue can be found here https://github.com/alexiwalker/rustpluginbug/tree/main. crateA in the problem description is plugin_error_minimal in this repo. crateB is inner_crate

if i attach inner_crate and plugin_error_minimal crates to the cargo list, the plugin does not recognise the following methods:
      
      use inner_crate;
      
      fn main() {
          let foo = inner_crate::SomeStruct::new(1,2,3);
          let sum = foo.sum();
          dbg!(&sum);
      }

the .. ::new(1,2,3)  is recognised. sum() on foo is also not recognised. The ::new is not coloured as a function by the ide, but sum() is. Neither allow me to go to their definitions, or provide information about the return types of the functions

inner_crate/src/lib.rs :
      
      pub fn add(left: usize, right: usize) -> usize {
          left + right
      }
      
      #[cfg(test)]
      mod tests {
          use super::*;
      
          #[test]
          fn it_works() {
              let result = add(2, 2);
              assert_eq!(result, 4);
          }
      }
      
      pub struct SomeStruct {
          a:u8,
          b:u8,
          c:u16
      }
      
      
      impl SomeStruct {
          pub fn new(a:u8,b:u8,c:u16)->SomeStruct {
              SomeStruct {
                  a,
                  b,
                  c,
              }
          }
      
          pub fn sum(&self) -> u32 {
              let mut sum = 0;
              sum = sum+self.a as u32;
              sum = sum+self.b as u32;
              sum = sum+self.c as u32;
              return sum
          }
      }

if this crate (inner_crate/crateB) is attached to the plugins cargo list, tests have the gutter "run" icon. If both crates are attached, the run test buttons do not appear.

example 1: showing only 1 crate attached, provides method information / annotated return types
![appcrateonlyhasimpl](https://github.com/intellij-rust/intellij-rust/assets/51602448/d7399381-1e11-409f-a88e-76fca9204fd1)

---

example 2:  1 crate attached, tests not runnable in IDE
![appcrateonlynotests](https://github.com/intellij-rust/intellij-rust/assets/51602448/c3daa05e-79a9-4ed8-8026-2f9dbae2312e)

---

example 3: 2 crates attached, tests are runnable
![bothcrateshastest](https://github.com/intellij-rust/intellij-rust/assets/51602448/4d2da9cb-9021-402b-81f9-1b42761bfaa8)

---

example 4: 2 crates attached,  impl methods do not provide any information (see the ::new() is white,  new and foo.sum() both do not provide type information
![bothcratesnoimpl](https://github.com/intellij-rust/intellij-rust/assets/51602448/b3709797-e10e-43dd-bb3d-fc1879c059b1)

**Comment by Maksim20023** [comment]
Hi! Thanks for the report.
It seems that the issue may appear in the project with multiple crates which aren't combined into a [workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html). This is a known issue for us, and as a workaround, could you please try to place your project into the [Cargo workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html)? Using a workspace is not mandatory but desirable to avoid problems.
With your example, after placing the project into the workspace, all functions (for example: return type definition, performing the "go to declaration" action), works, and tests have the gutter "run" icon.

**Comment by alexiwalker** [comment]
Thank you for your time! workspaces do appear to solve this problem for me. I am fairly new to rust (the language and the plugin) and wasnt familiar with that feature yet.  This does allow me to use both the gutter test run and provides type information properly!
