### ISSUE TITLE
Hint '`Self` doesn't implement `LowerHex`' in `bitflag` crate

### ISSUE THREAD

**Issue by sakaman** [intellij-rust/intellij-rust#10736]
## Environment

* **IntelliJ Rust plugin version:*0.4.199.5414-231*
* **Rust toolchain version:*1.26.0*
* **IDE name and version:*IntelliJ IDEA 2023.1.4 (Ultimate Edition) #IU-231.9225.16*
* **Operating system:*macOS 13.4.1*

## Problem description
Report inappropriate hint of Struct '`Self` doesn't implement `LowerHex`' in `bitflag` crate:

<img width="778" alt="image" src="https://github.com/intellij-rust/intellij-rust/assets/20101558/9d176bfc-9904-4879-a849-53eb9643e232">

## Steps to reproduce
create bitflag crate
```rust
bitflags! {
    #[derive(Debug, PartialEq)]
    pub struct MethodFlags: u16 {
        const PUBLIC = 0x0001;
    }
}
```

**Comment by Maksim20023** [comment]
Hi! Thank you all for reaching us. 
This issue is already known to us: #10019   Unfortunately, we currently don't have information about ETA for this issue.
When we have any new information about this issue, we will add a reply to GitHub 10019 ticket.
