### ISSUE TITLE
Highlight and indexing doesn't work with big struct which has #[serde(rename_all = "camelCase")]

### ISSUE THREAD

**Issue by rhacker** [intellij-rust/intellij-rust#10745]
## Environment

* **IntelliJ Rust plugin version:** 0.4.199.5414-231
* **Rust toolchain version:** rustc 1.71.0 (8ede3aae2 2023-07-12)
* **IDE name and version:** Intellij latest
* **Operating system:** Windows 11

## Problem description

```
#[serde(rename_all = "camelCase")]
#[derive(Deserialize, Serialize, Debug, Clone)]
struct D {
    a: i64,
    #[serde(with = "my_date_format")]
    b: Option<chrono::DateTime<Utc>>,
    #[serde(with = "my_date_format")]
    c: Option<chrono::DateTime<Utc>>,

    d: Option<String>,
    e: Option<String>,
    f: Option<f64>,
    // image_data: Option<serde_json::Value>,
    g: String,
    h: Option<f64>,
    i: Option<f64>,
    j: Option<String>,
    k: Option<String>,
    l: Option<String>,
    // Other fields commented out for privacy
}
```

struct like this is not being indexed and highlighted correctly.

## Steps to reproduce

```
#[serde(rename_all = "camelCase")]
#[derive(Deserialize, Serialize, Debug, Clone)]
struct D {
    a: i64,
    #[serde(with = "my_date_format")]
    b: Option<chrono::DateTime<Utc>>,
    #[serde(with = "my_date_format")]
    c: Option<chrono::DateTime<Utc>>,

    d: Option<String>,
    e: Option<String>,
    f: Option<f64>,
    // image_data: Option<serde_json::Value>,
    g: String,
    h: Option<f64>,
    i: Option<f64>,
    j: Option<String>,
    k: Option<String>,
    l: Option<String>,
    // Other fields commented out for privacy
}
```

just paste struct like this in the editor and we can see it's not being indexed and highlighted correctly.

**Comment by Maksim20023** [comment]
Hi! Thank you all for reaching us. 
I forwarded the issue description to our development team for investigating. Unfortunately, we currently don't have information about ETA for this issue.
When we have any new information about this issue, we will add a reply to this ticket.

**Comment by rhacker** [comment]
@Maksim20023 I have fixed the problem, since the `serde(rename_all)` should be declare after derive, there is a warning which I ignored.
