### ISSUE TITLE
Execute cargo metadata with RUST_BACKTRACE=1

### ISSUE THREAD

**Issue by stepancheg** [intellij-rust/intellij-rust#1074]
Because something is broken, and I have no idea what is.

<img width="761" alt="2017-03-19_0351" src="https://cloud.githubusercontent.com/assets/28969/24077221/89db5184-0c57-11e7-8c39-6bc3c15fad74.png">

**Comment by matklad** [comment]
It's https://github.com/rust-lang/cargo/issues/3844 causing a lot of grief recently :( 

I am not sure we should add `RUST_BACKTRACE=1` when we execute `cargo metadata` in the IDE: the case when it's better to execute `cargo metadata` manually from the console.

**Comment by stepancheg** [comment]
OK, no problem.
