### ISSUE TITLE
Do not insert matching }

### ISSUE THREAD

**Issue by stepancheg** [intellij-rust/intellij-rust#1076]
Although I'm very happy with intellij-rust, one feature annoys me.

Intellij-rust inserts `{}` when I type `{`. It is annoying, because most of the time I need to erase that matching brace.

E. g. I have a code like this:

```
match foo {
  Bar(x) <CURSOR HERE> if x => 1,
}
```

I want to type `=> {` at cursor position to convert code to:

```
match foo {
  Bar(x) => { if x { 1 } else { 2 } },
}
```

However, Intellij-rust inserts:

```
match foo {
  Bar(x) {} if x => 1,
}
```

so I need to immediately erase `}`.

Also, intellij-rust is very good at inserting matching `}` when I press Enter, e. g. in this case:

```
match foo {
  Bar(x) {<CURSOR HERE if x => 1,
}
```

So matching `}` right after `{` is almost never needed.

**Comment by minecrawler** [comment]
> So matching } right after { is almost never needed.

I disagree. Imho, it is needed most of the time, when just typing code. You described one scenario when correcting a line, but when writing code, you need `{` together with `}` all the time.

I think, a possible quick-solution would be a toggle-button for that behavior. A long-time solution might be some prediction algorithm.

**Comment by matklad** [comment]
If you place the cursor immediately before the `if`, we won't insert a matching `{`: https://youtu.be/JNgOsP1S_i8

We can decide if the matching brace is needed by looking at the next token, so we insert `}` if the next token is whitespace: https://github.com/intellij-rust/intellij-rust/blob/d4eec214568eb19b289be6d79742a70cc73c3b54/src/main/kotlin/org/rust/ide/typing/RsBraceMatcher.kt#L124.


I think that this particular use case should be covered by "move gurad into match arm" intention, will try to cook something up :)

**Comment by matklad** [comment]
Added an intention: https://zippy.gfycat.com/PracticalCreepyBoutu.mp4aa

closed by https://github.com/intellij-rust/intellij-rust/commit/e03ce9d523839f6f02936048a9686c39444b2b8d

**Comment by alygin** [comment]
I never paid much attention to that, but for Java, IDEA only inserts matching `}`s in some predefined contexts. Unfortunately, it sometimes doesn't insert them when I would expect it to do, but at least it doesn't annoy me when I do some nontrivial refactoring. Kotlin only analyzes the following symbol, CLion seems to not care about it at all and just throws `}` everywhere.

What do you think about such approach: try to insert a `}` and if it causes a syntax error nearby, remove it? I never looked into this part of the plugin, so not sure if there could be a reliable implementation.

**Comment by matklad** [comment]
>What do you think about such approach: try to insert a } and if it causes a syntax error nearby, remove it?

I am not sure that this is the heuristic we want here. Might be useful to check what exactly is Java doing there. 

And it also would be nice to have intentions for most non-weired situations, so that you don't have to type `{` manually :)

**Comment by stepancheg** [comment]
Another example:

```
let vec = unsafe <CURSOR HERE> mem::replace(&mut (arc as &mut Shared).vec, Vec::new());
```

Shouldn't intellij-rust only insert matching brace only if it the last character on the line?

> And it also would be nice to have intentions for most non-weired situations, so that you don't have to type { manually :)

That would be giant work I think.

**Comment by stepancheg** [comment]
Actually, inserting only at the end of line won't be enough. Another use case:

```
unsafe <CURSOR HERE>
let _: Box<Shared> = mem::transmute(ptr);
```

**Comment by stepancheg** [comment]
As minecrawler@ suggested, configuration option would probably be the best solution. Would it be hard to implement an option to disable insertion of matching brace?

**Comment by alygin** [comment]
> Might be useful to check what exactly is Java doing there.

[Here's](https://github.com/JetBrains/intellij-community/blob/04cca3fc20960350be3af72a854550115182f2ea/java/java-impl/src/com/intellij/codeInsight/highlighting/JavaBraceMatcher.java#L45) what Java does. The code is pretty the same as in the Rust plugin, but it behaves differently. For instance, in Java it adds the closing `}` in the following position:

```java
public void foo(/*caret*/) {
}
```

but does nothing when `{` is typed in a call expression:

```java
public void foo() {
   foo(/*caret*/);
}
```

So, I guess there's something else, not only `PairedBraceMatcher`. The `getCodeConstructStart()` method doesn't seem to have any effect on adding matching braces. Or I just don't get something in this API.

**Comment by matklad** [comment]
@stepancheg  `Settings > Editor > General > Smart keys > insert pair bracket` controls automatic brace pairing. 

@alygin 
In Java, brace insertion is more precisely controlled by this code: https://github.com/JetBrains/intellij-community/blob/9de9060087cbe00d2d12191441ae73d1de3f4d4d/java/java-impl/src/com/intellij/codeInsight/editorActions/JavaTypedHandler.java#L109

We can implement something like this as well. There's also `EnterAfterUnmatchedBraceHandler` which automatically adds `}` on Enter.

**Comment by stepancheg** [comment]
> Settings > Editor > General > Smart keys > insert pair bracket controls automatic brace pairing.

This option also stops inserting matching '(' and '[' which works well. But thanks anyway.

**Comment by matklad** [comment]
>This option also stops inserting matching '(' and '[' which works well. But thanks anyway.

Yeah, I think we need just to be more smart and do the same thing that Java does. I am in general against adding more options, I would prefer IDE to just do the right thing. 

By the way, @la10736 there's a nice option "surround selection on typing quote or brace", which is a little bit nicer to use than surrounders.

**Comment by la10736** [comment]
@matklad Thanks !
