### ISSUE TITLE
Cannot find declaration

### ISSUE THREAD

**Issue by Gedweb** [intellij-rust/intellij-rust#1079]
Cannot find declaration of crate when it's placed on local path:
```
[dependencies] # or `replace` section
forked_lib = { path = "some/path/forked_lib" }
```
As a result, autocomplete and other features is not working.

**Comment by matklad** [comment]
Hm, this is supposed to work: https://github.com/intellij-rust/intellij-rust/blob/2812b46825e0c8e762c1b61e97d752f112e641ac/src/test/kotlin/org/rust/cargo/toolchain/CargoProjectResolveTest.kt#L45

Can you try executing **refresh cargo project** action? Does it show any errors?

**Comment by Gedweb** [comment]
Sorry for worry, all work. It has been some one-time mistake.
Yours plugin is very helpful, thanks.

**Comment by matklad** [comment]
@Gedweb out of curiosity, what was the problem? Perhaps we should have shown an error message or something...
