### ISSUE TITLE
Can't profile bench on Rust 1.73.0

### ISSUE THREAD

**Issue by ZuoTiJia** [intellij-rust/intellij-rust#10820]
## Environment

* **IntelliJ Rust plugin version:**
[0.4.200.5446-232-nightly](https://plugins.jetbrains.com/plugin/8182-rust/versions/nightly/370644)
* **Rust toolchain version:**
rustc 1.73.0-nightly (500647fd8 2023-07-27)
binary: rustc
commit-hash: 500647fd8138cc09e87edb08d62f81654fbf6ef8
commit-date: 2023-07-27
host: aarch64-apple-darwin
release: 1.73.0-nightly
LLVM version: 16.0.5

* **IDE name and version:**
Build #CL-232.8660.186, built on July 26, 2023
* **Operating system:**
Mac OS
## Problem description
Can't profile bench on Rust 1.73.0

## Steps to reproduce
I create a Run/Debug cargo configure 

```
bench --package xxxx --bench xxx
```
I profile it, after build, it ran:
```
cargo bench --color=always --bench xxx --no-fail-fast --manifest-path .../xxx/Cargo.toml -- --format=json -Z unstable-options --show-output
```
the error message:
```
error: invalid value 'json' for '--format <format>'
  [possible values: pretty, terse]

For more information, try '--help'.
error: bench failed, to rerun pass `--bench xxx`

Caused by:
  process didn't exit successfully: `./target/release/deps/xxx-f817f5a67a4db1a6 --format=json -Z unstable-options --show-output --bench` (exit status: 2)
error: 1 target failed:
    `--bench xxx`
```

**Comment by Maksim20023** [comment]
Hi! Thank you for the report
This is a known issue for us and has already been reported. Please take a look at #7891. Unfortunately, we currently don't have information about ETA for this issue, and when we have any new information about it, we will add a reply to that ticket. You can subscribe to it to stay informed and vote (click the emoji button in the bottom-left corner of the GitHub post). 
If you have any further suggestions, please feel free to reach out.
