### ISSUE TITLE
Tokio macros are not recognised

### ISSUE THREAD

**Issue by stevepryde** [intellij-rust/intellij-rust#10849]
## Environment

* **IntelliJ Rust plugin version:** 0.4.200.5421-232
* **Rust toolchain version:** 1.72.0 (5680fa18f 2023-08-23) aarch64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2023.2.1 Ultimate Edition (IU-232.9559.62)
* **Operating system:** macOS 13.5.1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr, org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.ide.intentions.macros.function-like, org.rust.mir.borrow-check, org.rust.mir.move-analysis, org.rust.macros.proc, org.rust.ssr

## Problem description

Tokio macros like `tokio::main` and `tokio::test` are no longer recognised.

## Steps to reproduce

```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn Error + Send + Sync>> {
    Ok(())
}
```

The `main` in the macro will be underlined in red and hovering the mouse over it says "Unresolved reference: `main`"

**Comment by Maksim20023** [comment]
Hi. Thank you for reaching us.
Unfortunately, based on the description, I can't reproduce the issue. Please look at the screenshot: 
<img width="551" alt="Screenshot 2023-09-08 at 17 36 23" src="https://github.com/intellij-rust/intellij-rust/assets/135699123/07be5e6d-f667-442d-9023-959d3b3f99a0">

As a general troubleshooting step, please try to perform [Invalidate caches](https://www.jetbrains.com/help/idea/invalidate-caches.html) with the checked "Clear file system cache and Local History" option. If clearing the cache didn't help and the issue still exists, please collect and send logs ( [Help | Collect Logs and Diagnostic Data](https://www.jetbrains.com/help/idea/security-model.html#collect_logs)). Please remember that `idea.log` might contain sensitive information (e.g local paths). You can upload your logs to our https://uploads.jetbrains.com/. Uploaded files will only be accessible to JetBrains employees, and we guarantee the privacy of the data.

**Comment by stevepryde** [comment]
Invalidating caches didn't change anything, but I recreated the project from an empty project and imported all the modules again and it's working now. I have no idea what the issue was.

Closing this one.
