### ISSUE TITLE
Intelligent match completion

### ISSUE THREAD

**Issue by adiba** [intellij-rust/intellij-rust#1084]
For now I have created a live template for **match**. (Why isn't there one in the repo yet?)
It looks like this:
```
match $EXPRESSION$ {
    $MATCH1$ => { $BODY1$ },
    $MATCH2$ => { $BODY2$ },$END$
}
```
whereas the tab order is `MATCH1, MATCH2, BODY1, BODY2` and `MATCH1/2` have default value `Some(v)`/`None`.

I'd suggest a more intelligent solution (without live templates?):
In case the expression has exactly 2 possible values (e.g. `Option`, `Result`), all cases should be inserted.
If there aren't too many cases, a dialog should show up with a check-box for each option. All selected items should then be inserted, like this:
```
match o {
    std::cmp::Ordering::Equal => { },
    std::cmp::Ordering::Greater => { },
    std::cmp::Ordering::Less => { },
}
```
plus an underscore if cases remain uncovered of course.
If there are too many possible values, do something else idk.

IMO writing this by hand is quite tedious. Even for advanced pattern matching & destructing I would prefer automatic insertion and edit the patterns afterwards.

**Comment by matklad** [comment]
I think the best way to handle this is to have completion for the `match`, postifx template for match (already there), and an intention to fill out missing arms. Filed #1551 & #1552!
