### ISSUE TITLE
Wrong autocomplete suggestion for modules

### ISSUE THREAD

**Issue by adiba** [intellij-rust/intellij-rust#1085]
Somehow, when using other modules, top level modules like `std` are suggested as nested ones:
`use other_module::`
here `std` is suggested. Also when typing `std::`, a nested module of `other_module` is suggested, but modules that already occur in the path aren't suggested (if the path is invalid).
This seems so random... help!

**Comment by alygin** [comment]
Looks like a #874 relapse.

**Comment by adiba** [comment]
Although there are no cycles now

**Comment by matklad** [comment]
I am ... not sure if this is really fixed or not, but I can't reproduce this anymore, so closing! :)

**Comment by adiba** [comment]
@matklad my plugin is up to date
![image](https://cloud.githubusercontent.com/assets/23532559/26555327/cee85bc6-4494-11e7-857b-db035ed4d5fa.png)
