### ISSUE TITLE
Import package cannot be recognized normally

### ISSUE THREAD

**Issue by Anivie** [intellij-rust/intellij-rust#10850]
## Environment

* **IntelliJ Rust plugin version:** 0.4.200.5421-232
* **Rust toolchain version:** 1.72.0 (5680fa18f 2023-08-23) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2023.2.1 (CL-232.9559.58)
* **Operating system:** Windows 11.0
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr

## Problem description
When I import this [example](https://github.com/iced-rs/iced/tree/master/examples/styling) from Iced, Clion warns me that there is an unused import:
![QQ截图20230909184708](https://github.com/intellij-rust/intellij-rust/assets/88354708/1d8f3d6b-146a-4ae2-b46c-fc3995dce204)
But in fact these imports are necessary. When Clion cleans them up, the program will not compile normally.

## Steps to reproduce
Clone and open project.

**Comment by Maksim20023** [comment]
Hi! Thanks for reaching us.
This is a known issue for us and has already been reported. Please take a look at #9915. You can subscribe to it to stay informed and vote (click the emoji button in the bottom-left corner of the GitHub post). When we have new information, we will add a reply to that ticket.
If you have any further suggestions, please feel free to reach out.
