### ISSUE TITLE
--nocapture should be default for tests

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1086]

**Comment by CodeSandwich** [comment]
Are you sure it was a good idea? After the change all my passing tests throw thousands of lines into the run output. It became really hard to find the actually important output from failing tests.

**Comment by matklad** [comment]
I am not sure, but I lean yes.  This comes from my personal experience and from a couple of plugin's users whom I've asked. 

In the majority of cases, I run a single test or single module with tests. I do this using "run configuration from context" action (`ctr+shift+f10` on linux/windows, `some-sigil + r` on macs, or mouse click on the green icon in the gutter area), which creates configuration automatically and where defaults are very important. And when I run a single test, I absolutely want to see it's output, because I use `printf` debugging. 

For running all the tests in the project, I usually create by hand a separate run configuration. Because it's a single configuration, it's not a problem to customize it. 


If for your workflow `--nocapture` is not desirable, you should be able to disable it by editing default configuration (but it does not seem to work at the moment :(, will fix shortly):


![defaults](https://cloud.githubusercontent.com/assets/1711539/24542474/6fbab1d0-1604-11e7-83a6-bd5b7c5277fe.png)

**Comment by matklad** [comment]
Poll: should `--nocapture` be the default?

* :tada: yes, it should be a default
* :heart: no, tests output should be hidden

**Comment by CodeSandwich** [comment]
I love the idea of a "always pass --nocapture" checkbox, it will make everybody happy.

To bikeshed a bit, I have an argument in favor of defaulting the CHECKBOX to not pass the --nocapture: `Cargo test`'s default is lack of `--nocapture`, so new users of Intellij should also by default have no `--nocapture` when running tests.

**Comment by matklad** [comment]
Yeah, changing the default is a big disadvantage. The meta reason to justify this is that Cargo's defaults are tailored to the command-line usage, where it's simpler to `cargo test` then to figure out how to run a single test, while in the IDE you usually run a single test. 

There's an option to have a cake and eat it too: we can use `--nocapture` only for configurations from context...

**Comment by matklad** [comment]
Ok, `--nocapture` is default for a long time, and it worked out pretty well!
