### ISSUE TITLE
Display type of struct field names when viewed in quick-doc

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#1089]
It would be nice if in the following example:

```rust
struct S {
    /// A number.
    x: i32,
}

fn main() {
    let s = S{x: 0};
    let y = s.x;
}
```

Quick doc on the `.x` of `s` would show you that `x` is of type `i32` in addition to its doc string. This becomes even more useful when working with libraries that have `struct`s inside `struct`s.

**Comment by alygin** [comment]
You can quickly view the type of the field by moving the mouse pointer over it with Cmd (it's Ctrl in Windows/Linux, I guess) pressed. Though I agree, the same information should be displayed in the Quick Doc window.

**Comment by johnthagen** [comment]
@alygin Thanks for the reminder about <kbd>Ctrl</kbd>-Hover too. Agree it would be nice to have it in both.

**Comment by alexander-irbis** [comment]
Another way is Ctrl+Shift+I, which shows the declaration (it's useful with any entity, not only with fields)
