### ISSUE TITLE
Formatter should insert `;` after return statement

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1090]

**Comment by matklad** [comment]
This can be done with `PreFormatProcessor`. See `RsMatchArmCommaFormatProcessor`.

**Comment by d9n** [comment]
What are some example before and afters here? Are we talking about any expression, e.g.

`let x = 5<enter>`
`println!("Missing semicolon")<enter>`
`val += 10<enter>`

or some subset?

**Comment by anton-okolelov** [comment]
Not any expression. For example, there are multi line strings
```
let string = "line one
line two";
```

**Comment by matklad** [comment]
Sorry, I the original issue title was confusing. The `;` should be added after the `return` statement, as is

```
return
```
 ->

```
return;
```

There's one special case though: `;` should not be added in match arms, like 

```
match foo {
  Some(..) => { ... }
  None => return
}
```

Note that adding `;` to complete any statement is handled by **Complete Current Statement** action which is bound to `Ctrl+Shift+Enter` by default.

**Comment by anton-okolelov** [comment]
I can try to implement this feature but i'm not sure how fast. Is there a deadline for that?

**Comment by matklad** [comment]
No, there's no deadline :) Feel free to ask questions if you get stuck somewhere!

**Comment by anton-okolelov** [comment]
Could you please clarify this issue. When I start typing 'return' (for example 4 letters 'retu') I can press Enter and that's what I get:  return;  (with semicolon). It already works.
I'm a little bit confused, because I don't understand what the issue is about :)
Should I add semicolon when user doesn't use "Complete Current Statement" and presses Enter at the end of  line?
return<enter>  => return;

**Comment by matklad** [comment]
@anton-okolelov yep, we already handle inserting `;` or ` ` depending on the function type in autocompletion. However, our code formatter does not clean up semicolons. 

If you type

```
fn foo() {
    return
}
```

and then use **reformat code** action (`ctrl+alt+l`), you get the same code back, while you should ideally see

```
fn foo() {
    return;
}
```

That is, we should insert `;` during code formatting. We do something similar with commas in match arms in `org.rust.ide.formatter.RsMatchArmCommaFormatProcessor`. It turns this

```
fn main() {
    match x {
        1 => { 82 },
        2 => { 4 }
        _ => unimplemented!()
    }
}
```

Into this

```
fn main() {
    match x {
        1 => { 82 }
        2 => { 4 }
        _ => unimplemented!()
    }
}
```

**Comment by anton-okolelov** [comment]
@matklad thank you!

**Comment by anton-okolelov** [comment]
> Feel free to ask questions if you get stuck somewhere!
Okay :)

It seems I managed to find 'return expression' element, but I don't know how to add semicolon after it.
```
element.addAfter(...);
```
How to create PsiElement properly? Could you give me a clue?
Is there a factory for that or something?

**Comment by matklad** [comment]
@anton-okolelov take a look at `RsPsiFactory` and its usages.

**Comment by matklad** [comment]
>Is there a factory for that 

Spot on! :)

**Comment by matklad** [comment]
Oh, @anton-okolelov, we now require a CLA for PRs, see #1385 for details.

**Comment by mkaput** [comment]
@matklad I think you could set up some CLA bot, for example https://www.clahub.com/

**Comment by matklad** [comment]
Yeah, there's something like this being developed in JetBrains for community repository, but I would probably want to write our own thing, because I want something like @rust-highfive as well :) 

I am afraid clahub won't work as is for us, becuase we need the specific docu-sign CLA.

**Comment by anton-okolelov** [comment]
I've signed agreement
