### ISSUE TITLE
Join lines should remove `,` in struct literal

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1091]
```
S {
  foo: 1,
}
```

`Ctrl+Shift+J` ->

```
S { foo: 1 }
```

**Comment by matklad** [comment]
This is handled by `RawJoinLinesHandler`: https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/actions/RsJoinRawLinesHandler.kt

**Comment by d9n** [comment]
What should happen here post-join?

```rust
struct s {
   val1: i32,
   /*caret*/val2: i32,
   val3: i32,
}
```
A:
```rust
struct s {
   val1: i32,
   val2: i32, /*caret*/val3: i32,
}
```
B:
```rust
struct s { val1: i32, val2: i32, /*caret*/val3: i32 }
```

or none of the above / one of the above with a different final caret position?

**Comment by mkaput** [comment]
A

**Comment by d9n** [comment]
So could this bug be simplified to "comma followed by right-brace on the next line should delete comma on line joining"? Or should I only delete the comma if we're inside a struct?

**Comment by d9n** [comment]
OK I implemented a solution by being willing to delete commas before right brackets in any contexts, not just within structs, but feel free to push back on the CL if that approach is too broad. Especially, if you can point out a case where I shouldn't be removing a comma before a right bracket, let me know, and I'll add a test for that case as well. Thanks!
