### ISSUE TITLE
Autocompletion superimposed implemented functions from external crates

### ISSUE THREAD

**Issue by Niruyi** [intellij-rust/intellij-rust#1093]
The autocompletion superimposed implemented functions from external crates, in this case i work in different modules.

In the first module i use gtk::Box and in the second module it is std::boxed::Box, henceforth it shows me in the second module the completion of gtk::Box in combination with functions from std::boxed::Box and in each other module also.

gtk-rs Box function
    fn new(orientation: Orientation, spacing: i32) -> Box

is added to the auto-completion from std::boxed::Box, intellij-rust now says "This function takes 2 parameters but 1 parameter which supplied".
I do not know if it is an intellij-rust problem but I could never observe it.

**fast overview**
![intellij-rust-2017-03-26 22-14-06](https://cloud.githubusercontent.com/assets/2064210/24334857/cdaf4714-1272-11e7-9245-840bc95cf3b5.png)

**Comment by matklad** [comment]
Hm, that would be tough to solve properly, `gtk`'s box is [defined by the macro](https://github.com/gtk-rs/gtk/blob/1fd896a9f9f8c43e298b8db8b5c22ac5bc64aeee/src/auto/box_.rs#L19), that's why we think that `impl Box` referse to the Box from prelude.

**Comment by Kobzol** [comment]
It seems that this has been fixed somewhere along the way, it shows the correct completion in the latest version of the plugin for both Boxes, with all combinations of 2015/2018 edition and old/new macro expansion engine.
