### ISSUE TITLE
Fold one line methods

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1097]
It would be nice if one liners like

```Rust
pub fn root(&self) -> Node {
    Node { id: self.root, file: self }
}
```

Were folded by default, as in Java:

![one-line-method](https://cloud.githubusercontent.com/assets/1711539/24377779/31170b9e-1349-11e7-8de5-91556a8e4b06.png)

**Comment by alygin** [comment]
@matklad, closed?

**Comment by matklad** [comment]
Yep!

**Comment by miedzinski** [comment]
Is it possible to disable this?

**Comment by matklad** [comment]
Yep!

![folding](https://cloud.githubusercontent.com/assets/1711539/24863934/5dea4d30-1e0b-11e7-8612-bb91b84c98d5.png)

The option at the very bottom.

**Comment by miedzinski** [comment]
@matklad Thanks!
