### ISSUE TITLE
toml: double quote escaping issue

### ISSUE THREAD

**Issue by guai** [intellij-rust/intellij-rust#1107]
```toml
str = "I'm a string. \"You can quote me\". Name\tJos\u00E9\nLocation\tSF."
```
this line being shown incorrectly
like `You can quote me` is not a part of a string

**Comment by guai** [comment]
version 0.0.1.1759

**Comment by matklad** [comment]
closed by https://github.com/intellij-rust/intellij-rust/pull/1978
