### ISSUE TITLE
Is there a guide to which intellij-rust features work with which IntelliJ-based IDEs?

### ISSUE THREAD

**Issue by BatmanAoD** [intellij-rust/intellij-rust#1108]
From the [quick start guide]:

> You can use any JetBrains IDE to develop Rust. If you are not sure which one to choose, download IntelliJ IDEA community edition.

However, it appears that debugger integration isn't likely to be supported in IDEA. From user @matklad in #535:

 > It is certain that for the nearest future the debugger will be available in CLion, AppCode and maaaybe in RubyMine just because only these IDEs include com.intellij.modules.cidr.debugger module which we use. This is of course a shame, because it leaves out IDEA, PyCharm and other IDEs, and because Rust experience in CLion is not the best due to the interaction with CMake infrastructure. But of course this is just the beginning and we intend to fix these shortcomings :)

Are there any other features that are dependent on the choice of IDE? If so, I believe the recommendation in the quick-start guide might need to be enhanced, perhaps with a link to a page with a table of features indicating which IDEs support them.

**Comment by matklad** [comment]
Currently only debugger is CLion specific (we'll fix it!). 

IDEA specific features are

* Rust modules (module like in the `ctrl+alt+shift+s` menu), 

* Project creation dialog. 

In general, we strive to make experience equivalent in different IDEs, so I don't think we really need a specific differences page.

That said, docs were last updated ages ago, so it makes sense to go through quick-start guide once again.

**Comment by DieterVDW** [comment]
Are there some docs describing what features the plugin offers?
I installed the plugin and I know it added some Rust support features, but I don't have a clue which :) .

**Comment by alygin** [comment]
@DieterVDW, the most essential features are described [here](https://intellij-rust.github.io/features/).

**Comment by DieterVDW** [comment]
@alygin : Ok thanks, is exactly what I was looking for!

**Comment by matklad** [comment]
@DieterVDW it's also a good idea to look through weekly changelogs: https://intellij-rust.github.io/thisweek/

I haven't updated the main documentation for months :(, but all new features are mentioned in the changelog.
