### ISSUE TITLE
Is it possible to get a CLion open-source license for intellij-rust contributors?

### ISSUE THREAD

**Issue by BatmanAoD** [intellij-rust/intellij-rust#1109]
JetBrains [offers free CLion licenses for open-source projects](https://www.jetbrains.com/buy/opensource/?product=clion). These licenses must be applied for by the project. If and when JetBrains accepts the application, individual contributors can use CLion for free:

 > The software may be installed on any number of computers and concurrently used by as many open source project members as the number of licenses provided to the project.

Since CLion is currently the only IDE that supports the debugger-integration in its current state, having access to CLion seems important for anyone working on that feature. And, frankly, it seems to me that it's in JetBrains' best interest to support this project! :smile: 

(Disclaimer: I am not just trying to get a license for myself; unfortunately, I probably don't have time at the moment to contribute to the project, so I wouldn't consider myself eligible for the license anyway. I am, however, very interested in seeing the project succeed!)

**Comment by alygin** [comment]
Nice idea, but I believe it's not feasible due to the following statement:

> Projects that are sponsored by a commercial company or organization, or those with employees paid to work on the project are not eligible

Though, maybe JetBrains makes an exception when the mentioned _commercial company_ is JetBrains itself )

**Comment by BatmanAoD** [comment]
I saw that stipulation, but I didn't realize intellij-rust was in some way supported by JetBrains!

I did notice that the IntelliJ YouTrack site has [an issue open](https://youtrack.jetbrains.com/issue/IDEABKL-7289) for supporting Rust, and that this project is mentioned in the comments, but I couldn't tell whether there was any "official" support for the effort. I also didn't see it in the Readme, FAQ, etc. What kind of support is JetBrains providing? Is it mentioned anywhere?

**Comment by alygin** [comment]
@matklad works at JetBrains on this plugin. Similar questions were briefly discussed in the [gitter chat](https://gitter.im/intellij-rust/intellij-rust) recently.

**Comment by gertux** [comment]
I don't know it this is still relevant, but if I'm not mistaken you can download and use the EAP version of CLion without a license https://blog.jetbrains.com/clion/2017/05/clion-2017-2-eap-code-analysis-fixes/

I'm using a licensed version of CLion because I have an  'All Products Pack '

**Comment by BatmanAoD** [comment]
@gertux Thanks! I had a pre-1.0 EAP build installed a few years ago but for some reason thought they discontinued the program after 1.0 was released. Re-installing the latest EAP now :smile:
