### ISSUE TITLE
Way to retry rust-src download?

### ISSUE THREAD

**Issue by BatmanAoD** [intellij-rust/intellij-rust#1112]
I've found that I often have trouble downloading data from `static.rust-lang.org` from my computer; regardless of the tool I'm using (`curl`, `rustup`, etc) I receive a "couldn't resolve host name" error.

I don't really know what causes this, but I'm typically able to resolve the issue by re-trying the download a couple times.

Sure enough, upon installing IntelliJ-Rust and opening a project, I got an error:

    Failed to download standard library: rustup failed: `info: downloading component 'rust-src' error: component download failed for rust-src info: caused by: could not download file from 'https://static.rust-lang.org/dist/2017-03-11/rust-src-1.16.0.tar.gz' to 'C:\Users\<myname>\.rustup\tmp\7nbosxi96hsnu9ot_file info: caused by: error during download info: caused by: [6] Couldn't resolve host name (Couldn't resolve host 'static.rust-lang.org') 

I used "Invalidate Caches/Restart" to force the IDE to re-try the download; this failed once in the same way, then on the second invalidate/restart, the download was successful.

Is there an easier way to re-try a source-library download?

**Comment by matklad** [comment]
Hm, that's an interesting question! I want to redo out project settings dialog soon, adding an explicit "download standard library" button would be useful!

**Comment by matklad** [comment]
![new_settings](https://cloud.githubusercontent.com/assets/1711539/24800812/5bb99240-1baa-11e7-87f8-78d1522f9358.png)

`Download stdlib` should handle this.

Thanks for the report!

**Comment by BatmanAoD** [comment]
Cool, thank you!

I've successfully downloaded the sources by now, but I tried this feature out, and I didn't get any notification that anything was happening. Is that because the sources are already there?

**Comment by matklad** [comment]
Yep, if the field is filled with some path that means that everything is OK.

**Comment by weaming** [comment]
> ![new_settings](https://cloud.githubusercontent.com/assets/1711539/24800812/5bb99240-1baa-11e7-87f8-78d1522f9358.png)
> 
> `Download stdlib` should handle this.
> 
> Thanks for the report!

In my case, click to refresh and succeed getting rust stdlib

![image](https://user-images.githubusercontent.com/10275711/110606350-11aca680-81c5-11eb-819a-b1aec7fac4cf.png)
