### ISSUE TITLE
Cannot borrow immutable local variable `None` as mutable

### ISSUE THREAD

**Issue by eugene-bulkin** [intellij-rust/intellij-rust#1114]
I have a function that takes a `&mut Option<T>`, and in cases where it doesn't need anything, I can pass a `&mut None` in. However, this now is noted as an error in IntelliJ, when it wasn't before (and it isn't an actual Rust error).

**Comment by farodin91** [comment]
I think the checks thinks None is an variable. And this variable isn't mutable. 

I will look into it deeper. The checks need to be refactor decided between mutable and assignable.

**Comment by farodin91** [comment]
Assignable = reassignable

**Comment by matklad** [comment]
closed by https://github.com/intellij-rust/intellij-rust/pull/1122
