### ISSUE TITLE
"Reformat file with rustfmt" gives confusing error if rustfmt is not installed

### ISSUE THREAD

**Issue by BatmanAoD** [intellij-rust/intellij-rust#1131]
I hadn't realized that `rustfmt` is a separate package that isn't included by default with Cargo, and I hadn't installed it.

Without `rustfmt` installed, IntelliJ-Rust gives this error message:

 > C:\Users\<me>\.cargo\bin\cargo.exe fmt -- --write-mode=overwrite --skip-children <my-project>/<my-file>.rs stdout : stderr : error: no such subcommand: `fmt` Did you mean `doc`?

No, I did not mean `doc`, silly tool!

Obviously this is user error, but I believe IntelliJ-Rust could probably handle this fairly easily, i.e. by checking for the above error and suggesting to the user to manually run `cargo install rustfmt`, or by simply automatically checking if `rustfmt` is installed and doing the install automatically if not.

**Comment by BatmanAoD** [comment]
...note, though, that the `"did you mean `doc`?" error message is apparently not unique to the case where `rustfmt` simply isn't installed: https://github.com/rust-lang-nursery/rustfmt/issues/746

**Comment by maraisr** [comment]
@matklad @BatmanAoD Is this issue still relevant? If so, are you able to point me in the right direction in fixing this?

**Comment by mkaput** [comment]
Yeah, anything was done with this.

The main source of the action is [here](https://github.com/intellij-rust/intellij-rust/blob/7cd84c892bb48021b9d5157cdbb8dc54c269b026/src/main/kotlin/org/rust/ide/actions/RsFmtFileAction.kt), which generally just saves file and calls [this](https://github.com/intellij-rust/intellij-rust/blob/7cd84c892bb48021b9d5157cdbb8dc54c269b026/src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt#L79) function.

For detecting whether fmt is not installed, I would just check whether there is substring `no such subcommand: fmt` inside stderr. Maybe silly but will work with all these rustup shims and path shenanigans until somebody will change this beautiful message.

**Comment by BatmanAoD** [comment]
Thanks @maraisr!
