### ISSUE TITLE
"Find Usages" doesn't work in nested packages

### ISSUE THREAD

**Issue by alygin** [intellij-rust/intellij-rust#1137]
While working on one of the error annotations I stumbled upon a problem with the "Find Usages" command. It finds nothing when performed in a nested package. Here's a simple project that reproduces this problem: [alygin/usage](https://github.com/alygin/usage). [This simple case](https://github.com/alygin/usage/blob/243427bb263ae56b6c78dca08024c22b3832eb43/nested/src/lib.rs) doesn't work in the nested package.

I noticed that it stops working as soon as you add the dependency block to the root `Cargo.toml`. That is, the command works as expected when [this block](https://github.com/alygin/usage/blob/243427bb263ae56b6c78dca08024c22b3832eb43/Cargo.toml#L8) is removed.

I tried to find the way to fix it, but there's not much code in `RsFindUsagesProvider` and it seems that the platform does all the magic itself. Any hints on what could be the reason of such behaviour and how to fix it?

**Comment by matklad** [comment]
I have a vague idea that we add path dependencies as library roots (which we probably shouldn't do, and we definitely shouldn't do for workspace members), so these usages are filtered out by the default search scope ("project", and not "project and libraries").

**Comment by alygin** [comment]
You're right, the problem can be fixed by setting `origin = WORKSPACE` on the `nested` package. But we don't do that now because cargo doesn't add this package to the `workspace_members` list since there's no `[workspace]` block in the root `Cargo.toml` that contains `nested` as a member.

So, on the one hand, it's totally correct on the cargo side. On the other hand, many projects with nested packages don't use explicit workspaces, but it would be nice to handle them properly.

We could require explicit workspaces for such project layouts to work properly (in accordance with cargo) or treat all the packages that are located within the project directory as workspace members. What do you think?

**Comment by matklad** [comment]
>We could require explicit workspaces for such project layouts to work properly (in accordance with cargo) or treat all the packages that are located within the project directory as workspace members. What do you think?

I think we shouldn't treat a package as a library if it is an explicit member of the workspace regardless of the location, or if it is a path dependency and resides under module's content root .

**Comment by alygin** [comment]
> we shouldn't treat a package as a library if it is an explicit member of the workspace regardless of the location

It already works

> or if it is a path dependency and resides under module's content root

That's a thing to implement. I'll to that.
