### ISSUE TITLE
Show function parameters automatically

### ISSUE THREAD

**Issue by torkleyy** [intellij-rust/intellij-rust#1141]
It would be really helpful to see that you have to pass `(foo: Foo, bar: Bar)` while calling a function.

**Comment by alygin** [comment]
Cmd + P (Ctrl + P) within the arguments list [should work](https://github.com/intellij-rust/intellij-rust/pull/803). Also Cmd (Ctrl) + mouse hover. Also Cmd + J (Ctrl + J) on the function name.

**Comment by torkleyy** [comment]
I thought I tried that before, but apperantly I pressed the wrong keys. Is there a way to let them pop up by default?

**Comment by alygin** [comment]
Technically yes, they can be programmed to popup automatically, but it's not implemented at present.

**Comment by himikof** [comment]
Likely relevant: parameter hints proposed at #847 (now that 2016.3 is required).

**Comment by alygin** [comment]
> they can be programmed to popup automatically, but it's not implemented at present.

A bit more information on this: a parameters hint pops up automatically if you write a function name manually, but it does not when you choose a function from the autocompletion list. That's the room for improvement.

> Likely relevant: parameter hints proposed at #847 (now that 2016.3 is required).

The API is still [marked as experimental](https://github.com/JetBrains/intellij-community/blob/7561efbf462cc30eddbd78be24317e6e641afad4/platform/lang-api/src/com/intellij/codeInsight/hints/InlayParameterHintsProvider.java#L29) but I see that the feature has already made it to other IntelliJ products (I noticed it in DataGrip), so maybe it will stabilise soon.

**Comment by matklad** [comment]
>The API is still marked as experimental but I see that the feature has already made it to other IntelliJ products (I noticed it in DataGrip), so maybe it will stabilise soon.

If it's in 2016.3, it's ok to use it!

**Comment by matklad** [comment]
The relevant extension interface is `com.intellij.codeInsight.hints.InlayParameterHintsProvider` .

**Comment by farodin91** [comment]
I'll grab it.
