### ISSUE TITLE
Don't append a second file extension when creating a file

### ISSUE THREAD

**Issue by torkleyy** [intellij-rust/intellij-rust#1155]
[low priority]

When I create a new Rust file and I type in `bar.rs`, I'll get a `bar.rs.rs`.

**Comment by alygin** [comment]
Hm, I can't reproduce the problem. Could you, please, provide some information about your setup: what IDE you use (IDEA, CLion, PyCharm etc), its version and the plugin version?

**Comment by torkleyy** [comment]
Huh? I cannot reproduce it anymore, but I'm absolutely sure I got a `.rs.rs`.... I'll close this issue; should I experience this bug again, I'll reopen it.
