### ISSUE TITLE
Method name not highlighted if there are multiple matches

### ISSUE THREAD

**Issue by torkleyy** [intellij-rust/intellij-rust#1185]
I'm defining a method differently for two different configurations like this:

```rust
struct Foo;

impl Foo {
    #[cfg(unix)]
    fn foo(&self) {
        println!("Hello Unix!");
    }

    #[cfg(windows)]
    fn foo(&self) {
        println!("Hello Windows!");
    }
}
```

Auto-completion shows the method twice, but the function name does not get highlighted.

**Comment by farodin91** [comment]
With deref will get more of these cases of multiple matches.

**Comment by matklad** [comment]
This is https://github.com/intellij-rust/intellij-rust/issues/1191
