### ISSUE TITLE
Show trait of a method in autocomplete popup

### ISSUE THREAD

**Issue by farodin91** [intellij-rust/intellij-rust#1190]
It would a cool function to see some background infos.

**Comment by farodin91** [comment]
@matklad I like to grab, any tip to start this?

**Comment by matklad** [comment]
This is handled by `createLookupElement` from `CompletionEngine.kt`. You can insert additional info in the `is RsFunction` case. `RsFunction.role` can be used to check if this is a trait/impl method at all.
