### ISSUE TITLE
Prevent examples as project name

### ISSUE THREAD

**Issue by farodin91** [intellij-rust/intellij-rust#1194]

**Comment by matklad** [comment]
Why do we need this? Does Cargo fail if one names one's project "examples"?

**Comment by farodin91** [comment]
Cargo fails with a base folder name "examples".

**Comment by matklad** [comment]
Hm, seems to work fine here:

```
~/trash master*
λ cargo new examples
     Created library `examples` project

~/trash master*
λ cd examples/cargo

~/trash/examples master*
λ ls
src  Cargo.toml

~/trash/examples master*
λ cargo test --all
   Compiling examples v0.1.0 (file:///home/user/trash/examples)
    Finished dev [unoptimized + debuginfo] target(s) in 0.78 secs
     Running target/debug/deps/examples-ab5a25f76fbb9f9e

running 1 test
test tests::it_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests examples

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
```

Perhaps this a bug in Cargo specific to your invornment, or a bug in IntelliJ-Rust? Does creating `examples` project from the command line work for you?

**Comment by farodin91** [comment]
Interesting

**Comment by farodin91** [comment]
I created the project with intellij-rust.

**Comment by matklad** [comment]
Ok, I would say that it is a bug in Cargo: https://github.com/rust-lang/cargo/issues/3990.

We shouldn't duplicate this logic in IntelliJ Rust. Instead, we can show the error generated by Cargo when that issue is fixed.

**Comment by matklad** [comment]
PR to fix cargo: https://github.com/rust-lang/cargo/pull/3994
