### ISSUE TITLE
Autocomplete for types with type constraints

### ISSUE THREAD

**Issue by zummenix** [intellij-rust/intellij-rust#1195]
Probably it hasn't been implemented yet but I've decided to open the issue anyway.

Example:
```rust
fn main() {
    println!("{:?}", foo()./* autocomplete here */);
}

fn foo() -> Result<i32, i32> {
    Ok(42)
}
```
Autocomplete works for methods on `impl<T, E> Result<T, E>` but doesn't work on `impl<T, E> Result<T, E> where E: Debug` and bunch of others with type constraints, i.e. doesn't autocomplete `unwrap`, `expect`, etc.

**Comment by vlad20012** [comment]
Automatically implemented currently not supported. I'm working on it.
- [ ] Sized
- [ ] Sync
- [ ] Send
- [ ] #[derive()]

**Comment by torkleyy** [comment]
@vlad20012 Will custom `#[derive]`d traits also work?

**Comment by vlad20012** [comment]
@torkleyy I'm not sure yet, but I think so.

**Comment by matklad** [comment]
Hm, I wonder if we should be less conservative here and just resolve all methods regardless of trait bouds.

We'll use trait bounds to disambiguate possible conflicts and (somewhere in the future), to annotate errors like "you are calling `.contains_key` on `BTreeMap`, but `Key` is not `Hash`. Add `#[derive(Hash)]`?"

**Comment by farodin91** [comment]
@matklad I would prefer your idea.
For example
```rust
let mut map = HashMap::new();
                                         \\^unresolved
```
At this intellij can't know type constraints.
