### ISSUE TITLE
Don't insert `>` if typed after `<`

### ISSUE THREAD

**Issue by torkleyy** [intellij-rust/intellij-rust#1197]
I think there the auto-insert for `>` was recently implemented, however it would be nice to not have a second `>` every time you type it yourself (I'm used to that because other editors don't provide the functionality).

**Comment by matklad** [comment]
This is literally what I am working on just this very second :) 

![default](https://cloud.githubusercontent.com/assets/1711539/25664714/18fdd496-3024-11e7-95ce-99e8d7ad9dcf.png)

**Comment by matklad** [comment]
Closed by https://github.com/intellij-rust/intellij-rust/pull/1199
