### ISSUE TITLE
Debugger does not find binary when creating library instead of binary

### ISSUE THREAD

**Issue by jheyens** [intellij-rust/intellij-rust#1201]
When creating a library with cargo, `lib.rs` by default contains a test module with a sample function.

That function has a similar button on the left like the `main` function in the debugger sample. 
Clicking `Run` works as expected:
![root_window_1493889054](https://cloud.githubusercontent.com/assets/18119154/25697345/e4de3cc2-30ba-11e7-90f7-9c564e963689.jpg)
`Debug` does not find binary:
![root_window_1493889070](https://cloud.githubusercontent.com/assets/18119154/25697351/e93ecec6-30ba-11e7-856e-3f71a60897e9.jpg)

**Comment by IvankoB** [comment]
Appzs for the dump question - how to set up & activate stepped debugging (in CLion in Win7 for instance) for the newest plugin ?
