### ISSUE TITLE
Nightly build failures

### ISSUE THREAD

**Issue by farodin91** [intellij-rust/intellij-rust#1221]
https://teamcity.jetbrains.com/viewLog.html?buildId=1062159&tab=buildResultsDiv&buildTypeId=IntellijIdeaPlugins_Rust_OldestIdea_TestsRust

**Comment by matklad** [comment]
Ouch, thanks a lot for heads up!

Looks like Team City does not send notifications if a dependent build has failed (and I haven't looked at the builds themselves for a while because of long holidays in Russia :) ) !

**Comment by matklad** [comment]
Ok, the builds are green again and I've fixed my notification preferences, so I'll get notified when this happens again. There's still a problem that the TC nightly badge is green though, it should be fixed on TC side.
