### ISSUE TITLE
Angle brackets don't auto close correctly

### ISSUE THREAD

**Issue by drhagen** [intellij-rust/intellij-rust#1238]
After a closing bracket has been automatically inserted, typing the closing bracket manually should type over the existing one so that only one closing bracket . This does not happen with angle brackets `<>`; instead there are two closing `>`, so that I frequently end up with code like this:

Start here
`struct MyStruct`
then type `<` to get 
`struct MyStruct<>` 
then type `>` to erroneously get
`struct MyStruct<>>` 

The `(` and `[` and `{` brackets work as expected.

**Comment by alygin** [comment]
I believe it was fixed in #1199. Should be released in alfa later today.

**Comment by drhagen** [comment]
Confirmed fixed in 0.1.0.1991.
