### ISSUE TITLE
Too angry when missing a field in a struct

### ISSUE THREAD

**Issue by gilescope** [intellij-rust/intellij-rust#1250]
Until the very last field is added when instantiating a struct, there is no coloring / syntax highlighting of the fields you have filled in. Everything is an angry red squiggle telling you you've not completed all of it.

It would be great if it could give better support for not totally filled in structs as this is quite a common occurrence when coding. Maybe the red warning could be just be on the struct name rather than the full contents of the struct? (Apologies if what I'm asking for is very difficult).

(Also if you're in the area, if you autocomplete setting a struct member when instantiating  a struct it would be great if it also added the ': ' by default - that would be super slick)

**Comment by farodin91** [comment]
If it help a bit you could go red marked area and press alt enter to generate all missing fields.

**Comment by matklad** [comment]
>Maybe the red warning could be just be on the struct name 

Yeah, I feel this is the correct solution!

**Comment by matklad** [comment]
>Maybe the red warning could be just be on the struct name 

This looks like a nice solution!
