### ISSUE TITLE
Run all test (in a file & whole project)

### ISSUE THREAD

**Issue by tyoc213** [intellij-rust/intellij-rust#1262]
How can I run all test in the project and all test in a file?

**Comment by alygin** [comment]
To run all the test in your project, you need to create a cargo run configuration (Run -> Edit configurations -> Add New Configuration (+) -> Cargo Command) and set `test` as the command. Every time you run this configuration, all the project will be tested.

If you want to run all tests from a particular file in `tests/` directory, you can select the `Run 'file_name'` from the context menu of this file. A run configuration with proper parameters will be created automatically. You can also create such configuration manually.

Running all the tests from a particular file in `src/` directory will require either putting them into a test module with a unique name, or using some unique prefix for all the test function in this file. In this case you can create a run configuration and specify either the module name or the unique prefix as an additional argument to make cargo only run these tests. For instance, you can have `#[cfg(test)] mod foo_tests` in your file and create a configuration with the `test` command and `foo_tests` as an additional argument. Running such a configuration will execute only tests from this particular module.

So, the plugin actually leverages cargo's test harness, you just need to create a run configuration with proper parameters and use it when needed.

**Comment by matklad** [comment]
>To run all the tests in your project, you need to create a cargo run configuration (Run -> Edit configurations -> Add New Configuration (+) -> Cargo Command) and set test as the command. Every time you run this configuration, all the project will be tested.

I usually use a slightly lighter workflow **Find action** (`ctrl+shift+a`) > "Run Cargo command" > `test --all`. There are also shortcuts for rerunning the last/one of the previous run configurations. 

Running all test from a file can be accomplished by "focusing" on a file (selecting it in the project view, just activating an editor with the file opend, or by finding the file in "find file" action) and using a run shortcut (`ctlr+shift+f10`).
