### ISSUE TITLE
Autocomplete does not show members of T via Box<T>, Rc<T> and Arc<T>

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#1270]
![image](https://cloud.githubusercontent.com/assets/873919/26494833/591719a4-4229-11e7-9495-3a1181aba805.png)

**Comment by Undin** [comment]
I think it was closed by #1293

**Comment by matklad** [comment]
Yep, thanks @vasily-kirichenko and @Undin !
