### ISSUE TITLE
Multi line / documentation comments should be (auto) collapsible

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#1278]
![image](https://cloud.githubusercontent.com/assets/873919/26522500/167dde56-430b-11e7-9926-d69e3cad0b49.png)

**Comment by matklad** [comment]
If anyone wants to look into this, the code is in org.rust.ide.folding.RsFoldingBuilder.

**Comment by vasily-kirichenko** [comment]
Implemented in https://github.com/intellij-rust/intellij-rust/pull/1282

**Comment by matklad** [comment]
FYI you can add `close #1282` comment in the commit message or the pull request description, and then the issue will be closed once the PR is merged.
