### ISSUE TITLE
Wrong suggestion to remove parens around struct construction literal at `match ..` site

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#1285]
![1](https://cloud.githubusercontent.com/assets/873919/26527637/5c45ee0c-43a0-11e7-840a-513a6fd9ce78.gif)

**Comment by matklad** [comment]
To fix this, one need to look into `org.rust.ide.annotator.RedundantParenthesisVisitor`. Struct literal in conditions and matches is the only case where parenthesis are mandatory I think.
