### ISSUE TITLE
Error highlighting is not updated after an action executed

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#1286]
![1](https://cloud.githubusercontent.com/assets/873919/26527664/d976f650-43a0-11e7-8588-95d7f94a6702.gif)

That's a buggy action and it produces non compilable code, but the red squiggles do not appear until the document is changed (a space was inserted).

**Comment by ortem** [comment]
Now there is no "Remove parentheses..." quick-fix, so I close it.
<img width="475" alt="screen shot 2018-10-09 at 12 19 25" src="https://user-images.githubusercontent.com/4854600/46659488-b0301a00-cbbd-11e8-992c-c2f83937499b.png">
