### ISSUE TITLE
Wrong auto indentation in method chains

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#1299]
![1](https://cloud.githubusercontent.com/assets/873919/26577988/e424f484-4536-11e7-93c3-32cb14dbf83a.gif)

I think the cursor should be placed at position of the previous dot, if the dot is the first character in line.

**Comment by alexander-irbis** [comment]
> if the dot is the first character in line

If there is unfinished expression
```rust
    let matches =
        App::new("Unique Random File Generator")
            .version("1.0")
            |
```
but after ";" cursor should be placed as usual.
```rust
    let matches =
        App::new("Unique Random File Generator")
            .version("1.0");
    |
```
(sorry for "captaincy" :-))

**Comment by matklad** [comment]
We won't autoindent the cursor itself (because it's not clear if the expression is complete or not), but typing dot will place it in the proper position:

![autoindent dot](https://thumbs.gfycat.com/MediocreCompassionateBassethound-size_restricted.gif)
