### ISSUE TITLE
#![feature(test)] is not supported

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#1303]
![image](https://cloud.githubusercontent.com/assets/873919/26625024/8a4059e8-45fb-11e7-8636-a7782bc8b197.png)

![image](https://cloud.githubusercontent.com/assets/873919/26625044/98a46e66-45fb-11e7-918a-6df48e84e648.png)

(the above code is compiled).

**Comment by alygin** [comment]
Do you have the standard library correctly configured in "Preferences -> Lang & Frameworks -> Rust" and downloaded? Is there `libtest` library among dependencies in your project (Project -> External Libraries -> Rust -> libtest)?

<img width="264" alt="screen shot 2017-06-01 at 06 24 31" src="https://cloud.githubusercontent.com/assets/2101250/26663412/2411ded8-4693-11e7-91c5-39156e58fa0e.png">

**Comment by vasily-kirichenko** [comment]
Looks like there is no libtest anywhere:

![image](https://cloud.githubusercontent.com/assets/873919/26668234/6df5692a-46b1-11e7-97b5-6ff109952154.png)

![image](https://cloud.githubusercontent.com/assets/873919/26668240/763c7952-46b1-11e7-90f6-5b20ae6b874b.png)

![image](https://cloud.githubusercontent.com/assets/873919/26668280/a850ac2e-46b1-11e7-92d8-6505fc08a130.png)

But the project is compiled successfully. Is there a way to fix it?

**Comment by alygin** [comment]
Hm, that's strange, `libterm` and `libtest` are missing in your sources. Could you check if there's the `libtest-*` library in toolchains/nightly-.../lib? Since the project compiles, it should be there.

Is your toolchain up to date? If no, could you update it and check if the missing sources have downloaded?

**Comment by vasily-kirichenko** [comment]
`rustup update` has fixed the problem, everything is fine now, thanks!
