### ISSUE TITLE
Static vars are considered the same as local vars

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#1304]
![1](https://cloud.githubusercontent.com/assets/873919/26630100/0627c700-460e-11e7-9ec7-464dd1dda76b.gif)

**Comment by matklad** [comment]
Hm, this is sort-of how Rust actually works :) The left hand side of `let` is a pattern, `x` in the pattern can mean either of two things:

1. If there's a constant named `x` in scope, than `x` will match with that constant.

2. If there's no such constant, then `x` introduces a new name

```rust
const ONE: i32 = 1;
const TWO: i32 = 2;

fn main() {
    let x = 2;
    match x {
        ONE => println!("A"), // will match if x == 1
        TWO => println!("B"), // will match if x == 2
        THREE => println!("C"), // will match if x != 1 && x !=2 and will bind name `THREE` to it. 
    }
}
```

This somewhat unexpected context-sensitive rules are necessary to make it possible to write

```
match opt {
  Some(_) => {}
  None => {} // Here, `None` is a constant.
}
```

You are not actually allowed to pattern match `static`s:

```Rust
static  ONE: i32 = 1;

fn main() {
    match 2 {
        ONE => println!("A"),
        THREE => println!("C"),
    }
}
```

```
error[E0530]: match bindings cannot shadow statics
 --> src/main.rs:5:9
  |
1 | static  ONE: i32 = 1;
  | --------------------- a static `ONE` is defined here
...
5 |         ONE => println!("A"),
  |         ^^^ cannot be named the same as a static
```

But internally that `ONE` indeed resolves to static, and only after the compiler issues a warning. Does this make sense?

**Comment by Dr-Emann** [comment]
Or, more directly equivalent to the example in the issue:

```rust
static xs: &'static [i32] = &[3, 2, 10];

fn main() {
    let xs = [2, 3, 4];
}
```

```
error[E0530]: let bindings cannot shadow statics
 --> <anon>:4:9
  |
1 | static xs: &'static [i32] = &[3, 2, 10];
  | ---------------------------------------- a static `xs` is defined here
...
4 |     let xs = [2, 3, 4];
  |         ^^ cannot be named the same as a static

error: aborting due to previous error
```

https://is.gd/90khT1

**Comment by matklad** [comment]
I'm going to close the issue because there isn't something we can really fix here. We probably can create a more targeted inspection, warning, but I would say it would have only a rather niche use case.

Thanks for the more succinct example @Dr-Emann !
