### ISSUE TITLE
Add .tml extension for TOML

### ISSUE THREAD

**Issue by francislavoie** [intellij-rust/intellij-rust#1309]
I use the `.tml` extension for my TOML files, would be nice if it defaulted to those as well.

**Comment by matklad** [comment]
Looks like the spec says it should be `.toml`: https://github.com/toml-lang/toml#filename-extension, so I don't think we should add `.tml` as a default to the plugin. 

You can configure `.tml` as an addition extension for TOML in the IDE settings: `Settings > Editor > File Types`.
