### ISSUE TITLE
proc_macro crate is not recognized in editor

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#1311]
![image](https://cloud.githubusercontent.com/assets/873919/26725892/4f3d731c-47a9-11e7-94d4-406535da4e22.png)

However, the project compiles.

**Comment by alygin** [comment]
Do you see it in External Libraries -> Cargo? If no, try to run the "Refresh cargo project" action.

**Comment by alygin** [comment]
Oh, my bad, it's `proc_macro`, we should add it as an stdlib root.

**Comment by jannik17** [comment]
![image](https://user-images.githubusercontent.com/24388304/35228125-3abd912a-ff90-11e7-8b10-c6dd8d29be45.png)

proc_macro crate is not recognized in editor. I am using the newest build. This problem seems only to occur if the crate is in a workspace.
