### ISSUE TITLE
Wrong rust clippy inspection?

### ISSUE THREAD

**Issue by SamuelYvon** [intellij-rust/intellij-rust#1321]
Hello!

I was writing a little rust to learn it and I came about this:

![image](https://user-images.githubusercontent.com/12652003/26910651-28099c5e-4bd6-11e7-9cfb-d05281ae6e1a.png)

The plugin warns me that method starting with is_* is usually taking a reference to itself, but it is ignoring that a &mut self is a reference to self. 

I am unsure this is an issue, maybe this is on purpose but it seems to be that both should be valid. 

If this is an actual issue I'd love to submit a PR!

And I know this is not idiomatic rust and that I don't need a mut reference ;)

**Comment by farodin91** [comment]
I'm not sure but this should annotate. Your code doesn't need to be mutable.

Are implementing a trait?

**Comment by SamuelYvon** [comment]
I know it doesn't need to be mutable, my point is the inspection doesn't tell me that it doesn't have to be, but rather that I am not passing self into a method with a name starting with is_*, which I am.

**Comment by farodin91** [comment]
I look into the inspection https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/inspections/RsSelfConventionInspection.kt. It seems like normal behavior. The text could be a bit better. A function starting with is_* should be mutable. Or something else?

**Comment by SamuelYvon** [comment]
I think the text is fine, IMO the code should be
`SelfConvention("is_", listOf(SelfType.REF_SELF, SelfType.REF_MUT_SELF))` 
and not
 `SelfConvention("is_", listOf(SelfType.REF_SELF, SelfType.NO_SELF)),`

I fail to see why NO_SELF would be appropriate for a is_* impl method, maybe a function, so if this also checks for functions it seem ok.

I don't see any use case where you would need a mutable reference for a is_*, but I also think in case someone needs it, the message should maybe ask the user to consider why he is doing that.

**Comment by farodin91** [comment]
Same as Clippy see https://github.com/Manishearth/rust-clippy/wiki#wrong_self_convention

**Comment by matklad** [comment]
Yeah, I agree that this suggestion is a true positive! In Rust, `&T` is usually called just "reference", while "&mut T", which is used much more rarely, is called "mutable reference".
