### ISSUE TITLE
Add parameter name and type hints

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#1325]
![image](https://user-images.githubusercontent.com/873919/26964746-9f53077a-4cfb-11e7-86d5-1cee9198ec1f.png)

![image](https://user-images.githubusercontent.com/873919/26964768-b60122ae-4cfb-11e7-92f1-6241a250d361.png)

**Comment by farodin91** [comment]
Duplicated #1141

**Comment by johnthagen** [comment]
I think this was closed by #1326
