### ISSUE TITLE
Outer Comments not part of RustItem PSI

### ISSUE THREAD

**Issue by Turbo87** [intellij-rust/intellij-rust#133]
It seems that outer doc comments are not properly attached to the related `RustItem` at the moment

Example:

```rust
/// test test
fn test() {
}
```

Resulting PSI:

![bildschirmfoto 2015-11-14 um 15 49 58](https://cloud.githubusercontent.com/assets/141300/11164093/63af9e0e-8ae7-11e5-881d-f86e736a9901.png)

My plan was to extend the `DocumentationProvider` and show the doc comment contents in the help popup, but there is currently no way to get to the associated doc comments from the `RustFnItem` node.

**Comment by matklad** [comment]
A special case of this is top level `FileModItem` which should embrace all the nodes in the file, including all comments.
