### ISSUE TITLE
Go to Declaration doesn't seem to work between files

### ISSUE THREAD

**Issue by caizixian** [intellij-rust/intellij-rust#1335]
Go to Declaration works fine when jumping to some functions/variables defined in the same file, but it doesn't works when trying to jump to defined in other files, which are imported using `use` instructions.

**Comment by alexander-irbis** [comment]
I can't confirm this issue with current nightly plugin, Go to Declaration works fine for me, if declaration files (modules) and in other crates. Perhaps there are some additional circumstances.

**Comment by stellarator** [comment]
I can confirm. Interestingly it is working OK when project is opened for the first time (when **intellij-rust**'s badge is opened for the moment in the lower-right corner).

But all of the following attempts to open the project produce the same result.

OS: **Linux**
cargo: **cargo 0.19.0**
rustc: **rustc 1.18.0**
IDE: **CLion 2017.2** (tried in CLion 2017.1)
intellij-rust: **0.1.0.2058**

**Comment by andreycizov** [comment]
This seems to be triggered by some behaviour that I had not yet found. It works if I consequently restart the IDE.

Things tried:
- Restart the project with compilable code (works), then add a syntax error that should break the build. Still works.

Another part of the functionality that's not available is "jump to declaration" when the declaration is part of the macro definition, but I suppose that's expected.

You could blame this on the EAP, but this version seems to work fine with Python projects, so not sure if that could be related. 

Same here.
**OS**: OS X
**cargo**: cargo 0.21.0-nightly
**rustc**: rustc 1.20.0-nightly
**IDE**: IDEA 2017.2 EAP
**intellij-rust**: 0.1.0.2062
