### ISSUE TITLE
Add the ability to move a set of fields into a sub struct

### ISSUE THREAD

**Issue by jrmuizel** [intellij-rust/intellij-rust#1336]
e.g.

```rust
struct A {
   x: i32,
   y: i32,
   name: String
   color: Color
}
```

moves x and y into a sub struct and becomes:

```rust
struct Point {
   x: i32,
   y: i32
}

struct A {
   position: Point
   name: String
   color: Color
}
```

This is a very handy refactoring for rust code because of the ability/restriction of borrowing subfields. i.e. you can't borrow mutably borrow 'A' twice, but you could mutably borrow 'position' and 'name' at the same time.

**Comment by matklad** [comment]
We can start with a simple refactoring which only creates a new substruct, without fixing the call sites.
