### ISSUE TITLE
Nightly release channel is broken

### ISSUE THREAD

**Issue by alexbool** [intellij-rust/intellij-rust#1337]
One picture worth a thousand words
<img width="948" alt="screen shot 2017-06-13 at 10 23 29" src="https://user-images.githubusercontent.com/1283792/27070640-8a4e2dbc-5022-11e7-97e1-90b9bd6e4047.png">

**Comment by matklad** [comment]
;(

Now that we have bors, I've loosened the prepublising testing on TeamCity, and moved more checks to Travis instead. Hopefully, this is the last instance of failed nightliy.  Thanks for the report!
