### ISSUE TITLE
Dot autocompletion stops working at random

### ISSUE THREAD

**Issue by gngeorgiev** [intellij-rust/intellij-rust#1342]
Hey guys, I like the plugin but I have a weird issue. 

At random(seemingly) times the dot autocompletion stops working. All I get is the `lambda, let, match, not, par` items in the dropdown. The `::` autocompletion works fine. The only way to fix this, that I found is to delete the `.idea` folder and `Restart and clean cache`. If you help me to debug this I would maybe be able to provide more details.

OS: **Arch Linux**
cargo: **cargo 0.19.0 (28d1d60d4 2017-05-16)**
rustc: **rustc 1.18.0 (03fc9d622 2017-06-06)**
IDE: **CLion 2017.2**

Regards.

**Comment by matklad** [comment]
Okey, so there were some similar issues reported, where completion basically stops working, **in CLion**. I have absolutely no idea what might be the culprit, will try to use plugin with CLion instead of IDEA for some time...

**Comment by neonaot** [comment]
It looks like this bug has already been fixed one way or another. 
If the problem still occurs, please reopen this issue or create a new one.
