### ISSUE TITLE
Support use of rustfmt-nightly

### ISSUE THREAD

**Issue by CAD97** [intellij-rust/intellij-rust#1343]
[rust-lang announcement](https://users.rust-lang.org/t/rustfmt-releases/11357)

This plugin exposes the action `Reformat file with rustfmt`. As far as I can tell, this works by running `cargo fmt -- --write-mode=overwrite --skip-children`.

> We're also changing the parsing library used in Rustfmt from Syntex to libsyntax (because Syntex is not going to be maintained). This won't affect formatting or much else for end users, however, it means rustfmt will only work with the nightly toolchain.
> 
> [...]
> 
> Longer term, we are moving to distribute Rustfmt with the main Rust distro, so all users will be able to use libsyntax-based rustfmt.

If you have both stable and nightly compilers installed, you can install `rustfmt-nightly` with `cargo +nightly install rustfmt-nightly` and run it with `cargo +nightly fmt`, whether you are on stable or nightly at the time.

This plugin should allow the `rustfmt` action to use `rustfmt-nightly` as the previous crate will no longer be receiving updates.

Likely, this will need to be rolled into better UI-based support of using `rustfmt` as an external code formatter. The very minimum to avoid strange errors and questions is probably to catch cargo `exit code -1073741515` and display a popup that cargo failed, likely because of running a nightly-compiled cargo on stable. Alternatively, just add the `+nightly` flag to the cargo call, which should (untested) cause cargo to complain "you don't have nightly installed" if nightly is not installed. I don't think there is a solution that works on stable with current rustfmt and on stable forcing nightly with rustfmt-nightly.

Oh, and if anyone wants to set up an IDEA run configuration to run `rustfmt-nightly`, I got it working with Command: `+nightly` and Additional arguments: `fmt -- --write-mode=overwrite --skip-children`. Unfortunately, if you put `fmt` as the command and `+nightly` into the additional arguments, cargo receives `cargo fmt +nightly -- ...` which fails in some manner I don't quite understand.

EDIT: there's a box to select the build channel right next to command. Set that to nightly and have your command as fmt.

**Comment by Undin** [comment]
Looks like that it's outdated due to `rustfmt-preview`

**Comment by CAD97** [comment]
Yep, for the most part people should be using `rustfmt-preview` which works on whichever channel they've installed it on. And for those people who feel the need to use unstable configuration of rustfmt, well, I can just do what I've been doing.

**Comment by dvic** [comment]
I'm using `rustfmt-preview` on nightly, and I currently get an error:
``Unstable option (`--skip-children`) used without `--unstable-features` ``

The command that is being run is: `cargo fmt --all -- --emit=files --skip-children`

Does anyone else have this problem?

**Comment by dvic** [comment]
Probably caused by https://github.com/rust-lang-nursery/rustfmt/pull/1998

**Comment by Undin** [comment]
@dvic yeah, we know about this problem (see #2761).
It's related to recent changes about using unstable options of rustfmt.
Will be fixed in next version

**Comment by brokenthorn** [comment]
I suggested this: https://github.com/intellij-rust/intellij-rust/issues/2588#issuecomment-447016324

**Comment by CAD97** [comment]
@brokenthorn you should not be installing clippy from source anymore. You should be doing `rustup component add rustfmt`, which gives you stable `cargo fmt` as part of the toolchain distribution.

**Comment by brokenthorn** [comment]
Yes, but this needs to be clearer. Like for example add this to one of the first chapters in the book and stress the idea of proper uniform formatting.
