### ISSUE TITLE
Trying to "Go To Declaration" of webrender::RendererOptions fails

### ISSUE THREAD

**Issue by jrmuizel** [intellij-rust/intellij-rust#1346]
The declaration is here: https://github.com/servo/webrender/blob/568c727b7375961d08f0d979bd5e78b88ecde72f/wrench/src/wrench.rs#L168

Any tips for how to debug this kind of problem would be helpful too.

**Comment by Undin** [comment]
What version of plugin do you use?
I've just checked this case with the latest version of plugin (0.1.0.2104-nightly) and "Go To Declaration" works for me.

**Comment by jrmuizel** [comment]
Webrender has a workspace with a couple of subcrates. If I open the root webrender directory it works but if I instead open the wrench subdirectory/crate it does not.

**Comment by matklad** [comment]
Yep, that's definitely a bug! Although I would recommend opening the root of the workspace in IntelliJ, the IDE is better to be aware of the main Cargo.toml to handle everything correctly.

**Comment by matklad** [comment]
Hm, now I think it would actually be better if we just suggest to open the whole workspace, instead of trying to fix working with a partially opened workspace. 

@jrmuizel is there any significant reason why you prefer to open a specific member of the workspace?

**Comment by jrmuizel** [comment]
I believe when I was using vscode it worked better to open the sub crate than the whole workspace.
