### ISSUE TITLE
Basic Surrounder support

### ISSUE THREAD

**Issue by mrhota** [intellij-rust/intellij-rust#136]
Start with surrounding exprs with (). Perhaps also include a `loop{}` surrounder, too.

See [golang's `SurroundDescriptor`.](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/src/com/goide/editor/surround/GoSurroundDescriptor.java)

**Comment by Turbo87** [comment]
@matklad I guess this was resolved by #226

**Comment by matklad** [comment]
Ideally, we should have surround with `()` and `{}`. I suppose they can be handy in macros.

**Comment by Turbo87** [comment]
Do those even exist in Java?

**Comment by matklad** [comment]
Yes, not as templates, but as surround descriptors. Use `Ctrl-Alt-t` or `surround with` action to see what's available. 

@mrhota how are `()` and `{}` surrounders are used in practice? I have never used them myself =/

**Comment by mrhota** [comment]
You highlight some text, enter the key combination, and select the surround type. Nothing fancy.

**Comment by zjhmale** [comment]
i think we already have loop{} template [here](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/resources/org/rust/ide/liveTemplates/Rust.xml#L73) @mrhota
