### ISSUE TITLE
Latest plugin release not in plugins.jetbrains.com?

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#1360]
I read the recent release notes: https://intellij-rust.github.io/2017/06/17/changelog-44.html

But it doesn't look like the release was pushed up to plugins.jetbrains.com and as such I wasn't prompted to update to the latest version. Was this intentional?

**Comment by matklad** [comment]
Excellent catch! Looks like I've messed-up build numbers: https://plugins.jetbrains.com/plugin/8182-rust

**Comment by matklad** [comment]
Okey, the alpha with the correct buld number should be up soon: https://teamcity.jetbrains.com/viewLog.html?buildId=1095727&tab=buildResultsDiv&buildTypeId=IntellijIdeaPlugins_Rust_UploadAlphaRust

**Comment by matklad** [comment]
Okey, @johnthagen , alpha is up. Could you verify that everything works?

**Comment by johnthagen** [comment]
@matklad Everything is now working. PyCharm prompted me to to update the Rust plugin and the versions and dates look good.
