### ISSUE TITLE
Quick fixes on type mismatch

### ISSUE THREAD

**Issue by gilescope** [intellij-rust/intellij-rust#1362]
&str and String are part of the fun of Rust. It would be great to alt-enter on "Hello World" and to pick String::from("Hello World").

What would be super awesome would be structual search and replace that Resharper as then we could add these things in as we find them, but that's probably still a pipe dream for now!

Loving the cargo check functionallity btw - most awesome!

**Comment by matklad** [comment]
@gilescope hm, actually that's something I'd love to use as well :) 

However, I am not sure what's the most rustic way to get from `str` to `String` ... 

There are

* `"hello".to_owned()`
* `"hello".to_string()`
* `"String::from("hello")"`
* `format!("hello")`

Is there an "official" guideline for this?

**Comment by matklad** [comment]
>Loving the cargo check functionallity btw - most awesome!

It's @vasily-kirichenko's awesome work :)

**Comment by vasily-kirichenko** [comment]
I was just too annoyed to compile all the time to see the errors :)

**Comment by mkaput** [comment]
Hmm, I have quite different idea for this (but much more work to do):

What about adding annotator & quick-fix which would:
1. find usages of instances of type `A` in places where type `B` is expected and highlight them
2. determine whether `impl From<A> for B` is available
3. propose quick-fix to automatically insert `B::from(...)`

This way it would be much more intelligent behaviour

**Comment by gilescope** [comment]
Yes, really like this idea!

**Comment by johnthagen** [comment]
@matklad / @gilescope [I asked this question on the user forum](https://users.rust-lang.org/t/what-is-the-idiomatic-way-to-convert-str-to-string/12160).

Summary seems to be:
- Avoid `format!()` for something like this.
- `.to_owned()` seems to be slightly preferred due to what it semantically conveys
- Some preferred `.to_string()` for it's simplicity
- The runtime cost between `String::from()` `.to_string()` and `.to_owned()` are the same.

It seems like IntelliJ could suggest `.to_owned()` then.

**Comment by vlad20012** [comment]
@mkaput should we use `B::from` or just `a.into()` ?

(I think this feature will be E-easy very soon)

**Comment by mkaput** [comment]
Well I think it is quite context dependent :) Though 

In places where `B` can be easily determined, i.e. when destination type is explicitly provided in context, ideally we should use `.into()`. Otherwise - `B::from`.

So I think that as starting point we should use `B::from`

**Comment by vlad20012** [comment]
I've migrated it to a new issue #1730
