### ISSUE TITLE
Autoimport of missing use

### ISSUE THREAD

**Issue by msjyoo** [intellij-rust/intellij-rust#1366]
Is it possible to have autoimport of missing 'use' statements with Alt-Enter?

Right now it gives the suggestion in the error message but doesn't seem to have the auto fix option.

**Comment by matklad** [comment]
Nope, autoimport is a planned feature, but it is not implemented yet.

**Comment by matklad** [comment]
Nope, autoimport is a planned feature, but it is not implemented yet :(
