### ISSUE TITLE
"Import project" not available in pycharm

### ISSUE THREAD

**Issue by eddy-geek** [intellij-rust/intellij-rust#1368]
[Quickstart](https://intellij-rust.github.io/docs/quick-start.html) says:
![image](https://user-images.githubusercontent.com/2772505/27454704-1edb0142-579b-11e7-8627-45b70d0309a6.png)

But I have:
![image](https://user-images.githubusercontent.com/2772505/27454714-29f6f914-579b-11e7-91b7-e0ba490b50d3.png)

The tutorial should explicitely disallow pycharm or provide an alternative (use "Open"? manually edit $project/.idea/... ?)

**Comment by matklad** [comment]
Yeah, for PyCharm, `Open` should work. And totally agree that quick start guide could have a rewrite: it was written like a year ago, a lot of things have changed since then...

**Comment by Undin** [comment]
Fixed in https://github.com/intellij-rust/intellij-rust.github.io/pull/59
