### ISSUE TITLE
Support Widen Selection

### ISSUE THREAD

**Issue by gilescope** [intellij-rust/intellij-rust#1383]
Widen selection (Ctrl-W intellij keybinding) is one of my all time favorites. From the current selection or cursor it will extend the selection left and right to enclose the next logical grouping.

For example if the cursor was at <I> as you repeatly press Ctrl-W it will select the brackets (), then select the function call Client::new(), then the statement client = Client::new(), then the if and finally the function and possibly class after that (up until the whole file is selected I guess).

fn doSomething() {
 if debug {
                    client = Client::new(<I>);
                    host = "http://localhost:5000";
                }
}

For those of you who haven't tried it on other platforms, give it a go as it's a great tool to have. 

I miss it dearly, and so I'd like to put it on my christmas list.

(Loving the unelide lifetimes and make type explciit - they're great!)

**Comment by matklad** [comment]
@gilescope that's super strange, `ctrl+w` worked basically from the day one of the plugin, and it definitely works for me now.

**Comment by matklad** [comment]
So, for me it looks like this: https://zippy.gfycat.com/AdoredEagerCoral.webm

**Comment by gilescope** [comment]
My bad - CLion has some dodgy defaults. When I reset the keybindings back to "Intellij Classic" it works again. (YAY!)

This is great news!
