### ISSUE TITLE
Contributor License Agreement

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1385]
To everyone who has contributed code to IntelliJ Rust: we want to make this plugin officially supported by Jet Brains, but to do so, we need contributor license agreements signed by anyone who had added code to the plugin. If you do not wish to sign such a CLA form, let me know so that I can find a way to back out any changes you may have made.

To sign the CLA, please follow instructions at https://www.jetbrains.com/agreements/cla/. The procedure consists of a couple clicks: no need to scan or print or snail-mail anything. Comment on this issue after signing the CLA so that I can track progress easily.

The text of CLA can also be found [here](http://www.jetbrains.org/download/attachments/983565/JB_ContributorLicenseAgreement.pdf).

It's quite possible that due to recent code rewrites, your change may not appear anymore. If that is the case, I only ask that you verify this, so I can take you off of the list of people we need CLAs from.

Thank you all!

Q&A:

**Q:** Does this mean that IntelliJ Rust is becoming a closed source proprietary project of Jet Brains?

**A:** No, IntelliJ Rust plugin will be free, open source and welcoming to contributors. However it is possible that in the future Jet Brains releases a paid product based on the IntelliJ Rust technology.

**Q:** What is the purpose of CLA?

**A:** This CLA is for your protection as a Contributor as well as the protection of JetBrains and its users; it does not change your rights to use your own Contributions for any other purpose.

cc:

- [x] @alexeykudinkin
- [x] @alexpana
- [x] @allengeorge
- [x] @alobb
- [x] @alygin
- [x] @andruhon
- [x] @ashleysommer
- [x] @bgourlie
- [x] @CGavrila
- [x] @chriskrycho
- [x] @contradictioned
- [x] @d9n
- [x] @daschl
- [x] @Falkenfighter
- [x] @farodin91
- [x] @framlog
- [x] @friedroman
- [x] @greg-kargin
- [x] @himikof
- [x] @HybridEidolon
- [x] @johnthagen
- [x] @jonas-schievink
- [x] @KalitaAlexey
- [x] @Keats
- [x] @kumbayo
- [x] @la10736
- [x] @LiamClark
- [x] @Litarvan
- [x] @madisp
- [x] @mbStavola
- [x] @mcarlin
- [x] @mfarrugi
- [x] @mitchhentges
- [x] @mkaput
- [x] @mrhota
- [x] @netvl
- [x] @ninjabear
- [x] @oistein
- [x] @pavel-v-chernykh
- [x] @Shiroy
- [x] @sirgl
- [x] @slavam2605
- [x] @ThoseGrapefruits
- [x] @tigarmo
- [x] @tov
- [x] @Turbo87
- [x] @Undin
- [x] @vasily-kirichenko
- [x] @winger
- [ ] @zjhmale

Issue template take from https://github.com/jwiegley/use-package/issues/282 :)

**Comment by mkaput** [comment]
done

**Comment by farodin91** [comment]
done

**Comment by sirgl** [comment]
done

**Comment by Undin** [comment]
done

**Comment by greg-kargin** [comment]
done

**Comment by andruhon** [comment]
done

**Comment by daschl** [comment]
done

**Comment by jonas-schievink** [comment]
done

**Comment by contradictioned** [comment]
done

**Comment by mitchhentges** [comment]
done

**Comment by chriskrycho** [comment]
Done, and a hearty huzzah to this!

**Comment by KalitaAlexey** [comment]
@matklad,
I remember I did something, but I couldn't find any commits made by me.

**Comment by LiamClark** [comment]
Done!

**Comment by Keats** [comment]
done!

**Comment by vasily-kirichenko** [comment]
done.

**Comment by CGavrila** [comment]
done

**Comment by matklad** [comment]
@KalitaAlexey it was a small fix to the docs: https://github.com/intellij-rust/intellij-rust/commits?author=KalitaAlexey, so you don't need to sign the CLA then!

**Comment by ThoseGrapefruits** [comment]
done

**Comment by slavam2605** [comment]
done

**Comment by Turbo87** [comment]
done

**Comment by jeremy-w** [comment]
I'm not a contributor, but this was brought to my attention by a contributor. As I read it, [the CLA](http://www.jetbrains.org/download/attachments/983565/JB_ContributorLicenseAgreement.pdf) governs only "present and future Contributions", not past Contributions.

It seems like patches going forward should be collected alongside (present) or after (future) signed CLAs, but **owners of past contributors would need to execute a different document** to retroactively grant those rights (if they can).

IANAL, but this seems like it's stretching an existing CLA contract to cover a scenario it wasn't drafted for. If JetBrains have indicated they're A-OK with this, though, then go ahead and ignore all that – it wasn't clear from the issue whether so-and-so at JetBrains said "do this, and you're good", or whether it was an independent initiative on this project's part.

**Comment by matklad** [comment]
@jeremy-w thanks for bringing this up! I am a Jet Brains employee, and so yes, Jet Brains are A-OK with this. I am not a lawyer, but looks like section five covers past contributions:

>The rights that you grant to JetBrains under these terms are effective on the date you first submitted a contribution to JetBrains, even if your submission took place before the date you sign these terms.

**Comment by friedroman** [comment]
My change was a small doc update, so I guess you can take me off the list. https://github.com/intellij-rust/intellij-rust/commit/ee963c7107aa59b96bd9f0abe2caa5943e4c0e59

**Comment by jeremy-w** [comment]
@matklad Thanks for calling that out. It looks like similar CLA text is used all over the place, so I appreciate your help to understand this common boilerplate. It covers past contributions made to JetBrains, which they weren't made to at the time, but coupled with the retconning aspect and the transfer of ownership, that sounds like enough wiggle room to work without any problem between willing & excited participants. :) Looking forward to this going through!

**Comment by mcarlin** [comment]
done

**Comment by farodin91** [comment]
> We want to make this plugin officially supported by Jet Brains
@matklad This didn't change in near future the issue managing or?

**Comment by matklad** [comment]
@farodin91 could you reformulate your question? I am afraid I don't understand it :(

**Comment by vasily-kirichenko** [comment]
I think he asked if issues will be managed on github or will move to youtrack.

**Comment by matklad** [comment]
All issue & PR management will go through GitHub, as usual :)

**Comment by farodin91** [comment]
@matklad Sorry for my bad sentence. You answered my question.

**Comment by himikof** [comment]
done

**Comment by oistein** [comment]
done

**Comment by winger** [comment]
done

**Comment by ashleysommer** [comment]
Signed!

**Comment by mrhota** [comment]
@matklad I ran this
```
find . -name "*.java" -or -name "*.kt" -exec git blame -- '{}' ';' | grep my_name
```
and didn't get any output. I think whatever code I wrote is now rewritten, refactored, or deleted. I think you can remove me from the list.

**Comment by Falkenfighter** [comment]
Done

**Comment by farodin91** [comment]
@mrhota Here is your code refactored. https://github.com/intellij-rust/intellij-rust/commit/5ef4812704f44a266fffb3ef2702157c07729847

**Comment by framlog** [comment]
done

**Comment by pavel-v-chernykh** [comment]
done

**Comment by alexpana** [comment]
done

**Comment by madisp** [comment]
done

**Comment by ninjabear** [comment]
done

**Comment by bgourlie** [comment]
done :)

**Comment by HybridEidolon** [comment]
Done!

**Comment by kumbayo** [comment]
done

**Comment by la10736** [comment]
done

2017-07-02 10:19 GMT+02:00 Peter Oberndorfer <notifications@github.com>:

**Comment by johnthagen** [comment]
Done.

**Comment by mrhota** [comment]
done

**Comment by alexeykudinkin** [comment]
Adding my 2 cents: i don't think JetBrains CLA should be here. 

JetBrains w/o a doubt is one of the major contributors to this project (through sponsorship of one of its developers), though this project never was officially affiliated with a company, and i can hardly see why every contributor should grant those rights to anyone except the community behind it.

As an alternative, i'd like to bring into consideration two other options: 

1. Including ["lightweight" MIT CLA](https://gist.github.com/pjcozzi/4d1ab2166519de7ba41b).
2. Using [CLA assistant](https://github.com/cla-assistant/cla-assistant) (with a vendor neutral CLA, granting the rights towards the community).

**Comment by johnthagen** [comment]
Maybe JetBrains will provide complimentary licenses to the contributors for the eventual Rust IDE product 😄

**Comment by Litarvan** [comment]
done ^^

**Comment by allengeorge** [comment]
Done

________________________________

**Comment by alobb** [comment]
Done

**Comment by mbStavola** [comment]
Done!

Glad to see JB taking an interest in this wonderful project!

**Comment by matklad** [comment]
It is indeed the case that IntelliJ Rust was never an official JetBrains product. We would like to change this and to make the plugin officially supported by JetBrains. This is the reason why we are asking for a **specific** CLA, used for open source JetBrains projects.

It is also true that JetBrains sponsored the development of the plugin and that the plugin itself is build atop of open  source technologies developed at JetBrains.

**Comment by netvl** [comment]
Done.

**Comment by alygin** [comment]
Done

**Comment by mfarrugi** [comment]
done

**Comment by d9n** [comment]
Done

**Comment by zjhmale** [comment]
Done

**Comment by nicity** [comment]
https://blog.jetbrains.com/blog/2017/08/04/official-support-for-open-source-rust-plugin-for-intellij-idea-clion-and-other-jetbrains-ides/
