### ISSUE TITLE
Adding a details button in PR tests for bors.

### ISSUE THREAD

**Issue by farodin91** [intellij-rust/intellij-rust#1386]

**Comment by matklad** [comment]
@farodin91 could you expand a bit what do you want to add here? I don't quite get it now :)

**Comment by farodin91** [comment]
![screenshot from 2017-07-03 08-50-13](https://user-images.githubusercontent.com/1159212/27781122-dab536b0-5fcc-11e7-82e5-9236df5d8ed6.png)
But bors doesn't have a details button.
