### ISSUE TITLE
Allow for src or cargo project directory setup

### ISSUE THREAD

**Issue by bmsantos** [intellij-rust/intellij-rust#1390]
Some projects (e.g. [neon](https://www.neon-bindings.com/)) setup their cargo project file .toml and src directory in a subdirectory. In such cases, it would be useful to be able to do one of the following:

1. Allow users to set src directory
1. Allow for the setup of cargo project directory (the one with .toml) and assume that src exists in it
1. Have the plugin automatically look for the .toml file and apply same assumption as in previous point

**Comment by matklad** [comment]
Yeah, we definitely need something like this, though it is not obvious, how to implement it in a cross-ide way :( 

For IDEA, the current workaround is to open the root project in the IDE, and then add a subdirectory as a module (`cltr+alt+shift+s`, modules, **+** button, import module).

**Comment by bmsantos** [comment]
Yes, that a solution for IntelliJ IDEA. Unfortunately, I'm using JetBrains's CLion with Rust since it offer native debugger that works with Rust..

**Comment by matklad** [comment]
This was implemented in the latest release: https://intellij-rust.github.io/2017/10/02/changelog-53.html
