### ISSUE TITLE
Mutability can aid auto-completion

### ISSUE THREAD

**Issue by gilescope** [intellij-rust/intellij-rust#1409]
I'm in two minds on this one.

If you have a non-mutable variable, then the methods that are auto-completed should be subset to only show methods that take a non mutable self.

Alternatively one could show the mutable versions, but if a mutable method was selected one could change the var definition to be a 'mut'. This would be more 'flow', I worry the former may be a gotcha.

Thoughts?

**Comment by mkaput** [comment]
I think instead of hiding we could apply some colouring to mutable methods in immutable context
