### ISSUE TITLE
Hovering to show variable type doesn't work

### ISSUE THREAD

**Issue by jrmuizel** [intellij-rust/intellij-rust#1413]
Even though this feature was added, it doesn't seem to work for me in Intellij 2017.1.4

**Comment by matklad** [comment]
![hover](https://user-images.githubusercontent.com/1711539/27817872-e92c55e6-609b-11e7-8019-ae5835098583.png)

Seems to work here. Do you hold `ctrl` key when hovering?

**Comment by jrmuizel** [comment]
Ah, if I hold down Command on OS X I get types. I didn't know that you had to hold down a key.

**Comment by matklad** [comment]
Glad that it works for you now! Closing the issue then!
