### ISSUE TITLE
Dead-code lint: don't underline the entire item's text

### ISSUE THREAD

**Issue by abonander** [intellij-rust/intellij-rust#1415]
I love the new `cargo check` integration, but the highlighting for `dead_code` goes a little overboard:
![dead-code lint overzealous highlighting](https://user-images.githubusercontent.com/3198595/27819176-d2c8918c-604d-11e7-9521-0ec6d93f3972.PNG)

If it's possible to grey-out and underline the item name like the built-in "Unused declaration" inspection, that'd be most helpful.

**Comment by matklad** [comment]
Yeah, the right approach here I think is to make `rustc` to return a smaller span here, but short term I think we should remap it in IntelliJ.
