### ISSUE TITLE
Create a module file via quickfix

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#142]
Suppose I have a declaration like `mod foo;`, but I don't have `foo.rs` or `foo/mod.rs`. In this case, I want
  
  * `mod foo;` to be annotated as error,
  * a quick fix "Create module file".

The quick fix should create `foo.rs` and bring the editor to it. 

I think this should be the preferred way of creating a new Rust file. 

This method can be used to resovle mod decl to a file: https://github.com/alexeykudinkin/intellij-rust/blob/master/src/org/rust/lang/core/psi/util/RustModExtensions.kt#L40

**Comment by pavel-v-chernykh** [comment]
@matklad @Turbo87 If you don't mind I would like to pick that task

**Comment by matklad** [comment]
And don't forget to add a word about it to `Usage.md` :)

**Comment by pavel-v-chernykh** [comment]
@matklad got it :smirk:

**Comment by Turbo87** [comment]
we could also include:

- quick fix: "Create inline module"
- quick fix: "Create module folder"

**Comment by matklad** [comment]
"create inline module" is useless imo, it just changes `;` to `{}`. 

"Create module folder" can be useful, but I argue that we should go without it here. As I said, this quick fix should be the primary way of creating a Rust file, so it is better not to have extra options and key presses here. 

If you want a module folder, you should invoke this quick fix to get module file and then invoke the intention to change the file into `mod.rs`.
