### ISSUE TITLE
Result of indexing a vec given wrong type

### ISSUE THREAD

**Issue by jrmuizel** [intellij-rust/intellij-rust#1420]
Given the following code:
```rust
let x: Vec<u32> = vec![1, 2];
let a = x[0];
println!("food  {}", a);
```
the type of a should be u32. Intellij gives &u32.

**Comment by Undin** [comment]
No, it's not true.
Index operation returns reference at inner object because it's only borrowed without copying.
Implementation of the index operation for `Vec` in rust 1.18 stdlib is presented below:
```rust
impl<T> Index<usize> for Vec<T> {
    type Output = T;

    #[inline]
    fn index(&self, index: usize) -> &T {
        // NB built-in indexing via `&[T]`
        &(**self)[index]
    }
}
```

**Comment by Undin** [comment]
Indeed:)
