### ISSUE TITLE
Reference in 'for in' loop erases types

### ISSUE THREAD

**Issue by jrmuizel** [intellij-rust/intellij-rust#1430]
In the following code e is resolved as (&K, &V) instead of (&u32, &u32)

``` rust
        let h: HashMap<u32, u32> = HashMap::new();
        for e in &h {
            e
        }
```

However, if we drop the reference on 'h', e is properly resolved to (u32, u32)
```rust
        let h: HashMap<u32, u32> = HashMap::new();
        for e in h {
            e
        }
```

**Comment by farodin91** [comment]
I looked into it this problem, but looks like a huge problem. Erases of references and type parameter.
