### ISSUE TITLE
Errors in tests are not shown

### ISSUE THREAD

**Issue by orium** [intellij-rust/intellij-rust#1433]
The new `cargo check` feature does not show errors in tests (under the attributes `#[cfg(test)]`/`#[test]`).

**Comment by matklad** [comment]
This is waiting for https://github.com/rust-lang/cargo/pull/4039 on Cargo's side of things.

**Comment by orium** [comment]
rust-lang/cargo#4592 was merged.

**Comment by orium** [comment]
This is now available in stable cargo.  We can call `cargo check --tests --benches`.
