### ISSUE TITLE
Cargo check lints always use stable

### ISSUE THREAD

**Issue by torkleyy** [intellij-rust/intellij-rust#1447]
I'd like to work on a nightly project, is there some way I can make the lints work with nightly?

**Comment by matklad** [comment]
If you are using rustup, doing something like `rustup default nightly` or (in the project directory) `rustup override add nightly` should do the trick: we use whichever toolchain version rustup itself uses.

**Comment by torkleyy** [comment]
Ah right, makes sense. Didn't come to my mind. Thank you!
