### ISSUE TITLE
display function-parameter-hints automatically

### ISSUE THREAD

**Issue by dobkeratops** [intellij-rust/intellij-rust#1450]
At the moment you can get function-parameter information with CMD-P(mac), could an option be added for this to appear automatically on typing an open-parentheses after an alphanumeric ;

it might even be useful to display this in the modelling (or tooltips?) when browsing code as this will give you a lot of insight into whatever you're looking at.

I understand there might be issues with precision (over/underestimates of the available functions). Personally I have adopted 'intermediate naming schemes '(halfway reverting from c++ to c practices) to make raw text-searches more useful .. as such in my own sourcebase, an 'overestimate' would be fine.   (e.g, I use raw 'glFunctions' rather than the rust naming convention; i will probably do this with other C apis .. in the case where the world has a very common 2-letter prefix , i am ok forgoing the modern namespacing. I also have a tonne of my own functions designed to be found by easy text-based autocomplete)

**Comment by matklad** [comment]
You can configure IDEA to automatically show Parameter Info after a certain (possibly zero) delay. Quite confusingly, the relevant checkbox is buried in the code completion settings: 
![param_hits](https://user-images.githubusercontent.com/1711539/27988124-23f532a8-6423-11e7-8958-9684a08e73b0.png) :) 

There's a bug though that we don't automatically show parameter info after `()` are inserted in code completion. 

>it might even be useful to display this in the modelling (or tooltips?) when browsing code as this will give you a lot of insight into whatever you're looking at.

This will be handled by #1326 once we drop support for 2016.3, which does not support the feature.

**Comment by matklad** [comment]
Now autopopup correctly works after autocompletion: https://zippy.gfycat.com/CreativeUnawareHarpyeagle.webm
