### ISSUE TITLE
chroma coding: parameter vs type, display differently by default?

### ISSUE THREAD

**Issue by dobkeratops** [intellij-rust/intellij-rust#1451]
at the moment in the default colour schemes (I see a light and dark theme option out of the box), the Rust environment shows the parameters and types the same colour; especially with the ':' character this can make signatures hard to read (which is especially difficult in Rust because the signtures can be quite busy); 

IMO it would be a great help if the default schemes distinguished these, even if it was just a subtle shift in greyscale.

(perhaps the easiest piece of chroma coding to apply is the argument name, since it is extractable by regex as 'an alphanumeric string followed by :'
I think this is what the Rust emacs extention does by default - if in doubt following this scheme would be ok)

**Comment by matklad** [comment]
Hello @dobkeratops !

You can configure coloring for parameters via settings (`ctrl+alt+s` > Editor > Colors & Fonts > Rust):
![parameters](https://user-images.githubusercontent.com/1711539/27987973-d61fc636-641f-11e7-84fd-fd6da4cc8bd9.png).

For default colors, we just inherit values from the platform, and they use the same color for function parameters and names of types. 

>since it is extractable by regex as 'an alphanumeric string followed by :'

Unlike Emacs, in IntelliJ we have a full 100% percent precise syntax of Rust,  so we don't use regexpes for highlighting, and highlight parameters directly: https://github.com/intellij-rust/intellij-rust/blob/e3aa1e1c4871c80b1478ba06a06c5b73767e5d2e/src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt#L97 :)

**Comment by matklad** [comment]
Closing this as it seems like IntelliJ already support this feature :)

**Comment by dobkeratops** [comment]
hi thanks for the info, this helped readability a lot.

I would still make a couple of further requests:
[1] adjust the defaults, just change the hue of the 'parameters' a little (this will help other users)
[2]  add a few more cases:-
- and the name of a declaration : fn function name(..) ,  struct StructName{}   , trait TraitName {}. Call these 'declarations' perhaps;  highlighting 'functions','structs','traits' refers to their uses aswell.
- the 'type-parameter angle brackets' differently, 
-and the 'scope resolution operator ::' differently to other operators (default to operator of course)

[3]  Now this would be really special:
https://www.reddit.com/r/emacs/comments/6huzuq/is_there_an_extention_to/

ability to do unicode substitution of type-parameter brackets, e.g. displaying the type-parameter brackets as an actual unicode angle-bracket distinct from the 'greater-than' / 'less-than' symbols.
fn foo⟨T⟩(a:&Vec⟨T⟩)->Option⟨T⟩

I'm sure users of other C-like languages would appreciate this feature.
