### ISSUE TITLE
Refactoring module name removes `.rs` extension

### ISSUE THREAD

**Issue by torkleyy** [intellij-rust/intellij-rust#1453]
Using latest plugin release, `0.1.0.2061`, IntelliJ IDEA `2017.1.5`.

So I renamed the module declaration in my `main.rs` file from `mod foo;` to `mod bar;`. This refactoring renamed `foo.rs` to `bar` (without extension).

**Comment by matklad** [comment]
Files are now renamed correctly, but looks like directories (`foo/mod.rs`) don't work really great yet.

**Comment by Kobzol** [comment]
@ortem I checked both of these situations:
1) `a/b.rs` -> renamed `a::b` to `a::c` -> `a/c.rs`
2) `a/mod.rs` -> renamed `a` to `b` -> `b/mod.rs`
and both of them seem to work in `master`.

So I think that this issue can be closed.

**Comment by ortem** [comment]
@Kobzol OK, thank you!
