### ISSUE TITLE
Lifetimes can be multiple characters

### ISSUE THREAD

**Issue by abonander** [intellij-rust/intellij-rust#1458]
The parser implementation seems to assume lifetimes can only be one character:

![crop lifetime multiple chars](https://user-images.githubusercontent.com/3198595/28051843-ef6893f0-65bb-11e7-8e35-6a9818a1b3bb.png)

This is, of course, incorrect, as lifetimes can be any identifier. Unfortunately, the Rust grammar reference is still [highly anemic](https://doc.rust-lang.org/nightly/grammar.html#types), so I don't have a citation for this. But the parser should at least accept `'static`.

**Comment by abonander** [comment]
Nevermind, I just got the most recent plugin update and it seems this was silently fixed. Nice.

**Comment by mkaput** [comment]
Do you remember from which version have you updated?

We always have supported multicharacter lifetimes, and this error is result not of our parser but one of our annotators. I think it could be some glitch.

**Comment by abonander** [comment]
Sorry, I didn't check. I think I've been keeping it up-to-date, so probably the July 3rd release.

**Comment by abonander** [comment]
Actually, it's doing it with the current release now. It seems to happen when a type definition with a valid single-character lifetime is rewritten to `'static`, but I haven't been able to consistently reproduce it on the same line.

**Comment by mkaput** [comment]
I did some quick research, and this message comes from `cargo check` not from intellij rust itself
