### ISSUE TITLE
Implement function move up or down with step over function

### ISSUE THREAD

**Issue by farodin91** [intellij-rust/intellij-rust#1459]
Would like to implement it?
@matklad Any suggestions to start?

**Comment by matklad** [comment]
Is this about moving functions with `Ctrl+Shift+Up/Down`? I would **love** to have that! Not sure what extension points are relevant here, but there's `MethodUpDownUtil` in IntelliJ IDEA, which sounds like it might be an entry point to this stuff.

**Comment by farodin91** [comment]
Yes is about moving functions with Ctrl+Shift+Up/Down.

**Comment by farodin91** [comment]
MethodDownHandler in java could the function
