### ISSUE TITLE
Latest Commits broke "Create Project"

### ISSUE THREAD

**Issue by schmitch** [intellij-rust/intellij-rust#146]
Hello, with the latest PR's I can't press the 'create project' button

**Comment by schmitch** [comment]
@matklad  Is there a good way to debug a plugin? inside intellij?

**Comment by matklad** [comment]
You can just place a breakpoint and run the plugin (`execute gradle task > runIdea`). It will be just a usual debugging.

**Comment by schmitch** [comment]
wow i dindn't knew that I could run the plugin directly, thanks!

**Comment by matklad** [comment]
Hm, let me reformulate.

I don't know a good way to debug a plugin installed in IDEA via `install plugin from disk`.

But If you open plugin source code in IDEA and launch it (thus getting the second instance of IDEA running) you use usual debugging tools.

**Comment by matklad** [comment]
>wow i dindn't knew that I could run the plugin directly, thanks!

It would be great if you file a PR with updates to [CONTRIBUTING.md](https://github.com/alexeykudinkin/intellij-rust/blob/master/CONTRIBUTING.md#idea)

It is hard to write a good getting started thing if you already know how to start :)

**Comment by schmitch** [comment]
oh I will, however with intellij most things are really really easy. especially when there are predefined gradle tasks..
