### ISSUE TITLE
Improve Derive attribute compltion

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1465]
We have special cased completion for `derive` attribute

```
#[derive(|)]
struct S {
}
```

it suggests stuff like `Clone`, `Eq`, etc. I think it can be improved a little:

1) add suggestion to add `Clone, Copy`: this is a very often combo

2) the same for `PartialEq, Eq` combo.

3) remove suggestions for `RustcSerialize`, as it is superseded by serde.

The code is here:

https://github.com/intellij-rust/intellij-rust/blob/3c948dd52b61a6e537b0465a29e64326e48ec397/src/main/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProvider.kt

The tests are here:

https://github.com/intellij-rust/intellij-rust/blob/3c948dd52b61a6e537b0465a29e64326e48ec397/src/test/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProviderTest.kt

**Comment by Undin** [comment]
compltion -> completion :)
