### ISSUE TITLE
make cargo command configurable (xargo support)

### ISSUE THREAD

**Issue by dsvensson** [intellij-rust/intellij-rust#1477]
make cargo command configurable so that xargo can be used instead when dealing with embedded projects.

https://github.com/japaric/xargo

It might be interesting to perhaps default to this if a Xargo.toml exists.

xargo should be 100% compatible with cargo commands according to its documentation and I haven't found any issues either.

**Comment by jonas-schievink** [comment]
:+1: This would make intellij-rust extremely useful for embedded development since it's surprisingly difficult to add arbitrary commands to IntelliJ.

**Comment by jonas-schievink** [comment]
Turns out it's pretty easy when you shamelessly abuse the Bash configuration:

![screenshot-31 08 2017-30 07](https://user-images.githubusercontent.com/1786438/29946147-758647dc-8ea4-11e7-8e49-3c3776080b84.png)

(yes, it works despite the error)

**Comment by idubrov** [comment]
What I did, I created `xbin` directiory inside `~/.cargo` and linked all binaries from `~/.cargo/bin` into `~/.cargo/xbin` except `cargo` itself, which I linked to `xargo`. Then, I set `~/.cargo/xbin` as a toolchain location and here we go!

**Comment by sanmai-NL** [comment]
> Turns out it's pretty easy when you shamelessly abuse the Bash configuration:
> 
> ![screenshot-31 08 2017-30 07](https://user-images.githubusercontent.com/1786438/29946147-758647dc-8ea4-11e7-8e49-3c3776080b84.png)
> 
> (yes, it works despite the error)

This does not work for me, it does not support highlighting and clickable paths in the output console.
