### ISSUE TITLE
Integrate Intellij test window into rust

### ISSUE THREAD

**Issue by farodin91** [intellij-rust/intellij-rust#1485]
@matklad I would like to implement this feature. What interface do i need to implement?
![screenshot from 2017-07-18 09-30-25](https://user-images.githubusercontent.com/1159212/28305429-ee56bd94-6b9b-11e7-9c4c-cea50bf2dd65.png)

**Comment by mkaput** [comment]
I tried to implement this in #1029 , but unfortunately Rust test doesn't produce parseable output which could be easily consumed by IntelliJ. Ideally, firstly someone should implement different output frontends in libtest.

**Comment by farodin91** [comment]
@mkaput I could use your PR to a start. and build a behind an interface, to support easy replace of the different libtest frontend.

**Comment by mkaput** [comment]
👍 

But take into account @matklad suggestions :)

**Comment by farodin91** [comment]
@mkaput Do you there is any open issues to implement different frontends for libtest?

**Comment by mkaput** [comment]
Sincerely I have no idea whether such one exist :(

**Comment by farodin91** [comment]
I will open an issue
