### ISSUE TITLE
Support rust 1.19

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#1491]
Rust 1.19 is [released](https://blog.rust-lang.org/2017/07/20/Rust-1.19.html) :tada::tada::tada:.

So I think we should support next features:
- [x] CI builds with rust 1.19
- [x] numeric fields for tuple structs
- [x] unions
- [x] loop expressions
- [x] `eprint!` and `eprintln!` macros

**Comment by farodin91** [comment]
eprint! and eprintln! should work

**Comment by Undin** [comment]
Yes, auto completion and type inference should work at this moment. But we can know a little bit more about structure of these elements that can be useful in some other plugin features, for instance, #1490

**Comment by farodin91** [comment]
https://github.com/rust-lang/rfcs/pull/1506

**Comment by Undin** [comment]
Oh, it's the first feature of this release I've known.
I've forgotten about it.
Thanks a lot!
