### ISSUE TITLE
Support shorthand field init

### ISSUE THREAD

**Issue by farodin91** [intellij-rust/intellij-rust#1494]
https://github.com/rust-lang/rust/issues/37340

**Comment by farodin91** [comment]
This feature is stable since 1.17.

**Comment by farodin91** [comment]
@Undin Isn't this already fixed?

**Comment by Undin** [comment]
Hm, we support this feature syntactically and have the inspection to use field init shorthand when it's possible. Although we still resolve shorthand to field instead of variable (#1593), I think this issue can be closed

**Comment by Undin** [comment]
@farodin91 Thanks!
