### ISSUE TITLE
Gutter test icons for modules that contain tests

### ISSUE THREAD

**Issue by la10736** [intellij-rust/intellij-rust#1503]
It would be nice if we can provide a gutter icon to start test for modules too. On thinking about that I found that is little bit hard to find a good definition of what modules should have this icon and what not.

If we just say that every module that contains at least one test should have the test icon we will fall often in the cases where all modules have test icon (at least in my projects).

A pragmatic definition for _test module_ could be:
1. A module `test` or `tests` annotated by `#[cfg(test)]` that contain at lest a test function
2. A module contained in a _test module_ that have at least a test function
3. Have a test function means that the test function is in the module or in any of its submodules

Any thought?

If you are ok I can implement it.

**Comment by alygin** [comment]
It would be great to have such an icon. But I think in practice, only the point 1 seems reasonable to implement. In other cases, you usually don't have a line to put the icon on. I mean, modules are usually files and I can't recall seeing a nested module that is not fully devoted to tests (and thus having the `#[cfg(test)]` attribute) but containing individual test functions.

In other languages, when the whole file is a test module, we usually have a file context menu item to run tests, not a gutter icon. But that would be a separate feature.

**Comment by la10736** [comment]
@alygin 1, 2, 3 describe a recursive algorithm and not some possibility. Even when the module are file you have a line like
```rust
mod foo;
```
that include it.

Maybe is better to write an example:

`lib.rs`

```rust
mod out_no_test;

#[cfg(test)]
mod tests {
    #[test]
    fn foo_fn() {}
    mod inner_test {
         #[test]
         fn inner_test_fn()  {}
    }
    mod inner_no_test {
    }
    mod inner_file_test;
    mod inner_file_no_test;
}

mod no_test {
    fn some() {}
}
```
`inner_file_test.rs`
```rust
#[test]
fn bar() {}
```

Finally `inner_file_no_test.rs` doesn't contains any test function;

In this case we following gutter test icon on the mod lines:

* `tests`
* `inner_test`
* `inner_file_test`

Of course there are a lot of other corner cases that this example doesn't expose but I hope it is clear enough.

I'm using a lot of nesting in my tests because I find namespace a good way to group test topics and I can specialize the fixtures

**Comment by alygin** [comment]
> Even when the module are file you have a line like `mod foo;`

Ah, that's what you mean. Yeah, I think it makes sense.

**Comment by farodin91** [comment]
I would start with marking inner mods with a #[cfg(test)], because for me the use case is to run test for i'm working on.

**Comment by la10736** [comment]
@farodin91 I think we can split it in some PR by starting from the simpler and most important one.
Just a note, take care of both `test` and `tests` attributes. Thank you very much... I've no much time to spend on it.

**Comment by farodin91** [comment]
@la10736 What do you think?

**Comment by la10736** [comment]
@farodin91 Sorry I lost the ping... That solution is ok.
