### ISSUE TITLE
.iml files constantly shuffled

### ISSUE THREAD

**Issue by nathanaeljones** [intellij-rust/intellij-rust#1507]
intellij-rust shuffles the order of library entries in all .iml files, which is havoc with version control. I.e, this is shuffled:

```
    <orderEntry type="library" name="Rust &lt;imageflow&gt;" level="project" />
    <orderEntry type="library" name="Cargo &lt;imageflow&gt;" level="project" />
```

Also, `.idea/libraries/*.xml` have psudeorandom ordering of entries, which could be prevented by sorting. Both issues appear to stem from the same page of code:

https://github.com/intellij-rust/intellij-rust/blob/6e996235bd63597afeee1304553d1ef53f3fe1ca/src/main/kotlin/org/rust/cargo/project/workspace/LIbraryUtil.kt#L96-L117

**Comment by matklad** [comment]
This should be fixed by https://github.com/intellij-rust/intellij-rust/pull/1596. After it, we won't be recording any libraries into plugin.xml at all.
