### ISSUE TITLE
Use Java 7 for faster Travis CI builds

### ISSUE THREAD

**Issue by Turbo87** [intellij-rust/intellij-rust#151]
I really don't know why, but it seems that using Java 7 significantly speeds up the build times. Since we are using Kotlin we don't need any of the Java 8 features and this should be an easy change.

**Comment by matklad** [comment]
I think it is better not to special case CI builds.

**Comment by matklad** [comment]
We've switched to Java 6 https://github.com/intellij-rust/intellij-rust/commit/96967c10b118a75bacb20c2c9b253093ef9da9a8

**Comment by alexeykudinkin** [comment]
Yeah, but we've made it for a while: until IDEA 16 hits release, after that we'd soft-drop it (altogether with the support of IDEA 14)
