### ISSUE TITLE
Fix build failure

### ISSUE THREAD

**Issue by farodin91** [intellij-rust/intellij-rust#1510]
https://ci.appveyor.com/project/matklad/intellij-rust/build/1.0.2284
#1505

**Comment by la10736** [comment]
```
org.rustSlowTests.RsCargoCheckAnnotatorTest > test don't report syntax errors from cargo check FAILED
    java.lang.IllegalStateException: Expected:
    cannot find value `bla` in this scope
    '!', '&', '(', '::', ';', '[', '^', '{', '|' or '}' expected, got 'bla'
    '!', '&', '(', '::', ';', '[', '^', '{', '|' or '}' expected, got 'bla'
    <pat> expected, got ':'
    Got:
    cannot find value `bla` in this scope
        at org.rustSlowTests.RsCargoCheckAnnotatorTest.test don't report syntax errors from cargo 
```

I just dig it a little bit: what is missed in the output are the annotations that comes from syntax highlight but cargo check annotator do its job (produce 4 annotation and filter 3 of them).
Now syntax annotator should add again 3 other entries (slightly different from the _cargo check_ ones) but there are no trace about them.

**Comment by vlad20012** [comment]
Just fixed somewhere (failed to find the particular commit)
