### ISSUE TITLE
[feature] Please add an option to turn off errors highlighting

### ISSUE THREAD

**Issue by e-oz** [intellij-rust/intellij-rust#1513]
Looks like every few seconds plugin runs "cargo check" in background to find errors and highlight them in code. When size of the project is not small, it leads to false error messages (code is changed already about a minute ago but error is still highlighted), less responsive navigation and autocomplete, and, maybe not so critical, but still: waste of laptop battery. Most annoying thing is huge amount of red lines everywhere when I just write new code.

For me most important things your plugin gives is navigation and code completion - I think these things can work even without endless errors checking. 

Currently there is setting "Use cargo check to analyze code" in Preferences, but unchecking it doesn't give desired effect - plugin is still checking for errors (maybe with some other tool). For non-small codebases, running "cargo check" after all changes are made, is a more comfortable way.

I'm not asking to turn it off by default, just please add an option.

**Comment by vlad20012** [comment]
There is an option:
![image](https://user-images.githubusercontent.com/3221931/28614752-89a3037a-71ff-11e7-8b11-b708ab94290d.png)

**Comment by vlad20012** [comment]
Hmm, if you turn off "Use cargo check to analyze code", only internal Intellij-Rust analysis will be used. Currently it is mostly syntax errors. It should be fast. Please check it. It cargo check is still work after "Use cargo check to analyze code" unchecking, it is a bug. But I could not reproduce it.

**Comment by e-oz** [comment]
@vlad20012 I'm "checking" it every day and it's a very very slow check. I wasn't sure how plugin is checking it, "cargo check" was just an assumption, because it takes same time to run cargo check and to wait while errors highlights will be removed after changes.

So my ask can be rephrased: please add an option to turn off internal errors check, to leave only autocompletion and navigation.

**Comment by vlad20012** [comment]
Internal analysis should be as fast as autocompletion/navigation. If you see outdated error highlights, it is likely cargo check. To be sure it is cargo, May be you can check your process list for cargo wasting lot of CPU while you typing? 

Maybe someone other have the same issue (cargo check still works after it was disabled)

**Comment by mkaput** [comment]
> Internal analysis should be as fast as autocompletion/navigation.

More, internal analysis is crucial part of autocompletion/navigation.

@e-oz try to manually turn off any Rust inspections in settings, maybe this helps.

And you can always eventually turn off Hector Inspector (that funny guy on the status bar on right) but this will kill any intelligence.

**Comment by e-oz** [comment]
Well, without navigation it doesn't worth to try. Ok, hope Apple will release more powerful laptops next time :)

**Comment by matklad** [comment]
I think we can move some of errors from error annotator into inspections, to avoid some false positives, and it's definitely time to revisit our performance benchmarks: recently, I've found a rather stupid performance leak which hopefully I'll push a fix for soon :)

**Comment by matklad** [comment]
And as for Cargo check annotator, I am leaning towards disabling it by default: it definitely makes working with largish projects miserable :(

**Comment by neonaot** [comment]
Since most Rust code analyses implemented as inspections and Cargo check is disabled by default in favor of built-in code insight, I think this issue can be closed.
