### ISSUE TITLE
Add Autocomplete

### ISSUE THREAD

**Issue by schmitch** [intellij-rust/intellij-rust#152]
Hello, there doesn't seems to be a ticket for autocomplete, so I will raise one.

Currently it would be great if intellij-rust would have a good autocomplete. I'm not sure if rust-racer is good enough for this job, but I think using it would greatly help this plugin to get more users.

**Comment by matklad** [comment]
Autocomplete is definitely on the road map, but it will **not** be implemented via racer. The reason is that IntelliJ IDEs build a complete AST for the program and implement intelligent features (including auto complete) via static analysis of the tree. So external tool support might be beneficial at the start, but in the long term it is a waste of effort. 

At the moment almost all machinery for completion of local variables and items is in place, so it will be ready soon. Type guided completion of fields and methods will take some more time :)

**Comment by schmitch** [comment]
That sounds awesome.
Hm. I tried racer and it was not better than using a editor, so it's really great that intellij will have a good autocompletion for rust ;)

**Comment by fischmax** [comment]
Oh I'd really love that ♥♥♥

**Comment by daschl** [comment]
How will autocompletion be handled for both the stdlib functions as well as ones that are pulled in via cargo dependencies? 

On that note, it would be great if intellij could pull in the rustc-src as well as the sources via cargo?

**Comment by matklad** [comment]
>How will autocompletion be handled for both the stdlib functions as well as ones that are pulled in via cargo dependencies?

To autocomplete names from external crates and stdlib we need some support from cargo, which is [under way](https://github.com/rust-lang/cargo/pull/2196).

**Comment by daschl** [comment]
@matklad I understand how cargo helps with external crates, but stdlib is not pulled in through cargo? I think for java it just pulls in the JDK directly, so maybe it could be done the same way?

**Comment by matklad** [comment]
>I think for java it just pulls in the JDK directly, so maybe it could be done the same way?

Yes, we need some sort of a solution here, but I don't know how exactly we should handle it. 

* rust distribution includes only binary version of stdlb (rlib and so)
* to my knowledge, there is no official way to download stdlib sources

Maybe we should cooperate with cargo somehow, i.e. `cargo` can have a command to pull sources of standard library. Maybe we should parse `rlib`s. Maybe we should ask `cargo` to present info from rlibs in a stable text format. I've asked about it in this [comment](https://github.com/rust-lang/cargo/pull/2196#issuecomment-168494478).

**Comment by daschl** [comment]
@matklad hm, actually the sources are available for download which include the sources (https://static.rust-lang.org/dist/rustc-1.5.0-src.tar.gz) .. this is how racer needs it as well.

**Comment by matklad** [comment]
Thanks! Didn't know about that

**Comment by matklad** [comment]
Was closed by #205

**Comment by schmitch** [comment]
@matklad that looks not working, currently:
I get:
```
22:02:21 KotlinNullPointerException
         Error while indexing /usr/local/src/rustc-1.5.0/src/libcore/fmt/mod.rs
         To reindex this file IDEA has to be restarted
```

And then the index process hangs at:
/usr/local/src/rustc-1.5.0/src/test/run-pass/super-fast-paren-parsing.rs

**Comment by matklad** [comment]
@schmitch this is unrelated to autocompletion. I'm not 100% sure, but looks like it is the same as #199 .
