### ISSUE TITLE
More intelligent hints

### ISSUE THREAD

**Issue by alygin** [intellij-rust/intellij-rust#1524]
Having [inlay parameter hints](https://github.com/intellij-rust/intellij-rust/pull/1326) is cool, but sometimes it can bee quite annoying. In mature languages, this feature uses additional rules to hide hints when they are redundant. I don't know all the rules, but here're a few that are obvious:

1. Local variable that is passed as an argument, has the same name as the parameter:

<img width="245" alt="screen shot 2017-07-28 at 09 47 11" src="https://user-images.githubusercontent.com/2101250/28705741-d948f7ec-7379-11e7-8373-04882011b0de.png">

2. There's a single parameter (not counting `self` in methods) and its name matches the function's name:

<img width="145" alt="screen shot 2017-07-28 at 09 52 20" src="https://user-images.githubusercontent.com/2101250/28705894-80b2f9f6-737a-11e7-904f-de246fb7dc7e.png">

3. Functions that start with `set_` and have single parameter (not counting `self` in methods):

<img width="172" alt="screen shot 2017-07-28 at 09 55 25" src="https://user-images.githubusercontent.com/2101250/28706001-ead537a4-737a-11e7-967e-a2e9c45008b3.png">

In all these cases hints could be safely omitted.

**Comment by farodin91** [comment]
I like the idea of intelligent hints, but I would prefer to be able to switch between all and intelligent hints.

**Comment by alygin** [comment]
Here's the exact rules that Java uses (they can be found in "Show parameter name hints -> Configure... -> Java") setting:

- White list of name patterns (a couple dozens by default, customizable)
- Do not show if method name contains parameter name
- Show for non-literals in case of multiple params with the same type (off by default)
- Do not show for builder-like methods
