### ISSUE TITLE
Contributor License Agreement

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1526]
@d9n @zjhmale: we would like to make this plugin officially supported by JetBrains, and are collecting CLAs from all our awesome contributors! This happens in https://github.com/intellij-rust/intellij-rust/issues/1385, but looks like some notifications were not delivered because of the GitHub notification limit :) 

So please see https://github.com/intellij-rust/intellij-rust/issues/1385 :)

**Comment by zjhmale** [comment]
Hi @matklad Sorry for the big delay, I'm quite busy and not get online for months. Yeah, I will do the CLA ASAP, sorry for introducing this trouble 😅

**Comment by matklad** [comment]
Thanks @zjhmale !
