### ISSUE TITLE
Split TOML package into separate plugin

### ISSUE THREAD

**Issue by dlsniper** [intellij-rust/intellij-rust#153]
Hi,

As TOML is useful for others as well, not just for RUST, I would like to propose splitting the package into it's own plugin as it would make it reusable by others.
Thank you for your time and consideration.

**Comment by dlsniper** [comment]
P.S. I could also split out the TOML part myself but I guess it would be better (for lack of proper words) to be split by you (or someone else from JetBrains).

**Comment by alexeykudinkin** [comment]
Hi, @dlsniper! That's definitely in the list.

**Comment by Turbo87** [comment]
that is part of the reason why I think #111 makes sense

**Comment by matklad** [comment]
wow: https://github.com/stuartcarnie/toml-plugin

**Comment by alexeykudinkin** [comment]
Fixed: https://github.com/intellij-rust/intellij-toml
