### ISSUE TITLE
Structure view is not updated

### ISSUE THREAD

**Issue by alygin** [intellij-rust/intellij-rust#1539]
The Structure tool window doesn't update its content when the source code is changed. It seems that something broke long ago &mdash; I've got a setup with the 0.1.0.1668 (Feb 20) plugin version, the problem was already present.

I've tracked the structure tree update routine down to [this line of code](https://github.com/JetBrains/intellij-community/blob/97ba5bc54ac3657f785c5ba65992435c88937cdb/platform/lang-impl/src/com/intellij/ide/impl/StructureViewWrapperImpl.java#L195). Here, `value` is our file, but it always returns `true` from `isValid()`, hence rebuild is never triggered. I only found one commit that changed something significant in the structure view: 734406c5350ebbd66504f0844f67e80add2b3a44. But reversing it doesn't fix the problem.

**Comment by alygin** [comment]
I think it might be caused by some of the forced change commits that we do here and there, but commenting them out didn't help either. Though, I'm not sure I found all the places.

**Comment by matklad** [comment]
Thanks for investigation @alygin ! 

Looks like this is a platform problem, introduced between 2016.3 and 2017.1. Structure view uses `outOfCodeBlockModificationCount` to check if it should update itself: https://github.com/JetBrains/intellij-community/blob/master/platform/lang-impl/src/com/intellij/ide/structureView/newStructureView/StructureTreeBuilder.java#L186-L189. And looks like this modification count stopped working for Rust in 2017.1! The update routine in `StructureViewWrapperIml` is not related to this problem: it is the update that is scheduled when the UI itself changes.

**Comment by matklad** [comment]
https://youtrack.jetbrains.com/issue/IDEA-177231
