### ISSUE TITLE
`match` keyword completion

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1552]
Add completion for `match` keyword, which automatically adds `{}`. The code is in `org.rust.lang.core.completion.RsKeywordCompletionContributor`

**Comment by dobkeratops** [comment]
I was just about to ask about this: basically my observation is that swapping from C++ to Rust, some scenarios where an OOP IDE may offer assist with 'a bunch of virtuals to over-ride', the equivalent situation in Rust is 'a bunch of match arms'..  would it be possible for the IDE to actually query the type of the expression in the match and show it's definition somewhere,  even if not going all the way with specific 'match completion' (although that would be amazing eventually)

(n ms visual studio there's an interesting [code definition window](https://msdn.microsoft.com/en-us/library/f5yx24a6(v=vs.100).aspx) which always shows 'the definition of whats under the cursor' .. i'm not sure at what point you'd want that to show up though

**Comment by matklad** [comment]
Yeah, filling match arms the neighboring issue #1551 , and code definition windows looks like Quick Definition (<kbd>Ctrl+Shift+I</kbd>), which sadly does not work super great yet #1555  :(
