### ISSUE TITLE
Type hints should not be shown for tuple structs

### ISSUE THREAD

**Issue by robinst** [intellij-rust/intellij-rust#1560]
Using version 0.1.0.2133-nightly of the plugin, type hints are shown for tuple structs such as `Ok` or `Some`, see screenshot:

<img width="191" alt="screen shot 2017-08-02 at 15 37 54" src="https://user-images.githubusercontent.com/16778/28859076-92663984-7798-11e7-874c-cf9051335306.png">

They should probably not be shown in these cases as they don't add any value and make the code harder to read.

**Comment by farodin91** [comment]
This doesn't looks like type, this are parameter name infos

**Comment by Others** [comment]
I think these **are** parameter name info. But they still are totally useless and should be removed.

**Comment by farodin91** [comment]
This will be fixed by smart hints in #1536

**Comment by farodin91** [comment]
Closed
