### ISSUE TITLE
[FMT] Tune formatter settings to par with Rust formatting RFCs

### ISSUE THREAD

**Issue by mkaput** [intellij-rust/intellij-rust#1561]
Our formatter currently defaults to some its own style (mostly based on my personal preferences since times I wrote it) which is reported to not match rustfmt. These style conflicts should be removed and we should format code 1:1 as rustfmt.

Formatter source: https://github.com/intellij-rust/intellij-rust/tree/66fd640a00f23674a777112c0ee50e630059f52f/src/main/kotlin/org/rust/ide/formatter
RFCs: https://github.com/rust-lang-nursery/fmt-rfcs

Comments highlighting formatting differences will be very welcome!

[up-for-grab] [E-medium] - @matklad you know what to do :)

**Comment by mkaput** [comment]
oh actually it's duplicate of #431

**Comment by matklad** [comment]
Yeah, the problem is that `rustfmt` itself is in the process of changes: they recently switched to rustfmt-nightly, and tuned the default style. 

And the set of accepted RFCs does not inspire confidence either :( 

https://github.com/rust-lang-nursery/fmt-rfcs/tree/master/text

**Comment by mkaput** [comment]
Oh, forgot about the change
