### ISSUE TITLE
Opening a specific file causes IntelliJ to run out of memory and hang 

### ISSUE THREAD

**Issue by angusholder** [intellij-rust/intellij-rust#1565]
This file has a fairly complex macro so I figure that probably has something to do with it. I'm providing a zip of the project, just open main.rs and you should find that once the code analysis has kicked in, within a second or two, IntelliJ shoots up to its memory usage limit and hangs.

[intellij-test.zip](https://github.com/intellij-rust/intellij-rust/files/1194933/intellij-test.zip)

**Comment by vlad20012** [comment]
Thanks for report!
I've checked your project and think the issue has already been fixed with #1563. Please check it tomorrow on the latest [nightly](https://intellij-rust.github.io/install.html) Intellij-rust build.

**Comment by angusholder** [comment]
Ah wow great, I will do thanks!

**Comment by matklad** [comment]
@angusholder does the nightly version helped? 

FYI, you don't have to wait until the nightly, you can grab the latest build off nightly from https://teamcity.jetbrains.com/repository/download/IntellijIdeaPlugins_Rust_CurrentIdea_TestsRust/.lastSuccessful/intellij-rust-0.1.0.%7Bbuild.number%7D.zip (this can be installed via `Ctrl+Shift+A > Install plugin from disk`).

**Comment by angusholder** [comment]
Yeah all appears to work fine now, thank you!
