### ISSUE TITLE
formatting source remove comma in match statement

### ISSUE THREAD

**Issue by Geobert** [intellij-rust/intellij-rust#1566]
In this code
```
pub fn total_minutes(&self) -> i64 {
        match self.status {
            DayStatus::Worked => self.end.signed_duration_since(self.start).num_minutes() - self.pause,
            DayStatus::Weekend => 0,
            DayStatus::Holiday => unsafe { HOLIDAY_DURATION },
            _ => 0,
        }
    }
```
when launching code formatting, the comma at the end of `DayStatus::Holiday` case is removed. 

I think it shouldn't (as it makes compilation failing but I'm still a Rust newbie)

**Comment by matklad** [comment]
Yep, that's definitely a bug in the plugin! However, the, future versions of Rust will allow to omit this comma

**Comment by Geobert** [comment]
Workaround for people encountering this:
`Settings->Editor->Code Style`
check `Enable formatter markers in comments`

and put `// // @formatter:off` and `// @formatter:on` on the problematic section(s)

**Comment by matklad** [comment]
There's also "preserve punctuation" checkbooks in code style settings
