### ISSUE TITLE
Substitute type keywords with the actual type

### ISSUE THREAD

**Issue by Xaeroxe** [intellij-rust/intellij-rust#1568]
Type hints should not use the keyword Self, hints shown should reflect the name of the structure returned, not any of its possible aliases.  On the bottom two lines the hints show "Self"

![self](https://user-images.githubusercontent.com/6182002/28902619-695a6180-77bd-11e7-8431-9c6a6fbb6169.png)

**Comment by vlad20012** [comment]
Thanks for the report!
The issue looks fixed by #1550. Please, check it on the latest [nightly](https://intellij-rust.github.io/install.html) Intellij-rust build.
![image](https://user-images.githubusercontent.com/3221931/28920286-c883b6d8-7859-11e7-9312-6408014df255.png)

**Comment by farodin91** [comment]
Closed?

**Comment by matklad** [comment]
Yep, thanks @farodin91 !
