### ISSUE TITLE
plugin 'rust' is incompatible with this installation

### ISSUE THREAD

**Issue by liutaihua** [intellij-rust/intellij-rust#157]
after ./gradlew buildPlugin executed
i got this zip file
build/distributions/IntelliJ\ Rust-0.0.1.SNAPSHOT.zip 

when load it at intellij, throw error: plugin 'rust' is incompatible with this installation

intellij version:  14.1.5

./gradlew --version
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0

------------------------------------------------------------
Gradle 2.8
------------------------------------------------------------

Build time:   2015-10-20 03:46:36 UTC
Build number: none
Revision:     b463d7980c40d44c4657dc80025275b84a29e31f

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_66 (Oracle Corporation 25.66-b17)
OS:           Mac OS X 10.11.1 x86_64

**Comment by matklad** [comment]
Yes, you need IDEA 15 for the plugin. I will update README.

**Comment by matklad** [comment]
Readme updated, thanks!
