### ISSUE TITLE
Build Project command regression

### ISSUE THREAD

**Issue by sorenmortensen** [intellij-rust/intellij-rust#1577]
Prior to version 47 (0.1.0.2063), the Build Project command in IntelliJ ran `cargo build`. Now, after updating, it does nothing.

**Comment by matklad** [comment]
Hm, it should run `cargo check` instead. Could it be that you are using an older version of `cargo`, which does not have `check` command?

**Comment by sorenmortensen** [comment]
Nope, I'm using `cargo` 0.19.0, which does have the `check` command.

```
$ cargo --version
cargo 0.19.0 (28d1d60d4 2017-05-16)
```

When I say that the Build command does nothing, I don't just mean that it doesn't build the project. I mean that it doesn't appear to attempt _any_ action whatsoever - nothing appears in the bottom status bar, no UI panels appear, nothing happens.

**Comment by jcbritobr** [comment]
For me it runs check command, but Im assuming that the correct command to run is the build. The button is labelled "build".

**Comment by sorenmortensen** [comment]
I can no longer reproduce this.
