### ISSUE TITLE
It is not possible to debug applications with command line parameters

### ISSUE THREAD

**Issue by pabloa** [intellij-rust/intellij-rust#1587]
I create a Run configuration using parameters. When I Run it, it correctly executes a command like:
```
cargo run --color=always --bin myProg -- client peperulo
```
However, when I launch it with Debug, it executes other cargo line like:
```
cargo build --color=always --bin myProg -- client peperulo
```
and Cargo reports an error: 
```
error: Invalid arguments.

Usage:
    cargo build [options]
```

It works ok if I remove my command lines after --

**Comment by bgard6977** [comment]
@matklad please [see the PR](https://github.com/intellij-rust/intellij-rust/pull/1862) I just submitted for a fix.

**Comment by bgard6977** [comment]
I think this issue is resolved now.

**Comment by isegal** [comment]
Is there a regression with this issue?

I am not able to see a separate field for arguments.

Using 0.2.0.2428-182-nightly 
Clion 2018.2.4 on OSX

The only fields are:
Command:
Show stdout/stderr in tests
Environment variables
Working Directory
Backtrace [No/Short/Full]

Also tried default distribution from official repo - no luck.

**Comment by isegal** [comment]
Update: After looking at the PR commit and tinkering around, I answered my own question.

As far as I can see, there is no longer a field for separate command line arguments.

To specify them, need to add -- followed by arguments under the command field in the configuration.

Example:

Command: run -- arg1 arg2 arg3...

**Comment by JKingdom** [comment]
I meet this problem, when I point the params like
```
run -- params1 params2
```
it's run normal in "run"
but in debug, it's like:
```
/home/xxx/.cargo/bin/cargo build --color=always --featuresmsgbus-redis -- --dev -d=./sub
error: Found argument '--dev' which wasn't expected, or isn't valid in this context

USAGE:
    cargo build --color <WHEN> --features <FEATURES>

```
the params `--dev -d` not run successful in debug module

I'm use clion
CLion 2018.3.1
Build #CL-183.4588.63, built on December 4, 2018
Licensed to Chengxin Jin
Subscription is active until April 27, 2019
For educational use only.
JRE: 1.8.0_152-release-1343-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-29deepin-generic

the rust plugin is
v0.2.0.2111-183
