### ISSUE TITLE
Rolling Nightly Channel

### ISSUE THREAD

**Issue by alexeykudinkin** [intellij-rust/intellij-rust#161]
Now after we've got (almost) fully-fledged project-model support and decent (almost) resolve-implementation i believe, we're almost ready to start shipping value to the community by the way of rolling out nightly channel in the public.

We've some outstanding feature-requests (highly) desired to be landed in trunk prior to going public:

1. ~~#152~~

Though, we still have some show-stoppers impeding us from starting doing that:

1. ~~#119~~
2. ~~#16~~
3. #190, #199 (waiting #218) 
4. ~~#185~~

**Comment by matklad** [comment]
#16 is not a show stopper I believe. We don't need this level of AST details at the moment.

**Comment by matklad** [comment]
And I'd say that we should implement or reject #54 before v0.1

**Comment by alexeykudinkin** [comment]
Since [#2196](https://github.com/rust-lang/cargo/pull/2196) finally have found its way to the cargo master, and its already being rolled out to the nightly channel, i believe there are no more stoppers to start shipping builds (except #218).

**Comment by hastebrot** [comment]
Wow, amazing work! What does nightly channel mean? Will it be available as IDEA plugin over the settings dialog or do I need to add a nightly/EAP channel?

**Comment by alexeykudinkin** [comment]
@hastebrot exactly, you'd need `cargo-0.9.0-nightly` to get import working for Cargo backed projects. 
Yes, it's available right inside IDEA's plugin settings window, though you need to add our nightly channel as an additional plugin repository. Please, check out [README.md](https://github.com/intellij-rust/intellij-rust/blob/master/README.md) for the further assistance.
