### ISSUE TITLE
Get rid of dummy functions in test

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#162]

**Comment by Turbo87** [comment]
what did you mean by dummy functions?

**Comment by matklad** [comment]
As a workaround for https://github.com/intellij-rust/intellij-rust/issues/119 I've changed several test files from 

```Rust
fn foo() {}
```

to 

```Rust
fn foo() {}

fn bar() {}
```

I think I've removed all such workarounds, but I am not sure: I wasn't smart enough to name such dummy fns `dummy`, or leave a `//FIXME`

**Comment by Turbo87** [comment]
ah I see, thought you meant something else

**Comment by matklad** [comment]
I should've provided more info here :)
