### ISSUE TITLE
Separate parameter hints from type hints

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#1623]
It's not currently possible to show just parameter hints (the names of function parameter variables) or just type hints (the types of local variables). Sometimes it's helpful for me to see one or the other, but not both so this flexibility would be great.

**Comment by farodin91** [comment]
You can decide in rust settings or in inlay hint settings.

**Comment by johnthagen** [comment]
Thanks @farodin91 Maybe ideally I'd prefer a shortcut toggle between them, but this is totally fine.
