### ISSUE TITLE
Incorrect newline indentation in struct literals

### ISSUE THREAD

**Issue by doxxx** [intellij-rust/intellij-rust#1626]
When typing a struct literal, pressing Enter at the end of the last field line does not indent the new empty line correctly.

For example:

```rust
SomeStruct {
    foo: 1,
    bar: 2,<cursor>
}
```

Pressing Enter at `<cursor>` results in the following:

```rust
SomeStruct {
    foo: 1,
    bar: 2,
<cursor>
}
```

Whereas I would expect this instead:

```rust
SomeStruct {
    foo: 1,
    bar: 2,
    <cursor>
}
```

I believe this was working in an earlier version of the plugin. I'm currently using v0.1.0.2064.

**Comment by vlad20012** [comment]
Hmm, can't reproduce on nightly.

**Comment by matklad** [comment]
Yeah, I think this was fixed in https://github.com/intellij-rust/intellij-rust/commit/9e91420da18de2fe547c02cce6c21748fc7256b0

**Comment by doxxx** [comment]
Confirmed in latest plugin version.

**Comment by matklad** [comment]
@doxxx confirmed that it works, or that it does not work?

**Comment by doxxx** [comment]
Sorry, confirmed that it works.

**Comment by matklad** [comment]
Glad to hear that!
