### ISSUE TITLE
self:: autocompletion in function signatures

### ISSUE THREAD

**Issue by miedzinski** [intellij-rust/intellij-rust#1639]
[Imgur](http://i.imgur.com/w0AJFIE.png)

Notice the colons.

This happens even outside impl blocks. I don't think any other paths trigger it; only `self::`.

edit:
PyCharm Pro 2017.2.1
intellij-rust 0.1.0.2065
rustc 1.19.0 (0ade33941 2017-07-17)

**Comment by farodin91** [comment]
I will try fix it
