### ISSUE TITLE
Rustfmt doesn't work in workspaces

### ISSUE THREAD

**Issue by MaikKlein** [intellij-rust/intellij-rust#1641]
https://github.com/intellij-rust/intellij-rust/blob/7637ecd5643ddca202c7fff337f1600aefcecbb3/src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt#L78
It currently outputs:
```
cargo fmt -- --write-mode=overwrite --skip-children /home/maik/projects/breeze-lang/breeze-lang/src/visitor.rs
```
It should output:
```
cargo fmt -p breeze-lang -- --write-mode=overwrite --skip-children /home/maik/projects/breeze-lang/breeze-lang/src/visitor.rs
```
I think as a temporary workaround you could just look at the filepath, move up until you find the `src` folder and the next folder will be the workspace name. This also works for non workspace projects.

**Comment by matklad** [comment]
Hm, does `rustfmt` support `--all` argument?

**Comment by MaikKlein** [comment]
@matklad Yes it does.

**Comment by matklad** [comment]
Thanks for the report @MaikKlein! I've added the `--all` argument which hopefully should fix the issue. I wonder however if rustfmt should just work in this case? We are specifying the file explicitly, so in theory it should not care about workspaces at all...

**Comment by MaikKlein** [comment]
@matklad Not sure if I should open another issue. I just realized that `reformat file with rustfmt` now reformats the whole project.

**Comment by MaikKlein** [comment]
Update: It seems to work now. I think I ran into a different issue.
