### ISSUE TITLE
Debugger doesn't stop at breakpoints

### ISSUE THREAD

**Issue by stiv-yakovenko** [intellij-rust/intellij-rust#1643]
rust plugin version: Version: 0.1.0.2065
CLion 2017.2.1
Build #CL-172.3544.40, built on August 2, 2017

Also there is no way to create rust project in clion, the only option that worked -- is to open project created in IDEA. But debugger doesn't stop at the breakpoint in a simple helloworld application. Application starts, but debugger doesn't work.

**Comment by minecrawler** [comment]
see #535 and #557

**Comment by stiv-yakovenko** [comment]
@minecrawler, i've seen it, but i don't know how it may help me.

**Comment by minecrawler** [comment]
@stiv-yakovenko In the first issue, there is a guide on how to get the debugger working (workaround) further down, and the second issue is already a work-item for project-creation.

**Comment by stiv-yakovenko** [comment]
@minecrawler, would you be so kind to point out the instruction? I Tried to follow 
https://github.com/intellij-rust/intellij-rust/issues/535#issuecomment-320866757
but I don't understand where to get LLDB. I tried to download it here: https://lldb.llvm.org/download.html but these links are dead.

**Comment by minecrawler** [comment]
You usually can get it using your package manager on Linux (using Gentoo Linux, I got it via `sudo emerge -a lldb` from the [Gentoo Package Repo](https://packages.gentoo.org/packages/dev-util/lldb)), on macOS you can get it with XCode and on Windows you will have to build it yourself using the [code from git](https://lldb.llvm.org/source.html) and [these instructions](https://lldb.llvm.org/build.html#BuildingLldbOnWindows).

**Comment by stiv-yakovenko** [comment]
I've found the solution for windows, you have change toolchain from msvc to gnu: 

rustup install stable-gnu 
rustup default stable-gnu

now debugging works.

**Comment by stiv-yakovenko** [comment]
I'd propose for clion to diagnose if gdb has read all debug symbols correctly.

**Comment by Pzixel** [comment]
I hade same behaviour with installed `rust-mvsc` toolchain. Switch to `rust-gnu` fixes the problm

**Comment by johnthagen** [comment]
Hopefully with the [latest CLion announcement supporting MSVC](https://blog.jetbrains.com/clion/2019/06/clion-2019-2-eap-msvc-debugger-unused-includes-check-and-more/#more-6491) Rust support will follow.

**Comment by ortem** [comment]
MSVC [is supported](https://github.com/intellij-rust/intellij-rust/pull/5535) now. Please follow our [Help](https://www.jetbrains.com/help/clion/rust-support.html#debug) to learn more about Rust debugging in case of any problems. I think this can be closed now.
