### ISSUE TITLE
CLION build button sometimes doesn't work

### ISSUE THREAD

**Issue by stiv-yakovenko** [intellij-rust/intellij-rust#1647]
I use CLion 2017.2.1 (Build #CL-172.3544.40, built on August 2, 2017) and rust plugin 0.1.0.2065. 
Build button and ctrl-f9 is grey
<img width="469" alt="build_dont_work" src="https://user-images.githubusercontent.com/4163254/29620940-8e07fe38-8849-11e7-97cc-c62e8f4ecd92.png">

for this project: https://github.com/stiv-yakovenko/fileshare

**Comment by Undin** [comment]
Works in CLion 2018.1
fixed in #2317
