### ISSUE TITLE
Complex resolve fails

### ISSUE THREAD

**Issue by farodin91** [intellij-rust/intellij-rust#1649]
I will try to look into.
```rust
trait Foo {}
struct S<A: Foo> { a: A }
struct C;
impl Foo for C {}
type SBla<A> = S<A>;
impl S<C> {
  fn bind() -> Self { SBla{a:C} }
}    //X
fn main() {
  let a = SBla::bind();
}              //^ 
```
@matklad Any idea?

**Comment by farodin91** [comment]
It looks like a lot of work. And i'm on vacation next week.

**Comment by farodin91** [comment]
@vlad20012 Any suggestions? Or do you like to fix it?

**Comment by vlad20012** [comment]
Oh, i've missed it.
Currently I'm working on a really LARGE type inference changes. And I think it intersects with the issue, so I suggest to postpone.
Furthermore, if now it is a really `lot of work` (mostly for injecting hacks :)), in future it will become trivial =)

**Comment by farodin91** [comment]
Okay. Do you need any help for the type inference changes?

**Comment by vlad20012** [comment]
Hmm, you're looking for something to help? Can suggest this:
1. Simply [up for grab](https://github.com/intellij-rust/intellij-rust/issues?q=is%3Aopen+is%3Aissue+label%3A%22up+for+grab%22)
2. Mostly #1667
3. `impl<T> Trait for T`. As for me, it is a really major task, and it is not too difficult to implement. In `RsImplIndex.index` we should check if type is a type parameter of this impl (go to parent psi, find type parameters declaration and so on), then if it is a type parameter, save if to index with a specific key that is invalid identifier (like `#`). Then while finding impls retreive index twice: with actual type name and with out specific key.
