### ISSUE TITLE
Aliased crates hidden. 

### ISSUE THREAD

**Issue by lilith** [intellij-rust/intellij-rust#1658]
I have a prelude that includes `pub extern crate imageflow_types as s;`. While everything compiles, s:: does not autocomplete or allow go-to-definition. ::imageflow_types:: does. 
            
I'm pretty sure this used to work at one point. 

imageflow_types is a crate within my opened workspace.

**Comment by Undin** [comment]
@nathanaeljones Could your check it with the latest plugin version?
If it still doesn't work, could you please provide exact peace of code where completion and go-to definition don't work?

**Comment by dima74** [comment]
I guess it was fixed by #9545 or earlier. Please feel free to reopen or create a new issue if you encounter any problem
