### ISSUE TITLE
"Use field init shorthand" intentaion

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1663]
Add an inspection to convert `MyStruct { foo: foo }` into `MyStruct { foo }`.

**Comment by mkaput** [comment]
*field

**Comment by anton-okolelov** [comment]
Could I grab it?

**Comment by matklad** [comment]
Ah, unfortunately it is already handled by https://github.com/intellij-rust/intellij-rust/pull/1684 :) 

But, if you want to implement some intention, you can look into "invert if condition" (it is available in Java and Kotlin, for example), which we don't have yet. It should be possible to share some logic with DeMorgan law intention as well!

**Comment by anton-okolelov** [comment]
Yeah, it would be great. It seems interesting to me. I'm gonna implement it
