### ISSUE TITLE
Improving readability

### ISSUE THREAD

**Issue by gilescope** [intellij-rust/intellij-rust#1677]
Things like brackets and semi-colons are essential for robust source code maintainence. They make a Rust program safer than Python with all its whitespace rules. However you have to hand it to Python on the readability front - it can be quite pretty. 

Could we de-emphasise in our rust ide the ; and { } by making them less bright / less bold - maybe some boring gray that almost merges in with the background? This would help our eyes focus on the important bits.

Less is more.

**Comment by mkaput** [comment]
I think we should strictly stick with IntelliJ default when it comes to syntax highlighting default. If anyone want to change them, then one can just customize colour themes. Personally I very wouldn't like if we take the path of intellij-elixir here where each token type has different colour

**Comment by matklad** [comment]
Yeah, this is definitively something that should be implemented on the platform level and not on the language level. That said, I think that this suggestion can be rather controversial, and perhaps is better left for the user-defined color schemes :)
