### ISSUE TITLE
pd expands to `eprintln` and not `println`

### ISSUE THREAD

**Issue by MaikKlein** [intellij-rust/intellij-rust#1681]
![](http://i.imgur.com/D2Gpz1O.gif)

pd expands to `eprintln` and not `println`

**Comment by matklad** [comment]
Yeah, that was an intentional change: `pd` stands for debug print, and usually for debugging it either does not matter if stdout or stderr is used, or stderr is preferable.

**Comment by matklad** [comment]
Yeah, and if you find `println!` more useful, you can totally change the snippet via settings!
