### ISSUE TITLE
Type inference of `impl Trait` RFC 1522

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#1692]
[RFC 1522](https://github.com/rust-lang/rfcs/pull/1522)
```rust
trait Trait {
    fn bar() {}
}     //X
fn foo() -> impl Trait { unimplemented!() }
fn main() {
    foo().bar();
}        //^
```
I know that `impl Trait` is an unstable feature, but is used increasingly in rustc itself, and I tired of stumbling over type inference failures caused by this =D

It is pretty easy to implement - just create new type `TyAnon` in package `org.rust.lang.core.types.ty` with single field of type `List<BoundElement<RsTraitItem>>`, instantiate it in `Declarations.inferTypeReferenceType` for element of type `RsImplTraitType` and then add a special case for it in the `ImplLookup.findImplsAndTraits` just like `TyTypeParameter`.

---
You can find more info about how to start contributing to Intellij-Rust in [CONTRIBUTING.md](https://github.com/intellij-rust/intellij-rust/blob/master/CONTRIBUTING.md), and some info about our architecure in [ARCHITECTURE.md](https://github.com/intellij-rust/intellij-rust/blob/master/ARCHITECTURE.md). If you have any questions about this issue, you can ask them right here or in our [gitter](https://gitter.im/intellij-rust/intellij-rust). If you decided to grab this issue, please leave a comment here and put yourself in the [worklist](https://github.com/intellij-rust/intellij-rust/wiki/Worklist).

**Comment by oleg-semenov** [comment]
Hi @vlad20012, i decided to try to do this.
