### ISSUE TITLE
Document build dependencies/versions/tricks

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [intellij-rust/intellij-rust#170]
Maybe add a Dependencies.md or build.md?

I tried with Java6 and ran out of PermGen space.

Java7 gave this:
:compileKotlin
w: /Users/andrew/workspace/intellij-rust/src/main/kotlin/org/rust/cargo/project/CargoExternalSystemManager.kt: (71, 61): Parameter 'path' is never used
w: /Users/andrew/workspace/intellij-rust/src/main/kotlin/org/rust/lang/annotator/RustAnnotator.kt: (37, 34): Unnecessary safe call on a non-null receiver of type org.rust.lang.core.resolve.ref.RustReference
w: /Users/andrew/workspace/intellij-rust/src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt: (38, 17): Variable 'r' initializer is redundant
w: /Users/andrew/workspace/intellij-rust/src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt: (65, 50): Parameter 'level' is never used
w: /Users/andrew/workspace/intellij-rust/src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt: (68, 49): Parameter 'level' is never used
w: /Users/andrew/workspace/intellij-rust/src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt: (87, 44): Parameter 'level' is never used
w: /Users/andrew/workspace/intellij-rust/src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt: (99, 45): Parameter 'level' is never used
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.

java 8 worked fine.

**Comment by matklad** [comment]
We do target Java 8: https://github.com/intellij-rust/intellij-rust/blob/master/gradle.properties#L5

I suspect that if you change that line to `1.7` you will be able to use Java7.

**Comment by Turbo87** [comment]
https://github.com/intellij-rust/intellij-rust/blob/master/.travis.yml#L3 also says the same. IMHO that should be enough.

**Comment by andrewdavidmackenzie** [comment]
My point was, if you clone/download and trial to build - and happen to be
on java6 or java7 (for me) it tries and fails.....

The .travis.yaml file is not used in local build and it didnt occur to me
to look at it even.

It would save others and yourselves time if you just noted in the readme
"build with java8" or have a small build.md

**Comment by matklad** [comment]
Ouch, I was absolutely sure we mention Java8 in README. It is an oversight, will fix in a jiffy

**Comment by matklad** [comment]
Fixed, thanks for the report and sorry for misunderstanding :)
