### ISSUE TITLE
Could not load built plugin in IntelliJ Ultimate 14.1.5

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [intellij-rust/intellij-rust#171]
I built the plugin using instructions supplied.

When I tried to load it in IntelliJ Ultimate 14.1.5 I got this error:

<img width="405" alt="screen shot 2015-12-08 at 19 27 07" src="https://cloud.githubusercontent.com/assets/5529132/11664491/62cd2c14-9de2-11e5-99e7-81068fd263ba.png">

I tried that starting IntelliJ from terminal with Java6 and Java8 as JAVA_HOME just incase it depended on JRE version, but failed to load plugin from disk in both cases.
BTW: Not clear to me if IntelliJ is using a bundled JRE or not (The "Switch IDE Boot JDK" action is disabled....) and if that affected anything.

There was no log output when started from the command line to help. :-(

**Comment by matklad** [comment]
Yes, we are targeting IDEA 15 based IDEs. The plugin is not released yet, so we haven't paid any attention to integration with older versions of IDEA.

**Comment by alexeykudinkin** [comment]
@andrewdavidmackenzie unfortunately some of the IJ API change too fast, and we'd not be able to maintain compatibility with previous versions.

**Comment by alexeykudinkin** [comment]
@andrewdavidmackenzie if you're still interested in the plugin (and we're keenly thankful for that), you can now build it from `IDEA-14` branch and use it with IDEA 14.

It've been tested against 14.1.5, so if you would stuck another humbles let us know.
