### ISSUE TITLE
Lazy statics don't show up in code suggestion

### ISSUE THREAD

**Issue by UninterestinAcc** [intellij-rust/intellij-rust#1717]
A static variable initialized via [lazy static](https://github.com/rust-lang-nursery/lazy-static.rs) will not show up in IntelliJ's suggestions.

Example: 
```rust
lazy_static! {
    static ref BYTE_ARRAY: Mutex<Vec<u8>> = Mutex::new(vec![]); // Note: won't work for a public static reference either.
}

fn main() {
    BYTE_ARRAY.lock().unwrap() // Won't show suggestions for Vec<u8>
    BYTE_ARR // Won't suggest BYTE_ARRAY
}
```

**Comment by farodin91** [comment]
macro expansion aren't supported in intellij-rust

**Comment by UninterestinAcc** [comment]
Is support for that planned in the future?

**Comment by farodin91** [comment]
Is planned but this could take some time.

**Comment by matklad** [comment]
Closing as a subset of https://github.com/intellij-rust/intellij-rust/issues/229

Handing lazy_static first is a nice idea though!
