### ISSUE TITLE
Unify error annotation messages style

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#1732]
Compare this two:
![image](https://user-images.githubusercontent.com/3221931/30381680-c4666d40-98a5-11e7-984e-1ae94bca7e6d.png)

![image](https://user-images.githubusercontent.com/3221931/30381613-904ace20-98a5-11e7-8484-5bf8d2183bf2.png)

First is from cargo check, second - our own inspection. 

Now we have a [good utils](https://github.com/intellij-rust/intellij-rust/blob/b42286d6b582bffa3b103cf05a9d0ad35d70b101/src/main/kotlin/org/rust/lang/core/types/RsDiagnostic.kt) for error messages formatting, and I think we shouldn't write [E0000] string manually anywhere.

We have a lot of hand-written messages [here](https://github.com/intellij-rust/intellij-rust/blob/b42286d6b582bffa3b103cf05a9d0ad35d70b101/src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt), and they should be replaced with the new API.

**Comment by shssoichiro** [comment]
I'll give this one a try.

**Comment by farodin91** [comment]
@shssoichiro I could help if you need some?

**Comment by shssoichiro** [comment]
@farodin91 Thanks. I might need help just figuring out how to use the RsDiagnostic class, I couldn't find any locations where it's being used right now based on IntelliJ's go-to usage, although I haven't had a lot of time to look quite yet.

**Comment by farodin91** [comment]
1. I would move `RsDiagnostic` into `org.rust.core.utils` to split from type inference. 
2. Make `expectedFound` part `TypeError` until we need in a different location.
3. Switch the link to error description by using the channel.
4. Now start converting errors like https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt#L87-L89 into more clean error like `TypeError`
5. ... converting more

**Comment by shssoichiro** [comment]
Thanks! I think I've got the idea now. I was having trouble grokking Kotlin's syntax at first, but now that I've figured out what the code is doing I should have a PR up in a day or two.

**Comment by Jezza** [comment]
This issue seems OK to close, as it was fixed with the aforementioned PR.
