### ISSUE TITLE
Support impl for type parameter `impl<T> Trait for T`

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#1735]
Currently we don't look for impls like `impl<T> Trait for T`, so this test fails
```rust
trait Trait {
    fn foo(&self) {}
}    //X
impl<T> Trait for T {}
struct X;
fn main() {
    X.foo();
}   //^
```
It is pretty easy to implement. [Here](https://github.com/intellij-rust/intellij-rust/blob/9603f049d96b1ec515830b1db03737db14e3af1a/src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt#L48) we indexing the `impl` by the type. We should check if type is a type parameter of this impl (go to parent psi, find type parameters declaration and check the type name is the same), then if it is a type parameter, save it to index with a specific key that is invalid identifier (like #). Then while finding impls retreive index twice: with actual type name and with our specific key.

---
You can find more info about how to start contributing to Intellij-Rust in [CONTRIBUTING.md](https://github.com/intellij-rust/intellij-rust/blob/master/CONTRIBUTING.md), and some info about our architecure in [ARCHITECTURE.md](https://github.com/intellij-rust/intellij-rust/blob/master/ARCHITECTURE.md). If you have any questions about this issue, you can ask them right here or in our [gitter](https://gitter.im/intellij-rust/intellij-rust). If you decided to grab this issue, please leave a comment here and put yourself in the [worklist](https://github.com/intellij-rust/intellij-rust/wiki/Worklist).

**Comment by Undin** [comment]
I've previously thought about it
I want to grab it:)

**Comment by farodin91** [comment]
@Undin This could also fix #1649.

**Comment by Undin** [comment]
@vlad20012 Is this issue supposed to implement bounded free trait impls like following one?
```rust
impl<T: Foo> Trait for T {}
```
I'm asking because free trait impls support is really simple but the support of bounded free trait impls is much more difficult because of necessity to build closure of the bounds graph and check cycles in it.
```rust
trait Foo { fn foo(&self) {} }
trait Bar { fn bar(&self) {} }

impl<T: Bar> Foo for T {}
impl<T: Foo> Bar for T {}
```
But if I'm wrong and there is easy way to do it, I'll be glad to know about it:)

**Comment by Undin** [comment]
@farodin91 Are you sure? Your example doesn't contain any free trait impls so I don't know how fix of this issue can fix #1649

**Comment by farodin91** [comment]
@Undin I'm not sure

**Comment by vlad20012** [comment]
@Undin I don't see a much difference between `impl<T: Foo> for T` and `impl<T: Foo> for S<T>` in terms of trait boud matching. We do not support both =) So it's another issue. (see `RsPreciseTraitMatchingTest`)

@farodin91 no-no-no, #1649 is another problem
