### ISSUE TITLE
Experimental auto-import intention

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#1737]
The "real" auto-import should be a specific quick fix attached to an "unresolved reference" error annotation. The problem with this approach is that "unresolved reference" inspections produces a lot of false positives because of unsupported macros, so macros blocks this feature.

I have another idea. We can temporary implement auto-import as a regular intention. You don't see any error annotations, but just alt+enter to a name that should be imported and apply the intention. Then, when macros will be implemented, this intention will be transformed to a quick fix. So, macros now is not blocks this task and they may be implemented in parallel.

I just made a sample intention for qick start ([click](https://github.com/vlad20012/intellij-rust/commit/6848ffa9b71adf42766613f775151d69db3dafe0)). You can start from this commit. There are a large comment about how to continue.

A large discussion about auto-import also located here #1488.

---
You can find more info about how to start contributing to Intellij-Rust in [CONTRIBUTING.md](https://github.com/intellij-rust/intellij-rust/blob/master/CONTRIBUTING.md), and some info about our architecure in [ARCHITECTURE.md](https://github.com/intellij-rust/intellij-rust/blob/master/ARCHITECTURE.md). If you have any questions about this issue, you can ask them right here or in our [gitter](https://gitter.im/intellij-rust/intellij-rust). If you decided to grab this issue, please leave a comment here and put yourself in the [worklist](https://github.com/intellij-rust/intellij-rust/wiki/Worklist).

**Comment by Undin** [comment]
I think it can be closed - main functionality is implemented
