### ISSUE TITLE
Wrong type infered for match arm with diverging arms

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1743]
![image](https://user-images.githubusercontent.com/1711539/30579779-bf7f4ed8-9d22-11e7-8793-ab3c24d34b10.png)

This should not be `: !`. cc @vlad20012

**Comment by vlad20012** [comment]
As I see, `table.val` just not resolved here?

**Comment by matklad** [comment]
>As I see, table.val just not resolved here? (at Some(table) => table.val)

Hm, yeah, this explains this issue. `table.val` is not resovled because `get_table` returns an error-chain macro-generated result. 

Nevertheless, I think that for a match expression with only `TyUnknown` and `TyNever` types, we should pick the `TyUnknown`. The relevant code is in `org.rust.lang.core.types.infer.RsFnInferenceContext#inferMatchExprType`, in particular, `getMoreCompleteType` might need to be tweaked. 

Nethetheless,
