### ISSUE TITLE
Support for conda/virtual environments

### ISSUE THREAD

**Issue by EelcoHoogendoorn** [intellij-rust/intellij-rust#1745]
Im coming from python to rust, and as such I am used to working with virtual environments to manage my dependencies. Ive found conda very useful for rust as well, to create a recreatable environment of rust/gcc/cmake and whatever else I need that is outside of the scope of cargo.

However, I cant figure out how to make the rust plugin play nicely with my conda environment. I can point the plugin to the rust binaries in my conda env, but sadly there is some additional command line magic i need to perform to make macosx find the correct fortran libraries as installed in my virtual env (export LD_LIBRARY_PATH=$HOME/miniconda3/envs/model-processing-rs/lib:$LD_LIBRARY_PATH , to be precise); and I cant figure out how to run some shell commands before the integrated IDE commands. Which might be due to my limited understanding of the run/test configurations system; but ive trawled through a lot of google searches, and I get the impression my use case isnt covered. Obviously I could add the above to my bashrc but that would kindof defeat the point of a virtual environment.

Am I missing something? Or is there a general case to be made for better virtualenv integration along the lines of PyCharm?

**Comment by matklad** [comment]
Hi @EelcoHoogendoorn! Actually I have a similar problem in that I use [nix](https://nixos.org/nix/) to manage my environment and it also works by setting certain environmental variables. For the time being, I think the best approach is to launch IDE from the shell where the environment is activated. 

You don't have to add those export to bashrc though. I think you can open a new shell, execute commands to setup your env, and then launch IDEA from this shell (here's how to create a command-line launcher: https://stackoverflow.com/a/37180502).

It would be possible to integrate with some virtual envs more tightly, but the only established tool for Rust in this area is [rustup](https://www.rustup.rs/), and we do integrate with it.
