### ISSUE TITLE
type inference doesn't work through array indexes on references to Vecs. 

### ISSUE THREAD

**Issue by jrmuizel** [intellij-rust/intellij-rust#1748]
'm' has an unknown type in the following example:
```rust
fn foo() -> u32 {
    let r: Vec<u32> = Vec::new();
    let p = &r;
    let m = p[0];
    m
}
```

**Comment by vlad20012** [comment]
Hmm, we do not do auto deref on index expression. It's an issue.

**Comment by matklad** [comment]
`org.rust.lang.core.types.infer.RsFnInferenceContext#inferIndexExprType` looks like the place to look into!

**Comment by Undin** [comment]
I'll fix it
