### ISSUE TITLE
Intentions to change `assert(a == b)` to `assert_eq(a, b)`

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1762]
There are handy `assert_eq`, `assert_ne` macros in Rust. It would be nice to have inspections which would highlight`assert!(a == b)` and `assert!(a != b)` and suggest to change them into `assert_eq(a, b)` and `assert_ne!(a, b)`.

A similar inspection is implemented here: https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/inspections/RsSimplifyPrintInspection.kt

A complete example of adding new inspections is here: https://github.com/intellij-rust/intellij-rust/commit/df64cbac9b6d14413bd15f3e33971ea725108a1e#diff-5e7848624647a9a96dd649e15fa64ae5

**Comment by pocket7878** [comment]
@matklad 

I'd like to work on this!

**Comment by matklad** [comment]
Awesome @pocket7878 !

**Comment by matklad** [comment]
Was fixed by #1771

**Comment by robinst** [comment]
Note that recently an RFC was accepted that makes `assert!(a == b)` the preferred form in the future: [RFC 2011 Nicer assert messages ](https://github.com/rust-lang/rfcs/pull/2011)

So I would consider undoing the warning about using `assert!`, to not make people switch to `assert_eq!` and then back when the better `assert!` is implemented.

**Comment by matklad** [comment]
>So I would consider undoing the warning about using assert!, to not make people switch to assert_eq! and then back when the better assert! is implemented.

At the moment, `assert_eq!` gives a better error message, so I think we should flip the direction of the intention once the RFC is implemented and is stable. If one does not want better messages, now, one can disable the inspection :)

**Comment by mkaput** [comment]
> At the moment, assert_eq! gives a better error message, so I think we should flip the direction of the intention once the RFC is implemented and is stable. If one does not want better messages, now, one can disable the inspection :)

Note that our plugin is often used by beginner rustaceans, and so this intention might encourage them to use pattern which soon will be deprecated.

**Comment by matklad** [comment]
Yeah, I think for beginners it is especially important to use what is considered idiomatic now, and not bother with future great improvements :) 

I bet `assert_eq` won't be deprecated for real in the near future anyway, because the amount of warnings will be massive, and it's break `#[deny(warnings)]` crates :)
