### ISSUE TITLE
Line comments should not be generated at the first column

### ISSUE THREAD

**Issue by coder543** [intellij-rust/intellij-rust#1770]
The standard way that `rustfmt` formats code places the `//` of a comment at the same indentation level as the surrounding code. Intellij fights this behavior by placing the `//` at the beginning of the line, causing weird formatting issues.

For Java, this is configurable under Settings -> Code Style -> Java -> Code Generation -> `Line comment at first column`. It would be nice if Rust could be configured by default _not_ to do this, and it would be nice to have at least the option to `Add a space at comment start`, which the Java settings include.

**Comment by alexander-irbis** [comment]
#825 #1534

**Comment by aloucks** [comment]
Is there any update on this? It's really frustrating.

**Comment by p-avital** [comment]
Same problem here.
The other issues have been closed with PR #1972, but I don't think this was the right approach, since I believe `rustfmt` standard should be upheld, if only because it is available regardless of platform and IDE.
It's quite frustrating when toggling a line comment to see its indentation get completely broken.

**Comment by mrFranklin** [comment]
Is it not solved yet?
frustrating too~

**Comment by SeekingMeaning** [comment]
Relevant: https://github.com/JetBrains/intellij-community/blob/4999f5293e4307870020f1d0d672a3d35a52f22d/platform/lang-impl/src/com/intellij/application/options/codeStyle/CommenterForm.java

**Comment by SeekingMeaning** [comment]
Ah my bad, I didn't notice this part:

> It would be nice if Rust could be configured by default _not_ to do this

Most likely have to add defaults like here: https://github.com/JetBrains/intellij-community/blob/184607e98e1668609770e86bace6678d1e07e737/xml/impl/src/com/intellij/application/options/XmlLanguageCodeStyleSettingsProvider.java#L88-L96

I'm thinking set `LINE_COMMENT_AT_FIRST_COLUMN` to `false` and `LINE_COMMENT_ADD_SPACE` to `true`, and perhaps set `BLOCK_COMMENT_AT_FIRST_COLUMN` to `false` as well.

**Comment by Undin** [comment]
@SeekingMeaning yep
I'm already working on it
