### ISSUE TITLE
Extracting a function should create the necessary parameters.

### ISSUE THREAD

**Issue by jrmuizel** [intellij-rust/intellij-rust#1774]
It would be nice if when extracting a function from code all the variables used by that range of code became parameters to the new function.

For example:

```rust
fn foo(x: u32) -> u32 {
   x *= 2;
   x += 1;
   x
}
```
became
```rust

fn foo(x: u32) -> u32 {
    x *= 2;
    new_fn(x)
}

fn new_fn(x: u32) -> u32 {
   x += 1
   x
}
```

**Comment by farodin91** [comment]
I current work on this support.

**Comment by matklad** [comment]
Hm, I think this should not be closed yet, because we handled return values, but not the input parameters.

**Comment by Undin** [comment]
We don't handle function parameters so I think it should be opened yet

**Comment by Undin** [comment]
fixed
