### ISSUE TITLE
Autocompletion does not insert parentheses

### ISSUE THREAD

**Issue by alexander-irbis** [intellij-rust/intellij-rust#1780]
If the function is inserted without consuming the remainder of the identifier, the cursor moves forward, but the parentheses are not inserted

[![image.png](https://files.gitter.im/intellij-rust/intellij-rust/j9Va/thumb/image.png)](https://files.gitter.im/intellij-rust/intellij-rust/j9Va/image.png)
[![image.png](https://files.gitter.im/intellij-rust/intellij-rust/vX0z/thumb/image.png)](https://files.gitter.im/intellij-rust/intellij-rust/vX0z/image.png)

**Comment by vlad20012** [comment]
The actual code is located [here](https://github.com/intellij-rust/intellij-rust/blob/fcb26cbdbd7ae7a654597413b52862f3e115f58b/src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt#L127) (and the tests [here](https://github.com/intellij-rust/intellij-rust/blob/master/src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt#L31)).

We should make the condition more complex to check that a caret is at the end of a call expression (use `tailOffset`?)

**Comment by maraisr** [comment]
Can I grab this one @vlad20012 ?

**Comment by vlad20012** [comment]
@maraisr don't ask, just grab it! :)

**Comment by maraisr** [comment]
What do you mean `tailOffset`?

Are you thinking something like:

```rust
fn frobnicate() {}
fn main() { frob<caret>cate() }

// To complete to this

fn frobnicate() {}
fn main() { frobnicate()<caret> }
```
and there fore you want to check to see if the "tailOffset" of the `parent`is... something? [Here](https://github.com/intellij-rust/intellij-rust/blob/fcb26cbdbd7ae7a654597413b52862f3e115f58b/src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt#L127) ??

**Comment by vlad20012** [comment]
@maraisr
In your example the resulting code should be
```rust
fn frobnicate() {}
fn main() { frobnicate()<caret>cate() }
```

**Comment by alexander-irbis** [comment]
Was fixed eons ago.
