### ISSUE TITLE
Automatic recommendation to bring a library to program scope

### ISSUE THREAD

**Issue by ramvalleru** [intellij-rust/intellij-rust#1784]
When using intellij plugins for Java or Scala, they give automatic recommendation for a class package import when I write Map in a function or class.

Is this feature being implemented in intellij-rust. It would be useful if this feature is implemented to recommend standard Rust libraries as well as imported external libraries.

**For Example:**

``` Rust
let visited_fields = HashMap::new();
```
should recommend 

> use std::collections::HashMap;

**Comment by matklad** [comment]
Yep, it's a duplicate of https://github.com/intellij-rust/intellij-rust/issues/1366, which is not implemented yet, but is on the horizon :)
