### ISSUE TITLE
Fill struct & fill struct recursively intention 

### ISSUE THREAD

**Issue by mkaput** [intellij-rust/intellij-rust#1794]
Shortly, implement this for Rust: https://twitter.com/dlsniper/status/913458055039373312

**Comment by vlad20012** [comment]
We already have [AddStructFieldsFix](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFix.kt). It can be slightly improved: init fields with default values instead of `()` and fill structs recursively.

**Comment by pocket7878** [comment]
@vlad20012 I want to try to work on this!
