### ISSUE TITLE
Can't find crates [latest nightly]

### ISSUE THREAD

**Issue by Redrield** [intellij-rust/intellij-rust#1800]
On the latest nightly from rustup, a valid project that compiles just fine shows errors in the IDE for resolving the crate. This also breaks autocomplete for any crates used by a project. Setting the default toolchain to 'stable', and reloading the project in the IDE results in the errors disappearing. 

Environment
Operating system: Manjaro Linux
Linux kernel version: 4.12
Rust nightly version: 1.22.0-nightly (6f87d20a7 2017-09-29)
IntelliJ version: 2017.2.5
Plugin version: 0.1.0.2069

Screenshot of the issue is ![here](https://i.imgur.com/TeLwwcQ.png)

**Comment by alexander-irbis** [comment]
I noticed a couple of exceptions
(A)
![default](https://user-images.githubusercontent.com/1448323/31053817-240713ce-a695-11e7-99db-f8010ad6b7db.png)
(B)
![default](https://user-images.githubusercontent.com/1448323/31053812-02373256-a695-11e7-8fd4-ae354d8e72ac.png)
(C)
![default](https://user-images.githubusercontent.com/1448323/31053848-8380635a-a695-11e7-8feb-f8a35cd97913.png)
The last two are projects from the same workspace, but serde has different status.
After `cargo update` on C, B now is
![default](https://user-images.githubusercontent.com/1448323/31053931-f3bc0eac-a696-11e7-9a59-69f3e22daae1.png)
`cargo clean` and rebuilding of workspace changes nothing.

**Comment by alexander-irbis** [comment]
Playing with Cargo.toml and versions of rustc, changes the picture in a slightly random fashion. Once serde became available.

`rustup override set nightly-2017-09-28` - fixes problem.
`rustc 1.22.0-nightly (0e6f4cf51 2017-09-27)`
