### ISSUE TITLE
Display `Iterator<Item=T>` for parameter hints for iterators

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1803]
Parameter hints are not really useful for iterators right now:

![image](https://user-images.githubusercontent.com/1711539/31057723-2e4f47ce-a6f0-11e7-9584-7955f7807eaf.png)

I think we can invent some heuristics to decide when we should hide the real type and show something like `Iterator<Item=T>` instead.

**Comment by vlad20012** [comment]
I'm going to implement it. If some type implements `Iterator` trait, it will be shown as "impl Iterator<Item=T>". But it looks exactly the same as "impl Iterator" type. Any ideas how we can distinct them? "impl' T"? =D

**Comment by matklad** [comment]
Don't distinguish them? :) I don't think sure that we should place any special disambiguation logic until some users complain that they really need to know the difference between concrete type and impl trait :)
