### ISSUE TITLE
No type inference for elements of arrays

### ISSUE THREAD

**Issue by doxxx** [intellij-rust/intellij-rust#1806]
In the following code:

```rust
let a: [f64; 3] = [1.0, 2.0, 3.0];
let b = a[0];
let c = b.powi(2);
```

The type of `b` is not inferred -- it's shown as `<unknown>` -- and `powi` is not resolvable and thus not highlighted as a method of `f64`.

Plugin Version: 0.1.0.2069

**Comment by vlad20012** [comment]
Ok, this should be fixed by these 3 PRs

**Comment by Undin** [comment]
Fixed
