### ISSUE TITLE
Type recognize was broken

### ISSUE THREAD

**Issue by Gedweb** [intellij-rust/intellij-rust#1812]
After last update IDE cannot find type declaration of `stdlib`.
Plugin version: 0.1.0.2069
IDEA 2017.2.5

**Comment by matklad** [comment]
Could you share a project where stdlib is not detected properly?

Could you check that the project is displayed properly in Cargo toolbar?

![image](https://user-images.githubusercontent.com/1711539/31117174-95e23c9c-a831-11e7-9089-c216308e7e25.png)

Are there any errors if you use the refresh button on the toolbar?

**Comment by Gedweb** [comment]
My project have more then one module. One of modules based on Angular (TypeScript)
Have no any errors on toolbar.  "Invalidate cache and restart" has same result.
Yes, i can share my project, but not here )

![screenshot from 2017-10-03 14-26-14](https://user-images.githubusercontent.com/6544152/31123079-17022c0a-a847-11e7-9d66-0c96a0e3338c.png)

**Comment by matklad** [comment]
Ah, you actually use the previous version, the current one is `0.1.0.2070`. Could you try updating the plugin? I have a feeling that this is #1800.

**Comment by matklad** [comment]
>Could you try updating the plugin?

Please note that we've reworked our project model, so instead of adding IDEA modules, you need to link additional Cargo projects via the Cargo toolwindows (the green :heavy_plus_sign: sign).

**Comment by Gedweb** [comment]
So, plugin update and recreate project structure (sad) solve this problem.

**Comment by Dragonrun1** [comment]
So it's very confusing what it wants here since every path to the stdlib it rejects.
![bad_lib_paths](https://user-images.githubusercontent.com/1431541/31747807-cfa314a8-b423-11e7-8547-2cfc01618e50.PNG)

**Comment by Dragonrun1** [comment]
So it's very confusing what it wants here since every path to the stdlib it rejects.
![Uploading Bad_lib_paths.PNG…]()
