### ISSUE TITLE
With Non-[Default] channel, `cargo test` is broken when ‘Show stdout/stderr in tests.’

### ISSUE THREAD

**Issue by sanmai-NL** [intellij-rust/intellij-rust#1814]
```sh
rustup run nightly cargo test -- --nocapture
```
Fails with:
```
error: Unknown flag: '--nocapture'

Usage:
    cargo test [options] [--] [<args>...]
```
This also happens in the situation in the issue title.

Either this is a bug in Cargo or `intellij-rust` should not generate a broken command line.

**Comment by matklad** [comment]
What is the output of `rustup run nightly cargo version`? This seems like Cargo issue...

**Comment by sanmai-NL** [comment]
`cargo 0.23.0-nightly (e447ac7e9 2017-09-27)`

**Comment by matklad** [comment]
Hm, does `rustup run nightly cargo test -- --nocapture` command work from command line for your project?

For me, `cargo 0.23.0-nightly` seems to work from both command line and IDE, so this looks pretty mysterious!

**Comment by sanmai-NL** [comment]
```sh
rustup run nightly sh -c 'cargo test -- --nocapture'
```
works for me.

```sh
rustup run nightly cargo test -- --nocapture
```
fails:
```
error: Unknown flag: '--nocapture'

Usage:
    cargo test [options] [--] [<args>...]
```
## Meta
```sh
 rustup -V
```
```
rustup 1.6.01
```

**Comment by matklad** [comment]
Aha! Looks like version of rustup is important, it works with 1.5.0 and fails with 1.6.0!

**Comment by matklad** [comment]
Filed https://github.com/rust-lang-nursery/rustup.rs/issues/1262

**Comment by matklad** [comment]
That said, we probably should switch to `+nightly` syntax anyway, as it's more readable.

**Comment by sanmai-NL** [comment]
@matklad: shall I open another issue for the `+nightly` syntax?

**Comment by matklad** [comment]
>@matklad: shall I open another issue for the +nightly syntax?

Yeah, and let's close this one in favor of it!
