### ISSUE TITLE
Commands don't run `error: toolchain 'Nightly' is not installed`

### ISSUE THREAD

**Issue by sanmai-NL** [intellij-rust/intellij-rust#1827]
This bug is due to #1826. Lack of testing as warned for in the PR ...

**Comment by matklad** [comment]
Hm, I think `rustup run nightly` and `cargo +nightly` are equivalent? That is, the former one should complain about `toolchain nightly is not installed` as well?

**Comment by sanmai-NL** [comment]
The problem is that the `toString` method on `RustChannel`s has a caption with a capital that does not match the actual name. See https://github.com/intellij-rust/intellij-rust/blob/6e996235bd63597afeee1304553d1ef53f3fe1ca/src/main/kotlin/org/rust/cargo/toolchain/RustChannel.kt#L9-L12

I propose to do away with the initial capital in the channel titles. They do not add value IMHO and [channels are not represented with capitals in user documentation either](https://github.com/rust-lang-nursery/rustup.rs/tree/533f09818fff23ba55a7c60474f3798d41bdd69d#keeping-rust-up-to-date).

**Comment by sanmai-NL** [comment]
Of course regardless of the `toString()` implementation, it would be proper to use the `rustupArgument`, the third field in the triple. But that field can be `null`. Wouldn't it be better to refactor the code and drop the distinction between the second and third fields. `toString()` for `DEFAULT` can return `""`. That syntax would work with `cargo +channel` and would be obvious in the UI as well.

**Comment by sanmai-NL** [comment]
I’m working a slightly better solution now.

**Comment by matklad** [comment]
Yeah, and I think we need a test for it :) 

I don't think it's worth the hassle to launch a real rustup though, but a Unit test that creates a Cargo command line, turns it into a GeneralCommandLine, renders it to sting and checks that it looks reasonable is worth adding.

**Comment by matklad** [comment]
Here's an example of a similar in spirit test: https://github.com/intellij-rust/intellij-rust/pull/1668/files#diff-c1d7d0db62d5fcf36f5890eb4fcfe7bb

**Comment by sanmai-NL** [comment]
I did a live test with the fix in #1828. How to write a unit test in the way you describe isn’t obvious to me and I have some pressing other work to do ... I hope you can add the test this time, in case I contribute in the future I will ensure a unit test is added.

**Comment by Undin** [comment]
@matklad I think you wanted to write this in PR :smile:
