### ISSUE TITLE
Deprecated items are suggested as completion to `crate_name::mod_name::`

### ISSUE THREAD

**Issue by sanmai-NL** [intellij-rust/intellij-rust#1832]
E.g., `use hyper::mime::` suggests `TEXT_JAVSCRIPT` even though it's [deprecated](https://github.com/hyperium/mime/blob/f8e7bd3d35db21cd8e16b40d2d5aafc43f840d89/src/lib.rs#L718-L720). Using latest nightly of `intellij-rust`.

**Comment by Kobzol** [comment]
Deprecated items are no longer suggested in `use` statements. Probably resolved already.

**Comment by vlad20012** [comment]
Deprecated items are still in completion, but with the lowest priority.

**Comment by Kobzol** [comment]
Indeed they are in completion when i.e. impl methods are considered, but at least for me on master they are ignored in `use module::<..>` statements, which was probably the goal of this issue.

**Comment by vlad20012** [comment]
Works for me
![image](https://user-images.githubusercontent.com/3221931/57465456-509b0980-7287-11e9-9de6-8f9b15f98f6d.png)

**Comment by Kobzol** [comment]
Ah, sorry for the confusion. I tried it specifically with Hyper as was mentioned in this issue, on Hyper 0.10 `TEXT_JAVSCRIPT` is not suggested. But it is actually caused by their use of `#[doc(hidden)]`. Nevermind :)
