### ISSUE TITLE
Add a way to locate the implementation of a trait for a particular type

### ISSUE THREAD

**Issue by jrmuizel** [intellij-rust/intellij-rust#1839]
There's no easy way to know where a trait implementation is defined. (i.e. it could be defined near the trait or near the struct). Being able to jump to the correct location would be very valuable.

**Comment by vlad20012** [comment]
Hmm, ctrl+alt+B or click to the green icon little to the left of a trait/struct? Or I did not understood the problem.

**Comment by vlad20012** [comment]
![image](https://user-images.githubusercontent.com/3221931/31377219-03cbefe0-adb0-11e7-8a50-d7cb6268c1c5.png)

**Comment by jrmuizel** [comment]
Yes. That's exactly what I was looking for. I did notice that it doesn't seem work for types in the standard library like String or Vec. Is it possible to make it work there too?

**Comment by vlad20012** [comment]
Hmm, it works for me
![image](https://user-images.githubusercontent.com/3221931/31403687-87283e32-ae02-11e7-9c17-9b5f00569de0.png)

**Comment by jrmuizel** [comment]
Ah it looks like it does for me too. It just takes a little while to show up.

**Comment by vlad20012** [comment]
=)
Just use ctrl+alt+B. It works immediately
