### ISSUE TITLE
console output (stderr?) is no longer displaying in red

### ISSUE THREAD

**Issue by mmlinford** [intellij-rust/intellij-rust#1842]
I recently updated to the latest version and the colorful console output seems to have stopped working (it's only showing white text and blue links). It seems to be happening across all of my run configurations.

**Comment by LooMaclin** [comment]
Same behavior.

**Comment by matklad** [comment]
For what commands does it happen?

**Comment by mmlinford** [comment]
@matklad for me it was happening for both `run` and `test`

**Comment by LooMaclin** [comment]
@matklad 
![image](https://user-images.githubusercontent.com/10957765/31428130-68970276-ae72-11e7-8255-c7cf9fe916b5.png)
