### ISSUE TITLE
Local variable type hint is sometimes redundant

### ISSUE THREAD

**Issue by HighCommander4** [intellij-rust/intellij-rust#1850]
Local variable type hints are generally useful, but sometimes they are reundant, for example:

```
struct Point {
  x: i32,
  y: i32
};

fn foo() {
  let x = Point{ x: 42, y: 42 };
}
```

Here, showing a local variable hint for `x` is redundant, because the type name is right there as the first token of the initializer expression. I think in a case like this, the editor could be smarter and not show the hint.

**Comment by matklad** [comment]
@farodin91 wanna take a look? :)

**Comment by farodin91** [comment]
jo
