### ISSUE TITLE
COMP: No completion in this case

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#1857]
```rust
struct S<T> {
    t: T
}

trait Tr {
    fn foo(&self);
}

impl<T: Tr> S<T> {
    fn into<D: Tr>(self) -> S<D> {
        self.t.<caret>
    }
}
```

It's relevant only for completion. If write there `self.t.foo()` it will be resolved.

**Comment by matklad** [comment]
The most common cause for similar completion bugs is `originalFile` lost somewhere.

**Comment by Undin** [comment]
@vlad20012 do you still can reproduce it?
For me it works fine

**Comment by vlad20012** [comment]
Yep, it's fixed
