### ISSUE TITLE
Renaming directory module renames the `mod.rs`

### ISSUE THREAD

**Issue by torkleyy** [intellij-rust/intellij-rust#1859]
Given a module `foo`, renaming foo in the `mod foo;` declaration will rename the `mod.rs` instead of the directory.

**Comment by farodin91** [comment]
@matklad Try to solve this, but some architecture need to changed because you can not rename PsiDirectory with an rename processor. Therefore, files should not implement directly RsMod. Think we need to add an layer, correct?

**Comment by matklad** [comment]
Hm, I am almost sure that you can implement custom logic for renaming a directory...

**Comment by farodin91** [comment]
I have currently no idea, tried different workaround with changing file function setName.

**Comment by matklad** [comment]
RenameHandler should be able to anything with renamings I think: http://www.jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support/rename_refactoring.html

However, my gut feeling (without digging into the code, so I might be wrong), that PsiRenameProcessor should be enough here.
