### ISSUE TITLE
NoClassDefFoundError: org/rust/cargo/project/config/RustConfigForm

### ISSUE THREAD

**Issue by hsarkar** [intellij-rust/intellij-rust#186]
IntelliJ 15.0.2
Java 1.8.0_65

On clicking Preferences -> Other settings -> Rust it gives the following error

![abc_rs_-_sumo_-____development_sumo_](https://cloud.githubusercontent.com/assets/3184826/11912338/39ccc354-a65e-11e5-9e1a-e0ba5fa6e5e4.png)

Auto complete doesn't work in rust source files

**Comment by matklad** [comment]
>Auto complete doesn't work in rust source files

Yes, there is no semantic auto complete at the moment :) You can use expand word (`Alt + /`) to complete based on the words in a file
