### ISSUE TITLE
No single source of truth for cargo binary name.

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#187]
In `CargoInstallationManager` cargo executable is found from `RustSdkType`, which is correct: https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/cargo/service/CargoInstallationManager.kt#L25

In `CargoProjectResolver` it is found via a global setting: https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/cargo/project/CargoProjectResolver.kt#L47

Am I correct that the second one should be corrected to use `RustSdkType` as well? and that we can probably remove `RustSettings` altogether?

**Comment by alexeykudinkin** [comment]
Did you mean `CargoSettings`? Nope, we can't (and should not) remove them.

Though we definitely need to align this place with `CARGO_BINARY_NAME` usage.

**Comment by alexeykudinkin** [comment]
Could you, please, fix that? @matklad

**Comment by matklad** [comment]
yep
