### ISSUE TITLE
Toolchain settings forgotten on project load

### ISSUE THREAD

**Issue by ambaxter** [intellij-rust/intellij-rust#1870]
After the latest update (0.2.0.2073), no matter what I do I get the following error when opening a project:

```
Cargo project update failed:
	Can't update Cargo project, no Rust toolchain
```

Clicking "Setup toolchain", then "Ok" fixes the problem, but on the next reload the plugin loses the toolchain information again.

**Comment by matklad** [comment]
Ouch, that was a bad bug, thanks for the report!
