### ISSUE TITLE
Quick documentaion should contain link to the on-line docs

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1875]
PyCharm has a useful feature where it adds an "View external documentaion" link to the quick-doc popup (<kbd>Ctrl+Q</kbd>):

![image](https://user-images.githubusercontent.com/1711539/31652665-864f3a4e-b328-11e7-8ee4-bca7e4051252.png)

I think we should do the same for Rust, using `docs.rs` and `https://doc.rust-lang.org/std/`. 

The entry point for the relevant feature is `org.rust.ide.docs.RsDocumentationProvider`.

**Comment by matklad** [comment]
Wow, turns out we have a dedicated shortcut for viewing external docs: https://www.jetbrains.com/help/idea/viewing-external-documentation.html, which is used by PyCharm, for example. 

We need to do this as well, though it's E-less-easy, because I don't know off hand which API we should use.

**Comment by matklad** [comment]
Looks like we need to implement `ExternalDocumentationHandler`.

**Comment by Kobzol** [comment]
This seems to be resolved (https://github.com/intellij-rust/intellij-rust/pull/2555).
