### ISSUE TITLE
Fail to auto complete or go to declaration for multiple crates in one project

### ISSUE THREAD

**Issue by xinghun92** [intellij-rust/intellij-rust#1876]
It works well util I upgrade the plugin, unfortunately I forget the previous version of the plugin. But my colleague's MAC works well with same rust version, plugin version and PyCharm version. I find my PyCharm works well if  the project only contains one crate, but for project with multiple crates like diesel it does not work even to auto complete std lib. So I think there may be some errors in my settings.
```
Rust version: 1.22.0-nightly (4e9527cf6 2017-10-16)
Plugin version: 0.2.0.2074
PyCharm version: 2017.02.03
Mac version: 10.12.6
```
￼
<img width="988" alt="dingtalk20171017235536" src="https://user-images.githubusercontent.com/17715355/31675270-b4a6184a-b396-11e7-8035-2a45ea3041d5.png">
￼
I do not know what is wrong with my settings.

**Comment by matklad** [comment]
Could you check Cargo toolwondow as well https://github.com/intellij-rust/intellij-rust/issues/1812#issuecomment-333780717?

**Comment by xinghun92** [comment]
The cargo toolwindow show only rusqlite while diesel is not in it. Add diesel to cargo toolwindow fix it, thanks!

<img width="1166" alt="dingtalk20171018124411" src="https://user-images.githubusercontent.com/17715355/31701406-ce82bee0-b395-11e7-9ac1-84f2dad8299b.png">

**Comment by matklad** [comment]
Yeah, we really should add some warning for this case ....
