### ISSUE TITLE
Go to definition / autocompletion fails, although IntelliJ can access the source code

### ISSUE THREAD

**Issue by Hoeze** [intellij-rust/intellij-rust#1878]
I just cloned "python-librespot" and opened it with IntelliJ.
Then I tried to open the source code of "player", but IntelliJ does not find its definition.
I also tried adding the librespot source code directly, but this does not help either.
![bug_crop](https://user-images.githubusercontent.com/1200058/31689925-60bd5194-b391-11e7-8412-0957f746cf7e.png)
Opening "player.rs" directly over external libraries works, though.

**Comment by matklad** [comment]
We don't support macros yet unfortunately :(

**Comment by Hoeze** [comment]
OK, but this isn't a macro, is it?

The problem is that opening code definitions works inside a project but not with library dependencies:
Opening definitions works, if the code is available as a cargo sub-project in the workspace.

**Comment by mkaput** [comment]
This is code snippet inside `py_class!` macro invocation. Whenever we encounter anything macro-related we stop parsing it at this moment, that's why nothing works (excluding elementary token highlighting)

**Comment by Hoeze** [comment]
Ah, thank you for clarifying :)

**Comment by matklad** [comment]
Yeah, at the moment, we don't understand that the thing after `data` is a path at all, and so we don't know that we should show completion.

Closing as a part of a larger https://github.com/intellij-rust/intellij-rust/issues/229
