### ISSUE TITLE
Procedural macro libraries: extern crate proc_macro not found

### ISSUE THREAD

**Issue by alekratz** [intellij-rust/intellij-rust#1879]
Procedural macros (aka custom `derive`s) [require some special set-up in the Cargo.toml file](https://doc.rust-lang.org/book/first-edition/procedural-macros.html), with a `proc-macro = true` line under the `[lib]` section to allow usage of the `proc_macro` crate. The plugin doesn't seem to be aware of this and shows the crate as missing.

NB: I was using this on my personal [`enum-methods` crate](/alekratz/enum-methods), if you clone it and look at `src/lib.rs` in IntelliJ you'll see what I mean.

**Comment by Undin** [comment]
Now `rust-src` component for the latest nightly rust contains `proc-macro` sources so I think it can be closed
