### ISSUE TITLE
Add semicolon on completion of use item

### ISSUE THREAD

**Issue by mhaessig** [intellij-rust/intellij-rust#1888]
When completing a use item with a struct, traits const or static add the semicolon at the end if needed (like #1881).

**Comment by mhaessig** [comment]
@matklad Could we also insert a semicolon after a glob list?

**Comment by matklad** [comment]
Yeah, I think we can make typing `{` after `use foo::` to auto-insert `};`, but this is handled by completely separate machinery.

**Comment by mhaessig** [comment]
So a separate issue?

**Comment by matklad** [comment]
Yep!

**Comment by Kobzol** [comment]
This has been already fixed by https://github.com/intellij-rust/intellij-rust/pull/1901 and https://github.com/intellij-rust/intellij-rust/pull/2142.
