### ISSUE TITLE
Cannot edit right margin location

### ISSUE THREAD

**Issue by HighCommander4** [intellij-rust/intellij-rust#1889]
Under Settings -> Code Style -> Rust -> Wrapping and Braces, the "Right margin (columns)" setting is set to 100 and cannot be edited. It would be good to be able to edit this.

**Comment by ortem** [comment]
Fixed
<img width="438" alt="screen shot 2018-10-17 at 13 31 41" src="https://user-images.githubusercontent.com/4854600/47080572-041bae00-d211-11e8-91a8-a16444f9f28f.png">
