### ISSUE TITLE
Confusion about `RustBundle.properties`

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#189]
We have [RustBundle](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/resources/org/rust/lang/i18n/RustBundle.properties) with about 50 strings, but only three of them are actually used. This is suspicious. 

Should we remove the bundle or should we remove inlined user facing strings from the source code?

**Comment by Turbo87** [comment]
see https://github.com/intellij-rust/intellij-rust/commit/381316a9a1547e8d0db8cac57002d6122e91cafe#commitcomment-14543621

**Comment by matklad** [comment]
Ok, will eradicate them
