### ISSUE TITLE
Highlight overloaded operators

### ISSUE THREAD

**Issue by adiba** [intellij-rust/intellij-rust#1890]
In CLion, overloaded operators in C++ are highlighted in (a different) color:
![image](https://user-images.githubusercontent.com/23532559/31835011-4aa033f4-b5d0-11e7-907a-84893d0eb265.png)

Could we have this in intellij-rust?

related: https://github.com/intellij-rust/intellij-rust/issues/1892

**Comment by vlad20012** [comment]
Hmm, I think yes, but is it really useful feature?

**Comment by Undin** [comment]
I personally don't know about operators in CLion, but I think we can implement goto definition for operators like kotlin plugin does
At least I thought about it:)

**Comment by mkaput** [comment]
> is it really useful feature?

Yes it is, not only it visually tells that this operator might have non-typical behaviour, but also it is navigation point. R# also does this for both C# and C++

**Comment by adiba** [comment]
Now some operators are being highlighted for some reason. Has there been work on this?
Operators on primitives are highlighted as well though.

**Comment by vlad20012** [comment]
Yep, it's done by #1894

**Comment by adiba** [comment]
Great!
I'd like to point out that it's not consistent, at least not for me:

![image](https://user-images.githubusercontent.com/23532559/35469665-2898622e-033a-11e8-9284-0f52be092c3a.png)

Additionally, the point of this is to differentiate between primitive operations/simple hardware instructions and more complex ops, so again, primitive ops shouldn't be highlighted @Undin .
