### ISSUE TITLE
`unsafe` is not added for "Implement methods"

### ISSUE THREAD

**Issue by kryptan** [intellij-rust/intellij-rust#1895]
I have code like this:

```Rust
trait Trait {
    unsafe fn f();
}

impl Trait for () {
}
```

I click Alt+Enter on `impl Trait for ()` and select "Implement methods". IDE then adds stub `fn f() ` instead of `unsafe fn f()`.

**Comment by matklad** [comment]
The entry point here is `org.rust.ide.annotator.fixes.ImplementMembersFix`.
