### ISSUE TITLE
Macro arguments are highlighted incorrectly if they are keywords

### ISSUE THREAD

**Issue by kryptan** [intellij-rust/intellij-rust#1898]
In the following screenshot `var`, `let` and `type` are semantically the same thing - a macro argument, yet they are highlighted differently.

![image](https://user-images.githubusercontent.com/11528855/31867149-b80eab14-b792-11e7-92b7-c0a4b1fde145.png)

**Comment by Kobzol** [comment]
This doesn't happen in the latest version, `var`, `let` and `type` are highlighted as macro parameters.
