### ISSUE TITLE
Structure view does not show template constraints

### ISSUE THREAD

**Issue by jbayardo** [intellij-rust/intellij-rust#1899]
As of 0.2.0.2074, impls of templated types with different trait constraints on the template will display the same, though being different. For example

```
struct A<K> { ... }

impl<K: Ord> A<K> { ... }
impl<K: Display> A<K> { ... }
```

Will show in the Structure view as `A<K>` (although in separate items). I think they should be displayed separately, perhaps something like

```
A<K : Ord> (dropdown)
A<K : Display> (dropdown)
```

**Comment by matklad** [comment]
The relevant function is `org.rust.ide.presentation.UtilsKt#getPresentationForStructure`.
