### ISSUE TITLE
Plugin cannot find stdlib

### ISSUE THREAD

**Issue by tdyas** [intellij-rust/intellij-rust#1906]
The IntelliJ rust plugin displays the following error in the IntelliJ "Event Log" pane:

```
Cargo project update failed: no explicit stdlib or rustup found
```

My machine runs macOS High Sierra. I am using Rust 1.21.0 (installed via brew), IntelliJ 2017.2.5, and version  0.2.0.2075 of the IntelliJ Rust plugin.

The "Standard library" setting on the Settings > Languages & Frameworks > Rust pane is empty. Should that be set to something or should I be using rustup?

**Comment by matklad** [comment]
Yeah, `rustup` is usually the most convenient way to use Rust, and the most convenient for IDEs as well. You can get rustup over here: https://www.rust-lang.org/en-US/install.html.

If you do want to use non-rustup based toolchain, you need to download rust source code from https://github.com/rust-lang/rust and add it via settings.
