### ISSUE TITLE
Handle include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

### ISSUE THREAD

**Issue by jrmuizel** [intellij-rust/intellij-rust#1908]
The bindgen user manual suggests using:
`include!(concat!(env!("OUT_DIR"), "/bindings.rs"));`
as the way to use the generated code. IntelliJ seems to not follow this and thus gives no information/completion for the generated rust code.

Although `include` can take arbitrary compile-time args (or almost), the vast majority of real usages of `include` macro contains only:
* [x] string literals #3935
* [x] `concat` macro #4194
* [ ] `env!("OUT_DIR")` #4542

**Comment by jrmuizel** [comment]
@matklad is this easy to fix? If it is I'd like to give it shot if I get some guidance on how to do it.

**Comment by matklad** [comment]
That partial fix here should be more or less straightforward. Here's the place where we handle macros: https://github.com/intellij-rust/intellij-rust/blob/631a4e3a81b6fd5780a5cf0687605ce9c1319ed9/src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt#L581. I think we need to hard code include here: 

1) calculate the path, assuming that OUTPUT_DIR is just target 
2) find the RsFile using findFileByIoFile function 
3) process all names from it

**Comment by SOF3** [comment]
OUT_DIR is not just target. It is something that looks like `target\debug\build\cube-engine-abc40c94fb8a8059\out/protocol.rs`

**Comment by micfan** [comment]
add use case in https://github.com/tower-rs/tower-grpc/issues/186

**Comment by Riateche** [comment]
What's the state of this issue? It would be very nice to have auto-completion for generated code. It's one of the major pain points right now.

**Comment by Undin** [comment]
@Riateche plugin already supports `include` with string literals like `include!("bindings.rs")` and also will support `concat` macro as argument (`include!(concat!("foo", "bindings.rs"))`) since next release.
`env("OUT_DIR")` is not supported yet

**Comment by onelson** [comment]
I'm working with tonic (which I'm guessing is very closely related to tower-rs/tower-grpc#186 in terms of macro usage) and this feature doesn't seem to be working for me in v0.2.113.2150-193 in CLion 2019.3.1.

Wondering if this is a regression, or if I am just missing some config step. My project has several crates in it, but I don't see completions for the codegen module with or without a workspace defined at the project root.

**Comment by Undin** [comment]
@onelson it's not regression, but unfortunately, the `env!("OUT_DIR")` support is disabled by default. More info about why it was done can be found in #4573.
I've updated issue description with relevant status

**Comment by onelson** [comment]
I turned on the experimental feature, and gave it a spin. Seems like it will let me jump to the struct definitions where they lay in the out dir, but can't offer any completions based on the struct's default impl.

This is to say, the completions only go so far as modules and structs, but no methods. Is that expected?

**Comment by Undin** [comment]
> but can't offer any completions based on the struct's default impl.

@onelson is `impl` block generated by macro? If yes then try to enable new experimental macro expansion engine #3628

**Comment by onelson** [comment]
I had the new expansion engine on, but still no joy.

Here's the module produced by the build script, which is then brought in to my module via `include!()`.

https://gist.github.com/onelson/30abe1f04eb9fbba47080cef9ae30ea3#file-chatroom-rs-L724

I'm able to jump to the definition of `ChatroomClient` but the editor knows nothing about the `ChatroomClient::connect()` method (or any other methods here).

Some observations...

- If I jump to the definition for `ChatroomClient`, it takes me to the file produced by the build script (in the out dir), not where that module source is included in my actual project code.
- viewing the build script generated module in CLion, there's a ribbon along the top explaining analysis is disabled since this file is not a part of the module tree."

![image](https://user-images.githubusercontent.com/301388/72778477-f56b3600-3bcd-11ea-80d3-aa22282b0393.png)

**Comment by asimaranov** [comment]
The same issue when I'm using the gl crate (https://github.com/brendanzab/gl-rs/tree/master/gl)
![image](https://user-images.githubusercontent.com/25568730/73165723-69916680-4105-11ea-9d2f-bb02a41d27c4.png)

**Comment by JoHaHu** [comment]
I have the same issue. This only includes the file specified in the include! macro. If this file declares other generated module, then the locations of these modules are not recognized by the IDE.

**Comment by nixomose** [comment]
Hiyeeee.
So I've been waiting for this for a bit, and finally it's here. It's exactly what I need because I want the results of:

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

to index and work in autocomplete.
so I got the 2/18/2020 plugin, I invalidated caches, I went home and went to sleep and came back, and ....

it still doesn't work.

any idea how I can figure out what's going wrong?

**Comment by Undin** [comment]
@nixomose is `org.rust.cargo.fetch.out.dir` or `org.rust.cargo.evaluate.build.scripts` experimental feature enabled? if no, try to enable `org.rust.cargo.evaluate.build.scripts` (see #4734 for more details)

**Comment by onelson** [comment]
I have both enabled, but I was seeing the same "no completions" result as before.

Maybe a small repro project could help decide if this is a new/different problem warranting a new issue, or if these comments really belong here.

**Comment by Undin** [comment]
> Maybe a small repro project could help

@onelson oh, it would be great, indeed!

**Comment by onelson** [comment]
@Undin I took the smallest example in the tonic project offer and prepared it such that it could be built outside of their source tree.

- https://github.com/onelson/tonic-hello

In https://github.com/onelson/tonic-hello/commit/96fc3c7ef0d4b58a5ebb6ad1d62bfe3d0eda57a1 I tagged the places where a macro was used to include the source generated by the build script.

Initially, I suspected the fact my projects were using a cargo workspace might be breaking the completions, but this example doesn't use workspaces and displays the same issue.

It may be possible to refine the repro case, to simplify it, by stripping out just the build/include parts of tonic, but I'm maybe you'll be able to find a hint from this as-is.

**Comment by onelson** [comment]
I should add that I started at the most bare bones test:

- hand-writing a build script that writes a string to a file in the OUT_DIR
- include!() the file in another module
- all in the same crate

The steps outlined above must be the case the issue was building towards since it worked perfectly. I'm not sure what tonic (and others) are doing differently to cause an issue.

**Comment by onelson** [comment]
Experimenting with tonic-hello a little bit, I noticed the `tonic::include_proto!()` macro was implemented as

```rust
#[macro_export]
macro_rules! include_proto {
    ($package: tt) => {
        include!(concat!(env!("OUT_DIR"), concat!("/", $package, ".rs")));
    };
}
```

I decided to try replacing it with the code it would generate:

```
diff --git a/src/bin/server.rs b/src/bin/server.rs
index 34c63e8..0fdeacd 100644
--- a/src/bin/server.rs
+++ b/src/bin/server.rs
@@ -5,7 +5,7 @@ use hello_world::{HelloReply, HelloRequest};                                                       

 pub mod hello_world {
     // FIXME: symbols included here are without completions                                                       
-    tonic::include_proto!("helloworld");
+    include!(concat!(env!("OUT_DIR"), concat!("/", "helloworld", ".rs")));                                        
 }

 #[derive(Default)]
```

Completions work in this case!

This might be a viable workaround when working with `tonic`, but it seems like there are going to be more complex versions of this where substitution may not be so easy.

**Comment by Undin** [comment]
@onelson Oh, thanks a lot for your investigation!
Generated `include!` by macro call is real cause why completion doesn't work. We indeed doesn't support such case (see https://github.com/intellij-rust/intellij-rust/blob/7f91d8bbfff68f9ac1db903b420efe21b5ae6e3f/src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt#L113-L119)

I've created separate issue for it - #5036

**Comment by masihyeganeh** [comment]
There is a new `out-dir` in the `[build]` section on new nightly builds (See [rust-lang/cargo#7555](https://github.com/rust-lang/cargo/issues/7555#issue-514466453))
It can be used to get the out dir and fallback to previous method if this does not exists.
It worth noting that build-plan [is going to be deleted](https://github.com/rust-lang/cargo/issues/7614), so it maybe the only way to get the out dir.

**Comment by bugproof** [comment]
How to enable that experimental feature??? could anyone send a screenshot?

**Comment by bugproof** [comment]
I solved it for now by generating to `src/bindings.rs` and just using `pub mod bindings;` instead of `include!` macro. What benefits including from OUT_DIR even gives??

**Comment by Undin** [comment]
> How to enable that experimental feature???

@bugproof  Type `Experimental Features` in `Help | Find Action` dialog to open the experimental features dialog and enable desired option

**Comment by wanghao0123** [comment]
> @nixomose is `org.rust.cargo.fetch.out.dir` or `org.rust.cargo.evaluate.build.scripts` experimental feature enabled? if no, try to enable `org.rust.cargo.evaluate.build.scripts` (see #4734 for more details)

thanks，that works for me

**Comment by sburton84** [comment]
For anyone finding this isn't working in the latest CLion, and coming across this issue, I have found that I needed to enable the `org.rust.macros.proc` experimental feature to get this working. (You may also need `org.rust.cargo.evaluate.build.scripts` as mentioned above but for me it seemed this was already enabled by default.)
