### ISSUE TITLE
Rust toolchain setup requiring absolute paths?

### ISSUE THREAD

**Issue by norru** [intellij-rust/intellij-rust#1919]
I'm developing across Windows and Linux. Checking in the project in Windows and checking out in Linux causes a "Toolchain not found error" as the following toolchain

C:\Users\niguo\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src

1) c:\Users does not exist in Linux
2) it refers to the msvc toolchain
3) the rust toolchain configuration does not seem to be handling env vars

Is there a way I can refer to toolchains with their rustup channel name, or alt? (stable/nightly/testing/etc). I am really not keen on publishing a project containing absolute paths to my (Windows) filesystem and also not keen on manually changing paths before each and every git commit. Is it safe to .gitignore `misc.xml`?

**Comment by matklad** [comment]
Yep, it's safe (and I would say advisable) to ignore `misc.xml`. Toolchain paths are by their nature machine specific, so you can share them in meaningful way. 

If you are using rustup, then toolchain is discovered automatically, so no additional setup per project is required. Rustup's channels are stored separately, per run configuration, and run configurations are shareable (they are stored in `.idea/runConfigurations`, you have to check the `shared` checkbox in run configuration settings to put it there).

**Comment by norru** [comment]
I've tried to remove misc.xml altogether and didn't work as it contains a reference to "CargoProjects". However, the following macro seems to work. I only have to be careful to check misc.xml in once (with the correct path) and then perhaps ignore it:

 <option name="toolchainHomeDirectory" value="$USER_HOME$/.cargo/bin" />

Thanks for your suggestions!
