### ISSUE TITLE
Support CLion 2017.3

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1923]
from #1937:

When opening with CLion on OSX (CLion 2017.3 EAP, Build #CL-173.3415.24) and trying to debug, I get:

Error running 'Run HelloWorldRust': com/jetbrains/cidr/cpp/CPPToolchains

Unfortunately, there is no stacktrace that I can see, nor is there anything in the IDEA log files, that's the extent of the error I get.

I've tried changing the debugger to GDB but that doesn't seem to help. I can debug C++ normally, so I'm not sure what the problem is.

**Comment by matklad** [comment]
Okey, so turns out 2017.2 and 2017.3 are not API compatible, so we can't support both at the same time. The plan is to switch to 2017.3 only as soon as it is released.

**Comment by matklad** [comment]
There's a branch with 2017.3 support here: https://github.com/intellij-rust/intellij-rust/tree/clion-2017.3. It's possible to build plugin off it locally and install it into CLion EAP.

**Comment by norru** [comment]
Thanks, there is another regression I just found on 2017.3:

Here's how Cargo toolchain dir is saved in `misc.xml` in 2017.2. Correctly, it's using `$USER_HOME$`
```
  <component name="RustProjectSettings">
    <option name="toolchainHomeDirectory" value="$USER_HOME$/.cargo/bin" />
    <option name="useCargoCheckAnnotator" value="true" />
  </component>
```

In 2017.3, editing the `Settings -> Languages & Frameworks` tab causes the setting to switch to absolute path, which breaks the project for anyone else.

```
   <option name="toolchainHomeDirectory" value="C:\Users\niguo\.cargo\bin" />
```

I've tried to remove the `misc.xml` file altogether from the repo but it breaks all toolchain settings when checking the project out afresh.

**Comment by matklad** [comment]
>In 2017.3, editing the Settings -> Languages & Frameworks tab causes the setting to switch to absolute path, which breaks the project for anyone else.

Fixed in https://github.com/intellij-rust/intellij-rust/commit/08d020d25d97a734e337ca51840d2d965942078e

**Comment by Undin** [comment]
Current plugin version supports CLion 2017.3 so I think we can close this issue
