### ISSUE TITLE
Type inference renaming

### ISSUE THREAD

**Issue by jbayardo** [intellij-rust/intellij-rust#1924]
If you have two templated functions with the same return type template name:

```
fn a<Q>() -> Q {}
fn b<Q>() -> Q {}
```

And then have something that looks like `(a(), b())`, the plugin will type it as `(Q, Q)`. It should actually be something like `(Q1, Q2)`.

**Comment by ortem** [comment]
Now the inferred type of `(a(), b())` is `(<unknown>, <unknown>)`, so the bug seems to be fixed.
