### ISSUE TITLE
Compile & run inside docker

### ISSUE THREAD

**Issue by newtack** [intellij-rust/intellij-rust#1926]
I want to use Intellij-Rust on my Mac but have my Rust dependencies (including emscripten) inside of docker. Can I use docker to build and run the code from Intellij-Rust, if so how?

**Comment by berzi** [comment]
This is closed as completed but I couldn't find any explanation on how to actually do it.

**Comment by vlad20012** [comment]
@berzi The feature is available only in CLion, IntelliJ IDEA ultimate and other paid IDEs. The documentation can be found [here](https://blog.jetbrains.com/idea/2021/01/run-targets-run-and-debug-your-app-in-the-desired-environment/).

**Comment by codertao** [comment]
That seems to specifically be for running/debugging in docker. For my use case I have a development toolchain in docker that looks like a bit of a nightmare to get going on the dev machine. I've seen some stuff for using a docker toolchain in clion for C/C++ dev, but I don't think the rust plugin supports it?

**Comment by berzi** [comment]
> @berzi The feature is available only in CLion, IntelliJ IDEA ultimate and other paid IDEs. The documentation can be found [here](https://blog.jetbrains.com/idea/2021/01/run-targets-run-and-debug-your-app-in-the-desired-environment/).

I own CLion but I'd like to have code completion etc by keeping Rust on a container and not my host machine.

**Comment by Teebor-Choka** [comment]
This still does not seem to be possible, likely the issue to track to have a fully container sandboxed development environment is https://github.com/intellij-rust/intellij-rust/issues/3152
