### ISSUE TITLE
Error when debugging

### ISSUE THREAD

**Issue by Arcnor** [intellij-rust/intellij-rust#1937]
I've created a new project with IDEA (because CLion doesn't show Rust projects on the wizard) and I get a "Hello world" application running.

When opening with CLion on OSX (CLion 2017.3 EAP, Build #CL-173.3415.24) and trying to debug, I get:

```
Error running 'Run HelloWorldRust': com/jetbrains/cidr/cpp/CPPToolchains
```

Unfortunately, there is no stacktrace that I can see, nor is there anything in the IDEA log files, that's the extent of the error I get.

I've tried changing the debugger to GDB but that doesn't seem to help. I can debug C++ normally, so I'm not sure what the problem is.

**Comment by matklad** [comment]
@Arcnor Yeah, currently we don't support CLinon EAPs: 2017.2 and 2017.3 are backwards incompatible, so you can't support both without resorting to reflection. 

The issue to track is https://github.com/intellij-rust/intellij-rust/issues/1923

**Comment by Arcnor** [comment]
Thanks @matklad , will do that

**Comment by Arcnor** [comment]
Great! I also like that you have a full Gradle build for this (instead of the old IntelliJ path of forcing you to use IntelliJ itself, which doesn't really scale :D)

I'm having errors on the tests, though, is that expected? One of them is the inability to parse `mod.rs` from the Rust sources, but I'm on nightly, so that might be expected.

Besides that, I've installed the plugin, but when trying to debug, I'm getting an error about "More then one binary produced. Please specify --bin, --lib, or --test explicitly". (There is also a typo, it should be *than*)

I haven't modified the default running config, which is `run --bin MyTestApp`, and when I try to debug it's running `cargo build --color=always --bin MyTestApp`, so I'm a bit puzzled as to why it's saying that.

**Comment by matklad** [comment]
>I'm having errors on the tests while building the plugin, though, is that expected? One of them is the inability to parse mod.rs from the Rust sources, but I'm on nightly, so that might be expected.

Yeah, I've *temporary* disabled nightly tests a while ago and forgot to turn them back =/ It's on my working list though.

**Comment by matklad** [comment]
>I haven't modified the default running config, which is run --bin MyTestApp, and when I try to debug it's running cargo build --color=always --bin MyTestApp, so I'm a bit puzzled as to why it's saying that.

Hm, that should not happen I think. Will try to reproduce and debug this! (locally, debugging works fine for me).

**Comment by Arcnor** [comment]
Have you been able to try this? I've updated CLion again to the latest, but I'm getting the same error. I've also tried with a separate project, but the same happens.

Also, just to confirm, what I'm doing is generating the project using IntelliJ IDEA, then opening it with CLion and trying to debug the existing `Run` configuration of type `Cargo Command` with it.

**Comment by matklad** [comment]
@Arcnor I am not able to reproduce it unfortunately :( Could you share a project where you hit this issue?

**Comment by tstellanova** [comment]
> ...when trying to debug, I'm getting an error about "More then one binary produced. Please specify --bin, --lib, or --test explicitly". (There is also a typo, it should be _than_)
> 
> I haven't modified the default running config, which is `run --bin MyTestApp`, and when I try to debug it's running `cargo build --color=always --bin MyTestApp`, so I'm a bit puzzled as to why it's saying that.

I'm seeing the same problem Run > Output window shows:
```
/Users/todd/.cargo/bin/cargo build --color=always --bin mavwrangler
    Blocking waiting for file lock on the git checkouts
   Compiling mavlink v0.4.2 (/Users/todd/Documents/proj/rust-mavlink)
   Compiling mavwrangler v0.1.0 (/Users/todd/Documents/proj/mavwrangler)
    Finished dev [unoptimized + debuginfo] target(s) in 6.83s
```
and I get the error dialog "Debugging is not possible" "More then one binary produced. Please specify --bin, --lib, or --test explicitly"
