### ISSUE TITLE
Collapse use statements

### ISSUE THREAD

**Issue by itmuckel** [intellij-rust/intellij-rust#1939]
Some of my rust files have a lot of use statements.

As a programmer
I'd like to collapse the use statements
to reduce noise, when working on my code.

Please add a possibility to collapse use statements like you can collpase functions.

PS: Maybe a different issue, but collapsing crates would be nice, too.

**Comment by matklad** [comment]
If anyone wants to look into this, the code is in https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt.

**Comment by framlog** [comment]
I'm going to do this.

**Comment by Undin** [comment]
Implemented in #2101
