### ISSUE TITLE
Add a way to get the type of a selected sub expression

### ISSUE THREAD

**Issue by jrmuizel** [intellij-rust/intellij-rust#1944]
Sometimes the type of a particular sub expression is unclear. It would be great to be able to see what the type of a selected sub expression is.

**Comment by matklad** [comment]
Isn't this handled by selecting a subexpression and pressing ctrl + shift + p?

**Comment by jrmuizel** [comment]
Indeed. That seems to work perfectly. Is there a good guide to discovering these kinds of things?

**Comment by matklad** [comment]
Curious, looks like this particular shortcut is not really documented anywhere =\

In general, most features come from platform and are not Rust specific, including this one. They are usually documented here: https://www.jetbrains.com/idea/documentation/

It also helps to take a look at the default shortcuts: https://resources.jetbrains.com/storage/products/intellij-idea/docs/IntelliJIDEA_ReferenceCard.pdf

I'd love to write a blog post some day, describing the most helpful features of the plugin, but I haven't done that yet :(
