### ISSUE TITLE
Gutter icon doesn't create test command

### ISSUE THREAD

**Issue by la10736** [intellij-rust/intellij-rust#1964]
Start by a new bin project and click on run gutter icon. Now create a new test function like

```rust
#[test]
fn fail() {
    assert!(false)
}
```
and click on gutter icon to run the test but it will run just `cargo run` old command a don't create a new one.

This scenario also occurs for test modules and test function in test modules.

**Comment by mchernyavsky** [comment]
Duplicate of https://github.com/intellij-rust/intellij-rust/issues/1252.
