### ISSUE TITLE
Partial test coloring

### ISSUE THREAD

**Issue by la10736** [intellij-rust/intellij-rust#1966]
On ubuntu cargo test command coloring always behave like to use `--nocapture` flag also when I don't set _Show stdout/stderr in test_ and the colors of single test are not rendered.

![schermata del 2017-11-02 10-20-03](https://user-images.githubusercontent.com/3902961/32318430-8dcaab96-bfb7-11e7-96ee-f362a9edb965.png)

**Comment by la10736** [comment]
Maybe that is a duplicate of #1842 or something that is close to it

**Comment by la10736** [comment]
@matklad Any hints where I should look to fix it?

**Comment by matklad** [comment]
I think the cause is either in the `Cargo` class (we produce the actual command line there), or in the `getState` method of `CargoCommandConfiguration` (we produce an abstract representation of Cargo command there).

**Comment by la10736** [comment]
What I cannot understand is that `Cargo` class produce a correct command line `cargo test --color=always` but the this command behave different in *Run*'s window than how to behave in console one.

It seams to me that is not an issue about how `Cargo` class build the command line but how the *Run* canvas show the execution output because the cargo output like compilation data is correctly colored but test results no.

**Comment by la10736** [comment]
Ok, I don't find a simple way to solve it. 

A little debug session shows that stderr, where `cargo test` print test results, is always redirected to stdout and maybe without color info.

**Comment by la10736** [comment]
Maybe is a core issue: same behaviour with maven command.

**Comment by vaniakosmos** [comment]
any progress on this issue?
