### ISSUE TITLE
Disabling "Show argument name hints" does not work

### ISSUE THREAD

**Issue by eviltak** [intellij-rust/intellij-rust#1986]
The "Show argument name hints" option under Configure Parameter Hints cannot be disabled without disabling parameter hints entirely. The option re-enables itself every time I disable it. The other options do not show the same behaviour.

**Comment by searing** [comment]
I used to have this bug, but now with the latest Rust plugin version (0.2.0.2086), it seems to be fixed. (It may have been fixed before, I'm not sure.)
