### ISSUE TITLE
Non-clickable source code locations for altered cargo working directories

### ISSUE THREAD

**Issue by MattsGitCode** [intellij-rust/intellij-rust#1987]
With a multi-package workspace open, if the working directory of a cargo configuration is that of one of the packages, rather than the workspace, then paths in the compiler output are not turned into clickable links to the source code.

This situation is easy to get into inadvertently by clicking the green test button next to any unit test. This creates a new cargo configuration with the working directory set to that of the package under test.

**Comment by Kobzol** [comment]
This seems to work now.
