### ISSUE TITLE
Statement mover moves only first member in selection

### ISSUE THREAD

**Issue by mkaput** [intellij-rust/intellij-rust#1990]
![peek 2017-11-04 21-07](https://user-images.githubusercontent.com/3450050/32409049-5019379c-c1a4-11e7-8f2f-5bf96540e2a0.gif)

cc @farodin91

**Comment by farodin91** [comment]
source: `https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/actions/mover/RsStatementUpDownMover.kt`

**Comment by matklad** [comment]
I think this is fixed in https://github.com/intellij-rust/intellij-rust/pull/2062/files#diff-9be3dda6ce48348eea6a39e63080125aR67
