### ISSUE TITLE
Fields are not highlighted inside Self { ... }

### ISSUE THREAD

**Issue by HighCommander4** [intellij-rust/intellij-rust#1992]
In the following code:

```rust
struct Foo {
    member: i32
}

impl Foo {
    fn new() -> Self {
        Foo {
            member: 0
        }
    }
}
```

the use of `member` inside `new()` is highlighted as a field, but if I change the `Foo` to `Self`, like so:

```rust
impl Foo {
    fn new() -> Self {
        Self {
            member: 0
        }
    }
}
```
then `member` is no longer highlighted.

**Comment by kumbayo** [comment]
This is likely the same problem as #1897
In this case `Self` is not resolved to the `struct Foo` but instead to the `impl Foo` block.
(Can be seen by Ctrl-Clicking `Self`)
