### ISSUE TITLE
Regression: Lost Implement Member Quick Fix 

### ISSUE THREAD

**Issue by la10736** [intellij-rust/intellij-rust#2005]
From last update 0.2.0.2076 is not longer possible apply _Implement Members_ quick fix by ALT-ENTER key stroke.

```rust
struct A {}

impl Iterator for A {
}

impl Default for A {
}
```
Rollback to 0.2.0.2075 fix that issue.

I took a look to the tests code but I don't fond any test about it...

**Comment by vlad20012** [comment]
Oh, it was broken by #1789 and we don't have availability tests for this intention. I'll fix it
