### ISSUE TITLE
Find Usages of trait methods

### ISSUE THREAD

**Issue by glyn** [intellij-rust/intellij-rust#2018]
In the following code, for example:
```Rust
    trait T {
        fn f(&self);
    }

    struct S {}

    impl T for S {
        fn f(&self) {
            panic!("f was called");
        }
    }

    let s: S = S {};
    s.f();

```
Find Usages of `f` within `impl T for S` correctly identifies the one usage of `f`. However Find Usages of `f` within `trait T` does not find any usages.

Note that Find Usages of `T` in `Trait T` correctly find `impl T for S`, so a workaround for finding the usages of `f` within `trait T` is to Find Usages of `T` and then Find Usages of `f` in each implementation of `T`.

I observe that "Find Usages" is marked as "WIP" in the [features docs](https://intellij-rust.github.io/features/) and is scheduled for v0.5 in the [roadmap](https://github.com/intellij-rust/intellij-rust/issues/424), but Find Usages seems to work pretty well most of the time, so I thought it was worth calling out this case in case it was supposed to work already. Please close this issue if it is not yet supposed to work.

**Comment by Kobzol** [comment]
This works now in the current version of the plugin.
