### ISSUE TITLE
Error and warning messages in JSON format

### ISSUE THREAD

**Issue by atsky** [intellij-rust/intellij-rust#202]
Use JSON format for errors https://internals.rust-lang.org/t/do-you-have-a-tool-which-parses-error-messages/3051 when pull requenst https://github.com/rust-lang/rust/pull/30711 will be merged.

**Comment by zekesonxx** [comment]
That PR got merged months ago, and it looks like you're [already using it in the code](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/cargo/commands/Cargo.kt#L94), so this issue should probably get closed.

**Comment by matklad** [comment]
Yep, you are right, we should close this issue, thanks! Though that particular snippet of code is not about this feature of `rustc`, it is about `cargo metadata` command!
