### ISSUE TITLE
Exception in 'unknown plugin'

### ISSUE THREAD

**Issue by avkonst** [intellij-rust/intellij-rust#2031]
Every time I click 'run debug' of the main function in the Intelij Idea with Rust plugin, IDE complains about fatal error. Interestingly it does not have a callstack and no other information is provided and I can not submit the report as the corresponding button is disabled. See screenshot. Please let me know what information should I look for in order to enable easier troubleshooting.

![image](https://user-images.githubusercontent.com/3971413/32802049-c146ed64-c9e3-11e7-8a02-49d850ebc8f6.png)

This is the popup message I see on failure first of all:
![image](https://user-images.githubusercontent.com/3971413/32802581-59a0fe5a-c9e5-11e7-9c4d-167ae16d8cdd.png)

Intelij version: 
```
IntelliJ IDEA 2017.1
Build #IC-171.3780.107, built on March 22, 2017
JRE: 1.8.0_112-release-736-b13 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
```

Rust plugin version: 0.2.0.2076

Other installed plugins are:
3rd party: PlantUML integration, Rust, Scala
> note: scala plugin worked fined with PlantUML

Plugins by JetBrains, I guess:
Android Support, Ant Support, BashSupport, Bytecode Viewer, Copyright, Coverage, Eclipse Integration, EditorConfig, Git Integration, Gradle, Groovy, I18n for Java, IntelliLang, Java Bytecode Decompiler, JavaFX, JUnit, Kotlin, Markdown support, Maven Integration, Plugin DevKit, Properties Support, Settings Repository, Task Management, Terminal, TestNG-J, Toml, UI Designer, XPathView + XSLT Support, XSLT-Debugger, YAML

Default code sample is enough to reproduce:

```rust
fn main() {
    println!("Hello, world!");
}
```

**Comment by matklad** [comment]
Wow, that's bewildering. Could tell the version of CLion (Help > About), Rust plugin (Settings > Plugins) and check if there are some potentially interfering third-partly plugins installed?

**Comment by avkonst** [comment]
Just updated the ticket with this information.

**Comment by matklad** [comment]
Oups, this IntelliJ IDEA and not CLion, I've missed that! There's no Rust debugger in IDEA :(

**Comment by avkonst** [comment]
Yes, but I do not run the debugger :) I run this:

![image](https://user-images.githubusercontent.com/3971413/32802643-9102e00c-c9e5-11e7-8624-66569faa1b21.png)

**Comment by avkonst** [comment]
Also, it seems the exception happens only once on the first run after restart of the IDE.

**Comment by matklad** [comment]
@avkonst could you consider updating IDEA version? `2017.1` is the first release in `17.1` series, the latest patch release for that is `2017.1.5`, and there's already `2017.2.6` out :) Keep in mind that the latest releases of Rust plugin are compatible with `2017.2` and `2017.3 EAP` only, and there's a chance that the issue will be fixed with upgrade, because there were some compatibility troubles in the relevant piece of code somewhere between `2016.3` and `2017.1`.

**Comment by avkonst** [comment]
Thanks. I will try this later.

**Comment by avkonst** [comment]
The error does not appear anymore with newer Intelij Idea version 2017.2.5. Thank you. I should have tried upgrading before reporting :)

**Comment by matklad** [comment]
Glad that it works for you now, and that you can use the freshest Rust plugin :)
