### ISSUE TITLE
Type of a local variable is not recognized

### ISSUE THREAD

**Issue by avkonst** [intellij-rust/intellij-rust#2032]
I have taken code sample from Hyper crate. Notice the client variable is of unknown type for the IDE, because call to Client::new(...) is not recognized by the plugin. As a result, further intellisense on this variable and method calls is not available.

![image](https://user-images.githubusercontent.com/3971413/32804440-ec0367aa-c9eb-11e7-8d39-88d924c2e98b.png)

IDE version:
```
IntelliJ IDEA 2017.2.5
Build #IC-172.4343.14, built on September 26, 2017
JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
```

Plugin version: 0.2.0.2076

Code sample:
```rust
extern crate futures;
extern crate hyper;
extern crate tokio_core;

use std::io::{self, Write};
use futures::{Future, Stream};
use hyper::Client;
use tokio_core::reactor::Core;

fn main(){
    run();
}

fn run() -> Result<(), hyper::Error> {
    let mut core = Core::new()?;
    let client = Client::new(&core.handle());

    let uri = "http://httpbin.org/ip".parse()?;
    let work = client.get(uri).map(|res| {
        println!("Response: {} {:?}", res.status(), res.body());
    });

    core.run(work)?;
    Ok(())
}
```

Cargo.toml:
```toml
[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
```

**Comment by avkonst** [comment]
Cache invalidation, restart and reindexing do not help.

**Comment by avkonst** [comment]
Workaround so far is to declare the type of the variable explicitly: 
![image](https://user-images.githubusercontent.com/3971413/32808362-a6b3bcc0-c9f7-11e7-9663-daec709e35aa.png)

**Comment by kumbayo** [comment]
I just tried this code with a nightly build (version 0.2.0.2211-nightly) and this seems to be fixed already.
The binding client is inferred to be `Client<HttpConnector, Body>`

![screenshot_20171117_184121](https://user-images.githubusercontent.com/1041267/32960918-f5870610-cbc6-11e7-86e3-5181aea6cd5c.png)

**Comment by avkonst** [comment]
Great. Are there any instructions where I can download lightly version and
how I can install nightly version of the plugin? Thanks

**Comment by mkaput** [comment]
https://intellij-rust.github.io/install.html

**Comment by avkonst** [comment]
I have tried nightly. It is definitely resolved.
