### ISSUE TITLE
Highlight unknown identifiers and suggest quick-fix tips with relevant and applicable imports

### ISSUE THREAD

**Issue by avkonst** [intellij-rust/intellij-rust#2034]
I am coming from java/scala world, where IDE does this: if an identifier is unknown, it highlights it and suggest which definition one to import (if any).

Rust plugin shows this (notice `HttpConnector` variable is not known in the scope):

![image](https://user-images.githubusercontent.com/3971413/32808018-ae82ffe8-c9f6-11e7-8f1c-a23ce4805278.png)

I would expect the plugin to highlight this variable by red-line underscores and offer a tip to `use hyper::client::HttpConnector` automatically.

VS Code + RLS does similar thing:
![image](https://user-images.githubusercontent.com/3971413/32808227-31733cf6-c9f7-11e7-8b2e-185c2f8f93cb.png)
but I would expect one more tip in the quick-fix list: use fully qualified path to a variable instead of importing via use statement.

**Comment by matklad** [comment]
We have not yet implemented Rust language fully (the big missing piece is support for macros), so we can't 100% reliably detect unresolved names. There's an experimental intentions available for name resolution and type errors, but they are disabled by default because they can have false positives.

**Comment by avkonst** [comment]
May I enable this experimental feature? Also, are you planning to connect the plugin with RLS? It is quite useful as it does in-flight compilation and warning/error marking in real-time...

**Comment by matklad** [comment]
Yeap, here's the checkbox:

![image](https://user-images.githubusercontent.com/1711539/32879104-b1ab93e2-cab9-11e7-97a9-877af20cb8e1.png)

> Also, are you planning to connect the plugin with RLS? It is quite useful as it does in-flight compilation and warning/error marking in real-time...

No, we don't have plans to integrate with RLS yet: it's not quite stable (especially in workspaces), and we would like to implement our own error checking.
