### ISSUE TITLE
Wrong completion

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#2045]
### 1 `process` is in the completion list, but it's not a member of `Sha256`

![image](https://user-images.githubusercontent.com/873919/32978615-d194ce50-cc56-11e7-8777-aeea6084958a.png)

![image](https://user-images.githubusercontent.com/873919/32978621-e3b72e02-cc56-11e7-91e1-86246b3df4af.png)

### 2 `input` is _not_ in the completion list, but it's a member of `Sha256`

![image](https://user-images.githubusercontent.com/873919/32978610-c31f5d0e-cc56-11e7-9577-b7a7b7fb8aff.png)

![image](https://user-images.githubusercontent.com/873919/32978635-3e3e9284-cc57-11e7-9113-333a1adae425.png)

Rust plugin version: 0.2.0.2077

IntelliJ IDEA 2017.3 EAP (Ultimate Edition)
Build #IU-173.3622.25, built on November 9, 2017
IntelliJ IDEA EAP User
Expiration date: December 9, 2017
JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by kumbayo** [comment]
Thanks for the report
### Point 1
This seems to be related to #1860
We also autocomplete for traits that are not imported.
Adding `use crypto_hashes::digest::Input;` makes the code compile.

### Point 2
As far as i can see `fn input(&mut self, input: &[u8])` is a method on the `Digest` trait.
It seems this trait is implemented via 
`impl<D: Input + FixedOutput + BlockInput + Default> Digest for D {}`
`Sha256` satisfies all `Input`, `FixedOutput`, `BlockInput` and `Default` traits but it seems we do not pick up this generic impl...

**Comment by kumbayo** [comment]
We do not pick up the impl because of https://github.com/intellij-rust/intellij-rust/blob/49ed9479a6f40d17d23f1ae2188bfa28c328936d/src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt#L61-L68

#1735 is limited to unbounded impls like `impl<T> MyTrait for T`

**Comment by vlad20012** [comment]
Point 2 should be fixed with #2061
Point 1 is not really a problem: we currenly complete everything and don't looking to imported traits/trait bounds and I think it's right logic: we can complete a method first and then use some quick fix (which will be added in future, I guess) to import trait/satisfy trait bound

**Comment by vasily-kirichenko** [comment]
> Point 1 is not really a problem: we currenly complete everything and don't looking to imported traits/trait bounds and I think it's right logic: we can complete a method first and then use some quick fix (which will be added in future, I guess) to import trait/satisfy trait bound

It's a bug until autoimport is implemented.
