### ISSUE TITLE
Too subtle error highlighting

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#2047]
I find error highlighting with red underlining is too hard to spot:

![image](https://user-images.githubusercontent.com/873919/32989156-291e2556-cd22-11e7-8e53-5f2de1580f20.png)

Compare this to the approach Kotlin uses:

![image](https://user-images.githubusercontent.com/873919/32989162-4c0f12fa-cd22-11e7-8df6-b648f6fedfcd.png)

Is there a way to make it work as in Kotlin plugin (optionally, maybe)?

**Comment by vlad20012** [comment]
Kotlin uses such style for unresolved references only, and we will use it too, I guess. But errors like type mismatch kotlin plugin shows with same underlined style:
![image](https://user-images.githubusercontent.com/3221931/33227791-8232e94e-d1bc-11e7-8345-41c8397d7db7.png)
