### ISSUE TITLE
Variable type resolution is incorrect

### ISSUE THREAD

**Issue by avkonst** [intellij-rust/intellij-rust#2050]
Have a look into type hint for `r` variable within `caller_func`. It's correct type is String, but Intelij shows `<Box<Future> as Iterator>::Item`. The result is that all further intellisense and code assistance is broken.

![image](https://user-images.githubusercontent.com/3971413/33049542-824bc986-cec5-11e7-9213-fbfba65b6675.png)

The plugin proposes the navigation for `map` function to 2 places: 
![image](https://user-images.githubusercontent.com/3971413/33049574-a2979e5e-cec5-11e7-97a7-105607d19716.png)
Maybe this is the reason of incorrect type resolution.

Plugin version: 0.2.0.2215-nightly

Code sample used:
```rust
extern crate futures;
extern crate hyper;
extern crate tokio_core;

extern crate serde;
extern crate serde_json;

use futures::future::Future;

use hyper::server::{Http, Request, Response, Service};

use hyper::{Chunk};
use futures::Stream;

use std::io::Read;
use std::ops::Deref;

use std::panic;
use std::result;
use std::error;

struct AgentService {
    max_body_size: usize
}

impl AgentService {
    fn new() -> AgentService {
        AgentService { max_body_size: 1024 * 1024 }
    }

    fn get_body(&self, body: hyper::Body) -> Box<Future<Item=String, Error=<Self as hyper::client::Service>::Error>> {
       unimplemented!()
    }

    fn caller_func(&self, req: Request) -> Box<Future<Item=usize, Error=<Self as hyper::client::Service>::Error>> {
        let quote = self.get_body(req.body());
        let quote_len = quote.map(|r| {r.len()});
        Box::new(quote_len)
    }
}
```

**Comment by Undin** [comment]
Works with 0.4.169.4584-221

<img width="767" alt="image" src="https://user-images.githubusercontent.com/2539310/168177989-fcb06982-1355-4e66-8110-b579b1ded427.png">
