### ISSUE TITLE
File size limit not configurable

### ISSUE THREAD

**Issue by MrBuddyCasino** [intellij-rust/intellij-rust#2067]
I work with large auto-generated Rust files and run into this issue:
`The file size (9.66MB) exceeds configured limit (2.56M). Code insight features are not available.`

I would like to increase the limit, but there is no entry in the settings dialog, so its not actually configurable.

**Comment by matklad** [comment]
This is controlled via a properties file: https://stackoverflow.com/questions/23057988/file-size-exceeds-configured-limit-2560000-code-insight-features-not-availabl

**Comment by MrBuddyCasino** [comment]
Thanks! Wasn't aware this is unrelated to the plugin.
