### ISSUE TITLE
Wrong internal text instead of item name for E0603 (accessing private items)

### ISSUE THREAD

**Issue by kumbayo** [intellij-rust/intellij-rust#2081]
Example code:
```rust
mod foo {
    const BAR: u32 = 0x_a_bad_1dea_u32;
}
use foo::BAR;
```

Current error message:
![unification_after](https://user-images.githubusercontent.com/1041267/33285797-a2604c18-d3b3-11e7-9c48-43c8e9cda70e.png)

Before #1789 (where we did not print the item name)
![unification_before](https://user-images.githubusercontent.com/1041267/33285788-9e8ad220-d3b3-11e7-9406-94400dcb196f.png)

Rustc error message:
```
error[E0603]: constant `BAR` is private
   --> src/main.rs:232:5
    |
232 | use foo::BAR;
    |
```

**Comment by Undin** [comment]
Fixed in #2097
