### ISSUE TITLE
Wrong HTML escaping in E0308 tooltips causes problems around < and >

### ISSUE THREAD

**Issue by kumbayo** [intellij-rust/intellij-rust#2082]
Example code:
```rust
struct Example<T>(T);

fn testit() {
    let wrongAssignment: Example<u32> = Example(Example(1u8));
}
```

![html_escaping_e0308](https://user-images.githubusercontent.com/1041267/33286338-646e0a06-d3b5-11e7-8daa-05faed216aeb.png)
It wants to output `expected 'Example<u32>', found 'Example<Example<u8>>'`
but `LocalInspectionPass.createHighlightInfo()` calls `@NonNls String message = ProblemDescriptorUtil.renderDescriptionMessage(descriptor, element);`
which replaces '&lt;' by '<' but leaves `<html>` tags around the message.

This error was inspired by https://github.com/intellij-rust/intellij-rust/issues/1753#issuecomment-331313940 where the error message was probably OK.

Rustc error message:
```
error[E0308]: mismatched types
   --> src/main.rs:240:49
    |
240 |     let wrongAssignment: Example<u32> = Example(Example(1u8));
    |                                                 ^^^^^^^^^^^^ expected u32, found struct `Example`
    |
    = note: expected type `u32`
               found type `Example<u8>`
```

**Comment by vlad20012** [comment]
2 days ago I ran into the same problem from the same https://github.com/intellij-rust/intellij-rust/issues/1753#issuecomment-331313940 issue =)
I'll try to fix both of them soon

**Comment by vlad20012** [comment]
It's IntelliJ platform bug, Related issue: https://youtrack.jetbrains.com/issue/IDEA-186991

**Comment by vlad20012** [comment]
I think we can use another UTF arrows `❮ ❯` until the platform bug is fixed.

**Comment by mkaput** [comment]
Purely smart
