### ISSUE TITLE
Impl T for T gives false positives

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#2083]
![image](https://user-images.githubusercontent.com/1711539/33400271-8fc58474-d566-11e7-9a8e-82054e81e375.png)

Here, plugin erroneously resolves `YouCantCloneMe::foo`.

**Comment by vlad20012** [comment]
Hmm, we've decided that it's better to resolve as much as possible and filter only if resolved multiple methods with the same name. 

When there will come a bright future, we will show an error here with suggestion to implement the `Clone` trait for type `YouCantCloneME` :)
