### ISSUE TITLE
RustProjectSettings containing user specific data stored in .idea/misc.xml which can be shared

### ISSUE THREAD

**Issue by ghost** [intellij-rust/intellij-rust#2084]
The JetBrains documentation on [how to manage projects under Version Control Systems](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839) suggests:
> If you decide to share IDE project files with other developers [...] Here is what you need to share:
>
> All the files under .idea directory in the project root except the workspace.xml and tasks.xml files which store user specific settings

`RustProjectSettings` are stored in the file `.idea/misc.xml`, which according to the recommendation quoted above, should be shared among developers. However, at least on my system, it contains system / user specific data:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="RustProjectSettings">
    <option name="toolchainHomeDirectory" value="/usr/bin" />
  </component>
</project>
```

Different developers might use Rust toolchains located in different directories, hence this file cannot be shared anymore.

Please clarify whether this is a problem in the [JetBrains documentation](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839) or in the Rust plugin.

**Comment by Undin** [comment]
Similar to #3692
Fixed in #3732
