### ISSUE TITLE
Debug broken on macOS

### ISSUE THREAD

**Issue by chrisballinger** [intellij-rust/intellij-rust#2109]
I can no longer do a Debug on macOS with the latest Version: 0.2.0.2081 and CLion 2017.3.

Running as debug gives this output:
```
/Users/chrisbal/.cargo/bin/cargo build --color=always --package sds011 --bin sds011
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
```

![screen shot 2017-12-08 at 12 44 52 pm](https://user-images.githubusercontent.com/518687/33784398-9ab28aca-dc15-11e7-8d55-bd92c188037b.png)

A regular run gives this output:
```
/Users/chrisbal/.cargo/bin/cargo run --color=always --package sds011 --bin sds011
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/sds011`
<<< program output here>>>
```

It used to work with the plugin 2 versions back, so I think there was a regression. I can't get it to work even with a simple `cargo new test123 --bin` project, so I think it's broken regardless of configuration.

edit: here's an example project where it is broken https://github.com/chrisballinger/sds011-rs

**Comment by chrisballinger** [comment]
Ah I guess this is already fixed in 5c05b6bfbc8a4e735a35cda7b5e23396de0cb19c

Is there a way to easily run the HEAD version of this plugin?

**Comment by Undin** [comment]
I think the easiest way to get the latest version of the plugin is to use its nightly version.
See https://intellij-rust.github.io/install.html for details.

**Comment by matklad** [comment]
@chrisballinger you can also grab the build off the master branch from https://teamcity.jetbrains.com/guestAuth/repository/download/IntellijIdeaPlugins_Rust_CurrentIdea_TestsRust/.lastSuccessful/intellij-rust-0.2.0.%7Bbuild.number%7D.zip

Could you check that the fresh plugin build indeed works as expected?

**Comment by chrisballinger** [comment]
@matklad  Yep that build (3002) works as expected, except now there is this issue with env vars: https://github.com/intellij-rust/intellij-rust/issues/2110
