### ISSUE TITLE
Type highlighting logic deduces the wrong type of the variable

### ISSUE THREAD

**Issue by zolkko** [intellij-rust/intellij-rust#2112]
In the following snippet, `res` variable's type is deduced to be `Vec<&Foo>`. While it is actually `Vec<usize>`.

``` rust
use std::marker::PhantomData;

struct Foo<'a> {
    levels: &'a [u32]
}

struct Bar<'a> {
    phantom: PhantomData<&'a ()>
}

enum FooBar<'a> {
    FooData(Foo<'a>),
    BarData(Bar<'a>)
}

fn main() {
    let foo_bars: &[FooBar] = &[
        FooBar::FooData(Foo { levels: &[1, 2, 3] }),
        FooBar::BarData(Bar { phantom: PhantomData })
    ];
    let foos = foo_bars.iter().flat_map(|v| {
        match *v {
            FooBar::FooData(ref f) => Some(f),
            _ => None
        }
    }).collect::<Vec<_>>();
    let res = foos.iter().map(|v| v.levels.len()).collect::<Vec<_>>();
    println!("{:?}", res);
}
```

**Comment by kumbayo** [comment]
@zolkko Can you check if this problem still exists for you?
For me with 0.2.0.2238-nightly the type of `res` is `Vec<usize>` as you expected.
![intellij_2112](https://user-images.githubusercontent.com/1041267/34313505-e5a127ba-e76b-11e7-96d3-4a0c55986ff6.png)

**Comment by zolkko** [comment]
@kumbayo Affirmative. It is no longer reproducible, even in the 2017.3.1 + plugin 0.2.0.2082.
