### ISSUE TITLE
Macros' types aren't inferred

### ISSUE THREAD

**Issue by Quix0tic** [intellij-rust/intellij-rust#2128]
I declared a macro but, when I use it, types aren't inferred and it doesn't give any suggestion 
![Macro Declaration](https://preview.ibb.co/gABLVR/Macro_declaration.png)
![Macro Usage](https://image.ibb.co/i59UPm/No_suggestion.png)

**Comment by Undin** [comment]
@Quix0tic yeah, current version of plugin has rather restricted macros support, so lack of type inference/completion is expected behavior at this moment
But we are working on it :)

**Comment by Quix0tic** [comment]
Good to know! Thank you!

**Comment by MSxDOS** [comment]
@Undin I'm glad to hear that, as currently the plugin does pretty much nothing for anything heavily macro-oriented like `winapi`, which is a huge bummer considering almost everything there being implemented using macros.
