### ISSUE TITLE
Types of variables from a tuple are not recognized after unwrap()

### ISSUE THREAD

**Issue by DiceMaster** [intellij-rust/intellij-rust#2129]
Create an Optional or Result with a tuple. After unwrapping it into variables with unwrap(), their types will be displayed as `<unknown>`.

Example:
```rust
let a: Option<(i32, i32)> = Some((0, 0));
let (b, c) = a.unwrap();
```
`b` and `c` will be displayed as `<unknown>` instead of `i32`.

IDE and plugin:
intellij-rust 0.2.0.2234-nightly
IntelliJ IDEA 2017.3.1 (Community Edition)
Build #IC-173.3942.27, built on December 11, 2017

**Comment by Pzixel** [comment]
I have similar situation in my codebase:
![image](https://user-images.githubusercontent.com/11201122/34313800-0296f198-e77f-11e7-98f0-7ec8aa9824a5.png)

Minimal example:
```rust
extern crate iron;
extern crate bodyparser;
#[macro_use] extern crate serde_derive;

use iron::prelude::*;

fn main() {
}

fn example(request: &mut Request){
    let update = request.get::<bodyparser::Struct<Update>>();
    match update {
        Ok(Some(update)) => {
            let update = update;
        },
        _ => {}
    }
}

#[derive(Debug, Clone, Deserialize)]
struct Update {

}
```
