### ISSUE TITLE
auto-completion broken on xi-editor project

### ISSUE THREAD

**Issue by vlovich** [intellij-rust/intellij-rust#2139]
Can't seem to get auto completion working for https://github.com/google/xi-editor/.

Steps to reproduce:
1. Import "rust" folder from xi-editor as project
2. Open editor.rs
3. Try to cmd-click on various files.

Expected:
Should be able to cmd-click on things outside the current module & get taken there.  Should be able to hit ctrl-space after period to auto-complete the available functions.  Should see inferred type hint.

Actual:
Completion only available within the file.  Type inference doesn't work for things outside the current file.

Notes:
I've had auto-complete work properly on other projects so I'm not sure what the problem here is.

Environment:
OSX 10.12.6
1. Install rustup-init via homebrew (1.8.0)
2. rustup-init

IntelliJ CE 2017.3.1
Rust plugin 0.2.0.2082

**Comment by Undin** [comment]
@vlovich Did you attach cargo project?
If no, you can do it via notification (if there aren't attached projects yet) or via cargo tool window
<img width="1094" alt="screen shot 2017-12-21 at 01 38 47" src="https://user-images.githubusercontent.com/2539310/34232097-d1b3f778-e5ef-11e7-932d-797dc245f0c9.png">
After that all intellisense features should work as expected

**Comment by Undin** [comment]
Note that this project contains several cargo projects.
Unfortunately, we don't support auto import yet and you should add each cargo project manually.

**Comment by vlovich** [comment]
I've tried doing each cargo project manually but perhaps I'm not doing it right.  Do I create 1 project & have 1 module per cargo project or 1 top-level project per cargo project?

**Comment by vlovich** [comment]
Basically I'm trying to modify stuff in the core-lib cargo project.  Even if I import that as a standalone project I still don't get code completion.

**Comment by vlovich** [comment]
When I open lib.rs, it has highlighted some errors (erroneously I think).
```
#[cfg(target_os = "fuchsia")]
extern crate magenta;
```
Gets reported as ``Can't find crate for `magenta` `` which seems wrong since the target OS is macos not fuchsia.

Perhaps cfg selection is causing problems for the indexer?

**Comment by vlovich** [comment]
If I remove those, IntelliJ still complains about the body of `pub mod internal` in lib.rs (says everything is an unresolved module, even though they're in the same directory...).

**Comment by vlovich** [comment]
I think I tracked it down.
```
#[path=""]
pub mod internal
```

causes it to look for everything in the internal/ directory for modules even though the `#[path=""]` directive alters the path for the module.  If I create the internal folder as a symlink to "." it kind of works better as long as I open the files through internal/ rather than the real path.

**Comment by Undin** [comment]
> Do I create 1 project & have 1 module per cargo project or 1 top-level project per cargo project?

The best way is to open whole project (I mean IDE project) in IDEA and attach each cargo project via cargo tool window. In fact, each cargo project won't be a separate IDEA module because we use own project structure but logically yes, each cargo project will be separate "module"

> I think I tracked it down (at least partially).
#[path=""]
pub mod internal
> causes it to look for everything in the internal/ directory for modules even though the #[path=""]

Yeah, looks like we incorrectly process empty path. It's definitely bug

**Comment by vlovich** [comment]
> The best way is to open whole project (I mean IDE project) in IDEA and attach each cargo project via cargo tool window. In fact, each cargo project won't be a separate IDEA module because we use own project structure but logically yes, each cargo project will be separate "module"

Yeah, that's what I did but the completion still doesn't work within core-lib.  I think the path="" is 1 bug and I suspect the platform-specific #cfg directives also cause issues for the parser (e.g. missing modules that are hidden for the current platform).

**Comment by Undin** [comment]
About `path` attribute - I've created the separate issue (#2145) about it because it is not a bug with an empty value of `path` attribute. At this moment we don't support such cases at all regardless of path value
