### ISSUE TITLE
Make debugger to show string values

### ISSUE THREAD

**Issue by Pzixel** [intellij-rust/intellij-rust#2140]
It's very important to see what strings values are. But today the only way to see them is just log it somewhere. It's not really convinient and sometimes require large code rewrite to satisfy all rust rules to just borrow some value and print it, especially for nested values.

In a nutshell: currently debugger shows strings as `Vec<u8>`, but we need more human-readable representation.

**Comment by basebox-mt** [comment]
Rust Rover in 2024:

![Screenshot 2024-10-23 at 11 55 29](https://github.com/user-attachments/assets/386b4d0f-c078-487b-81db-30f72b18f83b)

Of course, I can `println` or log it, so it is not invalid.

**Comment by lucidBrot** [comment]
I know this isue is closed as completed, but i keep coming back to it. Currently I cannot view strings in the RustRover debugger (e.g. OsString inside PathBuf looks also like the screenshot above).

The 2018 MR stated  

> It's still far from perfect when lldb is used because doesn't allow to see separate elements of Vec but it's better than now  

is this still the best the rustrover debugger can do now, seven years later, or is there perhaps something on the consumer-side like maybe I just have to change some obscure setting (one can dream)?

**Comment by Maksim20023** [comment]
@lucidBrot Hello! 
Just did a quick check of your case (OsString inside PathBuf) in the latest RustRover 2025.2.2, and it seems to be working as expected.

<img width="657" height="248" alt="Image" src="https://github.com/user-attachments/assets/ddbf9443-eadf-40af-88f1-8bba7c09037c" />

Please ensure you have latest RustRover version installed and `renderers` option under Settings | Build, Execution, Deployment | Debugger | Data views | Rust is set to `Bundled Renderers`.
If strings are still not displayed correctly, please create an issue in our bug tracker https://youtrack.jetbrains.com/issues/RUST. If you could share a reproducible example, that would really help us look into the issue. Thanks a lot!

**Comment by lucidBrot** [comment]
<img width="571" height="294" alt="Image" src="https://github.com/user-attachments/assets/eb53665f-3a1d-4811-8d88-977fd2ead5e2" />

> renderers option under Settings | Build, Execution, Deployment | Debugger | Data views | Rust is set to Bundled Renderers.

I have verified this is the case ☑️ (and already has been)

So upgrading RustRover from 2024.3 to 2025.2.2 now (Using the JetBrains Toolbox, on Debian)

<img width="848" height="274" alt="Image" src="https://github.com/user-attachments/assets/53b0dccb-a09a-492f-945c-a302bb10ac81" />

And indeed, that fixed it. Thanks! I did not notice there was a pending update (which is much better than forced updates in any case :D )
