### ISSUE TITLE
Completion broken when project is located within a directory symlink on Windows

### ISSUE THREAD

**Issue by petertiedemann** [intellij-rust/intellij-rust#2141]
Repro:

Create a folder like C:\foo\mygit and use `mklink /D` (or /J) to create a directory symlink  `C:\mygit` =>` C:\foo\mygit`.

`cargo new` a project in say C:\foo\mygit\my_proj 

Open C:\foo\mygit\my_proj and verify that completion work.

Now open it via C:\mygit\my_proj (rooted in the symlink), and observe that completion (and type hints are) no longer working.

Version info etc:

Rust plugin version 0.2.0.2082, toml plugin version 0.2.0.9

![image](https://user-images.githubusercontent.com/1265354/34301149-a1dda0fc-e72b-11e7-8817-28f915ca35d5.png)

![image](https://user-images.githubusercontent.com/1265354/34301200-d7f8883c-e72b-11e7-9c78-11e8c2fcc533.png)

**Comment by mchernyavsky** [comment]
I checked this issue on the latest Rust plugin version (on Windows) and it seems to be fixed.
