### ISSUE TITLE
Local variable initialized after declaration does not get a type annotation

### ISSUE THREAD

**Issue by HighCommander4** [intellij-rust/intellij-rust#2144]
In the following code:

```
fn main() {
    let answer;
    answer = 42;
}
```

the variable `answer` does not get a type annotation, the way it would if it were initialized on the same line as its declaration.

**Comment by Undin** [comment]
CC @farodin91

**Comment by farodin91** [comment]
@vlad20012 Any idea why the type is unknown at `let answer;`? Is there a possibility to get the type.

**Comment by vlad20012** [comment]
Oh, I forget about `let answer;` [Here](https://github.com/intellij-rust/intellij-rust/blob/4236c2ba37a7c56add8b5596accb83d1c15c33ca/src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt#L458) should be created the new type variable `TyInfer.TyVar` instead on TyUnknown
