### ISSUE TITLE
Keyboard shortcut to toggle all type hints and parameter names

### ISSUE THREAD

**Issue by ivandardi** [intellij-rust/intellij-rust#2148]
It would be great if there was a keyboard shortcut to toggle showing the type hints and parameter names.

My motivation behind it is that while type hints are great, they sometimes do add clutter to the code and make it harder to read and reason about. So I'd love to be able to temporarily turn them off to be able to take a good look at the code, and then enable them back on when I'm actually coding and dealing with the types.

**Comment by mchernyavsky** [comment]
Actually, IDEA allows you define shortcut for this action:

![image](https://user-images.githubusercontent.com/6079006/49310046-401f7f80-f4ee-11e8-8a4b-2be4666076a7.png)

And yes, "parameter info hints" includes type hints.

**Comment by eliaslevy** [comment]
But the parameter name hints toggle does not include variable, closure, and iterator type hints.

**Comment by ortem** [comment]
@eliaslevy You're right. We've implemented the new interactive type hints #4217, and now this toggle affects only parameter name hints, but not type hints. Unfortunately, IntelliJ doesn't contain such a toggle for the new type hints so far. But it will be implemented someday: https://youtrack.jetbrains.com/issue/IDEA-220258
