### ISSUE TITLE
Import all cargo workspace member crates when importing a project

### ISSUE THREAD

**Issue by stepancheg** [intellij-rust/intellij-rust#2151]
When "Import Project" dialog invoked, intellij-rust creates a project with only with root cargo crate, but not with imported crates.

For example, with [futures-rs](https://github.com/alexcrichton/futures-rs/):

0. Clone https://github.com/alexcrichton/futures-rs/
1. Lauch "Import Project" dialog.
2. Select root folder of cloned futures-rs
3. Click next, next
4. Intellij-rust sees only root project:

<img width="741" alt="2017-12-24_1919" src="https://user-images.githubusercontent.com/28969/34328763-baf6e1a6-e8df-11e7-82f1-4b6f154bb3ac.png">

Although `Cargo.toml` of futures-rs [references futures-cpupool](https://github.com/alexcrichton/futures-rs/blob/bf5dc304ccc37e05e3dbe57c17c70ef1ca175136/Cargo.toml#L28-L29):

```
[workspace]
members = ["futures-cpupool"]
```

I would be convenient if `future-cpupool` also added to the project. It's important for project with 10 crates or so, because otherwise these crates need to be added to project manually.

Versions:
Intellij IDEA CE: 2017.3.1
intellij-rust: 0.2.0.2082
cargo: 0.25.0-nightly (930f9d949 2017-12-05)

**Comment by matklad** [comment]
Hm, one needs to add only the root of the workspace to the IDEA project. All workspace members are treated as parts of the workspace and in fact an error message should be shown if one tries to import a member of an already existing workspace.
