### ISSUE TITLE
Verify logic for getting sdk path from env

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#216]
[This functions](https://github.com/intellij-rust/intellij-rust/blob/47abfbf7485b50cc0c947fcbc359ea93cee8f5ed/src/main/kotlin/org/rust/cargo/project/RustSdkType.kt#L82) seems dubious to me: `CARGO_HOME`, unlike `JAVA_HOME` points not to the cargo binary location, but to the location of caches and configs. I have never heard of `RUST_HOME`.

**Comment by alexeykudinkin** [comment]
Ideas?

**Comment by matklad** [comment]
Here is doc about `CARGO_HOME`: https://github.com/rust-lang/cargo/blob/master/src/doc/environment-variables.md#environment-variables-cargo-reads, it has nothing to do with the location of cargo.

There is no mention about `RUST_HOME` anywhere. 

I will remove `tryGetSDKHomeFromEnv` after I'm done with metadata
