### ISSUE TITLE
primitive types in function arguments always underlined

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#2160]
_From @Jiehong on December 27, 2017 21:57_

Hi,

The following correct programme is weirdly highlighted:

``` rust
fn main() {
    println!("Sqr(21) = {}", sqr(21));
}

fn sqr(number: i64) -> i64 {
    return number * number;
}
```

Indeed, `number` (only on the `fn` line) and `i64` are highlighted in red, and underlined with a little squiggly.
On mouse-over, no information is shown.

When trying to go to the declaration of  `i64`, a `Cannot find declaration to go to` is shown. Perhaps this is the reason of the highlight?

Screenshot:

![image](https://user-images.githubusercontent.com/1061229/34394426-4e98541e-eb59-11e7-865e-16265cff6a61.png)

_Copied from original issue: intellij-rust/intellij-rust.github.io#58_

**Comment by neonaot** [comment]
It looks like this bug is no longer relevant in 2021.2.  May I close the issue?
<img width="453" alt="image" src="https://user-images.githubusercontent.com/49211026/133426835-16e2529a-ce03-4168-800e-4bbd3ce0050d.png">
