### ISSUE TITLE
0.2.0.2083 indexes forever.

### ISSUE THREAD

**Issue by ralfbiedert** [intellij-rust/intellij-rust#2161]
I just updated to `0.2.0.2083`. 

After re-starting Clion (2017.03) and re-opening my project there is an "Updating Indices" going on forever (20+ minutes) for a small project. It always seems to re-run the very same dependency (`.../checkout/stdsimd/...`).

Here is how it looks like in the IDE:

https://imgur.com/rf6Qsgt

The problem persists even after restarting Clion.

**Comment by vorot93** [comment]
I seem to have the same problem, in my case with `futures` package.

**Comment by swiftcoder** [comment]
I'm seeing the same infinite indexing loop on IntelliJ IDEA 2017.3.4, but only on Windows (not on Mac).

**Comment by ForsakenHarmony** [comment]
I'm having problems as well, it just doesn't update the syntax highlighting / auto complete for what feels like 5 minutes after I write something

**Comment by vlad20012** [comment]
@swiftcoder or @ForsakenHarmony, can you please spcify the rust project in which this bug is reproduced (if it is open-source, of course)? Or the project does not matter?

@ralfbiedert is the bug reproduceable for you on the latest versions of the plugin?

**Comment by ForsakenHarmony** [comment]
https://github.com/ForsakenHarmony/graphql-server

Seems to be the worst here

**Comment by vlad20012** [comment]
@ForsakenHarmony can't reproduce it. I use IntellJ IDEA 2017.3.4, the lates nigtly rust (2018-02-18), and the latest nightly IntelliJ-Rust plugin (0.2.0.2288-nightly)

**Comment by vlad20012** [comment]
@ForsakenHarmony try [the nightly IntelliJ-Rust channel](https://intellij-rust.github.io/install.html)

**Comment by vlad20012** [comment]
Everyone who have this issue, please try `ctrl+shift+A -> "invalidate caches"` action

**Comment by matthewkmayer** [comment]
I ran into this problem with the `intellij-rust` plugin on https://github.com/rusoto/rusoto , commit `79fc167cb` (`master` branch as of time of writing this).

Invalidating caches and updating nightly via `rustup update nightly` lets indexing make progress. However, it's taking a very long time because it's indexing every `target` directory and there are a *lot* of crates in Rusoto. 😄 

It's been sitting on one file in particular for a while: `ecs/target/rls/debug/build/typenum-(hash)/out` for at least five minutes now. Is this the same bug, root cause in the IntelliJ platform, or a different one?

Thanks!

**Comment by vlad20012** [comment]
@jrconlin can you please spcify the rust project in which this bug is reproduced (if it is open-source, of course)? Or the project does not matter?

**Comment by vlad20012** [comment]
Hmm, also ake a look as, maybe it will help #2161

**Comment by jrconlin** [comment]
@vlad20012 Sure thing: https://github.com/mozilla-services/megaphone/tree/wip 

I also tried invalidating caches, even a clean reinstall (by deleting the ~/.PyCharm* and the ./.idea directories) and still had the same problem. I get that this might be one of those really weird bugs, and I'm ok with providing as much info as I can. (Logs, configs, etc.) 

FWIW, the point that things hang doesn't seem to be related to a given file, although it does seem to hang more often in charm jars.

**Comment by jrconlin** [comment]
good-(ish) news? I am able to replicate the eternal index issue on two different machines. 
Both are using the same project, but are hanging on different files.

**Comment by vlad20012** [comment]
Oh, sorry for waiting. The fix will be available in the next release (tomorrow, I hope)

**Comment by matthewkmayer** [comment]
Thank you! 👍

**Comment by SHATSON** [comment]
Exclude the folders you do not want to index. You can do this by right-clicking the folder you want to exclude, then chose Mark Directory As > Excluded and PyChram won't index those files.
