### ISSUE TITLE
Ability to complete associated constants in Impl block.

### ISSUE THREAD

**Issue by bmusin** [intellij-rust/intellij-rust#2162]
Hi.
Say, I have
structure: `struct A;`
I implement methods on it: `impl { const MAX: usize = 512 }; ... }`
When I implement methods themselves,
I type `Self::` 
Then I press simultaneously _Ctrl-Space_, but plugin doesn't suggest me `MAX`(associated constant).

Could you please implement it?
Thanks.

**Comment by kumbayo** [comment]
This is possibly related to #1897
