### ISSUE TITLE
Run configuration allows only to run on channels, not on all toolchains

### ISSUE THREAD

**Issue by sanmai-NL** [intellij-rust/intellij-rust#2165]
E.g. it is not possible to specify `cargo run +nightly-2017-12-11` only `cargo run +nightly`.

**Comment by Kobzol** [comment]
@mchernyavsky Is it somehow possible to create a run configuration with a custom toolchain? It would be really nice for debugging `rustc` itself. If I add e.g. `+local` to the beginning of the Command of a run configuration, the debug button grays out.

**Comment by Undin** [comment]
@mchernyavsky can we close it since #7864 is merged?
