### ISSUE TITLE
"Remove braces from single expression" doesn't insert a comma

### ISSUE THREAD

**Issue by UninterestinAcc** [intellij-rust/intellij-rust#2176]
* [Recorded demonstration of bug](https://imgur.com/a/bTvBi)

Expected result:
```rust
match panic::catch_unwind(|| (f)(msg, args)) {
	Ok(inner) => inner,
	Err(err) => Err(CommandError(format!("{:?}", err)))
}
```

(Note the comma after `Ok(inner) => inner`)

**Comment by Undin** [comment]
Related code `org.rust.ide.intentions.UnwrapSingleExprIntention`
