### ISSUE TITLE
`./gradlew runIdea` runs IDEA twice

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#221]
If I execute `./gradlew runIdea`, I get an instance of IDEA running and, when I close it, the second instance starts up.

**Comment by himikof** [comment]
That seems to be caused by `:toml:runIdea` gradle task. Something fishy is going on there — `:toml:prepareSandbox` and `:toml:runIdea` probably should not be called from the top level ones, but I don't understand Gradle and/or IntelliJ Gradle plugin enough to find the actual reason.

**Comment by alexeykudinkin** [comment]
That's due to the fact that both Rust & Toml plugins do have similar tasks. 
Run `:runIdea` task (note heading colon) if you want to run just the one pertaining to the Rust plugin.
