### ISSUE TITLE
please also disable the "..." (browse for path) when disabling pathToStdlibField.text

### ISSUE THREAD

**Issue by xftroxgpx** [intellij-rust/intellij-rust#2214]
pathToStdlibField.text is disabled here: https://github.com/intellij-rust/intellij-rust/blob/1f50edae1567897b7aba1a99da68094f865c8500/src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt#L108

but the ability to browse&select a dir is still enabled, as I experienced here https://github.com/intellij-rust/intellij-rust/issues/2211#issuecomment-359149664 (has screenshot)

**Comment by kumbayo** [comment]
It looks like this was fixed by #2703 
@vlad20012 Can you close this issue?
