### ISSUE TITLE
typo? "is" -> "this" ?

### ISSUE THREAD

**Issue by xftroxgpx** [intellij-rust/intellij-rust#2215]
https://github.com/intellij-rust/intellij-rust/blob/17b2d6084efbb0ca552d9b90a49251c2b0512c2a/src/main/kotlin/org/rust/ide/intentions/AddElseIntention.kt#L16

(not submitting a PR due to `Note that we need an electronic CLA for contributions` and i don't wanna deal with that sh :) )

**Comment by Undin** [comment]
Fixed in #2224
