### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by andmer** [intellij-rust/intellij-rust#222]
Total time: 53.882 secs

C:\Users\andre\intellij-rust>gradlew buildPlugin
plugin.xml with 'idea-plugin' root is not found. IntelliJ specific tasks will be unavailable for :jps.
plugin.xml with 'idea-plugin' root is not found. IntelliJ specific tasks will be unavailable for :toml.
:generateRustLexer UP-TO-DATE
:generateLexers UP-TO-DATE
:generateRustPsiAndParser UP-TO-DATE
:generateParsers UP-TO-DATE
:generate UP-TO-DATE
:jps:compileKotlin UP-TO-DATE
:jps:compileJava UP-TO-DATE
:jps:processResources UP-TO-DATE
:jps:classes UP-TO-DATE
:jps:jar UP-TO-DATE
:toml:compileKotlin UP-TO-DATE
:toml:compileJava UP-TO-DATE
:toml:processResources UP-TO-DATE
:toml:classes UP-TO-DATE
:toml:jar UP-TO-DATE
:compileKotlin
e: C:\Users\andre\intellij-rust\src\main\kotlin\org\toml\ide\TomlHighlighter.kt: (9, 17): Unresolved reference: lang
e: C:\Users\andre\intellij-rust\src\main\kotlin\org\toml\ide\TomlHighlighter.kt: (10, 17): Unresolved reference: lang
e: C:\Users\andre\intellij-rust\src\main\kotlin\org\toml\ide\TomlHighlighter.kt: (15, 9): Unresolved reference: TomlLexer
e: C:\Users\andre\intellij-rust\src\main\kotlin\org\toml\ide\TomlHighlighter.kt: (28, 12): Unresolved reference: TomlTypes
e: C:\Users\andre\intellij-rust\src\main\kotlin\org\toml\ide\TomlHighlighter.kt: (31, 12): Unresolved reference: TomlTypes
e: C:\Users\andre\intellij-rust\src\main\kotlin\org\toml\ide\TomlHighlighter.kt: (34, 12): Unresolved reference: TomlTypes
e: C:\Users\andre\intellij-rust\src\main\kotlin\org\toml\ide\TomlHighlighter.kt: (37, 12): Unresolved reference: TomlTypes
e: C:\Users\andre\intellij-rust\src\main\kotlin\org\toml\ide\TomlHighlighter.kt: (40, 12): Unresolved reference: TomlTypes
e: C:\Users\andre\intellij-rust\src\main\kotlin\org\toml\ide\TomlHighlighter.kt: (43, 12): Unresolved reference: TomlTypes
:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by matklad** [comment]
Looks like a missing TOML submodule. Have you specified `--recursive` flag when you've cloned the repository?

**Comment by andmer** [comment]
sorry. my fault.

i missed the --recursive bit.

thanks!
