### ISSUE TITLE
Cargo project update failed: Project directory does not exist

### ISSUE THREAD

**Issue by recombinant** [intellij-rust/intellij-rust#2220]
Renamed some top level folders (which themselves contained Rust projects). This resulted in 

> Cargo project update failed: 
> Project directory does not exist

with no hint as to where the problem was. Removing all projects from Cargo Tool window fixed the issue - though the existing toml files had to be reattached.

**Comment by mfarrugi** [comment]
+1, this should let us know what files/directory it is looking for.

**Comment by mfarrugi** [comment]
Looks like this is coming from https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt#L271 , is it reasonable to print the path as part of the error?

eg. "Project directory '$expected' for '$manifest.path' does not exist."

**Comment by elichai** [comment]
I'm having the same problem now.
Both CLion and intellij-rust got updated and now it doesn't show me types and I get this `Project directory does not exist` in the event log

**Comment by mattraffel** [comment]
any resolution to this issue?  I started getting the problem today.

**Comment by elichai** [comment]
@mattraffel 
If you still have this problem I fount the solution here: https://github.com/intellij-rust/intellij-rust/issues/2120
Open the Cargo toolbar via `ctrl-E` click on `Cargo` and it will open a window on the right with all the cargo projects. remove everything with a red line under it and re add it.

**Comment by TheAifam5** [comment]
@elichai oh wow... its 2020 and still same thing. I wanted to switch back to the VSCode setup but thanks to you I can play with it around now.

**Comment by beac0n** [comment]
> @mattraffel If you still have this problem I've found the solution here: #2120 Open the Cargo toolbar via `ctrl-E` click on `Cargo` and it will open a window on the right with all the cargo projects. remove everything with a red line under it and re add it.

Thanks. This also works with RustRover
