### ISSUE TITLE
In certain closures, parameter type is displayed as if it's inferred

### ISSUE THREAD

**Issue by jkcclemens** [intellij-rust/intellij-rust#2236]
![image](https://i.imgur.com/sd3nJGX.png)

Notice on the third line `|e: CreateEmbed: CreateEmbed|`. It's clear that `e` is `CreateEmbed`.

**Comment by Undin** [comment]
CC @farodin91

**Comment by farodin91** [comment]
I can fix this, this should be a oneliner.
