### ISSUE TITLE
Formatter should add `;` after `break and continute

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#2249]
```rust
loop {
    if cond {
        break
    }
}
```

->

```rust
loop {
    if cond {
        break;
    }
}
```

We already have this logic for return: https://github.com/intellij-rust/intellij-rust/blob/70c9135dbcdc2347f8b85a8d4a542320b4503c97/src/main/kotlin/org/rust/ide/formatter/processors/RsReturnStatementFormatProcessor.kt.

It should be generalized to `break` and  `continue` as well.

**Comment by t-kameyama** [comment]
I will work on this
