### ISSUE TITLE
Format macros support

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#2256]
A lot of languages have possibility to create/print strings with some formatting. For example [Formatter](https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html) class in java or [printf](http://www.cplusplus.com/reference/cstdio/printf/) function in C/C++.
Rust has [formatting macros](https://doc.rust-lang.org/std/fmt/) for it. 

It would be great to have the support of format macros in intellij-rust like in other languages, i.e.:
* [ ] Highlight special constructions: `{}`, `{:?}`, etc. Looks like that good solution is to create special parser for format strings according to this [syntax](https://doc.rust-lang.org/std/fmt/#syntax)
* [ ] Check number of parameters and their types and show warnings if format strings and arguments don't match #4089

**Comment by Kobzol** [comment]
Fixed by https://github.com/intellij-rust/intellij-rust/pull/4969.
