### ISSUE TITLE
Go To > Implementation has no effect if no Cargo.toml is selected for project

### ISSUE THREAD

**Issue by devurandom** [intellij-rust/intellij-rust#2261]
I am looking at the Rust source code itself. There, Cargo.toml is in src/, so no automatically found by IntelliJ Rust. When I do not point IntelliJ Rust to the location of this file, and try to Go To > Implementation of `debug!`, nothing will happen. There is no even an error message.

By contrast, Find Usages responds with a red error box in the source code window, containing:
```
Cannot search for usages
Position to an element to find usages for, and try again.
```

Similarly, Go To > Declaration responds with a red error box containing: `Cannot find a declaration to go to`

The same effect (i.e. nothing) happens even after I point IntelliJ Rust to `src/Cargo.toml` (i.e. I "attach" to it), navigate to the definition of `debug!` inside the log crate (version 0.3.9) and then try to go to the implementation of `LogLevel` (keyboard cursor here) in the expression `$crate::LogLevel::Debug`.

I understand that the request to find the implementation of that might be weird, but there should at least be some error message pointing me to the reason: Why can IntelliJ Rust not resolve this symbol and find an implementation? Is it not aware that this is even a symbol? Is it a type of symbol that cannot have an implementation? Or is there no implementation visible in the source code that I gave IntelliJ Rust to look at (i.e. in the project and its dependencies)? And if so, was there maybe a problem resolving the dependencies of this project? Or was IntelliJ Rust even able to figure out anything meaningful about the project, i.e. is a Cargo.toml available?

**Comment by devurandom** [comment]
I found another instance of the "no error message" problem: In src/librustc/ty/context.rs, in `validate_hir_id_for_typeck_tables()`, `find_node_for_hir_id()` is being called. When I search for implementations of that, I get no answer at all (not even an error message). When I search for usages, I get the same "Cannot search for usages" message I described above.

**Comment by Kobzol** [comment]
@Undin I think that this might not be relevant anymore, as the plugin now allows attaching `Cargo.toml` from an arbitrary directory?

**Comment by ortem** [comment]
@Kobzol I agree with you, this should not be a problem anymore
