### ISSUE TITLE
How can I build the plugin for Intellij 14?

### ISSUE THREAD

**Issue by gwang** [intellij-rust/intellij-rust#227]
Followed the instructions, and successfully built the plugin with `IntelliJ Rust-0.0.1.SNAPSHOT.zip` in `build/distributions` folder. When I tried to `install from the disk` using this file, the following message showed up (see the image below). 

![image](https://cloud.githubusercontent.com/assets/84264/12709378/2da98b6a-c860-11e5-949b-be430d783f21.png)

After looking the building output, I noticed that it was using Intellij 15. How can I tell the build to use Intellij 14 instead? Thanks.

**Comment by matklad** [comment]
You can try this branch https://github.com/intellij-rust/intellij-rust/tree/IDEA-14-ci. But note that it  lags behind

**Comment by gwang** [comment]
Still have the same error :-(

Here are the commands I did:
1. `git clone https://github.com/intellij-rust/intellij-rust --branch IDEA-14-ci --single-branch`
2. `cd intellij-rust`
3. `.\gradlew buildPlugin`

To make step #3 work, I had to change my JAVA_HOME to point to JDK 1.8. The resultant `build\distributions\IntelliJ Rust-0.0.1.SNAPSHOT.zip` was using idea-14.1.5.

**Comment by gwang** [comment]
After upgrading Intellij from 14.1.4 to 14.1.6, it works! Thanks.
