### ISSUE TITLE
Ability to add breakpoints in .rs files

### ISSUE THREAD

**Issue by michaeleiselsc** [intellij-rust/intellij-rust#2273]
I work in AppCode and have installed the rust plugin for it. The syntax highlighting and checking seem to be working, but I can't set breakpoints in .rs files without editing the .xml file manually. Could we add this as a feature?

**Comment by farodin91** [comment]
Debugging is currently only support in CLion.

**Comment by michaeleiselsc** [comment]
OK, but since AppCode supports LLDB, and Rust works with LLDB, this should actually be a very small change. LLDB is language-agnostic, it just receives instructions saying "when you hit an instruction pointer matching this line of this file, break". There must be some code in AppEngine that only allows breakpoints to be set in a file if it's one of the usual extensions (.m, .mm, etc.). All that would need to change is to add .rs to that list. I tried editing the XML myself to add a breakpoint in a .rs file, and it worked correctly.

**Comment by demensdeum** [comment]
Guys please add this

**Comment by marcinmatczuk** [comment]
+1 for the request to enable debugging in AppCode, which AFAIK, is based on Lion because of C/C++/Objective-C(++) support. I am willing to help with implementing that, however in some mentoring mode, as I don't have experience with developing for this family of IDEs.

**Comment by vlad20012** [comment]
Currently, we support debugging in CLion only. AppCode is not a target.

**Comment by Undin** [comment]
Currently, our debugger support uses CPP toolchains to get debugger location so we depend on code available only in CLion
But it's quite confusing for a user because these settings contain cmake/cpp compiler properties which are completely irrelevant for rust developer. So we should create own debugger toolchain settings. It'll allow us to have not confusing settings for users and also, provide ability to enable debugger support in AppCode too

**Comment by adamski** [comment]
Any movement on this issue?

**Comment by Majkl578** [comment]
This is a bummer for paying customers who own i.e. PhpStorm or even IDEA but not CLion. It's a bit unfortunate since Rust is currently distributed as a plugin but actually requires CLion for proper developer experience.

**Comment by Undin** [comment]
@Majkl578 But it's a normal situation when a plugin provides different functionality in different environments.
Also, it's a common situation when some product is available only in some specific IDE like PyCharm, PhpStorm and sometimes via plugin in IDEA. For example, C++ support is available only in CLion. So I think it's better that non-paid Rust plugin is available in any IDE without debugger than it would be available only in CLion

**Comment by vroussea** [comment]
Any news about an impl of debugging in the other IDE ?

**Comment by Undin** [comment]
> Any news about an impl of debugging in the other IDE ?

@vroussea We are working on supporting debugging in IDEA Ultimate via [Native Debug](https://plugins.jetbrains.com/plugin/12775-native-debugging-support/) plugin but can't provide any estimate when it will be implemented

**Comment by njasm** [comment]
> 
> 
> > Any news about an impl of debugging in the other IDE ?
> 
> @vroussea We are working on supporting debugging in IDEA Ultimate via [Native Debug](https://plugins.jetbrains.com/plugin/12775-native-debugging-support/) plugin but can't provide any estimate when it will be implemented

👍 I'm looking forward to it! thanks!
