### ISSUE TITLE
Formatter breaks singleton list imports

### ISSUE THREAD

**Issue by Zteve** [intellij-rust/intellij-rust#2277]
The code:
```rust
use self::requestinput::{
    RequestInput,
};
```
is perfectly valid (given the appropriate modules), but the formatter (_without_ optimize imports being set) converts this to:
```rust
use self::requestinput::
    RequestInput,;
``` 
which is _not_ valid (note the invalid comma).

Rust plugin: 0.2.0.2086; IntelliJ: (Ultimate) 2017.3.4

**Comment by vlad20012** [comment]
Fixed with #2300
