### ISSUE TITLE
Intention to move type parameter bouds from the where clause to parameter list

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#2279]
Intention to convert this

```Rust
fn foo<T>() 
where
   T: Clone + Copy,
   T: Debug,
{}
```

into this:

```Rust
fn foo<T: Clone + Copy + Debug>() {}
```

In a sense, this is an opposite of this intention: https://github.com/intellij-rust/intellij-rust/blob/de894ebafb978825fcab95e455c0a89785a25c73/src/main/kotlin/org/rust/ide/intentions/MoveTypeConstraintToWhereClauseIntention.kt

It was introduced in this https://github.com/intellij-rust/intellij-rust/pull/762, take a look at it to learn about where to put tests/docs, etc.

**Comment by t-kameyama** [comment]
I will work on this
