### ISSUE TITLE
Support for custom macros

### ISSUE THREAD

**Issue by ukstv** [intellij-rust/intellij-rust#229]
Just a friendly reminder: please, support also non-standard-library macros, like ones provided by https://github.com/Geal/nom

**Comment by matklad** [comment]
Unfortunately, properly supporting custom macros is very difficult, so don't expect this in the nearest future :(

**Comment by ukstv** [comment]
Does not matter much, it is definitely a possibly maybe nice to have feature. Keep up the good work, man.

**Comment by Undin** [comment]
@ukstv 
Currently, we can expand macros and use top-level items generated by them in type inference, completion, etc.
You can see the result of expansion via `Show expanded macro` and `Show recursively expanded macro` action from a context menu or via the corresponding intention actions (at this moment they are available in the latest nightly builds but will be included in next stable release)

The current implementation doesn't take into account impl blocks (see #2458) but looks like it is enough to work with custom macros like nom crate provides.

So I think we can close this issue
