### ISSUE TITLE
Endless indexing on crates with typenum crate since 0.2.0.2088

### ISSUE THREAD

**Issue by RazrFalcon** [intellij-rust/intellij-rust#2320]
I waited for 15 min - it still indexing it.

I can't reproduce it on a new crate, but it freezes on `/target/release/build/typenum-7b1213e3ff752b96/out/`. I presume because of `consts.rs`. IDEA freezes completely when I'm trying to open this file.

[consts.zip](https://github.com/intellij-rust/intellij-rust/files/1748781/consts.zip)

**Comment by vlad20012** [comment]
Please try ctrl+shift+A -> "invalidate caches" action

**Comment by vlad20012** [comment]
Duplicate #2161

**Comment by RazrFalcon** [comment]
Didn't help.

**Comment by vlad20012** [comment]
It's IntelliJ platform bug. Related issue: https://youtrack.jetbrains.com/issue/IDEA-181227

Try to delete all caches manually. They're located in your user directory, e.g. `~/.IdeaIC2017.3`. Your IDEA settings stored in the same directory, so be careful
