### ISSUE TITLE
`rustfmt` runs on `cargo check` autolint

### ISSUE THREAD

**Issue by saghm** [intellij-rust/intellij-rust#2330]
Hi! I have a File Watchers hook set up to run rustfmt on the current file whenever it saves. Recently, I turned on the "use cargo check to analyze code" setting in the Rust plugin. However, it seems that my rustfmt hook runs every time cargo check runs, which is annoying since it will reformat things in the middle of my typing. Unchecking the File Watchers boxes such as "auto-save edited files to trigger the watcher" and "trigger the watcher on external changes" don't have any effect on this, although I'm sure that the issue is due to the File Watcher hook running since it doesn't occur if I disable the rustfmt hook.

Is there anything I can do to get this to stop? I've gotten quite used to using the cargo check analysis from within the IDE, but I'd also be loathe to give up the ability to automatically trigger rustfmt when saving a file.

**Comment by asv1** [comment]
I have this problem too. Intellij Rust version 0.2.0-2103

**Comment by vlad20012** [comment]
It common case you can't control when IntelliJ will save your files. More specifically, you can't use "cargo check" analysis without auto-save of files.

But you can simply solve it - just remove your file watchers and trigger rustfmt manually via IntelliJ-Rust action:
![image](https://user-images.githubusercontent.com/3221931/49290598-7510df80-f4b8-11e8-84cf-79014407413c.png)
(it's ctrl+shift+A -> type "rustfmt"; you can also assign a shortcut for this action)

**Comment by saghm** [comment]
Is there any way to have rustfmt trigger when I save through the vim-mode keybindings (`:w`, `:wq`, etc.)?
