### ISSUE TITLE
Wrong Formatting on inclusive_range_syntax

### ISSUE THREAD

**Issue by elbaro** [intellij-rust/intellij-rust#2335]
```
#![feature(inclusive_range_syntax)]
...
for i in 1..=10 {
```
When pressing ctrl+alt+L, it adds a space between `..` and `=`.

```
for i in 1.. = 10 {
```

**Comment by kumbayo** [comment]
We currently do not support the new inclusive range syntax `..=` at all.

But i have a work in progress implementation for it, which should be ready soon.
