### ISSUE TITLE
Reformatting issues with `break` inside `match`

### ISSUE THREAD

**Issue by twistedfall** [intellij-rust/intellij-rust#2339]
Hello!

Given the following [valid code](https://play.rust-lang.org/?gist=9bd9926bde817a8d1b8ce0ac1e03948d&version=stable):
```rust
fn main() {
	loop {
		match Some(0) {
			Some(v) => break Some(v),
			None => break Some(0)
		}
	};
}
```

if I run Reformat Code I get the following [invalid code](https://play.rust-lang.org/?gist=77a8d837de4de818c7cd294a56764dd8&version=stable):
```rust
fn main() {
	loop {
		match Some(0) {
			Some(v) => break Some(v);,
			None => break Some(0);
		}
	};
}
```

What more is if have the following [(invalid) code](https://play.rust-lang.org/?gist=7de132c516e9faa8e5533989a9af4991&version=stable):
```rust
fn main() {
	loop {
		match Some(0) {
			Some(v) => break Some(v);,
			None => break Some(0)
		}
	};
}
```

and I start hitting Reformat Code it keeps adding semicolons with each run. This is the [code](https://play.rust-lang.org/?gist=31e10509d1dec67c7d76952e7db0bb07&version=stable) I get after 10 Reformats:
```rust
fn main() {
	loop {
		match Some(0) {
			Some(v) => break Some(v); ; ; ; ; ; ; ; ; ; ;,
			None => break Some(0);; ; ; ; ; ; ; ; ;
		}
	};
}
```
Plugin version: 0.2.0.2088

**Comment by anton-okolelov** [comment]
Could I grab this issue?

**Comment by Undin** [comment]
Of course!
