### ISSUE TITLE
Unresolved reference: `str`

### ISSUE THREAD

**Issue by l0b0** [intellij-rust/intellij-rust#2367]
Using version 0.2.0.2089-173 of this plugin the `str::trim_left` part of [`.map(str::trim_left)`](https://github.com/l0b0/cronlist/blob/71d1205b2532ca28f3caf7bf9699d457519e709c/src/crontab/entry/mod.rs#L59) is highlighted. The plugin suggests fixing this by adding a superfluous `use` statement.

Similar to #920 and #1676.

**Comment by ForsakenHarmony** [comment]
This is happening to me with `u64` adding a `use` fixes it, but is unnecessary
