### ISSUE TITLE
Incorrect type detection for &mut u64 inside an enum.

### ISSUE THREAD

**Issue by axos88** [intellij-rust/intellij-rust#2386]
The following code detects the type of `y.0` to be `u32` although I think it should be `&mut u64` using `Expression Type CTRL+SHIFT+P`

    struct Millis(u64);
    
    let mut x = Millis(5);
    let y = &mut x;

    y.0 = 5;

![image](https://user-images.githubusercontent.com/1281218/37758242-c97dfee8-2daf-11e8-8b11-a72e321b6bbb.png)

**Comment by axos88** [comment]
If it indeed was an u64, this code should be equivalent, but obviously does not work:

    let mut x = Millis(5);

    println!("{:?}", x);

    {
        let y = &mut x;
        let mut z = y.0;
        z = 5;
    }

    println!("{:?}", x);

**Comment by vlad20012** [comment]
It's u64
![image](https://user-images.githubusercontent.com/3221931/37786294-5bd41cde-2e0d-11e8-8283-86b49ef81740.png)
Output:
```
Millis(5)
Millis(5)
```

And more:
![image](https://user-images.githubusercontent.com/3221931/37786328-778f045c-2e0d-11e8-924b-24c6d498b36f.png)
Output:
```
error[E0308]: mismatched types
 --> src\main.rs:8:5
  |
1 | fn main() {
  |           - expected `()` because of default return type
...
8 |     z
  |     ^ expected (), found u64
  |
  = note: expected type `()`
             found type `u64`
```
