### ISSUE TITLE
Unknown type inference for an embedded function variable

### ISSUE THREAD

**Issue by avkonst** [intellij-rust/intellij-rust#2390]
This one does not work:
![image](https://user-images.githubusercontent.com/3971413/37809659-1e17ce42-2eb5-11e8-9977-330cc0461709.png)

This one works:
![image](https://user-images.githubusercontent.com/3971413/37809688-4453cdb8-2eb5-11e8-8169-e7a85e61f55a.png)

**Comment by vlad20012** [comment]
I can't reproduce it. Works for me:
![image](https://user-images.githubusercontent.com/3221931/38192257-bd6a29ce-3674-11e8-9847-c5a91635a620.png)
![image](https://user-images.githubusercontent.com/3221931/38192262-c423e034-3674-11e8-9dd0-edcfccd7d18a.png)

**Comment by avkonst** [comment]
What is your version?

**Comment by vlad20012** [comment]
Hmm, I use nightly builds ([Setup instructions](https://intellij-rust.github.io/)), but I do not think it matters. I don't remember that we did something with closures from the last release.
