### ISSUE TITLE
How can i move this element (new rust file) to next group area - create new rust file menu

### ISSUE THREAD

**Issue by soomtong** [intellij-rust/intellij-rust#2391]
Hi team!

just see below image it 's from recent webstrom version using rust plugin

![image](https://user-images.githubusercontent.com/906974/37811362-105d8da4-2e9d-11e8-9bd5-37c58fe0c508.png)

can i move 'create new `rust file`' to down that group contain typed file elements?

it will be nicer UI than it is.

Thanks advance!

**Comment by amcsi** [comment]
I'm getting the same issue. Rust File is appearing at the very top of the list when creating a new file, and that's not good. I've also tried moving it in a couple of places under Menu and Toolbars, but that didn't work either.

**Comment by soomtong** [comment]
sorry I think it's not a big deal and now I can't see rust (heavy JavaScript works) :sob:
than we can close this ticket.
