### ISSUE TITLE
Reference and value as arguments are the same

### ISSUE THREAD

**Issue by r4v3n6101** [intellij-rust/intellij-rust#2412]
Sorry if question is duplicated. So...

```rust
let mut buf: Vec<u8> = ... ;
f.read_to_end(buf); // compiler: expected mutable reference, found struct `std::vec::Vec`
```
_read_to_end_ expects mutable reference to value, but take value itself without any error.

**Comment by vlad20012** [comment]
Hmm, what is the type of `f`? This code does not compile:
```rust
use std::io::Read;

fn main() {
    let mut buf: Vec<u8> = vec![1, 2];
    std::io::stdin().read_to_end(buf);
}
```

With error:
```
error[E0308]: mismatched types
 --> src/main.rs:6:34
  |
6 |     std::io::stdin().read_to_end(buf);
  |                                  ^^^
  |                                  |
  |                                  expected mutable reference, found struct `std::vec::Vec`
  |                                  help: consider mutably borrowing here: `&mut buf`
  |
  = note: expected type `&mut std::vec::Vec<u8>`
             found type `std::vec::Vec<u8>`
```

**Comment by vlad20012** [comment]
Oh, but you're talking about compile error too! Ok, so just use `f.read_to_end(&mut buf);` instead.

**Comment by vlad20012** [comment]
Or you about the fact that IntelliJ-Rust don't lint errors? So just enable `cargo check` in plugin settings
![image](https://user-images.githubusercontent.com/3221931/38044655-257f0f80-32c3-11e8-80ef-e89fea18df93.png)

**Comment by r4v3n6101** [comment]
I'm talking about IntelliJ error checker. It should show mismatched types, but it doesn't do it. 
Also, cargo test doesn't do it too. Only build or run show the error in the program.
'f' is variable for File, I forgot to mention this.

**Comment by vlad20012** [comment]
Did you checked "Use cargo check to analyze code" in the plugin settings as I indicated on the screen? It is disabled by default.

**Comment by r4v3n6101** [comment]
Yep, I did it. Nothing changes - the error is still fantom to checkers excluding "cargo run/test".

**Comment by vlad20012** [comment]
Hmm, weird. Works fine for me
![image](https://user-images.githubusercontent.com/3221931/38048929-8028d982-32cf-11e8-811f-ff50f1d0d79d.png)


Ok, I have another option :) You can enable "Experimental checks" in inspection settings. This will turn on our own analysis (independent of cargo). But it is incomplete.
![image](https://user-images.githubusercontent.com/3221931/38048998-a86f6172-32cf-11e8-90a9-7dbb74258106.png)

**Comment by r4v3n6101** [comment]
Without Experimental checks:
![default](https://user-images.githubusercontent.com/30029970/38049768-bd64ef8c-32d1-11e8-93a4-ab505393cfc8.png)

But with experimental checks turned on I've finally got the error. Thank you, @vlad20012 !
