### ISSUE TITLE
Debug does not work on windows

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#2413]
![image](https://user-images.githubusercontent.com/873919/38085875-e88290aa-335a-11e8-8edb-408298a79c92.png)
![image](https://user-images.githubusercontent.com/873919/38085962-3c6a3448-335b-11e8-8e1c-403585c161fa.png)

```
> rustup show
Default host: x86_64-pc-windows-msvc

nightly-x86_64-pc-windows-msvc (default)
rustc 1.26.0-nightly (e5277c145 2018-03-28)
```

CLion 2018.1
Build #CL-181.4203.549, built on March 26, 2018
Licensed to Vasily Kirichenko
Subscription is active until August 8, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by vlad20012** [comment]
MSVC toolchain is not supported for now. You can use GNU toolchain (`nightly-x86_64-pc-windows-gnu`)

**Comment by spease** [comment]
I've added a MinGW64 toolchain using the binaries from Git for Windows, but I'm still getting the error message about debugging not working with MSVC. I've even tried making the MinGW64 toolchain the default, rather than the original Visual Studio one.

How do I tell CLion to use the MinGW64 toolchain rather than the Visual Studio one?

Asking here because I found this while searching for the answer on Google.

**Comment by Undin** [comment]
@spease looks like that you use msvc rust toolchain.
Try to install gnu toolchain and then make it default
`rustup install stable-gnu`
`rustup default stable-gnu`

**Comment by computersarecool** [comment]
Hi,

I have installed the MinGW toolchain and made it the default.  When I click "run" the application works as expected.  When I try to debug I get:
`C:/Users/user/Documents/projects/rust_webserver/target/debug/rust_webserver.exe
Error creating process C:\Users\user\Documents\projects\rust_webserver\target\debug\rust_webserver.exe, (error 50).`

**Comment by insinfo** [comment]
I'm having this problem, I'm running Clion 200.1, Windows 10,  mingw-w64 x86_64-8.1.0-win32-seh-rt_v6-rev0
```console
C:/MyRustProjects/guessing_game/target/debug/guessing_game.exe
com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$GDBCommandException: 
Error creating process C:\MyRustProjects\guessing_game\target\debug\guessing_game.exe, (error 50).

Process finished with exit code 0
```

![image](https://user-images.githubusercontent.com/12227024/141498365-4733943b-3ad0-45d6-9f33-756189d4266e.png)

![image](https://user-images.githubusercontent.com/12227024/141499094-bfd897d1-564d-4921-8b78-9af58e1d327e.png)
