### ISSUE TITLE
Plugin doesn't work on CLion 2018.1

### ISSUE THREAD

**Issue by ashleysommer** [intellij-rust/intellij-rust#2417]
CLion 2018.1 came out yesterday. I held off updating my installation because the IDE reported the Rust plugin was incompatible with clion 2018.1.

This morning I updated the rust plugin to the latest version which had changed its CLion compatibility version, so the IDE was no longer reporting any update issues.

I updated my IDE to CLion 2018.1, and now the Rust plugin is not working at all, no Rust features are present, and it looks like it is not even being loaded at startup.

**Comment by ashleysommer** [comment]
Update: I checked in my plugin settings, and it was showing Rust greyed out in red, saying "This plugin is incompatible with this version of CLion".
I uninstalled the Rust plugin, then restarted the IDE, then reinstalled the plugin. The plugin is no longer showing up in red, and it appears to be working correctly again.

**Comment by evertvp** [comment]
Debugging in CLion doesn't work for me, with the error `Cannot create editor for: class org.rust.cargo.runconfig.command.CargoCommandConfiguration`

**Comment by vladikoff** [comment]
@ashleysommer I think this was fixed, check for updates

**Comment by nicholastmosher** [comment]
I just experienced this same issue, I was able to resolve it by uninstalling the Rust plugin from CLion (then restarting CLion), then reinstalling the Rust plugin (and restarting CLion again).

**Comment by ashleysommer** [comment]
@nicholastmosher Yes, thats what I did to fix it too.
I don't think this problem is specific to the rust Plugin in CLion, because _exactly_ the same thing happened to my EmberJS plugin in Webstorm when I updated Webstorm to WS 2018.1 yesterday.

**Comment by Undin** [comment]
All IDE's 2018.1 have a bug - they don't check update automatically that's why IDE doesn't suggest update plugin to new compatible version
It will be fixed in 2018.1.1
You can enable auto update via `Appearance & Behavior -> System Settings -> Updates` settings
So I think it can be closed
