### ISSUE TITLE
Can it not show private field when crates is external ？I see it，But I can't use it or change it public

### ISSUE THREAD

**Issue by mokeyish** [intellij-rust/intellij-rust#2422]
I see it，but I can't use it or change it public. I can't select correct field quickly while too much private fields .It is useful when in current working crate,if it really need public ,I can change it public.
![image](https://user-images.githubusercontent.com/16131917/38158179-7566ad4a-34c2-11e8-804d-53379826121f.png)
![image](https://user-images.githubusercontent.com/16131917/38158191-8766bdf0-34c2-11e8-84ea-1cf506a7e3d7.png)

**Comment by farodin91** [comment]
@Undin Should we change the completion list to show private field at the bottom or should we hide them.

**Comment by vlad20012** [comment]
I think we should hide them, just like we do it in IDEs for other languages.

**Comment by Kobzol** [comment]
If I'm not mistaken, this has already been resolved (https://github.com/intellij-rust/intellij-rust/pull/2874) and can be closed.
