### ISSUE TITLE
Debugger: "Set Value" option does nothing

### ISSUE THREAD

**Issue by vladikoff** [intellij-rust/intellij-rust#2429]
![set-value](https://user-images.githubusercontent.com/128755/38200521-bbc857ec-3662-11e8-9231-eb458bfeeab5.gif)

## STR

* Enter debug mode
* In the variables panel, open context menu, press "Set Value"

## IDE info

CLion 2018.1
Build #CL-181.4203.549, built on March 26, 2018
Licensed to CLion Evaluator
Expiration date: May 2, 2018
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.2

**Comment by Undin** [comment]
Note, it works for me with bundled LLDB in CLion 2020.1 with primitive types

**Comment by ortem** [comment]
I think this should be closed because setting primitive values works fine and setting complex values doesn't work because of [poor expression evaluation](https://github.com/intellij-rust/intellij-rust/issues/4548).
