### ISSUE TITLE
IDEA 16 EAP not supported?

### ISSUE THREAD

**Issue by pkolaczk** [intellij-rust/intellij-rust#243]
README.md states I need IDEA 15 or newer, but it fails to install in IDEA 16.
Is there any workaround?

**Comment by matklad** [comment]
To fix this properly we need https://github.com/JetBrains/gradle-intellij-plugin/issues/66

I will try to add a workaround for now

**Comment by matklad** [comment]
Ok, now it is possible to use the plugin with IDEA 16: https://github.com/intellij-rust/intellij-rust/commit/883ff74f60b085812e5066c080b95060a553ba8b

It seems to work fine, but *may* have some more bugs: I haven't use it with IDEA 16 myself yet. 

I'll keep the issue open until the workaround is removed.

**Comment by matklad** [comment]
Note to self: don't forget about [TOML](https://github.com/intellij-rust/intellij-toml/commit/5c8b1e8ffb9150c113f61ce7475ce7d8293bf357).
