### ISSUE TITLE
Incorrect "mismatched types [E0308]" on `clone`

### ISSUE THREAD

**Issue by makingthematrix** [intellij-rust/intellij-rust#2440]
In a method which adds two sets and returns the result as a new set:
```rust
    fn add_set(&self, other: &USet) -> USet {
        if self.is_empty() {
            other.clone()
        } else if other.is_empty() {
            self.clone()
        } else {
             // ...           
             USet { /* ... */ }
        }
    }
```

Intellij marks this code in red and displays "mismatched types [E0308] expected `USet`, found `&USet`". The code is valid. The problem lies in determining what is the result of the `clone()` operation. If the `if/else if/else` sequence is commented out, Intellij stops treating it as an error. It stops as well if I attempt to dereference the result of `clone`, ie. switching to:
```
...
*other.clone()
...
*self.clone()
...
```
stops Intellij from marking the code as erroneous. But this in fact is now an error, and `rustc` will not compile it.

Intellij IDEA 2018.1 CE, 181.4203.550
Rust plugin 0.2.0.2092.181

**Comment by vlad20012** [comment]
@makingthematrix what is USet and how `Clone` implemented for it? I tried a simple `derive` and can't reproduce it.
![image](https://user-images.githubusercontent.com/3221931/38448819-29c9fcf4-3a10-11e8-9dcf-968e6438dbf7.png)

**Comment by makingthematrix** [comment]
@vlad20012 
It's just from the code I use to learn Rust:
https://github.com/makingthematrix/rust-experiments/blob/master/src/utils/uset.rs
```
#[derive(Debug, Default, Clone)]
pub struct USet {
    set: Vec<bool>,
    len: usize,
}

impl USet {
// ...
   fn add_set(&self, other: &USet) -> USet {
        if self.is_empty() {
            other.clone()
        } else if other.is_empty() {
            self.clone()
        } else {
            let min: usize = min(self.min().unwrap(), other.min().unwrap());
            let max: usize = max(self.max().unwrap(), other.max().unwrap());

            let mut set = vec![false; max + 1];
            let mut len = 0usize;

            set.iter_mut()
                .enumerate()
                .skip(min)
                .take(max - min + 1)
                .for_each(|(i, value)| {
                    if self.contains(i) || other.contains(i) {
                        *value = true;
                        len += 1;
                    }
                });

            if len == 0 {
                USet::new()
            } else {
                USet { set, len }
            }
        }
    }
// ...
}
```
