### ISSUE TITLE
Is this intellij's Bug or intellij-rust 's Bug?

### ISSUE THREAD

**Issue by EighteenZi** [intellij-rust/intellij-rust#2443]
I made a rust project using intellij. Most of the time , it works very good , and i love it.
But sometimes it go wrong, it can not jump to the defining place of  struct, enum, methods.
and I cannot jump to the external libraries,too.
I don't know why.
Please help me on this.
Thanks a lot.

**Comment by licardoY** [comment]
the same with you. **"Cannot find declaration to go to"**
