### ISSUE TITLE
Incorrect "mismatched types [E0308]" on `write!` 

### ISSUE THREAD

**Issue by youta1119** [intellij-rust/intellij-rust#2452]
```rust
struct Point {
    x: i32,
    y: i32,
}

impl fmt::Display for Point {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "({}, {})", self.x, self.y) //Intellij marks this line 
    }
}
```
Intellij marks this code in red and displays "mismatched types [E0308] expected Result<(),Error>, found()". But the code is the code is compiled without problem.
The parser seems to incorrectly infer the return value.

**Comment by vlad20012** [comment]
Duplicate #2229
