### ISSUE TITLE
Support raw identifiers (RFC 2151)

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#2456]
Allows identifiers to start with `r#`. 
* [x] Lexer
* [ ] Parser and PSI

See [RFC 2151](https://rust-lang.github.io/rfcs/2151-raw-identifiers.html)

**Comment by Undin** [comment]
Let's reopen it because only lexer part is implemented

**Comment by Undin** [comment]
I think it can be closed due to #3036
