### ISSUE TITLE
(False) type mismatch errors for &f64

### ISSUE THREAD

**Issue by Zteve** [intellij-rust/intellij-rust#2460]
Since:

* IntelliJ Rust Plugin 0.2.0.2092.181
* IntelliJ IDEA 2018.1.1 (Ultimate Edition)
* Build #IU-181.4445.78, built on April 9, 2018
* JRE: 1.8.0_152-release-1136-b27 x86_64
* JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* macOS 10.13.4

I get lots of (false) type mismatch errors, rendering IDE unusable.

One of the simpler ones is:

```
/// simple-minded comparison of f64s; may panic if NaN etc.
/// 
fn f64compare(x: &f64, y: &f64) -> ::std::cmp::Ordering
{
    x.partial_cmp(y).unwrap()
}
```

Flags the `y` parameter to `.partial_cmp` as an error with the message:

```
mismatched types [E0308] expected `&&f64`, found `&f64`
```

Though it compiles and runs perfectly.

I notice lots of issues (#2449 #2452 #2451 #2448) around this area of type mismatches recently — could they be related?

**Comment by vlad20012** [comment]
> I notice lots of issues (#2449 #2452 #2451 #2448) around this area of type mismatches recently — could they be related?

We just enabled out own typeckeck analysis by default, so many people now catch these errors. You can simply disable the inspection again

**Comment by Zteve** [comment]
Can  you give me a hint where to disable this?  I don't see any change in the Rust language preferences .

**Comment by vlad20012** [comment]
![image](https://user-images.githubusercontent.com/3221931/38570703-279e6f2a-3cf7-11e8-8628-f5bd707e737a.png)

**Comment by Zteve** [comment]
OK. Thanks.
