### ISSUE TITLE
Debugging not possible; more than one binary produced

### ISSUE THREAD

**Issue by flaghacker** [intellij-rust/intellij-rust#2462]
When trying to debug a simple binary project I get the following error:

![image](https://user-images.githubusercontent.com/7887115/38582387-d1725bca-3d0f-11e8-8073-fe376f02cdbe.png)

I don't really get what this means, as far as I can tell "--bin" is already explicitly specified in the generated run configuration:

![image](https://user-images.githubusercontent.com/7887115/38582439-05cf414e-3d10-11e8-87c2-1499fa14fadc.png)

**Comment by Andreby42** [comment]
I get the same problem 。sad

**Comment by vasily-kirichenko** [comment]
Use gnu toolchain, debugging msvc is not supported (yet?).

**Comment by Andreby42** [comment]
I already use the gnu toolchain

**Comment by Andreby42** [comment]
Clion is the latest version

**Comment by vasily-kirichenko** [comment]
![image](https://user-images.githubusercontent.com/873919/38796342-cf006424-4163-11e8-9c10-46707beb9b89.png)

![image](https://user-images.githubusercontent.com/873919/38796375-e938cb6a-4163-11e8-8d40-8d15630d1e6b.png)

```
> rustup toolchain list
nightly-x86_64-pc-windows-gnu (default)
nightly-x86_64-pc-windows-msvc
```
I use Cygwin, and have installed everything under "debug" group.

**Comment by flaghacker** [comment]
I'm using msvc right now, guess that won't work? I'll try installing either cygwin or mingw.

**Comment by Undin** [comment]
@flaghacker yeah, unfortunately, msvc toolchain is not supported for debugging now

**Comment by QiJiYinQiao** [comment]
Default host: x86_64-pc-windows-gnu

nightly-x86_64-pc-windows-gnu (default)


![conf](https://user-images.githubusercontent.com/30022279/38909891-3554beaa-42f9-11e8-80c6-3ae6c727548a.png)

using mingw

just debug codes like  println!("hello world");

**Comment by QiJiYinQiao** [comment]
![conf](https://user-images.githubusercontent.com/30022279/38917628-ef73f1ec-431d-11e8-8713-f510114bab2b.png)

**Comment by Undin** [comment]
@QiJiYinQiao 
I still can't reproduce it
Could you provide output of `cargo build --message-format=json` for your project?

**Comment by tnovotny** [comment]
ok, wrong toolchain for me ... `.rustup\toolchains\stable-x86_64-pc-windows-msvc\`

**Comment by faller222** [comment]
may be this can help someone 

'''

rustup toolchain install nightly-x86_64-pc-windows-gnu
rustup default nightly-x86_64-pc-windows-gnu
rustup override set nightly-x86_64-pc-windows-gnu
rustup update && cargo update
'''

**Comment by Andreby42** [comment]
Thank u ,I will try

**Comment by tr4cks** [comment]
> may be this can help someone
> 
> ```
> rustup toolchain install nightly-x86_64-pc-windows-gnu
> rustup default nightly-x86_64-pc-windows-gnu
> rustup override set nightly-x86_64-pc-windows-gnu
> rustup update && cargo update
> ```

Personally, it solved my problem. Thank you!
