### ISSUE TITLE
"Cannot declare a new module at this location" on all external crates with symlinked `~/.cargo`

### ISSUE THREAD

**Issue by mammothbane** [intellij-rust/intellij-rust#2466]
Presumably related to #652, same symptoms as #637. I had my `.cargo/` symlinked to another drive because I have a small SSD, and was seeing `cannot declare a new module at this location` on `mod` declarations in `lib.rs` in all external crates (examined through `External Libraries`). The only exceptions were the stdlib crates found in `rust-src` (`std`, `core`, `alloc`, `rustc_*san`, etc.), which have a different icon and seem to correctly detect `lib.rs` (in purple). 
![ij-rust-crates](https://user-images.githubusercontent.com/1946010/38706892-f00c6288-3e7c-11e8-95cc-76883afef502.png).

This resulted in basically all IDE features breaking: syntax highlighting, autocomplete, goto-def, etc.

![ij-rust-no-highlight](https://user-images.githubusercontent.com/1946010/38707039-9e1aba78-3e7d-11e8-8c9d-8b921f3eb37a.png)

The problem immediately resolved itself when I replaced my `.cargo` symlink with the actual directory. It'd be really nice to get a fix for this case since I'm pretty tight on SSD space (and I imagine there are others in the same situation)!

I encountered this issue on IntelliJ 181.4445.78, plugin version 0.2.0.2092-181 on Windows 10

**Comment by Undin** [comment]
@mammothbane we've just released new plugin version where this problem should be fixed. Could you please check that false positive error annotations are gone in your case with the latest plugin?
