### ISSUE TITLE
Support for Ctrl+Shift+Enter

### ISSUE THREAD

**Issue by fischmax** [intellij-rust/intellij-rust#247]
This should place a matching number of closing parenthesis in the current line, insert a semicolon if necessary (this is probably harder than in other languages, since in Rust many semicolons are optional), create a new line after the current one and move the cursor there.

Maybe I can try this myself, but I am **very** new to Kotlin so no promises ):

**Comment by alexpana** [comment]
It seems that https://github.com/intellij-rust/intellij-rust/pull/291 stalled, and since this is marked as `up for grab`, I'm thinking of giving it a try.

**Comment by matklad** [comment]
closed by #347
