### ISSUE TITLE
Enum case is marked as unused if it's used by unqualified name

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#2470]
![image](https://user-images.githubusercontent.com/873919/38765625-590e786e-3fce-11e8-93ca-7d278d259c58.png)

**Comment by Undin** [comment]
Hm, what annotation is shown on `swap` method?
Looks like that `swap` is never used and if it's true then `Player::X` is really never constructed

**Comment by vasily-kirichenko** [comment]
Yes, you are right, thanks.
