### ISSUE TITLE
Status bar error message, angle brackets do no display

### ISSUE THREAD

**Issue by ajjaic** [intellij-rust/intellij-rust#2473]
![image](https://user-images.githubusercontent.com/295616/38792569-395f78ee-416b-11e8-8ae4-139300919b1e.png)

I noticed the status bar error messages when hovering over an error in the editor, do not display properly. The error message was meant to be `mismatched types [E0308]expected \`Result<(), Error>;\`, found \`()\`'

**Comment by ratijas** [comment]
I have duplicated this issue on Jetbrains YouTrack: https://youtrack.jetbrains.com/issue/IDEA-241500

Not sure which Subsystem it belongs to, though.
