### ISSUE TITLE
Wrong mismatched type error for return value Result<File, Error>

### ISSUE THREAD

**Issue by ltfschoen** [intellij-rust/intellij-rust#2474]
I created the following issue in the Fern library, but it appears that the underlying cause is likely intellij-rust https://github.com/daboross/fern/issues/26

**Comment by vlad20012** [comment]
Looks like the bug has already been fixed, but not released yet. Can you please try to use IntelliJ-Rust nightly (pls don't be confused with Rust nightly). You can find the setup instructions [here](https://intellij-rust.github.io/install.html).

**Comment by vlad20012** [comment]
@ltfschoen, is it fixed with the latest release?

**Comment by Undin** [comment]
@ltfschoen feel free to reopen the issue if it doesn't work for you with the latest plugin version
