### ISSUE TITLE
"Apply same member order" generates wrong code

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#2476]
**Steps to reproduce:**
Apply `Apply same member order` quick fix for the following code
```rust
trait Foo {
    type T;
    const C: i32;
    fn foo();
}

struct S;

impl Foo for S/*caret*/ {
    fn foo() { unimplemented!() }
    const C: i32 = unimplemented!();
}
```

**Expected:**
```rust
impl Foo for S {
    const C: i32 = unimplemented!();
    fn foo() { unimplemented!() }
}
```

**Actual:**
```rust
impl Foo for S {
    const C: i32 = unimplemented!();
    const C: i32 = unimplemented!();
}
```

See code of the corresponding inspection and quick fix [here](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/inspections/RsSortImplTraitMembersInspection.kt)

**Comment by JakubAdamWieczorek** [comment]
I'll take a look. :)

**Comment by JakubAdamWieczorek** [comment]
@Undin, are you sure this is the right example? According to the existing test cases the fix for the inspection should not be available in the first place seeing that the `T` member is missing from the `impl`.

**Comment by mkaput** [comment]
Personally I'd expect this intention to work even if I haven't provided all items yet.

**Comment by JakubAdamWieczorek** [comment]
I now see the `RsSortImplTraitMembersInspectionTest` tests were a bit misleading. The inspection does in fact kick in even for incomplete `impls`, as indeed it ought to! :) I submitted a PR that addresses this issue.

**Comment by Undin** [comment]
@JakubAdamWieczorek 👍 
I'll review it asap
