### ISSUE TITLE
Mismatched types

### ISSUE THREAD

**Issue by AurevoirXavier** [intellij-rust/intellij-rust#2482]
Clion 2018.1
OS X 10.13.4

```rust
    let string: String = "string".to_owned();  // Mismatched types [#0308]
    println!("{}", string);
```

Actually, `to_owned()` can create an owned `String` from a string slice.

**Comment by vlad20012** [comment]
Hmm, can't reproduce it
![image](https://user-images.githubusercontent.com/3221931/38999955-93919814-43fb-11e8-9b9f-d03298ac13f0.png)

**Comment by AurevoirXavier** [comment]
@vlad20012 

All the thing with newest version.

[!img](https://i.imgur.com/n8a0LOs.png)

**Comment by AurevoirXavier** [comment]
@vlad20012 
Version: `0.2.0.2326-181-nightly`.
Still got this problem.

**Comment by vlad20012** [comment]
@AurevoirXavier Do you have any dependencies in your project? Could you please list them?

**Comment by AurevoirXavier** [comment]
@vlad20012 Nope. And I create a new project now, but still got that warning.
