### ISSUE TITLE
Highlighting behaves differently when src is not in project root

### ISSUE THREAD

**Issue by gegy1000** [intellij-rust/intellij-rust#2483]
In this given project setup,
![Project](https://i.imgur.com/qhjlMwK.png)

With two identical `main.rs` files of:
```rust
fn main() {
    let v = None;
}
```

The file within `/src` highlights correctly (with run option and None highlight):
![src/main.rs](https://i.imgur.com/jUrFJee.png)

While the file within `/directory/src` does not:
![directory/src/main.rs](https://i.imgur.com/r7UlyjB.png)

**Comment by gegy1000** [comment]
This still occurs if the `Cargo.toml` is in `directory` instead of the root.

**Comment by gegy1000** [comment]
Looks like this is caused by my workspace not being set as a cargo workspace. Whoops!

**Comment by Undin** [comment]
@gegy1000 Looks like that `directory` project is not added as cargo project so IDE applies only base syntax highlighting.
You can add `directory` project into workspace members in root `Cargo.toml` or add `directory` as cargo project manually (someday it will be added automatically) via cargo toolwindow
But it seems in both cases you need separate `Cargo.toml` for `directory` project
