### ISSUE TITLE
Cannot exclude directories/files

### ISSUE THREAD

**Issue by umut-sahin** [intellij-rust/intellij-rust#2493]
I cannot exclude directories manually and target directory is not excluded by default. So if I try to find/replace something using find/replace in path, files in target directory also appear in search. 

![screenshot from 2018-04-24 20-12-14](https://user-images.githubusercontent.com/24782661/39203121-8a6ac86e-47fc-11e8-989a-3d84ff22ce38.png)

This also makes working with node and rust together hard since find/replace in path also searches node_modules.

**Additional information:**
CLion 2018.1.1
Build #CL-181.4445.84, built on April 10, 2018
JRE: 1.8.0_152-release-1136-b27 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.16.3-1-ARCH
Rust plugin: Version: 0.2.0.2093-181

**Comment by kbknapp** [comment]
Same issue.

Additional information:
CLion 2018.1.5
Build #CL-181.5281.33, built on June 14, 2018
JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-23-generic
Rust plugin: Version: 0.2.0.2098-181

**Comment by chrde** [comment]
As a workaround, you can edit your ${project}/.idea/${project}.iml
Replace
`        <content url="file://$MODULE_DIR$" />
`
with
```
<content url="file://$MODULE_DIR$" >
      <excludeFolder url="file://$MODULE_DIR$/target" />
</content>
```
