### ISSUE TITLE
Underscore Imports not expected

### ISSUE THREAD

**Issue by CAD97** [intellij-rust/intellij-rust#2496]
```rust
#![feature(underscore_imports)] // #48216

// std_prelude inspired
pub use std::{
    // Traits
    cmp::{Ord, PartialOrd},
    fmt::{Debug, Display, Write as _},
    io::{Read as _, Write as _, BufRead as _, Seek as _},
    hash::Hash,
};
```

![Imgur](https://i.imgur.com/6RgKuRl.png)

[rust-lang/rust#48216: Tracking issue for RFC #2166: impl-only-use](https://github.com/rust-lang/rust/issues/48216)

Note that now rustc [treats `_` as a reserved identifier](https://github.com/rust-lang/rust/pull/48842) internally. (Logically it still isn't -- for example `macro m($i:ident) {} m!(_)` is still an error -- but this simplifies the internals some.)

**Comment by Undin** [comment]
Fixed in #3528
