### ISSUE TITLE
[Windows] backtrace file link is off-by-one

### ISSUE THREAD

**Issue by CAD97** [intellij-rust/intellij-rust#2502]
![Imgur](https://i.imgur.com/4LyS8zN.png)

(By the way, Windows 10, I got cargo coloring working in the run window by adding `--color always` and log color by [forcing it there](https://docs.rs/slog-term/2.4.0/slog_term/struct.TermDecoratorBuilder.html#method.force_color) as well. Coloring works auto in the terminal, but doesn't automatically happen in the run dialog, but works when forced.)

(Funnily enough, because of the backtrace=short setting in the run configuration, I was having the opposite problem with my backtrace; [failure's Backtrace](https://docs.rs/failure/0.1.1/failure/struct.Backtrace.html) only generates an actual backtrace if `RUST_BACKTRACE` is set, which it was in the run dialog but not in the terminal. I'm now forcing `RUST_BACKTRACE` at program startup.)

**Comment by mchernyavsky** [comment]
It looks like a platform problem. Today I got same error with Kotlin (on macOS).

![image](https://user-images.githubusercontent.com/6079006/49222491-116db000-f3ed-11e8-88a2-36fbbb00563e.png)

**Comment by Undin** [comment]
Looks like it's fixed in the platform
@CAD97 could you check it please on your machine?

**Comment by CAD97** [comment]
This does seem to be correct now.

**Comment by Undin** [comment]
@CAD97 Thanks!
