### ISSUE TITLE
Introduce a variable should be an Intention as well

### ISSUE THREAD

**Issue by strangemonad** [intellij-rust/intellij-rust#2506]
When programming Java in IntelliJ, introduce variable is one of my most common workflows (and it's been around for a while:
https://blog.jetbrains.com/idea/2010/11/smarter-and-faster-introduce-variable-in-java/

It would be cool to have something similar in intellij-rust

**Comment by kumbayo** [comment]
This should already work.
Can you provide an example where it does not work as expected?
Thanks!

**Comment by strangemonad** [comment]
Sorry if I'm missing something obvious. I don't see any intention I could enable that would give me this behaviour. Even the simplest case provides no indication that a variable can be introduced:

```
fn s() -> &str {}
fn main() {
   s();
}
```

**Comment by kumbayo** [comment]
```rust
fn s() -> &str {}
fn main() {
   |s|(|)|;
}
```
I tried placing the cursor at the any of the `|` and pressing Alt-Shift-V.
I always end up with the expected result below.
This more or less matching the actions documented in the link you provided.
```rust
fn s() -> &str {}
fn main() {
    let s = s();
}
```
What i see now is that pressing Alt-Enter at the `|` does not show a `Introduce local variable` action/popup.
While it does show that action in Kotlin/Java projects.

**Comment by strangemonad** [comment]
oh, I see now. Yeah, I was looking for the Alt-Enter key and the Introduce Variable Intention (what java and kotlin use) rather than the extract variable refactor.
