### ISSUE TITLE
Indexing rustc sources takes infinite amount of time

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#251]
Steps to reproduce:

* download and unpack https://static.rust-lang.org/dist/rustc-1.6.0-src.tar.gz
* open `rustc-1.6.0` in IDEA
* wait forever until indexing is done.

Quick profiling again points to error related functions in `ParserUtils`, so it may be the same issue as https://github.com/intellij-rust/intellij-rust/issues/230.

@alexeykudinkin can this be fixed in https://github.com/intellij-rust/intellij-rust/tree/recovering ?

**Comment by matklad** [comment]
I've found (at least one) file that causes problems. It is [super-fast-paren-parsing.rs](https://github.com/rust-lang/rust/blob/master/src/test/run-pass/super-fast-paren-parsing.rs). Guess what's inside! 

Right, it's parens!

```Rust
static a: isize =
(((((((((((((((((((((((((((((((((((((((((((((((((((
(((((((((((((((((((((((((((((((((((((((((((((((((((
(((((((((((((((((((((((((((((((((((((((((((((((((((
(((((((((((((((((((((((((((((((((((((((((((((((((((
(((((((((((((((((((((((((((((((((((((((((((((((((((
1
)))))))))))))))))))))))))))))))))))))))))))))))))))
)))))))))))))))))))))))))))))))))))))))))))))))))))
)))))))))))))))))))))))))))))))))))))))))))))))))))
)))))))))))))))))))))))))))))))))))))))))))))))))))
)))))))))))))))))))))))))))))))))))))))))))))))))))
;
```

**Comment by alexeykudinkin** [comment]
@matklad guess, why is that?

**Comment by matklad** [comment]
It can't deside if it's a paren_expr or tuple_expr

**Comment by matklad** [comment]
Hm, and even I remove `tuple_expr` from the grammar, it fails to parse all ~250 pars of parens. About 230 pairs is Ok though. 

Am I correct that this is [a limitation](https://github.com/JetBrains/Grammar-Kit/blob/a976f3ec0f3ae9f966f2b08cc4af7416ed9a9b5e/support/org/intellij/grammar/parser/GeneratedParserUtilBase.java#L64) of grammar kit?

**Comment by alexeykudinkin** [comment]
Don't forget that we're using patched instance of the GK. Therefore we're capable of doing pretty anything with it.
