### ISSUE TITLE
Add info about supported IDE versions

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#252]
One of the common questions asked about plugin is "does it works with CLion". It would be answered if we had a supported versions section, like in the [go lang plugin](https://github.com/go-lang-plugin-org/go-lang-idea-plugin#pre-release-builds)

Can we generate this automatically based on `plugin.xml`? It can be a nice hackathone idea.

**Comment by alexeykudinkin** [comment]
I believe that it's just one-time thing. Will do this.

**Comment by matklad** [comment]
superseded by https://github.com/intellij-rust/intellij-rust/issues/419
