### ISSUE TITLE
Copyright plugin does not work for rust files 

### ISSUE THREAD

**Issue by marhkb** [intellij-rust/intellij-rust#2524]
I dont't know if this is an issue of intellij-rust or the copyright plugin.
I have configured `File | Settings | Editor | Copyright` to insert a copyright into my rust files.
But this is impossible, because the option to insert a copyright is not displayed at all for rust files.

**Comment by Undin** [comment]
Note, Copyright plugin is not available in CLion (see the corresponding [issue](https://youtrack.jetbrains.com/issue/CPP-10423))
