### ISSUE TITLE
Very slow autocomplete, syntax highlighting

### ISSUE THREAD

**Issue by abhijat** [intellij-rust/intellij-rust#2525]
Hi

I have been experiencing very slow autocomplete and syntax highlighting recently with the plugin. 

The projects I have worked with are fairly small, eg https://github.com/abhijat/mosler

I have attached a CPU profile, thread dumps and the idea.log file. 

The problem I've seen is that after entering a symbol and pressing '.' autocomplete takes 5 to 10 seconds to trigger. 

Syntax highlighting also lags behind by about the same amount of time. Also the symbol name completion is similarly slow.

I have disabled the macro expansion option but it did not seem to make a difference. 

I am on Windows, using intellij ultimate 2018.1.3. The plugin version is 0.2.0.2094-181. The IDE and code are both installed on an SSD. 

I have also seen that the IDE works normally when writing Java and Python code so I suspect this may be specific to the rust plugin.

[logs-20180511-201210.zip](https://github.com/intellij-rust/intellij-rust/files/1995683/logs-20180511-201210.zip)

[IU-181.4892.42_abhijat_11.05.2018_19.57.43.zip](https://github.com/intellij-rust/intellij-rust/files/1995678/IU-181.4892.42_abhijat_11.05.2018_19.57.43.zip)

[threadDumps-freeze-20180511-194702-IU-181.4892.42-8sec.zip](https://github.com/intellij-rust/intellij-rust/files/1995677/threadDumps-freeze-20180511-194702-IU-181.4892.42-8sec.zip)

**Comment by EdeMeijer** [comment]
Just a heads up that the Java max memory setting for Intellij can be a performance killer too if you run into it. I had some performance issues like this while working on a Rust project and increasing Intellij's max memory to 4G solved it for me. 
https://www.jetbrains.com/help/idea/increasing-memory-heap.html

**Comment by abhijat** [comment]
Hi @EdeMeijer , thanks for the tip.

I just cross checked and I've given 4GB to Xmx as well as 2GB for Xms in vmoptions but this is still an issue for me.

**Comment by jgrimes** [comment]
I added these settings:
```
-Xms2048m
-Xmx4096m
-XX:ReservedCodeCacheSize=2048m
```
Seems to have helped somewhat, but my CPU still spikes to nearly 100% across all cores pretty regularly and this behavior still occurs. I even notice this performance problem on a machine with 8 cores, fast NVMe SSD, and 32GB of RAM. It does seem to be correlated with the dependencies: either the number of dependencies or specific ones. Also adding in type annotations can help with the immediate symptoms -- but this isn't really a sustainable option.

I've also noticed there are several issues potentially related to this: https://github.com/intellij-rust/intellij-rust/issues/2486 https://github.com/intellij-rust/intellij-rust/issues/2498 https://github.com/intellij-rust/intellij-rust/issues/2549

This is really my only problem with the plugin so if there is something specific I can do to help get this resolved I'd like to help.

**Comment by Undin** [comment]
@abhijat We've just released a new plugin version with some performance improvements. Could you please check it and give us feedback?

**Comment by abhijat** [comment]
I just checked on windows and Linux and I can confirm I can see some improvement in the responsiveness in autocomplete and syntax highlighting. Unfortunately the CPU spike is still there when completion is triggered but I can see that the autocomplete is now a bit quicker than before. 

If you would like I can supply profiling information if that would help.

**Comment by bl4ck5un** [comment]
I experience the same on macOS. The IDE hangs for seconds from time to time.

**Comment by zhsheng26** [comment]
I experience the same on macOS. The IDE hangs for seconds from time to time.

**Comment by oysterpack** [comment]
The IDE hangs constantly using the rust plugin. I am using Intellij Ultimate 2018.3 on Ubuntu 18.04 on Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz and run it with 4g of JVM heap.

The performance is unacceptable and kills developer productivity.

**Comment by unixunion** [comment]
I noticed significant slowdown in autocomplete, I've bumped XMXup to 2GB, no improvement.  Windows 10 Ryzen 2700X and NVME disks.  Seems to have started after I added a few more dependencies. 

```
solace_semp_client = { git = "https://github.com/unixunion/rust_solace_semp_client.git" }
hyper = "0.11.6"
colored = "1.7"
tokio-core = "0.1.6"
futures = "0.1"
serde_json = "1.0"
clap = "2.32.0"
```

**Comment by SirWindfield** [comment]
I recently started a new project and experience slow autocompletion and type inference right from the start. I have the following dependencies:

```toml
[dependencies]
tokio = "0.1.15"
tower-web = "0.3.4"
clap = "2.32.0"
log = "0.4.6"
env_logger = "0.6.0"
qrcode = "0.9.0"
colored = "1.7.0"
serde_json = "1.0.38"
serde = "1.0.88"
pnet = "0.22.0"
```

CLion takes a solid 1.5-2s until the type annotations are added and my IntelliSense shows up.
Is there any way to help out by providing more information? Log files, PC specs etc. pp.?

**Comment by vlad20012** [comment]
You can disable macro expansion and it should increase performance significantly (but macros will not work, of course). Uncheck Settings | Languages & frameworks | Rust | Expand declarative macros
![image](https://user-images.githubusercontent.com/3221931/53300393-8b300100-3857-11e9-829f-643475265745.png)

We will fix performance problems with macros in #3015

**Comment by SirWindfield** [comment]
@vlad20012 Ah thank you! It improved performance significantly :smile:

**Comment by sci4me** [comment]
Yeah, I don't know why the performance is so bad, but it's unbearable. Alt+Enter leads to a ~5 second delay before the context menu shows up. Syntax highlighting is relatively slow too but not nearly as bad as Alt+Enter.

**Comment by mchernyavsky** [comment]
@sci4me Is [this comment](https://github.com/intellij-rust/intellij-rust/issues/2525#issuecomment-466781080) not working for you?

Can you also check the memory consumption? You can enable memory indicator in settings:
`Preferences > Appearance & Behavior > Windows Options > Show memory indicator`

**Comment by sci4me** [comment]
> @sci4me Is [this comment](https://github.com/intellij-rust/intellij-rust/issues/2525#issuecomment-466781080) not working for you?
> 
> Can you also check the memory consumption? You can enable memory indicator in settings:
> `Preferences > Appearance & Behavior > Windows Options > Show memory indicator`

I assumed it was no longer relevant due to the PR being merged. However, I'm hesitant to disable macro expansion without understanding what it does. I guess I'll give it a shot.

**Comment by mchernyavsky** [comment]
> I assumed it was no longer relevant due to the PR being merged.

This PR will be included in the next release, which is scheduled for tomorrow.

Also, new macro expansion system is disabled by default (see https://github.com/intellij-rust/intellij-rust/issues/3628).

**Comment by abhijat** [comment]
I just wanted to update the devs that I started writing a large rust project again on the latest version (2019.1.1) and IME the plugin is much faster and more responsive. Kudos to the devs for this and the other ergonomic improvements, it's very much more productive now. 

PS I am now working on a workspace based project broken into multiple small crates so this might also have helped in improving autocomplete speed, I'm not sure.

**Comment by Undin** [comment]
> IME the plugin is much faster and more responsive

@abhijat Thanks for the feedback! Glad to hear it!
I think the issue can be closed now and other performance problems should be filed as separate issues

**Comment by steelx** [comment]
still facing this in 2020. Im using i7 with 32GB RAM. Assigned 8GB to IDEA Intellij. while its HEAP always crosses its 499mb mark.
