### ISSUE TITLE
intellij-rust marking public struct private when surrounded by a macro

### ISSUE THREAD

**Issue by benkonz** [intellij-rust/intellij-rust#2531]
I am getting red error markings when I try to access fields in a bitflag that I have created. 

Here is the code for the bitflag:
```rust
bitflags! {
    pub struct LcdControlFlag : u8 {
        const BACKGROUND            = 0b00000001;
        const SPRITES               = 0b00000010;
        const SPRITES_SIZE          = 0b00000100;
        const BACKGROUND_TILE_MAP   = 0b00001000;
        const BACKGROUND_TILE_SET   = 0b00010000;
        const WINDOW                = 0b00100000;
        const WINDOW_TILE_MAP       = 0b01000000;
        const DISPLAY               = 0b10000000;
    }
}
```
When I try to access any of the fields in the bitflag, the plugin thinks that the struct is private, even though the struct is public and the code compiles fine.

![image](https://user-images.githubusercontent.com/18561476/40050961-5db924f8-5839-11e8-88d9-103f2d2e3f1e.png)

**Comment by vlad20012** [comment]
Looks like this is fixed already. Please, check in on the latest plugin.

**Comment by benkonz** [comment]
Yeah, looks like this has been fixed. Thanks.
