### ISSUE TITLE
Cargo project naming restrictions should be reflected in plugin project naming restrictions

### ISSUE THREAD

**Issue by bzm3r** [intellij-rust/intellij-rust#2546]
Trying to create a project named test will make cargo emit: 

`error: The name `test` cannot be used as a crate name`

So, the plugin itself should not allow a project named `test` to be created.

**Comment by kumbayo** [comment]
Cargo contains quite a few limitations for crate names which we are missing.
In crates names it only allows alphanumeric characters and '-' '_'

There is a blacklist of keywords:
https://github.com/rust-lang/cargo/blob/827bf050dcff4315a997649023b245c22d78133c/src/cargo/ops/cargo_new.rs#L132

There is a blacklist of artifact names not allowed for bin crates:
https://github.com/rust-lang/cargo/blob/827bf050dcff4315a997649023b245c22d78133c/src/cargo/core/compiler/layout.rs#L74
