### ISSUE TITLE
Type information for crates referenced in use without an extern crate is missing

### ISSUE THREAD

**Issue by mehcode** [intellij-rust/intellij-rust#2547]
```rust
// main.rs
use parking_lot::Mutex;

fn main {
  let lock = Mutex::new(());
}
```

IntelliJ can't find the `Mutex` type. If you add `extern crate parking_lot`, IntelliJ can find the type again. Note that in nightly (and stable very soon as of Rust 2018) `extern crate` is linted against and is superflous.

**Comment by KodrAus** [comment]
This also affects the new `crate::` style absolute paths, which the syntax parser trips up on.
