### ISSUE TITLE
Add multirust support on Windows

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#255]
Make [this function](https://github.com/intellij-rust/intellij-rust/blob/976779abe3a4e7e9749872780535eeff6dd6b512/src/main/kotlin/org/rust/cargo/project/RustSdkType.kt#L24-L62) handle multirust and windows combo.

**Comment by zjhmale** [comment]
`Windows support` is still a future work of multirust.

**Comment by jajakobyly** [comment]
Windows is supported in multirust-rs

**Comment by zjhmale** [comment]
cool. i will try it this weekend.

**Comment by matklad** [comment]
Hm, I don't think it is worth doing: the new tool, called `rustup` is coming soon, and it will use a different directory structure anyway.

**Comment by zjhmale** [comment]
:joy:
