### ISSUE TITLE
"Unresolved identifier" for absolute path referring to non-pub `use`

### ISSUE THREAD

**Issue by ExpHP** [intellij-rust/intellij-rust#2551]
There are three key components to this I can identify:

* You must have a non-pub `use` of an item somewhere.
* In a child module, you must `use` that `use` (treating it like some sort of "private reexport").
* The `use` in the child module must be an absolute path.

```rust
#[allow(unused)]
mod lol {
    mod hidden {
        pub(crate) struct PubSuperUse;
        pub(crate) struct PrivateUse;
    }

    // three different items that should all be visible to lol::foo
    // (I'd add one for `pub(self) use`, but... the plugin can't parse it)
    struct PrivateStruct;
    use self::hidden::PrivateUse;
    pub(super) use self::hidden::PubSuperUse;

    mod foo {
        //use super::{PrivateStruct, PubSuperUse, PrivateUse}; // works fine
        use ::lol::{PrivateStruct, PubSuperUse, PrivateUse};

        fn bar1() -> PubSuperUse { PubSuperUse }
        fn bar2() -> PrivateStruct { PrivateStruct }
        fn bar3() -> PrivateUse { PrivateUse }
    }
}
```

![screenshot_20180526_121544](https://user-images.githubusercontent.com/1411280/40578231-894a9d38-60de-11e8-81e8-dae3a290cdc9.png)

**Note:** The error depicted currently has an intent associated with it which will add `use ::lol::hidden::PrivateUse` to the top of `mod foo`, ~~which is not actually a visible path.~~

**IntelliJ Rust:** 0.2.0.2095-181
**CLion:** 2018.1

**Comment by Kobzol** [comment]
Works in the latest version of the plugin (with new name resolution).
