### ISSUE TITLE
NullPointerException with macro expansion

### ISSUE THREAD

**Issue by ForsakenHarmony** [intellij-rust/intellij-rust#2552]
This error repeatedly shows up in clion 2018.2 but turning off macro expansion "fixes" it

https://gist.github.com/ForsakenHarmony/1d728e4b4a44b6d7587db053419b5376

This completely kills syntax highlighting, auto complete ...

this project
https://github.com/google/xi-win

**Comment by ForsakenHarmony** [comment]
well it happens on all projects

still haven't really figured out what macro expansion really does currently as well

**Comment by Undin** [comment]
@ForsakenHarmony 
Macro expansion tries to match macro call arguments with macro body and creates new items. It allows us to make item resolution and type inference with items declared via macros.

For example, for the following code
```rust
macro_rules! if_std {
    ($ i:item) => (
        #[cfg(feature = "use_std")]
        $ i
    )
}

struct Foo;
impl Foo {
    fn bar(&self) {}
}

if_std! {
    fn foo() -> Foo { Foo }
}

fn main() {
    foo().bar()
}
```
we know about `foo` function and about its type and can navigate from `bar()` call to its definition
