### ISSUE TITLE
All error highlighting from cargo check disappears after editing the code a bit

### ISSUE THREAD

**Issue by ExpHP** [intellij-rust/intellij-rust#2553]
With "Use cargo check to analyze code" enabled, in version 0.2.0.2095-181:

* I open up a file, and give it a good while for cargo check to run in the background.
* A bunch of errors get highlighted in the source code.
* I begin editing the source.
* After about 20 seconds, as my CPU begins to spin up, **all error highlighting from cargo check vanishes!**  (other errors from IntelliJ are still highlighted)
* Simply waiting or making tiny edits to the source does not ever seem to bring them back.  (I hear my CPU spin down after *something* apparently finishes processing, but no errors appear). The best luck I've had so far is to Ctrl+A, Ctrl+/, Ctrl+/ and then wait.  (Because this takes too long to be practical, I'm now back to spamming cargo check in a run configuration...)

I tried with both possible settings of the new "Expand macros" option.

In version 0.2.0.2087, the highlighted errors never vanished.  They would instantaneously update from one set of error spans to new set of error spans whenever cargo check caught up.

**IntelliJ Rust:** 0.2.0.2095-181
**CLion:** 2018.1

**Comment by mchernyavsky** [comment]
@ExpHP In the past few months, we fixed a lot of bugs related to cargo check. So could you please check the latest version of the plugin?

**Comment by ExpHP** [comment]
I haven't had this issue for a long time now; I will just close the thread.
