### ISSUE TITLE
How to show Unicode characters in debug window?

### ISSUE THREAD

**Issue by VitalyAnkh** [intellij-rust/intellij-rust#2556]
I bind a Chinese sentence to a variable. But when debugging I get unreadable codes. I use Win10, a Chinese version. The CLion and the code file use UTF-8 as default. How to fix this problem?
![snipaste_2018-05-29_02-09-20](https://user-images.githubusercontent.com/24508452/40625879-99923a24-62e7-11e8-8e26-865e0a8c1711.png)
![snipaste_2018-05-29_02-10-48](https://user-images.githubusercontent.com/24508452/40625884-a13f9636-62e7-11e8-91bf-97756daf3a8a.png)

**Comment by ortem** [comment]
@VitalyAnkh Could you please check the issue on your environment?

**Comment by VitalyAnkh** [comment]
@mchernyavsky @ortem Sorry for the late reply. This problem has been fixed, thank you!
