### ISSUE TITLE
Setup search scope for lambda arguments correctly

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#2557]
Looks like the search scope for lambda arguments is bigger than it should be, so renaming it suggest wrong text occurrences:

![image](https://user-images.githubusercontent.com/1711539/40653076-b247b82c-6342-11e8-8d55-6c9d7d2c470a.png)

**Comment by JakubAdamWieczorek** [comment]
There are more constructs where that happens.

```rust
fn main() {
    if let Some(a) = Some(1) {
        println!("{}", a);
    }
    // a

    for b in vec!["string"] {
    }
    // b

    match Some(2) {
        Some(c) => {}
        _ => {}
    }
    // c
}
```

Though to me it seems that restricting the search scope could sometimes be undesirable:

```rust
use std::fs::File;

fn main() {
    if let Ok(mut file) = File::open("data.csv") {
        // ...
    }
    // `file` is closed.
}
```

Either way, looks like https://github.com/intellij-rust/intellij-rust/blob/3d38194c1d70911faf3981a62e0b393b9994b538/src/main/kotlin/org/rust/lang/core/psi/ext/RsPatBinding.kt#L56:L59 is what needs to be modified.
