### ISSUE TITLE
Unexpected result when I try to format code.

### ISSUE THREAD

**Issue by da2018** [intellij-rust/intellij-rust#2559]
```
use api::config::Config;

// ...
#[cfg(test)]
mod tests {
    use api::config::Config;
    use api::client::Client;
    use api::error::Error;
}
```

changes to 
```
use api::config::Config;
use api::config::Config;
use api::client::Client;
 use api::error::Error;
// ...
#[cfg(test)]
mod tests {
}
```

Is this a bug?

**Comment by Undin** [comment]
Yes, it's a bug
But looks like it was fixed in #2521 and landed in the latest release
What version of plugin do you use?

**Comment by da2018** [comment]
version 0.2.0.2094-173

**Comment by Undin** [comment]
Unfortunately, we don't support 2017.3 IDEs anymore and this bug was fixed only for 2018.1 and above
To get the latest plugin version, please, update your IDE to 2018.1

**Comment by Undin** [comment]
Duplicate of #2519

**Comment by da2018** [comment]
Got it.
