### ISSUE TITLE
Add "reformat with rustfmt" action

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#256]
Basically, run `cargo fmt` on the current file. Use [this](https://github.com/intellij-rust/intellij-rust/blob/976779abe3a4e7e9749872780535eeff6dd6b512/src/main/kotlin/org/rust/cargo/commands/Cargo.kt) to run execute cargo. Path to Cargo is available via SDK. You'll need the [skip-children](https://github.com/rust-lang-nursery/rustfmt/pull/719) rustfmt flag.

Relevant docs:
http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/creating_an_action.html
http://www.jetbrains.org/intellij/sdk/docs/basics/action_system.html
http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/creating_an_action.html

**Comment by mrhota** [comment]
dibs!

**Comment by zjhmale** [comment]
this action need `$home/.cargo/bin` in path, maybe should add a not in readme after this issue fixed.
and there are two duplicate links there @matklad

**Comment by mrhota** [comment]
I'm not working on this. Someone else should feel free to pick it up.

**Comment by zjhmale** [comment]
and another issue is that `cargo fmt` command can not receive `write-mode` and `skip-children` options only `rustfmt` command can.

**Comment by matklad** [comment]
If you invoke `cargo fmt` then it will look inside `.cargo/bin` regardless of `PATH`. To pass arguments to `rustfmt`, you can use `--`:

```
cargo fmt -- --skip_children 
```

**Comment by zjhmale** [comment]
cool! i just implemented use `rustfmt` maybe i should change to `cargo fmt` and send pr to fix this issue. but one more question is that `rustfmt` can format a specific file but `cargo fmt` can not, it will format all the files in the cargo project. @matklad

**Comment by zjhmale** [comment]
@matklad one more question is that if i use `rustfmt` it will just format the specific file but if i use `cargo fmt` it will format the super mod file either, just like the verbose progress message shown below.

```
0:42:52 › λ -> cargo fmt -v -- --write-mode=overwrite --skip-children ./src/bar.rs
[Lib] "/Users/xxx/Documents/rustspace/phrase/src/lib.rs"
rustfmt --write-mode=overwrite --skip-children ./src/bar.rs /Users/zjh/Documents/rustspace/phrase/src/lib.rs
```

```
0:43:36 › λ -> rustfmt -v --write-mode=overwrite --skip-children ./src/bar.rs
Formatting ./src/bar.rs
```
