### ISSUE TITLE
Error creating process when debugging

### ISSUE THREAD

**Issue by jajo-11** [intellij-rust/intellij-rust#2565]
If I try to debug code in CLion (2018.1.3) I get the following message:

Error creating process C:\source\repos\numeric_laplace\target\debug\main.exe, (error 50).

The log of GDB does not mention any problems (just the No warranty etc.)
I can debug the same project on Linux.

(the toolchain is set to mingw)

**Comment by qazwsxal** [comment]
Same issue here using stable-gnu

**Comment by Vincent-P** [comment]
Having the same problem here are there any new about that?

**Comment by computersarecool** [comment]
+1

I am having the same issue.

**Comment by jajo-11** [comment]
Not an Intellij issue use MinGW-W64

**Comment by hankbigoldli** [comment]
+1

**Comment by insinfo** [comment]
I'm having this problem, I'm running Clion 200.1, Windows 10,  mingw-w64 x86_64-8.1.0-win32-seh-rt_v6-rev0
```console
C:/MyRustProjects/guessing_game/target/debug/guessing_game.exe
com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$GDBCommandException: Error creating process C:\MyRustProjects\guessing_game\target\debug\guessing_game.exe, (error 50).

Process finished with exit code 0
```

![image](https://user-images.githubusercontent.com/12227024/141498365-4733943b-3ad0-45d6-9f33-756189d4266e.png)
