### ISSUE TITLE
Use declarations in a "UseTree" aren't found well

### ISSUE THREAD

**Issue by delitescere** [intellij-rust/intellij-rust#2568]
Thanks for a lovely editor plugin!

If a Use declaration contains a UseTree (see https://doc.rust-lang.org/reference/items/use-declarations.html), compilation is happy, but the code highlighting / declaration navigation is not.

The following simple examples both compile, but the visual / navigation experience in the IDE is quite different.

```toml
[dependencies]
ansi_term = "0.11"
```

## 😸  
```rust
extern crate ansi_term;

use ansi_term::Colour::Blue;

fn main() {
    let audience = Blue.paint("world"); // also gets type inference / argument name annotations
    println!("Hello, {}!", audience);
}
```

## 😿 
```rust
extern crate ansi_term;

use ansi_term::Colour;
use Colour::Blue;

fn main() {
    let audience = Blue.paint("world");
    println!("Hello, {}!", audience);
}
```

**Comment by Undin** [comment]
Fixed in #2685
