### ISSUE TITLE
Create struct/method from usage refactoring

### ISSUE THREAD

**Issue by JekoTronik** [intellij-rust/intellij-rust#2576]
In my TDD workflow, I start by creating a test in my lib.rs with **tmod** and **tfn**
Which I will complete as follow :
```rust
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_shopping_list() {
        let basket = ShoppingBasket { errands: "" };
        assert_eq!(basket.view(), "Sales Taxes: 0.0 Total: 0.0");
    }
}
```

Then, I would like to extract a struct using some shortcut on **"ShoppingBasket"** word. It would add this at the beginning of my file :
```rust
struct ShoppingBasket {
    errands: ,
}
```
Could add `#[derive(Debug)]` also and suggest errands'type.
Then, I would like to implements a function for the newly created struct using another shortcut on **"basket.view()"**. As a result it would add this after the structure definition : 
```rust
impl ShoppingBasket {
    fn view(&self) -> &str {
        ""
    }
}
```

Is that possible actually ? Or something similar ? No need to create module nor extra file actually.

**Comment by dima74** [comment]
Creating method from usage is now implemented thanks to #6039
