### ISSUE TITLE
"Reformat file with rustfmt" does not work due to unrecognized option 'write-mode'

### ISSUE THREAD

**Issue by Lehona** [intellij-rust/intellij-rust#2579]
When invoking the "Reformat file with rustfmt" shortcut, cargo fails to execute:

Cargo execution failed (exit code 1). C:/Users/Lehona/.cargo/bin/cargo.exe fmt --all -- --write-mode=overwrite --skip-children E:/documents/ChainOfResponsibility/src/main.rs stdout : Unrecognized option: 'write-mode' stderr :

I guess this option has been deprecated or changed names, although I don't know what to change it to for now.

**Comment by Undin** [comment]
Yeah, it's known issue
It's because of `--write-mode` flag was dropped in nightly rustfmt
