### ISSUE TITLE
Implement label break value (RFC 2046)

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#2582]
[RFC](https://github.com/rust-lang/rfcs/blob/master/text/2046-label-break-value.md)
[PR](https://github.com/rust-lang/rust/pull/50045)

**Comment by afetisov** [comment]
Is there something left to do on this issue? The syntax, typechecking, control flow analysis and "experimental feature" diagnostic all seem to be implemented.
