### ISSUE TITLE
Mismatch type.

### ISSUE THREAD

**Issue by AurevoirXavier** [intellij-rust/intellij-rust#2595]
Try this code:

```rust
fn foo(string: &str) -> String {
    string.split_whitespace()
        .fold(
            (vec![], "ignore_this"),
            |(mut v, "ignore_this"), word| {
                v.push(word);
                (v, "ignore_this")
            },
        )
        .0
        .join(" ")
}
```

Mismatch type: 
```
expect `String`, found `Vec<str>`
```

UPD:
## Environment

* **IntelliJ Rust plugin version:** 0.4.151.3975-211-nightly
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.1.3 Ultimate Edition (IU-211.7628.21)
* **Operating system:** macOS 10.15.6
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
The plugin fails to infer type of `.join` call

![image](https://user-images.githubusercontent.com/2539310/125190089-1735fe00-e244-11eb-9323-e5cb321a4007.png)

**Comment by Undin** [comment]
@vlad20012 
I've reproduced it with `nightly-2018-04-15` toolchain. With the latest stable and nightly toolchain type inference works correctly

@AurevoirXavier It's a bug but as a workaround try to update your rust toolchain

**Comment by AurevoirXavier** [comment]
@Undin 

But I'm in `2018-06-23`. Now I update to `2018-06-27`, still got this problem.

**Comment by Kobzol** [comment]
The type is correct in the latest version of the plugin.

**Comment by Undin** [comment]
Looks like the plugin stops producing error here just because it can't infer type of `.join` call (i.e. type if `unknown`).
So I think it should be reopened

**Comment by vlad20012** [comment]
Now it seems to work
![image](https://user-images.githubusercontent.com/3221931/167849765-e2b99843-7b63-457a-a82f-63bcd52a4ea9.png)
