### ISSUE TITLE
Auto-completion Not Working

### ISSUE THREAD

**Issue by Noah11012** [intellij-rust/intellij-rust#2600]
I have CLion version 2018.1.5 and I have installed the nightly build of the Rust plugin. The version is 0.2.0.2352-181-nightly if you needed to know. I have tried reinstalling the plugin with no luck.

**Comment by Undin** [comment]
The latest nightly plugin version really has a bug
Try the latest release build please or wait for next nightly build

**Comment by Noah11012** [comment]
Next nightly update fixed my problem.
