### ISSUE TITLE
CPU exausted

### ISSUE THREAD

**Issue by qiuxiafei** [intellij-rust/intellij-rust#2606]
When I working on a rust project, the Intellij-IDEA exhausted 4 CPU cores frequently. The process sample is in this file: [intellij-sample.txt](https://github.com/intellij-rust/intellij-rust/files/2130848/intellij-sample.txt)

And the jvm stack:  [jstack.txt](https://github.com/intellij-rust/intellij-rust/files/2130860/jstack.txt).

My idea version:
```
IntelliJ IDEA 2018.1.5 (Ultimate Edition)
Build #IU-181.5281.24, built on June 12, 2018
Licensed to qiu xiafei
Subscription is active until November 30, 2018
JRE: 1.8.0_152-release-1136-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.5
```

And rust plugin version is: `Version: 0.2.0.2098-181`.

**Comment by ForsakenHarmony** [comment]
I feel like something has happened in a recent update that has made the plugin a lot slower and heavier on the cpu

**Comment by qiuxiafei** [comment]
Checked. New version works!

**Comment by qiuxiafei** [comment]
Well, I mean it works on version 77. I didn't recognize version 78 just released, I'll try it.

**Comment by amenzhinsky** [comment]
Well better now, thanks! But it's still really slow compared to other languages.

**Comment by Undin** [comment]
@amenzhinsky unfortunately, it's expected
Rust has more complex type system than almost all common languages so all intellisense features require more computations. But of course, we'll try to make it quicker
