### ISSUE TITLE
Wrong link to changelog 76 displayed in IntelliJ

### ISSUE THREAD

**Issue by DjebbZ** [intellij-rust/intellij-rust#2609]
Hi,

IntelliJ prompted me to update the Rust plugin (Rust 0.2.0.2096-181 -> 0.2.0.2098-181), it displayed the following link for the changelog :
`https://intellij-rust.github.io/2018/06/20/changelog-76.html`
whereas the correct one should be
`https://intellij-rust.github.io/2018/06/19/changelog-76.html` (day 19, not 20).

I'm sure you can't do anything about this one, but maybe someone could investigate the cause of this "bug" to prevent it from happening again. I have no idea what the process is, it could be a human error.

End of the report !

**Comment by Undin** [comment]
Hi!
Thanks for the report
Actually, the link is correct but page address is not 😄 
It's already fixed in https://github.com/intellij-rust/intellij-rust.github.io/commit/a7cdb7b3613dfc9881e0c9c824ddc61873781fc0
