### ISSUE TITLE
Error java.lang.NoSuchMethod when compiling in IDEA 15.0.3 on Linux Mint 17.3

### ISSUE THREAD

**Issue by Discordia** [intellij-rust/intellij-rust#261]
What I do:
1. Installed rust the normal way. Then installed cargo-nightly so version of cargo is: 
"cargo 0.9.0-nightly (c91bf61 2016-02-24)"
2. Installed the intellij-rust plugin as instructed, worked fine. Version of IDEA is 15.0.3. And type is Ultimate. Running on Linux Mint 17.3.
3. Import a project by opening the cargo.toml. Tested with the guessing_game and hello_world from "the book". Also tested glutin. Every time it imports fine but then there is no rust SDK setup so I do that. Looks fine. Rust compiler version is 1.6.0 (rustc 1.6.0 (c30b771ad 2016-01-19)).
4. Then I press Ctrl+F9 to build and it starts but fails. Output is:
"Information:cargo: cargo build
Information:2016-02-24 14:46 - Compilation completed with 1 error and 0 warnings in 5s 55ms
Error:Module 'glutin' production: java.lang.NoSuchMethodError: kotlin.sequences.SequencesKt.generateSequence(Lkotlin/jvm/functions/Function0;)Lkotlin/sequences/Sequence;"

**Comment by matklad** [comment]
You need to update your Kotlin plugin. This is mentioned in docs,

> At the moment you also need to update the Kotlin plugin to the latest version.

but it's easy to miss. Sorry about this inconvenience,

**Comment by Discordia** [comment]
Ok that worked, thanks. You should really put that in the README.md under installation.

**Comment by matklad** [comment]
Indeed we should. Fixed, thanks!
