### ISSUE TITLE
TOML: support dotted keys

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#2610]
Now `foo.bar = "baz"` is valid toml
See the corresponding [paragraph](https://github.com/toml-lang/toml#user-content-keys) in toml readme for more details

**Comment by ericnchen** [comment]
I'm looking for this feature as well.

I'm using PyCharm + the toml package and `foo.bar = "baz"` parses as `{"foo": {"bar": "baz"}}` as expected, but the toml plugin is highlighting the period as an error. There seems to be no way to disable this error as well.

**Comment by TanVD** [comment]
It's a real pain guys, waiting for the feature as well
