### ISSUE TITLE
`std` lib resolve

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#262]
We need to attach sources to the SDK and actually resolve `std`.

This may is relevant: https://github.com/Diggsey/multirust-rs/issues/37

**Comment by matklad** [comment]
Mostly done. 

Something like https://github.com/intellij-rust/intellij-rust/pull/277 is needed to fix resolve withing stdlib itself (this is most important for the prelude, which is not resolved at the moment)

https://github.com/intellij-rust/intellij-rust/pull/313 is a nice to have for this feature.

**Comment by alexeykudinkin** [comment]
#277 is in progress.
