### ISSUE TITLE
Some std references aren't resolved

### ISSUE THREAD

**Issue by mfarrugi** [intellij-rust/intellij-rust#2633]
I also see the #2220  error, but I'm not sure if it's related.

```
use std::ffi::CString; // resolves
use std::path::Path; // resolves
use std::ptr::NonNull; // doesn't resolve
use std::slice; // doesn't resolve
```

Looks like libstd resolves, but not libcore? 

Intellij-rust is pointing to an unzipped `wget https://static.rust-lang.org/dist/rustc-1.27.0-src.tar.gz`, ie. not installed via rustup. The issue is fixed when I grab a new copy of the sources, or by moving the existing, seemingly broken copy somewhere else. 

Something fishy is going on.. how would I go about debugging why only some of the refs weren't being resolved? I thought it might be some internal corporate issue, but would expect that to cause intellij-rust to not work with the stdlib at all.

As a side note, the Standard Library config continues to use the previous path if the new path does not contain sources.

**Comment by mfarrugi** [comment]
The issue here was using `rustc-src` instead of `rust-src`, the former only contains a subset of the standard library.

**Comment by mfarrugi** [comment]
I was wrong about my fix.

It appears to be some issue with resolving libcore and/or the libstd prelude when the rust/src directory is 
- read-only (linux 644) and owned by another user
- fuse mounted (eg. sshfs)
that does not happen when the same files are copied as the user (linux 444, me).

I should be able to at least add some debug printing to the below spots and make progress.. but would be ecstatic to hear any hints :)

---

Sort of independently of this issue, should these places that are resolving the standard library provided by a user complain a bit more loudly if something is amiss?

https://github.com/intellij-rust/intellij-rust/blob/627887ef3961d11f2d91643158d61f435b34925a/src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt#L42-L49

https://github.com/intellij-rust/intellij-rust/blob/1dca9f516eff6b1b65c3c5a4bb5efc3a45320d33/src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt#L841-L844

---
Some strace logs that didn't really help me..
```
# Local, 444 owner=marco group=$company
  27048 lstat("/home/marco/test/ijr/rust-sources/src/libstd/prelude/v1.rs",  <unfinished ...>
  27046 <... gettimeofday resumed> {1533172447, 11054}, NULL) = 0
  27048 <... lstat resumed> {st_mode=S_IFREG|0440, st_size=2327, ...}) = 0
  27046 gettimeofday( <unfinished ...>
> 27048 open("/home/marco/test/ijr/rust-sources/src/libstd/prelude/v1.rs", O_RDONLY <unfinished ...>
  
Works.
  
# Local, 644 owner=$notme group=$company
  30147 lstat("/opt/rust/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/prelude/v1.rs",  <unfinished ...>
  21453 clock_gettime(CLOCK_MONOTONIC, {1318750, 997182834}) = 0                                           
  30147 <... lstat resumed> {st_mode=S_IFREG|0644, st_size=2327, ...}) = 0                                                                                                                                                                                      
  21453 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
  30147 access("/opt/rust/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/prelude/v1.rs", W_OK <unfinished ...>
  21453 <... clock_gettime resumed> {1318750, 997250937}) = 0
  30147 <... access resumed> )            = -1 EACCES (Permission denied)

Never opened; doesn't work.

# Fuse Mounted, 644 owner=$notme group=$company

  30420 lstat("/home/marco/mounted/rust/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/prelude/v1.rs",  <unfinished ...>
  29980 <... fstat resumed> {st_mode=S_IFREG|0644, st_size=4298, ...}) = 0
  30420 <... lstat resumed> {st_mode=S_IFREG|0644, st_size=2329, ...}) = 0
  29980 read(571,  <unfinished ...>
  30420 access("/home/marco/mounted/rust/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/prelude/v1.rs", W_OK <unfinished ...>
  21453 <... futex resumed> )             = -1 ETIMEDOUT (Connection timed out)
  30420 <... access resumed> )            = -1 EROFS (Read-only file system)
  21453 futex(0x2ee01d8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
> 30420 open("/home/marco/mounted/rust/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/prelude/v1.rs", O_RDONLY <unfinished ...>
  21453 <... futex resumed> )             = 0
  30420 <... open resumed> )              = 574
  21453 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
  30420 fstat(574,  <unfinished ...>
  21453 <... clock_gettime resumed> {1318899, 554359377}) = 0
  30420 <... fstat resumed> {st_mode=S_IFREG|0644, st_size=2329, ...}) = 0
  21453 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
  30420 read(574,  <unfinished ...>

Opened but doesn't work.
```

**Comment by snaar** [comment]
I had same issue with rust-src installed via nix - it might be relevant that it lives in /nix/store/ here. I poked at it randomly and it somehow went away, possibly after I blew away .idea directory and recreated the project.

**Comment by pschuprikov** [comment]
My guess is that the problem might be due to a little symlink-resolving incosistency. When a path is checked for being a crate root, the symlinks are eventually resolved here https://github.com/intellij-rust/intellij-rust/blob/7b3ea026d83acccd98a6ccb792de14ef3b6a6fff/src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt#L132-L133 Unfortunately, in the next line the resulting URL is being checked against URLs that were constructed (in case of *stdlib*) without any symlink resolution here https://github.com/intellij-rust/intellij-rust/blob/7b3ea026d83acccd98a6ccb792de14ef3b6a6fff/src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt#L43-L48  

I am totally new to the code base, and I do not know how `isCrateRoot` affects name resolution, but after I added `?.canonicalFile` to the end of https://github.com/intellij-rust/intellij-rust/blob/7b3ea026d83acccd98a6ccb792de14ef3b6a6fff/src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt#L43 at least *prelude* started to resolve correctly.

**Comment by Undin** [comment]
@mfarrugi Looks like we fixed this issue. Could you check that name resolution works correctly in your case with the latest plugin?

**Comment by mfarrugi** [comment]
@Undin confirming this fixes it for me.

**Comment by Undin** [comment]
@mfarrugi Great!
