### ISSUE TITLE
Struct fields don't auto ident until close brace reformatting?

### ISSUE THREAD

**Issue by mjlbach** [intellij-rust/intellij-rust#2634]
With IdeaVim I find it preferable to disable "Insert paired bracket", "Insert pair quote", and "Insert pair '}'" under Smart Keys such that I do not have to leave normal mode to skip over a close bracket (You can only type through close brackets and if they are on the same line). 

I recently have found that the autoident fails when typing struct field names. I'm not sure if this is a configuration issue, but it doesn't seem to happen in similar C++ code (I use Clion).

![out](https://user-images.githubusercontent.com/13316262/42247576-46487ab2-7ed6-11e8-9b58-b2429634908b.gif)

**Comment by neonaot** [comment]
We cannot reproduce this problem now.
If it is still relevant please reopen this issue or create a new one.
