### ISSUE TITLE
No completion suggestions except for main.rs

### ISSUE THREAD

**Issue by ChijinZ** [intellij-rust/intellij-rust#2654]
## Environment

* **Intellij-Rust plugin version: Pycharm 2018.1.4 (Professional Edition)**
* **IDE name and version: Version: 0.2.0.2099-181**
* **Operating system: Ubuntu 16.04 LTS**

## Problem description

I found that I only got completion suggestions in main.rs. 

<img width="507" alt="2" src="https://user-images.githubusercontent.com/32416157/42416242-d616d53a-829b-11e8-968c-4d87d7974ff9.png">
<img width="506" alt="3" src="https://user-images.githubusercontent.com/32416157/42416243-d9177e6a-829b-11e8-9315-cfd83535d046.png">

I' not sure whether I miss some settings or not. But I verify that trash.rs has attached with Cargo.toml.

**Comment by Undin** [comment]
Looks like that `trash` module isn't declared in `main.rs`.
Try to add `mod trash;` in `main.rs`
