### ISSUE TITLE
add release tags

### ISSUE THREAD

**Issue by lazyuser** [intellij-rust/intellij-rust#2660]
Please add a git tag for each release [available for download](https://plugins.jetbrains.com/plugin/8182-rust). I've just tried to investigate a regression, but was unable to correlate between releases and commits.

**Comment by Undin** [comment]
Some time ago we started to create release branches like https://github.com/intellij-rust/intellij-rust/tree/release-105
For more details see [here](https://github.com/intellij-rust/intellij-rust/blob/master/MAINTAINING.md#releases)
I think it should solve this issue
