### ISSUE TITLE
testCargoMetadata failed

### ISSUE THREAD

**Issue by zjhmale** [intellij-rust/intellij-rust#267]
when i run `./gradlew test`

i got a test case failed

```
org.rust.cargo.commands.CargoTestCase > testCargoMetadata FAILED
    com.intellij.execution.ExecutionException: No metadata subcommand, please update cargo
        at org.rust.cargo.commands.Cargo.execute(Cargo.kt:76)
        at org.rust.cargo.commands.Cargo.fullProjectDescription(Cargo.kt:43)
        at org.rust.cargo.commands.Cargo.fullProjectDescription$default(Cargo.kt:42)
        at org.rust.cargo.commands.CargoTestCase.testCargoMetadata(CargoTestCase.kt:11)
```

and i currently get 

* `rustc 1.6.0`
* `cargo 0.8.0 (28a0cbb 2016-01-17)`

how can i fix it.

**Comment by matklad** [comment]
You can update cargo :) `cargo 0.9.0-nightly (6c05bcb 2016-01-29)` is the minimal version, which has metadata command. 

This particular test picks `cargo` from `$PATH` and is skipped if `cargo` is not found. So if you don't want to update cargo, it's fine just to remove it from PATH, or just change [this condition](https://github.com/intellij-rust/intellij-rust/blob/master/src/test/kotlin/org/rust/cargo/CargoTestCaseBase.kt#L15) to true.

**Comment by zjhmale** [comment]
:ok_hand: thx :)

**Comment by zjhmale** [comment]
but i find latest version of cargo is 0.8.0 https://github.com/rust-lang/cargo/releases @matklad

**Comment by matklad** [comment]
Yes, 0.9.0 is a yet-to-be release nightly version (it will hit stable with Rust 1.8). You can install it with multirust (nightly toolchain), or from a tarball linked in Cargo's readme.

**Comment by zjhmale** [comment]
thx! i just upgrade cargo to `0.9.0-nightly (8fc3fd8 2016-02-29)` and fix it.
