### ISSUE TITLE
Type hints for enum variants are not shown

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#2690]
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2374-182-nightly
* **IDE name and version:** IU-182.3684.40
* **Operating system:** macOS 10.13.5

## Problem description

Type hints for enum variants are not shown

## Steps to reproduce

```rust
let a = Some(10);
let b = Ok("abc");
```
<img width="264" alt="screen shot 2018-07-20 at 11 35 30" src="https://user-images.githubusercontent.com/2539310/42992389-0fa78f64-8c11-11e8-9a3f-96e6a5967fac.png">

**Comment by Undin** [comment]
@paavohuhtala issue for your corresponding twitter message
Type inference works fine in this case (you can check it via quick documentation, for example)
But we really have a bug with type hints for enum variants
Thanks for the catch!

**Comment by paavohuhtala** [comment]
@Undin I think my issue was something different, as at the time I did not get any autocompletion for types defined in `core` (like Option and Result). Restarting once or twice fixed it though, so I can't repro it anymore.

**Comment by Undin** [comment]
@paavohuhtala interesting
If you reproduce it again, could you please create an issue about it?
Anyway, there is a bug with type hints for enum variants

**Comment by Undin** [comment]
I've just remembered that we implemented such behavior intentionally to not show type hints in trivial cases
We have `Show only smart hints` option in rust settings panel to switch off it
