### ISSUE TITLE
type inference went wrong with match **.as_str()

### ISSUE THREAD

**Issue by longwusha** [intellij-rust/intellij-rust#2695]
## Environment

* **Intellij-Rust plugin version:0.2.0.2100-181
* **IDE name and version:CLION 2018.1.6
* **Operating system:deepin linux 15.6

## Problem description
[type inference error]
Something went wrong with match **.as_str()
The plugin tell me that Error:(29, 17) mismatched types [E0308]expected `str`, found `&str`.
In fact, I succeeded in building and running my program, and all the test cases were passed.

## Steps to reproduce
token.rs

#[derive(PartialEq, Clone, Debug)]
pub enum Token {
    Define,
    Extern,
    Delimiter,
    OpenParenthesis,
    CloseParenthesis,
    Comma,
    Identifier(String),
    Number(f64),
    Operator(String),
}

lexer.rs

use regex::Regex;
use token::Token::*;
use token::Token;

pub fn tokenize(input: &str) -> Vec<Token> {
    // 注释：以#开头，以\n结尾
    let comment_re = Regex::new(r"(?m)#.*\n").unwrap();
    // 从输入中移除所有注释（使用空行替代）
    let preprocessed = comment_re.replace_all(input, "\n");

    // token的正则表达式，目前只是不同令牌类型的简单正则表达式的并集
    // 运算符以与标识符相同的方式解析，对它们的区分将在后面进行
    let token_re = Regex::new(concat!(
        r"(?P<identifier>\p{Alphabetic}\w*)|",
        r"(?P<number>\d+\.?\d*)|",
        r"(?P<delimiter>;)|",
        r"(?P<oppar>\()|",
        r"(?P<clpar>\))|",
        r"(?P<comma>,)|",
        r"(?P<operator>\S)")).unwrap();

    // 定义解析结果
    let mut result = Vec::new();

    // 根据正则表达式匹配结果，对输入进行解析
    for cap in token_re.captures_iter(preprocessed.as_ref()) {
        let token = if cap.name("identifier").is_some() {
            match cap.name("identifier").unwrap().as_str() {
                "def" => Define,
                "extern" => Extern,
                identifier => Identifier(identifier.to_string())
            }
        } else if cap.name("number").is_some() {
            match cap.name("number").unwrap().as_str().parse() {
                Ok(number) => Number(number),
                Err(_) => panic!("Lexer failed trying to parse number")
            }
        } else if cap.name("delimiter").is_some() {
            Delimiter
        } else if cap.name("oppar").is_some() {
            OpenParenthesis
        } else if cap.name("clpar").is_some() {
            CloseParenthesis
        } else if cap.name("comma").is_some() {
            Comma
        } else {
            Operator(cap.name("operator").unwrap().as_str().to_string())
        };

        result.push(token)
    }

    result
}

#[cfg(test)]
mod tests {
    use lexer::tokenize;
    use token::Token::*;

    #[test]
    fn identifier() {
        let tokens = tokenize("test");
        let expected_tokens = vec![Identifier("test".to_string())];
        assert_eq!(tokens, expected_tokens);
    }

    #[test]
    fn define() {
        let tokens = tokenize("def");
        let expected_tokens = vec![Define];
        assert_eq!(tokens, expected_tokens);
    }

    #[test]
    fn external() {
        let tokens = tokenize("extern");
        let expected_tokens = vec![Extern];
        assert_eq!(tokens, expected_tokens);
    }

    #[test]
    fn number() {
        let tokens = tokenize("123");
        let expected_tokens = vec![Number(123.0)];
        assert_eq!(tokens, expected_tokens);

        let tokens = tokenize("123.1");
        let expected_tokens = vec![Number(123.1)];
        assert_eq!(tokens, expected_tokens);

        let tokens = tokenize("0.1");
        let expected_tokens = vec![Number(0.1)];
        assert_eq!(tokens, expected_tokens);
    }

    #[test]
    fn delimiter() {
        let tokens = tokenize(";");
        let expected_tokens = vec![Delimiter];
        assert_eq!(tokens, expected_tokens);

        let tokens = tokenize("123;");
        let expected_tokens = vec![Number(123.0), Delimiter];
        assert_eq!(tokens, expected_tokens);

        let tokens = tokenize("abc;");
        let expected_tokens = vec![Identifier("abc".to_string()), Delimiter];
        assert_eq!(tokens, expected_tokens);
    }

    #[test]
    fn parenthesis() {
        let tokens = tokenize("(");
        let expected_tokens = vec![OpenParenthesis];
        assert_eq!(tokens, expected_tokens);

        let tokens = tokenize(")");
        let expected_tokens = vec![CloseParenthesis];
        assert_eq!(tokens, expected_tokens);

        let tokens = tokenize("(abc)");
        let expected_tokens = vec![OpenParenthesis, Identifier("abc".to_string()), CloseParenthesis];
        assert_eq!(tokens, expected_tokens);

        let tokens = tokenize("(12)");
        let expected_tokens = vec![OpenParenthesis, Number(12.0), CloseParenthesis];
        assert_eq!(tokens, expected_tokens);
    }

    #[test]
    fn comma() {
        let tokens = tokenize(",");
        let expected_tokens = vec![Comma];
        assert_eq!(tokens, expected_tokens);

        let tokens = tokenize("x,y");
        let expected_tokens = vec![Identifier("x".to_string()), Comma, Identifier("y".to_string())];
        assert_eq!(tokens, expected_tokens);

        let tokens = tokenize("1,2");
        let expected_tokens = vec![Number(1.0), Comma, Number(2.0)];
        assert_eq!(tokens, expected_tokens);
    }

    #[test]
    fn operator() {
        let tokens = tokenize("+");
        let expected_tokens = vec![Operator("+".to_string())];
        assert_eq!(tokens, expected_tokens);

        let tokens = tokenize("-");
        let expected_tokens = vec![Operator("-".to_string())];
        assert_eq!(tokens, expected_tokens);

        let tokens = tokenize("*");
        let expected_tokens = vec![Operator("*".to_string())];
        assert_eq!(tokens, expected_tokens);

        let tokens = tokenize("/");
        let expected_tokens = vec![Operator("/".to_string())];
        assert_eq!(tokens, expected_tokens);

        let tokens = tokenize("%");
        let expected_tokens = vec![Operator("%".to_string())];
        assert_eq!(tokens, expected_tokens);

        let tokens = tokenize("=");
        let expected_tokens = vec![Operator("=".to_string())];
        assert_eq!(tokens, expected_tokens);
    }
}

**Comment by vlad20012** [comment]
Duplicate #2670

**Comment by longwusha** [comment]
Any one know how to upload rust file to github?
I fail to do that,because rust file is not a supported file type.

**Comment by vlad20012** [comment]
You can just create a gist https://gist.github.com/

**Comment by longwusha** [comment]
@vlad20012 

Thank you!

**Comment by longwusha** [comment]
How can I deal with it?
Just ignore it,or maybe there is some way to disable this error?

**Comment by vlad20012** [comment]
Alt+enter -> right arrow -> disable inspection
![image](https://user-images.githubusercontent.com/3221931/43037160-ecce9c50-8d12-11e8-9ad6-28dfb11cf878.png)
