### ISSUE TITLE
f64::from type inference broken

### ISSUE THREAD

**Issue by eric1221bday** [intellij-rust/intellij-rust#2713]
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2101-182
* **Rust toolchain version:** rustc 1.26.0 (a77568041 2018-05-07)
* **IDE name and version:** CLion 2018.2
* **Operating system:** MacOS 10.13.5

## Problem description

There seems to be a bug in the parser that causes it to flag valid and recommend lossless casting code as mismatched types error.

Per recommendation from clippy here (https://rust-lang-nursery.github.io/rust-clippy/v0.0.204/index.html#cast_lossless) lossless casting should be done with `::from` instead of `as`. This didn't use to be an issue but after the recent update this seems to be broken.

In particular the error thrown is `mismatched types [E0308], expected i8, found u32`

<img width="576" alt="screen shot 2018-07-26 at 11 03 10 pm" src="https://user-images.githubusercontent.com/8923171/43265674-9eb1728a-9128-11e8-9c06-57f3ac90167a.png">

## Steps to reproduce

1. declare u32 variable
2. cast u32 to f64 using `f64::from`

```rust
const TOP_BAR_HEIGHT: u32 = 27;
let y_board = y - f64::from(TOP_BAR_HEIGHT);
```

**Comment by Ploppz** [comment]
Could this be related to my issue?
![scrot](https://i.imgur.com/micBvTw.png)
It should work according to [this](https://docs.rs/stdweb/*/stdweb/web/struct.TypedArray.html?search=#implementations) - `impl<'a, T: ArrayKind> From<&'a [T]> for TypedArray<T>`. The code is here https://github.com/koute/stdweb/blob/master/examples/webgl/src/main.rs#L154.

Also something I find strange is that in the output window, this error does not even show up, only a completely unrelated error somewhere else. (assuming that the same errors that are displayed in the code will show up in the console window, sorry if this is wrong)

**Comment by eun-ice** [comment]
I would upvote this bug, since [cargo clippy](https://github.com/rust-lang-nursery/rust-clippy) actually encourages type casts to be in this form.
