### ISSUE TITLE
`self` parameter is not highlighted when select

### ISSUE THREAD

**Issue by orium** [intellij-rust/intellij-rust#2722]
Places where parameters are used are usually highlighted when the cursor is over them:

![regular parameter highlight](https://i.imgur.com/YBFZ5Wb.png)

However this does not happen for `self`, which would be very useful:

![no highlight for self](https://i.imgur.com/YjUvhX7.png)

**Comment by ortem** [comment]
Highlighting works fine when the caret is at the beginning of self parameter declaration:
<img width="136" alt="self" src="https://user-images.githubusercontent.com/4854600/43459715-10e39f16-94d7-11e8-847a-a66af0cfd790.png">
But I think it should work in above case too.

**Comment by mibac138** [comment]
Fixed by #3804
