### ISSUE TITLE
Cargo check in wrong directory

### ISSUE THREAD

**Issue by Ploppz** [intellij-rust/intellij-rust#2723]
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2101-181
* **Rust toolchain version:** rustc 1.29.0-nightly (6a1c0637c 2018-07-23)
* **IDE name and version:** From Arch Linux package repository: `Name            : intellij-idea-community-edition \\ Version         : 2:2018.1.5-1`
* **Operating system:** Arch Linux

## Problem description & reproduction
`cargo check` seems to be called in the wrong directory when I try to compile an example:
1. Clone https://github.com/koute/stdweb
2. Open IntelliJ and open `examples/webgl/` as project root.

When I am editing `main.rs`, right-click and click "Recompile main.rs", I get these errors in the bottom window in IntelliJ:
```
/home/ploppz/.cargo/bin/cargo check --color=always --all --all-targets
    Checking hasher v0.1.0 (file:///home/ploppz/code/rust/stdweb/examples/hasher)
   Compiling webgl v0.1.0 (file:///home/ploppz/code/rust/stdweb/examples/webgl)
error[E0432]: unresolved import `stdweb::js_export`
 --> hasher/src/lib.rs:8:5
  |
8 | use stdweb::js_export;
  |     ^^^^^^^^^^^^^^^^^ no `js_export` in the root

error: cannot determine resolution for the attribute macro `js_export`
  --> hasher/src/lib.rs:11:3
   |
11 | #[js_export]
   |   ^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `hasher`.
warning: build failed, waiting for other jobs to finish...
```

Why is it `check`ing in the `hasher` directory?

**Comment by Undin** [comment]
It's because we try to compile all targets by default. To turn off such behavior use `Preferences > Language & Frameworks > Rust > Compile all project targets if possible`

**Comment by Undin** [comment]
@Ploppz does it fix your issue?

**Comment by Ploppz** [comment]
Yes, thanks.
