### ISSUE TITLE
Shows error on correct code. (TypedArray::from)

### ISSUE THREAD

**Issue by Ploppz** [intellij-rust/intellij-rust#2724]
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2101-181
* **Rust toolchain version:** rustc 1.29.0-nightly (6a1c0637c 2018-07-23)
* **IDE name and version:** From Arch Linux package repository: `Name            : intellij-idea-community-edition \\ Version         : 2:2018.1.5-1`
* **Operating system:** Arch Linux

## Problem description & reproduction
1. Clone https://github.com/koute/stdweb
2. Open IntelliJ and open `examples/webgl/` as project root.
3. Open `main.rs`
![scrot](https://i.imgur.com/0Iv0hPc.png)
It should work according to [this](https://docs.rs/stdweb/*/stdweb/web/struct.TypedArray.html?search=#implementations) - `impl<'a, T: ArrayKind> From<&'a [T]> for TypedArray<T>`. The code is here https://github.com/koute/stdweb/blob/master/examples/webgl/src/main.rs#L154.

**Comment by Kobzol** [comment]
This now works in the current version of the plugin.
