### ISSUE TITLE
Remove unnecessary parenthesis around condition quick fix/inspection

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#274]
Oftentimes I write

```Rust
if (cond) {
    // do stuff
}
```

and it's cumbersome to remove parenthesis manually. I wish there were an inspection for this.

Docs:
http://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support/annotator.html
http://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support/quick_fix.html

Example:
https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/inspections/UnresolvedModuleDeclarationInspection.kt

Test:
https://github.com/intellij-rust/intellij-rust/blob/master/src/test/kotlin/org/rust/ide/inspections/RustInspectionsTest.kt

**Comment by zjhmale** [comment]
can you explain more specific what this issue really want to do? it is really confused me.

did you mean can auto remove parenthesis just like

from

```rust
if (cond) {
    // do stuff
}
```

to 

```rust
if (cond) // do stuff
```

but in rust you must put code inside a block after if statement.

thx for more detailed explaination :)

**Comment by jajakobyly** [comment]
Parenthesis are `()`, `{}` are called brackets.

The idea of the issue is to transform
```rust
if (cond) {...}
```
into
```rust
if cond {...}
```

**Comment by zjhmale** [comment]
sorry... i just confused with these two words :sweat_smile:

**Comment by juicycool92** [comment]
Thanks for nice reply @mkaput .
I totally understand why, after read this section.
> Which is more _rusty_.

lol
