### ISSUE TITLE
Add "go to super mod" action

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#275]

**Comment by zjhmale** [comment]
did you mean [this](http://rustbyexample.com/mod/super.html) ?

**Comment by matklad** [comment]
Yes. If file `src/foo/bar.rs` is open in editor, I want to have an action to navigate to `src/foo/mod.rs`. There is already a function for retrieving super module: https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/lang/core/psi/util/RustModExtensions.kt#L53, but the action itself is missing.
