### ISSUE TITLE
Add "Invert if condition" intention

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#2754]
The intention should negate the condition and swap the if's branches. 

Here's a similar intentino in Kotlin: https://github.com/JetBrains/kotlin/blob/efec82c0ebcf6ff26b88f6e411785c3df5510f7e/idea/src/org/jetbrains/kotlin/idea/intentions/InvertIfConditionIntention.kt. We don't need to implement **all** the features in one go, but it might be a good idea to look at it to see what's possible.

Here's a related intention in IntelliJ Rust:
https://github.com/intellij-rust/intellij-rust/blob/3fe98015358240e48a45150554875903d93e1256/src/main/kotlin/org/rust/ide/intentions/AddElseIntention.kt
https://github.com/intellij-rust/intellij-rust/blob/3fe98015358240e48a45150554875903d93e1256/src/test/kotlin/org/rust/ide/intentions/AddElseIntentionTest.kt

**Comment by zinoviy23** [comment]
I want to try implement this feature
