### ISSUE TITLE
Impls for aliased types are ignored

### ISSUE THREAD

**Issue by cheblin** [intellij-rust/intellij-rust#2778]
## Environment

* **Intellij-Rust plugin version:** 0.20.2103-182
* **Rust toolchain version:** stable-x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2018.2.2 (Ultimate Edition)
Build #IU-182.4129.26, built on August 16, 2018
Licensed to Sirguy Chikirev
Subscription is active until March 21, 2019
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
* **Operating system:**

## Problem description
IDE  IntelliSense do not recognize Rust type aliases.  

## Steps to reproduce
create default executable Rust project, and insert this snippet.
```Rust
struct EE {
    pub field1: u32,
    pub field2: u8,
}

type XX = EE;

impl XX {
    pub fn new() -> XX {
        XX { field1: 2, field2: 3 }
    }
}

fn main() {
    let xx = XX::new(); // new() is not recognized by intellisense
    println!("{:?}", xx.field2); //xx type in not recognized by intellisense

    let yy = EE::new();// new() is not recognized by intellisense
    println!("{:?}", yy.field2); //yy type in not recognized by intellisense
}
```

but the code is correct and compile / executed properly.

**Comment by z2665** [comment]
I get the same problem.  When I use libc. the type aliases, like  pub type c_int = i32; can't recognized by intellisense

**Comment by cheblin** [comment]
IDEA cannot recognize aliased types totally... and Impls  to.

**Comment by vlad20012** [comment]
@cheblin m? It isn't truth. We support type aliases in all cases excluding impls for aliased types. If you bumped into a bug, please, provide more info.
![image](https://user-images.githubusercontent.com/3221931/44513081-1a036b80-a6c5-11e8-923f-f20759239288.png)

**Comment by cheblin** [comment]
![capture1](https://user-images.githubusercontent.com/29354319/44624162-d739d180-a918-11e8-9dc1-76e87a9cea42.PNG)
![capture2](https://user-images.githubusercontent.com/29354319/44624163-dbfe8580-a918-11e8-9b5a-eea4a211ad65.PNG)

**Comment by vlad20012** [comment]
@cheblin, Yep, the last comment is an unknown bug. I fixed it in #2797. Thanks for the report!

**Comment by Kobzol** [comment]
How difficult would it be to implement this, could you maybe provide some mentoring hints? My projects typically use impls on aliased types a lot, so this would help to get better code completion.

**Comment by vlad20012** [comment]
@Kobzol Oh, I have a branch that implements this, I just forget to push it =/
