### ISSUE TITLE
into_iter() isn't recognized for slices leading to unknown types

### ISSUE THREAD

**Issue by YaLTeR** [intellij-rust/intellij-rust#2780]
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2103-182
* **Rust toolchain version:** 1.28.0
* **IDE name and version:** CLion 2018.2
* **Operating system:** Arch Linux

## Problem description
![image](https://user-images.githubusercontent.com/1794388/44312504-13919d00-a402-11e8-9b63-952bb32ade84.png)

## Steps to reproduce
Create a new project with the following code and observe the issues.
```rust
fn main() {
    let arr = &[1, 2, 3, 4, 5];

    for entry in arr {
        // `entry` has unknown type.
        println!("{}", entry);
    }

    for entry in arr.into_iter() {
        // `entry` has unknown type.
        // `into_iter()` is not recognized.
        println!("{}", entry);
    }

    for entry in arr.iter() {
        // `entry` has known type.
        println!("{}", entry);
    }
}
```

**Comment by NyxCode** [comment]
just stumbled over this too. 
![image](https://i.imgur.com/3ZkKZ3r.png)
both implementations redirect to the same file when clicked on.

**Comment by vlad20012** [comment]
@NyxCode looks like some recent stdlib changes in the nightly Rust break our name resolution. As work-around, you can use stable Rust for now.

**Comment by NyxCode** [comment]
oh, that seems to work. thanks.

**Comment by NyxCode** [comment]
nevermind, it still isn't working. i am on 1.36.0 (stable).

**Comment by Kobzol** [comment]
It was probably caused by missing support for const generics. It works in the current version of the plugin.
