### ISSUE TITLE
Invalid resolution for function defined in a macro.

### ISSUE THREAD

**Issue by blackbeam** [intellij-rust/intellij-rust#2787]
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2104-182
* **Rust toolchain version:** 1.28.0
* **IDE name and version:** CLion 2018.2.1
* **Operating system:** macOS 10.13.6

## Project description
`Cargo.toml`:
```toml
[package]
name = "idea-issue"
version = "0.1.0"
authors = ["blackbeam <aikorsky@gmail.com>"]

[dependencies]
exonum = "0.9.1"
```

`src/lib.rs`:
```rust
#[macro_use]
extern crate exonum;

encoding_struct! {
    struct Dummy {
        foo: u8,
    }
}

fn foo() {
    let dummy = Dummy::new(0);
}
```

## Problem description
Resolution for `Dummy` is correct:
<img width="302" alt="2018-08-22 12 13 30" src="https://user-images.githubusercontent.com/155883/44455332-79e70d00-a606-11e8-90f2-d801ee099b5d.png">

However, resolution for `Dummy::new` is somehow `digest::digest::Digest::new`:
<img width="333" alt="2018-08-22 12 14 41" src="https://user-images.githubusercontent.com/155883/44455418-b0248c80-a606-11e8-883b-8e7348fa093d.png">

So an error reported as a result:
<img width="504" alt="2018-08-22 12 11 12" src="https://user-images.githubusercontent.com/155883/44455471-cdf1f180-a606-11e8-8ccd-38fe55dfe7fb.png">

And this is true for every struct defined using `encoding_struct!` macro and leads to gazillions of annoying errors:
<img width="194" alt="2018-08-22 12 36 18" src="https://user-images.githubusercontent.com/155883/44455931-ff1ef180-a607-11e8-9a11-e03780fd4b83.png">

**Comment by vlad20012** [comment]
Should be fixed with #2458
