### ISSUE TITLE
Code completion not working for external crates?

### ISSUE THREAD

**Issue by typoon** [intellij-rust/intellij-rust#2793]
## Environment

I have tried this with both CLion 2018.2.2 and IDEA Ultimate version 2018.2.2.
The Rust plugin version is 0.2.0.2103-182

Tried with both Rust 1.28 and nightly (1.30 at this time).

Operating System is Ubuntu 17.10.

## Problem description

I have added an external crate to the project (rand), but can't get any code completin from it.
I added the "rand" dependency in the Cargo.toml file and it was succesfully installed.

When I add "extern crate rand;" to the code, the IDE understands it fine.

If I type "use rand::<ctrl+space>" to see the completions, I only see some defaults but none of the expected ones. See image below:

![Code completion](https://i.imgur.com/bHkp7Aj.png)

I expected to see for example the "Rng" module being suggested there.

## Steps to reproduce

Create a new Rust project.
Add the following line to the `Cargo.toml` file:

~~~
rand = "0.3"
~~~

Compile the project.

Edit the `main.rs` file and add the following code to it:

~~~rust
extern crate rand;

use rand::<ctrl+space>

fn main() {
}
~~~

**Comment by Undin** [comment]
Looks like that your project model is not updated after changes in `Cargo.toml`
Try to sync project explicitly via sync button in cargo toolwindow. Also check that option `Watch Cargo.toml` is enabled - it should update your project model automatically

**Comment by typoon** [comment]
Alright, I made some progress. When I include rand 0.3, Cargo will compile and install both rand 0.3.22 and 0.4.3 (at this time). The `Cargo.toml` looks like this:

~~~
[dependencies]
rand = "0.3.22"
~~~

And a `cargo build` will generate this output:

~~~
 $ cargo build
   Compiling libc v0.2.43                                                                                                                                                                                           
   Compiling rand v0.4.3
   Compiling rand v0.3.22
   Compiling bla v0.1.0 (file:///home/henrique/tmp/rust/bla)
   Finished dev [unoptimized + debuginfo] target(s) in 2.32s
~~~

So there are 2 `rand` crates in the project.

If I create a new project and instead tell it to use `rand` 0.4:

~~~
[dependencies]
rand = "0.4"
~~~

Then `cargo build` will install just one `rand` crate, and the auto complete feature works.

So it seems there is some sort of bug where Intellij-rust doesn't know what to do if there are two versions of a crate in the project.

**Comment by vlad20012** [comment]
Duplicate #2439, I guess
