### ISSUE TITLE
I would like to use --all-features

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#2812]
_From @timbru on August 30, 2018 11:29_

I use a feature in my project that is required for a certain module to be available. When I run tests the feature is not enabled by default and my module is not compiled, and my test doesn't run. I can then edit the configuration for the test I ran and add '--all-features'. Then things work as desired.

I have this work around, so this is not critical, but it would be very nice if this behaviour could be the default, or if there would be a way to configure this for my whole project. Now, I need to re-do this whenever I move things around, add new feature dependent modules, or whenever I want to run a single new test in this module.

I am sorry if I missed how this can be done today, happy to learn :)

_Copied from original issue: intellij-rust/intellij-rust.github.io#62_

**Comment by timbru** [comment]
Thanks a lot!
