### ISSUE TITLE
Allow color scheme customization of the `unsafe` keyword

### ISSUE THREAD

**Issue by aloucks** [intellij-rust/intellij-rust#2814]
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2104-182

## Problem description

Add the ability to change the `unsafe` keyword color independently of other keywords:

![image](https://user-images.githubusercontent.com/221559/29736474-87436f56-89cf-11e7-870a-581f61f32ea1.png)

![image](https://user-images.githubusercontent.com/221559/44881703-8a3e5e00-ac7e-11e8-8061-7c13de616da5.png)

**Comment by Undin** [comment]
@aloucks Could you clarify use case?

**Comment by Undin** [comment]
@aloucks But why do you want this? How will it help you?

Currently, I'm against this feature because:
* It's not common behavior - I don't know any other language in IntelliJ platform with the similar option
* Looks like it's quite redundant because if you see such highlighting you already can see function signature or a start of unsafe block (otherwise, such highlighting doesn't help at all)
* It may lead to the desire to customize of all other keywords

**Comment by aloucks** [comment]
The `unsafe` keyword is rather unique in the sense that it doesn't have counterparts in most other languages and it doesn't fit into most other categories of keywords. It's more akin to an annotation in the sense that it flags a function or a code block. The purpose of the `unsafe` keyword is to explicitly declare that certain safety checks are disabled in the function or code block and that you must be extra careful. Allowing it to have a custom color enables it to stand out visually and quickly draw attention to it. 

Overall, I think it _looks nicer_ and helps me identify unsafe sections quicker. You could argue that's subjective, but it's also not a minority opinion. The other editors already support this.

**Comment by matklad** [comment]
Seems like an ok option to add to me: though I personally hate when different keywords get different highlighting, and I don't think that unsafe specifically needs any more calling out, I also think that some users might find this feature useful. 

That said, I think a more fun feature would be to add "unsafe code" inspection, disabled by default, which should allow to quickly find all instances of unsafe in the codebase.
