### ISSUE TITLE
Fix escape handling for non-byte strings

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#283]
Basically, fix this: https://github.com/intellij-rust/intellij-rust/commit/2886d63e9c12b4ba86dfcc4e39de842b2dc46efe

Kudos to @jajakobyly for investigation

**Comment by jajakobyly** [comment]
Generally speaking, *extended* byte escapes are actually only allowed in byte literals. The commit 2886d63 allowed them for all kind of strings.

The thing to do is to limit this change only for byte literals.
