### ISSUE TITLE
Support for cross platform development

### ISSUE THREAD

**Issue by ancwrd1** [intellij-rust/intellij-rust#2846]
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2104-182
* **Rust toolchain version:** 1.29.0
* **IDE name and version:** IntelliJ 2018.2 commuinity
* **Operating system:** Linux 64-bit

## Problem description
It would be nice to support cross-platform development, in particular a possibility to define a target for a project, for example x86_64-pc-windows-gnu to be able to work on Windows-specific project but under Linux environment.
Currently it's not possible as IDE always assumes the host OS as the target and compilation fails for OS-specific code parts.

**Comment by Mikayex** [comment]
It seems working if you create a `.cargo/config` file at the root of your repository with this content:
```
[build]
target = "arm-unknown-linux-gnueabihf" #Or whatever triplet you use
```
More info : https://doc.rust-lang.org/cargo/reference/config.html

**Comment by vlad20012** [comment]
FYI now the plugin takes Cargo config into account to evaluate `cfg` options. So you need to add the following code into your `.cargo/config`
```toml
[build]
target = "wasm32-unknown-unknown"
```

to fix the issue.

Note, the feature is available in [nightly](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly) builds for now and will be landed in the next ([v146](https://github.com/intellij-rust/intellij-rust/milestone/54?closed=1)) stable plugin version. Also, it requires at least Rust 1.52 (currently in beta). See #7093 for more details

**Comment by ancwrd1** [comment]
Thank you very much for your great work on Rust plugin, highly appreciated!

**Comment by alexlapa** [comment]
> So you need to add the following code into your .cargo/config

It seems that this feature does not work correctly when there are multiple crates in workspace.
Changing top-level crate's `.cargo/config` changes intellisense behaviour in all workspace members, but changing `.cargo/config` in workspace member has no effect.

**Comment by Undin** [comment]
@alexlapa I've created a separate issue with this use case - #7175
