### ISSUE TITLE
Copyright in footer of github page outdated (2016)

### ISSUE THREAD

**Issue by kolloch** [intellij-rust/intellij-rust#2847]
## Problem description

The copyright in the footer of the github pages seems outdated since there has been so much good new stuff:

https://intellij-rust.github.io/

© 2016 Marek Kaput and contributors
© 2016 JetBrains

**Comment by Kobzol** [comment]
It has been since updated:
![image](https://user-images.githubusercontent.com/4539057/103282054-cd3aa880-49d4-11eb-928d-ab61fd443c6f.png)
