### ISSUE TITLE
Incorrect error: expected `n16`, found `u8`

### ISSUE THREAD

**Issue by kryptan** [intellij-rust/intellij-rust#2876]
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2106-181
* **Rust toolchain version:** rustc 1.30.0-nightly (cb6d2dfa8 2018-09-16)
* **IDE name and version:** IDEA 2018.1
* **Operating system:** Windows 10

## Problem description

Expression `u16::from(0u8)` shows error "expected `n16`, found `u8`". In reality there is no error and code is accepted by rustc.

![image](https://user-images.githubusercontent.com/11528855/46149034-0f169a80-c272-11e8-8280-45d912e58889.png)

**Comment by vlad20012** [comment]
Hmm, I hoped that it will be fixed by #2903, but your case is a combination of 2 bugs =D
