### ISSUE TITLE
No autocomplete for std modules and types are highlighted in red

### ISSUE THREAD

**Issue by gngeorgiev** [intellij-rust/intellij-rust#2877]
## Environment

* **Intellij-Rust plugin version: v0.2.0.2106-183/-v0.2.0.2106-183-nightly** 
* **Rust toolchain version: cargo 1.31.0-nightly (de314a8b2 2018-09-21) / rustc 1.30.0-nightly (887690686 2018-09-27)**
* **IDE name and version: CLion 2018.2/2018.3**
* **Operating system: OS X High Sierra**

## Problem description

There's no autocomplete for any module inside `std`. Also importing a module, e.g. `std::io::Error` highlights the error in the code in red. Didn't have such problems with the previous version of the plugin. Cargo builds the project fine and in the directory where my toolchain sources should be the files appear to be fine, I also just tried updating with rustup, no changes.

## Steps to reproduce

Just creating a new project within the CLion IDE with a simple hello world fn causes the problem for me:

```rust
use std::io::Error;

fn main() -> Result<(), Error> {
    println!("Hello, world!");
    Ok(())
}
```

https://cl.ly/6757255ff1ef

**Comment by JoshMcguigan** [comment]
I am able to reproduce this error in the following environment.

## Environment
Intellij-Rust plugin version: v0.2.0.2106-182
Rust toolchain version: rustc 1.30.0-nightly (90d36fb59 2018-09-13)
IntelliJ IDEA 2018.2.4 (Ultimate Edition)
Build #IU-182.4505.22, built on September 18, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
Operating system: OS X High Sierra 10.13.6

**Comment by Techcable** [comment]
I am able to reproduce this on Linux using the latest plugin release.
Oddly, ctrl-hovering over the 'std' portion of the path claims 'multiple implementations',
both of which point to the same file (/home/nicholas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/lib.rs).

When I upgraded to this release, I had a similar problem where explicit extern crate declarations conflicted with my implicit 2018 edition import and references to the crate wouldn't resolve. Similarly to the issue with std, ctrl-hovering showed it had 'multiple declarations'. Removing the explicit extern crate declaration fixed the issue and references to the crate resolved again. Maybe the issue with std crates is similar?

Oddly enough all of the items in the prelude work properly, but manually imported items don't seem to work at all.
Could you please publish an release as soon as you fix this issue? This makes autocomplete  and type inference all but useless.
Funny thing is, even without any support for types from the standard library your autocomplete is still leaps and bounds ahead of racer and the RLS :laughing: 

## Environment
Intellij-Rust plugin version: 
Rust toolchain version: cargo 1.31.0-nightly (de314a8b2 2018-09-21) / rustc 1.30.0-nightly (887690686 2018-09-27)
IDE name and version: CLion 2018.2/2018.3
Operating system: OS X High Sierra

**Comment by gngeorgiev** [comment]
For anyone interested, the `fix-std-crate-resolution` branch seems to have fixed this, you can build the plugin and install it from disk until the changes get to the nightly.

**Comment by DCjanus** [comment]
Temporary solution: replace `std::xxx` with `::std::xxx`.

**Comment by gngeorgiev** [comment]
@DCjanus `rustfmt` removes the leading `::` by default. I don't think there's a setting to change this behavior.

**Comment by laptou** [comment]
I am experiencing this issue again; when I control+hover over a reference to `std` it says "multiple implementations", but they all point to the same implementation. Autocomplete for `std` modules does not work.

OS: Ubuntu 18.10
IDE: CLion 2018.3.4
IntelliJ-Rust: v0.2.91.2115-183
Rust: rustc 1.32.0 (9fda7c223 2019-01-16)
