### ISSUE TITLE
Wrong lifetime lint error

### ISSUE THREAD

**Issue by Veykril** [intellij-rust/intellij-rust#2887]
## Environment

* **Intellij-Rust plugin version: 0.2.0.2106-182**
* **Rust toolchain version: rustc 1.30.0-nightly (551244f05 2018-09-10)**
* **IDE name and version: CLion 2018.2.4**
* **Operating system: Windows 10**

## Problem description
The ide gives me a `needless_lifetimes` lint error, even though the program does not compile without the lifetimes. This only happens with impl in argument position, using generics by declaring them in the <> it works fine.

## Steps to reproduce
```rust

extern crate either;
use either::Either;

pub struct Dummy;

pub type DummyType<'a> = Either<&'a str, Dummy>;

fn test<'a>(_class: impl Into<DummyType<'a>>) {}
```
![clion64_2018-09-30_21-35-10](https://user-images.githubusercontent.com/3757771/46261858-bfe29b00-c4f9-11e8-8070-a8e50774284c.png)

**Comment by mchernyavsky** [comment]
Thanks for report! I will fix it and #2844 after merge #2868.
