### ISSUE TITLE
Multiple implementations for extern crate + use in 2018 edition

### ISSUE THREAD

**Issue by mguillemot-tel** [intellij-rust/intellij-rust#2893]
## Environment

* **Intellij-Rust plugin version:** 0.2.0.SNAPSHOT-182
* **Rust toolchain version:** rustc 1.30.0-nightly (887690686 2018-09-27)
* **IDE name and version:** IntelliJ IDEA Community 2018.2
* **Operating system:** OSX High Sierra

## Problem description

When using Rust in 2018 edition mode, `extern crate` declarations conflict with `use` declarations for the same modules. For example:

```rust
extern crate hex;

use hex::encode;

fn main() {
    let d = encode(vec![1u8, 2u8]);
    println!("Result: {:?}", &d);
}
```

The IDE would not be able to resolve the `encode()` call in main(), with tooltip "Unresolved reference: 'encode'".

This seems to be a similar problem to #2877: the IDE reports "Multiple implementations" for the `hex` module. I built the branch `fix-std-crate-resolution` and it fixes the issue for `use std::` patterns, but not for this case.

The obvious workaround is removing the `extern crate` declaration which is no longer necessary in Rust 2018, but this makes it awkward to switch between editions. Furthermore, having the `extern crate` declaration is correct, even if not required; the IDE should probably accept it.

## Steps to reproduce

Open the provided module in the IDE with `edition = "2018"` enabled in Cargo.toml.

The module compiles fine, but the IDE will not be able to resolve `encode`.

**Comment by prasannavl** [comment]
@mguillemot-tel - Does 2018 edition work otherwise? My CLion throw a fit having almost zero auto-complete and inspection by merely just having `edition = 2018`. Removed it and works like charm, with my "semi-2018" projects just as long as I add `extern crate`s.

**Comment by mguillemot-tel** [comment]
@prasannavl Yes I don't have any particular problem with `edition = "2018"` when I remove all the `extern crate`. Note that I'm using the `fix-std-crate-resolution` branch of the Rust plugin, which I built myself. Before that, I had trouble with everything coming from `std`, which might explain why everything looks broken to you. One workaround for that was replacing all `use std::x` by `use ::std::x`.
