### ISSUE TITLE
Support "Go to Declaration" inside macros

### ISSUE THREAD

**Issue by HighCommander4** [intellij-rust/intellij-rust#2898]
It would be very useful if "Go to Declaration" worked inside macro invocations.

For example, in the following macro invocation:

```rust
error_chain! {
    foreign_links {
        Json(serde_json::Error)
    }
}
````

if you would be nice if "Go to Declaration" worked on `serde_json::Error`.

Eclipse CDT supports this for C/C++ macros. Their general implementation strategy is:

* When expanding macros, keep track of a mapping between tokens in the source text, and where in the macro expansion they end up.
* When performing "Go to Declaration" on a token inside a macro invocation, use the mapping to look up the corresponding token in the (final) expansion. (If there are multiple such tokens in the final expansion, can try each one, or pick the first, or something.)
* Perform "Go to Declaration" as if it had been invoked on the token in the expansion.

**Comment by vlad20012** [comment]
Yep, I'm going to try this approach. When will be free time =)

**Comment by vlad20012** [comment]
Yeah, this approach works great! I've just made a prototype and it works as expected. I'll finish it right after #3015 landing.

**Comment by vlad20012** [comment]
Will be very soon. All preparations are done #3640
