### ISSUE TITLE
Support `#[path=]` attribute for mod decls

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#294]
Change this guys https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/lang/core/psi/util/RustModExtensions.kt#L62-L75

to use `path=` and to conform to changes in https://github.com/rust-lang/rust/pull/31534

**Comment by matklad** [comment]
Path attributes are added in https://github.com/intellij-rust/intellij-rust/commit/084d59ab2930d140bda13f4bd4dcb110561bfde7

**Comment by zjhmale** [comment]
Cheers!
