### ISSUE TITLE
Implement `New Cargo Project` action

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#2944]
It would be great to have `New > Cargo Project` action in the context menu like `New > Rust File` action that we already have.

**Comment by amakeev** [comment]
`File | New Project` seem to already have 'Rust' project type in IntelliJ IDEA and CLion.
Do you mean an action that would create a Cargo.toml?

**Comment by vlad20012** [comment]
> Do you mean an action that would create a Cargo.toml?

Yep. Well-formatted Cargo.toml and `src` directory. It's usual case to crate a nested crate.

**Comment by Kobzol** [comment]
Fixed by https://github.com/intellij-rust/intellij-rust/pull/3519.
