### ISSUE TITLE
--nocapture default removed from Cargo test

### ISSUE THREAD

**Issue by jmmk** [intellij-rust/intellij-rust#2979]
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2109-182

## Problem description

Prior to the latest version, output from `println!` calls in tests would be shown in the console (See https://github.com/intellij-rust/intellij-rust/issues/1086)

The latest version merged #2901 which removes the `--nocapture` argument and no longer displays test output. Maybe it's intended, but it caught me off guard

I also see there's an open issue https://github.com/rust-lang/rust/issues/54669 to perhaps address this

## Steps to reproduce

```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        println!("invisible output");
    }
}
```

**Comment by mchernyavsky** [comment]
Hello.

Oh, I didn't think that changing the default options in this particular case can cause trouble.

At the moment we can't support the `--nocapture` option (https://github.com/rust-lang/rust/issues/54669 describes the problem). For the present, we're waiting for an answer from libtest developers.

**Comment by chinedufn** [comment]
@mchernyavsky are there any settings that we can tweak in the IDE to disable `--format=json` and instead enable `--nocapture` for the time being?

**Comment by mchernyavsky** [comment]
@chinedufn https://github.com/intellij-rust/intellij-rust/pull/3004 will partially solve the problem.
