### ISSUE TITLE
What's the meaning of Rust SDK?

### ISSUE THREAD

**Issue by coderplay** [intellij-rust/intellij-rust#299]
Seems there is no such term in rust.  Where is it? I work on Mac OS, no idea which path I should configure to.

**Comment by coderplay** [comment]
ok, I figured out. It's the home directory of `rustc`

**Comment by matklad** [comment]
Yes, SDK is an IntelliJ IDEA specific term for a set of development tools for a particular language. In case of Rust, SDK is basically just cargo. 

There is a explanation of how to setup SDK in [quck start](https://github.com/intellij-rust/intellij-rust/blob/master/doc/Usage.md#quick-start). It is a bit to terse at the moment, but I am planing to improve SDK setup workflow soon, so the docs will get an update.

**Comment by matklad** [comment]
FYI docs updated with a short explanation of what SDK is: https://github.com/intellij-rust/intellij-rust/blob/master/doc/QuickStart.md

**Comment by t0r0X** [comment]
Updates:
* the Quickstart page has moved: https://intellij-rust.github.io/docs/quick-start.html
* the FAQ page tries to explain why there is no SDK: https://intellij-rust.github.io/docs/faq.html
* the Troubleshooting page mentions also the toolchain settings: https://intellij-rust.github.io/docs/troubleshooting.html#is-the-rust-toolchain-properly-setup
