### ISSUE TITLE
Rust REPL console like in PyCharm

### ISSUE THREAD

**Issue by Hoeze** [intellij-rust/intellij-rust#2991]
[There is a new Rust REPL from google.](https://github.com/google/evcxr)

It would be cool if this would be integrated into Intellij.
Imagine programming rust would be as comfortable as writing python code...

**Comment by CAD97** [comment]
(Minor clarification: this isn't a Google product, it's just a project owned by Google (because everything a Google employee makes is owned by Google by default).)

**Comment by ortem** [comment]
Fixed by https://github.com/intellij-rust/intellij-rust/pull/4615

**Comment by Hoeze** [comment]
@ortem I just retried running the Rust REPL.
Is there a possibility to spawn it in debug mode?
In PyCharm, the most useful feature IMO is that I can:
- set a breakpoint
- go to the Console window
- start an interactive session and try code

**Comment by dima74** [comment]
@Hoeze no, unfortunately it is not possible now to use debugging within Rust REPL

**Comment by Hoeze** [comment]
@dima74 Is there any chance to get this working?
What would be needed for that?

**Comment by dima74** [comment]
@Hoeze currently we communicate with evcxr using simple text protocol. We send commands to evcxr, it compile and evaluate them, and we receive command output back. Integrating debugging into this workflow requires changes both to IntelliJ Rust and Evcxr and sounds like rather complex task. So unfortunately we don't have such plans at the moment
