### ISSUE TITLE
First test result status is always unknown

### ISSUE THREAD

**Issue by technic** [intellij-rust/intellij-rust#2996]
## Environment

* **Intellij-Rust plugin version:** 
Version: 0.2.0.2109-182

* **Rust toolchain version:** 
$ cargo --version
cargo 1.30.0 (36d96825d 2018-10-24)
$ rustup.exe --version
rustup 1.14.0 (a364ad985 2018-09-25)
$ rustc.exe --version
rustc 1.30.0 (da5f414c2 2018-10-24)

* **IDE name and version:** 
PyCharm 2018.2.4 (Professional Edition)

* **Operating system:**
Windows 10 Version 1803

## Problem description

Test window doesn't show status of the first test:
![screenshot](https://github.com/technic/rust-idea-test/raw/master/screenshot.png)

## Steps to reproduce
Open this sample [project](https://github.com/technic/rust-idea-test) in IDE. Run the tests.

**Comment by vvvy** [comment]
+1
IDE name and version:
IntelliJ IDEA 2018.2.5 (Community Edition)
Build #IC-182.4892.20, built on October 16, 2018
JRE: 1.8.0_152-release-1248-b19 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by vlad20012** [comment]
Current status: we can't reproduce it on MAC and Linux, will check on Windows soon

**Comment by mchernyavsky** [comment]
I managed to reproduce the issue on my Windows 10.

**Comment by caiopsouza** [comment]
The same happens if you run a single test on my Windows 10.

**Comment by technic** [comment]
Updated to Version: 0.2.0.2110-182
but it didn't fix the problem for me.

**Comment by technic** [comment]
Checked it on 0.2.0.2471-182-nightly today and it works!
Great job JetBrains 👍
