### ISSUE TITLE
Wrong type name resolution.

### ISSUE THREAD

**Issue by crlf0710** [intellij-rust/intellij-rust#2997]
Hello, I've met this problem: In Rust std prelude, there's a `Result` type, with two type parameters. In a third party crate called `wio`, there's a `Result` type too, but with one type parameter.

According to rust type name resolution, if i `use ::wio::Result` in my module, all `Result` should resolve to  `wio::Result`, but without the `use`, the `Result` should resolve to the std one.

Currently it seems intellij-rust always resolves to the one in prelude. Maybe it's lookup order problem, i don't know.

**Comment by Patryk27** [comment]
Are you sure you don't have a wildcard use somewhere at the top of your file? (like `use wio::*;`)

**Comment by crlf0710** [comment]
Well, i mean it *should* resolve to `wio::Result` but it resolves to `std` one instead, and prompts for one type parameter missing.

**Comment by vlad20012** [comment]
I guess the problem is that `::wio::Result` defined with a macro, and we failed to expand that macro (for a some reason). Could you please check it?

**Comment by vlad20012** [comment]
Is it `wio = "0.2.0"` crate? Rustc don't wont to compile this expample =D

![image](https://user-images.githubusercontent.com/3221931/47739901-81223b00-dc87-11e8-9063-81cec1344d32.png)

**Comment by crlf0710** [comment]
@vlad20012 `wio` is a windows-only crate, it's defined with this code.

```
use std::result;
use winapi::shared::minwindef::DWORD;
use winapi::um::errhandlingapi::GetLastError;
#[derive(Clone, Copy, Debug)]
pub struct Error(DWORD);
impl Error {
    pub fn code(&self) -> u32 { self.0 }
}

pub type Result<T> = result::Result<T, Error>;
```

**Comment by dima74** [comment]
@mili-l could you please test this on windows?

```toml
[dependencies]
wio = "0.2.0"
```

```rust
use wio::Result;

// Result here should resolve to `wio`
type Test = Result<i32>;
```

**Comment by dima74** [comment]
Looks like it was fixed some time ago. Please feel free to reopen or create new issue if encounter any problems
