### ISSUE TITLE
Ctrl-Alt-Up/Down not working in test tool window when compilation fails

### ISSUE THREAD

**Issue by dvtomas** [intellij-rust/intellij-rust#3002]
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2109-182

## Problem description

When ordinary compilation (Ctrl-F9, Shift-F10 with run configuration) fails, I can use Ctrl-Alt-Up/Down arrows to jump around the compilation errors. This is immensely useful. Now that the plugin has received preliminary support for proper test tool (btw, that's great, thank you for that!), when the compilation fails, the test tool reports "Test framework quit unexpectedly", and the compiler output shows up in the right pane of the test tool. However, Ctrl-Alt-Up/Down doesn't work with that, I need to grab the mouse and click on the errors, I'm forced to do that like hundred times a day :-( (I use TDD extensively)

**Comment by vlad20012** [comment]
I think Ctrl-Alt-Up/Down don't work even for regular compilation, not just in tests =)
But I heard @mchernyavsky is going to solve it =)

**Comment by dvtomas** [comment]
For regular compilation it works fine, it's just the test tool not playing along..
