### ISSUE TITLE
Cannot debug in Windows

### ISSUE THREAD

**Issue by xdray** [intellij-rust/intellij-rust#3011]
CLion version info:
```
CLion 2018.2.5
Build #CL-182.4892.24, built on October 16, 2018
```

RUST version info:
```
C:\Users\xiangjianjun>rustup show
Default host: x86_64-pc-windows-msvc

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu
stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-gnu (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

nightly-x86_64-pc-windows-gnu (default)
rustc 1.31.0-nightly (e7f5d4805 2018-10-18)
```

Error when debug
```
E:/Projects/testrs/target/debug/testrs.exe
Error creating process E:\Projects\testrs\target\debug\testrs.exe, (error 50).

Process finished with exit code 0
```

**Comment by xdray** [comment]
thank you. You solution is right after i try.

**Comment by ice1000** [comment]
I've just encountered the same problem and solved it in exactly the same way.
Maybe this should be added to some FAQ/trouble shooting channels?

**Comment by sampleref** [comment]
This helped.

**Comment by insinfo** [comment]
I'm having this problem, I'm running Clion 200.1, Windows 10,  mingw-w64 x86_64-8.1.0-win32-seh-rt_v6-rev0
```console
C:/MyRustProjects/guessing_game/target/debug/guessing_game.exe
com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$GDBCommandException: 
Error creating process C:\MyRustProjects\guessing_game\target\debug\guessing_game.exe, (error 50).

Process finished with exit code 0
```

![image](https://user-images.githubusercontent.com/12227024/141498365-4733943b-3ad0-45d6-9f33-756189d4266e.png)

![image](https://user-images.githubusercontent.com/12227024/141499094-bfd897d1-564d-4921-8b78-9af58e1d327e.png)

**Comment by insinfo** [comment]
@jonirrings
worked with Clion 2021.2.3 and mingw64 10.0 and gdb 10.2 and rustc 1.56.1 

![image](https://user-images.githubusercontent.com/12227024/142461850-f0f244cc-ff18-4664-8e96-8146f6cb0840.png)
