### ISSUE TITLE
(PSI): Poor PSI structure for types

### ISSUE THREAD

**Issue by jajakobyly** [intellij-rust/intellij-rust#303]
Grammar rule for types does not yield a wrapper PSI element for a `type`. This means that a sequence of PSI elements which denote particular type is not wrapped inside specialised PSI type:

![java_2016-03-27_22-07-52](https://cloud.githubusercontent.com/assets/3450050/14067618/83fb387c-f468-11e5-9c3c-315bb55583c2.png)

That guy from the screenshot should be wrapped inside something like `RustType`, or even better `RustSliceType` or `RustArrayType` which would inherit (as PSI element interface) from `RustType` ("abstract" element interface).

Because of this, it's almost impossible to write some stuff related to types specifically. Also, expand selection doesn't work well.

**Comment by matklad** [comment]
Oh no =( I've spend the whole day today to try to sort out our `rust.bnf`, and I wasn't terrible successful =(

Will take a look at this tomorrow.

**Comment by matklad** [comment]
Looks like the type PSI is in need of serious rework, so don't expect this issue to be fixed super fast.
