### ISSUE TITLE
Code analysis results are not displayed.

### ISSUE THREAD

**Issue by serbe** [intellij-rust/intellij-rust#3034]
## Environment

* **Intellij-Rust plugin version: 0.2.0.2110-182**
* **Rust toolchain version: 1.31.0-nightly (d586d5d2f 2018-10-29)**
* **IDE name and version: Intellij IDEA 2018.2.5 (Community Edition)**
* **Java: jdk8-openjdk 8.u192-1 amd64**
* **Operating system: Arch Linux 4.18.16-arch1-1-ARCH amd64**

## Problem description
When executing code analysis, blank lines are displayed instead of general analysis results.

## Steps to reproduce
Go to Menu -> Analyze -> Inspect code... -> press Ok
In "Inspection Results" window select: General -> Annotator -> File name
![idea](https://user-images.githubusercontent.com/837026/48348853-89b93f00-e693-11e8-9cce-4d797722016c.jpg)

**Comment by serbe** [comment]
Windows 10 x84 with Intellij IDEA 2018.2.5 (Community Edition)
![rust version](https://user-images.githubusercontent.com/837026/48396334-1a8f2980-e72b-11e8-85e8-64c41bfbeda6.jpg)

Install jbsdk8u152b1248.19_windows_x64 via JB SDK bintray downloader plugin.
But lines blanks again.
![idea](https://user-images.githubusercontent.com/837026/48396408-5924e400-e72b-11e8-992f-dc749757123c.jpg)

**Comment by Undin** [comment]
@serbe Hm :thinking:
I'd recommend to file an issue in platform [tracker](https://youtrack.jetbrains.com/issues/IDEA) because looks like it's platform issue

**Comment by amakeev** [comment]
@serbe if you decide to file a bug report to IntelliJ, please also attach the logs (Help | Compress Logs and Show in Explorer). Please set visibility to 'jetbrains-team' to avoid sharing any personal info.

**Comment by indiv0** [comment]
Any update on this?

I'm running into the same thing with IntelliJ IDEA 2019.1.2-1 on Arch Linux (4.20.7-arch1-1-ARCH) with intellij-rust (v0.2.98.2124-191). Tried switching JDK to `jdk-openjdk` (11.0.3.u4-1) and back to the bundled JDK (1.8.0_202-b49 boot bundled), no dice.

**Comment by eun-ice** [comment]
It's happening to me too

CLion 2019.2
Build #CL-192.5728.100, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 6
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: org.intellij.plugins.markdown, org.toml.lang, org.rust.lang

**Comment by lancelote** [comment]
Got the same problem. I am also not sure why these annotator values are displayed in inspection results in the first place. Those are not errors, right?

<img width="1474" alt="results" src="https://user-images.githubusercontent.com/2500320/73275474-34b20c00-41f8-11ea-863c-7724ef6674b0.png">

**Comment by frederikhors** [comment]
Same here and I don't know what is the warning/annotation/error:

![image](https://user-images.githubusercontent.com/41120635/76908574-5307c000-68a9-11ea-9238-11ce8d10c439.png)
