### ISSUE TITLE
Incorrect code completion when referencing generic struct from lib.rs in main.rs

### ISSUE THREAD

**Issue by lbrande** [intellij-rust/intellij-rust#3035]
Create a Rust binary project add a lib.rs file and import that lib.rs into main.rs with "extern crate" and "use". When trying to call a method of a struct defined in lib.rs with . syntax the relevant methods aren't suggested. It works if you use :: syntax though.

**Comment by lbrande** [comment]
It seems to be related to generic classes.

**Comment by Kobzol** [comment]
This seems to work in the current version of the plugin, with both edition `2015` and `2018`:
```rust
// lib.rs
pub struct S<T>(T);

impl<T> S<T> {
    pub fn test<R>(&self, t: T, r: R) {}
}

// main.rs
extern crate example_project;

use example_project::S;

fn main() {
    let s = S(1);
    s./*test is suggested*/;
}
```
