### ISSUE TITLE
autocomplete very very slowly.

### ISSUE THREAD

**Issue by pinguo-wangqinlong** [intellij-rust/intellij-rust#3067]
This feature of AutoComplete for AppCode is very difficult to use. about 5-7 seconds every time。I tried Android Studio and Xcode. Their automatic prompts are very easy and fast, but AppCode is not, so I gave up and continued to use Xcode. I want to say it again, very very very slowly。

**Comment by vlad20012** [comment]
Is it somehow related to Rust? :thinking:
If now, please, leave your feedback at [AppCode issue tracker](https://youtrack.jetbrains.com/issues/OC)

**Comment by pinguo-wangqinlong** [comment]
> Is it somehow related to Rust? 🤔
> If not, please, leave your feedback at [AppCode issue tracker](https://youtrack.jetbrains.com/issues/OC)

wow, sorry for that . I will remove it asap.

**Comment by pinguo-wangqinlong** [comment]
error for report.
