### ISSUE TITLE
Rust code editing causes long freezes for some edits

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#3078]
https://youtrack.jetbrains.com/issue/CPP-14753

**Comment by amakeev** [comment]
`ParamaterInfo` hind could be made async

**Comment by vlad20012** [comment]
@amakeev Yep, I found `OCAsyncParameterInfoHandler`. Thanks

**Comment by vlad20012** [comment]
@amakeev Looks like it isn't truly asynchronous. It can perform "updateParameterInfo" asynchronously, but not "showParameterInfo". I.e. first parameter info lookup is always sync. Did I understand it right?

**Comment by amakeev** [comment]
@vlad20012 please see the internal discussion in CPP-14753
