### ISSUE TITLE
Support multirust/rustup

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#308]
http://www.rustup.rs/

**Comment by matklad** [comment]
In particular, use `RUSTUP_TOOLCHAIN` to switch toolchains.

**Comment by matklad** [comment]
Rough sketch of a design:

Toolchain is determined by a `toolchain_home` path. if `toolchain_path/rustup` or `toolchain_path/multirust` exist, toolchain is *rustup toolchain*. For a rustup toolchain and additional string field `toolchain_version` is stored. The field should be displayed in the UI. It can be either null (the default toolchain is used) or some variant from `rustup toolchain list` / `multirust list-toolchains`. If it is not null than `RUSTUP_TOOLCHAIN` environmental variable must be set for every cargo command.

**Comment by matklad** [comment]
Persistence and UI parts are here: https://github.com/intellij-rust/intellij-rust/tree/master/src/main/kotlin/org/rust/cargo/project/settings

Cargo execution parts are here: https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/cargo/commands/Cargo.kt

**Comment by siler** [comment]
I've started poking around at this for fun despite the current state of the configuration folder RFC. Given that rustup will be the official Rust toolchain manager would it make sense to create an application component for configuring rustup and then change the project-level configurations to either select from currently installed toolchains or install a new one? 

I'm not sure that rustup is currently advanced enough for all the features we need (i.e., show me the directories in which everything resides in a convenient json/toml format) but for now we can infer based on the current standards.

**Comment by matklad** [comment]
Nice!

I think a good and isolated first step in this direction would be just to figure out if we are running rustup and show toolchain name in the settings (*without* the ability to choose it).

Application component would make sense if we persisted some information about toolchains, but it seems like we don't need to yet? I think that we can just query `rustup` about available toolchains when we need the list, and store a project toolchain in per-project settings. 

>i.e., show me the directories in which everything resides in a convenient json/toml format

And what directories to we need? It looks like that using rustup amounts to setting `RUSTUP_TOOLCHAIN` environmental variable when we call `~/.cargo/bin/rustup`.

**Comment by siler** [comment]
> I think a good and isolated first step in this direction would be just to figure out if we are running rustup and show toolchain name in the settings (without the ability to choose it).

Agreed, I think that's fair.

> Application component would make sense if we persisted some information about toolchains, but it seems like we don't need to yet?

I had two ideas about this, one was erroneous I think and the other is for the future. Agree with not needed yet. The latter was about configuring rustup automation (keeping stable/beta/nightly up to date) and project default toolchain settings (latest stable, locked to specific version, etc.). Perhaps I'll add issues for those after this.

> And what directories do we need?

I was thinking about the other items that rustup installs like the source and docs. We definitely want to be able to reference the source. It might be that this is another item where we rely on the current standards until the RFC drops.

**Comment by matklad** [comment]
> project default toolchain settings (latest stable, locked to specific version, etc.)

I think we should leverage rustup overrides mechanism for this, which we can also do in a stateless fashion. 

> I was thinking about the other items that rustup installs like the source and docs. 

Looks like it can't do this yet, or can it? Ideally, the stdlib location should be plugged into the `cargo metadata` command.

**Comment by matklad** [comment]
@siler one thing to keep in mind is that you should invoke `rustup` in the background thread, while the results are displayed in the main thread (Event Dispatch Thread), so there is some bit of asynchronous behavior. It is currently handled in an ad-hoc manner (see `RustProjectSettingsPanel#scheduleVersionUpdate`), but perhaps it makes sense to introduce some abstraction to deal with it.

**Comment by siler** [comment]
Noted, will take a peak.

Out of curiosity why does the RustProjectConfigurable have its own form which is essentially a duplicate of RustProjectSettingsPanel's form? It has an additional field for declaring sources, but this seems particularly odd since the experience you would see during the wizard isn't the one you would see later.

**Comment by siler** [comment]
Nevermind! Figured it out. Learning how to Swing.

**Comment by kumbayo** [comment]
Today I ran into a problem you might want to keep in mind when adding support for rustup.
The current rust/cargo version/feature detection might cause problems together with "rustup override".

RustToolchain.containsMetadataCommand() is used to check if the "cargo metadata" command is available. When doing so it runs cargo outside of the project path.
Later when "cargo metadata" is used it is run inside the project path.

Because of "rustup override" it is possible that both commands refer to different toolchain/cargo versions when run in different pahts.

The first call to RustToolchain.containsMetadataCommand() returns true.
But later runs of "cargo metadata" fail because the project specific cargo version is too old.

**Comment by matklad** [comment]
@kumbayo yet, this a possible failure mode. But I hope that everyone uses toolchain with cargo metadata nowadays?  Metadata less toolchains are pretty ancient in the Rust terms. 

Though, I think that we'll need some sort of feature detection for `workspaces` support soon.

**Comment by siler** [comment]
@kumbayo Thanks for the heads up!

I'm working on this a bit slowly, if anyone else wants to take a stab at it feel free.

**Comment by matklad** [comment]
We already make a use of rustup, and we can switch toolchains per run configuration, so I'll mark this as closed.

**Comment by lostmsu** [comment]
@matklad where's the UI for that for existing projects?
