### ISSUE TITLE
I have no code insight, highlighting and autocompletion for number `core`-methods

### ISSUE THREAD

**Issue by KizzyCode** [intellij-rust/intellij-rust#3087]
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2111-182
* **Rust toolchain version:** rustc 1.30.1 (1433507eb 2018-11-07)
* **IDE name and version:** CLion 2018.2.6
* **Operating system:** macOS Mojave 10.14.1 (18B75)

## Problem description
I have no code insight, highlighting and autocompletion for number `core`-methods like `checked_add` and similar.

**Comment by vlad20012** [comment]
Do you use rustup? If not, you should set up the sources of the standard library
