### ISSUE TITLE
cargo test --no-run won't run becasue --no-run is applied twice

### ISSUE THREAD

**Issue by mmlinford** [intellij-rust/intellij-rust#3100]
## Environment

* **Intellij-Rust plugin version:** v0.2.0.2111-183
* **Rust toolchain version:** rustc 1.30.1 (1433507eb 2018-11-07) / cargo 1.30.0 (a1a4ad372 2018-11-02)
* **IDE name and version:** IntelliJ IDEA 2018.3 (Ultimate Edition) Build #IU-183.4284.148, built on November 21, 2018
* **Operating system:** Windows 10

## Problem description
When I try to run a Cargo configuration that includes `test --no-run` I get an error like the one below:
```
C:/Users/Mike/.cargo/bin/cargo.exe test --no-run --no-run
error: The argument '--no-run' was provided more than once, but cannot be used multiple times

USAGE:
    cargo.exe test --message-format <FMT> --no-run

For more information try --help

Process finished with exit code 1
```
This didn't happen until recently when I upgraded the plugin (I don't remember which version I had before, sorry). My run configuration definitely only has `--no-run` once. Things work fine when I run Cargo from the command line.

## Steps to reproduce
- Create a new cargo run configuration
- Enter `test --no-run` as the command
- Run the configuration

**Project with the problem**: [mmlinford/intellij-rust-no-run-issue](https://github.com/mmlinford/intellij-rust-no-run-issue)

**Comment by mmlinford** [comment]
Wow, looks like you fixed this pretty quickly! When do you think the next release will be?

**Comment by vlad20012** [comment]
Expected on next week, but you can start to use it tomorrow with the nightly update channel of our plugin. You can find instructions [here](https://intellij-rust.github.io/install.html).
