### ISSUE TITLE
Document-based auto completion

### ISSUE THREAD

**Issue by DCjanus** [intellij-rust/intellij-rust#3102]
First of all, thanks for your work all along.

This issue is a supplement to the existing auto-completion mechanism.

It seems that we are parsing the source code directly, obviously, this is a very complicated job, and not work for the code generated by macro.

How about we parse the HTML files generated by `cargo doc`, with this, macro-generated code will be well supported.

I believe this is not a very perfect idea, but it looks so attractive.

**Comment by vlad20012** [comment]
We will support macros much finer when #3015 will be landed. Procedural macro support is planned too. So I think we don't need such hacks
