### ISSUE TITLE
Feature request: Auto create boilerplate for trait implementation.

### ISSUE THREAD

**Issue by crlf0710** [intellij-rust/intellij-rust#3104]
When trying to implement a trait with lots of methods for a struct, it would be really nice if the plugin can insert the signature of all the necessary associated constants, types, and methods with a auto-fix or something.

**Comment by Undin** [comment]
@crlf0710 It's already implemented
![2018-12-02 10 55 31](https://user-images.githubusercontent.com/2539310/49337218-e1a6ee00-f620-11e8-9199-95f8c3792344.gif)
Or do you mean something else?

**Comment by crlf0710** [comment]
Wow, what's exactly what i want. Somehow I've missed the existence of the feature! Sorry.

Thank you for pointing it out.
