### ISSUE TITLE
E0308 Mismatched type on the same type

### ISSUE THREAD

**Issue by elichai** [intellij-rust/intellij-rust#3107]
## Environment

* **Intellij-Rust plugin version:**  v0.2.0.2111-183
* **Rust toolchain version:** nightly-2018-10-01-x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2018.3 183.4284.156
* **Operating system:** Ubuntu 18.04

## Problem description
A lot of time i'm getting errors like these: 
```mismatched types [E0308] expected `Option<StatePatch>`, found `Option<StatePatch>` less... (Ctrl+1) 
Inspection info:The Rust type checker. ```
```mismatched types [E0308] expected `Option<[u8; 12]>`, found `Option<[u8; 12]>` less... (Ctrl+1) 
Inspection info:The Rust type checker```
```mismatched types [E0308] expected `Vec<u8>`, found `Vec<{integer}>` less... (Ctrl+1) 
Inspection info:The Rust type checker.```
```mismatched types [E0308] expected `String`, found `String` less... (Ctrl+1) 
Inspection info:The Rust type checker.```
## Steps to reproduce
I'm not sure what the recurring event that brings this problem, most of these errors involve an Option, but some Involve Vecs too (String Is a Vec) so this might be a problem with identifying generics.

**Comment by vlad20012** [comment]
Please, link the rust project where you get such errors. (I guess it is rust-lang/rust)
