### ISSUE TITLE
Add context aware run configuration

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#311]
`Ctrl+Shift+f10` should create a specific run configuration depending on context. 

If it is invoked in a file with `fn main()`, a `cargo run` configuration should be created with the correct `--bin`.

If it is invoked inside a test module or a test function, a `cargo test` configuration for the specific tests should be created. 

To implement this, we need to split our single `CargoCommandConfiguration` into `CargoBase` `CargoCommand`, `CargoRun` and `CargoTest` `Configuration`s. Then we should add context awareness to the configurations. As usual, the go plugin is a good example of this feature.

**Comment by alexpana** [comment]
I can implement this if no one is working on it.

**Comment by matklad** [comment]
Started implementing this in https://github.com/intellij-rust/intellij-rust/commit/283f8ac1b441147c1227ebc5992b7dc75fbbacb0.

My idea is simply to use single `CargoCommand` configuration and add a number of `ConfigurationProviders` for tests and binary files.

**Comment by matklad** [comment]
Implemented running a single test in https://github.com/intellij-rust/intellij-rust/commit/b35451a6bb69bab91bce06a130a4bf29504a7467
