### ISSUE TITLE
Add "Put parameters on separate lines" intention

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#3113]
The intention should transform
```rust
fn foo(parameter_1: i32, parameter_2: i32, parameter_3: i32) -> i32 {
```
into
```rust
fn foo(
    parameter_1: i32,
    parameter_2: i32,
    parameter_3: i32,
) -> i32 {
```

[Here](https://github.com/JetBrains/kotlin/blob/ba6da7c40a6cc502508faf6e04fa105b96bc7777/idea/src/org/jetbrains/kotlin/idea/intentions/ChopParameterListIntention.kt) is the implementation of similar intention in Kotlin.

**Comment by vlad20012** [comment]
I think we should check how rustfmt format this case

**Comment by ortem** [comment]
@vlad20012 I just copied the example from rustfmt output 👌
