### ISSUE TITLE
Syntax highlighting for types

### ISSUE THREAD

**Issue by netvl** [intellij-rust/intellij-rust#312]
Currently the plugin highlights all types (except type parameters) as identifiers. Ideally all types should be highlighted as types, so they would be more visible.

I understand that the partial reason to treat them as just identifiers is that there is no real identifier resolution available, but:
* it should be possible to highlight at least primitive types
* it may be possible to inspect whether an identifier is in a type position (after `:` in function signatures, for example) and highlight it accordingly.

What do you think?

**Comment by matklad** [comment]
>I understand that the partial reason to treat them as just identifiers is that there is no real identifier resolution available

Well, we do have identifier resolution available :) It is not complete yet, but it is constantly improving. We don't use it for highlighting at the moment, but this is definitely on the roadmap.

**Comment by netvl** [comment]
@matklad I meant that, as far as I can see, it is still impossible to navigate, say, from type use site to its definition :) But of course, this is all just speculations on my part, I may be totally wrong :)

**Comment by matklad** [comment]
Basic navigation within one file already works:

![test](https://cloud.githubusercontent.com/assets/1711539/14172981/e10bd8c2-f743-11e5-8c48-33f685efb16f.gif)

Navigation between files of a single project should work if you use beta version of Cargo and import the project properly.

Navigation to the standard library sources kinda works, but it is a bit complex to setup right now, I'm improving this at the moment. 

There are surely some bugs with resolve! If **Goto declaration** does not work for your particular use case than you can file an issue/ask about it on gitter.

**Comment by netvl** [comment]
Are these changes published already? I'm asking because I've just installed the plugin from the nightly plugins repository and keyboard shortcuts for navigation do not work, including types in the single file.

But anyway, this is not what this issue is about :) I'll play with it more later and file a new issue if there are indeed problems with it.

**Comment by matklad** [comment]
Yes, Goto definition was implemented several months ago.

**Comment by matklad** [comment]
@netvl I believe this is fixed by @mfarrugi  in #503. The default colors for enum and struct are the same as for any identifier though, so you need to change them to see it:

![idents](https://cloud.githubusercontent.com/assets/1711539/16567353/7be02d6c-4226-11e6-8102-9525b1fcc92f.png)

Perhaps we should have different default colors for structs and enums?

**Comment by mfarrugi** [comment]
The default is set to `Class`, so that'd be a PR for jetbrains. 
It'll play nicely with other color schemes, though.
