### ISSUE TITLE
False positive "Unresolved reference" if module name is equal to crate name

### ISSUE THREAD

**Issue by vlad9486** [intellij-rust/intellij-rust#3120]
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2111-182
* **Rust toolchain version:** 1.32.0
* **IDE name and version:** IDEA 2018.2.6 (community version)
* **Operating system:** macOS Mojave 10.14.1

## Problem description

Using the same name for module and dependent crate cause false Unresolved reference error.

## Steps to reproduce

    mod serde {
        pub struct Foo;

        use serde::Serialize;

        impl Serialize for Foo { }
    }

`Serialize` is not resolved here although `use serde::Serialize;` should correspond to crate not to module `use self::serde::Serialize;`.

**Comment by Kobzol** [comment]
This works in the current version of the plugin if edition is `2018` (otherwise it doesn't compile even with `rustc`).
