### ISSUE TITLE
Rename corresponding item in trait or impls

### ISSUE THREAD

**Issue by mchernyavsky** [intellij-rust/intellij-rust#3128]
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2492-183-nightly
* **Rust toolchain version:** 1.32.0-nightly
* **IDE name and version:** IC-183.4284.148
* **Operating system:** macOS Mojave 10.14.1

## Problem description

When you rename an item in a trait implementation, the corresponding item from the trait definition should be renamed also. On the other hand, when you rename an item in a trait definition, the corresponding items from the all trait implementations should be renamed also.

## Steps to reproduce

* Copy-paste the following code and try to rename method `foo`:

```rust
struct S;

trait T {
    fn foo();
}

impl T for S {
    fn foo() {}
}
```

**Comment by vlad20012** [comment]
#2163 may be related
