### ISSUE TITLE
False-positive "Call to unsafe function requires unsafe block"

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#3129]
![image](https://user-images.githubusercontent.com/3221931/49679753-c7e12d00-fa9e-11e8-8faf-c264d556beca.png)
Currently we think that functions in any `extern` block are unsafe. It isn't truth. For example, functions inside `extern "rust-intrinsic" {}` block are safe. Also function inside extern block followed with `#[wasm-bindgen]` proc macro are safe too (but it is rather procedural macro magic).

**Comment by jsmnbom** [comment]
Is there any way to turn off this inspection in the meantime?

**Comment by ortem** [comment]
@jsmnbom try [this](https://www.jetbrains.com/help/idea/disabling-and-enabling-inspections.html)

**Comment by vlad20012** [comment]
@ortem it's annotator, not an inspection. It isn't possible to disable it

**Comment by vlad20012** [comment]
I found that most of functions inside `extern "rust-intrinsic"` blocks are unsafe, but there are some that are safe =/ I guess it is hardcoded somewhere in the compiler

**Comment by MSxDOS** [comment]
Any way to disable this annotation? Getting swamped with false positives when actively using `likely`\ `unlikely` intrinsics.

**Comment by DzenanJupic** [comment]
`core::intrinsics::unlikely` is another example:

![image](https://user-images.githubusercontent.com/56133904/126049812-d5298ab5-f3ea-4b8a-b3c8-2c63a183a543.png)

**Comment by Kxuan** [comment]
> I found that most of functions inside `extern "rust-intrinsic"` blocks are unsafe, but there are some that are safe =/ I guess it is hardcoded somewhere in the compiler

This is the hardcoeded list. These names should be considered as "safe".

Link: [pub fn intrinsic_operation_unsafety(intrinsic: Symbol) -> hir::Unsafety {](https://github.com/rust-lang/rust/blob/fc323035ac49b8d834fc2a0f580af8fd45e90b30/compiler/rustc_typeck/src/check/intrinsic.rs#L66)

**Comment by insinfo** [comment]
It may be off topic, but does anyone know how to disable the hightlight of unsafe function calls in RustRover?

![image](https://github.com/intellij-rust/intellij-rust/assets/12227024/60c87481-2521-4b03-9881-4d329bd66266)
