### ISSUE TITLE
No autocomplete for `extern C` type definitions

### ISSUE THREAD

**Issue by chinedufn** [intellij-rust/intellij-rust#3131]
## Environment

* **Intellij-Rust plugin version:**

`Version: 0.2.0.2492-182-nightly` (87)

* **Rust toolchain version:**

`rustc 1.32.0-nightly (14997d56a 2018-12-05)`

* **IDE name and version:**

`PhpStorm 2018.2.4`

* **Operating system:**

`macOS Mojave 10.14`

## Problem description

There is no auto complete for the `web-sys` crate.

## Steps to reproduce

1. Add `web-sys` as a dependency

```
[dependencies.web-sys]
version = "=0.3.6"
features = [
  'Document',
  'Element',
  'HtmlCanvasElement',
  'HtmlElement',
  'Node',
  'WebGlBuffer',
  'WebGlProgram',
  'WebGlRenderingContext',
  'WebGlShader',
  'WebGlVertexArrayObject',
  'WebGlUniformLocation',
  'Window',
  'console',
]
```

2. Type `web_sys::` and the only autocomplete suggestion will be `web_sys::window()`

---

`web_sys` uses a ton of code generation and `extern` blocks, not sure if that's related here.

**Comment by chinedufn** [comment]
![image](https://user-images.githubusercontent.com/2099811/50042898-9afdbe80-0038-11e9-9608-b768b11c3da9.png)

It knows which functions exist (screenshot above) - if that helps with where the issue might be

**Comment by chinedufn** [comment]
Not sure how hard this is to fix but I'd be happy to take a stab with a little guidance!

Incredibly useful for anyone doing WebAssembly work.

Would it be possible to point me in the right direction and I can try my best to take it from there?

**Comment by Undin** [comment]
@chinedufn It seems that all bindings are generated from some intermediate representation and included into `web-sys` via `include!(env!("BINDINGS"));`
Unfortunately, the plugin doesn't take into account any sources included in such way at this moment
See #1908

**Comment by chinedufn** [comment]
Gotcha - thank you!!
