### ISSUE TITLE
New install performs little to no analysis

### ISSUE THREAD

**Issue by cbailey555** [intellij-rust/intellij-rust#3132]
## Environment

* **Intellij-Rust plugin version:**
v0.2.0.2111-183
* **Rust toolchain version:**
rustup 1.16.0
stable-x86_64-unknown-linux-gnu (default)
rustc 1.31.0 (abe02cefd 2018-12-04)

* **IDE name and version:**
CLion 2018.3.1

* **Operating system:**
Arch Linux

## Problem description
Maybe I'm mistaken about the level of analysis that's supposed to be done by the plugin, but the only errors its able to find are things like unclosed delimiters and missing semi-colons. Mistyped or non-existent imports, typos referencing non-existent struct fields, unsatisfied trait bounds, attempting to use things that aren't in scope, all of these things get a grey eyeball followed by a green check mark. Essentially everything that gets caught by the compiler is given a thumbs up by clion/intellij rust.

## Steps to reproduce
This code passes analysis

```
fn nothing_unusual(x : u29999lslkkdii3221113) -> Option<Giraffe> {
    
    use this_module_doesnt_exist::giraffes;

    let nonexistent_giraffe = a_giraffe::あいうえお();
    let giraffe_name = a_giraffe.give_name("Dave");

    Some(giraffe_name)
}
```

**Comment by vlad20012** [comment]
> Maybe I'm mistaken about the level of analysis that's supposed to be done by the plugin

Yep, you are mistaken =)
Our error reporting is very poor for now. But you can enable cargo check to analyze code and see lints from the compiler.
![image](https://user-images.githubusercontent.com/3221931/49691958-00e0d680-fb5f-11e8-97b5-1a8b085d0e6d.png)
