### ISSUE TITLE
Incorrect comments highlighting in documentation code blocks

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#3142]
## Environment

* **Intellij-Rust plugin version:** v0.2.0.2495-183-nightly
* **Rust toolchain version:** 1.32.0-nightly (14997d56a 2018-12-05)
* **IDE name and version:** IntelliJ IDEA 2018.3.1 (Ultimate Edition)
* **Operating system:** macOS 10.13.6

## Problem description

All lines of multiline eol comments (except the first one) is highlighted in wrong way in quick documentation
<img width="526" alt="screen shot 2018-12-12 at 11 30 33" src="https://user-images.githubusercontent.com/2539310/49856999-69031700-fe02-11e8-8b04-a6a8dd45760d.png">

## Steps to reproduce

Open quick documentation, for example, for `HashMap`

**Comment by Undin** [comment]
Found out that it's a platform bug
I've created the corresponding [issue](https://youtrack.jetbrains.com/issue/IDEA-205588) in IDEA tracker

**Comment by Kobzol** [comment]
It seems to me that this has been fixed in 2020.1 (or sooner).

**Comment by Undin** [comment]
@Kobzol indeed! It fixed at least since 2019.2.4
Thanks!
