### ISSUE TITLE
Adding, removing and re-adding a rust module fails

### ISSUE THREAD

**Issue by deaddowney** [intellij-rust/intellij-rust#315]
I added a Rust module, deleted it, and then tried to add it (from the cargo file).  I get "Cannot Save Settings.  The project is already registered".

**Comment by matklad** [comment]
Thanks for the report!

Looks like an upstream issue: https://youtrack.jetbrains.com/issue/IDEA-154075

The easy workaround is just closing and reopening the project structure dialog. 

I am curious about your use case though. Why are you importing a single Rust module, as opposed to importing the whole project? Are you using Rust in a primarily non-Rust project?

**Comment by deaddowney** [comment]
Yes, I am porting a C++ project over to Rust and need to have the C++ module open with the Rust Module.

**Comment by naory** [comment]
I am trying to re-import a Gradle module and I'm getting the same issue (https://youtrack.jetbrains.com/issue/IDEA-154075) 
I'm using the latest ultimate (2016.2.4) and the suggested workaround (closing and reopening the project structure dialog) does not work.

this forces me to re-create the entire project from scratch
