### ISSUE TITLE
Support docker

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#3152]
Currently, we assume that all sources of stdlib/extern crates are located in user local machine.
So we can't provide any intellisence when rust related things are located in a docker container.

It would be great to support such case of work too.
Looks like some other languages already have such feature (for example, php), so we can take a look at the existing implementations.

Docker container with rust can be found here https://github.com/rust-lang/docker-rust

**Comment by LeFredd** [comment]
Hi, any news?

**Comment by Undin** [comment]
@LeFredd Sorry, but there aren't any news about docker
This issue is about what we need to do in general but we can't provide any estimation when it will be implemented. At this moment, it's not in our short term plan

**Comment by jendakol** [comment]
Hello, any chance you'll get to this? It would be a great improvement e.g. in development for experimental targets like XTensa ESP32...

**Comment by PiDelport** [comment]
Related (or duplicate): https://github.com/intellij-rust/intellij-rust/issues/1926

**Comment by Undin** [comment]
@mchernyavsky I reopen this since it's more about docker-based toolchain than about compilation/running in docker container

**Comment by richard-delorenzi** [comment]
It would be nice to at least fix the error message. I have been stuck for 2 days, with this. It told me that it could not find `cargo`. However I have been told the problem is that it is looking for other components also.

If IDEA only need to read library source, then maybe we can map this read-only into the host.

**Comment by Teebor-Choka** [comment]
This is a deal-breaker for modern container based development in Rust.

What are the plans for this feature? Is it going to be incorporated into the IDEs? Given how CLion is able to properly use toolchains within a development container for C++ this should not be more complicated or different.

**Comment by Daniel599** [comment]
any update regarding this feature? we use Clion with the new C++ docker toolchain, and it will be useful if it could include Rust in it, since we also develop in Rust
