### ISSUE TITLE
The Rust plugin doesn't work for newest CLion 2018.3.2

### ISSUE THREAD

**Issue by NanXiao** [intellij-rust/intellij-rust#3160]
The Rust plugin doesn't work.

## Environment

Intellij-Rust plugin version: v0.2.0.2112-183
Rust toolchain version: 
```
$ rustup.exe update
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: checking for self-updates

  stable-x86_64-pc-windows-msvc unchanged - rustc 1.31.0 (abe02cefd 2018-12-04)
```

IDE name and version: The newest CLion 2018.3.2

Operating system: Windows 7

## Problem description
The plugin doesn't work. E.g., no auto-complete function. Please check the following snap:  
![image](https://raw.githubusercontent.com/NanXiao/images/master/rust-plugin.JPG)

Thanks in advance!

**Comment by vlad20012** [comment]
Looks like the power-save mode is enabled. So nothing work, as expected

**Comment by NanXiao** [comment]
@vlad20012 Yes, you are correct! Sorry for not knowing this. I will close it, thanks very much again!
