### ISSUE TITLE
Code completion doesn't work for some items in libc

### ISSUE THREAD

**Issue by MikailBag** [intellij-rust/intellij-rust#3165]
## Environment

* **Intellij-Rust plugin version:** v0.2.0.2112-183
* **Rust toolchain version:** rustc 1.33.0-nightly (d99a320cb 2018-12-18)
* **IDE name and version:** CLion 2018.3.1
* **Operating system:** GNU/Linux Ubuntu Cosmic x64

## Problem description
This bug refers to many items in libc.
For example
- struct msghdr
- fn WIFEXITED

![screenshot from 2018-12-20 17-35-45 - edited](https://user-images.githubusercontent.com/11889433/50291000-6184e300-047e-11e9-9fa6-63155ecc631f.png)

Also, I should mention that IDE doesn't mark usages of these types as errors:
![image](https://user-images.githubusercontent.com/11889433/50291129-b9bbe500-047e-11e9-812e-f36f33454617.png)

**Comment by Kobzol** [comment]
`libc::msghdr` is auto-completed and resolved in the latest version of the plugin.
