### ISSUE TITLE
Wrong brace indent on enter typing

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#3170]
## Problem description
Editor place wrong indent if previous line starts with not indented comment

## Steps to reproduce
1.
```rust
fn main() {
//qwe
    struct S {/*caret*/}
}
```
2. Then type <enter>
3. Result:
```rust
fn main() {
//qwe
    struct S {
    
}
}
```
But I expect:
```rust
fn main() {
//qwe
    struct S {
    
    }
}
```

**Comment by Kobzol** [comment]
Works in the latest version of the plugin.
