### ISSUE TITLE
Change return type intention

### ISSUE THREAD

**Issue by Keshi** [intellij-rust/intellij-rust#3173]
It seems that rust is designed to require specifying the return type in a function signature.  However, manually typing out full types for the function return in the signature is not really the most ergonomic thing to do while iterating on a function.    **It would be really great to be able to visualize the current return type of a function as written(or some warning in the case of disagreement between control flow branches) as one of those in-line visualization text thingies, as well as offer to just append the inferred type (same as what you'd get using View->Expression Type) to the function signature as a refactoring/fix option if the returning expressions in its body have consistent types with each other**, so that you can: name the function, write the logic, press some button and have the return type added/fixed for you based on your function logic.

### Example
Before:
```Rust
fn foo() {
    42/*caret*/
}
```
After:
```Rust
fn foo() -> i32 {
    42
}
```

**Comment by saskenuba** [comment]
I always lose some time trying to match the expected output of the function. This would be awesome!

**Comment by Kobzol** [comment]
@mchernyavsky I think that this can be closed, it was fixed by https://github.com/intellij-rust/intellij-rust/pull/5087.
