### ISSUE TITLE
Add "convert to block/typle struct" intention

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#3180]
Add 2 intentions to convert  structs between block/tuple fields:

```rust
struct Foo(i32, i32);
```
<=>
```rust
struct Foo {
    _0: i32,
    _1: i32,
}
```

**Comment by rrevenantt** [comment]
I would like to work on this issue, and I am not sure if these intentions should also convert all usages accordingly.

**Comment by vlad20012** [comment]
I still think that alt+enter intentions are needed, b/c it's hard to find refactorings if you don't know about them
