### ISSUE TITLE
nightly incorrectly prompts "async is reserved keyword in Edition 2018" error at await!(async { /* ... */ });

### ISSUE THREAD

**Issue by imkow** [intellij-rust/intellij-rust#3189]
it still prompts "async is reserved keyword in Edition 2018" error at await!(async { /* ... */ });

**Comment by Undin** [comment]
Check it with the latest stable/nightly build, please

**Comment by imkow** [comment]
@Undin of course latest

**Comment by vlad20012** [comment]
@imkow we meant, please, re-check it, b/c we __just__ released a new nightly about an hour ago

**Comment by imkow** [comment]
@Undin @vlad20012 now looks better, thanks for your efforts. Surprising that you made this extra update to all release channels. Thank you all, guys. Happy New Year from Shanghai, China!
