### ISSUE TITLE
extern crate can not be autocompleted in use crate::xxx

### ISSUE THREAD

**Issue by gfreezy** [intellij-rust/intellij-rust#3207]
## Environment

* **Intellij-Rust plugin version:0.2.0.2113-183**
* **Rust toolchain version:1.31.1**
* **IDE name and version:Intellij IDEA 2018.3.2**
* **Operating system:macos 10.14.1**

## Problem description
use not resolved.

## Steps to reproduce
```rust
extern crate actix;

use crate::actix;  // <- actix is not resolved

fn main() {
    println!("Hello, world!");
}
```

**Comment by rjain11** [comment]
+1

**Comment by Kobzol** [comment]
Works in the latest version of the plugin.
