### ISSUE TITLE
type alias with external crate in absolute path doesn't resolve

### ISSUE THREAD

**Issue by gfreezy** [intellij-rust/intellij-rust#3208]
## Environment

* **Intellij-Rust plugin version:0.2.0.2113-183**
* **Rust toolchain version:1.31.1**
* **IDE name and version:Intellij IDEA 2018.3.2**
* **Operating system:macos 10.14.1**

## Problem description
use not resolved.

## Steps to reproduce
1. add actix to cargo.toml
2. enable 2018 edition
3. add following lines to main.rs

```rust
type Ar2 = ::actix::Arbiter;

fn main() {
    println!("Hello, world!");
}

```

rust compiles. However, Intellij-rust cannot resolve actix

**Comment by Kobzol** [comment]
Works in the latest version of the plugin.
