### ISSUE TITLE
Cargo not found on Windows

### ISSUE THREAD

**Issue by gentoo90** [intellij-rust/intellij-rust#322]
When running `Build` -> `Make Project`, Idea can't find `cargo` if it's not in system `%PATH%` even though SDK is set correctly and `Run` uses `cargo` from SDK.

![cargonotfound](https://cloud.githubusercontent.com/assets/1297574/14348243/d62e9392-fcc3-11e5-9994-db5782567763.png)

Steps to reproduce:

1. Install [Rust MSI](https://www.rust-lang.org/downloads.html) with `Add to PATH` feature **disabled**
2. Import a project into Idea and set Rust SDK
3. `Build` -> `Make Project` - fails
4. `Run...` -> `Add New Configuration` -> `cargo build` - works

**Comment by matklad** [comment]
Yep, it is a know issue: https://github.com/intellij-rust/intellij-rust/issues/224.

The workaround is either to add `cargo` to path, or to remove `make` from before run in the run configuration. 

We will fix this soon, I'm working on a related issue right now!
