### ISSUE TITLE
Unresolved Reference 'abs'

### ISSUE THREAD

**Issue by huhlig** [intellij-rust/intellij-rust#3238]
## Environment

* **Intellij-Rust plugin version:** v0.2.0.2113-183
* **Rust toolchain version:** rustc 1.31.1
* **IDE name and version:** CLion 2018.3.2
* **Operating system:** Windows 10

## Problem description
Unresolved reference to numeric method 'abs()'. Seems to occur when types are defined elsewhere or in parenthesis but Tracking down a minimal case has been difficult. 

## Steps to reproduce

Open Project and Canvas file. 
https://github.com/huhlig/softrender-rs/blob/master/src/image/canvas.rs#L38

**Comment by twistedfall** [comment]
The minimal case is here:

```rust
fn main() {
	1i32.abs();
}
```

![afbeelding](https://user-images.githubusercontent.com/406037/55167025-7d301180-5170-11e9-8078-d1b7aede1462.png)
