### ISSUE TITLE
Auto complete doesn't show super methods

### ISSUE THREAD

**Issue by NightBalance** [intellij-rust/intellij-rust#3259]
## Environment

* **Intellij-Rust plugin version:** 

[![QQ20190117-2.png](https://i.loli.net/2019/01/17/5c4048cd94f33.png)](https://i.loli.net/2019/01/17/5c4048cd94f33.png)

* **Rust toolchain version:**

[![QQ20190117-4.png](https://i.loli.net/2019/01/17/5c40494b645a3.png)](https://i.loli.net/2019/01/17/5c40494b645a3.png)

* **IDE name and version:**

[![QQ20190117-1.png](https://i.loli.net/2019/01/17/5c40487b7e437.png)](https://i.loli.net/2019/01/17/5c40487b7e437.png)

* **Operating system:**

[![QQ20190117-3.png](https://i.loli.net/2019/01/17/5c4049046cab8.png)](https://i.loli.net/2019/01/17/5c4049046cab8.png)

## Problem description

The auto complete not show the insert method.

[![QQ20190117-0.png](https://i.loli.net/2019/01/17/5c4049875dac3.png)](https://i.loli.net/2019/01/17/5c4049875dac3.png)

**Comment by vlad20012** [comment]
It's related to the type contained in HashSet. Works for `isize`, but not for `(isize, isize)`. It because impl Hash for (...) made by a macro. So it is macro-related issue
