### ISSUE TITLE
Provide AddMutableFix for assignments with immutable references

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#3277]
`RsAssignToImmutableInspection` [provides](https://github.com/intellij-rust/intellij-rust/pull/3200)  `AddMutableFix` for values, but not for references. It would be useful to provide such fix for function parameters with reference type, e.g.:
```Rust
struct S { a: i32 }
fn foo(s: &S) {
    s.a = 42; // Cannot assign to field of immutable binding [E0594]
}
```
becomes
```Rust
struct S { a: i32 }
fn foo(s: &mut S) {
    s.a = 42; // OK
}
```

**Comment by snpefk** [comment]
Hello. 

I would like to implement this feature, but I can't figure out the purpose of `RsPatBinding`.

**Comment by ortem** [comment]
Hi @snpefk,

`RsPatBinding` is a part of `PatIdent` (which relates to [IdentifierPattern](https://doc.rust-lang.org/reference/patterns.html#identifier-patterns) in Rust Reference). It consists of an optional binding mode (`mut`, `ref` or `ref mut`) and a identifier.

You can use `PsiViewer` to discover Rust grammar.
<img width="769" alt="screenshot 2019-01-28 at 17 46 48" src="https://user-images.githubusercontent.com/4854600/51843790-cd335900-2324-11e9-9658-c0cf3679daca.png">

**Comment by snpefk** [comment]
Shouldn't it be closed now?

**Comment by Undin** [comment]
@snpefk Yep!
BTW if you add something like `Closes #issue-number` in PR message, Github will automatically close the issue when PR is merged
See [here](https://help.github.com/en/articles/closing-issues-using-keywords) for details
