### ISSUE TITLE
Move analysis doesn't work

### ISSUE THREAD

**Issue by mchernyavsky** [intellij-rust/intellij-rust#3288]
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2532-183-nightly
* **Rust toolchain version:** 1.33.0-nightly
* **IDE name and version:** CLion 2018.3.3
* **Operating system:** macOS Mojave 10.14.2

## Problem description

Consider the following code:

```rust
struct S;
fn main() {
    let x = Some(S);
    let y = x;
    let z = x; // use of moved value: `x`
}
```

Rustc will report the error at the last statement, but IntelliJ Rust will not.

**Comment by ortem** [comment]
The problem is our type inference process deriving incorrectly: it gives `Copy` impl for `Option<T>` for any `T`, but not for `T: Copy`.
