### ISSUE TITLE
Completion of associated type methods

### ISSUE THREAD

**Issue by fan-tom** [intellij-rust/intellij-rust#3290]
## Environment

* **Intellij-Rust plugin version:** v0.2.0.2114-183
* **Rust toolchain version:** 
rustup 1.16.0 (beab5ac2b 2018-12-06), 
rustc 1.33.0-nightly (adbfec229 2018-12-17), 
cargo 1.33.0-nightly (2cf1f5dda 2018-12-11)
* **IDE name and version:** 
PyCharm 2018.3.3 (Community Edition)
Build #PC-183.5153.39, built on January 9, 2019
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* **Operating system:**
macOS Sierra 10.12.6
## Problem description
I have no completion in following piece of code
![image](https://user-images.githubusercontent.com/14140464/51736473-0319d880-20ac-11e9-9df1-60a122918c26.png)
![image](https://user-images.githubusercontent.com/14140464/51736518-1b89f300-20ac-11e9-9865-8adc06a80d92.png)

I expected I can see all the methods trait Iterator exposes, but it seems that plugin cannot infer type
of method into_iter, as it refers to Self::IntoIter associated type of IntoIterator trait, which is unknown at that point.

**Comment by Kobzol** [comment]
Iterator methods are correctly auto-completed in the latest version of the plugin.
