### ISSUE TITLE
Wrong type inferred for 'Gc<xx>.clone()' only using type alias

### ISSUE THREAD

**Issue by songzhi** [intellij-rust/intellij-rust#3296]
## Environment

* **Intellij-Rust plugin version: v0.2.0.2114-183**
* **Rust toolchain version: nightly-x86_64-pc-windows-msvc 1.33.0-nightly**
* **IDE name and version: CLion 2018.3**
* **Operating system: Win10-64bit**
* crate version `gc = "0.3.2"`

## Problem description
I used the crate 'gc' and type alias.Then the `clone()` method's return type is incorrect.
But the result of `cargo check` is correct.It can build successfully.
![default](https://user-images.githubusercontent.com/18499849/51785183-de4a6180-218e-11e9-9e2b-03ae82495a93.png)

## Steps to reproduce

```rust
use gc::{Gc, GcCell};

type Val = Gc<i32>;

fn get_value() -> Val {
    unimplemented!()
}

fn set_value(val: Val) {
    unimplemented!()
}

fn main() {
    let val = get_value();
    set_value(val.clone());
    let v = val.clone();
}
```

**Comment by Kobzol** [comment]
Works in the latest version of the plugin.
