### ISSUE TITLE
Build button on toolbar duplicates, when C++ + CLion

### ISSUE THREAD

**Issue by MikailBag** [intellij-rust/intellij-rust#3309]
## Environment

* **Intellij-Rust plugin version:** (last at the moment of creating issue)
* **Rust toolchain version:** nightly
* **IDE name and version:** CLion latest
* **Operating system:** Ubuntu cosmic x64

## Problem description
If the same project contains Rust and C++/CMake code, there will be two build buttons on the toolbar.
First will compile only Rust-related targets, and second - only CMake-related targets/

**Comment by Undin** [comment]
Fixed in #3308

**Comment by MikailBag** [comment]
But how should I fix this problem in existing project? Standard actions like reopen CLion or reload cmake/cargo project don't seem to help

**Comment by Undin** [comment]
@MikailBag For example, update plugin
