### ISSUE TITLE
Add keyboard shortcuts for mac

### ISSUE THREAD

**Issue by kindlychung** [intellij-rust/intellij-rust#331]
None of the shortcuts work on a mac, please update the docs. Thanks!

**Comment by alexeykudinkin** [comment]
Hey, @kindlychung! Non-working shortcuts may be related with language support not being complete to the moment.

What kind of shortcuts do not work for you?

**Comment by kindlychung** [comment]
None of the shortcuts works, for example, as shown in the quickstart guide.

**Comment by matklad** [comment]
The problem with specifying shortcuts for all keymaps is that there a lot of different keymaps! There are two different only for mac! But yes, the docs could say that the shortcuts are for the default Windows/Linux keymap and provide a way to learn shortcuts for other layouts. 

You can see `Help > Keymap reference` for the list of most useful shortcuts. Also, if you invoke "find action" and type a name of an action (they are **bold** in the quick start), you'll see a shortcut for it.

As a note, the plugin currently uses only actions already available in IntelliJ IDEA, and does not have any custom shortcuts. 

I'll update the docs, thank you for the feedback.

**Comment by kindlychung** [comment]
Cool, thanks!
