### ISSUE TITLE
Cannot launch Project Structure dialog after updating Rust

### ISSUE THREAD

**Issue by kryptan** [intellij-rust/intellij-rust#332]
After updating Rust I get this exception when I press Ctrl+Alt+Shift+S:

    12:50:13 ExecutionException: Cannot start process, the working directory 'C:\Program Files\Rust stable GNU 1.7' does not exist

Rust is now in `...\Rust stable GNU 1.8` but to change path I need to open this dialog which I cannot do.

**Comment by matklad** [comment]
That's bad :( Luckily, it will be fixed by #323 . As a workaround, you can remove Rust sdk entry at the `~/.IdeaIC2016.1/config/options/jdk.table.xml` configuration file.
