### ISSUE TITLE
Non-imported enums are not suggested in autocompletion list

### ISSUE THREAD

**Issue by Riateche** [intellij-rust/intellij-rust#3329]
Follow-up for #2721. Importing structs works like a charm now, but importing enums is not possible this way. For example:
```rust
mod a {
    pub struct MyAbc;
    pub enum MyDef {
        MyDefVar1,
        MyDefVar2,
    }
}
mod c {
    use crate::a::MyDef::MyDefVar1;

    fn x() {
        [cursor here]

    }
}
```
At the cursor position, the plugin suggests `MyDefVar1` and `MyDefVar2`, so I can import the variant by choosing the suggested item. But most often I want to import the enum itself, and `MyDef` is absent in the suggestion list. `MyAbc` is suggested and can be imported properly.

**Comment by Undin** [comment]
@Riateche Thanks for the reports 👍 
They are very useful!
