### ISSUE TITLE
Autocompletion/Suggestion does not work in latest IDEA Community

### ISSUE THREAD

**Issue by Kein** [intellij-rust/intellij-rust#3331]
Using
Using IntelliJ IDEA 2018.3.4 Community
and
IntelliJ-RUST 0.2.91.2115-183 (30 jan stable)

I have some basic global suggestions but autocompletion and context-aware suggestion wont work:
![image](https://user-images.githubusercontent.com/623756/52174619-97b8c080-27a7-11e9-95dc-caac2bdf5579.png)

**Comment by vlad20012** [comment]
Is it worked on some previous versions?

**Comment by Kein** [comment]
Havent tried on any other versions.

**Comment by vlad20012** [comment]
Do you use rustup? If not, you should manually provide the std library sources. But I highly recommend to use rustup. 
If you use rustup already, try to restart the IDE. If it isn't help, try to manually run `rustup component add rust-src`

**Comment by Kein** [comment]
> f it isn't help, try to manually run rustup component add rust-src

You are right, for some reason it failed to do so automatically. Manual installation fixed it, thanks.

**Comment by laptou** [comment]
I am experiencing #2877, which is similar to this issue. When I control+hover over a reference to `std` it says "multiple implementations", but they all point to the same implementation. Autocomplete for `std` modules does not work.

OS: Ubuntu 18.10
IDE: CLion 2018.3.4
IntelliJ-Rust: v0.2.91.2115-183
Rust: rustc 1.32.0 (9fda7c223 2019-01-16)

**Comment by laptou** [comment]
It seems that breakage only occurs when `std` is imported at the same time as one of its submodules:

![imagen](https://user-images.githubusercontent.com/14832331/52184844-cace7480-27e6-11e9-84ab-67d1c6864003.png)
This is fine.

![imagen](https://user-images.githubusercontent.com/14832331/52184860-eafe3380-27e6-11e9-81c9-58d7caad7add.png)
![imagen](https://user-images.githubusercontent.com/14832331/52184861-f18cab00-27e6-11e9-8802-a8af5282888b.png)
This is not.

**Comment by neonaot** [comment]
Could not reproduce the problem with `Multiple implementations`. Probably the issue was fixed at some point. Also, it is not relevant to the original problem about the lack of autocompletion. 
If you still facing a similar problem with `std`, please open an issue using `Create New Issue` action right from your IDE (which automatically provides the information about your environment) and attach a small reproducible example (including `Cargo.toml`)
