### ISSUE TITLE
Debugger displays incorrect values for strings

### ISSUE THREAD

**Issue by denbkh** [intellij-rust/intellij-rust#3357]
## Environment

* **Intellij-Rust plugin version:** v0.2.91.2115-183
* **Rust toolchain version:** 1.32.0 (9fda7c223 2019-01-16)
* **IDE name and version:** CLion 2018.3.4 Build #CL-183.5429.37
* **Operating system:** Ubuntu 18.04.1 LTS

## Problem description
Debugger displays incorrect values for strings in "Variables" window.
![2019-02-07_01-50-22](https://user-images.githubusercontent.com/4642384/52379194-d20db080-2a7a-11e9-910f-6b9f4c01cfef.png)

## Steps to reproduce
1. Create simple main.rs file with content
```
fn main() {
    let var1 = "123";
    let var2 = "456";
    println!("Hello, world!");
}
```
2. Set breakpoint to the last line

3. Click "Debug"

**Comment by ortem** [comment]
@denbkh Thanks for reporting! The problem should be fixed with bundled GDB pretty-printers which will be added soon.
