### ISSUE TITLE
Auto-import action may produce incorrect code

### ISSUE THREAD

**Issue by mchernyavsky** [intellij-rust/intellij-rust#3393]
## Environment

* **Intellij-Rust plugin version:** 0.2.92.2548-183-nightly
* **Rust toolchain version:** 1.34.0-nightly
* **IDE name and version:** CLion 2018.3.4
* **Operating system:** macOS Mojave 10.14.2

## Problem description

* Before auto-import:
```rust
enum A { B }
fn main() {
    let x = B/*caret*/
}
```

* After:
```rust
use crate

enum A { B }
fn main() {
    let x = B/*caret*/
}
```

**Comment by dima74** [comment]
Looks like it was fixed (can't reproduce in 0.4.155.4114-212)
