### ISSUE TITLE
Reexported types does not display in autocompletion

### ISSUE THREAD

**Issue by LooMaclin** [intellij-rust/intellij-rust#3396]
## Environment

* **Rust toolchain version:**

[loomaclin@loomaclin ~]$ rustup show
Default host: x86_64-unknown-linux-gnu

installed toolchains

stable-x86_64-unknown-linux-gnu
nightly-2018-06-01-x86_64-unknown-linux-gnu
nightly-2018-10-14-x86_64-unknown-linux-gnu
nightly-2019-01-17-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

installed targets for active toolchain

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.34.0-nightly (b244f61b7 2019-02-12)

* **IDE name and version:**
IntelliJ IDEA 2018.3.3 (Community Edition)
Build #IC-183.5153.38, built on January 9, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.20.7-arch1-1-ARCH
* **Operating system:**
[loomaclin@loomaclin ~]$ archey3

               +                OS: Arch Linux x86_64
               #                Hostname: loomaclin
              ###               Kernel Release: 4.20.7-arch1-1-ARCH
             #####              Uptime: 1:33
             ######             WM: None
            ; #####;            DE: GNOME
           +##.#####            Packages: 990
          +##########           RAM: 6002 MB / 15741 MB
         #############;         Processor Type: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
        ###############+        $EDITOR: None
       #######   #######        Root: 69G / 117G (58%) (ext4)

## Problem description
![reproduce gif](https://github.com/LooMaclin/reproduce_autoimport_reexported_types_idea_rust_plugin/blob/master/reproduce.gif)

1) `ggez` crate re-exported crate `mint`: https://docs.rs/ggez/0.5.0-rc.0/ggez/?search=#reexports
2) `mint` have public struct `Point2`: https://docs.rs/mint/0.5.1/mint/struct.Point2.html
3) but it dosnt display in autocompletion

## Steps to reproduce
1) Create empty project.
2) Add "ggez = "0.5.0-rc.0"
3) write `fn test(point: Point2<f32>)`
4) try to use autocomplete on `Point2<f32>`

Repo with reproduce: https://github.com/LooMaclin/reproduce_autoimport_reexported_types_idea_rust_plugin

**Comment by khionu** [comment]
If this can be raised in priority, that would be appreciated. This bug is now 4 months old, and is quite hindering, especially in game dev where we depend on nested crates a lot more than elsewhere.

**Comment by LooMaclin** [comment]
@Undin @vlad20012 could we raise the priority of this task?

**Comment by khionu** [comment]
[Amethyst](https://amethyst.rs) is sponsoring a bounty on this issue. If anyone is interested, please [email me](mailto:khionu@amethyst.rs) or reach me on Discord (Khionu#0047).

**Comment by Undin** [comment]
The current behavior is due to two independent issues:
* wrong parsing of `vec!` macro calls in `mint` repo
* auto import doesn't take into account re-exports via `pub extern crate` mechanism

The first one is already fixed in #4067. It should solve the problem related to name resolution. You can try the latest nightly version of the plugin (see [instuction](https://intellij-rust.github.io/install) to get the corresponding fix. Also, you can enable experimental macro expansion engine (see `Preferences | Languages & Frameworks | Rust | Expand declarative macros` option) to get proper completion.
The second one is going to be fixed soon.
