### ISSUE TITLE
Add `.ref` postifx template

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#3400]
Like `foo.not` -> `!foo`, but `foo.ref` -> `&foo`

**Comment by matklad** [comment]
and `refm` for `&mut foo`

**Comment by Undin** [comment]
Implementation of `not` postfix template can be found [here](https://github.com/intellij-rust/intellij-rust/blob/34bd4c53bccdf5b933205058a093381043406189/src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt#L46-L52)

**Comment by matklad** [comment]
Issues with links to code should have E-mentor as well, right?
