### ISSUE TITLE
Can't autocomplete associated method

### ISSUE THREAD

**Issue by CaptainMexiko** [intellij-rust/intellij-rust#3402]
## Environment

* **Intellij-Rust plugin version: v0.2.92.2116-183**
* **Rust toolchain version: stable-x86_64-pc-windows-gnu**
* **IDE name and version: CLion version CLion 2018.3.4
Build #CL-183.5429.37, built on January 31, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o**
* **Operating system: Windows 10 10.0**

## Problem description

I try to use [`rodio`,](https://github.com/tomaka/rodio) but the autocompletion don't show any of the `rodio::Decoder` associated method : 

![rodio_erreur_completion](https://user-images.githubusercontent.com/8819667/52822935-7dd68200-30b3-11e9-8cb8-635aa3bf797c.png)

even though they exist : 

![rodio_associeted_method](https://user-images.githubusercontent.com/8819667/52823022-d0b03980-30b3-11e9-8d35-9f35edad90bd.png)

It seems that CLion have problem with `impl<R> Decoder<R>` : 

![rodio_error_impl](https://user-images.githubusercontent.com/8819667/52823659-0d7d3000-30b6-11e9-8ecf-6a6dc5ab6d0d.png)

The `has implementation` shortcut don't work, maybe it because `rodio` has two struct `Decoder`

```rust
#[cfg(any(feature = "wav", feature = "flac", feature = "vorbis", feature = "mp3"))]
pub struct Decoder<R>(DecoderImpl<R>)
where
    R: Read + Seek;

#[cfg(not(any(feature = "wav", feature = "flac", feature = "vorbis", feature = "mp3")))]
pub struct Decoder<R>(::std::marker::PhantomData<R>);

```

## Steps to reproduce

Just add rodio `0.8.1` has your dependecies and try to create a Decoder
`let source = rodio::Decoder::`

**Comment by vlad20012** [comment]
Currently we can't evaluate #[cfg] attributes, so in your case `Decoder` can't be resolved to single definition.

**Comment by CaptainMexiko** [comment]
Ok, thanks for the quick answer.
