### ISSUE TITLE
Make plugin settings searchable in IDE

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#3404]
It would be great to have an ability to find plugin options from `Find action` dialog, but you can't at this moment

Related changes in gradle-intellij-plugin https://github.com/JetBrains/gradle-intellij-plugin/pull/347

**Comment by ice1000** [comment]
Where can I find related document? I searched "searchable options" and I found nothing related.

**Comment by Undin** [comment]
@ice1000 I don't know the separate document about it but it's about an ability to find some option via `find action`/`find all` dialogs (you can find more about `find all` [here](https://www.jetbrains.com/help/idea/searching-everywhere.html))
But before 2019.1 options provided by plugins couldn't be found at all. Since 2019.1 plugins can provide special xml with mapping from word to the corresponding option. 
The latest versions of gradle-intellij-plugin can generate such xml automatically so I think it can be closed because it's already works in builds for 2019.1 platform

**Comment by ice1000** [comment]
Ah, information get. So upgrading the intellij-gradle-plugin allows us to make the options searchable for free, right?

**Comment by Undin** [comment]
> So upgrading the intellij-gradle-plugin allows us to make the options searchable for free, right?

@ice1000 Yep, but if I understand correctly, it work only when you use IDEA >= 191.2752 for plugin builds (https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/main/groovy/org/jetbrains/intellij/IntelliJPlugin.groovy#L337)

**Comment by ice1000** [comment]
Thanks for the information!
