### ISSUE TITLE
"abstract" is not accepted as a mod name

### ISSUE THREAD

**Issue by ice1000** [intellij-rust/intellij-rust#3409]
My project structure:
![2019-02-17 00-28-08](https://user-images.githubusercontent.com/16398479/52908818-3daa0780-324b-11e9-97fe-67c6504b0a58.png)

Error message:
![2019-02-17 00-28-03](https://user-images.githubusercontent.com/16398479/52908820-44387f00-324b-11e9-9908-beabc216c775.png)

I suppose it's caused by the text-matching parser rule definition.

Plugin version: 0.2.92.2116-191
I don't think anything else is related to the issue. I can add post other info if needed.

**Comment by ortem** [comment]
`abstract` is a keyword [reserved for future use](https://doc.rust-lang.org/book/appendix-01-keywords.html#keywords-reserved-for-future-use), so you can't use it as a mod name. Rust compiler also prohibits it; just try to compile the code:
```Rust
mod abstract {
    pub fn foo() {}
}

fn main() {
    abstract::foo();
}
```

**Comment by ice1000** [comment]
Thanks!
