### ISSUE TITLE
Remove IDEA 15 compatibility

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#341]
when dropping 15
- [x] fix `@Storage` warning
- [x] use 1.8 java version
- [ ] lex unsigned 64 bit integers correctely
- [ ] switch to `Path` from `File` everywhere?  
- [x] use named disposables (eg, [here](https://github.com/intellij-rust/intellij-rust/blob/18cb75377e7a8853df998858ce874c48ded13261/src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt#L30))
- [x] check if perhaps with Java 8 we can work around https://youtrack.jetbrains.com/issue/KT-9073 ( No :( )
- [ ] ~use `onFinished` in `Task` implementations (toolchain)~
- [x] use `SemVer.INVALID` in toolchain. 

when dropping 2016.1

- [ ] review nullability of `getParent` methods (#606)
- [x] remove copy-pasted `GeneratedParserUtilsBase`.
- [x] don't bundle our own Kotlin runtime
- [x] figure what to do with recursion markers ( https://github.com/intellij-rust/intellij-rust/commit/e097ecfa2903bdc3e7626a783a52f65b2b48e384 )

when dropping 2016.2

- [ ] review green stubs
- [ ] don't bundle miglayout and layout.kt

**Comment by alexeykudinkin** [comment]
Nope, that'd be postponed until 2017.1. We're supporting 2 last major releases.

**Comment by matklad** [comment]
Hm, and isn't 2016.1 supposed to be a release? I thought that `XXXX.R` is a single version number, and that `major,minor,patch` version was changed to `release.patch`.

**Comment by alexeykudinkin** [comment]
`2016.2` wouldn't be a major one.

**Comment by johnthagen** [comment]
FWIW, I *think* @matklad is correct. See https://blog.jetbrains.com/blog/2016/03/09/jetbrains-toolbox-release-and-versioning-changes/

> YYYY.R

> where yyyy represents the year, and r the release within that year, obviously with the aim of having multiple releases per year

Each "`R`" is a major release, even from how the licensing works.

**Comment by alexeykudinkin** [comment]
@johnthagen my point was, that we're supporting 2 consecutive _year_ versions.

**Comment by johnthagen** [comment]
@alexeykudinkin Understood! Thanks.
