### ISSUE TITLE
Naming lints get enforced on extern variables

### ISSUE THREAD

**Issue by pie-flavor** [intellij-rust/intellij-rust#3414]
## Environment

* **Intellij-Rust plugin version:** v0.2.0.2114-183
* **Rust toolchain version:** rustc 1.33.0-nightly (a2b0f247b 2018-12-30)
* **IDE name and version:** CLion 2018.3.3
* **Operating system:** Windows 10 1809

## Problem description

Any static muts defined in an extern block have naming lints applied to them, even though they shouldn't because you have no control over them.

## Steps to reproduce

```rust
extern "C" {
    static mut foo: u32;
}
```
This generates a warning about static constant naming in IJ, but not in cargo build.

**Comment by Undin** [comment]
The same as #6023
Fixed by #6024
