### ISSUE TITLE
Add `Make public` quick-fix

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#3422]
It will be useful to suggest making item or field public, e.g. transform
```Rust
mod m {
    fn foo() {}
}
fn main() {
    m::foo/*caret*/();
}
```
to
```Rust
mod m {
    pub fn foo() {}
}
fn main() {
    m::foo();
}
```

It can be done via adding the corresponding quick-fix and passing it to [AccessError](https://github.com/intellij-rust/intellij-rust/blob/4462463c19a69de93e2d1094e463081c29273265/src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt#L223) and/or [StructFieldAccessError](https://github.com/intellij-rust/intellij-rust/blob/4462463c19a69de93e2d1094e463081c29273265/src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt#L235). For more details, see `AddMutableFix` and `CannotReassignToImmutable`.

This feature can be implemented in few stages.

**Comment by zinoviy23** [comment]
Can I try to implement this?

**Comment by ortem** [comment]
@zinoviy23 Yes, sure.
