### ISSUE TITLE
Automatically add module declaration

### ISSUE THREAD

**Issue by sirgl** [intellij-rust/intellij-rust#3426]
It would be good to automatically add declaration of module to corresponding location during file creation.
Example:
```
foo.rs  <-- create file
...
lib.rs  <-- add mod foo here
```

**Comment by vlad20012** [comment]
Currently, it works in a different order. When you type `mod foo;` in some file, the plugin shows you suggestion to create a file with such name:
![peek 2019-02-21 12-45](https://user-images.githubusercontent.com/3221931/53159255-8ad50300-35d6-11e9-9cc5-9304d2bdbdaf.gif)

**Comment by sirgl** [comment]
I know, but it would be more convenient to have such feature.
Thw other solution is to add action to create module or make chooser with options to create empty file or module

**Comment by vlad20012** [comment]
I think we can consider it as closed by #3826
