### ISSUE TITLE
Make Type hints to use Aliases

### ISSUE THREAD

**Issue by khionu** [intellij-rust/intellij-rust#3437]
As you can see here, I'm using a Type Alias because of the explicit type length. However, that shows in the Type Hints as the backing type. I think it would be prudent to make it use the Type Alias. If an alias is being used, it's intentionally masking, and it's not the IDE's job to say what it is masking. If configurable, it should default to using the Alias.

![20190224_2823b4](https://user-images.githubusercontent.com/11195266/53304358-43eb4580-3842-11e9-80b4-b1685cecf080.png)

**Comment by mkurnikov** [comment]
From `RustPython` codebase: 
![image](https://user-images.githubusercontent.com/2341827/58732057-1392e480-83f9-11e9-839a-0b1c7bbca2f7.png)
with `pub type PyObjectRef = Rc<PyObject<dyn PyObjectPayload>>;` accessible in scope.

**Comment by Undin** [comment]
Implemented in #4243
