### ISSUE TITLE
No type inference for split method

### ISSUE THREAD

**Issue by asv1** [intellij-rust/intellij-rust#3468]
## Environment

* **Intellij-Rust plugin version:**
v0.2.92.2116-183

* **Rust toolchain version:**
1.33

* **IDE name and version:**
WebStorm 2018.3.5

* **Operating system:**
Windows 10

## Problem description
There are no type inference for split method which returns iterator.

## Steps to reproduce
![untitled](https://user-images.githubusercontent.com/13184913/53691816-2c561480-3d8e-11e9-961b-1b59e925f63b.jpg)

**Comment by vlad20012** [comment]
Split type is defined with a macro, and we currently don't expand macros from the standard library.
![image](https://user-images.githubusercontent.com/3221931/53741335-315ab700-3ea7-11e9-93b0-35227cdbbe96.png)

Will be fixed with #3015
