### ISSUE TITLE
Publish as a library?

### ISSUE THREAD

**Issue by ice1000** [intellij-rust/intellij-rust#3486]
I'm a plugin developer working on the [pest's plugin](https://github.com/pest-parser/intellij-pest). Pest is an elegant parser generator for Rust, which allows some interaction with grammar file and Rust code.

I want to develop something like,

+ automatically inject Pest language to Rust's `#[grammar_inline = "bla"]`
+ help Rust resolve references that are from the grammar file

However, during development I didn't find a way to add Rust plugin as a library dependency.
Is there any stable URL for obtaining an artifact?

I'm aware that I can do `setPlugins("org.rust.lang:0.2.93.2117-191")`, say, specify a version explicitly (so gradle download plugin dependency for me), or `setPlugins("org.rust.lang")` and install the plugin in my localPath IDE.

However I don't want to specify a version in my build script. Is there any way to not to specify a specific version?

**Comment by Undin** [comment]
> Is there any stable URL for obtaining an artifact?

[Plugin repository](https://plugins.jetbrains.com/plugin/8182-rust) provides such URLs but for each build separately

> Is there any way to not to specify a specific version?

It seems there is no way to avoid it.
Note, we don't provide stable API yet so any plugin update can break your plugin especially if you're going to use more complicated interaction than injection and reference contribution

**Comment by ice1000** [comment]
BTW, if I want to do something like "contribute to the references resolving process of some file if they have some macros", is there any materials that I can look into?

**Comment by ice1000** [comment]
> Note, we don't provide stable API yet so any plugin update can break your plugin especially if you're going to use more complicated interaction than injection and reference contribution

Yup I'm aware. Hopefully I can follow the up-to-date API. I've implemented an injector, feeling that it's very easy.
![rust-injected](https://user-images.githubusercontent.com/16398479/53776511-44c84b00-3ec4-11e9-9771-83106b6ccd57.png)

**Comment by vlad20012** [comment]
> Is there any way to not to specify a specific version?

Gradle (unlike Cargo) usually use __exact__ versions of some dependency, and a maintainer upgrade it manually. You can also use git submodules and somehow depends on this repo instead of binary artifact, but I don’t know if this is a good or bad idea. 

> BTW, if I want to do something like "contribute to the references resolving process of some file if they have some macros", is there any materials that I can look into?

Mmm, could you please point to specific Pest feature you want to support? And maybe we can discuss about it in some chat? Maybe discord?

**Comment by Undin** [comment]
> BTW, if I want to do something like "contribute to the references resolving process of some file if they have some macros", is there any materials that I can look into?

I think [this](https://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support/reference_contributor.html) can be useful
The main part of integration: we implement `ContributedReferenceHost` for some PSI element, you implement `PsiReferenceContributor` which provides additional references in some cases
At this moment, we have two psi elements which implement `ContributedReferenceHost`: `RsMetaItem` and `RsLitExpr` (in fact, only `RsLitExprImpl` implements `ContributedReferenceHost` but we are going to move it to public API in teh nearest future)

**Comment by ice1000** [comment]
Is there API for getting the `src` directory?

**Comment by vlad20012** [comment]
> Is there API for getting the src directory?

`RsElement.containingCargoTarget?.pkg?.crateRoot?.parent`
This should works, but maybe there is a better solution.

**Comment by ice1000** [comment]
> Mmm, could you please point to specific Pest feature you want to support? And maybe we can discuss about it in some chat? Maybe discord?

Pest generates an `enum` called `Rule` during deriving the parser, all the grammar rules become a variance. intellij-rust is not abled to find the definitions of these generated variance, but with my plugin there can be something (the rules in the grammar file) for the symbols to refer to.

Example:

+ Pest file (grammar.pest)
```
....
expression = { ... }
```

+ Rust file
```rust
#[derive(Parser)]
#[grammar = "grammar.pest"]
struct MiniParser;

pub fn parse_str(input: &str) -> Result<Expression, String> {
    Ok(expression_to_expression(
        MiniParser::parse(Rule::expression, input)
            .map_err(|err| format!("Parse failed at:{}", err))?
            .next()
            .unwrap(),
    ))
}
```
The `Rule::expression` is generated from the rule in the grammar file snippet.

**Comment by ice1000** [comment]
Yup the reference I want to contribute is targeting an expression. This sounds like a little bit more difficult than contributing to a literal.

**Comment by ice1000** [comment]
I feel like this is very similar to the properties plugin (which support `*Bundle.message` resolving).

**Comment by vlad20012** [comment]
In the ideal world this should work like this:
1. we can expand procedural macros
2. `Rule` variants can be successfully resolved to macro expansions
3. Then you implement `TargetElementEvaluatorEx2` in your plugin and refine go-to-declaration target (just like we supported resolve to standard `derive` in `RsTargetElementEvaluator`)

But in the real world, we don't support procedural macros :(
But we aim to! #3015 will bring some infrastructure that will be also used to support procedural macros, there is a [command line procedural macro expander](https://github.com/fedochet/rust-proc-macro-expander), so one day they will be supported.
Hack name resolution is a very bad idea b/c soon we will rewrite it completely (and by many other reasons). You can try to refine go-to-declaration target when reference is not resolved `TargetElementEvaluatorEx2.getElementByReference` (reuse out hacks from `RsTargetElementEvaluator`) and then walk up PSI manually, but I think it's a bad idea too...

**Comment by ice1000** [comment]
> Hacking name resolution is a very bad idea b/c soon we will rewrite it completely

Ooops, how's the rewrite gonna be? I'd say it at least hacking the name resolutino work for me, because I cannot come up with a better (or possible) idea. As we know, the parser generation takes seconds even in Rust, I can't imagine how long is that gonna take for a plugin to interact with another process and parse the stdio.

**Comment by vlad20012** [comment]
> Rust, I can't imagine how long is that gonna take for a plugin to interact with another process and parse the stdio.

It should be expanded single time and then re-expanded on grammar change or manually. Just like we Gramma Kit that you use =)

**Comment by vlad20012** [comment]
> Ooops, how's the rewrite gonna be?

I'm about `NameResolution.kt` file

**Comment by ice1000** [comment]
> > Rust, I can't imagine how long is that gonna take for a plugin to interact with another process and parse the stdio.
> 
> It should be expanded single time and then re-expanded on grammar change or manually. Just like in Grammar Kit that you use =)

Really! It sounds like a very efficient and a best-practice implementation. Great work!

**Comment by Undin** [comment]
@ice1000 After #3489 `RsLitExpr` implements `ContributedReferenceHost `

**Comment by ice1000** [comment]
Closing as answered
