### ISSUE TITLE
`e.backtrace()` call of `failure::Error` is marked invalid

### ISSUE THREAD

**Issue by twistedfall** [intellij-rust/intellij-rust#3487]
## Environment

* **Intellij-Rust plugin version:** v0.2.93.2117-183
* **Rust toolchain version:** rustc 1.33.0 (2aa4c46cf 2019-02-28)
* **IDE name and version:** Build #IU-183.5912.21, built on February 26, 2019
JRE: 1.8.0_202-b08 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
* **Operating system:** Linux 5.0.0-gentoo

## Problem description
While using `failure-0.1.5` when you have an object of type `failure::Error` the call to its `backtrace()` method, while being valid Rust code, is marked invalid and IDEA suggests importing `failure::Fail` trait. After importing this trait the error goes away, but rustc start to give warning about unused import.

The method `backtrace()` exists on the type itself, it's not implemented as `failure::Fail` trait. And in fact it's signature is different.

## Steps to reproduce
(not giving the rust playground link because you can't use `failure` there)
```rust
fn a(e: failure::Error) {
	e.backtrace();
}

fn main() {
}
```
![afbeelding](https://user-images.githubusercontent.com/406037/53794986-4b40dc00-3f31-11e9-87f4-7b3f1dbdaa89.png)

![afbeelding](https://user-images.githubusercontent.com/406037/53795144-a246b100-3f31-11e9-8a74-54a29f1271d9.png)

**Comment by Kobzol** [comment]
This should be fixed by the new macro expansion engine, please try it (https://github.com/intellij-rust/intellij-rust/issues/3628).

**Comment by twistedfall** [comment]
Thanks! This issue is indeed fixed by using the new macro engine.
