### ISSUE TITLE
Cannot resolve LinkedList type

### ISSUE THREAD

**Issue by fan-tom** [intellij-rust/intellij-rust#3491]
## Environment

* **Intellij-Rust plugin version:**
v0.2.93.2117-183
* **IDE name and version:**
PyCharm 2018.3.5 (Community Edition)
Build #PC-183.5912.18, built on February 26, 2019
JRE: 1.8.0_152-release-1343-b28 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6
* **Operating system:**
macOs

## Problem description
Plugin cannot resolve LinkedList type
![image](https://user-images.githubusercontent.com/14140464/53866053-70f1e200-4012-11e9-8776-8d6553d54566.png)

**Comment by vlad20012** [comment]
Yeah, it's a bug, I've reproduced it
