### ISSUE TITLE
"Implement methods" strips lifetime and dyn on method signature

### ISSUE THREAD

**Issue by athre0z** [intellij-rust/intellij-rust#3493]
## Environment

* **Intellij-Rust plugin version:** v0.2.93.2117-183
* **Rust toolchain version:** rustc 1.35.0-nightly (f22dca0a1 2019-03-05)
* **IDE name and version:** CLion 2018.3.4
* **Operating system:** macOS 10.14

## Problem description
When generating method implementations for a trait, the `dyn` marker and lifetime parameters in pathes in the method signature are elided. This is deprecated in Rust 2018.

Both lints (`bare_trait_objects`, `elided_lifetimes_in_paths`) are allowed by default, so this is likely not too important for now.

## Steps to reproduce

```rust
#![deny(elided_lifetimes_in_paths)]

struct S<'a>(std::marker::PhantomData<&'a u32>);

trait T2 {
    fn stuff(&self, s: S<'_>) -> S<'_>;
}

struct X;
impl T2 for X {
    // Press cmd + n here -> implement methods
}
```

```rust
#![deny(bare_trait_objects)]

trait T1 {}

trait T2 {
    fn stuff(&self, t: &dyn T1) -> &dyn T1;
}

struct X;
impl T2 for X {
    // Press cmd + n here -> implement methods
}
```

**Comment by krojew** [comment]
Any chance for a fix? It's quite frustrating to get new warnings when using "implement methods".

**Comment by jbx1** [comment]
This issue becomes evident immediately when one follows the Rust Book Ch17.3

```
trait State {
    fn request_review(self: Box<Self>) -> Box<dyn State>;
}

struct Draft {}

impl State for Draft {
    //intellij Rust plugin generates this when implementing the method of trait State
     fn request_review(self: Box<Self>) -> Box<State> {
        unimplemented!()
    }
}
```
It then highlights the `<State>`  saying `Trait objects without an explicit 'dyn' are deprecated`. 

Should really be fixed because it confuses beginners.

**Comment by Kobzol** [comment]
@Undin The `dyn` problem should be solved by https://github.com/intellij-rust/intellij-rust/pull/5317.
I tried the lifetime example on `master` and the lifetimes are not elided anymore, so maybe this issue can be closed.
