### ISSUE TITLE
Debugger won't run test

### ISSUE THREAD

**Issue by svenschmidt75** [intellij-rust/intellij-rust#3502]
Project: https://github.com/svenschmidt75/Rust/tree/master/NeuralNetwork
Commit: 0e37da5d8e4ab0ee426c9fb0e86762a8f56f5524

Open file model.rs, and try to run test test_backprop_andgate in the debugger.
I get an error, see screenshot.

![Screenshot from 2019-03-09 07-31-09](https://user-images.githubusercontent.com/17226522/54072836-649d9d00-423d-11e9-88c2-1102760a9642.png)

**Comment by svenschmidt75** [comment]
Works with CLion 2018.3.4 and plugin version v0.2.93.2117-183

**Comment by Undin** [comment]
@svenschmidt75 Thanks for the report!
The bug is because of incompatible changes in CLion
It will be fixed in the next plugin release
Also, the bug should be already fixed in the latest nightly builds. If you want to try them, see instruction [here](https://intellij-rust.github.io/install))
