### ISSUE TITLE
click #[test] fn...  to debug, println!("{}",...) not  work!

### ISSUE THREAD

**Issue by zhuxiujia** [intellij-rust/intellij-rust#3505]
click `#[test]
fn test() {
    println!("Hidden output")
} ` to debug, `println!("{}",...)` not  work in Clion!
if need println! ,must add command  "--nocapture"

you can see stackoverflow  https://stackoverflow.com/questions/25106554/why-doesnt-println-work-in-rust-unit-tests

**Comment by mchernyavsky** [comment]
This should help: https://stackoverflow.com/a/54592689/5900099

**Comment by zhuxiujia** [comment]
> This should help: https://stackoverflow.com/a/54592689/5900099

yes,I've already done this, but I can add this parameter by default.

**Comment by mchernyavsky** [comment]
> yes,I've already done this, but intellij-rust can add this parameter by default？

Have you enabled the option for the Cargo Command **template** (as shown in the screenshot from the answer) or for a specific configuration?

**Comment by zhuxiujia** [comment]
> > yes,I've already done this, but intellij-rust can add this parameter by default？
> 
> Have you enabled the option for the Cargo Command **template** (as shown in the screenshot from the answer) or for a specific configuration?

Yes, Thank you   that's work now.   This option was not enabled by default.
