### ISSUE TITLE
Margin length uncontrolled

### ISSUE THREAD

**Issue by sntdevco** [intellij-rust/intellij-rust#3516]
## Environment

- **Intellij-Rust plugin version:** v0.2.93.2117-183
- **Rust toolchain version:** 1.32.0
- **IDE name and version:** CLion 2018.3
- **Operating system:** Ubuntu 18.04.2 LTS

## Problem description
The margin length is uncontrolled for a line break for the same method

## Steps to reproduce
Just write the code below and you'll see the margin continuing beyond the function call
![intellijrust-error1](https://user-images.githubusercontent.com/17377258/54102326-eb917780-43ed-11e9-867e-9210e96b6010.png)

**Comment by ortem** [comment]
The margin disappears if you add some statement below. The behavior is the same as for Java or Kotlin.

<img width="180" alt="Screenshot 2019-03-12 at 11 50 42" src="https://user-images.githubusercontent.com/4854600/54186735-1a2a5380-44bd-11e9-9dcb-cdf8c5debc3c.png">

**Comment by sntdevco** [comment]
All right! @ortem 
`closing!()`
