### ISSUE TITLE
Fails to parse properly a static variable preceded with `$(tt:tt)?` in a macro

### ISSUE THREAD

**Issue by fredpointzero** [intellij-rust/intellij-rust#3521]
Hi,

In a macro, I declare static variable. When I use explicitly `pub` intellij-rust detect correctly the variable, but this is not the case when using instead `$(tt:)?`.

(See `Problem description` for a working and failing macro)

## Environment

* **Intellij-Rust plugin version:** v0.2.93.2117-183
* **Rust toolchain version:** nightly-x86_64-pc-windows-gnu (update hash: 9ee98c6e8151b42de859, updated at 2019-03-07)
* **IDE name and version:** CLion 2018.3.4
Build #CL-183.5429.37, built on January 31, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* **Operating system:** Windows 10 10.0 version 1803 OS build 17134.590

## Problem description

In this file:
```
#[macro_export]
macro_rules! enumstr_err {
    ($($tt:tt)? enum $name:ident as $NAMES:ident as $VALUES:ident { $($entry:ident => $value:expr),* }) => {
        #[allow(dead_code)]
        $($tt)? const $VALUES: &[$name] = &[$($name::$entry),*];
        #[allow(dead_code)]
        $($tt)? const $NAMES: &[&str] = &[$($value),*];
        #[derive(Debug, Clone, Copy, Eq, PartialEq, Hash)]
        $($tt)? enum $name {
            $($entry),*
        }
    };
}

#[macro_export]
macro_rules! enumstr_ok {
    (pub enum $name:ident as $NAMES:ident as $VALUES:ident { $($entry:ident => $value:expr),* }) => {
        #[allow(dead_code)]
        pub const $VALUES: &[$name] = &[$($name::$entry),*];
        #[allow(dead_code)]
        pub const $NAMES: &[&str] = &[$($value),*];
        #[derive(Debug, Clone, Copy, Eq, PartialEq, Hash)]
        pub enum $name {
            $($entry),*
        }
    };
}

#[cfg(test)]
mod tests {
    enumstr_err! {
        pub enum EnumAll as ENUM_ALL_NAMES as ENUM_ALL_VALUES {
            Value0 => "value0",
            Value1 => "value1"
        }
    }

    enumstr_ok! {
        pub enum EnumAll2 as ENUM_ALL_NAMES2 as ENUM_ALL_VALUES2 {
            Value0 => "value0",
            Value1 => "value1"
        }
    }

    #[test]
    fn compiles() {
        let _v_err = ENUM_ALL_NAMES[0];
        let _v_ok = ENUM_ALL_NAMES2[0];
    }
}
```
`let _v_err = ENUM_ALL_NAMES[0];` => `ENUM_ALL_NAMES` is unknown to the parser
`let _v_ok = ENUM_ALL_NAMES2[0];` => `ENUM_ALL_NAMES2` is known to the parser

The only difference is that the visiblity token is dynamic in the first macro (`$(tt:tt)?`) and fixed in the second (`pub`)

## Steps to reproduce

1. Create a rust library project
2. Copy the sample into lib.rs
3. Use CLion with the Rust plugin to open the file
4. CTRL+Hover `ENUM_ALL_NAMES2` in let statement => displays the definition of `ENUM_ALL_NAMES2`
5. CTRL+Hover `ENUM_ALL_NAMES` in let statement => nothing happens, _expected: displays the definition of `ENUM_ALL_NAMES`_

**Comment by vlad20012** [comment]
We don't support `?` in macros for now. I'll fix it

**Comment by fredpointzero** [comment]
Thanks for taking care of this!
