### ISSUE TITLE
Move refactoring

### ISSUE THREAD

**Issue by fan-tom** [intellij-rust/intellij-rust#3531]
Does anyone work on "Move ..." refactoring to easily move types/functions/impls from one module to another with automatic imports fixing? Current implementation suggest to move the entire file

**Comment by vlad20012** [comment]
> Does anyone work on

Currently, no

**Comment by dima74** [comment]
Current plan:
* [ ] Move single file (#5181)
* [ ] Move directory / Move file with its child modules
* [ ] Move top level items

**Comment by dima74** [comment]
Move refactoring is mostly completed, so I invite everyone to try it and share feedback! All code is in [`diralik/move`](https://github.com/intellij-rust/intellij-rust/tree/diralik/move) branch, so you can just run IDE from this branch, or, alternatively, use these plugin builds:
* 2020.1: [intellij-rust-0.2.125.SNAPSHOT-201-dev.zip](https://github.com/intellij-rust/intellij-rust/files/4769551/intellij-rust-0.2.125.SNAPSHOT-201-dev.zip)
* 2020.2: [intellij-rust-0.2.125.SNAPSHOT-202-dev.zip](https://github.com/intellij-rust/intellij-rust/files/4769541/intellij-rust-0.2.125.SNAPSHOT-202-dev.zip)

---

There are two types of move refactoring: 
1. Move top level items. To invoke it place cursor at some item in editor (or select multiple items), press F6 and then optionally select additional items to move
![image](https://user-images.githubusercontent.com/6505554/84427701-c28a1300-ac3e-11ea-9934-94e349eb6472.png)

2. Move files or directories. It can be invoked directly from editor (F6 when cursor is at empty line) or from file tree (F6 or using cut&paste or using drag&drop):
![image](https://user-images.githubusercontent.com/6505554/84428547-1517ff00-ac40-11ea-829c-50902591f7e7.png)

---

What is expected to work now:
* Moving multiple files (with child modules) / multiple directories
* Moving to different crate
* Checking visibility conflicts (use of private item/field/method after move)
* Changing references to moved elements
  - including references in imports, references though reexports, self references, etc
* Changing relative references from moved elements
* Adding import for traits which methods are used in moved items

---

What is not expected to work now:
* 2015 edition
* References inside macro calls / macro_rules
* Moving macros / updating references to macros
* Anything related to `cfg` attributes
* Changing paths in attributes (https://github.com/intellij-rust/intellij-rust/issues/5446#issuecomment-634477944)
* References from comments/text
* [`#[path]`](https://doc.rust-lang.org/reference/items/modules.html#the-path-attribute) attributes

**Comment by Kobzol** [comment]
@dima74 Awesome! This is one of the refactorings that are very annoying and IDE support helps a lot. The nested impls below structs/enums are very handy.

One additional feature request: if the target file does not exist yet, could the refactoring create it?

**Comment by dima74** [comment]
@Kobzol good idea! I will implement it (at least for simple case when it is possible to find parent mod for nonexistent target file)

**Comment by Kobzol** [comment]
We now have https://github.com/intellij-rust/intellij-rust/pull/5490/files - maybe you can reuse the quick fix's method to find available modules. Thanks again, I'm looking forward to the move refactoring!

**Comment by Undin** [comment]
@dima74 Can we close this issue? Looks like all base cases are already supported

**Comment by dima74** [comment]
@Undin Yes, closing, since all base cases are supported
