### ISSUE TITLE
Improve chain call formatting

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#355]
Problem: chain calls should be formatted beautifully.

Looks like the rust community is [split](https://github.com/rust-lang/rust/pull/33020#discussion_r59975354) about what the proper formating is (rustfmt [issue](https://github.com/rust-lang-nursery/rustfmt/issues/439)).

Basically, there are two options:

a) simply indent

```
calculate().bar().iter()
    .map(|i| ... )
    .filter(...)
    .collect(...)
```

b) align to dot

```
calculate().bar()
           .iter()
           .map(|i| ... )
           .filter(...)
           .collect(...)
```

I think we should implement both styles and add an option "align method calls" (off by default, imo).  We should not insert newlines ourselves.

**Comment by jajakobyly** [comment]
Will implement this, but it's not my highest priority currently

**Comment by lilianmoraru** [comment]
The problem with `align to dot` is that sometimes the line is to long and everything is strangely aligned on the far right...
