### ISSUE TITLE
Regression: Debugger is not working in Clion 2019.1 Beta

### ISSUE THREAD

**Issue by maxim-banaev** [intellij-rust/intellij-rust#3552]
## Environment

* **Intellij-Rust plugin version:** v0.2.93.2117-191
* **Rust toolchain version:** 1.28.0
* **IDE name and version:** Clion 2019.1 Beta CL-191.6183.6
* **Operating system:** Ubunty 18.04

## Problem description

I get the following in the event log every time I try to debug any Rust unit test:

Error running 'Test MyTest': 

> org.rust.debugger.runconfig.RsLocalDebugProcess.postCommand(Lcom/jetbrains/cidr/execution/debugger/CidrDebugProcess$VoidDebuggerCommand;)Lorg/jetbrains/concurrency/Promise;

## Steps to reproduce

Debug next simple code:
`pub fn add(a: i32, b: i32) -> i32 {
    a + b
}

// This is a really bad adding function, its purpose is to fail in this
// example.
#[allow(dead_code)]
fn bad_add(a: i32, b: i32) -> i32 {
    a - b
}

#[cfg(test)]
mod tests {
    // Note this useful idiom: importing names from outer (for mod tests) scope.
    use super::*;

    #[test]
    fn test_add() {
        assert_eq!(add(1, 2), 3);
    }

    #[test]
    fn test_bad_add() {
        // This assert would fire and test will fail.
        // Please note, that private functions can be tested too!
        assert_eq!(bad_add(1, 2), 3);
    }
}`

https://youtrack.jetbrains.com/issue/CPP-15745

**Comment by maxim-banaev** [comment]
Reproduce with a simple example.
`
fn main() {
    println!("Hello World!");
}
`

**Comment by Undin** [comment]
Duplicates of #3502
