### ISSUE TITLE
Cannot find declaration (large project: Servo)

### ISSUE THREAD

**Issue by ejmg** [intellij-rust/intellij-rust#3563]
Hi everyone, thank you so much for developing this plugin over at JetBrains. Here's my issue:

## Environment

* **Intellij-Rust plugin version:** `0.2.0.2114-182`
* **Rust toolchain version:** `rustup 1.17.0 (069c88ed6 2019-03-05)`
* **IDE name and version:** IntelliJ Ultimate 2018.2.2
* **Operating system:** `x86_64 Linux 5.0.2-arch1-1-ARCH`

## Problem description
When navigating files in subdirectory [servo/servo](https://github.com/servo/servo/tree/cc2d20315149887ee1f125deac1a1807722a50ee/ports/servo), it appears that IntelliJ is not able to detect crate/root information correctly, and will give `Cannot find declaration to go to` for basically all modules being used in this subdirectory.

Here is a screenshot of what I am seeing, specifically:

![Screenshot_20190319_150809](https://user-images.githubusercontent.com/18218174/54638454-0d77a380-4a59-11e9-9b3f-be9cf4885056.png)

Furthermore, closing the project and restarting it does not seem to help here. I think my issue is similar/the same as what occurred for #1346, except that I have imported Servo as a project proper (i.e. from its root).

## Steps to reproduce

1. Open project
2. Open file
3. Attempt go-to definition

Let me know if some more information/debugging on my end would be of use if this is a legitimate bug.

**Comment by Undin** [comment]
@ejmg Hi!
Thanks for the report!
Looks like the main reason that name resolution doesn't work for `non_android_main.rs` is this file is included via `include!` macro in `servo/ports/servo/main.rs`. Unfortunately, the plugin doesn't support almost all intelli-sense features for such files at this moment because it doesn't know that such files are part of a project
See related issue #1908

We are going to implement such support for included files right after #3015 but we can't provide any time estimation because of some technical issues related to `include` macro.

So you can try to replace (if it's possible at all) `include` macro invocation to help the plugin understand this code better

**Comment by Undin** [comment]
BTW latest versions of IntelliJ Rust plugin doesn't support IDEA 2018.2 so all new features are available only in 2018.3 and 2019.1 IDEs

**Comment by ejmg** [comment]
Undin, thanks for the response.

> Looks like the main reason that name resolution doesn't work for non_android_main.rs is this file is included via include! macro in servo/ports/servo/main.rs. Unfortunately, the plugin doesn't support almost all intelli-sense features for such files at this moment because it doesn't know that such files are part of a project
> See related issue #1908
> 
> We are going to implement such support for included files right after #3015 but we can't provide any time estimation because of some technical issues related to include macro.

It's funny how we features we take for granted! In retrospect, the issue is a lot more clear.

> We are going to implement such support for included files right after #3015 but we can't provide any time estimation because of some technical issues related to include macro.

Totally understandable. I'm excited nonetheless :slightly_smiling_face: 

> BTW latest versions of IntelliJ Rust plugin don't support IDEA 2018.2 so all new features are available only in 2018.3 and 2019.1 IDEs

Thanks for the heads up. I'm running off of an AUR packaging of intellij ultimate and don't expect it to update as quickly JetBrains rolls them out, but I'll keep an eye on it and switch over to a manual install if the maintainers don't push an update out soon.

Thank so you so much for the response, you cleared up a lot of stuff for me!

**Comment by vlad20012** [comment]
> I'm running off of an AUR packaging

We're very-very (very-very-very-very) recommend installing the JetBrains toolbox (you can do it [from AUR](https://aur.archlinux.org/packages/jetbrains-toolbox/) btw) and then manage updates of our products from the toolbox. Late updates are not the single limitation of AUR packages. The most significant drawback is the fact that they use AUR OpenJDK packages when we bundle custom builds of patched JDK with our products. So AUR versions can have weird bugs. I even saw a segfault (yep, segfault in java, lol)
