### ISSUE TITLE
Snippets from other editors

### ISSUE THREAD

**Issue by RustSnippets** [intellij-rust/intellij-rust#357]
https://github.com/zargony/atom-language-rust/blob/master/snippets/rust.cson
https://github.com/abaez/ta-rust/blob/master/snippets.lua
https://github.com/freebroccolo/rust-snippets/blob/master/rust-snippets.el
https://github.com/darookee/vim-snippets/blob/master/UltiSnips/rust.snippets
https://github.com/rust-lang/sublime-rust/tree/master/snippets

Maybe you can derive some ideas from other editors and implement it in your project.

**Comment by matklad** [comment]
Our snippets are here (warning, XML! ) https://github.com/intellij-rust/intellij-rust/blob/master/src/main/resources/org/rust/ide/liveTemplates/Rust.xml .

**Comment by jajakobyly** [comment]
Ok, "taking" this.
