### ISSUE TITLE
Consider renaming `iter` postfix template into `for`

### ISSUE THREAD

**Issue by SomeoneToIgnore** [intellij-rust/intellij-rust#3580]
A few considerations on why it would seem to be better:

* There is already a number of `iter` methods present, but no `for` ones
<img width="531" alt="image" src="https://user-images.githubusercontent.com/2690773/54885009-f7fee100-4e7f-11e9-852a-196e011f88aa.png">

* It seems more natural to use the Rust keyword, also the same is already done by other postfix templates such as `let`, `match`

**Comment by Undin** [comment]
@SomeoneToIgnore I don't think we need to *rename* `iter` postfix template into `for` because it's common postfix template to generate `for` loop over a collection
But indeed we can add `for` template a well as it's done for Java/Kotlin/etc

**Comment by SomeoneToIgnore** [comment]
That was exactly my point — make a 

> common postfix template to generate for loop over a collection

to be invoked via `for` postfix template, not `iter` as it is now because of the reasons I've mentioned above.

The current implementation for `iter`, `IterPostfixTemplate` is rather simple and wraps the collection with a `for` loop, without any iterators involved. I would expect the `iter()` method involved into the generation when using a template with such name.

But I don't insist, good that the ticket is useful anyway :)

**Comment by Undin** [comment]
> The current implementation for iter, IterPostfixTemplate is rather simple and wraps the collection with a for loop, without any iterators involved. I would expect the iter() method involved into the generation when using a template with such name.

Yeah, it would be great but it's should be a separate issue
