### ISSUE TITLE
Show diff if `assert_eq` fails

### ISSUE THREAD

**Issue by SomeoneToIgnore** [intellij-rust/intellij-rust#3584]
Similar to Java and Kotlin, I would like to be able to display a diff for the cases when `assert_eq!` macro fails.

Kotlin example:
<img width="368" alt="image" src="https://user-images.githubusercontent.com/2690773/54885344-c0923380-4e83-11e9-938b-4903b0588c3c.png">

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/2690773/54885343-be2fd980-4e83-11e9-881d-585128f6d990.png">

**Comment by Undin** [comment]
@SomeoneToIgnore Already implemented in #3465

**Comment by SomeoneToIgnore** [comment]
Indeed, sorry.
