### ISSUE TITLE
Allow navigation in rustdocs of the standard library

### ISSUE THREAD

**Issue by SomeoneToIgnore** [intellij-rust/intellij-rust#3591]
Rustdocs from the standard library contain a lot of links to the other places of the documentation:

<img width="941" alt="image" src="https://user-images.githubusercontent.com/2690773/54886078-81b4ab80-4e8c-11e9-9efe-5267c2486d27.png">

It would be great to be able to navigate to those via Cmd + click (Ctrl + click) similar to the way it's possible to navigate to the method definition currently.

**Comment by vlad20012** [comment]
@Undin Maybe we should start to build PSI for docs just like Java does

**Comment by Undin** [comment]
@vlad20012 Looks like we already do it. But only while highlighting

**Comment by vlad20012** [comment]
We have a lexer, but not a parser

**Comment by Undin** [comment]
> We have a lexer, but not a parser or PSI structure

@vlad20012 agree. It makes sense

**Comment by Kobzol** [comment]
Related issue: https://github.com/intellij-rust/intellij-rust/issues/4518

**Comment by vlad20012** [comment]
I'm working on this
