### ISSUE TITLE
Refactor `RustNamedElement`

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#360]
All usages of `nameElement` are followed by `.text`, which does not really work for top level modules. Besides, there is `com.intellij.psi.PsiNameIdentifierOwner`, which can be reused instead of providing our own `val nameElement` (the benefits are unclear however).

**Comment by jajakobyly** [comment]
Whoa didn't know that PsiNameIdentifierOwner isn't used :O

**Comment by alexeykudinkin** [comment]
This refactoring should be straightforward and assume no more than just a replacement of the `.text` with  the `.name` references of the respective named-elements.

**Comment by matklad** [comment]
@alexeykudinkin I suspect we are not on the same page here, I must have caused a massive confusion by #361 :(

So, we have `RustNamedElement`:

```
interface RustNamedElement   : RustCompositeElement
                             , PsiNamedElement
                             , NavigatablePsiElement {
    val nameElement: PsiElement?
}
```

What is the semantics of this `nameElement`? To me, it looks like this should be the identifier (a single word), so that `RustNameElement.name` can be implemented as `this.nameElement.text`. I don't understand how it is possible to return `this` for `nameElement` and then use `.name` (I understand that it was your suggestion [here](https://github.com/intellij-rust/intellij-rust/pull/359#discussion_r61402455)). Using `.name` will require this recursion

```
interface RustNamedElement   : RustCompositeElement
                             , PsiNamedElement
                             , NavigatablePsiElement {
    val nameElement: RustNamedElement?
}
```

To me, looks like this `nameElement` is an implementation detail (and `name` is the interface). I've tried to implement it in this PR: https://github.com/intellij-rust/intellij-rust/pull/364

**Comment by alexeykudinkin** [comment]
Fix also `nameElement` for the `RustFile`, please!

**Comment by matklad** [comment]
Closed by https://github.com/intellij-rust/intellij-rust/pull/364
