### ISSUE TITLE
Auto-complete does not work with `bitflags!` generated structs

### ISSUE THREAD

**Issue by aloucks** [intellij-rust/intellij-rust#3611]
## Environment

* **Intellij-Rust plugin version:** Rust (0.2.95.2120-191)
* **Rust toolchain version:** rustc 1.33.0 (2aa4c46cf 2019-02-28)
* **IDE name and version:** IntelliJ IDEA 2019.1 Build #IC-191.6183.87 March 27, 2019
* **Operating system:** Windows 10 Pro 64bit

## Problem description

Auto-completion does not work for the associated constants of structs created with `bitflags!`.

In addition, Goto Declaration fails when structs are imported with **Rust 2018** edition syntax:

```rust
use bitflags::bitflags;
```

Using **Rust 2015** edition syntax enables Goto Declaration to work, but the auto-completion still does not.

```rust
#[macro_use]
extern crate bitflags;
```

## Steps to reproduce

Cargo.toml

```toml
[package]
name = "foo"
version = "0.1.0"
edition = "2018"

[dependencies]
bitflags = "1.0.4"
```

main.rs (2018 edition syntax)

```rust
use bitflags::bitflags;

bitflags! {
    struct Foo: u32 {
        const A = 0b00000000;
        const B = 0b10000000;
    }
}

fn main() {
    Fo<auto-complete-here-does-NOT-find-the-struct>
    Foo::<auto-complete-here-does-NOT-find-A-or-B>
}
```

main.rs (2015 edition syntax)

```rust
#[macro_use]
extern crate bitflags;

bitflags! {
    struct Foo: u32 {
        const A = 0b00000000;
        const B = 0b10000000;
    }
}

fn main() {
    Fo<auto-complete-finds-the-struct>
    Foo::<auto-complete-here-does-NOT-find-A-or-B>
}
```

It's understandable that general support for macro generated structs may be a long way off (or impossible?), but it would be nice if support for `bitflags!` could be baked in, considering it's the 3rd most downloaded crate on [crates.io](https://crates.io/).

**Comment by vlad20012** [comment]
There are two problems:
1. Autoimport from macro expansions. Will be automatically fixed with #3015
2. `bitflags` with 2018 edition syntax. Looks like we should support attribute [`#[macro_export(local_inner_macros)]`](https://doc.rust-lang.org/edition-guide/rust-2018/macros/macro-changes.html#macros-using-local_inner_macros).

**Comment by aloucks** [comment]
Today's plugin update (0.2.96.2122-191) fixes the issue when importing the crate with Rust 2015 syntax! 🎉 

One minor thing I noticed was that the associated constants are not sorted to the top of the auto-complete suggestions for the `bitflags!` defined structs.

**Comment by vlad20012** [comment]
> Today's plugin update (0.2.96.2122-191) fixes the issue when importing

Only if you enable the new macro expansion system =) Now waiting on #3628 :((
Also I'll try to support `#[macro_export(local_inner_macros)]` on this release cycle.

**Comment by aloucks** [comment]
@vlad20012 This seems to be broken now even when using the Rust 2015 syntax :( 

I'm also seeing some references to `bitflags!` generated structs as completely unresolved or they resolve but the associated constants aren't recognized.

Unfortunately, I hadn't updated my plugin in quite a while and I wasn't actively watching for this, so I don't know exactly which update caused the regression. I suspect #3750 was the culprit or a change after.

Current:

* **IntelliJ Rust plugin version:** 0.2.108.2148-192
* **Rust toolchain version:** 1.38.0 (625451e37 2019-09-23) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2019.2.4 Community Edition (IC-192.7142.36)
* **Operating system:** Windows 10 10.0
