### ISSUE TITLE
RsRenameProcessor shouldn't accept elements from other languages

### ISSUE THREAD

**Issue by undeadcat** [intellij-rust/intellij-rust#3614]
* **Intellij-Rust plugin version:** v0.2.95.2120-191
* **IDE name and version**: Intellij IDEA Ultimate 2019.1

RsRenameProcessor shouldn't accept elements from other languages [here](https://github.com/intellij-rust/intellij-rust/blob/1409910b8f28133bc1d03c0ca2bfda7ea9a6e48a/src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt#L18):
```
override fun canProcessElement(element: PsiElement): Boolean = element !is RsTupleFieldDecl
```

RenameProcessors should return true from `canProcessElement` only for elements that they can rename, otherwise chaos ensues. The platform picks the first available processor in `com.intellij.refactoring.rename.RenamePsiElementProcessor#forElement`.
Other processors can have language-specific logic like collecting implementors/inheriors for their language-specific elements.

Currently, having the rust plugin enabled causes invalid rename in JS because `com.intellij.lang.javascript.refactoring.JSDefaultRenameProcessor` has custom logic related to JS properties:

```js
//JS
const userId = 'john'; //rename 'userId here'
const response = { userId };
```
Expected:
```js
//JS
const johnId = 'john';
const response = { userId: johnId };
```

A user found that the problem is caused by the Rust plugin: https://jbs.zendesk.com/agent/tickets/2035133
A similar issue is not reproducible for me with Java-specific rename features, probably because processors from intellij-community are somehow ordered before plugins, but order between different plugins is not determined.

**Comment by fbecart** [comment]
I'm the happy user who initially reported the issue. Thanks for the quick reaction :1st_place_medal:
