### ISSUE TITLE
Local variable rename should detect name conflicts

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#3630]
If I rename some variable with a name that is already in the scope, I should be notified about it with dialog with "continue renaming" and "cancel" buttons
 
![Peek 2019-04-01 17-29](https://user-images.githubusercontent.com/3221931/55335428-ba174380-54a3-11e9-89bc-342dd24de082.gif)

**Comment by 1tgr** [comment]
I started seeing this popup after a recent plugin update (I'm now on version 0.3.134.3455-202).

Is there a way to turn it off, and accept the rename anyway? I'm comfortable to introduce shadowed identifiers into my Rust code, I would not consider if a conflict to have two variables in the same scope with the same name.

cc @Kobzol

**Comment by Kobzol** [comment]
@vlad20012 should we introduce an option to turn this off?

**Comment by 1tgr** [comment]
Or just a "Don't ask me again" box
