### ISSUE TITLE
Broken docs.rs links from cargo.toml

### ISSUE THREAD

**Issue by shavz** [intellij-rust/intellij-rust#3638]
## Environment

* **Intellij-Rust plugin version:v0.2.95.2120-191**
* **Rust toolchain version:1.16.0**
* **IDE name and version:Intellij IDEA Ultimate 2019.1**
* **Operating system:Mac OS Mojave**

## Problem description
Clicking the document gutter link in cargo.toml does not take you to the right url of the docs.rs page for the crate.

For example, if I add neon as a library, it takes me to `https://docs.rs/neon/0.2.0/neon/` however the right link is `https://docs.rs/crate/neon/0.2.0`

## Steps to reproduce

1. Add any crate.
2. Click the little three cube pyramid thing.
![image](https://user-images.githubusercontent.com/40373468/55451490-d5f32480-561e-11e9-96c2-cd1f46d3c313.png)

**Comment by lights0123** [comment]
That is because:
> docs.rs failed to build neon-0.2.0
Please check build logs and if you believe this is docs.rs' fault, report into this issue report.

So the correct path doesn't exist, because the docs did not build correctly. This would be the fault of the library author.

**Comment by shavz** [comment]
I see! Thank you for taking time to look at this
