### ISSUE TITLE
Client::connect detected from out of scope module

### ISSUE THREAD

**Issue by bh2smith** [intellij-rust/intellij-rust#3654]
## Environment

* **Intellij-Rust plugin version:** v0.2.95.2120-191
* **Rust toolchain version:** rustc 1.32.0 (9fda7c223 2019-01-16)
* **IDE name and version:** PyCharm 2019.1
* **Operating system:** MacOS 10.14.4

## Problem description

`Client::connect` is being detected as an HttpStream from a trait which is not in scope. 

https://github.com/hyperium/hyper/blob/796a7f3ba19791b6551e84bf6a1ea50b165b88f5/src/net.rs#L395-L411

We are trying to `use mongodb::connect`

![Screenshot 2019-04-05 at 1 59 18 PM](https://user-images.githubusercontent.com/11778116/55626219-36af6800-57ab-11e9-80ec-81d6a30fe033.png)

## Steps to reproduce

Here is the source where the error is appearing

https://github.com/gnosis/dex-services/blob/78691d601597176e1fcc3afc081644699151dcce/driver/src/db_interface.rs#L9-L41

**Comment by Kobzol** [comment]
Works with the latest version of the plugin.
