### ISSUE TITLE
Fix package name when suggesting version in Cargo.toml

### ISSUE THREAD

**Issue by Riateche** [intellij-rust/intellij-rust#3655]
If you write `env-logger = ` in `Cargo.toml`, the IDE will suggest the latest version of the `env_logger` crate. However, cargo won't accept this because the package name is written incorrectly (`env-logger`). I assume that the IDE knows the correct package name, since it's able to suggest its version. It would be nice if it could correct the package name as well.

An alternative solution would be to support auto-completion of package name. The IDE seems to attempt that, but it only suggests "env" and "benv", not "env-logger".

Relevant: #1778

**Comment by Kobzol** [comment]
Fixed by https://github.com/intellij-rust/intellij-rust/pull/6390.

**Comment by Undin** [comment]
Reopen because of https://github.com/intellij-rust/intellij-rust/issues/5908#issuecomment-744738226

**Comment by Kobzol** [comment]
This now works in stable.
