### ISSUE TITLE
Great performance degradation

### ISSUE THREAD

**Issue by e-oz** [intellij-rust/intellij-rust#367]
Please watch [attached video](https://github.com/intellij-rust/intellij-rust/files/245344/slow.mov.zip) to see how currently plugin works with file of 1854 lines. Latest version of nightly update, latest version of IDEA.

IntelliJ IDEA 2016.1
Build #IU-145.970, built on April 18, 2016
JRE: 1.8.0_76-release-b162 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
OS X 10.11.4,
MacBookPro11,1;Intel Core i5;2.4 GHz;8 GB.

Lowest CPU usage when I type: 107%.
I'm ready to send you content of source file by email - just let me know where to send (and please don't publish it).

**Comment by matklad** [comment]
You can send the file to `aleksey.kladov@gmail.com`

**Comment by e-oz** [comment]
done

**Comment by matklad** [comment]
fixed by https://github.com/intellij-rust/intellij-rust/commit/9970c82fb72d28b37ca434356cf4868880aec900

**Comment by e-oz** [comment]
Works awesome, thank you **very** much!
