### ISSUE TITLE
[feature suggestion]: auto-delete corresponding parenthesis

### ISSUE THREAD

**Issue by DjebbZ** [intellij-rust/intellij-rust#3677]
Hello,

I'm learning Rust using intellij-rust and found a minor annoyance that could be solved. This is a feature suggestion, not even a feature request, I'm humbly asking for your time and don't have the skills to contribute (Rust + Kotin + Intellij etc. are all foreign to me).

### Description

*Legend: `|` is the cursor.
When I type a `(` intellij-rust auto-insert the corresponding closing paren `)` so I end up with `(|)`. But if my cursor is inside empty parens `(|)` and I press Backspace to delete the opening parens, I end with a dangling closing parens `|)`.

### Proposed solution

Deleting an opening parens should automatically delete the corresponding closing parens:

`(|)` => `Backspace` => `|`

I've just checked: it works natively with IntellJ Ultimade when editing Java and JavaScript code. I don't know of IntelliJ Community but I suppose it's the same. I suppose it's possible to implement the feature in intellij-rust since it works for other languages.

Thanks in advance!

**Comment by ortem** [comment]
Hi @DjebbZ,

Does your problem occurs only in case of brackets `[]` somewhere before parentheses `()`? For example, in such code:
```Rust
fn foo() {
    let a = [];
    let b = 123;
    (|);
    let c = 42;
}
```

**Comment by DjebbZ** [comment]
Not sure I understand what you mean, but in the example you've just shown,
pressing BACKSPACE delete only the opening parenthesis, not both.

**Comment by ortem** [comment]
@DjebbZ IntelliJ Rust already supports brace matching and auto-deletion corresponding parentheses. So this issue relates to an existing bug, but not to new feature suggestion. This #3740 PR fixes your problem in case of brackets before parentheses (e.g. it fixes the case I showed above). The question is does it fixes your problem completely? I mean are there some other cases except brackets before parentheses?

**Comment by DjebbZ** [comment]
Sorry, "brackets before parentheses" is totally unclear to me. For me it means `[]()` but this is not what I'm talking about.

Basically what I'm saying is that for brackets, parentheses and the like I prefer the IDE to never allow me to be in an inconsistent state. Other examples:

``` rust
foo()|; // cursor between closing paren and column
```

Pressing BACKSPACE should not delete the closing paren but only move the cursor one character to the left, inside the empty parentheses. Pressing BACKSPACE a second time should delete both parentheses at the same time.

Is it clearer ?

PS: thank you for taking the time trying to understand the issue.

**Comment by ortem** [comment]
@DjebbZ 
> Pressing BACKSPACE should not delete the closing paren but only move the cursor one character to the left

This behavior is strange. The usual behavior is
1. `foo()|` --BACKSPACE--> `foo(`
2. `foo(|)` --BACKSPACE--> `foo`

The second case already works fine if there are no brackets in the code, for example
```Rust
fn foo() {
    let b = 123;
    bar(|);
    let c = 42;
}
```
but seems to fail in case of any brackets in the code before parens.

**Comment by DjebbZ** [comment]
I get your point about the "strangeness" of the behavior, it's the usual
way of working with Lisp-like language. By that I mean having always
balanced parentheses and similar signs.

I will test tomorrow with brackets before parentheses.

**Comment by ortem** [comment]
I think this issue is fixed. Please reopen it if brace deletion still be broken in the next IJ Rust release.
