### ISSUE TITLE
Items shown as deprecated even when deprecated only in a future version.

### ISSUE THREAD

**Issue by kolmogorov-fan-account** [intellij-rust/intellij-rust#3681]
## Environment

* **Intellij-Rust plugin version:** v0.2.96.2122-191
* **Rust toolchain version:** 1.33.0
* **IDE name and version:** CLion 2019.1
* **Operating system:** Windows 10

## Problem description

Functions are shown as deprecated even when they are only scheduled to be deprecated in a future version. This is a problem since that often means that there are no alternatives yet, especially when using stable Rust.

## Steps to reproduce

The following code demonstrate the issue.

```rust
fn main() {
    let _i: u8 = mem::zeroed();
}
```

The `mem::zeroed` function is declared with

```rust
#[rustc_deprecated(since = "2.0.0", reason = "use `mem::MaybeUninit::zeroed` instead")]
```

However, `mem::MaybeUninit` is not available on stable.

Thank you

**Comment by Undin** [comment]
cc @isamborskiy

**Comment by panstromek** [comment]
Not sure if this is a bad thing. I think there is some value in showing that the function will be deprecated. But probably showing some less "critical" warning for this case would be better...
