### ISSUE TITLE
Incorrect inspection on mismatched types in function

### ISSUE THREAD

**Issue by ELD** [intellij-rust/intellij-rust#3683]
## Environment

* **Intellij-Rust plugin version:** v0.2.96.2601-191-nightly
* **Rust toolchain version:** rustc 1.35.0-nightly (96d700f1b 2019-04-10)
* **IDE name and version:** CLion 2019.1
* **Operating system:** macOS 10.13

## Problem description
When writing a method to extract a `syn::Type` from another `syn::Type`, the type checker for the extension incorrectly infers the return type as a `&Type` instead of `Type`. The compiler accepts this input but the Intellij Rust plugin does not.

## Steps to reproduce

The following code snippet should result in the plugin displaying an error inspection:

```rust
fn get_type(syn_type: Type) -> Type {
    match syn_type {
        Type::Path(ref type_path) => {
            if type_path.path.segments[0].ident == "Option" {
                match type_path.path.segments[0].arguments {
                    PathArguments::AngleBracketed(ref angle_bracketed) => {
                        match angle_bracketed.args[0] {
                            GenericArgument::Type(ref arg_type) => arg_type.clone(),
                            _ => unreachable!(),
                        }
                    }
                    _ => unreachable!(),
                }
            } else {
                syn_type
            }
        }
        _ => unreachable!(),
    }
}
```

![image](https://user-images.githubusercontent.com/650044/55928129-d1a5a900-5bd4-11e9-87ea-d493673916a5.png)

**Comment by vlad20012** [comment]
`syn::Type` defined with attribute `#[cfg_attr(feature = "clone-impls", derive(Clone))]`. We don't support `cfg`-attributes for now. So, the plugin don't know that the type implements `Clone`. Then, you call `(&Type).clone()`, and it falling back to standard `impl Clone for &T` with `&T` return value, so at first arm you got `&Type` instead of `Type`.

**Comment by ELD** [comment]
@vlad20012 Ah, thanks for following up with an explanation.
