### ISSUE TITLE
Impl function fails to resolve with new macro expansion engine

### ISSUE THREAD

**Issue by ramosbugs** [intellij-rust/intellij-rust#3689]
First off, THANK YOU for the new macro expansion engine announced in https://intellij-rust.github.io/2019/04/10/changelog-96.html. This bug report is for a minor issue with the new engine, but overall it has significantly improved my development experience!

## Environment

* **Intellij-Rust plugin version:** 0.2.96.2122-191
* **Rust toolchain version:** cargo 1.34.0 (6789d8a0a 2019-04-01)
* **IDE name and version:** IntelliJ 2019.1 Community Edition
* **Operating system:** MacOS 10.14.1

## Problem description

After enabling the new macro expansion engine, IntelliJ was, for the first time, able to navigate to the macros where many of my functions are defined

For some reason, one of my function calls still fails to resolve: https://github.com/ramosbugs/oauth2-rs/blob/0d306c115f62c87453404d448540f8080f6165a9/tests/lib.rs#L80

The call site is as follows:
```rust
#[test]
fn test_code_verifier_challenge() {
    // Example from https://tools.ietf.org/html/rfc7636#appendix-B
    let code_verifier =
        PkceCodeVerifierS256::new("dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk".to_string());
    assert!(
        code_verifier.code_challenge().as_str() == "E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM"
    );
}
```

For the call to `code_verifier.code_challenge()`, IntelliJ isn't able to find the definition of `code_challenge`, which is defined in the macro expansion at: https://github.com/ramosbugs/oauth2-rs/blob/0d306c115f62c87453404d448540f8080f6165a9/src/lib.rs#L617

Note that IntelliJ is able to resolve `PkceCodeVerifierS256::new()`, which is part of the same macro expansion. It seems to be able to find all of the functions in that expansion except for `code_challenge()` and `authorize_url_params()`.

**Comment by vlad20012** [comment]
Looks like the problem is in `new` function - for some reason it's multiresolved to `PkceCodeVerifierS256::new` and `Digest::new`. Then, type of `verifier` isn't inferred and so `code_challenge` isn't resolved. Same with the test where `authorize_url_params` used. 

So this is a bug in name resolution. Minimal example:
```rust
struct S;
trait New1 { fn new(); }
impl New1 for S { fn new() {} }

trait New2 { fn new(); }
trait Bound {}
impl<T: Bound> New2 for T { fn new() {} }

fn main() {
    S::new(); // unresolved
}
```
