### ISSUE TITLE
MacroExpansionManager in misc.xml seems to have per-user settings

### ISSUE THREAD

**Issue by dsilvasc** [intellij-rust/intellij-rust#3692]
What steps will reproduce the issue?
Update to IntelliJ IDEA version 2019.1.1 with Scala plugin version 2019.1.7 and open a Scala project.

What is the expected result?
misc.xml should not contain per-user settings according to https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

What happens instead?
misc.xml has this:

```xml
  <component name="MacroExpansionManager">
    <option name="directoryName" value="rtaKaNvu" />
  </component>
```

**Comment by neandrake** [comment]
This causes modifications to misc.xml in non-rust projects. The plugin has to be disabled in order to prevent this file from constantly being modified in opened project. Would you consider issuing a patch with a fix for this issue without making it part of #3628?

**Comment by vlad20012** [comment]
Also we should not modify any XMLs in non-rust projects anyway
