### ISSUE TITLE
Rust code in macros is not syntax highlighted

### ISSUE THREAD

**Issue by dobrakmato** [intellij-rust/intellij-rust#3706]
## Environment

* **Intellij-Rust plugin version:** v0.2.96.2122-191
* **Rust toolchain version:** rustc 1.33.0 (2aa4c46cf 2019-02-28)
* **IDE name and version:** CLion 2019.1 Build #CL-191.6183.77, built on March 25, 2019
* **Operating system:** Windows 10 10.0

## Problem description
Passing a Rust code to declarative macro results in missing syntax highlighting and code completion. 

However when the code passed to the macro has syntax error in it (eg. unbalanced parentheses), the highlighting is back and it seems that the IDE has once again clue what the types are.

## Steps to reproduce

1. Create new project
2. Add https://docs.rs/compact_arena/0.2.1/compact_arena/ crate to project.
3. Write example code. 
4. `assert_eq` should be blue but actually is white.

![image](https://user-images.githubusercontent.com/779469/56085767-3ff2a180-5e49-11e9-88ee-968be2df0f41.png)

5. We create a syntax error and `assert_eq` is suddenly blue.

![image](https://user-images.githubusercontent.com/779469/56085777-5d277000-5e49-11e9-9259-a633b04c15ab.png)

**Comment by vlad20012** [comment]
We currently see a text inside macros as just a set of tokens. So we don't provide highlighting/errors/intentions/actions/etc inside it. 

I have a prototype implementation of highlighting inside macros. I'll continue to work on it after #3640 landing (some optimizations are needed there)
![image](https://user-images.githubusercontent.com/3221931/56091000-d78bda80-5eb1-11e9-9109-b88e78894d14.png)
![image](https://user-images.githubusercontent.com/3221931/56091002-df4b7f00-5eb1-11e9-9364-52fe39009808.png)

**Comment by netvl** [comment]
Are there any updates on this? #3640 seems to be merged quite some time ago.

**Comment by Undin** [comment]
@netvl see #4640

**Comment by netvl** [comment]
@Undin thanks! not sure how I missed it

**Comment by Nerixyz** [comment]
Any update on this issue? I think it's also the issue for the `rooted` macro in [mozjs](https://github.com/servo/rust-mozjs). It's correctly resolved with `org.rust.cargo.evaluate.build.scripts` enabled, but there's no syntax-highlighting: [screenshot](https://i.imgur.com/huoGUNl.png).
