### ISSUE TITLE
Macro with {pub mod} not recognized from outer scope

### ISSUE THREAD

**Issue by jirislav** [intellij-rust/intellij-rust#3710]
## Environment

* **Intellij-Rust plugin version: v0.2.96.2123-183**
* **Rust toolchain version: 1.34.0**
* **IDE name and version: CLion**
* **Operating system: Ubuntu**

Experimental engine for declarative macros enabled:
![obrazek](https://user-images.githubusercontent.com/7583416/56100660-e018fb00-5f1b-11e9-904c-055204bc7bb3.png)

## Problem description

[This macro usage](https://github.com/daboross/screeps-in-rust-via-wasm/blob/665a7b33936487108901ebe43ec1c0827801dab0/screeps-game-api/src/game.rs#L461-L489) will expand (using [this macro](https://github.com/daboross/screeps-in-rust-via-wasm/blob/665a7b33936487108901ebe43ec1c0827801dab0/screeps-game-api/src/macros.rs#L401-L434)) into the following:
```rust
// game.rs
pub mod spawns {
    ...
}
```
But the Rust plugin doesn't recognize the `spawns` module within the `game` module - example [here](https://github.com/daboross/screeps-starter-rust/blob/019fed609fa8b5cf57b15e3606908b62f59b91b3/src/main.rs#L48):
![obrazek](https://user-images.githubusercontent.com/7583416/56100628-6ed94800-5f1b-11e9-86e5-3d88024fb8b2.png)

Here the `spawns` isn't recognized by Rust plugin, but `rustc` compiles the program just fine.
Other modules are visible normally by the plugin.

<hr>

This is very annoying as there is neither completion, nor syntax highlighting when inside the for cycle above.

I can hack it so that the IDE knows the `values()` are of `Vec<objects::StructureSpawn>` type, but I think IDE should determine this by itself:
![obrazek](https://user-images.githubusercontent.com/7583416/56100594-04280c80-5f1b-11e9-9626-76f70e4bab70.png)

## Steps to reproduce

```bash
cd /tmp
git clone https://github.com/daboross/screeps-starter-rust.git
cd screeps-starter-rust
git checkout 019fed609fa8b5cf57b15e3606908b62f59b91b3
cargo install cargo-screeps
cargo install cargo-web
clion . # and see the src/main.rs#48
```

## Related issues
#3383

**Comment by vlad20012** [comment]
Yeah, we currently have a problems with expanding macros containing `///` docs, because they should be lowered to `#[docs = ""]` before macro expansion, what we don't currently do.
