### ISSUE TITLE
Regression in from resolve inference

### ISSUE THREAD

**Issue by la10736** [intellij-rust/intellij-rust#3717]
## Environment

* **Intellij-Rust plugin version:** 0.2.96.2122-191
* **Rust toolchain version:** rustc 1.33.0-beta.5 
* **IDE name and version:** IntelliJ 2019.1
* **Operating system:** Ubuntu 16.04

## Problem description

After last update plugin reports some new error related to the use of `From<_>` trait. Seams that use just the standard impl 
```rust
impl<T> From<T> for T {
    fn from(t: T) -> T { t }
}
```
to resolve it.

## Steps to reproduce

Unfortunately simple cases works like expected. But you can observe this behavior in https://github.com/la10736/rstest in `lib.rs`

**Comment by vlad20012** [comment]
I've tried the project with both old and new macro expansion engines and in both cases the only error I see is related to `Clone`: 
![image](https://user-images.githubusercontent.com/3221931/56195188-23b75600-603d-11e9-897f-a3f052ea1350.png)
So I can't reproduce. Maybe really you have more complex workspace? Also do you use `rustup override`?

**Comment by la10736** [comment]
Strange behavior... after a reboot this morning the issue is disappeared. I saw the same behavior  2 days ago at home: in this case it disappeared without reboot but just after an IntellJ restart and a `rustup update` in the middle.

So I cannot say how we can reproduce it now. 

The `clone()`'s issue is already tracked at #3593
