### ISSUE TITLE
Derive attribute with crate name is not processed properly

### ISSUE THREAD

**Issue by Riateche** [intellij-rust/intellij-rust#3721]
## Environment

* **Intellij-Rust plugin version:** v0.2.96.2598-191-nightly
* **Rust toolchain version:** stable
* **IDE name and version:** CLion 2019.1
* **Operating system:** Linux

## Problem description
The IDE doesn't seem to understand derive attributes with crate names.

## Steps to reproduce
Add `serde_derive` dependency and input the following code:
```rust
#[derive(Clone, serde_derive::Serialize)]
pub struct A(u32);

fn main() {
    let a = &A(0);
    let _b: A = a.clone();
}
```
This produces E0308:
![1](https://user-images.githubusercontent.com/1740713/56224522-6a767180-6078-11e9-976f-a65ac3550766.png)

I assume that this is because the IDE didn't pick up the derived `Clone` implementation.

**Comment by Kobzol** [comment]
Works in the latest version of the plugin.
