### ISSUE TITLE
Incorrect formatting of curly-braced macro call

### ISSUE THREAD

**Issue by fan-tom** [intellij-rust/intellij-rust#3741]
## Environment

* **Intellij-Rust plugin version:**
v0.2.96.2122-191
* **IDE name and version:**
WebStorm 2019.1.1
Build #WS-191.6707.60, built on April 16, 2019
Licensed to Mushfiqur Rahman
Subscription is active until April 8, 2020
JRE: 1.8.0_202-release-1483-b44 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4

## Problem description
Plugin incorrectly formats macro invocation with curly braces
<img width="168" alt="изображение" src="https://user-images.githubusercontent.com/14140464/56473720-9040b380-6488-11e9-9b45-b26c86b02a9b.png">
Cmd+Alt+L
<img width="173" alt="изображение" src="https://user-images.githubusercontent.com/14140464/56473730-a9496480-6488-11e9-8ffc-d241ed7606da.png">
As we can see, reformatting inserts additional space berween macro name and argument braces, that doesn't happen when parentheses or square brackets are used

**Comment by vlad20012** [comment]
Hmm, what rustfmt think about it? As for me, space before `{` is expected

**Comment by fan-tom** [comment]
@vlad20012, fustfmt agree with you, closing
