### ISSUE TITLE
Feature Request (lazy_static field detection)

### ISSUE THREAD

**Issue by tbraun96** [intellij-rust/intellij-rust#3742]
I really enjoy the intelliJ IDE for Rust. It is getting close to being perfect! I would find it REALLY helpful to allow the checker and highlighter to detect fields in lazy_static! { } blocks. I have fields therein with "pub static ref"  and nothing shows up when I search the mod::. Thank you for everything,

Thomas Braun

**Comment by vlad20012** [comment]
Hmm, out plugin should recognize definitions from `lazy_static`  by default, so please, provide more details of your specific case. You can also try to enable the new macro expansion engine (follow instructions in #3628).
