### ISSUE TITLE
Plugin fails to resolve workspace member with absolute path

### ISSUE THREAD

**Issue by cfeitong** [intellij-rust/intellij-rust#3746]
## Environment

* **Intellij-Rust plugin version: v0.2.96.2122-191**
* **Rust toolchain version:  1.33.0-nightly**
* **IDE name and version: clion 2019.1.2**
* **Operating system: macOS 10.14.4**

## Problem description
Create a workspace with two members and reference one from another with absolute path. 
Though it is not regard as an error, going to definition, finding reference and code completion don't work.

## Steps to reproduce
[https://github.com/cfeitong/intellij-rust-workspace-error](https://github.com/cfeitong/intellij-rust-workspace-error)

**Comment by Kobzol** [comment]
Do you have the second package in dependencies in `Cargo.toml`? You should add it as a dependency with a local path, for example:
```[toml]
[dependencies]
second_crate_in_workspace = { path = "../second_crate_in_workspace" }
```
In this way it works for me.

**Comment by cfeitong** [comment]
> Do you have the second package in dependencies in `Cargo.toml`?

Yes. Without dependency declaration in `Cargo.toml`, it won't compile. In my case `cargo build` works fine, but the plugin doesn't

**Comment by Undin** [comment]
Works for me so I suppose it can be closed.
@cfeitong could you check it with the latest plugin version to ensure that it works for you as well?

**Comment by pront** [comment]
This is still happening on macOS + rustc 1.71.0 (8ede3aae2 2023-07-12)
