### ISSUE TITLE
Bad parsing of empty brace-structs with comment

### ISSUE THREAD

**Issue by jajakobyly** [intellij-rust/intellij-rust#375]
Following snippet:
```rust
struct Foo { /* comment */ }

fn main() {
}
```
Produces following parser error:
![java_2016-05-05_17-51-06](https://cloud.githubusercontent.com/assets/3450050/15048494/1f1fef4c-12ea-11e6-8b14-6ecdef0b41d7.png)

[rustc has no objects](http://is.gd/sXbuoZ)

**Comment by matklad** [comment]
Yep, this is a recent change in rust. Before, only `struct Foo;` was allowed.
