### ISSUE TITLE
Cargo project update failed

### ISSUE THREAD

**Issue by WEBhicham** [intellij-rust/intellij-rust#3756]
## Environment

* **Intellij-Rust plugin version:**
v0.2.97.2123-191
* **Rust toolchain version:**
1.34
* **IDE name and version:**
Clion 2019.1.2
* **Operating system:**
Windows 10 pro
## Problem description
When starting Clion I get the following error:

```
Cargo project update failed:
Execution failed (exit code 101).
C:/Users/hicha/.cargo/bin/cargo.exe metadata --verbose --format-version 1 --all-features -Zoffline
stdout : error: the `-Z` flag is only accepted on the nightly channel of Cargo
```

## Steps to reproduce
I realy don't know.

**Comment by Undin** [comment]
@WEBhicham Disable `Preferences | Languages & Frameworks | Rust | Cargo | Offline mode` option or use nightly compiler

**Comment by WEBhicham** [comment]
That worked, Thx for the fast response!
