### ISSUE TITLE
Enhancement: Hyperlink curly brackets please

### ISSUE THREAD

**Issue by gilescope** [intellij-rust/intellij-rust#3784]
Would be super-awesome if brackets { (maybe other types of brackets too?) were hyperlinked to their pair so you could ctrl-click on them and you'd go to the matching bracket.

If people really like it you could bake it in to all your IDEs.

**Comment by mibac138** [comment]
You can already go to a matching brace using <kbd>Ctrl</kbd> + <kbd>[</kbd> and <kbd>Ctrl</kbd> + <kbd>]</kbd>. You can also change the keyboard shortcut by changing it in the keymap setting "Move Caret to Code Block Start/End"

**Comment by panstromek** [comment]
`ctrl+shift+m` does the same thing for all types of parens ;)

**Comment by Undin** [comment]
I think it can be closed due to this feature already exists in the platform (i.e works in IntelliJ Rust too) for all type of brackets
