### ISSUE TITLE
Traits from transitive dependencies incorrectly show up in completion

### ISSUE THREAD

**Issue by Riateche** [intellij-rust/intellij-rust#3798]
## Environment

* **Intellij-Rust plugin version:** v0.2.98.2618-191-nightly
* **Rust toolchain version:** stable
* **IDE name and version:** CLion 2019.1.2
* **Operating system:** Linux

## Problem description

The IDE suggests traits that are not actually available in the current context. It seems that it happens when these traits are available in dependencies.

## Steps to reproduce
```rust
fn main() {
    std::iter::once(()).colle
}
```
When there are no dependencies, it correctly suggests `collect` and nothing else. But if I add `mdbook = "0.2.3"` to `Cargo.toml`, it starts suggesting `collect_vec` and `collect_tuple` from `itertools` because `mdbook` depends on `itertools`. If I accept the suggestion, the code will not compile because I can't import `itertools` (it's not a direct dependency of the current crate).

**Comment by Undin** [comment]
Fixed by #9945
