### ISSUE TITLE
Cannot find declaration if declared with `pub use`

### ISSUE THREAD

**Issue by kluen** [intellij-rust/intellij-rust#3801]
## Environment

* **Intellij-Rust plugin version:** v0.2.97.2123-191
* **Rust toolchain version:** 1.34.0
* **IDE name and version:** IntelliJ IDEA 2019.1.1 (Community Edition)
Build #IC-191.6707.61, built on April 16, 2019
JRE: 1.8.0_202-release-1483-b44 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* **Operating system:** macOS 10.14

## Problem description
A function declared with `pub use` cannot be resolved from outside the module:

<img width="259" alt="Bildschirmfoto 2019-05-06 um 16 17 58" src="https://user-images.githubusercontent.com/13871367/57231382-b3d43400-701a-11e9-8566-17ed850e086d.png">

## Steps to reproduce
`main.rs`:
```
mod foo {
    pub use bar::baz;

    mod bar {
        pub fn baz() {}
    }
}

fn main() {
    crate::foo::baz();
}
```

**Comment by vlad20012** [comment]
Should be fixed with #3768
