### ISSUE TITLE
Add option to use IDE default toolchain rather than set per project

### ISSUE THREAD

**Issue by cormacc** [intellij-rust/intellij-rust#381]
I'm working on a project on Linux and Windows, and have to reconfigure the project rust path every time I switch back and forth. Would be useful to be able to configure the project to use the IDE default rust path.
Could be that the option is already there right under my nose, mind you -- wouldn't be the first time :)

**Comment by matklad** [comment]
Can you explain your use case a bit more please? Per projects settings are stored in the `.idea` directory inside the project (toolchain settings are in `.idea/misc.xml`). If you don not share this folder between Windows and Linux project, then each can have its own settings.

**Comment by cormacc** [comment]
Sure -- don't place the .idea directory under source control, but for my windows work I'm usually running windows on a vm accessing the same dev tree as I'm using on the linux host, so implicitly sharing the same project folder. Sometimes also switch back and forth between a windows laptop with a dev tree synched to my main linux dev machine, with similar results. Though these may well be fringe/corner cases -- think I can tell dropbox not to sync the .idea directory, but don't think there's an analogue when using virtual box shared folders.

**Comment by matklad** [comment]
Ah, so the core problem here is sharing `.idea` folder between a Windows and a Linux machine... While it is possible to share some parts of `.idea`, folder, sharing it entirely is not supported ([docs](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems)).

I think that one day we will implement a more feature rich toolchain management: in particular, there will be a global set of toolchains, and you will be storing only the name of the toolchain in the project config. The path to the toolchain will be stored in global IDE settings. However this probably won't happen in the nearest future, and I am absolutely unsure about the design (and there is rustup coming), so I'll close this issue for now. 

So I would advice to use ignored folders in Git/Dropbox. I don't know what is the right solution for VirtualBox, but I think that you don't actually want to run the IDE in the virtual machine: it will be slower. Instead, you can edit the code in the IDE running in the host, and only `cargo run` it from virtual box (And be careful about `target` directory, I am not sure that `cargo` is prepared that it can contain artifacts build with other OS).
