### ISSUE TITLE
assert_eq! diff can lead to confusion 

### ISSUE THREAD

**Issue by marcoesposito1988** [intellij-rust/intellij-rust#3814]
First of all, thanks for creating this plugin! It makes working with Rust a breeze.

The PR #3465 introduced nice error messages for showing the result of unit tests. The problem is that it assumes that the left argument as "expected" and the right one as "actual" (in my opinion correctly, in accordance to the most popular convention).

Unfortunately, not only such convention is not mentioned in the Rust docs, but the same rust docs consistently reverse the arguments 🤦‍♂ 

In order to avoid confusion, I think it would make sense to change "expected" and "actual" to "left" and "right". Highlighting the assert_eq! call site next to the message with the value of the arguments should also help users in their heroic pursuit to determine what is what.

**Comment by vlad20012** [comment]
Sounds reasonable

**Comment by Undin** [comment]
As mentioned [here](https://github.com/intellij-rust/intellij-rust/pull/3821#pullrequestreview-236416190) the platform doesn't have API to rename the corresponding labels. I've filed [issue](https://youtrack.jetbrains.com/issue/IDEA-214459) in IDEA tracker about it.
To make diff message less confusing I've swapped expected and actual values in #3848
