### ISSUE TITLE
Can't build: All files are up-to-date

### ISSUE THREAD

**Issue by Riateche** [intellij-rust/intellij-rust#382]
Build was suddenly broken for me after some update. When I select "Make project", IDEA says "All files are up-to-date" and does nothing. 

I tried to:
- close project and delete ".idea" folder from project folder;
- import project as described in Quick Start;
- set SDK for the project (1.8 stable);
- Refresh Cargo project and Invalidate caches/Restart

Nothing seems to help. Can I do something to debug the issue?

**Comment by matklad** [comment]
We no longer use `make project` to build cargo project. We decided to do so because only run configuration knows the set of flags which affect how the project is build. 

So, instead of `make project`, just create a run configuration which executes `cargo build` command. Does this help?

**Comment by Riateche** [comment]
Run configuration is not a perfect workaround. Make command produces nice looking compile error table when there are any errors, while run command only produces text log.

**Comment by matklad** [comment]
Yeah, we need to work on presenting errors better. The problem with make is that it was just executes `cargo build`. So, if in your run configuration you had `--release` flag then the project got build twice. And no tests were build at all. 

Please note that now we hyperlink errors in `cargo run` output. You can use `Cltl+Alt+Up/Down` shortcut to navigate to next/previous error.

**Comment by NeoWu95** [comment]
@matklad Do you solve this problem now? I meet this problem today when I build artifact in IDEA.

**Comment by NeoWu95** [comment]
@Riateche Do you solve this problem now? I meet this problem today when I build artifact in IDEA.

**Comment by cosmo2021** [comment]
i have the same problem like that
