### ISSUE TITLE
Cargo uses incorrect path (multirust)

### ISSUE THREAD

**Issue by Riateche** [intellij-rust/intellij-rust#383]
IDEA uses invalid paths for some internal cargo directories when I use "Run" option. 

Toolchain root is set to /home/ri/.multirust/toolchains/stable/bin.
Project SDK path is /home/ri/.multirust/toolchains/stable.

I've added a custom Cargo command with settings:
Command: build
Additional arguments: -v

Cargo output in IDEA looks like: 

> /home/ri/.multirust/toolchains/stable/bin/cargo build -v
> Compiling utf8-ranges v0.1.3
>      Running `rustc /home/ri/.cargo/registry/src/github.com-88ac128001ac3a9a/utf8-ranges-0.1.3/src/lib.rs --crate-name utf8_ranges --crate-type lib -g -C metadata=afda04de2a52d0c6 -C extra-filename=-afda04de2a52d0c6 --out-dir /home/ri/rust/rust_qt/repo/qt_wrapper_generator/target/debug/deps --emit=dep-info,link -L dependency=/home/ri/rust/rust_qt/repo/qt_wrapper_generator/target/debug/deps -L dependency=/home/ri/rust/rust_qt/repo/qt_wrapper_generator/target/debug/deps --cap-lints allow`

When running from terminal, cargo output is different:

>    Compiling utf8-ranges v0.1.3
>      Running `rustc /home/ri/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/utf8-ranges-0.1.3/src/lib.rs --crate-name utf8_ranges --crate-type lib -g -C metadata=afda04de2a52d0c6 -C extra-filename=-afda04de2a52d0c6 --out-dir /home/ri/rust/rust_qt/repo/qt_wrapper_generator/target/debug/deps --emit=dep-info,link -L dependency=/home/ri/rust/rust_qt/repo/qt_wrapper_generator/target/debug/deps -L dependency=/home/ri/rust/rust_qt/repo/qt_wrapper_generator/target/debug/deps --cap-lints allow`
> 

So, cargo should use `/home/ri/.multirust/toolchains/stable/cargo/registry` instead of `/home/ri/.cargo/registry`. This issue causes cargo to rebuild all dependencies whenever I switch between terminal and IDEA, which is highly inconvenient.

**Comment by matklad** [comment]
Yes, we should not use path to the particular toolchain as a toolchain root. Instead, we must use multirust wrapper scripts and set `MULTIRUST_TOOLCHAIN` env variable: https://internals.rust-lang.org/t/multirust-rs-integration-with-tools/3293/12. 

So, the workaround is to use path to the multirust wrapper as a path to the toolchain. It is `~/.cargo/bin` if you use rustup (aka multirust-rs) and I think it is `/usr/bin` if you use multirust. 

I'll change toolchain path suggesting function such that it does not suggests paths from `./multirust/toolchains` directly. Proper toolchain version management from within IDE will be implemented as a part of https://github.com/intellij-rust/intellij-rust/issues/308

**Comment by Riateche** [comment]
How can I change toolchain root for existing project?

**Comment by matklad** [comment]
Settings > Languages & Frameworks > Rust.

Should look like this:

![Toolchian](https://cloud.githubusercontent.com/assets/1711539/14491097/85f717d0-017f-11e6-98d6-0f60ee0e2016.png)

**Comment by Riateche** [comment]
Thanks, setting toolchain path to "/usr/local/bin" seems to help. 

For some reason IDEA can't find this settings page using "toolchain" keyword.

**Comment by matklad** [comment]
https://github.com/intellij-rust/intellij-rust/issues/384
