### ISSUE TITLE
Cannot find declaration of BTreeMap and BTreeSet

### ISSUE THREAD

**Issue by hackerer1c** [intellij-rust/intellij-rust#3835]
## Environment

* **IntelliJ-Rust plugin version: 0.2.98.2632-191-nightly**
* **Rust toolchain version: 1.34.0 (91856ed52 2019-04-10)**
* **IDE name and version: CLion 2019.1.3**
* **Operating system: macOS 10.14.4**

## Problem description

```rust
use std::collections::{BTreeMap, BTreeSet};
//                     ^         ^
//                   'Cannot find declaration to go to'
```

## Steps to reproduce

Type `use std::collections::{BTreeMap, BTreeSet}` and click `BTreeMap` and `BTreeSet` with cmd/ctrl key down.

**Comment by hackerer1c** [comment]
I have tried nightly IntelliJ Rust (which should be with [#3768](https://github.com/intellij-rust/intellij-rust/pull/3768)), but no better...
...so I ended up adding some `self` to Rust source code to temporarily and partially fix this bug.

**Comment by vlad20012** [comment]
It's because we didn't moved std edition to 2018. I hope we'll fix it until the next release
