### ISSUE TITLE
Restore the ability to run `cargo check` as the build command

### ISSUE THREAD

**Issue by abreis** [intellij-rust/intellij-rust#3842]
The ability to use `cargo check` when building a project was removed in #3510, I'm assuming because we can now pick `cargo check` as the external linter.

I have not found this to be a good substitute, because I cannot get a tool window with a list of all linter issues project-wise (the way one gets when running `build project`). 

Furthermore, I find `cargo check` to be too intensive to be running on-the-fly for large projects.

Please consider restoring the ability to run `cargo check` manually and seeing the output in a tool window. Thank you.

**Comment by abreis** [comment]
I solved the issue by adding a custom Run configuration that calls `cargo check`.

**Comment by mchernyavsky** [comment]
You also can run external linter manually in cargo toolwindow:
![image](https://user-images.githubusercontent.com/6079006/57755648-13f16700-76fa-11e9-83dd-0f090200d0e7.png)
And we have special action to run linter (you can add a shortcut for it):
![image](https://user-images.githubusercontent.com/6079006/57755840-8d895500-76fa-11e9-96d9-aec1294af4e4.png)

**Comment by abreis** [comment]
@mchernyavsky I tried that but got this error:

![jdkerr](https://user-images.githubusercontent.com/95046/57766708-c37d0800-76ff-11e9-896e-4d114b1f56b6.png)

Is it just a misconfiguration or should I report a bug?

**Comment by mchernyavsky** [comment]
@abreis Yes, report a bug, please. You can configure JDK for your project and it should fix the problem, but I think we shouldn't use Java modules in project model.

**Comment by mchernyavsky** [comment]
Oops, we already have "Rust module" :)
![image](https://user-images.githubusercontent.com/6079006/57773816-93466100-7721-11e9-9782-e3082c53f43c.png)
Please, check your module type in `File > Project Structure > Project Settings > Modules`.

**Comment by abreis** [comment]
Yep, that works. I'm guessing this happened because this project was created a long time ago. Thanks!
