### ISSUE TITLE
Auto Completion not working for Iterator (0..n)

### ISSUE THREAD

**Issue by ShinduHub** [intellij-rust/intellij-rust#3859]
## Environment

* **Intellij-Rust plugin version:** v0.2.97.2123-191
* **Rust toolchain version:** 1.34.0 (91856ed52 2019-04-10)
* **IDE name and version:** Intellij IDEA Community 2019.1.2(JBR8)
* **Operating system:** Windows 10 1809 (Build 17763.475)

## Problem description
Autocompletion not showing ```sum()``` function for an Iterator (After ```(0..n).```)

## Steps to reproduce

```rust
fn main() {
    println!("{}", sum(10));
}

pub fn sum(n: i64) -> i64{
    (0..n).sum()
}
```

**Comment by vlad20012** [comment]
Just enable new macro expansion engine as described in #3628

**Comment by ShinduHub** [comment]
Thanks!
