### ISSUE TITLE
Quick Navigate popup shows preceding comments

### ISSUE THREAD

**Issue by Furyhunter** [intellij-rust/intellij-rust#389]
The function declaration should be shown, but due to the way `RustDocumentationProvider#RustFnItem.formatSignature()` is implemented (it assumes visibility will be the first child element) it includes the edge-bound doc comments and outer attributes.

![image](https://cloud.githubusercontent.com/assets/141511/15208291/5e1f0a92-17f0-11e6-861c-69ed615420d2.png)

[Relevant function](https://github.com/intellij-rust/intellij-rust/blob/8282cb8de7be4f2394eb29ad226823b77ccd1610/src/main/kotlin/org/rust/ide/documentation/RustDocumentationProvider.kt#L30-L40)

**Comment by matklad** [comment]
Good catch!
