### ISSUE TITLE
Please do not display "Preparing parameter info..." popup window

### ISSUE THREAD

**Issue by e-oz** [intellij-rust/intellij-rust#3900]
Or let me know how to turn this feature off.
It's extremely annoying, it eats my keypresses and doesn't let me use your wonderful plugin.

toolchain 1.36.0
plugin 0.2.98.2124-191
idea IC-191.7141.44
macOS

**Comment by vlad20012** [comment]
This popup was added in #3834. It is displayed during preparing a parameter info which blocks the UI. It means that analysis is just too slow in your case, and if we will not show the "preparing" popup, your UI will be blocked anyway during the preparing. But you can simply disable "parameter info" feature in `Settings | Editor | General | Code completion | Show the parameter info popup`.
![image](https://user-images.githubusercontent.com/3221931/58353418-20eb2480-7e77-11e9-8358-57526931cb76.png)

Parameter info popup is a something like this:
![image](https://user-images.githubusercontent.com/3221931/58354005-c9e64f00-7e78-11e9-8790-3ed9cc04f384.png)

**Comment by e-oz** [comment]
Thank you very much, @vlad20012 , it solved my issue!

**Comment by mvlabat** [comment]
@vlad20012, can we control displaying the "Preparing parameter info..." window itself? I don't mind my IDE freezing for a little bit, the window annoys me much more. I don't want it to be shown even if I manually press `CTRL+P` for displaying the popup.
Thank you

**Comment by mvlabat** [comment]
Another argument against the window is that it blocks typing the code. While the UI is just frozen (without the modal window) it at least doesn't block the keyboard input, but now I can't continue writing the code, and it's extremely irritating. I wish there was an option to disable the window without disabling the parameters popup.

**Comment by e-oz** [comment]
Sorry, but looks like I was too fast to close it.
I turned off all related options but this window still appears sometimes and even when I don't see it - some symbols are typed into the void, and in such moments I want to kill somebody.
<img width="423" alt="Screenshot 2019-05-28 at 15 56 33" src="https://user-images.githubusercontent.com/526352/58484117-c47f5200-8161-11e9-8721-dfd97d1ec367.png">
I'll have to downgrade plugin version (impossible to use this version), please let me know when it will be fixed.

**Comment by mvlabat** [comment]
@e-oz, yeah, that's right, because the proposed solution doesn't disable the window itself, but disables the parameters popup (that's what we see above the function, when we press `CTRL+P`, for instance). You still may see the window when you trigger that popup manually.

I vote for reverting #3834 completely, as it doesn't fix UI freezes, but only makes experience worse with blocking keyboard input.

**Comment by Undin** [comment]
New version with #3917 fix is already published
@e-oz @mvlabat Could you please check that everything ok for you with the latest version?

**Comment by mvlabat** [comment]
Haven't got a chance to test it extensively, but it seems to work much better than it did, at least in the place where it froze my UI for 2-3 seconds. I don't notice any freezes now!
@vlad20012 @Undin Thanks a lot for the great job!

**Comment by e-oz** [comment]
Zero issues, 0 symbols lost while typing. Also, cmd+p (method signature tooltip) is blazing fast now (not sure if it's related).
Thank you very much for your work on this issue. Best Rust plugin everr!
