### ISSUE TITLE
Missing 'Create method'

### ISSUE THREAD

**Issue by svenschmidt75** [intellij-rust/intellij-rust#3904]
## Environment

* **Intellij-Rust plugin version:** 0.2.98.2125-192
* **Rust toolchain version:** stable-x86_64-unknown-linux-gnu (default)
rustc 1.35.0 (3c235d560 2019-05-20)

* **IDE name and version:** CLion 2019.2 EAP
* **Operating system:** PopOs 18.04

## Problem description
Say you have this code

```rust
fn load_image_file(path: &str) -> Result<Vec<Image>> {
    let mut file = File::open(&Path::new(path))?;
    let mut buffer = Vec::<u8>::new();
    let number = file.read_to_end(&mut buffer);
    let images = parse_image_data(buffer)?;
    Ok(images)
}
```

Place the cursor on parse_image_data on the 2nd last line.
There is no way to create a method stub. I think it would be
helpful if the plugin could generate code
```rust
fn parse_image_data(buffer: &mut Vec<u8>) -> Result<Vec<Image>> { }
```

**Comment by fan-tom** [comment]
I often encounter the same pattern when develop top-to-bottom and just invent method/function on the fly and then want IDE to generate that missing functions for me with signatures based on their calls
