### ISSUE TITLE
Disable sintax highlighting in docs

### ISSUE THREAD

**Issue by serega** [intellij-rust/intellij-rust#3909]
## Problem description
Is there a way to disable syntax highlighting of rust code in code fences?  I find it hard to visually separate the actual code from the examples in comments in the files with heavy documentation.  I would rather have the code in comments to be highlighted as comment.

**Comment by aloucks** [comment]
It would also be interesting if the syntax coloring could remain but have the colors desaturated so that the code appears muted inside the comment.

**Comment by vlad20012** [comment]
> Is there a way to disable syntax highlighting of rust code in code fences?

Yes! Just uncheck `Settings | Languages & Frameworks | Rust | Inject Rust language into documentation comments`:

![image](https://user-images.githubusercontent.com/3221931/58386032-a64f1000-8002-11e9-9d75-52d205e622fa.png)

Also you can change the text style of such injected code fragments. Maybe you can find one that suits you. Check out `Settings | Editor | Color Scheme | General | Code | Injected language fragment`

![image](https://user-images.githubusercontent.com/3221931/58386078-5886d780-8003-11e9-9175-caffb2016331.png)

(For my scheme (Darcula) by default it has background `#364135` (green))

**Comment by serega** [comment]
Thanks.  This checkbox removes the background color - great, but the syntax highlighting is still there. I understand that this seems like a cool feature, but it results in too much noise that is hard to read.  I prefer boring grey comments without any special highlighting, like in original Intellij IDEA for Java.  Note, that the foreground checkbox has effect on Rust language, because it seems like the implementation of the syntax highlighting in comments takes over. I think the code highlighting inside the comment block should be configurable. It could be one of the "Effects", like 'syntax highlight' effect.

**Comment by Undin** [comment]
@serega as @vlad20012 already [mentioned](https://github.com/intellij-rust/intellij-rust/issues/3909#issuecomment-496024189) you can disable it via `Settings | Languages & Frameworks | Rust | Inject Rust language into documentation comments` option

**Comment by blueglyph** [comment]
In some projects, it doesn't work for some reason. The code is correct, compiles and run, the option is enabled, but the code in `///` comments is not highlighted. If I copy/paste it to another project in which code highlighting works, the same comment is correctly highlighted.

Any idea if that's related to a per-project handling of this option?

**Comment by vlad20012** [comment]
@blueglyph, it's absolutely expected behavior. You can't have a doctest in a `main.rs` and IntelliJ Rust highlights only doctests, not an arbitrary code in doc comments.
