### ISSUE TITLE
Use `RustOuterAttributeOwner` in `DocumentaionProvider`

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#391]
This is a follow up of #370, which was implemented only for top level items. Now as https://github.com/intellij-rust/intellij-rust/commit/0c9a1f704db6c9d9d5193cded2d1fe9ad29642da has landed, it is possible to implement doc provider for more different things, like enum variants and methods.

@Furyhunter you might be interested in this.

**Comment by Furyhunter** [comment]
This issue also needs (currently nonexistent) `RustInnerAttributeOwner` on appropriate elements (I believe these are impl method members, trait members, functions, modules, and files) before it can fully replace the current implementation.

Inner attributes and doc comments are already attached to elements in PSI.

**Comment by matklad** [comment]
I think we can just omit inner attributes/comments for the moment: looks like mos of the documentation is done via outer doc comments.

**Comment by jajakobyly** [comment]
Mod files have docs in inner attrs

**Comment by matklad** [comment]
Indeed, this is a big use case. Will try to add `InnerAttributeOwner` shortly. The thing that bothers me is that Inner attributes are withing the node which is a descendant of the documented node.

That is, outer attributes are always children, but inner attributes can be grand children. 

Not that this is bad, but just something to be aware of.

**Comment by jajakobyly** [comment]
Introducing some kind of method like `val owner` for attributes might be useful

**Comment by matklad** [comment]
Here you are: https://github.com/intellij-rust/intellij-rust/commit/f6f821987eee5c6d36d7189292cfba6f118ba72c

**Comment by matklad** [comment]
Probably should also revise this guy: https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RustItemImplMixin.kt#L34

**Comment by matklad** [comment]
Would be great if somebody reviewed this [two](https://github.com/intellij-rust/intellij-rust/commit/ec35e1ab9221252e79853df235eb506ffdf7d938) [commits](https://github.com/intellij-rust/intellij-rust/commit/1420eb41062193ed58d931554cc4b9d4d8a9362f), I am not really happy with the design. Perhaps, we should use one interface with default impls for both inner and outer things, like

```
interface RustAttributeOwner {
    val outerAttrbutes: List<RustOuterAttribute> = emptyList()
    val innerAttrbutes: List<RustInnerAttribute> = emptyList()
}
```

However, default methods in interfaces don't quite work with Java classes yet: https://youtrack.jetbrains.com/issue/KT-9073
