### ISSUE TITLE
Wrong doctest highlighting in lazy_static

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#3910]
## Environment

* **Intellij-Rust plugin version:** v0.2.99.2645-191-nightly
* **Rust toolchain version:** rustc 1.35.0 (3c235d560 2019-05-20)
* **IDE name and version:** IU-191.7141.44
* **Operating system:** macOS 10.13.6 

## Problem description
![image](https://user-images.githubusercontent.com/2539310/58416680-0db0a280-808b-11e9-9396-3670a10f055c.png)

## Steps to reproduce
Open `lib.rs` of `lazy_static = "1.3.0"`

**Comment by vlad20012** [comment]
Should be fixed by #3797
