### ISSUE TITLE
Help - CLion thinks the project is CMake

### ISSUE THREAD

**Issue by mouse07410** [intellij-rust/intellij-rust#3916]
CLion needs to understand that Rust, Python and a few other languages that it supports do **not** require or use `CMakeLists.txt` file.

*Seems related to #631. Guys, in **three years** it should be possible to fix this...?*

## Environment

* **Intellij-Rust plugin version:** `v0.2.98.2124-191`
* **Rust toolchain version:** `stable-x86_64-apple-darwin (default) rustc 1.35.0 (3c235d560 2019-05-20)`
* **IDE name and version:** CLion 2019.1.3
* **Operating system:** MacOS Mojave 10.14.5

## Problem description

CLion erroneously demands `CMakeLists.txt` file, and complains that it isn't present in a Rust project (!)

![Rust-project-as-CMake](https://user-images.githubusercontent.com/5923577/58509790-5ccb0600-8165-11e9-9631-a81ef351f86d.png)

## Steps to reproduce

Create or open a Rust project

**Comment by vlad20012** [comment]
CLion understand rust without problems, you just need to open the project correctly. Just use **Open** button instead of "import" or anything else:
![image](https://user-images.githubusercontent.com/3221931/58546432-006ff100-820e-11e9-9b2c-db23379bad13.png)
Or `File | Open`.

If you already have a broken project that requires CMake, close it, delete `*impl` and `.idea` files and then open it as described

**Comment by mouse07410** [comment]
Thank you!! Deleting the `.idea/` directory (found no `*impl` files), and opening the way you showed, resolved the problem.

I'm still confused how this project became broken, as I think I always opened it like this (but it was not created by CLion originally). Regardless, your recommendation solved this problem.

**Comment by ralucado** [comment]
In my case I was opening it correctly but my project had botha  cargo.toml and a CmakeLists.txt file. When opening it a small window appears saying the project has two configurations, but it was sized badly and the option for Cargo was not visible, leading me to open it as cmake and breaking it. I managed to find out that i had to resize the window to see all the options but that is not very friendly behaviour in the first place.
