### ISSUE TITLE
Feature Request: Ability to provide custom gdb pretty printer/formatter

### ISSUE THREAD

**Issue by fredpointzero** [intellij-rust/intellij-rust#3923]
Hi, it would be nice to be able to provide custom pretty printer for gdb when developping a crate.

Do you think this is something possible ?

**Comment by ortem** [comment]
Hi @fredpointzero,

To add new pretty-printers locally, you can edit bundled pretty-printers as described [here](https://github.com/intellij-rust/intellij-rust/issues/3639#issuecomment-480232986)

**Comment by fredpointzero** [comment]
Thanks for the info, I will use this.
