### ISSUE TITLE
Error with Code Autocompletion

### ISSUE THREAD

**Issue by anvial** [intellij-rust/intellij-rust#394]
Hello, 

I'm new to Rust-lang and only first-day user of your plugin for CLion. 

I've the following error with code completion. 

com/intellij/util/VisibilityIcons
java.lang.NoClassDefFoundError: com/intellij/util/VisibilityIcons
	at org.rust.ide.icons.RustIconsKt.addVisibilityIcon(RustIcons.kt:43)
	at org.rust.lang.core.psi.RustVisibilityOwnerKt.iconWithVisibility(RustVisibilityOwner.kt:17)
	at org.rust.lang.core.psi.impl.mixin.RustFnItemImplMixin.getIcon(RustFnItemImplMixin.kt:30)
.....

Any ideas how to fix that issue? 

Thank You.

**Comment by matklad** [comment]
@anvial that's most definitely the bug on our side, will try to fix it shortly. 

Unfortunately I myself use the plugin with IDEA, so often times I miss CLion specific issues. 

Thanks for the report!

**Comment by matklad** [comment]
Here is [the link to the build](https://teamcity.jetbrains.com/repository/download/IntellijIdeaPlugins_Rust_Idea16_TestsRust/769400:id/intellij-rust-0.0.1.162.zip) with the issue fixed. You can install it with **install plugin from disk** action. 

Nightly build should be created later today,
