### ISSUE TITLE
Auto import doesn't show anything in own crate

### ISSUE THREAD

**Issue by Fullstop000** [intellij-rust/intellij-rust#3948]
## Environment

* **Intellij-Rust plugin version:** 0.2.98.2125-191
* **Rust toolchain version:** 1.35.0
* **IDE name and version:** CLION 2019.1.4
* **Operating system:** macOS 10.13.6

## Problem description
Auto-import hint doesn't show any things in the crate I created but only shows things in `std` and extern crates. I tried `Alt + Enter` but got nothing.

**Comment by vlad20012** [comment]
Could you please link the project where we can reproduce the issue?

**Comment by Fullstop000** [comment]
@vlad20012 The link https://github.com/Fullstop000/wickdb. 

BTW, the problem occurs after I updated the plugin to the newest.

**Comment by Fullstop000** [comment]
I tried switching to Goland 2019.1 but didn't solve the problem.

**Comment by ice1000** [comment]
I have the same issue

**Comment by vlad20012** [comment]
@Fullstop000 I reproduced it on your project. Thanks! I'll try to fix it before next release (which is likely to be today)
