### ISSUE TITLE
unix module code completion

### ISSUE THREAD

**Issue by Arkrait** [intellij-rust/intellij-rust#3957]
## Environment

* **Intellij-Rust plugin version: 0.2.98.2126-183**
* **Rust toolchain version: 1.36.0-nightly**
* **IDE name and version: clion 2018.3.4**
* **Operating system: Arch Linux**

## Problem description
Plugin doesn't have code completion for std::os::unix.

## Steps to reproduce
![2019-06-04-221825_1366x768_scrot](https://user-images.githubusercontent.com/13279672/58907818-b5774180-8717-11e9-9ece-542b226f3e6e.png)

**Comment by Czocher** [comment]
This is a immediate result of #4093, since the `std::os` uses `cfg_if` to load `unix`.

**Comment by ortem** [comment]
This issue is not related to #4093.

The declaration of the `unix` module basically looks like this (see `os/mod.rs`):
```Rust
cfg_if::cfg_if! {
    if #[cfg(doc)] {
        pub use crate::sys::unix_ext as unix;
    } else {
        pub use crate::sys::ext as unix;
    }
}
```
The plugin cannot resolve `cfg_if::cfg_if!` so `unix` mod declaration could not be expanded and used in code insight e.g. completion.

The issue is probably related to #3864.

**Comment by KoStard** [comment]
Any updates?

**Comment by lUNuXl** [comment]
Any updates on this issue? It's been quite a bit of time since the first report.

**Comment by vlad20012** [comment]
The work in progress. You can follow #6104
