### ISSUE TITLE
Display path to standard library in the Rust settings page

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#396]
Problem: There is no sure indication if the Rust standard library is attached properly. That is, if you open the Rust file and don't see the notification, it could be that you have already attached library, or that you have dismissed the notification.

Solution: the most obvious way to add this information is to add

```
Standard library: not `attached | ~/projects/rust-1.7.0` |Download| |Attach|
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~   ~~~~~~
```

panel to [Project Settings](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt)

**Comment by mfarrugi** [comment]
The notification should also automatically disappear on successful download or attach.
