### ISSUE TITLE
Incorrect mismatched types checking on shift operator

### ISSUE THREAD

**Issue by Fullstop000** [intellij-rust/intellij-rust#3964]
## Environment

* **Intellij-Rust plugin version:** v0.2.98.2125-191
* **Rust toolchain version:** 1.35.0
* **IDE name and version:** Goland 2019.1
* **Operating system:** macOS 10.13.6

## Problem description

![image](https://user-images.githubusercontent.com/12471960/58939304-84475180-87a9-11e9-9fe5-8e0585f88518.png)

## Steps to reproduce
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=13cff937bcf8ed1346a6100c28b8804f

**Comment by Fullstop000** [comment]
It's weird that the error has disappeared but I don't change any configurations or update the plugin.

**Comment by vlad20012** [comment]
It should work if you enable the new macro expansion system (see #3628)

**Comment by Fullstop000** [comment]
Since this is no longer a problem, this could be closed.
