### ISSUE TITLE
Expanded macros occupy a lot of space

### ISSUE THREAD

**Issue by MSxDOS** [intellij-rust/intellij-rust#3968]
## Environment

* **Intellij-Rust plugin version:** v0.2.98.2125-191
* **Rust toolchain version:** 1.37.0-nightly (5d8f59f4b 2019-06-04) x86_64-pc-windows-msvc 
* **IDE name and version:** IntelliJ IDEA 2019.1.3
* **Operating system:** Windows 7 x64

## Problem description
I've opened a few of my projects that have `winapi` and `ntapi` crates among their dependencies using the new macro expansion engine and noticed that `.IdeaIC2019.1\system\rust_expanded_macros` already contains **64 478** files and occupies 266 MB of disk space due to the minimum file size on disk being equal to the cluster size (4 KB) with the actual folder size of 53,8 MB.

I really think we should group expanded macros somehow (anyhow) to both reduce the occupied space and improve performance because every request to open and read or map a file is a separate system call for each operation.

Related: https://github.com/intellij-rust/intellij-rust/issues/3685

**Comment by vlad20012** [comment]
I hope I'll solve this problem eventually. Ideally, before enabling new engine by default (#3628).

Just note that it isn't as easy as it seems :)

**Comment by daboross** [comment]
I use this a number of times in [screeps-game-api](https://github.com/daboross/screeps-in-rust-via-wasm/tree/master/screeps-game-api), for what it's worth.

My particular use case is for creating a bunch of modules with similar methods, to match JavaScript structures which this project creates bindings to.
