### ISSUE TITLE
Incorrect cast

### ISSUE THREAD

**Issue by ice1000** [intellij-rust/intellij-rust#3975]
https://github.com/intellij-rust/intellij-rust/blob/b939b34aa5df38c3f16d72d125e856a82960a8fc/src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt#L321

`first.element` is sometimes `org.rust.lang.core.psi.impl.RsImplItemImpl`, which is not `RsNamedElement`, causing `ClassCastException`.

**Comment by vlad20012** [comment]
I just fixed it
