### ISSUE TITLE
Impl blocks for aliased types are not recognized

### ISSUE THREAD

**Issue by ice1000** [intellij-rust/intellij-rust#3982]
## Environment

* **Intellij-Rust plugin version:** ![image](https://user-images.githubusercontent.com/16398479/59074468-5719a280-8880-11e9-8532-0dc4886be018.png)
* **Rust toolchain version:** Irrelevant
* **IDE name and version:** CL-192, EAP
* **Operating system:** Windows

## Problem description

Minimum, reproducible example:

```rust
struct Elder;
type Frog = Elder;
impl Frog { pub fn talk_and_laugh(self) {} }

fn main() {
    let elder = Elder;
    elder.<caret>
}
```

Actual behavior:

![image](https://user-images.githubusercontent.com/16398479/59074564-d018fa00-8880-11e9-9c65-586f8881994f.png)

Notice the method `talk_and_laugh` is not in the completion list and cannot jump to definition after manually write the function.

**Comment by Undin** [comment]
Duplicates of #3322
