### ISSUE TITLE
Regression: False positive "Unresolved reference" for reexported constants depending on the sequence of imports

### ISSUE THREAD

**Issue by danilaml** [intellij-rust/intellij-rust#3989]
## Environment

* **Intellij-Rust plugin version:** 99
* **Rust toolchain version:** 1.35.0
* **IDE name and version:** Idea 2019.1.3
* **Operating system:** Win 10 x64 1809

## Problem description
After updating Rust plugin to 98 (and later to 99) I've discovered a strange problem in one of my projects. constant `K` was not being resolved:

![image](https://user-images.githubusercontent.com/2046350/59139988-b8d12e00-89a0-11e9-9f19-f8e07bbc4668.png)

Here is somewhat reduced project: https://github.com/danilaml/res-bug

## Steps to reproduce

It seems to be somewhat random, i.e. I could figure out a specific logical reason for this behaviour. For example, if I add `use res_bug::consts::*;` into adjacent `img_tests`, when `K` is recognized just fine. Similarly, when reducing, it becomes resolved and unresolved at random.

**Comment by vlad20012** [comment]
Hi!
I got 404 on your link. Could you please check it?

**Comment by danilaml** [comment]
@vlad20012 sorry, forgot to make it public. Should be fine now.
