### ISSUE TITLE
Add an option to show stderr/stdout in test toolwindow always

### ISSUE THREAD

**Issue by sirgl** [intellij-rust/intellij-rust#3994]
## Environment

* **Intellij-Rust plugin version:** v0.2.99.2126-191
* **Rust toolchain version:** 1.18.3
* **IDE name and version:** 2019.1.4
* **Operating system:** mac os

## Problem description
Now if test successfully passed, no output shown. I think, it is wrong, because there may be logging, `dbg!` values and so on, which can be helpful even for passed tests - you may want to compare correct value from passed test and incorrect value from failed one (for java e. g. all output shows always).

**Comment by Undin** [comment]
As I understand it's because of https://github.com/rust-lang/rust/issues/54669
@mchernyavsky am I right?
