### ISSUE TITLE
Projects are not properly created

### ISSUE THREAD

**Issue by Jire** [intellij-rust/intellij-rust#400]
Using the new Rust project option, the project is not created properly. No source folder is generated, the project is not usable.

http://i.imgur.com/tdRjIFO.png

**Comment by matklad** [comment]
Unfortunately we have not yet implemented functionality for creating new Rust project from within IDE. 

So, you need to `cargo new my_project` from the command line and then open it, as descried in  the [Quick Start]

[Quick Start]: https://github.com/intellij-rust/intellij-rust/blob/master/doc/QuickStart.md

**Comment by matklad** [comment]
Created https://github.com/intellij-rust/intellij-rust/issues/402 and https://github.com/intellij-rust/intellij-rust/issues/401

**Comment by Jire** [comment]
@matklad Thank you for the very prompt response.
