### ISSUE TITLE
No type info when using enumerate

### ISSUE THREAD

**Issue by GideonUng** [intellij-rust/intellij-rust#4013]
## Environment

* 0.2.99.2126-191
* 1.35.0
* Clion 2019.1.4
* Linux Mint 19.1

## Problem description
second tuple type does not get resolved when using enumerate when iterating over collection

## Steps to reproduce

```rust	
let mut v = Vec::new();
v.push((1i32, 1f32));
for (i, (ii, ff)) in v.iter().enumerate() {
  // i gets resolved to usize
  // clion fails to deduce the type for ii, ff 
}
```

**Comment by Kobzol** [comment]
The types are resolved correctly in the latest version of the plugin.
