### ISSUE TITLE
False positive E0118 in stdlib

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#4017]
## Environment

* **Intellij-Rust plugin version:** 0.2.100.2656-192-nightly
* **Rust toolchain version:** rustc 1.37.0-nightly (02564de47 2019-06-10)
* **IDE name and version:** IU-192.4787.16
* **Operating system:** macOS 10.13

## Problem description
Primitive types can have free impls is stdlib. But the plugin always produces error annotation.
For example, open `libcore/slice/mod.rs` and find impl for `[T]`
![image](https://user-images.githubusercontent.com/2539310/59329010-7c7e3480-8cf6-11e9-8532-b264552f9951.png)

The bug was introduced in #3825

**Comment by Undin** [comment]
CC @mibac138

**Comment by mibac138** [comment]
@Undin I'll send a pr this week
