### ISSUE TITLE
add the ability to run a custom version of rustfmt

### ISSUE THREAD

**Issue by LooMaclin** [intellij-rust/intellij-rust#4024]
Hi. I want to use rustfmt with command `cargo +nightly fmt`, but in current version of plugin command cannot be customized

**Comment by abonander** [comment]
I'd like to signal-boost this; it'd be nice to have even just a checkbox to run rustfmt with nightly to access unstable options like `merge_imports`.

**Comment by Keating950** [comment]
Why not at least just run whatever version of rustfmt is in our `$PATH`? Right now, the plugin insists that rustfmt isn't installed just because I built it from source rather than using rustup.

**Comment by emailnjv** [comment]
This is especially an issue when using nightly builds that don't have rustfmt on the latest toolchain yet.

**Comment by dvcrn** [comment]
I'm having the same issue, I want to run the nightly version of rustfmt but it refuses to use it.

```
❯ cargo fmt --version
rustfmt 1.4.37-nightly (a8068832 2021-09-08)

❯ cargo +nightly fmt --version
rustfmt 1.4.37-nightly (a8068832 2021-09-08)

❯ rustfmt --version
rustfmt 1.4.37-nightly (a8068832 2021-09-08)

❯ which rustfmt
/Users/david/.cargo/bin/rustfmt
```

Everything points to the correct rustfmt, but I'm still getting `rustfmt is not installed`, because I build from source

**Comment by dvcrn** [comment]
Okay actually that ended up working. Having a nightly rustfmt in my stable toolchain makes this plugin pick it up and give me nightly features

**Comment by dvcrn** [comment]
@spikespaz I don't fully remember, but I think I stopped using stable rustfmt and only the nightly one, even in stable toolchain. That's what I meant with having 'nightly rustfmt in my stable toolchain'
