### ISSUE TITLE
GDBCommandException is occurred when entering to debug session

### ISSUE THREAD

**Issue by NDelt** [intellij-rust/intellij-rust#4048]
## Environment
* **Intellij-Rust plugin version:** v0.2.99.2126-191
* **Rust toolchain version:** 1.35.0
* **IDE name and version:** CLion 2019.1.4
* **Operating system:** Windows 10 1903

## Problem description
```rust
fn main() {
    println!("Hello, world!"); // Breakpoint
    let x = 1;
    println!("{}", x);
}
```
**Run | Debug 'Sample'**

After I enter to debug session, debugger dies immediately and the following error message appears.

```
com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$GDBCommandException: Warning:
Cannot insert breakpoint 1.
Cannot access memory at address 0x4016da
```

**Comment by ortem** [comment]
@NDelt Do you use `MinGW` toolchain with `Bundled GDB`? You can check it via `File | Settings | Build, Execution, Deployment | Toolchains`.

**Comment by NDelt** [comment]
@ortem I'm using WSL as toolchain. Is it related to Rust, not only C/C++?

**Comment by ortem** [comment]
@NDelt Yes, it is. IntelliJ Rust uses the debugger provided by CLion's toolchain. You can try `Cygwin` toolchain if you don't mind to install it; Cygwin should work fine.

I'll try to investigate your problem with WSL toolchain (actually I have never tried using WSL as CLion's toolchain) and leave a comment here later.

**Comment by NDelt** [comment]
@ortem Thanks. I'll try using MinGW-w64 toolchain. I hope WSL would be supported for IntelliJ Rust.

**Comment by NDelt** [comment]
@ortem I've changed toolchain from WSL to MinGW-w64 but the same error occurs.

**Comment by ortem** [comment]
@NDelt I cannot reproduce it. Could you please check the debugger itself this way?

1. Open the Windows' terminal
2. Compile your code via `rustc -g`
3. Run the debugger (something like `C:\MinGW\bin\gdb my.exe`)
4. Enter `b 2` (set breakpoint to the second line)
5. Enter `r` (run)

**Comment by NDelt** [comment]
@ortem It works well on the command line interface.
![rustgdb](https://user-images.githubusercontent.com/46282492/60097001-6019d780-978d-11e9-8322-8afe58a882b1.PNG)

Non-ASCII word has broken. I don't know what is the cause. (Encoding of terminal and source code is UTF-8.)

**Comment by ortem** [comment]
@NDelt Thanks for trying! Then I'd like to know something else:
1. Have you tried setting a breakpoint in CLion at another line of your code or even another Rust project?
2. Whether the Rust debugging was working on previous CLion/IJ-Rust versions?

**Comment by NDelt** [comment]
@ortem
1. Yes, and the same issue has occurred.
2. It doesn't work either.

I've found warning message `Version 8.3; supported versions are 7.8.x-8.2.x` in **Settings | Build, Execution, Deployment | Toolchains | MinGW**. Maybe this could be the cause.

**Comment by ortem** [comment]
@NDelt Yes, you should use older gdb version. For example, I have `MinGW-W64-builds-4.3.5` (AFAIK, it is from https://mingw-w64.org/doku.php/download/mingw-builds) with `gdb-8.1` and it works fine.

**Comment by ortem** [comment]
@NDelt Is your problem fixed?

**Comment by NDelt** [comment]
@ortem Yes, it works well after downgrading gdb version.

**Comment by ortem** [comment]
@NDelt Great!
