### ISSUE TITLE
Complete symbols from the prelude

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#405]
```
fn main() {
    let x: Op<caret>
}
```

should complete to 

```
fn main() {
    let x: Option
}
```

if the user has set up the Rust standard library.

**Comment by matklad** [comment]
fixed in https://github.com/intellij-rust/intellij-rust/pull/444

**Comment by chriskrycho** [comment]
I just want to say: you all as a team are doing amazing work. I have this repo watched on GitHub, and seeing issues like this one go by… it's impressive, and I'm enjoying using the plugin myself—seeing it get better all the time is fantastic.
