### ISSUE TITLE
Rust missing syntax highlighting sometimes

### ISSUE THREAD

**Issue by maxim-banaev** [intellij-rust/intellij-rust#4054]
## Environment

* **Intellij-Rust plugin version:**
* **Rust toolchain version:**
* **IDE name and version:** CLion 2019.1.4 
* **Operating system:** Windows 10, macOS 10.14

## Problem description

On a simple project with a single dependency to the sysinfo crate there is not syntax highlighting for the structures under the sysinfo module. See screencast: https://www.screencast.com/t/BZ8OAw9mkj1

Attachment in the youtrack ticket.
https://youtrack.jetbrains.com/issue/CPP-16616

Sample project attached.

**Comment by Undin** [comment]
@paulcsiki Thanks for the report!
The main reason is a way how `sys` module declared in `sysinfo` crate. 
Now its declaration is
```rust
cfg_if! {
    if #[cfg(target_os = "macos")] {
        mod mac;
        use mac as sys;
    } else if #[cfg(windows)] {
        mod windows;
        use windows as sys;
        extern crate winapi;
    } else {
        mod linux;
        use linux as sys;
    }
}
```
And unfortunately, the plugin doesn't support `cfg` attributes for now. It leads to multi-variant name resolution of `sys` module. This, in turn, prevents correct name resolution of child items

**Comment by paulcsiki** [comment]
Hey @Undin,

Thank you very much for the detailed response. I've noticed that VS Code with RLS can pull out the documentation for the sys module once the code is written but has no autocompletion (Intelisense? or this is a Microsoft thing?). I wonder how the do it to bypass this limitation?

![VSCode with RLS](https://i.imgur.com/7xaz4F3.png)

**Comment by vlad20012** [comment]
@paulcsiki IntelliJ Rust doesn't use RLS, so our limitations are only our limitations (and RLS limitation are only RLS limitation). I guess RLS can resolve the name when IntelliJ Rust can't.

**Comment by vlad20012** [comment]
Already fixed
