### ISSUE TITLE
Rust `rotate_X` functions aren't recognized

### ISSUE THREAD

**Issue by elichai** [intellij-rust/intellij-rust#4063]
## Environment

* **Intellij-Rust plugin version:** v0.2.100.2128-191
* **Rust toolchain version:** rustc 1.35.0 (3c235d560 2019-05-20)
* **IDE name and version:** CLion 2019.1.4 Build #CL-191.7479.33, built on May 30, 2019
* **Operating system:** Linux 5.1.14-arch1-1-ARCH

## Problem description
CLion doesn't recognize the `u32.rotate_right()`/`rotate_left()` functions

## Steps to reproduce
```rust
fn main() {
    let a: u32 = 5;
    let b = a.rotate_right(7);
}
```
![clion_rotate](https://user-images.githubusercontent.com/2167860/60144407-3910d500-9790-11e9-90f2-36d55842b138.png)

**Comment by Undin** [comment]
@elichai Thanks for the report!
`rotate_X` methods for primitive types are generated by macros and our default macro expansion engine doesn't support them for some technical reasons.
Try to enable the experimental macro expansion engine. It should solve your issue.
You can do it via `Preferences | Languages & Frameworks | Rust | Expand declarative macros` option.
![image](https://user-images.githubusercontent.com/2539310/58436688-4f633c80-80cf-11e9-9bcf-0f81bf30f46b.png)
Note, it’s not stable yet but we don’t know any critical issue related to it. More about new macro engine can be found in #3628
