### ISSUE TITLE
Changes to tab sizes are not persisted

### ISSUE THREAD

**Issue by nesteruk** [intellij-rust/intellij-rust#407]
When changing the size of indents in the IDEA Community option pages, changes related to Rust are not saved when pressing OK or Apply.

**Comment by matklad** [comment]
Out of curiosity, do you really want to change tab settings? Looks like community is settled on four spaces for indent.

**Comment by nesteruk** [comment]
I couldn't care less what "community settled" on, I have my own presets, they are not subject to any form of discussion or negotiation.

**Comment by matklad** [comment]
Thanks! It's interesting that your opinion [is shared] by a significant part of Rust users.

[is shared]: https://users.rust-lang.org/t/please-help-test-rustfmt/5386/11
