### ISSUE TITLE
Code completion and syntax coloring with fns from some mods (e.g. compute example in gfx-rs project)

### ISSUE THREAD

**Issue by imkow** [intellij-rust/intellij-rust#4075]
## Environment
* all the recent nightly intellij-rust plugin
* all rust toolchain
* CLion
* all OS

## Problem description
Code compleation and syntax coloring with fns from some mods (e.g. compute example in gfx-rs project):
https://github.com/gfx-rs/gfx/blob/master/examples/compute/main.rs#L156
from the line, all command_buffer.xxx() invocations are no code completion and syntax coloring.

Thx.

**Comment by Undin** [comment]
@imkow Thanks for the feedback!
The real reason why name resolution and code completion don't work is [here](https://github.com/gfx-rs/gfx/blob/master/examples/compute/main.rs#L8-L14).
`back` crate alias is declared with `cfg` attribute. But the plugin doesn't support them at this moment so it finds several declarations of `back` crate and fails to find `Instance` declaration from [line](https://github.com/gfx-rs/gfx/blob/master/examples/compute/main.rs#L40).
We are going to support `cfg` attributes and related things but can't provide any time estimation when it will be implemented

**Comment by imkow** [comment]
@Undin thanks. However, in my personal project, I removed those cfg , still got the problem at command_buffer.xxx()

**Comment by Undin** [comment]
@vlad20012 or @mchernyavsky Could you take a look? It seems we can't infer type of `command_buffer` => completion doesn't work properly

**Comment by imkow** [comment]
the code updated to https://github.com/gfx-rs/gfx/blob/master/examples/compute/main.rs#L165

**Comment by imkow** [comment]
@Undin @vlad20012  @mchernyavsky this is a bug, not related to ```cfg```

**Comment by Undin** [comment]
@imkow Looks like the issue with type inference is already fixed - I checked it on https://github.com/gfx-rs/gfx/blob/6d7cff1fe269127f164c764cebd53c7cfb245db9/examples/compute/main.rs because the current version of file is changed. So there is the only issue related to `cfg` attributes support in a workspace

**Comment by imkow** [comment]
@Undin thx, I'll revisit.
