### ISSUE TITLE
Errors about Copy types being used after being moved.

### ISSUE THREAD

**Issue by CleanCut** [intellij-rust/intellij-rust#4076]
## Environment

* **Intellij-Rust plugin version:**

  v0.2.101.2670-191-nightly

* **Rust toolchain version:**

  ```
  $ rustc --version
  rustc 1.35.0 (3c235d560 2019-05-20)
  ```

* **IDE name and version:**

  IntelliJ IDEA 2019.1.3 (Ultimate Edition)

* **Operating system:**

  macOS Mojave 10.14.5

## Problem description

Lots and lots of errors complaining about using copy types because they have moved (but copy types don't move).

## Steps to reproduce

Just use a Copy type twice in any expression.

![image](https://user-images.githubusercontent.com/5838512/60387386-73fc5c80-9a5f-11e9-8d88-9b205c004821.png)

**Comment by imkow** [comment]
tested your case, no this problem.

**Comment by CleanCut** [comment]
I uninstalled the plugin, then reinstalled through the alpha channel instead of nightly, got the same version number `v0.2.101.2670-191-nightly` (which is sort of weird), but now I no longer have this error (which is even weirder, but at least the problem went away).

🤷‍♂
