### ISSUE TITLE
CLion often crashes  after updating Rust Plugin to v0.2.100.2128-191

### ISSUE THREAD

**Issue by SharpKnifer** [intellij-rust/intellij-rust#4087]
## Environment

* **Intellij-Rust plugin version:**
 v0.2.100.2128-191
* **Rust toolchain version:**
rustc 1.33.0-nightly (c76f3c374 2019-01-18)
* **IDE name and version:**
CLion 2019.1.4
Build #CL-191.7479.33, built on May 30, 2019
JRE: 1.8.0_202-release-1483-b53 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* **Operating system:**
macOS 10.14

## Problem description
CLion often crashes  after updating Rust Plugin to v0.2.100.2128-191.
Before I update the Rust Plugin , My CLion works well. But after I update the Rust Plugin, My CLion always crash. I do not know what is going wrong. I want to downgrade the Rust Plugin back to the previous version.

**Comment by ortem** [comment]
Hi @SharpKnifer, could you please provide the logs? You can open it via `Show Log in Finder` action, or find it manually if you cannot even invoke the action in CLion (then you should search for `/Users/<user>/Library/Logs/CLion2019.1/idea.log` or similar).

**Comment by SharpKnifer** [comment]
[threadDump-20190702-171050.txt](https://github.com/intellij-rust/intellij-rust/files/3349302/threadDump-20190702-171050.txt)
this is my log file at /Library/Logs/CLion2019.1/threadDumps-freeze-20190702-171045-CL-191.7479.33-10sec/threadDump-20190702-171050.txt

**Comment by SharpKnifer** [comment]
[idea.log](https://github.com/intellij-rust/intellij-rust/files/3349317/idea.log)
@ortem And this is my idea.log

**Comment by ortem** [comment]
@SharpKnifer Thank you! Also, you can try removing IJ Rust plugin by removing its containing directory (it should be `~/Library/Application Support/CLion2019.1/intellij-rust`). Then relaunch CLion, check whether it works without the plugin and reinstall the plugin.

**Comment by SharpKnifer** [comment]
> @SharpKnifer Thank you! Also, you can try removing IJ Rust plugin by removing its containing directory (it should be `~/Library/Application Support/CLion2019.1/intellij-rust`). Then relaunch CLion, check whether it works without the plugin and reinstall the plugin.

By the way, could you please give me some advice? Which Rust Plugin version I should install. I love this plugin on CLion. It's  a very friendly and awesome plugin . But recently the crash makes me very upset. I hope you can find out what is going wrong. Thank you very much!

**Comment by ortem** [comment]
@SharpKnifer  Your IJ Rust version `v0.2.100.2128-191` is stable and should work fine. Have you tried running CLion after removing the plugin?

**Comment by SharpKnifer** [comment]
It seems like the latest version v0.2.100.2128-191 has some bug. I downgrade to old version(v0.2.93.2117-183). Then my CLion works well.

**Comment by Undin** [comment]
I suppose it can be closed now
