### ISSUE TITLE
cfg_if fails to expand macro

### ISSUE THREAD

**Issue by suyoshi** [intellij-rust/intellij-rust#4093]
## Problem description
```rust
cfg_if::cfg_if! {
    if #[cfg(unix)] {
        macro_rules! log {
            ( $( $t:tt )* ) => {
                println!($( $t )* );
            }
        }
    } else {
        macro_rules! log {
            ( $( $t:tt )* ) => {
                web_sys::console::log_1(&format!( $( $t )* ).into());
            }
        }
    }
}
```

```
[dependencies]
cfg-if = "1.0.0"
```

This compiles and works but Intellij reports that it cannot find `log!`. I guess this is similar to https://github.com/intellij-rust/intellij-rust/issues/2601 ?

## Steps to reproduce

Call `log!("")` from the macro above.

**Comment by vlad20012** [comment]
Unfortunately, we don't support macros defined in expansions of other macros.

**Comment by suyoshi** [comment]
I see. Are there any plans to support it in the future? If not I'll just try to work around it somehow.

**Comment by Undin** [comment]
@suyoshi we don't have plans to fully support macros generated by other macros in the nearest future because it requires a lot of work and at the same time it's a rather rare case.
Also, at this moment the plugin doesn't support `cfg` attributes
