### ISSUE TITLE
Make TOML plugin compatible with 2019.3

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#4098]
## Environment

* **IDE name and version:** CLion 2019.3 Nightly 193.952
* **Operating system:** macOS 10.14.4

## Problem description

With #4091 in place Rust Plugin is now compatible with 193 branch. Unfortunately, this is not the case for TOML plugin, as it is impossible to install it on 2019.3 IDE using nightly plugin repository https://plugins.jetbrains.com/plugins/nightly/8195

**Comment by Undin** [comment]
The latest version of Toml plugin supports nightly builds of 2019.3
