### ISSUE TITLE
Trait constraint in associated type is not detected 

### ISSUE THREAD

**Issue by lovasoa** [intellij-rust/intellij-rust#4103]
## Environment

* **Intellij-Rust plugin version:** v0.2.100.2128-191
* **Rust toolchain version:** 1.36.0
* **IDE name and version:** IntelliJ IDEA 2019.1.3 (Community Edition) Build #IC-191.7479.19
* **Operating system:** macOS 10.14.5

## Problem description

I have a generic function that operates on the pixels of a [`GenericImageView`](https://docs.rs/image/0.21.2/image/trait.GenericImageView.html). The `GenericImageView` trait has an associated `Pixel` type, that must implement the [`Pixel`](https://docs.rs/image/0.21.2/image/trait.Pixel.html) trait. IntelliJ rust seems to fail to detect that, and does not find the Pixel::channels function.

## Steps to reproduce

Download the code of [lovasoa/seamcarving v0.0.2](https://github.com/lovasoa/seamcarving/releases/tag/v0.0.2)
Navigate to [this part of the code](https://github.com/lovasoa/seamcarving/blob/8aa1f61cf58d36a75d0032efdfadda28880c2e64/src/lib.rs#L89-L95).

**Comment by nnao45** [comment]
same probplem occured.
intellij-rust dose not detect trait has associated type's function

**Comment by Undin** [comment]
Works now
