### ISSUE TITLE
MSVC debugger can be enabled (experimentally) on CLion, can we (experimentally) enable it for rust now?

### ISSUE THREAD

**Issue by imkow** [intellij-rust/intellij-rust#4104]
ATS.

FYI: https://github.com/intellij-rust/intellij-rust/blob/master/debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt#L78

**Comment by ortem** [comment]
Unfortunately, new CLion's debugger doesn't support MSVC for Rust for now. We are working on it.

**Comment by imkow** [comment]
Any progress on this? thx.

**Comment by HydrogenC** [comment]
Also seeking for MSVC support.

**Comment by kterhorst** [comment]
Please.

**Comment by CodingBeagle** [comment]
The one reason keeping me from really using CLion for Rust development right now!

**Comment by SonicZentropy** [comment]
If I were ever to save a busload of children from certain doom and Jesus himself descended from the heavens and gave me one wish as a reward, my wish would be seeing this issue closed successfully

**Comment by gilescope** [comment]
You’re saying we need a bus, a driver and a deity before we can close this ticket? This seems like scope creep if ever I saw it...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by HydrogenC** [comment]
> The one reason keeping me from really using CLion for Rust development right now!

Good news: MSVC debugger support for C++ implemented (not experimental) in CLion 2020.1 EAP.

**Comment by jbouzaglou** [comment]
Any ETA before we see this trickle down to Rust?

**Comment by imkow** [comment]
any progress, guys? please

**Comment by JakubKoralewski** [comment]
> 
> 
> any progress, guys? please

I was able to start the debugger on the EAP with Rust with the default toolchain set to MSVC.

**Comment by imkow** [comment]
@JakubKoralewski Are you sure? I'm on the latest EAP, and default toolchain is MSVC, and I can't debug rust project, it pops up "MSVC toolchain is not supported. Please use GNU toolchain." error message box.

**Comment by JakubKoralewski** [comment]
@imkow Yup. I'm sure as much as I can be. I'm not sure how to prove the debugger is definitely running under MSVC, but I can show you a stopped program with MSVC set as default:
![obraz](https://user-images.githubusercontent.com/43069023/76711295-fa042480-670e-11ea-994f-5cd3ca09a27d.png)
![obraz](https://user-images.githubusercontent.com/43069023/76711309-1e600100-670f-11ea-8c50-1a207b6bd043.png)

I've tested every possible debugger. but I still can't access a struct inside a vector in any of them :confused:

**Comment by imkow** [comment]
@JakubKoralewski I think that you are confused by the settings. In fact, the rust toolchain is not set by the CLion toolchain settings, it's set by `rustup default [toolchain name here]`, and you can check it by `rustup default`.

**Comment by JakubKoralewski** [comment]
> 
> 
> @JakubKoralewski I think that you are confused by the settings. In fact, the rust toolchain is not set by the CLion toolchain settings, it's set by `rustup default [toolchain name here]`, and you can check it by `rustup default`.

Oh sorry. I removed it.

**Comment by andyjsbell** [comment]
How's this coming along?  I would love to see this in CLion.

**Comment by MSxDOS** [comment]
@ortem
>  We are working on it.

How is it going?

**Comment by uyplayer** [comment]
**still can't use MSVC debugger ?     , these guys  bought IDE , and still can't support  MSVC debugger    .  made my day**
