### ISSUE TITLE
Enable rustfmt on save by default

### ISSUE THREAD

**Issue by Riateche** [intellij-rust/intellij-rust#4118]
It would be nice to have an option to turn on "Enable rustfmt on save" for all new projects.

**Comment by Undin** [comment]
You can set up the default value for any project setting for all new projects via `File | Other Settings | Settings for New Projects` option. See more [here](https://www.jetbrains.com/help/idea/configuring-project-and-ide-settings.html#ide-level).
Also, if you try to open project settings from the welcome screen, IDE will open settings for new projects as well.
<img width="516" alt="Screen Shot 2019-07-09 at 17 18 44" src="https://user-images.githubusercontent.com/2539310/60895688-c0207b80-a26d-11e9-9ee5-a9c074d6fe81.png">

**Comment by Riateche** [comment]
Nice, thank you.
