### ISSUE TITLE
Create implement trait action

### ISSUE THREAD

**Issue by sirgl** [intellij-rust/intellij-rust#4123]
It is very tedious write boilerplate code for trait implementations by hand.

E. g. for
```rust
pub struct TreeResultPrettyView<'t, 'r, 'e> {
    result: &'t TreeResult,
    resolver: &'r dyn KindResolver,
    escaper: &'e dyn Escaper,
}
```
it is boring to write something like this with all type and lifetime parameters repeating:
```rust
impl <'t, 'r, 'e>Display for TreeResultPrettyView<'t, 'r, 'e> {
    fn fmt(&self, f: &mut Formatter) -> Result<(), Error> {
       ...
    }
}
```
So I suggest to add dialog like for goland: 
https://habrastorage.org/webt/io/iy/t3/ioiyt3kh0gn_057wq5_wd66h8iu.gif

## Environment

* **IntelliJ Rust plugin version:** 0.2.101.2129-192
* **Rust toolchain version:** 1.38.0-nightly (481068a70 2019-07-05) x86_64-apple-darwin
* **IDE name and version:** CL-192.5438.15
* **Operating system:** macOS 10.14.5

**Comment by AndreKR** [comment]
This should probably also create `impl` blocks for supertraits.

For example when I want to implement `std::error::Error` for an error type, it needs to create `impl` blocks for `core::fmt::Debug` and `core::fmt::Display`.
