### ISSUE TITLE
Freeze (forever) on rename while macro expansion is running

### ISSUE THREAD

**Issue by kellerkindt** [intellij-rust/intellij-rust#4126]
#  Environment

* **IntelliJ Rust plugin version:**
0.2.101.2129-192
* **Rust toolchain version:**
rustup 1.18.3 (435397f48 2019-05-22)
cargo 1.36.0 (c4fcfb725 2019-05-15)
cargo 1.37.0-nightly (4c1fa54d1 2019-06-24)
rustc 1.36.0 (a53f9df32 2019-07-03)
rustc 1.38.0-nightly (6e310f2ab 2019-07-07)
* **IDE name and version:**
CLion 2019.2 EAP 192.5587.18
* **Operating system:**
Ubuntu 18.04
* more logs at https://youtrack.jetbrains.com/issue/CPP-16797 (limited visibility to the jetbrains/clion teams only)

## Problem description & Steps to reproduce
Start CLion and while it is expanding macros (which can be checked in the bottom of the window) try to rename a variable (SHIFT+F6). CLion will freeze and no longer respond (gave it a coffee brake, but it did not recover).

freezing = can't click anything, does not respond on mouse movements or keyboard inputs

**Comment by kellerkindt** [comment]
Just as a note, with the latest Beta (CLion 2019.2 Beta, Build #CL-192.5728.28, built on July 11, 2019), it still locks. And as a further note, it does not only lock when the macro expansion is running, but also at seemingly random times when trying to rename something (this was also true with the previous version).

**Comment by vlad20012** [comment]
Hi!
I tried to fix the same issue in #4114.
Could you please try the latest nightly _plugin_ (see [instructions](https://intellij-rust.github.io/install.html))?

**Comment by kellerkindt** [comment]
It works. Also CPU usage has come down.
But I want to note that I wasn't able to test it intensively yesterday, I won't be able to do so until August again.
But what the 1h session yesterday showed was promising.

**Comment by Undin** [comment]
I think it can be closed
@kellerkindt if you still have with the same problem, feel free to ping us to reopen it
