### ISSUE TITLE
Renamed crate lost in autocomplete.

### ISSUE THREAD

**Issue by alexander-irbis** [intellij-rust/intellij-rust#4133]
## Problem description

Renamed in Cargo.toml crate is not displayed in autocomplete if it imported from the same workspace. The content of this crate is suggested as it should.

![Screenshot_20190711_180508](https://user-images.githubusercontent.com/1448323/61064210-07437380-a40a-11e9-95a0-19d277415430.png)

![Screenshot_20190711_180612](https://user-images.githubusercontent.com/1448323/61064223-0ca0be00-a40a-11e9-95b1-52d252659705.png)

Example project to reproduce:
https://github.com/alexander-irbis/bug-report/tree/renamed-import/sub

**Comment by dima74** [comment]
This was fixed some time ago
![image](https://user-images.githubusercontent.com/6505554/188566445-18fe905e-da34-47cd-bbef-30a919c3a5a0.png)
