### ISSUE TITLE
Missing completion for "use self"

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#4137]
## Environment

* **IntelliJ Rust plugin version:** 0.2.102.2682-192-nightly
* **Rust toolchain version:** rustc 1.36.0 (a53f9df32 2019-07-03)
* **IDE name and version:** CLion 2019.3 Nightly 193.1187
* **Operating system:** macOS 10.14.4

## Problem description

Consider the following code:

```rust
mod front_of_house {
    pub mod hosting {
        pub fn add_to_white_list() {
            println!("adding to whitelist ...");
        }
    }
}
```

I want to bring `hosting` into scope, so I do

```rust
use self::front_of_house::
```

pressing `Ctrl+Space` to invoke completion list reports `No suggestions`:

<img width="432" alt="Screen Shot 2019-07-12 at 14 03 46" src="https://user-images.githubusercontent.com/2500320/61123780-e92f4f00-a4ad-11e9-9896-5a8622f50e8f.png">

while manual typing `h` suggests the relevant module name. The problem seems to be caused by a `self` usage as completion works perfectly with the following example:

```rust
use crate::front_of_house::
```

<img width="565" alt="Screen Shot 2019-07-12 at 14 05 45" src="https://user-images.githubusercontent.com/2500320/61123884-2d225400-a4ae-11e9-90f0-7474c34681a8.png">

**Comment by dima74** [comment]
@lancelote could you please check - probably issue was fixed some time ago - I can't reproduce it with `0.3.141.3632-203-nightly`:

![image](https://user-images.githubusercontent.com/6505554/105995803-8ff03600-60ba-11eb-948f-1e454b122e83.png)

**Comment by lancelote** [comment]
Thank you for looking into it 🙏
Seems to be obsolete indeed (0.3.141.3638-203-nightly).
