### ISSUE TITLE
Intellij freezes when using "Implement methods" on a trait in Intellij 2019.2 EAP/Beta2

### ISSUE THREAD

**Issue by BensPublicCodeRepos** [intellij-rust/intellij-rust#4142]
## Environment

* **IntelliJ Rust plugin version:** Currently nightly from a suggestion in another issue, but this was happening in the latest stable release as well.

* **Rust toolchain version:** 1.36.0
* **IDE name and version:** Intellij 2019.2 Beta2
* **Operating system:** Archlinux, currently kernel version 5.2 but I have also tried with the latest LTS release (4.19) 

## Problem description
When using Intellij's "Implement methods" feature on an `Impl` block, the IDE will freeze and not recover. I've attached the thread dump from a recent occurrence below. 

[threadDump-20190713-115330.txt](https://github.com/intellij-rust/intellij-rust/files/3389143/threadDump-20190713-115330.txt)

## Steps to reproduce

Attempt to implement a trait without providing any of the methods: 

```rust
impl <Trait> for <Type> {
    
} 
```

When the red lines show up, hit ctrl+i to use the "Implement Methods" feature. Select all methods in the popup and hit enter. At this point, the IDE should freeze.

**Comment by vlad20012** [comment]
Just a note: the bug can be reproduced only if both "Run rustfmt on save" and "Run external linter to analyze code on the fly" are enabled, only on 2019.2 EAP, and most likely only on a Linux system with X11 (but I don't sure)
