### ISSUE TITLE
GDB pretty-printers crash on Option-like enums

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#4155]
## Environment

* **IntelliJ Rust plugin version:** 0.2.102.2685-192-nightly
* **Rust toolchain version:** 1.36.0
* **IDE name and version:** CLion 2019.2
* **Operating system:** Ubuntu

## Problem description

The GDB pretty-printer introduced in #3715 crashes on some enums, specifically on `Option`-like enums with a non-primitive value type, because of the invalid discriminant. Maybe this is because of wrong DWARF generation in rustc, though console GDB works well on such enums. So probably there should be a way to read the valid discriminant somehow.

Without pretty-printers:
<img width="956" alt="Screenshot 2019-07-18 at 11 53 10" src="https://user-images.githubusercontent.com/4854600/61443833-eff90e80-a952-11e9-91e4-b1a3f484a951.png">

With bundled pretty-printers:
<img width="779" alt="Screenshot 2019-07-18 at 11 57 08" src="https://user-images.githubusercontent.com/4854600/61444192-96ddaa80-a953-11e9-8c5a-a80183431c87.png">

Console GDB:
<img width="726" alt="Screenshot 2019-07-18 at 12 12 32" src="https://user-images.githubusercontent.com/4854600/61445351-eb822500-a955-11e9-8315-2134085aa0fa.png">

**Comment by Kobzol** [comment]
Thanks, I didn't have code that could reproduce it, now that I have it, I'll try to take a look at it.

**Comment by Kobzol** [comment]
So for this code:
```rust
enum MyEnum1<T> { A(T), B }

fn main()
{
    let a1 = MyEnum1::A(String::from("111"));
    let a2 = MyEnum1::B;
}
```
Discriminant in a1 is `94689684138817` (should be `0`).
Discriminant in a2 is `0` (should be `1`).

If the enum is inverted, i.e. `enum MyEnum2<T> { B, A(T) }`, discriminant for `MyEnum2::B` is still 0 (which is in this case correct), discriminant for `MyEnum2::A` is garbage, as in `MyEnum1`.

This doesn't happen with simple types. I think that it has something to do with some zero-sized optimization. If I use the enum for example with a type that contains a reference (i.e. 0 is not a valid value for that type), it also causes this error.

I suspect that this may be a Rustc DWARF generation issue (the enum DWARF generation was changed a few months ago). I'll try to investigate, but it will probably take me some time.

**Comment by Kobzol** [comment]
The enum debug metadata generation was changed in Rust a few months ago, and since then there's probably no straightforward way of detecting the compressed enums. I'll try to figure out a way to solve it with the author of the metadata generation and keep this issue updated.

In the meantime, we can apply some heuristic. For example: if the variant value if larger than let's say 100, it's probably a compressed enum (non-nullable pointers are unlikely to have a value < 100). It seems very fragile though, so maybe we should just keep the `EnumProvider` disabled for those invalid enums for now.

**Comment by Kobzol** [comment]
@ortem I think that this can be closed now, since https://github.com/intellij-rust/intellij-rust/pull/6804 fixed the rendering in GDB.
