### ISSUE TITLE
'Self' in generic arguments is wrongly accused of being a trait object

### ISSUE THREAD

**Issue by burjui** [intellij-rust/intellij-rust#4174]
## Environment

* **IntelliJ Rust plugin version:** 0.2.102.2130-191
* **Rust toolchain version:** rustc 1.36.0 (a53f9df32 2019-07-03)
* **IDE name and version:** IntelliJ IDEA 2019.1.3 (Community Edition)
* **Operating system:** Arch Linux

## Problem
In the following snippet
```rust
// 2018 edition
trait X {
    type A;
}
trait Y<T> {}
trait Z: X + Y<<Self as X>::A> {}
```
`Self` is highlighted with orange background and shows the following hint: `Trait objects without an explicit 'dyn' are deprecated`. Of course, on every commit an "are you sure" dialog pops up, because this is counted as a warning, even though it doesn't come from the compiler.

**Comment by vlad20012** [comment]
Hmm, they should be `TyTypeParameter.self()`
