### ISSUE TITLE
Estimate the number of users who are on 15.0.4

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#418]
Looks like supporting 15.0.4 causes a bunch of non-trivial issues, #417 being the latest and, hopefully, the last one. 

I have a strong suspicion that there are exactly 0 users who use 15.0.4 with IntelliJ Rust. It has been broken for quite a while, but not a single issue was reported. In contrast, when 15.0.5 had been broken, we got [a report](https://github.com/intellij-rust/intellij-rust/issues/378) pretty soon.

**Comment by matklad** [comment]
> It has been broken for quite a while, 

Hm, this may or may not be a lie. I don't know specifically when 15.0.4 got broken but 15.0.5 was working.

**Comment by alexeykudinkin** [comment]
First of all, we'd not (and definitely will not in the future) drop support just out of guess. The only reasonable source of ceirtainty for such a case would be reported statistic which we do not have yet.

Second, it's not that `15.0.4` is _that_ paramount for us, it's just a good opportunity to establish the whole process of maintaining compatibility across IDEA updates (and Kotlin of course).

**Comment by alexeykudinkin** [comment]
#417 should be reported directly to @zolotov, since binding UI forms with the code null-/non-null-checks instrumentation seems bizarre.
