### ISSUE TITLE
Jump from test results to doctest leads to unexpected position

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#4208]
## Environment

* **IntelliJ Rust plugin version:** 0.2.103.2698-192-nightly
* **Rust toolchain version:** rustc 1.36.0 (a53f9df32 2019-07-03)
* **IDE name and version:** CLion 2019.3 Nightly 193.1846
* **Operating system:** macOS 10.14.4

## Problem description

I am running some doctests and trying to jump from the test results back to doctest declaration, unfortunately the resulting goto line is not quite correct.

## Steps to reproduce

- Consider the following code from a library package

```rust
/// Reversed Words
/// https://www.codewars.com/kata/reversed-words
///
/// Complete the solution so that it reverses all of the words within the string
/// passed in.
///
/// # Examples
///
/// ```
/// # use rust_codewars::kyu8::reversed_words;
///
/// let words = "The greatest victory is that which requires no battle";
/// let result = reversed_words::reverse_words(words);
///
/// assert_eq!(result, "battle no requires which that is victory greatest The");
/// ```
///
pub fn reverse_words(str: &str) -> String {
    str.split_whitespace()
        .rev()
        .collect::<Vec<&str>>()
        .join(" ")
}
```

- run `cargo test` run configuration
- try to jump from the test result tree to a doctest
- line 17 is focused, while I expect 8

<img width="806" alt="tests" src="https://user-images.githubusercontent.com/2500320/62275384-7d0b8f80-b44a-11e9-9aaa-09568e7148de.png">

**Comment by Undin** [comment]
Combination of the current psi for doc comments (single psi node) and API for navigation from test result tree to the corresponding element makes desired navigation impossible.
But looks like after creation full ast tree according to markdown grammar rules it will be possible

CC @mchernyavsky

**Comment by mchernyavsky** [comment]
@Undin What can we do in this situation?

<img width="300" alt="screen" src="https://user-images.githubusercontent.com/6079006/62333545-8f2e1200-b4cc-11e9-8ec6-55af7afa905a.png">

**Comment by Undin** [comment]
I don't see a lot of variants in such case. I suppose we will navigate to wrong line.
BTW we already have a similar situation when you change name or location of test function or module after test running.
Don't think that it's an important issue because I believe you change test code and navigate to it from prev test result quite rarely
