### ISSUE TITLE
Reexports fail to resolve

### ISSUE THREAD

**Issue by ishitatsuyuki** [intellij-rust/intellij-rust#4209]
## Environment

* **IntelliJ Rust plugin version:** 0.2.103.2698-192-nightly
* **Rust toolchain version:** 1.38.0-nightly
* **IDE name and version:** IDEA Ultimate 2019.2
* **Operating system:** Linux (Arch)

## Problem description

Reexports of a crate with `pub use` (utilizing Rust 2018) does not work when it's in a crate. `pub use` in a project works fine. (Nesting may also be involved in conditions - try with the concrete example below.)

Concrete example: `amethyst::renderer::rendy` completely fails to resolve. However, resolution and navigation is fixed after the following patch to Amethyst:

```
diff --git a/amethyst_rendy/src/lib.rs b/amethyst_rendy/src/lib.rs
index b1d9fb2e..7a7a025a 100644
--- a/amethyst_rendy/src/lib.rs
+++ b/amethyst_rendy/src/lib.rs
@@ -51,13 +51,13 @@ extern crate amethyst_derive;
 #[macro_use]
 extern crate shred_derive;
 
+pub extern crate rendy;
+
 #[macro_use]
 mod macros;
 
 #[doc(inline)]
 pub use palette;
-#[doc(inline)]
-pub use rendy;
 
 pub mod pass;

```

Note that `pub extern crate` is also just fixed recently, so it may be a good idea to try on a nightly version of the plugin.

## Steps to reproduce

Sample project: https://github.com/amethyst/amethyst-starter-2d

Use statements under `amethyst::renderer::rendy` in `src/render.rs` is "dead".

**Comment by vvilhonen** [comment]
Still happening with 
 
* **IntelliJ Rust plugin version:** 0.2.122.3105-201
 
* **Rust toolchain version:** 1.43.1
 
* **IDE name and version:** IDEA Ultimate 2020.1.1
 
* **Operating system:** MacOS 10.15.4

**Comment by Undin** [comment]
Looks like it fixed now so I close this issue
