### ISSUE TITLE
Make RustModulesIndex independent of CargoProjectWorkspace.

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#421]
Currently, `RustModulesIndex` depends on `CargoProjectWorkspace`, because key in the index is `RustCratePath`.This is problematic, because the index becomes invalid once workspace data is updated. Here is a [slight modification] of `CargoProjectResolveTestCase` which demonstrates the issue. It is also pretty visible when working with real projects. 

The core of the problem is that `ModuleIndex` violates

>The data returned by DataIndexer.map() must depend only on input data passed to the method, and must not depend on any external files. Otherwise your index will not be correctly updated when the external data changes, and you will have stale data in your index.

contract. This can be avoided by using `FileIncludeIndex` trick: store a name as a key and a referece offest as a value in the index and get the final result by resolving the reference at offeset. Also with some effort I can get rid of the JarFileSystem, so that we should be able to use `FileIncludeIndex` directly. 

[slight modification]: https://github.com/intellij-rust/intellij-rust/commit/b67bf90c05d9bd54bd449a174b7e0d777af266b0

**Comment by alexeykudinkin** [comment]
This can't be avoided by relying on `FileIncludeIndex`: it would simply store the very same stale data.

**Comment by alexeykudinkin** [comment]
We need to bind index to the `CargoProjectWorkspace` lifetime directly, there seem no other option.

**Comment by matklad** [comment]
> We need to bind index to the CargoProjectWorkspace lifetime directly, there seem to be no other option.

I believe there is such an option. I'll try to implement this, maybe I'll hit a roadblock along the way though. 

Tying index lifetime to Workspace would be unfortunate: it's better not to reindex the standard library when the user modifies `Cargo.toml`.
