### ISSUE TITLE
deprecated trait objects 

### ISSUE THREAD

**Issue by lovasoa** [intellij-rust/intellij-rust#4216]
## Environment

* **IntelliJ Rust plugin version:** 0.2.102.2130-192
* **Rust toolchain version:** 1.36.0 (a53f9df32 2019-07-03) x86_64-apple-darwin
* **IDE name and version:** IC-192.5728.98
* **Operating system:** macOS 10.14.6

## Problem description
`Self`in return position on traits triggers a `Trait objects without an explicit 'dyn' are deprecated` warning.

## Steps to reproduce

```rust
pub trait Default {
    fn default() -> Self;
}
```

In this valid code, `Self` is highlighted with a deprecation warning.

This may have already been reported and fixed in #4174, but I'm not sure. Feel free to close the issue if it's already fixed on the master branch; I tested only with the latest released version of the plugin.

**Comment by mchernyavsky** [comment]
Yes, it's already fixed.
