### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by stevenkucera** [intellij-rust/intellij-rust#422]
The Project Structure tool window parses great, but forgets its position when you move to another file. Is it possible to memorise for each file, the scrollbar position as well as which nodes have been opened and which have been closed?

Steve

**Comment by matklad** [comment]
Are you sure that you are describing Project Structure and not File Structure?

![file_vs_project](https://cloud.githubusercontent.com/assets/1711539/15563623/02e7d95a-2313-11e6-94b0-dc9a4e1724c8.png)

File Structure is on the left, and Project Structure is on the right.

Project structure does remember its state. Structure view does not remember its state, but this is not the thing we can fix in the plugin. Here is a platform [issue](https://youtrack.jetbrains.com/issue/IDEA-82694), though it is not implemented yet.

**Comment by stevenkucera** [comment]
Whoops, I meant File Structure. A pity this hasn't been fixed, it makes the File Structure next to useless for a large file.
