### ISSUE TITLE
Create action "Go to reference type definition"

### ISSUE THREAD

**Issue by sirgl** [intellij-rust/intellij-rust#4221]
In rust many types are inferred and are not present explicitly in text.
It would be very good if when the cursor is on the reference, there would be additional action in context menu to go to type definition.

```rust
struct A;

fn foo() -> A{unimplemented!()}

fn bar() {
  let x = foo();
  x<|>  // on apply "Go to reference type definition" we go to A
}
```
This action will help those ones, who doesn't use mouse, as they may assign keybinding for this action.

**Comment by dvtomas** [comment]
Ctrl-Shift-B
