### ISSUE TITLE
impl Trait as return type of nested function

### ISSUE THREAD

**Issue by fan-tom** [intellij-rust/intellij-rust#4233]
## Environment

* **IntelliJ Rust plugin version:** 0.2.102.2130-192
* **Rust toolchain version:** 1.37.0-nightly (433a46781 2019-06-28) x86_64-apple-darwin
* **IDE name and version:** CL-192.5728.100
* **Operating system:** macOS 10.14.4

## Problem description
When `impl Trait` is used in nested function return type position, plugin reports

![изображение](https://user-images.githubusercontent.com/14140464/62783216-6235bc80-bad5-11e9-9b8e-32fc3f991ddd.png)

**Comment by mchernyavsky** [comment]
> When impl Trait is used in nested function return type position, plugin reports

I can't reproduce it on this code:
```rust
struct S;
trait T {}
impl T for S {}

fn main() {
    fn foo() -> impl T { S }
}
```

**Comment by fan-tom** [comment]
Seems that you need to combine trait impl and closure
<img width="611" alt="изображение" src="https://user-images.githubusercontent.com/14140464/62840003-ebebb280-bcac-11e9-8dbb-79fc91f921ea.png">


```rust
struct Foo;

trait Trait {
    fn qaz();
}

trait Test {
    type T;
}

impl Test for u32 {
    type T = ();
}

impl Trait for Foo {
    fn qaz() {
        let baz = vec![].into_iter().map(|_: ()| {
            fn bar() -> impl Test<T=()> {
                1u32
            }
        });
    }
}

```
