### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by alexeykudinkin** [intellij-rust/intellij-rust#424]
```
MVP
    Core
        [x] Lexing
        [x] - Raw Literals

        [x] Parsing

        [x] Resolve
        [x] - Fully-qualified names

    IDE
        [x] Navigation
        [x] - Goto Everything

        [x] Basic completion

v0.1
    Core
        [ ] Type-system support (initial)
        [ ] - Resolved/unresolved typing
        [ ] - Inference (initial)

    IDE
        [ ] Core Language Inspections (initial)
        [ ] - Unresolved symbols
        [ ] - ?


v0.5
    Core
        [ ] Borrower (initial)
        [ ] Type-system support (complete)
        [ ] - Inference (complete)

    IDE
        [ ] Core Language Inspections (complete)
        [ ] - Types-induced errors
        [ ] - ?

        [ ] Find Usages

        [ ] Completion
        [ ] - Smart?


v1.0
    Core
        [ ] Borrower (complete)

    IDE
        [ ] Refactorings
        [ ] - Rename
        [ ] - Extract method (bound to CF)
        [ ] - Extract variable
        [ ] - Extract type/trait/impl (?)

        [ ] Testing

        [ ] Debugger 

v2.0
    Core
        [ ] Control flow

    IDE
        [ ] Advanced Inspections
```

**Comment by laktak** [comment]
This is the only place that mentions a debugger. Can we vote for features?

Debugger +1

**Comment by matklad** [comment]
@laktak here, I've created an issue for this: https://github.com/intellij-rust/intellij-rust/issues/535. It's mainly for voting because debugger is further down the roadmap.

**Comment by chriskrycho** [comment]
Quick request: can you good folks convert the code block above to be a standard list, so that this shows up as actual GitHub tasks/checkboxes? That would have the really nice side effect of giving an immediate visual representation on this issue of how far along the roadmap the project is.

**Comment by matklad** [comment]
@chriskrycho I think this is a too coarse grained check list to be able to use it as a progress indicator. Creating milestones for shorter goals might be a good idea though.

**Comment by Undin** [comment]
This roadmap is outdated. Let's close it
