### ISSUE TITLE
Many Errors are Not Displayed

### ISSUE THREAD

**Issue by naftulikay** [intellij-rust/intellij-rust#4260]
#### IntelliJ Rust Plugin Version

```
0.2.103.2131-192
```

#### Rust Toolchain Version

```
stable-x86_64-unknown-linux-gnu unchanged - rustc 1.36.0 (a53f9df32 2019-07-03)
```

#### IDE Name and Version

```
PyCharm 2019.2 (Community Edition)
Build #PC-192.5728.105, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-48-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: 
Non-Bundled Plugins: org.intellij.plugins.markdown, org.toml.lang, org.rust.lang
```

#### Operating System

```
Linux axel 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## Problem description

![Screenshot from 2019-08-14 11 33 38](https://user-images.githubusercontent.com/347571/63046499-63753980-be87-11e9-84c1-8573ea8bd941.png)

Obviously broken code gets no highlighting or any indication that there is an error. Code completion works exactly as expected and everything else seems fine, but many compilation errors just simply don't show up. It is inconsistent as to what shows and what doesn't.

The yellow highlighting above simply suggests simplifying my code rather than it being an actual warning or an error.

## Steps to reproduce

```rust
pub struct Jabronie;

impl Jabronie {
    pub fn new() -> Self {
        println!("{}", THIS_DOES_NOT_EXIST);
    }
}
```

This code is broken in that

 1. `new` does not return anything
 2. `THIS_DOES_NOT_EXIST` is a variable that does not exist.

I don't see any error highlighting telling me that something is wrong here.

**Comment by mchernyavsky** [comment]
Select **"Run external linter to analyze code on the fly"** from `Preferences > Languages & Frameworks > Rust > Cargo`.

https://www.jetbrains.com/help/clion/rust-support.html#project-settings

**Comment by naftulikay** [comment]
@mchernyavsky that fixed it.

Honest question: why isn't this enabled by default?

**Comment by mchernyavsky** [comment]
@naftulikay It works too slow on large projects.
