### ISSUE TITLE
Code analysis disabled when using a crate in subfolder of another crate

### ISSUE THREAD

**Issue by reuvenpo** [intellij-rust/intellij-rust#4273]
Sorry if this is a duplicate, I couldn't find anyone else reporting this issue.

## Environment

* **IntelliJ Rust plugin version:** 0.2.103.2131-192
* **Rust toolchain version:** cargo 1.36.0-nightly (c4fcfb725 2019-05-15)
* **IDE name and version:** Clion 2019.2
* **Operating system:** Pop!_OS 18.04

## Problem description
When creating a crate within another crate, if files from the first crate are associated with its `Cargo.toml` file, then when viewing the files of the inner crate, the IDE displays the following message:

> File is not included in module tree, analysis is not available ------- [Do not show again]

In the following directory tree, the message is seen when opening the file at `libfoo/derive/src/lib.rs`

```
libfoo
├── Cargo.toml
├── derive
│   ├── Cargo.toml
│   └── src
│       └── lib.rs
└── src
    └── lib.rs
```

**Comment by mibac138** [comment]
Do you have the following in `libfoo/Cargo.toml`?
```toml
[workspace]
members = [ "derive" ]
```

**Comment by reuvenpo** [comment]
Nevermind, i just found out i can control which folders are considered Cargo folders through the "Cargo" tab on the right hand side of the editor window.

For the record, i'm not using a workspace at the moment (although i think i should)
