### ISSUE TITLE
Autocomplete not working with associated types

### ISSUE THREAD

**Issue by ufoscout** [intellij-rust/intellij-rust#4277]
## Environment

* **IntelliJ Rust plugin version:**
0.2.103.2131-192

* **Rust toolchain version:**
rustc 1.36.0 (a53f9df32 2019-07-03)

* **IDE name and version:**
Intellij IntelliJ IDEA 2019.2 (Community Edition)

* **Operating system:**
Ubuntu 18.04 64bit

## Problem description
The autocomplete does not work for struct fields whose type is an associated type of a generic parameter.

## Steps to reproduce

Here a complete reproducer:

```rust

pub trait Connection {
    fn get_conn(&self);
}

// The trait Pool has an associated type CONN which is a Connection
pub trait Pool {
    type CONN: Connection;
    fn get_pool(&self);
}

// The struct UsePool has a field whose type is set to POOL::CONN
pub struct UsePool<POOL: Pool> {
    pool: POOL,
    conn: POOL::CONN,
}

impl <POOL: Pool> UsePool<POOL> {

    pub fn do_smt(&self) {
        self.pool.get_pool(); // get_pool() is autocompleted correctly

        // Since POOL::CONN is of type 'Connection', the IDE should 
        // autocomplete the method 'get_conn()' but this does not happen
        self.conn.get_conn(); // <-- get_conn() IS NOT AUTOCOMPLETED
    }

}
```

**Comment by ortem** [comment]
This seems to be fixed

**Comment by likeabbas** [comment]
I am still seeing this issue with 
* rust version 1.60.0-nightly (a7e2e3396 2022-01-08)
* CLion rust plugin  0.4.163.4354-213-nightly
* CLion 2021.3.2 Build #CL-213.6461.75
* MacOs Catalina 10.15.7 
<img width="407" alt="Screen Shot 2022-01-09 at 4 37 19 PM" src="https://user-images.githubusercontent.com/6827281/148702002-456d63a5-aff4-48a1-bdcd-ad2e581ea023.png">
