### ISSUE TITLE
More descriptive goto class

### ISSUE THREAD

**Issue by mfarrugi** [intellij-rust/intellij-rust#428]
![gotoclass](https://cloud.githubusercontent.com/assets/2286456/15628578/4961eb8a-24d2-11e6-940f-cf8548526d42.png)

Should be something more like
```
Client (in hyper/client/mod.rs)
Client (in solicit/client/async.rs)
Client (in websocket/client/mod.rs)
```

or 

```
Client (hyper::client::Client)
Client (solicit::client::async::Client)
Client (websocket::Client)
```

**Comment by matklad** [comment]
Fixed in https://github.com/intellij-rust/intellij-rust/commit/bf96463527bd11de259f47e6e99a49b829ac57b0
