### ISSUE TITLE
Format-on-save fails with rustup error: "Found argument '--installed' which wasn't expected, or isn't valid in this context"

### ISSUE THREAD

**Issue by HighCommander4** [intellij-rust/intellij-rust#4281]
## Environment

* **IntelliJ Rust plugin version:** 0.2.103.2131-192
* **Rust toolchain version:** 1.31.1
* **IDE name and version:** IDEA Community 2019.2
* **Operating system:** Linux

## Problem description

After a recent plugin update, format-on-save started to fail, giving an error on each save.

The event log shows:

```
Rustfmt is not installed
Install
```

Clicking on "Install" has no effect, the error comes back on the next save.

The following output appears on the command line:

```
WARN - rust.openapiext.CommandLineExt -         Execution failed (exit code 1).
        /home/nr/.cargo/bin/rustup component list --installed
        stdout :
        stderr : error: Found argument '--installed' which wasn't expected, or isn't valid in this context
```

**Comment by Igosuki** [comment]
I have the same error, while for me this command works in the terminal : 
`rustup component list --installed` so not sure if that is the real cause

**Comment by mchernyavsky** [comment]
@HighCommander4 Can you please run `rustup self update` and let me know if it helps?

@Igosuki Can you run `rustup --version` from [terminal emulator](https://www.jetbrains.com/help/idea/terminal-emulator.html) and show the output?

**Comment by HighCommander4** [comment]
Thanks, I can confirm that `rustup self update` solves the problem.
