### ISSUE TITLE
Intellij-rust should stop external linter before running

### ISSUE THREAD

**Issue by sirgl** [intellij-rust/intellij-rust#4283]
Now if project is big enough and complex, external linter works not that fast.
AFAIU, cargo takes lock on directory when running `cargo check`, so when I run application, I have to wait until `cargo check` completes.
![image](https://user-images.githubusercontent.com/11944514/63349838-75bf0e00-c386-11e9-9479-a2273abd9ce7.png)

## Environment

* **IntelliJ Rust plugin version:** 0.2.103.2131-192
* **Rust toolchain version:** 1.39.0-nightly (29a54035c 2019-08-19) x86_64-apple-darwin
* **IDE name and version:** CL-192.5728.100
* **Operating system:** macOS 10.14.5

**Comment by mchernyavsky** [comment]
I'm not sure we can safely kill `cargo check`: https://github.com/rust-lang/rust-clippy/issues/3890
