### ISSUE TITLE
Renaming metavariable in macros do nothing

### ISSUE THREAD

**Issue by sirgl** [intellij-rust/intellij-rust#4285]
After inplace rename idea doesn't save changes.
![2019-08-20 20 28 04](https://user-images.githubusercontent.com/11944514/63351345-4231b300-c389-11e9-9107-3e8c15efecd3.gif)

code:
```rust
macro_rules! my_macro {
    ($x:ex) => {$x};
}
```

## Environment

* **IntelliJ Rust plugin version:** 0.2.103.2131-192
* **Rust toolchain version:** 1.39.0-nightly (29a54035c 2019-08-19) x86_64-apple-darwin
* **IDE name and version:** CL-192.5728.100
* **Operating system:** macOS 10.14.5

**Comment by Nashenas88** [comment]
I'm also experiencing this

## Environment
- **IntelliJ Rust plugin version:** `0.2.109.2149-192`
- **Rust toolchain version:** `rustc 1.40.0-nightly (91fd6283e 2019-11-02)`
- **IDE name and version:** `Build #IC-192.7142.36, built on October 29, 2019`
- **Operating system**: `Linux pop-os 5.3.0-20-generic #21+system76~1572304854~19.10~8caa3e6-Ubuntu SMP Tue Oct 29 00:4 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by mili-l** [comment]
see https://github.com/intellij-rust/intellij-rust/pull/9729

**Comment by Undin** [comment]
@mili-l it isn't related to proc macro expansion. It was fixed by #8998
