### ISSUE TITLE
Build tool window does not display anything

### ISSUE THREAD

**Issue by ice1000** [intellij-rust/intellij-rust#4288]
## Environment

* **IntelliJ Rust plugin version:** same as #4286 

## Problem description

<details>
<pre>
C:/Users/ice10/.cargo/bin/cargo.exe build --color=always --package voile --bin voilec --message-format=json
   Compiling voile v0.1.1 (C:\Users\ice10\git-repos\ProofAssistants\voile-rs)
{"reason":"compiler-message","package_id":"voile 0.1.1 (path+file:///C:/Users/ice10/git-repos/ProofAssistants/voile-rs)","target":{"kind":["lib"],"crate_types":["lib"],"name":"voile","src_path":"C:\\Users\\ice10\\git-repos\\ProofAssistants\\voile-rs\\src/lib.rs","edition":"2018","doctest":true},"message":{"rendered":"error[E0004]: non-exhaustive patterns: `Rec(_, _)` not covered\n   --> src\\syntax\\core\\ast.rs:269:15\n    |\n217 | / pub enum Neutral {\n218 | |     /// Local variable, referred by de-bruijn index.\n219 | |     Var(DBI),\n220 | |     /// Global variable, referred by index. Needed for recursive definitions.\n...   |\n241 | |     Rec(Fields, Box<Self>),\n    | |     --- not covered\n242 | | }\n    | |_- `syntax::core::ast::Neutral` defined here\n...\n269 |           match self {\n    |                 ^^^^ pattern `Rec(_, _)` not covered\n    |\n    = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms\n\n","children":[{"children":[],"code":null,"level":"help","message":"ensure that all possible cases are being handled, possibly by adding wildcards or more match arms","rendered":null,"spans":[]}],"code":{"code":"E0004","explanation":"\nThis error indicates that the compiler cannot guarantee a matching pattern for\none or more possible inputs to a match expression. Guaranteed matches are\nrequired in order to assign values to match expressions, or alternatively,\ndetermine the flow of execution. Erroneous code example:\n\n```compile_fail,E0004\nenum Terminator {\n    HastaLaVistaBaby,\n    TalkToMyHand,\n}\n\nlet x = Terminator::HastaLaVistaBaby;\n\nmatch x { // error: non-exhaustive patterns: `HastaLaVistaBaby` not covered\n    Terminator::TalkToMyHand => {}\n}\n```\n\nIf you encounter this error you must alter your patterns so that every possible\nvalue of the input type is matched. For types with a small number of variants\n(like enums) you should probably cover all cases explicitly. Alternatively, the\nunderscore `_` wildcard pattern can be added after all other patterns to match\n\"anything else\". Example:\n\n```\nenum Terminator {\n    HastaLaVistaBaby,\n    TalkToMyHand,\n}\n\nlet x = Terminator::HastaLaVistaBaby;\n\nmatch x {\n    Terminator::TalkToMyHand => {}\n    Terminator::HastaLaVistaBaby => {}\n}\n\n// or:\n\nmatch x {\n    Terminator::TalkToMyHand => {}\n    _ => {}\n}\n```\n"},"level":"error","message":"non-exhaustive patterns: `Rec(_, _)` not covered","spans":[{"byte_end":9
439,"byte_start":9435,"column_end":19,"column_start":15,"expansion":null,"file_name":"src\\syntax\\core\\ast.rs","is_primary":true,"label":"pattern `Rec(_, _)` not covered","line_end":269,"line_start":269,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":19,"highlight_start":15,"text":"        match self {"}]},{"byte_end":8559,"byte_start":7650,"column_end":2,"column_start":1,"expansion":null,"file_name":"src\\syntax\\core\\ast.rs","is_primary":false,"label":"`syntax::core::ast::Neutral` defined here","line_end":242,"line_start":217,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":19,"highlight_start":1,"text":"pub enum Neutral {"},{"highlight_end":53,"highlight_start":1,"text":"    /// Local variable, referred by de-bruijn index."},{"highlight_end":14,"highlight_start":1,"text":"    Var(DBI),"},{"highlight_end":78,"highlight_start":1,"text":"    /// Global variable, referred by index. Needed for recursive definitions."},{"highlight_end":13,"highlight_start":1,"text":"    Ref(GI),"},{"highlight_end":33,"highlight_start":1,"text":"    /// Meta variable reference."},{"highlight_end":14,"highlight_start":1,"text":"    Meta(MI),"},{"highlight_end":46,"highlight_start":1,"text":"    /// Lifting self to a higher/lower level."},{"highlight_end":26,"highlight_start":1,"text":"    Lift(u32, Box<Self>),"},{"highlight_end":38,"highlight_start":1,"text":"    /// Postulated value, aka axioms."},{"highlight_end":16,"highlight_start":1,"text":"    Axi(Axiom),"},{"highlight_end":59,"highlight_start":1,"text":"    /// Function application, with all arguments collected"},{"highlight_end":64,"highlight_start":1,"text":"    /// (so we have easy access to application arguments).<br/>"},{"highlight_end":70,"highlight_start":1,"text":"    /// This is convenient for meta resolution and termination check."},{"highlight_end":8,"highlight_start":1,"text":"    ///"},{"highlight_end":53,"highlight_start":1,"text":"    /// The \"arguments\" is supposed to be non-empty."},{"highlight_end":30,"highlight_start":1,"text":"    App(Box<Self>, Vec<Val>),"},{"highlight_end":48,"highlight_start":1,"text":"    /// Projecting the first element of a pair."},{"highlight_end":20,"highlight_start":1,"text":"    Fst(Box<Self>),"},{"highlight_end":49,"highlight_start":1,"text":"    /// Projecting the second element of a pair."},{"highlight_end":20,"highlight_start":1,"text":"    Snd(Box<Self>),"},{"highlight_end":31,"highlight_sta
rt":1,"text":"    /// Row-polymorphic types."},{"highlight_end":38,"highlight_start":1,"text":"    Row(VarRec, Variants, Box<Self>),"},{"highlight_end":40,"highlight_start":1,"text":"    /// Record literal, with extension."},{"highlight_end":28,"highlight_start":1,"text":"    Rec(Fields, Box<Self>),"},{"highlight_end":2,"highlight_start":1,"text":"}"}]},{"byte_end":8537,"byte_start":8534,"column_end":8,"column_start":5,"expansion":null,"file_name":"src\\syntax\\core\\ast.rs","is_primary":false,"label":"not covered","line_end":241,"line_start":241,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":8,"highlight_start":5,"text":"    Rec(Fields, Box<Self>),"}]}]}}
{"reason":"compiler-message","package_id":"voile 0.1.1 (path+file:///C:/Users/ice10/git-repos/ProofAssistants/voile-rs)","target":{"kind":["lib"],"crate_types":["lib"],"name":"voile","src_path":"C:\\Users\\ice10\\git-repos\\ProofAssistants\\voile-rs\\src/lib.rs","edition":"2018","doctest":true},"message":{"rendered":"error[E0004]: non-exhaustive patterns: `Rec(_, _)` not covered\n   --> src\\syntax\\core\\ast.rs:298:15\n    |\n217 | / pub enum Neutral {\n218 | |     /// Local variable, referred by de-bruijn index.\n219 | |     Var(DBI),\n220 | |     /// Global variable, referred by index. Needed for recursive definitions.\n...   |\n241 | |     Rec(Fields, Box<Self>),\n    | |     --- not covered\n242 | | }\n    | |_- `syntax::core::ast::Neutral` defined here\n...\n298 |           match self {\n    |                 ^^^^ pattern `Rec(_, _)` not covered\n    |\n    = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms\n\n","children":[{"children":[],"code":null,"level":"help","message":"ensure that all possible cases are being handled, possibly by adding wildcards or more match arms","rendered":null,"spans":[]}],"code":{"code":"E0004","explanation":"\nThis error indicates that the compiler cannot guarantee a matching pattern for\none or more possible inputs to a match expression. Guaranteed matches are\nrequired in order to assign values to match expressions, or alternatively,\ndetermine the flow of execution. Erroneous code example:\n\n```compile_fail,E0004\nenum Terminator {\n    HastaLaVistaBaby,\n    TalkToMyHand,\n}\n\nlet x = Terminator::HastaLaVistaBaby;\n\nmatch x { // error: non-exhaustive patterns: `HastaLaVistaBaby` not covered\n    Terminator::TalkToMyHand => {}\n}\n```\n\nIf you encounter this error you must alter your patterns so that every possible\nvalue of the input type is matched. For types with a small number of variants\n(like enums) you should probably cover all cases explicitly. Alternatively, the\nunderscore `_` wildcard pattern can be added after all other patterns to match\n\"anything else\". Example:\n\n```\nenum Terminator {\n    HastaLaVistaBaby,\n    TalkToMyHand,\n}\n\nlet x = Terminator::HastaLaVistaBaby;\n\nmatch x {\n    Terminator::TalkToMyHand => {}\n    Terminator::HastaLaVistaBaby => {}\n}\n\n// or:\n\nmatch x {\n    Terminator::TalkToMyHand => {}\n    _ => {}\n}\n```\n"},"level":"error","message":"non-exhaustive patterns: `Rec(_, _)` not covered","spans":[{"byte_end":1
0489,"byte_start":10485,"column_end":19,"column_start":15,"expansion":null,"file_name":"src\\syntax\\core\\ast.rs","is_primary":true,"label":"pattern `Rec(_, _)` not covered","line_end":298,"line_start":298,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":19,"highlight_start":15,"text":"        match self {"}]},{"byte_end":8559,"byte_start":7650,"column_end":2,"column_start":1,"expansion":null,"file_name":"src\\syntax\\core\\ast.rs","is_primary":false,"label":"`syntax::core::ast::Neutral` defined here","line_end":242,"line_start":217,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":19,"highlight_start":1,"text":"pub enum Neutral {"},{"highlight_end":53,"highlight_start":1,"text":"    /// Local variable, referred by de-bruijn index."},{"highlight_end":14,"highlight_start":1,"text":"    Var(DBI),"},{"highlight_end":78,"highlight_start":1,"text":"    /// Global variable, referred by index. Needed for recursive definitions."},{"highlight_end":13,"highlight_start":1,"text":"    Ref(GI),"},{"highlight_end":33,"highlight_start":1,"text":"    /// Meta variable reference."},{"highlight_end":14,"highlight_start":1,"text":"    Meta(MI),"},{"highlight_end":46,"highlight_start":1,"text":"    /// Lifting self to a higher/lower level."},{"highlight_end":26,"highlight_start":1,"text":"    Lift(u32, Box<Self>),"},{"highlight_end":38,"highlight_start":1,"text":"    /// Postulated value, aka axioms."},{"highlight_end":16,"highlight_start":1,"text":"    Axi(Axiom),"},{"highlight_end":59,"highlight_start":1,"text":"    /// Function application, with all arguments collected"},{"highlight_end":64,"highlight_start":1,"text":"    /// (so we have easy access to application arguments).<br/>"},{"highlight_end":70,"highlight_start":1,"text":"    /// This is convenient for meta resolution and termination check."},{"highlight_end":8,"highlight_start":1,"text":"    ///"},{"highlight_end":53,"highlight_start":1,"text":"    /// The \"arguments\" is supposed to be non-empty."},{"highlight_end":30,"highlight_start":1,"text":"    App(Box<Self>, Vec<Val>),"},{"highlight_end":48,"highlight_start":1,"text":"    /// Projecting the first element of a pair."},{"highlight_end":20,"highlight_start":1,"text":"    Fst(Box<Self>),"},{"highlight_end":49,"highlight_start":1,"text":"    /// Projecting the second element of a pair."},{"highlight_end":20,"highlight_start":1,"text":"    Snd(Box<Self>),"},{"highlight_end":31,"highlight_s
tart":1,"text":"    /// Row-polymorphic types."},{"highlight_end":38,"highlight_start":1,"text":"    Row(VarRec, Variants, Box<Self>),"},{"highlight_end":40,"highlight_start":1,"text":"    /// Record literal, with extension."},{"highlight_end":28,"highlight_start":1,"text":"    Rec(Fields, Box<Self>),"},{"highlight_end":2,"highlight_start":1,"text":"}"}]},{"byte_end":8537,"byte_start":8534,"column_end":8,"column_start":5,"expansion":null,"file_name":"src\\syntax\\core\\ast.rs","is_primary":false,"label":"not covered","line_end":241,"line_start":241,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":8,"highlight_start":5,"text":"    Rec(Fields, Box<Self>),"}]}]}}
{"reason":"compiler-message","package_id":"voile 0.1.1 (path+file:///C:/Users/ice10/git-repos/ProofAssistants/voile-rs)","target":{"kind":["lib"],"crate_types":["lib"],"name":"voile","src_path":"C:\\Users\\ice10\\git-repos\\ProofAssistants\\voile-rs\\src/lib.rs","edition":"2018","doctest":true},"message":{"rendered":"error[E0004]: non-exhaustive patterns: `Rec(_, _)` not covered\n   --> src\\syntax\\core\\ast.rs:323:15\n    |\n217 | / pub enum Neutral {\n218 | |     /// Local variable, referred by de-bruijn index.\n219 | |     Var(DBI),\n220 | |     /// Global variable, referred by index. Needed for recursive definitions.\n...   |\n241 | |     Rec(Fields, Box<Self>),\n    | |     --- not covered\n242 | | }\n    | |_- `syntax::core::ast::Neutral` defined here\n...\n323 |           match self {\n    |                 ^^^^ pattern `Rec(_, _)` not covered\n    |\n    = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms\n\n","children":[{"children":[],"code":null,"level":"help","message":"ensure that all possible cases are being handled, possibly by adding wildcards or more match arms","rendered":null,"spans":[]}],"code":{"code":"E0004","explanation":"\nThis error indicates that the compiler cannot guarantee a matching pattern for\none or more possible inputs to a match expression. Guaranteed matches are\nrequired in order to assign values to match expressions, or alternatively,\ndetermine the flow of execution. Erroneous code example:\n\n```compile_fail,E0004\nenum Terminator {\n    HastaLaVistaBaby,\n    TalkToMyHand,\n}\n\nlet x = Terminator::HastaLaVistaBaby;\n\nmatch x { // error: non-exhaustive patterns: `HastaLaVistaBaby` not covered\n    Terminator::TalkToMyHand => {}\n}\n```\n\nIf you encounter this error you must alter your patterns so that every possible\nvalue of the input type is matched. For types with a small number of variants\n(like enums) you should probably cover all cases explicitly. Alternatively, the\nunderscore `_` wildcard pattern can be added after all other patterns to match\n\"anything else\". Example:\n\n```\nenum Terminator {\n    HastaLaVistaBaby,\n    TalkToMyHand,\n}\n\nlet x = Terminator::HastaLaVistaBaby;\n\nmatch x {\n    Terminator::TalkToMyHand => {}\n    Terminator::HastaLaVistaBaby => {}\n}\n\n// or:\n\nmatch x {\n    Terminator::TalkToMyHand => {}\n    _ => {}\n}\n```\n"},"level":"error","message":"non-exhaustive patterns: `Rec(_, _)` not covered","spans":[{"byte_end":1
1563,"byte_start":11559,"column_end":19,"column_start":15,"expansion":null,"file_name":"src\\syntax\\core\\ast.rs","is_primary":true,"label":"pattern `Rec(_, _)` not covered","line_end":323,"line_start":323,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":19,"highlight_start":15,"text":"        match self {"}]},{"byte_end":8559,"byte_start":7650,"column_end":2,"column_start":1,"expansion":null,"file_name":"src\\syntax\\core\\ast.rs","is_primary":false,"label":"`syntax::core::ast::Neutral` defined here","line_end":242,"line_start":217,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":19,"highlight_start":1,"text":"pub enum Neutral {"},{"highlight_end":53,"highlight_start":1,"text":"    /// Local variable, referred by de-bruijn index."},{"highlight_end":14,"highlight_start":1,"text":"    Var(DBI),"},{"highlight_end":78,"highlight_start":1,"text":"    /// Global variable, referred by index. Needed for recursive definitions."},{"highlight_end":13,"highlight_start":1,"text":"    Ref(GI),"},{"highlight_end":33,"highlight_start":1,"text":"    /// Meta variable reference."},{"highlight_end":14,"highlight_start":1,"text":"    Meta(MI),"},{"highlight_end":46,"highlight_start":1,"text":"    /// Lifting self to a higher/lower level."},{"highlight_end":26,"highlight_start":1,"text":"    Lift(u32, Box<Self>),"},{"highlight_end":38,"highlight_start":1,"text":"    /// Postulated value, aka axioms."},{"highlight_end":16,"highlight_start":1,"text":"    Axi(Axiom),"},{"highlight_end":59,"highlight_start":1,"text":"    /// Function application, with all arguments collected"},{"highlight_end":64,"highlight_start":1,"text":"    /// (so we have easy access to application arguments).<br/>"},{"highlight_end":70,"highlight_start":1,"text":"    /// This is convenient for meta resolution and termination check."},{"highlight_end":8,"highlight_start":1,"text":"    ///"},{"highlight_end":53,"highlight_start":1,"text":"    /// The \"arguments\" is supposed to be non-empty."},{"highlight_end":30,"highlight_start":1,"text":"    App(Box<Self>, Vec<Val>),"},{"highlight_end":48,"highlight_start":1,"text":"    /// Projecting the first element of a pair."},{"highlight_end":20,"highlight_start":1,"text":"    Fst(Box<Self>),"},{"highlight_end":49,"highlight_start":1,"text":"    /// Projecting the second element of a pair."},{"highlight_end":20,"highlight_start":1,"text":"    Snd(Box<Self>),"},{"highlight_end":31,"highlight_s
tart":1,"text":"    /// Row-polymorphic types."},{"highlight_end":38,"highlight_start":1,"text":"    Row(VarRec, Variants, Box<Self>),"},{"highlight_end":40,"highlight_start":1,"text":"    /// Record literal, with extension."},{"highlight_end":28,"highlight_start":1,"text":"    Rec(Fields, Box<Self>),"},{"highlight_end":2,"highlight_start":1,"text":"}"}]},{"byte_end":8537,"byte_start":8534,"column_end":8,"column_start":5,"expansion":null,"file_name":"src\\syntax\\core\\ast.rs","is_primary":false,"label":"not covered","line_end":241,"line_start":241,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":8,"highlight_start":5,"text":"    Rec(Fields, Box<Self>),"}]}]}}
{"reason":"compiler-message","package_id":"voile 0.1.1 (path+file:///C:/Users/ice10/git-repos/ProofAssistants/voile-rs)","target":{"kind":["lib"],"crate_types":["lib"],"name":"voile","src_path":"C:\\Users\\ice10\\git-repos\\ProofAssistants\\voile-rs\\src/lib.rs","edition":"2018","doctest":true},"message":{"rendered":"error[E0004]: non-exhaustive patterns: `&Rec(_, _)` not covered\n  --> src\\syntax\\core\\level.rs:75:15\n   |\n75 |         match self {\n   |               ^^^^ pattern `&Rec(_, _)` not covered\n   |\n   = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms\n\n","children":[{"children":[],"code":null,"level":"help","message":"ensure that all possible cases are being handled, possibly by adding wildcards or more match arms","rendered":null,"spans":[]}],"code":{"code":"E0004","explanation":"\nThis error indicates that the compiler cannot guarantee a matching pattern for\none or more possible inputs to a match expression. Guaranteed matches are\nrequired in order to assign values to match expressions, or alternatively,\ndetermine the flow of execution. Erroneous code example:\n\n```compile_fail,E0004\nenum Terminator {\n    HastaLaVistaBaby,\n    TalkToMyHand,\n}\n\nlet x = Terminator::HastaLaVistaBaby;\n\nmatch x { // error: non-exhaustive patterns: `HastaLaVistaBaby` not covered\n    Terminator::TalkToMyHand => {}\n}\n```\n\nIf you encounter this error you must alter your patterns so that every possible\nvalue of the input type is matched. For types with a small number of variants\n(like enums) you should probably cover all cases explicitly. Alternatively, the\nunderscore `_` wildcard pattern can be added after all other patterns to match\n\"anything else\". Example:\n\n```\nenum Terminator {\n    HastaLaVistaBaby,\n    TalkToMyHand,\n}\n\nlet x = Terminator::HastaLaVistaBaby;\n\nmatch x {\n    Terminator::TalkToMyHand => {}\n    Terminator::HastaLaVistaBaby => {}\n}\n\n// or:\n\nmatch x {\n    Terminator::TalkToMyHand => {}\n    _ => {}\n}\n```\n"},"level":"error","message":"non-exhaustive patterns: `&Rec(_, _)` not covered","spans":[{"byte_end":2819,"byte_start":2815,"column_end":19,"column_start":15,"expansion":null,"file_name":"src\\syntax\\core\\level.rs","is_primary":true,"label":"pattern `&Rec(_, _)` not covered","line_end":75,"line_start":75,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":19,"highlight_start":15,"text":"        match self {"}]}]}
}
{"reason":"compiler-message","package_id":"voile 0.1.1 (path+file:///C:/Users/ice10/git-repos/ProofAssistants/voile-rs)","target":{"kind":["lib"],"crate_types":["lib"],"name":"voile","src_path":"C:\\Users\\ice10\\git-repos\\ProofAssistants\\voile-rs\\src/lib.rs","edition":"2018","doctest":true},"message":{"rendered":"error[E0004]: non-exhaustive patterns: `&Rec(_, _)` not covered\n  --> src\\syntax\\core\\pretty.rs:12:15\n   |\n12 |         match self {\n   |               ^^^^ pattern `&Rec(_, _)` not covered\n   |\n   = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms\n\n","children":[{"children":[],"code":null,"level":"help","message":"ensure that all possible cases are being handled, possibly by adding wildcards or more match arms","rendered":null,"spans":[]}],"code":{"code":"E0004","explanation":"\nThis error indicates that the compiler cannot guarantee a matching pattern for\none or more possible inputs to a match expression. Guaranteed matches are\nrequired in order to assign values to match expressions, or alternatively,\ndetermine the flow of execution. Erroneous code example:\n\n```compile_fail,E0004\nenum Terminator {\n    HastaLaVistaBaby,\n    TalkToMyHand,\n}\n\nlet x = Terminator::HastaLaVistaBaby;\n\nmatch x { // error: non-exhaustive patterns: `HastaLaVistaBaby` not covered\n    Terminator::TalkToMyHand => {}\n}\n```\n\nIf you encounter this error you must alter your patterns so that every possible\nvalue of the input type is matched. For types with a small number of variants\n(like enums) you should probably cover all cases explicitly. Alternatively, the\nunderscore `_` wildcard pattern can be added after all other patterns to match\n\"anything else\". Example:\n\n```\nenum Terminator {\n    HastaLaVistaBaby,\n    TalkToMyHand,\n}\n\nlet x = Terminator::HastaLaVistaBaby;\n\nmatch x {\n    Terminator::TalkToMyHand => {}\n    Terminator::HastaLaVistaBaby => {}\n}\n\n// or:\n\nmatch x {\n    Terminator::TalkToMyHand => {}\n    _ => {}\n}\n```\n"},"level":"error","message":"non-exhaustive patterns: `&Rec(_, _)` not covered","spans":[{"byte_end":334,"byte_start":330,"column_end":19,"column_start":15,"expansion":null,"file_name":"src\\syntax\\core\\pretty.rs","is_primary":true,"label":"pattern `&Rec(_, _)` not covered","line_end":12,"line_start":12,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":19,"highlight_start":15,"text":"        match self {"}]}]}
}
error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0004`.
error: Could not compile `voile`.
To learn more, run the command again with --verbose.

Process finished with exit code 101
</pre>
</details>

This scary thing appears in my build tool windows when I build my project. I guess it's a json parse failure, please take a look. When build exits, the build tool window shows nothing:
![image](https://user-images.githubusercontent.com/16398479/63403567-d3b31c00-c3ad-11e9-929c-8d700962f804.png)

**Comment by mchernyavsky** [comment]
Can you please provide more information about your environment? You can use [Create New Issue](https://github.com/intellij-rust/intellij-rust/pull/4113) action for it.

**Comment by ice1000** [comment]
Sounds like you're interested in reproducing the issue, but me myself cannot reproduce it reliably (although it happens more than once). I have attached the command line log in the issue, collapsed using the `<details>` HTML tag. Did you see that?

I'm running on Windows 10 1903, latest rust stable (1.37) installed with rustup

**Comment by ice1000** [comment]
CLion 2019.2

**Comment by mchernyavsky** [comment]
I have managed to reproduce it on macOS:

<img width="1401" alt="изображение" src="https://user-images.githubusercontent.com/6079006/63499336-5502cf80-c4d0-11e9-98e2-8f42a18cfdde.png">

I think we will fix it in https://github.com/intellij-rust/intellij-rust/pull/4254. For now I will disable the new built tool window on the stable version of the plugin. You can disable the build tool window by setting `cargo.build.tool.window.enabled` variable to `false` (see `Actions > Registry...`).

**Comment by ice1000** [comment]
Thanks, and I haven't encountered this for a day long.
