### ISSUE TITLE
Rust plugin keeps looking for a deleted package on 

### ISSUE THREAD

**Issue by LiamClarkeNZ** [intellij-rust/intellij-rust#4295]
## Environment

* **IntelliJ Rust plugin version:** 0.2.103.2131-192
* **Rust toolchain version:** 1.36.0
* **IDE name and version:** IntelliJ IDEA 2019.2.1 (Ultimate Edition) Build #IU-192.6262.58
* **Operating system:** Pop!_OS 18.10

## Problem description

I created a Rust package within an existing project to experiment with it, and have since removed the Rust code and Cargo.toml etc. However on start-up, or when running `Refresh Cargo Project` the following error is emitted by the plugin:

> Cargo project update failed: Execution failed (exit code 101). `/home/liam/.cargo/bin/cargo metadata --verbose --format-version 1 --all-features` stdout : error: could not find `Cargo.toml` in `/home/liam/.../prometheus-jmx-exporter/docker/files/rustlang/finalise-configuration` 
or any parent directory

The directory `rustlang/finalise-configuration` has been deleted, but appears to still be cached somewhere. There is nothing in the Module Settings in IDEA that contains this path, so I presume it's elsewhere?

## Steps to reproduce

I haven't tried to reproduce, but this is what I did.
1) Create a rust package inside an existing module
2) Write code, and build the package within IDEA
2) Delete it
3) Run IDEA action Refresh Cargo Project

**Comment by mchernyavsky** [comment]
@LiamClarkeNZ, hello. Try to remove the package using "Detach Cargo Project" button from Cargo Tool Window:

<img width="359" alt="изображение" src="https://user-images.githubusercontent.com/6079006/63477194-b43ef080-c48c-11e9-9e50-bf10c8fb54dd.png">

**Comment by LiamClarkeNZ** [comment]
Thanks @mchernyavsky I completely missed that tab! Problem solved.
