### ISSUE TITLE
All files show "File is not included in module tree, …"

### ISSUE THREAD

**Issue by ctron** [intellij-rust/intellij-rust#4302]
## Environment

* **IntelliJ Rust plugin version:** 0.2.103.2131-192
* **Rust toolchain version:** 1.36.0
* **IDE name and version:** CLion 2019.2.1
* **Operating system:** RHEL 7.6

## Problem description

Since upgrading to CLion 2019.2.1, which probably upgraded the Rust plugin as well, all files show a bar, exception the `main.rs` show a bar "File is not included in the module tree, analysis is not available".

This worked perfectly in the version before.

**Comment by ctron** [comment]
Rolling back to "CLion 2019.2", having the same Rust plugin version, seems to fix the issue.

**Comment by lovasoa** [comment]
I had the same problem after updating the plugin. I invalidated caches and the problem went away.

**Comment by vlad20012** [comment]
Very weird stuff. Could you please try to invoke ctrl+shift+A "invalidate caches"?

**Comment by ctron** [comment]
So I re-upgraded to "2019.2.1" and the problem was no longer present.

I still "invalidated caches" … which fixed a few "missing references" I had after starting.

**Comment by SvetlinZarev** [comment]
I have the same issue and it is always reproducible on the Mac and Linux versions of currently newest CLion + Rust plugin:

CLion 2019.2.5
Build #CL-192.7142.39, built on October 29, 2019
Runtime version: 11.0.4+10-b304.77 amd64
Non-Bundled Plugins: org.toml.lang, org.rust.lang
Rust plugin version: 0.2.109.2149-192

Reproducible scenario:

1. Create empty project with main.rs file
2. Add "async-std" to cargo toml
3. Try to use any struct from async-std, for instance TcpListener

Expected result: I get autocompletion and suggestions for structures in the async-std crate

Actual result: the IDE behaves as if async-std is not added to cargo.toml

![suggestions](https://user-images.githubusercontent.com/1794797/68700849-54894a80-058e-11ea-9626-446923dd1141.jpg)

When I manually navigate to the file/module I see the following message:

![message](https://user-images.githubusercontent.com/1794797/68700844-518e5a00-058e-11ea-9447-694564a4d6d6.jpg)

I've experienced the issue only with the async-std crate.

**Comment by Undin** [comment]
@SvetlinZarev it seems different issues
The reason of your case is described in https://github.com/intellij-rust/intellij-rust/issues/4627#issuecomment-553307766

**Comment by JamesWone** [comment]
I have encountered the problem with @SvetlinZarev today.
1. add "futures 0.3.1 && async-std 1.0.1" to Cargo.toml
2. move mouse point to async_std::net::ToSocketAddrs show box " Unresolved reference 'ToSocketAddrs' "
3. open "External Libraraies/async-std 1.0.1/src/net/addr.rs" show "File is not included in module tree, analysis is not available"
4. cargo clean not work.
5. rm .idea -rf not work.
6. and click "Invalidate Caches / Restart" not work too.
My IDEA and all-plugin is also up to date.

**Comment by Undin** [comment]
> 4. cargo clean not work.
> 5. rm .idea -rf not work.
> 6. and click "Invalidate Caches / Restart" not work too.

@JamesWone All these steps are not relevant to your problems because the initial issue and your one differ. At this moment, there is no workaround to fix it

**Comment by stianeklund** [comment]
I think this problem is related to accidental deletion of the `.IML` file. I accidentally deleted mine today and have this issue in CLion.

**Comment by jcollum** [comment]
@stianeklund 2nded: deleting `.idea` folder does not help.

**Comment by CoolOppo** [comment]
Happening for me as well. The project it's happening to me with is async-std. Deleting the `.idea` folder and invalidating the cache didn't work either.

**Comment by Undin** [comment]
@CoolOppo See #4627

**Comment by adamnemecek** [comment]
I'm not sure this will help anyone but it appears that in my case, I was seeing this due to misunderstanding how CLion parses the packages.

If you are seeing this problem with nested crates, you need to include your nested crates in the top level lib.rs/main.rs. CLion I guess only analyzes crates that are included and ignores the nested crates so you have to include them.

**Comment by Undin** [comment]
@adamnemecek but it's not true
You **haven't** include nested crates to top level lib.rs/main.rs. You need to add these crates to plugin project structure.
You have two different ways to do it: crate single [workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) for all crates in your project or attach nested crates to project structure directly. To make the second variant, just invoke `Attach Cargo Project` in context menu on `nested_crate_dir` directory or `nested_crate_dir/Cargo.toml` file
Alternatively, invoke `Attach` action at the top of editor with opened `nested_crate_dir/Cargo.toml` file.

| Context menu | Editor notification |
| -|-|
| ![image](https://user-images.githubusercontent.com/2539310/74130341-dff89300-4bf2-11ea-86bf-9432d9f22661.png) | ![image](https://user-images.githubusercontent.com/2539310/74130419-1afac680-4bf3-11ea-9929-4e30274dd4eb.png) |

**Comment by adamnemecek** [comment]
Ok sure but things seem to work when I do. Like this is probably a better solution anyway since it's version controlled and such.

**Comment by JohnnyJayJay** [comment]
This issue also happens in IntelliJ 2019.3.4 for me, without any dependency or nested crates. All the previous attempts like deleting `.idea`, invalidating the caches and so on have not worked for me either. 

Are there any updates on this, is there a solution?

**Comment by 166MMX** [comment]
> ~This issue also happens in IntelliJ 2019.3.4 for me, without any dependency or nested crates. All the previous attempts like deleting `.idea`, invalidating the caches and so on have not worked for me either.~
> 
> ~Are there any updates on this, is there a solution?~
> 
> Edit: Disregard this. I'm fairly new to rust and simply forgot to add the file as a module x)

@JohnnyJayJay please be so kind and explain how you added the file to module x

I am still struggling with this. And am not sure what I forgot.

**Comment by JohnnyJayJay** [comment]
@166MMX You need to add a `mod name;` declaration for every file in your `lib.rs` or `main.rs` file.

**Comment by 166MMX** [comment]
> @166MMX You need to add a `mod name;` declaration for every file in your `lib.rs` or `main.rs` file.

@JohnnyJayJay Thanks a ton! It solved it for me.

Though after so adding the `mod name;` declaration to my `lib.rs` it yield a redeclaration warning. The reason for that was that I also had that module implemented within `lib.rs`. Now I just had to move the implementation to the the other file. But after cleanup and moving the code it's not complaining anymore.

I guess I was holding it wrong too, oops.

**Comment by steelx** [comment]
this doesnt work if you are solving `rustlings` exercise.
![image](https://user-images.githubusercontent.com/3184210/80955385-dc089580-8e1c-11ea-8357-4b3620993660.png)

**Comment by SoumenDass** [comment]
Same issue when I open Rust exercises downloaded from exercism e.g. the [Prime Factors exercise](https://exercism.io/my/solutions/3ea4002587e546c9ab9d73b051dd8646).

![image](https://user-images.githubusercontent.com/576199/89988561-51a0bf00-dcb2-11ea-8b81-09da10da1647.png)

**Comment by vlad20012** [comment]
If someone runs into this nowadays, please, file a new separate issue.

**Comment by lockieluke** [comment]
Make sure you need to use one of the functions declared in that file, the error will go away magically.

**Comment by nojitsi** [comment]
Make sure there is no space in project path.
Moving directory to new path without spaces fixed issue for me.
