### ISSUE TITLE
Substitute type parameters with actual types in Parameter Info

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#4308]
##  Environment

* **IntelliJ Rust plugin version:** Build from source `release-104` b3e124a8bec678541004e69cb7aba51c247cf714
* **Rust toolchain version:** rustc 1.36.0 (a53f9df32 2019-07-03)
* **IDE name and version:** 2019.2 CLion 192.5728.100
* **Operating system:** macOS 10.14.6

## Problem description

With #4207 in place the Plugin now substitute generic types in completion variants

<img width="781" alt="completion" src="https://user-images.githubusercontent.com/2500320/63672287-50992800-c7ea-11e9-94f1-2a54ef5545ca.png">

Should not the same be done for `Parameter Info` (`cmd + P`) as well? The same example

<img width="782" alt="parameter_hit" src="https://user-images.githubusercontent.com/2500320/63672325-61e23480-c7ea-11e9-8566-d50a6bbba4e2.png">

The implementation is located in `org.rust.ide.hints.parameter.RsParameterInfoHandler`

## Steps to reproduce

```rust
struct S<T1>();

impl <T2> S<T2> {
    fn foo(&self, x: T2) -> T2 { x }
}

fn main() {
    let s = S::<i32>();
    s.foo()
}
```

**Comment by Kobzol** [comment]
I started to work on this some time ago and I'm not sure about `E-easy` :D In any case, I'll revive my branch and try to finish it.

**Comment by ortem** [comment]
@Kobzol OK, I was not pretty sure if this is "easy" or "medium" actually, so I've changed the label 😄

> I'll revive my branch and try to finish it

Great, thank you!
