### ISSUE TITLE
File is not included in module tree

### ISSUE THREAD

**Issue by zhuxiujia** [intellij-rust/intellij-rust#4314]
if the file    is    "mod Test" not use " pub  mod Test" include  in   main.rs
it will be  "File is not included in module tree"

Clion  Version:  2019.2.1

**Comment by vlad20012** [comment]
Umm, maybe I didn't understand you but looks like it's expected: if file is not included into the module tree, it is... not included into module tree. Wow. Could you please describe your issue in details?

**Comment by zhuxiujia** [comment]
> Umm, maybe I didn't understand you but looks like it's expected: if file is not included into the module tree, it is... not included into module tree. Wow. Could you please describe your issue in details?

If the module does not add the "pub" keyword, clion prompts will Tips "File is not included in module tree"

**Comment by vlad20012** [comment]
Could you please reduce it to the minimal "hello-world" size reproducible expample? Because I can't reproduce it naively.

**Comment by Alex-PK** [comment]
I had the same problem on a project after updating both CLion and the IntelliJ plugin the same day.
It started working again after I selected "Invalidate Caches/Restart..." from the File menu.
I guess the cache format changed between versions.

**Comment by bugproof** [comment]
@Alex-PK didn't help

**Comment by zhuxiujia** [comment]
> Could you please reduce it to the minimal "hello-world" size reproducible expample? Because I can't reproduce it naively.



```rust
macro_rules! cfg_time {
    ($($item:item)*) => {
        $(
            #[cfg(feature = "time")]
            #[cfg_attr(docsrs, doc(cfg(feature = "time")))]
            $item
        )*
    }
}

cfg_time! {
    pub mod time;
}
```

so the   Clion IDE   not  tell me  have  time mode  method  delay_for() method.
if you change to this code,not use  cfg_time!   macro,IDE  will  tell me have this method.
```rust
    pub mod time;
```

so i  think  ide  have not  Intellisense , It's because of macro。

did it  will  support  macro Intellisense ？  if not , write rust code   just like  use  Notepad write it.........
that is so bad......

**Comment by Undin** [comment]
> did it will support macro Intellisense ？

@zhuxiujia Yep. But the default macro expansion engine can't process `impl` blocks and `mod` declarations because of some technical reasons. So in your case, it leads to `File is not included in module tree` notification.

Try to use turn on experimental macro expansion engine (see #3628). It should fix your issues (including cases from tokio crate)

**Comment by zhuxiujia** [comment]
> > did it will support macro Intellisense ？
> 
> @zhuxiujia Yep. But the default macro expansion engine can't process `impl` blocks and `mod` declarations because of some technical reasons. So in your case, it leads to `File is not included in module tree` notification.
> 
> Try to use turn on experimental macro expansion engine (see #3628). It should fix your issues (including cases from tokio crate)

Thank you. I hope it will be stable as soon as possible
