### ISSUE TITLE
Not able to add i32 and &i32

### ISSUE THREAD

**Issue by umanwizard** [intellij-rust/intellij-rust#4328]
## Environment

* **IntelliJ Rust plugin version:**
0.2.104.2132-192
* **Rust toolchain version:**
1.37.0
* **IDE name and version:**
CLion 2019.2.1
* **Operating system:**
macOS 10.14.6
## Problem description

This is a valid rust program (`cargo run` works fine) but my IDE reports `mismatched types`.

```rust
fn main() {
    0 + &0;
}
```

**Comment by vlad20012** [comment]
Should be solved if you enable the new macro expansion engine. See #3628

**Comment by umanwizard** [comment]
> Should be solved if you enable the new macro expansion engine. See #3628

Confirmed, thanks!
