### ISSUE TITLE
Can't  jump to definition with multi version package 

### ISSUE THREAD

**Issue by wonderflow** [intellij-rust/intellij-rust#4329]
## Environment

* **IntelliJ Rust plugin version:**
0.2.104.2132-192

* **Rust toolchain version:**

1.36.0

* **IDE name and version:**

CLion 2019.2.1

* **Operating system:**

Darwin 18.7.0 Darwin Kernel Version 18.7.0:

## Problem description

Can't  jump to definition with a package have multiple version such as [Crate k8s_openapi](https://docs.rs/k8s-openapi/0.5.0/k8s_openapi/#modules) which have many versions.

![image](https://user-images.githubusercontent.com/2173670/63995174-303ed580-cb2a-11e9-89be-61762904f878.png)

## Steps to reproduce

when I specify the version by  feature in cargo.toml, the compiler can work well, but I can't use jump to definition. Packages without multiple versions is OK.

![image](https://user-images.githubusercontent.com/2173670/63995209-519fc180-cb2a-11e9-8a54-6bef52cb5246.png)

![image](https://user-images.githubusercontent.com/2173670/63995344-b9eea300-cb2a-11e9-921e-2f46c528684d.png)

![image](https://user-images.githubusercontent.com/2173670/63995318-a8a59680-cb2a-11e9-9999-ef4ff44a9cd5.png)

**Comment by Undin** [comment]
@wonderflow Thanks for the report!
The reason of the problem is declaration of several modules with the same name via `cfg` attribute. At this moment plugin doesn't support them (see #1191) but we are working on at right now

**Comment by wonderflow** [comment]
@Undin  thanks for your effort

**Comment by LyleScott** [comment]
I'm getting this same problem with this same module, fyi, those checking that this is still a problem.

**Comment by Undin** [comment]
@LyleScott could you create a new issue, please? I doubt that it's the same issue
