### ISSUE TITLE
CLion profiler: jump to Rust source is not available

### ISSUE THREAD

**Issue by Kobzol** [intellij-rust/intellij-rust#4333]
## Environment

* **IntelliJ Rust plugin version:** master (19803f)
* **Rust toolchain version:** 1.37
* **IDE name and version:** CLion 2019.2 #CL-192.5728.100 (the version packaged with the plugin in current `master`)
* **Operating system:** Linux Mint 19.2

## Problem description
I have tried to use the CLion built-in profiler (using `perf`) on a Rust application. It works very seamlessly, however when I right-click on a method in the resulting flamechart or method list, the option `Jump to source` is grayed out, so I cannot quickly jump from the profiler output to the source code. The method names are formatted correctly (with proper paths and demangled).

This happens both in debug mode and release mode with debug symbols. `addr2line` is available on my system and it is being picked up by the plugin (at least it looks like so, based on a quick debug).

I noticed that there are some classes that seem like they should be implementing this functionality (`RsSymbolSearcher`, `RsPerfNavigatableNativeCall`, etc.), however when I put a breakpoint inside them they are not called at all when I profile the application/display the flamechart/right-click on a method.

If you can give me some hints I can take a shot at fixing this.

**Comment by Kobzol** [comment]
@ortem I looked at this closer and it seems like a bug in CLion, it doesn't work in CLion even for C++. CLion passes the runtime absolute addresses to `AddressSymbolizer`, but it is not able to resolve them, because it needs relative addresses. For example:

```
# this is the address provided by CLion, does not return anything
$ addr2line -e example_project 55d2ab6ec10b

# this is the correct relative address
$ addr2line -e example_project c10b
/rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/ptr/mod.rs:177
```

**Comment by ortem** [comment]
@Kobzol Thank you! There is an issue in CLion tracker: https://youtrack.jetbrains.com/issue/CPP-20199

**Comment by Kobzol** [comment]
@ortem This now works in CLion 2020.3 :tada: :rocket:
