### ISSUE TITLE
Bad type inference and unresolved reference

### ISSUE THREAD

**Issue by maxim-banaev** [intellij-rust/intellij-rust#4340]
## Environment

* **IntelliJ Rust plugin version:** 0.2.104.2132-192
* **Rust toolchain version:** 1.18.3
* **IDE name and version:** CLion 2019.2.1
* **Operating system:** Linux

## Problem description
Example of code:
```rust
trait MyDiv<T> {
  type Output;
  fn div(&self, rhs: T) -> (Self::Output, Self::Output);
}

impl<T> MyDiv<T> for T
  where T: std::ops::Div<T, Output=T> + std::ops::Rem<T, Output=T> + Copy {
  type Output = T;
  fn div(&self, rhs: T) -> (Self::Output, Self::Output) {
    (*self / rhs, *self % rhs)
  }
}

fn main() {
  let a = 4;
  let b = 2;
  let result = a.div(b);
  println!("{:#?}", result);
}
```

Expected: valid code and type of result is `(i32, i32)`
Actual: type of result is `i32` and code isn't valid because: `unresolved reference div`

https://youtrack.jetbrains.com/issue/CPP-17312

**Comment by Undin** [comment]
I didn't investigate why but it works correctly with new experimental macro expansion engine. See #3628 for more details
