### ISSUE TITLE
Type inference fails on `await`-ed expression

### ISSUE THREAD

**Issue by moxaj** [intellij-rust/intellij-rust#4345]
##  Environment

* **IntelliJ Rust plugin version:**
0.2.104.2132-192
* **Rust toolchain version:**
rustc 1.39.0-nightly (dfd43f0fd 2019-09-01)
* **IDE name and version:**
Ultimate 2019.2.1
* **Operating system:**
Windows 10 Pro 1903

## Problem description
^title

## Steps to reproduce
(sorry for using tokio as a repro ..)

1. Add these dependencies
  ```
[dependencies]
tokio = "0.2.0-alpha.4"
futures = "0.1.28"
futures-util-preview = "0.3.0-alpha.18"
  ```
2. Call next on an `UnboundedReceiver<String>`:
  ```
use futures_util::StreamExt;
use tokio;
use tokio::sync::mpsc::unbounded_channel;

#[tokio::main]
async fn main() {
    let (sender, mut receiver) = unbounded_channel::<String>();
    let next = receiver.next().await;
}
  ```

__Expected:__ the type of `next` correctly inferred
__Actual:__ the type of `next` is `unknown`
![image](https://user-images.githubusercontent.com/7839686/64116396-89a93d80-cd92-11e9-8143-0ea36ac47c5d.png)

**Comment by moxaj** [comment]
Same issue with:

```
[dependencies]
tokio = "0.2.0-alpha.4"
futures-preview = "0.3.0-alpha.18"
```

```rust
use std::io;
use std::net::{IpAddr, Ipv4Addr, SocketAddr};

use futures::StreamExt;
use tokio::codec::{FramedRead, LinesCodec};
use tokio::net::TcpListener;

#[tokio::main]
async fn main() -> io::Result<()> {
    let addr = SocketAddr::new(IpAddr::V4(Ipv4Addr::LOCALHOST), 9090);
    let mut socket = TcpListener::bind(&addr).await?;
    while let Ok((socket, _)) = socket.accept().await {
        let (stream_raw, _) = socket.split();
        let mut stream = FramedRead::new(stream_raw, LinesCodec::new());
        let message = stream.next().await;
    }
    Ok(())
}
```

**Result:** the type of `message` is `unknown`
![image](https://user-images.githubusercontent.com/7839686/65170305-b030cf00-da48-11e9-8389-86ed910d6761.png)

**Comment by mchernyavsky** [comment]
@moxaj, have you updated to the latest version of the plugin? If yes, try to [invalidate caches](https://www.jetbrains.com/help/idea/working-with-projects.html#3c03e31d).


<img width="796" alt="изображение" src="https://user-images.githubusercontent.com/6079006/65177060-a7e38e80-da5e-11e9-8d1c-b50e848cf9c1.png">

**Comment by moxaj** [comment]
@mchernyavsky i'm on version `0.2.105.2133-192`, which I believe is the latest. Invalidating the caches didn't seem to help.

**Comment by moxaj** [comment]
This is strange - the first example (with the channel) does not work either, but I remember it working right after the update was released.

**Comment by mchernyavsky** [comment]
Oh, this PR is not released yet. Please, upgrade to the nightly version of the plugin.

**Comment by moxaj** [comment]
Oh, that explains it. Sorry for the noise!
