### ISSUE TITLE
Unfinished syntax highlighting in large .rs files

### ISSUE THREAD

**Issue by Fullstop000** [intellij-rust/intellij-rust#4347]
## Environment

* **IntelliJ Rust plugin version:** 0.2.104.2132-192
* **Rust toolchain version:** 1.36.0
* **IDE name and version:**Goland 2019.2
* **Operating system:** macOS Mojave 10.14.5

## Problem description
Wired highlighting occurs after updating to 0.2.104.2132-192
![image](https://user-images.githubusercontent.com/12471960/64153866-5209c680-ce62-11e9-8aaf-921c6832c39a.png)

![image](https://user-images.githubusercontent.com/12471960/64153882-56ce7a80-ce62-11e9-9da3-1f346af63297.png)

It seems the highlighting now is loaded lazily and in a large `.rs` file the highlighting stops on the middle.

**Comment by ice1000** [comment]
Happens to me too, but I have an easy workaround (just edit the code)
