### ISSUE TITLE
"Unresolved reference" for SNAFU's context selectors

### ISSUE THREAD

**Issue by ivan** [intellij-rust/intellij-rust#4354]
## Environment

* **IntelliJ Rust plugin version:** 0.2.104.2132-192
* **Rust toolchain version:** rustc 1.39.0-nightly (dfd43f0fd 2019-09-01)
* **IDE name and version:** IntelliJ IDEA 2019.2.1
* **Operating system:** NixOS

## Problem description

The Rust plugin shows "Unresolved reference" for SNAFU's context types.

"SNAFU creates context selectors mirroring each error variant. These are used with the context method to provide ergonomic error handling." https://docs.rs/snafu/0.5.0/snafu/

These types are created in the current module through `derive` and [a procedural macro in snafu-derive](https://github.com/shepmaster/snafu/blob/32016ad94634a4a801c1d833ffe543c28247a57f/snafu-derive/src/lib.rs#L1195-L1394), but the Rust plugin is unaware of them, whether or not the new macro expansion engine is being used.

## Steps to reproduce

1. Create a project over https://github.com/ludios/rust-plugin-bug-snafu
2. Open main.rs
3. Observe "Unresolved reference" for `OpenConfig` and `SaveConfig`.

![rust plugin snafu Screenshot_20190905_020952](https://user-images.githubusercontent.com/4458/64306754-5b3e8480-cf83-11e9-9e3a-e392679d89fc.png)

**Comment by ivan** [comment]
Not sure if this is just #1786

**Comment by vlad20012** [comment]
We just not support procedural macros for now

**Comment by 0xcaff** [comment]
FWIW, you can just do:

```rust
let config = fs::read(filename).map_err(|source| OpenConfig { filename, source })?;
```

instead of using the shortcut. It works with IntelliJ.

**Comment by mili-l** [comment]
see https://github.com/intellij-rust/intellij-rust/pull/9729
