### ISSUE TITLE
Create LookupElements for completions

### ISSUE THREAD

**Issue by HybridEidolon** [intellij-rust/intellij-rust#436]
Right now the direct Named Elements are used in `getVariants` for the different reference types. The completions work, but it's hard to differentiate between functions, bindings, and modules because the icons flicker a lot in the editor.

Using LookupElements in the variants array allows IntelliJ to display rich information about each completion, and also attach rules for inserting the completion.

Some notes:
- `#[deprecated]` is now stable and can be used by everyone. LookupElements should use strikethrough for deprecated elements.
- Bold face could be used for field references and impl methods specific to the type, and non-bold for trait methods. This is not particularly useful without type system support.
- An InsertHandler should be attached for fn call and method completions to add the parentheses and set the cursor inside them. For method calls, type system support is needed. Macros should add the !, but as of this writing macro items are not included in completions nor are references made for them at all.
- Wrapping LookupElements in `PrioritizedLookupElement.withPriority` allows the completion list to be sorted. This allows elements of similar kinds and proximity to be sorted together (modules, fn items, consts, statics, bindings, ...).
- The type string could be added for certain kinds of elements, but this cannot be fully resolved without type system support.

SDK doc reference: http://www.jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support/code_completion.html

Example of LookupElement creation in Go-lang plugin: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/3936626d8c3d1cda0273fb31c823c42f76ec1235/src/com/goide/completion/GoCompletionUtil.java#L314

**Comment by matklad** [comment]
Closing: we already have some simplistic lookup elements and insertion handlers. There's a lot room for improvement of course!
