### ISSUE TITLE
Type info action doesn't take into account type aliases

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#4366]
## Environment

* **IntelliJ Rust plugin version:** 0.2.105.2731-192-nightly
* **Rust toolchain version:** 1.39.0-nightly (9eae1fc0e 2019-08-23) x86_64-apple-darwin
* **IDE name and version:** IU-192.6603.8
* **Operating system:** macOS 10.13.6

## Problem description
After #4243 we have info about type alias for structs and enums. But `Type Info` intention doesn't use it and always insert base type instead of a type alias.

![2019-09-08 14 32 38](https://user-images.githubusercontent.com/2539310/64487619-8526ce00-d245-11e9-8172-da67019368d6.gif)

## Steps to reproduce
```rust
use std::cell::RefCell;

type BoxedCell<T> = Box<RefCell<T>>;

fn foo<T>(c: &BoxedCell<T>) {
    let b = c;
}

```

**Comment by Kobzol** [comment]
I just noticed this, it seems like it might be caused by the same problem, so I'll just attach it here as a test case:
```rust
```

**Comment by Undin** [comment]
@Kobzol No, your issue has other reason (see #2778).
In general, it's because index (that the plugin uses while completion for items from `impl` blocks) doesn't know relation between `Wrapped` and `Direct`.
Probably, we can support such case as well but it seems such feature will cause a significant performance regression
