### ISSUE TITLE
Parameter info in function and method call arguments

### ISSUE THREAD

**Issue by HybridEidolon** [intellij-rust/intellij-rust#437]
Extension point `codeInsight.parameterInfo` via ParameterInfoHandler interface allows function parameters to be shown when the users presses `Ctrl+P` where relevant. For fn calls, this is trivial so long as the fn is resolved properly, but robust type information won't be available without type system support. Method calls require type system support.

ParameterInfoHandler interface: https://upsource.jetbrains.com/idea-ce/file/idea-ce-1731d054af4ca27aa827c03929e27eeb0e6a8366/platform/lang-api/src/com/intellij/lang/parameterInfo/ParameterInfoHandler.java

**Comment by mbStavola** [comment]
I'd like to attempt this.

**Comment by alygin** [comment]
@mbStavola, any progress on this?
I've just drafted a working prototype of the feature and could polish it off if things got stuck here.

**Comment by mbStavola** [comment]
Sorry for the late reply. Things picked up at work so I wasn't able to really devote much time to this. Thanks for picking it up!

**Comment by alygin** [comment]
No worries, first things first.
Hope you'll get back when time allows, there're plenty of other cool features are waiting for their time here :)
