### ISSUE TITLE
Workspace analysis broken after latest update

### ISSUE THREAD

**Issue by Karrq** [intellij-rust/intellij-rust#4373]
## Environment

* **IntelliJ Rust plugin version:** 0.2.105.2133-192
* **Rust toolchain version:** nightly-x86_64-linux
* **IDE name and version:** CLion 2019.2.1
* **Operating system:** Manjaro Linux

## Problem description
Workspace crates don't have analysis after last plugin update, thus resulting in a lot of "File not included in module tree, analysis is not available" and inability to check for any name, be it function module crate...

## Steps to reproduce
Get previous plugin version, make your workspace, open the workspace root as IDE's root project, update plugin.

**Comment by Undin** [comment]
@Karrq Thanks for the report!
I suppose it may be the same bug as #4372
Could you please provide:
* output of `rustc --version --verbose` command
* logs. They can be found via `Show Log in` action. Also, you can compress all logs into zip via `Compress Logs and Show in` action

**Comment by vlad20012** [comment]
Looks like #4314 or #4302. Could you please try to invoke ctrl+shift+A "invalidate caches"?

**Comment by Karrq** [comment]
`rustc --version --verbose` output:

```
rustc 1.39.0-nightly (9af17757b 2019-09-02)
binary: rustc
commit-hash: 9af17757be1cc3f672928ecf06c40a662c5ec26d
commit-date: 2019-09-02
host: x86_64-unknown-linux-gnu
release: 1.39.0-nightly
LLVM version: 9.0
```

I wasn't getting any message in the log, just a lint on top of the file.
Anyways I somebody suggested I should try refreshing the cache (saw in on the email from github) and it seemed to have fixed it.

**Comment by Kilerd** [comment]
same issue in CLion 2019.2.1

rust info
```
rustc 1.39.0-nightly (2b8116dce 2019-09-08)
binary: rustc
commit-hash: 2b8116dced2c6c5d02e1c4359e89dc0919d6001b
commit-date: 2019-09-08
host: x86_64-apple-darwin
release: 1.39.0-nightly
LLVM version: 9.0
```
clion info
```
CLion 2019.2.1
Build #CL-192.6262.62, built on August 21, 2019
Runtime version: 11.0.3+12-b304.39 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: carbon-now-sh, cc.duduhuo.git-conflict, com.jetbrains.plugins.ini4idea, com.markskelton.one-dark-theme, com.paperetto.dash, com.tobszarny.activetabhighlighter.plugin.id, io.github.qeesung.component.HighlightBracketPair, izhangzhihao.rainbow.brackets, Docker, org.toml.lang, org.rust.lang, rs.pest
```

**Comment by Drudenhaus** [comment]
Same issue with IntelliJ except with main.rs (any other files in src/ exhibit the same behavior).
```
IntelliJ IDEA 2019.2.3 (Ultimate Edition)
Build #IU-192.6817.14, built on September 23, 2019
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.2.8-gentoo
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: 
Non-Bundled Plugins: mobi.hsz.idea.gitignore, BashSupport, org.intellij.scala, org.toml.lang, org.rust.lang
```
Rust
```
rustc 1.38.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.38.0
LLVM version: 9.0
```
Rust plugin 0.2.108.2148-192

**Comment by SnowyCoder** [comment]
Same issue with latest update,
Clion info:
```
CLion 2019.2.5
Build #CL-192.7142.39, built on October 29, 2019
Runtime version: 1.8.0_232-b09 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 4.19.81-1-MANJARO
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: Key Promoter X, Lua, org.intellij.plugins.markdown, org.toml.lang, org.rust.lang
```
Rust info: 
```
rustc 1.40.0-nightly (38048763e 2019-11-06)
binary: rustc
commit-hash: 38048763e885a3ee139abf39d59a530b16484150
commit-date: 2019-11-06
host: x86_64-unknown-linux-gnu
release: 1.40.0-nightly
LLVM version: 9.0
```
Plugin info: 0.2.109.2149-192

Is there any update on this issue? it seems quite dead

**Comment by ahoebeke** [comment]
Any update? What changed between the version updates? :-/

**Comment by vmsh0** [comment]
I have this as well.

**Comment by David-OConnor** [comment]
Getting this still.

**Comment by vlad20012** [comment]
@David-OConnor Please, try `Ctrl + Shift + A` -> type "Invalidate Cache / Restart". If it doesn't help, please, open a separate issue

**Comment by David-OConnor** [comment]
Thanks - opening new issue.
