### ISSUE TITLE
Unable to specify which target to use when building the project.

### ISSUE THREAD

**Issue by photex** [intellij-rust/intellij-rust#4387]
## Environment

* **0.2.105.2133-192**
* **1.37.0**
* **CLion 2019.2.1**
* **Windows 10**

## Problem description

I'd like to be able to configure which target is built when building the project. Currently there is no option to control this. 
It may not seem like much, but when you have a large build, you end up with an enormous amount of disk space wasted.

**Comment by mchernyavsky** [comment]
See this comment: https://github.com/intellij-rust/intellij-rust/issues/4386#issuecomment-531218523

**Comment by photex** [comment]
Sorry, as I mentioned in the other issue, here I'm not talking about which project to build.

I have a workspace with a bunch of 'projects' and I build for multiple 'targets'. I don't see a way to specify the target triple to build with:

I build for many target triples:
- x86_64-unknown-linux-gnu 
- aarch64-unknown-linux-gnu
- x86_64-pc-windows-msvc
- x86_64-pc-windows-gnu
- x86_64-unknown-linux-musl 
- aarch64-unknown-linux-musl

I personally never want the 'default'.

**Comment by photex** [comment]
And so cool, that the new build window actually supports all that correctly! :D
