### ISSUE TITLE
Missing syntax hinting for several atomic primitive types

### ISSUE THREAD

**Issue by JasonShin** [intellij-rust/intellij-rust#4389]
## Environment

* **IntelliJ Rust plugin version:**
0.2.105.2133-192

* **Rust toolchain version:**
rustc 1.39.0-nightly (34e82a7b7 2019-09-10)
cargo 1.39.0-nightly (fe0e5a48b 2019-09-04)

* **IDE name and version:**
Pycharm: 2019.2.1

* **Operating system:**
Ubuntu 18

## Problem description
![Screenshot from 2019-09-14 10-09-47](https://user-images.githubusercontent.com/2525002/64900949-ee8c5e00-d6d7-11e9-8566-ff6e5f555703.png)

In Rust STD for Atomic primitive types, there are more primitive types than `AtomicBool`. It includes AtomicIsize, AtomicUsize, AtomicI8, AtomicU16. I propose intellij-rust should implement hinting for these types as well.

**Comment by Undin** [comment]
@JasonShin try to enable new macro expansion engine. It should fix your issue
See #3628 for more details

**Comment by JasonShin** [comment]
@Undin thanks, it's correctly giving me syntax hinting for those atomic primitive types. I will play around with it more and report any issue
