### ISSUE TITLE
There should be an auto completion popup after typing double-colon

### ISSUE THREAD

**Issue by himikof** [intellij-rust/intellij-rust#439]
This can probably be implemented by using a custom `CompletionContributor` and overriding `invokeAutoPopup` method (similar to [java implementation](https://upsource.jetbrains.com/idea-ce/file/idea-ce-d89b575251e4b9a54349e94f8682622caec855a9/java/java-impl/src/com/intellij/codeInsight/completion/JavaCompletionContributor.java?nav=32852:32852)).

Auto-popup will be most useful after implementing #433.

**Comment by matklad** [comment]
Perhaps we should completely switch from reference based to contributor based completion?

**Comment by matklad** [comment]
Ouch, this was much easier to implement than I expected, no need to re rail all completion onto providers. Should have fixed this ages ago. Thanks a lot for the report and fix suggestion!

**Comment by daschl** [comment]
Awesome! Its weird but this is such a timesaver, especially going through third party libs where you don't know how the method is called and you just want to breeze through the list of available methods/variants :)

**Comment by matklad** [comment]
>where you don't know how the method is called and you just want to breeze through the list of available methods/variants

<kbd>Ctrl+Space</kbd> always can be used to invoke completion.

**Comment by daschl** [comment]
ah cool I didn't know that, thanks!
