### ISSUE TITLE
Plugin does not handing non-default directory layouts for source that Cargo handles fine.

### ISSUE THREAD

**Issue by paul-callahan** [intellij-rust/intellij-rust#4408]
## Environment

* **IntelliJ Rust plugin version:**
0.2.105.2133-192
* **Rust toolchain version:**
1.37.0
* **IDE name and version:**
CLion 2019.2.2
* **Operating system:**
Macos Mojave
## Problem description

 Basically I have my rust source in `src/rust/` rather than `src/`.   Cargo has configuration options to handle this.   The Intellij Rust plug does not handle this correctly.

The plugin gives the error `File is not included in module tree, analysis is not available` when opening any rust file in the project in the IDE.

I have my source tree laid out like this:
```
project
   +
   +----+
   |   src
   |    +
   |    +------+
   |    |      c
   |    |      +
   |    |      +--+
   |    |         *.c
   |    +------+
   |          rust
   |            +
   |            +--+
   +               *.rs
Cargo.toml
```

In my `Cargo.toml` I specify this layout for Rust:
```toml
[lib]
path = "src/rust/lib.rs"
name = "myproject"
crate-type = ["whatever"]
```

Cargo deals with this fine - it builds the rust source in `src/rust`.  The plugin does not

## Steps to reproduce

Create a new rust project.  Move the rust source code to `src/rust/`.  Edit your Cargo.toml with the above `lib` settings.   Import the project into CLion or Intellij.  Open a rust file in the project.   Observe the error `File is not included in module tree, analysis is not available`

**Comment by Undin** [comment]
Fixed by #4507
