### ISSUE TITLE
Support 2019 EAP 3

### ISSUE THREAD

**Issue by dvdplm** [intellij-rust/intellij-rust#4433]
Since `CLion 2019.3 EAP  Build #CL-193.3519.24` came out I keep getting bugged about upgrading but also warned that the Rust plugin is not compatible.

I have several likely related issues:

- on my machine, 2019.3 EAP does not start (see https://youtrack.jetbrains.com/issue/CPP-17489)
- I do not get new updates to the Rust plugin in the working CLion 2019.2 because I'm invited to upgrade to 2019.3 EAP
- I'm not sure what the state of the rust plugin is wrt supporting 2019.3 EAP

My system (as reported from the "about" dialog in 2019.3 EAP):

```
CLion 2019.3 EAP
Build #CL-193.3519.24, built on September 18, 2019
CLion EAP User
Expiration date: October 18, 2019
Runtime version: 11.0.4+10-b480.2 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: G1 Young Generation, G1 Old Generation
Memory: 3000M
Cores: 12
Registry: run.processes.with.pty=TRUE, ide.tooltip.initialDelay=903, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.andrewbrookins.wrap_to_column, com.vladsch.idea.multimarkdown, izhangzhihao.rainbow.brackets, org.toml.lang, org.sylfra.idea.plugins.linessorter
```

**Comment by Undin** [comment]
Try to reinstall plugin
The latest stable version of the plugin supports the latest 2019.3 EAP so looks like it's a bug in IDE plugin update

**Comment by ice1000** [comment]
2019.3 EAP CLion works for me

**Comment by dvdplm** [comment]
> looks like it's a bug in IDE plugin update

Indeed. Removing and re-installing works. Thanks!
