### ISSUE TITLE
let statement get spoiled by the inserted match

### ISSUE THREAD

**Issue by SomeoneToIgnore** [intellij-rust/intellij-rust#4435]
## Environment

* **IntelliJ Rust plugin version:**

0.2.106.2134-193

* **Rust toolchain version:**

rustc 1.37.0 (eae3437df 2019-08-13)

* **IDE name and version:**

CLion 2019.3 EAP
Build #CL-193.3519.24, built on September 18, 2019
Runtime version: 11.0.4+10-b480.2 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

* **Operating system:**

macOS 10.14.6

## Problem description

Consider a snippet:

```rust
fn main() {
    let result = /*caret*/Vec::with_capacity(42);

    let test = false;
}
```

I would like to create a different `Vec` depending on some complex condition ergo I put the caret before `Vec` and type `match something {` and press enter:

```rust
fn main() {
    let result = match 22 {/*caret*/Vec::with_capacity(42);

    let test = false;
}
```

Expected:
the snippet turns into the following:

```rust
fn main() {
    let result = match 22 {
        /*caret*/Vec::with_capacity(42);
    }

    let test = false;
}
```

Actual:

the next `let` statement gets corrupted:

```rust
fn main() {
    let result = match 22 {
        Vec::with_capacity(42);

        let
    } test = false;
}
```

Note: the same approach works fine when `if` is used instead of `match` or if the `let` expression is replaced with something else.

**Comment by Kobzol** [comment]
It works correctly with the latest version of the plugin.
