### ISSUE TITLE
Not all cargo flags are proposed for completion in run configuration window

### ISSUE THREAD

**Issue by SomeoneToIgnore** [intellij-rust/intellij-rust#4440]
## Environment

* **IntelliJ Rust plugin version:** 0.2.106.2134-193
* **Rust toolchain version:** 1.37.0 (eae3437df 2019-08-13) x86_64-apple-darwin
* **IDE name and version:** CLion 2019.3 EAP (CL-193.3519.24)
* **Operating system:** macOS 10.14.6

## Problem description

There's a flag `--all-targets` that is sometimes useful, for instance, when I want to run `check` on every part of my codebase.

But the autocomplete does not propose it:

![image](https://user-images.githubusercontent.com/2690773/65603408-49fafd80-dfae-11e9-87fe-56d8e700f822.png)

Would be good to check if all other flags from https://doc.rust-lang.org/cargo/commands/cargo-check.html and other commands are present in the completion options.

**Comment by Undin** [comment]
Already fixed. I supposed by #6071
