### ISSUE TITLE
Add `Analyze backtrace` tool window

### ISSUE THREAD

**Issue by SomeoneToIgnore** [intellij-rust/intellij-rust#4442]
## Environment

* **IntelliJ Rust plugin version:** 0.2.106.2134-193
* **Rust toolchain version:** 1.37.0 (eae3437df 2019-08-13) x86_64-apple-darwin
* **IDE name and version:** CLion 2019.3 EAP (CL-193.3519.24)
* **Operating system:** macOS 10.14.6

## Problem description

Intellij Idea has an instrument to analyze the stacktraces: https://blog.jetbrains.com/idea/2006/08/analyzing-external-stack-traces/

When launched, it inserts the formatted clipboard contents into the tool window and, when applied, allows to navigate to the places in the source code for each frame.

Would be great to have similar functionality for Rust.

**Comment by SomeoneToIgnore** [comment]
How can I find and run this action?

Searching everywhere does not help:
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/2690773/68425757-65614700-01af-11ea-9ffd-1f0304148514.png">

**Comment by mchernyavsky** [comment]
@SomeoneToIgnore
![image](https://user-images.githubusercontent.com/6079006/68431496-6ef4aa00-01c3-11ea-9b09-36cfc401ec11.png)

**Comment by SomeoneToIgnore** [comment]
Ok, looks like if I enter `analyze stac` it appears, but not a letter before, that's odd.

What's also strange is that it's disabled (notice how gray it is):
<img width="663" alt="image" src="https://user-images.githubusercontent.com/2690773/68433553-7914a980-01bf-11ea-950a-e07366b53c94.png">

If I select it, nothing happens.

Any idea what should I do to make it work?

**Comment by ortem** [comment]
@SomeoneToIgnore Unfortunately, this action is currently disabled in CLion (even with Rust plugin). We'll try to fix this problem on the CLion side and let you know when it is ready. However, you can use `Analyze Stack Trace or Thread Dump...` action in IDEA.

**Comment by ortem** [comment]
Fixed in CLion 2020.1 EAP (coming soon).
