### ISSUE TITLE
Extract function action produces weird output for Maps

### ISSUE THREAD

**Issue by SomeoneToIgnore** [intellij-rust/intellij-rust#4444]
## Environment

* **IntelliJ Rust plugin version:** 0.2.106.2134-193
* **Rust toolchain version:** 1.37.0 (eae3437df 2019-08-13) x86_64-apple-darwin
* **IDE name and version:** CLion 2019.3 EAP (CL-193.3519.24)
* **Operating system:** macOS 10.14.6

## Problem description

Consider the code:

```rust
fn main() {
    let mut test_map = std::collections::HashMap::new();
    test_map.insert(1, 2);
}
```

Note that there are no `use` declarations for the HashMap, it's used with a fully qualified name.
I would like to extract the `test_map.insert(1, 2);` string into a separate method.
I select it, use extract function action, specify the function name and get the method.

Expected:

```rust
fn populate_map(test_map: &mut std::collections::HashMap<i32, i32>) {
    test_map.insert(1, 2);
}
```

Actual:

```rust
fn populate_map(test_map: &mut HashMap<i32, i32, RandomState>) {
    test_map.insert(1, 2);
}
```

Two things that are weird:

1. No fully qualified name is used. Since I've had no `use`, I would expect the extraction to either use the FQN or add a `use` instead and, potentially, remove the first FQN.

2. A `RandomState` generic pops up. Usually I don't care about the generics that have a default value specified so I would expect it to be omitted.

**Comment by dima74** [comment]
@SomeoneToIgnore looks like it is fixed now:
1. Import for `HashMap` is added
2. No `RandomState` generics thanks to #5312

Here is result in version 0.4.154.4085-212:
```rust
use std::collections::HashMap;

fn main() {
    let mut test_map = std::collections::HashMap::new();
    populate(&mut test_map);
}

fn populate(test_map: &mut HashMap<i32, i32>) {
    test_map.insert(1, 2);
}
```
