### ISSUE TITLE
Add an intention to replace var.clone() with T::clone(&var) for certain types

### ISSUE THREAD

**Issue by SomeoneToIgnore** [intellij-rust/intellij-rust#4451]
## Environment

* **IntelliJ Rust plugin version:** 0.2.106.2134-193
* **Rust toolchain version:** 1.39.0-nightly (6ef275e6c 2019-09-24) x86_64-apple-darwin
* **IDE name and version:** CLion 2019.3 EAP (CL-193.3519.24)
* **Operating system:** macOS 10.14.6

## Problem description

For smart pointers such as `Rc` and `Arc` sometimes it might be a good idea to explicitly indicate that no extra allocation happens by explicitly writing the `Arc::clone` instead of the regular `.clone()` call.

It would be good to have an intention to convert the regular `.clone()` calls into the other version.

Example:

```rust
let test = Arc::new(5);
// I want to turn this
let regular_clone_call = test.clone();
// into this
let explicit_arc_clone = Arc::clone(&test);
```

**Comment by vlad20012** [comment]
What do you think about an intention that converts any method call into UFCS form and vice versa?

**Comment by SomeoneToIgnore** [comment]
Sounds even better.

**Comment by Kobzol** [comment]
Closed by https://github.com/intellij-rust/intellij-rust/pull/5601 and https://github.com/intellij-rust/intellij-rust/pull/5614.
