### ISSUE TITLE
Incorrect type resolution

### ISSUE THREAD

**Issue by khionu** [intellij-rust/intellij-rust#4467]
## Environment

* **IntelliJ Rust plugin version:** 0.2.106.2135-192
* **Rust toolchain version:** nightly-x86_64-pc-windows-msvc rustc 1.39.0-nightly (f0b58fcf0 2019-09-11)
* **IDE name and version:** CLion 2019.2.3
* **Operating system:** Windows 10 Pro x64 1906

## Problem description
I'm not exactly sure what the problem is, but the surface issue is that matching on an `Arc<T>` won't accept `T` LHS patterns, only `Arc<T>`.

## Steps to reproduce
https://gist.github.com/khionu/be678f0ce03ecb10fe597c845e5c8313

**Comment by Kobzol** [comment]
The code that you have posted does not compile with `rustc`. If `match x.deref()` is used instead, it compiles with `rustc` and works in the plugin.
