### ISSUE TITLE
debugging fail: process launch failed: failed to get reply to handshake packet

### ISSUE THREAD

**Issue by lishubing** [intellij-rust/intellij-rust#4469]
## Environment

* **IntelliJ Rust plugin version: 0.2.106.2135-192**
* **Rust toolchain version: 1.37.0**
* **IDE name and version: CLion 2019.2.2**
* **Operating system: macOS Mojave 10.14.6**

## Problem description

debugging failed with message：

```
process launch failed: failed to get reply to handshake packet

Process finished with exit code 0
```

But running rust-lldb from terminal and debugging works fine. And simply running rust program is good too, only debugging failed.

## Steps to reproduce

Simply debugging any rust program in CLion.

**Comment by lishubing** [comment]
@ortem Hi, how are we doing with this issue? Do you need more information?

**Comment by ortem** [comment]
@lishubing Hello, sorry for a long wait. I'd recommend you to update your CLion to the latest version because older versions might have some problems with new macOS. Please inform me if it helps; if not, I'll try to investigate this issue.

**Comment by lishubing** [comment]
@ortem I've updated CLion to 2019.2.4, still the same error.

**Comment by ortem** [comment]
@lishubing Do C/C++ debugging work in your CLion?

**Comment by lishubing** [comment]
@ortem Oh no, it's not working...
This issue seems not be relevant to intellij-rust, pls just close it if needed.

**Comment by ortem** [comment]
@lishubing No problem, please create an issue in [CLion's issue tracker](https://youtrack.jetbrains.com/issues/CPP).
