### ISSUE TITLE
No Type Recognition in For-In Loop

### ISSUE THREAD

**Issue by erayerdin** [intellij-rust/intellij-rust#4477]
I cannot get intellisense in `for ... in ...` loop. For instance:

```
let results: [i32; 3] = [0, 1, 2];
for result in results {
    // no intellisense for `result` in here
}
```

A screenshot:

![no autocomplete in for loop intellij-rust](https://user-images.githubusercontent.com/2399084/65952657-d0419480-e431-11e9-8748-048b153fbd0a.png)

***

# Environment
 - Manjaro 18.1.0
 - rustc 1.37.0 (eae3437df 2019-08-13)
 - cargo 1.37.0 (9edd08916 2019-08-02)
 - rustup 1.18.3 (2019-05-23)
 - **Toolchain:** stable-x86_64-unknown-linux-gnu (default)

## IDE

```
PyCharm 2019.2.2 (Community Edition)
Build #PC-192.6603.34, built on September 10, 2019
Runtime version: 11.0.3+12-b304.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.19.69-1-MANJARO
GC: ParNew, ConcurrentMarkSweep
Memory: 386M
Cores: 2
Registry: 
Non-Bundled Plugins: org.intellij.plugins.markdown, org.toml.lang, org.rust.lang
```

**Comment by ortem** [comment]
@erayerdin your code doesn't compile. You can use `for result in results.iter()` to iterate over an array, and our type inference will work in this case.

**Comment by erayerdin** [comment]
Today in "Issues that will never let you sleep"...

Sorry for that. I'm closing the issue.
