### ISSUE TITLE
Add section to contributing.md for attaching debugger to the plugin host

### ISSUE THREAD

**Issue by bgourlie** [intellij-rust/intellij-rust#448]
I'm having a hard time figuring out how to attach a debugger to the plugin host.  Typically I would use the "Plugin" run configuration but IntelliJ isn't recognizing the module as a plugin so I'm unable to configure it.

**Comment by matklad** [comment]
You run plugin via `runIdea` gradle task (find action > execute gradle task)

**Comment by matklad** [comment]
Has ^^^^ helped?

**Comment by bgourlie** [comment]
It did.  My issue was mostly an intellij UX issue -- I was selecting the
actual `.gradle` file for the Gradle Project field and it was failing to
run anything.  I'm all good now.  I really appreciate the swift response.
