### ISSUE TITLE
Goto Definition doesn't work for path attribute macros

### ISSUE THREAD

**Issue by CAD97** [intellij-rust/intellij-rust#4481]
## Environment

* **IntelliJ Rust plugin:**
0.2.106.2135-192 (Sep 30, 2019)
* **Rust toolchain:**
beta-x86_64-pc-windows-gnu (default)
rustc 1.39.0-beta.1 (968967007 2019-09-24)
* **IDE:**
IntelliJ IDEA 2019.2.2 (Ultimate Edition)
Build #IU-192.6603.28, built on September 6, 2019
Runtime version: 11.0.3+12-b304.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1971M
Cores: 8
Registry: 
Non-Bundled Plugins: [...], org.toml.lang, org.rust.lang

## Problem description

Attribute macros using a path (e.g. `#[lib::foo]`) do not work with Goto Definition. Goto Definition works fine when the macro is imported and used without qualification (e.g. `#[foo]`).

## Steps to reproduce

```rust
// name = "foo"
// lib.proc-macro = true
extern crate proc_macro;
use proc_macro::TokenStream;
#[proc_macro_attribute]
pub fn foo(attr: TokenStream, item: TokenStream) -> TokenStream { item }
```
```rust
// name = "consumer"
// dependencies.foo.path = "path/to/foo"
use lib; use lib::foo;
#[lib::foo] fn does_not_work() {}
#[foo] fn this_does_work() {}
```

**Comment by Kobzol** [comment]
@Undin Go to definition for complex paths in attributes seems to work now, is there something left to resolve here?

**Comment by Undin** [comment]
> is there something left to resolve here?

Yep. For example, a slightly modified code from the  issue:
```rust
//- lib.rs
extern crate proc_macro;
use proc_macro::TokenStream;
#[proc_macro_attribute]
pub fn foo(attr: TokenStream, item: TokenStream) -> TokenStream { item }

//- main.rs
#[lib::foo] // foo cannot be resolved by the plugin
fn does_not_work() {}

fn main() {}
```
