### ISSUE TITLE
Code suggestions, type detection and declaration lookup not working for GitHub dependency

### ISSUE THREAD

**Issue by TerminatorNL** [intellij-rust/intellij-rust#4499]
## Environment

* **IntelliJ Rust plugin version:** 0.2.107.2757-192-nightly
* **Rust toolchain version:** 1.38.0
* **IDE name and version:** IntelliJ IDEA - 0.2.107.2757-192-nightly
* **Operating system:** Fedora 30 (Kernel: 5.2.11-200)

## Problem description
I am unable to get any code suggestions for a dependency that's not hosted on crates.io, but is instead hosted on GitHub ([Azul](https://github.com/maps4print/azul)).

I have whipped up a [minimalist-bug-report.zip](https://github.com/intellij-rust/intellij-rust/files/3693253/minimalist-bug-report.zip) where my problem can be replicated. 

## Observed behavior
`cargo check`, `cargo build` and `cargo run` all work as intended.

There's no type annotations visible, and go-to-declaration does not work for anything related to [azul](https://azul.rs).
![image](https://user-images.githubusercontent.com/13693773/66255303-5afff780-e782-11e9-806e-1f389b46f52b.png)

Other types, like HashMap all work.
![image](https://user-images.githubusercontent.com/13693773/66255319-8be02c80-e782-11e9-846b-521b844404cf.png)

In my main project, where multiple crates are present, it also thinks `Label` is not imported into the scope, while it is. (It thinks I am missing: `iui::controls::Label`, while I explicitly import `azul::widgets::Label`)
![image](https://user-images.githubusercontent.com/13693773/66255446-c26a7700-e783-11e9-818a-a10adf2a488d.png)

This program compiles and runs just fine.

```
/home/predator/.cargo/bin/cargo run --color=always
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/bug_report`
```

## Steps to reproduce

`main.rs` contents:
```rust
extern crate azul;

use azul::{prelude::*, widgets::{label::Label, button::Button}};

struct DataModel {
    counter: usize,
}

impl Layout for DataModel {
    fn layout(&self, _info: LayoutInfo<Self>) -> Dom<Self> {
        let label = Label::new(format!("{}", self.counter)).dom();
        let button = Button::with_label("Update counter").dom()
            .with_callback(On::MouseUp, |cb_info: CallbackInfo<Self>| { cb_info.state.data.counter += 1; Redraw });


        let dom = Dom::div()
            .with_child(label)
            .with_child(button);

        dom
    }
}

fn main() {
    let mut app = App::new(DataModel { counter: 0 }, AppConfig::default()).unwrap();
    let window = app.create_window(WindowCreateOptions::default(), css::native()).unwrap();
    app.run(window).unwrap();
}
```
`cargo.toml` contents:
```toml
[package]
name = "bug_report"
version = "0.1.0"
edition = "2018"

[dependencies]
azul = { git = "https://github.com/maps4print/azul", rev = "5984b8020ca7bbf218af1704243f277f34da600b" }
```

[minimalist-bug-report.zip](https://github.com/intellij-rust/intellij-rust/files/3693253/minimalist-bug-report.zip)

## Settings
![image](https://user-images.githubusercontent.com/13693773/66255529-b4692600-e784-11e9-951d-ad8e707c0f2f.png)

![image](https://user-images.githubusercontent.com/13693773/66255524-aa472780-e784-11e9-810f-bdba52196238.png)

## Thank you!
Thank you for your time and effort in making this fantastic plugin. If there's any more information needed, I'll gladly supply it. I might have missed something.

**Comment by Undin** [comment]
@TerminatorNL thanks for the report!
I've reproduced this issue.
Interesting fact: the reason isn't GitHub-hosted dependency but because of the structure of Azul library. It uses custom paths to `lib.rs` and the plugin failed to find them so all intellisense features don't work
I'm working on fix now
