### ISSUE TITLE
Add link in log that runs rustc --explain

### ISSUE THREAD

**Issue by arlowhite** [intellij-rust/intellij-rust#450]
When you have a message suggesting **rustc --explain**, that line should be hidden.
For example, hide this line:
> examples/test_video.rs:58:57: 58:58 help: run `rustc --explain E0308` to see a detailed explanation

Instead, the **[E0308]** error code above the removed line should be a link that runs `rustc --explain E0308` for you and displays the result in a popup or dialog.

This would make logs a bit shorter and easier to scan visually.

This is low priority, but I think it would be a cool feature and probably fairly easy. Maybe tag this up for grabs?

**Comment by matklad** [comment]
A good idea!

I think that running the compiler and displaying a popup would require too much code for the feature. However, we can simply hyperlink to https://doc.rust-lang.org/error-index.html#E0308

The related class is [CargoConsoleFilter](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/cargo/runconfig/CargoConsoleFilter.kt)

**Comment by himikof** [comment]
Also, it should be noted that explain note format changed between old and [new error formatting](https://internals.rust-lang.org/t/new-error-format/3438). With the new error format, it is just `[--explain E0308]` at the end of the error line. So both old and new formats should be supported.
