### ISSUE TITLE
No type inference

### ISSUE THREAD

**Issue by asv1** [intellij-rust/intellij-rust#4505]
## Environment

* **IntelliJ Rust plugin version:** 0.2.107.2137-192
* **Rust toolchain version:** 1.38
* **IDE name and version:** PyCharm Community 2019.2
* **Operating system:** Windows 10 x64

## Problem description
No type inference in such code

## Steps to reproduce
```rust
fn main() -> Result<(), &'static str> {
    let array = [Err("fail"), Ok(1)];
    let result = array.iter().cloned().collect::<Result<Vec<_>, _>>()?;
    result. // <-- no autocomplete here
    Ok(())
}
```

**Comment by Undin** [comment]
Interesting fact: I can reproduce this issue only when new experimental expansion engine is enabled.
@asv1 Could you confirm it?

**Comment by asv1** [comment]
@Undin

I have no autocomplete with default and experimental engines.
