### ISSUE TITLE
Completing generic types could add `<>` automatically

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#4508]
In code like

```rust
let xs = (0..10)
    .map(|i| i * 2)
    .collect::<Ve/*cursor*/>()
```

it's pretty clear that, for `Vec` completion variant, `<>` would be needed anyway. It would be cool if IDE inserted them automatically, similarly for `()` in function calls.

see https://github.com/rust-analyzer/rust-analyzer/pull/1970

**Comment by Kobzol** [comment]
I started working on this, however there are multiple ways to proceed. There is currently an inspection called `RsWrongTypeParametersNumberInspection` which warns about wrong number of type parameters and if there are parameters when there should be none, it uses the `RemoveTypeParameter` quick fix to remove them.

I can either (ranging from most to least general solution):
1) Extend the inspection to apply a different quick fix if there are missing type parameters, let's say `AddTypeParameter`, which would add the missing type parameters, and then also use this quick fix for code completion.
2) Create a new intention which would add missing type parameters (independent of `RsWrongTypeParametersNumberInspection`) and reuse this intention during code completion.
3) Just modify code completion to add type parameters and don't change the existing inspection.

I think that 1) would be the best solution, as it would allow to add missing type parameters anywhere where there is a generic type/function call (and it could also be reused for code completion). If you think that it's a good idea, I'll start a PR where we can discuss this further. What do you think?
