### ISSUE TITLE
Properly indent known macro calls

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#451]
```Rust
fn foo() {
    write!(&mut self.destination, "{}",
           magic_number);
}
```

gets reformatted to

```Rust
fn foo() {
    write!(&mut self.destination, "{}",
    magic_number);
}
```

And it really should not. It is important that `write!` is a known format-like macro. Unknown macros are properly left intact. @jajakobyly you might want to look into this :)

**Comment by jajakobyly** [comment]
:+1:
