### ISSUE TITLE
Add screenshots to Rust and Toml plugin pages

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#4517]
At this moment, both Rust and Toml plugin pages don't have any screenshot.
![image](https://user-images.githubusercontent.com/2539310/66554469-b997ed80-eb55-11e9-947a-156bbbbf99d1.png)

It would be great to add some screenshots about both plugins

**Comment by MarinaKalashina** [comment]
Done
https://plugins.jetbrains.com/plugin/8182-rust/
https://plugins.jetbrains.com/plugin/8195-toml

**Comment by Undin** [comment]
@MarinaKalashina Thanks!
