### ISSUE TITLE
Unable to infer inner type

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#4519]
## Environment

* **IntelliJ Rust plugin version:** 0.2.107.2137-192
* **Rust toolchain version:** 1.40 nightly
* **IDE name and version:** CLion 2019.2.4
* **Operating system:** Windows 10

## Problem description

The plugin has problems inferring inner type - see the reproduction sample code.

## Steps to reproduce

```rust
trait Foo {
     type Output;
}

macro_rules!  impl_foo {
    ($ty:ident) => (
        impl Foo for $ty {
            type Output = $ty;
        }
    )
}

impl_foo!(u8);

struct Bar<'a, T: 'a>(&'a [u8], PhantomData<T>);

struct WhateverComesAfterBar<T>(PhantomData<T>);

fn foo<'a, T: Foo + 'a>(data: &'a [T]) -> WhateverComesAfterBar<Bar<T::Output>>;

let data: [u8; 16] = [0u8; 16];

// here test is recognized as WhateverComesAfterBar<Bar<?>>
let test = foo(&data);
```

**Comment by Undin** [comment]
Thanks for the report!
The default macro expansion engine doesn't take into account `impl` blocks generated by macros.
Try to enable new experimental macro engine (see #3628)

**Comment by krojew** [comment]
I can confirm the experimental engine works.
