### ISSUE TITLE
Autocomplete for `|` in closures

### ISSUE THREAD

**Issue by SomeoneToIgnore** [intellij-rust/intellij-rust#4524]
## Environment

* **IntelliJ Rust plugin version:** 0.2.107.2135-193
* **Rust toolchain version:** 1.38.0 (625451e37 2019-09-23) x86_64-apple-darwin
* **IDE name and version:** CLion 2019.3 EAP (CL-193.4099.17)
* **Operating system:** macOS 10.15

## Problem description

Similar to the way the plugin autocompletes open brackets with their closed counterparts, add autocomplete for closure parameter declaration delimiters: `|`

```rust
self.0.into_iter().map(/*caret*/
```

I input `|`

Expected:

```rust
self.0.into_iter().map(|/*caret*/|
```

Actual: 

```rust
self.0.into_iter().map(|/*caret*/
```

**Comment by Undin** [comment]
Duplicate of #3830
