### ISSUE TITLE
Error recognizing import

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#4534]
## Environment

* **IntelliJ Rust plugin version:** 0.2.107.2137-192
* **Rust toolchain version:** 1.40 nightly
* **IDE name and version:** CLion 2019.2.4
* **Operating system:** Windows 10

## Problem description

Importing a symbol from the version crate results in an invalid error (see example).

## Steps to reproduce

```rust
use version::{Version, version};

struct Foo
{
    // version is unrecognized despite being imported; removing lowercase "version" from the import solves the issue
    version: Version,
}
```

**Comment by Undin** [comment]
Duplicate of #4509
