### ISSUE TITLE
Lex `&&` in patterns as two separate tokens

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#454]
This line should be changed: https://github.com/intellij-rust/intellij-rust/blob/c2ff917e4d060acb8c3df00836030ba213e2020e/src/main/kotlin/org/rust/lang/core/grammar/rust.bnf#L437

**Comment by jajakobyly** [comment]
There is no way to split token into two. `&&` has to be tokenized as `& &` and then collapsed by parser there `&&` is needed.
