### ISSUE TITLE
Unable to resolve anyhow's `context` with `anyhow!`

### ISSUE THREAD

**Issue by matschaffer** [intellij-rust/intellij-rust#4544]
## Environment

* **IntelliJ Rust plugin version:** 0.2.107.2137-192
* **Rust toolchain version:** rustc 1.37.0 (eae3437df 2019-08-13)
* **IDE name and version:** IntelliJ IDEA 2019.2.3 (Ultimate Edition)
Build #IU-192.6817.14, built on September 24, 2019
* **Operating system:** macOS

## Steps to reproduce

Make a new project, use this as main.rs

```rust
use anyhow::{anyhow, Context, Result as AnyResult};
use std::collections::HashMap;

fn main() -> AnyResult<()> {
    println!("Hello, world!");

    let mut data: HashMap<String, String> = HashMap::new();
    data.insert("foo".to_string(), "bar".to_string());
    data.get("thing").context("no thing in hash")?;

    Err(anyhow!("failed anyway"))
}
```

context will be undefined

![Screen Shot 2019-10-19 at 11 47 21 AM](https://user-images.githubusercontent.com/690/67136781-3cabf880-f266-11e9-91d4-245631afcda1.png)

But this works:

```rust
use anyhow::{Context, Result as AnyResult};
use std::collections::HashMap;

fn main() -> AnyResult<()> {
    println!("Hello, world!");

    let mut data: HashMap<String, String> = HashMap::new();
    data.insert("foo".to_string(), "bar".to_string());
    data.get("thing").context("no thing in hash")?;

    Ok(())
}
```

So perhaps it's a dupe of https://github.com/intellij-rust/intellij-rust/issues/4509 though the symptom doesn't seem as explosive as what's described there.

I can still resolve (and click-navigate) other things like `anyhow!`, `AnyResult`, etc.

**Comment by matschaffer** [comment]
Actually noticed yesterday that I can even click-navigate on `context` despite the error. So seems like it's largely some sort of display-stage bug.

**Comment by pierrehts** [comment]
Still hapenning

**Comment by pierrehts** [comment]
Still happening! Did you figure any workarounds ? It's not blocking on my side tho

**Comment by matschaffer** [comment]
Yeah since it’s mostly just a bit of red, I’ve been ignoring it. Annoying but livable.
