### ISSUE TITLE
Add option to dismiss popup about not configured toolchain

### ISSUE THREAD

**Issue by jajakobyly** [intellij-rust/intellij-rust#455]
![idea_2016-06-13_13-37-23](https://cloud.githubusercontent.com/assets/3450050/16006204/04781b10-316c-11e6-8b28-3974f64196c1.png)
This guy is pretty annoying when I am editing test files for our plugin.

**Comment by matklad** [comment]
I'll do this. As a workaround, you can setup a rust toolchain :)

**Comment by matklad** [comment]
But this option would be project-local, will it be OK with you?

**Comment by jajakobyly** [comment]
that's my intention
