### ISSUE TITLE
Struct implement multi Trait contains same function,  type inference error

### ISSUE THREAD

**Issue by jolestar** [intellij-rust/intellij-rust#4558]
## Environment

* **IntelliJ Rust plugin version:**
0.2.108.2143-193
* **Rust toolchain version:**
rustc 1.38.0 (625451e37 2019-09-23)
rustc 1.39.0-beta.5 (fa5c2f3e5 2019-10-02)
* **IDE name and version:**
CLion 2019.3 EAP
* **Operating system:**
macOS 10.15

## Problem description

<img width="413" alt="Screen Shot 2019-10-24 at 14 38 37" src="https://user-images.githubusercontent.com/77268/67460939-d6ace000-f66e-11e9-8148-4dc443f77bbe.png">

For example, the above code, rustc can compile and run, but intellij-rust-plugin prompts error. 

## Steps to reproduce

edit code in intellij:

```rust
pub trait CustomHash {
    fn hash(&self) -> String;
}

#[derive(Hash)]
pub struct DemoStruct {}

impl CustomHash for DemoStruct {
    fn hash(&self) -> String {
        "hash_str".to_string()
    }
}

fn main() {
    let t = DemoStruct {};
    let hash = t.hash();
    print_hash(hash);
}

fn print_hash(hash: String) {
    println!("hash:{}", hash);
}
```

**Comment by Kobzol** [comment]
Works with the latest version of the plugin.
