### ISSUE TITLE
TeamCity runs failing due to OOM

### ISSUE THREAD

**Issue by akunohomu** [intellij-rust/intellij-rust#4562]
Recent [test](https://teamcity.jetbrains.com/viewType.html?buildTypeId=IntellijIdeaPlugins_Rust_193_TestIdea&guest=1) [runs](https://teamcity.jetbrains.com/viewType.html?buildTypeId=IntellijIdeaPlugins_Rust_192_TestIdea&guest=1) are failing due to out-of-memory error. Some [nightly uploads](https://teamcity.jetbrains.com/viewLog.html?buildId=2604329&buildTypeId=IntellijIdeaPlugins_Rust_192_UploadNightly&guest=1) are failing for same reason.

I don't know how important this is but it's linked from README and almost always says failed now.

**Comment by Undin** [comment]
Now we use GitHub actions for release purposes so I think it can be closed
