### ISSUE TITLE
The second double quote doesn't get automatically added if there's a typo

### ISSUE THREAD

**Issue by Derp0** [intellij-rust/intellij-rust#4564]
## Environment

* **IntelliJ Rust plugin version: 0.2.0.2094-173**
* **Rust toolchain version: 1.38.0**
* **IDE name and version: IntelliJ IDEA Ultimate 2017.3.5**
* **Operating system: Win 7 SP1 x64**

## Problem description
If there's a typo in the code it messes up autocompletion of double quotes.

## Steps to reproduce
Take this code for example:
```
enum Color {
    CMYK{cyan:u8, magenta:u8, yellow:u8, black:u8}
}
```

If I do `println!()` before `CMYK{}` (which gets flagged as a typo) I get the autocompletion correctly like so `println!("")`, but if I try to add the same `println!()` after the typo I only get one double quote like this `println!(")` and I have to manually close it by adding another double quote.

**Comment by Derp0** [comment]
![IntelliJ IDEA Rust Plugin](https://user-images.githubusercontent.com/31321109/67569621-3624f180-f73c-11e9-8a5f-a6a5ac0c0aa3.gif)

**Comment by Derp0** [comment]
Should I update IntelliJ IDEA to fix this problem? I mean does this also happen in the 2019 edition of it or not?

**Comment by vlad20012** [comment]
The issue was fixed a long time ago. The problem is that you use the plugin from 2017. Please, update IntelliJ IDEA to 2019.2.

**Comment by Derp0** [comment]
OK, gonna update to 2019, thanks.
