### ISSUE TITLE
IDE hans loading project

### ISSUE THREAD

**Issue by ucayalifish** [intellij-rust/intellij-rust#4565]
## Environment

* **IntelliJ Rust plugin version: 0.2.108.2148-192**
* **Rust toolchain version: rustc 1.38.0 (625451e37 2019-09-23)**
* **IDE name and version: CLion 2019.2.4, IDEA 2019.2.3 **
* **Operating system: MacOS, Windows**

## Problem description

Both Idea and CLion hang pretty frequently loading various Rust-lang projects. A dialog with loading progress bar appears and stops at about 50% (sometimes less, sometimes more). The application is unresponsive and have to be killed with OS tools. After one or more attempts the project gets loaded and IDE functions in a normal way.

**Comment by Undin** [comment]
@ucayalifish Thanks for the report!
It's not clear without thread dumps but looks like it's known platform bug (see https://youtrack.jetbrains.com/issue/IDEA-220475)
It's already fixed in the latest builds so try to update your IDE to 2019.3 EAPs

**Comment by ucayalifish** [comment]
Thank you for response. The issue is closed.
