### ISSUE TITLE
Cannot Jump to Definition of External Symbols

### ISSUE THREAD

**Issue by webern** [intellij-rust/intellij-rust#4591]
## Environment

* **IntelliJ Rust plugin version:** 0.2.108.2148-192
* **Rust toolchain version:** 
```
rustc 1.36.0 (a53f9df32 2019-07-03)
cargo 1.36.0 (c4fcfb725 2019-05-15)
```
* **IDE name and version:**
```
CLion 2019.2.3
Build #CL-192.6817.18, built on September 24, 2019
Licensed to XYZ / ABC
Subscription is active until May 1, 2020
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 12
Registry: run.processes.with.pty=TRUE, cidr.max.intellisense.file.length=5000000
Non-Bundled Plugins: org.toml.lang, org.rust.lang
```

* **Operating system:** macOS 10.14.6 (18G1012)

## Problem description

I am unable to jump to sourcode definitions of symbols that are defined in extern crates. (I am also unable to jump to sourcecode definitions in the standard library.)

## Steps to reproduce

  * In the project root do `cargo build`.
  * Open the attached project in CLion with the Rust Plugin installed.
  * Use the shared run configuration to run the program.
  * Go to main.rs, line 6 and place your cursor in the `thread_rng` or `rand` symbol.
  * Attempt to GOTO Definition.

### Result

`Cannot find declaration to go to.`

### Desired Result

Jumping to the function definition found in `$CARGO_HOME/registry/src/github.com-1ecc6299db9ec823/rand-0.7.2/src/rngs/thread.rs` `Line 80`

### Image

![image](https://user-images.githubusercontent.com/6260372/68091327-3788a500-fe33-11e9-8ba9-cc23ef337657.png)

## Discussion

I use this functionality extensively in CLion with C++, Goland with Go, and Intellij with Java. It is very important to my productivity.

As of right now I can't tell if this feature is intended to be supported with the Rust plugin, and is not working just for me, or if this feature is not supported for symbols outside of my project.

Thus, I'm not sure yet if this issue is a bug report or a feature request.

## Project

[project.zip](https://github.com/intellij-rust/intellij-rust/files/3802077/project.zip)

**Comment by webern** [comment]
I heard from a user on the Discord channel that it works for them.

How can I completely nuke the state of CLion and the Rust plugin? I have tried "Invalidate Caches and Restart".

I have also tried turning off all but the bare minimum of plugins.

Neither of these worked. How can I completely erase all traces CLion and the Rust plugin from my computer and start over? 

![image](https://user-images.githubusercontent.com/6260372/68221887-fc0ae980-ff9e-11e9-9730-a47b1f9c0d6c.png)

**Comment by mchernyavsky** [comment]
@webern Can you please check your project is presented in Cargo Tool Window? If no, you can attach it manually.

![image](https://user-images.githubusercontent.com/6079006/68226953-f98eab00-0003-11ea-8ca1-07a985259036.png)

**Comment by webern** [comment]
Excellent. I verified on the small test project. When the Cargo project is missing from the Cargo Tool Window, I get the undesired behavior. When the Cargo  project is added to the Cargo Tool Window, I get the desired behavior.

**Comment by Undin** [comment]
I think it can be closed
