### ISSUE TITLE
Add support for @ bindings in slice patterns

### ISSUE THREAD

**Issue by zroug** [intellij-rust/intellij-rust#4593]
Currently they make IntelliJ Rust unusable for the rest of the file.

```rust
#![feature(slice_patterns)]

fn main() {
    match [1, 2, 3] {
        [x, ref xs @ ..] => {
            dbg!(x);
            dbg!(xs);
        }
    }
}
```

## Environment

* **IntelliJ Rust plugin version:** 0.2.109.2778-192-nightly
* **Rust toolchain version:** 1.40.0-nightly

**Comment by Undin** [comment]
@zroug parsing errors should go away after #4778.
You can check it in the latest plugin version.
Type inference for `xs` is not implemented yet.

**Comment by zroug** [comment]
Great, I can confirm that the parsing issue is gone. That makes working with this feature much easier.

**Comment by Undin** [comment]
I've created a more generic issue about subslice pattern support - #4917
So I think it can be closed because it's more about syntax error that was already fixed
