### ISSUE TITLE
Trait type inference error

### ISSUE THREAD

**Issue by s97712** [intellij-rust/intellij-rust#4599]
## Environment

* **IntelliJ Rust plugin version:** 0.2.109.2149-192
* **Rust toolchain version:** rustc 1.40.0-nightly (22bc9e1d9 2019-09-30)
* **IDE name and version:** idea-IC-192.6817.14
* **Operating system:** arhclinux

## Problem description
```rust
trait A {
  type Test = ();
}
struct B {}
impl A for B {
  type Test = bool;
}

struct ExtractType<T: A> {
  v: A::Test
}

fn test (arg: ExtractType<B>) {
  let v = arg.v;
  // the variable shoud be Inferred to be bool, but it actual infererd to ()
}
```

**Comment by Kobzol** [comment]
This code does not seem to be valid and compilable by `rustc`. Apart from the unstable associated type default, the actual syntax should be either `T::Test` or `<T as A>::Test` (see https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=31495e21fa255f001fa8a41a89bb589d).

With both `T::Test` and `<T as A>::Test`, the plugin correctly infers the type to be `bool`.
