### ISSUE TITLE
Resolve & completion for functions declared in foreign mods

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#460]

**Comment by matklad** [comment]
closed by https://github.com/intellij-rust/intellij-rust/commit/46e2eabee1251b3c21d3c9e399eab3292748195e

**Comment by alexeykudinkin** [comment]
You can close issues automatically just mentioning "Fixes #460" in the commit message.

**Comment by matklad** [comment]
Yep, I do this most of the time, but sometime I just forget to.
