### ISSUE TITLE
Support cfg attribute in resolve

### ISSUE THREAD

**Issue by HybridEidolon** [intellij-rust/intellij-rust#461]
Currently working on a library that has different implementations based on the target OS, ala

``` rust
#[cfg(target_os = "linux")]
#[path="impl/linux/mod.rs"]
mod impl;

// ...
```

The resolve engine should ignore module declarations whose config attributes do not match.

This also depends on support of the path attribute in module declaration resolve.

**Comment by matklad** [comment]
Another approach is to use multiresolve here. I don't know which one is better: multiresolve seems more correct, but using the `cfg` for the current machine is more convenient.

**Comment by Furyhunter** [comment]
It could also depend on the toolchain being used.

Multiresolve may work for direct references to the module, but imports from it would still have to be single resolves.

**Comment by Undin** [comment]
Let's close it to have single root [issue](https://github.com/intellij-rust/intellij-rust/issues/1191) about `cfg` support
