### ISSUE TITLE
unresolved reference: File with async_std (async code)

### ISSUE THREAD

**Issue by stephanbuys** [intellij-rust/intellij-rust#4614]
## Environment

* **IntelliJ Rust plugin version:** 0.2.109.2149-192
* **Rust toolchain version:** 1.39.0 (4560ea788 2019-11-04) x86_64-apple-darwin
* **IDE name and version:** CLion 2019.2.4 (CL-192.6817.32)
* **Operating system:** macOS 10.15.1

## Problem description

async_std
https://docs.rs/async-std/0.99.12

async_std includes a File struct but it's displayed as Red (ie, the Unresolved reference: `File`) error. 

## Steps to reproduce

Open https://github.com/async-rs/async-std/blob/master/examples/print-file.rs

**Comment by Undin** [comment]
Thanks for the report!
The reason of unexpected error annotation is that almost all `mod` declarations are produced by macros in `lib.rs`.
The default macro expansion engine doesn't take into account `impl` blocks and `mod` declaration generated by macros.
Try to enable new experimental macro engine (see #3628) - it should solve your issue

**Comment by stephanbuys** [comment]
It does thank you!
