### ISSUE TITLE
Unable to specify rust source path into zip file

### ISSUE THREAD

**Issue by Furyhunter** [intellij-rust/intellij-rust#462]
The automatic source download sets the standard library path to a reference inside the zip ala:

```
/Users/Eidolon/rust-1.9.0-src.zip!/rust-1.9.0/src
```

However, the configuration dialog will not let you set this same path yourself.

Throwing code: https://github.com/intellij-rust/intellij-rust/blob/5ae2b8a351a85ebfa83c40c265267dae544c1ec4/src/main/kotlin/org/rust/cargo/project/configurable/RustProjectConfigurable.kt#L60

**Comment by matklad** [comment]
You should be able to set the path to `/Users/Eidolon/rust-1.9.0-src.zip`. I think this is the problem with presentation, that is, the path to zip in the UI should look like `/Users/Eidolon/rust-1.9.0-src.zip`

**Comment by Furyhunter** [comment]
Is there any reason that ! syntax couldn't be allowed, if I e.g. combined sources for several different versions into a single zip?

**Comment by matklad** [comment]
>Is there any reason that ! syntax couldn't be allowed, if I e.g. combined sources for several different versions into a single zip?

It is certainly possible to do so, but I don't think it will bring any benefits. Almost no one will understand that it is possible to select something *inside* the archive, and rust sources are not usually fond in a `.zip` archive. 

This support for `.zip`s is mostly a hack. I wanted to provide a single click "download stdlib" action and, to make it simple, I wanted to avoid extracting archives. And IntelliJ IDEA can work with a zip archive as a file system (this is not possible out of the box for `.tar.gz`, for example), so I've just written some code to grab stdlib `.zip` from GitHub and not a `.tar.gz` from `static.rust-lang.org`.

And, finally, it should be `cargo`'s or `rustup`'s job to download stdlib :) See https://internals.rust-lang.org/t/how-to-provide-standard-library-sources-for-tools/3490/33 and https://github.com/rust-lang/cargo/pull/2768.
