### ISSUE TITLE
Problems tool window missing

### ISSUE THREAD

**Issue by p-avital** [intellij-rust/intellij-rust#4632]
Hello,

Probably the most problematic lacking feature for me is the fact that unlike most other languages handled by IDEA or the language servers available for VSCode, there's no place where all the detected errors and warnings are regrouped.
Any plans on handling that?

Thanks :)

**Comment by mchernyavsky** [comment]
https://github.com/intellij-rust/intellij-rust/pull/3926

You can enable it by setting `cargo.build.tool.window.enabled` variable to `true` (see `Actions > Registry...`).

**Comment by p-avital** [comment]
Thanks, not exactly what I wanted as it doesn't automatically refresh and doesn't include clippy lints, but close enough for now.
Took me a while to find it though, as on my version the key was `org.rust.cargo.build.tool.window`

On the other hand, I just realized that ever since I started using `[workspace]` properly in my "master" crate (working on a project with a lot of subcrates), the paths in `cargo watch`'s output are more informative and AwesomeConsole can now take me to the files, whereas they used to be limited to things like `src/lib.rs` which would make AwesomeConsole ask me to pick the file. So I guess I'll return to my previous workflow of running `cargo watch -x clippy` in an adjacent terminal tab. It's not as nice looking as a proper Problems pane, but good enough.

Thanks for the help :)

**Comment by mchernyavsky** [comment]
@p-avital 
You can use "Run External Linter" action:

![image](https://user-images.githubusercontent.com/6079006/68855460-50c10980-06ef-11ea-8739-a0adab293627.png)

Also, you can run an external linter on the fly (see [Help](https://www.jetbrains.com/help/clion/rust-support.html#project-settings)). IntelliJ will report such errors inline in your text editor.

You may be interested in looking at [this issue](https://github.com/intellij-rust/intellij-rust/issues/3853).
