### ISSUE TITLE
Have any plan to support remote build/run?

### ISSUE THREAD

**Issue by NamsooCho** [intellij-rust/intellij-rust#4651]
Hi.
I am a huge fan of Rust plugin and using CLion for Rust programming.
As my code grows, I feel pain when work using my MacBook Pro.
I wish to work with my macbook to edit code and run a Linux server to build/run my Rust program.
Have any plan for this?

**Comment by nearmax** [comment]
To be more specific, it would be great it Clion Rust could support Full Remote development like it does for C++: https://www.jetbrains.com/help/clion/remote-projects-support.html

**Comment by tweirtx** [comment]
Lack of this feature is why I'm developing a project in VSCode...I'm not gonna manage to get anywhere with JetBrains on a Pi, but I can remote develop on the Pi from my laptop in VSCode

**Comment by daimaxiaxie** [comment]
I also want to develop rust completely remote like C++ in Clion.

**Comment by hameerabbasi** [comment]
Hello. I do a lot of remote development. My workflow typically includes connecting to and debugging/developing on a remote machine completely, without needing to clone/build locally at all, perhaps because of a low-powered machine or one lacking certain hardware features.

One way I can do this easily and in a language-agnostic manner is with VSCode. I do believe CLion/Jetbrains are the superior IDEs in most regards but this one.

**Comment by webern** [comment]
There are two things that keep making me think I should switch to VSCode.

1) Full support for remote development like C++ in CLion.
2) Derive/proc-macro expansion.

derive/proc-macro expansion appears to be getting very, very close. It would be nice to know where remote development lands on the roadmap.

**Comment by seanpianka** [comment]
Support for running cargo commands remotely, in even the simplest of capacities, would be incredibly helpful. Running large compilations over a several hour span of work can really heat up one's laptop, and necessitates being tethered to an outlet, which isn't a fantastic developer experience.

The day I can write Rust and iterate, away from an outlet, with my laptop on my actual _lap_, without it burning me from the scalding CPU exhaust, or draining out of battery in 30 minutes, will be a good day.

**Comment by mchernyavsky** [comment]
@seanpianka See https://github.com/intellij-rust/intellij-rust/pull/6836.

**Comment by seanpianka** [comment]
Thanks for the fast PR, @mchernyavsky. This is an awesome step forward for this feature. 😄

If I understand correctly, this PR adds support for running any cargo command on a remote host over SSH but without support for capturing stderr output in `cargo test` invocations. Is that correct?

I really appreciate the response time!

**Comment by mchernyavsky** [comment]
@seanpianka Yes, I also added an option to choose where you want to build your program. If "Build on remote target" option is enabled, we send the whole working directory to the target and run the project with `cargo` (so you need Rust installation on your SSH server / Docker image / WSL distribution). If "Build on remote target" option is disabled, we build the project locally and then send the executable to the target, so you don't need `cargo` on the target in this case.

> without support for capturing stderr output in cargo test invocations. Is that correct?

Not only in `cargo test`. [Build Tool window](https://github.com/intellij-rust/intellij-rust/pull/3926) also doesn't work, because we can't parse build output properly.

**Comment by seanpianka** [comment]
@mchernyavsky Thanks for the explanation. I cloned and checked-out your branch `run-targets` locally, built the plugin with Gradle command from the contributor's guide, and installed it into the development CLion IDE.

After opening an existing Rust project (i.e. has `.idea/`), I see this IDE error while it's ostensibly performing macro-expansion:
```
Error during macro expansion

java.lang.NoSuchMethodError: 'java.util.List java.util.stream.Stream.toList()'
	at org.rust.lang.core.macros.MacroExpansionTaskBase$submitExpansionTask$1.invoke(MacroExpansionTask.kt:214)
	at org.rust.lang.core.macros.MacroExpansionTaskBase$submitExpansionTask$1.invoke(MacroExpansionTask.kt:193)
	at org.rust.stdext.CompletableFutureKt.supplyAsync$lambda-0(CompletableFuture.kt:14)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by nirvana-msu** [comment]
This has become somewhat redundant with the release of [remote development support](https://youtrack.jetbrains.com/issue/IDEA-226455#focus=Comments-27-5290105.0-0), I would say. It's a nicer way to develop remotely (assuming you do not need a local copy of the files for whatever reason), and this plugin only needs to work with that remote IDE itself (locally) - so you get debugging and everything out of the box, just when developing locally.

**Comment by seanpianka** [comment]
Is there documentation for setting this up with Rust currently, @nirvana-msu? Or is this a feature that still needs to be added?

**Comment by nirvana-msu** [comment]
There is nothing specific to Rust - the feature allows you to work with an IDE running remotely as if it is running locally. Just follow [jetbrains gateway docs](https://www.jetbrains.com/help/go/2021.3/remote-development-a.html) (currently EAP). You then setup up your remote IDE just as you would your local (i.e. use CLion, or IDEA with Rust plugin)

**Comment by seanpianka** [comment]
Awesome! Thank you for explanation and link.

I will check out EAP and dive in soon. Hopefully I can get it working with an existing remote CLion installation.

Perhaps a change to the plugin's README pointing to this documentation would suffice for this issue? At least once remote development is generally available.

**Comment by csnewman** [comment]
> This has become somewhat redundant with the release of [remote development support](https://youtrack.jetbrains.com/issue/IDEA-226455#focus=Comments-27-5290105.0-0), I would say.

"Remote development support" isn't suitable for all targets, such as low power arm devices like the Raspberry Pi, as the remote IDE is too heavy and would likely be too slow. Ignoring the ram and other compatibility issues.

https://github.com/intellij-rust/intellij-rust/pull/6836 works quite well as is with a raspberry pi.

**Comment by webern** [comment]
Is it possible to do remote Rust development right now (2021.3) with the new JetBrains Gateway feature in either CLion or IntelliJ?

https://blog.jetbrains.com/blog/2021/11/29/introducing-remote-development-for-jetbrains-ides/
