### ISSUE TITLE
Exception in typification for items without visitor implementations

### ISSUE THREAD

**Issue by Furyhunter** [intellij-rust/intellij-rust#466]
Attempting to resolve the type of an enum, const, etc. item will result in an UnsupportedOperationException being thrown.

https://github.com/intellij-rust/intellij-rust/blob/ef491ce032b56765493e3e5f5c2429b5dff4af72/src/main/kotlin/org/rust/lang/core/types/visitors/RustTypificationEngine.kt#L134

I question the purpose of throwing an exception here, especially while the implementation is still not complete, because these exceptions leak out into the user view very easily.

**Comment by himikof** [comment]
This regressed when `RustItemElement` became an interface. The visitors in RTE only try to assert correct usage of themselves, unimplemented elements should return `RustUnknownType`.
