### ISSUE TITLE
Unknown error, but compilation is ok

### ISSUE THREAD

**Issue by clintnetwork** [intellij-rust/intellij-rust#4666]
Hi,

We work on the [Lucid ](https://github.com/lucid-kv/lucid) project, I've some errors in Intellij, but on VsCode it's okay and no errors in compilation!

![image](https://user-images.githubusercontent.com/5221349/69250113-60d55f00-0baf-11ea-802b-908d4aa1a581.png)

**Comment by ortem** [comment]
Hi @clintnetwork, thank you for reporting. Our analysis produces some false positives sometimes. In the case of small project like yours, I'd recommend using [Cargo check on the fly](https://www.jetbrains.com/help/clion/rust-support.html#project-settings) and [disable our broken inspections](https://www.jetbrains.com/help/idea/disabling-and-enabling-inspections.html#disable_in_editor) (`Type checker` in your case).

**Comment by clintnetwork** [comment]
Okey @ortem I will do this, IntelliJ with Rust works very fine, so congrats!

**Comment by Kobzol** [comment]
I checked out the corresponding file from Lucid at ~November 2019. The errors are no longer shown in the latest version in the plugin.
