### ISSUE TITLE
Hyper `echo` example compiles and runs but shows squiggly error in CLion IDE

### ISSUE THREAD

**Issue by bes** [intellij-rust/intellij-rust#4668]
## Environment

* **IntelliJ Rust plugin version:**
0.2.110.2150-192
* **Rust toolchain version:**
stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin
* **IDE name and version:**
CLion 2019.2.5
* **Operating system:**
macOS 10.14.6

## Problem description

CLion compiles and runs the example `echo.rs` from https://github.com/hyperium/hyper but shows a red squiggly line with an error message in the IDE

<img width="860" alt="Screenshot 2019-11-21 at 11 04 13" src="https://user-images.githubusercontent.com/85731/69327967-b57be700-0c4e-11ea-9405-53dccfcd815c.png">

## Steps to reproduce

I am using this example (link to tagged version v0.12.35):  https://github.com/hyperium/hyper/blob/v0.12.35/examples/echo.rs which I copied straight into CLion and created a standard run configuration using the "play button" next to `fn main`.

The `Cargo.toml` looks like this
```
[package]
name = "xyz"
version = "0.1.0"
authors = ["abc"]
edition = "2018"

[dependencies]
hyper = "0.12.35"
futures = "0.1"
```

**Comment by dima74** [comment]
Can't reproduce with the latest version. Feel free to reopen or create a new issue if you encounter any problems
