### ISSUE TITLE
Int type after assignment, pluginx point error

### ISSUE THREAD

**Issue by Yanwenjiepy** [intellij-rust/intellij-rust#4672]
## Environment

* **IntelliJ Rust plugin version:**
      0.2.110.2150-192
* **Rust toolchain version:** 
      rustup 1.18.3 (435397f48 2019-05-22)
      rustc 1.36.0 (a53f9df32 2019-07-03)
* **IDE name and version:**
     Clion 2019.2.1
* **Operating system:**
     Linux rabbit 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux

## Problem description
     Int type has the Copy trait, an older variable is still usable after assignment.But plugins point error.
     The program can be compiled and executed normally.

## Steps to reproduce
step1 source code:
```rust
pub fn loop_test() {
    let mut counter = 1;
    let num1: i32;

    let res = loop {
        counter += 1;
        if counter == 10 {
            num1 = counter * 3;
            break counter * 4;  // plugins: Use of moved value
        }
    };

    let num = counter * 2;  // plugins: Use of moved value
    println!("num is: {}", num);
    println!("num1 is: {}", num1);
    println!("res is: {}", res);
}
```

step 2 build and run
```
pylang@rabbit:~/rust_projects/rust_learn$ cargo run src/main.rs 
   Compiling rust_learn v0.1.0 (/home/pylang/rust_projects/rust_learn)
    Finished dev [unoptimized + debuginfo] target(s) in 0.24s
     Running `target/debug/rust_learn src/main.rs`
num is: 20
num1 is: 30
res is: 40
```

**Comment by vlad20012** [comment]
I can't reproduce it. Do you use the new macro expansion engine? (#3628)

**Comment by Yanwenjiepy** [comment]
I feel so strange, after I restarted my computer and then reopened my CLion, the problem was gone.
However, after I updated the plugin, I did restart the CLion many times. I always had the previous problem, but after I restarted the computer, it was fixed.
