### ISSUE TITLE
Mismatched types: in qrcode crate

### ISSUE THREAD

**Issue by citizen-stig** [intellij-rust/intellij-rust#4702]
## Environment

* **IntelliJ Rust plugin version: 0.2.110.2150-192**
* **Rust toolchain version: rustc 1.35.0 (3c235d560 2019-05-20)**
* **IDE name and version: CLion 2019.2.5 Build #CL-192.7142.39, built on October 29, 2019**
* **Operating system: macOS Mojave 10.14.6**

## Problem description

CLion with Rust plugin complains about incorrect type from simple example from [qrcode](https://docs.rs/qrcode/0.11.0/qrcode/) crate:

<img width="685" alt="Screenshot 2019-11-27 at 19 15 02" src="https://user-images.githubusercontent.com/3115300/69749938-ddd27c80-114b-11ea-82d5-437ea9dfb574.png">

## Steps to reproduce

1. Create an new project
1. add qrcode to dependencies
1. use this sample in main.rs https://gist.github.com/citizen-stig/a2ee28d8b1e0ad4f32385a7a7657c2cc

**Comment by ortem** [comment]
Hi @citizen-stig, enabling [experimental macro engine](https://www.jetbrains.com/help/clion/rust-support.html#project-settings) should solve your problem.

**Comment by citizen-stig** [comment]
Hi @ortem!

Thanks for quick reply and experimental macro engine really helped:

![Screenshot 2019-11-28 at 17 55 57](https://user-images.githubusercontent.com/3115300/69823162-74647380-1208-11ea-95e1-0cc29c8dd43e.png)
