### ISSUE TITLE
Support `paste::item!` macro.

### ISSUE THREAD

**Issue by wdanilo** [intellij-rust/intellij-rust#4707]
Hi guys! I know that implementing support for proc macros is hard and I highly appreciate your work in this direction. However, I've got a simple request here - why don't we support the `paste` macro as a special case built-into IntellIJ? https://docs.rs/paste/0.1.6/paste

I believe supporting it as a special case would not require a lot of work, while this macro is one of the most useful macros we can ever imagine - it allows compile-time concatenation of tokens, and allow for amazing things. A simple example - generation of getters and setters:

```rust
macro_rules! mk_accessors {
    (self . $target:ident . $field:ident : $type:ty) => { paste::item! {
        pub fn $field(&self) -> &$type {
            &self.$target.$field
        }

        pub fn [<$field _mut>](&mut self) -> &mut $type {
            &mut self.$target.$field
        }

        pub fn [<set_ $field>](&mut self, t:$type) {
            *self.[<$field _mut>]() = t;
        }
    }};

    (self . $target:ident .  { $($field:ident : $type:ty),* } ) => {
        $(mk_accessors!{self . $target . $field : $type})*
    };

    ($(self . $target:ident . $field:ident : $type:ty),*) => {
        $(mk_accessors!{self . $target . $field : $type})*
    };
}

pub struct HierarchicalTransform<OnChange> {
    origin    : Matrix4<f32>,
    transform : Transform,
    dirty     : dirty::SharedBool<OnChange>
}

impl<OnChange> HierarchicalTransform<OnChange> {
    mk_accessors! {
        self.transform.position : Vector3<f32>,
        self.transform.rotation : Vector3<f32>,
        self.transform.scale    : Vector3<f32>
    }
}
```

**It would allow to drastically cut the amount of manually generated boilerplate in our codebases.**

**Comment by aldanor** [comment]
@Undin this issue is marked as closed by #6908, however the following doesn't work, wonder if there's something I'm missing?

```rust
macro_rules! def {
    ($name:ident) => {
        paste::paste! { fn $name() {} }
    };
}

struct X;

impl X {
    def!(f1);
}

fn f2() {
    X::f1() // <-- autocomplete here doesn't work, `X::f1` not found 
}
```

Note also that the macro is now called `paste::paste!` (and not `paste::item!`).

**Comment by Undin** [comment]
@aldanor What version of the plugin do you use? Have you enabled `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` [experimental](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features)) features as described in #6908?

**Comment by aldanor** [comment]
@Undin apologies, my bad! Enabled both (enabling the build script part is a bit scary, but so far so good) - and paste-like macros are expanded correctly now in impl blocks.
