### ISSUE TITLE
Grazie plugin issues

### ISSUE THREAD

**Issue by ice1000** [intellij-rust/intellij-rust#4725]
## Environment

* **IntelliJ Rust plugin version:** 0.2.112.2804-193-nightly
* **Rust toolchain version:** 1.39.0 (4560ea788 2019-11-04) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2019.3 (CL-193.5233.103)
* **Operating system:** Windows 10 10.0

## Problem description

![image](https://user-images.githubusercontent.com/16398479/70201421-a08a6380-16e4-11ea-8ddc-90567b2732a8.png)

This is very normal doc comment, with no repeated whitespaces. I guess intellij rust passes the indentation text to grazie.

**Comment by lancelote** [comment]
Hi @ice1000, which Grazie version do you have? 2019.3-6.2.stable with Rust plugin 0.2.112.2806-193-nightly works fine for me.

**Comment by ice1000** [comment]
I'm using grazie from plugin marketplace 2019.3-6.2.stable

**Comment by lancelote** [comment]
Reproducible example

```
mod foo {
    
    /// Bar
    /// Foo
    fn bar() {}
}
```

**Comment by kurikomoe** [comment]
I can confirm that it still appear up to now (2020-3-10)

<img width="192" alt="image" src="https://user-images.githubusercontent.com/31176859/76324099-81712280-6320-11ea-932b-3643d8177690.png">

Environment:
Grazie 2019.3-6.2 stable
Rust 0.2.118.3009-193-nightly
Clion 2019.3.4

**Comment by ice1000** [comment]
Is this fixed?

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/94470668-93ea7500-01fa-11eb-8b3e-fed0cb379a68.png)

Seems the answer is yes
