### ISSUE TITLE
Implement Members not available when there are still default functions to implement

### ISSUE THREAD

**Issue by diondokter** [intellij-rust/intellij-rust#4728]
## Environment

* **IntelliJ Rust plugin version:** 0.2.111.2147-193
* **Rust toolchain version:** 1.41 nightly
* **IDE name and version:** IntelliJ 2019.3
* **Operating system:** Windows 10 Pro 64-bit 1909

## Problem description
When implementing a trait for a struct, there's the option to auto implement the members of that trait.
![afbeelding](https://user-images.githubusercontent.com/8545127/70248476-3ec90880-177b-11ea-8867-fd2bf4d67239.png)
The menu auto selects the required members and allows you to additionally select the default functions.
![afbeelding](https://user-images.githubusercontent.com/8545127/70248535-543e3280-177b-11ea-9b24-7ffbd4d9cc91.png)

When all the required functions have already been implemented, this menu doesn't appear anymore. It would be an improvement to have that menu available to be able to quickly implement the default functions at a later point.

## Steps to reproduce
1. Implement all required trait functions.
![afbeelding](https://user-images.githubusercontent.com/8545127/70248808-c747a900-177b-11ea-8fab-e686763d57e5.png)
2. Put cursor on the impl line and press 'alt+enter'.
3. The option to implement members is not there.
![afbeelding](https://user-images.githubusercontent.com/8545127/70248946-fb22ce80-177b-11ea-9e21-7c52088f7ce8.png)

**Comment by Undin** [comment]
You can invoke the same dialog via `Implement methods` action (<kbd>⌘ + I</kbd>/<kbd>Ctrl + I</kbd>) inside impl
