### ISSUE TITLE
Switch Grammar Kit to ElementVisitor with result

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#473]

**Comment by matklad** [comment]
@alexeykudinkin I've just tried to pull this off and came to the conclusion that it's better not to do this. 

The main problem is that while `RustElementVisitor` is "computing", it still inherits from `PsiVisitor`, which is not "computing", so you'll get, e.g, this footgun:

```Java
  public R visitComposite(@NotNull RustCompositeElement o) {
    visitElement(o); // visitElement returns void because it's from PsiElementVisitor
    return null;
  }
```

And it seems impossible to actually get the result back =\ 

`Impl` classes has a corresponding 

```Java
  public <R> R accept(@NotNull RustElementVisitor<R> visitor)
```

But in the interface you have only 

```Java
  public void accept(@NotNull PsiElementVisitor visitor)
```

Instead, I think we can provide an API which encapsulates the access to lateinit variable, here is [an example]. Or we can just leave things as they are and just write more tests :) 

[an example]: https://github.com/intellij-rust/intellij-rust/commit/cf6ace41c70871213267efd0fd926c665307c29b#diff-3ca103da9aafbfce18a798cd68c9e0faR15

**Comment by matklad** [comment]
@alexeykudinkin thoughts?

**Comment by alexeykudinkin** [comment]
Yeah, `PsiElementVisitor` complicates those things.

**Comment by alexeykudinkin** [comment]
But i'd like the idea of `RustComputingVisitor` (though i'd rather change `go` for `set`, but that's minor).

**Comment by matklad** [comment]
Closed

https://github.com/intellij-rust/intellij-rust/commit/5509878c7145f23a6474565bb1c3c94f4ecf2ae9

https://github.com/intellij-rust/intellij-rust/commit/670cbbc4080d6ec061440c000f33bf830d360c90
