### ISSUE TITLE
IDE does not infer array size

### ISSUE THREAD

**Issue by p0lunin** [intellij-rust/intellij-rust#4738]
## Environment

* **IntelliJ Rust plugin version:** 0.2.111.2147-193
* **Rust toolchain version:** rustc 1.37.0 (eae3437df 2019-08-13)
* **IDE name and version:** PyCharm 2019.3 Community Edition
* **Operating system:**

## Problem description

Editor does not highlight array size when I initialize an array with a size constant BAR, which is equal to the constant FOO + 1.

## Steps to reproduce
```rust
const FOO: usize = 1;
const BAR: usize = FOO + 1;
fn main() {
    let bar = [0; BAR];
}
```

**Comment by ortem** [comment]
@p0lunin thanks for reporting. The issue is related to type inference so I've changed your title to a more specific one.
