### ISSUE TITLE
Detect #[tokio::test] attribute as testable function

### ISSUE THREAD

**Issue by fujiapple852** [intellij-rust/intellij-rust#4746]
## Feature request

Tokio 0.2.x provides the [tokio::test](https://docs.rs/tokio/0.2.4/tokio/attr.test.html) attribute for defining async tests.  The plugin does not detect these as a testable functions, i.e. no green "run" arrow is shown in the IDE (tested in CLion).

The `#[tokio::test]` attribute is implemented as a procedural-macro which ultimately outputs a standard `#[test]` attribute (see [here](https://docs.rs/tokio-macros/0.2.0/src/tokio_macros/lib.rs.html#201)).  Given the plugin does not currently expand procedural macros it makes sense that it would not detect these.

Assuming support for procedural macro expansion is not imminent, it may be helpful to expand the detection logic for testable functions to cover attributes matching the pattern `#[.*::test]`.

**Comment by Undin** [comment]
@fujiapple852 Thanks for the report and suggestion!
It's a really good idea. I think the pattern should be a little bit less restricted, something like `#[.*test]` to handle `#[cargo_test]` and similar attributes
