### ISSUE TITLE
Type inference breaks with Iterator flatten

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [intellij-rust/intellij-rust#4751]
## Environment

* **IntelliJ Rust plugin version:** 0.2.113.2810-193-nightly
* **Rust toolchain version:** 1.39 stable
* **IDE name and version:** IntelliJ IDEA 2019.3
* **Operating system:** Windows 10 x64

## Problem description
Calling `flatten` in an iterator chain breaks type inference further along.

## Steps to reproduce

main.rs (working version):

```rust
fn main() {
    let data = vec![vec![1, 2, 3], vec![4, 5, 6]];
    handle(&data[..]);
}

fn handle(slice: &[Vec<i32>]) -> Vec<i32> {
    slice
        .iter()
        .flat_map(|d| d)
        .map(|data| data + 1)
        .collect()
}
```

Type inference on the `map` call works, inferring `&i32` for `data`.

main.rs (broken version):

```rust
fn main() {
    let data = vec![vec![1, 2, 3], vec![4, 5, 6]];
    handle(&data[..]);
}

fn handle(slice: &[Vec<i32>]) -> Vec<i32> {
    slice
        .iter()
        .flatten()
        .map(|data| data + 1)
        .collect()
}
```

No type inference on the `map` call after `flatten`.

Experimental macro expansion engine is enabled.

**Comment by Kobzol** [comment]
Works in the latest version of the plugin.
