### ISSUE TITLE
Enable Clippy in IntelliJ

### ISSUE THREAD

**Issue by JosephTLyons** [intellij-rust/intellij-rust#4756]
## Environment

* **IntelliJ Rust plugin version: 0.2.111.2147-193**
* **Rust toolchain version: not sure how to check, but I am using the most current version of Rust (1.39.0)**
* **IDE name and version: IntelliJ 2019.3**
* **Operating system: macOS 10.15.2**

## Problem description
I can't seem to find out if there is a way to enable Clippy warnings within IntelliJ using the Rust plugin.  If anyone could let me know if this is possible, and if so, could point me towards some setup document, that would be greatly appreciated.  Thank you very much.

**Comment by Undin** [comment]
You can find the corresponding options here `Preferences | Languages & Frameworks | Rust | Cargo`. You need to enable `Run external linter to analyze code on the fly` option and choose `Clippy` in  `External linter` combobox.
BTW, there is useful action to create issue `Help | Create New Issue`. It fills all environment fields

**Comment by JosephTLyons** [comment]
> You can find the corresponding options here `Preferences | Languages & Frameworks | Rust | Cargo`. You need to enable `Run external linter to analyze code on the fly` option and choose `Clippy` in `External linter` combobox.
> BTW, there is useful action to create issue `Help | Create New Issue`. It fills all environment fields

Excellent.  So I notice that I have to deselect `Cargo Check` in order to select `Clippy`, will this result in the loss of any warnings / errors from Cargo?

**Comment by Undin** [comment]
> will this result in the loss of any warnings / errors from Cargo?

It shouldn't - Clippy includes all compiler warning/error messages and provides additional own ones

**Comment by JosephTLyons** [comment]
> > will this result in the loss of any warnings / errors from Cargo?
> 
> It shouldn't - Clippy includes all compiler warning/error messages and provides additional own ones

Awesome!  Thank you very much for your help!  It is much appreciated!

**Comment by norru** [comment]
How do I enable Clippy reports for the whole solution rather than one file at a time?

**Comment by ozkriff** [comment]
@norru you can create a run configuration for clippy using [the "run cargo command" action](https://plugins.jetbrains.com/plugin/8182-rust/docs/cargo-command-configuration.html#run-command) and it'll show the complete output in the build panel:
![image](https://user-images.githubusercontent.com/662976/197349248-036f2f57-e22f-4a1f-9f5d-b65ecc4bccf6.png)

**Comment by norru** [comment]
I know I can run a build.

I want Cargo Clippy to run *without me triggering a build*. The IDE already does it when I open a file and shows me the issues in the "problems" view.
