### ISSUE TITLE
Feature Request - option to not step into core Rust code while debugging

### ISSUE THREAD

**Issue by GrumpyMetalGuy** [intellij-rust/intellij-rust#4764]
It would be super helpful to have a facility for the Rust plugin similar to the one for JS and Python under Build, Execution, Deployment -> Debugger -> Stepping to not step into the Rust core code when debugging. I don't really want to step into collections code or similar, and it would be nice to have the plugin do this for me.

Bonus points if there's also a feature to list crates that can be skipped over too :)

**Comment by Scordo** [comment]
I would really appreciate it, too.

**Comment by GrumpyMetalGuy** [comment]
Looks like, similar to #4763 , you can add something like:

skip -rfu ^(std)|(core)|(alloc)::.*

to .gdbinit to skip over these. Clearly not exhaustive, but a step in the right direction...
