### ISSUE TITLE
Cannot run from editor gutter icon

### ISSUE THREAD

**Issue by Rhywun** [intellij-rust/intellij-rust#4766]
## Environment

* **IntelliJ Rust plugin version:** 0.2.112.2148-193
* **Rust toolchain version:** 1.41.0
* **IDE name and version:** IDEA 2019.3.1 (Community)
* **Operating system:** macOS Catalina v10.15.1

## Problem description
The editor's 'Run' gutter icon no longer offers options to Run the current crate. 

It did work for awhile after the latest plugin update so I am not sure if the update caused this problem or something else caused it. 

Another change is that a couple days after the latest plugin update, I enabled the REPL which is a new feature of the update, and that is when I noticed the Run icon stopped working properly. However, I disabled the REPL again and the Run icon still doesn't work, so that seems unrelated too.

## Steps to reproduce

1. Create new Rust binary anywhere
2. Navigate to the `main` function in src/main.rs
3. Click on the Run icon that appears in the gutter
4. The popup menu reads "Nothing Here"

Expected - menu reads "Run [name of crate]" plus two other entries which I don't remember the exact wording.

**Comment by andrey-yantsen** [comment]
@Rhywun just a quick check: do you have Kotlin plugin enabled? Any chance Gradle plugins are disabled/not installed?

I had the same issue with PHP and got it resolved by enabling gradle plugins, see the discussion in comments for https://youtrack.jetbrains.com/issue/KT-34503.

**Comment by Rhywun** [comment]
Both were enabled. **Disabling** the Gradle plugin solved the issue. (The Kotlin plugin enabled/disabled has no impact on the issue.)

Weird. Seems like a Gradle plugin bug. But thanks for pointing it out!
