### ISSUE TITLE
Drop Item suffix

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#477]
Such that `RustStructItemElement` becomes `RustStructElement`.

**Comment by alexeykudinkin** [comment]
What for?

**Comment by matklad** [comment]
>RustItemElement is now an interface. Should we change RustStructItemElement to RustStructElement perhaps?

Looks like `Item` says essentially nothing.

**Comment by alexeykudinkin** [comment]
That's induced primarily by the grammar, following the Rust's one (also following `parser.rs` convention). Seems like this refactoring brings essentially nothing.

**Comment by matklad** [comment]
Point about `parser.rs` is a valid one, then let's leave it as is, though this `ItemElement` sounds like `ThingThing`.
