### ISSUE TITLE
False-positive "method is private" error when accessible trait method shadows inaccessible inherent method

### ISSUE THREAD

**Issue by abonander** [intellij-rust/intellij-rust#4794]
CLion 2019.3.2
Build #CL-193.5662.56, built on December 18, 2019
Rust plugin version 0.2.112.2148-193

The following test runs and prints `<Foo as Bar>::bar()` as expected:
![image](https://user-images.githubusercontent.com/3198595/71535854-3c5f5780-28be-11ea-94c6-24db4db07b05.png)

**Comment by dima74** [comment]
Looks like it was fixed some time ago. Feel free to reopen or create a new issue if you encounter any problems
