### ISSUE TITLE
Incorrect typechecking when returning from an async block

### ISSUE THREAD

**Issue by whatisaphone** [intellij-rust/intellij-rust#4808]
## Environment

* **IntelliJ Rust plugin version:** 0.2.113.2150-193
* **Rust toolchain version:** 1.40.0 (73528e339 2019-12-16) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2019.3.1 Community Edition (IC-193.5662.53)
* **Operating system:** Windows 10 10.0

## Problem description

I noticed some incorrect typechecking when returning from an `async` block:

```rust
use std::{future::Future, pin::Pin};

pub fn test() -> Pin<Box<dyn Future<Output = i32>>> {
    Box::pin(async {
        return 10;
    })
}
```

`rustc` compiles this code just fine. However, this plugin expects the expression `10` to have the type `Pin<Box<Future<Output=i32>>>`.

![Screenshot](https://i.imgur.com/cyHBidJ.png)         

I searched and the closest issue I could find is #3870/#3875 which may or may not be related.

**Comment by Restioson** [comment]
Similarly, on the latest version, early returns get a `mismatched types` error, but `expected (), found i32`: 
![image](https://user-images.githubusercontent.com/6688948/72448706-24456e80-37c0-11ea-950c-af9fcad7a8aa.png)

This async block happens to be in a (non-async) function returning `()`. Changing its return type to `f32` changes the error to say `expected f32`. 
![image](https://user-images.githubusercontent.com/6688948/72448985-9ddd5c80-37c0-11ea-991b-6adba312aaec.png)
