### ISSUE TITLE
Issue with complex macro expansion (https://seed-rs.org/guide/quickstart)

### ISSUE THREAD

**Issue by stephanbuys** [intellij-rust/intellij-rust#4811]
#4621  Environment

* **IntelliJ Rust plugin version:** 0.2.112.2148-193
* **Rust toolchain version:** 1.40.0 (73528e339 2019-12-16) x86_64-apple-darwin
* **IDE name and version:** CLion 2019.3.2 (CL-193.5662.56)
* **Operating system:** macOS 10.15.2

## Problem description

The plugin has a problem with the macro expansion for view elements with the Seed project.

## Steps to reproduce

Have a look at the quickstart project https://github.com/seed-rs/seed-quickstart/blob/master/src/lib.rs#L30, try adding something a bit more complex for example:

```
    div![
        h4!["Hello world!"],
        button![
            attrs! { At::Class => "classname" },
            simple_ev(Ev::Click, Msg::Increment),
            format!("Hello, World × {}", model.val)
        ]
    ]
```

**Comment by David-OConnor** [comment]
I came here looking to address this specifically; will take a look. These macros are essentially functions that take parameters in an arbitrary order, and each one can be passed an arbitrary number of times; I suspect this will be easy, and apply beyond Seed.

**Comment by k2d2o2** [comment]
Any progress?

**Comment by dima74** [comment]
Should be fixed in [latest nightly](https://intellij-rust.github.io/install.html#nightly-builds) with [new name resolution](https://github.com/intellij-rust/intellij-rust/issues/6217) engine [enabled](https://github.com/intellij-rust/intellij-rust/pull/6378)
