### ISSUE TITLE
Type inference fails with str::split

### ISSUE THREAD

**Issue by fctorial** [intellij-rust/intellij-rust#4815]
## Environment

* **IntelliJ Rust plugin version:**
0.2.113.2150-193
* **Rust toolchain version:**
1.37
* **IDE name and version:**
 CLion 2019.3
* **Operating system:**
Linux

## Problem description

Type inference doesn't work for result of str::split

## Steps to reproduce

Use this minimal code:

```
use std::path::Path;

fn main() {
    "abc def".split(" ");
}
```

**Comment by panstromek** [comment]
This should be fixed with new macro expansion engine. Try to enable it in settings ;)

**Comment by fctorial** [comment]
Yes, it solved the issue.
