### ISSUE TITLE
Syntax parsing leads to hang of IDEA

### ISSUE THREAD

**Issue by sirgl** [intellij-rust/intellij-rust#482]
This part of code immediately leads to hang of IDEA(when there is trailing } ). It is not possible to do something after it, so I can't attach exception message and stacktrace.

```
use std::Vec;

mod BlockArchiver;
    pub fn compute_frequency_table(data : &Vec) -> [u64; 256] {
        let mut byte_frequencies : [u64; 256] = [0; 256];
        for byte in data {
            byte_frequencies[byte as usize] += 1;
        }
        return byte_frequencies;
    }

}
```

**Comment by matklad** [comment]
Is this the whole file? This snippet alone does not freeze my IDE. Can you share the whole file?

**Comment by sirgl** [comment]
Hm, opening file with this code is ok. Yes, it was the whole file. But if you remove in next code bracket after mod and place semi there IDE freezes.
```
use std::Vec;

mod BlockArchiver {
    pub fn compute_frequency_table(data : &Vec) -> [u64; 256] {
        let mut byte_frequencies : [u64; 256] = [0; 256];
        for byte in data {
            byte_frequencies[byte as usize] += 1;
        }
        return byte_frequencies;
    }

}
```

**Comment by matklad** [comment]
Strange. So it seems like it is not related to the parsing, because if it was parsing, then this file alone would be enough to cause a freeze. 

Does

```
use std::Vec;

mod BlockArchiver;
```

causes the same effect? Is the code of you while project available somewhere (e.g., on github?). I supect that this might be an issue with symbols resolve, by I need more context to be able to reproduce it.

**Comment by sirgl** [comment]
exported project [here](https://github.com/sirgl/archiver)
by the way, catched exception, but can't paste stacktrace because exchange buffer is not responding when IDE freezed =(
It is infinite recursion in RustResolveUtil.getCrateResolveUnit

**Comment by matklad** [comment]
Yes, I was able to reproduce it, thanks!

**Comment by matklad** [comment]
Regarding the Rust code, you don't need to write `mod BlockArchiver` inside your `BlockArchiever.rs`

The ideomatic layout will look like this

```
// Directory layout
src/
  lib.rs
  block_archiever.rs

// File lib.rs
mod block_archiever; // note snake_case name
use block_archiever::compute_frequency_table;

// File block_archiever.rs

    pub fn compute_frequency_table(data : &Vec) -> [u64; 256] {
        let mut byte_frequencies : [u64; 256] = [0; 256];
        for byte in data {
            byte_frequencies[byte as usize] += 1;
        }
        return byte_frequencies;
    }
```

And if you do write `mod BlockArchiever;` inside "BlockArchiever", then we get some weird resolve infinite loop :(

**Comment by sirgl** [comment]
It is my first day with rust, don't be strict :) But I think, IDE should resist such kind of strange behavior of some users

**Comment by matklad** [comment]
I am trying to be helpful :) It took me a lot of time to wrap my head around Rust module and crate system, they are indeed complicated.

And of course the IDE should resist this, working on the fix right now ;)
