### ISSUE TITLE
Auto complete not working on wildcard re-exports of another crate

### ISSUE THREAD

**Issue by chinedufn** [intellij-rust/intellij-rust#4830]
## Environment

* **IntelliJ Rust plugin version:** `0.2.113.2150-193`
* **Rust toolchain version:** `rustc 1.42.0-nightly (da3629b05 2019-12-29)`
* **IDE name and version:** `CLion 2019.3.2`
* **Operating system:** `MacOS Mojave`

## Problem description

Autocomplete doesn't work for wild-card re-exports that came from a different crate.

## Steps to reproduce

```rust
// crate-grandchild
pub struct GrandchildStruct {
}
```

```rust
// crate-child
pub use crate_grandchild::*;
```

```rust
// crate-parent
fn main () {
  GrandC // <---- does not auto complete
}
```

**Comment by chinedufn** [comment]
How involved is fixing this for someone with zero Kotlin knowledge?

I’d be happy to work on this with some guidance!

**Comment by chinedufn** [comment]
`web-sys` doesn't use `include!` anymore for the bindings. As of https://github.com/rustwasm/wasm-bindgen/pull/2012

All of the types are now exported via wildcard export.

So this issue is the only thing preventing auto-complete from web-sys I believe.

**Comment by hardiesoft** [comment]
I rolled back to the previous version of web-sys for exactly this reason, but I'm keen to see this be supported too!

**Comment by dima74** [comment]
Wildcard reexports should work in the latest version. Feel free to reopen or create a new issue if you encounter any problem
