### ISSUE TITLE
Missing completion options for itertools::GroupBy 

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#4837]
## Environment

* **IntelliJ Rust plugin version:** 0.2.114.2828-193-nightly
* **Rust toolchain version:** 1.39.0 (4560ea788 2019-11-04) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.1 Snapshot (CL-201.3800)
* **Operating system:** macOS 10.15

## Problem description

Some methods (e.g. `into_iter`) are missing from completion on `itertools::GroupBy` once a closure is passed to `group_by` call.

## Steps to reproduce

```rust
extern crate itertools;

use itertools::Itertools;

fn foo(data: &str) {
    data.chars().group_by(|&chr| chr).into_i
}
```

try finish completion with `into_iter`:

<img width="609" alt="bad" src="https://user-images.githubusercontent.com/2500320/72362399-2a761500-3704-11ea-9520-3d86bb41954b.png">

without the closure:

<img width="784" alt="good" src="https://user-images.githubusercontent.com/2500320/72362407-2ea23280-3704-11ea-9dd4-1e0b9cfe5eee.png">

**Comment by dima74** [comment]
Looks like it was fixed some time ago

![image](https://user-images.githubusercontent.com/6505554/203374688-75cb07de-0f32-4312-8732-b69b38bced76.png)
