### ISSUE TITLE
[Suggestion] Allow Creation of Cargo Crates within non-rust projects.

### ISSUE THREAD

**Issue by chorman0773** [intellij-rust/intellij-rust#4841]
I work with projects consisting of multiple languages, including rust (in particular, Java projects with natives written in rust). However the rust plugin for IntelliJ doesn't allow me to directly create a new crate within an existing (java) project, and requires a roundabout solution to achive. The ability to a) contain the crate within the existing project, and b) have the ability to quickly switch between the crate and the rest of the project are both incredibly useful to have when developing JNI code.

**Comment by Undin** [comment]
> a) contain the crate within the existing project

If you are using IntelliJ IDEA (I think it's true as you mentioned Java project), you can create new Rust module inside your existing project. Just invoke `File | New | Module` action and choose `Rust` option.
<img width="662" alt="Screen Shot 2020-01-17 at 09 33 17" src="https://user-images.githubusercontent.com/2539310/72589480-6d0a3e00-390c-11ea-9d3d-741d338b4c2a.png">
If you want to create module from an existing cargo project, invoke `File | New | Module from Existing Sources` action and point directory where you crate is located. IDE will create new module and add the cargo project into project module

> b) have the ability to quickly switch between the crate and the rest of the project are both incredibly useful to have when developing JNI code.

Sorry, but I didn't catch what does it mean. IntelliJ IDEA shows sources of all modules of a project in [Project View](https://www.jetbrains.com/help/idea/project-tool-window.html) even they are not located in the same directory. Could you provide any details about the desired feature?

**Comment by chorman0773** [comment]
On Fri, Jan 17, 2020 at 01:45 Arseniy Pendryak <notifications@github.com>
wrote:

> a) contain the crate within the existing project
>
> If you are using IntelliJ IDEA (I think it's true as you mentioned Java
> project), you can create new Rust module inside your existing project. Just
> invoke File | New | Module action and choose Rust option.
>

Odd, that option wasn’t available for me for some reason. I had to use a
roundabout method, where I created a new project in the existing folder
from a different window, then open a file to attach the cargo project.

>
> [image: Screen Shot 2020-01-17 at 09 33 17]
> <https://user-images.githubusercontent.com/2539310/72589480-6d0a3e00-390c-11ea-9d3d-741d338b4c2a.png>
> If you want to create module from an existing cargo project, invoke File
> | New | Module from Existing Sources action and point directory where you
> crate is located. IDE will create new module and add the cargo project into
> project module.
>
b) have the ability to quickly switch between the crate and the rest of the
> project are both incredibly useful to have when developing JNI code.
>
> Sorry, but I didn't catch what does it mean. IntelliJ IDEA shows sources
> of all modules of a project in Project View
> <https://www.jetbrains.com/help/idea/project-tool-window.html> even they
> are not located in the same directory. Could you provide any details about
> the desired feature?
>
Apologies, I meant to have that part be interpreted as a result of the
first part. They both refer to the same feature.

**Comment by Undin** [comment]
> Odd, that option wasn’t available for me for some reason. I had to use a
roundabout method, where I created a new project in the existing folder
from a different window, then open a file to attach the cargo project.

Indeed, it sounds really odd. Is this option available for you now?

**Comment by chorman0773** [comment]
It was after I attached the cargo project (I believe it has to do with the fact that it changed some nature of the project, or the equivalent in IntelliJ). It seems to be available now on a new project (that hasn't used rust before. Seems like something was an issue on my end.
