### ISSUE TITLE
Macros language injection

### ISSUE THREAD

**Issue by asimaranov** [intellij-rust/intellij-rust#4844]
I want to inject language to a macros string, but there is no such option (https://www.jetbrains.com/help/clion/using-language-injections.html). 
![image](https://user-images.githubusercontent.com/25568730/72680086-d59d1a80-3ac6-11ea-8c05-9d97026c0461.png)
How may I do that?

**Comment by CraftSpider** [comment]
Just ran into this myself. Having GLSL injection for vulkano shaders would be incredibly handy.
