### ISSUE TITLE
Inspections

### ISSUE THREAD

**Issue by alexeykudinkin** [intellij-rust/intellij-rust#485]
- [ ] Unresolved symbols
- [ ] ?

**Comment by Furyhunter** [comment]
I thought about doing an Unresolved symbols inspection a while back, but without full symbol resolution (especially through macros), it could be very annoying to have enabled.

**Comment by bgourlie** [comment]
Regarding macros, is it possible to implement macro expansion in the plugin and resolve symbols taking the expanded AST into account?

**Comment by Furyhunter** [comment]
Absolutely, we talked about it a bit in gitter. But it is definitely on the backburner compared to other tasks on the roadmap.

**Comment by jajakobyly** [comment]
Maybe Unused variable, function, type, ... ?

**Comment by jajakobyly** [comment]
Usage of unstable item

**Comment by jajakobyly** [comment]
Quickfix: Convert block doc comment (`/** ... */`) to eol doc comment (`/// ...`)

**Comment by johnthagen** [comment]
Variable shadowing
