### ISSUE TITLE
Join lines action doesn't work for doc comments with 2020.1

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#4854]
## Environment

* **IntelliJ Rust plugin version:** 0.2.114.SNAPSHOT-201-dev
* **Rust toolchain version:** 1.40.0 (73528e339 2019-12-16) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.1 EAP (CL-201.3803.17)
* **Operating system:** macOS 10.13.6

## Problem description
Join lines action (`Ctrl+Shift+J`) incorrectly joins doc comment lines with 201 platform.

For the following code 
```rust
//! line 1<caret>
//! line 2

fn main() {}
```

it produces
```rust
//! line 1 //! line 2

fn main() {}
```

instead of
```rust
//! line 1 line 2

fn main() {}
```

The relevant tests were temporarily [disabled](https://github.com/intellij-rust/intellij-rust/blob/c113c6b26334873bf11cf8c03ce3817b6b075d1c/src/test/kotlin/org/rust/ide/actions/RsJoinLinesHandlerTest.kt#L94-L116).

Looks like [RsJoinLinesHandler](https://github.com/intellij-rust/intellij-rust/blob/e494c90ae5b0e2f407d79b5ae4262bf27c62ef37/src/main/kotlin/org/rust/ide/actions/RsJoinLinesHandler.kt) is not called by platform to make proper code transformation

**Comment by Stzx** [comment]
@Undin 

Is there any need to deal with this situation?

```rust
/// a
/// b<caret>
//! c
//! d
```
