### ISSUE TITLE
Add missing fields silently fails for structs with raw identifiers for fields

### ISSUE THREAD

**Issue by maxim-banaev** [intellij-rust/intellij-rust#4861]
## Environment

* **IntelliJ Rust plugin version:** 0.2.114.2151-193
* **Rust toolchain version:** rustc 1.40.0 (73528e339 2019-12-16)
* **IDE name and version:** CL-193.6015.37
* **Operating system:** Windows 10(amd64) v10.0

## Problem description

Given this struct definition:

```rust
use std::os::raw::{c_float, c_int};

pub struct MplaneT
{
    dist: c_float,
    r#type: c_int,
   signbits: c_int,
}
```
...the add missing fields helper will stop at dist and  you'll end up with this:

```rust
impl Default for MplaneT {
    fn default() -> Self {
        Self {
            dist: 0.0,
        }
    }
}
```

The r# syntax is used in rust to escape the names of fields that contain keywords, which is very important for ffi compatibility:

https://doc.rust-lang.org/book/appendix-01-keywords.html
"Raw identifiers are the syntax that lets you use keywords where they wouldn’t normally be allowed. You use a raw identifier by prefixing a keyword with r#."

Submitted to CLion bug tracker as https://youtrack.jetbrains.com/issue/CPP-18787

**Comment by binarycrusader** [comment]
IntelliJ Rust Plugin Version: 0.2.114.2151-193
rustc --version: rustc 1.40.0 (73528e339 2019-12-16)
