### ISSUE TITLE
Extract Inline Module intention only works from root project file

### ISSUE THREAD

**Issue by U007D** [intellij-rust/intellij-rust#4878]
## Environment

* **IntelliJ Rust plugin version:**
0.2.114.2151-193

* **Rust toolchain version:**
rustc 1.40.0 (73528e339 2019-12-16) and rustc 1.42.0-nightly (c2d141df5 2020-01-24)

* **IDE name and version:** 
CLion 2019.3.3
Build #CL-193.6015.37, built on January 20, 2020
Runtime version: 11.0.5+10-b520.30 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-7625-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 32
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: org.toml.lang, org.rust.lang, com.jetbrains.edu

* **Operating system:**
Linux pop-os 5.3.0-7625-generic and Mac OS X 10.15

## Problem description
In `lib.rs` or `main.rs`, an `ALT+ENTER` within an inline module shows `Extract inline module` option, as expected.

But in the resulting (or any other) submodule, `ALT+ENTER` within an inline module does *not* show `Extract inline module` option.

## Steps to reproduce
In `lib.rs`, type:
```rust
mod foo {}
```
with the cursor within the scope of `foo`, press `ALT+ENTER` and select `Extract inline module`.

Now select the newly created `foo.rs` file and type:
```rust
mod bar {}
```
with the cursor within the scope of `bar`, press `ALT+ENTER`.  Note `Extract inline module` is not available.  This is unfortunate, because it means that organization of unit tests into modular sub-groups, for example, must be orchestrated manually.

**Comment by U007D** [comment]
@Undin @ortem Hello, any thoughts or updates?

**Comment by U007D** [comment]
A friendly ping to ask if anyone has been able to repro the issue or not?

**Comment by Undin** [comment]
@U007D Sorry, I missed your issue somehow
Yep, I can reproduce this issue
