### ISSUE TITLE
Implement `CString::new("hello").unwrap().as_ptr()` inspection

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#488]
See the RFC for the discussion: https://github.com/rust-lang/rfcs/pull/1642. The explanation why this is bad can be found [here](https://github.com/rust-lang/rust/commit/33aa3edf246c7f024a54b6ba9cf53bc7ca2c7f18) :) 

Here are some examples of inspections: https://github.com/intellij-rust/intellij-rust/tree/master/src/main/kotlin/org/rust/ide/inspections

**Comment by zjhmale** [comment]
i'm working on this.
