### ISSUE TITLE
The same issue when I'm using the gl crate (https://github.com/brendanzab/gl-rs/tree/master/gl)

### ISSUE THREAD

**Issue by asimaranov** [intellij-rust/intellij-rust#4882]
The same issue when I'm using the gl crate (https://github.com/brendanzab/gl-rs/tree/master/gl)
![image](https://user-images.githubusercontent.com/25568730/73165723-69916680-4105-11ea-9d2f-bb02a41d27c4.png)

_Originally posted by @asimaranov in https://github.com/intellij-rust/intellij-rust/issues/1908#issuecomment-578675123_

**Comment by dima74** [comment]
I can't reproduce it with the latest version. Feel free to reopen or create a new issue if you encounter any problem
