### ISSUE TITLE
Good code red: strange interference between `geo` and `nalgebra` crates

### ISSUE THREAD

**Issue by alexbool** [intellij-rust/intellij-rust#4887]
## Environment

* **IntelliJ Rust plugin version:** 0.2.115.2837-193-nightly
* **Rust toolchain version:** 1.40.0-stable
* **IDE name and version:** IntelliJ IDEA 2019.3.2 (Community Edition)
Build #IC-193.6015.39, built on January 21, 2020
* **Operating system:** macOS 10.15.2 Catalina

## Problem description
Seems like in certain circumstances some methods are resolved incorrectly.

## Steps to reproduce
Imagine a crate like this:
<img width="504" alt="Screenshot 2020-01-28 at 11 11 01" src="https://user-images.githubusercontent.com/1283792/73247237-7f646180-41c1-11ea-93a2-62350dbd0d02.png">
<img width="504" alt="Screenshot 2020-01-28 at 11 11 54" src="https://user-images.githubusercontent.com/1283792/73247254-88edc980-41c1-11ea-9fe1-9e5979c264d5.png">
`Vector4`'s `new` method is not being resolved:
<img width="504" alt="Screenshot 2020-01-28 at 11 12 08" src="https://user-images.githubusercontent.com/1283792/73247259-8be8ba00-41c1-11ea-9b36-bee6530b9234.png">
Now add `geo` crate to the manifest:
<img width="504" alt="Screenshot 2020-01-28 at 11 12 29" src="https://user-images.githubusercontent.com/1283792/73247270-93a85e80-41c1-11ea-9375-e1dbd723bfce.png">
And now this good code is highlighted as bad:
<img width="504" alt="Screenshot 2020-01-28 at 11 12 56" src="https://user-images.githubusercontent.com/1283792/73247285-9c993000-41c1-11ea-8aea-72fe7003b3f1.png">
Surprisingly, the `new` method is being resolved from `PointExt` trait in `rstart` crate!
<img width="504" alt="Screenshot 2020-01-28 at 11 13 11" src="https://user-images.githubusercontent.com/1283792/73247299-a0c54d80-41c1-11ea-80a6-4bd17efdd6b3.png">

Plugin settings:
<img width="1109" alt="Screenshot 2020-01-28 at 11 27 06" src="https://user-images.githubusercontent.com/1283792/73247508-0ca7b600-41c2-11ea-86b5-18fd4f00ec26.png">

**Comment by alexbool** [comment]
@vlad20012 @Undin what can I do to help debug this?

**Comment by flaghacker** [comment]
The same issue happens between `nalgebra` and `exr`, where `Vector4::new` is being resolved to `exr::image::rgba::CreatePixels::new`. Manually copying the relevant  `CreatePixels` trait into the project itself doesn't appear to trigger the bug, I couldn't find a minimal example.

**Comment by flaghacker** [comment]
It looks like without `exr` being included, `Vector4::new()` can't be resolved at all, but the IDE for some reason doesn't mark it as an error. When `exr` is added, the IDE sees `CreatePixels::new` as applicable for some reason and latches onto it, giving an error.

**Comment by flaghacker** [comment]
It looks like this is already fixed on the latest master when experimental macro expansion is enabled.

**Comment by Undin** [comment]
Looks like it's the same issue as #5007
See details answer https://github.com/intellij-rust/intellij-rust/issues/5007#issuecomment-592434057

**Comment by alexbool** [comment]
@Undin There’s also a separate issue that functions that should not autocomplete (from another crate), get autocompleted.
