### ISSUE TITLE
Spurious "Use of moved value" on a u32

### ISSUE THREAD

**Issue by locka99** [intellij-rust/intellij-rust#4902]
## Environment

* Plugin 0.2.114.2151-193
* Rust 1.40.0
* CLion 2019.3
* Windows

## Problem description

I have code that imports std::u32 to get at the u32::MAX const, but it seems to generate a spurious "use of moved value" when I use the same u32 twice in a function:

## Steps to reproduce

In my code base, the word `first` on the line under "next: first," is underlined and marked with error "use of moved value". I assume the plugin sees that I used it on the line previous, thinking it was a move, but as it is a u32 so the compiler would done a copy not a move.

```
use std::u32;

#[derive(Debug, Clone)]
pub struct Handle {
    next: u32,
    first: u32,
}

impl Handle {
    /// Creates a new handle factory, that starts with the supplied number
    pub fn new(first: u32) -> Handle {
        Handle {
            next: first,
            first, // <-- ERROR HERE
        }
    }

    /// Returns the next handle to be issued, internally incrementing each time so the handle
    /// is always different until it wraps back to the start.
    pub fn next(&mut self) -> u32 {
        let next = self.next;
        // Increment next
        if self.next == u32::MAX {
            self.next = self.first;
        } else {
            self.next += 1;
        }
        next
    }

    pub fn set_next(&mut self, next: u32) {
        self.next = next;
    }

    /// Resets the handle to its initial state
    pub fn reset(&mut self) {
        self.set_next(self.first);
    }
}
```

**Comment by vlad20012** [comment]
Hi! Thanks for the report! 
Do you have the new experimental macro expansion engine enabled (#3628)? If yes, this can be the cause... In this case, you can try to restart the IDE or invoke ctrl+shift+A "invalidate caches"

**Comment by locka99** [comment]
I don't have the experimental macro expansion on, it's set to "expand with default engine". I cleared caches and restarted and the issue reappeared. I'll try on my home pc later to see if the issue happens there too.

**Comment by vlad20012** [comment]
Hmm. Don’t you use `rustup override`?

**Comment by locka99** [comment]
No I don't. It's a stable rust set through "rustup default stable-gnu". I'll get back to you tonight because one machine can't fetch from crates.io at the moment and I want to reproduce the behaviour from a machine that is building normally.

**Comment by locka99** [comment]
I'm going to close the issue because it works on the other computer. I think it is because the external crates could not be fetched there was nothing in External Libraries, even a reference to Rust's own stdlib.
