### ISSUE TITLE
async keyword throws IDE error

### ISSUE THREAD

**Issue by filipesmedeiros** [intellij-rust/intellij-rust#4907]
## Environment

* **IntelliJ Rust plugin version:** 0.2.114.2151-193
* **Rust toolchain version:** 1.41.0 (5e1a79984 2020-01-27)
* **IDE name and version:** WebStorm 2019.3
* **Operating system:** Windows10

## Problem description
`async` keywork seems to not get recognized by the IDE/plugin. Error says: "This feature is only available in Edition 2018", but I have a sibling file Cargo.toml with `[package] edition = "2018"`

## Steps to reproduce
Just install plugin, and if you want to reproduce, clone deno, many files have this problem.

Is there anything I'm doing wrong or that I can do to try to fix this?

**Comment by tuzymandias** [comment]
I am experiencing this issue as well. Sometimes it works, but half of the time it doesn't.

**Comment by mchernyavsky** [comment]
Everything works for me (I have checked `deno`). 

![image](https://user-images.githubusercontent.com/6079006/76319352-24f60f00-62f0-11ea-9f89-f8f827f98dc8.png)

Can you please check Cargo Tool Window and make sure your project is attached?

<img width="293" alt="Cargo Tool Window" src="https://user-images.githubusercontent.com/6079006/76319572-79998a00-62f0-11ea-98be-f9d7817fdae6.png">

**Comment by filipesmedeiros** [comment]
I guess something must've been wrong with my config (although it's weird cuz I don't remember having changed anything). It's fixed now! Thanks

**Comment by tuzymandias** [comment]
It wasn't working for me, but I found out the actual problem and I'm posting my finding here just in case another user have the same experience. A crate I was using (`reqwest`) uses macro call to generate its module declaration. Following issue #3628 and using the experimental macro expansion engine solved my problem.

**Comment by detailyang** [comment]
same issue here :(

**Comment by iraizo** [comment]
> It wasn't working for me, but I found out the actual problem and I'm posting my finding here just in case another user have the same experience. A crate I was using (`reqwest`) uses macro call to generate its module declaration. Following issue #3628 and using the experimental macro expansion engine solved my problem.

Im using `reqwest` too, using the new engine and i still got the issue telling me that im not using the 2018 edition

**Comment by marksiano** [comment]
Still an issue, how do I re-open this?

**Comment by sjud** [comment]
I'm getting this issue as well. When I change my crate's cargo file from 2021 to 2018 it goes away, but obviously that isn't much of a fix.
