### ISSUE TITLE
Prelude is not resolved after toolchain override

### ISSUE THREAD

**Issue by Alphare** [intellij-rust/intellij-rust#4930]
I noticed that the general name resolution is broken when there are too many changes (for example when rebasing and moving around in history a lot) and I had to delete the contents of `lib.rs` to fix the issue. Now the prelude is not resolved, which is making it very hard to work even after trying to disable then re-enable the Rust Plugin.

## Environment

* **IntelliJ Rust plugin version:** 0.2.115.2157-193
* **Rust toolchain version:** 1.40
* **IDE name and version:** PyCharm 2019.3 (#PY-193.5233.109)
* **Operating system:** Linux 5.4.0-3-amd6

## Steps to reproduce

I'm not sure when it started. 

If you want the state I'm in: 
```
hg clone https://foss.heptapod.net/octobus/mercurial-devel
hg up b561fdbcc60
cd rust/hg-cpython/
cargo c (to make sure that it compiles)
```

**EDIT:** it seems that the real issue is setting a toolchain override with rustup. It confuses the plugin.

**Comment by Alphare** [comment]
Upgrading to PyCharm 2019.3.2 (Build #PY-193.6015.41, built on January 21, 2020) does not resolve the matter.

**Comment by jrhenderson1988** [comment]
I _think_ I'm seeing the same issue in Intellij IDEA. I'm very new to Rust so I'm not entirely sure but I gather that what is in the [prelude](https://doc.rust-lang.org/std/prelude/index.html) should be automatically imported. I've been following the [tutorial in the book](https://doc.rust-lang.org/book/ch20-03-graceful-shutdown-and-cleanup.html) and have a project that looks like the code at the very end of the page.

I can confirm that it compiles and runs fine (both from Intellij IDEA and Cargo), but Intellij IDEA with the Rust plugin complains about unresolved references for structs that should be imported automatically by the prelude (`Vec`, `Box`, `FnOnce`, `Send`, `Drop`, `Some`, `Option`).

- **IntelliJ Rust plugin version:** 0.2.115.2157-193
- **Rust toolchain version:** 1.40
- **IDE name and version:** Intellij IDEA 2019.3.1 Community Edition (Build #IC-193.5662.53)
- **Runtime version:** 11.0.5+10-b520.17 amd64
- **Operating system:** Windows 10 (Version 1903, Build 18362.592)

**Comment by Undin** [comment]
@Alphare oh, it seems your cargo workspace is not added to the plugin project structure. In this case, the plugin can't attach rust stdlib to it so name resolution doesn't work including all items from prelude. The plugin 
To add the workspace to project structure, invoke `Attach Cargo Project` in context menu on `rust` directory or `rust/Cargo.toml` file
Alternatively, invoke `Attach` action at the top of editor with opened `rust/Cargo.toml` file.

| Context menu | Editor notification |
| -|-|
| ![image](https://user-images.githubusercontent.com/2539310/74130341-dff89300-4bf2-11ea-86bf-9432d9f22661.png) | ![image](https://user-images.githubusercontent.com/2539310/74130419-1afac680-4bf3-11ea-9929-4e30274dd4eb.png) |

It should solve your issue

**Comment by Undin** [comment]
@jrhenderson1988 probably, it's the same issue as described above. But I'm not sure without the exact structure of your project

**Comment by Alphare** [comment]
@Undin I don't see either of those actions. I remember seeing them at the very start of the project, of course, but it looks attached to me. I have the following in my local `.idea/workspace.xml`: 

```
<component name="CargoProjects">                                              
    <cargoProject FILE="$PROJECT_DIR$/rust/Cargo.toml" />                       
</component> 
```

**Comment by jrhenderson1988** [comment]
@Undin I don't seem to have the "Attach Cargo Project" context menu option and I'm not prompted in Cargo.toml either. Hitting `CTRL+SHIFT+A` (Find action...) and typing "Attach Cargo Project" does show a matching the result, but selecting it seems to have no effect for me.

My project layout is a bit different as I don't have a rust subfolder like in OP's example. You can find it [here](https://github.com/jrhenderson1988/rust-webserver).

**Comment by Alphare** [comment]
@Undin I managed to reproduce the same error when switching toolchains in a toy project. It seems that the plugin does not understand/respect the `rustup override set <version>` operations and the setting give no way of changing the toolchain version.

**Comment by Alphare** [comment]
@Undin Are there any plans towards fixing toolchain mismatches? This bug is very visible and annoying.

**Comment by Alphare** [comment]
Confirmed still the case in `0.2.122.3105-201`.

**Comment by Alphare** [comment]
Setting a global override to match the project version fixes the issues, though it's still definitely a bug.

**Comment by Alphare** [comment]
Another, less brutal solution is to use `rustup which cargo` inside the folder with the local override and use the `bin/` folder where this toolchain's cargo is located as the toolchain location, and `lib/rustlib/src/rust/src` as the stdlib location.

That way you can still have the default version be whatever you want, but this is a bit cumbersome.

**Comment by Alphare** [comment]
For those using relatively recent versions of Rust (this comment was prompted by Debian stable's upgrade to 1.41.1), you need to install the `rust-std` component in your `rustup` toolchain to have the `src` folder in `rustlib`.

`rustup component add rust-std`, then (re)install your toolchain.
