### ISSUE TITLE
"Standard library" setting field not accepted

### ISSUE THREAD

**Issue by tanmatra** [intellij-rust/intellij-rust#494]
Regardless the file I choose, after pressing "Ok" button and opening settings again, text field stays empty. I've tried whatever I can, "rust-1.10.0-src.zip", "rust-1.9.0-src.zip", extracted files, or path inside the zip.

Plugin version is 0.0.1.695. IDEA is 2016.2.EAP, but I think it also the same in 2016.1.

**Comment by matklad** [comment]
What os do you use?

**Comment by tanmatra** [comment]
Windows 7 x64

**Comment by matklad** [comment]
Will take a look, it is probably platform specific, I have not tested this feature on windows. Does `Download` link from the in editor notification?

**Comment by matklad** [comment]
I was able to reproduce this issue. It happens if you have an invalid toolchain specified. In my case, I use msvc toolchain without visual studio installed. We should definitely show a proper error message.

**Comment by matklad** [comment]
I've just checked it with a more recent build of a plugin, and it shows a proper error message about invalid toolchain, so I'll close this issue.

**Comment by spencersutton** [comment]
I'm still having this problem with plugin version 0.0.1.743 from nightly repo. The toolchain location is correct, it shows the rust version number and doesn't show an error message (it does if I put in a random location).

OS: OS X 10.11.4
Intellij: 2016.1

**Comment by matklad** [comment]
@spencersutton in the settings you see version numbers for both rustc and Cargo, is this correct?

**Comment by spencersutton** [comment]
@matklad Correct. What I see is this when I reopen the settings menu:

![screen shot 2016-07-01 at 11 13 48 am](https://cloud.githubusercontent.com/assets/5770094/16526011/21364212-3f7d-11e6-8820-665ba0a62cb3.png)

The Rust menu item is also has the blue unsaved changed color but there is no reaction to hitting Apply or Ok and is still there when reopening the settings menu.
![screen shot 2016-07-01 at 11 15 52 am](https://cloud.githubusercontent.com/assets/5770094/16526054/4fae694e-3f7d-11e6-9adf-8ce790930b1f.png)

**Comment by matklad** [comment]
I've found one more case where we don't show an error message. Plugin assumes that you have a `Cargo.toml` in the root directory of your project, and it will not work properly otherwise (in particular, it would be impossible to save standard library location :( ). Do you have `Cargo.toml` in your project?

**Comment by spencersutton** [comment]
`Do you have Cargo.toml in your project?`

I didn't and adding one fixed it. Thanks!
The Cargo.toml I created didn't actually change though.

**Comment by matklad** [comment]
>The Cargo.toml I created didn't actually change though.

I am not sure that I've understood you correctly, but changing the settings should not change `Cargo.toml` in any way.

**Comment by spencersutton** [comment]
`I am not sure that I've understood you correctly, but changing the settings should not change Cargo.toml in any way.`

I think maybe I'm the one who didn't understand correctly. I interpreted `(in particular, it would be impossible to save standard library location :( )` to mean that it would save the path in Cargo.toml but I think you meant it uses that to determine the root directory of the project? I'm very new to Rust so I don't know much about all this :)

**Comment by matklad** [comment]
Yeah, unfortunately at the moment path to standard library is not specified in Cargo.toml, so we have to write some custom code to handle stdlib and provide completions for it. So this "standard library location" is very IntelliJ Rust specific setting. Cargo should provide the ability to specify stdlib in Cargo.toml in the future, and this would greatly simplify things on out side.

So at the moment we use `Cargo.toml` to find an IntelliJ module -- a specific entity which stores IntelliJ representation of the libraries. And if there is no `Cargo.toml`, we just silently do nothing instead of reporting an error.

**Comment by jcbritobr** [comment]
i have the same issue on ubuntu, and toolchain is correct, and the cargo.toml is in root folder

**Comment by matklad** [comment]
@jcbritobr are you using `rustup`?

**Comment by jcbritobr** [comment]
No. I downloaded de offline installer and used the script to install. This is a wrong way?

**Comment by matklad** [comment]
Rustup (https://www.rustup.rs/) is a more convenient way to work with Rust in general, and enjoys better support in IntellijJ as well. 

If you don't use rustup, than to have completion and resovle for symbols from standard library, you'll need to download the sources from https://www.rust-lang.org/en-US/other-installers.html#source, extract them, and put the path to them into the `Standard library` field which should be enabled in that case.

**Comment by jcbritobr** [comment]
Yes, I did, but the Field doesnt save the  changes .
