### ISSUE TITLE
fmt::Debug is not inferred for thread::Result

### ISSUE THREAD

**Issue by Kobzol** [intellij-rust/intellij-rust#4943]
## Environment

* **IntelliJ Rust plugin version:** 0.2.115.2157-193
* **Rust toolchain version:** cargo 1.41.0 (626f0f40e 2019-12-03)
* **IDE name and version:** CLion 2019.3.3 (CL-193.6015.37)
* **Operating system:** Linux 5.0.0-37-generic

## Problem description
`unwrap` is not offered in code completion for Result returned from the `std::thread::JoinHandle::join` method. This is probably caused by the fact that `fmt::Debug` is not inferred for the Error type parameter of the returned Result type, which is `Box<dyn Any + Send + 'static>`.

## Steps to reproduce
```rust
let t = std::thread::spawn(|| ());
t.join()./* unwrap is not offered here */
```
When I use unwrap, it compiles fine, but code completion doesn't offer it.

**Comment by Undin** [comment]
@Kobzol Thanks for the report!

> This is probably caused by the fact that fmt::Debug is not inferred for the Error type parameter of the returned Result type, which is Box<dyn Any + Send + 'static>.

Yeah, looks like the main reason is incorrect processing of `impl` items for `dyn Trait`.
More precisely,  the plugin can't find `impl fmt::Debug for dyn Any { ... }` that provides implementation of `Debug` trait
Should be fixed by #4913
