### ISSUE TITLE
Type alias created by macro not recognized in `use` statement

### ISSUE THREAD

**Issue by CleanCut** [intellij-rust/intellij-rust#4951]
## Environment

* **IntelliJ Rust plugin version:** 0.2.116.2847-193-nightly
* **Rust toolchain version:** rustc 1.41.0 (5e1a79984 2020-01-27)
* **IDE name and version:** IntelliJ IDEA 2019.3.2 Ultimate Edition
* **Operating system:** macOS Mojave 10.14.6

## Problem description

I ran into this doing Amethyst's [pong tutorial](https://book.amethyst.rs/master/pong-tutorial.html).  Honestly, I'm not sure support for a [type alias in a macro](https://github.com/amethyst/amethyst/blob/master/amethyst_rendy/src/types.rs#L93-L110) is even possible.  So I'm not sure if this is a bug, feature request, or an insane wish, but here we go...

`DefaultBackend` is unrecognized in use statements such as

```rust
use amethyst::renderer::types::DefaultBackend;
```

or

<img width="511" alt="image" src="https://user-images.githubusercontent.com/5838512/74113735-64033a00-4b63-11ea-81a8-bf3489183e5a.png">

## Steps to reproduce

```shell
cargo new scratch
cd scratch
```

Add the following line to Cargo.toml's [dependencies] section
```toml
amethyst = "0.14.0"
```

In `main.rs` add:
```rust
use amethyst::renderer::types::DefaultBackend;
```

It won't autocomplete! It won't highlight correctly!

It compiles and  runs fine for me with `cargo run --features=metal`

**Comment by Undin** [comment]
@CleanCut Hi!
The main reason is not macros but the absence of cargo features. To make it compile you pass `metal` feature to the compiler but name resolution in the plugin doesn't know what feature it should use.
To pass this knowledge, just specify the corresponding feature in `Cargo.toml`:

```toml
[dependencies]
amethyst = { version  = "0.14.0", features = ["metal"] }
```

It should solve your issue

**Comment by CleanCut** [comment]
@Undin Thank you, that works!

**Comment by CleanCut** [comment]
@Undin Question: If I am making a _library_ and I don't want to enable this feature for everyone, is there a way I can let IntelliJ know that _I_ want the feature enabled locally, but not enable it for users of my library?

**Comment by vlad20012** [comment]
@CleanCut if you develop a library, currently IntelliJ Rust thinks that all its features are enabled.

**Comment by CleanCut** [comment]
Thanks! That put me on the right path.  I hadn't yet specified features for _my_ library which enabled the features in the dependencies.  When I added this to my `Cargo.toml` then it started working:

```
[features]
metal = ["amethyst/metal"]
```
