### ISSUE TITLE
Support &raw [mut|const] syntax

### ISSUE THREAD

**Issue by CAD97** [intellij-rust/intellij-rust#4954]
## Environment

* **IntelliJ Rust plugin version:** 0.2.115.2157-193  
* **Rust toolchain version:** nightly

## Problem description

`&raw` syntax is not supported.

Tracking issue: https://github.com/rust-lang/rust/issues/64490  
RFC: https://github.com/rust-lang/rfcs/pull/2582

* [x] syntax
* [ ] type inference

**Comment by afetisov** [comment]
I believe this should have been closed by #8410.

**Comment by CAD97** [comment]
Agreed.
