### ISSUE TITLE
use std::os::unix::io::AsRawFd can't not completion

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#4960]
## Environment

* **IntelliJ Rust plugin version:**

0.2.117.2854-193-nightly

* **Rust toolchain version:**

> rustc 1.43.0-nightly (a1912f2e8 2020-02-12)
> binary: rustc
> commit-hash: a1912f2e89b77cfe2a0e64b96f444848fe4e2d49
> commit-date: 2020-02-12
> host: x86_64-unknown-linux-gnu
> release: 1.43.0-nightly
> LLVM version: 9.0

* **IDE name and version:**

clion 3.4

* **Operating system:**

Archlinux

## Problem description

`use std::os::unix::io::AsRawFd` can't complet codes

## Steps to reproduce

1. `use std::os::unix::io::AsRawFd`
2. use this trait in codes
3. input `as_raw`
4. nothing in complete list

**Comment by Undin** [comment]
Looks like it's related to wrong cfg attributes evaluation in stdlib
@ortem Could you take a look?

**Comment by Sherlock-Holo** [comment]
@Undin @ortem Hello, is there any progress about it?

**Comment by ortem** [comment]
@Sherlock-Holo Sorry for the long reply. This issue is strongly related to #3957.

**Comment by Sherlock-Holo** [comment]
ok, I will watch #3957 too
