### ISSUE TITLE
panic! macro not being resolved properly

### ISSUE THREAD

**Issue by not-wlan** [intellij-rust/intellij-rust#4962]
## Environment

* **IntelliJ Rust plugin version:** 0.2.115.2157-193
* **Rust toolchain version:** 1.42.0-nightly (cd1ef390e 2020-01-31) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2019.3.3 (CL-193.6015.37)
* **Operating system:** Linux

## Problem description
The panic! macro isn't being resolved properly and the autofix suggests importing core::panicking::panic, which is currently locked behind a feature flag. The project compiles fine

## Steps to reproduce
1. Create a new project
2. Enter the following code
```
fn main() {
    panic!("Test!");
}
```
~~Switching to the experimental macro expansion fixes this.~~ The fix was only temporary.

**Comment by vlad20012** [comment]
The issue appears on Rust nightly only

**Comment by not-wlan** [comment]
I just noticed that the error re-appeared with the experimental engine, it just some time. I'll update the original post to reflect that.
