### ISSUE TITLE
`Self::` prefix for enum breaks navigation

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [intellij-rust/intellij-rust#4980]
## Environment

* **IntelliJ Rust plugin version:** 0.2.117.2854-193-nightly
* **Rust toolchain version:** 1.41 stable
* **IDE name and version:** IntelliJ IDEA 2019.3.3 Ultimate
* **Operating system:** Windows 10 x64

## Problem description
If referring to an enum variant with a `Self::` prefix, IntelliJ cannot find it.

## Steps to reproduce

main.rs:

```rust
fn main() {
    let _ = Si7021Commands::MeasureTemperatureNoHold.as_bytes();
}

pub trait Command {
    fn as_bytes(&self) -> &[u8];
}

#[non_exhaustive]
enum Si7021Commands {
    MeasureHumidityNoHold,
    MeasureTemperatureNoHold,
}

impl Command for Si7021Commands {
    fn as_bytes(&self) -> &[u8] {
        match *self {
            Si7021Commands::MeasureHumidityNoHold => &[0xF5],
            Self::MeasureTemperatureNoHold => &[0xF3],
        }
    }
}
```

This compiles fine.

Ctrl-clicking `MeasureHumidityNoHold` in the match takes caret to its declaration in the enum.

Ctrl-clicking `MeasureTemperatureNoHold` gives error "Cannot find declaration to go to".

(I was also making a repro for a bug with `#[non_exhaustive]` but it was already reported as #4896)

**Comment by JokerQyou** [comment]
Documentation tooltip also breaks on `Self`: if you focus the cursor on `Self` and press `F1`, an empty tooltip pops up.

![image](https://user-images.githubusercontent.com/1465267/76397540-3275cc80-63b6-11ea-9a4d-5596b937065b.png)
