### ISSUE TITLE
False positive "Unresolved reference" when using proc macros

### ISSUE THREAD

**Issue by msdinit** [intellij-rust/intellij-rust#4989]
## Environment

* **IntelliJ Rust plugin version: 0.2.115.2157-193**
* **Rust toolchain version: 1.42.0**
* **IDE name and version: CLion 2019.3**

## Problem description
False positive for unresolved reference in arguments in a function when the required import is supplied by a procedural macro (Sorry for the convoluted explanation, not sure how to word it better)

## Steps to reproduce
You need to add `juniper = "0.14"` to dependencies.

Minimal code to reproduce:
```rust
pub struct Query;

#[juniper::object]
impl Query {
    fn test_executor(executor: &Executor) -> String {"Test".to_string()}
}
```

`&Executor` is highlighted as unresolved reference, and autocomplete does not work for it, but the code compiles, and in fact if you add `use juniper::Executor;` the compiler would complain about unused import

## Related links
https://github.com/graphql-rust/juniper/issues/465
^ This might provide better context with specific macro implementation

**Comment by Undin** [comment]
@msdinit thanks for the report
Unfortunately, IntelliJ Rust plugin doesn't support items generated by procedural macros
See 1786 for more details

**Comment by Undin** [comment]
Duplicate of #1786
