### ISSUE TITLE
Invalid access for modules behind a macro

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#4997]
## Environment

* **IntelliJ Rust plugin version:** 0.2.116.2163-193
* **Rust toolchain version:** 1.43.0-nightly
* **IDE name and version:** CLion 2019.3.4
* **Operating system:** Windows 10

## Problem description

Public modules exported from crates behind a macro are shown as private.

## Steps to reproduce

Add tokio as a dependency and `use tokio::sync::mpsc::channel`. `tokio::sync::mpsc` is underlined red as private.

**Comment by vlad20012** [comment]
Duplicate #4991. Fixed in the nightly IntelliJ Rust plugin. You can try it now, just follow [the instructions](https://intellij-rust.github.io/install.html)
