### ISSUE TITLE
futures select! marco parsed failed

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#5006]
## Environment

* **IntelliJ Rust plugin version:** 0.2.117.2862-193-nightly
* **Rust toolchain version:** 1.43.0-nightly (e02974078 2020-02-18)
* **IDE name and version:** clion 2019.3.4
* **Operating system:** Archlinux

## Problem description
`futures-0.3` `select!` marco parsed failed

## Steps to reproduce
1. `use futures::{select, future::FutureExt};`
2. use `select!` marco
3. the `select!` color is red, and report 

> Unresolved reference: `select`

**Comment by caibirdme** [comment]
same problem

**Comment by Undin** [comment]
`select` macro is generated by [macro call](https://github.com/rust-lang/futures-rs/blob/dde9766fff8371dae4464ead06ed560702d64b70/futures/src/lib.rs#L587-L594).
Currently, the plugin doesn't support such macros.

@vlad20012 is there conceptual problem to resolve (not expand) such macros?

**Comment by fjna** [comment]
Are the following problems also related to this issue?

1. When I try to navigate to the macro declaration (ctrl/cmd + click) it goes nowhere?
I've seen that rust-analyzer can do it and correctly navigates to `futures-macro-0.3.4/src/lib.rs:38`, is there anything to be ported from rust-analyzer that can help here?

1. Inside the `select!` macro there's no code syntax highlighting, code completion, or any form of code assistance. Is that expected?

**Comment by mili-l** [comment]
see https://github.com/intellij-rust/intellij-rust/pull/9729
