### ISSUE TITLE
Plugin fails on servo project

### ISSUE THREAD

**Issue by iulianR** [intellij-rust/intellij-rust#5016]
## Environment

* **IntelliJ Rust plugin version:** 0.2.116.2155-201
* **Rust toolchain version:** 1.41.0
* **IDE name and version:** CLion 2020.1 EAP
* **Operating system:** Linux 5.4.19-200.fc31.x86_64

## Problem description

When trying to use CLion and the Rust plugin with https://github.com/servo/servo, the plugin tries to run `~/.cargo/bin/cargo check --message-format json` and fails. That's to be expected, as the command should be something like `./mach check --message-format json` because `mach` does some extra things behind the scene.

There should be a way to specify the command the plugin runs in order to get its input. I might have missed it, but I can't find a way to do it.

## Steps to reproduce

Try to load the https://github.com/servo/servo project.

**Comment by vlad20012** [comment]
Probably it tries to run this command because you enabled `org.rust.cargo.evaluate.build.scripts` option in `Experimental Features` dialog. This feature is incomplete and is expected to fail in some projects

**Comment by iulianR** [comment]
Yes, you are right, I do have the option enabled. Feel free to close the issue or reword title/description if you do not have a similar one. Thanks!
