### ISSUE TITLE
Extract enum variant to struct

### ISSUE THREAD

**Issue by sirgl** [intellij-rust/intellij-rust#5024]
It would be cool if there were an intention (or better refactoring) to extract enum variant to separate struct.

Example:
```rust 
enum A {
    Variant1 { name: String, id: usize, }
}
```
extract into something like:
```rust
enum A {
     Variant1(Variant1)
}

struct Variant1 { 
    name: String, 
    id: usize, 
}
```
As a refactoring it could also replace usages, but intention is already great.

**Comment by Undin** [comment]
I think it should be reopened because the intention is not available yet
