### ISSUE TITLE
pub(crate) should be completed

### ISSUE THREAD

**Issue by sirgl** [intellij-rust/intellij-rust#5025]
2 issues:
1. There is no separate completion item `pub(crate)`
2. Inside () `crate` is not suggested

Here suggested `crate::` which is syntactically incorrect.
![image](https://user-images.githubusercontent.com/11944514/75509899-b9708f80-5a1b-11ea-93ff-9d768b5f77f5.png)

**Comment by Kobzol** [comment]
This is not yet fully resolved (not sure why GH closed it, I didn't use the words "closes" or "fixes"). In a follow-up PR, I will also improve completion to contain `pub(crate)` directly.
