### ISSUE TITLE
Support include! macro call generated by another macro

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#5036]
## Environment

* **IntelliJ Rust plugin version:** 0.2.117.3001-201-nightly
* **Rust toolchain version:** 1.43.0-nightly (6d69caba1 2020-02-27) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.1 EAP Ultimate Edition (IU-201.5616.10)
* **Operating system:** macOS 10.13.6

## Problem description
If `include!` macro call is generated by another macro, the plugin doesn't process such calls and as a result all items from included file cannot be resolved or completed.

See https://github.com/intellij-rust/intellij-rust/issues/1908#issuecomment-593026377 for real world case

## Steps to reproduce
`hello.rs`

```rust
pub fn hello() -> &'static str {
    "Hello!"
}
```

`main.rs`

```rust
macro_rules! generate_include {
    ($package: tt) => {
        include!($package);
    };
}

generate_include!("hello.rs");

fn main() {
    println!("{}", hello());
}

```

**Comment by Sherlock-Holo** [comment]
I remember recently parsing tonic generate codes is correct (if not parse, restart clion can fix it).

Does intellij-rust remove this support for now? My plugin version is `0.2.119.3013-193-nightly` and `org.rust.cargo.fetch.out.dir` is enabled

**Comment by LesnyRumcajs** [comment]
I ping this topic, the usage like in `tonic-build` https://github.com/hyperium/tonic/tree/master/tonic-build doesn't produce any completions - tried with `org.rust.cargo.fetch.out.dir` as well.

e.g.
Having a `build.rs` file in root:
```
fn main() -> Result<(), Box<dyn std::error::Error>> {
    tonic_build::compile_protos("proto/rusty_fingers/v1/rusty_fingers.proto")?;
    Ok(())
}
```
and then calling somewhere:
```
pub mod rusty_fingers {
    tonic::include_proto!("rusty_fingers.v1");
}

use rusty_fingers::...
```

Unable to get any completions. Compiles fine when used. Tried restarting CLion, didn't help. It's really a pain.

**Comment by Sherlock-Holo** [comment]
after update rust nightly version or intellij-rust version, tonic parse failed again, need `invalidate data and restart` to force refresh
