### ISSUE TITLE
Plugin is incompatible with 201

### ISSUE THREAD

**Issue by sirgl** [intellij-rust/intellij-rust#5047]
## Environment

CLion 2020.1 EAP
Build #CL-201.5616.31, built on February 20, 2020
CLion EAP User
Expiration date: March 21, 2020
Runtime version: 11.0.6+8-b722.15 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: org.toml.lang

Plugin version: 0.2.117.2170-193

## Problem description

Updated clion to 201 and got version incompatibility:

![image](https://user-images.githubusercontent.com/11944514/75955771-1ae7a100-5ee9-11ea-9e2d-14f8eaf80101.png)

**Comment by sirgl** [comment]
Never mind, just had version for 193, reinstallation helped. Just strange that Clion can't update automatically.

**Comment by Undin** [comment]
Probably, it's a platform bug https://youtrack.jetbrains.com/issue/IDEA-227901
