### ISSUE TITLE
Rust REPL output contains "garbage"

### ISSUE THREAD

**Issue by CDirkx** [intellij-rust/intellij-rust#5058]
## Environment

* **IntelliJ Rust plugin version:** 0.2.117.2170-193
* **Rust toolchain version:** Rust 1.43 nightly
* **IDE name and version:** CLion 2019.3.4 193.6494.38
* **Operating system:** Windows 10

## Problem description
Using evcxr.exe (Rust REPL) with `--disable-readline` causes the output to include "garbage".

```
Welcome to evcxr. For help, type :help
╔?[33m>> ?[0m>> 1 + 2
3
╔?[33m>> ?[0m
>>
```

```
Welcome to evcxr. For help, type :help
╔?[33m>> ?[0m>> a
   ?[91m^?[0m ?[94mnot found in this scope?[0m
?[91mcannot find value `a` in this scope?[0m
╗?[33m>> ?[0m
>>
```

## Steps to reproduce
The problem does not happen when using evcxr.exe standalone without `--disable-readline`.

The problem does happen when using evcxr.exe standalone with `--disable-readline` and in the editor Rust REPL window, as there `--disable-readline` is [always set](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/cargo/toolchain/Evcxr.kt).

## Resolution
I could not find what the `--disable-readline` option does exactly, and could thus not determine if this is:

- a bug in evcxr.exe itself
  - raise bug report at evcxr
  - Rust REPL `--disable-readline` default option is correct
- intended behaviour
  - Rust REPL `--disable-readline` default option is not correct (at least on my system/platform/configuration)

**Comment by Undin** [comment]
@dima74 Looks like the problem is related to console escape symbols in output that windows console can't process

**Comment by dima74** [comment]
By default evcxr uses [rustyline](https://github.com/kkawakam/rustyline) to read input, but rustyline uses escape sequences to turn terminal into special interactive mode, so `--disable-readline` [was added](https://github.com/google/evcxr/pull/68) to read input directly

Evcxr uses colored crate, and there is [similar report](https://github.com/mackwic/colored/issues/59), which suggests using `colored::control::set_virtual_terminal(true);`. I will check evcxr with this line added
