### ISSUE TITLE
Type-hinting fails with RwLockReadGuard

### ISSUE THREAD

**Issue by andrey-yantsen** [intellij-rust/intellij-rust#5069]
## Environment

* **IntelliJ Rust plugin version:** 0.2.117.2170-193
* **Rust toolchain version:** 1.41.1 Stable
* **IDE name and version:** IntelliJ IDEA 2019.3.3 (Ultimate Edition) Build #IU-193.6494.35, built on February 11, 2020
* **Operating system:** macOS Catalina 10.15.3

## Problem description

I have a pet-project with some awful Rust-code. The plugin is unable to properly guess the type returned by one of the functions I've created:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/629281/76219835-61513e80-620e-11ea-929c-49f565a0adc2.png">

As you can see — `get()` and `headers()` functions are highlighted in red, but they exist in the returned type. And the code compiles without an issue :)

The function `get_http_client` returns `LockResult<RwLockReadGuard<'static, reqwest::Client>>` — probably the plugin struggles with dereferrencing `RwLockReadGuard` into `reqwest::Client`.

## Steps to reproduce

Clone [andrey-yantsen/plex-api.rs](https://github.com/andrey-yantsen/plex-api.rs) and navigate to [plex-api/src/my_plex/auth.rs](https://github.com/andrey-yantsen/plex-api.rs/blob/7e1471e765ab4c3520db7de971c84b250903d434/plex-api/src/my_plex/auth.rs#L31-L38). Unfortunately, I was unable to reproduce the issue with some minimal code snippet.

**Comment by andrey-yantsen** [comment]
Could be related to #5054

**Comment by Kobzol** [comment]
I cloned the repository and it seems to work with the latest version of the plugin.

**Comment by andrey-yantsen** [comment]
Ha, yeah, seems like it is. Thank you!
