### ISSUE TITLE
Cannot find functions from traits

### ISSUE THREAD

**Issue by huming2207** [intellij-rust/intellij-rust#5072]
## Environment

* **IntelliJ Rust plugin version:** v117
* **Rust toolchain version:** 1.41.1 stable
* **IDE name and version:** CLion 2019.3.4; Intellij IDEA 2019.3.3
* **Operating system:** Manjaro Linux 19.0.2 (on latest stable branch)

## Problem description

Hi there, 

I'm a Rust beginner started a few days ago. I'm trying to design a server-side Kanban app (like Trello etc) with Actix-web and MongoDB.I'm trying to use [this validator library](https://github.com/Keats/validator/issues/95) to validate the user registration form. However, my IDE tells me it can't find the `validate()` function from the library's `Validate` trait. Did I forget to add something?

My code can get compiled but I haven't tried if there are any run-time errors or not. But even if there are any run-time errors, I guess it doesn't really matter for IDEs to find this function (unless if I really screwed up something).

For more info, please also refer to this issue: https://github.com/Keats/validator/issues/95

Thanks & Regards,
Jackson

## Steps to reproduce

1. Clone my project: https://github.com/huming2207/shachiku-rs
2. Open it with Jetbrains IDEs
3. Have a look on this file (`src/controller/auth.rs`): https://github.com/huming2207/shachiku-rs/blob/4cf60a472d9795b194e8887bd41914de8b8f81ea/src/controller/auth.rs#L30
4. Hover the mouse cursor on **line 30** `new_user.validate();`
5. You will see the IDE cannot find the function `validate()`

**Comment by huming2207** [comment]
Any updates?

**Comment by cakekindel** [comment]
Have you seen #5468?

**Comment by cakekindel** [comment]
That might be related to the issue you're running into here

**Comment by huming2207** [comment]
@cakekindel Yea looks like it's the same
