### ISSUE TITLE
Can't resolve references from terminal_size crate

### ISSUE THREAD

**Issue by mchernyavsky** [intellij-rust/intellij-rust#5075]
## Environment

* **IntelliJ Rust plugin version:** 0.2.118.SNAPSHOT-193-dev
* **Rust toolchain version:** 1.43.0-nightly (3dbade652 2020-03-09) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2019.3.3 Ultimate Edition (IU-193.6494.35)
* **Operating system:** macOS 10.15.3

## Problem description

![image](https://user-images.githubusercontent.com/6079006/76303921-8956a580-62d3-11ea-8c61-185deac9ad14.png)

## Steps to reproduce

terminal_size = "0.1.10"

```rust
use terminal_size::{Width, Height, terminal_size};

fn main() {
    let size = terminal_size();
    if let Some((Width(w), Height(h))) = size {
        println!("Your terminal is {} cols wide and {} lines tall", w, h);
    } else {
        println!("Unable to get terminal size");
    }
}
```

**Comment by Kobzol** [comment]
Works with latest plugin version.
