### ISSUE TITLE
Using bundled GDB debugger on OSX: not in executable format: file format not recognised

### ISSUE THREAD

**Issue by david-mcgillicuddy-moixa** [intellij-rust/intellij-rust#5077]
## Environment

* **IntelliJ Rust plugin version:** 0.2.117.2170-193
* **Rust toolchain version:** 1.40.0 (73528e339 2019-12-16) x86_64-apple-darwin
* **IDE name and version:** CLion 2019.3.4 (CL-193.6494.38)
* **Operating system:** macOS 10.15.3

## Problem description
When trying to use bundled GDB (since LLDB is not yet suitable c.f. https://github.com/intellij-rust/intellij-rust/issues/4548)
Running anything in debug mode produces the error:
```
com.jetbrains.cidr.execution.debugger.gdb.GDBDriver$DDBCommandException: "/Users/user/code/hello-world/target/debug/hello-world": not in executable format: File format not recognised
```
I reinstalled clion from scratch as advised in https://github.com/intellij-rust/intellij-rust/issues/2751 and also deleted the `./target` directory.

## Steps to reproduce
- `cargo new --bin` to produce hello world main.
- Set debugger toolchain to bundled GDB (for me it's 8.0.1)
- right click arrow next to main function, choose debug 'run hello-world'

**Comment by ortem** [comment]
It is not recommended to use CLion's GDB on macOS because of [known problems with some GDB versions](https://youtrack.jetbrains.com/issue/CPP-14546).

> since LLDB is not yet suitable c.f. #4548

LLDB is suitable and recommended. There are some unimplemented features in LLDB, but unfortunately, GDB support [isn't completed yet](https://sourceware.org/gdb/current/onlinedocs/gdb/Rust.html) too.

**Comment by david-mcgillicuddy-moixa** [comment]
Is this not supposed to be happening?
https://i.imgur.com/EvRV2tS.png
https://i.imgur.com/kPiGVKs.png
Top is built-in renderers, bottom is bundled renderers. 
Either way it's not part of this issue I suppose, I'll close it. Thanks for the quick response!

**Comment by ortem** [comment]
@david-mcgillicuddy-moixa oh, I forgot to notice that you should use CLion 2020.1 (it is EAP now) to have better Rust support (including enums) in LLDB.

**Comment by david-mcgillicuddy-moixa** [comment]
Oh _that's_ why I wasn't seeing what other people were seeing. I just clicked download and didn't think about it. Wonderful tip thanks!
