### ISSUE TITLE
Not possible to enable features when building project

### ISSUE THREAD

**Issue by RichoDemus** [intellij-rust/intellij-rust#5078]
## Environment

* CLion 2019.3
* Windows 10 pro

## Problem description
I want to set a feature when building my project (Ctrl+F9)
I've gone through the settings (Lang&Framew/Rust) but the option seems to be lacking

## Steps to reproduce
Create a new project, press Ctrl+F9 (build project)
it will print something like this:
`C:/Users/<username>/.cargo/bin/cargo.exe build --color=always --all --all-targets`

what I'm expecting
adding something like `--features "my-feature"` in some configuration box in settings and then getting
`C:/Users/<username>/.cargo/bin/cargo.exe build --color=always --all --all-targets --features "my-feature"`

**Comment by mchernyavsky** [comment]
You can enable [the experimental build tool window](https://github.com/intellij-rust/intellij-rust/pull/3926) by setting `cargo.build.tool.window.enabled` variable to `true` (see `Actions > Registry...`). 

Then you can just add `--features "my-feature"` to "Command" field:

![image](https://user-images.githubusercontent.com/6079006/76344335-744d3700-6312-11ea-974f-f809f70ac1ef.png)

**Comment by RichoDemus** [comment]
Thanks for the response, but this only applies to when I run that cargo command, not when I do "build project" (Ctrl+F9) right? while this workaround works, it's a bit unergonomic to not be able to build normally

**Comment by mchernyavsky** [comment]
@RichoDemus Sorry for the long response.

If `org.rust.cargo.build.tool.window` is enabled "build project" should build the current selected Run configuration. You can see the actual build command line in the Build tool window:

![image](https://user-images.githubusercontent.com/6079006/100357918-69544700-3006-11eb-985d-0a77d21480d8.png)

**Comment by RichoDemus** [comment]
I see thanks
Any words on when this will not be hidden by experimental flags?

**Comment by mchernyavsky** [comment]
I hope we will merge https://github.com/intellij-rust/intellij-rust/pull/4254 soon and after that, we can enable it by default.

**Comment by Undin** [comment]
@RichoDemus We need #4254 to fix current major issues. So after this PR, I suppose we will enable build tool window by default and add a user-visible option to enable/disable it
