### ISSUE TITLE
Cannot borrow immutable local variable 'NAME' as mutable

### ISSUE THREAD

**Issue by Infiziert90** [intellij-rust/intellij-rust#5088]
## Environment

* **IntelliJ Rust plugin version:** 0.2.117.2170-193
* **Rust toolchain version:** 1.41.0 (5e1a79984 2020-01-27) x86_64-apple-darwin
* **IDE name and version:** CLion 2019.3.3 (CL-193.6015.37)
* **Operating system:** macOS 10.15.3

## Problem description
The error is not correct. 
I can compile the project without any warning or errors from the compiler.

## Steps to reproduce
```rust
use lazy_static::lazy_static;
use std::sync::RwLock;
use std::collections::HashMap;

lazy_static! {
    static ref USERS: RwLock<HashMap<String, X>> = RwLock::new(HashMap::new());
}

struct X {
    _name: String,
}

fn test() {
    let mut users = USERS.write().unwrap();
    users.insert("Hallo".to_string(), X{_name: "Hallo".to_string()});
    let _x = users.get("Hallo");
}

fn main() {
    test();
    println!("{:?}", "x");
}
```
<img width="633" alt="Bildschirmfoto 2020-03-12 um 16 41 37" src="https://user-images.githubusercontent.com/22648449/76538982-6b7a7380-6480-11ea-854a-a09b5d6c7a1d.png">

**Comment by LoopyAshy** [comment]
I constantly run into this error also and hope they choose to fix this soon as this bug has existed for months now

**Comment by Kobzol** [comment]
@Infiziert90 @LoopyAshy do you still experience this error in the latest version of the plugin? I can't seem to reproduce it with the code sample posted here. It seems to work even with the default macro engine, but try it with the new experimental macro engine (https://github.com/intellij-rust/intellij-rust/issues/3628).

**Comment by LoopyAshy** [comment]
> @Infiziert90 @LoopyAshy do you still experience this error in the latest version of the plugin? I can't seem to reproduce it with the code sample posted here. It seems to work even with the default macro engine, but try it with the new experimental macro engine (#3628).

this indeed fixed my issue: I am greatly appreciative of this being brought to my attention, as it has been a nightmare with all the missing functionality caused by it.
