### ISSUE TITLE
Code completion regression in web-sys?

### ISSUE THREAD

**Issue by ralfbiedert** [intellij-rust/intellij-rust#5104]
Hi,

There might be a regression in the latest version of the plugin w.r.t auto-completion of the `web-sys` crate. 

I have to admit I'm not 100% sure it actually worked before (I think it did) as I'm toying with that crate only occasionally and I don't know how to roll back to an older version of the plugin.

See this video:

**https://streamable.com/k5bcw**

## Environment

* **IntelliJ Rust plugin version:** `0.2.118.2171-193` and `0.2.119.3015-193-nightly`
* **Rust toolchain version:** `rustc 1.42.0 (b8cedc004 2020-03-09)`
* **IDE name and version:** `CLion 2019.3.4`
* **Operating system:** `Windows 10`

Happens both with `Experimental` and `Default` macro engine.

## Problem description

- When I load a small sample project using the `web-sys` crate like this:
    ```toml
    web-sys = { version = "0.3", features = ["Window", "Document"] }
    ```
- And then in `src/lib.rs` try to access methods of a `Document` struct
- There is no auto-completion 
- In addition, the following error is printed on the Event Log:
    ```
    21:19	Cargo project update failed:
			Project directory does not exist
    ```

## Steps to reproduce

See above, or clone [**this repo**](https://github.com/ralfbiedert/rust_issues/tree/intellij_rust_no_suggestion) (`intellij_rust_no_suggestion` branch).

**Comment by ortem** [comment]
Related issues: #3066, #3066.

@ralfbiedert You can check some advice from other users there like enabling experimental features or using an older `web_sys` version. Please tell us if it helps or not.

**Comment by ralfbiedert** [comment]
Hi, thanks for the suggestions. Experimental features didn't change anything; in fact, I had all enabled already:

![image](https://user-images.githubusercontent.com/301288/77936155-c5699e80-72b2-11ea-8db8-1bbee1cfad0f.png)

I also set ` -Didea.max.intellisense.filesize=200000` without success. However, force-downgrading to an older version (`0.3.30`) worked. 

I played a bit more:
```
web-sys = { version = "=0.3.30", features = ["Window", "Document"] } // ok
web-sys = { version = "=0.3.33", features = ["Window", "Document"] } // ok
web-sys = { version = "=0.3.34", features = ["Window", "Document"] } // ok
web-sys = { version = "=0.3.35", features = ["Window", "Document"] } // ok
web-sys = { version = "=0.3.36", features = ["Window", "Document"] } // broken
web-sys = { version = "=0.3.37", features = ["Window", "Document"] } // broken
```

So apparently a change in `web-sys` from `0.3.35` to `0.3.36` started to provoke a problem in the IntelliJ-Rust code completion.

**Comment by Sroka** [comment]
Confirming, 0.3.36 broke something. I wonder if this task completed on wasm-bindgen side is the source of this issue?
https://github.com/rustwasm/wasm-bindgen/pull/2012

**Comment by panstromek** [comment]
related: fixing https://github.com/intellij-rust/intellij-rust/issues/4830 should solve this issue according to author

**Comment by mili-l** [comment]
see #9729
