### ISSUE TITLE
Failure to parse reference to variable named raw

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [intellij-rust/intellij-rust#5105]
## Environment

* **IntelliJ Rust plugin version:** 0.2.119.3016-193-nightly
* **Rust toolchain version:** 1.42 stable / 1.43 nightly 2020-03-11
* **IDE name and version:** IntelliJ IDEA 2019.3.3 Ultimate
* **Operating system:** Windows 10 x64

## Problem description
Plugin fails to parse a reference to a variable named raw.

## Steps to reproduce

```rust
fn main() {
    let raw = "text".to_owned();
    let mut new = String::with_capacity(raw.len() + 2);
    new.push('"');
    new.push_str(&raw);
    new.push('"');
    println!("{}", new);
}
```

The `r` in `&raw` is highlighted red with `<expr> expected, got 'raw'`. Code compiles and runs without problems. (This is a reduced form of code I wrote earlier today)

**Comment by Undin** [comment]
Looks like it was introduced in #5081

**Comment by vlad20012** [comment]
I'll fix it
