### ISSUE TITLE
Better cfg_if support

### ISSUE THREAD

**Issue by gilescope** [intellij-rust/intellij-rust#5116]
One might like to do the following:
```rust
 cfg_if! {
     if #[cfg(feature = "foo")]
     {
         pub(crate) mod my_foo;
     }
 }
```
but one would get told "File is not included in module tree, analysis is not available" when one opens `my_foo.rs`. The work around is to not use cfg_if:
```rust
#[cfg(feature = "foo")]
#[path = ""]
mod foo {
    pub(crate) mod my_mod;
}

#[cfg(feature = "foo")]
pub(crate) use foo::*;
```
This works and CLion understands the above, but it would be great if it could understand cfg_if and see that the module was part of the tree.
(This is using 0.2.118.2171-193 version of the rust plugin)

**Comment by dima74** [comment]
This was fixed some time ago
