### ISSUE TITLE
Cargo build tool window feature regresion, when click in error not goes to code pointed by error

### ISSUE THREAD

**Issue by lumasepa** [intellij-rust/intellij-rust#5121]
## Environment

* **IntelliJ Rust plugin version:** 0.2.118.2171-193
* **Rust toolchain version:** 1.44.0-nightly
* **IDE name and version:** Clion 2019.3.5
* **Operating system:** Archlinux - Kernel 5.5.9-arch1-2 - Gnome 3.36

## Problem description
Previously in the cargo build tool window when you clicked in an error or warning the IDE shows only that error in the right side of the panel and opens in the editor the code line where the error was. Now it does not open the editor with the code line failing.

## Steps to reproduce
Build a project with an error having the experimental feature cargo build tool window activated. Click on the error.

**Comment by mchernyavsky** [comment]
Hello!
I can't reproduce it. Can you share an example project?

**Comment by lumasepa** [comment]
Hi, now I can't reproduce it too. Probably had an error that build tool window can't parse. Now I don't have errors in my project.
