### ISSUE TITLE
TOML plugin crashes at startup

### ISSUE THREAD

**Issue by dvdplm** [intellij-rust/intellij-rust#5129]
The latest nightly build of the Rust/TOML plugin crashes at startup. I am pretty sure it's actually the TOML plugin that fails (see [trace](https://ea.jetbrains.com/browser/ea_reports/5523230)) but I'm unsure if it is tied to the Rust version used. I have `rustc 1.44.0-nightly (1edd389cc 2020-03-23)`.

It's a bit annoying because the crashing plugin stops the project from loading. The ui shows `loading...` but cannot open any files.

**Comment by Undin** [comment]
@dvdplm Thanks for the report!
Looks like you installed [oxidize](https://plugins.jetbrains.com/plugin/7841-oxidize) plugin that conflicts with IntelliJ Rust
Try to uninstall it, restart IDE and check again

**Comment by dvdplm** [comment]
> Try to uninstall it, restart IDE and check again

Totally worked. You rock!

Still, it's a bit worrying that a conflicting plugin can get the IDE in such a bad state, let me know if I can provide any more info to help debug. :)

**Comment by Undin** [comment]
> Totally worked. You rock!

Glad to help!

> Still, it's a bit worrying that a conflicting plugin can get the IDE in such a bad state

We too. Probably, oxidize plugin should be marked as deprecated because it does nothing and may produce such conflicts

I think this issue can be closed now
