### ISSUE TITLE
Add real performance tests

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#513]
Make sure that the CI fails if performance degrades significantly.

**Comment by sirgl** [comment]
Usually it is impossible to run perfomance tests without side effects from other proceses, especially on CI server, so is it really make sense?

**Comment by bgourlie** [comment]
The environment in which the tests are run has to be reasonably controlled for, at least.   Travis-ci perf tests would be very uncontrolled -- Hardware, load, etc could change at any given point.

**Comment by matklad** [comment]
We plan to use a dedicated TeamCity agent for this.

**Comment by matklad** [comment]
Ok, I've added a special run configuration for performance tests which is pinned to a single teamcity agent. Currently it only logs test times, and will not fail the build on regression: we need to estimate variance first. 

The performance charts are available here: https://teamcity.jetbrains.com/viewType.html?buildTypeId=IntellijIdeaPlugins_Rust_PerfrormanceTestsRust&tab=buildTypeStatistics&branch_IntellijIdeaPlugins_Rust=__all_branches__

See the last chart.

**Comment by matklad** [comment]
Charts now live here: https://teamcity.jetbrains.com/project.html?projectId=IntellijIdeaPlugins_Rust&tab=stats

I've added a conservative failure condition if tests are slowed down by at least 80%. Will try to make the bound more tight if tests are stable enough.
