### ISSUE TITLE
`Extract enum variant` intention doesn't replace usages in struct literals

### ISSUE THREAD

**Issue by mchernyavsky** [intellij-rust/intellij-rust#5136]
## Environment

* **IntelliJ Rust plugin version:** 0.2.119.3026-201-nightly
* **Rust toolchain version:** 1.43.0-nightly (3dbade652 2020-03-09) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.1 Beta (CL-201.6668.10)
* **Operating system:** macOS 10.15.4

## Problem description

title

## Steps to reproduce
```rust
enum E {
    /*caret*/V1 { x: i32 },
    V2
}

fn main() {
    let v = E::V1 { x: 42 };
    if let E::V1 { x } = v {
        println!("{}", x)
    };
}
```

**Comment by mchernyavsky** [comment]
cc @Kobzol

**Comment by Kobzol** [comment]
Right, I only handled struct patterns, but not struct constructors. I'll send a PR.
