### ISSUE TITLE
New Projects Complaining of missing cargo.toml

### ISSUE THREAD

**Issue by 06needhamt** [intellij-rust/intellij-rust#514]
Upon trying to run a new project containing the following code
``` rs
fn main() {
    println!("Hello World!");
}
```
The run configuration occurs complaining of a missing cargo.toml
See Screenshot
![rust](https://cloud.githubusercontent.com/assets/4162227/16625744/ef2eed4e-439d-11e6-8d97-a5c4c4a49ac1.png)

To Try and remedy this i tried to create a simple cargo.toml with the following code 
```
[package]
name = "hello_world" # the name of the package
version = "0.1.0"    # the current version, obeying semver
authors = ["you@example.com"]
```

However the IDE still complains of a missing cargo.toml file

**Comment by matklad** [comment]
Ah, I see, the name of the file should be `Cargo.toml` and not `cargo.toml`. Note the capital C.

Did this helped?

**Comment by matklad** [comment]
To elaborate, `cargo` itself requires that capital C.

**Comment by jajakobyly** [comment]
Hmm seems strange having in mind that ntfs is case insensitive

**Comment by bgourlie** [comment]
NTFS is case sensitive. See https://support.microsoft.com/en-us/kb/100625.

**Comment by 06needhamt** [comment]
Issue still occurs but now idea says Cargo.toml is a non project file and should not be edited

**Comment by matklad** [comment]
@06needhamt we don't yet support creating a new project from the IDE, see https://github.com/intellij-rust/intellij-rust/issues/401. So you need to do `cargo new` from the command line and then open the resulting directory in the IDE. 

But "is a non project file" seem to be an issue with `RustModuleType`, thanks for the report!

**Comment by 06needhamt** [comment]
Adding Support See WIP PR https://github.com/intellij-rust/intellij-rust/pull/516
