### ISSUE TITLE
Insert trailing comma in match after "Complete current statement"

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#5140]
## Environment

* **IntelliJ Rust plugin version:** 0.2.119.3025-201-nightly
* **Rust toolchain version:** 1.42.0 (b8cedc004 2020-03-09) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.1 Beta (CL-201.6668.10)
* **Operating system:** macOS 10.15.3

## Problem description

I'm used to "Complete current statement" action but it doesn't do the best job in `match`, I guess it is safe to insert a trailing `,` there.

## Steps to reproduce

```rust
fn main() {
    let a = 1;

    match a {
        1 => println!(1)<caret>
    };
}
```

Invoke "Complete current statement" (<kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>Return</kbd>):

```rust
fn main() {
    let a = 1;

    match a {
        1 => println!(1)
        <caret>
    };
}
```

Expected:

```rust
fn main() {
    let a = 1;

    match a {
        1 => println!(1),
        <caret>
    };
}
```

**Comment by Stzx** [comment]
I think I will fix it together in this #5133 PR.

**Comment by Stzx** [comment]
@Undin can you help me? I wonder if there are class related to it?

**Comment by Undin** [comment]
> I think I will fix it together in this #5133 PR.

@Stzx could you, please, do it in separate PR?

> @Undin can you help me? I wonder if there are class related to it?

see `org.rust.ide.typing.assist.RsSmartEnterProcessor`

**Comment by Stzx** [comment]
@Undin Ok. I will open a new PR.

**Comment by lancelote** [comment]
@Stzx Thank you 🙏
