### ISSUE TITLE
False compilation error when calling 'read' method on a RwLock while having the crate 'futures' in my cargo.toml

### ISSUE THREAD

**Issue by maxim-banaev** [intellij-rust/intellij-rust#5154]
## Environment

* **IntelliJ Rust plugin version:** 0.2.118.2171-193
* **Rust toolchain version:** 1.44, nightly-x86_64-pc-windows-gnu
* **IDE name and version:** CLion 2019.3.2
* **Operating system:** Microsoft Windows 10 Pro, 10.0.18363

## Problem description

False compilation error when calling 'read' method on a RwLock while having the crate 'futures' in my cargo.toml

Submitted to CLion bug tracker as https://youtrack.jetbrains.com/issue/CPP-19678

## Steps to reproduce
Clone and run this repo: https://github.com/Jasperav/rwlockfutures. When opening this project in CLion and going to main.rs, you will see that CLion thinks the project will not compile, because of the error message that I attached in the attachments. It compiles and runs just fine.

**Comment by Undin** [comment]
@Jasperav try to enable new macro expansion engine (see #3628 for more details). It should solve your issue

**Comment by Jasperav** [comment]
@Undin did solved it, thanks :) issue can be closed

**Comment by Undin** [comment]
> did solved it, thanks :)

Glad to hear it!

> issue can be closed

We will close all issues that can be fixed by new macro expansion engine after the engine will become the default option
