### ISSUE TITLE
GDB fails with "File format not recognized" on Windows

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#5160]
## Environment

* **IntelliJ Rust plugin version:** 0.2.118.2171-193
* **Rust toolchain version:** rustc 1.42.0 (b8cedc004 2020-03-09)
* **IDE name and version:** CLion
* **Operating system:** Windows 7

## Problem description
Debug with  GDB doesn't work and fails with an exception.

Console log:
```
Error during pretty printers setup: Undefined info command: "pretty-printer". Try "help info".

Some features and performance optimizations will not be available.

com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$GDBCommandException:
"C:/Personal/xxx/Documents/workspace/untitled/target/debug/untitled.exe": not in executable format: File format not recognized
```

**Comment by ortem** [comment]
https://github.com/intellij-rust/intellij-rust/issues/2630#issuecomment-606112014
> Is it a problem that mingw32-make.exe is used?

@psotos I think 32-bit `make` is not a problem. Everything should work fine if you're using `stable-x86_64-pc-windows-gnu` + `MinGW-w64 GDB`. Maybe something wrong with your MinGW installation? I'd recommend you to try to use Cygwin instead of MinGW, probably it will help.

**Comment by psotos** [comment]
> [#2630 (comment)](https://github.com/intellij-rust/intellij-rust/issues/2630#issuecomment-606112014)
> 
> > Is it a problem that mingw32-make.exe is used?
> 
> @psotos I think 32-bit `make` is not a problem. Everything should work fine if you're using `stable-x86_64-pc-windows-gnu` + `MinGW-w64 GDB`. Maybe something wrong with your MinGW installation? I'd recommend you to try to use Cygwin instead of MinGW, probably it will help.

Nope my MinGW works fine. I use it for other tools and nothing has problems except this.

**Comment by ortem** [comment]
@psotos That's strange. I'd try these possible solutions:
* To use Cygwin
* To reinstall MinGW
* To use MinGW32 + `stable-i686-pc-windows-gnu` (using `rustup default`, not `rustup override`)

Please inform us if something helps.

**Comment by psotos** [comment]
@ortem Can I send you the exe that is being generated? Perhaps you can see something wrong with it or reproduce the defect?
Also this is a work machine, I need to be careful what I install on it. Installing Cygwin is not really an option for me.

**Comment by ortem** [comment]
@psotos I'm not sure that your exe can help us find a solution. If installing Cygwin is not an option, try doing this:
1. `$ rustup default stable-x86_64-pc-windows-gnu` (just to make sure it is a global setting)
2. Create a new "hello world" project and start debugging it

**Comment by psotos** [comment]
@ortem Brand new project still fails:
![Capture](https://user-images.githubusercontent.com/5159250/78149567-248af880-7404-11ea-960e-042d6275c582.PNG)

**Comment by psotos** [comment]
@ortem The problem is now resolved. I did in fact, have to upgrade MinGW. I used these settings:
![MinGW-settings](https://user-images.githubusercontent.com/5159250/78151698-dcb9a080-7406-11ea-92cd-b79ebcc09800.PNG)

**Comment by ortem** [comment]
@psotos Great!
