### ISSUE TITLE
No "mismatched types" [E0308] error on empty function

### ISSUE THREAD

**Issue by Stzx** [intellij-rust/intellij-rust#5166]
## Environment

* **IntelliJ Rust plugin version:** 0.2.118.2171-193
* **Rust toolchain version:** cargo 1.44.0-nightly (7019b3ed3 2020-03-17)
* **IDE name and version:** IDEA 2019.3.4
* **Operating system:** Windows 10

## Problem description

```rust
fn test_fun() -> ! {
    // For empty function return `()`, no error detected.
    // Actually this will raise [E0308] error.
}
```

## Steps to reproduce

1. Use the following code:
```rust
fn test_fun() -> ! {
}
```
2. Run `cargo check`

**Comment by ortem** [comment]
@Stzx thank you for reporting. Looks like the problem is not only with diverging functions but with any functions with a return type, e.g.
```Rust
fn foo() -> i32 {} // no error highlighted
```
