### ISSUE TITLE
Insert closing `*/` after `/*` (block comment)

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#5171]
## Environment

* **IntelliJ Rust plugin version:** 0.2.120.3030-201-nightly
* **Rust toolchain version:** 1.42.0-nightly (f43c34a13 2020-02-02) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.1 Beta Ultimate Edition (IU-201.6668.13)
* **Operating system:** macOS 10.15.3

## Problem description
After starting block comment (inserting `/*`), the plugin should automatically insert a closing `*/` as other IDE/plugins do.

![block_comment](https://user-images.githubusercontent.com/4854600/78140561-e1944980-7432-11ea-83b0-3b341d1a3954.gif)

**Comment by Kobzol** [comment]
Should this be implemented using `EnterHandlerDelegateAdapter`?

**Comment by ortem** [comment]
@Kobzol Probably. If so, you can check [this implementation](https://github.com/JetBrains/intellij-community/blob/master/platform/lang-impl/src/com/intellij/codeInsight/editorActions/enter/EnterInBlockCommentHandler.java). But also maybe all we have to do is implement `CodeDocumentationAwareCommenter` in `RsCommenter` and reuse `EnterInBlockCommentHandler`. I haven't explored the problem, so several approaches should be tested to find a proper way to do this, and not break our other handlers like `RsEnterInLineCommentHandler`.

**Comment by Kobzol** [comment]
Thanks for the pointers. I tried to play with `CodeDocumentationAwareCommenter` briefly and it solves this issue relatively easily, but it's not especially pretty. I'll send a PR with some tests to discuss this further.

**Comment by mcfriend99** [comment]
Hi, @Kobzol sorry to be asking this here but its the only place related google keeps redirecting me to for my problem. It's an intellij plugin question and not about rust or this current plugin. I implemented `CodeDocumentationAwareCommenter` in my plugin for a custom language. Problem is its not working. The IDE is not autocompleting the block comments. Is there a pre-requisite for this??

**Comment by Kobzol** [comment]
Have you also implemented `Commenter`? Do comments normally work, just the autocompletion doesn't work? You need to register the commenter in the XML plugin config file.
