### ISSUE TITLE
Use CLion-style icons for symbols?

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#5176]
I've noticed that we still use Java-esque `(C)` icon for structs and unions on IntelliJ (hasn't checked CLion). Perhaps it makes sense to move [these icons](https://www.jetbrains.com/help/clion/icons-and-symbols.html#structure-icons) into platform and use them instead?

**Comment by Undin** [comment]
> hasn't checked CLion

We use the same icons across all IDEs like before

> Perhaps it makes sense to move these icons into platform and use them instead?

Yeah, it really makes sense. Thanks!
