### ISSUE TITLE
ash::vk no longer visible in 0.30.0

### ISSUE THREAD

**Issue by Delamare2112** [intellij-rust/intellij-rust#5192]
## Environment

* **IntelliJ Rust plugin version:** 0.2.119.2172-193
* **Rust toolchain version:** tested with: 1.44.0-nightly (f509b26a7 2020-03-18) and stable 1.42.0 (b8cedc004 2020-03-09)
* **IDE name and version:** CLion 2019.3.5 Build #CL-193.6911.21
* **Operating system:** Arch Linux with kernel: 5.5.13-arch1-1-vfio

## Problem description
In ash version 0.30.0, code completion for `ash::vk` does not work.  It worked fine in ash version 0.29.0.  Going into ash's source code from CLion, [lib.rs line 36](https://github.com/MaikKlein/ash/blob/master/ash/src/lib.rs#L36) is `pub mod vk;` with vk highlighted in red.  Hovering over vk gets CLion telling me "File not found for module `vk` [E0583]" yet [vk.rs](https://github.com/MaikKlein/ash/blob/master/ash/src/vk.rs) does exist and is in the same folder as lib.rs.  Cargo build / run works just fine but now that I've updated to 0.30.0 none of the CLion code analysis works.

## Steps to reproduce
Cargo.toml:
```toml
[package]
name = "ash_clion_test"
version = "0.1.0"
edition = "2018"

[dependencies]
ash = "0.30.0"
```
main.rs:
```rust
fn main() {
    let test = ash::vk::BufferCopy::builder();
}
```
CLion will not know what type "test" is and will not let you look at BufferCopy's structure.

**Comment by Undin** [comment]
@Delamare2112 hi!
I've reproduced your issue.
In `0.30.0` `vk.rs` became too big too IntelliJ IDEs. There is a file size limit that prevents IDE to index files with size more than the limit. It was introduced to prevent performance problems with large files.
![image](https://user-images.githubusercontent.com/2539310/78421757-d7589200-7662-11ea-8e84-af79944b8b47.png)
To solve your issue you need to change `idea.max.intellisense.filesize` property. You can tune it as described [here](https://www.jetbrains.com/help/idea/tuning-the-ide.html#common-platform-properties). Note, it may affect IDE performance in other cases.
But I'd recommend to file issue to the maintainer of `ash` lib to split `vk.rs` into several files

**Comment by Delamare2112** [comment]
Increasing the property totally worked!  Thanks!
