### ISSUE TITLE
Polish README.md

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#521]
Although we have awesome  https://intellij-rust.github.io, README.md is still the thing that many of the users will see for the first time, so we should make sure that it is short and clear. 

Things to improve: 

  * [ ] there are seven hyper links currently. I suggest to leave only two prominent links: for the developers and for the users. 
  * [ ] we should add short installation instructions to README.md, because some people prefer jump to straight in, instead of studding fancy gh-pages.

**Comment by alexeykudinkin** [comment]
Please, add the following item:

- [ ] Mention _actual_ (not desirable) state-of-the-art (to mitigate such a confusion as may be seen in #524)

**Comment by matklad** [comment]
Fixed together with polishing https://intellij-rust.github.io/. Readme gives short installation instructions and describes wip status.
