### ISSUE TITLE
Clion debugger cannot view enum structure

### ISSUE THREAD

**Issue by wspl** [intellij-rust/intellij-rust#5210]
## Environment

* **IntelliJ Rust plugin version:** 0.2.119.2172-193
* **Rust toolchain version:** rustc 1.44.0-nightly (42abbd887 2020-04-07)
* **IDE name and version:** Clion 2019.3.5 193.6911.21
* **Operating system:** MacOS 10.14.5

## Problem description
Debugger - Variables cannot expand any enum type variable to look its structure/content:
![image](https://user-images.githubusercontent.com/2133311/78784603-322e1880-79d8-11ea-82af-f6dc5a028883.png)
```rust
struct A {
    a: i32
}

fn main() {
    let a = Some(A { a: 1 });
    println!("Hello, world!");
}
```

But without an enum type wrapping, it works well:
![image](https://user-images.githubusercontent.com/2133311/78784681-58ec4f00-79d8-11ea-8351-18cabe910bda.png)

```rust
struct A {
    a: i32
}

fn main() {
    let a = A { a: 1 };
    println!("Hello, world!");
}
```

`Result` is also have this problem.
Is it a bug or an unimplemented feature?

**Comment by Undin** [comment]
Try to update your CLion to 2020.1 EAP. Or wait a little bit for release version that should be published this week. 
CLion 2020.1 brings updated LLDB that can render Rust enums properly.
See #4548 for more details

**Comment by ortem** [comment]
@wspl please let us know if updating to CLion 2020.1 (it has been released already) helps

**Comment by Undin** [comment]
I think it can be closed

**Comment by AndreKR** [comment]
Not sure if it's better to reopen this one or create a new one.

Unless I'm misunderstanding the issue, I am still seeing the same thing in:

IntelliJ Rust plugin version: 0.3.141.3634-202-nightly
Rust toolchain version: rustc 1.59.0-nightly (c5ecc1570 2021-12-15)
IDE name and version: CLion 2020.2.1 Build #CL-202.6948.80
Operating system: Windows

Target: x86_64-pc-windows-gnu

![image](https://user-images.githubusercontent.com/1188538/146435959-8eee1189-26d8-4490-a5c8-d4598a77964d.png)

![image](https://user-images.githubusercontent.com/1188538/146436041-9ca6507a-c7c5-45df-ad81-566d55aa0719.png)

**Comment by 52617365** [comment]
Still running into this problem on an M2 Mac on the currently newest stable CLion. It is saying the value is an invalid value instead of showing me the contents.
