### ISSUE TITLE
Polish usage docs

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#522]
Problem: we have a number of useful inspections, intentions and other neat tricks, which are not that easily discoverable. 

A good way to improve features visibility is to add GIFs to the website. It would be nice to document GIF creating process so that it can be easily repeated when new features are added.

**Comment by jajakobyly** [comment]
I can do some gifs, though I have no idea what to present on them

**Comment by matklad** [comment]
* Basic stuff like completion, go to definition, go to class, go to symbol.
* Every intention and quick fix (expand, contract module, create file by quick fixing unresolved mod decl, go to super mod, add derive, extract inline module, remove extra parenthesis, toggle `{}` around single item import, context aware snippets, context aware run configurations)

**Comment by matklad** [comment]
For the presenting, I think two things are important: 

* name of the thing to be able to **find action** it
* shortcut (there are some apps that can echo key presses)
