### ISSUE TITLE
Syntax highlighting or errors are not being shown in the IDE

### ISSUE THREAD

**Issue by ajazam** [intellij-rust/intellij-rust#5225]
## Environment

* **IntelliJ Rust plugin version:** 0.2.119.2201-201
* **Rust toolchain version:** 1.42.0 (b8cedc004 2020-03-09) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2020.1 Ultimate Edition (IU-201.6668.60)
* **Operating system:** Windows 10 10.0

## Problem description
The syntax highlighting is not working. When I enter garbage into a source file errors aren't shown in the file. It used to work pre 2020.1

**Comment by Undin** [comment]
@ajazam It's rather hard to understand what's going on without anything additional info: [logs](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files), project sources (or at least sample project where issue can be reproduced), screenshots, etc.
Without additional info, I can recommend only try `File | Invalidate Caches / Restart` action

**Comment by ajazam** [comment]
Sorry this is my first issue.

![screenshot](https://user-images.githubusercontent.com/1839987/79012710-d346db80-7b5e-11ea-91c1-0d0627461d2a.PNG)

I've uploaded a screenshot of spme test source with the test "garbage here" in two places. Since my original message I've upgrade IDE to latest version. When I created the issue it was the RC.

IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Licensed to Abdul Azam
Subscription is active until August 1, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Non-Bundled Plugins: com.andrey4623.rainbowcsv, net.seesharpsoft.intellij.plugins.csv, org.intellij.scala, com.intellij.bigdatatools, com.intellij.plugins.html.instantEditing, training, org.toml.lang, org.rust.lang, com.jetbrains.edu, uk.co.hadoopathome.intellij.avro.intellijavroviewer

I've also uploaded my idea.log file

[idea.log](https://github.com/intellij-rust/intellij-rust/files/4462827/idea.log)

Let me know if you want any other info

**Comment by ajazam** [comment]
Ive just tested using the following and the plugin works fine

IntelliJ IDEA 2019.3.4 (Community Edition)
Build #IC-193.6911.18, built on March 17, 2020
Runtime version: 11.0.6+8-b520.43 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 3987M
Cores: 16
Registry: 
Non-Bundled Plugins: Batch Scripts Support, CMD Support, org.intellij.scala, org.toml.lang, org.rust.lang, com.jetbrains.edu, org.jetbrains.erlang, org.scalafmt.ScalaFmt

![Capture2](https://user-images.githubusercontent.com/1839987/79014374-ad233a80-7b62-11ea-946a-c132fa544607.PNG)

**Comment by Undin** [comment]
Could you check file type settings?
`Settings | Editor | File Types` and find `Rust` file type. Looks like the corresponding pattern was changed after IDE update. If it's true, then `Rust` file type doesn't have any associated pattern.
To fix it, just add `*.rs` pattern to `Rust` fil type. It should fix your issue
Could you also provide a screenshot of rust file tab with icon? (just to ensure my assumption)

**Comment by ajazam** [comment]
![rusttab](https://user-images.githubusercontent.com/1839987/79021253-e95e9700-7b72-11ea-91a4-59ba1af7dbe1.PNG)

Your assumption was correct :)

*.rs was already assigned

![renderscript](https://user-images.githubusercontent.com/1839987/79021373-39d5f480-7b73-11ea-93d5-e4d6ab78c391.PNG)

After applying your suggestion the rust plugin is now working. Thank you
