### ISSUE TITLE
No code completion

### ISSUE THREAD

**Issue by LOMS** [intellij-rust/intellij-rust#524]
Am I missing something, or it doesn't work yet?

**Comment by alexeykudinkin** [comment]
Could you, please, elaborate on that? Completion is not all-mighty yet, but it ought to cover some not that far-fetched cases.

**Comment by agilob** [comment]
Just came to report the same issue. I have a one-file project, autocomplete "works", but only within some scopes, and it's very slow:
1. Inside a function it suggests only variable names
2. From different function it takes a few seconds to load possible suggestions (ctrl+space)
3. Does not work for ext crates at all 
4. Competition of core doesn't work at all (eg. `println!`, `let`, `for`)

Here is a short recording where I tried autocomplete and ctrl+space http://webmshare.com/nqQao

I used both configurations, standard where plugin downloaded sources and extracted them and my custom where I provided location of rust sources. I have rustc, cargo, racer and rustfmt available in $PATH.

ArchLinux, IDEA 2016.1.3, all installations made from Arch [repos](https://www.archlinux.org/packages/), but rust sources from git. Hope that helps :)

**Comment by Furyhunter** [comment]
IDEA does not use racer.

Several kinds of expressions are not typified at all yet, so you will not get completions out of them. Example of what typification means:

```rust
let b = "".<caret>
```

I do not believe the "" is typified to `&'static str`, so you wouldn't be able to get completions from impls for `&str`.

**Comment by LOMS** [comment]
@alexeykudinkin  I tried completions of core, keywords and stdlib, like @agilob mentioned in p4.

**Comment by alexeykudinkin** [comment]
@LOMS @agilob first of all, thanks for your careful report! Unfortunate current (plugin's) _state of the art_ assumes that there may be some inconsistencies related with the language support and especially such a tricky matter as methods completion. Though this is our primary goal right now, stay tuned!

**Comment by agilob** [comment]
So how did you get those suggestions on https://intellij-rust.github.io/ ?

**Comment by alexeykudinkin** [comment]
@agilob those are primarily file-bound.
