### ISSUE TITLE
Rust plugin doesn't see reference in index operator

### ISSUE THREAD

**Issue by denofevil** [intellij-rust/intellij-rust#5248]
## Environment

* **IntelliJ Rust plugin version:**
0.2.120.2202-201
* **Rust toolchain version:**
1.42.0
* **IDE name and version:**
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
* **Operating system:**
macOS 10.15.4

## Problem description
Consider the following example:
```rust
use objc::*;
unsafe fn make_menu(target_class: *const Class) {
    msg_send![target_class, new];
}
```
No usages found for `target_class` parameter

## Steps to reproduce
1. Open given example
2. Search for usages of target_class

Expected: usage in `msg_send![target_class, new];` is found.
Actual: no usages found

**Comment by Undin** [comment]
Looks like the full example is
```rust
#[macro_use]
extern crate objc;

use objc::runtime::*;

unsafe fn make_menu(target_class: *const Class) {
    let _: Object = msg_send![target_class, new];
}
```

Our default macro expansion engine doesn't support find usages in arbitrary macro calls (only some macros from stdlib like `println`)
Try to enable new experimental macro expansion engine (see #3628 for more details).
Note, although it should make name resolution faster, it may add some performance regression while indexing and typing (i.e. while the expansion of macro calls) especially in large codebase. We are working on eliminating this performance issue right now.

**Comment by denofevil** [comment]
Thanks a lot, it works!

**Comment by Undin** [comment]
@denofevil Great!
Don't hesitate to share any feedback (especially about new expansion engine) - it will help us to polish new engine to make it default option
