### ISSUE TITLE
Support for showing rendered doc comments in editor

### ISSUE THREAD

**Issue by dima74** [intellij-rust/intellij-rust#5255]
## Environment

* **IntelliJ Rust plugin version:** 0.2.120.2202-201
* **Rust toolchain version:** 1.42.0 (b8cedc004 2020-03-09) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2020.1 Ultimate Edition (IU-201.6668.121)
* **Operating system:** Linux 5.6.3-arch1-1

## Problem description
IDEA 2020.1 has gained an option for [showing rendered doc comments in the editor](https://blog.jetbrains.com/idea/2020/03/intellij-idea-2020-1-eap8/#in_editor_javadocs_rendering).

It would be nice to support this for Rust doc comments too.

Here is user request for it in YouTrack: https://youtrack.jetbrains.com/issue/KT-37361#focus=streamItem-27-4035491.0-0

**Comment by rookboom** [comment]
Does this support showing images (local or url) via markdown syntax?
