### ISSUE TITLE
Clion/Idea window won't open

### ISSUE THREAD

**Issue by dvtomas** [intellij-rust/intellij-rust#5267]
## Environment

* **IntelliJ Rust plugin version:** 0.2.120.2202-201
* **Rust toolchain version:** 1.42.0 (b8cedc004 2020-03-09) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2020.1 Community Edition (IC-201.6668.121)
* **Operating system:** Linux 5.4.0-4-amd64

## Problem description

The main window in Clion or Idea is not opened.

## Steps to reproduce

This has happened to me before sporadically, restarting couple of times has usually helped, but now I really can't open the project at all. I'm not totally sure this is related to Rust, but can't rule it out.

At the beginning of a new day I start Clion, hoping it will open my Rust project I'm working on. The splash screen shows, some progress bars in the notification area, and that's all. No main window shows up. I can't work.

If I use Intellij Idea, I have another project (Scala one) opened from last day, showing up correctly. I use File/Open item to open the Rust project, but it also doesn't open.

I'm attaching desktop screencast of hte Clion starting session. Thanks!

[out-1.ogv.zip](https://github.com/intellij-rust/intellij-rust/files/4508223/out-1.ogv.zip)

**Comment by dvtomas** [comment]
Just now I had success by opening another Rust project first (`clion.sh path-to-another-project`) and then, now having the menu available, opening my desired project using "File/open". At last I'm able to work, but that is just a workaround.

**Comment by ortem** [comment]
Hello @dvtomas, could you please provide us CLion log? It is located in `~/.cache/JetBrains/<product><version>/log` directory ([more information](https://www.jetbrains.com/help/idea/2020.1/tuning-the-ide.html?logs-directory#logs-directory)).

**Comment by dvtomas** [comment]
Attached. Last two launches from just now failed to open again, I guess the launch before that (yesterday morning) went fine.

[idea.log.zip](https://github.com/intellij-rust/intellij-rust/files/4514219/idea.log.zip)

**Comment by ortem** [comment]
@dvtomas Thank you! I haven't found any critical errors in the log yet, so probably the problem relates to slow/infinite project indexing. Could you please provide us some more information:
1. How big is your project (in KLOC)?
2. Have you tried waiting for several minutes before terminating IDE? Maybe the project will open after long indexing, and then we could see something more in the logs.
3. Have you tried [cleaning IDE caches](https://www.jetbrains.com/help/clion/cleaning-system-cache.html)? If no, please try doing it. You can actually run `Invalidate Caches...` action even without opening any project: just run CLion without a project, press `Ctrl+Shift+A`, and find this action by name.

**Comment by dvtomas** [comment]
Hi,
The project is about 80 KLOC, if it is of any relevance. But, I don't think the problem relates to slow indexing for the following reasons:

1. CPU is idle
2. This has happened to me before, sometimes the main window does open, sometimes not. However, when the window DID open, it opened very quickly. When it did not open, it didn't open for a loong time, CPU being idle.
3. The main window isn't waiting for the indexing to finish before it opens up, the indexing can go on while the main window is actually open (I'm not an expert on this, maybe there actually is something to wait for)
4. I *can't use the method you described, because there is no window open at all, there's nowhere to do Ctrl-Shift-A at!*. See the screencast I've attached to the issue.
5. I think I've encountered this with some Scala projects within Intellij IDEA as well - having one project opened, then opening another one "in a new window" resulted in the new window not being opened. However, some usual progress bars on the project being opened in the notification area (bottom right) have appeared as if the project was being opened, just the project window didn't show up.

I can't reproduce the issue right now, Clion seems to start my project reliably now. But, this has been bothering me on and off for at least half a year now, so I'm definitely not expecting this problem to just go away by itself.

**Comment by ortem** [comment]
@dvtomas OK, I got the point. Thank you for investigating this problem with Scala projects too. Looks like the problem relates to the IDEA (CLion) itself, but not just with Rust plugin. So I've opened the corresponding issue on IDEA tracker: https://youtrack.jetbrains.com/issue/IDEA-238539. Please follow the new issue and feel free to ask any questions and provide any additional information there.
