### ISSUE TITLE
'!' expected, but got '!' on top-level macro invocation.

### ISSUE THREAD

**Issue by NobbZ** [intellij-rust/intellij-rust#527]
There is a red wiggly line below an `!` of a top-level macro invocation. It does not matter if this macro does actually exist or not.

When hovering over the exclamation mark you get a tooltip saying "'!' expected, but got '!'":

![expected exclamation but got exclamation](https://cloud.githubusercontent.com/assets/58951/16844593/13b8fa3a-49e6-11e6-90c9-3641b2a8f8a5.png)

The project does compile though, without problems.

**Comment by matklad** [comment]
Hm, I though that `name! name (arguments)` macro form was only available for `macro_rules!`. How is `peg` macro defined?

**Comment by matklad** [comment]
Looks like this forms is allowed for procedural macros.
