### ISSUE TITLE
Show control flow in breadcrumbs

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#5271]
Sorry for a laconic bug report, hope the picture is worth a thousand words :) 

![image](https://user-images.githubusercontent.com/1711539/79908074-e7ba8c00-841a-11ea-909e-de35686d6845.png)

![image](https://user-images.githubusercontent.com/1711539/79908133-00c33d00-841b-11ea-9770-504972d5a71b.png)

**Comment by Undin** [comment]
See `org.rust.ide.miscExtensions.RsBreadcrumbsInfoProvider`

**Comment by Stzx** [comment]
I will try to fix it :)

**Comment by Kobzol** [comment]
@Stzx I started implementing it yesterday, but I'm not very far yet (although it seems that it should be easy), so go for it if you want :)

**Comment by Stzx** [comment]
@Kobzol  XD

I'm done (maybe
