### ISSUE TITLE
Put struct fields on separate lines after "Extract enum variant"

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#5282]
## Environment

* **IntelliJ Rust plugin version:** 0.2.122.SNAPSHOT-201-dev
* **Rust toolchain version:** 1.43.0 (4fb7144ed 2020-04-20) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.1 (CL-201.6668.126)
* **Operating system:** macOS 10.15.3

## Problem description

I guess it makes sense to put struct fields on separate lines in the first place after "Extract enum variant" action (#5182) call as rustfmt enforce.

## Steps to reproduce

```rust
enum A {
    Variant1 { name: String, id: usize, }
}
```

call "Extract enum variant"

```rust
struct Variant1 { pub name: String, pub id: usize, }

enum A {
    Variant1(Variant1)
}
```

after running `cargo fmt`

```rust
struct Variant1 {
    pub name: String,
    pub id: usize,
}

enum A {
    Variant1(Variant1),
}
```

**Comment by Undin** [comment]
Looks like it should be implemented from formatter side (not in the intention) and it will be automatically applied by the platform to all generated code (including described intention)

**Comment by Kobzol** [comment]
@Undin Could you please point me to the corresponding code of the formatter which affects formatting of auto-generated code?
