### ISSUE TITLE
Convert `Extract enum variant` intention to refactoring

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#5284]
`Extract enum variant` intention introduced in #5037 and #5182 is more refactoring than typical intention because it makes global code transformation (replacement of the corresponding usages).
It's great but it can apply changes too long for typical intention because of working with usages. It's not nice both from the user side - the corresponding actions usually show progress in such cases, and platform side - all code (reference search and replacement) is invoked under write action that may lead to IDE freezes.
It would be great to refactor the implementation and use proper approaches from platform. More details:
* Use `com.intellij.refactoring.BaseRefactoringProcessor` to move search of usages into read action and provide the corresponding progress
* Provide the corresponding action in `Refactor | Extract` menu (see `org.rust.ide.refactoring.RsBaseEditorRefactoringAction`)
* Use `org.rust.ide.intentions.RsRefactoringAdaptorIntention` to provide the same refactoring action as intention or even drop existing intention and leave only refactoring

Also, I think we need to move all the corresponding code to `org.rust.ide.refactoring` package to be consistent with other refactorings

See `org.rust.ide.refactoring.convertStruct.RsConvertToNamedFieldsAction` as example

**Comment by Undin** [comment]
CC @Kobzol @mchernyavsky

**Comment by Kobzol** [comment]
If it causes IDE freezes or similar problems, then it definitely should be changed. I'm a bit worried about discoverability though. Usually if I want to perform something, I check Alt+Enter and if it's offered, I run it directly. Going through the refactoring menus is a bit slower process. Things like introducing a field or extracting a method is known by many users from other IntelliJ IDEs and other languages, but this refactoring would be Rust specific, so other people may not expect it to live in the refactoring menu. Is there a way to somehow increase it's visibility even after converting it to a refactoring action?

**Comment by Undin** [comment]
We may keep it as intention but still use refactoring infrastructure under the hood. See `org.rust.ide.intentions.ConvertToStructIntention` as an example

**Comment by Kobzol** [comment]
OK, that would be ideal from my point of view. I'll try to refactor it and send a PR.
