### ISSUE TITLE
"Use of moved value" warnings with Copy values

### ISSUE THREAD

**Issue by DomWilliams0** [intellij-rust/intellij-rust#5294]
## Environment

* **IntelliJ Rust plugin version:** 0.2.121.3059-201-stable
* **Rust toolchain version:** 1.43.0
* **IDE name and version:** CLion 2020.1
* **Operating system:** Arch Linux

## Problem description
It complains that `Copy` values have been moved.

## Steps to reproduce
```rust
// compiles fine
fn main() {
    let a = 0i32;
    let b = a;
    let c = a; // <-- "Use of moved value"
}
```

**Comment by ortem** [comment]
@DomWilliams0 Thank you for reporting! Please try to [invalidate caches and restart CLion](https://www.jetbrains.com/help/clion/cleaning-system-cache.html).

**Comment by DomWilliams0** [comment]
That's fixed it for my main cargo project, but a scratch file still suffers the same issue

**Comment by ortem** [comment]
@DomWilliams0 Rust scratch files support is still very weak, and such files are not even connected to the Rust standard library. We recommend using either regular Cargo projects or `Rust REPL` (you can run open it using `Ctrl+Shift+A` or `Tools` menu).

**Comment by DomWilliams0** [comment]
@ortem Thank you - seeing as invalidating caches worked, I'll close the issue :smile:
