### ISSUE TITLE
modules not getting resolved without mod.rs file

### ISSUE THREAD

**Issue by rajasekarv** [intellij-rust/intellij-rust#5299]
## Environment

* **IntelliJ Rust plugin version: 0.2.121.3059-201-stable**
* **Rust toolchain version: rustc 1.44.0-nightly (7f3df5772 2020-04-16)**
* **IDE name and version: IntellJ Idea 2020.1**
* **Operating system: Ubuntu 18.04**

## Problem description
As mod.rs is no longer necessary, I have removed it and kept module_name.rs as it is. However, this way, submodules are not getting resolved now. 

## Steps to reproduce
This is the place where there is a problem with resolution
https://github.com/rajasekarv/native_spark/blob/f4bf96353b69e9056157992a9590872bc0b74122/src/rdd/rdd.rs#L23

Whole project: https://github.com/rajasekarv/native_spark/blob/master/src/rdd/rdd.rs#L23

**Comment by Kobzol** [comment]
The module is properly resolved in the latest version of the plugin.
