### ISSUE TITLE
IntelliJ Rust plugin can not recognize the `fold` syntax

### ISSUE THREAD

**Issue by taoweicn** [intellij-rust/intellij-rust#5300]
## Environment

* **IntelliJ Rust plugin version:** 0.2.121.3059-201-stable
* **Rust toolchain version:** rustc 1.43.0 (4fb7144ed 2020-04-20)
* **IDE name and version:** CLion 2020.1
* **Operating system:** macOS 10.15.4

## Problem description

IntelliJ Rust plugin can not recognize the [`fold`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.fold) syntax, but the code can be compiled and executed.
Some approaches have been tried and proved to be invalid, like reinstalling the plugin, invalidating caches and restarting, and even reinstalling the CLion. 😔

## Steps to reproduce

Write the following code in CLion with IntelliJ Rust plugin:
![image](https://user-images.githubusercontent.com/25795549/80573494-a5a0d400-8a32-11ea-9786-0e63979140b1.png)
Then execute:
![image](https://user-images.githubusercontent.com/25795549/80574924-4db79c80-8a35-11ea-8960-8647c6f973a2.png)
Result:
![image](https://user-images.githubusercontent.com/25795549/80574989-66c04d80-8a35-11ea-9f39-b5d43c81dcd2.png)

**Comment by Undin** [comment]
Try to enable new macro expansion engine (see #3628 for details). It should help

**Comment by taoweicn** [comment]
Thanks, it works!!
