### ISSUE TITLE
New IDE window should not be opened

### ISSUE THREAD

**Issue by Stzx** [intellij-rust/intellij-rust#5302]
## Environment

* **IntelliJ Rust plugin version:** 0.2.121.3059-201
* **Rust toolchain version:** rustc 1.44.0-nightly (b2e36e6c2 2020-04-22)
* **IDE name and version:** IntelliJ IDEA 2020.1
* **Operating system:** Windows 10

## Problem description

Create a Rust project in an open project, but do not open it. The IDE will still open a new window, and the window cannot be closed. Even if you exit the program directly, the IDEA process cannot end normally. Unless forced to end through the task manager.

I tried to find the problem, but no results. (Some similar problems were reproduced in the Gradle plugin)

![bug](https://user-images.githubusercontent.com/19950702/80591067-9aa86c80-8a4f-11ea-867c-628bc0583a13.gif)

## Steps to reproduce

Follow the steps in the gif.

**Comment by neonaot** [comment]
Sorry to keep you waiting. It looks like this bug is not reproducible in IntelliJ IDEA 2021.1. Most likely, it has already been fixed. Please let us know if the problem still persists.
