### ISSUE TITLE
Files not included into module tree, analysis not available

### ISSUE THREAD

**Issue by steelx** [intellij-rust/intellij-rust#5303]
## Environment

* **IntelliJ Rust plugin version:** 0.2.121.3059-201-stable
* **Rust toolchain version:** 1.43.0 (4fb7144ed 2020-04-20) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2020.1 (CL-201.6668.126)
* **Operating system:** Windows 10 10.0

## Problem description
As soon as I load up, which ever files are not added into GIT shows error on top "Files not included into module tree, analysis not available"

## Steps to reproduce
I installed CLion today first time.

**Comment by steelx** [comment]
I added the file as mod in `main.rs` -> `mod visibility_system;`

and it started working. Not sure if its requirement or a bug !

**Comment by vlad20012** [comment]
`Files not included into module tree` just says you that you the file... is not included into module tree. Why did you decide it's a bug?
