### ISSUE TITLE
Generate constructor looses dyn

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#5305]
## Environment

* **IntelliJ Rust plugin version:**  0.2.121.3059-201-stable
* **Rust toolchain version:** 1.44.0-nightly (b2e36e6c2 2020-04-22)
* **IDE name and version:** CLion 2020.1
* **Operating system:** Windows 10

## Problem description

When using "generate constructor", each `dyn Trait` gets stripped of dyn (and any further traits).

## Steps to reproduce

```rust
struct Widget {
    test: Box<dyn Display + Send>,
}

impl Widget {
    // notice the invalid type in the generated constructor
    pub fn new(test: Box<Display>) -> Self {
        Widget { test }
    }
}
```

**Comment by Kobzol** [comment]
@Undin I looked at it briefly and `Box<dyn Display + Send>` is resolved to  `Box<Display>`, so this looks like a type inference issue. Also `dyn` will need to be somehow stored in the type so that it can be reproduced in `TypeRenderer` (unless we just write `dyn` everytime).
