### ISSUE TITLE
Evcxr executable not found

### ISSUE THREAD

**Issue by Delamare2112** [intellij-rust/intellij-rust#5316]
## Environment

* **IntelliJ Rust plugin version:**  0.2.121.3059-201-stable
* **Rust toolchain version:**  Tested with:
  * (stable) 1.43.0 (4fb7144ed 2020-04-20)
  * 1.44.0-nightly (b2e36e6c2 2020-04-22)
* **IDE name and version:**  CLion 2020.1.1  Build #CL-201.7223.86
* **Operating system:**  Arch Linux (kernel: 5.6.7-arch1-1-vfio)

## Problem description  
The Rust REPL won't start.  Attempting to start it for the first time does successfully run `cargo install evcxr_repl`, but then when attempting to open it I get:
```
Error: Can't start evcxr
    Evcxr executable not found
```  
Re-running with the green restart arrow next to the error window presents a similar error:
```
Error: Can't start evcxr.
    java.lang.RuntimeException: Evcxr executable not found
```
However (in and out of CLion's terminal):
```sh
delamare@Ashalanoray ~ % which evcxr     
/home/delamare/.cargo/bin/evcxr
delamare@Ashalanoray ~ % echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/usr/lib/emscripten:/home/delamare/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/delamare/.cargo/bin
````  
I have attempted uninstalling and reinstalling with both nightly and stable and also install in or out of CLion each time also restarting CLion.

Not sure what to try next...
## Steps to reproduce  
Tools -> Rust REPL

**Comment by dima74** [comment]
@Delamare2112 thanks for reporting, I will take a look. As a workaround, you can add `evcxr` executable to directory with rust toolchain (Settings / Languages & Frameworks / Rust / Toolchain location). Most likely it is `/usr/bin`, so you could do:

    sudo ln -s /home/USER/.cargo/bin/evcxr /usr/bin/

**Comment by Delamare2112** [comment]
Workaround is working!  I'll try to remove the symlink if/when this issue gets resolved.  Thanks!
