### ISSUE TITLE
IDE does not understand that macro-generated type implements copy under certain conditions

### ISSUE THREAD

**Issue by flaghacker** [intellij-rust/intellij-rust#5318]
## Context

I'm hitting an annoying issue where the IDE does not understand that `Unit<Vec3<f32>>` from the `nalgebra` crate implements `Copy`. The same goes for `Point3`, which is similarly defined as a wrapper struct around `Vec3`. This results in `Cannot move` error highlights everywhere in the code.

This issue could be related to a couple other open issues, eg. #3987 and #3006, but I'm not 100% sure so I've opened a new one. Feel free to merge with an existing issue of course!

## The code

I spent a lot of time getting to a minimal example without any external dependencies, the result is still inspired by the `nalgebra` implementation that also heavily (ab)uses macros. I think the issue is caused by the combination of multiple repeated macro parameters. I have annotated each part of the code to note why it has to be part of the minimal example.

```rust
#![allow(dead_code)]

//This issue is specific to macros, manually writing out this implementation works fine.
macro_rules! define_point_vec {
    //We need two repeated macro parameters, in this case $coord and $axis.
    ($vec_name:ident; $($coord:ident),+; $($axis:ident),+) => {
        //$vec_name implements Copy!
        #[derive(Copy, Clone, Default)]
        struct $vec_name {
            //The type of coord doesn't matter, it can be any Copy type.
            $($coord: f32,)*
        }

        impl $vec_name {
            //I think this is the actual issue, the combination of two different repeated macro
            // parameters. Changing either *coord or *axis to the other parameters makes the entire
            // problem disappear. It's really interesting because this function is not actually used 
            // and so shouldn't be relevant at all, but without it the issue goes away.
            $(
            fn $axis() {
                let mut result: Self = Default::default();
                result.$coord = 1.0;
            }
            )*
        }
    }
}

define_point_vec!(Vec1; x; x_axis);

//The issue only happens when the resulting struct is wrapped in another generic struct that
// also implements Copy
#[derive(Copy, Clone)]
struct Wrapper<T> {
    inner: T
}

//Here we try to copy Wrapper<Vec1>
fn foo(wrapper: &Wrapper<Vec1>) -> Wrapper<Vec1> {
    //IDE says "Cannot move" but rustc compiles this just fine.
    *wrapper
}
```

## Environment

* **IntelliJ Rust plugin version:** 0.2.121.3059-201-stable
* **Rust toolchain version:** stable-x86_64-pc-windows-msvc, rustc 1.43.0 (4fb7144ed 2020-04-20)
* **IDE name and version:** CLion 2020.1
* **Operating system:** Windows 10 version 2004

The exact same thing happens in both the old and the new experimental macro engines.

**Comment by flaghacker** [comment]
The full error:

![image](https://user-images.githubusercontent.com/7887115/82914472-d6135980-9f6f-11ea-8cd3-b9fe423441db.png)

It looks like the IDE doesn't understand the type `&Wrapper<Vec1>`. Again everything works fine if you comment out the declaration of `fn $axis()`, even though that should really not have an effect.

**Comment by Undin** [comment]
Works for me with the latest plugin version so I close this issue.
@flaghacker if it still doesn't work for you, don't hesitate to ping us
