### ISSUE TITLE
How to disable module structure check in tests folder?

### ISSUE THREAD

**Issue by pymongo** [intellij-rust/intellij-rust#5324]
## Environment

* **IntelliJ Rust plugin version:0.2.121.3059-201-stable**
* **Rust toolchain version:1.43.0**
* **IDE name and version:CLion 2020.1.1**
* **Operating system:macOS 10.14.6**

## Problem description

```
├── tests
│   ├── test_1.rs
│   ├── test_2.rs
│   ├── common
│   │   ├── mod.rs
│   │   └── utils.rs
```

If **both** define `mod common` in `test_1.rs` and `test_2.rs`,

then the statement `use common::util::add;` in `test_1.rs` got an Error:

> Module `common` is private

But If I run all tests in tests folder, no error occur.

How to disable module private check in tests folder?

![](http://showmethemoney.hnengdata.com/image_after_2019_06/2449/temp.png)

## Steps to reproduce

Source Code

```rust
// tests/common/mod.rs
pub mod util;

// tests/common/util.rs
pub fn add(x: i32, y: i32) -> i32 {
  x + y
}

// tests/test_1.rs
mod common;
use common::util::add; // Error

#[test]
fn test() {
  assert_eq!(add(1,1), 2)
}

// tests/test_2.rs
mod common;
use common::util::add;

#[test]
fn test() {
  assert_eq!(add(1,1), 2)
}
```

**Comment by vlad20012** [comment]
Duplicate #3757
