### ISSUE TITLE
Cargo project update failed: Execution failed (exit code 101)

### ISSUE THREAD

**Issue by MightyPork** [intellij-rust/intellij-rust#5328]
In some projects I'm getting the following error and code analysis then does not work. I haven't found a reliable work-around.

> Cargo project update failed: Execution failed (exit code 101). /usr/bin/cargo check --message-format json stdout : ...

![Screenshot_20200505_092039](https://user-images.githubusercontent.com/2041118/81043022-b8dbf580-8eb1-11ea-996f-d0876baac7c7.png)

:paperclip: [idea.log](https://github.com/intellij-rust/intellij-rust/files/4579287/idea.log)

plugin 0.2.121.3059-201-stable
cargo 1.43.0 (3532cf738 2020-03-17)
rustc 1.43.0 (4fb7144ed 2020-04-20)

```
CLion 2020.1.1
Build #CL-201.7223.86, built on April 29, 2020
Subscription is active until January 3, 2021
Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.6.8-arch1-1
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 4
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false, cidr.max.intellisense.file.length=2000000
Non-Bundled Plugins: mobi.hsz.idea.gitignore, awesome.console, color.scheme.Dark Blue Theme, color.scheme.Tempo-theme, color.scheme.Wombat, com.etienne.toggleinclude, com.github.tom-power.close-tab-left-right, com.jetbrains.plugins.ini4idea, com.markskelton.one-dark-theme, com.widerwille.afterglow, krasa.IdeaIconPack, name.kropp.intellij.makefile, org.toml.lang, org.rust.lang, rs.pest
Current Desktop: KDE
```

**Comment by vlad20012** [comment]
See https://github.com/intellij-rust/intellij-rust/issues/5016#issuecomment-592021552

**Comment by MightyPork** [comment]
That helped, closing in favor of  #5016
