### ISSUE TITLE
Compatibility with IntelliJ Ultimate 2016

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [intellij-rust/intellij-rust#533]
Recently I have updated my IntelliJ installation to the 2016 version (now moved to yearly release numbering) and I can't get my projects previously configured with the rust SDK and the plugin to work, and I can't find a way to add a rust SDK to it (the existing ones are marked as invalid).

Any ideas on workarounds to get this to work?

IntelliJ version: 
IntelliJ IDEA 2016.2
Build #IU-162.1121.32, built on July 9, 2016
JRE: 1.8.0_76-release-b216 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Rust plugin:
Version: 0.0.1.808

I have the SDK configured in Settings > Languages & Frameworks > Rust

<img width="555" alt="screen shot 2016-07-16 at 19 42 51" src="https://cloud.githubusercontent.com/assets/5529132/16896514/85e53f94-4b8d-11e6-89a0-cb5c9490758f.png">

But when I try and configure a Rust SDK in my project (via Project Structure dialog), there is no option for Rust:

<img width="343" alt="screen shot 2016-07-16 at 19 41 42" src="https://cloud.githubusercontent.com/assets/5529132/16896518/a3f11f12-4b8d-11e6-943f-a6db3a10db6a.png">

**Comment by jajakobyly** [comment]
Yep, there is no SDK entry in Project Structure dialogue, because we resigned from using IDEA's SDK system, as it's not available in PyCharm, Clion etc.

But from what I see, your projects are incorrectly imported, as plugin doesn't see `Cargo.toml`. Try to reimport them

**Comment by matklad** [comment]
>the existing ones are marked as invalid

Looks like together with updating IDEA, you have updated the plugin from a rather old version. As @jajakobyly said, we've got rid of the SDK's a while ago.

So your best bet is just to open the projects again. Check out more or less up to date guide: https://intellij-rust.github.io/docs/quick-start.html

**Comment by matklad** [comment]
Looks like this is an "upgrading from old version" related problem, so closing this. 

We would love to provide smooth migration paths, but this is not cost effective given the relatively young age of the plugin.

**Comment by andrewdavidmackenzie** [comment]
The project I was importing (servo) doesn't have a Cargo.toml in the root, so I added a fake one and imported again and things look much better now. Thanks

**Comment by matklad** [comment]
Ah, I should really check how the plugin works with servo.

But yes, multi crate projects are not currently supported in the most convenient way. Another option besides adding a fake `Cargo.toml` is opening subdirectory with `Cargo.toml`. 

Things should become easier once cargo fully implements the workspaces RFC.

**Comment by andrewdavidmackenzie** [comment]
At least for me, I can't "Command click" into other methods/structs across the project with this import....

**Comment by matklad** [comment]
>At least for me, I can't "Command click" into other methods/structs across the project with this import....

If you add a fake Cargo.toml then the imports across files won't work. IntelliJ Rust communicates with Cargo to learn about project structure, so it is important that Cargo config itself is correct. 

You should be able to open Servo components, because they have the necessary Cargo.toml: https://www.youtube.com/watch?v=8oji7N85Mmw&feature=youtu.be. 

Opening the whole of Servo would be impossible without workspaces support.

**Comment by andrewdavidmackenzie** [comment]
Makes sense.

Any issue I can follow for the workspaces support?

**Comment by matklad** [comment]
Yep, here it is: https://github.com/rust-lang/cargo/issues/2122

Hm, Actually if you are using IntelliJ Idea (and not PyCharm, CLion, etc), you might be able to open the root servo project and then add components as modules (`Ctrl+Alt+Shift+S` > `Modules` > `+` > `Import from source`).

**Comment by matklad** [comment]
But in general expect rough edges with Servo. It uses a custom build system, and we unfortunately need a pretty tight integration with `Cargo` to work properly. One obvious problem is that while `mach` downloads dependencies into `.cargo` folder inside the project directory, and invoking `cargo` without `mach` downloads deps to `~/.cargo`.

**Comment by matklad** [comment]
>Any issue I can follow for the workspaces support?

Workspaces support have landed in both Cargo and IntelliJ Rust. 

Though it seems that Servo does not use workspaces yet...
