### ISSUE TITLE
Aliased `use`s are completet to their original name, not the alias

### ISSUE THREAD

**Issue by NobbZ** [intellij-rust/intellij-rust#534]
When aliasing a `use` it will be completed under the original name, not to the alias as shown on the screenshot.

![aliased_uses_are_completed_wrong](https://cloud.githubusercontent.com/assets/58951/16900634/cbafa3a0-4c2a-11e6-8589-f413bc73ec1a.png)

Transcription of the picture:

A code fragment which starts with `use std::collections::HashMap as Map;` below of that is a line `pub type Histogram = Map<String, u32>` the cursor is just after the `p` of `Map`, a completion PopUp is visible and wants to expand/complete `Map` to `HashMap`.

**Comment by matklad** [comment]
@alexeykudinkin what do you think is the best way to thread alias info from the [declarations] function into our completion engine? I still think that just exposing `ScopeEntries` is the simplest approach. Another way would be to store the aliased name in the `UserData` of the `RustNamedElement`, but this is ugly imo. 

[declarations]: https://github.com/intellij-rust/intellij-rust/blob/fb0e37fc85f95027abc9c1fe794981ee8f7fc966/src/main/kotlin/org/rust/lang/core/resolve/RustResolveEngine.kt#L221

**Comment by matklad** [comment]
@alexeykudinkin ping ^^^

**Comment by alexeykudinkin** [comment]
Yeah, sorry for delay. Will take a more in-depth look tonight.
