### ISSUE TITLE
Toml plugin requires restart after being disabled

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#5344]
## Environment

* **IntelliJ Rust plugin version:** 0.2.121.3059-201-stable
* **Rust toolchain version:** 1.43.0 (4fb7144ed 2020-04-20) x86_64-apple-darwin
* **IDE name and version:** PyCharm 2020.2 Snapshot Professional Edition (PY-202.3784)
* **Operating system:** macOS 10.15.3

## Problem description

Even though Toml is dynamic it is still required restart once disabled.

## Steps to reproduce

1. Install Toml (tested with 0.2.120.37-193)
2. Not restart is required - OK
3. Disable the plugin
4. Restart is required - FAIL

**Comment by Undin** [comment]
I think it should be fixed in the platform
See https://youtrack.jetbrains.com/issue/IDEA-240988

**Comment by Undin** [comment]
@lancelote Could you please check that everything is fine with latest platform nightly?

**Comment by lancelote** [comment]
Works fine indeed in 202.4590.
