### ISSUE TITLE
"u128 << i8" is falsely considered as an error

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#5346]
## Environment

* **IntelliJ Rust plugin version:** 0.2.122.3078-201-nightly
* **Rust toolchain version:** 1.43.0 (4fb7144ed 2020-04-20) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.1.1 (CL-201.7223.86)
* **Operating system:** macOS 10.15.3

## Problem description

Based on https://youtrack.jetbrains.com/issue/PY-42352

Plugin falsely complains about using shift `u128 << i8`.

## Steps to reproduce

```rust
fn main() {
    println!("1 << 3 is {}", shifter(3));
}

fn shifter(i: i8) -> u128 {
    let one = 1 as u128;
    one << i
}
```

<img width="532" alt="Screen Shot 2020-05-09 at 16 07 30" src="https://user-images.githubusercontent.com/2500320/81474590-39328b80-920f-11ea-8961-48923f772571.png">

**Comment by Undin** [comment]
Everything is fine if new macro expansion engine is enabled. See #3628 for details

**Comment by lancelote** [comment]
Oh, thanks, I forgot to enable it once again ☹️
