### ISSUE TITLE
--benches is not a recognized flag for Run Cargo Command

### ISSUE THREAD

**Issue by CAD97** [intellij-rust/intellij-rust#5349]
![image](https://user-images.githubusercontent.com/5992217/81515713-5ba5d100-9303-11ea-881f-3bb124909486.png)

Meta:
IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 29, 2020
Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16

Rust plugin version 0.2.121.3059-201-stable

**Comment by mchernyavsky** [comment]
Fixed by https://github.com/intellij-rust/intellij-rust/pull/6056.
