### ISSUE TITLE
Run Configuration: allow toolchain override + debugger

### ISSUE THREAD

**Issue by Bromeon** [intellij-rust/intellij-rust#5387]
## Environment

* **IntelliJ Rust plugin version:** 0.2.121.3059-193-stable
* **Rust toolchain version:** 1.44.0-nightly, nightly-x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2019.3.3 (Build #CL-193.6015.37)
* **Operating system:** Windows 10

## Problem description
Background: I have the Rust MSVC toolchain as default on my system. I'm compiling release builds from CLion using that. However, I would like to use the debugger during development, and since the MSVC toolchain is not ready to be used with the debugger (#4104), I need to be able to switch to the GNU one.

Cargo offers the [plus syntax for toolchain override](https://github.com/rust-lang/rustup/blob/master/README.md#toolchain-override-shorthand). The toolchain name must be placed before any subcommand such as `run`:
```
cargo +nightly-x86_64-pc-windows-gnu run
```

It looks like CLion does not recognize this syntax as "running a Rust executable" -- probably because `run` is no longer the first command argument -- and therefore provides no option to run with the debugger.

## Steps to reproduce

Not project- or code-dependent.
1. Install both MSVC and GNU Rust toolchains on Windows (nightly in this example)
1. Choose MSVC as default (`rustup default nightly-x86_64-pc-windows-msvc`)
1. Open any Rust project with a binary target in CLion
1. Go to _Run Configurations_, add _Cargo Command_ `+nightly-x86_64-pc-windows-gnu run`
![grafik](https://user-images.githubusercontent.com/708488/82130520-657c7800-97cc-11ea-84f9-479dbb5304c3.png)

Now try to run the program with the debugger. The _Debug_ button is disabled, shortcut won't work either:
![grafik](https://user-images.githubusercontent.com/708488/82130529-847b0a00-97cc-11ea-8432-2d561de0c521.png)

Same applies for the _Coverage_ button.
It seems like the normal _Run_ button is correctly choosing the specified GNU toolchain.

**Comment by mchernyavsky** [comment]
Fixed by https://github.com/intellij-rust/intellij-rust/pull/7864.
