### ISSUE TITLE
Uncommenting a doc comment

### ISSUE THREAD

**Issue by CDirkx** [intellij-rust/intellij-rust#5388]
## Environment

* **IntelliJ Rust plugin version:** 0.2.121.3059-201-stable
* **Rust toolchain version:** Rust 1.45 nightly
* **IDE name and version:** CLion 2020.1.1
* **Operating system:** Windows 10

## Problem description
Uncommenting (`CTRL+ '/'`) on a doc comment (`///`) results in a single remaining slash:

before:
```rust
/// this is a doc comment
```

after:
```rust
/ this is a doc comment
```

expected:
```rust
this is a doc comment
```

## Solution
The implementation right now is to just remove two '/' characters at the beginning of the line. My proposal would be to extend this to removing two or three characters, depending on how many are written.

**Comment by vlad20012** [comment]
for someone who decides to fix it: it's possible by implementing `SelfManagingCommenter` to `RsCommenter`

**Comment by Kobzol** [comment]
I'll try to implement it. If I understand it correctly, using `SelfManagingCommenter` is a low-level manual comment implementation, therefore if we implement it, we no longer need to implement `Commenter` for `RsCommenter`?

**Comment by Undin** [comment]
@Kobzol we still need to implement `Commenter` because we use `lang.commenter` extension point to register our commenter and it requires to implement `Commenter` interface

**Comment by vlad20012** [comment]
> `SelfManagingCommenter` is a low-level manual comment implementation

Yes. Moreover, there are no open-source implementations of `SelfManagingCommenter` =/

"Default" implementation (used for regular `Commenter`) can be found at `CommentByBlockCommentHandler`/`CommentByLineCommentHandler`. It looks scary. I don't know what parts of them are really needed in the case of Rust.

Also, take a look at `SelfManagingCommenterUtil`.
