### ISSUE TITLE
Debug fails (macOS)

### ISSUE THREAD

**Issue by egorbarsukoff** [intellij-rust/intellij-rust#5391]
## Environment

* **IntelliJ Rust plugin version:** 0.2.121.3059-201-stable
* **Rust toolchain version:** 1.43.1 (8d69840ab 2020-05-04) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.1.1 (CL-201.7223.86)
* **Operating system:** macOS 10.15.4

## Problem description

Debug in default configuration fails with  "No such file or directory". File exists and runs by "run" button.
![image](https://user-images.githubusercontent.com/28301369/82166743-0ef16580-98c2-11ea-97e8-94ddb895cdd4.png)

## Steps to reproduce

It can be reproduced by running debug in default "Hello world" example.

**Comment by ortem** [comment]
@egorbarsukoff Are you using GDB as a debugger? If so, try to select `Bundled LLDB` in the [toolchain settings](https://www.jetbrains.com/help/clion/configuring-debugger-options.html#select-debugger).

**Comment by egorbarsukoff** [comment]
@ortem 
By default (for c++ projects) I use Remote Host, and there GDB is set. After I switch default toolchain to local, rebuffing

**Comment by egorbarsukoff** [comment]
@ortem 
By default (for c++ projects) I use a Remote Host, and there GDB is set. After I switched the default toolchain to local, the debugger started working.
But this is strange. Rust projects are created, storing, and running locally.

**Comment by ortem** [comment]
@egorbarsukoff We recommend using LLDB on macOS (see #5077 for explanation). As for remote development, IJ Rust only supports [remote debugging via gdbserver](https://www.jetbrains.com/help/clion/remote-debug.html) but does not support remote toolchains so far.

**Comment by ortem** [comment]
Looks like this issue can be closed.
@egorbarsukoff Please reopen it if switching to LLDB does not help.
