### ISSUE TITLE
Suggest to install nightly toolchain

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#5396]
## Environment

* **IntelliJ Rust plugin version:** 0.2.123.SNAPSHOT-201-dev
* **Rust toolchain version:** 1.43.0 (4fb7144ed 2020-04-20) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.1.1 Ultimate Edition (IU-201.7223.91)
* **Operating system:** macOS 10.13.6

## Problem description
If you don't have nightly toolchain on your machine, `Run with Coverage` action fails with `error: toolchain 'nightly-x86_64-apple-darwin' is not installed`. It would be great to handle such cases somehow. For example, provide a quick way to install nightly toolchain from IDE

**Comment by mchernyavsky** [comment]
Fixed in https://github.com/intellij-rust/intellij-rust/pull/5760.
