### ISSUE TITLE
Syntax highlighting recognizes everything as variable by default

### ISSUE THREAD

**Issue by LastExceed** [intellij-rust/intellij-rust#5397]
## Environment

* **IntelliJ Rust plugin version:** 0.2.121.3059-201-stable
* **Rust toolchain version:** 1.41.0
* **IDE name and version:** IntelliJ Ultimate 2020.1.2 Preview
* **Operating system:** Windows 10 Home x64

## Problem description

Anything typed in the editor is highlighted as `Variables -> Default` unless it is explicitly recognized as something else. This can be very confusing when you're the type of programmer that likes to read information by color (who usually has a different color for variables compared to default text), most notably with syntax errors. Variables should only be highlighted in their respective color when recognized as such, just like everything else. unrecognized text should be displayed in the editor's default text color (or have it's own color).

I am not naming any actual colors since they depend on user configuration.

## Steps to reproduce

* set the highlighting color of `Variables -> Default` to some unique color of your choice
* type any random gibberish in a rust file
* see that it's highlighted in that color even though it's clearly not a variable

**Comment by vlad20012** [comment]
Hmm, looks like our "Variables | Default" really means "any identifier". So, we don't have a color setting for "any variable". For some reason...
