### ISSUE TITLE
Project layout

### ISSUE THREAD

**Issue by Turbo87** [intellij-rust/intellij-rust#54]
Is there any reason for not using the usual Maven/Gradle [project layout](https://docs.gradle.org/current/userguide/java_plugin.html#N12323)?

**Comment by matklad** [comment]
I guess the reason is mainly historical: we switched to gradle build not so long ago :)

@alexeykudinkin @atsky what do you thing about changing the layout. I'd like to do it while we don't have PRs

**Comment by matklad** [comment]
Ouch, we do have a massive PR here: https://github.com/alexeykudinkin/intellij-rust/pull/38

**Comment by Turbo87** [comment]
Yep, #38 should probably be merged first.

**Comment by Turbo87** [comment]
in the same step I would also like to move the component test data into folders mirroring the package hierarchy. currently in "Project" view we have top-level packages for all the testData folders but I think it would be better if the data was closer to the actual test code in that view.

**Comment by matklad** [comment]
>in the same step I would also like to move the component test data into folders mirroring the package hierarchy.

This is better done in a separate step, because it does not depends on 38.

**Comment by matklad** [comment]
I'm not quite happy with toml package layout at the moment, see discussion here: https://github.com/alexeykudinkin/intellij-rust/pull/76#discussion_r44133060

**Comment by matklad** [comment]
@alexeykudinkin so we are changing the layout?

**Comment by alexeykudinkin** [comment]
@matklad why not?

**Comment by matklad** [comment]
I was just asking for conformation. Will do this tomorrow: at the moment I am adding metadata to cargo
