### ISSUE TITLE
Can't recognize `tokio TcpStream`

### ISSUE THREAD

**Issue by Future2100** [intellij-rust/intellij-rust#5419]
As the title, when I use `tokio TcpStream`, rust can't find where it is but I can compile successfully.
(There would be something wrong with rust condition compilation.)

**Comment by Undin** [comment]
See https://github.com/intellij-rust/intellij-rust/issues/4627#issuecomment-583407031

**Comment by Undin** [comment]
Duplicate of #4627

**Comment by Future2100** [comment]
Thanks a lot.
