### ISSUE TITLE
Can't disable plugin annotations for built-in macros

### ISSUE THREAD

**Issue by MSxDOS** [intellij-rust/intellij-rust#5425]
I want to disable all annotations like "Argument never used" for `print`, `println` and other built-in macros which were added in some plugin version but there's no such option in Editor->Inspections->Rust, the Registry or Experimental Features menus.

How do I do it?

**Comment by vlad20012** [comment]
It's impossible for now :(

Are there some issues with it?

**Comment by MSxDOS** [comment]
The plugin only checks the name of the macro, not its origin. It results in annotations also being applied to macros that don't even come from std e.g. custom `print` implementations in `no_std` environment that may have completely different syntax. It's not a problem with auto-completion or other stuff that applied to them before.
