### ISSUE TITLE
Incorrect TODO highlight 

### ISSUE THREAD

**Issue by RazrFalcon** [intellij-rust/intellij-rust#5429]
## Environment

* **IntelliJ Rust plugin version:** 0.2.122.3105-201
* **IDE name and version:**  IntelliJ IDEA 2020.1.1 (Community Edition)

## Problem description

The `TODO` keyword should be ignored when it's not at the start of a comment?

![2020-05-24-181253_3840x2160_scrot](https://user-images.githubusercontent.com/725494/82757618-47290480-9dea-11ea-9f70-46a2b56c5552.png)

## Steps to reproduce

```rust
// struct Todo(i32);
```

**Comment by Undin** [comment]
> The TODO keyword should be ignored when it's not at the start of a comment?

No, it works correctly according to the default regexp for todo. By default, it's a `todo` word  and everything else after it.
You may try to change the pattern via `Preferences | Editor | TODO` settings (note, a pattern should be written using [Java regex syntax](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html)). Also, [this](https://www.jetbrains.com/help/idea/using-todo.html) page can be helpful
