### ISSUE TITLE
Highlight items from `std` part of stdlib with `no_std` attribute

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#5431]
## Environment

* **IntelliJ Rust plugin version:** 0.2.123.3110-201-nightly
* **Rust toolchain version:** 1.45.0-nightly (a74d1862d 2020-05-14) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.1.1 Ultimate Edition (IU-201.7223.91)
* **Operating system:** macOS 10.13.6

## Problem description
`println!` macro is a part of `std` crate. But if there is `#![no_std]` attribute, we can't use it. So usage of `println!` is compilation error. It would be great to highlight usages of items from `std` as compilation error in `no_std` context

## Steps to reproduce
```rust
#![no_std]

fn main() {
    println!("Hello, world!");
}
```

**Comment by Kobzol** [comment]
`#![no_std]` is currently stored in the attributes of `RsFile`, but this attribute is global for the whole crate, so it should probably be first moved to a crate/package.

**Comment by Undin** [comment]
> #![no_std] is currently stored in the attributes of RsFile, but this attribute is global for the whole crate, so it should probably be first moved to a crate/package.

Note, currently, `Package`/`Target`/`CargoWorkspace` objects are immutable (almost) and created during `Cargo refresh` phase. And I don't think we want to pass any info from code to these object directly

> I just realized that you can get the root file of the crate and check if it has the #![no_std] attribute. Is that an OK solution?

Yep. See `org.rust.lang.core.psi.RsFile#attributes` property
