### ISSUE TITLE
Iterator type hints noisy when type isn't changing

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [intellij-rust/intellij-rust#5433]
The type hints for iterator chains are generally useful. However, sometimes I find a chain like this is useful:

```rust
vec
    .iter()
    .filter(...)
    .filter(...)
    .filter(...)
    .map(...)
    .collect();
```

The `impl Iterator<Item=&SomeType>` hints on the `filter` calls aren't very useful, since the type is the same after all of them. It would be nice if there was an option to only show hints when type has changed; in this case, they'd be shown on `iter` and `map` calls.

**Comment by Kobzol** [comment]
This option is already implemented, it's just turned off by default. If you go to `Editor -> Inlay Hints -> Rust -> Chain method hints` and turn off `Show same consecutive types`, you should get the behaviour that you want.

**Comment by vlad20012** [comment]
> Maybe we could compare the types based on the rendered string output instead?

Oh, it looks like we should do it this way. Except for the fact that inlay presentation is not a string... Let's summon @ortem here

**Comment by ortem** [comment]
Yes, inlay presentations are not strings. A possible solution here: create a special comparator for two `Ty` objects such that `TyAdt` with `impl Iterator` are compared using their `TyAnon` representation (from `org.rust.ide.hints.RsTypeHintsPresentationFactory#tryIteratorHint`). @vlad20012 what do you think?

**Comment by vlad20012** [comment]
Hmm, maybe it's easier to prepare types with `TypeFolder` - replace iterator types with `impl Iterator` and then compare them as usual
