### ISSUE TITLE
What is the logic behind labeling function arguments?

### ISSUE THREAD

**Issue by abetkin** [intellij-rust/intellij-rust#5442]
![whr](https://user-images.githubusercontent.com/2223279/82818517-7d788980-9ea7-11ea-8420-a1db9811c4ea.png)

In the screen above we see that `x < 3` expression is labeled with "cond:", despite being the sole argument of the function `whr`. I've been using Goland and there AFAIK sole arguments are not decorated.

Is that a bug? Or are there some rules  behind this that I don't know about?

## Environment

* **IntelliJ Rust plugin version:** 0.2.122.3105-201
* **Rust toolchain version:** 1.45.0-nightly (a74d1862d 2020-05-14) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.1.1 (CL-201.7223.86)
* **Operating system:** Linux 5.6.12-1-manjaro

**Comment by ortem** [comment]
@abetkin The rules may be different for different languages. In Rust, we hide hints for single-argument functions only if the function name starts with `set_` like `fn set_x(value: i32)` or if the function name equals to the parameter name like `fn foo(foo: i32)`.

You can configure them with [black lists](https://www.jetbrains.com/help/clion/parameter-hints.html#config-hints). For example, to hide hints for single-argument functions, you can add `(*)` pattern to the blacklist.

**Comment by abetkin** [comment]
Thank you!
