### ISSUE TITLE
Duplicate type hint (str and char) on collect generic parameter

### ISSUE THREAD

**Issue by Tom01098** [intellij-rust/intellij-rust#5443]
## Environment

* **IntelliJ Rust plugin version:** 0.2.122.3105-201
* **Rust toolchain version:** 1.43.1
* **IDE name and version:** IDEA 2020.1.1
* **Operating system:** Windows 10 Home

## Problem description
The plugin is showing two different type hints for a discarded generic parameter.

## Steps to reproduce
See the following:
```rust
use std::collections::HashSet;

pub fn anagrams_for<'a>(word: &str, possible_anagrams: &[&str]) -> HashSet<&'a str> {
    let sorted = {
        let mut vec =  word.chars().collect::<Vec<_>>();
        vec.sort();
        &vec.iter().collect::<String>()[..]
    };

    todo!()
}
```
![image](https://user-images.githubusercontent.com/7976946/82819920-24a1f480-9e99-11ea-8ae6-d15840502693.png)

The underscore is being type hinted as both `str` and `char`, even though the type hint for `vec` understands it is a `char`.

**Comment by vlad20012** [comment]
Hi! Thanks for the report!

You can disable hints for placeholders in `File | Settings | Editor | Inlay Hints | Rust | Type hints`

![image](https://user-images.githubusercontent.com/3221931/82834479-e670f900-9ec9-11ea-9efd-9326a74261ff.png)


I've taken a loot at #5197 and the implementation seems buggy. I think we should hotfix or disable them for now in the next release
