### ISSUE TITLE
Resolving std value parameter type

### ISSUE THREAD

**Issue by andrew0x0007c8** [intellij-rust/intellij-rust#5450]
## Environment

* **IntelliJ Rust plugin version:** 0.2.122.3105-201
* **Rust toolchain version:** 1.43.1 (8d69840ab 2020-05-04) x86_64-unknown-linux-gnu
* **IDE name and version:** WebStorm 2020.1.1 (WS-201.7223.93)
* **Operating system:** Linux 4.15.0-101-generic

## Problem description
After update to 0.2.122.3105-201 plugin version I've got errors:
Unresolved reference: `None` -> on using std::option::Option::None
also `Use of moved value` on f64 variables, which copy by default

**Comment by andrew0x0007c8** [comment]
![image](https://user-images.githubusercontent.com/33863848/82902914-9cdfe700-9f79-11ea-9305-c4391e384723.png)
red dash -> Use of moved value error

**Comment by Undin** [comment]
Probably, something happens with caches after update.
As a workaround, you may try to invalidate caches via `File | Invalidate Caches/Restart` action
