### ISSUE TITLE
Cargo.toml dependencies autocompletion should be insensitive to - vs _

### ISSUE THREAD

**Issue by Riateche** [intellij-rust/intellij-rust#5453]
For example, if I input `once-ce`, it should suggest both `once_cell = "1.4.0"` and `once-cell-regex = "0.1.1"`. It should correct the prefix according to the selected option. The inconsistency of crate name styles is a major pain point, so the IDE should help with that when possible. Currently, only crates that exactly match the prefix are suggested.

Another thing that would be useful is a quick fix feature that detects misspelled crate names and suggests to correct them. But choosing the correct name in the first place would save more time, of course.

**Comment by Kobzol** [comment]
Fixed by https://github.com/intellij-rust/intellij-rust/pull/6390.

**Comment by Undin** [comment]
Reopen because of https://github.com/intellij-rust/intellij-rust/issues/5908#issuecomment-744738226

**Comment by Kobzol** [comment]
This now works in stable.
