### ISSUE TITLE
Unresolved reference for type that is available via module with `cfg_attr` with `path`

### ISSUE THREAD

**Issue by Enrico2** [intellij-rust/intellij-rust#5458]
## Environment

* **IntelliJ Rust plugin version:** 0.2.122.3105-201
* **Rust toolchain version:** 1.45.0-nightly (a74d1862d 2020-05-14) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.1.1 Ultimate Edition (IU-201.7223.91)
* **Operating system:** macOS 10.15.4

## Problem description

[This `Color` type](https://docs.rs/env_logger/0.7.1/env_logger/fmt/enum.Color.html) is not found in IntelliJ for code completion, and when used, is shown as red erroring with Unresolved reference.

The type is implemented in `env_logger` in `extern_impl.rs` that's referenced like so:
```rust
#[cfg_attr(feature = "termcolor", path = "extern_impl.rs")]
#[cfg_attr(not(feature = "termcolor"), path = "shim_impl.rs")]
mod imp;
```

fwiw `imp` is also red:
![image](https://user-images.githubusercontent.com/161314/82948470-af94f480-9f56-11ea-923b-cc2ff01a3574.png)

## Steps to reproduce

Offending line: https://github.com/apollographql/apollo-cli/blob/ba48c9f6af91a98bcf0b13fea026acfde1d36f0f/cli/src/log.rs#L24

check out that commit in that repo

oddly, the `use` line (line 6) isn't red.
```rust
use env_logger::fmt::{Color, Formatter};
```

![image](https://user-images.githubusercontent.com/161314/82948710-2500c500-9f57-11ea-9b2c-d6dce6cc7be4.png)

**Comment by Undin** [comment]
Thanks for the report!
`cfg_attr` is not supported by plugin yet. You can see the current state of conditional compilation support in #1191
