### ISSUE TITLE
Improper error highlighting (rug "1.8.0" multiplication)

### ISSUE THREAD

**Issue by spquix** [intellij-rust/intellij-rust#5461]
## Environment

* **IntelliJ Rust plugin version: 0.2.122.3105-201**
* **Rust toolchain version: rustc 1.43.1 (8d69840ab 2020-05-04) x86_64-apple-darwin**
* **IDE name and version: IntelliJ IDEA 2020.1.1 Community Edition (IC-201.7223.91)**
* **Operating system: macOS 10.13.6**

## Problem description

IDE improperly highlight RHS operand or overloaded multiplication '*' operator for "rug::Integer" 
type.

mismatched types [E0308]

whereas compilation and test run without errors.

No error highlighting problems with Add '+' and Sub '-' operators.

Also it seems IDE suppose wrong completions for Add::add, Mul::mul methods  Integer type.

## Steps to reproduce

`Cargo.toml`
```toml
[dependencies]
rug = "1.8.0"
```

```rust
use rug::Integer;

#[test]
fn ops() {
    let res: Integer = Integer::from(123 * 456);

    let t: Integer = Integer::from(&Integer::from(123) * &Integer::from(456));
    assert_eq!(t, res);
    let t: Integer = Integer::from(123) * &Integer::from(456); // improper error highlight on RHS
    assert_eq!(t, res);
    let t: Integer = &Integer::from(123) * Integer::from(456);
    assert_eq!(t, res);
    let t: Integer = Integer::from(123) * Integer::from(456); // improper error highlight on RHS

    assert_eq!(t, res);

    // + and - are Ok:

    let res: Integer = Integer::from(123 + 456);

    let t: Integer = Integer::from(&Integer::from(123) + &Integer::from(456));
    assert_eq!(t, res);
    let t: Integer = Integer::from(123) + &Integer::from(456);
    assert_eq!(t, res);
    let t: Integer = &Integer::from(123) + Integer::from(456);
    assert_eq!(t, res);
    let t: Integer = Integer::from(123) + Integer::from(456);
    assert_eq!(t, res);
}
```
<img width="1280" alt="screenshot-idea-rust" src="https://user-images.githubusercontent.com/16068775/82998101-f561c380-a00f-11ea-9ecf-9e04e15750c0.png">

**Comment by Kobzol** [comment]
It should work with the new macro expansion engine. Try to enable it (https://github.com/intellij-rust/intellij-rust/issues/3628) to see if that helps.

**Comment by spquix** [comment]
Thank you, with new macro expansion all works right.
No incorrect error highlighting.
Correct suggestions for macro generated functions.
