### ISSUE TITLE
Cargo.toml dependencies versions for docs urls are different from those Cargo uses

### ISSUE THREAD

**Issue by avrong** [intellij-rust/intellij-rust#5467]
There is a difference between how Cargo and Docs.rs treat versions of dependencies. This is understandable because of the different purposes of version in config file and that one for docs. However, when a user want to see a documentation for specific crate in dependencies, it will be reasonable to show him docs for the version Cargo downloads and then compiler uses.

Two cases that are different from what is expectable:
1.  Version without any operators ⇒ caret requirement
   Docs should be latest semver-compatable version, instead docs.rs treats that as exact. Can be fixed by adding caret to the version in url.
   ![image](https://user-images.githubusercontent.com/6342851/83169802-3d6e0c80-a11c-11ea-82c8-8165e979b73d.png)
2. Empty version ⇒ wildcard requirement
   Docs should be latest version, instead version is missed in the url. Can be fixed by changing to * (star/wildcard) version in the url.
   ![image](https://user-images.githubusercontent.com/6342851/83169967-7c03c700-a11c-11ea-984d-d29ac8ae99f9.png)

I found three different implementations of docs.rs url generation for different places in the editor: `CargoCrateDocLineMarkerProvider` for Cargo.toml, `RsDocumentationProvider` for quick help and `RsCrateDocLineMarkerProvider` for `extern crate` expressions.

Source: [Specifying Dependencies - The Cargo Book](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html)

Happy to help and ready to fix this if it is reasonable.

Related to #5440

**Comment by Kobzol** [comment]
Also related to https://github.com/intellij-rust/intellij-rust/issues/5411.

**Comment by vlad20012** [comment]
An interesting fact is that the real used version is not "the latest semver-compatible version" or "the latest version". The real version is determined by Cargo using Cargo.lock (and satisfying different version requirements from different crates). 

Another way is to get the actual version from a cargo workspace, I guess. But this makes problems when editing Cargo.toml. I.e. you can change a version of some dependency, but the link will not be updated until the cargo refresh.
