### ISSUE TITLE
Support "`main` function not found" error

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#5477]
## Environment

* **IntelliJ Rust plugin version:** 0.2.122.3105-201
* **Rust toolchain version:** 1.32.0 (9fda7c223 2019-01-16) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.2 EAP Ultimate Edition (IU-202.4357.23)
* **Operating system:** macOS 10.13.6

## Problem description
Binary crate root should have `main` function. Otherwise, the compiler produces [E0601](https://doc.rust-lang.org/error-index.html#E0601) error. Currently, the plugin says nothing about it.
I think we can add error annotation to `RsFile` if it's is a crate root and the corresponding target is binary and provide quick fix to add `main` function to the file.
Note, there is `#![no_main]` attribute.

**Comment by Kobzol** [comment]
What should be the span of the annotation? It might be annoying to mark the whole file with a red underline.

**Comment by Stzx** [comment]
@Kobzol Hey, I have implemented it on my branch.

> What should be the span of the annotation?

Directly mark `RsFile` instead of file content.

To be determined:

* How to write test in `RsErrorAnnotatorTest`? (I tried to override `createAnnotationFixture()` to avoid the entire test class from failing, but this only solved part of the problem. Or use `if (isUnitTestMode)`?)

**Comment by Undin** [comment]
> What should be the span of the annotation? It might be annoying to mark the whole file with a red underline.

Yep, if we highlight the whole file, it will be very annoying. Fortunately, IntelliJ Platform can provide  the following file-level annotations:
![image](https://user-images.githubusercontent.com/2539310/83433391-03657900-a442-11ea-958b-f27a06935e32.png)

> How to write test in RsErrorAnnotatorTest?

I'm not sure that we can achieve the desired result using `RsErrorAnnotator`. I'd recommend creating a separate inspection for it.
It seems you can use `org.rust.ide.annotator.RsAnnotationTestBase#checkFixByText` as for all other test. Just wrap all text of file into error tag and don't insert caret

**Comment by Stzx** [comment]
> I'm not sure that we can achieve the desired result using RsErrorAnnotator. I'd recommend creating a separate inspection for it.

I used `visitFile(PsiFile file)` to accomplish this goal.

However, this caused the entire test class to fail (`RsErrorAnnotatorTest`). So implementing a class alone seems like a great decision. I will push PR later
