### ISSUE TITLE
CLion / Rust plugin debug timeout

### ISSUE THREAD

**Issue by Strangelovian** [intellij-rust/intellij-rust#5485]
## Environment

* **IntelliJ Rust plugin version:** 0.2.123.3132-201
* **Rust toolchain version:** 1.43.1 (8d69840ab 2020-05-04) x86_64-pc-windows-gnu
* **IDE name and version:** CLion 2020.1.1 (CL-201.7223.86)
* **Operating system:** Windows 10 10.0

## Problem description
GNU toolchain is configured via rustup:
```
> rustup toolchain list
stable-x86_64-pc-windows-gnu (default)
```
The GNU MinGW toochain is downloaded from CLion suggested [link](http://mingw-w64.org/doku.php/download/mingw-builds), and CLion is configured to use in Settings, Build Execution Deployment, Toolchains:
![Annotation 2020-06-02 151540](https://user-images.githubusercontent.com/3154712/83524478-f4370780-a4e3-11ea-806c-bb116f606aae.jpg)

## Steps to reproduce
With the following hello world:
```
fn main() {
    let x = 5;
    print!("Hello, {} world!", x);
}
```
Set a breakpoint on the print, and start debugging.
CLion enters in debug mode, but the "Variables" tab is stuck with message "Collecting Data".
![Annotation 2020-06-02 151025](https://user-images.githubusercontent.com/3154712/83524154-783cbf80-a4e3-11ea-9eb6-2eedd1f08bb0.jpg)

After a while, the debugging sessions times out without being able to display any debugging data:
![Annotation 2020-06-02 151026](https://user-images.githubusercontent.com/3154712/83524245-9f938c80-a4e3-11ea-91b0-2ab7b9b267af.jpg)

However, the same rust program debugs fine with the same GDB configured in CLion preferences:
![Annotation 2020-06-02 151209](https://user-images.githubusercontent.com/3154712/83524385-d669a280-a4e3-11ea-8fd4-68c2013e685b.jpg)

**Comment by Strangelovian** [comment]
I'm kind of sad the debugging works well with visual studio code + rust  + microsoft c++ runtime, because I'd rather use CLion 😭

**Comment by ortem** [comment]
@Strangelovian Your `MinGW` version `3.3` is old, could you please try to update it? I have `MinGW w64 6.0` with `gdb 8.1` and it works fine. If updating won't help, please provide us CLion debugger logs:
1. Enable `#com.jetbrains.cidr.execution.debugger` as described [here](https://intellij-support.jetbrains.com/hc/en-us/articles/360001436079-Collecting-additional-logs-in-CLion-)
2. Collect log file using `Collect Logs and Diagnostic Data` action and attach them

**Comment by Strangelovian** [comment]
I somewhat found a mingw distribution that works for me:
https://jmeubank.github.io/tdm-gcc/
With other things, it contains a recent GDB version 8.1 for the GNU x86_64 toolchain.

However, the "Download..." link provided in the CLion toolchain settings windows is less useful for rust:
http://mingw-w64.org/doku.php/download
For example, the http://mingw-w64.org/doku.php/download/win-builds version 1.5 contains an older GDB version that is time outing when trying to debug rust.
It would be nice to have an FAQ written helping people debug rust with CLion to find a working GDB more easily.

**Comment by Strangelovian** [comment]
See my previous comment

**Comment by Strangelovian** [comment]
I somewhat found a mingw distribution that works for me:
https://jmeubank.github.io/tdm-gcc/
With other things, it contains a recent GDB version 8.1 for the GNU x86_64 toolchain.

However, the "Download..." link provided in the CLion toolchain settings windows is less useful for rust:
http://mingw-w64.org/doku.php/download
For example, the http://mingw-w64.org/doku.php/download/win-builds version 1.5 contains an older GDB version that is time outing when trying to debug rust.
It would be nice to have an FAQ written helping people debug rust with CLion to find a working GDB more easily.

**Comment by Strangelovian** [comment]
I somewhat found a mingw distribution that works for me:
https://jmeubank.github.io/tdm-gcc/
With other things, it contains a recent GDB version 8.1 for the GNU x86_64 toolchain.

However, the "Download..." link provided in the CLion toolchain settings windows is less useful for rust:
http://mingw-w64.org/doku.php/download
For example, the http://mingw-w64.org/doku.php/download/win-builds version 1.5 contains an older GDB version that is time outing when trying to debug rust.
It would be nice to have an FAQ written helping people debug rust with CLion to find a working GDB more easily.

**Comment by ortem** [comment]
@Strangelovian you can use a link provided by CLion to download a recent MinGW version using [MingW-W64-builds](http://mingw-w64.org/doku.php/download/mingw-builds) instead of Win-Builds

> It would be nice to have an FAQ written helping people debug rust with CLion to find a working GDB more easily

You're right, I think our FAQ should contain info about specific MinGW versions 👍

**Comment by ortem** [comment]
Also, the corresponding issue in CLion: https://youtrack.jetbrains.com/issue/CPP-19651
