### ISSUE TITLE
Add postfix templates for Result/Option wrapping

### ISSUE THREAD

**Issue by panstromek** [intellij-rust/intellij-rust#5494]
When you write functions that return Result or Option, it's very common to write out full expression first and then wrap it in `Ok($expr)` and alike. It would be great to have postfix templates for these operations.

Specifically:
 - `$expr.ok<caret>` expand to `Ok($expr)`
 - `$expr.err<caret>` expand to `Err($expr)`
 - `$expr.some<caret>` expand to `Some($expr)`
 - ~~`$expr.none<caret>` expand to `None($expr)`~~

**Comment by Undin** [comment]
> $expr.none<caret> expand to None($expr)

Probably, you meant something else? `Option::None` doesn't have any fields

**Comment by panstromek** [comment]
@Undin Oh, right, I didn't think about it 😄 nevermind that case then.

**Comment by panstromek** [comment]
This seems like a pretty easy task, so I am gonna give it a shot. I wanted to start contrubuting at some point anyway ;)
