### ISSUE TITLE
Half minute to minute long freezes on versions > 0.2.120.2202-201 due to getOwnedDirectory

### ISSUE THREAD

**Issue by KronicDeth** [intellij-rust/intellij-rust#5499]
## Environment

* 0.2.123.3132-201
* rustc 1.45.0-nightly (769d12eec 2020-05-12)
* IntelliJ Ultimate Edition 2020.1.2
* macOS 10.15.4

## Problem description

In order to prevent 10s of seconds to almost a minute long pauses when making changes in https://github.com/lumen/lumen, I've had to downgrade from the latest release to 0.2.120.2202-201.

A lot of the longest pauses seem attributed to `getOwnedDirectory` from the `threadDumps-freeze` directories.

![Screen Shot 2020-06-04 at 7 49 44 AM](https://user-images.githubusercontent.com/298259/83758657-04f89200-a638-11ea-9294-051a00994ca4.png)

All the `threadDumps-freeze` directories that appear associated with the plugin are attached in this zip: [Archive.zip](https://github.com/intellij-rust/intellij-rust/files/4730110/Archive.zip)

## Steps to reproduce

1. `git clone git@github.com:lumen/lumen.git lumen/lumen`
2. `cd lumen/lumen`
3. `git checkout otp-runtime-selection`
3. Open the repository in the IDE.
4. Try to edit a file, such as adding an if inside a function in `liblumen_alloc/src/erts/process.rs`
5. Get a long freeze if plugin > 0.2.120.2202-201

**Comment by vlad20012** [comment]
Looks like it's caused by `chain method hints`, you can disable them in the settings `File | Settings | Editor | Inlay Hints | Rust | Chain method hints`

![image](https://user-images.githubusercontent.com/3221931/83760383-8cb4bf80-a67d-11ea-9eab-d5ddde9fc6a4.png)

**Comment by KronicDeth** [comment]
Reinstalling the latest version and turning off Show Hints for Chain method hints did help somewhat with adding `if` in `process.rs`, but I still got a freeze when typing `term.type_of` after accidentally typing `term.type-` in `YoungHeap`'s `Debug`:

[Archive 2.zip](https://github.com/intellij-rust/intellij-rust/files/4730286/Archive.2.zip)

**Comment by vlad20012** [comment]
Oh, looks like the problem code is executed regardless of Chain method hints status. 

But! It should not be executed if you disable "Show iterators as `impl Trait<...>`" option!
![image](https://user-images.githubusercontent.com/3221931/83762644-6f352500-a680-11ea-8879-1eed7d00d5de.png)

**Comment by KronicDeth** [comment]
Leaving "Show Hints" checked and unchecking "Show iterators as `impl Iterator<..>`" fixed the freeze in `Debug for YoungHeap` and adding the `if`s in `process.rs` also don't freeze. :heart:.  

I'll leave it up to you if you want to leave this issue open to fix the underlying performance issue or if you prefer to close since there is a work-around.

**Comment by vlad20012** [comment]
Let's leave it open, I'll fix it soon
