### ISSUE TITLE
Make changelog visible in IntelliJ update dialog

### ISSUE THREAD

**Issue by robinst** [intellij-rust/intellij-rust#550]
I saw that the website has a nice changelog, e.g. this: https://intellij-rust.github.io/2016/07/25/changelog-6.html

It would be cool if that showed up in IDEA when it detects that the plugin can be updated. Currently, the dialog is just blank (sorry, no screenshot, already updated 😄).

**Comment by matklad** [comment]
I don't think that we can show that change log exactly (jekyll uses markdown, plugin.xml wants html). Syncing changelogs between two locations is not very exciting, and I like the website UI more. 

So for now I've just added a link to the website: https://github.com/intellij-rust/intellij-rust/commit/4f25ec11919f8287da2590560057abfb3534bebb

Thanks for the report!
