### ISSUE TITLE
Unable to resolve async blocks

### ISSUE THREAD

**Issue by bh2smith** [intellij-rust/intellij-rust#5502]
## Environment

* **IntelliJ Rust plugin version:** 0.2.123.3132-201
* **Rust toolchain version:**  cargo 1.43.0 (2cbe9048e 2020-05-03)
* **IDE name and version:** IntelliJ IDEA 2020.1.2
* **Operating system:** macOS 10.15.4 Catalina

## Problem description

IDE cannot resolve blocks contained within `async move`. Unfortunately this non-resolution will render my favourite IDE unusable.

![Screen Shot 2020-06-04 at 4 08 20 PM](https://user-images.githubusercontent.com/11778116/83768282-dd78e800-a67e-11ea-8c95-523b230f5498.png)

## Steps to reproduce

This is part of https://github.com/gnosis/dex-services.

For one particular code block (i.e. the one in the screenshot), see precisely here

https://github.com/gnosis/dex-services/blob/dc70fff494b4069addc17cc567bb9c1ac49bbafb/driver/src/price_estimation/average_price_source.rs#L19-L45

**Comment by afetisov** [comment]
This seems to be fixed. Close?
