### ISSUE TITLE
Function chain formatting differs from rustfmt

### ISSUE THREAD

**Issue by NyxCode** [intellij-rust/intellij-rust#5509]
## Environment

* **IntelliJ Rust plugin version:** 0.2.123.3132-201
* **Rust toolchain version:**
```
nightly-x86_64-unknown-linux-gnu (default)
rustc 1.45.0-nightly (a74d1862d 2020-05-14)
```
* **IDE name and version:** 
```
CLion 2020.1.1
Build #CL-201.7223.86, built on April 29, 2020
```
* **Operating system:** arch/linux

## Problem description
This snippet below is formatted by rustfmt like this:
```rust
let user = sqlx::query!(
    "SELECT user_id, first_name, last_name from users WHERE user_id = $1",
    user_id
)
.execute(db)
.await?;
```
IntelliJ Rust (ctrl alt L) formats it like this:
```rust
let user = sqlx::query!(
    "SELECT user_id, first_name, last_name from users WHERE user_id = $1",
    user_id
)
    .execute(db)
    .await?;
```

## Steps to reproduce
Paste the snippet above into a rust project, run *Code -> Reformat Code* and compare it to the output of `cargo fmt`

**Comment by NyxCode** [comment]
Could *ctrl alt l* just run `cargo fmt`?

**Comment by vlad20012** [comment]
> Could ctrl alt l just run cargo fmt?

Yes. Just assign this shortcut to this action
![image](https://user-images.githubusercontent.com/3221931/83854701-c1795300-a71f-11ea-841b-50e490a49198.png)
(ctrl+shift+A "fmt")

**Comment by NyxCode** [comment]
> Yes. Just assign this shortcut to this action
Yeah that works, but then, I need another shortcut for every other filetype.

**Comment by NyxCode** [comment]
I haven't done a good job explaining what's the problem here, sorry.
The main issue I see is that IntelliJ automatically indents the code that way while typing.
```rust
my_function(
    argument1,
    argument2
)
```
When I now insert a newline, IntelliJ indents like this:
```rust
my_function(
    argument1,
    argument2
)
    .await
```

**Comment by NyxCode** [comment]
https://intellij-rust.github.io/2020/10/05/changelog-132.html 🥳
