### ISSUE TITLE
Stackoverflow error

### ISSUE THREAD

**Issue by SlNPacifist** [intellij-rust/intellij-rust#551]
I got this error when opened freshly cloned https://github.com/emoon/rust_minifb commit 09ee02c09c6ac671d49a7ac5a0f6c1d68bfdb447. Callstack is in [gist](https://gist.github.com/SlNPacifist/67145055f84747c8e3c4a08c4a36dd66) since it is very large. Plugin version was 0.0.1.843

**Comment by matklad** [comment]
What file did you opened? Have you attached standard library sources? 

I can't reproduce the issue right away, but it's very likely that our type inference code sometimes does not terminate :(

**Comment by matklad** [comment]
Hm, quite probably it is `windows/mod.rs`.

**Comment by matklad** [comment]
Test case:

```
fn foo(S: S){
    let x = S;
    S.<caret>foo();
}
```

**Comment by SlNPacifist** [comment]
I had 2 windows open - one with big ProDBG project (which is not Cargo project itself, but contains several of them inside), one simple playground project. Then I cloned rust_minifb & opened it and got error message. Could not reproduce later, just closed everything and opened rust_minifb - everything got OK.
