### ISSUE TITLE
Improve user visible text of ConvertToTyWithDerefsRefsFix

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#5519]
## Environment

* **IntelliJ Rust plugin version:** 0.2.124.3142-201-nightly
* **Rust toolchain version:** 1.45.0-nightly (a74d1862d 2020-05-14) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.2 EAP Ultimate Edition (IU-202.5103.13)
* **Operating system:** macOS 10.13.6

## Problem description
Text of the quick fix is too long and maybe confusing (especially for inexperienced users).
It seems it can be significantly simplified since the dereference operator is just `*` in text representation

<img width="838" alt="Screen Shot 2020-06-06 at 20 38 58" src="https://user-images.githubusercontent.com/2539310/83950823-36d74780-a836-11ea-87cc-10434dda5258.png">

## Steps to reproduce
```rust
const INITIAL_TEXT: &[u8] = b"Hello, World!";

#[no_mangle]
pub extern "C" fn _start() -> ! {
    let vga_buffer = 0xb8000 as *mut u8;

    unsafe {
        for (index, value) in INITIAL_TEXT.iter().enumerate() {
            *vga_buffer.offset(index as isize * 2) = value
        }
    }

    loop {}
}
```

**Comment by Kobzol** [comment]
What should be the displayed text? The specific operators that will be used for the conversion like `Convert to u8 using ***/&mut & &mut` or just a generic text like `Convert to u8 by applying * or &/&mut`?

**Comment by Undin** [comment]
> The specific operators that will be used for the conversion like Convert to u8 using ***/&mut & &mut or just a generic text like Convert to u8 by applying * or &/&mut?

The first thing I want to know when I apply some quick fix is what it will do. So yes, it would be great if the quick fix shows a specific operator.

Also, probably, `Convert to %type_name% using` or `Convert to %type_name% by applying` is redundant here. It complicates the message, makes it too long that looks not great in UI and adds only a bit additional info because it duplicates error message from the annotation.
Also, if a type is quite complex, its text representation may be huge.
Maybe just `Add %specific_operator%` or `Apply %specific_operator%`? What do you think?
Probably, I'm wrong and info about type is really needed here then we can provide something like `Convert to %type_name% with %specific_operator%`

**Comment by Kobzol** [comment]
I think that the `Convert to %type_name%` part is still useful. I often don't even read the error annotation and try Alt+Enter first to see what fixes are available to invoke them right away. `Apply *` kind of says that you need to convert something, but it doesn't tell you the target type right away, which I consider useful. `Convert to %type_name%` immediately tells you that the fix will do a type conversion (high-level overview) and if we add the specific operators to the fix text, it also tells the user what exactly will the fix do (low-level overview).

**Comment by Undin** [comment]
Ok, let's start with specific operator instead of `dereferences and/or references`
