### ISSUE TITLE
Make "Expand module" refactoring available in "Refactor this" popup

### ISSUE THREAD

**Issue by jajakobyly** [intellij-rust/intellij-rust#553]
Explanation: https://gfycat.com/ApprehensiveUntimelyBream

**Comment by matklad** [comment]
How did you get that green rectangle with the action and a shortcut?

**Comment by jajakobyly** [comment]
Presentation assist plugin. Folks from uni showed me it some time ago :P

**Comment by matklad** [comment]
closed by https://github.com/intellij-rust/intellij-rust/commit/6487a51d238ebb1473b81e8f0d75ea3861b5abbb
