### ISSUE TITLE
Broken navigation to some items in 2020.2

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#5537]
- [ ] Navigation from module declaration to a file
```rust
mod foo/*caret*/; // Ctrl + B
```
In 2020.2 Ctrl + B on a module declaration invokes "Find Usages" instead of navigating to the file. But our find usages doesn't work in this case =/

- [ ] Navigation from extern crate declaration to a crate root file
```rust
extern crate foo/*caret*/; // Ctrl + B
```
In 2020.2 Ctrl + B on an extern crate declaration invokes "Find Usages" instead of navigating to the file. But our find usages doesn't work in this case =/

- [x] Navigation to an associated type from its binding #5538
```rust
type T = dyn Iterator<Item/*caret*/=i32>; // Ctrl + B
```
In 2020.2 it does nothing

**Comment by vlad20012** [comment]
There is a discussable question: maybe we really want to do "Find Usages" by Ctrl +B (Ctrl + Click) on module declarations and extern crates. In this case, we could provide navigation to files by "Go To Implementation" (Ctrl + Alt + B) action

**Comment by Kobzol** [comment]
My 2 cents: I personally use Ctrl+click on mod items for navigation, it's a quick way of moving between "neighbour" files. I expect Find usages to be invoked only if there is no target element to navigate to, for example in generic parameters: `struct S<T/*caret*/>(T);`. If there's something to navigate to, I would prefer to keep the old behaviour.

**Comment by Undin** [comment]
@vlad20012 everything works with latest 2020.2 EAP again
