### ISSUE TITLE
Cmd+Mouse over on method doesn't show signature

### ISSUE THREAD

**Issue by e-oz** [intellij-rust/intellij-rust#555]
Currently "standalone" functions signatures are being displayed just fine, but for methods it only displays `Rust Impl Method Member Element Impl "%method_name%" [%filename.rs%]`.

mac OS 10.12, 
Rust plugin 0.0.1.843, 
IntelliJ IDEA 2016.2, 
Build #IU-162.1121.32
JRE: 1.8.0_76-release-b216 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by matklad** [comment]
Fixed in https://github.com/intellij-rust/intellij-rust/commit/0a32e0569d0182272540cbdd9fe508e4e9fd0900 :)
