### ISSUE TITLE
type inference for return type of HashMap entry API after clone() still resolves to borrow

### ISSUE THREAD

**Issue by haraldmaida** [intellij-rust/intellij-rust#5554]
## Problem description

type inference shows type mismatch error when using the `entry` API of a `std::collections::HashMap` or `hashbrown::HashMap` and clone() the returned borrowed value. Adding an explicit type annotation does not help.

## Steps to reproduce

```rust
use std::collections::HashMap;
// use hashbrown::HashMap;  //same problem

struct Foo {
    bars: HashMap<u64, String>,
}

impl Foo {
    fn get_or_insert(&mut self, id: u64) -> String {
        self.bars.entry(id).or_insert(String::new()).clone()
    }

    fn get_or_insert_with(&mut self, id: u64) -> String {
        self.bars.entry(id).or_insert_with(String::new).clone()
    }

    fn with_type_annotation(&mut self, id: u64) -> String {
        let result: String = self.bars.entry(id).or_insert(String::new()).clone();
        result
    }
}
```
for all 3 methods the following error is given by the Rust plugin:

mismatched types [E0308] expected `String`, found `&mut String` 
 Inspection info:The Rust type checker.

## Environment

* **IntelliJ Rust plugin version: 0.2.123.3132-201**
* **Rust toolchain version: stable 1.44.0**
* **IDE name and version: IntelliJ IDEA Ultimate 2020.1.2**
* **Operating system: Windows 10 Pro 2004**

**Comment by Kobzol** [comment]
Do you still experience the problem? I can't reproduce it on latest nightly.

**Comment by haraldmaida** [comment]
Yes, does not occure on current stable version either. Seams to be fixed. Thanks a lot for your efforts.
