### ISSUE TITLE
Auto Completion

### ISSUE THREAD

**Issue by John0x** [intellij-rust/intellij-rust#556]
Hey, I'm not quite sure on how to make the auto completion working.
I've installed rust through rustup. The rust source is downloaded to and the path set.

I tried to run "cargo metadata" to install the standard library source (read it on the web), but it still hangs after 2 hours...

Any hints? :)

**Comment by matklad** [comment]
Hi! You should not call `cargo metadata` yourself, the plugin will do this automatically :) 

Have you tried following the user guide: https://intellij-rust.github.io/docs/quick-start.html ?

What exactly hags for 2 hours? Is it `cargo metadata` command?

Hm, I have an idea what's going on...Where exactly did you read about cargo metadata and library sources?

**Comment by John0x** [comment]
Ah, it works now. thanks :)
I didn't follow the guide since there is a project creation wizard for rust within intellij idea.

**Comment by matklad** [comment]
We don't support project creation from within the IDE yet, so you'll have to `cargo new my_project` from the command line and then import the resulting folder into the IDE.

**Comment by John0x** [comment]
Hey, the std library files are loaded now, but I still don't get auto completion for things like "use std::collections::HashMap;"

**Comment by matklad** [comment]
Hm, it's hard to say what exactly may be wrong... I think we shold add a trouble shooting page. Some things to check

* the project should have a valid Cargo.toml in the root directory 
* Rust targets should be setup correctly. That is, if you define a main function in your `main.rs` then `cargo run` should run this file. 
* In the Rust settings (`Settings > Language & Frameworks > Rust`) toolchain should be specified
* In the Rust settings the path to standard library should be specified
* In the project view (<kbd>Alt+1</kbd>), in the external libraries you should see your dependencies and stdlib.

**Comment by John0x** [comment]
Well, I have everything checked that you mentioned.
![image](https://cloud.githubusercontent.com/assets/5455173/17154825/eacbf400-5382-11e6-8e35-b0dca81d2601.png)
![image](https://cloud.githubusercontent.com/assets/5455173/17154853/05b3a56a-5383-11e6-8f59-9887b2d96911.png)

But still no auto completion.
![image](https://cloud.githubusercontent.com/assets/5455173/17154863/132cc474-5383-11e6-86eb-bea9d3c7bcbc.png)

**Comment by matklad** [comment]
That's strange. Perhaps it's windows specific. Will take a close look tomorrow when I'll be near a windows VM.

For the time being the only advice I can give is to try to delete the project, recreate it and import again :( 

Also you can try not to setup path to standard library manually. Just import the project, and open some Rust file. A panel should appear which would suggest to `Download` or `Attach` standard library. Try clicking `Download`, it should download a zip archive with the stdlib instead of the unpacked sources.

**Comment by matklad** [comment]
One more thing: try running "refresh cargo project" action. That is, <kbd>Ctrl+Shift+A</kbd> "refresh cargo project" <kbd>Enter</kbd>. Does it show an error or a success message?

**Comment by John0x** [comment]
Tried it with the zip file too, same result.
Refresh cargo project doesn't show any errors. Only "Project 'rtest' successfully updated!"

**Comment by matklad** [comment]
Hey, that was a terrible bug! Thanks a lot for the report!

**Comment by matklad** [comment]
Updates for alpha and nightly channels will be up in about five minutes
