### ISSUE TITLE
Contradictory toolchain detection for debugger

### ISSUE THREAD

**Issue by stevefan1999-personal** [intellij-rust/intellij-rust#5560]
## Environment

* **IntelliJ Rust plugin version:** 0.2.123.3132-193
* **Rust toolchain version:** 1.46.0-nightly
* **IDE name and version:** CLion
* **Operating system:** Windows 10 version 2004

## Problem description
I ran debug on Windows with GNU toolchains but it shows I'm using MSVC toolchain despite the binaries generated are indeed MinGW artifacts.

## Steps to reproduce
1. `rustup override set nightly-x86_64-pc-windows-gnu`
2. Create a build profile "Run" with command "run"
3. Start debug on build profile "Run"
4. Expect failure "MSVC toolchain is not supported. Please GNU toolchain."
5. Double check if the binary produced is very huge which indicates GNU toolchain build

Don't know if huge file sizes mattered here (my GNU toolchain debug build costs 80MB for some reason)

**Comment by Undin** [comment]
Thanks for the report
Currently, the plugin doesn't support `rustup override` so I suppose it's the cause of your problem
