### ISSUE TITLE
`Extract enum variant` intention incorrectly handles some usages

### ISSUE THREAD

**Issue by mchernyavsky** [intellij-rust/intellij-rust#5565]
## Environment

* **IntelliJ Rust plugin version:** 0.2.123.SNAPSHOT-201-dev
* **Rust toolchain version:** 1.45.0-nightly (a74d1862d 2020-05-14) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.1.1 Ultimate Edition (IU-201.7223.91)
* **Operating system:** macOS 10.15.5

## Problem description

**Before**:
```rust
enum Foo { Bar/*caret*/(i32) }

fn id<T>(x: T) -> T { x }

fn main() {
    id(Foo::Bar)(42);
}
```

**Actual**:
```rust
struct Bar(pub i32);

enum Foo { Bar(Bar) }

fn id<T>(x: T) -> T { x }

fn main() {
    id(Bar(Foo::Bar))(42);
}
```

**Expected (???)**:
```rust
struct Bar(pub i32);

enum Foo { Bar(Bar) }

fn id<T>(x: T) -> T { x }

fn main() {
    id(|x| Foo::Bar(Bar(x)))(42);
}
```

**Comment by Kobzol** [comment]
That's a pretty cool idea with the lambda! I'll send a PR with a fix.
