### ISSUE TITLE
Show error annotation if repr attribute is placed on an unsupported item

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#5566]
## Environment

* **IntelliJ Rust plugin version:** 0.2.125.3158-202-nightly
* **Rust toolchain version:** 1.46.0-nightly (0262de554 2020-06-07) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.2 EAP Ultimate Edition (IU-202.5428.22)
* **Operating system:** macOS 10.13.6

## Problem description
Currently, you can place `repr` attribute on each rust item the plugin doesn't produce [E0517](https://doc.rust-lang.org/error-index.html#E0517) error as expected.
It would be great to show the corresponding error in the editor when necessary and add `remove` quick fix. As an example, see `org.rust.ide.annotator.RsErrorAnnotator#checkInlineAttr`

## Steps to reproduce
```rust
#[repr(u8)]
fn foo() {}

#[repr(C)]
trait Foo {}
```

**Comment by Stzx** [comment]
It seems that `E0566` can be implemented together.

**Comment by Undin** [comment]
@Stzx Probably, but it's not necessary

**Comment by Stzx** [comment]
@Undin 
I should be done (except adding tests.

It looks very easy to implement E0566 in the current code, should I implement it?
