### ISSUE TITLE
Annotation level of lint inspections doesn't respect lint level of lint check attributes

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#5567]
## Environment

* **IntelliJ Rust plugin version:** 0.2.125.3158-202-nightly
* **Rust toolchain version:** 1.46.0-nightly (0262de554 2020-06-07) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.2 EAP Ultimate Edition (IU-202.5428.22)
* **Operating system:** macOS 10.13.6

## Problem description
The plugin provides some "Lint" inspections. For example, "Trait naming convention", "Liveness analysis", etc. Such inspections are related to compiler inspections and error level of such inspections is controlled by [lint check attributes](https://doc.rust-lang.org/reference/attributes/diagnostics.html#lint-check-attributes).
You can mark some lint check as compiler error with `deny` or `forbid` attributes. But plugin inspections don't take them into account and always use warning level.

![image](https://user-images.githubusercontent.com/2539310/84591169-fdf62e80-ae44-11ea-9e11-6eb31faf8b98.png)

## Steps to reproduce
```rust
#[error(non_camel_case_types)]

trait foo {}
```

**Comment by Undin** [comment]
`org.rust.ide.inspections.RsLintInspection` is base class for such inspection in the plugin

**Comment by Stzx** [comment]
@Undin Can you assign it to me? I want to finish it.
