### ISSUE TITLE
Support for the new or_pattern

### ISSUE THREAD

**Issue by quangIO** [intellij-rust/intellij-rust#5581]
This is an experimental feature but I think Intellij Rust should support it. 
Tracking issue for RFC 2535, 2530, 2175: https://github.com/rust-lang/rust/issues/54883

Example:

```rust
#![feature(or_patterns)]
fn main() {
   let a = Some(1);
   match a {
     Some(1 | 2) => panic!(), // Syntax error according to Intellij Rust
     _ => panic!(),
   }
}
```

**Comment by quangIO** [comment]
Oops, duplicate, there's already open issue for this.

**Comment by Undin** [comment]
Duplicate of #5032
