### ISSUE TITLE
Inlay type hints are not shown in CLion

### ISSUE THREAD

**Issue by artemmukhin** [intellij-rust/intellij-rust#5600]
The issue is related to the ticket from Zendesk Support.

## Environment

* **IntelliJ Rust plugin version:** 0.2.124.3162-202
* **Rust toolchain version:** N/A
* **IDE name and version:** N/A
* **Operating system:** macOS 10.8+

## Problem description
Rust inlay type hints are enabled in `Preferences | Editor | Inlay Hints | Rust | Type hints` settings but are not shown in the editor.

**Comment by ortem** [comment]
It would be helpful to know the exact IDE version (can be found in Help menu)

**Comment by neonaot** [comment]
Can't reproduce.
