### ISSUE TITLE
Vec::dedup() doesn't show up in autocompletion

### ISSUE THREAD

**Issue by AndreKR** [intellij-rust/intellij-rust#5615]
## Environment

* **IntelliJ Rust plugin version:** 0.2.123.3132-193
* **Rust toolchain version:** 1.45.0
* **IDE name and version:** CLion 2019.3.5
* **Operating system:** Win 7

## Problem description
The function `dedup()` doesn't show up in the method autocompletion of a Vec:

![image](https://user-images.githubusercontent.com/1188538/85181216-a2cd9d00-b285-11ea-909e-de6da2b03b49.png)

However, after writing it completely, I can navigate to the function by ctrl-clicking it.

In case that is relevant, I have the new macro engine enabled:

![image](https://user-images.githubusercontent.com/1188538/85181328-efb17380-b285-11ea-9a2d-779ff7066e31.png)

**Comment by dima74** [comment]
@AndreKR could you please check if the issue still persists. I can't reproduce using:

* **IntelliJ Rust plugin version:** 0.3.139.3573-203-nightly
* **Rust toolchain version:** 1.48.0 (7eac88abb 2020-11-16) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.3 (CL-203.5981.166)
* **Operating system:** Linux 5.9.14-arch1-1
* **Macro expansion engine:** new
* **Name resolution engine:** old

![image](https://user-images.githubusercontent.com/6505554/103301793-2a554f00-4a13-11eb-855d-390b5c3517a1.png)

**Comment by AndreKR** [comment]
With Plugin 0.3.139.3573-202-nightly I cannot reproduce it anymore either.
