### ISSUE TITLE
Dependency on openid crate causes very long indexing

### ISSUE THREAD

**Issue by brianhv** [intellij-rust/intellij-rust#5621]
## Environment

* **IntelliJ Rust plugin version:** 0.2.124.3162-201
* **Rust toolchain version:** stable-x86_64-apple-darwin (default), rustc 1.43.1 (8d69840ab 2020-05-04)
* **IDE name and version:** WebStorm 2020.1.2
Build #WS-201.7846.79, built on June 2, 2020
Runtime version: 11.0.7+10-b765.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Non-Bundled Plugins: DBN, IdeaVIM, ru.adelf.idea.dotenv, reasonml, org.toml.lang, org.rust.lang
* **Operating system:** macOS 10.14.6

## Problem description

After performing the steps to reproduce, once the IDE picks up the new dependency it will start indexing. It will take a very long time, and may never complete.

While indexing, background tasks window very quickly and repeatedly flashes tasks like the following:

![image](https://user-images.githubusercontent.com/248645/85214733-3910ca00-b33d-11ea-8bcd-56853a3c86eb.png)

![image](https://user-images.githubusercontent.com/248645/85214734-4332c880-b33d-11ea-8683-5656846277f3.png)

I've found that if `openid` is the only dependency it will eventually complete, but after adding a few `actix` related dependencies, it does not complete in a reasonable amount of time (within tens of minutes).

If I `rm -rf ~/.cargo/registry/src/github.com-1ecc6299db9ec823/openid-0.4.0` while the IDE is stuck indexing, the indexing completes very quickly.

## Steps to reproduce

1. Use `cargo new` to create a new project
2. Open the new project in the IDE
3. Add `openid = "0.4.0"` under `[dependencies]` in `Cargo.toml` and save it

**Comment by vlad20012** [comment]
Hello! Thanks for the report!

I've reproduced it. I'll try to investigate it soon.

**Comment by vlad20012** [comment]
The issue is fixed in the nightly plugin. You can try it now (see [instructions](https://intellij-rust.github.io/install.html))
