### ISSUE TITLE
Rust plugin says a variable is unused but it's used by a home made macro

### ISSUE THREAD

**Issue by ant-druha** [intellij-rust/intellij-rust#5627]
Repost from https://youtrack.jetbrains.com/issue/IDEA-244129

* I'm using [Coding Game](https://www.codingame.com/ide/puzzle/temperatures) to practise Rust
* Rust plugin is version **0.2.124.3162-201**
* The sample code uses a macro (see included file) to ease input parsing
* In the attached sample the Rust analyzer says that "**i**", declared line 20, is unused whereas it's used by the macro line 21. See screenshot:

![](Capture d'écran 2020-06-21 16.55.47.png)

IU-201.7846.76, JRE 11.0.7+10-b765.53x64 JetBrains s.r.o., OS Mac OS X(x86_64) v10.15.5, screens 1920x1200; Retina

![image](https://user-images.githubusercontent.com/3117044/85284402-cff19980-b497-11ea-8ad5-654e6ca54a9f.png)

[temperatures.rs.zip](https://github.com/intellij-rust/intellij-rust/files/4813010/temperatures.rs.zip)

**Comment by Kobzol** [comment]
Please try the experimental macro engine, it should solve your issue: https://github.com/intellij-rust/intellij-rust/issues/3628.

**Comment by Farzy** [comment]
Hi, it works as expected, thanks! As it says "experimental" I did not choose this option the first time I installed the Rust plugin.

**Comment by Shoeboxam** [comment]
I am still experiencing an issue with this while using the new macro engine. Variables used in macros defined within the current scope are not detected as "used". 

- Rust Intellij plugin version 0.3.129.3308-202
- Intellij 2020.2
- "Expand Declarative Macros:" option set to "Use new engine"

<img width="1680" alt="Screen Shot 2020-09-02 at 2 53 35 PM" src="https://user-images.githubusercontent.com/3630029/92024455-3a427800-ed2c-11ea-9031-b6d5ecbc4907.png">


Thanks for the great plugin!

**Comment by mili-l** [comment]
see https://github.com/intellij-rust/intellij-rust/pull/9729
