### ISSUE TITLE
Why "Get rid of options to disable the Test Tool window" on change log #125 ?

### ISSUE THREAD

**Issue by neocoin** [intellij-rust/intellij-rust#5676]
## Environment

* **IntelliJ Rust plugin version: #125**
* **Rust toolchain version: stable**
* **IDE name and version: clion, intelliJ**
* **Operating system: Linux**

## Problem description

I'm using "Disable the Test tool window" option for checking all warning message from toolchain.

But, after [changelog #125](https://intellij-rust.github.io/2020/06/29/changelog-125.html), this option removed. 

I cann't find reason for this decision on issue tracking system. Could anybody show in here?

**Comment by RazrFalcon** [comment]
Same here. How to revert old behevior? The new panel is kinda broken (it ignores segfaults).

**Comment by mchernyavsky** [comment]
> I cann't find reason for this decision on issue tracking system. Could anybody show in here?

It's a legacy implementation, that makes it difficult to develop new features, so we decided to drop it and fix Test Tool window problems if any.

> I'm using "Disable the Test tool window" option for checking all warning message from toolchain.

@neocoin Try to enable new Build Tool window (`Actions > Registry... > org.rust.cargo.build.tool.window`). With this option enabled, all compilation messages will be shown on a separate tab.

@RazrFalcon Can you please create a separate issue with steps to reproduce?

**Comment by RazrFalcon** [comment]
@mchernyavsky Is there a way to simply log it into output panel, just like during building process?

**Comment by mchernyavsky** [comment]
@RazrFalcon You can pass the `--nocapture` option to the test binary. For example:
```bash
cargo test -- --nocapture
```

**Comment by RazrFalcon** [comment]
@mchernyavsky Thanks! That's exactly why I wanted. And I had to use console for the past few days...

**Comment by ArekPiekarz** [comment]
Just adding to discussion that for me the default test window is unusable, because it doesn't show stderr, so in failing tests there is no reason of failure and no stacktrace. Thankfully the alternative solution from https://github.com/intellij-rust/intellij-rust/issues/5676#issuecomment-653253642 is still working.

**Comment by mchernyavsky** [comment]
@ArekPiekarz Can you show an example when it doesn't work? Does it work for simple cases?

![image](https://user-images.githubusercontent.com/6079006/86541838-d7458800-bf18-11ea-8383-bbe63a40df8a.png)

![image](https://user-images.githubusercontent.com/6079006/86541813-9a799100-bf18-11ea-9ebb-a536cc4a6649.png)

**Comment by ArekPiekarz** [comment]
@mchernyavsky your example works correctly for me, so I'll get back when I find a minimal reproduction of my case.
