### ISSUE TITLE
Unrecognized nightly clippy warnings

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#5685]
## Environment

* **IntelliJ Rust plugin version:** 0.2.125.3191-201
* **Rust toolchain version:** 1.46.0-nightly (2f517ce6f 2020-06-28)
* **IDE name and version:** CLion 2020.1
* **Operating system:** Windows 10

## Problem description

Running given version of clippy as external linter results in `No suspicious code found. 343 files processed in ...`, while there if fact are warning when clippy is manually run.

## Steps to reproduce

Install given clippy version and run on a project with lint warnings.

**Comment by vlad20012** [comment]
Most likely it's related to #5682. external linter inspection is completely broken in 0.2.125 release of the plugin

**Comment by vlad20012** [comment]
Issue #5682 is fixed in the nightly plugin. @krojew you can try it now (see [instructions](https://intellij-rust.github.io/install.html)) and check whether your issue is fixed too
