### ISSUE TITLE
Smart autocompletion not working when nesting several `for` loops.

### ISSUE THREAD

**Issue by joslopgar** [intellij-rust/intellij-rust#5686]
## Environment

* **IntelliJ Rust plugin version: 0.2.125.3191-201**
* **Rust toolchain version: 1.44.1**
* **IDE name and version: CLion 2020.1.2**
* **Operating system: Windows 10**

## Problem description
Smart autocompletion not working when nesting several `for` loops. See below to reproduce issue.

## Steps to reproduce

1.) Create a new fresh project in CLion:
`cargo new <project-name>`

2.) Create a function which contains several nested for loops:

```rust
fn process(string: String) -> HashMap<String, Vec<String>> {
    for line in string.lines() {
        for sentence in line.split_terminator('.') {
            for word in sentence.trim().split_whitespace() {
                if word.chars().nth(0).unwrap().is_uppercase() {
                    todo!()
                }
            }
        }
    }
    todo!()
}
```

3.) Realize that **type hinting** and smart **code completion/suggestion** works only inside the first for-loop. For the second and third for-loops, they won't work (See images below).
![first-for-loop](https://user-images.githubusercontent.com/11969459/86281117-50717200-bbdd-11ea-9a34-81b5085ebb07.png)
![second-for-loop](https://user-images.githubusercontent.com/11969459/86294060-1d86a880-bbf4-11ea-8228-3496bab986f7.png)
![third-for-loop](https://user-images.githubusercontent.com/11969459/86294139-460ea280-bbf4-11ea-9e12-6e431c580e03.png)

**Comment by Undin** [comment]
@joslopgar thanks for the report!
Actually, it's not related to nested loops. Reason of completion absence is fail of type inference for `line.split_terminator('.')` expression. Try to enable new macro expansion engine (see #3628 for details). It should solve your issue.

**Comment by joslopgar** [comment]
Thank you for your answer @Undin ! I'm glad this is a known issue, I imagine it's been researched by now. Should I close the issue then?

**Comment by Undin** [comment]
> I tried enabling the new macro expansion engine and it worked!

Glad to hear it!

> Should I close the issue then?

No. We will fix all issues that are fixed by new macro expansion engine (like this one) after it becomes default option (I hope quite soon)
