### ISSUE TITLE
`for<'lifetime>` formatting issue

### ISSUE THREAD

**Issue by grossws** [intellij-rust/intellij-rust#569]
Currently (rust plugin v0.0.1.866-nightly) thing like `where F: for<'b> Fn(...)` are reformatted to `where F: for < 'b > Fn(...)` which is a bit ugly and inconsistent with type parameters formatting in other cases (in `impl`, `struct`/`trait`, `fn` they are condensed).

Would you change default formatting for this case and add an option in `Code style -> Rust` if it's really needed for someone.

**Comment by grossws** [comment]
Partially resolved in `0.0.1.879-nightly`: formatting is good in `where F: for<'b> Fn(...)` clauses but still with same spaces in references in structs:

```rust
struct Client<'a> {
    auth_fn: &'a for < 'b > Fn(&'b str, &'b str) -> (Cow<'a, str>, Cow<'a, str>, Cow<'a, str>)
}
```

**Comment by matklad** [comment]
@jajakobyly I am reviewing grammar in this area, this will likely get fixed as a collateral damage.

**Comment by grossws** [comment]
@matklad, if you ping back this issue after grammar changes I'll test plugin nightly build (which I'm currently on) and report the result.

**Comment by matklad** [comment]
@grossws I've kicked a new nightly build, should be there in about 15 minutes.

**Comment by matklad** [comment]
Alpha is there

**Comment by grossws** [comment]
@matklad, :+1:, works as intended. Thank you.

**Comment by matklad** [comment]
Thanks for the great report!
