### ISSUE TITLE
No values are shown for primitive types while debugging with MSVC

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#5694]
## Environment

* **IntelliJ Rust plugin version:** 0.2.126.SNAPSHOT-202-dev
* **Rust toolchain version:** 1.40.0 (73528e339 2019-12-16) i686-pc-windows-msvc
* **IDE name and version:** CLion 2020.2 EAP (CL-202.5792.50)
* **Operating system:** Windows 10 10.0

## Problem description

I see no values e.g. for integer variables

<img width="642" alt="Screen Shot 2020-07-03 at 20 30 17" src="https://user-images.githubusercontent.com/2500320/86489158-20a4a480-bd6c-11ea-8b81-a5bcfe7edca6.png">

Should I update some dependency perhaps? The plugin was rebuild from master today with the latest changes.

Build toolchain:

<img width="762" alt="Screen Shot 2020-07-03 at 20 29 42" src="https://user-images.githubusercontent.com/2500320/86489157-200c0e00-bd6c-11ea-949a-fce538987f46.png">

**Comment by ortem** [comment]
@lancelote Is your Windows 32-bit or 64-bit?
I've reproduced this while using `Visual Studio x86` + `i686-pc-windows-msvc` on my 64-bit Windows. However, debugging works fine when I use `Visual Studio amd64` + `x86_64-pc-windows-msvc`.

**Comment by lancelote** [comment]
I had 64-bit Windows.
Switching to `stable-x86_64-pc-windows-msvc` resolves the problem, thank you 🙏

**Comment by ta32** [comment]
do we support debugging on the mvc toolchain now? didn't know this

**Comment by Undin** [comment]
@ta32 Yep. The initial version of the corresponding was enabled in #5535. Note, since it requires changes in debugger itself, it works since 2020.2 EAPs only.
You can track the progress in #5632
