### ISSUE TITLE
Formatter forces a comma after the last field of a struct

### ISSUE THREAD

**Issue by LoganDark** [intellij-rust/intellij-rust#5696]
Right now, whenever reformatting a struct, a trailing comma is always forced after the last field. I don't like this convention. There is no setting in the Code Style section to change this.

So whenever I reformat something like this:
![image](https://user-images.githubusercontent.com/4723091/86509475-1fd83680-bd9d-11ea-95c5-43ca75e2c50a.png)

The Rust plugin insists on placing a comma at the end:
![image](https://user-images.githubusercontent.com/4723091/86509487-28c90800-bd9d-11ea-8231-3e283c78c8d0.png)

even though it looks exceedingly ugly to me, and I only like using commas to separate values.

I would like the setting to turn this off, as it is my code, and I don't want a comma there. It's unnecessary and ugly.

**Comment by LoganDark** [comment]
![image](https://user-images.githubusercontent.com/4723091/86509570-ce7c7700-bd9d-11ea-83b4-742823b0d6c2.png)
This also occurs when creating an instance of a struct. And it's also probably repeated elsewhere.

**Comment by Kobzol** [comment]
This actually mirrors the behaviour of `rustfmt`. Although I suppose that there could be an option in the formatter settings to turn it off.

**Comment by LoganDark** [comment]
I don't mind this being the default if I have the ability to change it.

**Comment by vlad20012** [comment]
There is an option in `Settings | Editor | Code Style | Rust | Wrapping and Braces | Keep when reformatting | Punctuation`
![image](https://user-images.githubusercontent.com/3221931/86542527-0959e880-bf1f-11ea-950c-cf43649b7281.png)

**Comment by LoganDark** [comment]
That's for _all_ punctuation, including commas within `match`, semicolons and so on. I'd like more granular control over this.
