### ISSUE TITLE
futures:poll! doesn't hint return type

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#5714]
## Environment

* **IntelliJ Rust plugin version:** 0.2.127.3210-201-nightly
* **Rust toolchain version:** rustup 1.22.1 (2020-07-08)
* **IDE name and version:** clion 2020.1.2
* **Operating system:** Arch Linux

## Problem description
`futures::poll!` return value doesn't hint type

## Steps to reproduce

```rust
let v = futures::poll!(self.poll_handle(cx));
```

the v doesn't hint type

**Comment by Undin** [comment]
@Sherlock-Holo Could you provide more complete code example?
It's rather hard to determine what's wrong here without any context

**Comment by Sherlock-Holo** [comment]
@Undin 

sorry for the late reply

the complex example like

```rust
async fn doit() -> Poll<usize> {
    let fut = dd();
    
    futures::pin_mut!(fut);
    
    let result = futures::poll!(fut);

    result
}

async fn dd() -> usize {
    10
}
```

we can see the `let result` doesn't have type hint

![image](https://user-images.githubusercontent.com/10096425/87962287-8a051100-cae9-11ea-9639-e55de51f96f5.png)

**Comment by Undin** [comment]
@vlad20012 Could you check it, please?

**Comment by vlad20012** [comment]
There are multiple bugs here:
1. We don't support `$crate` from transitive dependencies. A workaround - add `futures-util = "0.3.5"` and `pin-utils = "0.1.0"` to direct dependencies
2. We don't support associated type bounds in our type inference that are used in the standard library
```
impl<P> Future for Pin<P>
where
    P: Unpin + ops::DerefMut<Target: Future>,
```

**Comment by vlad20012** [comment]
Should be fixed with these PRs: #5796, #5808 and #5809

![image](https://user-images.githubusercontent.com/3221931/88547552-9841b880-d026-11ea-9049-666197069577.png)

**Comment by vlad20012** [comment]
Now fixed in master

**Comment by Sherlock-Holo** [comment]
```rust
fn main() {
    let n = futures::executor::block_on(dd());

    println!("{}", n);
}

async fn dd() -> usize {
    let fut = ddd();

    futures::pin_mut!(fut);

    let x = futures::poll!(fut);

    futures::future::poll_fn(|_| {
        x
    }).await
}

async fn ddd() -> usize {
    10
}
```

![image](https://user-images.githubusercontent.com/10096425/88748525-d0aad900-d183-11ea-9ce0-7c0a9b3a77fe.png)

that's strange, it report Poll<?> not Poll<usize>

@vlad20012 could you see what problem happened?

**Comment by Undin** [comment]
@Sherlock-Holo I suppose you don't use the latest nightly (https://plugins.jetbrains.com/plugin/8182-rust/versions/nightly/93138) so you see the intermediate result with not all necessary fixes

**Comment by Sherlock-Holo** [comment]
Oh you are right, I don't have the latest plugin, I updated the plugin this morning and I thought it's the latest, and I am wrong.
now update to 0.3.128.3252-201-nightly, problem fixed, thanks :)
