### ISSUE TITLE
Support `Try` trait while type inference of `?` operator

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#5731]
## Environment

* **IntelliJ Rust plugin version:** 0.3.127.3214-201-nightly
* **Rust toolchain version:** rustup 1.22.1 (2020-07-08)
* **IDE name and version:** clion
* **Operating system:** Arch Linux

## Problem description
Poll<Result<T, E>> implement `Try` trait but when use `?`, the return value doesn't have type hint.

## Steps to reproduce

```rust
let x = poll_sth(cx)?;
```

x doesn't have type hint

**Comment by Undin** [comment]
@Sherlock-Holo could you provide a more complete code example?

**Comment by Sherlock-Holo** [comment]
```rust
fn ddd() -> Poll<Result<(), String>> {
    Poll::Pending
}

fn dd() -> Poll<Result<(), String>> {
    let x = ddd()?;

    Poll::Pending
}
```

the x doesn't have type hint

![image](https://user-images.githubusercontent.com/10096425/87250381-eedfbc00-c496-11ea-9597-32ecc3d26231.png)

**Comment by Undin** [comment]
Thanks! I can reproduce it.
Looks like the reason is the absence of common support of `Try` trait. Only hardcoded versions for `Result` and `Option` enums
