### ISSUE TITLE
No code hints for type definition

### ISSUE THREAD

**Issue by TheLudlows** [intellij-rust/intellij-rust#5738]
## Environment

* **IntelliJ Rust plugin version:** 0.3.127.3218-201-nightly
* **Rust toolchain version:** 1.46.0-nightly (6bb3dbfc6 2020-06-22) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.1.1 (CL-201.7223.86)
* **Operating system:** macOS 10.13.6

## Problem description
No code hints for type definition
## Steps to reproduce
![](https://github.com/TheLudlows/rust-tour/blob/master/common/qa.jpg?raw=true)

**Comment by Kobzol** [comment]
Type aliases cannot be used as constructors (https://github.com/rust-lang/rust/issues/17422) and you also cannot call associated methods with `.` (you have to use `Foo::say_hello` or `Boo::say_hello`).

If you try to complete `Foo::` or `Boo::`, the associated method is offered.

**Comment by TheLudlows** [comment]
> Type aliases cannot be used as constructors ([rust-lang/rust#17422](https://github.com/rust-lang/rust/issues/17422)) and you also cannot call associated methods with `.` (you have to use `Foo::say_hello` or `Boo::say_hello`).
> 
> If you try to complete `Foo::` or `Boo::`, the associated method is offered.

Sorry, it's still same

**Comment by Kobzol** [comment]
So to be clear, when you have code like this:
```rust
struct Foo;
type Boo = Foo;
impl Foo {
    fn say_hello(&self) {
         println!("hello");
    }
}

fn foo(x: Boo) {
    x./*caret*/
}
```
`say_hello` is not offered at `/*caret*/` for you?

`let b = Boo;` is not valid Rust code, you cannot use a type alias to create an instance of a struct. That is also why the plugin doesn't offer anything in such case.

**Comment by TheLudlows** [comment]
tks for your reply. ![](https://github.com/TheLudlows/rust-tour/blob/master/common/1.jpg?raw=true)
I want to use try_new function, but no hit. and i'm sure function is really exist.

**Comment by Kobzol** [comment]
That indeed looks like a bug, the function is resolved, but it is not offered during completion.

**Comment by ortem** [comment]
Could not reproduce. Probably, [cache invalidation](https://www.jetbrains.com/help/idea/invalidate-caches.html) will fix this problem. Please reopen if the problem persists.
