### ISSUE TITLE
Rename inside a macro invocation fails

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#5740]
## Environment

* **IntelliJ Rust plugin version:** 0.3.126.3220-201
* **Rust toolchain version:** 1.46
* **IDE name and version:** CLion 2020.1
* **Operating system:** Windows 10

## Problem description

Renaming an identifier inside a macro invocation fails with `some generated file name.rs is read-only` error.

## Steps to reproduce

```rust
macro_rules! test {
    ($name:ident) => {
        pub static $name: i32 = 0;
    }
}

test!(SYMBOL); // try renaming SYMBOL
```

**Comment by vlad20012** [comment]
Unfortunately, it's not implemented yet. It's a known limitation.
