### ISSUE TITLE
Handle types not indexed from Erupt crate in plugin versions after 0.3.126.3220-201

### ISSUE THREAD

**Issue by nathanvoglsam** [intellij-rust/intellij-rust#5755]
## Environment

* **IntelliJ Rust plugin version:** 0.3.126.3220-201, anything after 0.2.123.3132-201
* **Rust toolchain version:** 1.44.1
* **IDE name and version:** CLion 2020.1.1 and Intellij IDEA Ultimate 2020.1
* **Operating system:** Windows 10 Pro 1909

All tests/examples provided were produced with the new macro engine enabled, even in the older versions where it was still marked as experimental.

## Problem description

Following version 0.2.123.3132-201 the plugin no longer indexes any types declared with `non_dispatchable_handle!` from the [erupt](https://gitlab.com/Friz64/erupt) Vulkan bindings. This includes types like Semaphore, DescriptorPool, DescriptorSet, which are declared in the crate like so:
```rust
crate :: non_dispatchable_handle ! ( Semaphore , SEMAPHORE , doc = "[Vulkan Manual Page](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkSemaphore.html) · Non-dispatchable Handle" ) ;
```

The macro itself is declared as:
```rust
// adapted from ash
#[doc(hidden)]
#[macro_export]
macro_rules! non_dispatchable_handle {
    ($name:ident, $ty:ident, $doc_link: meta) => {
        #[repr(transparent)]
        #[derive(Eq, PartialEq, Ord, PartialOrd, Clone, Copy, Hash, Default)]
        #[$doc_link]
        pub struct $name(pub u64);

        impl $name {
            pub const TYPE: crate::vk1_0::ObjectType = crate::vk1_0::ObjectType::$ty;

            pub const fn null() -> $name {
                $name(0)
            }

            pub const fn is_null(&self) -> bool {
                self.0 == 0
            }
        }

        impl std::fmt::Pointer for $name {
            fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                write!(f, "0x{:x}", self.0)
            }
        }

        impl std::fmt::Debug for $name {
            fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                write!(f, "0x{:x}", self.0)
            }
        }
    };
}
```

With the big stack of includes copied from the initial codebase I encountered the error in, these two screenshots show the later plugin versions failing to highlight the types that were created with the `non_dispatchable_handle!` macro as structs, they also do not show up in any autocomplete or for auto import in newer versions.

`0.3.126.3220-201`
![old](https://cdn.discordapp.com/attachments/231405311133614080/734280967895777360/bug1.png)

`after 0.3.126.3220-201`
![new](https://cdn.discordapp.com/attachments/231405311133614080/734280973834911784/bug2.png)

## Steps to reproduce

Using the snippets below for a minimal crate to reproduce the issue

`Cargo.toml`
```toml
[package]
name = "bug-repro"
version = "0.1.0"
authors = ["Nathan Voglsam"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
erupt = "0.10"
```

`src/lib.rs`
```rust
use erupt::vk1_0::{
    AccessFlags, AttachmentLoadOp, AttachmentStoreOp, Buffer, BufferCreateInfoBuilder,
    BufferUsageFlags, ClearColorValue, ClearDepthStencilValue, ClearValue, CommandBuffer,
    CommandBufferAllocateInfoBuilder, CommandBufferBeginInfoBuilder, CommandBufferLevel,
    CommandBufferUsageFlags, CommandPool, CommandPoolCreateInfoBuilder, CommandPoolResetFlags,
    DescriptorBufferInfoBuilder, DescriptorImageInfoBuilder, DescriptorPool,
    DescriptorPoolCreateInfoBuilder, DescriptorPoolSizeBuilder, DescriptorSet,
    DescriptorSetAllocateInfoBuilder, DescriptorType, Extent2DBuilder, Fence, Format, Framebuffer,
    FramebufferCreateInfoBuilder, ImageLayout, IndexType, Offset2DBuilder, PipelineBindPoint,
    PipelineStageFlags, Rect2DBuilder, RenderPass, RenderPassBeginInfoBuilder,
    RenderPassCreateInfoBuilder, Semaphore, SemaphoreCreateInfoBuilder, SharingMode,
    SubmitInfoBuilder, SubpassContents, SubpassDependencyBuilder, SubpassDescriptionBuilder,
    Vk10DeviceLoaderExt, WriteDescriptorSetBuilder, SUBPASS_EXTERNAL, WHOLE_SIZE,
};

#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
}
```

The other imports are provided to demonstrate the issue only occurring on the handle types.

Simply loading that crate up in the IDE with the newer plugin versions should reproduce the error.

**Comment by Undin** [comment]
@nathanvoglsam Thanks for the report!
The cause of this issue is a bug in name resolution that prevents correct handling macro calls with `crate::` prefix, i.e. `crate::non_dispatchable_handle!` in your case
