### ISSUE TITLE
Intention to "inline" type alias

### ISSUE THREAD

**Issue by panstromek** [intellij-rust/intellij-rust#5756]
It'd be cool to have intention that would replace type alias with the original type.

Before:
```rust
type MyInt = i32;
fn main () {
    let num : /*caret*/MyInt = 0;
}
```
After:
```rust
fn main () {
    let num : /*caret*/i32 = 0;
}
```

This would come in handy sometimes, but I'd say it's not a priority. ATM I'd like to have this for bunch of generated code from `c2rust` output. It creates a lot of code with type aliases like `libc::c_int` that are just aliased rust primitive types, so I want to "inline" them.

**Comment by Kobzol** [comment]
I think that this was already discussed in https://github.com/intellij-rust/intellij-rust/issues/824, but it was more focused on introducing type aliases, so let's keep this issue to be about inlining them. Maybe the inlining should offer to keep the type alias after inlining it, same as with the normal inline value refactoring.
