### ISSUE TITLE
Autocompletion/autoimporting for locally referenced crates within the same workspace does not work

### ISSUE THREAD

**Issue by sebschmi** [intellij-rust/intellij-rust#5761]
## Environment

* **IntelliJ Rust plugin version:** 0.3.126.3220-201
* **Rust toolchain version:** 1.45.0 (5c1f21c3b 2020-07-13) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2020.1.3 Community Edition (IC-201.8538.31)
* **Operating system:** Linux 5.3.0-62-generic

## Problem description

Related to #4780.
It seems like the autocompletion as well as the automatic importing of unresolved identifiers ignores crates referred locally completely.

For an example check out the following commit of the following project like this:
```
git clone https://github.com/algbio/practical-omnitigs.git
cd practical-omnitigs
git checkout b5d5ee6fbad958f8b9eba05c8e3dbe99671ff786
```
Open the project in IDEA.
Open the file `cli/src/main.rs`.
Type anything like `use gen` outside a method or any prefix of `genome_graph` inside a method. The crate `genome_graph` will not be proposed, so the autocompletion does not work in this case.
Additionally, uncomment the second line in this file and press the `Build Project` button. Try to resolve any of the identifiers not found using `[Ctrl]+[Space]`. No suggestions are generated, so the automatic importing does not work here either.

The crate `genome_graph` is included in the dependencies of the `cli` crate via local reference (`genome-graph = {path = "../genome_graph"}`), but that should not make any difference to a crate imported from crates.io.

**Is there a workaround for this, other than pushing alpha versions to crates.io all the time?**

**Comment by jearmstrong21** [comment]
Not sure how welcome this is 😅 but I can reproduce this on my own project, which compiles fine but doesn't index the local dependency. Windows 10, CLion 2020.2.3 and I can provide more information if needed.

**Comment by dima74** [comment]
This was fixed some time ago
