### ISSUE TITLE
Can't find macros by name in Rust

### ISSUE THREAD

**Issue by maxim-banaev** [intellij-rust/intellij-rust#5773]
## Environment

* **IntelliJ Rust plugin version:**
* **Rust toolchain version:**
* **IDE name and version:** CL-201.7846.88
* **Operating system:** Linux

## Problem description

How I can find where using macros in my project (println f.e.) via Search Everywhere? How I can find next row:
vec!

**Comment by ortem** [comment]
To find all the project usages of a macro or any other item from stdlib, you can navigate to its declaration (<kbd>Ctrl</kbd>+<kbd>B</kbd> on any usage) and run `Find Usages Settings...` action (<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>7</kbd>). Then, in the `Find Usages` dialog, in the `Scope field`, select a scope for your search. For example, you can search for usages only in `Project Files`.

Please follow the [documentation](https://www.jetbrains.com/help/idea/find-highlight-usages.html) for more information.
