### ISSUE TITLE
No syntax highlighting in code inside a macro

### ISSUE THREAD

**Issue by rphsoftware** [intellij-rust/intellij-rust#5775]
## Environment

* **IntelliJ Rust plugin version:** 0.3.126.3220-201
* **Rust toolchain version:** 1.45.0
* **IDE name and version:** IntelliJ IDEA Ultimate 2020.1.3
* **Operating system:** Arch Linux (Kernel 5.7.9-arch1-1)

## Problem description

When using a macro provided by the `neon` library, the code inside the declare_types macro does not get syntax highlighting or any kind of coding assistance.
![image](https://user-images.githubusercontent.com/11350302/88085405-15cc7b00-cb86-11ea-91f6-244e41f0020c.png)

## Steps to reproduce

Step 1: Create new project using Neon ( https://neon-bindings.com/ )
Step 2: Open the `native` directory from the new Neon project as an IntelliJ IDEA project
Step 3: In src/lib.rs, paste the following code  https://gist.github.com/rphsoftware/272145569607857f80750a0dc5381ada
Step 4: You will notice that no code inside the macros gets highlighted

## Confirmations

* I am using the new macro expansion engine
* I have verified my rust installation
* The code compiles properly using the method described by the neon project

**Comment by vlad20012** [comment]
Thanks for the report! I fixed it in #5777
![image](https://user-images.githubusercontent.com/3221931/88183744-83d27a00-cc3a-11ea-88ad-a3c052e2fa4e.png)

**Comment by rphsoftware** [comment]
Not sure if this is the correct place to ask, but how would I compile the plugin with your patch and install it into my IDE?

**Comment by Undin** [comment]
@rphsoftware clone repo, checkout the corresponding branch (`macro-group-matching`) and launch `./gradlew :plugin:buildPlugin` command. Plugin zip archive can be found in `plugin/build/distributions`.
See the corresponding [section](https://github.com/intellij-rust/intellij-rust/blob/master/CONTRIBUTING.md#building--running) in CONTRIBUTING.md for more details

**Comment by vlad20012** [comment]
Btw the fix is landed, so it's available in the nightly plugin, so you don't need to build it manually. You can try the nightly plugin now (see [instructions](https://intellij-rust.github.io/install.html))
