### ISSUE TITLE
Empty slice match confuses linter

### ISSUE THREAD

**Issue by dimpolo** [intellij-rust/intellij-rust#5786]
## Environment

* **IntelliJ Rust plugin version:** 0.3.126.3220-201
* **Rust toolchain version:** nightly-i686-pc-windows-gnu
* **IDE name and version:** Pycharm 2020.1.3
* **Operating system:** Windows 10

## Problem description
Matching against an empty slice reports an error on the match after.
The code compiles fine, but the second match arrow reports `'(', ',', <operator>, '[' or '}' expected, got '=>'`

## Steps to reproduce

``` rust
fn main() {
    let array = [42];
    match array[..] {
        [] => {}  // <- if you put a comma here, the error disappears, but rustfmt will remove it again
        [_x] => {} // <- error for this match arrow
        _ => {}
    }
}
```

**Comment by afetisov** [comment]
Can't reproduce it on the latest plugin version. Close?

**Comment by Undin** [comment]
@afetisov Thanks!
Looks like your changes from #7462 fixed this issue 😄 
I've added the corresponding tests in #8251 to commit proper behavior
