### ISSUE TITLE
"MSVC debugger cannot be used with GNU Rust toolchain"

### ISSUE THREAD

**Issue by flaghacker** [intellij-rust/intellij-rust#5794]
## Environment

* **IntelliJ Rust plugin version:** 0.3.126.3220-201
* **Rust toolchain version:** stable-x86_64-pc-windows-gnu - rustc 1.45.0 (5c1f21c3b 2020-07-13)
* **IDE name and version:** CLion 2020.1.2, Build #CL-201.7846.88, built on June 3, 2020
* **Operating system:** Windows 10 Version 2004

## Problem description

I'm trying to debug my program, but I get the following popup:

![image](https://user-images.githubusercontent.com/7887115/88463560-eaae9800-ceb3-11ea-879d-5efb0a4e085d.png)

My rustup toolchain is set to GNU (see above).

Clicking the "Configure" buttong on that dialog opens this window:

![image](https://user-images.githubusercontent.com/7887115/88463595-2cd7d980-ceb4-11ea-8330-b904511ebed7.png)

but that doesn't seem useful to me either, I just want to not use MCVC at all, right?

I remember that debugging on GNU would just work™, but this is a fresh Windows and CLion install so there could be something I fogot to set up correctly. Is there something I'm missing? Could the dialog be changed to be a bit more helpful about what the problem actually is?

**Comment by ortem** [comment]
@flaghacker Please set up the Cygwin or MinGW toolchain using [this article](https://www.jetbrains.com/help/clion/quick-tutorial-on-configuring-clion-on-windows.html). You can also find more information on Rust debugging [here](https://blog.jetbrains.com/clion/2019/10/debugging-rust-code-in-clion/?_ga=2.252115977.1492513215.1595711832-1089880583.1595609132). Feel free to ask any questions here.

**Comment by flaghacker** [comment]
Ah, I see, I'll try that. Is it right that WSL doesn't work for Rust yet?

**Comment by flaghacker** [comment]
I've set up MinGW like this now: 

![image](https://user-images.githubusercontent.com/7887115/88485312-44c36200-cf75-11ea-92d7-57ecda10bd0d.png)

When I try to debug my program I get this error in the console:

```
com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$GDBCommandException: Error creating process C:\Documents\Programming\STTT\sttt\target\release\main.exe, (error 50).
```

**Comment by Undin** [comment]
@flaghacker You try to use a 32-bit debugger with 64-bit binaries. Try to use mingw64

**Comment by Undin** [comment]
> Is it right that WSL doesn't work for Rust yet?

Unfortunately, yeah

**Comment by flaghacker** [comment]
Ah you're right, with mingw-w64 it does work. Thanks for the help!
