### ISSUE TITLE
Docs `italics`

### ISSUE THREAD

**Issue by alexeykudinkin** [intellij-rust/intellij-rust#580]
Please, stop making doc-comments an italics font. 
And use italics anywhere else. It looks ugly.

<img width="595" alt="screen shot 2016-08-07 at 15 16 13" src="https://cloud.githubusercontent.com/assets/428277/17462585/02a2933a-5cb2-11e6-9dfb-b78f829134f3.png">

**Comment by mkaput** [comment]
Hmm, we don't apply any custom styling to doc comments (apart from markup in Default scheme, as stack one is horrible). Everything is inherited, so I don't think we should enforce custom theming here.

**Comment by zekesonxx** [comment]
intellij-rust Rustdoc comments (`Rust -> Rustdoc comment`) inherit from `Language Defaults -> Comments -> Doc Comment -> Text`, which is, by default, italic.

![](https://puu.sh/qvjgH.png)

![](https://puu.sh/qvjiC.png)

**Comment by alexeykudinkin** [comment]
@mkaput @zekesonxx

**Comment by gilescope** [comment]
I'd like to re-open this as it's definitely a bug. Italics fail to render ascii diagrams well.

```
     |
     |
     | 
```

turn into 
```
     \
     \
     \
```

Given the focus on markdown, being able to display ascii disgrams nicely is important.
