### ISSUE TITLE
Borrow trait ambiguity with RefCell

### ISSUE THREAD

**Issue by alexxbb** [intellij-rust/intellij-rust#5805]
## Environment

CLion 2020.2 Beta
Build #CL-202.6397.12, built on July 14, 2020
CLion EAP User
Expiration date: August 13, 2020
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.19.0-6-amd64
GC: ParNew, ConcurrentMarkSweep
Memory: 7987M
Cores: 4
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: IdeaVIM, org.toml.lang, org.rust.lang
Current Desktop: XFCE

Rust: 1.45 stable

Rust Plugin: 0.3.126.3220-202

## Problem description

We know that `Rc<RefCell<_>> `is a very common pattern in Rust.
Because of how traits work in Rust, there is an ambiguity between `Rc::borrow` and `RefCell::borrow` depending on which trait is in scope. 
Most of the time, the IDEs feature of auto-import symbols is very useful, but in this case, it much more often than not it silently imports the `std::borrow::Borrow` into the current scope, breaking the code, and if the user of not aware of this behavior (especially beginners) it's sometimes difficult to spot.

Here is a related rustlang issue: https://github.com/rust-lang/rust/issues/41906

## Steps to reproduce
```rust
use std::cell::RefCell;
use std::rc::Rc;
use std::borrow::Borrow; // This breaks RefCell::borrow()

fn main() {
    let r = Rc::new(RefCell::new(5));
    println!("{:?}", r.borrow());
}
```

## Proposal
Prohibit the IDE from auto-importing the Borrow trait. Or maybe add a pop up to confirm the user intention to import the trait.
I know this is not a bug but rather a big quality of life improvement.

**Comment by Reylak** [comment]
I'm backing this proposal up. Maybe another possibility is to add an inspection about this import which is most often not what the user wants? As suggested by the rut-lang issue in the OP.

**Comment by morristai** [comment]
According to @ozkriff (as IntelliJ-Rust team member) response in Discord channel, here's a temporary workaround quoted from him, hope it might help:
> In the meantime you could disable auto-imports for Rust at Settings/Preferences (Ctrl+Alt+S) -> Editor -> General -> Auto Import
![image](https://user-images.githubusercontent.com/10728152/149756504-771670fc-f9c3-432a-a989-de7ec868393e.png)
