### ISSUE TITLE
Cargo complaining about missing fields

### ISSUE THREAD

**Issue by alexeykudinkin** [intellij-rust/intellij-rust#581]
Project 'librustc_typeck' failed to update. Cargo execution failed (exit code 101). /usr/local/bin/cargo metadata --verbose stdout : stderr : failed to parse manifest at `/Users/akudinkin/Desktop/projects/rust/rustc/src/librustc_typeck/Cargo.toml` Caused by: expected a value of type `string` for the key `package.version`

**Comment by matklad** [comment]
Looks like a syntax error in the Cargo.toml? 

What is the commit hash of rustc checkout at `Users/akudinkin/Desktop/projects/rust/`?

**Comment by alexeykudinkin** [comment]
It's manually created, seems fishy that we cannot proceed w/o version of the package being present.

**Comment by matklad** [comment]
It's not us, it's the `Cargo` itself.

**Comment by alexeykudinkin** [comment]
Still bad.
