### ISSUE TITLE
latest nightly rust-src installation path just changed

### ISSUE THREAD

**Issue by imkow** [intellij-rust/intellij-rust#5823]
Cargo project update failed:
				download failed: Failed to find stdlib in sysroot

looks like that's caused by the src path change.

before: `lib\rustlib\src\rust\src`
after nightly-2020-07-28: `lib\rustlib\src\rust\library` 

be reminded: the subdirectory structure and subdir names also changed.
the change can be seen in `lib\rustlib\manifest-rust-src` manifest file.

intellij-rust could use the path from the manifest-rust-src instead of hard coded, for good.

**Comment by eburkey** [comment]
I have experienced the same error this morning on Pop_OS! 20.04 and nightly. Manually setting the path in the plugin's settings window does not fix the errors.

**Comment by ooopSnake** [comment]
i have try :
```bash
cd  ${my rustup home}/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library
ln -s library src # or cp -r library src
```
plugin report : **corrupted standard library**
```bash
Cargo project update failed:
			corrupted standard library: ${my rustup home}/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src
```
