### ISSUE TITLE
Rust error format updates and IDE support

### ISSUE THREAD

**Issue by jonathandturner** [intellij-rust/intellij-rust#583]
I'm not sure if this will impact you all, but we're discussing [moving to the new Rust error format](https://github.com/rust-lang/rust/pull/35401).  Once this goes in, there are still some weeks between it hitting nightly and it being available in a stable release.  We're hoping to use this time to make the transition as smooth as possible.

The change will impact plugins that use a regex on the compiler output to parse the errors.  This will need to be updated once users start using the new errors.

The PR also includes a stable JSON mode which includes all the same information as the error message, but in a more structured way.  This should hopefully give plugins a couple of options on how to work with compiler errors.

Please let us know in the thread on the PR if this impacts your plugin, and how we can help.

**Comment by matklad** [comment]
Thanks! Replied on the PR.
