### ISSUE TITLE
Macros expand for all opened projects even if only one has changed

### ISSUE THREAD

**Issue by nazar-pc** [intellij-rust/intellij-rust#5834]
## Environment

* **IntelliJ Rust plugin version:** 0.3.127.3249-202
* **Rust toolchain version:** Current nightly
* **IDE name and version:** IDEA Ultimate 2020.2 202.6397.59
* **Operating system:** Ubuntu Linux 20.10

## Problem description
When a few Rust projects are opened in different windows, expanding macros is always triggered across all opened projects when only one has changed.

This becomes a big problem when 5 Rust projects are opened at the same time.

## Steps to reproduce

1. Open 2 Rust projects as 2 windows
2. Change Cargo.toml in one of them
3. Observer macros expansion running in both windows at a slightly different pace

**Comment by afetisov** [comment]
Doesn't seem to be an issue on the latest plugin version. Close?

**Comment by nazar-pc** [comment]
Looks like it, closing
