### ISSUE TITLE
Debug mode fails to set CARGO_MANIFEST_DIR environment variable

### ISSUE THREAD

**Issue by luckystreak63** [intellij-rust/intellij-rust#5836]
## Environment

* **IntelliJ Rust plugin version:** 0.3.127.3249-202
* **Rust toolchain version:** x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2020.2
* **Operating system:** Windows

## Problem description
Running a project in _Debug_ mode fails to set CARGO_MANIFEST_DIR environment variable.

## Steps to reproduce
Create a new rust project.
Add the default Cargo run configuration.
Add the following code to `main.rs`:
```rust
use std::env;

fn main() {
    if let Some(_manifest_dir) = env::var_os("CARGO_MANIFEST_DIR") {
        println!("Found CARGO_MANIFEST_DIR");
    } else {
        println!("Error finding CARGO_MANIFEST_DIR");
    }
}
```
Pressing `Run` prints "Found CARGO_MANIFEST_DIR".
Pressing `Debug` prints "Error finding CARGO_MANIFEST_DIR".

**Comment by luckystreak63** [comment]
It seems this variable is typically set by Cargo at runtime:
https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates

**Comment by fkrauthan** [comment]
Looks like I've reported the same issue in #6500

**Comment by luckystreak63** [comment]
Fixed by https://github.com/intellij-rust/intellij-rust/pull/7630
