### ISSUE TITLE
toolchain location not included in PATH passed to cargo

### ISSUE THREAD

**Issue by tamird** [intellij-rust/intellij-rust#5843]
Hello! We are big fans of this plugin in [Fuchsia](https://fuchsia.dev).

In Fuchsia, we use self-contained rust toolchains, which means that our `cargo`, `rustc`, etc. are not usually in our PATH. This seems to be a problem for this plugin because `cargo` is executed with intellij's PATH, and is then unable to find `rustc`.

Would it be possible to execute cargo with the toolchain location (specified in the plugin's settings) appended to PATH?

cc @brunowonka

**Comment by mchernyavsky** [comment]
@tamird Hello!

Try to modify Cargo Command configuration template:

<img width="1183" alt="Screenshot 2020-07-31 at 21 36 29" src="https://user-images.githubusercontent.com/6079006/89066390-0b746300-d376-11ea-8f93-d223d7ff6eb6.png">

<img width="854" alt="Screenshot 2020-07-31 at 21 36 47" src="https://user-images.githubusercontent.com/6079006/89066396-0dd6bd00-d376-11ea-97a0-0fd5c45fbba1.png">

**Comment by tamird** [comment]
@mchernyavsky thanks for the response! I think that setting only affects my configurations. This bug is about the plugin itself attempting to invoke cargo and failing. My event log still shows:

```
6:58 PM	Cargo project update failed:
							Execution failed (exit code 101).
							        /usr/local/google/home/tamird/src/fuchsia/prebuilt/third_party/rust/linux-x64/bin/cargo metadata --verbose --format-version 1 --all-features
							        stdout : error: could not execute process `rustc -vV` (never executed)
							
							Caused by:
							  No such file or directory (os error 2)
							
							        stderr : 

```

**Comment by Kobzol** [comment]
If I'm not mistaken, I think that you can work around this by modifying the PATH variable before starting the IDE. I.e. if you start the IDE from a command line like this: `$ PATH=... clion`, it should pick it up. At least it worked for me (https://github.com/intellij-rust/intellij-rust/issues/4331).

**Comment by tamird** [comment]
@Kobzol thanks. I've sent a PR to try to solve this more generally.
