### ISSUE TITLE
Converting struct to tuple doesn't convert struct creation via Self

### ISSUE THREAD

**Issue by DomWilliams0** [intellij-rust/intellij-rust#5851]
## Environment

* **IntelliJ Rust plugin version:** 0.3.127.3249-202
* **Rust toolchain version:** 1.4.5.0
* **IDE name and version:** CLion 2020.2
* **Operating system:** Linux

## Problem description
The "convert to tuple" intention doesn't refactor construction.

## Steps to reproduce
```rust
struct MyStruct {
    a: i32,
    b: i32,
}
impl MyStruct {
    fn new(a: i32, b: i32) -> Self {
        Self {a,b}
    }

    fn destructure(self) -> (i32, i32) {
        let MyStruct{a,b} = self;
        (a,b)
    }
}
```
Running "convert to tuple" intention gives the following:

```rust

struct MyStruct(i32, i32);

impl MyStruct {
    fn new(a: i32, b: i32) -> Self {
        Self {a,b} // <------ not converted! it should become `Self(a, b)`
    }

    fn destructure(self) -> (i32, i32) {
        let MyStruct(a, b) = self;
        (a,b)
    }
}
```

**Comment by Undin** [comment]
Looks like the problem in using `Self` to create struct. If you use struct name, it works correctly

**Comment by Kobzol** [comment]
@Undin
```rust
var usages = ReferencesSearch
            .search(element)
            .asSequence()
            .map { UsageInfo(it) }
```
This does not find the usage of `Self {a, b}`. I think that it's caused by the fact that `Self` does not resolve to `MyStruct`, but to `impl MyStruct`.
