### ISSUE TITLE
std::prelude::v1 imports are shown as unresolved

### ISSUE THREAD

**Issue by fctorial** [intellij-rust/intellij-rust#5859]
## Environment

* **IntelliJ Rust plugin version:**
0.3.127.3249-201
* **Rust toolchain version:**
1.43
* **IDE name and version:**
intellij community 2020.1.4
* **Operating system:**
linux

## Problem description

`std::prelude::v1::*` imports are displayed as unresolved (in red). 
https://prnt.sc/tt4t14

**Comment by Kobzol** [comment]
If you open the `Cargo` tool window, is anything underlined in red? Try refreshing the cargo project from the tool window, invalidate IntelliJ caches (`File -> Invalidate Caches/Restart`) and open the project again. Does the problem still persist then?

**Comment by fctorial** [comment]
@Kobzol Yes the project name has a red squiggly. Invalidating caches and restarting doesn't change anything.

**Comment by Undin** [comment]
@fctorial Thanks for the report!
Could you provide a project example where it happens? And does it happen even with a new "Hello, World" project?

**Comment by fctorial** [comment]
@Undin Never mind, this issue isn't there in latest idea. I had to remove `.idea` directory for projects created with old idea.
