### ISSUE TITLE
Execute Cargo command action

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#586]
Like "Execute Gradle task", or "Execute manage.py command" for Django in PyCharm, but for Cargo.

**Comment by zjhmale** [comment]
@matklad did you mean this in Gradle tool view?

![image](https://cloud.githubusercontent.com/assets/6234553/17863212/6842ff52-68cb-11e6-8760-679a004a615a.png)

**Comment by zjhmale** [comment]
@matklad agreed, a toolbar may not be necessary at first.

**Comment by zjhmale** [comment]
@matklad i'll take this, while no promise to finish it soon 😅

**Comment by matklad** [comment]
I'll tackle this. @mkaput I hope this won't collide hugely with your work on tests :)

**Comment by mkaput** [comment]
Depends on how much you will modify `CargoCommandConfiguration` & co. ;) But I haven't done a lot yet apart from test locator

**Comment by matklad** [comment]
Fixed in https://github.com/intellij-rust/intellij-rust/commit/9f545171d9c40b5e223e3c85a4d6bcdcb2aac3d0

https://gfycat.com/SlipperyDemandingCrab

**Comment by zjhmale** [comment]
Cool!
