### ISSUE TITLE
Failed to find stdlib in sysroot with nightly

### ISSUE THREAD

**Issue by mbenoukaiss** [intellij-rust/intellij-rust#5872]
## Environment
* **IntelliJ Rust plugin version:** 0.3.127.3249-201
* **Rust toolchain version:**  1.47.0-nightly (2020-08-03)
* **IDE name and version:** CLion 2020.1
* **Operating system:** Debian 9

## Problem description
When setting nightly as the default toolchain with rustup, the plugin fails to load stdlib.
I believe it might be caused by the difference in path to stdlib sources, stable sources are in src while nightly sources are in library :
Stable: `~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src` 
Nightly: `~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/`

## Steps to reproduce
Install nightly 2020-08-03 (i suppose future ones will also cause the bug), set nightly as the default toolchain and start your IDE where intellij-rust is installed.

**Comment by Undin** [comment]
Duplicate of #5823

**Comment by Undin** [comment]
@mbenoukaiss It's already fixed in #5838. Fixed will be landed in tomorrow nightly (see [instruction](https://intellij-rust.github.io/install#nightly-builds) how to install it) and will be in next stable release (next week I hope)
