### ISSUE TITLE
include! OUT_DIR completion broken in workspaces

### ISSUE THREAD

**Issue by hahnrobert** [intellij-rust/intellij-rust#5878]
IntelliJ Rust plugin version: 0.3.127.3249-202
Rust toolchain version: 2020-07-02 nightly
IDE name and version: CLion 2020.2
Operating system: MacOS

## Problem description
Create a project which generates code in a file in the OUT_DIR.  Now, add the project to a cargo workspace. Observe that the previously working auto completion is now no longer working.

**Comment by Undin** [comment]
Try to enable `org.rust.cargo.evaluate.build.scripts` option in `Experimental Features` settings. You can find it via `Help | Find Action` and type "Experimental Features". It should solve your issue.
Note, it significantly increases project structure loading

**Comment by clintfred** [comment]
@hahnrobert Did this work in plugin version 126? Might be related to #5861.

**Comment by hahnrobert** [comment]
Thanks for following up so quickly. The problem isn’t with the file structure it’s with which cargo project was attached. 
First I made sure that no Cargo project was attached, meaning that opening the cargo tab in IntelliJ shows an empty list. Auto complete doesn’t work. 
Then I select the crates Cargo.toml and click attach in the info bar at the top of the file. The project is added to the cargo window and auto completion works as expected. 
I remove the project again but instead of adding the crate’s cargo toml I am adding the workspace’s one. Auto completion now stopped working.

Workspace support seems to generally be a little broken. When selecting a project within the workspace and adding its Cargo.toml all other projects are added underneath the one I added. 

It’s kinda awkward and difficult to explain this issue. So please reach out and ask questions for clarity.

**Comment by tdrozdowski** [comment]
I've got the same issue with my setup - this was working previously.  Does downgrading to a specific plugin version restore this behavior?

**Comment by tdrozdowski** [comment]
So far 126 is the only recent build for this that works - 127, 128, 129 and the 130 nightly so far yield the same results.

**Comment by Bromeon** [comment]
This still seems to be a problem, I've seen it e.g. with the `prost` or `gdnative` libraries, which both generate code in `target` directory as part of their build step. Unfortunately, the generated code does not take part in static analysis and code completion.

Are there any known workarounds? Is it possible to manually add the `OUT_DIR` or so?
