### ISSUE TITLE
Add De Morgan's Laws intentions

### ISSUE THREAD

**Issue by mkaput** [intellij-rust/intellij-rust#588]
Implement boolean expression manipulating intentions like one in IntelliJ

**Comment by matklad** [comment]
:apple:

**Comment by mkaput** [comment]
Yeah, typing on SwiftKey, so much fun

**Comment by zjhmale** [comment]
https://blog.jetbrains.com/idea/2014/09/the-inspection-connection-issue-2/

seems a lot work to do here :scream:

**Comment by mkaput** [comment]
You can copy paste this from IntelliJ, PyCharm, Groovy and Kotlin implementations :p

**Comment by mkaput** [comment]
Also De Morgan laws are pretty simple and straightforward. Implementation should be recursive over rust expression. Typing infra to check whether expression is boolean already works and it's api is very very friendly.

**Comment by zjhmale** [comment]
i will checkout the intellij implementations 😁

**Comment by zjhmale** [comment]
@mkaput and maybe a intention instead of a inspection is better? i mean boolean sequence just have DeMorgan equivalent, but there not exists a best one.

**Comment by mkaput** [comment]
> @mkaput and maybe a intention instead of a inspection is better?

yeah, wrong words

**Comment by zjhmale** [comment]
@mkaput here is a problem that we can not easily get the operator for a `RustBinaryExprElement` just like [python-plugin](https://github.com/JetBrains/intellij-community/blob/master/python/src/com/jetbrains/python/codeInsight/intentions/PyDemorganIntention.java#L56), [groovy-plugin](https://github.com/JetBrains/intellij-community/blob/master/plugins/groovy/src/org/jetbrains/plugins/groovy/intentions/control/DemorgansLawIntention.java#L57) and [kotlin-plugin](https://github.com/JetBrains/kotlin/blob/master/idea/src/org/jetbrains/kotlin/idea/intentions/ConvertNegatedBooleanSequenceIntention.kt#L60).

![2333333333333333](https://cloud.githubusercontent.com/assets/6234553/17561728/00817d00-5f5a-11e6-9b49-78c66437fcdd.png)

**Comment by mkaput** [comment]
working on this

**Comment by mkaput** [comment]
Here you are ^ @zjhmale  :smile:

**Comment by zjhmale** [comment]
@mkaput thx! 😃
