### ISSUE TITLE
Cannot find declaration to go to std::os::windows, EncodeWide and OsStrExt

### ISSUE THREAD

**Issue by Zymlex** [intellij-rust/intellij-rust#5881]
![изображение](https://user-images.githubusercontent.com/25817412/89519750-30f2e800-d820-11ea-9d0d-a9f7734dc0bc.png)
![изображение](https://user-images.githubusercontent.com/25817412/89519692-1f114500-d820-11ea-85c6-a891328e6929.png)
![изображение](https://user-images.githubusercontent.com/25817412/89519658-115bbf80-d820-11ea-995a-1cfc81444807.png)

## Environment

* **IntelliJ Rust plugin version:** 0.3.127.3249-202
* **Rust toolchain version:** last stable-x86_64-pc-windows-msvc and nightly-x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2020.2 Build #CL-202.6397.106, built on July 28, 2020
* **Operating system:** Windows Server 2019

## Problem description
Cannot find declaration to go to std::os::windows, EncodeWide and OsStrExt.

## Steps to reproduce

```rust
use std::ffi::{self, OsStr, OsString};
use std::fs;
use std::io::Error;
use std::os::windows::ffi::{EncodeWide, OsStrExt};

fn main() {
    let path = "";

    let var1: EncodeWide<'_> = OsStr::new(path).encode_wide();
}
```

**Comment by Undin** [comment]
Similar with #3957 and #4960

**Comment by HydrogenC** [comment]
Any updates?

**Comment by Undin** [comment]
@HydrogenC basic implementation to make name resolution work in this case was done in #6417 and currently it's under `org.rust.cargo.fetch.actual.stdlib.metadata` experimental feature (to turn it on, enable `org.rust.cargo.fetch.actual.stdlib.metadata option` in `Experimental Feature` dialog. You can open it via `Help | Find Action` and type `Experimental features`).
We are working on some minor things (like #6890) to enable it by default
