### ISSUE TITLE
Extracting selected expression initializer into function can incorrectly extract the initialized variable, too

### ISSUE THREAD

**Issue by panstromek** [intellij-rust/intellij-rust#5894]
If you select the block intuitively by placing caret at the start of the expression and then selecting all lines below, you will get this behaviour because it also selects a semicolon and plugin considers the variable as a part of the expression then.

#### Steps to reproduce:
1. 
```rust
fn foo (x : i32) -> i32 {
    let y = <selection>if x == 1 {
        3
    } else {
        5
    };</selection> // Note that selection here is not semantically correct
    y
}
```
2. invoke extract function, set name and hit enter

#### Expected result
```rust 

fn foo (x : i32) -> i32 {
    let y = bar(x);
    y
}

fn bar(x: i32) -> i32 {
    if x == 1 {
        3
    } else {
        5
    }
}
```
#### Actual result
```rust
fn foo (x : i32) -> i32 {
    bar(x);
    y
}

fn bar(x: i32) {
    let y = if x == 1 {
        3
    } else {
        5
    };
}
```

I know this can be technically "correct" because it selects closest meaningul syntax substree, but it's probably not the expected thing to happen in most cases. I would probably prefer an error over this behaviour, saying that the user didn't select valid expression, but mentioned expected behaviour would maybe be better, even though it's not technically correct, I guess?

**Comment by dima74** [comment]
Fixed in #7649
