### ISSUE TITLE
Wrong inference for amethyst `Option<Handle<SpriteSheet>>::as_ref().unwrap().clone()`

### ISSUE THREAD

**Issue by onelson** [intellij-rust/intellij-rust#5896]
## Environment

* **IntelliJ Rust plugin version:** 0.3.127.3249-202
* **Rust toolchain version:** 1.44.0
* **IDE name and version:** CLion 2020.2 Build #CL-202.6397.106
* **Operating system:** Ubuntu 20.04

## Problem description

For certain types such as an `Option<Handle<SpriteSheet>>`, an owned (clone) of a ref of the inner value is mistaken for a reference. The feedback from the plugin suggests adding `*` to deref, which is not possible since the value is not a reference.

The inference works correctly for `Option<String>`, so I don't quite understand what the issue is.

## Steps to reproduce

With `amethyst = "0.15.0"` in your dependencies, and overlooking the obvious runtime issues with the code that follows:

```rust
use amethyst::assets::Handle;
use amethyst::renderer::SpriteSheet;

fn main() {
    let maybe: Option<Handle<SpriteSheet>> = None;
    let _cloned: Handle<SpriteSheet> = maybe.as_ref().unwrap().clone();
}
```
The inference flags this as an error when it isn't.

![deref-bug](https://user-images.githubusercontent.com/301388/89722639-e8af0380-d9a0-11ea-8d92-e679d9831aa8.png)

**Comment by Undin** [comment]
I think it's because `Clone` implementation of `amethyst::assets::Handle` is generated by proc macros
```rust
#[derive(Derivative)]
#[derivative(
    Clone(bound = ""),
    Eq(bound = ""),
    Hash(bound = ""),
    PartialEq(bound = ""),
    Debug(bound = "")
)]
pub struct Handle<A: ?Sized> {
    id: Arc<u32>,
    #[derivative(Debug = "ignore")]
    marker: PhantomData<A>,
}
```
But the plugin doesn't support proc macros yet. As a result, you get wrong type inference for this struct

**Comment by mili-l** [comment]
see https://github.com/intellij-rust/intellij-rust/pull/9729
