### ISSUE TITLE
Add mod declaration after the last availaible in the file when performing "Attach file to main.rs" action

### ISSUE THREAD

**Issue by avrong** [intellij-rust/intellij-rust#5903]
## Environment

* **IntelliJ Rust plugin version:** 0.3.127.3249-202
* **Rust toolchain version:** 1.45.2 (d3fb005a3 2020-07-31) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.2 (CL-202.6397.106)
* **Operating system:** macOS 10.15.6

## Problem description

I believe that the better option will be to add the new `mod` declaration right after the last one available if it is present. It will reduce the following manual editing.

<img width="772" src="https://user-images.githubusercontent.com/6342851/89767968-9c300900-db03-11ea-85da-db26138cb3ba.png">

<img width="772" src="https://user-images.githubusercontent.com/6342851/89768843-d6e67100-db04-11ea-9d9c-d2b09efc0d39.png">

`Optimize Imports` action doesn't solve the problem completely.

<img width="772" src="https://user-images.githubusercontent.com/6342851/89768856-dc43bb80-db04-11ea-9d8f-86c86c6d0e2b.png">

## Expected result

```rust
use std::path::Path;

use module::whatever;

mod module;
mod new_module;

fn main() {...}
```

**Comment by Kobzol** [comment]
I wanted to do this in the original PR, but didn't get to it. I think that it's a great idea, thanks! :)
