### ISSUE TITLE
Completion in Cargo.toml lacks the relevant crate name

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#5908]
## Environment

* **IntelliJ Rust plugin version:** 0.3.129.3272-202-nightly
* **Rust toolchain version:** 1.47.0-nightly (6c8927b0c 2020-07-26) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.2 (CL-202.6397.106)
* **Operating system:** macOS 10.15.4

## Problem description

It is not always the case but sometimes completion in `Cargo.toml` lacks relevant options and suggest some less interesting crates, e.g. with `serde_json`

<img width="451" alt="Screen Shot 2020-08-10 at 19 40 11" src="https://user-images.githubusercontent.com/2500320/89810477-cd312d80-db45-11ea-8e00-e162be8209b0.png">

**Comment by Kobzol** [comment]
Fixed by https://github.com/intellij-rust/intellij-rust/pull/6390.

**Comment by Undin** [comment]
I think we shouldn't close this issue because `org.rust.crates.local.index` experimental feature is disabled by default for now, i.e. nothing changes from user point of view

**Comment by Kobzol** [comment]
I see, sorry for that. I closed a few other issues, probably got a bit excited.

**Comment by Undin** [comment]
> I see, sorry for that.

Don't worry about it

> I closed a few other issues, probably got a bit excited.

😄
Indeed, crate index opens a lot of opportunities

**Comment by Kobzol** [comment]
This was fixed by the local crate index, which is now enabled by default.
