### ISSUE TITLE
Move refactor doesn't move rename imports 

### ISSUE THREAD

**Issue by jaupe** [intellij-rust/intellij-rust#5952]
## Environment

* **IntelliJ Rust plugin version:**
0.3.128.3278-202
* **Rust toolchain version:**
1.45.2
* **IDE name and version:**
CLion 2020.2
Build #CL-202.6397.106, built on July 28, 2020
Licensed to CLion Evaluator
Expiration date: September 6, 2020
Runtime version: 11.0.7+10-b944.20 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 12
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: org.toml.lang, org.rust.lang
* **Operating system:**
macOS 10.15.5

## Problem description
Move refactors broke compile because it doesn't factor in rename imports.

I have a rename import like:

```rust
use serde_json::Value as Json;
```

And when I move a struct from one to another, it doesn't move the rename import. It correctly imported the right type (`serde_json::Value`) but didn't respect the rename so it broke my build. 

## Steps to reproduce

Create a struct using a rename import and move to another file and it won't move the rename import.

**Comment by MightyPork** [comment]
Maybe another symptom of the bug: move seems to fail at updating imports in a workspace.

I had two crates, one with a library, one a binary using it. I moved some traits to a different module in the library.

The new import was added at the end of the imports block in the binary crate, but the original import was not removed, leading to a compile error.

**Comment by dima74** [comment]
@jaupe @MightyPork sorry for the late response

Could you please provide minimal code snippets which can be used to reproduce the bug?

**Comment by MightyPork** [comment]
In honesty i forgot about the bug, there's now new and exciting ones (like Vec importing unstable alloc::Global when copying code). anyway


```
[dependencies]
serde = "1"
serde_json = "1"
```

main.rs
```
mod foo;
mod bar;
use foo::Json;
fn main() {
    let j : Json = Json::Null;
    println!("Hello, world!");
}
```

foo.rs
```
pub use serde_json::Value as Json;

pub fn do_stuff(x: Json) {
    let a : Json = Json::Null;
}
```

bar.rs is an empty file

move do_stuff to bar and see the import from main.rs stay unchanged = compile fails. 
The rename disappeared during the move so bar.rs now contains:

```
use serde_json::Value;

pub fn do_stuff(x: Value) {
    let a : Value = Value::Null;
}
```

**Comment by Undin** [comment]
> like Vec importing unstable alloc::Global when copying code

If it's about `Implement Memebrs` functionality, then there is #6186 and we are working on fix in #6896

**Comment by MightyPork** [comment]
`main` imports the re-exported `Value` as `Json`, that's what breaks after the move.

The renames being resolved and disappearing is not right, but in this case did not cause a problem. I think in the OP's code the alias was there to resolve ambiguity and this was conflated by renames being resolved, so the code stopped working.

-- 

yeah  #6186 seems like the issue I'm looking at, I'm not sure what caused the import being added though

**Comment by dima74** [comment]
@MightyPork sorry, I still don't understand how we get compile error after move. `use foo::Json;` in `main.rs` indeed stays unchanged, but `pub use serde_json::Value as Json;` in `foo.rs` also stays unchanged, isn't it? Topic of removing unused imports after move is [a separate issue which is actually not easy to solve](https://github.com/intellij-rust/intellij-rust/pull/6392)

**Comment by MightyPork** [comment]
You're right, my bad. I didn't actually try compiling it. The editor window auto-scrolled one line down so the import was hidden. I think this happens when imports are auto-added? Confused me more than once...

Maybe @jaupe can give a better example?

**Comment by MightyPork** [comment]
Just to add: I just tried to reproduce my original problem I mentioned above, with renames within a workspace. It does not happen anymore :+1:
