### ISSUE TITLE
Unexpected multi resolve with glutin crate

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#5961]
## Environment

* **IntelliJ Rust plugin version:** 0.3.129.3287-202-nightly
* **Rust toolchain version:** 1.45.0 (5c1f21c3b 2020-07-13) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.2.1 Preview Ultimate Edition (IU-202.6948.5)
* **Operating system:** macOS 10.13.6

## Problem description
The plugin shows two items as a result of name resolution of `glutin::event_loop` path. That leads to lack of name resolution for all items from this module (of course, it's expected because of multi resolve of `event_loop` module itself)
![image](https://user-images.githubusercontent.com/2539310/90617105-f6714e00-e216-11ea-9b63-953a70ee63a2.png)

It's interesting that both name resolution results are the same

This bug was introduced in [`v128`](https://github.com/intellij-rust/intellij-rust/milestone/36) release. Everything works fine with `v127` 

## Steps to reproduce
`Cargo.toml`
```toml
[dependencies]
glutin = "0.24"
```

`main.rs`
```rust
use glutin::event_loop::EventLoop;

fn main() {}
```

**Comment by Kobzol** [comment]
Bisected this to https://github.com/intellij-rust/intellij-rust/commit/bcdc01d9d48f7ab1150b94f743c530a77a95e2b8.

**Comment by Undin** [comment]
> Bisected this to bcdc01d.

@Kobzol oh, thanks!

**Comment by Undin** [comment]
CC @SergeevPavel
