### ISSUE TITLE
'File is not included in module tree' - again

### ISSUE THREAD

**Issue by inzanez** [intellij-rust/intellij-rust#5962]
## Environment

* **IntelliJ Rust plugin version:** latest stable && nightly
* **Rust toolchain version:** 1.47.0-nightly
* **IDE name and version:** CLion 2020.2
* **Operating system:** Linux

## Problem description
In a large project with a workspace and multiple crates, I get the warning
`File is not included in module tree, analysis is not available` for every file in the project.

I tried invalidating the cache and restarting etc. but that did not help. I figured out that the latest `0.2` version just before the jump `0.3` works and analyzes the files correctly. However, the `0.2` version doesn't happen to have the fix that's required for the current nightly version, as paths changed. So either I'm missing the `stdlib` sysroot with the old verison, or have non-analyzed files with the `latest stable` or `nightly` plugin version.

## Steps to reproduce
`git clone https://github.com/tokio-rs/tokio`
open the project in CLion.

**Comment by ImSingee** [comment]
I think this should be marked as "bug"

**Comment by vlad20012** [comment]
Discussed with @inzanez in [another issue](https://github.com/intellij-rust/intellij-rust/issues/5861#issuecomment-683266226) that his case is very specific and isn't fully described in this issue. 

@ImSingee do you experiencing similar to this. Try to invoke `File | Invalidate Caches / Restart` and if it doesn't help, please, open another issue
