### ISSUE TITLE
Duplicate build target found

### ISSUE THREAD

**Issue by coderplay** [intellij-rust/intellij-rust#597]
Just randomly clone a rust project from github, loaded it with intellij rust. Found this error:
```
Project 'tokio' failed to update. Cargo execution failed (exit code 101). /usr/local/bin/cargo metadata --verbose stdout : stderr : error: unable to get packages from source Caused by: failed to parse manifest at `/Users/minzho/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.73/Cargo.toml` Caused by: duplicate build target found: `/Users/minzho/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.73/src/lib.rs
```

**Comment by matklad** [comment]
Seems like you are using a nightly toolchain which has a bug in Cargo which prevents regex crate from building. This is already fixed, so you need to update your nightly toolchain. 

See https://internals.rust-lang.org/t/cargo-regression-regex-crate-broken-on-2016-08-05-nightly/3819 for more details.
