### ISSUE TITLE
Duplicate rust warning "unused import"

### ISSUE THREAD

**Issue by qiujiangkun** [intellij-rust/intellij-rust#5971]
## Environment

* **IntelliJ Rust plugin version:**
0.3.128.3278-202

* **Rust toolchain version:**
rustup 1.22.1 (2020-07-08)
cargo 1.45.1 (f242df6ed 2020-07-22)
rustc 1.45.2 (d3fb005a3 2020-07-31) stable

* **IDE name and version:**
CLion 2020.2
Build #CL-202.6397.106, built on July 28, 2020
* **Operating system:**
OS: Manjaro 20.1 Mikah
Kernel: x86_64 Linux 5.4.52-1-MANJARO
## Problem description
Warnings like "unused import" show multiple times when click on "build" button
```log
 Compiling test_one v0.1.0 (/home/jack/Dev/test_one)
warning: unused import: `std::str`
 --> src/main.rs:1:5
  |
1 | use std::str;
  |     ^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `std::str`
 --> src/main.rs:1:5
  |
1 | use std::str;
  |     ^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: 1 warning emitted

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.24s

```
```rust
use std::str;

fn main() {
}
```
I tried commands like `cargo build`, `cargo build --verbose`, `cargo run` and `cargo run --verbose`, none of which duplicate the warning.
Clicking on "run" button will only show the warning once.

## Steps to reproduce
1. create a new Cargo project
2. paste in the code shown above
3. click on "build" button

## Relevant information
https://github.com/rust-lang/rls/issues/907
I'm sure that rust-lang has fixed it a few years ago, but it is recurring now in Clion. It probably has something to do with the procedure of building.

**Comment by mchernyavsky** [comment]
> I tried commands like `cargo build`, `cargo build --verbose`, `cargo run` and `cargo run --verbose`, none of which duplicate the warning.

Try to run `cargo build --all --all-targets`.

**Comment by qiujiangkun** [comment]
> > I tried commands like `cargo build`, `cargo build --verbose`, `cargo run` and `cargo run --verbose`, none of which duplicate the warning.
> 
> Try to run `cargo build --all --all-targets`.
It shows
```text
 Compiling test_one v0.1.0 (/home/jack/Dev/test_one)
warning: unused import: `std::str`
 --> src/main.rs:1:5
  |
1 | use std::str;
  |     ^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `std::str`
 --> src/main.rs:1:5
  |
1 | use std::str;
  |     ^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: 1 warning emitted

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.24s
```

**Comment by mchernyavsky** [comment]
You can disable `Compile all project targets if possible` option in `Preferences | Languages & Frameworks | Rust | Cargo` to remove `--all-targets` flag from the command line. Or you can set `org.rust.cargo.build.tool.window` variable to true in `Action | Registry...` to build only the current target.
