### ISSUE TITLE
The actual command of the "Build" button doesn't change according to cargo command

### ISSUE THREAD

**Issue by qiujiangkun** [intellij-rust/intellij-rust#5972]
For example,
I have three binary cargo crates in the same directory as follows:
```text
project
| -- c1
| -- c2
| -- c3
```
And I have three commands in Run/Debug configuration
- Run c1 `run --package c1 --bin c1`
- Run c2 `run --package c2 --bin c2`
- Run c3 `run --package c3 --bin c3`

I choose `Run c1` and click on Build button, then c1 compiles. It's what is supposed to happen.
However, I choose `Run c2` and click on Build button, then c1, instead of c2, compiles. It should compile c2 instead.
So do c3.

Moreover, I cannot change the arrangement of crates in Crate Panel

**Comment by mchernyavsky** [comment]
What command is shown in the Run Tool Window when you click the Build button for `Run c2`?

![image](https://user-images.githubusercontent.com/6079006/90829560-a4304a00-e348-11ea-8e32-3a139a864033.png)

If it's the same as mine, try to set `cargo.build.tool.window.enabled` variable to true in the registry (`Actions > Registry...`).

**Comment by qiujiangkun** [comment]
> What command is shown in the Run Tool Window when you click the Build button for `Run c2`?
> 
> ![image](https://user-images.githubusercontent.com/6079006/90829560-a4304a00-e348-11ea-8e32-3a139a864033.png)
> 
> If it's the same as mine, try to set `cargo.build.tool.window.enabled` variable to true in the registry (`Actions > Registry...`).

Yeah, if  `cargo.build.tool.window.enabled` is false, then my result is the same as yours:
```log
/usr/bin/cargo build --color=always --all --all-targets
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s

Process finished with exit code 0
```
If it's true, it works normally
```log
/usr/bin/cargo build --color=always --package c2 --bin c2 --message-format=json
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s

Process finished with exit code 0
```
