### ISSUE TITLE
Run tests with coverage results in "the linked panic runtime `panic_unwind` is not compiled with this crate's panic strategy `abort`" error

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#5973]
## Environment

* **IntelliJ Rust plugin version:** 0.3.128.3278-202
* **Rust toolchain version:** 1.47.0-nightly (792c645ca 2020-08-17) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.2 (CL-202.6397.106)
* **Operating system:** macOS 10.15.6

## Problem description

Running tests with basic Run works fine, but Run with coverage fails with the following error

```
Testing started at 22:11 ...
/Users/jetbrains/.cargo/bin/cargo +nightly test --color=always --all-features --no-fail-fast -- -Z unstable-options --format=json --show-output
   Compiling proc-macro2 v1.0.19
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.38
   Compiling quote v1.0.7
   Compiling flow_impl_derive v0.10.0 (/Users/jetbrains/git/flow/flow_impl_derive)
error: the linked panic runtime `panic_unwind` is not compiled with this crate's panic strategy `abort`

error: aborting due to previous error

error: could not compile `flow_impl_derive`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

Process finished with exit code 101
```

## Steps to reproduce

1. Open https://github.com/andrewdavidmackenzie/flow/tree/master/flow_impl_derive
2. Run `test --all-features` cargo command with coverage

**Comment by lancelote** [comment]
Based on a user report in support.

**Comment by andrewdavidmackenzie** [comment]
I doubt it maters but just FYI - in my original report it was found in 
```
IntelliJ IDEA 2020.2 (Ultimate Edition)
Build #IU-202.6397.94, built on July 27, 2020
Licensed to Red Hat UK Limited / Andrew Mackenzie
Subscription is active until July 25, 2021
Runtime version: 11.0.7+10-b944.20 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
```

but it seems you were able to reproduce it in CLion!

**Comment by mchernyavsky** [comment]
The problem is, when we `Run with Coverage`, we implicitly add the environment variables mentioned [here](https://github.com/mozilla/grcov#example-how-to-generate-gcda-files-for-a-rust-project) including `-Cpanic=abort`, but it looks like `-Cpanic=abort` can't be used in proc-macro libs. Previously, we used `-Zno-landing-pads` instead of `-Cpanic=abort`, but recently it has been [removed](https://github.com/rust-lang/rust/pull/70175) from cargo. I will ask somebody from cargo if there is a workaround.

**Comment by Amanieu** [comment]
If you use `--target` then RUSTFLAGS only applies to crates built for the target, which doesn't include proc macros. So the workaround is to just use `--target x86_64-unknown-linux-gnu` to "cross-compile" to the default target.
