### ISSUE TITLE
Link source code references in wasm-pack output

### ISSUE THREAD

**Issue by MakotoE** [intellij-rust/intellij-rust#5991]
## Environment

* **IntelliJ Rust plugin version:** 0.3.129.3308-202
* **Rust toolchain version:** rustc 1.47.0-nightly (8e21bd063 2020-08-14)
* **IDE name and version:** WebStorm 2020.2
* **Operating system:** Debian Buster

The wasm-pack configuration is very useful and I'm very thankful for it. It would be really nice if source code references are hyperlinked to what it is referencing. Currently, the output does not provide a link to the referenced source code location, so I must find it myself. (Command value for wasm-pack configuration is `build`)

![wasm-pack output](https://user-images.githubusercontent.com/36318069/91128651-6dff0d00-e65d-11ea-85b0-9a5723556a70.png)

When I click the Build button, source code references are linked. It would be helpful for the wasm-pack output to do the same.

![Build output](https://user-images.githubusercontent.com/36318069/91128806-b3bbd580-e65d-11ea-9897-7bdce6faebdc.png)

**Comment by avrong** [comment]
Hello. Soon we will finish and merge #5939. It uses cargo build task in a separate window which supports the links you mentioned.

With build tool window enabled in experimental features, in terms of error it will look like this:
<img width="1103" src="https://user-images.githubusercontent.com/6342851/91140256-3ec9b980-e6b8-11ea-84cf-4c9710360511.png">
