### ISSUE TITLE
Get rid of the secret jars in `lib/gk`

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#60]
Relaying on the close source fork of the grammar kit is a code smell.

**Comment by Turbo87** [comment]
Apart from the fact that GrammerKit doesn't seem to be published on any Maven repository, what are the differences to the official release?

**Comment by alexeykudinkin** [comment]
@Turbo87 you can now see them in our fork: intellij-rust/Grammar-Kit.

**Comment by alexeykudinkin** [comment]
Now, we're particularly bounded by those guys: JetBrains/Grammar-Kit#82, JetBrains/Grammar-Kit#83, JetBrains/Grammar-Kit#84, JetBrains/Grammar-Kit#85
