### ISSUE TITLE
Can't find async function

### ISSUE THREAD

**Issue by TheLudlows** [intellij-rust/intellij-rust#6006]
## Environment

* **IntelliJ Rust plugin version:** 0.3.130.3311-201-nightly
* **Rust toolchain version:** 1.47.0-nightly (5180f3da5 2020-08-23) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.1.3 (CL-201.8743.17)
* **Operating system:** macOS 10.13.6

## Problem description

![image](https://user-images.githubusercontent.com/6505554/103212287-6f965580-491b-11eb-8dea-c7f0c1a334df.png)

```Rust
async fn learn_sing() {
    println!("learn sing")
}

async fn sing_song() {
    println!("sing song")
}

async fn dance() {
    println!("dance")
}

async fn sing() {
    learn_sing().await;
    sing_song().await
}

async fn all() {
    futures::join!(sing(), dance());
}

#[test]
fn start() {
    futures::executor::block_on(all())
}
```

## Steps to reproduce

but it's can run successfully

**Comment by vlad20012** [comment]
Hmm, looks like a bug in `futures::join` macro expansion. Could you please specify the version of the `futures` crate?

By the way, your CLion 2020.1.3 is outdated, consider updating to 2020.2.1 (this most likely doesn't related to the issue)

**Comment by Undin** [comment]
@TheLudlows As I see, you created this issue via `Create New Issue` plugin action. It's great!
This action also can put code example into issue template - just selected necessary code in editor and invoke this action

**Comment by TheLudlows** [comment]
> Hmm, looks like a bug in `futures::join` macro expansion. Could you please specify the version of the `futures` crate?
> 
> By the way, your CLion 2020.1.3 is outdated, consider updating to 2020.2.1 (this most likely doesn't related to the issue)

`furures` version is 0.3.4

**Comment by TheLudlows** [comment]
> @TheLudlows As I see, you created this issue via `Create New Issue` plugin action. It's great!
> This action also can put code example into issue template - just selected necessary code in editor and invoke this action

Ok, Thanks

**Comment by vlad20012** [comment]
Hmm, the original code snipped was lost. But I see that a macro `join` is not resolved:
```
fn main() {
    futures::join!();
}
```

**Comment by dima74** [comment]
#6566 will fix resolve of `futures::join!()` macro. But `futures::join` [uses procedural macro internally](https://github.com/rust-lang/futures-rs/blob/7ce5ce8349b38803f218bfbafd0a5f1e102bbaa0/futures-util/src/async_await/join_mod.rs#L97), so original issue will still persist

**Comment by mili-l** [comment]
see https://github.com/intellij-rust/intellij-rust/pull/9729
