### ISSUE TITLE
Indexing never stops on the rustc project

### ISSUE THREAD

**Issue by vandenheuvel** [intellij-rust/intellij-rust#6007]
## Environment

* **IntelliJ Rust plugin version:** 0.3.129.3308-202
* **Rust toolchain version:** 1.47.0-nightly (f44c6e4e2 2020-08-24) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.2 (CL-202.6397.106)
* **Operating system:** Linux 5.8.3-arch1-1

## Problem description
Analysis never completes. The "Indexing" indicator is active in the editor window.

## Steps to reproduce

* Clone https://github.com/rust-lang/rust
* Remove any previous `.idea/` folder, invalidate caches, restart
* **Create build folder by running `x.py check`**, about 7 GB large
* Open the project
* In a background task, files are indexed, indices updated, process completes, memory about 1.2 of 2 GB
* Open any rust file
* `Indexing` appears in the top right corner of the editor window
* Changes to `Syncing` after a second or two
* 25% of 8 (4x2) cores are used, memory usage of the entire java process is about 2.3 GB, IDE indicates about 1.3 of 2 GB
* Changes back to `Indexing` again after a minute or so, this stays the same for many hours.
* 25% of 8 (4x2) cores are used, memory usage of the entire java process is about 2.3 GB

## Logs

[clion-logs-20200826-141137.zip](https://github.com/intellij-rust/intellij-rust/files/5129729/clion-logs-20200826-141137.zip)

**Comment by vlad20012** [comment]
Could you, please, attach your logs to the issue? (you can collect them with `Help | Collect Logs and Diagnostic Data` action in the IDE)

**Comment by vandenheuvel** [comment]
@vlad20012 I added a log to the original description.

**Comment by vandenheuvel** [comment]
I have now found out that, even with a `<excludeFolder url="file://$MODULE_DIR$/build" />` line in `.idea/rust.iml`, the above occurs.

**Comment by vandenheuvel** [comment]
If you're in this situation, moving away the `build/` folder gets the analysis process to continue (by syncing). You can then put that folder back after analysis has completed: as one would hope, a resync happens and then analysis works.

**Comment by vlad20012** [comment]
Try this plugin version. It is built from #6008 branch. ([install plugin from disk instructions](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk))
[intellij-rust-0.3.130.SNAPSHOT-202-dev.zip](https://github.com/intellij-rust/intellij-rust/files/5130067/intellij-rust-0.3.130.SNAPSHOT-202-dev.zip)

**Comment by vandenheuvel** [comment]
@vlad20012 and I agree that this plugin version doesn't solve the problem. @vlad20012 also found out that it works in IDEA but not in CLion.

**Comment by vlad20012** [comment]
This is a CLion issue https://youtrack.jetbrains.com/issue/CPP-21654
It's going to be fixed in the next build (2020.2.1?)

**Comment by vandenheuvel** [comment]
@vlad20012 why do you think that these are the same?

**Comment by vandenheuvel** [comment]
Good luck: 2020.2.1 just came out. These bugs probably are the same; the problem is now fixed. @vlad20012 thanks a lot for your help!
