### ISSUE TITLE
Code completion not working for standard library

### ISSUE THREAD

**Issue by mcon** [intellij-rust/intellij-rust#6016]
## Environment

* **IntelliJ Rust plugin version:**
0.3.129.3308-201
* **Rust toolchain version:**
1.46.0
* **IDE name and version:**
CLion 2020.1
Build #CL-201.6668.126, built on April 9, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-106-generic
GC: ParNew, ConcurrentMarkSweep
* **Operating system:**
Ubuntu 2018.04.4

## Problem description
No methods corresponding to vec appear for autocompletion - my stdlib is set up correctly (visible in the LHS bar).
![broken_intellisense](https://user-images.githubusercontent.com/3117092/91538720-26ec7280-e910-11ea-87aa-52a4e2204810.jpg)
This issue doesn't seem to be specific to vec, there are plenty of other stdlib types that don't seem to autocomplete.

## Steps to reproduce
- Create simple vector
```
fn main() {
    let mut vec = Vec::new();
    vec.push(1);
    vec.push(2);
}
```
- Try `vec.` and observe the autocomplete

**Comment by vlad20012** [comment]
Hello!
Looks really weird. Let's try to invoke `File | Invalidate Caches / Restart` action.

**Comment by mcon** [comment]
Magic, that seems to have worked @vlad20012 - thanks!
