### ISSUE TITLE
No type resolution when injecting Rust code into templating language

### ISSUE THREAD

**Issue by Mcat12** [intellij-rust/intellij-rust#6026]
Hello, I'm working on a plugin for [LALRPOP], a parser-generator for Rust: https://github.com/Mcat12/intellij-lalrpop

I'm having some trouble injecting Rust code into parser files. I think I need to tell IntelliJ-Rust to include the file as part of the crate, so I thought to make an issue here. I've looked into the Rust plugin code, such as the injector for doc tests, but haven't found anything that helps.

**Example** (from [here](https://github.com/Mcat12/mips/blob/b588cf6b80bc10b82ecc514e85385cc3238ab7a7/mips-assembler/src/parser.lalrpop)):
![image](https://user-images.githubusercontent.com/4417660/91646392-a6fffe80-ea1c-11ea-9fd6-f1deb13128ca.png)
![image](https://user-images.githubusercontent.com/4417660/91646380-96e81f00-ea1c-11ea-8024-76d06b3946ca.png)

The `OpCode` type is defined in `crate::ast` and my language injector outputs the following code for the `"add"` terminal (code [here](https://github.com/Mcat12/intellij-lalrpop/blob/2434cb860c03d3935d815f88cae0ba6269eb026c/src/main/kotlin/com/mdrobnak/lalrpop/injectors/LalrpopRustInjector.kt#L25-L31)):
```rust
use crate::ast::*;

fn __intellij_lalrpop() -> OpCode {
    OpCode::Add
}
```

Unfortunately `OpCode` is not recognized. In fact, there are no suggestions beyond the items declared in the file:
<p align="center">
<img src="https://user-images.githubusercontent.com/4417660/91646373-7029e880-ea1c-11ea-945d-5d1d0800a04a.png">
<br>
<img src="https://user-images.githubusercontent.com/4417660/91646404-cac34480-ea1c-11ea-817b-e5d98bc29732.png">
</p>

As a side note, auto-complete never finishes and uses quite a bit of CPU doing "nothing":
<p align="center">
<img src="https://user-images.githubusercontent.com/4417660/91646416-ff370080-ea1c-11ea-8364-b86c8a514f05.png">
</p>

Is there something I need to do to tell the Rust plugin to consider these injected files/snippets as part of the current crate? There isn't much documentation out there for language injection, so hopefully this is the right place for this question.

[LALRPOP]: https://github.com/lalrpop/lalrpop

**Comment by vlad20012** [comment]
Well, there's no idiomatic way. We definitely should provide some API for this. But I think it's possible to do it using some deprecated and internal APIs.

When `doneInjecting` is invoked, it's possible to retrieve the injected PSI (using a deprecated internal API):
`val psi = com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.getCachedInjectedFileWithLanguage(context, RsLanguage)`

Then you can use `RsExpandedElement.setContext` to set a "fake parent" for the injected elements. You can't invoke `setContext` on the PsiFile itself, but you can invoke it on its childer, so it should look like this:
```
val psi = InjectedLanguageUtil.getCachedInjectedFileWithLanguage(context, RsLanguage)
for (child in psi.childrenOfType<RsExpandedElement>() {
    child.setContext(some context)
}
```
(note that I'm going to remove the `setContext` extension, so, it can also we treated as deprecated)

To make it work as expected, you may want to introduce an inline module in the injection (to unite __intellij_lalrpop function and `use`s):

```
mod __intellij_lalrpop {
    use crate::ast::*;

    fn __intellij_lalrpop() -> OpCode {
        OpCode::Add
    }
}
```

What should be used as an argument to `setContext`? Well, it depends on how the name resolution is actually working for this parser generator. It should some rust PSI element in the crate where the parser generator is used. You can start with a crate root file.

> As a side note, auto-complete never finishes and uses quite a bit of CPU doing "nothing":

This most likely unrelated. You can analyze what the plugin is actually doing with a profiler (I suggest IDEA profiler!) or by multiple `jstack` invocations. If you're interested.

**Comment by Mcat12** [comment]
Thanks for the quick and extensive response! I'll try out your suggestions and report back. Also, I can help work on a more stable/idiomatic API for this if you're interested.

**Comment by Mcat12** [comment]
Ok, this works very well. Let me know what I can do to help make a stable interface for this when that times comes!
