### ISSUE TITLE
New line handling in parameters

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#603]
Opening a new line in parameter list shold properly indent the caret:

Before: 

```
    pub fn configure(&self,
                     verbose: u32,
                     quiet: Option<bool>,
                     color: &Option<String>,<caret> 
                     frozen: bool,
                     locked: bool) -> CargoResult<()> {
```

After as it should be:

```
    pub fn configure(&self,
                     verbose: u32,
                     quiet: Option<bool>,
                     color: &Option<String>,
                     <caret> 
                     frozen: bool,
                     locked: bool) -> CargoResult<()> {
```

What currently happens:

```
    pub fn configure(&self,
                     verbose: u32,
                     quiet: Option<bool>,
                     color: &Option<String>,
        <caret> 
                     frozen: bool,
                     locked: bool) -> CargoResult<()> {
```

**Comment by mkaput** [comment]
I think this might be parser recovery issue (as usual): IntelliJ inserts `IntelliJIdeaRulezzzz` string in place of caret when determining indentation.

**Comment by matklad** [comment]
>I think this might be parser recovery i

Thanks! I didn't have to spend two days figuring it was the parser issue, and instead I've spend the last two days fixing the parser (https://github.com/intellij-rust/intellij-rust/commit/c887fda2d73b5f0d08fac4c16b9060c46ad22c60) :)

**Comment by matklad** [comment]
Seems like this is not only parser recovery. For this branch (https://github.com/matklad/intellij-rust/tree/param-recovery)

I get

```
fn foo(x: i32,<caret>
       y: i32) {}
```

=>

```
fn foo(x: i32, 
    <caret>
       y: i32) {}
```

**Comment by mkaput** [comment]
There is no auto-alignment implemented (yet): https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/formatter/blocks/RustFmtBlock.kt#L90-L91
