### ISSUE TITLE
Add an Gradle task to update cargo options in `Run anything` and cargo command completion provider

### ISSUE THREAD

**Issue by mchernyavsky** [intellij-rust/intellij-rust#6058]

**Comment by avrong** [comment]
I was thinking about this recently.

What if we could make a full-featured DSL for the commands and options description, and then regenerate it from time to time using [cargo commands docs](https://github.com/rust-lang/cargo/tree/master/src/doc/man). It already has some kind of grouping using templates and special tags for the options.

Docs also have full multi-sentence descriptions, but for most of the cases, I think we could just take the first one for the short description in `Run Anything`.

For the special cases like `--bin`, `--test` or `--target`  where we can also provide a suggestion of option depending on the context, there can be another custom completion that will work simultaneously with the generated one.
