### ISSUE TITLE
Feature request: Run nightly rustfmt on save

### ISSUE THREAD

**Issue by qiujiangkun** [intellij-rust/intellij-rust#6061]
Currently I am working on a project with stable rust, and I would like to use nightly version of rustfmt.

- Nightly rustfmt supports more formatting options and produce prettier results.
- Stable rust project compiles on all of stable, unstable, and nightly rustc.

In terminal, I can easily use `+nightly` to switch to nightly version if I have nightly rust installed.
```log
➜  rustfmt +nightly --version
rustfmt 1.4.20-nightly (48f6c32 2020-08-09)
➜  rustfmt --version  
rustfmt 1.4.17-stable (8a93416 2020-07-20)
```

Moreover, there're ignored(by the plugin) warnings if I use nightly configurations for stable rustfmt. Mixing up nightly and stable versions of rustfmt has messed up my git history, since other developers may accidentally use nightly version.

https://github.com/rust-lang/rustfmt/issues/4412
This issue was for this problem. I thought it was a bug of rustfmt, but it turns out that I mistakenly simply ran `rustfmt` and intellij-rust called stable rustfmt and ignored the warning at the same time.

So, I would like intellij-rust to give an checkbox like "Use nightly rustfmt" in the settings, or give an option textbox for customizing arguments for "Run rustfmt on save".

**Comment by Yuri6037** [comment]
If you are on Linux, there is a workarround:

```
mv ~/.cargo/bin/rustfmt ~/.cargo/bin/rustfmt-old
ln -s ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustfmt ~/.cargo/bin/
```
