### ISSUE TITLE
is it a quick way to add dbg! macro for the selected text?

### ISSUE THREAD

**Issue by Kilerd** [intellij-rust/intellij-rust#6062]
while debugging, I found that adding a dbg macro for selected expression or variable cost me a lot times. first I need to cut the selection, then type `dbg!()`, then paste what I cut.

I think it would be better if there is a shortcut for this operation?

**Comment by Undin** [comment]
There is `dbg` postfix completion
Just type `.dbg` after expression and select necessary expression if several are available
Note, there is `Remove dbg!` intention to remove `dbg!` macro from your expression

![2020-09-04 10 49 43](https://user-images.githubusercontent.com/2539310/92214277-9c21ef80-ee9c-11ea-9333-01cce5dde74d.gif)

**Comment by Kilerd** [comment]
thanks, and yep that's what I need.

sorry for not noticing the release note.
