### ISSUE TITLE
Support cargo workspaces

### ISSUE THREAD

**Issue by alexbool** [intellij-rust/intellij-rust#607]
The name says it all :)
I'll just leave it here https://github.com/rust-lang/rfcs/blob/master/text/1525-cargo-workspace.md

**Comment by matklad** [comment]
Already in progress: https://github.com/rust-lang/cargo/issues/3003

**Comment by matklad** [comment]
Workspaces are supported with the latest alpha/nighltly IntelliJ Rust and yesterday's Cargo
