### ISSUE TITLE
cfg_if::cfg_if! not resolved in stdlib

### ISSUE THREAD

**Issue by CraftSpider** [intellij-rust/intellij-rust#6081]
## Environment

* **IntelliJ Rust plugin version:** 130
* **Rust toolchain version:** Nightly
* **IDE name and version:** CLion / IntelliJ, 2020.2.1
* **Operating system:** Windows

## Problem description

The macro path `cfg_if::cfg_if!` isn't resolved in the standard library, both using it from a separate project, and if your project is the rust-lang/rust directory. This means that most platform-specific implementations aren't handled correctly, so there is both no auto-correct for things like `MetadataExt` on unix, and the submodules inside aren't resolved as part of the std cargo project, meaning bad code resolution for working on them

## Steps to reproduce

Simply import any rust project, and look under `std/src/sys/mod.rs` on the dependencies

**Comment by josueeduardo** [comment]
This issue has been very annoying for me as I use `std::os::`* a lot in my current project, definitely keeping an eye on it ! :eyes:
