### ISSUE TITLE
TOML plugin: support folding

### ISSUE THREAD

**Issue by toaster** [intellij-rust/intellij-rust#6083]
## Environment

* **IntelliJ TOML plugin version:** 0.2.130.3337-202
* **IDE name and version:** RubyMine 2020.2
* **Operating system:** MacOS 10.15

## Problem description

I use a larger TOML file for documentation.
Currently I switch to VisualStudio Code with the “Even Better TOML” plugin for editing it because navigating the file is quite hard without folding.
It would be very helpful if the TOML plugin would support folding in a similar way as VSC does.
VSC without plugins still support folding based on indentation. With the aforementioned TOML plugin it supports folding based on TOML structure.

How it looks like in VSC with TOML extension:

![vsc_toml_folding](https://user-images.githubusercontent.com/73959/92439666-8a499080-f1ab-11ea-8612-ac10d6ca9196.gif)

**Comment by Kobzol** [comment]
I added a basic folding implementation in https://github.com/intellij-rust/intellij-rust/pull/6084. Note that it will probably work a bit differently than in VSCode, as every table and array table are separate elements, so you cannot nest an array table inside another table or vice versa. Therefore only arrays and inline tables can be nested recursively.

**Comment by Xtrem532** [comment]
@Kobzol Will this Implementation support `#region` comments for folding? IF no, is support for that also possible?

**Comment by Kobzol** [comment]
Hmm, I only vaguely remember that from Rider/Visual Studio. Is it common to use that for TOML? @Undin is there some platform support for `#region` comments in IntelliJ?

**Comment by Undin** [comment]
@Kobzol Yep, IntelliJ platform supports custom region folding. And this feature is even implemented for Rust.
See #3005 as example how it was implemented for Rust

**Comment by Kobzol** [comment]
@Xtrem532 custom fold regions should be supported with https://github.com/intellij-rust/intellij-rust/pull/6084.
