### ISSUE TITLE
Unresolved reference

### ISSUE THREAD

**Issue by imkow** [intellij-rust/intellij-rust#6088]
## Environment
latest plugin
latest rust toolchain nightly

## Problem description
https://github.com/google/tarpc/blob/master/example-service/src/server.rs#L72 // unresolved reference `serve`

**Comment by Undin** [comment]
@imkow thanks for your feedback!
JFTR there is `Help | Create New Issue` action to create an issue draft in our repo with filled `Environment` section. Also, if you select some code in the editor, the corresponding text will be added in `Steps to reproduce` section

**Comment by imkow** [comment]
thanks
