### ISSUE TITLE
Cannot select path to Standard library

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#609]
I have made a very simple `main.rs` and am trying to get some autocomplete on the standard library.

When I open `Settings -> Languages & Frameworks -> Rust` the file browser button for the Standard library is disabled.

![no-std-lib-browser](https://cloud.githubusercontent.com/assets/10340167/17757717/16ac206e-64b7-11e6-9833-115874ad5f4e.png)

Platform:
- Windows 10 x64
- Rust 0.10 x86_64-pc-windows-gnu
- PyCharm 2016.2.2
- intellij-rust 0.0.1.903

**Comment by matklad** [comment]
We support only Cargo based projects at the moment, so you need to provide a `Cargo.toml` as well.

**Comment by johnthagen** [comment]
I see that now in the Troubleshooting section: https://intellij-rust.github.io/docs/troubleshooting.html

Perhaps it's worth mentioning somewhere in the Quick Start Guide (for newbies like me): https://intellij-rust.github.io/docs/quick-start.html

Or in the UI it could state `N/A Required`?

Otherwise, I think the issue can be closed.  Thanks!

**Comment by johnthagen** [comment]
When following the Quick Start properly, this is not an issue.
