### ISSUE TITLE
Can't set LLDB path

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#6097]
Original issue: https://youtrack.jetbrains.com/issue/CPP-22088

## Environment

* **IntelliJ Rust plugin version:** 0.3.131.3327-202-nightly
* **Rust toolchain version:** 1.46.0 (04488afe3 2020-08-24) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.2.2 Preview Ultimate Edition (IU-202.7319.5)
* **Operating system:** macOS 10.15.3

## Problem description
I can't type in the field, If I choose the path in Finder, nothing happens. Applying the configurable changes nothing.
![image](https://user-images.githubusercontent.com/4854600/92724203-e6124600-f372-11ea-8057-7afa9700a0d0.png)

**Comment by Undin** [comment]
The described behavior is expected so I don't understand what we should do here. Just press "Download" button to download LLDB and the field will be filled automatically

**Comment by Undin** [comment]
Note, there is #5915 that describes problem with debugger loading. So I think this issue can be closed
