### ISSUE TITLE
`Add remaining patterns` should be available inside match body

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#6124]
## Environment

* **IntelliJ Rust plugin version:** 0.3.132.3356-202-nightly
* **Rust toolchain version:** 1.46.0 (04488afe3 2020-08-24) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2020.2.2 Ultimate Edition (IU-202.7319.50)
* **Operating system:** Linux 5.4.0-47-generic

## Problem description

#5720 removed `Fill match arms` intention. Now match filling is only available as a quick fix for `Match must be exhaustive` annotation. The issue is that `Fill match arms` intention was available inside `match` body while the fix is not. It is a usual workflow when you type `match foo {` and then applying the intention. The need to move the caret to `match` keyword is annoying.

## Steps to reproduce

`Add remaining patterns` should be available here:

```rust
fn main() {
    match Some(1) {
        /*caret*/
    }
}
```

**Comment by Undin** [comment]
I'm working on it
