### ISSUE TITLE
Wrong return places highlighting

### ISSUE THREAD

**Issue by maxwase** [intellij-rust/intellij-rust#6130]
## Environment

* **IntelliJ Rust plugin version:** 0.3.130.3337-202
* **Rust toolchain version:** rustc 1.46.0 (04488afe3 2020-08-24) latest stable
* **IDE name and version:** CLion 2020.2.1
* **Operating system:** Fedora 31
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.13.2
Kernel Version: 5.7.15-100.fc31.x86_64
OS Type: 64-bit
Processors: 12 × Intel® Core™ i7-8700 CPU @ 3.20GHz
Memory: 31.1 GiB of RAM

CLion 2020.2.1
Build #CL-202.6948.80, built on August 25, 2020
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.7.15-100.fc31.x86_64
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 12
Registry: run.processes.with.pty=TRUE, documentation.show.toolbar=true, ide.allow.merge.buttons=false, search.everywhere.settings=true, debugger.watches.in.variables=false, cidr.max.intellisense.file.length=600000
Non-Bundled Plugins: name.kropp.intellij.makefile, org.jetbrains.plugins.localization, org.toml.lang, tanvd.grazi, izhangzhihao.rainbow.brackets, org.rust.lang, rs.pest
Current Desktop: KDE

## Problem description
False highlighting of the return places from a function with local constants in it.

![image](https://user-images.githubusercontent.com/23321756/93509248-2308aa80-f928-11ea-815a-adff3cad52c6.png)

## Steps to reproduce
Create a new rust project and insert this code:
```
fn main() -> std::io::Result<()> {
    const HIGHLIGHT_CONST: &str = "highlight";
    return Ok(());
}
```
P.S.
All is ok without `return` keyword.

**Comment by dima74** [comment]
Looks like it was fixed some time ago. @maxwase feel free to reopen if you find any error

![image](https://user-images.githubusercontent.com/6505554/181083586-0f03d3bb-650d-4184-b0d6-c16152f5e5d4.png)
