### ISSUE TITLE
Error handling nested unnamed struct fields

### ISSUE THREAD

**Issue by qiujiangkun** [intellij-rust/intellij-rust#6154]
I have the following code which compiles.
```rust
struct Baz{val: i32}
struct Bar(Baz);
struct Foo(Bar);

fn main() {
    let x = Foo(Bar(Baz{val:1}));
    x.0.0.val;
}
```
However, IntelliJ-Rust sees it as an error.
![image](https://user-images.githubusercontent.com/33482468/94046571-70db5200-fe03-11ea-925e-7a918f6e68e0.png)

Since rustfmt has the same behavior, it seems like it's an error from the Rust language server or so, which uses a slightly different tokenizer from rustc. But I'm not very sure what has actually caused the problem. Please help me open an issue in a proper place, or tell me where to go.

**Comment by vlad20012** [comment]
Duplicate #6029

**Comment by Undin** [comment]
@qiujiangkun FYI there is `Help | Create New Issue` action to create an issue template in our repo which fills all necessary fields in `Environment` section that can be very helpful sometimes. Also, if you select rust code in the editor and invoke this action, it will be placed in ` Steps to reproduce` section
