### ISSUE TITLE
Non existent errors being marked as errors

### ISSUE THREAD

**Issue by medakk** [intellij-rust/intellij-rust#6160]
## Environment

* **IntelliJ Rust plugin version:** 0.3.131.3366-202
* **Rust toolchain version:** rustc 1.46.0 (04488afe3 2020-08-24)
* **IDE name and version:** CLion 2020.2.3
* **Operating system:** openSUSE LEAP 15.1

## Problem description

Some lines are marked as an error, but they are error-free and compile fine. One example:

```rust
pub mod util {
    use nalgebra_glm::Vec2;

    pub fn union(s1: &Vec2, s2: &Vec2) -> Vec2 {
        if s1.x < s2.x {
            s1.clone()
        } else {
            s2.clone()
        }
    }    
}
```

The error shown by the rust plugin is:

```
mismatched types [E0308] expected `Matrix<f32, U2, U1, <unknown>>`, found `&Matrix<f32, U2, U1, <unknown>>`
```

**Comment by aspin** [comment]
In general it seems like `nalgebra` causes IntelliJ Rust a whole heap of problems. Probably related to https://github.com/intellij-rust/intellij-rust/issues/5007

**Comment by dima74** [comment]
@medakk @aspin do you still experience the error? Looks like it was fixed some time ago
