### ISSUE TITLE
`impl`s from local macros are not accounted

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#6164]
## Environment

* **IntelliJ Rust plugin version:** 0.3.132.3360-202-nightly
* **Rust toolchain version:** 1.46.0 (04488afe3 2020-08-24) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2020.2.2 Ultimate Edition (IU-202.7319.50)
* **Operating system:** Linux 5.4.0-48-generic

## Problem description

```rust
macro_rules! as_is {
    ($($t:tt)*) => { $($t)* };
}

fn main() {
    struct S;
    as_is! {
        impl S {
            fn foo(&self) {}
        }
    }
    S.foo();
}   //^ unresolved
```

**Comment by snaggen** [comment]
I see this also, I generate the Debug trait in a macro for a struct I have, and then when I tries to print the debug for that struct it is marked as an error in IntelliJ saying that Debug is not implemented for that Struct. The code compiles and runs fine, so the error is in the indexing of macros.

**Comment by snaggen** [comment]
Here is a repository that reproduces my issue. https://github.com/snaggen/intellij-rust-issue-6165
Just open main.rs and you should see that the map is marked as not implementing Debug, while it clearly does and it compiles.
