### ISSUE TITLE
"Run tests" icon runs main program instead

### ISSUE THREAD

**Issue by ejmahler** [intellij-rust/intellij-rust#617]
When I click the play icon next to fn main(), my program runs and prints as expected. Next to one of my tests, there is an empty circle icon with a smaller play icon next to it. I expect this to run the test, but instead it just runs the main program.

See here for an example: http://imgur.com/a/cngkr

Intellij version: 2016.2.2
Intellij-rust version: 0.0.1.903
Rust/cargo version: 1.11 and 1.13 nightly (updated today) via rustup

Specific reproduction steps:

1. Run "cargo new my_test_project --bin"
2. Import the project via intellij -- I used all default settings
3. Press play icon next to fn main, it should work
4. Paste the following test into main.rs -- the run test icon should appear next to "do_the_thing":
```
#[cfg(test)]
mod test {
#[test]
    fn do_the_thing() {
         assert!(false);
     }
 }
 ```

When I click it, I expect the test to run and to fail. Instead, I see "hello world" printed in the console area.

**Comment by zjhmale** [comment]
@ejmahler i think the best way to tackle this for now is to add a new test cargo command configuration.

![image](https://cloud.githubusercontent.com/assets/6234553/17878677/4dd1ce38-691f-11e6-9c38-e19aef50ec53.png)

and this will lead to expected behaviors, but will cause another wired erroneous with the run configuration panel (out of the scope of this issue).

![snapshot](https://cloud.githubusercontent.com/assets/6234553/17878758/d6362120-691f-11e6-97f7-626141ccaa85.gif)

i'll try to fix this.
