### ISSUE TITLE
Autoformatting issue

### ISSUE THREAD

**Issue by dmitry-vovk** [intellij-rust/intellij-rust#619]
Given the code:
```rust
#[macro_use(stmt)]
extern crate cassandra;
```
After hitting `Reformat Code` shortcut the code looks like this:
```rust
#[macro_use(stmt)] extern crate cassandra;
```
Expected result would be the code unchanged.

Plugin version: 0.0.1.938-nightly
IDEA version: IU-162.1628.40

**Comment by zjhmale** [comment]
issue confirmed, and maybe you can use `Code > Reformat file use rustfm` currently as an alternative until this fixed. FYI, it requires you to install [rustfmt](https://github.com/rust-lang-nursery/rustfmt) first.

**Comment by mkaput** [comment]
This is expected behaviour, you can turn it off in code style settings
