### ISSUE TITLE
Multiple rust sub-projects (i.e. IntelliJ "modules") in same project breaks type checker in IDE

### ISSUE THREAD

**Issue by stevepryde** [intellij-rust/intellij-rust#6192]
## Environment

* **IntelliJ Rust plugin version:**
0.3.131.3366-202

* **Rust toolchain version:**
Currently 1.48 but it has been the same at least since 1.45 probably earlier

* **IDE name and version:**
IntelliJ Ultimate 2020.2.2 (but has been present since at least 2020.0)

* **Operating system:**
Linux (Manjaro)

## Problem description
If I have multiple IntelliJ subprojects (IntelliJ calls them "modules" - via File -> Project Structure > +) that use Rust, it seems to confuse the type checker for IntelliJ-Rust and it does not understand some specific traits like AsRef<&str> and others.

The crates all show up correctly in the cargo side panel and I have tried refreshing them and setting the toolchain versions for each of them and nothing seems to resolve it. The only way I have been able to resolve the issue is to open each crate in a separate project on its own, which means having to switch between multiple windows which is inefficient and frustrating.

## Steps to reproduce

1. Use File -> Project Structure > + to add multiple Rust sub-projects (IntelliJ calls them "modules") in the same project
2. Try to dereference String into &str like this:

```rust
fn split_str(text: &str) -> Vec<String> {
    text.split("\n").map(|x| x.to_string()).collect()
}

let t = String::from("some\ntext");
let v = split_str(&t);
```

Firstly, IntelliJ-Rust warns that split_str(&t) expects &str but gets &String, which is wrong because a reference to String should convert to &str automatically (the code runs fine).
Secondly, when typing `text.split`, IntelliJ-Rust doesn't recognise this as the string `split` method and instead gives me documentation for AsSock...

See attached screenshot for the AsRef issue:
![asrefbug](https://user-images.githubusercontent.com/16758000/94981323-70b02480-0570-11eb-9c57-d5c30b36cad9.png)

Is there any way to resolve this? Or can this please be fixed?

**Comment by vlad20012** [comment]
This can occur when different projects use `rustup override` with different toolchains, see #3123.

By the way, there's no need to add intellij modules. You can add cargo projects directly from the Cargo toolwindow (side panel)

**Comment by stevepryde** [comment]
Aha, that could be it. I can confirm that removing the override fixed the issue. Thanks!
