### ISSUE TITLE
If a file is named "coordinator.rs", the plugin treats it as a non-Rust file.

### ISSUE THREAD

**Issue by mkb137** [intellij-rust/intellij-rust#6194]
## Environment

* **IntelliJ Rust plugin version:** 0.3.131.3366-202
* **Rust toolchain version:** 1.46
* **IDE name and version:** CLion 2020.2.3
* **Operating system:** Windows 10

## Problem description
If a rust file is named "coordinator.rs", the IDE treats it as if it's some unknown file type and not a rust file.

## Steps to reproduce
* Create a project
* Create a new file named "coordinator.rs" in lib
Unlike a normal rust file, the file is marked with a question mark and there is no message to add the file to a module.  Cargo compiles it correctly.  If the file is renamed to anything else, the IDE treats it correctly.

**Comment by DomWilliams0** [comment]
Do you have an overriding file type association with that name? I've been bitten by this before.

Look in `Settings > Editor > File Types` and check if the "Text" association (or any other non-Rust ones) are associated with "coordinator.rs".

**Comment by mkb137** [comment]
Yep, that was it.  Somehow it was in the list of text file associations.   Weird.

Thanks!
