### ISSUE TITLE
Coverage on windows 10

### ISSUE THREAD

**Issue by olegdovger** [intellij-rust/intellij-rust#6195]
## Environment

* **IntelliJ Rust plugin version:** 0.3.131.3366-202
* **Rust toolchain version:** nightly-x86_64-pc-windows-gnu
* **IDE name and version:** WebStorm 2020.3 EAP
* **Operating system:** Windows 10

## Problem description

I do not see coverage for any file

![image](https://user-images.githubusercontent.com/964292/95002515-a63f2700-05dd-11eb-9be4-29a9c6b4b580.png)

## Steps to reproduce

Create new rust project and run tests with coverage

**Comment by olegdovger** [comment]
WebStorm 2020.3 EAP
Build #WS-203.4203.27, built on September 30, 2020
WebStorm EAP User
Expiration date: October 30, 2020
Runtime version: 11.0.8+10-b1098.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1962M
Cores: 12
Registry: debugger.watches.in.variables=false, js.debugger.webconsole=false
Non-Bundled Plugins: com.alayouni.ansiHighlight, com.berzanmikaili.intellij.monokai_pro, wide-task-browser, com.jetbrains.CyanTheme, com.khmelyuk.multirun, com.markskelton.one-dark-theme, com.sburlyaev.terminal.plugin, com.vecheslav.darculaDarkerTheme, hu.aradipatrik.onedarknative, io.loli.browserfx, krasa.CpuUsageIndicator, net.antelle.intellij-xcode-dark-theme, net.seesharpsoft.intellij.plugins.csv, org.toml.lang, quokka.js, rs.pest, wallaby.js, warm-night, deno, dev.blachut.svelte.lang, cn.yiiguxing.plugin.translate, ru.adelf.idea.dotenv, training, org.rust.lang

**Comment by mchernyavsky** [comment]
@olegdovger It is a bug in grcov: https://github.com/mozilla/grcov/issues/462

**Comment by mchernyavsky** [comment]
@olegdovger Hmm, looks like it works on the latest plugin's nightly. The current stable version doesn't include https://github.com/intellij-rust/intellij-rust/pull/6170 and https://github.com/intellij-rust/intellij-rust/pull/6048.

**Comment by olegdovger** [comment]
Thank you. It realy works ;)

I used latest version from here - https://plugins.jetbrains.com/plugins/list?channel=nightly&pluginId=8182 (https://intellij-rust.github.io/)
