### ISSUE TITLE
Incorrectly reports duplicate imports when using compile time conditions.

### ISSUE THREAD

**Issue by ctron** [intellij-rust/intellij-rust#6215]
## Environment

* **IntelliJ Rust plugin version:** 0.3.132.3395-202
* **Rust toolchain version:** 1.46.0 (04488afe3 2020-08-24) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.2.3 (CL-202.7319.72)
* **Operating system:** Linux 5.8.11-200.fc32.x86_64

## Problem description

Reports duplicate imports, even when only one is enabled through a conditional `cfg`.

## Steps to reproduce

~~~rust
#[cfg(feature = "stm32f4xx")]
use stm32f4xx_hal::stm32::Peripherals as DevicePeripherals;

#[cfg(feature = "stm32f7xx")]
use stm32f7xx_hal::pac::Peripherals as DevicePeripherals;
~~~

Results in:

![image](https://user-images.githubusercontent.com/202474/95424449-ef2b0e80-0942-11eb-8492-9f08ab5c17e3.png)

and:

![image](https://user-images.githubusercontent.com/202474/95424560-197ccc00-0943-11eb-8b62-b84f82115407.png)

However, this is wrong. As in the current configuration only one feature is enabled. I would expect the editor to follow the external linter configuration.

**Comment by Undin** [comment]
Will be solved in #5189
