### ISSUE TITLE
Build using nightly toolchain

### ISSUE THREAD

**Issue by rikvdkleij** [intellij-rust/intellij-rust#6228]
## Environment
IntelliJ IDEA 2020.2.3 (Ultimate Edition)
Build #IU-202.7660.26, built on October 6, 2020

* **IntelliJ Rust plugin version: 0.3.132.3395-202**
* **Rust toolchain version: nightly**
* **IDE name and version:**
* **Operating system: Ubunty**

## Problem description
Building a project using `cargo +nightly build` goes fine on the command-line but I don't how to configure IntelliJ in that way for building the project.

## Steps to reproduce
Build project and using a project which depends on nightly features.

**Comment by rikvdkleij** [comment]
Another solution is to change the default Rust toolchain.

**Comment by maxammann** [comment]
This is another way which works fine with this plugin: https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

**Comment by cbachhuber** [comment]
> This is another way which works fine with this plugin: https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

Thanks! To be explicit: adding a `rust-toolchain.toml` with contents

```toml
[toolchain]
channel = "nightly"
```

to the repo root does the trick.
