### ISSUE TITLE
Macros are not expanded inside included files

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#6243]
## Environment

* **IntelliJ Rust plugin version:** 0.3.133.3405-202-nightly
* **Rust toolchain version:** 1.47.0 (18bf6b4f0 2020-10-07) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.2.3 Ultimate Edition (IU-202.7660.26)
* **Operating system:** macOS 10.15.6

## Problem description
![image](https://user-images.githubusercontent.com/2539310/95752963-8aa4e200-0ca9-11eb-9a47-8ccbfaf39493.png)

## Steps to reproduce
https://github.com/snaggen/intellij-rust-issue-6165

**Comment by Undin** [comment]
Will be fixed with [name resolution 2.0](https://github.com/intellij-rust/intellij-rust/issues/6217)
It already works properly with changes from #6241

**Comment by snaggen** [comment]
Using the new name resolution 2.0, I can no longer reproduce these issues using the tests above. So in that sense it work.
However, I still have issues with the attributes not completing in the real project... will try to investigate this an see if I can get it to work or if I can find an example that is possible to reproduce.
