### ISSUE TITLE
Go to declaration is not working in iced project

### ISSUE THREAD

**Issue by maxim-banaev** [intellij-rust/intellij-rust#6247]
## Environment

* **IntelliJ Rust plugin version:**  0.3.132.3395-202
* **Rust toolchain version:** rustc 1.43.0-nightly
* **IDE name and version:** CLion 2020.2.4
* **Operating system:** macOS 10.14.6

## Problem description

Go to declaration is not working in iced/examples/counter/src/main.rs

![image](https://user-images.githubusercontent.com/37836437/95839870-2b4bde00-0d4c-11eb-8ea3-00e037b871af.png)

Rust iced version:
0.1.1

Submitted to CLion bug tracker https://youtrack.jetbrains.com/issue/CPP-22406
## Steps to reproduce

1. Clone project https://github.com/hecrj/iced.git
2. Open in CLion
3. Open  iced/examples/counter/src/main.rs

Cannot go to declaration for button or Text

**Comment by xiuno** [comment]
git clone https://github.com/hecrj/iced the master branch, CLion+Rust appears "cannot go to declaration for button or Text". 0.1 is ok! 0.1 and master all can complied successfully.

**Comment by Undin** [comment]
Fixed by #5189
