### ISSUE TITLE
auto-completion does not work for generic constructs

### ISSUE THREAD

**Issue by getynge** [intellij-rust/intellij-rust#625]
When calling a function that has return type T, code suggestions on the returned variable will not work.  This bug also applies for destructuring a structured type.  A specific example

```
enum Amazing<T>{
    Cool(T),
    Lame,
}

impl<T> Amazing<T>{
    fn uncool(self) -> T{
        if let Amazing::Cool(a) = self {
            a
        }else{
            panic!("You can't take cool from something that has none of it");
        }
    }
}

fn main() {
    let x = Amazing::Cool(String::new());
    let a = x.uncool();
    a. //nothing shows up here, suggestions for String should show up
}
```

**Comment by kumbayo** [comment]
@getynge Can you retry this with the latest version?
When I try your code with version 0.1.0.2007-nightly,
I get the correct auto completion.

**Comment by matklad** [comment]
Looks like it is indeed working now!
