### ISSUE TITLE
E0603: Module is private

### ISSUE THREAD

**Issue by patricksuo** [intellij-rust/intellij-rust#6270]
## Environment

* **IntelliJ Rust plugin version:** 0.3.132.3395-202
* **Rust toolchain version:** rustc 1.47.0 (18bf6b4f0 2020-10-07)
* **IDE name and version:**  CLion 2020.2.4

* **Operating system:** macOS 10.14.5

## Problem description
False positive E0603:
[
![rust](https://user-images.githubusercontent.com/1446131/96404795-5f247900-120e-11eb-87f8-189d77494837.png)
](url)

## Steps to reproduce

1. clone async-std  git clone https://github.com/async-rs/async-std.git
2. git checkout cc4bb943b00aee6ce8a02310819fb903df8967ad
3. open `src/future/future/flatten.rs` in CLion

**Comment by patricksuo** [comment]
hi @Undin , do you know any workaround for this issue?

**Comment by ortem** [comment]
Hello @patricksuo, please try to enable the new name resolution engine via `Use experimental name resolution engine` option in `Preferences | Languages & Frameworks | Rust settings`. Seems like it might help since the `ready` module is expanded from the macro IIUC
