### ISSUE TITLE
Suggest trait items in impl block while completion

### ISSUE THREAD

**Issue by renoth** [intellij-rust/intellij-rust#6282]
## Environment

* 0.3.133.3426-202
* 1.47.0
* IDEA 2020.2.3 Ultimate
* Windows 8

## Problem description

When doing the yew tutorial i tried to get an autocomplete for a method in Component of yew but there was no autocomplete suggestions at all. I was thinking it should  suggest the methods Component is having to implement them in my Class.

![image](https://user-images.githubusercontent.com/4069007/96768141-c5abc180-13dd-11eb-8e59-bcc767a3dff2.png)

For example Component has these two methods which i think should be suggested when autocompleting

![image](https://user-images.githubusercontent.com/4069007/96768388-23400e00-13de-11eb-873d-4f922a5ddb8a.png)

## Steps to reproduce

Create new Project with rust and yew. Try to get autocomplete suggestion.

**Comment by panstromek** [comment]
The issue is on point, but I just wanted to mention that you can invoke `Implement Methods` dialog with `ctrl+i` or `alt+insert | Implement Methods` and plugin will generate boilerplate for the ones you choose.

**Comment by renoth** [comment]
Thanks for the hint, it works well but not as easy as autocomplete suggestion.
