### ISSUE TITLE
Icons are not shown

### ISSUE THREAD

**Issue by adelarsq** [intellij-rust/intellij-rust#629]
The icons for each file don't show properly on Intellij:

![ca947524-6abe-11e6-83df-ace46b5976d3](https://cloud.githubusercontent.com/assets/430272/17977113/bee2d128-6ac6-11e6-85a8-23691e3b8f9d.png)

Using:
* Last version from Intellij-Rust plugin and Toml plugin, none other no standard plugins
* rustup 0.6.0
* rustc 1.11.0
* Intellij Community 2016.2

**Comment by mxmind** [comment]
Hi @adelarsq, 
It is the wrong issue list for your concern.
Please, try this solution https://github.com/ChrisRM/material-theme-jetbrains/issues/170, or ask authors of given theme to add missed icons.

**Comment by adelarsq** [comment]
@mxmind Thanks. Just notice that there is no icons in the icon_associations.xml file. I thought that when didn't icons the first found was used. I will ask to add new icons 😃
