### ISSUE TITLE
Opening a rust project in CLion

### ISSUE THREAD

**Issue by nathanaeljones** [intellij-rust/intellij-rust#631]
What is the correct way to open a Rust project from CLion? File->Import Project leaves CMake in control.

**Comment by matklad** [comment]
It is not possible to disable CMake integration in the CLion at the moment unfortunately :( If your project does not have any C++/CMake in it than it may be more convenient to use IntelliJ Community (modulo having both IC, and CL installed)

**Comment by bradleygibson** [comment]
I have run into this and the answer above leaves me confused.

What is the point of the IntelliJ-Rust plugin being compatible with CLion if one cannot then open a Rust project?

**Comment by minecrawler** [comment]
@bradleygibson  But of course you can open a rust project! It's just that CLion always wants to have a cmake file. I always delete the file and hence always have a big fat error in my CLion log. Nevertheless, I can code Rust and I can build and run Rust code from both, the CLion "Run" button (custom Rust profile) and the built-in terminal.

**Comment by bradleygibson** [comment]
Oh--I think i will have to try this again! :)  I bailed too quickly, as I did not expect to see any errors on a virgin `cargo new` Rust project.  Thanks, @minecrawler.

**Comment by mouse07410** [comment]
Might be worth pointing out that #3916 describes how to solve this problem. Perhaps this issue should be closed now?
