### ISSUE TITLE
Extend "remove braces from lambda expression" to any single expression block

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#632]
```
let x = { 92 };
```

=>

```
let x = 92;
```

cc @zjhmale #576

**Comment by matklad** [comment]
More flavorful example: 

```
        let lookup_id = |enc_id| {
            match live_pkgs.get(enc_id) {
                Some(&(ref id, _)) => Ok(Some(id)),
                None => {
                    if all_pkgs.contains(enc_id) {
                        Ok(None)
                    } else {
                        Err(internal(format!("package `{}` is specified as a dependency",
                                             enc_id)))
                    }
                }
            }
        };
```

=>

```
        let lookup_id = |enc_id| {
            match live_pkgs.get(enc_id) {
                Some(&(ref id, _)) => Ok(Some(id)),
                None => if all_pkgs.contains(enc_id) {
                    Ok(None)
                } else {
                    Err(internal(format!("package `{}` is specified as a dependency",
                                         enc_id)))
                }
            }
        };
```

**Comment by mkaput** [comment]
Hmm doesn't this change ownership semantics?

**Comment by matklad** [comment]
Yeah, I think there may be some corner cases when the semantics changes because of "closed enclosing block" limitation of the current borrowchk, which should be lifted by non lexical lifetimes. 

However I think these would be pretty rare corner cases. Also, there is no rule that quick fix should not change semantics.

**Comment by mkaput** [comment]
Fine, but this question has to be taken into account as user usually expects quick fixes to just work and not to mess up user's code

**Comment by zjhmale** [comment]
agree with @mkaput that quick fix should not change code semantic cause users always trust it when they enter `Alt+Enter` and `Enter`.

**Comment by matklad** [comment]
Oups, sorry, I used the wrong wording. Quick fixes should indeed be fixes. But intentions can totally change the semantics (something like "filp `,`" comes to mind).

**Comment by zjhmale** [comment]
fair enough 😄 
>Oups, sorry, I used the wrong wording. Quick fixes should indeed be fixes. But intentions can totally change the semantics (something like "filp ," comes to mind).

**Comment by matklad** [comment]
Hey, this was fixed!
