### ISSUE TITLE
Add redirect input option for run configuration

### ISSUE THREAD

**Issue by telezhnaya** [intellij-rust/intellij-rust#6320]
## Environment

* **IntelliJ Rust plugin version:** 0.3.133.3417-202-beta
* **Rust toolchain version:** 1.45.2 (d3fb005a3 2020-07-31) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.2.1 (CL-202.6948.80)
* **Operating system:** macOS 10.15.7

## Problem description

It would be cool if run configuration could provide `InputRedirectAware.InputRedirectOptions` so that the users could pass path to the file for redirecting input, as it's done in Java, Python or C++.

**Comment by Undin** [comment]
Note, it will be also useful for [CodeForces](https://codeforces.com/) integration in [EduTools](https://plugins.jetbrains.com/plugin/10081-edutools/) plugin
