### ISSUE TITLE
Do not offer not applicable live templates inside attrs

### ISSUE THREAD

**Issue by mkaput** [intellij-rust/intellij-rust#634]
This behaviour is pretty annoying:
![idea_2016-08-27_15-10-44](https://cloud.githubusercontent.com/assets/3450050/18027599/7da1fb82-6c68-11e6-92da-25674ac50f84.png)

Define new [RustContextType](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/template/RustContextType.kt) for attrs and blacklist it in all templates (we have no template applicable for attrs currently)

[up for grab]

**Comment by kumbayo** [comment]
I would like to try implementing this.

**Comment by kumbayo** [comment]
Should i create tests for the other live templates main, tfn, mod or is the single test for macro enough?

There are 2 remaining live templates inside attributes which i was not able to remove.
surround/B and surround/P

Those are defined in com.jetbrains.intellij.idea/ideaIC/2016.2.2/137889dde3d6d7980a86b03965069f09d200ddde/ideaIC-2016.2.2/lib/resources.jar!/liveTemplates/surround.xml

**Comment by mkaput** [comment]
> Should i create tests for the other live templates main, tfn, mod or is the single test for macro enough?

Enough

> There are 2 remaining live templates inside attributes which i was not able to remove.
surround/B and surround/P

I doubt we can do anything with them so let them stay
