### ISSUE TITLE
Not all types are imported by Implement Members quick fix

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#6340]
## Environment

* **IntelliJ Rust plugin version:** 0.3.135.3449-202-nightly
* **Rust toolchain version:** 1.49.0-nightly (ffa2e7ae8 2020-10-24) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.2.3 Ultimate Edition (IU-202.7660.26)
* **Operating system:** macOS 10.15.6

## Problem description
When I try to invoke `Implement members` quick fix for `Display` trait, it doesn't import `std::fmt::Result` type alias that leads to error annotation.
![2020-11-02 10 44 10](https://user-images.githubusercontent.com/2539310/97842266-65c7eb80-1cf8-11eb-958b-9eb414cad881.gif)

## Steps to reproduce
```rust
struct Foo;

impl std::fmt::Display for Foo {
}
```

Expected:
```rust
use std::fmt::{Formatter, Result};

struct Foo;

impl std::fmt::Display for Foo {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        unimplemented!()
    }
}
```

Actual:
```rust
use std::fmt::Formatter;

struct Foo;

impl std::fmt::Display for Foo {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        unimplemented!()
    }
}
```

**Comment by nirvdrum** [comment]
Additionally, it'd be helpful if the quick fix either automatically added an alias or a fully qualified type if the name `Result` is already in scope.

**Comment by qiujiangkun** [comment]
This is still annoying, especially when I have multiple kinds of Result. Any plan to fix this?

**Comment by Lipen** [comment]
Just wanted to submit the feature request, but this issue already exists.
Would be nice if "Implement Members" imported the necessary types up until their modules. For example, just `use std::fmt;` instead of `use std::fmt::{Display, Formatter, Result};`. The generated code would look like:
```Rust
impl fmt::Display for Foo {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        todo!()
    }
}
```
This would resolved all the problems with "already existing Result in the scope" and would unified the interface usage.
