### ISSUE TITLE
Document has no code highlighting

### ISSUE THREAD

**Issue by jelipo** [intellij-rust/intellij-rust#6345]
## Environment

* **IntelliJ Rust plugin version:** 0.3.134.3455-203
* **Rust toolchain version:** mingw64(w64 7.0)
* **IDE name and version:** CLion 2020.2
* **Operating system:** Windows 10 (19042.610)

## Problem description
The document has no code highlighting.

![image](https://user-images.githubusercontent.com/16136814/97955666-ad767200-1de1-11eb-97a7-96679480be99.png)

## Steps to reproduce
- Create a new Rust binary project.
- Write doc:
```
/// Init
/// # Example
/// ```
/// let src = [1, 2, 3, 4];
/// let mut dst = [0, 0];
/// ```
fn main() {}
```

**Comment by Undin** [comment]
@jelipo It's expected behavior. Highlighting in doc comment is not supposed to be in binary targets because nothing stops you from writing anything in code snippets since compiler doesn't check them. In library target, any rust code snipper is doc test and it should be compilable to run the test.

**Comment by jelipo** [comment]
> @jelipo It's expected behavior. Highlighting in doc comment is not supposed to be in binary targets because nothing stops you from writing anything in code snippets since compiler doesn't check them. In library target, any rust code snipper is doc test and it should be compilable to run the test.

Thanks for your reply.
I just want to have hints and highlights when writing example. It can help me reduce my example errors.

**Comment by vlad20012** [comment]
@jelipo You can create a library target (lib.rs) with `pub main() {}` function and a binary target (main.rs) with a one-line main that just delegates to that `main` in lib.rs. This looks like a common pattern in Rust.
