### ISSUE TITLE
Add many math methods for every type

### ISSUE THREAD

**Issue by rekby** [intellij-rust/intellij-rust#6357]
## Environment

* **IntelliJ Rust plugin version:** 0.3.134.3455-202
* **Rust toolchain version:** 1.47.0
* **IDE name and version:** IntelliJ IDEA 2020.2.3 (Community Edition), Build #IC-202.7660.26, built on October 6, 2020
* **Operating system:** Windows 10

## Problem description
Autocomplete add many math method for every type, even if type empty.

## Steps to reproduce

```rust
struct T {}

fn main() {
    let t: T;
    t.
}
```
then put cursor after t. and press ctrl+space.

(I can't upload screenshot because github ```can't process that file``` - both for png and jpg)

**Comment by afetisov** [comment]
This seems to no longer reproduce. Close?
