### ISSUE TITLE
Provide completion in repr attribute

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#6365]
## Environment

* **IntelliJ Rust plugin version:** 0.3.135.3464-202-nightly
* **Rust toolchain version:** 1.49.0-nightly (a601302ff 2020-11-06) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.2.3 Ultimate Edition (IU-202.7660.26)
* **Operating system:** macOS 10.15.6

## Problem description
The plugin already knows what args `repr` attribute supports because it can produce the corresponding error annotations.
It would be great to provide completion for these attributes

**Comment by zeroeightysix** [comment]
I'd like to work on this
