### ISSUE TITLE
tokio 0.3 code completion has problem

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#6379]
## Environment

* **IntelliJ Rust plugin version:** 0.3.136.3472-202-nightly
* **Rust toolchain version:** rustc 1.49.0-nightly (1773f60ea 2020-11-08)
* **IDE name and version:** clion 2020.2
* **Operating system:** Windows with WSL toolchain

## Problem description
the codes
```rust
use tokio::io::AsyncWriteExt;
use tokio::net::TcpStream;

#[tokio::main]
async fn main() {
    let mut stream = TcpStream::connect("www.test.com:80").await.unwrap();
    stream.write_all(b"123").
}
```

when I type `.`  the completion list doesn't have `await` or any about the `WriteAll` method, only have 
![image](https://user-images.githubusercontent.com/10096425/98787761-dc709180-243a-11eb-8fca-676473a68aff.png)

## Steps to reproduce

input this codes and look the completion list

**Comment by vlad20012** [comment]
The problem is legacy-scope `write_impl!` macro defined with other macro:
```rust
cfg_io_util! {
    /// Defines numeric writer
    macro_rules! write_impl {
```

**Comment by Sherlock-Holo** [comment]
> The problem is legacy-scope `write_impl!` macro defined with other macro:
> 
> ```rust
> cfg_io_util! {
>     /// Defines numeric writer
>     macro_rules! write_impl {
> ```
> 
> This should be eventually covered by #6217

Can I experience the new name resolution for now?

**Comment by vlad20012** [comment]
Oh, I'm wrong. The problem is in `pin_project!` macro expansion. New resolve only makes things worst in this case (i.e. also adds `write_impl` resolution failure)
