### ISSUE TITLE
Show type of variable when Ctrl-Hover

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#640]
When Ctrl-Hovering, it would be neat if you could see the type of the variable if that is available to `intellij-rust`.

![rust-ctrl-hover](https://cloud.githubusercontent.com/assets/10340167/18107583/7c26a3f0-6ed6-11e6-9edb-8d98dedb42e2.png)

PyCharm does something like this for Python code:

![pycharm-type-hover](https://cloud.githubusercontent.com/assets/10340167/18107667/e4999d3e-6ed6-11e6-87a1-8ff6b18c3577.png)

**Comment by kindlychung** [comment]
Scala plugin does this with shift+ctrl+p, which I like a lot (better than ctrl hovering).

**Comment by matklad** [comment]
@kindlychung we already have `Shift+Ctrl+p` functionality, though type inference itself is very poor at the moment, so it's not very usable.

**Comment by johnthagen** [comment]
@kindlychung  Thanks for the tip, hadn't used `Shift+Ctrl+P` before.

Currently the types are shown for functions with `Ctrl+Hover`, so it seems like it would be a natural addition for variables as well.  If they type inference is poor for a while, seems fine to me as that's a separate effort.

**Comment by the8472** [comment]
In addition to variables it would be even better if the information were available in chained calls. For a beginner it is quite helpful to know what the type of some intermediate result is so one can call the right transformations on it.

![eclipse-tooltip](https://cloud.githubusercontent.com/assets/1065730/19747257/e9f20970-9bda-11e6-875b-00f154d56094.png)

**Comment by matklad** [comment]
String displayed by hover is controlled by `org.rust.ide.docs.RsDocumentationProvider#getQuickNavigateInfo`.

**Comment by PedroD** [comment]
https://stackoverflow.com/questions/54851861/how-do-i-activate-type-annotations-hints-in-kotlin-like-depicted/54852497#54852497
