### ISSUE TITLE
Show function signature in Ctrl-Q Quick Doc

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#641]
When `Ctrl-Q` (Quick Doc) onto a function, it would be neat if it showed the function signature (parameters, parameter types, return type).

Here is an example of how it is done in PyCharm:
![pycharm-function-signature](https://cloud.githubusercontent.com/assets/10340167/18111910/535ca288-6ef1-11e6-81b3-fcdb424198de.png)

**Comment by matklad** [comment]
The code is here: https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/docs/RustDocumentationProvider.kt

Signature is already shown in quick navigation popup, so it should be straightforward to add it to quick doc as well
