### ISSUE TITLE
Rust project not showing in Pycharm even though plugin is installed

### ISSUE THREAD

**Issue by EdEn922** [intellij-rust/intellij-rust#642]
![screenshot from 2016-08-31 08-59-45](https://cloud.githubusercontent.com/assets/6241194/18116022/7df7bd44-6f59-11e6-9560-dfe74788fbc4.png)

**Comment by matklad** [comment]
Yes, this is a known issue ( https://github.com/intellij-rust/intellij-rust/issues/557 ). Will try to fix soonish :)
