### ISSUE TITLE
Don't suggest autocomplete for private functions

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#644]
In the following code:

``` rust
mod my {
    // Items in modules default to private visibility.
    fn private_function() {
        println!("called `my::private_function()`");
    }
}

fn main() {
    my::
}
```

`intellij-rust` suggests `private_function` for autocomplete, but if a user were to select this, they get a compile error:

`error: function `private_function` is private`

I would think it would be best to omit private functions from the autocomplete.

There is also probably a corollary to `pub` vs. private `struct`s and `struct` members.

**Comment by eviltak** [comment]
The same goes for private submodules.

```rust
mod foo {
    mod config;
   pub use config::Config;
}
```

When typing `foo::`, `intellij-rust` prompts both `config` and `Config`, when it should prompt only the latter.
