### ISSUE TITLE
Cannot deduce type of variable in some cases involving traits

### ISSUE THREAD

**Issue by HighCommander4** [intellij-rust/intellij-rust#6442]
In the following code:

```rust
struct S {}

trait Trait {
    type T;

    fn foo(self) -> Self::T;
}

impl Trait for S {
    type T = i32;

    fn foo(self) -> i32 {
        return 5;
    }
}

trait TraitExt {
    type T;

    fn bar(self) -> Option<Self::T>;
}

impl<Model, T> TraitExt for Model
where
    Model: Trait<T = T>,
{
    type T = T;

    fn bar(self) -> Option<Self::T> {
        Some(self.foo())
    }
}

fn main() {
    // intellij-rust says the type of "waldo" is "Option<<unknown>>"
    let waldo = S {}.bar();
}
```

intellij-rust is unable to deduce the type of the variable `waldo`, displaying it as `Option<<unknown>>`.

## Environment

* **IntelliJ Rust plugin version:** 0.3.135.3484-202
* **Rust toolchain version:** 1.37.0
* **IDE name and version:** IDEA 2020.2.1
* **Operating system:** Linux

**Comment by kumbayo** [comment]
For me, this problem appears to be fixed with the current Git version
(`9bff907f34c5af444fc70506b58996d9c64a365b`) of the plugin.
Now `waldo` is inferred as `Option<i32>`.

@HighCommander4 can you check if this issue is also solved for you?

**Comment by HighCommander4** [comment]
Confirmed that this works now, thanks!
