### ISSUE TITLE
Unresolved reference: `Multiaddr`

### ISSUE THREAD

**Issue by 15ho** [intellij-rust/intellij-rust#6452]
## Environment

* **IntelliJ Rust plugin version:** 0.3.135.3484-202
* **Rust toolchain version:** 1.48.0 (7eac88abb 2020-11-16) x86_64-pc-windows-msvc
* **IDE name and version:** GoLand 2020.2.3 (GO-202.7319.61)
* **Operating system:** Windows 10 10.0

## Problem description
Unresolved reference: `Multiaddr` : https://github.com/libp2p/rust-libp2p/blob/dae07b075b421fb0a33bbf85d91ad802e37845f9/examples/chat.rs#L137

Actually, libp2p::Multiaddr has been used: https://github.com/libp2p/rust-libp2p/blob/dae07b075b421fb0a33bbf85d91ad802e37845f9/examples/chat.rs#L55

## Steps to reproduce
I just opened the rust-libp2p project

**Comment by Undin** [comment]
@15ho Thanks for your report!
I reproduced this issue. And as I see, the issue should be solved with new experimental name resolution engine. You can enable it via `Use experimental name resolution engine` option in `Preferences | Languages & Frameworks | Rust` settings. The option is already available in nightly builds (see [instruction](https://intellij-rust.github.io/install#nightly-builds) how to install nightly build of the plugin) and will be landed with the next stable release this week (I hope today)
