### ISSUE TITLE
passing environment variables to cargo build

### ISSUE THREAD

**Issue by pmnoxx** [intellij-rust/intellij-rust#6474]
## Environment

* **IntelliJ Rust plugin version:** 0.3.136.3514-202
* **IDE name and version:**  CLion 2020.2.5
* **Operating system:** Ubuntu

## Problem description
Cargo allow passing environment variables for example `RUSTFLAGS`, `RUSTC_FLAGS`. My specifying those variables it's possible to improve build time considerately. 

Intellij/Clion provide a mechanics for specifying environment variable through `Appearance & Behavior` -> `Path Variables`.
It's possible to key/value environment variables there.  

However, Rust plugin to Intellij seems to ignore those variables when running build.

## Steps to reproduce
1) In `Appearance & Behavior` -> `Path Variables` add a flag
RUSTFLAGS="-C XXXX"
2) Run build

If you were to run this in command line as `RUSTFLAGS="-C XXXX" cargo build` you would get an error.
However, you can see that the build still works and the flag is ignored.
This can also be seen by replacing $HOME/.cargo/bin/cargo with a bash script, which runs `env`.
It shows that the environment variables set in the setting are ignored.

Near Foundation would be willing to sponsor a fix for this issue. I'm going to contact Maksym Zavershynskyi for the details.

**Comment by nearmax** [comment]
An important question to maintainers: If we sponsor implementation of this feature would you be willing to review the pull request and accept this work into your code base?

**Comment by mchernyavsky** [comment]
Hello!

As I understand it from [the doc](https://www.jetbrains.com/help/idea/absolute-path-variables.html), `Path Variables` is not about adding new variables to the environment but about modifying existing variables' values.

You can add new variables to the environment of new run configurations by modifying Cargo configuration **template**:

![image](https://user-images.githubusercontent.com/6079006/101043617-8f8e5f80-358f-11eb-85ff-374c7156f542.png)

This variables should also affect `Build` (Ctrl+F9) if you enable `org.rust.cargo.build.tool.window` in Registry. More info - https://github.com/intellij-rust/intellij-rust/issues/5078.

**Comment by Undin** [comment]
> An important question to maintainers: If we sponsor implementation of this feature would you be willing to review the pull request and accept this work into your code base?

@nearmax depends on what you want to implement but the general answer is yes. We haven't strict rules about the content of PRs but it shouldn't break existing working features and shouldn't complicate maintenance without actual reason. For example, we currently don't want to implement some specific support for libraries/frameworks if the library is not a core library in Rust ecosystem (custom test runners, HTTP frameworks, etc.) since they require a lot of work to maintain and usually are quite unstable.
If the PR contains any improvement of possible user workflows, we will be glad to merge it.
Note, currently, we have a small blockage in PR reviews but we are working on it 😅

**Comment by pmnoxx** [comment]
@mchernyavsky I tested your solution, it works. However, this is highly not intuitive to use.
I think it would be much easier to specify the flags if there was an edit box in setting where you could specify environment to use to run cargo.

For example an edit Max could look like this

Environment variable: [ "RUSTC_WRAPPER=sccache RUSTFLAGS="-C lto=off -C link-arg=-fuse-ld=lld -Zshare-generics=y" ]
I see that Rust plugin already has a page at Setting -> Languages & Frameworks -> Rust where you can specify which framework to run. It would be great to be able to specify environment variables there for all projects.

**Comment by pmnoxx** [comment]
I noticed that CLion often becomes unresponsive, that happens because cargo will use all available threads default. This can cause CLion to become unresponsive for a few minute while there is a build in progress. The proper solution is to limit the number of cores used by cargo, this can be controlled by adding "-j N" flag. For example, for 8 cores processor, I would set the number of cores used to 6, this would allow CLion to remain responsive.

I would suggest to add something like:
Extra parameters to cargo: [ "-j 6" ]

It would be best if there was a way to provide global overrides to all rust projects. Currently as a temporally hack, I replace cargo binary with a bash script that sets proper environment, and add extra "-j 6" argument.

**Comment by octylFractal** [comment]
I second the suggestion for global build variables, projects such as [tch-rs](https://github.com/LaurentMazare/tch-rs#getting-started) rely on them to grab build-time configuration and I would like to be able to specify these for all projects, not just the one runner.

**Comment by pmnoxx** [comment]
I'll close this issue. It's possible to specify such options with `.cargo/config`.

**Comment by remoun** [comment]
I'm running into this issue. I tried using `[env]` in `.cargo/config` but it doesn't work either. What would it take to support adding env vars to the builder?

**Comment by superstator** [comment]
I'd put in a vote for reopening this too. `config.toml` is working for me, but it's pretty inconvenient. Realistically, you can only have a single `.cargo/config.toml` in the root of a given project (cargo searches parent folders for configs, but not children). Ours has important build settings like target-specific rustflags which are checked into source control, but our codebase also uses some `env!` values that are developer specific and should not get checked in or applied globally via `$HOME/.cargo/config.toml`.

Cargo will prefer an extensionless `.cargo/config` over the `.toml` default, so for now my workaround is to copy the existing versioned config w/o the extension, add that to `.gitignore`, and make my edits there, but it would be so much nicer to just set/override variables in IntelliJ.

**Comment by vlad20012** [comment]
@superstator, why doesn't [this solution](https://github.com/intellij-rust/intellij-rust/issues/6474#issuecomment-738049730) suits you?

**Comment by superstator** [comment]
That has a couple suboptimal aspects
- It's a bit confusing as to whether it's global; tweaking the default Cargo template feels like it should apply to any cargo project, though in reality it seems to only change it for the current project, and even then only to new build configs
- More important, it doesn't apply to the external linter option, which I use heavily

Maybe a better option is to appeal to the cargo maintainers for a less hacky way to break up the `.cargo/config.toml` file. Something like `.cargo-user/config.toml` or `.cargo/config.user`.
