### ISSUE TITLE
Unrecognised fields and no autocomplete [generated by macros]

### ISSUE THREAD

**Issue by petar-dambovaliev** [intellij-rust/intellij-rust#6482]
## Environment

* **IntelliJ Rust plugin version:**
0.3.136.3514-202
* **Rust toolchain version:**
stable-x86_64-apple-darwin (default)
rustc 1.48.0 (7eac88abb 2020-11-16)
* **IDE name and version:**
Intellij IDEA community version 2020.2.3
* **Operating system:**
MacOS catalina 10.15.7

## Problem description
The IDE cannot recognise fields that are added from an attribute macro.
They are coloured red and the error message is `no such field`.
Also there is no autocomplete for generated methods.

## Steps to reproduce
Use my crate https://crates.io/crates/actix_responder_macro
or any other crate that does something similar

```rust
#[actix_responder(meta_attr = "builder(default)")]
#[derive(TypedBuilder, Serialize, Deserialize)]
pub struct SuccessResp {
    success: bool,
}

fn main() {
   SuccessResp{
       success: true,
      ///these generated fields are not recognised as well as the methods generated by `TypedBuilder`
       status_code: Default::default(),
       content_type: Default::default()
    }
}
```

**Comment by Undin** [comment]
Currently, the plugin doesn't support items generated by procedural macros. See #1786
