### ISSUE TITLE
Project fails to import with experimental "evaluate build scripts" option

### ISSUE THREAD

**Issue by 2xsaiko** [intellij-rust/intellij-rust#6483]
## Environment

* **IntelliJ Rust plugin version: 0.3.136.3514-203**
* **Rust toolchain version: 1.48.0-nightly**
* **IDE name and version: CLion 2020.3 (Build #CL-203.5981.166)**
* **Operating system: Gentoo Linux x86_64**

## Problem description

When the "org.rust.cargo.evaluate.build.scripts" option is enabled and a specific #[derive] is used, importing the Cargo project will fail at the "Updating workspace info" stage:
![image](https://user-images.githubusercontent.com/3987560/101201311-d780b580-3667-11eb-825b-18748c5a8462.png)

Nothing gets written to the event log.

## Steps to reproduce 

- Enable the "org.rust.cargo.evaluate.build.scripts" option in the Experimental Features dialog.
- Clone the repo, check out one of these commits:
  First affected commit: 2xsaiko/mcrestool@300c50b
  Current commit: 2xsaiko/mcrestool@11d6700
- Import the project (no need to touch the C++ part, importing the Cargo.toml will reproduce it)
- Project will fail to import (or fail to refresh in case it was already imported) and show an error like in the image above

Also tested this on another PC and a completely fresh IDEA installation/config with the same results.

The issue does not occur when commenting out this line: [mcplatfm/src/ident.rs:10][1], specifically the derive for BinDeserialize (which is a proc macro that comes from another project in the same repo)

The same derive macro is used elsewhere in this repo (e.g. in [library/src/workspace/mod.rs:25][2]) and works without issue there.

[1]: https://github.com/2xsaiko/mcrestool/blob/11d6700b5a1eaae65a8557c1c6a7acaac8b98f16/mcplatfm/src/ident.rs#L10
[2]: https://github.com/2xsaiko/mcrestool/blob/11d6700b5a1eaae65a8557c1c6a7acaac8b98f16/library/src/workspace/mod.rs#L25

**Comment by afetisov** [comment]
"Evaluate build scripts" was recently stabilized. Does this bug still apply?

**Comment by 2xsaiko** [comment]
Doesn't look like it does!
