### ISSUE TITLE
Plugin does not understand #![macro_use]

### ISSUE THREAD

**Issue by KarelPeeters** [intellij-rust/intellij-rust#6486]
* **IntelliJ Rust plugin version:** 0.3.136.3514-203
* **IDE name and version:** CLion 2020.3, Build #CL-203.5981.166

The plugin is not able to resolve macros that should be visible because of #![macro_use] instead of the more common #[macro_use].

To reproduce the issue, create a new empty binary project, write in `main.rs`:

```rust
mod module;

my_macro!();

fn main() {}
```

and in a second file `module.rs`:

```rust
#![macro_use]

macro_rules! my_macro { () => {} }
```

This code compiles fine with rustc. In the IDE, executing the "go to declaration" action on the macro call in main doesn't work, showing that the plugin didn't resolve the macro. If the macro is changed to actually declare items those items are also not resolved. The issue goes away when `#![macro_use]` in `module.rs` is replaced by `#[macro_use]` on the module declaration in `main.rs`.

I don't fully understand what `#![macro_use]` even means, but this came up in an existing project I'm working on and I reduced it to this minimal example.

**Comment by dima74** [comment]
Fixed in [latest nightly](https://intellij-rust.github.io/install.html#nightly-builds) with [new name resolution](https://github.com/intellij-rust/intellij-rust/issues/6217) engine [enabled](https://github.com/intellij-rust/intellij-rust/pull/6378)
