### ISSUE TITLE
Cargo Run Configuration - Run behaves different then Debug

### ISSUE THREAD

**Issue by fkrauthan** [intellij-rust/intellij-rust#6500]
## Environment

* **IntelliJ Rust plugin version:**: `0.3.136.3514-203`
* **Rust toolchain version:** `1.47.0`
* **IDE name and version:** `CLion 2020.3`
* **Operating system:** `Windows 10`

## Problem description

I have a small [bevy test game](https://github.com/fkrauthan/simple-pong-bevy) build in CLion. To start it I use the default `Cargo` run Configuration. With a normal run everything is working as expected. But when I run it in Debug mode (the same Configuration) it can not find my assets. When looking through the asset loading code I discovered that they ether use the `exe` path to find assets (in case of a simple run it is not there) or if available the use the path defined by the `CARGO_MANIFEST_DIR` environment variable.

It seems like that `CARGO_MANIFEST_DIR` is not defined in case I debug my application (not sure if there are any other env variables that `cargo run` by default set).

Personally I expect that Run and Debug behave exactly the same beside that Debug attaches a debugger to the application.

## Steps to reproduce

1. Create a simple cargo application that prints out the `CARGO_MANIFEST_DIR` env variable
1. Create a `Cargo` `Run/Debug Configuration` in CLion
1. Start the application with normal `Run` and see that the env variable prints something
1. Start the application with debug `Run` and see that the env variable does not exist

**Comment by fkrauthan** [comment]
Is there any update to this? This still seem to be an issue with the latest plugin version as well?

**Comment by Undin** [comment]
@fkrauthan could you clarify why you need this environment variable at all? Is this binary supposed to be run without cargo?

**Comment by fkrauthan** [comment]
Well since I use a Cargo Run as my run configuration in intellij I expect that debug and regular run behave the same. But the regular run seem to use cargo to actually execute my rust binary (which in turn sets that environment variable) but debug seem to directly execute the compiled binary instead of running it through cargo (therefor not setting that environment variable).

Where this becomes a problem is when I work with the Bevy game engine as it ether looks for assets in the binary folder or if `CARGO_MANIFEST_DIR` is set in that directory. So currently the regular run of my game works without issues but when I try to debug my game it fails as it can't find the assets.

**Comment by luckystreak63** [comment]
Eventually the code would be run without cargo as a standalone binary (release mode), but during development it would be nice to have Debug behave as closely to Run as possible.

Debug is usually a button you press to diagnose an error you got pressing Run. When the environment isn't the same, you end up with Debug-specific bugs, which prevent you from diagnosing the original bug you set out to solve.
