### ISSUE TITLE
plugin "Rust" won't be able to load on IDEA 2020.3 when Android plugin was disabled

### ISSUE THREAD

**Issue by anatawa12** [intellij-rust/intellij-rust#6503]
## Environment

* **IntelliJ Rust plugin version:** `0.3.136.3514-203`
* **Rust toolchain version:** `rustc 1.47.0 (18bf6b4f0 2020-10-07)`
* **IDE name and version:** `IntelliJ IDEA 2020.3 (Ultimate Edition) Build #IU-203.5981.155, built on December 1, 2020`
* **Operating system:** `macOS Big Sur Version 11.0.1`

## Problem description

The Rust plugin was automatically disabled and cannot be enabled with the error shown below:
![Unable to apply changes: plugin "Rust" won't be able to load](https://user-images.githubusercontent.com/22656849/101907158-7f185d80-3bfd-11eb-8a99-c5c9845b79fa.png)

## Steps to reproduce

1. Open Rust project with IDEA.
1. Open a Rust file.
1. Intellij IDEA says 'Plugins supporting *.rs files found. Enable Rust plugin Ignore extension' so click 'Enable Rust plugin'
1. Click 'OK' to enable Rust plugin.
1. The IDE says 'Cannot Save Settings'

**Comment by Undin** [comment]
@anatawa12 Thanks for the report! Could you attach [logs](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files), please?

**Comment by anatawa12** [comment]
@Undin Sorry, I've removed idea.log so I can't send idea.log and I not possible to reproduce now. I found this issue was fixed when the Android plugin was disabled but I couldn't know how to reproduce it. I'm trying to reproduce this issue again.

**Comment by anatawa12** [comment]
For information, I'm going to tell how I got I can't reproduce this issue.

At First, I've disabled Android plugin and I couldn't turn enabled Rust plugin.
I tried re-install Rust plugin but still I couldn't do it.
I found #5237 so I enabled Android plugin then I can turn enabled it.
But now I can't reproduce the bug.

**Comment by rikvdkleij** [comment]
I ran in a similar issue. Building a project did not work anymore for Scala and Rust projects. After enabling the Android plugin (and some other plugins otherwise I could not save the new settings) it worked again.

**Comment by anatawa12** [comment]
@Undin This bug is not caused for long time since I reported this issue. Should I close this issue?

**Comment by Undin** [comment]
> @Undin This bug is not caused for long time since I reported this issue. Should I close this issue?

Yep, let's close it
