### ISSUE TITLE
Optional dependencies aren't shown in External Libraries

### ISSUE THREAD

**Issue by sfackler** [intellij-rust/intellij-rust#651]
Note that log does appear but libc does not. I'm running 0.0.1.903 on OSX.

<img width="713" alt="screen shot 2016-09-02 at 4 55 25 pm" src="https://cloud.githubusercontent.com/assets/1455697/18219283/2114be20-712e-11e6-84e3-c2f741d54f43.png">

**Comment by matklad** [comment]
Hey, looks like the necessary functionality was just implemented in Cargo: https://github.com/rust-lang/cargo/pull/3038

**Comment by sfackler** [comment]
Ah, great!
