### ISSUE TITLE
Context action to toggle between different representations of a dependency

### ISSUE THREAD

**Issue by blaenk** [intellij-rust/intellij-rust#6510]
Sorry if this has been requested before, wasn't sure how to search for it.

It's not uncommon to start off with a basic dependency in Cargo.toml:

``` rust
rusqlite = "0.24.2"
```

Then realize you need to add some `features`. It'd be great if we could Alt+Enter the name to be able to switch to dict form to make it easy to append e.g. `, features = ["bundled-full"]`:

``` rust
rusqlite = { version = "0.24.2" }
```

Maybe even an option to switch to the fully expanded form:

``` rust
[dependencies.rusqlite]
version = "0.24.2"
```

In which case Alt+Enter on the `[dependencies.rusqlite]` is what would show the context action.

**Comment by Kobzol** [comment]
I think that this was already asked in https://github.com/intellij-rust/intellij-rust/issues/4869. @Undin is working on it, but it's not ready yet.

**Comment by blaenk** [comment]
Seems like it. Thanks for finding that! I'll close this one now.
