### ISSUE TITLE
Obvious wrong code is not red annotated

### ISSUE THREAD

**Issue by rikvdkleij** [intellij-rust/intellij-rust#6520]
## Environment
IntelliJ IDEA 2020.3 (Ultimate Edition)
Build #IU-203.5981.155, built on November 30, 2020
Runtime version: 11.0.9+11-b1145.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-33-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins: IdeaVIM, PsiViewer, com.intellij.nativeDebug, com.intellij.plugins.gnomekeymap, com.vecheslav.darculaDarkerTheme, org.toml.lang, org.rust.lang, org.intellij.scala, izhangzhihao.rainbow.brackets
Current Desktop: ubuntu:GNOME

active toolchain
----------------
stable-x86_64-unknown-linux-gnu (default)
rustc 1.48.0 (7eac88abb 2020-11-16

## Problem description
![image](https://user-images.githubusercontent.com/509315/102342929-3b757900-3f9a-11eb-83c5-04c0a957a2b0.png)

IntelliJ doesn't complain at line 192

## Steps to reproduce
Checkout https://github.com/MaikKlein/ash, import into IntelliJ and navigate to `examples/src/lib.rs`, go to line 192 and do some random typing.

**Comment by vlad20012** [comment]
Enable external linter in `Settings | Languages & Frameworks | Rust | Cargo | Run external linter to analyze code on the fly` or `Ctrl`+`Shift`+`A` "cargo check"

**Comment by rikvdkleij** [comment]
@vlad20012 Thanks! 
It's confusing because other wrong code _is_ red annotated with default settings.

**Comment by rikvdkleij** [comment]
So probably you use the Grammar-Kit to to check the syntax and `Cargo check` for type checking.

**Comment by Kobzol** [comment]
The plugin actually does a lot of type checking on its own, but there will (probably always) be some cases that it misses. For such situations you can use the external linter to find more errors (at the cost of performance).

**Comment by rikvdkleij** [comment]
@Kobzol Ok, thanks for your explanation!
