### ISSUE TITLE
Analysis of .rs files is incredibly slow

### ISSUE THREAD

**Issue by eeeebbbbrrrr** [intellij-rust/intellij-rust#6522]
## Environment

* **IntelliJ Rust plugin version:** 0.3.137.3543-203
* **Rust toolchain version:** 1.47.0 (18bf6b4f0 2020-10-07) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.3 (CL-203.5981.166)
* **Operating system:** macOS 10.15.1
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description

Yesterday (even with the -nightly rust plugin), after working on some major changes to a very large Rust codebase, the analysis engine has become incredibly slow.  It now seems to take >5mins to analyze a file.

My project is quite large with over 250k lines of rust (the majority of this is bindgen-generated code):

```
$ loc   
--------------------------------------------------------------------------------
 Language             Files        Lines        Blank      Comment         Code
--------------------------------------------------------------------------------
 Rust                   136       250199         2633         2702       244864
 Markdown                19          903          253            0          650
 Toml                    20          701           94          120          487
 C/C++ Header             4          321            5            0          316
 YAML                     1          135            2            2          131
 C                        1          150           29            5          116
 Plain Text              13           40            0            0           40
 Bourne Shell             3           41           13            5           23
 Makefile                 1           20            7            2           11
--------------------------------------------------------------------------------
 Total                  198       252510         3036         2836       246638
--------------------------------------------------------------------------------
```

## Steps to reproduce

I don't know that there are any per se.  It just started happening out of the blue.

**Comment by vlad20012** [comment]
Could you please share a link to your projects (if it is open source, of course)? If not, please, run `Help | Diagnostic Tools | Start CPU Usage Profiling` and then after few minutes `Help | Diagnostic Tools | Stop CPU Usage Profiling` then attach the snapshot to this issue

**Comment by eeeebbbbrrrr** [comment]
It is an open-source project.  I can commit/push all my WIP stuff if you really want to play in it. The WIP stuff does not compile!

**Comment by vlad20012** [comment]
Yep, I'd like to play with it, but most likely tomorrow

**Comment by eeeebbbbrrrr** [comment]
You can clone this branch:  https://github.com/zombodb/pgx/tree/pgptr

I just create a standard "Rust Library" project.  I'm on the 1.47.0 toolchain.

Basically everything from syntax coloring, to intellisense stuff when pressing `.`, to even following through to declarations using COMMAND+B (or COMMAND+Click) just stop working for awhile.

The large files are in `pgx-pg-sys/src/pgXX.rs` -- those are the bindgen generated files which are definitely huge.  I plan on splitting these things up as part of the refactoring I'm doing, but regardless, I'd still have the same amount of code (assuming that's even the problem here).

LMK if I can provide any other details.

**Comment by vlad20012** [comment]
Ok, cool, I managed to reproduce it and found the reason. It's simple - our name resolution algorithms run in O(n) when n is a number of declared named items in a module. We'll fix it during `name resolution 2.0` evolution (see #6217). But today `name resolution 2.0`  doesn't help. So the only workaround is to declare fewer items in a module.

**Comment by vlad20012** [comment]
@dima74 Please, consider making `RsItemsOwner.getExpandedItemsWithName` run in O(1). It looks relatively simple with the new name resolution if we store a `HashMap` in `RsCachedItems` instead of a list

**Comment by eeeebbbbrrrr** [comment]
Great. Thanks for the incredibly quick diagnosis. 

I definitely have a lot of N’s!

like I said I’m working on cleaning up my mess so while I’m doing that I’ll be looking forward to the new resolution impl. 

Thanks again!

**Comment by vlad20012** [comment]
I'm trying to fix it in #6526. Looks like it works even with the old name resolution engine!

I made a build for you, use it with CLion 2020.3:

[intellij-rust-0.3.138.SNAPSHOT-203-dev.zip](https://github.com/intellij-rust/intellij-rust/files/5710091/intellij-rust-0.3.138.SNAPSHOT-203-dev.zip)

**Comment by eeeebbbbrrrr** [comment]
That seems drastically faster.  Great work!  Can't wait for an official release.

**Comment by vlad20012** [comment]
The fix is included in the latest nightly build
