### ISSUE TITLE
Action to suppress external linter (clippy) warning

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#6527]
## Environment

* **IntelliJ Rust plugin version:** 0.3.138.3548-203-nightly
* **Rust toolchain version:** 1.50.0-nightly (f76ecd066 2020-12-15) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.1 Snapshot (CL-211.3290)
* **Operating system:** macOS 10.15.6
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

I would love a quick action to suppress (instead of apply) a specific external linter warning by inserting `#[allow(clippy::...)]` comment.

Similar how e.g. "suppress for statement" works in PyCharm

![suppress](https://user-images.githubusercontent.com/2500320/102501331-60e3af00-408e-11eb-833f-9c9d518f708f.gif)

## Steps to reproduce

```rust
pub fn abbreviate(phrase: &str) -> String {
    let mut result = String::new();
    let mut last = ' ';

    for current in phrase.replace("'", "").chars() {
        if (!last.is_alphabetic() && current.is_alphabetic())
            || (last.is_lowercase() && current.is_uppercase())
        {
            result.push(current.to_ascii_uppercase());
        }
        last = current;
    }

    result
}
```

to

```rust
pub fn abbreviate(phrase: &str) -> String {
    let mut result = String::new();
    let mut last = ' ';

    for current in phrase.replace("'", "").chars() {
        #[allow(clippy::suspicious_operation_groupings)]
        if (!last.is_alphabetic() && current.is_alphabetic())
            || (last.is_lowercase() && current.is_uppercase())
        {
            result.push(current.to_ascii_uppercase());
        }
        last = current;
    }

    result
}
```

**Comment by mchernyavsky** [comment]
Closed by https://github.com/intellij-rust/intellij-rust/issues/8794.
