### ISSUE TITLE
Cannot apply two-parts of a single clippy warning

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#6529]
## Environment

* **IntelliJ Rust plugin version:** 0.3.138.3548-203-nightly
* **Rust toolchain version:** 1.50.0-nightly (f76ecd066 2020-12-15) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.1 Snapshot (CL-211.3290)
* **Operating system:** macOS 10.15.6
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

[I have a file](https://gitlab.com/lancelote/rust-exercism/-/blob/d144415d0b16acca6bb3ebb72f510c75474e506d/grade-school/tests/grade-school.rs#L3) where `clippy` reports a warning consisting of two parts

```
warning: this function's return value is unnecessarily wrapped by `Option`
 --> grade-school/tests/grade-school.rs:3:1
  |
3 | / fn some_strings(v: &[&str]) -> Option<Vec<String>> {
4 | |     Some(v.iter().map(|s| (*s).to_string()).collect())
5 | | }
  | |_^
  |
  = note: `#[warn(clippy::unnecessary_wraps)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_wraps
help: remove `Option` from the return type...
  |
3 | fn some_strings(v: &[&str]) -> std::vec::Vec<std::string::String> {
  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: ...and change the returning expressions
  |
4 |     v.iter().map(|s| (*s).to_string()).collect()
  |
```

The plugin suggest me to apply either the first part or the second

<img width="815" alt="apply" src="https://user-images.githubusercontent.com/2500320/102509395-8d4ff900-4097-11eb-9809-a19dd0feee52.png">

The problem is - as soon as one action is applied - the second vanishes as the code becomes invalid.

**Comment by Fryuni** [comment]
I made the mistake of clicking on the "Apply suggested replacement made by external linter" on the problems toolbar.
I had 63 warnings. Now I have 80 errors.
