### ISSUE TITLE
Autocomplete issue

### ISSUE THREAD

**Issue by jkvargas** [intellij-rust/intellij-rust#6539]
## Environment

* **IntelliJ Rust plugin version: 0.3.137.3543-203**
* **Rust toolchain version: 1.48.0 **
* **IDE name and version: Clion 2020.3 **
* **Operating system: 5.9.11-3-MANJARO Linux**

## Problem description
Having a package dependency gdnative = "0.9.1"
I dont have autocomplete for some types like gdnative::api::{Area, MeshInstance, CollisionShape};
But if I compile the code it works normally.
One friend told me that I need to enable "Load code from OUT_DIR"

## Steps to reproduce
Create a new project, add gdnative as a dependency and try to autocomplete  some type that is inside  gdnative::api::...

**Comment by dima74** [comment]
@jkvargas please enable `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` [experimental features](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features), it should be fixed

![Peek 2022-08-05 19-15](https://user-images.githubusercontent.com/6505554/183118676-54ffe65c-1ba5-449f-8289-93affeac19f8.gif)

**Comment by Undin** [comment]
@dima74 let's keep it open since build script evaluation is not enabled by default yet
