### ISSUE TITLE
Wrong rendering of ANSI escape codes in Build view

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#6540]
## Environment

* **IntelliJ Rust plugin version:** 0.3.139.3558-203-nightly
* **Rust toolchain version:** 1.50.0-nightly (11c94a197 2020-12-21) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.3 Ultimate Edition (IU-203.5981.155)
* **Operating system:** macOS 10.15.6
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
Children nodes in Build view incorrectly handle escape codes
![image](https://user-images.githubusercontent.com/2539310/102881533-0f586d00-445e-11eb-9e17-8afba3ae3663.png)

Note, everything is fine in root node
![image](https://user-images.githubusercontent.com/2539310/102881498-ffd92400-445d-11eb-8a52-0491fb28bb3d.png)

## Steps to reproduce
* Clone https://github.com/Undin/rust-os
* (probably `$ rustup default nightly` is required)
* Checkout `030e913a318e43fdd69df75d374002ba42112f14` commit
* Run `cargo test`

**Comment by mchernyavsky** [comment]
I have created the issue in IntelliJ tracker: https://youtrack.jetbrains.com/issue/IDEA-258407

**Comment by ortem** [comment]
JFYI: There is [`build-std`](https://doc.rust-lang.org/cargo/reference/unstable.html#build-std) Cargo option that can be used to add some fake errors to stdlib crates. For example, the Cargo command on macOS will be
```
run --package <my> --bin <my> -Z build-std --target x86_64-apple-darwin
```
