### ISSUE TITLE
Multiple Incorrect Errors Shown in IDE for Repository

### ISSUE THREAD

**Issue by MrKWatkins** [intellij-rust/intellij-rust#6547]
## Environment

* **IntelliJ Rust plugin version:** 0.3.137.3543-203
* **Rust toolchain version:** rustc 1.48.0 (7eac88abb 2020-11-16)
* **IDE name and version:** CLion 2020.3
* **Operating system:** Ubuntu 20.04.1 LTS

## Problem description

Recently CLion started showing various incorrect errors for my Rust repository, which builds and runs fine. I haven't been able to narrow it down to a specific issue I'm afraid. It just started showing errors during recent development; afraid I cannot remember if adding a certain file triggered it or not. I have tried invalidating caches and restarting; the problems remain.

Example invalid errors being shown in the IDE:

camera.rs line 21 'Cannot move'
object.rs line 21 'Use of moved value'
ray_tracing.rs line 22 'Cannot move'

## Steps to reproduce

Load the following repo with CLion and the Rust plugin: https://github.com/MrKWatkins/rust-rendering/tree/e2fd20fac2e1dd83b600b3b4c176899b1b2b8695

**Comment by ortem** [comment]
Related to https://github.com/intellij-rust/intellij-rust/issues/3987 due to `nalgebra`

**Comment by smandy** [comment]
I'm seeing similar ( cannot move) when project compiles + runs fine.

**Comment by thechubbypanda** [comment]
Issue still prevalent, can also be seen in [breakout.rs](https://github.com/bevyengine/bevy/blob/main/examples/game/breakout.rs) in Bevy.
