### ISSUE TITLE
Wrap with try!(...) or ...? intention/quickfix

### ISSUE THREAD

**Issue by mkaput** [intellij-rust/intellij-rust#655]
I'd like IntelliJ to offer me putting expressions which return value of type `Result<T, E>` with `try!` macro. I'm not sure whether this should be intention or quickfix.

Additionally (stuff for separate PR) it could use `...?` notation instead if applicable feature gate is open.

Not sure if [up for grab] yet

**Comment by matklad** [comment]
Ok, so `?` is stable, and we don't really need an intention to wrap with `?` I think ;)
