### ISSUE TITLE
Plugin doesn't suggest std import when writing

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#6560]
## Environment

* **IntelliJ Rust plugin version:** 0.3.137.3543-203
* **Rust toolchain version:** 1.48.0 (7eac88abb 2020-11-16) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2020.3 (CL-203.5981.166)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

When writing a symbol which is not yet imported, the plugin provides autocomplete on the fly. For some reason those suggestions never contain symbols from `std`. To autoimport such symbol from std, one needs to manually write it in full, and then use "import" from context actions, where `std` symbols appear.

## Steps to reproduce
```rust
// assuming tokio crate is a dependency
// while writing Instant, a suggestion appears to complete and import it from tokio, not std
// only when finishing the name and using context import action, std is suggested
let now = Instant
```

**Comment by dima74** [comment]
@krojew could you please check, looks like it was fixed some time ago

![image](https://user-images.githubusercontent.com/6505554/180875364-b2c13135-2ce3-4539-9750-71215a5b90e2.png)
