### ISSUE TITLE
Toolchain version specified in "Rust-toolchain" file is ignored by IDE error checker.

### ISSUE THREAD

**Issue by mdsimmo** [intellij-rust/intellij-rust#6561]
## Environment

* **IntelliJ Rust plugin version:** 0.3.137.3543-203
* **Rust toolchain version:** 1.48.0 (7eac88abb 2020-11-16) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.3 (CL-203.5981.166)
* **Operating system:** Linux 5.4.0-58-generic
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description

If the toolchain version (stable/nightly) is specified in the "rust-toolchain" file, then the IDE will ignore it and use the default toolchain. 

For example, when using experimental features, the IDE will always highlight the experimental feature as a compile error, even when the `#[feature(...)]` is added.

## Steps to reproduce
1. Set the default toolchain to stable: 

`rustup default stable`

2. Set the projects toolchain to nightly through the rust toolchain file: 

```
cd my/project/
echo "nightly" > rust-toolchain
```

3. Add the following code to `main.rs`. The code will compile but the IDE will display an error

```rust
#![feature(box_syntax)]

fn main() {
    let a = box 1; // IDE error: "`box` expression syntax is experimental [E0658]"
    println!("{}", a);
}
```

**Comment by mchernyavsky** [comment]
Does this code compile? As I understand it, IDE shows the error because you are using the stable toolchain.

**Comment by mdsimmo** [comment]
Yes, it does compile. I am using the nightly build. I am using the "rust-toolchain" file to make the compiler use nightly builds.

**Comment by mdsimmo** [comment]
So, it seems the IDE checks against the default toolchain specified by rustup. If I run `rustup default nightly`, then the errors disappear.

It seems the real bug is that the IDE ignores the rust-toolchain file (updated OP)
