### ISSUE TITLE
Stock rerun icon in Build tool window Sync tab

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#6565]
## Environment

* **IntelliJ Rust plugin version:** 0.3.139.3568-203-nightly
* **Rust toolchain version:** 1.50.0-nightly (f76ecd066 2020-12-15) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.1 Snapshot (CL-211.3903)
* **Operating system:** macOS 10.15.6
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Try building some project. Build tool window will have a Sync tab. Rerun button on this tab has a stock icon and no hint while hovering over it with a mouse.

<img width="636" alt="Screen Shot 2020-12-28 at 13 46 45" src="https://user-images.githubusercontent.com/2500320/103209276-bd0ec480-4913-11eb-9c7f-905ea898a25d.png">

**Comment by Undin** [comment]
@lancelote nice catch! Thanks!
The bug was introduced by my changes in #6555
