### ISSUE TITLE
Test fails with rustup version 0.5.0

### ISSUE THREAD

**Issue by kumbayo** [intellij-rust/intellij-rust#657]
When running `gradle test` with rustup 0.5.0 the case testDownloadStdlib fails.
`java.lang.AssertionError: Failed to download stdlib via rustup`

We should probably skip this test if the "component" subcommand is not available.

(Check the same way as we do it for cargo?)
```rust
val hasMetadataCommand = cargo.generalCommand("metadata", listOf("--help")).runExecutable() != null
```

Error message:
```
WARN - rg.rust.cargo.toolchain.Rustup - Failed to execute `/home/kumbayo/.cargo/bin/rustup component add rust-src`
code  : 1
stdout:

stderr:
error: Found argument 'component' which wasn't expected, or isn't valid in this context

USAGE:
    rustup [FLAGS] [SUBCOMMAND]

For more information try --help
```

cc #626

**Comment by matklad** [comment]
Yes, we indeed should skip the test for older rustups. Though I believe we should  not introduce a special `RustupVersion` with this info: `metadata` command is mandatory, while `rustup add component` is a "progressive enhancement", so we just must handle its absence gracefully.

**Comment by matklad** [comment]
Just in case anyone finds this issue, `rustup self update` should fix the tests.
