### ISSUE TITLE
Support structured build output tool window for cargo check run configurations

### ISSUE THREAD

**Issue by Mcat12** [intellij-rust/intellij-rust#6583]
## Environment

* **IntelliJ Rust plugin version:** 0.3.138.3572-203
* **Rust toolchain version:** 1.48.0
* **IDE name and version:** CLion 2020.3
* **Operating system:** Fedora 33

## Problem description
The structured build tool window shows up for `build`/`run`/`test`, but does not work for `check`. Running a check build is usually much faster than even a debug build, so it is often used to check for errors. Having the structured build output window for check builds would improve the user experience of fixing errors.

## Steps to reproduce
Create a `cargo check` run configuration and see that it opens a text-only build output tool window.
Create a `cargo build` run configuration and see that it opens in a structured build output tool window.

**Comment by sabbyX** [comment]
maybe for clippy too 🙂
