### ISSUE TITLE
Type inference is broken for slices

### ISSUE THREAD

**Issue by MSxDOS** [intellij-rust/intellij-rust#6587]
In this example
```Rust
struct Array {
    array: [u32; 32],
}

let a = Array { array: [0; 32] };
let b = [0u16; 4];

let test1 = &b[..];
let test2 = &a.array[..];
```
the plugin can't infer the types for `test1` and `test2`.

Using CLion 2020.3 and latest Rust nightly. I've been having this problem for some time now.
Current plugin version: 0.3.139.3575-203-nightly

**Comment by kumbayo** [comment]
Hello @MSxDOS
Is the problem still happening for you?
I just tried with the latest version from Git (4144226728bd88c701be90dcf2dbfe964668a898 rust-build-number-3941) with Rust 1.55 nightly
and the types of `test1` and `test2` seem to be inferred correctly for me.

![image](https://user-images.githubusercontent.com/1041267/123165383-73430900-d474-11eb-9290-daae28e02428.png)

**Comment by MSxDOS** [comment]
Hello,
Seems to be fine here too now.
