### ISSUE TITLE
Configured Rust Toolchain is incompatible with the plugin

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#659]
I just updated to `intellij-rust` v0.1.0.981 and was greeted with this error:

![rust-toolchain-error](https://cloud.githubusercontent.com/assets/10340167/18329344/fbdc98c0-7520-11e6-92a5-03c5fe12052c.png)

I am on Windows 10 using the latest stable Rust 0.11.0.

Perhaps related to the new feature "Support for workspaces on nightly Cargo."

**Comment by matklad** [comment]
Can you please invoke `cargo metadata --help` in the console and paste the output here?

It would also be helpful to the the log file of your IDE :)

**Comment by johnthagen** [comment]
> It would also be helpful to the the file of your IDE :)

Sorry, what do you mean?  I'm using PyCharm 2016.2.3, is that what you needed?  Happy to supply whatever you need.

Here is some `cargo` output:
```
C:\Users\John Hagen\PycharmProjects\rust_belt>cargo -V
cargo 0.12.0-nightly (6b98d1f 2016-07-04)
```

```
C:\Users\John Hagen\PycharmProjects\rust_belt>cargo metadata --help
Output the resolved dependencies of a project, the concrete used versions
including overrides, in machine-readable format.

Usage:
    cargo metadata [options]

Options:
    -h, --help                 Print this message
    --features FEATURES        Space-separated list of features
    --no-default-features      Do not include the `default` feature
    --no-deps                  Output information only about the root package
                               and don't fetch dependencies.
    --manifest-path PATH       Path to the manifest
    --format-version VERSION   Format version [default: 1]
                               Valid values: 1
    -v, --verbose ...          Use verbose output
    -q, --quiet                No output printed to stdout
    --color WHEN               Coloring: auto, always, never
```

**Comment by matklad** [comment]
>It would also be helpful to the the file of your IDE :)

Oups, I've somehow typed `the` instead of `log`. 

It would be still interesting to see the log file though (https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files) !

**Comment by johnthagen** [comment]
Sure thing:

[idea-log.zip](https://github.com/intellij-rust/intellij-rust/files/461546/idea-log.zip)
