### ISSUE TITLE
Go to symbol does not help when there are multiple overloads

### ISSUE THREAD

**Issue by stepancheg** [intellij-rust/intellij-rust#660]
When I'm using go to symbol action, I often see something like this:

![2016-09-08_2234](https://cloud.githubusercontent.com/assets/28969/18363879/0eb36eae-761d-11e6-83ed-f6c057b155e0.png)

The problem is that function with name `channel` is declared in rust stdlib, and also in futures-rs, and also twice in tokio-core.

If intellij-rust could show at least crate name, or better fully qualified name of symbol, it would be convenient.

**Comment by kumbayo** [comment]
This is partially related to https://github.com/intellij-rust/intellij-rust/issues/658#issuecomment-245552053
On the right side we currently always display "Cargo <project-name>" as library instead of the actual library name.

**Comment by matklad** [comment]
Note that it is just a display option, that is, you search for `st::s::ch` at the moment.

**Comment by matklad** [comment]
> you can't search for st::s::ch at the moment.

You can in the master branch of the plugin!
