### ISSUE TITLE
Fail to detect missing fields

### ISSUE THREAD

**Issue by PizzaCrust** [intellij-rust/intellij-rust#6600]
## Environment

* **IntelliJ Rust plugin version:** 0.3.138.3572-203
* **Rust toolchain version:** 1.51.0-nightly (e22670468 2020-12-30) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2020.3.1 Community Edition (IC-203.6682.168)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
It fails to detect the error, `Some fields are missing`.
```rust
struct A;

impl A {
    fn b<C>(d: C) {
        struct E<F> {
            value: F
        }
        impl<G> E<G> {
            fn new(h: G) -> Self {
                Self {
                   value: h
                }
            }
        }
    }
}
```
Additionally, highlighting and go to definition doesn't work on the bugged `value`.
If the same function is placed in the top level, everything works correctly. It seems that this only happens when it's under impl.
Bugged:
![image](https://user-images.githubusercontent.com/15954148/103444671-40764000-4c9d-11eb-8952-53eb00e437d8.png)
Expected:
![image](https://user-images.githubusercontent.com/15954148/103444678-52f07980-4c9d-11eb-8289-f2094df915e2.png)

## Steps to reproduce
Place the aforementioned code in the editor

**Comment by Undin** [comment]
@vlad20012 As I see, we put all ancestor structs, enums and impls as suitable items for `Self` resolve in `org.rust.lang.core.resolve.NameResolutionKt#processLexicalDeclarations` during iteration in `org.rust.lang.core.resolve.NameResolutionKt#walkUp`, as a result we have multiresolve for `Self`
![image](https://user-images.githubusercontent.com/2539310/103461982-30a93b00-4d33-11eb-89a6-52a7bed49869.png)
and as a result, we can't resolve any items under `Self` (`value` in this case).

Also, in this case we duplicate `Self` item during completion
![image](https://user-images.githubusercontent.com/2539310/103461977-2424e280-4d33-11eb-9f5c-cfd4676888d6.png)

Currently, I'm thinking about omitting the non-first items with `Self` name (i.e. wrap some path processor somewhere and add such filtration). Looks like it should take the nearest item during processing that solves the issue.
What do you think?
