### ISSUE TITLE
Fail to register usage of trait method implemented in macros

### ISSUE THREAD

**Issue by PizzaCrust** [intellij-rust/intellij-rust#6608]
## Environment

* **IntelliJ Rust plugin version:** 0.3.138.3572-203
* **Rust toolchain version:** 1.51.0-nightly (e22670468 2020-12-30) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2020.3.1 Community Edition (IC-203.6682.168)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
```rust
trait A {
    fn b();
}
macro_rules! c {
   () => {
       pub struct D;
       impl A for D {
           fn b() {}
       }
   };
}
c!();
pub struct E;
impl A for E {
    fn b() {}
}
fn f() {
    D::b();
    E::b();
}
```
The IDE says the only invocation of trait method `A::b` is `E::b`, however you can see that is not the case.

## Steps to reproduce
Place the aforementioned code in the editor, and attempt to see usages of `A::b`

**Comment by mili-l** [comment]
see https://github.com/intellij-rust/intellij-rust/pull/9729

**Comment by Undin** [comment]
Not related to procedural macro support
