### ISSUE TITLE
Treat 'char' and 'str' as primitives

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#662]
Currently [`char`](https://doc.rust-lang.org/std/primitive.char.html) and [`str`](https://doc.rust-lang.org/std/primitive.str.html) are not treated as [primitives](https://doc.rust-lang.org/std/#primitives), and this seems to cause incorrect highlighting in the editor as well as some false positive unresolved references.

![char_str_primitives](https://cloud.githubusercontent.com/assets/10340167/18368477/1c95be5c-75ee-11e6-95fa-c6ff332c847f.png)

**Comment by johnthagen** [comment]
They seem to be listed as primitives here: https://github.com/intellij-rust/intellij-rust/blob/19bfd28ba33906e8d5c17db6d731b97b5c4167ef/src/main/kotlin/org/rust/lang/refactoring/RustNamesValidator.kt#L40

**Comment by kumbayo** [comment]
This is probably caused by missing RustCharacterType, RustStringType at
https://github.com/intellij-rust/intellij-rust/blob/438619beb6c2ef327d0859608d5c6e75fb9f3a40/src/main/kotlin/org/rust/lang/core/types/visitors/impl/RustTypificationEngine.kt#L195

Im looking into creating a fix.
