### ISSUE TITLE
Ambiguated go to definition whilst disambiguated

### ISSUE THREAD

**Issue by PizzaCrust** [intellij-rust/intellij-rust#6634]
## Environment

* **IntelliJ Rust plugin version:** 0.3.138.3572-203
* **Rust toolchain version:** 1.51.0-nightly (fde692739 2021-01-02) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2020.3.1 (CL-203.6682.181)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
If you go to definition of the call of `a`, it shows you two options even though its disambiguated.

## Steps to reproduce
```rust
trait A {
    fn a() {}
}
trait B {
    fn a() {}
}
struct C;
impl A for C {}
impl B for C {}
impl C {
    fn b() {
        <Self as A>::a();
    }
}
```

**Comment by dima74** [comment]
Looks like it was fixed some time ago. @PizzaCrust feel free to reopen if you encounter any other error
