### ISSUE TITLE
error running files that have hyphens in their name

### ISSUE THREAD

**Issue by berardino** [intellij-rust/intellij-rust#664]
imported this project https://github.com/tomaka/glium and when running any of the tutorial
examples (eg: tutorial-02.rs) I get the following error. It works by simply removing the hyphen an naming the file for instance tutorial02.rs

```
/usr/local/bin/cargo run --example tutorial_02
error: no example target named `tutorial_02`

Did you mean `tutorial-02`?

Process finished with exit code 101
```

**Comment by himikof** [comment]
This is certainly a regression, introduced in 8536a96. Hyphens should only be replaced by underscores in crate names, not all target names. This should be easy to fix by moving the `name.replace("-", "_")` into the construction of `ExternCrate` (and verifying that #647 is still fixed, not sure if there are any tests for that).
