### ISSUE TITLE
Complete paired vertical pipe in closures

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#6640]
## Environment

* **IntelliJ Rust plugin version:** 0.3.138.3572-203
* **Rust toolchain version:** 1.48.0 (7eac88abb 2020-11-16) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.3 (CL-203.5981.166)
* **Operating system:** macOS 10.16
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
The second (paired) vertical pipe is not inserted when inserting the first pipe
![map](https://user-images.githubusercontent.com/4854600/104089468-62b12480-5280-11eb-992e-b03ed4acf52b.gif)

## Steps to reproduce
```Rust
fn main() {
    vec![1,2,3].iter().map(/* insert `|` here */); // expected: two pipes `||` will be inserted
}
```

**Comment by Undin** [comment]
Duplicate of #3830

**Comment by ortem** [comment]
Uh, I've only searched for "closure" and "pipe". Thanks!
