### ISSUE TITLE
Some operating system related traits doesn't autocomplete well

### ISSUE THREAD

**Issue by Frago9876543210** [intellij-rust/intellij-rust#6641]
## Environment
* **IntelliJ Rust plugin version:** 0.3.138.3572-203
* **Rust toolchain version:** 1.50.0-nightly (1c389ffef 2020-11-24) x86_64-unknown-linux-gnu
* **IDE name and version:** PhpStorm 2020.3
* **Operating system:** Ubuntu 18.04 LTS

## Problem description
Plugin can't find some extensions traits such as `.as_raw_fd()` on Linux
![image1](https://user-images.githubusercontent.com/13465245/104105097-fef91c80-52bc-11eb-892b-84fd41846f8b.png)
```
error[E0599]: no method named `as_raw_fd` found for struct `std::net::UdpSocket` in the current scope
 --> src/main.rs:6:17
  |
6 |     dbg!(socket.as_raw_fd());
  |                 ^^^^^^^^^ method not found in `std::net::UdpSocket`
  |
  = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
  |
1 | use std::os::unix::io::AsRawFd;
  |
```
Even after adding `use std::os::unix::io::AsRawFd;` it doesn't work.

https://doc.rust-lang.org/std/os/unix/net/index.html
I also ran into this problem when trying to use documentations from that module. Rust plugin can't autocomplete and jump to the definition.

![image2](https://user-images.githubusercontent.com/13465245/104105493-91022480-52bf-11eb-84c5-df3907b832f4.png)

## Steps to reproduce
Paste that code into IDE
```rust
use std::net::UdpSocket;
use std::os::unix::io::AsRawFd;

fn main() {
    let socket = UdpSocket::bind("127.0.0.1:3400")
        .expect("couldn't bind to address");

    // It's assuming that `.as_raw_fd()` is autocompleted
    // and suggests to import `std::os::unix::io::AsRawFd` (depending on host OS?)
    dbg!(socket.as_raw_fd());
}
```

```rust
use std::os::unix::net::UnixDatagram;

fn main() -> std::io::Result<()> {
    let socket = UnixDatagram::bind("./socket")?;
    Ok(())
}
```

**Comment by Undin** [comment]
@Frago9876543210 try to enable `org.rust.cargo.fetch.actual.stdlib.metadata` experimental feature via the corresponding dialog. To open the dialog, just invoke `Help | Find Action` action and type `Experimental features`

**Comment by Frago9876543210** [comment]
@Undin Seems it fixed, but it require restart IDE

**Comment by Undin** [comment]
> @Undin Seems it fixed, but it require restart IDE

@Frago9876543210 no, it doesn't require to restart IDE, only refresh Сargo projects
![image](https://user-images.githubusercontent.com/2539310/104120386-868b6d80-5347-11eb-9d4d-90288fe1b079.png)
