### ISSUE TITLE
can't set environments for a test run config

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#6646]
## Environment

* **IntelliJ Rust plugin version:** 0.3.139.3589-203-nightly
* **Rust toolchain version:** rustc 1.51.0-nightly (26438b473 2021-01-08)
* **IDE name and version:** clion 2020.3.1
* **Operating system:** Archlinux

## Problem description
can't set environments for an existing test run config, if set environments, press ctrl+shift+f10 will create a new config named 'xxx(1)', xxx is the origin config name

## Steps to reproduce

1. press ctrl+shift+f10 for a test case, it will create a new run config
2. edit the config environments
3. press ctrl+shift+f10 again, it will create a new config named xxx(1), not reuse the existing config with the new environments

**Comment by Sherlock-Holo** [comment]
I've met this problem in Goland https://youtrack.jetbrains.com/issue/GO-10254
will it be the same problem?

**Comment by Undin** [comment]
@Sherlock-Holo I don't think it's the same problem. But maybe they are related
