### ISSUE TITLE
Not suggesting assert_eq!

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#6670]
## Environment

* **IntelliJ Rust plugin version:** 0.3.138.3572-203
* **Rust toolchain version:** 1.49.0 (e1884a8e3 2020-12-29) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2020.3.1 (CL-203.6682.181)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Since the new engine was introduced, the `assert_eq!` macro is no longer suggested. 

## Steps to reproduce

Try to type `assert_eq!` and notice it's not suggested.

**Comment by dima74** [comment]
@krojew thanks for the report!

Do I understand correctly that with new name resolution engine:

* Completion doesn't work when cursor is in the middle of macro path:

![image](https://user-images.githubusercontent.com/6505554/104947294-9a307700-59cc-11eb-9edb-ad085d5143b9.png)

* Completion works when cursor is at the end of macro path:

![image](https://user-images.githubusercontent.com/6505554/104947367-b92f0900-59cc-11eb-897c-ef6c5d40b3c6.png)

?

**Comment by krojew** [comment]
To be honest - this is very non-deterministic. Sometimes it works when writing, but mostly, the only suggestions are:

![image](https://user-images.githubusercontent.com/1268573/104947889-b4faef80-59bc-11eb-858a-f9fb07c583a9.png)

I've enabled the machine learning suggestions, if that makes a difference.

**Comment by dima74** [comment]
@krojew could you please full code from the screenshot?

**Comment by krojew** [comment]
I can't, since it's proprietary. I can tell you that it happens in all test modules. It may be influenced by the float_eq import: `use float_eq::*;`, since those seem to be the only suggestions.

**Comment by krojew** [comment]
Just made an observation that suggestions do not appear when typing, but they do appear when pressing the completion shortcut.

**Comment by dima74** [comment]
@krojew could you please install [nightly build](https://www.jetbrains.com/rust/download/) and check whether issue was fixed

**Comment by krojew** [comment]
Well, now the opposite happens - assert_* macros are immediately suggested, but the ones which were there before disappeared and require manually pressing ctrl+space.

**Comment by dima74** [comment]
> but the ones which were there before disappeared and require manually pressing ctrl+space.

Do I understand correctly that you mean e.g. `assert_inhabited` from `std::intrinsics`? Looks like with old resolve we have same behaviour, so probably it is expected

**Comment by krojew** [comment]
This is what I see when trying to write `assert`:

![image](https://user-images.githubusercontent.com/1268573/106012152-6b488e00-60bb-11eb-989b-a1ddb5fa8407.png)

After a few seconds:

![image](https://user-images.githubusercontent.com/1268573/106012220-7c919a80-60bb-11eb-816e-a9acb2838c53.png)

It's a bit slow (on 18 cores at 4.5GHz with 32GB RAM), but it works.

**Comment by dima74** [comment]
@krojew do you observe this behaviour (slow completion for some methods like `assert_inhabited`) with both old and name resolution engine?

**Comment by krojew** [comment]
Both take about the same time. In version 0.3.140.3644-203 it's about 1-2s.

**Comment by dima74** [comment]
Looks like slow completion is an unrelated issue, so I created #6778.

And completion of `assert_eq!` with new resolve was fixed in #6692, so I guess we can close this issue
