### ISSUE TITLE
Associated function should be completed even if base type is not imported

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#6679]
## Environment

* **IntelliJ Rust plugin version:** 0.3.140.3605-203-nightly
* **Rust toolchain version:** 1.48.0 (7eac88abb 2020-11-16) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2020.3.1 Ultimate Edition (IU-203.6682.168)
* **Operating system:** Linux 5.8.0-36-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
When I type some path `Foo::`, I expect to see completion for `Foo`s associated items even if `Foo` is not imported (but it's possible to import some `Foo`). The same behavior is applied to kotlin: try to write `ConcurrentHashMap.` and invoke the completion.

## Steps to reproduce
```rust
// No import for std::path::Path
fn main() {
    Path::n/*should complete `new`*/;
}
```

**Comment by dima74** [comment]
I believe it was fixed by #8315
