### ISSUE TITLE
Support operator highlighting

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#668]
`intellij-rust` currently has a Colors & Fonts setting for "Operator Sign", but it does not seem to be functional.

For reference:
- [Unary operator expressions](https://doc.rust-lang.org/reference.html#unary-operator-expressions)
- [Binary operator expressions](https://doc.rust-lang.org/reference.html#binary-operator-expressions)

[highlighterDemoText.rs](https://github.com/intellij-rust/intellij-rust/blob/9403901249c1db15ed8cdc49a48554d54bdd3666/src/main/resources/org/rust/ide/colors/highlighterDemoText.rs#L35) doesn't have `+=` marked up as an operator, for example.

Tested in
- `intellij-rust` 0.1.0.981
- PyCharm Pro 2016.2.3

**Comment by mkaput** [comment]
highlighterDemoText.rs uses markers only for parts highlighted by annotators. The problem lies elsewhere: [RustHighlighter](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/highlight/RustHighlighter.kt) doesn't map ops to operator sign colour.

**Comment by mkaput** [comment]
Yes and I think this is the only file which you would have to touch :)

**Comment by allengeorge** [comment]
Hmm. So there are 40 operators... Is there a way to refer to all operators as a whole, or do I have to add them all to that list?

**Comment by mkaput** [comment]
You can create a token set
