### ISSUE TITLE
Allow increasing the macro resolution step count

### ISSUE THREAD

**Issue by wdanilo** [intellij-rust/intellij-rust#6681]
## Problem Description

Hi, some of my macros are not expanded at all in IntelliJ when the macro input text gets bigger and the macro needs to make more resolution steps. According to some of the docs (like [here](https://blog.jetbrains.com/clion/2020/07/intellij-rust-0-3-new-macro-expansion-engine/)), the new expansion engine "If there are more calls inside, the process repeats until it reaches full expansion or hits the limit of 64 steps". I would like to ask for a possibility to change this limit from inside a config window in IntelliJ.

**Comment by max-dekock** [comment]
I'm having the same issue. This feature would be very useful

**Comment by micpap25** [comment]
Same problem for me.

**Comment by dima74** [comment]
Fixed by #8927
