### ISSUE TITLE
Macro expansion regression

### ISSUE THREAD

**Issue by alexforster** [intellij-rust/intellij-rust#6694]
## Environment

* **IntelliJ Rust plugin version:** 0.3.139.3615-203
* **Rust toolchain version:** 1.49.0 (e1884a8e3 2020-12-29) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.3.1 (CL-203.6682.181)
* **Operating system:** macOS 10.15.7
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Since updating to `#139` the following code results in an incorrect error highlight when `Display` is implemented via the a macro provided by the [thiserror](https://github.com/dtolnay/thiserror) crate.

## Steps to reproduce

```toml
[dependencies]
thiserror = "1.0.23"
```

```rust
#[derive(Debug, thiserror::Error)]
enum MyError {
    #[error("example arm")]
    ExampleArm,
}

type Result<T> = std::result::Result<T, MyError>;

fn thing() -> Result<()> {
    unimplemented!()
}

#[test]
fn test() {
    match thing() {
        Ok(_) => unimplemented!(),
        // the second `e` token is highlighted with: `MyError` doesn't implement `Display` (required by {})
        Err(e) => eprintln!("this implements Display: {}", e),
    }
}
```

**Comment by Undin** [comment]
@alexforster what version do you use before? `v138` shows the same error.
And it's expected currently since the plugin can't expand proc macros yet. See #1786 for more details
