### ISSUE TITLE
Disable the new 'Built tool window'

### ISSUE THREAD

**Issue by chertov** [intellij-rust/intellij-rust#6697]
## Environment

* **IntelliJ Rust plugin version:** 0.3.139.3615-203
* **Rust toolchain version:** 1.51.0-nightly (44e3daf5e 2020-12-31) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.3.1 (CL-203.6682.181)
* **Operating system:** macOS 10.15.7
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
I do not see the debug output from bindgen and my custom build steps.
How can i return a raw cargo build output?

**Comment by chertov** [comment]
I find the way to disable it!

Help -> Find Action -> type 'Experimental Features' -> click on 'Experimental Features...'

![image](https://user-images.githubusercontent.com/436625/105178851-9e2dd780-5b39-11eb-8065-1eba3ee33976.png)

In my opinion, this option should be in "Run / Debug Configuration" as well as the "--nocapture" option for the testing tool window. It would be very convenient!

**Comment by Undin** [comment]
@chertov thanks for feedback!

> I do not see the debug output from bindgen and my custom build steps.

Is your project open-sourced? It would be great to see the difference between console output and build view

> In my opinion, this option should be in "Run / Debug Configuration" as well as the "--nocapture" option for the testing tool window. It would be very convenient!

We didn't have a plan to implement it this way. We don't want to complicate UI of run configuration editor without actual users of such option. So it's quite interesting to check your use-case, probably it's possible to support it in Build View as well

**Comment by chertov** [comment]
@Undin, no it is not opensource project, but the output looks like: 
```

error: failed to run custom build command for `recorder v0.1.0 (/Users/user/dev/packages/android)`

Caused by:
  process didn't exit successfully: `/Users/user/rust_target/debug/build/recorder-f97f70973f2f8aeb/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'a `libclang` shared library is not loaded on this thread', /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.29.3/src/lib.rs:1659:1
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/core/src/panicking.rs:92:14
     2: core::option::expect_failed
               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/core/src/option.rs:1260:5
     3: core::option::Option<T>::expect
               at /Users/user/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:349:21
     4: clang_sys::clang_createIndex
               at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.29.3/src/link.rs:156:25
     5: clang::Index::new
               at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-0.24.0/src/lib.rs:2655:34
     6: dart_bindgen::Codegen::generate
               at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/dart-bindgen-0.1.8/src/lib.rs:98:21
     7: build_script_build::main
               at ./build.rs:18:20
     8: core::ops::function::FnOnce::call_once
               at /Users/user/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: build failed

Process finished with exit code 101
```

![image](https://user-images.githubusercontent.com/436625/105181290-aafffa80-5b3c-11eb-8ec7-2cf77bff9963.png)

![image](https://user-images.githubusercontent.com/436625/105181324-b6ebbc80-5b3c-11eb-8d28-68310ea0ce8c.png)

I guess this is a typical output for errors in __build.rs__

**Comment by chertov** [comment]
@Undin oh, thanks!! i see the output in root node!
![image](https://user-images.githubusercontent.com/436625/105183251-07641980-5b3f-11eb-9602-49ebe5873d50.png)

**Comment by Undin** [comment]
@chertov Great!
I've filed #6698 to show full error text in the corresponding node as well.
Thank you for this report!
