### ISSUE TITLE
Convert function to closure (and vice versa) intentions

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#6711]
## Environment

* **IntelliJ Rust plugin version:** 0.3.140.3613-203-nightly
* **Rust toolchain version:** 1.48.0 (7eac88abb 2020-11-16) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.3.1 (CL-203.6682.181)
* **Operating system:** macOS 10.16
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
It would be great to have intentions to convert a local function into a closure and vice versa. For example, to convert
```Rust
fn main() {
    fn foo(x: i32) -> i32 { x + 1 }
}
```
into
```Rust
fn main() {
    let foo = |x: i32| -> i32 { x + 1 };
}
```
and vice versa.

This intention might also be a quick fix for [`E0434`](https://doc.rust-lang.org/error-index.html#E0434) compiler error (which is not implemented yet and tracked [here](https://github.com/intellij-rust/intellij-rust/issues/886)). For example,
```Rust
fn main() {
    let env = 0;
    fn foo_func(x: i32) -> i32 { x + env + 1 } // error[E0434]: can't capture dynamic environment in a fn item; help: use the `|| { ... }` closure form instead
}
```

**Comment by nschoellhorn** [comment]
Hi, I'd like to work on this issue. Didn't contribute to this plugin yet, and would like to start getting into that :)

**Comment by ortem** [comment]
@nschoellhorn You're welcome! Feel free to ask any questions
