### ISSUE TITLE
Create function intention should create async function if necessary

### ISSUE THREAD

**Issue by dima74** [intellij-rust/intellij-rust#6712]
## Environment

* **IntelliJ Rust plugin version:** 0.3.139.3615-203
* **Rust toolchain version:** 1.51.0-nightly (4253153db 2021-01-17) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.3.1 (CL-203.6682.181)
* **Operating system:** Linux 5.10.9-arch1-1
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description
"Create function intention" should create async function if we call `.await` directly on function call result:

![Peek 2021-01-24 18-26](https://user-images.githubusercontent.com/6505554/105634986-cab35d80-5e71-11eb-88c6-eeff3f05454c.gif)

## Steps to reproduce
```rust
async fn foo() {
    /*cursor*/bar().await;
}
```

**Comment by Stzx** [comment]
I have already implemented it locally, can it be assigned to me?
