### ISSUE TITLE
Cargo project update failed: corrupted standard library: /Users/1/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src

### ISSUE THREAD

**Issue by wisegps** [intellij-rust/intellij-rust#6722]
## Environment

* **IntelliJ Rust plugin version:*0.2.123.3132-193*
* **Rust toolchain version:
$ rustc --version
rustc 1.49.0 (e1884a8e3 2020-12-29)
$ cargo --version
cargo 1.49.0 (d00d64df9 2020-12-05)

* **IDE name and version:*WebStorm 2019.3*
* 
* **Operating system:*MacOS BigSur*

## Problem description
Cargo project update failed: 
corrupted standard library: /Users/1/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src

## Steps to reproduce

![image](https://user-images.githubusercontent.com/4989061/105796652-432d3200-5fca-11eb-81a2-57f013905d51.png)

**Comment by Undin** [comment]
@wisegps you use a quite old plugin that doesn't support new structure of stdlib. Try to update your IDE and Rust plugin and it should fix your issue

**Comment by Undin** [comment]
Note, currently, 2020.3 is the latest major IDE version

**Comment by Undin** [comment]
I close this issue
@wisegps don't hesitate to ask any questions if IDE and plugin updates won't help

**Comment by pavlus** [comment]
IntelliJ 2020.* versions are quite buggy, there is a reason, why people still use older versions.

**Comment by erikbg7** [comment]
Updating IDE to 2021 version and Rust plugin to the last version solved the issue.

**Comment by rvalle** [comment]
I am using CLion 2018.3 which is the "perpetual" license that we own.

I am getting this corrupted standard library message.

However, as far as I understand, providing this standard library path is for the purpose of accessing the source code of the standard library while debugging.

Well, I can debug and step into functions in the standard library , and I can see that the files are being pulled from those paths that were "corrupt".

All seems to work just fine to me.
