### ISSUE TITLE
Incorrect macro expansion

### ISSUE THREAD

**Issue by PizzaCrust** [intellij-rust/intellij-rust#6736]
## Environment

* **IntelliJ Rust plugin version:** 0.3.141.3632-203-nightly
* **Rust toolchain version:** 1.51.0-nightly (4d0dd02ee 2021-01-23) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2020.3.2 Community Edition (IC-203.7148.57)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
Expansion doesn't include parameter

Expected expansion
```rust
pub enum A {
    b(String),
}
```
Bugged expansion
```rust
pub enum A {
    b(),
}
```
## Steps to reproduce
```rust
macro_rules! a {
    ($($name:ident $( ($($arg:tt)*) )?)*) => {
        pub enum A {
            $(
                $name $((a!(@marker $($arg)*)))?,
            )*
        }
    };
    (@marker $name:ty) => {
        $name
    }
}

a!{
    b(String)
}
```

**Comment by Undin** [comment]
@PizzaCrust Could you re-check it with the latest plugin version, please? I cannot reproduce it

**Comment by PizzaCrust** [comment]
@Undin Yep, its still bugged 
![image](https://user-images.githubusercontent.com/15954148/114361566-754d3980-9ba0-11eb-8793-6916f2aaafff.png)

**Comment by Undin** [comment]
@PizzaCrust Hm, sorry for disturbing. I've re-checked it myself once again with the latest stable, beta and nightly plugin versions and reproduced the bug each time. Interesting...

**Comment by mili-l** [comment]
see https://github.com/intellij-rust/intellij-rust/pull/9729
