### ISSUE TITLE
Reformat breaks custom macros

### ISSUE THREAD

**Issue by grossws** [intellij-rust/intellij-rust#674]
I have macro with `<-` token in its definition:

``` rust
macro_rules! try_ufn {
    ($e:ident <- $s:expr) => (try!(unsafe {
        $e($s.ctx).ok_or($crate::std::io::Error::from_raw_os_error(EINVAL as i32))
    }))
}
```

Currently reformat inserts space between `<` and `-` in code that use this macro and leads to compile error:

```
error: no rules expected the token `<`
   --> src/smbc.rs:115:53
    |
115 |         let open_fn = try_ufn!(smbc_getFunctionOpen < - self );
    |                                                     ^
```

Also, macro calls sometimes break parser: 

``` rust
trace!(target: "smbc", "open_with {:?}", options);
```

first parenthesis is marked as error with message `'(' unexpected` and colon is marked `'!', '&', ')', '=' or '|' expected, got ':'`.

rust plugin version: 0.1.0.1005-nightly

**Comment by matklad** [comment]
I believe both issues are fixed now, thanks @HeyLey !
