### ISSUE TITLE
Enums are not properly rendered in CLion 2021.1 with gdb

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#6746]
## Environment

* **IntelliJ Rust plugin version:** 0.3.141.SNAPSHOT-211-dev
* **Rust toolchain version:** 1.48.0 (7eac88abb 2020-11-16) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.1 EAP (CL-211.4961.21)
* **Operating system:** Linux 4.15.0-132-generic
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description
Expected:
![Screenshot from 2021-01-28 01-37-18](https://user-images.githubusercontent.com/2539310/106064074-4b8c8680-610a-11eb-8d3c-295d1660259e.png)

Actual:
![Screenshot from 2021-01-28 01-42-16](https://user-images.githubusercontent.com/2539310/106064095-547d5800-610a-11eb-8aea-cdeb16e9e218.png)

## Steps to reproduce
```rust
enum EnumA {
    Var1 { a: u32 },
    Var2(u64),
    Var3 { a: u32, b: TestEnumB },
}

enum TestEnumB {
    Var1(u64),
    Var2 { a: u32, b: String, c: EnumC },
}

enum EnumC {
    Var1(u64),
}

enum EnumD {}

fn main() {
    let a = EnumA::Var3 {
        a: 5,
        b: TestEnumB::Var2 {
            a: 5,
            b: "hello".to_owned(),
            c: EnumC::Var1(8),
        },
    };
    let d: EnumD;
    print!(""); // #break
}
```

**Comment by memoryallocator** [comment]
I faced the same issue. The simplier way to reproduce:

```
#[derive(Eq, PartialEq, Debug)]
    enum NestedEnum {
        NestedFirst,
        NestedSecond,
        NestedLast,
    }

    #[derive(Eq, PartialEq, Debug)]
    enum Enum {
        Variant(NestedEnum),
        A,
        B,
        C,
    }

    let q = Enum::A;

    assert_ne!(Enum::A, Enum::C);
    assert_eq!(q, Enum::A);
    assert_eq!(q, Enum::C);
```

![image](https://user-images.githubusercontent.com/40700358/107142312-16b8d480-693f-11eb-88e7-364e721446b3.png)

More than that, on commenting out Enum::B variant, I get
![Screenshot](https://user-images.githubusercontent.com/40700358/107142420-defe5c80-693f-11eb-85a0-4dae05c04484.png)

Environment
**CLion** 2020.3.2
**Build** #CL-203.7148.70, built on January 26, 2021
**Runtime version:** 11.0.9.1+11-b1145.77 amd64
**VM:** OpenJDK 64-Bit Server VM by JetBrains s.r.o.
**Linux** 5.4.0-65-generic

**Comment by Undin** [comment]
@memoryallocator could you specify what GDB do you use, please? You can check it via `Settings | Build, Execution, Deployment | Toolchains` settings

**Comment by memoryallocator** [comment]
@Undin I use _Bundled GDB_ (Version: 9.2).

**Comment by Undin** [comment]
@ortem looks like we don't know about such issues with 2020.3. Could you check it, please?

**Comment by ortem** [comment]
@Undin @memoryallocator I've opened a separate issue for this particular case since it is not related to the new CLion 2021.1. Please follow https://github.com/intellij-rust/intellij-rust/issues/6817
