### ISSUE TITLE
Can we expect WSL support in 2021?

### ISSUE THREAD

**Issue by sabbyX** [intellij-rust/intellij-rust#6760]
Almost all languages Jetbrains support got this feature 😄. If so, I would like to have the following features :)
* Something like [Run Targets](https://blog.jetbrains.com/idea/2021/01/run-targets-run-and-debug-your-app-in-the-desired-environment/), It would be really handy for cross-platform development
* Ability to launch project from inside WSL fs, when comes to WSL2, Linux->NTFS fs performance is horribly slow, chance to slow down compilation (?) or do we get something like [C++'s WSL toolchain](https://www.jetbrains.com/help/clion/how-to-use-wsl-development-environment-in-clion.html) ?

**Comment by lancelote** [comment]
Hi @sabbyX, with #6456 in place you can install the nightly plugin version and try the newly implemented support. Just don't forget to enable `org.rust.wsl` experimental feature.
