### ISSUE TITLE
`Fill missing arguments` adds redundant argument after introducing new parameter

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#6772]
## Environment

* **IntelliJ Rust plugin version:** 0.3.141.3634-203-nightly
* **Rust toolchain version:** 1.48.0 (7eac88abb 2020-11-16) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.3.1 (CL-203.6682.181)
* **Operating system:** macOS 10.16
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
![change_signature_bug](https://user-images.githubusercontent.com/4854600/106447407-82f48d80-6492-11eb-8fac-279d9eda1dd8.gif)

Before `Change signature` + `Fill missing arguments`:
```Rust
fn process_person(first_name: &str, age: u8) {
}
fn main() {
    process_person("Alice", 42);
}
```

After:
```Rust
fn process_person(first_name: &str, last_name: &str, age: u8) {
}
fn main() {
    process_person("Alice", "", 0), 42); // expected: `process_person("Alice", "", 42);`
}
```

**Comment by Kobzol** [comment]
Hmm, I guess that fill missing arguments wasn't really intended for situations where the argument is missing, but the comma is already there :D Time to fix it.

**Comment by Kobzol** [comment]
@ortem
This:
```rust
fn foo(a: u32, b: &str, c: u32) {}
fn main() {
    foo(0,/*caret*/ ,1);
}
```
is currently parsed like this:
```
RsExprStmtImpl(EXPR_STMT)
  RsCallExprImpl(CALL_EXPR)
    RsPathExprImpl(PATH_EXPR)
    RsValueArgumentListImpl(VALUE_ARGUMENT_LIST)
      PsiElement(()
      RsLitExprImpl(LIT_EXPR)
      PsiElement(,)
      PsiErrorElement:')' or <expr> expected, got ','
  PsiWhiteSpace
  PsiElement(,)
  RsExprStmtImpl(EXPR_STMT)
    RsLitExprImpl(LIT_EXPR)
    PsiErrorElement:'(', ';', <operator> or '[' expected, got ')'
  PsiElement())
```
And the `exprList` of the call arguments contains just the first argument (`0`). This is a bit problematic for this quick fix.

Without changing the parser, I tried to reconstruct the arguments step-by-step, i.e. put the first missing argument after a comma, then the second etc. It inserts the code correctly, i.e. I get from
```foo(0,,1)``` to ```foo(0, "", 1)```
However, the arguments are not reparsed correctly after this change, i.e. their `exprList` only contains `0` and `""`, even though their text is now correct, so it should contain all three arguments. Is there a way to somehow force reparsing of the element?

I tried `blockSupport.reparseRange`, but it does not seem to do what I want.

**Comment by ortem** [comment]
@Kobzol Probably `com.intellij.psi.PsiDocumentManager#doPostponedOperationsAndUnblockDocument` will help with reparsing (or something else from `PsiDocumentManager`)

**Comment by Kobzol** [comment]
Thanks, it seems to work.

**Comment by vlad20012** [comment]
I guess I've improved parsing a bit in #7019
