### ISSUE TITLE
No syntax highlighting in version 0.3.140.3644-203

### ISSUE THREAD

**Issue by lukaszwojtow** [intellij-rust/intellij-rust#6775]
## Environment

* **IntelliJ Rust plugin version:**
0.3.140.3644-203
* **Rust toolchain version:**
cargo --version:
cargo 1.49.0 (d00d64df9 2020-12-05)
rustup --version:
rustup 1.23.1 (3df2264a9 2020-11-30)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.49.0 (e1884a8e3 2020-12-29)`

* **IDE name and version:**
IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 26, 2021
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-64-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 3987M
Cores: 16
Non-Bundled Plugins: com.intellij.nativeDebug, org.toml.lang, org.sonarlint.idea, izhangzhihao.rainbow.brackets, Pythonid, DeepBugsPython, org.jetbrains.plugins.vue, org.rust.lang
Current Desktop: MATE
* **Operating system:**
Linux Mint 19.3 fully patched.
## Problem description
No syntax highlighting and very limited code completion with current version.

**Comment by Undin** [comment]
@lukaszwojtow could you provide logs (`Help | Show Log in %file_manager_name%` action), please?

**Comment by lukaszwojtow** [comment]
Logs: https://drive.google.com/file/d/1nFYQZaSnN2DPyiv8dVqoWWJlr46aw3kQ/view?usp=sharing

**Comment by Undin** [comment]
@lukaszwojtow Thanks!
It seems your issue is not related to Rust plugin. Try to disable `Rainbow Brackets` plugin or enable and update `Kotlin` plugin. As I understand, `Rainbow Brackets` plugin uses some classes from `Kotlin` plugin and it fails (for some reason) when `Kotlin` plugin is disabled.

**Comment by Undin** [comment]
Oh, I even found the commit when the corresponding bug was introduced in `Rainbow Brackets` plugin - https://github.com/izhangzhihao/intellij-rainbow-brackets/commit/4bc3010ba224bfc7a10a1d1a72e6d1999df769fd

**Comment by lukaszwojtow** [comment]
Amazing! Thank you! So a bug in RainbowBrackets made Rust plugin to stop working, nice...

**Comment by Undin** [comment]
> So a bug in RainbowBrackets made Rust plugin to stop working, nice...

As I see, it breaks any analysis for any language in editor. It's because of the architecture of IntelliJ platform: all plugins live in the same process and not isolated enough from each other in some cases. It allows them easily communicate with each other to provide cross language features but also it allows breaking almost anything in some cases.
