### ISSUE TITLE
Public methods do not appear in list of methods

### ISSUE THREAD

**Issue by arn-the-long-beard** [intellij-rust/intellij-rust#6779]
Hello guys :wink: 
## Environment

* **IntelliJ Rust plugin version:** 0.3.140.3644-203
* **Rust toolchain version:** 1.48.0-nightly (397b390cc 2020-08-27) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.3.2 (CL-203.7148.70)
* **Operating system:** Linux 5.4.0-65-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

I do not see my public methods in the window when writing my code .

![list](https://user-images.githubusercontent.com/30114057/106584948-18e9f000-6547-11eb-86e7-fc59d32e13e1.png)

## Steps to reproduce

Here is the page of the code : 

https://github.com/arn-the-long-beard/seed-routing/blob/main/src/router/mod.rs

Thank you guys for the help :smile:

**Comment by dima74** [comment]
This is because `Router` methods are inside <code>impl<Route: **Default** + ...> Router<Route> { ... }</code>, and `impl Default` for `ExampleRoutes` is generated by `#[derive(WithDefaultRoute)]` proc macro. The plugin currently doesn't support expanding procedural macros (#1786).

**Comment by arn-the-long-beard** [comment]
Haa thank you for your message :+1: 

So even if `Router` itself does not have any` #[derive(Default)]` it still does not get its methods because of the generic type `Route`.

Ok thank you. Maybe we could fine a way to ignore the generic type, just to help a bit :wink:  or I could try to write an other way.

I close the issue.

Thank you !
