### ISSUE TITLE
rustdoc template

### ISSUE THREAD

**Issue by kindlychung** [intellij-rust/intellij-rust#678]
Please see here: https://github.com/RustDT/RustDT/issues/135

**Comment by mrhota** [comment]
what should we use as abbreviations?

It seems like IntelliJ doesn't let you use "///" to insert a live template

**Comment by matklad** [comment]
I am a bit  uneasy about this feature: there is no strict format for Rust documentation, so I would expect that different projects would use different guidelines, if any. And even if there were a common format, it would be difficult to decide which parts of the general template are applicable to the current function. 

If the user needs this feature, they can add a custom live template themselves.
