### ISSUE TITLE
Editing in code blocks in doc comments completely broken

### ISSUE THREAD

**Issue by mahkoh** [intellij-rust/intellij-rust#6790]
## Environment

* **IntelliJ Rust plugin version:** 0.3.140.3644-203
* **Rust toolchain version:** 1.49.0 (e1884a8e3 2020-12-29) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.3.2 (CL-203.7148.70)
* **Operating system:** Linux 5.9.13-arch1-1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Start here:

```rust
/// ```
/// # use repr_c_impl::layout::{Array, Type};
/// let x = Array {
/// };
/// ```
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Array<I: Layout> {
    pub element_type: Box<Type<I>>,
    pub num_elements: Option<u64>,
}
```

Execute the "Add missing fields action". Result:

```rust
/// ```
/// # use repr_c_impl::layout::{Array, Type};
/// let x = Array {
/// element_type: ,num_elements: };
/// ```
#[derive(CloBox::new(Type { })ne, Debug, Eq, NonePartialEq)]
pub struct Array<I: Layout> {
    pub element_type: Box<Type<I>>,
    pub num_elements: Option<u64>,
}
```

---

Start here with the cursor at the marked position:

```rust
/// ```
/// # use repr_c_impl::layout::{Array, Type};
/// let x = Array {
/// <cursor>
/// };
/// ```
```

Press tab. Result:

```rust
/// ```
/// struct Array {
    <cursor> /// 
/// }
/// ```
```

**Comment by vlad20012** [comment]
Fixed by #7512
