### ISSUE TITLE
Pretty printers don't work in Windows GDB in CLion

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#6809]
Seems like CLion (even 2020.3) ignores pretty-printed values and renders them using the raw representation, although GDB console shows them fine:
<img width="991" alt="Screenshot 2021-02-05 at 13 34 22" src="https://user-images.githubusercontent.com/4854600/107022815-e47c6b00-67b6-11eb-8489-ddebe45b865e.png">

_Originally posted by @ortem in https://github.com/intellij-rust/intellij-rust/issues/6804#issuecomment-773950565_

**Comment by ortem** [comment]
@Undin Have you managed to reproduce this on your machine? I suppose this problem might occur only on my configuration (but probably not)

**Comment by Pzixel** [comment]
No, I actually have the exact same problem with nightly plugin and most recent CLion:

![image](https://user-images.githubusercontent.com/11201122/107126051-96528f00-68be-11eb-9c92-c1ed3895a87f.png)

**Comment by ortem** [comment]
@Pzixel OK, thank you!

**Comment by Undin** [comment]
Actually, I failed to reproduce it. Works for me for the following configurations:
CLion 2020.3, MinGW-w64 GDB 9.1, rustc 1.49.0
CLion 2020.3.2, MinGW-w64 GDB 9.1, rustc 1.49.0
CLion 2020.3.2, MinGW-w64 GDB 10.1, rustc 1.49.0

@ortem Could you provide your configuration to issue description, please?

@Pzixel Could you provide your configuration too, please?

**Comment by Pzixel** [comment]
CLion 2020.3.1
Build #CL-203.6682.181, built on December 30, 2020
You have a perpetual fallback license for this version.
Subscription is active until January 16, 2022.
Runtime version: 11.0.9.1+11-b1145.63 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 16
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: org.toml.lang, com.intellij.plugin.adernov.powershell, org.rust.lang, ru.adelf.idea.dotenv
0.3.141.3634-203-nightly

**Comment by ortem** [comment]
I suppose this problem could have been fixed since the MinGW bundled with CLion was updated
