### ISSUE TITLE
Wrong enum variant is rendered in CLion 2020.3 with GDB

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#6817]
## Environment

* **IntelliJ Rust plugin version:** 0.3.140
* **Rust toolchain version:** 1.49.0
* **IDE name and version:** CLion 2020.3.2 (CL-203.7148.70)
* **Operating system:** Linux 5.4.0-65-generic

## Problem description
```Rust
#[derive(Eq, PartialEq, Debug)]
enum NestedEnum {
    NestedFirst,
    NestedSecond,
    NestedLast,
}

#[derive(Eq, PartialEq, Debug)]
enum Enum {
    Variant(NestedEnum),
    A,
    B,
    C,
}

fn main() {
    let q = Enum::A;
    print!(""); // break
}
```
Expected: `Enum::A`
Actual: `Enum::C`

_Originally posted by @memoryallocator in https://github.com/intellij-rust/intellij-rust/issues/6746#issuecomment-774642594_

**Comment by Kobzol** [comment]
Similar code from https://github.com/intellij-rust/intellij-rust/issues/4155 also doesn't work with old GDB (tested with 9.2).

```rust
enum MyEnum1<T> { A(T), B }

fn main()
{
    let a1 = MyEnum1::A(String::from("111"));
    let a2 = MyEnum1::B;
}
```
However, I'm not sure if it's worth it to include code/fixes for the older GDB? I suppose that the currently supported version of CLion use a modern enough GDB so that it works with them.

**Comment by ortem** [comment]
@Kobzol Thank you, you're right. CLion bundles GDB v 10.1 [since 2021.1 release](https://www.jetbrains.com/help/clion/2021.1/configuring-debugger-options.html), and we're not aiming to support custom GDB binaries of older versions. Since we've already dropped 2020.3 IDEs support, this should issue can be closed.

**Comment by Kobzol** [comment]
https://github.com/intellij-rust/intellij-rust/blob/master/prettyPrinters/gdb_lookup.py#L12 this can probably also be removed :)
