### ISSUE TITLE
Exception in HttpUrlsUsageInspection in 2021.1

### ISSUE THREAD

**Issue by niktrop** [intellij-rust/intellij-rust#6822]
There is a new `HttpUrlsUsageInspection` in WebStorm. It fails for TOML literals:
https://ea.jetbrains.com/browser/ea_problems/250663

**Comment by Undin** [comment]
Actually, it's a bug in `HttpUrlsUsageInspection` inspection itself and it's already fixed (see https://youtrack.jetbrains.com/issue/IDEA-260297)

**Comment by Undin** [comment]
Similar to #6754
