### ISSUE TITLE
Enable Custom Postfix Completion

### ISSUE THREAD

**Issue by SonicZentropy** [intellij-rust/intellij-rust#6823]
Simple feature request!  I would like the ability to build my own postfix completions in Rust like you can with other languages.  I'm happy to work on this myself if someone can point me in the correct direction

**Comment by Kobzol** [comment]
I think that for enabling this you need to implement `RsPostfixTemplateProvider::getPresentableName`, i.e. like this:
```kotlin
override fun getPresentableName(): String = "Rust"
```
and then the harder part :D Implement `RsPostfixTemplateProvider::createEditor` (see https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt). For an inspiration, you can check the Java implementation here: https://github.com/JetBrains/intellij-community/blob/master/java/java-impl/src/com/intellij/codeInsight/template/postfix/templates/editable/JavaPostfixTemplateEditor.java.

Other useful class seems to be `TemplateContextType`, which represents a context on which templates can be applied (i.e. an generic expression, a match expression, a let declaration, etc.). See https://github.com/JetBrains/intellij-community/blob/master/java/java-impl/src/com/intellij/codeInsight/template/JavaStringContextType.java for an example. You can implement several such contexts to let the user choose where should the custom template be applicable.

Just FYI, until this feature is implemented, as a workaround you can use https://github.com/xylo/intellij-postfix-templates, which has some primitive support for Rust. You can also find implementation hints for custom templates in this repository.
