### ISSUE TITLE
Switching optional dependencies

### ISSUE THREAD

**Issue by survived** [intellij-rust/intellij-rust#6828]
## Environment

* **IntelliJ Rust plugin version:** 0.3.140.3644-203
* **Rust toolchain version:** stable-x86_64-apple-darwin (rustc 1.49.0 (e1884a8e3 2020-12-29))
* **IDE name and version:** GoLand 2020.3
* **Operating system:** MacOS 11.2

## Problem description
I used to have ability to switch optional dependencies (turn them on/off). Whether optional dependency is turned on/off affects on conditional compilation and hints from IDE. Since the last release I'm able to switch features, but not optional dependencies.

## Steps to reproduce

https://user-images.githubusercontent.com/14890036/107629817-3f213580-6c95-11eb-853f-f60112429029.mov

**Comment by Undin** [comment]
@survived Thanks for the report!
I've reproduced the issue.
As a temporary workaround, you may use inline tables to make it work

**Comment by Undin** [comment]
Regression after #6623

**Comment by survived** [comment]
> As a temporary workaround, you may use inline tables to make it work

Thank you, this actually makes it work!
