### ISSUE TITLE
Support function parameter info

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#685]
[CLion and other IntelliJ IDEs support parameter info](https://www.jetbrains.com/help/clion/2016.1/viewing-method-parameter-information.html), which helps make it more clear which parameters and their types are being passed while you type.

![clion-parameter-info](https://cloud.githubusercontent.com/assets/10340167/18800656/25910588-81ac-11e6-8a0d-44497bfab399.png)

This feature would make a great addition to `intellij-rust`, and I think all of the information is already captured and used elsewhere in the plugin for things like function Quick Doc.

**Comment by matklad** [comment]
dupe: https://github.com/intellij-rust/intellij-rust/issues/437.
