### ISSUE TITLE
Incorrect "toolchain is incompatible with the plugin" message

### ISSUE THREAD

**Issue by danslapman** [intellij-rust/intellij-rust#686]
![intellij-rust-bug](https://cloud.githubusercontent.com/assets/1708325/18809132/52f55822-827d-11e6-8ae8-b91dc47410d7.png)

**Comment by mkaput** [comment]
Your cargo seems not to have `cargo metadata` command, hence the warning

**Comment by danslapman** [comment]
Just executed `cargo metadata` in project's folder, works fine.

**Comment by johnthagen** [comment]
Probably similar / duplicate of #659.

**Comment by matklad** [comment]
>Your cargo seems not to have cargo metadata command, hence the warning

Not sure what was the real issue, but turns out we executed cargo a bunch of times for no real reason. Perhaps something was wrong with concurrent Cargos? This has happend before.
