### ISSUE TITLE
Code completion for Gradle Version Catalogs in TOML files

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [intellij-rust/intellij-rust#6860]
With Gradle 7.0, there will be an official way to declare dependencies in TOML files and in Kotlin.

Should be great that the TOML plugin adds code completion for this syntax.

Björn Kautler suggests: I'd recommend to know from the imported Gradle build which TOML files are version catalogs and then provide completion for exactly those files.

Related docs:
https://docs.gradle.org/nightly/userguide/platforms.html#sub:conventional-dependencies-toml

**Comment by Undin** [comment]
I don't think that it should be done in TOML plugin since it knows nothing about any specific format.
File an issue IDEA [issue tracker](https://youtrack.jetbrains.com/newIssue?project=IDEA) please

**Comment by JavierSegoviaCordoba** [comment]
Done: https://youtrack.jetbrains.com/issue/IDEA-262280
