### ISSUE TITLE
Loses track of macros when rebinding on "use" 

### ISSUE THREAD

**Issue by njam** [intellij-rust/intellij-rust#6863]
## Environment

* **IntelliJ Rust plugin version:** 0.3.141.3674-203
* **Rust toolchain version:** 1.49.0
* **IDE name and version:** IntelliJ IDEA 2020.3.2
* **Operating system:** Linux 5.10.7

## Problem description

When rebinding (aliasing, renaming) a macro on "use" it seems IntelliJ Rust loses track of it. Finding usages doesn't work anymore, nor does "go to implementation".

For example in this file, it's possible to go to the implementation for `foo!()`, but not for `foo2!()`:
```rust
use crate::foo as foo2;

#[macro_export]
macro_rules! foo {
    () => { println!("Hello world") };
}

fn main() {
    foo!();
    foo2!();
}
```

## Steps to reproduce

1. Create a new project with the `src/main.rs` as above.
2. Try to Ctrl+Click on foo!() and foo2!()

**Comment by dima74** [comment]
Please try to [enable](https://github.com/intellij-rust/intellij-rust/pull/6378) new name resolution engine

**Comment by njam** [comment]
I can confirm that it works when enabling the "new name resolution engine"!
