### ISSUE TITLE
Run terminal not support a progressbar (indicatif)

### ISSUE THREAD

**Issue by mkueh** [intellij-rust/intellij-rust#6867]
Hello,

I have tried to add a progress bar (https://docs.rs/indicatif/0.15.0/indicatif/) to my software, unfortunately it does not display "live" in CLion.

## Environment

CLion 2020.3.2 x64
Rust 1.50
Windows 10

## Problem description

The progressbar is not displayed in CLion

## Steps to reproduce

example-code:
https://github.com/mitsuhiko/indicatif/blob/main/examples/download.rs

**Comment by dariuszk** [comment]
Hello, 

CLion 2021.3.2
Rust 1.58
Windows 11

I notice this same problem, but one additional remark.  The progress bar from indicatif is not visible when the program is started by run/debug configuration, but when the app is started in the tab terminal progress is visible.

**Comment by aedm** [comment]
Indicatif only seems to work in terminals, and CLion's output windows aren't terminals. CLion just captures and displays stdout.

**Comment by Undin** [comment]
@mchernyavsky does #8807 fix this issue?

**Comment by mchernyavsky** [comment]
@Undin Yes, I have checked it:

<img width="766" alt="Screen Shot 2022-06-03 at 18 20 56" src="https://user-images.githubusercontent.com/6079006/171884055-588fa6cd-48cb-4824-b630-67f7593a6684.png">
