### ISSUE TITLE
Typing quote (") inside a raw string literal should not close it

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#687]
```
r###"Hello, <caret> World!"###
```

typing `"` should produce

```
r###"Hello, "" World!"###
```

now it gives

```
r###"Hello, ""### World!"###
```

**Comment by matklad** [comment]
Yep, it's important that `<caret>` is on the whitespace. cc @mkaput

**Comment by mkaput** [comment]
Hmm I guess it's needed to check in [RustQuoteHandler#getClosingQuote](https://github.com/intellij-rust/intellij-rust/blob/6c1ed8532ea6071ecd2ccc1d96c01711144ac207/src/main/kotlin/org/rust/ide/typing/RustQuoteHandler.kt#L81) whether `offset` is inside value.

**Comment by matklad** [comment]
Also, typing `'` should not add `'"###` :)
