### ISSUE TITLE
IntelliJ Error When Importing a Rust project

### ISSUE THREAD

**Issue by joesan** [intellij-rust/intellij-rust#6871]
## Environment

* **IntelliJ Rust plugin version:** - 0.3.139.3615-203
* **Rust toolchain version:** - rustup 1.23.1 (3df2264a9 2020-11-30)
* **IDE name and version:** - IntelliJ 2020.3 
* **Operating system:** - Ubuntu 20.04
* **Rustc Version:** - rustc 1.50.0 (cb75ad5db 2021-02-10)

## Problem description
Importing a Rust project in IntelliJ threw up an error saying:

```
Execution failed (exit code 1).
/home/joesan/.cargo/bin/cargo metadata --verbose --format-version 1 --all-features
stdout : error: no override and no default toolchain set
error: backtrace:
error:    0: error_chain::backtrace::imp::InternalBacktrace::new
   1: rustup::config::Cfg::find_or_install_override_toolchain_or_default
   2: rustup_init::main
   3: std::sys_common::backtrace::__rust_begin_short_backtrace
   4: main
   5: __libc_start_main
   6: <unknown>


stderr : 
```

## Steps to reproduce
Just imported a project (https://github.com/lycheeverse/lychee) and I got this error.

**Comment by Undin** [comment]
@joesan As you can see in "error: no override and no default toolchain set" error message, rustup fails to find toolchain for the project. Just set up default toolchain (e.g. `rustup default stable`) or add [override](https://rust-lang.github.io/rustup/overrides.html) for the project

**Comment by joesan** [comment]
```
joesan@joesan-InfinityBook-S-14-v5:~$ rustup default stable
info: using existing install for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.50.0 (cb75ad5db 2021-02-10)
```

I do have the toolchain set as default, but still it would not be picked by Intellij. Could you please reopen this ticket?

**Comment by Undin** [comment]
@joesan could you elaborate what "it would not be picked by Intellij" phrase mean in your case?

**Comment by joesan** [comment]
/home/joesan/.cargo/bin/cargo test --color=always --no-run
error: no override and no default toolchain set

Process finished with exit code 1

**Comment by joesan** [comment]
When I run cargo test from the console, it just runs. Do I need to set up anything else in IntelliJ? Where would IntelliJ look for Rust? Where in IntelliJ do I tell it to look under /home/joesan/.cargo/bin?

**Comment by Undin** [comment]
By default, the plugin looks for cargo in `~/.cargo/bin` dir (in `/home/joesan/.cargo/bin` in your case).
Are you sure that when you run cargo from console, you run exactly binary from `/home/joesan/.cargo/bin`?
Let's check the following things:
- launch `which cargo` to get location of your cargo binary
- launch `/home/joesan/.cargo/bin/cargo test --color=always --no-run` from console in project directory

**Comment by joesan** [comment]
```
joesan@joesan-InfinityBook-S-14-v5:~/.cargo/bin$ which cargo
/home/joesan/.cargo/bin/cargo
```

```
joesan@joesan-InfinityBook-S-14-v5:~/Projects/Private/rust-projects/lychee$ /home/joesan/.cargo/bin/cargo test --color=always --no-run
    Finished test [unoptimized + debuginfo] target(s) in 0.12s
joesan@joesan-InfinityBook-S-14-v5:~/Projects/Private/rust-projects/lychee$ 

```

**Comment by joesan** [comment]
Do I have to add some RUST_UP Home or something like that?

**Comment by joesan** [comment]
I have the following in my .bash_profile file:

```
export RUSTUP_HOME="/opt/softwares/rustup"
export PATH="$SBT_HOME/bin:$SCALA_HOME/bin:$MAVEN_HOME/bin:$RUSTUP_HOME:$ROS_ROOT:$KUBECTL_HOME:$TERRAFORM_HOME:$MINIKUBE_HOME:$PATH:/usr/local/bin"
```

I have installed the toolchain in the following folder path:

```
joesan@joesan-InfinityBook-S-14-v5:/opt/softwares/rustup$ ls
drwxrwxr-x joesan joesan   4 KB Fri Aug 28 21:57:25 2020  .
drwxr-xr-x joesan joesan   4 KB Tue Dec 22 09:54:21 2020  ..
drwxrwxr-x joesan joesan   4 KB Sat Feb 20 08:28:20 2021  downloads
.rw-rw-r-- joesan joesan 102 B  Fri Feb 26 16:40:08 2021  settings.toml
drwxrwxr-x joesan joesan  12 KB Fri Feb 26 16:38:09 2021  tmp
drwxrwxr-x joesan joesan   4 KB Fri Aug 28 21:57:25 2020  toolchains
drwxrwxr-x joesan joesan   4 KB Fri Aug 28 21:57:33 2020  update-hashes
joesan@joesan-InfinityBook-S-14-v5:/opt/softwares/rustup$ 
```

**Comment by joesan** [comment]
joesan@joesan-InfinityBook-S-14-v5:~$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /opt/softwares/rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.50.0 (cb75ad5db 2021-02-10)

**Comment by joesan** [comment]
Resolved this. Go to File -> Settings and set the Tool Chain Location manually which points to:

`/opt/softwares/rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin`
