### ISSUE TITLE
Mismatched types [E0308] reported in Clion, but not with cargo check

### ISSUE THREAD

**Issue by sbehnke** [intellij-rust/intellij-rust#6880]
## Environment

* **IntelliJ Rust plugin version:** 0.3.141.3674-203
* **Rust toolchain version:** 1.50.0 (cb75ad5db 2021-02-10) aarch64-apple-darwin
* **IDE name and version:** CLion 2020.3.2 (CL-203.7148.70)
* **Operating system:** macOS 11.2.1
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description
The Rust plugin in Clion shows and error for a mismatched type, but this error does not appear running cargo check, and cargo runs without issues.

## Steps to reproduce
I've included the project file to reproduce the issue.

[snake.zip](https://github.com/intellij-rust/intellij-rust/files/6017150/snake.zip)

**Comment by Undin** [comment]
@sbehnke Thanks for the report!

Do I understand correctly that you are about the following false-positive error?
![image](https://user-images.githubusercontent.com/2539310/108618711-5993a580-7431-11eb-9fcf-71bdf09a4161.png)

**Comment by sbehnke** [comment]
I believe so, yes. Cargo check doesn't report this issue, but the rust plugin does. Sounds like a false positive.

**Comment by Undin** [comment]
Oh, unfortunately, it's expected for now. `Clone` trait is implemented for `Handle<T>` only when `T : Asset`; at the same time there is blanket implementation `impl<T> Asset for T where T: TypeUuid + AssetDynamic + TypeUuidDynamic {}`. And `ColorMaterial` struct implements `TypeUuid` via proc derive macro
<img width="496" alt="Screen Shot 2021-02-21 at 18 38 59" src="https://user-images.githubusercontent.com/2539310/108630096-363e1a00-7474-11eb-8fa4-d681cd68560b.png">

But the plugin cannot expand proc macros for now. See #1786 as base meta issue about proc macro support. Actually, we've already started implementing it and as a first step we are going to support function-like proc macros (see #6564). Derive proc macros is supposed to be supported as a second step

**Comment by sbehnke** [comment]
Thanks for the update. Looking forward to the fix whenever it happens. 😁

**Comment by ta32** [comment]
@Undin Is this a bug in the editor introspections or is it from cargo check. I saw in another issue you are re-implementing the linting instead of using an external linter. I went to the introspections settings and I couldn't disable this introspection.

After I updated I started receiving errors for this "mismatched types [E0308]"
![image](https://user-images.githubusercontent.com/26617779/110074994-332d1d00-7dd6-11eb-9bf1-f59f6a8ebae2.png)

* **IntelliJ Rust plugin version:** 0.3.142.3705-203
* **Rust toolchain version:** 1.50.0 (cb75ad5db 2021-02-10) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2020.3.2 (CL-203.7148.70)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

**Comment by bandrefilipe** [comment]
> @Undin Is this a bug in the editor introspections? I saw in another issue you are re-implementing the linting instead of using an external linter. I went to the rust introspections settings and I couldn't disable this introspection. Is there a way to temporarily disable all plugin inspections and only use cargo check?
> 
> After I updated I started receiving errors for this "mismatched types [E0308]" ![image](https://user-images.githubusercontent.com/26617779/110074994-332d1d00-7dd6-11eb-9bf1-f59f6a8ebae2.png)
> 
>     * **IntelliJ Rust plugin version:** 0.3.142.3705-203
> 
>     * **Rust toolchain version:** 1.50.0 (cb75ad5db 2021-02-10) x86_64-pc-windows-msvc
> 
>     * **IDE name and version:** CLion 2020.3.2 (CL-203.7148.70)
> 
>     * **Operating system:** Windows 10 10.0
> 
>     * **Macro expansion engine:** new
> 
>     * **Name resolution engine:** new

Hey, @ta32 ! Have you found any solution to this problem?
I'm having the exact same issue with Yew and my 'solution' for now is needlessly assigning the result of the `html!` macro to a variable and then returning it immediately after.
