### ISSUE TITLE
Can't find a way to disable 'greyed out' cfg setting

### ISSUE THREAD

**Issue by raphaelcohn** [intellij-rust/intellij-rust#6882]
I like the way code for non-active cfgs is greyed out, except it's become really annoying for my current workflow, and I'd like to disable it.

In essence, I'm working on some x86_64 code that uses `cfg(target_feature)` to enable AVX, etc. The cfg grey out code things this feature isn't available (when it is). Worse, sometimes I need to twork on `target_feature` that my native CPU doesn't support. Greying out all the code and removing all syntax highlighting makes it really hard to avoid subtle typos et al.

Is there a way to disable the `cfg` greying out?

PS I know this isn't the right place, but the forum is gitter, which doesn't work for me.

**Comment by ortem** [comment]
@raphaelcohn IntelliJ Rust uses `$ rustc --print cfg` command to collect enabled `cfg` options. Conditionally enabled code should not be greyed out in the IDE, e.g. when using `target_features` supported by your CPU. Please check `$ rustc --print cfg` output and provide us more details on what exactly goes wrong with the supported target features.

As for working with features unsupported by your actual platform, please follow the corresponding issue on enabling specific `cfg` option: https://github.com/intellij-rust/intellij-rust/issues/5188.

If you want to disable the greying out for all your code, there are two potential ways of doing this:
1. Open `Preferences | Editor | Color Scheme | Rust` and disable `Conditionally disabled code` foreground. This just affects  colors, ignoring all the logic related to conditional code: code navigation, type inference, code completion, disabled annotations and inspections, and so on
2. Open `Registry...` (can be found via `Ctrl+Shift+A` menu) and disable `rust.cfg.attributes.enabled` option. This should completely disable all the mentioned logic

Feel free to ask any further questions and provide more information right here!

**Comment by raphaelcohn** [comment]
@ortem - thank you for the suggestions.

Just using whatever the native CPU target supports is fundamentally the cause of this problem. I'm running a Mac Pro trash can, so I should be seeing support upto avx, but rustc assumes the native CPU only supports SSE2; this is a flaw in rustc itself.

Over the last 10 years, I've seen the assumption that one is not cross compiling to be a common idiom that breaks many, many toolchains. I've reported bugs in more C libraries than I can recall, and even rust has similar assumptions, eg libc assuming it can call a freebsd binary on the compiling machine. All compiler toolchains and workflows should always assume cross-compilation from the get-go.

I've worked around this by creating my own shadow toolchain, then using POSIX shell binaries to inject the target-features  I want. This isn't perfect - it ties me into a particular target (which is annoying - I'd like to be able to switch targets when coding to see what's going on), and there's no easy way to force the plugin to resync if I decide to change targets.

The downside to this approach is I really need the shadow toolchain path to be relative to my .idea folder, so I can check it into source control and have others on my team share it.

An example simple binary to shadow rustc:-

```
#!/usr/bin/env sh
# This file is part of r-parser. It is subject to the license terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/r-parser/master/COPYRIGHT. No part of r-parser, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
# Copyright © 2021 The developers of r-parser. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/r-parser/master/COPYRIGHT.


set -e
set -u
set -f

_program_path_find()
{
	if [ "${0%/*}" = "$0" ]; then

		# We've been invoked by the interpreter as, say, bash program
		if [ -r "$0" ]; then
			pwd -P
		# Clutching at straws; probably run via a download, anonymous script, etc, weird execve, etc
		else
			printf '\n'
		fi

	else

		# We've been invoked with a relative or absolute path (also when invoked via PATH in a shell)

		_program_path_find_parentPath()
		{
			parentPath="${scriptPath%/*}"
			if [ -z "$parentPath" ]; then
				parentPath='/'
			fi
			cd "$parentPath" 1>/dev/null
		}

		# pdksh / mksh have problems with unsetting a variable that was never set...
		if [ "${CDPATH+set}" = 'set' ]; then
			unset CDPATH
		fi

		if command -v realpath 1>/dev/null 2>/dev/null; then
			(
				scriptPath="$(realpath "$0")"

				_program_path_find_parentPath
				pwd -P
			)
		elif command -v readlink 1>/dev/null 2>/dev/null; then
			(
				local recursionDepth=0
				_program_path_resolve_symlinks_recursively()
				{
					local unresolvedPath="$1"
					
					recursionDepth=$((recursionDepth + 1))
					
					if [ $recursionDepth -gt 10 ]; then
						printf '%s\n' 'Recursion to depths greater than 10 is not allowed when resolving links.'
						return 1
					fi
					
					local potentialLinkDestination="$(readlink -- "$unresolvedPath")"
					
					if [ -z "$potentialLinkDestination" ]; then
						scriptPath="$unresolvedPath"
						return 0
					fi
					local linkDestination="$potentialLinkDestination"
					local parentFolderPath="${unresolvedPath%/*}"
					
					if [ "$parentFolderPath" = "$unresolvedPath" ]; then
						_program_path_resolve_symlinks_recursively "$linkDestination"
					else
						case "$linkDestination" in
														
							/*)
								_program_path_resolve_symlinks_recursively "$linkDestination"
							;;
							
							*)
								_program_path_resolve_symlinks_recursively "$parentFolderPath"/"$linkDestination"
							;;
							
						esac
					fi
				}

				scriptPath="$0"
				_program_path_resolve_symlinks_recursively "$scriptPath"

				_program_path_find_parentPath
				pwd -P
			)
		else
			# This approach will fail in corner cases where the script itself is a symlink in a path not parallel with the concrete script
			(
				scriptPath="$0"

				_program_path_find_parentPath
				pwd -P
			)
		fi

	fi
}

set_requires_target()
{
	local results_vary_by_target=false
	local can_set_target=true
	local can_set_target_cpu=true
	while [ $# -ne 0 ];
	do
		case "$1" in
			
			'--print')
				if [ $# -gt 1 ]; then
				
					case "$2" in
					
						'cfg'|'target-cpus'|'target-features')
							results_vary_by_target=true
						;;
					
						*)
							:
						;;
					
					esac
					shift 1
				fi
			;;
			
			'--target')
				can_set_target=false
			;;
			
			'-C')
				if [ $# -gt 1 ]; then
				
					case "$2" in
					
						target-cpu=*)
							results_vary_by_target=true
						;;
					
						*)
							:
						;;
						
					esac
					shift 1
				fi
			;;
		
			*)
				:
			;;
			
		esac
		
		shift 1
	done
	
	if $results_vary_by_target; then
		if $can_set_target; then
			requires_target=true
		fi
		if $can_set_target_cpu; then
			requires_target_cpu=true
		fi
	fi
}

main()
{
	local requires_target=false
	local requires_target_cpu=false
	set_requires_target "$@"
	
	if $requires_target; then
		set -- "$@" --target x86_64-unknown-linux-musl
	fi
	if $requires_target_cpu; then
		set -- "$@" -C target-cpu='tigerlake'
	fi
	
	exec ~/.cargo/bin/rustc "$@"
}

main "$@"
```

A full set for anyone else interested is at <https://github.com/lemonrock/.cargo/tree/master/tools/intellij-rust-plugin-toolchain>; note that it could do with a lot more work to be suitable for anything other than my very specific case.

**Comment by raphaelcohn** [comment]
Closing this @ortem's answer is complete.
