### ISSUE TITLE
Debugger downloading failed

### ISSUE THREAD

**Issue by porfirioribeiro** [intellij-rust/intellij-rust#6911]
## Environment

* **IntelliJ Rust plugin version:** 0.3.143.3706-211-nightly
* **Rust toolchain version:** 1.52.0-nightly (9c09c1f7c 2021-02-26) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2021.1 EAP Ultimate Edition (IU-211.6222.4)
* **Operating system:** Linux 5.11.1-1-manjaro
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
I'm having troubles to get the debug to work in IDEA 2021.1 EAP, it always fails to download the debugger

## Steps to reproduce
![image](https://user-images.githubusercontent.com/499246/109627289-61420100-7b39-11eb-89e7-f5a9893f74a6.png)
![image](https://user-images.githubusercontent.com/499246/109627345-70c14a00-7b39-11eb-9986-2f38a2937cb4.png)
It goes until the middle of the progressbar and then fails
![image](https://user-images.githubusercontent.com/499246/109627420-86cf0a80-7b39-11eb-8483-9191309c565a.png)

**Comment by Undin** [comment]
Should be fixed now

**Comment by porfirioribeiro** [comment]
It is working, thank you!
