### ISSUE TITLE
Completion option for "println!" with prefilled "{}"

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#6920]
## Environment

* **IntelliJ Rust plugin version:** 0.3.143.3703-211-nightly
* **Rust toolchain version:** 1.52.0-nightly (3f5aee2d5 2021-02-12) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.2 EAP (CL-212.454)
* **Operating system:** macOS 10.15.6
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Based on the user feedback https://plugins.jetbrains.com/plugin/8182-rust/reviews#review=50514

Provide a completion option / life template for `println!("{}", |);` as it is quite often used this way.

**Comment by Undin** [comment]
Note, `println` postfix completion does exactly the same
![2021-03-04 19 27 39](https://user-images.githubusercontent.com/2539310/109995871-bc354d00-7d1f-11eb-8151-f7c2a85b37ab.gif)

**Comment by lancelote** [comment]
Ah, I see, that is actually perfect from my point of view.

**Comment by Undin** [comment]
@lancelote I suppose we can close it, don't I?
