### ISSUE TITLE
Rustfmt is broken?

### ISSUE THREAD

**Issue by qiujiangkun** [intellij-rust/intellij-rust#6921]
## Environment

* **IntelliJ Rust plugin version:** 0.3.142.3705-203
* **Rust toolchain version:** rustc 1.52.0-nightly (e9920ef77 2021-02-11)
* **IDE name and version:** Clion
* **Operating system:** Manjaro

## Problem description
I can run `cargo fmt`, but can't run `rustfmt --emit=stdout`and copy & paste my code into stdin. It seems that intellij-rust did not specify the toml file. I have `edition = "2018"` in my `Cargo.toml`.
```log
/usr/bin/rustfmt --emit=stdout
					stdout : 
					stderr : error[E0670]: `async fn` is not permitted in Rust 2015
					--> <stdin>:13:5
					13 | pub async fn run_async_produce_topic<Interface: KafkaInterface>(_interface: Interface, config: AppConfig) -> Result<(), KafcatError> {
					^^^^^ to use `async fn`, switch to Rust 2018 or later
					= help: set `edition = "2018"` in `Cargo.toml`
					= note: for more on editions, read https://doc.rust-lang.org/edition-guide
```

**Comment by qiujiangkun** [comment]
Found out it's because I didn't set `edition = "2018"` in `rustfmt.toml`
https://github.com/rust-lang/rustfmt/issues/4454

**Comment by Undin** [comment]
@qiujiangkun I suppose it can be closed?

**Comment by qiujiangkun** [comment]
I don't think it being solved. I suppose it works out of the box

**Comment by qiujiangkun** [comment]
Well, it worked for me somehow.
