### ISSUE TITLE
Can't detect "use of undeclared crate or module" error, the same code in vscode can be detected.

### ISSUE THREAD

**Issue by SummerVibes** [intellij-rust/intellij-rust#6932]
## Environment

* **IntelliJ Rust plugin version:0.3.142.3705-203**
* **Rust toolchain version:*1.5*
* **IDE name and version:Clion 2020.3.2**
* **Operating system:MacOS 11.2.2**

## Problem description
Can't detect "use of undeclared crate or module" error, the same code in vscode can be detected.
![image](https://user-images.githubusercontent.com/32605477/110341501-5b7e7b00-8065-11eb-824e-7912d9f27222.png)
![image](https://user-images.githubusercontent.com/32605477/110341631-82d54800-8065-11eb-9436-f3f8adfee8c7.png)

## Steps to reproduce
1. git clone https://github.com/SummerVibes/lite-raft.git
2. open the project and open lite-rpc/src/client/client.rs

**Comment by Undin** [comment]
Actually, the plugin can show you some of these errors via embedded inspections but they are disabled by default in some cases not to show possible false positives (especially, when you use proc macros). But if you want to try, disable `Ignore unresolved references without quick fix` option of `Rust | Unresolved reference` inspection in `Settings / Preferences | Editor | Inspections` settings.
Eventually, they will be enabled by default in all cases.

Also, the plugin has a feature called `External Linter`. It runs `cargo check` or `cargo clippy` in the background and highlights your code in editor in accordance with the result (vscode uses the same approach). You can enable `Run external linter to analyze code on the fly` option in `Settings / Preferences | Languages & Frameworks | Rust | Cargo`. See https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-code-analysis.html#external-linters for more details

**Comment by SummerVibes** [comment]
That's what I need, thanks!
