### ISSUE TITLE
Having variable as output of asm! macro is not counted as initializing it

### ISSUE THREAD

**Issue by Teln0** [intellij-rust/intellij-rust#6937]
## Environment

* **IntelliJ Rust plugin version:** 0.3.142.3705-203
* **Rust toolchain version:** 1.52.0-nightly (caca2121f 2021-03-05) x86_64-unknown-none
* **IDE name and version:** CLion 2020.3.2 (CL-203.7148.70)
* **Operating system:** Linux 5.11.2-arch1-1
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description
I have a function in my code that reads from a register into a variable then returns it. The variable is not initialized before being used inside of the asm! macro and when I try to return in, Clion tells me it is not initialized and underlines it with squiggles as if it was an error.

## Steps to reproduce

```rust
    pub fn read_cr3() -> usize {
        let result: u64;
        unsafe {
            asm!("mov {}, cr3", out(reg) result);
        };
        result as usize
    }
```

With this Clion says there is an error when there isn't

**Comment by Kobzol** [comment]
Probably the same situation as in https://github.com/intellij-rust/intellij-rust/issues/5815.

**Comment by Undin** [comment]
@Kobzol Thanks!
I'd prefer not to mark this issue as duplicate since #5815 is produced by different analysis and they should be checked separately (even they will have the same fix in the future)
But yes, the cause of these issues is the same - currently plugin knows nothing about `asm` macro
