### ISSUE TITLE
Dependency completion shows empty versions

### ISSUE THREAD

**Issue by ralfbiedert** [intellij-rust/intellij-rust#6949]
## Environment

* **IntelliJ Rust plugin version:** 0.3.142.3705-203
* **Rust toolchain version:** 1.50.0 (cb75ad5db 2021-02-10) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2020.3.2 (CL-203.7148.70)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Since the latest update dependency completion seems to be broken, showing empty versions:

![image](https://user-images.githubusercontent.com/301288/110780536-16289c00-8265-11eb-90b2-3cd695333f07.png)

## Steps to reproduce

1. Create empty project
1. Open `Cargo.toml`
2. Go to `[dependencies]` section
3. Type `walkdir`
4. Observe completion expanded as `="null"`:

![image](https://user-images.githubusercontent.com/301288/110780965-96e79800-8265-11eb-9f40-baec3d0f1645.png)

**Comment by ortem** [comment]
@ralfbiedert Thank you for reporting! There is a known problem with our new local crates index. It should be fixed before enabling the corresponding experimental feature (`org.rust.crates.local.index` in Registry).

As a temporary workaround, you can try to invalidate IDE caches using `File | Invalidate Caches / Restart` (can be found via `Ctrl+Shift+A` as well). The local crates index will be freshly rebuilt after any saved changes in a `Cargo.toml` file.

**Comment by ortem** [comment]
Looks like this problem was fixed in #6818. Although IJ Rust 0.3.142 already contains this fix, the problem can persist until the crates index is rebuilt. I think this issue can be closed now.

@ralfbiedert Please let us know if the caches invalidation does not help.
