### ISSUE TITLE
Collapse doc comments inside doctests collapses comments in the doctest rather than the file

### ISSUE THREAD

**Issue by afetisov** [intellij-rust/intellij-rust#6950]
## Environment

* **IntelliJ Rust plugin version:** 0.3.142.3705-203
* **Rust toolchain version:** 1.52.0-nightly (45b3c2851 2021-03-04) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.3.2 (CL-203.7148.70)
* **Operating system:** Linux 5.4.0-66-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Calling "Collapse doc comments" within a code example embedded into a doc comment will collapse doc comments in the example, rather than doc comments in the containing file. It kind of makes sense, but it's hard to imagine that anyone would put doc comments inside doc comments, and it makes folding via keyboard shortcuts confusing.

## Steps to reproduce

Consider the following example code:

```rust
/// Example structure
/// 
/// ```
/// /// This is an inner doc comment
/// fn /* caret */ example() {}
/// ```
struct Example;
```

After calling "Collapse doc comments" via keyboard shortcut or a context menu called at the caret:

```rust
/// Example structure
/// 
/// ```
/// /* ... */
/// fn /* caret */ example() {}
/// ```
struct Example;
```

Expected outcome: 

```rust
/* ... */
struct Example;
```

**Comment by Undin** [comment]
It's expected behavior since we inject Rust languages in doc comment code snippets and as a result, you get most of IDE features for injected code. You can disable the injection via `Inject Rust language into documentation comments` option in `Preferences | Languages & Frameworks | Rust` settings
