### ISSUE TITLE
Tab title for mod.rs files

### ISSUE THREAD

**Issue by scharris** [intellij-rust/intellij-rust#696]
When a mod.rs file is open, the tab title is only "mod.rs" (unless multiple mod.rs files happen to be open), which does not distinguish the module being viewed.  If the user has a lot of modules of this form in their own directories, it is difficult to distinguish which module is being viewed.

Workarounds currently are to keep "scroll from source" on (which otherwise might not be wanted as for example I find it distracting), or to always keep an unwanted "mod.rs" open so all mod.rs tabs are labeled with their directories for disambiguation.

I'm proposing instead that mod.rs files always show the parent directory name at least.

**Comment by mkaput** [comment]
Note: Gradle support does something like this for gradle scripts

**Comment by matklad** [comment]
Should be an easy thing to add: com.intellij.openapi.fileEditor.impl.EditorTabTitleProvider

**Comment by mbStavola** [comment]
I'd like to attempt this.

**Comment by matklad** [comment]
Thanks @mbStavola for fixing this!

@scharris have you tried disabling tabs altogether and using GoTo class/symbol/file instead for navigation :) ? 

This sounds strange, but may actually be more convenient than tabs (I don't use them myself, and I am not alone: https://www.youtube.com/watch?v=eq3KiAH4IBI&feature=youtu.be&t=10m30s ).
