### ISSUE TITLE
Bulild and provide .zip files of the plugin for commits to master

### ISSUE THREAD

**Issue by hamza1311** [intellij-rust/intellij-rust#6961]
Currently, if one wants to use the `master` build of the plugin, they have to clone and compile the code themselves. It would be nice to have CI build the plugin and then publish the file(s) somewhere so such users don't have to compile the plugin themselves

**Comment by vlad20012** [comment]
Nightly builds aren't enough?

**Comment by hamza1311** [comment]
> Nightly builds aren't enough?

@vlad20012, You mean nightly builds of the plugin? Are those available? I'm unable to find anything.

**Comment by Undin** [comment]
@hamza1311 Yep. See instruction on how to install [here](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly)

**Comment by hamza1311** [comment]
Oh, I somehow missed that. Thanks
