### ISSUE TITLE
Macros using `paste!` don't get expanded successfully

### ISSUE THREAD

**Issue by fwouts** [intellij-rust/intellij-rust#6983]
## Environment

* **IntelliJ Rust plugin version:** 0.3.144.3738-203-nightly
* **Rust toolchain version:** 1.52.0-nightly (f5d8117c3 2021-03-16) aarch64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.3.3 Ultimate Edition (IU-203.7717.56)
* **Operating system:** macOS 11.2.3
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

I'm using declarative macros extensively in my codebase, and I make use of [paste](https://docs.rs/paste) to concatenate identifiers. I noticed that code generated using the `paste!` macro doesn't get successfully expanded by the IntelliJ Rust plugin, even when using the new engine to expand declarative macros.

## Steps to reproduce

Sample code exhibiting the issue (from [this sample repository](https://github.com/fwouts/intellij-rust-macro-bug/blob/master/src/main.rs)):
```rust
use paste::paste;

macro_rules! declare_some_struct {
    ( $ name: ident) => {
        // Conventional declarative macro. This works perfectly! 🎉
        struct $name {
            value: String,
        }

        impl $name {
            pub fn greet(&self) {
                println!("Hello from {}, {}!", stringify!($name), self.value);
            }
        }

        // Slightly less conventional declarative macro, making use of https://docs.rs/paste to
        // concatenate identifiers (extremely useful when doing more advanced code generation!).
        paste! {
            struct [<$name Bar>] {
                value: String,
            }

            impl [<$name Bar>] {
                pub fn greet(&self) {
                    println!("Hello from {}, {}!", stringify!([<$name Bar>]), self.value);
                }
            }
        }
    };
}

declare_some_struct!(Foo);

fn main() {
    // This works perfectly well with the IntelliJ Rust plugin.
    // Cmd+clicking on Foo brings me to the macro call that defines it.
    // It even autocompletes .greet() when using the new engine to expand declarative macros!
    let foo = Foo { value: "Bob".to_owned() };
    foo.greet();

    // This doesn't work so well on the other hand.
    let bar = FooBar { value: "Jane".to_owned() };
    bar.greet();
}
```

The IntelliJ Rust plugin does correctly expand the `Foo` struct, but it's unable to detect the `FooBar` struct.

Here is the recursively expanded macro. It looks like it's unable to run the macro, maybe because it comes from another crate?
```rust
struct Foo {
    value: String,
}
impl Foo {
    pub fn greet(&self) {
        {
            ::std::io::_print(IntellijRustDollarCrate::format_args_nl!( "Hello from {}, {}!" , stringify ! ( Foo ) , self . value ));
        };
    }
}
paste! {
            struct [ < Foo Bar > ] {
                value : String ,
            }

            impl [ < Foo Bar > ] {
                pub fn greet ( & self ) {
                    println ! ( "Hello from {}, {}!" , stringify ! ( [ < Foo Bar > ] ) , self . value ) ;
                }
            }
        }
```

Let me know if I can help with any more details :)

**Comment by Undin** [comment]
@fwouts Thanks for the report!

`paste` macro is not expanded by macro expander because it's not a declarative macro but a procedural one. The plugin hasn't provided procedural macro expansion yet by default. But recently we landed initial support for function-like procedural macros and fortunately, `paste` macro belongs to this class of proc macros. See #6908 for more details (especially how to enable it). Don't hesitate to share any feedback. It will help us to catch bugs and polish this functionality to turn it on by default

**Comment by fwouts** [comment]
Thank you @Undin! That makes a lot of sense, I didn't even think to wonder what type of macro `paste!` was :)

Are you able to confirm that #6908 does indeed fix this with the sample project I provided?

I tried enabling both of these experimental features, running Refresh Cargo Projects, invalidating cache and restarting, but the `FooBar` struct in my example still doesn't seem to be detected.

**Comment by Undin** [comment]
Oh, sorry for the confusion.
I totally forgot that procedural macro expansion doesn't work on Apple silicon machines for now because it requires the corresponding native binary in plugin and we haven't built it yet for macos arm. Actually, only #2486 stops us from building it.
We will support it as soon as macos-11 will be available in GitHub actions runners

**Comment by fwouts** [comment]
Thanks @Undin.

Looking at [the code](https://github.com/intellij-rust/intellij-rust/blob/e756cb40b80c22205672a36e52799b9366bfd40f/src/main/kotlin/org/rust/openapiext/RsPathManager.kt#L28), it looks like it's already configured to automatically run the native binary with `arch -x86_64` on Apple silicon machines, so shouldn't it work already?

Anyway, I'm happy to use my old laptop as a workaround for now :)

**Comment by fwouts** [comment]
FYI I tried running the Intel version of IntelliJ via Rosetta 2 (with the same settings and experimental flags), and I can see that the native helper process is now running. That doesn't seem to be enough to fix it though.

https://user-images.githubusercontent.com/772570/111550179-b173c100-87d1-11eb-87a1-08732183f3ea.mov

On the other hand, it does work perfectly on a real Intel laptop, so I guess I'll just have to be patient and wait for https://github.com/actions/virtual-environments/issues/2486 to be resolved!
