### ISSUE TITLE
No highlights with multiple import items

### ISSUE THREAD

**Issue by ilyavenner** [intellij-rust/intellij-rust#6985]
## Environment

* **IntelliJ Rust plugin version:** 0.3.143.3737-203
* **Rust toolchain version:** 1.47.0 (18bf6b4f0 2020-10-07) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.3.3 (CL-203.7717.62)
* **Operating system:** Linux 5.10.19-1-manjaro
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

If crate `foo` provides two symbols named `Bar` (for example trait and derive macro), then type-based highlighting does not work. (see the screenshot below).

![image](https://user-images.githubusercontent.com/13315957/111485702-e89d9000-8747-11eb-8a89-efeb2779dd7b.png)

## Steps to reproduce
Try importing `StructOpt` items like shown in the attached screenshot.

**Comment by Undin** [comment]
@ilyavenner thanks for the report!

What highlighting do you expect in such cases? I suppose currently it works as expected since you have two different ways hot to highlight a name and it's quite weird to try to apply both highlighting or choose a random one

**Comment by ilyavenner** [comment]
> What highlighting do you expect in such cases?

I do not know. This is not an easy question.

> I suppose currently it works as expected since you have two different ways hot to highlight a name and it's quite weird to try to apply both highlighting or choose a random one.

Completely agree. I opened this issue to notify developers of this behavior.

**Comment by Undin** [comment]
>  I opened this issue to notify developers of this behavior.

Thank you!
Since we consider that current behavior is expected, I close the issue
