### ISSUE TITLE
The newest crate version is not shown in dependencies completion

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#6996]
## Environment

* **IntelliJ Rust plugin version:** 0.3.144.3742-211-nightly
* **Rust toolchain version:** 1.52.0-nightly (b3e19a221 2021-03-12) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.2 EAP (CL-212.1136)
* **Operating system:** macOS 10.15.6
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

> Note: I have `org.rust.crates.local.index` enabled

The plugin doesn't suggest the latest crate version in `Cargo.toml` dependencies completion.

## Steps to reproduce

Try e.g. `regex`, 1.4.5 is available

<img width="474" alt="docs" src="https://user-images.githubusercontent.com/2500320/111810384-02c1a480-88e7-11eb-9127-e5b48ee03c5b.png">

1.4.3 is the latest version the plugin is willing to give me

<img width="457" alt="plugin" src="https://user-images.githubusercontent.com/2500320/111810432-0f45fd00-88e7-11eb-9055-127c7bde2c09.png">

**Comment by avrong** [comment]
I guess it should be fixed now with https://github.com/intellij-rust/intellij-rust/pull/7067 merged.

The way this can now occur is if the cargo registry index wasn't updated. In fact, cargo doesn't have a command to only update the index. So it will be updated on `cargo build` if there are changed dependencies in Cargo.toml, or if you search for something like `cargo search intellijidearulezzz`

**Comment by avrong** [comment]
I think this surely can be closed now
