### ISSUE TITLE
Support type aliases

### ISSUE THREAD

**Issue by HydrogenC** [intellij-rust/intellij-rust#6999]
I have the following definitions: 
```
struct AA<U, V> {
    a:U,
    b:V
}

impl<U, V> AA<U, V> {
    fn func() {}
}

type AAA<U> = AA<U, i8>;
```

And I type `AAA::<i8>::`, however, "func" is not in the auto-completion list.

**Comment by dima74** [comment]
@HydrogenC could you please specify plugin version?

I can't reproduce with:

* **IntelliJ Rust plugin version:** 0.3.146.3786-203-nightly
* **Rust toolchain version:** 1.53.0-nightly (07e0e2ec2 2021-03-24) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.3.2 (CL-203.7148.70)
* **Operating system:** Linux 5.11.11-arch1-1
* **Macro expansion engine:** new
* **Name resolution engine:** new

![image](https://user-images.githubusercontent.com/6505554/114054579-a8d64e00-9898-11eb-8f26-8e4fb9d45f61.png)

**Comment by HydrogenC** [comment]
It could have been a occasional parse lag. I would close this.
