### ISSUE TITLE
New Name Resolution Not Working With The Windows Crate

### ISSUE THREAD

**Issue by Nerixyz** [intellij-rust/intellij-rust#7010]
## Environment

* **IntelliJ Rust plugin version:** 0.3.143.3737-203
* **Rust toolchain version:** 1.50.0 (cb75ad5db 2021-02-10) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2020.3.2 (CL-203.7148.70)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

With the new name resolution turned on, the resolution for the [`windows`](https://github.com/microsoft/windows-rs) crate is broken (this isn't the case with the old one).

## Steps to reproduce

0. Enable the new resolution engine
1. Create a new rust project
2. Use the [simple example](https://github.com/microsoft/windows-rs/tree/master/examples/simple) (except replace the dependencies to `windows = "0.6"`)
3. Build or run the project (to generate binding-files)
4. Optionally refresh the project (this should be done in step 3 - just to be sure)

Now in `main.rs` the `use bindings::windows::ui::Colors;` import isn't highlighted. To verify, turn off the new engine and reload the project.

**Comment by AlyoshaVasilieva** [comment]
The `windows` crate `simple` example v0.6 is broken (no highlighting/navigation) for me as well on current nightly plugin.

However:

1. v0.7 works fine (with some code changes, obviously)
2. Replacing `::windows::include_bindings!();` with `::std::include!(::std::concat!(::std::env!("OUT_DIR"), "/windows.rs"));`, which is what it expands to, also fixes it. 

Some weird macro interaction?
