### ISSUE TITLE
Strange expanding of function-like macro

### ISSUE THREAD

**Issue by ShagonRU** [intellij-rust/intellij-rust#7030]
## Environment

* **IntelliJ Rust plugin version:** 0.3.143.3737-203
* **Rust toolchain version:** 1.53.0-nightly (07e0e2ec2 2021-03-24) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2020.3.3 (CL-203.7717.62)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
Experimental features also enabled:
org.rust.cargo.evaluate.build.scripts | true
org.rust.macros.new.engine | true

Cargo projects refreshed many times.

====

Problem: Strange behavior and inconclusive type inference for functional-like proc-macro.
The variable "s" is of type \<unknown\> (dbg! () macro knows about the type and reports an unused Result because of using Clippy as external linter, i think).
![image](https://user-images.githubusercontent.com/28485306/112735997-77888480-8f60-11eb-8483-7e35273bb18d.png)

Problem:  Highlighting and auto-completion inside macro brackets does not work:
![image](https://user-images.githubusercontent.com/28485306/112736047-c504f180-8f60-11eb-93a7-47ea1ea57552.png)

## Steps to reproduce
Repo with MRE: https://github.com/ShagonRU/function-like-macro-expansion-problem
You do not need to install a database, just expanding the macro and examining the syntax highlighting is enough for this issue.

**Comment by Undin** [comment]
@ShagonRU is `org.rust.macros.proc` enabled as well?
Works for me
![image](https://user-images.githubusercontent.com/2539310/112748223-0e862880-8fc3-11eb-937e-991d1e7668c6.png)

**Comment by ShagonRU** [comment]
> @ShagonRU is `org.rust.macros.proc` enabled as well?
> Works for me
> ![image](https://user-images.githubusercontent.com/2539310/112748223-0e862880-8fc3-11eb-937e-991d1e7668c6.png)

Sure.
![image](https://user-images.githubusercontent.com/28485306/112748795-f0bac280-8fc6-11eb-970d-004c90bc6135.png)

**Comment by ShagonRU** [comment]
This issue related to wrong project creation (in some cases, i don't know why and how).

If someone face this issue, just remove all your projects from `Cargo` sidepanel and attach them back manually on the `Cargo` panel or use suggested action about missing project. It worked for me and repo at the start topic.
