### ISSUE TITLE
Adding and removing crate level cfg breaks macro expansion

### ISSUE THREAD

**Issue by PizzaCrust** [intellij-rust/intellij-rust#7039]
## Environment

* **IntelliJ Rust plugin version:** 0.3.145.3769-203-nightly
* **Rust toolchain version:** 1.53.0-nightly (07e0e2ec2 2021-03-24) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2020.3.3 Community Edition (IC-203.7717.56)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
Adding and removing a crate level cfg breaks macro expansion until restart

```rust
#![cfg(target_pointer_width = "64")]

macro_rules! anything {
    ($($tt:tt)*) => {
        $($tt)*
    };
}

anything!(pub struct A;);
```

## Steps to reproduce
1. Place this code in the editor
```rust
macro_rules! anything {
    ($($tt:tt)*) => {
        $($tt)*
    };
}

anything!(pub struct A;);
```
2. Add a crate level cfg
```rust
#![cfg(target_pointer_width = "64")]
```
3. Remove cfg
Now macro expansion is broken until the IDE restarts

**Comment by PizzaCrust** [comment]
I forgot to add how to trigger the bug 🤦

**Comment by mili-l** [comment]
see https://github.com/intellij-rust/intellij-rust/pull/9729
