### ISSUE TITLE
This feature is only available in edition 2018 for async/await syntax in README.md

### ISSUE THREAD

**Issue by qiujiangkun** [intellij-rust/intellij-rust#7044]
## Environment

* **IntelliJ Rust plugin version:** 0.3.144.3766-203
* **IDE name and version:** CLion 2020.3.3
* **Operating system:** MacOS

## Steps to reproduce
Have a README.md
```
` ``rust
async fn foo(){}
` ``
```
![image](https://user-images.githubusercontent.com/33482468/113401993-ea698380-93d6-11eb-9722-564b68e7dd00.png)

**Comment by ortem** [comment]
@qiujiangkun Please try specifying `edition = "2018"` in your `Cargo.toml` file. The corresponding Rust [documentation](https://doc.rust-lang.org/edition-guide/editions/creating-a-new-project.html) might be helpful.

**Comment by qiujiangkun** [comment]
It does not work
[project.zip](https://github.com/intellij-rust/intellij-rust/files/6277759/project.zip)

**Comment by Stzx** [comment]
@orium I think I've had enough free time lately to fix this, can you assign it to me?

**Comment by orium** [comment]
> @orium I think I've had enough free time lately to fix this, can you assign it to me?

I think you mean @ortem :slightly_smiling_face:

**Comment by Stzx** [comment]
> > @orium I think I've had enough free time lately to fix this, can you assign it to me?
> 
> I think you mean @ortem 🙂

Oh, Sorry. 😂
