### ISSUE TITLE
Error expanding functional-like macros if the body contains floating point numbers

### ISSUE THREAD

**Issue by chamoretto** [intellij-rust/intellij-rust#7049]
## Environment

* **IntelliJ Rust plugin version:** 0.3.145.3776-203-nightly
* **Rust toolchain version:** 1.53.0-nightly (74874a690 2021-03-30) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2020.3.3 (CL-203.7717.62)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

![image](https://user-images.githubusercontent.com/28485306/113485892-ad75bd80-94b8-11eb-970b-7b4e52149bcd.png)

## Problem description

If you use `Some (10.0)` (number with a dot) in a function-like macro, the macro will stop expanding with the error about comma and the type will not be deduced either, but the code will still work. This can be tested against the version in repository below.
![image](https://user-images.githubusercontent.com/28485306/113485949-f6c60d00-94b8-11eb-8bdc-4179c8e9b8a3.png)
It compiles to proper code and works as expected, but can not be expanded by plugin.

===

Almost the same with sqlx::query_as!() macro with **bad expanding**: no highlighting and another error:
![image](https://user-images.githubusercontent.com/28485306/113485638-40155d00-94b7-11eb-81b9-1c947983f45b.png)
![image](https://user-images.githubusercontent.com/28485306/113485640-460b3e00-94b7-11eb-9f82-dd55fdf2eb31.png)
![image](https://user-images.githubusercontent.com/28485306/113485646-4d324c00-94b7-11eb-8c6f-1549c619c526.png)

Variant from the repo, without needed env var - **right expanding** (without inlay type hint - because `DATABASE_URL` is unset):
![image](https://user-images.githubusercontent.com/28485306/113485661-676c2a00-94b7-11eb-9069-a087eb882196.png)

Variant from my work project, with properly used `DATABASE_URL`  - **right expanding** and proper inlay type hint:
![image](https://user-images.githubusercontent.com/28485306/113485693-87035280-94b7-11eb-9cb8-ec56793c3cde.png)
And i have buggy highlighting, as you can see.

All `query_as!` macros above were compiled to right code and work well in my project, but three of them cannot be expanded properly by plugin.

## Steps to reproduce

1. Clone repo, i've created special branch for this issue - https://github.com/ShagonRU/function-like-macro-expansion-problem/tree/issue7049-examples
2. Try to expand examples from `test` function

## Another bugs with Go to definition

When i trying to go to `User`'s definition, the plugin offers to go to login_var (as seen by the green highlight) and give me very strange suggest about `User`'s possible definitions:
![image](https://user-images.githubusercontent.com/28485306/113486195-2de8ee00-94ba-11eb-89ee-a95fa639d025.png)

I unable to go to `login_var` from macros body:
![image](https://user-images.githubusercontent.com/28485306/113486258-76081080-94ba-11eb-85ce-b82dbc2962be.png)

**Comment by vlad20012** [comment]
#8203 fixes the only bug with floating-point literals.

#8233 should fix other bugs (weird highlighting and go to declaration)
