### ISSUE TITLE
Rust plugin won't be able to load on IDEA 2020.2.2

### ISSUE THREAD

**Issue by Dentrax** [intellij-rust/intellij-rust#7056]
## Environment

* **IntelliJ Rust plugin version:** `0.3.140.3644-202`
* **Rust toolchain version:** `rustc 1.49.0 (e1884a8e3 2020-12-29)`
* **IDE name and version:** `CLion 2020.2.2`
* **Operating system:** `macOS BigSur 11.0.1`

## Problem description

<img width="231" alt="Screen Shot 2021-04-05 at 15 36 26" src="https://user-images.githubusercontent.com/16493751/113574400-b08dbc80-9624-11eb-9cf4-86f20ccba5e1.png">

<img width="795" alt="Screen Shot 2021-04-05 at 15 36 15" src="https://user-images.githubusercontent.com/16493751/113574385-a9ff4500-9624-11eb-8e6c-bce87ff93209.png">

## Steps to reproduce

1. Click `Enable Rust plugin`
2. Select `Enable`
3. Click `OK`

See the error

**Comment by ortem** [comment]
@Dentrax Please try the following steps:
1. [Uninstall](https://www.jetbrains.com/help/idea/managing-plugins.html#remove-plugin) the Rust plugin and the Toml plugin
2. [Install](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_repo) the Rust plugin again. IDE will suggest installing the required Toml plugin automatically

**Comment by Dentrax** [comment]
> @Dentrax Please try the following steps:
> 1. [Uninstall](https://www.jetbrains.com/help/idea/managing-plugins.html#remove-plugin) the Rust plugin and the Toml plugin
> 2. [Install](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_repo) the Rust plugin again. IDE will suggest installing the required Toml plugin automatically

This fixed the issue. 👍
