### ISSUE TITLE
Wild "use std::alloc::Global" is added when I change function return type with "Change Signature"

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#7077]
## Environment

* **IntelliJ Rust plugin version:** 0.3.146.3786-211-nightly
* **Rust toolchain version:** 1.52.0-nightly (b3e19a221 2021-03-12) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.1 (CL-211.6693.114)
* **Operating system:** macOS 10.15.6
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

The plugin inserts `use std::alloc::Global;` once I change a function return type via "Change Signature" refactoring.

## Steps to reproduce

```rust
fn main() {}

fn foo() -> Vec<Vec<i32>> {
    vec![vec![42]]
}
```

Try changing the return type to `Vec<Vec<i16>>`

```rust
use std::alloc::Global;

fn main() {}

fn foo() -> Vec<Vec<i16>> {
    vec![vec![42]]
}
```

Not sure if I understand why 🤔 

https://user-images.githubusercontent.com/2500320/114207748-64fd4a80-9965-11eb-92f8-a95edd1f8303.mov

**Comment by Kobzol** [comment]
I think that this is the same situation as in https://github.com/intellij-rust/intellij-rust/issues/6186, since the allocator is now a generic parameter of `Vec`. I'll try to use the same approach as in https://github.com/intellij-rust/intellij-rust/pull/6896 to fix it.
