### ISSUE TITLE
Cargo run configuration doesn't support command line arguments

### ISSUE THREAD

**Issue by fctorial** [intellij-rust/intellij-rust#7084]
## Environment

* **IntelliJ Rust plugin version:** 0.3.144
* **Rust toolchain version:** 1.51.0
* **IDE name and version:** 2020.3.3
* **Operating system:** linux/nixos

## Problem description

Cargo run configuration doesn't allow you to add command line arguments for the executable.

**Comment by Undin** [comment]
You should add them into `command` field after `--` in the exactly [same way](https://doc.rust-lang.org/cargo/commands/cargo-run.html#description) as you do it for cargo.
Also, see https://plugins.jetbrains.com/plugin/8182-rust/docs/cargo-command-configuration.html#cargo-command-config
