### ISSUE TITLE
Feature request: hiding `where` clauses

### ISSUE THREAD

**Issue by p0lunin** [intellij-rust/intellij-rust#7110]
Sometimes `where` clauses with generics may take a lot of space, as you can see at the image below:

![image](https://user-images.githubusercontent.com/48922415/114698743-1f0b0280-9d28-11eb-8ca2-7ffaaf95e25b.png)

There is currently no way to hide this, which can be annoying when the user wants to quickly scroll up|down.
I think it can be solved in one of the following ways:
1. Button for hiding `where` clauses, like a button for hiding the arguments of a function or the body of a function.
2. Button to hide the function definition and body with arguments, body and generics, leaving only the function name.

**Comment by vlad20012** [comment]
Sounds like a simple `RsFoldingBuilder` improvement
