### ISSUE TITLE
println postfix complection inserts an extra line in an unfinished match

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#7117]
## Environment

* **IntelliJ Rust plugin version:** 0.3.146.3802-211-nightly
* **Rust toolchain version:** 1.52.0-nightly (b3e19a221 2021-03-12) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.1 (CL-211.6693.114)
* **Operating system:** macOS 10.15.7
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

`println` postfix completion inserts an extra line with the variable reference when I call it inside an unfinished `match`.

## Steps to reproduce

```rust
use regex::Regex;

fn main() {
    let re = Regex::new("picture").unwrap();
    let quote = "Every face, every shop, bedroom window, public-house, and
dark square is a picture feverishly turned--in search of what?
It is the same with books. What do we seek through millions of pages?";

    for line in quote.lines() {
        let contains_substring = re.find(line);
        match contains_substring {
            Some(_) => line.
        }
    }
}
```

Type `println` after `line.` and accept the postfix completion suggestion. Result:

```rust
use regex::Regex;

fn main() {
    let re = Regex::new("picture").unwrap();
    let quote = "Every face, every shop, bedroom window, public-house, and
dark square is a picture feverishly turned--in search of what?
It is the same with books. What do we seek through millions of pages?";

    for line in quote.lines() {
        let contains_substring = re.find(line);
        match contains_substring {
            Some(_) => {
                println!("{}", line);
                line
            }
        }
    }
}
```

https://user-images.githubusercontent.com/2500320/114871896-7087c000-9e02-11eb-90f8-ff98bd43d83d.mov

**Comment by vlad20012** [comment]
This works almost as expected. The template is designed to work in the case when `match` is an expression with a meaningful return value, for example:
```rust
fn main() {
    let a = match (something) {
        A(b) -> b,
        _ => 1
    }
}
```
If you apply the postfix template to this example, it preserves the correctness of assignment `b` to `a`:
```rust
fn main() {
    let a = match (something) {
        A(b) -> {
            println("{}", b);
            b
        }
    }
}
```

This may look incorrect in the case where the `match` value is not used:
```rust
fn main() {
    match (something) {
        A(b) -> b,
        _ => 1
    }
}
```
... but I'm not sure that we should overcomplicate the behavior of the template so much.

**Comment by Stzx** [comment]
It seems to me that identifying and providing a return value should not be useful in most cases. Unless it is made smarter to recognize return values, this will complicate the template.

**Comment by vlad20012** [comment]
Also try
```rust
let a = 1;
let b = a.println/*caret*/;
```

**Comment by lancelote** [comment]
Honestly, I would prefer it to be less smart, but I see the point. Let me close the ticket for now and thank you for the clarification.
