### ISSUE TITLE
Cannot go to an obvious definition

### ISSUE THREAD

**Issue by ailisp** [intellij-rust/intellij-rust#7122]
## Environment

* **IntelliJ Rust plugin version:**
0.2.123.3132-193
* **Rust toolchain version:**
rustc 1.51.0 (2fd73fabe 2021-03-23)
* **IDE name and version:**
CLION 2019.3.1
* **Operating system:**
Mac 10.14.6 (18G103)

## Problem description
Cannot goto obvious definition 

## Steps to reproduce

Clone this repo: https://github.com/near/nearcore, In this file: https://github.com/near/nearcore/blob/4bb0d5ac2264950fe79c70f29f5b22120159356f/runtime/near-vm-runner-standalone/src/main.rs#L216

`script.step` method is an obvious method definition in https://github.com/near/nearcore/blob/4bb0d5ac2264950fe79c70f29f5b22120159356f/runtime/near-vm-runner-standalone/src/script.rs (same dir, different rust file), but intellij-rust cannot figure out what to go to

A little more insight: `script` is creating by `    let mut script = Script::default();`, and intellij-rust said script is "variable: <unknown>", which might be the reason it cannot go to definition

**Comment by Undin** [comment]
@ailisp I cannot reproduce the issue with the latest plugin version.
Could you re-check your code with the latest plugin build? Note, you use a quite old IDE (2019.3). Currently, the plugin doesn't support IDEs older than 2020.3

**Comment by ailisp** [comment]
Thanks! Probably due to my IDE is too old, plugin is a Apr 2021 version,
which is probably auto updated by IDE.

**Comment by ailisp** [comment]
Yeah it works perfectly in IDE 2021.1

**Comment by Undin** [comment]
@ailisp Great!
