### ISSUE TITLE
Unresolved reference for macro in tracing crate

### ISSUE THREAD

**Issue by qiujiangkun** [intellij-rust/intellij-rust#7123]
Macros like `info` and `debug` in `log` crate are correctly highlighted.
```rust
#[macro_use] extern crate log;
debug!("");
```
But not in `tracing`, where these macros are marked red in rather large projects, unless I explicitly `use tracing::debug`
```rust
#[macro_use] extern crate tracing;
debug!("");
```
![image](https://user-images.githubusercontent.com/33482468/114998534-a47ee600-9ed3-11eb-9b66-31f5c0d12687.png)

**Comment by dima74** [comment]
@qiujiangkun looks like it is fixed now. Feel free to reopen if you encounter any other errors

![image](https://user-images.githubusercontent.com/6505554/182747069-5f6a7826-9ce4-4e0e-a24a-0157f5b44287.png)
