### ISSUE TITLE
Confusing display of primitive arithmetic types at debugger

### ISSUE THREAD

**Issue by chamoretto** [intellij-rust/intellij-rust#7127]
## Environment

* **IntelliJ Rust plugin version:** 0.3.146.3804-211-nightly
* **Rust toolchain version:** 1.53.0-nightly (16bf626a3 2021-04-14) x86_64-pc-windows-msvc
* **IDE name and version:** PyCharm 2021.1 Professional Edition (PY-211.6693.115)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
When i use debugger, i see types from C/C++ like `long long` instead of "Rusty" types like `u32`. Even `u8` zero becames C-`\0`.
![image](https://user-images.githubusercontent.com/28485306/115087655-38be6c80-9f17-11eb-8412-e3b8c02f87e0.png)

## Steps to reproduce
https://play.rust-lang.org/?version=nightly&edition=2018&gist=8991970d74de6c8f9276766e1fa1972f

**Comment by Undin** [comment]
@ShagonRU Thanks for the report!
It's a known issue of msvc lldb. See #5632
Current workarounds are:
- use gnu toolchain. Requires CLion
- use unix OS

**Comment by ortem** [comment]
Fixed by #9649 (with 2022.3+ IDE builds).
