### ISSUE TITLE
Strange behavior of auto-completion of crate versions in Cargo.toml

### ISSUE THREAD

**Issue by chamoretto** [intellij-rust/intellij-rust#7128]
## Environment

* **IntelliJ Rust plugin version:** 0.3.146.3804-211-nightly
* **Rust toolchain version:** 1.53.0-nightly (16bf626a3 2021-04-14) x86_64-pc-windows-msvc
* **IDE name and version:** PyCharm 2021.1 Professional Edition (PY-211.6693.115)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Experimental feature** `ort.rust.crates.local.index`: enabled

## Problem description
Confusing autocompletion of versions at Cargo.toml.
There are 3 cases:
1. Plain dependency definition `reqwest = "0.11.3"`: autocompletion **works** as expexted
2. Long dependency definition `reqwest = {version = "0.11.3}`: **no** autocompletion
3. Dedicated dependency definition - **parital** autocompletion, plugin suggests only the last version.
```toml
[dependencies.reqwest]
version = "0.11.3"
```

## Steps to reproduce

https://user-images.githubusercontent.com/28485306/115091098-48da4a00-9f1f-11eb-9a94-476713d5638d.mp4

**Comment by Undin** [comment]
@ShagonRU Thanks for the report!

@avrong 
2. It looks like we don't support such patterns at all
3. I suppose we can use local index not only for key-value dependencies but also for all other cases.
See `CratesIoCargoTomlSpecificDependencyHeaderCompletionProvider` and `CratesIoCargoTomlSpecificDependencyVersionCompletionProvider`

**Comment by avrong** [comment]
@Undin partially implemented in #7068
