### ISSUE TITLE
Cut releases every week possible?

### ISSUE THREAD

**Issue by sum-elier** [intellij-rust/intellij-rust#7129]
If rust-analyzer cuts out a release every week, would it be possible to do the same in this project?
Cutting a release with whatever is considered stable at the moment every week, no matter how small.
This would have the benefit of delivering to the wider public more frequently allowing for faster feedback to detect bugs or issues, and at the same time providing value for the users faster. I equate this with having like a continuous delivery as done in web development.

My guess is there are internal organizational rules dictating current schedule or perhaps internal testing / design requires more time than a week.

In any case awesome plugin 👍🏻

**Comment by Undin** [comment]
@sum-elier Thank you for your desire to make the plugin better!

But I don't think it would be efficient for us, at least currently. Each release requires some resources from the team and weekly releases increase the required effort and, at the same time, decrease resources for development.
Yeah, feedback is very important but we get quite enough feedback from two-week releases.

Note, we also publish [nightly builds](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly) of the plugin to get more feedback

**Comment by sum-elier** [comment]
Thanks for the explanation, I am totally unaware of the inner workings of the development process done here so excuse my ignorance. I don't know how I missed out the nightly builds, but they look to fulfill what I had in mind. Would you say that nightly releases are good enough for everyday use?

**Comment by Undin** [comment]
> Would you say that nightly releases are good enough for everyday use?

They are not so well tested, so we can't guarantee that they don't contain critical bugs (actually, almost nobody can do it 😄) but some major issues appear quite rare.
