### ISSUE TITLE
Unexpected navigation bar items in Rust files

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#7153]
## Environment

* **IntelliJ Rust plugin version:** 0.3.147.3812-211-nightly
* **Rust toolchain version:** 1.51.0 (2fd73fabe 2021-03-23) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.1 Ultimate Edition (IU-211.6693.111)
* **Operating system:** macOS 10.15.6
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description
<img width="562" alt="Screen Shot 2021-04-21 at 19 50 10" src="https://user-images.githubusercontent.com/2539310/115591485-d086d680-a2da-11eb-96d6-227f5ece30da.png">

<img width="580" alt="Screen Shot 2021-04-21 at 19 46 22" src="https://user-images.githubusercontent.com/2539310/115591106-6e2dd600-a2da-11eb-9d31-9ada5775692d.png">

Introduced in #6581

## Steps to reproduce
```rust
struct C {
    a: i32
}

mod bar;

fn main() {}
```

**Comment by Kobzol** [comment]
Oops. Since I reused the breadcrumbs implementation, I kind of assumed that its tests would cover all needed situations. But it is obviously not the case. I'll send a PR with tests right away.

**Comment by Kobzol** [comment]
Hmm, when `StructureAwareNavBarModelExtension::getPresentableText` returns null, it renders it with `toString`. That is unfortunate :disappointed: Should I add support for the missing cases (things like named field decl) only to the navbar or also to the breadcrumbs? Or do we actually want to disable the breadcrumbs in favor of the navbar, as is done e.g. by Kotlin?
