### ISSUE TITLE
"sel" sometimes autocompletes to "slice_end_index_len_fail" which is private from the stdlib

### ISSUE THREAD

**Issue by TinBryn** [intellij-rust/intellij-rust#7159]
## Environment

* **IntelliJ Rust plugin version:** 0.3.145.3797-211
* **Rust toolchain version:** 1.51.0
* **IDE name and version:** CLion 2021.1 Build #CL-211.6693.114, built on April 6, 2021
* **Operating system:** Ubuntu 20.04

## Problem description
Rust programming heavily uses the `self` keyword and just for piece of mind I like to autocomplete even small words like `self`. However this private function in the stdlib matches and sometimes intelliJ puts that at the top and imports the function which results in an import of non public x error.

**Comment by dima74** [comment]
I believe this was fixed in #7914. Feel free to reopen if you encounter any other errors

![image](https://user-images.githubusercontent.com/6505554/182746334-7df51293-161e-4e47-af21-f4ecfa6e6870.png)
