### ISSUE TITLE
Toml [dependency] context action: convert to long form + auto completion 

### ISSUE THREAD

**Issue by ralfbiedert** [intellij-rust/intellij-rust#7161]
## Feature Request 

Quite often I find myself having to repeat the same tedious action; in a `Cargo.toml` looking like this:

```
[dependencies]
bumpalo = "3.6.1"
```

I want to transform a dependency into that:

```
[dependencies]
bumpalo = { version = "3.6.1", features = ["collections"] }
```

It would be nice if 

- I could Alt-Enter over the `3.6.1` string and get a context action "Convert to long form" (name TBD) that transforms ` "3.6.1"` into `{ version = "3.6.1" }`
- I then type `fe...` and press `Ctrl-space` inside the `{}` block it should also complete to `features = []`

**Comment by Kobzol** [comment]
You're in luck, the first suggestion has been recently implemented (https://github.com/intellij-rust/intellij-rust/pull/6960) and it will be available in the next release :)

There is already an issue for the second suggestion - https://github.com/intellij-rust/intellij-rust/issues/4455 (actually multiple issues probably), so I'm going to close this issue as a duplicate.
