### ISSUE TITLE
Conflicts with Arend plugin

### ISSUE THREAD

**Issue by zxeoc** [intellij-rust/intellij-rust#7172]
## Environment

* **IntelliJ Rust plugin version:** 0.3.145.3797-211
* **Rust toolchain version:** 1.51.0 (2fd73fabe 2021-03-23) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2021.1 Ultimate Edition (IU-211.6693.111)
* **Operating system:** Linux 5.11.14-1-manjaro
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description
When Arend plugin actived, all "Run/Debug/Record and Debug/..." with default run configuration would just build the code ( no running/debugging/...).

## Steps to reproduce
Active Arend plugin and Rust plugin, restart IDEA, try to Run the code( any code, even "hello-world").

**Comment by Undin** [comment]
Thanks for the report!
It's an Arend plugin bug. I've filed the corresponding [issue](https://github.com/JetBrains/intellij-arend/issues/266) in their issue tracker
