### ISSUE TITLE
White console colors maps to black on dark themes

### ISSUE THREAD

**Issue by cherryleafroad** [intellij-rust/intellij-rust#7186]
From best I can tell, white ANSI colors are mapped to black in order to prevent White on White text on the light theme. Clearly this is needed. However, when you're on the black theme, this causes black on black which is the same issue in reverse

Could this previous fix be fixed to detect what theme you're on and auto-adjust (or allow user to adjust)? If you're using a black theme (or darkish theme - since it can occur even on non-black themes), the white color should not be changed as it is hard to see black on black (or black on darkish theme)

The only fix right now is to go into settings and change the black console color to white

![image](https://user-images.githubusercontent.com/13651622/116316881-6e5d2400-a767-11eb-822d-32e2ac02aefb.png)

Pull request: https://github.com/intellij-rust/intellij-rust/pull/3312
Responsible function: https://github.com/intellij-rust/intellij-rust/blob/65c0f55e0c28985b3dde72cc5384b88590d19377/src/main/kotlin/org/rust/cargo/runconfig/RsAnsiEscapeDecoder.kt#L126

**Comment by RealXuChe** [comment]
Same issue. It's even worse when on the high contrast theme: the background color is pure black, the same as the text.

**Comment by cherryleafroad** [comment]
While this fixes it for dark themes, there are some more custom themes that may be dark that this fix cannot detect (I'm using a material theme for example). I know that this can't be detected for every theme in existence, but it would be nice to maybe have a toggle switch, or be able to add a particular theme to the list to be whitelisted.
