### ISSUE TITLE
Make backtrace frames clickable from test runner window

### ISSUE THREAD

**Issue by nathanaeljones** [intellij-rust/intellij-rust#720]
It should be possible to format backtraces such that IntelliJ automatically links them to the corresponding source. 

FILENAME:LINE, with no leading whitespace, appears to work in CLion.

**Comment by alygin** [comment]
The problem with #724 is that it doesn't work in many cases. For instance, if you run this code:

    let a: Option<u32> = None;
    a.unwrap();

on a Windows or MacOS, you'll get no links to the source code at all:

    thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
    stack backtrace:
       1:        0x108188f48 - std::sys::backtrace::tracing::_imp::write::hb03a0f85d9cccd1b
       2:        0x10818a9ff - std::panicking::default_hook::{{closure}}::h945d25329ef3fdd6
       3:        0x108189f95 - std::panicking::default_hook::hc98de28314f7e4d1
       4:        0x10818a4e6 - std::panicking::rust_panic_with_hook::hf47d6a84575c96f5
       5:        0x10818a384 - std::panicking::begin_panic::heb2e59d774c89ce6
       6:        0x10818a2a2 - std::panicking::begin_panic_fmt::h2640a71eaf059834
       7:        0x10818a207 - rust_begin_unwind
       8:        0x1081af6c0 - core::panicking::panic_fmt::h8e7400f6438ecb75
       9:        0x1081af5c4 - core::panicking::panic::h61585b9964ba1fa2
      10:        0x108183234 - <core::option::Option<T>>::unwrap::h1e345852ce596efa
      11:        0x108183350 - launcher::do_countdown::h25c70d1fbfb33a27
      12:        0x10818331a - launcher::launch_rocket::hc31ffb37a7acfdc0
      13:        0x1081833a8 - launcher::main::h2cd7a4ff8d266cce
      14:        0x10818afba - __rust_maybe_catch_panic
      15:        0x108189ad6 - std::rt::lang_start::h95854775e4ac8b95
      16:        0x1081833d9 - main

I think, the better solution would be to analyse the stack trace lines, extract method names and add links to those of them that relate to the current project: `launcher::main()`, `launcher::launch_rocket()` and `launcher::do_countdown()` in the above example. Java/Kotlin do that and it saves great deal of time.

@matklad, what do you think? Does the plugin already accumulate enough information to do that? If so, I could try to implement such a feature. The thing I don't know now is how to get to the crate name, especially if we're working in a multi-crate environment (workspaces for instance).

**Comment by matklad** [comment]
Yep, I think this should be doable using current resolve infrastructure, though some refactoring may be necessary. 

There is a [RustPath](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/lang/core/symbols/RustPath.kt) class that represents colon::qualified::path. It can be passed to [ResolveEngine](https://github.com/intellij-rust/intellij-rust/blob/c389114ac0f94fc90dcf7c12bc9f14668fa3d18d/src/main/kotlin/org/rust/lang/core/resolve/RustResolveEngine.kt#L71) to get the element it points to. The tricky argument to the `resolve` method is `pivot`. It is a PSI element which is used to determine where to start searching (crate root for absolute paths, current scope/module for relative ones).

Here, we don't have a PSI element for a `pivot`, so we need to lookup a crate by name. [getCrateRoot](https://github.com/intellij-rust/intellij-rust/blob/c389114ac0f94fc90dcf7c12bc9f14668fa3d18d/src/main/kotlin/org/rust/cargo/util/RustCrateUtil.kt#L36) function can be used to get hold of the available crates information.

**Comment by matklad** [comment]
I am refactoring a resolve infra slightly at the moment, so there may be some merge conflicts :)

**Comment by matklad** [comment]
>Here, we don't have a PSI element for a pivot

Hm, I haven't thought about it that much, but an alternative approach for resolving `foo::bar::baz` string might be to create a temporary PSI file 

```
extern crate foo;

fn main() {
     let _ = foo::bar::baz;
}
```

and then to resolve the path using our usual reference machinery. I don't think I like this approach, but it's nice to keep it in mind.

**Comment by alygin** [comment]
Thanks for the explanation! I'll have a look at the classes you mentioned and try to figure out how to combine them to solve the issue.

**Comment by alygin** [comment]
I can create a `Path` and find a `CargoProjectDescription.Package` for every function I want to resolve. Unfortunately, I can't figure out how to finish this puzzle and find the `pivot`. Actually, I can do it for external creates (by leveraging `CargoProjectDescription.externalCrates`), but not for my own crate. Is there an analogue of the `ExternCrate.virtualFile` that works for our own crates?
