### ISSUE TITLE
Auto-select WSL based toolchain when opening a project inside 

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#7203]
## Environment

* **IntelliJ Rust plugin version:** 0.3.147.3837-211-nightly
* **Rust toolchain version:** 1.51.0 (2fd73fabe 2021-03-23) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.1.1 (CL-211.7142.21)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

When I open a project which is located directly in WSL FS (using #6456) CLion automatically selects a default Rust toolchain in Windows FS, which is not very convenient.

Would prefer it to select a Rust toolchain inside the WSL.

**Comment by iamwwc** [comment]
`To turn it on, enable org.rust.wsl experimental feature`, Where I can enable this feature :) @lancelote

**Comment by Undin** [comment]
@iamwwc https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features
