### ISSUE TITLE
File system completion for string literals should suggest paths relative to project root

### ISSUE THREAD

**Issue by shocoman** [intellij-rust/intellij-rust#7219]
## Environment

* **IntelliJ Rust plugin version:** 0.3.147.SNAPSHOT-211-dev
* **Rust toolchain version:** 1.51.0 (2fd73fabe 2021-03-23) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2021.1 Ultimate Edition (IU-211.6693.111)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
Right now file system completion (#5430) displays files in the directory that contains our .rs file. It works correctly for macros like include_str(...) but not for functions like File::open(...) as it expects paths to be relative to project root. 

![before](https://user-images.githubusercontent.com/8329446/117814542-a3509700-b28e-11eb-8e58-4a5c4e0753f3.gif)

It would be pretty nice if the default directory for completion was project root (except the most obvious cases such as "include..." macros). I think it is more common use case. Optionally, we may be able to use a special path prefix ("./") to display paths relative to the current folder as before. Like this:
![after2](https://user-images.githubusercontent.com/8329446/117820728-00e7e200-b295-11eb-88df-75f53ff96507.gif)

**Comment by Undin** [comment]
@Kobzol would you like to handle it since you implemented the corresponding functionality?
If so, I suppose we need to provide proper context in `org.rust.lang.core.resolve.ref.RsLiteralFileReferenceSet#getDefaultContexts` when we resolve/complete relative paths for `pathValueLiteral` pattern

**Comment by Kobzol** [comment]
Sure, I'll implement this. I'm just now sure how it should work yet.

Making a distinction between `"path"` and `"./path"` doesn't seem right to me, I think that it's people just use these interchangeably and I don't think that we should distinguish between these.

Regarding the context directory, should it always be project root? We could also look at the current active Run target and try to take the working directory from it. WDYT?

**Comment by Undin** [comment]
> Making a distinction between "path" and "./path" doesn't seem right to me, I think that it's people just use these interchangeably and I don't think that we should distinguish between these.

Agree

> Regarding the context directory, should it always be project root?

I think the behavior should be consistent with default working dir created for the Cargo run configuration. Also, it may be useful to check default implementation of `com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReferenceSet#getDefaultContexts`

> We could also look at the current active Run target and try to take the working directory from it. WDYT?

We can, but it looks rather non-obvious (at least to me) so I think it's better just to implement a simple solution and adjust it in the future if it will be needed for someone

**Comment by Kobzol** [comment]
OK, it would probably be "too magic". I'll check `getDefaultContexts` and send a PR.

**Comment by Kobzol** [comment]
I checked `org/rust/ide/newProject/Utils.kt`, which generates the default `Run` configurations. It uses `project.basePath` as the default working directory, which seems to be deprecated to me (it should correspond to `project.baseDir()`, which is marked as deprecated)..

When creating a run configuration from the editor, it seems to use this (at least for binary targets):
```kotlin
val workingDirectory = if (usePackageOption) {
    pkg.workspace.contentRoot
} else {
    pkg.rootDirectory
}
```
So, should I use the workspace content root (i.e. the parent directory of the nearest `Cargo.toml` of a given element, if I'm not mistaken)?

**Comment by Undin** [comment]
@Kobzol yep, looks like `pkg.workspace.contentRoot` is enough here but I haven't checked all possible cases (workspace with different crates, examples, additional binaries in `bin` dir, etc.
