### ISSUE TITLE
Incorrect operator precedence in mutable assignments

### ISSUE THREAD

**Issue by afetisov** [intellij-rust/intellij-rust#7220]
## Environment

* **IntelliJ Rust plugin version:** 0.3.146.3826-211
* **Rust toolchain version:** 1.54.0-nightly (bacf770f2 2021-05-05) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.1 (CL-211.6693.114)
* **Operating system:** Linux 5.4.0-72-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

In mutable assignments, expressions which contain logical && and || operators as well as block expressions (ordinary, try, async or unsafe) are parsed incorrectly. Surprisingly, if a mutable assignment is changed into a fresh let binding, the expression is parsed correctly.

## Steps to reproduce

```rust
    let mut x = false;
    x = { 0 } != 0;
    //  ^^^^^ Error: mismatched types [E0308] expected `bool`, found `i32`
    //           ^^ Error: mismatched types [E0308] expected `()`, found `i32`
    // Parsed as: ( ( x = { 0 } ) != 0 )
    
    x = true && { 0 } == 0;
    //          ^^^^^ Error: mismatched types [E0308] expected `bool`, found `i32` 
    // Parsed as:  ( x = ( ( true && { 0 } ) == 0 ) )
    // Same errors if `==` is changed to `!=`, `>`, `<`, `>=`, `<=`, or with `||` instead of `&&`.
    
    // the following statements are parsed correctly
    x = 0 != { 0 } && true;
    x = 0 != 0;
    let x = { 0 } != 0;
    let x = true && { 0 } == 0;
    let x = 0 != { 0 } && true;
    let x = 0 != 0;
```

**Comment by afetisov** [comment]
@vlad20012 
Just FYI, I have looked at that bug and tracked it down to the "StmtModeExprOff" rule in the parser. It is defined via an external function, but participates in a Pratt parser for expressions, which means that the code is generated incorrectly: instead of properly recursing in the RHS of binary operators, the Pratt parser stops, calls StmtModeExprOff and then starts anew.

However, the real issue is why StmtModeExprOff was used in the first place. It exists so that statements of the form 

```rust
for i in it { /* ... */ } &x;
```

are parsed as a loop followed by taking a reference to `x` rather than as a binary operator with the loop as the LHS. Frankly, it's a very odd case since all binary operators in such position either fail type checking or are just meaningless (what's the point of a single statement of the form `&x` or `+x` with unused result?). However, the RustC parser made this choice and so the plugin must conform. I guess it was made to avoid dumb errors like

```rust
fn foo(y: usize) -> usize {
    let x = 5;
    if y > x {
        y + x
    }
    ++x
}
```

Here someone erroneously assumed that the block return in the `if` statement will return from the function and that the preincrement operator exists in Rust.

The only possibility for confusion which I see all have the form `BlockLike Binop Expr`, since blocks commonly are used on their own as statements. However, the current grammar is flawed in that, even if StmtModeExprOff was parsed correctly, statements of the form

```rust
return if a > b { a } else { b } + 5;
```

would be incorrectly parsed as

```rust
return if a > b { a } else { b }; 
+ 5;
```

since the "isIncompleteBlockExpr" subrule rule in binary operators will bail after parsing a block.

I believe that the grammar should be changed so that isIncompleteBlockExpr is removed, StmtModeExprOff is changed to just Expr, and the statement parser would either accept a block statement, or any expression without limitations (i.e. in the example above as soon as we parse `break` we know that we're parsing an expression and just use the Pratt parser to parse the rest of the statement. However, I didn't test that there are no other edge cases.

**Comment by vlad20012** [comment]
> Just FYI, I have looked at that bug and tracked it down to the "StmtModeExprOff" rule in the parser. It is defined via an external function, but participates in a Pratt parser for expressions, which means that the code is generated incorrectly: instead of properly recursing in the RHS of binary operators, the Pratt parser stops, calls StmtModeExprOff and then starts anew.

Yeah, I just investigated it to the same point. But I see that `StmtModeExprOff` isn't used at all, there are exactly zero calls to it in the generated parser

**Comment by afetisov** [comment]
Indeed, because of the rather unintuitive behaviour of GrammarKit's Pratt parser generator. If your rule inherits from Expr, then instead of calling it the Expr parser is called, with no warnings about dropped rules.

Considering the block parsing rule mentioned above, I believe the real edge case looks like the following:

```rust
for i in [1, 2, 3] { /* do stuff */ }
*x = expr;
```

Without the block parsing special cases, this would parse as `(for i in [1, 2, 3] { /* do stuff */ } * x ) = expr` which is obviously nonsensical, and it's a common edge case.

I wonder if there are other edge cases which we should consider?

**Comment by vlad20012** [comment]
You better not know how I fixed it (#7414). I think it's the most awful hack I have ever done.

**Comment by afetisov** [comment]
That's disappointing :( I'd rather try and fix the grammar.

**Comment by vlad20012** [comment]
The only possible alternative is to bring changes to Grammar-Kit itself. I tried to contribute to it a few years ago, but GK code quality is so bad that it's easier to rewrite it completely... which I also tried once, but stopped halfway.

**Comment by afetisov** [comment]
I don't believe we need to change Grammar-Kit. If I understand the problem correctly, the only ambiguous situation is where a statement starts with a block expression (while, loop, async, simple block etc). If it's true, then the rules should be the following:

* Expr is split into two parts, BlockLikeExpr (listed above) and SimpleExpr (all subrules of Expr other than the blocklike ones). `Expr ::=  BlockLikeExpr | SimpleExpr`
* Statements production rules are changed, so that instead of Expr we would parse `BlockLikeExpr | SimpleExpr`. I.e. if a statement starts with a block, then that block is the entire statement, otherwise we parse an expression as usual.
* In all other contexts we leave Expr as is, e.g. a `let` binding parses Expr on its right-hand side just like now.
* Everything related to the StatementMode flag is removed. Functions `isCompleteBlockExpr / isIncompleteBlockExpr` are removed. Binary operators have Expr as their RHS.

Factoring out BlockLikeExpr wouldn't change parsing priorities in a meaningful way. The only rules which currently precede it are `RetExpr | YieldExpr | LambdaExpr | AssignBinExpr`. The first 3 are unambiguous with BlockLikeExpr and can be interchanged with it. AssignBinExpr can start with a BlockLikeExpr, but in this case it shouldn't be parsed anyway. See [the Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=fn%20foo(x%3A%20%26mut%20usize)%20%7B%0A%20%20%20%20%7B%20*x%20%7D%20%3D%205%3B%0A%7D).

I have tried a bit to implement it, but the grammar is so complex that I haven't succeeded thus far. I also fear that it may result in unexpected changes to some Psi nodes, if some of the rules which must be removed are not private.

**Comment by vlad20012** [comment]
To be honest, I don't understand your plan. Perhaps we could speak with a voice? You can call me on Telegram (the contact is in the github profile)
