### ISSUE TITLE
"Import all" context action / quick fix

### ISSUE THREAD

**Issue by ralfbiedert** [intellij-rust/intellij-rust#7241]
## Feature Request

When refactoring I often find myself cut & paste code between files. It would be nice to get an **Import all** context action / quick fix, available on _any_ missing item that imports all unambiguous items.   

![image](https://user-images.githubusercontent.com/301288/119123029-725f2780-ba2f-11eb-95d2-e5ae520fc200.png)

**Comment by Undin** [comment]
Not sure that we actually need this quick fix. Looks like the proper way to solve the described problem is to import all necessary stuff after `Paste` action, as other languages do

**Comment by ralfbiedert** [comment]
> the proper way to solve the described problem is to import all necessary stuff after Paste action, as other languages do

No strong opinion. The annoying part is having to fix 10+ imports the plugin already knows about. I've used "Import all" in other tools (Resharper?, can't recall) and liked the workflow, but yes, import-on-paste could be even better.

**Comment by Kobzol** [comment]
If someone wants to implement this, it should be possible using `CopyPastePostProcessor`. You can take a look how Kotlin implements it [here](https://github.com/JetBrains/kotlin/blob/master/idea/src/org/jetbrains/kotlin/idea/codeInsight/KotlinCopyPasteReferenceProcessor.kt).

**Comment by Sushisource** [comment]
I would love this feature - I'd also advocate for a generic import all action (in addition to any copy-paste hook). EX: It's easy to imagine the new file was created outside of the IDE, now the copy-paste hook is useless, but the general action is useful.

**Comment by Kobzol** [comment]
Actually, the hook could work in that case, just Select all (Ctrl+A), Cut (Ctrl+X), Paste (Ctrl+V), and the references would be imported :)

But if course an Import All action makes sense by itself.

**Comment by dima74** [comment]
@ralfbiedert @Sushisource use case with pasting code from editor is fixed in #7597, also please note that there is an option "Add unambiguous imports on the fly" (#8266)
