### ISSUE TITLE
Please do not show auto-completing (of existing identifiers) for identifier declaration

### ISSUE THREAD

**Issue by anatawa12** [intellij-rust/intellij-rust#7249]
## Environment

* **IntelliJ Rust plugin version:** 0.3.146.3826-211
* **Rust toolchain version:** 1.52.1 (9bc8c42bb 2021-05-09) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.1.1 Ultimate Edition (IU-211.7142.45)
* **Operating system:** macOS 11.2.1
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description

When I declare some identifier, the Intellij Rust shows an auto-completing window and focuses the top hit.
I think that's not good.

## Steps to reproduce

1. Create a rust project.
2. Write `let s` in your code.
3. PROBLEM1: then IntelliJ Rust shows auto-completing window focusing `std`.
4. Please enter a space after `let s`
5. PROBLEM2: then IntelliJ Rust enters as `let std `

![image](https://user-images.githubusercontent.com/22656849/119245322-6603d780-bbb3-11eb-8471-a5f8f7a0a395.png)

**Comment by afetisov** [comment]
There could be a destructuring pattern in the binding, and an IDE should provide autocompletion for that, so the popup kind of makes sense, but it shouldn't fire as soon. The full autocompletion prompt should only appear once the binding is definitely more complex than an identifier, or if explicitly called for.
