### ISSUE TITLE
Document `Attach Cargo Project` action

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#7283]
Currently, the plugin documentation contains info only about opening existing project via `Open` action. Although it's the most common case how to get a configured project model for Rust project in our IDEs, there are cases when a project is more complex and Rust crate is only part of such project.
The plugin provides `Attach Cargo Project` action to add almost any project directory as a separate Cargo project and configure project model in complex cases.
It would be great to have a paragraph or even a page in our documentation about it.
Note, currently, the action can be invoked from three places: editor notification, Cargo tool window and context menu on the corresponding `Cargo.toml`

**Comment by MarinaKalashina** [comment]
Done https://plugins.jetbrains.com/plugin/8182-rust/docs/attaching-cargo-projects.html
