### ISSUE TITLE
mac clion rust can not into  unix package

### ISSUE THREAD

**Issue by timchenxiaoyu** [intellij-rust/intellij-rust#7286]
![image](https://user-images.githubusercontent.com/9782796/120257973-cf769b00-c2c3-11eb-8918-3528b38dfddc.png)

**Comment by Undin** [comment]
Duplicate of #3957

Try to enable `org.rust.cargo.fetch.actual.stdlib.metadata` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features) to make it work
