### ISSUE TITLE
Rust REPL doesn't work with recent evcxr_repl v0.10.0

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#7295]
## Environment

* **IntelliJ Rust plugin version:** 0.4.148.3892-211-nightly
* **Rust toolchain version:** 1.53.0-nightly (42816d61e 2021-04-24) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.1.2 RC Ultimate Edition (IU-211.7442.27)
* **Operating system:** macOS 10.15.6
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
I can pass only one command. The second one cannot be entered and the IDE shows errors popup 

![image](https://user-images.githubusercontent.com/2539310/120469879-974a8780-c3ab-11eb-9a09-364061e7d19d.png)

Note, everything is fine with `evcxr_repl v0.9.0`

**Comment by wonbyte** [comment]
I also am experiencing this problem.
