### ISSUE TITLE
Improve code formatting

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#73]
While we should leverage [rustfmt](https://github.com/nrc/rustfmt) for code formatting, it is still necessary to provide indentation support for enjoyable editing. 

* [code](https://github.com/alexeykudinkin/intellij-rust/blob/master/src/org/rust/lang/formatter/RustFormattingBlock.kt)
* [docs](http://www.jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support/code_formatting.html)
* formatting in the [go plugin](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/src/com/goide/formatter/GoFormattingModelBuilder.java)

**Comment by matklad** [comment]
The major pain at the moment is the support for chain calls. That is, this

```Rust
foo().bar()
     .baz()
```

is not aligned.

**Comment by matklad** [comment]
Current formatter is here: https://github.com/intellij-rust/intellij-rust/tree/master/src/main/kotlin/org/rust/ide/formatter

**Comment by zjhmale** [comment]
is this can be closed after #289 merged?

**Comment by matklad** [comment]
Not quite. There is at least three reasons to implement our own formatter in addition to `rustfmt`.

* refactorings and snippets use IDEAs formatter
* `rustfmt` is not quite done yet, so by itself it is not a 100% solution for all formatting problems
* Not everybody has `rustfmt` installed

**Comment by zjhmale** [comment]
:+1: the second point matters most i think.

**Comment by jajakobyly** [comment]
I'll try to do sth in this area

**Comment by jajakobyly** [comment]
Hmm should anything be done here apart from providing similar configurability to rustfmt? Wrapping could be imho delegated to rustfmt, the same may apply to inserting commas etc.

**Comment by matklad** [comment]
Yeah, I guess the issue can be closed because it is too vague. However, I think there are still some bugs with formatter which need fixing. For example, I found that it does not indents macro calls properly. I can't check the example, but it was somethign along the lines of

```
try!(write!(wherer, "str", 
     param))
```

getting reformatted to 

```
try!(write!(wherer, "str", 
param))
```

Will create an issue once I have time to properly reproduce this.
