### ISSUE TITLE
Can we make the settings of Rust shared across all project (editor-wide)

### ISSUE THREAD

**Issue by QuarticCat** [intellij-rust/intellij-rust#7309]
## Environment

* **IntelliJ Rust plugin version:** 0.4.147.3871-211
* **Rust toolchain version:** 1.52.1
* **IDE name and version:** CLion 2021.1.2-1
* **Operating system:** Arch Linux

## Problem description

I want to set `Rustfmt - Use rustfmt instead of built-in formatter` for all of my projects.

## Steps to reproduce

- Select `Rustfmt - Use rustfmt instead of built-in formatter`
- Create a new project
- This option remains unselected in the new project

**Comment by Undin** [comment]
@QuarticCat you can set up default settings via settings opened from Welcome screen or via `File | New Project Settings | Preferences for New Projects`

**Comment by QuarticCat** [comment]
@Undin Thanks. That helps.
