### ISSUE TITLE
Debug &str printing is non-deterministic on Windows

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#7331]
## Environment

* **IntelliJ Rust plugin version:** 0.4.148.3911-211
* **Rust toolchain version:** 1.54.0-nightly (dbe459ded 2021-06-02) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.1.2 (CL-211.7442.42)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

When trying to print &str variables, the result is very non-deterministic. Sometimes the actual string is printed, but often additional characters are added:

![image](https://user-images.githubusercontent.com/1268573/121641179-26802b00-ca8f-11eb-85aa-37405408440b.png)

Note what is the actual length of the string.

## Steps to reproduce

Try to print &str variable on Windows.

**Comment by Undin** [comment]
@krojew Thanks for the report!
Unfortunately, at this moment msvc lldb doesn't know about Rust types, as a result, some pretty printers don't work as expected.
Specifically for this issue, we have a [hack](https://github.com/intellij-rust/intellij-rust/pull/7065) to make `str` rendering work.
Also, we are working on a proper fix on lldb side but it's a more complicated task, so no ETA. See #5632 as tracking issue about msvc lldb
