### ISSUE TITLE
Wrong no named argument error highlighting with `format_args_capture` feature

### ISSUE THREAD

**Issue by josem435** [intellij-rust/intellij-rust#7332]
## Environment

* **IntelliJ Rust plugin version:** `0.4.148.3911-211`
* **Rust toolchain version:** `1.54.0-nightly-2021-05-11-x86_64-pc-windows-msvc`
* **IDE name and version:** `PyCharm 2021.1.2 (Community Edition) (PC-211.7442.45)`
* **Operating system:** `Windows 10 10.0.19042 Build 19042`
* **Macro expansion engine:** `new`
* **Name expansion engine:** `new`

## Problem description

`format_args_capture` feature allows you to pass implicit named args into formatting macros. The inspector doesn't recognize this feature.

![image](https://user-images.githubusercontent.com/77453282/121678944-b8982b80-caaf-11eb-90cc-86ac9ea05281.png)

## Steps to reproduce

```rust
#![feature(format_args_capture)]

fn foo() {
    let output_string = String::from("I am a string");
    println!("{output_string}");
}
```

**Comment by bugproof** [comment]
This shouldn't be closed. I still get those warnings.

**Comment by vault-thirteen** [comment]
I am still getting this bug in the latest version of CLion with the latest verison of Rust plug-in.
