### ISSUE TITLE
Code Insight does not Work with Re-exports Depending on a `#[cfg(...)]` Attribute

### ISSUE THREAD

**Issue by HTG-YT** [intellij-rust/intellij-rust#7340]
## Environment

* **IntelliJ Rust plugin version:** 0.4.149.3914-212-nightly
* **Rust toolchain version:** 1.55.0-nightly (24bdc6d73 2021-06-12) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.2 EAP (CL-212.3724.2)
* **Operating system:** Windows 10 21H1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Code insight does not work when two modules are re-exported with the same name, but depends on a `#[cfg(..)]` attribute.

## Steps to reproduce

A [reproducible example](https://github.com/TheRustCompilerCollection/rcc/blob/main/src/common/datastructures/mod.rs).

You can simply open that folder or the entire project in any JetBrains IDE and will achieve the same result when `use`d in another file:
![image](https://user-images.githubusercontent.com/39023054/121809893-3c5d3e00-cc91-11eb-8fc8-15f952f8ebdc.png)
[Source](https://github.com/TheRustCompilerCollection/rcc/blob/main/src/common/datastructures/lock.rs)

**Comment by HTG-YT** [comment]
Possible suggestion: Probably we can have some sort of an "environment" for a project, specifying some `#[cfg(...)]` values so that they can be checked in analysis?

**Comment by dima74** [comment]
Please feel free to reopen if you still experience the problem
