### ISSUE TITLE
Generate stubs for trait implementation

### ISSUE THREAD

**Issue by shravanshetty1** [intellij-rust/intellij-rust#7342]
https://www.jetbrains.com/go/guide/tips/implement-an-interface/

**Comment by Kobzol** [comment]
Would something like this work for you? https://github.com/intellij-rust/intellij-rust/pull/5339#issuecomment-727628728

**Comment by shravanshetty1** [comment]
> Would something like this work for you? [#5339 (comment)](https://github.com/intellij-rust/intellij-rust/pull/5339#issuecomment-727628728)

Yes exactly, this saves alot of time and i find this feature highly useful while using intellij to code other languages.

**Comment by Kobzol** [comment]
@vlad20012 Could you please take another look at the mentioned PR? Thanks.
