### ISSUE TITLE
Disable tests

### ISSUE THREAD

**Issue by Shadowblitz16** [intellij-rust/intellij-rust#7343]
## Environment

* **IntelliJ Rust plugin version:** 0.4.148.3911-211
* **Rust toolchain version:** rustc 1.52.1 (9bc8c42bb 2021-05-09)
* **IDE name and version:** idea comunity
* **Operating system:** kubuntu 20.04

## Problem description
I am getting..
```
error[E0152]: found duplicate lang item `panic_impl`
 --> src/main.rs:7:1
  |
7 | fn panic(_info: &PanicInfo) -> ! {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: the lang item is first defined in crate `std` (which `test` depends on)
  = note: first definition in `std` loaded from /home/shadowblitz16/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-0a9489cf400f65e4.so, /home/shadowblitz16/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-0a9489cf400f65e4.rlib
  = note: second definition in the local crate (`rust_os`)
```

when trying to follow this...
https://os.phil-opp.com/freestanding-rust-binary/

## Steps to reproduce

- create a new project
- add these files...
```
//main.rs
#![no_std]
#![no_main]

use core::panic::PanicInfo;

#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    loop {}
}

#[no_mangle]
pub extern "C" fn _start() -> ! {
    loop { }
}
```
```
# Cargo.toml
[package]
name = "rust-os"
version = "0.1.0"
authors = ["shadowblitz16"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]

```
- try to build with this..
![image](https://user-images.githubusercontent.com/2453707/121824052-19fdfd00-cc5e-11eb-9673-fff7b369fea7.png)

**Comment by afetisov** [comment]
You're getting the error from rustc, which means that there is an error in your project. I cannot tell you which error is that, since the supposedly minimal example that you provided doesn't actually reproduce your error (but it does produce a linker error since you didn't define an entry point). However, the most likely reason is that one of your dependencies (probably even your library crate) depends on the `std` library. It's easy to get an example: add a `lib.rs` with `pub use std::mem::MaybeUninit;` to your example project and import `use rust_os::MaybeUninit;` inside of main, you'll get the duplicate handler error that you specified.

**Comment by Shadowblitz16** [comment]
there is not error I can compile it fine through the terminal

**Comment by afetisov** [comment]
CLion doesn't perform any tests when you Build the project. It directly calls `cargo build` with some extra command-line arguments specified by the run configuration. The error that you posted also looks exactly like a compiler error, CLion lints errors are provided exclusively within the editor.

The minimal example that you provided also doesn't trigger the error you specified on a clean CLion project for me. It's possible that you have some options in the run configuration which trigger the compiler error (e.g. a wrong compiler target). You can try uploading a minimal error example as a whole folder, together with the `.idea` subfolder. Maybe we could identify what's wrong with your config.

**Comment by sagacity** [comment]
I ran into the same issue, even without tests. Disabling the "Compile all project targets if possible" option fixed it for me.

I'm not sure why there is a `test` target when I didn't define any tests, though.
