### ISSUE TITLE
Box<[T]> and Box<[T; N]>  mismatched types 

### ISSUE THREAD

**Issue by davyzhu** [intellij-rust/intellij-rust#7350]
## Environment

* **IntelliJ Rust plugin version:**
*  0.4.151.3973-211-nightly
* **Rust toolchain version:**
* Rust 1.52
* **IDE name and version:**
* Pycharm 2021.1.2
* **Operating system:**
* Win 10

## Problem description
Copy source from https://doc.rust-lang.org/stable/std/primitive.slice.html#examples-87
```Rust
let s: Box<[i32]> = Box::new([10, 40, 30]);
let x = s.into_vec();
// `s` cannot be used anymore because it has been converted into `x`.
assert_eq!(x, vec![10, 40, 30]);
```
Compile success, but Pycharm editor will show an error, is it a bug?
![image](https://user-images.githubusercontent.com/149704/122145565-0e8e1a00-ce88-11eb-9bc3-e2f918580565.png)

**Comment by PatrickNorton** [comment]
I'm noticing the same with function calls—it seems IntelliJ Rust doesn't recognize that unsize coercion works on `Box` as well.

```rust
pub fn test_coercion(_x: Box<[u32]>) {}

pub fn test_2() {
    let x = Box::new([1, 2, 3]);
    test_coercion(x)
}
```
