### ISSUE TITLE
Poor Intellisense on Large Modules

### ISSUE THREAD

**Issue by Redfire75369** [intellij-rust/intellij-rust#7354]
## Environment

- IntelliJ Rust Plugin Version: `0.4.148.3911-211`
- Rust Toolchain Version: `rustc 1.51.0 (2fd73fabe 2021-03-23)`
- IDE Name and Version: CLion 2021.1.2
- Operating system: Windows 10 

## Problem Description
When using large modules, little to no intellisense is provided for those modules. This makes it difficult to import the correct functions, enums, constants, or structs (Collectively referred to as "items"), and pass the right parameters to the items. This greatly increases the friction while coding and reduces productivity significantly, as referring to the docs very often is required.

## Steps to Reproduce
1. Add [rust-mozjs](https://github.com/servo/rust-mozjs) as a dependency via git like [this](https://github.com/Redfire75369/spiderfire/blob/b84b0f838905f184208d2634e07ff8718a65f1bd/Cargo.toml#L12).
2. Type `use mozjs::jsapi::`
  - No intellisense is provided for what items can be imported.
3. Type `JS_NewGlobalObject` or any other item within `mozjs::jsapi`.
  - No intellisense is provided for importing the function.
4. Import `JS_NewGlobalObject` with `use mozjs::jsapi::JS_NewGlobalObject`.
  - No intellisense is provided for the types of the arguments.

## Notes
1. I cannot confirm this is purely due to the large number of items, but I believe it is likely as all other modules in the package have correct intellisense. The `jsapi` module in particular has over 1700 items as can be seen [here](https://doc.servo.org/mozjs/jsapi/index.html).
2. I am currently working on a project, named Spiderfire, that can be found [here](https://github.com/Redfire75369/spiderfire), which suffers from this issue.
  - **Warning: CLion fails to find to compile the module due to the requirement of the Visual Studio Developer Command Prompt (on Windows).**
  - **Warning: Compiling the project can take a long time on weak hardware due to the requirement of compiling SpiderMonkey.**

**Comment by afetisov** [comment]
It's not an issue with performance, it's an issue with name resolution and macro handling. Specifically, the relevant module has the following structure:

```rust
// rust-mozjs/lib.rs
pub mod jsapi {
    pub use mozjs_sys::jsapi::glue::*;
    pub use mozjs_sys::jsapi::js::detail::*;
    pub use mozjs_sys::jsapi::js::Scalar::Type;
    pub use mozjs_sys::jsapi::js::*;
    pub use mozjs_sys::jsapi::mozilla::MallocSizeOf;
    pub use mozjs_sys::jsapi::JS::detail::*;
    pub use mozjs_sys::jsapi::JS::shadow::Object;
    pub use mozjs_sys::jsapi::JS::*;
    pub use mozjs_sys::jsapi::*;
}
```

You can see that it's a number of imports from `mozjs_sys::jsapi`. Ok, let's look how that module is defined.

```rust
// mozjs/lib.rs

/* snip */

// Reexport the bindings in the jsapi module
pub use generated::root as jsapi;

// The bindings generated by bindgen
mod generated {
    include!(concat!(env!("OUT_DIR"), "/build/jsapi.rs"));
}
```

So the imports that you're after are included at build time from an autogenerated bindings file. In fact, that file doesn't even exist until one builds `rust-mozjs` and `mozjs-sys` properly. I certainly can't do that on my machine, it requires configuring and building Spidermonkey and I'm not doing that.

Until the build completes successfully there is nothing to include, so IDEA is working as expected. It's possible that name resolution will still fail to work once you set it up since macros are a complicated thing, but I can't test it.

**Comment by Redfire75369** [comment]
> Until the build completes successfully there is nothing to include, so IDEA is working as expected. It's possible that name resolution will still fail to work once you set it up since macros are a complicated thing, but I can't test it.

Using the workaround where you start CLion from the Visual Studio Developer Command Prompt, after setting all environment variables. I was able to successfully compile them. However, as you suspected, the name resolution still fails.

**Comment by Undin** [comment]
@Redfire75369 try to enable `org.rust.cargo.evaluate.build.scripts` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features). It allows plugin to know the proper value of `OUT_DIR` variable for each crate and make construction like `include!(concat!(env!("OUT_DIR"), "/build/jsapi.rs"));` work as expected. See https://github.com/intellij-rust/intellij-rust/issues/1908 for more details
