### ISSUE TITLE
Support items generated by snafu derive macro

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#7365]
Here is the use-case:

Cargo.toml:

```toml
[package]
name = "snafu-jetbrains"
version = "0.1.0"
edition = "2018"

[dependencies]
snafu = "0.6"
```

main.rs

```rust
use snafu::Snafu;

/// The error type for this library.
#[derive(Debug, Snafu)]
enum Error {
    #[snafu(display("This is always an error:: {}", message))]
    AlwaysError { message: String },
}

fn hello_world() -> Result<(), Error> {
    AlwaysError {
        message: "this is a struct created by snafu",
    }
    .fail()
}

fn main() {
    hello_world().unwrap()
}
```

Problem:

![image](https://user-images.githubusercontent.com/6260372/121945000-20e14a00-cd08-11eb-8249-a0e6c728b0e3.png)

Desired behavior: code completion should be available for the struct `AlwaysError`:

![image](https://user-images.githubusercontent.com/6260372/121945213-60a83180-cd08-11eb-9413-077c12de7f80.png)

Desired behavior: context actions should provide the ability to fill in missing struct fields for the `AlwaysError` struct.

![image](https://user-images.githubusercontent.com/6260372/121945297-76b5f200-cd08-11eb-9e4e-e0d1b8f4ab82.png)

Thank you! 🚀

_Originally posted by @webern in https://github.com/intellij-rust/intellij-rust/issues/6908#issuecomment-860922178_

**Comment by webern** [comment]
Thank you for transferring this to an issue!
