### ISSUE TITLE
"Move Statement Up/Down" doesn't work for statements inside a block expression as parameter

### ISSUE THREAD

**Issue by sum-elier** [intellij-rust/intellij-rust#7376]
## Environment

* **IntelliJ Rust plugin version:** 0.4.150.3936-211-nightly
* **Rust toolchain version:** 1.55.0-nightly (ce1d5611a 2021-06-18) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.1.2 (CL-211.7442.42)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Trying to move statements inside an expression block being passed as a parameter to a function prevents the command "Move Statement Up/Down" from working in the statements.

## Steps to reproduce

Paste the code snippet below into IDE and try to move any of the `println!` statements up or down using the shortcut mapped to the command "Move Statement Up/Down":

```rust
fn async_receiver<F, T>(future: F)
   where
      F: std::future::Future<Output = T>,
{
}

fn foo() {
   async_receiver(async {
      println!("1");
      println!("2");
   });
}
```
or
```rust
fn foo(a: u32) {}

fn main() {
    foo({
        println!("1");
        println!("2");
        1
    });
}
```

**Comment by Kobzol** [comment]
It's not actually caused by `async` blocks, but by the block being inside an argument list. It also doesn't work here:
```rust
fn foo(a: u32) {}

fn main() {
    foo({
        println!("1");
        println!("2");
        1
    });
}
```

**Comment by sum-elier** [comment]
I'll update the issue title to be accurate and include your example.
