### ISSUE TITLE
Run test in failure when module name is rust keyword

### ISSUE THREAD

**Issue by ihciah** [intellij-rust/intellij-rust#7387]
## Environment

* **IntelliJ Rust plugin version:** 0.4.148.3911-211
* **Rust toolchain version:** v1.53.0 stable
* **IDE name and version:** CLion 211.7442.42
* **Operating system:** MacOS 11.2.3 (20D91)

## Problem description
Clink run icon on test will result in failure if file name is rust keywords(like struct.rs, enum.rs or type.rs)

## Steps to reproduce

Create a file named struct.rs and write any test inside it. Click run icon on the test.

**Comment by Kobzol** [comment]
What error are you getting?
I tried it locally and it seems to work for me:
```rust
// main.rs
#[path = "struct.rs"]
mod foo;

// struct.rs
#[cfg(test)]
mod tests {
    #[test]
    fn test() {
        assert_eq!(1, 1);
    }
}
```
The IDE invokes
```
cargo test --color=always --package example_project --bin example_project foo::tests::test --no-fail-fast -- --format=json --exact -Z unstable-options --show-output
```
and the test works.

**Comment by ihciah** [comment]
> What error are you getting?
> I tried it locally and it seems to work for me:
> 
> ```rust
> // main.rs
> #[path = "struct.rs"]
> mod foo;
> 
> // struct.rs
> #[cfg(test)]
> mod tests {
>     #[test]
>     fn test() {
>         assert_eq!(1, 1);
>     }
> }
> ```
> 
> The IDE invokes
> 
> ```
> cargo test --color=always --package example_project --bin example_project foo::tests::test --no-fail-fast -- --format=json --exact -Z unstable-options --show-output
> ```
> 
> and the test works.

In my case the module name is the same as the file name which is a keyword. 
(I'm sorry and I should describe the problem as "module name is rust keyword" instead of "file name is rust keyword")

The command executed is(some project names are hidden):
```
/Users/ihciah/.cargo/bin/cargo test --color=always --lib xxxxxx::struct::tests::test --no-fail-fast --manifest-path /Users/ihciah/code/XXXXXX/Cargo.toml -- --format=json --exact -Z unstable-options --show-output
```

If I execute the command manually, it matches nothing, which maybe the cause of IDE showing error(The error is "Test framework quit unexpectedly"). However, if I replace `xxxxxx::struct::tests::test` with `xxxxxx::r#struct::tests::test`, the expected result is returned. 

I think maybe the module name passed to cargo command should be pre-processed?

By the way, if I add `r#` to a non-keyword, it matches failed too. I don't know if the behavior is the designed in cargo beacuse adding `r#` does no harm in common rust code.

**Comment by Kobzol** [comment]
Oh, I didn't realize that you're using raw identifiers, and I was wondering how the heck are you able to include such files :D
I created a [PR](https://github.com/intellij-rust/intellij-rust/pull/7390) that tried to fix this.
