### ISSUE TITLE
Suggest `match to if-let` intention in more cases

### ISSUE THREAD

**Issue by avrong** [intellij-rust/intellij-rust#7409]
The current intention behavior: convert match with a single non-empty arm to if let.

The situations below can also be handled:

### 1. One empty arm

```rust
match something {
    Some(_) => {}
}
```

```rust
if let Some(_) = something {

}
```

### 2. Two exhaustive arms

```rust
match something {
    Some(_) => {}
    None => {}
}
```

```rust
if let Some(_) = something {

} else {
    
}
```

#### For example, `if let to match` intention behaves this way, but the opposite can't be applied:

```rust
if let Some(_) = something {

}
```

```rust
match something {
    Some(_) => {}
    None => {}
}
```

**Comment by Kobzol** [comment]
I suppose that this can be done fully general now with irrefutable patterns. Something like
```rust
match e {
    E::V1(_) => 1,
    E::V2(_) => 1 + 2,
    E::V3(_) => 3
}
// v
if let E::V1(_) = e {
   1
} else if let E::V2(_) = e {
   1 + 2
} else {
   3
}
```
I'll send a PR next week.

**Comment by Undin** [comment]
Since #9396 reverted changes introduced in #7435, I reopen this issue
