### ISSUE TITLE
Detect when stdlib source does not match active rustc version

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#741]
I had an existing `intellij-rust` project using stable 1.11.0 and the 1.11.0 stdlib source code.

I ran

``` bash
rustup update
```

``` bash
rustup show
Default host: x86_64-pc-windows-gnu

stable-x86_64-pc-windows-gnu (default)
rustc 1.12.0 (3191fbae9 2016-09-23)
```

After restarting `intellij-rust`, the project did not prompt with any warnings that my rustc version differed from the stdlib source that was attached to the project.  I think ideally if those do not match, the user should be prompted to download a new stdlib source.  Currently, my workaround is to delete the old stdlib source (in this case `rust-1.11.0-src.zip`) to get `intellij-rust` to prompt me to download again.

**Comment by johnthagen** [comment]
@matklad I think with the recent rework of reading the version of rustc each time the project is opened, that this problem has been solved. At least, I haven't run into it in a long time.

I am inclined to close this issue.

**Comment by matklad** [comment]
Indeed!
