### ISSUE TITLE
Windows - rustup takes very long time

### ISSUE THREAD

**Issue by ghost23** [intellij-rust/intellij-rust#744]
Hi,

I have an issue on my windows machine. I startup intellij with the Rust plugin and the rust tools already configured. It seems on startup rustup is started and it almost completely blocks the IDE while running and it runs a very long time, I haven't yet had the patience to wait for it to stop.

Though when I start rustup update in a commandline without IntelliJ it works just fine and quickly finishes, since I already have the latest stuff installed.

In my intellij log folder I see a freeze-.... Folder with threadDumps. In one of those it reads in the first line:

"AWT-EventQueue-0 2016.2.4#IU-162.2032.8 IDEA, eap:false, os:Windows 10 10.0, java-version:JetBrains s.r.o 1.8.0_112-release-b343" prio=0 tid=0x0 nid=0x0 blocked
     java.lang.Thread.State: BLOCKED
 on com.intellij.ide.plugins.cl.PluginClassLoader@191f721 owned by "ApplicationImpl pooled thread 1" Id=29

In another, I see this:

"AWT-EventQueue-0 2016.2.4#IU-162.2032.8 IDEA, eap:false, os:Windows 10 10.0, java-version:JetBrains s.r.o 1.8.0_112-release-b343" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: TIMED_WAITING
 on com.intellij.openapi.application.impl.ReadMostlyRWLock@6e4fea
	at sun.misc.Unsafe.park(Native Method)

and a bit down:

"ProcessWaitFor: rustup.exe" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE
 (in native)
[threadDump-20161016-195340.txt](https://github.com/intellij-rust/intellij-rust/files/532015/threadDump-20161016-195340.txt)
[threadDump-20161016-195525.txt](https://github.com/intellij-rust/intellij-rust/files/532016/threadDump-20161016-195525.txt)

I have attached those dumps.

When I temporarily rename rustup to something else, so that IntelliJ cannot find it, everythings works OK.

**Comment by matklad** [comment]
We certainly should not block while waiting for rustup, but it should not deadlock as well. What happens if you execute `rustup component add rust-src` manually?

**Comment by ghost23** [comment]
It downloads the component and installs it, though installing takes quite some time. I am not sure though, if it is as long, as IntelliJ was hanging.
