### ISSUE TITLE
Double Build Run Configuration for Tests

### ISSUE THREAD

**Issue by Redfire75369** [intellij-rust/intellij-rust#7443]
## Environment
- IntelliJ Rust Plugin Version: `0.4.149.3939-211`
- Rust Toolchain Version: `rustc 1.51.0 (2fd73fabe 2021-03-23)`
- IDE Name and Version: CLion 2021.1.2
- Operating system: Windows 10 

## Problem description
Running `cargo test` through a run configuration causes the project to be built twice (I'm not sure if the second time is files being moved around or being recompiled, former seems likelier), once during the `Before Launch` task, and once during the actual run. This results in wasted time, which is significant on slower computers. I have not tested this with `cargo run` yet, but I believe results will be similar.

## Steps to reproduce
This was attempted in [Spiderfire](https://github.com/Redfire75369/spiderfire), which has the large dependency of `mozjs`/`mozjs_sys`.
1. Create a run configuration that runs `cargo test`
2. Run the run configuration
3. Project is built once in the Build tab, then built again in the Run tab

## Run Configuration XML
```xml
<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="Test" type="CargoCommandRunConfiguration" factoryName="Cargo Command">
    <option name="command" value="test" />
    <option name="workingDirectory" value="file://$PROJECT_DIR$" />
    <option name="channel" value="DEFAULT" />
    <option name="requiredFeatures" value="true" />
    <option name="allFeatures" value="false" />
    <option name="emulateTerminal" value="false" />
    <option name="withSudo" value="false" />
    <option name="backtrace" value="SHORT" />
    <envs />
    <option name="isRedirectInput" value="false" />
    <option name="redirectInputPath" value="" />
    <method v="2">
      <option name="CARGO.BUILD_TASK_PROVIDER" enabled="true" />
    </method>
  </configuration>
</component>
```

**Comment by mchernyavsky** [comment]
As a workaround, you can disable `org.rust.cargo.build.tool.window` feature in `Action > Experimental features...`
