### ISSUE TITLE
IDE jumps to location of first error after building erroneous code

### ISSUE THREAD

**Issue by MrMuetze** [intellij-rust/intellij-rust#7466]
Hey everyone 👋 first of all thank you for an awesome plugin!

## Environment

IntelliJ Rust plugin version: 0.4.150.3968-211
Rust toolchain version: nightly-2021-01-11
IDE name and version: CLion 2021.1.2
Operating system: macOS 11.4

## Problem description

Whenever I build my Rust project and there are errors, the IDE automatically jumps to the location of the first error. This also happens if that error is located in a different file. I would love to disable this behavior completely and not automatically jump to a different location.

## Steps to reproduce

Just write some Rust code that won't compile. The IDE should jump to the location of the first error automatically.

**Comment by Sushisource** [comment]
This drives me batty as well, constantly ends up with me typing something where I didn't mean to since often I'm continuing to edit while compile is happening and then *bam* my cursor is moved somewhere else.

**Comment by MrMuetze** [comment]
I just noticed that this was shipped already :) thank you very much!
