### ISSUE TITLE
Formatting of `return` expression with block subexpressions breaks the code

### ISSUE THREAD

**Issue by afetisov** [intellij-rust/intellij-rust#7467]
## Environment

* **IntelliJ Rust plugin version:** 0.4.151.3966-211-nightly
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.1.2 (CL-211.7442.42)
* **Operating system:** Linux 5.4.0-77-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

The following code:

```rust
fn f() {
    return { 3 } + 5;
}
```

after calling "Reformat Code" becomes:

```rust
fn f() {
    return { 3 }; + 5;
}
```

Expected: code stays the same, since the priority of `return` expressions is lower than that of binary operators.

The error doesn't reproduce if `return` is changes into `break` or `yield`.

**Comment by afetisov** [comment]
@vlad20012 That pull request has nothing to do with this issue. The error happens on the branch that I pushed.

**Comment by vlad20012** [comment]
Okaay

**Comment by vlad20012** [comment]
I've re-checked this after merging #7462 and the issue seems fixed

**Comment by afetisov** [comment]
Strange, I got it while working on that branch. Oh well, off with it.
