### ISSUE TITLE
False "never used" warning

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#7469]
## Environment

* **IntelliJ Rust plugin version:** 0.4.150.3968-211
* **Rust toolchain version:** 1.55.0-nightly (868c702d0 2021-06-30) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.1.2 (CL-211.7442.42)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

When using the `tracing` crate, variables used for logging are falsely marked as not used.

## Steps to reproduce

```Rust
use tracing::*;

if let Err(error) = foo() {
    // "error" is marked as not used
    error!(%error, "foo!");
}
```

**Comment by ortem** [comment]
Thank you for reporting. Please try executing `Re-Expand All Rust Macros` action, and then `Invalidate Caches` action if the first one doesn't help. Both actions can be invoked via `Ctrl+Shift+A` menu.

**Comment by krojew** [comment]
Seems like restarting the IDE helped.
