### ISSUE TITLE
Incorrect reformatting if a pattern contains ..

### ISSUE THREAD

**Issue by jfirebaugh** [intellij-rust/intellij-rust#747]
Reformat the following code:

```
fn main() {
    match x {
        A(.., B) => true,
        C => false
    }
}
```

Expected result: no change.

Actual result:

```
fn main() {
    match x {
        A(.., B) => true,
    C => false
}
}
```

**Comment by matklad** [comment]
Are you using the alpha or the nightly version of the plugin? This should be fixed in the latest nightly.

**Comment by jfirebaugh** [comment]
Confirmed, it's fixed in nightly.
