### ISSUE TITLE
Unable to run debugger: Debugger is not loaded yet; Debugger: Debugger downloading failed

### ISSUE THREAD

**Issue by notfed** [intellij-rust/intellij-rust#7500]
Looks like I'm getting the same error as https://github.com/intellij-rust/intellij-rust/issues/5921:

> Unable to run debugger: 
> Debugger is not loaded yet; 

> Debugger: 
> Debugger downloading failed 

I'm on Linux fedora 5.10.16-100.fc32.x86_64.

## Environment

* **IntelliJ Rust plugin version:** 0.3.131.3366-201
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2020.1.4 Ultimate Edition (IU-201.8743.12)
* **Operating system:** Linux 5.10.16-100.fc32.x86_64

**Comment by Undin** [comment]
@notfed you have a quite old plugin version. I'd recommend you update the plugin. Note, the latest plugin versions are built only for 2021.1 and 2021.2 major IDE versions so they require updating IDE as well

**Comment by notfed** [comment]
I switched to CLion which works fine, haven't yet tried your proposed  IntelliJ solution. We can close this.
