### ISSUE TITLE
False positive "methods calls get_ usually take self by reference" for get_xxx_mut

### ISSUE THREAD

**Issue by qiujiangkun** [intellij-rust/intellij-rust#7520]
## Environment

* **IntelliJ Rust plugin version:** 0.4.150.3968-211
* **Rust toolchain version:** 1.55.0-nightly (e6b4c252e 2021-06-25) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.1.2 (CL-211.7442.42)
* **Operating system:** Linux 5.10.42-1-manjaro
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
I have a function called `get_client_mut(&mut self) -> &mut Client`, but it gives me a warning.
![image](https://user-images.githubusercontent.com/33482468/125481433-c39a2bbc-ce49-420e-9551-6d43a2f38fd0.png)

**Comment by Kobzol** [comment]
Related issue: https://github.com/intellij-rust/intellij-rust/issues/7475
