### ISSUE TITLE
Move vec macro arguments not working when missing a comma

### ISSUE THREAD

**Issue by sum-elier** [intellij-rust/intellij-rust#7522]
## Environment

* **IntelliJ Rust plugin version:** 0.4.152.3985-211-nightly
* **Rust toolchain version:** null
* **IDE name and version:** CLion 2021.1.3 (CL-211.7628.27)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Moving `vec!` macro arguments down and then up when some arguments are in a single line and missing a comma, fails.

### Fails
```rust
fn main() {
   let v = vec![
      "a",
      "b",/*caret. Move statement down*/
      "c", "d"
   ];
}
```
```rust
fn main() {
   let v = vec![
      "a",
      "c", "d"
      "b",/*caret. Try to move statement up. Doesn't work.*/
   ];
}
```
### Works
A
```rust
fn main() {
   let v = vec![
      "a",
      "b",/*caret. Move statement down*/
      "c", "d",
   ];
}
```
```rust
fn main() {
   let v = vec![
      "a",
      "c", "d",
      "b",/*caret. Try to move statement up. Works.*/
   ];
}
```
B
```rust
fn main() {
   let v = vec![
      "a",
      "b",
      "c", /*caret. Move statement down*/
      "d"
   ];
}
```
```rust
fn main() {
   let v = vec![
      "a",
      "b",
      "d",
      "c",/*caret. Try to move statement up. Works.*/
   ];
}
```

**Comment by sum-elier** [comment]
@ortem I saw https://github.com/intellij-rust/intellij-rust/pull/6904 fixing this but discovered this bug :(

**Comment by ortem** [comment]
@sum-elier Thank you for your report, it should be fixed indeed. For example, IDE automatically adds a comma in the following situation with function arguments:

Before
```Rust
foo(
    1,
    2, // move down
    3
)
```
After
```Rust
foo(
    1,
    3,
    2,
)
```
