### ISSUE TITLE
Proc macro expansion doesn't work on nightly rust

### ISSUE THREAD

**Issue by PizzaCrust** [intellij-rust/intellij-rust#7541]
## Environment

* **IntelliJ Rust plugin version:** 0.4.152.3991-211-nightly
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2021.1.3 Community Edition (IC-211.7628.21)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
When I switch from stable to nightly and try to expand proc macros, it will say:
`Failed to expand the macro: the procedural macro is not compiled successfully`

## Steps to reproduce
Expand proc macro on nightly rust

**Comment by Undin** [comment]
Fixed by #7611
