### ISSUE TITLE
run wrong test on wsl

### ISSUE THREAD

**Issue by gengjiawen** [intellij-rust/intellij-rust#7543]
## Environment

* **IntelliJ Rust plugin version:** 0.4.150.3968-211
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.1.3 (CL-211.7628.27)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Steps to reproduce

Repo: https://github.com/gengjiawen/monkey-rust

The test case run not right. Looks like it runs in `wasm`, but the test exist in `parser` package.

![image](https://user-images.githubusercontent.com/3759816/126069448-5194a6b0-c526-4e0b-9d7f-6577700686c4.png)

**Comment by mchernyavsky** [comment]
It actually runs the test from `parser`:

<img width="1792" alt="Screenshot 2021-07-18 at 22 43 40" src="https://user-images.githubusercontent.com/6079006/126080285-8763580c-0022-4856-bdae-a291963f9b61.png">

**Comment by gengjiawen** [comment]
Thanks. I forget there is a same test in `parser` too. Sorry for this inconvenience.
