### ISSUE TITLE
Don't run permanent "Building..." task if "Redirect input from" file doesn't exist

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#7548]
## Environment

* **IntelliJ Rust plugin version:** 0.4.152.3991-212-nightly
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.3 EAP (CL-213.1283)
* **Operating system:** macOS 11.4
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

#7273 and #7239 introduced a warning inside a run configuration if the "Redirect input from" file doesn't exist. Unfortunately, it is still possible to start this configuration which will result in a permanent "Building..." progress bar and a disabled "Run" icon.

## Steps to reproduce

- Create a new binary project
- Edit `main.rs` run configuration and specify some missing file in "Redirect input from" field
- Run the configuration

**Comment by ValeryAntopol** [comment]
The same happens to me if I specify a path to inexistent directory in "Working dir" field of run configuration without touching other fields.

## Environment

* **IntelliJ Rust plugin version:** 0.4.159.4232-212
* **Rust toolchain version:** 1.54.0 (a178d0322 2021-07-26) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.2.3 (CL-212.5457.51)
* **Operating system:** macOS 11.5.2
* **Macro expansion engine:** new
* **Name resolution engine:** new
