### ISSUE TITLE
Indicate cargo.toml not in root path

### ISSUE THREAD

**Issue by metaclips** [intellij-rust/intellij-rust#7572]
## Environment

* **IntelliJ Rust plugin version:**
* **Rust toolchain version:**
* **IDE name and version:**
* **Operating system:**

## Problem description
Is it possible for intellij-rust to detect cargo.toml that are not on the root path? I really don't want to use cargo workspace, is there an alternative like rust-analyzer `rust-analyzer.linkedProjects` where I can indicate all cargo.toml paths?

**Comment by Undin** [comment]
You can attach necessary Cargo projects via `Attach Cargo Project` action. See https://plugins.jetbrains.com/plugin/8182-rust/docs/attaching-cargo-projects.html

**Comment by metaclips** [comment]
Thanks @Undin closing now.

**Comment by alexjpwalker** [comment]
Are there any technical limitations in the plugin that would prevent it from being able to detect `Cargo.toml`s recursively?

We're currently developing the plugin (to add Bazel support), and tried adding this recursive search so we don't need to manually "Attach Cargo Project" for every project. Specifically, by making `CargoProjectService.suggestManifests()` do a recursive file search for `Cargo.toml`s, return all of them, and make `guessAndSetupRustProject` attach all the returned Cargo projects, not just the first one we find.

It actually succeeds and adds all the Cargo projects, but then code analysis appears broken for some of the attached projects. e.g: we auto-find project A and project B, but in source files in project B, we can't navigate to the stdlib sources when clicking on a standard Rust symbol such as `Option`.

**Comment by vlad20012** [comment]
I know only one technical limitation: processing files recursively using IntelliJ's VFS is SLOW

**Comment by alexjpwalker** [comment]
Is it so slow that this would be a blocker? ie: if a PR were submitted to detect `Cargo.toml`s recursively, would it be rejected on the basis of slowness?

I have not tested in a very large project (such as `intellij-rust` itself!), but in projects with ~100 source files, it appears to perform well enough - I see virtually no difference between the time taken to detect the Cargo projects before + after the change.

We could add an upper limit, say 1000, on the total number of directories to scan before giving up.
