### ISSUE TITLE
INT: add intention to implement a trait leads to generating an invalid code for unsafe trait

### ISSUE THREAD

**Issue by mili-l** [intellij-rust/intellij-rust#7590]
## Environment

* **IntelliJ Rust plugin version:** 0.4.153.4012-212-nightly
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.2 (CL-212.4746.61)
* **Operating system:** macOS 11.0.1
* **Macro expansion engine:** disabled
* **Name resolution engine:** new

## Problem description
`Implement trait' operation leads to generating invalid code for unsafe trait

## Steps to reproduce
1. There is a code
  ```rust
  enum Hello {
      World(String),
      Store { name: String },
  }
  
  unsafe trait Foo {
      // methods go here
  }
  ```
2. Move cursor to `Hello` and press Alt+Enter => intension appears
3. Choose `Implement trait'
4. Choose `Foo` for implementation 

## Expected Result:
unsafe imlp is generated
  ```rust
  unsafe impl Foo for Hello {}
  ```

## Actual Result:
Invalid code is generated
  ```rust
  impl Foo for Hello {}
  ```
![unsafeimpl](https://user-images.githubusercontent.com/1213122/127125482-7186848c-dd10-4de7-8b0d-e8683deff0db.gif)

Related #7480

**Comment by vlad20012** [comment]
@Kobzol, hmm, it looks like after template finish we should also insert `unsafe` if the trait is `unsafe`

**Comment by vlad20012** [comment]
But maybe such implicit `unsafe` insertion is not a good idea :thinking:

**Comment by vlad20012** [comment]
Better let's provide `AddUnsafeFix` for `E0200`

**Comment by Kobzol** [comment]
I think that we should do both.

**Comment by vlad20012** [comment]
> I think that we should do both.

I'm not sure if an IDE should implicitly add `unsafe` because this is, well, unsafe. It should take the user's attention, like "LOOK here, Oh MY GOD this is UNSAFE! uuunnnsSSSAAAFFeee actually RIGHT HERE, do you see it? Do you REALLY consider this UnSaFe OK here?"

**Comment by Kobzol** [comment]
:D Okay, when you state it like that, I suppose that there is some value in being explicit here. I'll send a PR that provides `AddUnsafeFix` here.
