### ISSUE TITLE
Proc macro on struct which are generating new struct in crates failing

### ISSUE THREAD

**Issue by Kloenk** [intellij-rust/intellij-rust#7610]
## Environment

* **IntelliJ Rust plugin version:** 0.4.151.3997-211
* **Rust toolchain version:** 1.53.0
* **IDE name and version:** clion, CLion 2021.1.3
* **Operating system:** macOS 11.5 (m1)

## Problem description
The proc macros from the crate [pnet](https://crates.io/crates/pnet) cannot be expanded

## Steps to reproduce
- create rust project depending on net
- try to get autocompletion for [`MutableIpv4Packet`](https://docs.rs/pnet/0.28.0/pnet/packet/ipv4/struct.MutableIpv4Packet.html) (or any other `#[packet]` created struct )(either use or just using it, both failes)

**Comment by dima74** [comment]
@Kloenk please enable `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` [experimental features](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features), it should work
