### ISSUE TITLE
Plugin stop working after upgrading CLion to 2021.2

### ISSUE THREAD

**Issue by cuonglm** [intellij-rust/intellij-rust#7612]
## Environment

* **IntelliJ Rust plugin version:** 0.4.151.3997-211
* **Rust toolchain version:** Not relevant
* **IDE name and version:**
```
CLion 2021.2
Build #CL-212.4746.93, built on July 27, 2021
...
Runtime version: 11.0.11+9-b1504.13 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2000M
Cores: 8
Registry: run.processes.with.pty=TRUE
```

* **Operating system:** MacOS BigSure 11.5 M1

## Problem description

After upgrading CLion to 2021.2, the plugins how error:

```
Incompatible: requires IDE build 211.* or later
```

## Steps to reproduce

Upgrading CLion to 2021.2

**Comment by lancelote** [comment]
It is probably [IDEA-274852](https://youtrack.jetbrains.com/issue/IDEA-274852). The problem was fixed on the marketplace side, please perform `Help | Check for Plugin Updates/Check for Updates`. Has it helped?

**Comment by cuonglm** [comment]
> It is probably [IDEA-274852](https://youtrack.jetbrains.com/issue/IDEA-274852). The problem was fixed on the marketplace side, please perform `Help | Check for Plugin Updates/Check for Updates`. Has it helped?

I did check for updates last night but nothing available.

Works now! Thanks!
