### ISSUE TITLE
Import suggestions displayed incorrectly

### ISSUE THREAD

**Issue by magnusja** [intellij-rust/intellij-rust#7623]
## Environment

* **IntelliJ Rust plugin version:** 0.4.152.5026-212
* **Rust toolchain version:** 1.56
* **IDE name and version:** IntelliJ #IU-212.4746.92
* **Operating system:** MacOS Catalina or sth like that, also got it on Archlinux

## Problem description

I have structs with the exact same name in different modules, when I press `ALT+Enter` to show import suggestions it is not correctly displaying the module. Module is always the same, but if I choose one to import the other module is actually used for import depending what I choose. This is super annoying because I never know which is which.

<img width="608" alt="Screenshot 2021-08-04 at 13 19 01" src="https://user-images.githubusercontent.com/1659457/128172406-2b674f82-5ffe-4223-88c5-3c7f580143a5.png">

**Comment by vlad20012** [comment]
Duplicate #7609
There is a workaround, see [the comment](https://github.com/intellij-rust/intellij-rust/issues/7609#issuecomment-891879605).
