### ISSUE TITLE
"Nest use statements" doesn't preserve inline comments locations

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#7629]
## Environment

* **IntelliJ Rust plugin version:** 0.4.153.4027-212-nightly
* **Rust toolchain version:** 1.56.0-nightly (492723897 2021-07-29) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.3 EAP (CL-213.1988)
* **Operating system:** macOS 11.4
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Inline comments location for `use` statements is not preserved upon invoking "Nest use statements". Not sure how popular this usecase is so please feel free to ignore if it is a bad practice.

P.S.: relevant PR #7339.

## Steps to reproduce

Invoke "Nest use statements" on the following code

```rust
use std::fmt::Debug; // debug
use std::hash::Hash; // hash

fn main() {
    println!("Hello, world!");
}
```

Actual result

```rust
// debug
use std::{
    fmt::Debug,
    hash::Hash
};  // hash

fn main() {
    println!("Hello, world!");
}
```

Expected result

```rust
use std::{
    fmt::Debug, // debug
    hash::Hash  // hash
};

fn main() {
    println!("Hello, world!");
}
```

**Comment by Kobzol** [comment]
Hmm. To be honest, I'm not sure how hard we should try to preserve everything here. I think that this use case is not very common, but mainly I'm not sure if we can make this fully general. Even if we implemented support for this particular case, I suppose that it would be easy to find a "counter-example" that splits the comments in a way that seems weird to some user.

What should happen in this case?
```rust
use std::fmt::{Debug, Display}; // A
// B
use std::hash::{Hash, H2}; // C
```
Currently the comment is deleted. Should it be put in between the nested items? Or below the created nested group?

A similar situation happens with flattening
```rust
use std::fmt::{Debug, Display/*invoke flatten*/}; // debug
//v
use std::fmt::Debug;
use std::fmt::Display;
// debug
```
Should the comment be duplicated? Put to first/last element?

If you want, I can fix this case, but it seems to me that it's an uphill battle :D

**Comment by lancelote** [comment]
OK, I see, let me close it for now then. If there will be more similar reports we can reopen it.
