### ISSUE TITLE
IDEA build support

### ISSUE THREAD

**Issue by aplatypus** [intellij-rust/intellij-rust#764]
Plug in Version: 0.1.0.1129
## IDEA version:  2016.2.5

I am having a variety of problems with the build IDEA menu.  As far as I can tell the issue seems to be that IDEA believes that Rust is a java project.

I understand making an IDEA plugin is a long-term process but it might be a good thing to have a readme with information about what bits of the  IDEA UI work and are not yet working.  It is just asking for an SDK.

Run is just using the Cargo run command.  That is fine, why can't it use cargo for the make and build functions until something better comes along?

That's all.  I just want to record a plea for documenting what doesn't yet work, it could have saved me a night of investigation looking  for things that I shouldn't expect to work.

Keep up the good work.

... will

**Comment by xilec** [comment]
Actually, on the main page of this repository there is link https://intellij-rust.github.io/. And more detailed features is described [here](https://intellij-rust.github.io/features/).

**Comment by aplatypus** [comment]
Thanks for that, I obviously missed the point that said, "`Build menu not supported`".

As a long time IDEA user off and on, one is used to an expected workflow.  The best thing about IDEA is that everything works together beta software and bugs aside, it is a good platform for that reason.

That's why I feel that it is important to point-out when an add-on to the normal environment _diverges_ from the _expected workflow_.  Alas neither of those two links mention the lack of build menu support.  The comment on the features page seems to use RUN as the _build command_.  Since it runs cargo.

An odd choice of semantics imho.  Run cargo is more like `gradle build` or `make all`, as I see things.  One day, if the language becomes common-use people will need to **build** large applications from components and **run** different programs/applications, services, tools, etc individually.  As I said, the great thing with IDEA is they have a good solid practical model about development workflow and tooling.

**Comment by kcauchy** [comment]
Duplicate issue:  #736

**Comment by matklad** [comment]
@aplatypus Yep, this is a known plain point :( Unfortunately, I don't see an obvious way to fix it right know. I've left a more thorough comment on https://github.com/intellij-rust/intellij-rust/issues/736#issuecomment-257270870.

Closing as a duplicate.
