### ISSUE TITLE
Cannot differentiate completion items

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [intellij-rust/intellij-rust#7648]
## Environment

* **IntelliJ Rust plugin version:** 0.4.152.4026-212
* **Rust toolchain version:** `rustc 1.54.0 (a178d0322 2021-07-26)`
* **IDE name and version:** IntelliJ IDEA 2021.2 (Ultimate Edition) Build #IU-212.4746.92, built on July 27, 2021
* **Operating system:** Windows 10 10.0

## Problem description
Cannot differentiate completion items

## Steps to reproduce
0. `cargo new project1`
1. Add `read_input = "0.8.4"` and `"eyre = "0.6.5"` to `Cargo.toml`
2. Open `main.rs` and add
```rust
fn main() -> eyre::Result<()> {
    let input = input::<u32>().get();

    Ok(())
}
```
3. Move the cursor on `input` and press <kbd>alt+enter</kbd>, you see this
![image](https://user-images.githubusercontent.com/39968/128710730-90d1b10b-67a7-490d-a742-460133fbfc8e.png)
4. Select "Import" and press <kbd>enter</kbd>, you see this
![image](https://user-images.githubusercontent.com/39968/128709710-8aabe7ec-2b4e-4da7-90ed-1a9e4d704a87.png)

Now as you can see, the suggested 2 items are from different places (same crate in this example) but we can't differentiate them. Is it possible to add the full path like `read_input::shortcut::input` or `read_input::prelude::input` to the suggestion so that we know which is which? Thanks.

**Comment by vlad20012** [comment]
Duplicate #7609
There is a workaround, see [the comment](https://github.com/intellij-rust/intellij-rust/issues/7609#issuecomment-891879605).
