### ISSUE TITLE
Infer types of closure parameters from function signature

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#765]
It would be powerful to infer the types of parameters for closures based upon the functions that they are passed into (though I can only imagine this is complex).  It would make it very powerful to write closures having autocomplete/checking on the parameter types.

Consider the following code:

```toml
[package]
name = "rust_test"
version = "0.1.0"
authors = ["johnthagen <johnthagen@gmail.com>"]

[dependencies]
piston_window = "0.56.0"
```

```rust
extern crate piston_window;

use piston_window::{clear, PistonWindow, rectangle, WindowSettings};

fn main() {
    let title = "Hello Piston!";
    let mut window: PistonWindow = WindowSettings::new(title, [640, 480])
        .exit_on_esc(true)
        .build()
        .unwrap_or_else(|error| { panic!("Failed to build PistonWindow: {}", error) });

    while let Some(event) = window.next() {
        // Function signature:
        // pub fn draw_2d<E, F, U>(&mut self, e: &E, f: F) -> Option<U>
        //     where W: OpenGLWindow, E: GenericEvent, F: FnOnce(Context, &mut G2d) -> U
        window.draw_2d(&event,
                       |context, // Infer context as `Context`
                        graphics| {  // Infer graphics as `&mut G2d`
                           clear([0.0, 0.0, 0.0, 1.0], graphics);
                           rectangle([1.0, 1.0, 1.0, 1.0],
                                     [50.0, 50.0, 100.0, 100.0],
                                     context.transform,
                                     graphics);
                       });
    }
}
```

**Comment by marhoily** [comment]
Is implementing this far off? I'm seeing stuff in weekly updates that is hardly comparable in importance to this and I wonder...

**Comment by matklad** [comment]
@marhoily it's moderately remote at the moment. Providing a proper type inference is really tricky, especially given that Rust uses a rather specialized and undocumented type inference algorithm (it's not pure HM because of the method resolution). And it's also not clear yet if it would be possible to use RLS for type inference... 

It will be definitely implemented eventually though!

**Comment by matklad** [comment]
Works now!

![completion](https://user-images.githubusercontent.com/1711539/28785647-aded5cca-761f-11e7-9488-aa732dfbd55e.png)

Kudos to @vlad20012 !
