### ISSUE TITLE
Missing most IntelliJ-Rust features when injecting Rust code via Jetbrains plugin

### ISSUE THREAD

**Issue by AzureMarker** [intellij-rust/intellij-rust#7655]
## Environment

* **IntelliJ Rust plugin version:** 0.4.152.4026-212
* **Rust toolchain version:** 1.53.0
* **IDE name and version:** IntelliJ IDEA 2021.2 CE
* **Operating system:** Fedora 34

## Problem description
Hello, I'm working on a plugin for [LALRPOP], a parser-generator for Rust: https://github.com/Mcat12/intellij-lalrpop
Part of the plugin involves injecting Rust code into the grammar file, like so:
![image](https://user-images.githubusercontent.com/4417660/128794168-84227be1-6ae9-48bc-aee3-6613384307b7.png)

I previously opened an issue about injecting Rust code and got a great response: #6026. After that issue everything worked! Unfortunately, now I'm running into issues during the update to 2021.2 (which may also apply to 2021.1 and 2020.3.4, not sure how far back it goes).

After updating my plugin to work with 2021.2 and the latest version of the Rust plugin, I only get partial support from the Rust plugin:
![Screenshot from 2021-08-09 18-15-07](https://user-images.githubusercontent.com/4417660/128794410-5b29e67b-37c5-41ef-8948-62d9d2670122.png)
![Screenshot from 2021-08-09 18-14-43](https://user-images.githubusercontent.com/4417660/128794415-d615f34b-a49a-4b57-b7d5-e7b67a72cda2.png)

If you activate auto-complete, it seems to know what is in scope, but everything else seems to be broken (smart syntax highlighting, go-to-definition, etc).

I've done some debugging by looking at the calls to `setContext`, which is supposed to (afaik) put all of the injected Rust code into the context that I want, namely as if it was included in another file. I call it here: https://github.com/AzureMarker/intellij-lalrpop/blob/0c01823f13acb82c2c42240ff02bd17d1af53836/src/main/kotlin/com/mdrobnak/lalrpop/injectors/RustInjectHack.kt#L31
The module I want to inject the code into and the code itself (from `psi`/`child`) looks good. Maybe something changed in the internals of intellij-rust?

## Steps to reproduce
1. Install the Rust plugin
2. Install v0.2.5 of the intellij-lalrpop plugin
3. Open a project with a lalrpop grammar file, example (`mips-assembler/src/parser.lalrpop`):
    https://github.com/AzureMarker/mips
4. Try interacting with the injected Rust code.

[LALRPOP]: https://github.com/lalrpop/lalrpop

**Comment by AzureMarker** [comment]
Did some testing to try and bisect when this stopped working. It looks like it stops working (by default) in the transition from intellij-rust 0.3 to 0.4 (release 147). This is when the new name resolution engine got enabled by default. Disabling the new engine makes everything work again, at least until version 157.

| IntelliJ version | intellij-lalrpop version | intellij-rust version | New name resolution engine? | Works? |
| -- | -- | -- | -- | -- |
| 2020.2 | 0.2.3 | 0.3.140.3644-202 | Default (No) | Yes |
| 2020.3 | 0.2.3 | 0.4.148.3911-203 | Default (Yes) | No |
| 2020.3 | 0.2.3 | 0.3.146.3826-203 | Default (No) | Yes |
| 2020.3 | 0.2.3 | 0.4.147.3871-203 | Default (Yes) | No |
| 2020.3 | 0.2.3 | 0.4.147.3871-203 | No | Yes |
| 2021.2 | 0.2.7 | 0.3.146.3826-211 | Default (No) | Yes |
| 2021.2 | 0.2.7 | 0.4.148.3911-212 | Default (Yes) | No |
| 2021.2 | 0.2.7 | 0.4.148.3911-212 | No | Yes |
| 2021.2 | 0.2.7 | 0.4.152.4026-212 | No | Yes |
| 2021.2 | 0.2.7 | 0.4.154.4085-212 | No | Yes |
| 2021.2 | 0.2.7 | 0.4.155.4114-212 | No | Yes |
| 2021.2 | 0.2.7 | 0.4.156.4145-212 | No | Yes |
| 2021.2 | 0.2.7 | 0.4.157.4174-212 | Yes & No | No |
| 2021.2 | 0.2.7 | 0.4.160.4261-212 | Yes & No | No |

Language injection does work though if you disable the new name resolution engine in 0.4 releases, at least up to version 156. Once the setting checkbox to disable the new name engine was removed in 157, it stops working even if you use the experimental feature to disable the new engine.

**Comment by AzureMarker** [comment]
@vlad20012 I've been poking around the intellij-rust codebase trying to find a way of telling the new name resolution engine that the code snippets in my LALRPOP files are children of the parser mod. Previously I was able to just use `setContext`, when the name resolution was bottom-up. Now that it's top-down it doesn't seem to recognize the code snippets are part of the same crate (the parser mod needs to be updated with knowledge of new children I think).

There is still some code in intellij-rust that uses `setContext`, so I thought to see if that code does something special. The example I found does not sadly:
https://github.com/intellij-rust/intellij-rust/blob/304b4e2c4ca359ba8f59b9abdcee73dfad16d718/src/main/kotlin/org/rust/ide/utils/import/importUtils.kt#L231

I also experimented with trying to modify the stub children of the parser module, but without success. Any ideas?

**Comment by vlad20012** [comment]
I have an idea, but it's too hard to explain (because the new name resolution is a really complex thing).
I will try to fix this

**Comment by vlad20012** [comment]
I think now it should be enough to rename the fake mod from `__intellij_lalrpop` to `__tmp__` (see `TMP_MOD_NAME` in `RsCodeFragmentFactory.kt`).

**Comment by AzureMarker** [comment]
Thanks @vlad20012! That seems to have fixed the problem again. I published [0.2.12](https://github.com/AzureMarker/intellij-lalrpop/releases/tag/v0.2.12), which should be available once JetBrains reviews the update.
