### ISSUE TITLE
Console-output encoding problems (UTF-8)

### ISSUE THREAD

**Issue by Philipp91** [intellij-rust/intellij-rust#766]
I execute this in my UTF-8 encoded source file:
`println!("Test äöüß");`
On my system console, the output is fine. In IntelliJ, I get this instead:
`Test Ã¤Ã¶Ã¼ÃŸ`
This output are the proper UTF-8 bytes, but interpreted as latin-1 (see http://www.ltg.ed.ac.uk/~richard/utf-8.cgi?input=%C3%A4&mode=char).

**Comment by mkaput** [comment]
If you're using Windows (and I believe so, as it's the only OS I'm aware of which doesn't use utf-8), I believe you have to change terminal code page, see: http://stackoverflow.com/questions/1259084/what-encoding-code-page-is-cmd-exe-using

**Comment by Philipp91** [comment]
Indeed, my "chcp" outputs code page 850 latin-1. Apparently (http://stackoverflow.com/questions/388490/unicode-characters-in-windows-command-line-how#comment10782008_388500) UTF-8 code page 65001 can cause different problems? Could I change it only for IntelliJ?

I'm also using other programming languages in the same IntelliJ installation and in PhpStorm (namely Java, PHP and JavaScript). All of them seem to use the same output panel in the IDE and none of them has encoding issues when outputting special characters from unit tests and other runnable scripts, all of which are stored as UTF-8. Maybe they have a different kind of workaround? So I agree that this is a platform issue, but it might be fixable by a workaround in the plugin or by changing some configuration in the plugin, which would lead to a better user experience than everyone googling this issue and then reading up on and fiddling with chcp.
From a PHP script, for example, I'm able to output even Chinese characters, which are definitely not part of code page 850. So the output must be using UTF-8 somehow, instead of converting to latin-1, even though it's being displayed in the IntelliJ console on Windows where chcp is set to 850.

**Comment by Philipp91** [comment]
Thanks a lot! I can confirm that this works.
