### ISSUE TITLE
Add "switch order of trait bounds" intention

### ISSUE THREAD

**Issue by afetisov** [intellij-rust/intellij-rust#7661]
I propose an intention which switches trait bounds. It should be as simple as switching operands of the binary operator `+`, but the `+` in trait bounds isn't treated as an operator. Specifically, the semantics should be as follows:

```rust
// input
fn foo<T: Clone + Ord /*caret*/+ ?Sized>() {}

// output
fn foo<T: Clone + ?Sized /*caret*/+ Ord>() {}
```

```rust
// input
impl<'a, T> Foo<'a, T>
    where T: IntoIterator /*caret*/+ 'a,
{ /* pass */ }

// output
impl<'a, T> Foo<'a, T>
    where T: 'a /*caret*/+ IntoIterator,
{ /* pass */ }
```

```rust
// input
fn foo(x: &dyn Send +/*caret*/ for<'a> Iterator<Item=&'a u32>) {}

// output
fn foo(x: &dyn for<'a> Iterator<Item=&'a u32> +/*caret*/ Send) {}
```

**Comment by dima74** [comment]
There are actions "Move element left"/"Move element right" (<kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>Alt</kbd><kbd>→</kbd>) which can be used for same purpose (cursor should be at one of trait bound)

**Comment by Undin** [comment]
I close the issue since it's already implemented
