### ISSUE TITLE
alt+enter has no effects

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#7684]
## Environment

* **IntelliJ Rust plugin version:** 0.4.154.4050-212-nightly
* **Rust toolchain version:** rustc 1.56.0-nightly (5a19ffe1c 2021-08-13)
* **IDE name and version:** Clion 2021.2
* **Operating system:** Archlinux

## Problem description
in the pass, press `alt+enter` for a variable, there will be a menu like 
![image](https://user-images.githubusercontent.com/10096425/129473495-1185e903-589f-499d-b113-528dc509b5d6.png)
, but now press `alt+enter`, nothing happend.
That makes me hard to import struct or crate, because I need to use the mouse to click it

I have tested in Goland to make sure the shortcuts key is not bind by another program

## Steps to reproduce
1. write something like `Error::new()`, the `Error` will become red.
2. press `alt+enter` for the `Error`, nothing happened.

**Comment by mattsse** [comment]
Same on Mac.
upgraded to latest clion, still there.
This is also not limited to rust files. Created a dummy JS file and alt+enter does nothing there as well.

**Comment by vlad20012** [comment]
I can't reproduce it using exactly the same versions of the Rust plugin, CLion, and `rustc 1.56.0-nightly (2d2bc94c8 2021-08-15)`. But I use Ubuntu, not Archlinux.

**Comment by vlad20012** [comment]
Ok, I've reproduced

**Comment by mili-l** [comment]
@Sherlock-Holo @mattsse Could you add https://plugins.jetbrains.com/plugins/nightly/8195 to `Custom Plugin Repositories` for Toml plugin and Update it
<img width="630" alt="Screenshot 2021-08-16 at 10 06 02" src="https://user-images.githubusercontent.com/1213122/129531827-16c099e0-b3a4-4342-a2a8-e39f75582adf.png">

**Comment by Sherlock-Holo** [comment]
> @Sherlock-Holo @mattsse Could you add https://plugins.jetbrains.com/plugins/nightly/8195 to `Custom Plugin Repositories` for Toml plugin and Update it
> <img width="630" alt="Screenshot 2021-08-16 at 10 06 02" src="https://user-images.githubusercontent.com/1213122/129531827-16c099e0-b3a4-4342-a2a8-e39f75582adf.png">
> 

I installed the nightly toml, and problem solved
Could you tell me when the stable toml plugin can fix the problem too？

**Comment by Undin** [comment]
@Sherlock-Holo the latest Rust plugin should work properly with stable Toml plugin
