### ISSUE TITLE
Invalid iterator type resolution

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#7689]
## Environment

* **IntelliJ Rust plugin version:** 0.4.153.4056-212
* **Rust toolchain version:** 1.56.0-nightly (08095fc1f 2021-07-26) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.2 (CL-212.4746.93)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

After updating to the new version, types inferred from iterators use the type alias, instead of the actual type, which means it's always `Item`. In the given example, the type should be `Member`.

![image](https://user-images.githubusercontent.com/1268573/129684596-17c83937-1ac4-4482-a4f7-37b25b9c6f91.png)

## Steps to reproduce

Use `iter()` on any collection and find any element. See how the plugin resolves the resulting type.

**Comment by Kobzol** [comment]
The plugin now tries to print more things with their aliased name, but auto-completion, type inference etc. should still work for `new_owner`, is that so? Or are these things broken?

@vlad20012 Maybe in some cases it would be better to unwrap the alias, but I'm not sure what the rules should be.

**Comment by krojew** [comment]
In such cases the alias should definitely be unwrapped. Having all types named `Item` when using iterators doesn't add much value. I'm not sure using aliases in those grey hints at all is a good approach, since we're usually more interested in the actual type, not some internal alias.

**Comment by vlad20012** [comment]
@Kobzol I think associated types should be always unwrapped, maybe we just shouldn't fill `aliasedBy` in the case of an associated type.

Btw where this bug was introduced? Is it #7635 or #7521? Looks like they shouldn't have led to this.

**Comment by Kobzol** [comment]
I'm not sure, I'll try to bisect it. Interesting that it doesn't happen for `into_iter`:
```rust
let items = vec!(1, 2, 3);
let items2 /*Item*/ = items.iter()
    .find(|x| x == 1)
    .unwrap();

// vs
let items = vec!(1, 2, 3);
let items2 /*u32*/ = items.into_iter()
    .find(|x| x == 1)
    .unwrap();
```

**Comment by Kobzol** [comment]
What's even weirder is that in `RsInlayTypeHintsProviderTest` it shows `&u32` instead of `Item` :)

**Comment by vlad20012** [comment]
There is a possibility that this bug has existed for a long time, and we just escalated it by extending aliases to all types

**Comment by Kobzol** [comment]
It has regressed in https://github.com/intellij-rust/intellij-rust/pull/7521. I created a fix, although there are some issues (let's discuss in the [PR](https://github.com/intellij-rust/intellij-rust/pull/7692)).
