### ISSUE TITLE
Tuples do not show the correct type

### ISSUE THREAD

**Issue by joshuataylor** [intellij-rust/intellij-rust#7699]
## Environment

* **IntelliJ Rust plugin version:** 0.4.153.4056-212
* **Rust toolchain version:** rustc 1.56.0-nightly (30a0a9b69 2021-08-17)
* **IDE name and version:** CLion CL-212.4746.93 (built on July 27, 2021)
* **Operating system:** Archlinux

## Problem description
Tuples do not show the correct type nor have their type work.

Example project here: https://github.com/joshuataylor/bevy_example_split

Screenshots (sorry):
CLion:
![2021-08-18_14-45](https://user-images.githubusercontent.com/225131/129850753-0ebd7891-1319-4ad6-8ce6-8a2ee01e961c.png)

VSCode (rust analyser) works:
![2021-08-18_14-43](https://user-images.githubusercontent.com/225131/129850527-ed6e50fd-4a4c-426f-b704-f79be5531584.png)

## Steps to reproduce

1. Clone https://github.com/joshuataylor/bevy_example_split
2. Open `src/main.rs`
3. See that it does not have a typehint

**Comment by Undin** [comment]
Reproduced with nightly rust toolchain.
But it works with stable one

**Comment by neonaot** [comment]
It seems like I have same problem in IDEA with stable rust toolchain:
<img width="822" alt="image" src="https://user-images.githubusercontent.com/49211026/129856380-cb09c60e-d5bc-4537-b8ce-5c5aa07ecd14.png">
* **IntelliJ Rust plugin version:** 0.4.153.4056-212
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.2 Ultimate Edition (IU-212.4746.92)
* **Operating system:** macOS 11.4
* **Macro expansion engine:** new
* **Name resolution engine:** new

In CLion, hints work. In both IDEs all hints are switched on.
<img width="818" alt="image" src="https://user-images.githubusercontent.com/49211026/129856829-cb3f8559-e09c-4469-8465-45e7915652a7.png">
* **IntelliJ Rust plugin version:** 0.4.153.4056-212
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.2 (CL-212.4746.93)

**Comment by SonicZentropy** [comment]
I am having the same issue and purely switching to Stable toolchain wasn't enough to fix it.  I also had to Invalidate Caches in Intellij and restart, at which point my type hints came back normally.

I'm having a further problem though where it doesn't seem to understand that f32 primitives impl Copy, and is flagging them all as being moved.  I'm not sure if it's related or not, so I may need to make a new issue instead,  but it **only** occurs in this same area of code related to bevy's iter tuple methods.

Here's a minimal example of it occurring on Windows 10, Stable toolchain, most recent Intellij + Rust plugin:
![ExamplePicture](https://i.imgur.com/toOHUen.jpeg)

**Comment by Undin** [comment]
@MrGVSV Just want to note that it's not necessary to restart your IDE. Just invoke `Refresh Cargo Projects` action in Cargo tool window
![image](https://user-images.githubusercontent.com/2539310/139522591-8db503a8-881e-4641-8a41-82a5203dfac2.png)

**Comment by ChristianIvicevic** [comment]
> Try to enable `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` experimental feature via the corresponding dialog. To open the dialog, just invoke `Help | Find Action` action and type `Experimental features`

This has actually fixed other issues as well such as `query.iter()` not appearing in code completion.

**Comment by tgrkzus** [comment]
Those experimental features worked for me for a while - but seem to not work on recent version of Rust. Downgrading to Rust 1.62 seemed to have brought them back to working. If anyone runs into the same problem.
