### ISSUE TITLE
Trait and derive macro share the same name. In `#[derive(Name)]` is highlighted as function and causes autocompletion to stop working

### ISSUE THREAD

**Issue by eliaperantoni** [intellij-rust/intellij-rust#7707]
## Environment

* **IntelliJ Rust plugin version:** 0.4.153.4056-211
* **Rust toolchain version:** 1.56.0-nightly
* **IDE name and version:** CLion 2021.1.2
* **Operating system:** Arch Linux x86_64

## Problem description

A crate of mine exports a trait and a derive macro. They are both imported with `use raven_ecs::Component`, similarly to how `use serde::Serialize` would bring into scope both the trait and the derive macro.

But when I do `#[derive(Component)]` CLion highlights `Component` as a function instead of a trait, this is something that doesn't happen with Serde's `Serialize`.

![image](https://user-images.githubusercontent.com/6002855/129909543-ff39b942-01f1-4390-8509-36947888a711.png)

The issue with that is I have an `impl<T: Component> Query for (T,) {}` and CLion doesn't autocomplete methods from that trait. Although it "recognizes its error" as I manually give the name of the method:

![image](https://user-images.githubusercontent.com/6002855/129909991-d521a797-d46e-46aa-9975-42975234ebe2.png)

![image](https://user-images.githubusercontent.com/6002855/129910039-dfc11b3e-b463-4841-9d09-1c9f7aba05d9.png)

If I manually do `impl Component for MyComponent` then the autocompletion works. That's why I think the root cause is CLion trating `Component` primarily as a macro. I'm not sure why it doesn't do that with Serde.

I should mention that the code compiles and runs fine.

## Steps to reproduce

The repo is publicly avaiable [here](https://github.com/eliaperantoni/raven).
The `#[derive(...)]` line is [here](https://github.com/eliaperantoni/raven/blob/master/raven_ecs_example/src/main.rs#L5).

The repo is structured as a workspace. The interesting crates for this issue are:
+ `raven_ecs`: A library that provides various items. It defines the `Component` trait and the `Query` trait that implements itself for all `(T,) where T: Component`. The `Query` trait has methods (such as `query_shallow`) that don't get autocompleted.
+ `raven_ecs_proc`: Contains just a `#[proc_macro_derive(Component)]`. Crate `raven_ecs` lists this as one of its dependencies and re-exports the macro with `pub use raven_ecs_proc::Component`. As far as I can tell this is pretty much what Serde does.
+ `raven_ecs_example`: Showcases the usage of `raven_ecs`, including the derive macro.

**Comment by vlad20012** [comment]
`Component` in `#[derive(Component)]` is not a trait, it's procedural macro (i.e. a function). `Serialize`/Deerialize will also resolve to procedural macros in the future, currently this can be considered as a bug.
I.e. the bug is a reverse thing - that `Serialize` is not highlighted as a function

**Comment by vlad20012** [comment]
Missing autocompletion is also a (known) bug

**Comment by eliaperantoni** [comment]
Thank you @vlad20012, I thought there was something wrong with my macro. I can live with the missing autocompletion.

Out of curiosity: may I ask why `Serialize`/`Deserialize` are treated differently to my trait/macro?

**Comment by vlad20012** [comment]
`Serialize`/`Deserialize` are hardcoded in the plugin (see [KnownDerivableTrait](https://github.com/intellij-rust/intellij-rust/blob/e6812294b03b1d27537398d709bd8dcdcf0d09a2/src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt#L191))

**Comment by eliaperantoni** [comment]
Ah I see, thank you very much for the insight!
