### ISSUE TITLE
Massive amount of macro.dll are created

### ISSUE THREAD

**Issue by tyhi** [intellij-rust/intellij-rust#7709]
## Environment

* **IntelliJ Rust plugin version:** 0.4.153.4045-212
* **Rust toolchain version:** 1.56.0-nightly (rustc 1.56.0-nightly (0fa319039 2021-08-12)
* **IDE name and version:** Clion 2021.2
* **Operating system:** Windows 11 (22000.132)

## Problem description
I'm guessing that this is from CLion but maybe I'm wrong and it's from rustc itself in which case this can be closed, and I can report there.

While working with the sqlx crate I noticed Clion having issues with saving when I checked my entire disk was filled with sqlx-macros.dll, about 6.2k of them totaling 70GB.

![image](https://user-images.githubusercontent.com/31829732/130002062-5ccdfbf1-6124-492e-ada0-8f6929967b59.png)

I have the experimental engine enabled along with proc macros.

## Steps to reproduce

Not sure at what point caused this but I was mostly using sqlx::query! macros and in one instance had 7 macros each with 7-12 parameters which did seem to be putting a toll on Clion.

**Comment by vlad20012** [comment]
It's definitely CLion, not Rustc
