### ISSUE TITLE
Autocompletion does not work when files use include!

### ISSUE THREAD

**Issue by raphaelcohn** [intellij-rust/intellij-rust#771]
I'm working with a very large code base that uses `include!` to break up modules that otherwise would be excessively large. We also use it to make sure our code is well organized, with a file-per-major item pattern (a struct, a pub fn, a pub type, that sort of thing). It make finding things a snap - find, TextMate cmd-T, etc. And it works with intellij-rust too - Cmd-N is wonderful.

What doesn't work is autocompletion. Autocompletion works perfectly for things in the stdlib. And within a file referencing other items. But not across files. Likewise, find usages does not work, either, and we're not confident refactor change name will. For us, this is a major reason to use an IDE.

(We realise we're not doing things "The Rust Way", but the "Rust Way" for modules doesn't scale. It's an anti pattern. It's more code, and it creates more collisions that need not occur when many developers are at work on a code base. And the the file system does not represent the contents. A million and one mod X / pub use X aren't appropriate, along with all the duplicated use X  statements that creates).

**Comment by DGolubets** [comment]
While I don't agree with using include this way, I stumbled across a library that used it (and it has just 6 modules overall.. a joke, right?) and it's totally of the grid for autocomplete.

**Comment by Techcable** [comment]
More importantly, this allows using generated code like [bindgen ffi bindings](https://github.com/servo/rust-bindgen). Normally I can sacrifice features like macros for the autocomplete productivity gains, but bindgen is so useful I can't go without it. It'd be awesome if this worked for this use case.

**Comment by Ekranos** [comment]
Is there any update on this? Since I got the same problem and this issue is open since Nov 2016.

Also I have to agree that the Rust module way just doesn't really scale. I am working on a project with ~150 structs in one module (and yes, they belong this tightly together...) and it would be a blessing to be able to split them into multiple files while retaining autocomplete.

And including generated bindings which get completed would be really great too.

**Comment by raphaelcohn** [comment]
@Techcable You might like my tool [bindgen-wrapper](https://github.com/lemonrock/bindgen-wrapper) that makes extensive use of include! to make FFI bindings intelligible... An example in use are the bindings for ucx-sys in [ucx](https://github.com/lemonrock/ucx).

**Comment by dweidenfeld** [comment]
Well this is also a problem for other *gen tools like: https://github.com/jsgf/rust-xdr/tree/master/xdrgen

**Comment by raphaelcohn** [comment]
@dweidenfeld Cool - I didn't know of xdrgen. Thanks!

**Comment by raphaelcohn** [comment]
Ok, this is starting to get a little annoying now that the latest build has a banner "File is not included in module tree, analysis not available".

if there's no intention to sort this in the medium term, could we ***PLEASE*** have a way to disable or dismiss this banner. It takes up valuable screen real estate and also eye line - it's very distracting when working on code.

**Comment by Undin** [comment]
@raphaelcohn Could you describe how do you use `include` macro in your project?
I've created #3935 that implements initial support for `include` macro. All restrictions of the implementation described in the PR

**Comment by raphaelcohn** [comment]
An example project might be <https://github.com/lemonrock/dpdk> with, for example a module such as <https://github.com/lemonrock/dpdk/tree/master/workspace/dpdk-bus/src/pci> (this is the `pci` module in the crate `dpdk-bus`).

The `mod.rs` file shows how I make use of `include!`: <https://github.com/lemonrock/dpdk/blob/master/workspace/dpdk-bus/src/pci/mod.rs>.

Autocompletion should then work in, say, `DpdkPciBus.rs`, picking up the `use super::*` statements in `mod.rs`, etc.

An example of a project using derived C code bindings might be: <https://github.com/lemonrock/dpdk/tree/master/workspace/dpdk-sys>; the bindings are in <https://github.com/lemonrock/dpdk/tree/master/workspace/dpdk-sys/src/bindgen>, eg <https://github.com/lemonrock/dpdk/tree/master/workspace/dpdk-sys/src/bindgen/structs>.

**Comment by raphaelcohn** [comment]
@Undin I'd be happy to test your pull request. What do I need to get a version of your code as a plugin into my IntelliJ instance?

**Comment by Undin** [comment]
@raphaelcohn Huge thanks for examples!
Looks like even the current restricted implementation should cover most cases in this repo
>  I'd be happy to test your pull request.

It would be great!
You can get plugin with changes from the PR from our public [teamcity](https://teamcity.jetbrains.com/viewLog.html?buildId=2346347&buildTypeId=IntellijIdeaPlugins_Rust_CurrentIdea_TestsRust&tab=artifacts)

**Comment by raphaelcohn** [comment]
Initial testing feedback:-

* The banner "File is not included in module tree, analysis not available" has gone. Thank you.
* Syntax highlighting works as it should
* Autocompletion works for `Self::` and `self.`. Yippee!!!
* Project pane just displays "loading..." after more than 6 minutes.
* Likewise find-file doesn't work (Cmd-N), it just displays "Searching..."
* Crumbs (?) at top still work with drop downs.

Thank you for making this patch. If it can work (even sort-of) with the project pane, so I can navigate, it would be an enormous improvement for my workflow.

**Comment by Undin** [comment]
> * Project pane just displays "loading..." after more than 6 minutes.
> * Likewise find-file doesn't work (Cmd-N), it just displays "Searching..."

@raphaelcohn Could you please re-check with the latest plugin version?
Project tree and file search shouldn't be affected by this feature and I can't reproduce these issues on my machine.

**Comment by raphaelcohn** [comment]
Now works! Thank you.

**Comment by thefallentree** [comment]
has this been released?

**Comment by Undin** [comment]
@thefallentree if the plugin recognizes where including file is located then completion works in it. All supported cases are described in #1908

**Comment by Undin** [comment]
I think it can be closed now - #1908 is enough to track the status of `include` support
