### ISSUE TITLE
Drag-and-drop moving into same directory

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#7712]
## Environment

* **IntelliJ Rust plugin version:** 0.4.153.4056-212
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.2 (CL-212.4746.93)
* **Operating system:** macOS 11.4
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
Currently, IDE allows moving a Rust file into the directory where it really is.

https://user-images.githubusercontent.com/49211026/130078398-7423b9ba-0129-4211-92be-f18ae40c846c.mov

## Steps to reproduce
1. Create a project with one or more files except main.rs and lib.rs
2. Include extra files by ```mod filename;``` into main.rs
3. Drag-and-drop allows dropping the file into a file in the same directory (it moves the first file into the directory of the second one)

**Comment by ortem** [comment]
It looks quite strange from my point of view that the problem only occurs when there are at least three files (but not two of them). @dima74 I'm wondering do you happen to know the reason for such behaviour? It is not really important I guess but I'm just curious.

**Comment by neonaot** [comment]
> problem only occurs when there are at least three files 

@ortem, sorry, it is my mistake in the description (_more than one file_), two files include `main.rs` is enough, but not only `lib.rs`+`main.rs`

**Comment by ortem** [comment]
@neonaot OK, thank you for clarifying this!
