### ISSUE TITLE
Question: will jetbrains consider releasing a rust IDE?

### ISSUE THREAD

**Issue by cyberhck** [intellij-rust/intellij-rust#7717]
As the title suggests, I was wondering if JetBrains would consider releasing a full flexed IDE, which plugins are also working, the things goland does for go, the things rider does for C#, the thing webstorm does for TypeScript are far far more than what this plugin does for Rust.

If jetbrains were to create a dedicated for Rust I think the experience to write rust would be a lot more better than today.

**Comment by Undin** [comment]
See https://github.com/intellij-rust/intellij-rust/issues/4654#issuecomment-555338092

**Comment by cyberhck** [comment]
didn't realize there was an issue, will follow up there.
