### ISSUE TITLE
Fails to detect that Eq is a sufficient trait bound to satisfy PartialEq requirement

### ISSUE THREAD

**Issue by dnut** [intellij-rust/intellij-rust#7729]
This is valid rust code that compiles without a problem, but Intellij thinks it is invalid.
```rust
struct Foo<T> {
    bar: T
}

impl<T: PartialEq> PartialEq for Foo<T> {
    fn eq(&self, other: &Self) -> bool {
        self.bar == other.bar
    }

    fn ne(&self, other: &Self) -> bool {
        self.bar != other.bar
    }
}

impl<T: Eq> Eq for Foo<T> {}
```
The last "Eq" in the above code gets marked as an error by Intellij with the message:
```
the trait bound `Foo<T>: PartialEq<Foo<T>>` is not satisfied [E0277] the trait `PartialEq<Foo<T>>` is not implemented for `Foo<T>`
```
The only way to get Intellij to stop complaining is by adding where T: PartialEq to the Eq impl. But Eq implies PartialEq so it is not necessary.

**Comment by only-rust** [comment]
I just had the same issue but with PartialOrd
