### ISSUE TITLE
Inserting code into doctest

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#7732]
## Environment

* **IntelliJ Rust plugin version:** 0.4.154.4067-212-nightly
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.2 (CL-212.4746.93)
* **Operating system:** macOS 11.4
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
Then you paste multiline fragments of code into doctest, IDE adds "//" instead of "///". Indents don't matter.

https://user-images.githubusercontent.com/49211026/130643416-72f134f7-ab3a-45ba-990a-becdc8af7ad2.mov

it also happens with simple text (not rust code):
<img width="185" alt="image" src="https://user-images.githubusercontent.com/49211026/130676381-9b2e016b-8949-4128-921f-1c33d55ea85a.png">

## Steps to reproduce
1. Copy two or more lines
2. Insert them into doctest

```rust
fn a(){
    let b = 566;
    let d = 78;
}
///
/// ```
///use sandbox::add;
///let a = add(3, 2);
///
///assert_eq!(a, 5);
/// ```
pub fn add(a: i32, b: i32) -> i32 {
    a + b
}
```

**Comment by Kobzol** [comment]
I think that this is a duplicate of https://github.com/intellij-rust/intellij-rust/issues/3649.

**Comment by neonaot** [comment]
> I think that this is a duplicate of #3649.

Yes, exactly :flushed:
