### ISSUE TITLE
Generating constructor omits paths to symbols

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#7739]
## Environment

* **IntelliJ Rust plugin version:** 0.4.153.4056-212
* **Rust toolchain version:** 1.54.0 (a178d0322 2021-07-26) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.2.1 (CL-212.5080.54)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

When generating a constructor for a struct containing members of types in the form of `path::Type`, the `path` part gets omitted.

## Steps to reproduce

Generate a constructor for given struct:

```rust
struct Request {
    data: Vec<u8>,
    stream_id: StreamId,
    handler: oneshot::Sender<Frame>,
}
```

The constructor looks like this:

```rust
impl Request {
    pub fn new(data: Vec<u8>, stream_id: StreamId, handler: ::Sender<Frame>) -> Self {
        Request { data, stream_id, handler }
    }
}
```

Note the lack of `oneshot` path.

**Comment by Kobzol** [comment]
@vlad20012 The corresponding code uses `RsTypeReference.substAndGetText`, which ends in `RsPsiRenderer::appendPathWithoutArgs`, which renders `foo::bar` as `::bar` when the `shortPaths` option is set to true. I can change the option to not use short paths, but it seems to me that the `appendPathWithoutArgs` function shouldn't append `::` if there is a qualifier and `shortPaths` is set to `true`?
