### ISSUE TITLE
Possibility to create module

### ISSUE THREAD

**Issue by torkleyy** [intellij-rust/intellij-rust#774]
It would be nice to create a module inside a directory (to create a directory and a mod.rs inside) both per Quick-fix and with the File -> New menu

**Comment by torkleyy** [comment]
I guess the current situation is good. There is a quick-fix for creating a module and if you don't have a directory already it'll convert the file to a directory with a `mod.rs`.

**Comment by matklad** [comment]
There's also expand/contract refactorings available for `mod.rs` and `foo.rs` files, though the don't deal with nested modules properly atm.
