### ISSUE TITLE
cargo build doesn't have $PATH from user

### ISSUE THREAD

**Issue by karlp** [intellij-rust/intellij-rust#7747]
## Environment

* **IntelliJ Rust plugin version:** 0.4.153.4056-212
* **Rust toolchain version:** rustc 1.54.0 (a178d0322 2021-07-26)
* **IDE name and version:** 
IntelliJ IDEA 2021.2.1 (Community Edition)
Build #IC-212.5080.55, built on August 24, 2021
Runtime version: 11.0.11+9-b1504.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.13.12-200.fc34.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 6
Non-Bundled Plugins: org.toml.lang (0.2.153.4056-212), org.rust.lang (0.4.153.4056-212)
Kotlin: 212-1.5.10-release-IJ5080.55
Current Desktop: GNOME
* **Operating system:** fedora 34

## Problem description
I have a cortex-m project with the following in my ```.cargo/config```
```
rustflags = [
  "-C", "link-arg=-Tlink.x",
   "-C", "linker=arm-none-eabi-ld",
]
```

From my terminal, ```arm-none-eabi-ld``` is available, it's my user path.
```
$ echo $PATH
/home/karlp/.cargo/bin:/home/karlp/.local/bin:/home/karlp/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
$ which arm-none-eabi-ld
~/.local/bin/arm-none-eabi-ld
$ 
```
And ```cargo build``` works.  Inside IntelliJ though, I just a "not found" error
```
error: linker `arm-none-eabi-ld` not found
  |
  = note: No such file or directory (os error 2)
```

The path inside the runner is just a ```PATH=/app/bin:/usr/bin``` which doesn't seem particularly useful...

**Comment by vlad20012** [comment]
`Cargo build` inherits environment variables from the parent process, i.e. from IntelliJ IDEA. For some reason, your IDEA process has a different PATH variable value.

**Comment by vlad20012** [comment]
Your path `/app/bin:/usr/bin` looks a little bit like IntelliJ IDEA is installed from Flatpak or a similar thing, is it so?

**Comment by karlp** [comment]
yeah, this was stupid flatpak.  I've removed it and installed it from the plain community download instead and it works now.  (at least as far as this issue is concerned!)  thanks for the help!
