### ISSUE TITLE
False positive: Use after move on Copy type

### ISSUE THREAD

**Issue by maxim-banaev** [intellij-rust/intellij-rust#7755]
## Environment

* **IntelliJ Rust plugin version:** 0.4.153.4056-212
* **Rust toolchain version:** nightly-x86_64-apple-darwin - rustc 1.56.0-nightly (5eacec9ec 2021-08-28) (also tested on stable 1.54.0)
* **IDE name and version:** CL-212.4746.93
* **Operating system:** OS Mac OS X(x86_64) v11.5.2

## Problem description

The following code does compile but is detected as an error (use after move). u32 is Copy and is not actually moved.
I have invalidated all caches, and the error persists.

`fn main() {`
`    let x = 5u32;`
`    let y = x + 1;`
`    let z = x + 2; //< Use of moved value`
`}`

## Steps to reproduce

Submitted to CLion tracker as https://youtrack.jetbrains.com/issue/CPP-26367

**Comment by mili-l** [comment]
Could you provide diagnostic data: `Help` -> `Collect Logs and Diagnostic Data`?

**Comment by redpandamonium** [comment]
Yes I can. The IDE warns it has personal information in it. I don't want to share that on github. Is there an easy way to sanitize it, or how do I submit that?

**Comment by redpandamonium** [comment]
I also want to add that creating a new project with the example code does not reproduce the error. 
What I did was replace the main function in another project. The error seems to be specific to something in that project.

**Comment by ortem** [comment]
@redpandamonium Thank you for the detailed report!

The problem is probably caused by the use of `bevy` as a dependency.
Related issue: https://github.com/intellij-rust/intellij-rust/issues/7246

**Comment by ThrashAbaddon** [comment]
I also stumbled on this one while working with `bevy`.
