### ISSUE TITLE
Cargo-expand output is illegible

### ISSUE THREAD

**Issue by mahkoh** [intellij-rust/intellij-rust#7762]
## Environment

* **IntelliJ Rust plugin version:** 0.4.153.4056-212
* **Rust toolchain version:** 1.54.0 (a178d0322 2021-07-26) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.2 (CL-212.4746.93)
* **Operating system:** Linux 5.13.10-arch1-1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

![2021-08-30-173656_647x367_scrot](https://user-images.githubusercontent.com/1882250/131365329-b047ff13-fa6b-4fe8-bf59-d2f3f02ea675.png)

## Steps to reproduce

Use the cargo expand action. The invocation seems to hard-code a theme that assumes a terminal theme with a white background (wtf?).

https://github.com/intellij-rust/intellij-rust/blob/2b54b2d26e2d6b90b51c5f7bcd6db549104c02ba/src/main/kotlin/org/rust/ide/intentions/RunCargoExpandIntention.kt#L45

**Comment by vlad20012** [comment]
Hmm, with a light IntelliJ theme, the terminal will have a white background indeed. 

We should choose Cargo-expand theme depending on a current intellij theme

**Comment by afetisov** [comment]
Why doesn't the expansion just open in a separate temporary file window? Seems like that would automatically fix the problems with the theme choice, as well as make the expansion easier to read and navigate. Personally copying cargo-expand output to a new window is the first thing I do.
