### ISSUE TITLE
Allow debugging Rust code within Node.js native extensions

### ISSUE THREAD

**Issue by vjpr** [intellij-rust/intellij-rust#7763]
## Environment

* **IntelliJ Rust plugin version:**

0.4.154.4085-211

* **Rust toolchain version:**

info: The currently active `rustc` version is `rustc 1.54.0 (a178d0322 2021-07-26)`

* **IDE name and version:**

CLion 2021.1.3

* **Operating system:**

macOS

## Problem description

I would like to use a `Custom Build Application` to run Node.js with a file that contains a Rust-based native extension and debug it.

`node foo.js`

```
# foo.js

require('target/native.node')`
```

I am using the [`napi-rs`](https://github.com/napi-rs/napi-rs) package to build the native extension.

This approach works when making a native Node extension using [`cmake-js`](https://github.com/cmake-js/cmake-js) in CLion.

I have also tried `attach to process`, and breakpoints do not fire. This again works with cmake.

I have made sure I am building the `napi-rs` binary with debug symbols enabled.

Should this work?

**Comment by vlad20012** [comment]
c.c. @ortem, @avrong

**Comment by ortem** [comment]
@vjpr Thank you for the report. I'm afraid I'm not familiar with Node.js native extensions, could you please attach an example project (a Git repo or zip file)?

Meanwhile, I'd recommend trying the following. After attaching to the process, you can [pause](https://www.jetbrains.com/help/clion/starting-the-debugger-session.html#pause) the debug session and check whether CLion is able to show the source code by using [Frames](https://www.jetbrains.com/help/clion/examining-suspended-program.html#examine-frames) tab. If you can navigate to the source code this way, you can then try to add breakpoints again and check if they are active (red) or not.

**Comment by Igosuki** [comment]
Sounds like something that would be doable using remote gdbserver execution

**Comment by vjpr** [comment]
I created a new blank `napi-rs` project, opened CLion, and it works. So it must be something to do with how the `swc` project is setup which is where I couldn't get it to work.

Working CLion project: https://github.com/vjpr/issue-napi-rs-intellij

Thanks for help. Closing.
