### ISSUE TITLE
LLDB pretty-printers for OsStr, CStr, Path do not work on Rust 1.55.0

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#7779]
## Environment

* **IntelliJ Rust plugin version:** 0.4.155.4075-212-nightly
* **Rust toolchain version:** 1.56.0-nightly (2f662b140 2021-08-29) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.2.1 (CL-212.5080.54)
* **Operating system:** macOS 11.2.3
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
LLDB pretty-printers for `OsStr`, `CStr`, and `Path` types do not work on Rust 1.56.0

**Rust 1.54.0 stable (work fine)**
<img width="741" alt="Rust 1.54.0 stable" src="https://user-images.githubusercontent.com/4854600/131844578-fdf244e3-f906-4c22-a0ec-2ae4acad9982.png">

**Rust 1.54.0 nightly (fail)**
<img width="749" alt="Rust 1.54.0 nightly" src="https://user-images.githubusercontent.com/4854600/131844583-25fe4c87-0b0e-4477-a47f-f8e920104905.png">

**Comment by Undin** [comment]
The same for rustc 1.55.0 (c8dfcfe04 2021-09-06) x86_64-apple-darwin
