### ISSUE TITLE
Improve move refactoring use path resolution

### ISSUE THREAD

**Issue by Igosuki** [intellij-rust/intellij-rust#7781]
## Environment

* **IntelliJ Rust plugin version:** 0.4.155.4086-212-nightly
* **Rust toolchain version:** rustc 1.56.0-nightly (0035d9dce 2021-08-16)
* **IDE name and version:** CLion 2021.2
* **Operating system:** Ubuntu 21.04

## Problem description
When refactoring and moving to new mods, the imports include the actual deepest place of the import, which more often than not are often private.

## Steps to reproduce
For instance use actix-web and move code to a new module file.

## My opinion for fixes
Instead of using the actual resolved path of the type in the target crate, use the first publicly accessible one by walking up the modules.

**Comment by Igosuki** [comment]
Example of imports after a move->refactoring I did today : 
```use actix::address::{Addr, MailboxError};```
It should have been :
```use actix::{Addr, MailboxError};```

The plugin also doesn't include traits like FromStr etc but that's another issue

**Comment by dima74** [comment]
@Igosuki Thanks for report!

> Example of imports after a move->refactoring I did today :
> `use actix::address::{Addr, MailboxError};`
> It should have been :
> `use actix::{Addr, MailboxError};`

Could you please provide sample code? I can't reproduce it with `actix = "0.12.0"` using code:
```rust
use actix::{Addr, MailboxError, Actor};

// move to mod foo
fn func<T: Actor>(a: Addr<T>, e: MailboxError) {}

mod foo;
```

> The plugin also doesn't include traits like FromStr etc but that's another issue

It should work, could you please also provide some sample code?

**Comment by Igosuki** [comment]
The actix move problem has disappeared with the latest version of the plugin, but here's a video to illustrate what I mean about FromStr 
![refactoring_failure_intellij](https://user-images.githubusercontent.com/406150/132984790-0f086f45-187d-4c9a-b029-eacf71c16d6a.gif)
