### ISSUE TITLE
Generate Rust types from JSON

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#7783]
It would be great to help users to generate Rust types from a given JSON object just in IDE instead of using external converters like https://transform.tools/json-to-rust-serde.

Currently, in IntelliJ ecosystem, GoLand already provides such [feature](https://www.jetbrains.com/help/go/working-with-json.html):
![](https://resources.jetbrains.com/help/img/idea/2021.2/go_converting_json_to_struct.animated.gif)

See [this](https://youtrack.jetbrains.com/issue/GO-3334#focus=Comments-27-4650182.0-0) comment from GoLand [feature request](https://youtrack.jetbrains.com/issue/GO-3334) to get some variants in what form it can be implemented

Note, golang stdlib contains json encoding/decoding functionality, so the original feature in GoLand should always work. In the case of Rust, I suppose we will have to use some external library like [serde](https://serde.rs/) but it's not a problem since serde is one of the most popular libraries in the Rust ecosystem

_Originally suggested in https://twitter.com/yoshuawuyts/status/1433368407232155653_

**Comment by Kobzol** [comment]
[This](https://github.com/intellij-rust/intellij-rust/pull/7405) could be possibly used to add `serde` to dependencies after generating the struct, if it's not already there.

**Comment by Altair-Bueno** [comment]
Definitely needed!
