### ISSUE TITLE
can't not make variable mutable quickly

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#7789]
## Environment

* **IntelliJ Rust plugin version:** 0.4.155.4094-212-nightly
* **Rust toolchain version:** rustc 1.56.0-nightly (b7404c898 2021-09-03)
* **IDE name and version:** Clion 2021.2.1
* **Operating system:** Archlinux

## Problem description
in previous versions, when I write a variable like

```rust
let a = vec![1u8];
```

the `a` is immutable, then if I want to make it mutable, I just need to move the cursor before `a` after the ` ` space, and press `m`, the plugin will display a list with an item `mut`, then I press enter, the `mut` keyword will be inserted in the correct place with correct whitespace.

for now, when I press `m`, nothing happened, I need to keeping press `ut` and the whitespace manually.

I hope you could take back this feature, it is very useful

**Comment by mili-l** [comment]
Hello, @Sherlock-Holo, sorry for this experience. For now, you could call Code Completion (Ctrl + Space) right after you pressed `m`

**Comment by afetisov** [comment]
That should probably be an intention, it would make more sense this way, would be faster and more reliable.

**Comment by Sherlock-Holo** [comment]
is it possible to let the completion list display automatically? for now it still needs press ctrl space to display the list. in the past it will display automatically after press the `m`

**Comment by vlad20012** [comment]
This regressed in #7582.

**Comment by Sherlock-Holo** [comment]
because we only have `let` postfix completion and it always generate immutable variable, we won't add mut keyboard every times after created the variable
for example
```rust
let buf = vec![0; 4096];
reader.read_extually(&mut buf)?;
```

now clion will report buf should be mutable.
let's move cursor to the buf variable.
if supports display the completion list automatically after press m, we just need to press m and enter to choose the mut item.
for now we have to press m, ctrl space and then press enter to insert the mut keyword.

in previous version it supports display completion list automatically, i think there are many people like me, got used to press m and enter. now we have to re-adapt the new way to insert the mut keyword
