### ISSUE TITLE
Inherit language default Parameter for Rust function parameter

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#779]
The new parameter highlighting is great, I think one small improvement could be made. Currently it inherits from "'Identifiers→Default' of Language Defaults", but I think it could be made a little better if it inherited from "'Identifiers→Parameter"

Relates to #763

![image](https://cloud.githubusercontent.com/assets/10340167/20288834/35113084-aaa4-11e6-858f-c8ba1c53c921.png)

**Comment by mkaput** [comment]
I believe this has been resolved by c31add155d2e4a8ed15a2b20a463aafac4ea9f6e

**Comment by matklad** [comment]
Yep, thanks @mkaput and @johnthagen !
