### ISSUE TITLE
[feature] Add an option to disable blackslash on new line in strings

### ISSUE THREAD

**Issue by e-oz** [intellij-rust/intellij-rust#780]
Please add an option to code style settings, to be able to don't add "\" inside strings on pressing "enter" key. I don't know any other language plugin where such behavior is turned on by default.

**Comment by matklad** [comment]
Hm, this is an interesting issue! 

>I don't know any other language plugin where such behavior is turned on by default.

Hm, in my understanding it's not quite the case: if you press an Enter inside a string literal, you'll get the new line, but the contents of the string literals stays the same. So, if you have `"Hello, World"` and the caret is behind `W`, then pressing Enter leads to

Python:
```
"Hello " \
"World"
```

Java, Kotlin:

```
"Hello " +
    "World"
```

The equivalent in Rust would be

```
"Hello \
    World"
```

The interesting part is that in Rust

```
"Hello, 
    World"
```

is also a valid syntax and it means `"Hello, \n    World"`. 

So we indeed should not add `\` blindly! I am annoyed with this behavior as well when I am [writing tests for Cargo](https://github.com/rust-lang/cargo/commit/afae9f3f8d4f45a6e419d57f371f5157070d7c8e#diff-c79c8c3d6b488a508268ba418c49a75dR315), which uses multiline string literals

I am strongly against having checkboxes for such small features and think that we just need to do the right thing. 

I think a good strategy is *not* to add a `\` if there is at least one unescaped newline already. That way, if you have a very long string literal and use Enter to break it in two, you'll get the same literal. However, if you indeed mean literal `\n` and have a text which spans several lines, the IDE won't get in the way. 

@e-oz @mkaput does this sound reasonable?

**Comment by la10736** [comment]
IMHO the actual behavior is the correct one but is very annoying while you want to write a multi line string.
_PyCharm_ change this behavior according to string type (single quote and triple quote) and intellij-rust do the same thing for `r#`'s strings but `r#`'s strings are not the same of standard string and not suitable for all cases.

What about use something like shift-enter or ctrl-enter to enable this behavior instead of the standard one?
The only issue that I see is how to document this _magic feature_ because I don't see anything like this in other IDEs.

**Comment by matklad** [comment]
>What about use something like shift-enter or ctrl-enter to enable this behavior instead of the standard one?

<kbd>Shift + Enter</kbd> and <kbd>Ctrl + Enter</kbd> already has a meaning assigned: the first one opens a new line even if you are in the middle of the old one (a really convenient shortcut!) and the second one breaks the line in two but leaves the cursor on the first half.

**Comment by la10736** [comment]
That were just some examples... <kbd>Shift</kbd> + <kbd>Alt</kbd> + <kbd>Enter</kbd> should be free.

**Comment by matklad** [comment]
I've implemented "don't add `\` if there is at least one unescaped newline" heuristic for now because it's strictly better than the status quo.

**Comment by e-oz** [comment]
It's not what I'm asking, I hate this backslash wholeheartedly already, so feel free to close this issue and open something else if you are strongly against checkboxes. I think onky way for me then is fork this repo, remove that useless piece of ...functionality and use my own and only version.

**Comment by e-oz** [comment]
and transformation of 2 lines into 2 escaped (quoted) lines with + sign is absolutely different thing. Just backslash without any escaping is another.

**Comment by matklad** [comment]
Ok, so there is definitely a split of opinions! Let's close this for the time being then: current situation roughly follows the platform conventions, and there is no strictly better alternative in sight. 

If you want to tweak the plugin for yourself, it's totally OK! To disable this behavior, you'll need to delete [these lines](https://github.com/intellij-rust/intellij-rust/blob/48d122ebde0ce7e96ee62bc34ec393fc0dc5f639/src/main/resources/META-INF/plugin.xml#L125-L126).

@e-oz @la10736 thanks for the input!

**Comment by mkaput** [comment]
When I was implementing this I wasn't aware that no backslash had any special meaning, also I was following original issue. In this situation I believe @la10736's solution would be the better one, as such heuristics, as your one @matklad, have the property of irritating some users. This whole issue is an example.

The problem with making custom shortcuts is that the platform isn't friendly in this area if I recall correctly, and there is a reason behind this: this would be non-standard behaviour.

After all I think removing whole feature might be good solution....

**Comment by matklad** [comment]
>After all I think removing whole feature might be good solution....

I personally find this feature very convenient (for example, for [nice formatting of error messages](https://github.com/rust-lang/cargo/commit/151f12fc4474853c91225df3a632037ff5ef34f4#diff-54306f59fd4e355f0446fc9b53b4c31cR457)), and my experience is that you want escapes *most* of the time, while literal `\n` are pretty rare. So I am keen on leaving escaping as the default behavior, and providing a context aware means to disable it. An unescaped newline heuristic is one such way. Another possibility is to add Escape/Unescape newlines intention.
