### ISSUE TITLE
Navigate-to-definition doesn't work with glob imports

### ISSUE THREAD

**Issue by chriskrycho** [intellij-rust/intellij-rust#782]
Say I define an enum, and want to `use` its fields in an `impl` method for convenience:

```rust
enum MyCases {
    A,
    B
}

impl MyCases {
    fn next_case(self) -> Self {
        use MyCases::*;

        match self {
            A => B,
            B => A,
        }
    }
}
```

Code completion for the cases in the match body fails. If they're prefixed with `MyCases::` it works. Seems like lookup doesn't support glob imports like this yet. It would be super nice if it did!

**Comment by matklad** [comment]
Unfortunately this is not because of the glob imports, but because of the ambiguities between enum variants and identifiers:

```
match self {
   C => C // catch all clause that binds self to the name `C`. 
}
```

**Comment by matklad** [comment]
I'm closing this and #957 in favor of https://github.com/intellij-rust/intellij-rust/issues/958 :)
