### ISSUE TITLE
Can't attach library sources

### ISSUE THREAD

**Issue by Wyverald** [intellij-rust/intellij-rust#784]
I'm on a Mac using Homebrew to install Rust (version 1.13.0). I don't have rustup installed.

When I download the sources from https://www.rust-lang.org/en-US/downloads.html and try to attach them in intellij-rust, I simply get an error saying "Invalid Rust standard library source path: .../rustc-1.13.0-src.tar.gz".

**Comment by matklad** [comment]
Yep, you should the extract the archive. It's mentioned in the quick start (https://intellij-rust.github.io/docs/quick-start.html), but it is not that easy to notice :(
