### ISSUE TITLE
The trait method implemented through a derived macro cannot be prompted

### ISSUE THREAD

**Issue by juebanlin** [intellij-rust/intellij-rust#7848]
## Environment

* **IntelliJ Rust plugin version:**  0.4.156.4114-212-nightly
* **Rust toolchain version:** 1.56.0-nightly  x86_64-apple-darwin
* **IDE name and version:**  CLion 2021.2.1
* **Operating system:** MacOs Catalina 10.15.7

## Problem description
If you want to know what methods a structure has, you need to consult the source code, which is very unfriendly. However, vscode doesn't seem to have this problem.
How can I configure it to give him a prompt?

## Steps to reproduce
![1](https://user-images.githubusercontent.com/5427272/133393620-03d03489-0249-4a5d-87f2-0888302d365e.png)
<img width="527" alt="5" src="https://user-images.githubusercontent.com/5427272/133393841-2a4ce0af-7340-481b-93fc-fe396984204d.png">
![2](https://user-images.githubusercontent.com/5427272/133393646-089029d5-b0f6-4e3d-a68d-82858b9aec33.png)
![3](https://user-images.githubusercontent.com/5427272/133393643-96ee957b-dea1-44ba-a19b-b831b57fe069.png)

like this:

![4](https://user-images.githubusercontent.com/5427272/133393637-f3a673e7-889e-4356-9668-12ca945afb51.png)

**Comment by Undin** [comment]
It's because the plugin doesn't expand procedural macros by default yet. But it can (at least, function-like and derive proc macros). See #6908 for details and instructions on how to turn it on

**Comment by juebanlin** [comment]
tks

**Comment by Undin** [comment]
Let's keep this issue open since the corresponding feature is not enabled by default yet
