### ISSUE TITLE
Support Profiler for WSL

### ISSUE THREAD

**Issue by mili-l** [intellij-rust/intellij-rust#7857]
## Problem description
**Profiler for WSL 2 is supported on Clion, let's do it for Rust Plugin**

https://www.jetbrains.com/help/clion/cpu-profiler.html
 
Because of https://github.com/microsoft/WSL2-Linux-Kernel is used for WSL, 
to install Perf for Ubuntu rub the following scripts:
```
sudo apt install build-essential flex bison libssl-dev libelf-dev
git clone --depth=1 https://github.com/microsoft/WSL2-Linux-Kernel.git
cd WSL2-Linux-Kernel/tools/perf
make
```
And set the Perf for Plugin in Settings (Preferences):
<img width="555" alt="Screenshot 2021-09-17 at 10 52 18" src="https://user-images.githubusercontent.com/1213122/133754370-33f384ea-1d83-4a8d-ae14-6cb6867234ba.png">

**Comment by LoganDark** [comment]
What about WSL 1? What if I don't want to run my code in a slow VM ?
