### ISSUE TITLE
Cargo falsely indicates failure when reloading project

### ISSUE THREAD

**Issue by Igosuki** [intellij-rust/intellij-rust#7858]
## Environment

**IntelliJ Rust plugin version:** 
0.4.156.4122-212-nightly
* **Rust toolchain version:**
nightly-x86_64-unknown-linux-gnu
* **IDE name and version:**
CLion 2021.2.1
* **Operating system:**
Linux

## Problem description
Despite successfully reloading cargo, cargo says "failed"

## Steps to reproduce
Not sure where it comes from, I have a workspace and a lot of crates, see the screenshot
![Screenshot from 2021-09-17 11-05-16](https://user-images.githubusercontent.com/406150/133756932-0f008382-09ec-47d7-bf77-8d722b68e9da.png)

**Comment by Igosuki** [comment]
It's just that the plugin indicates sync success when it actually fails

**Comment by johnperry-math** [comment]
Sorry; I have this problem with some projects. Why is it closed? How does one fix it?

**Comment by Igosuki** [comment]
use cargo in the terminal directly to figure out how it fails

**Comment by johnperry-math** [comment]
It doesn't fail at the terminal. That's the problem. For me, IntelliJ reports that Cargo fails, but Cargo doesn't fail at the command line.
