### ISSUE TITLE
introduce local variable - refactor.

### ISSUE THREAD

**Issue by LiamClark** [intellij-rust/intellij-rust#786]
Intelij usually has cntrl - alt - v to introduce a local variable from an expression.
Are there any plans to support this? is this a feature you guys even want?

Not sure how hard this is to implement but i'd like to give it a shot.
Any pointers for implementing this?

P.S.
Sorry if it is actually there and I'm just to stupid to find it.

**Comment by matklad** [comment]
No, there is no such feature yet. Implementing basic support for introduce variable should not be super complex. Take a look at the go plugin for the example: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/master/src/com/goide/refactor/GoRefactoringSupportProvider.java#L35

**Comment by LiamClark** [comment]
@matklad 
So i've been working on this a bit.

I have most of it working binding statements, expressions and accounting for mutability, multiple occurences etc.

However i'm not really sure how to do the suggested names part.
Should i open as a work in progress for more feedback?

**Comment by matklad** [comment]
@LiamClark do please open a PR! I've started a bit of work myself, but looks like you further away along the path! 

>However i'm not really sure how to do the suggested names part.

it's totally OK to suggest something silly like `i` for the start!
