### ISSUE TITLE
no autocomplete in the bin subfolder and other pecularities

### ISSUE THREAD

**Issue by philippkeller** [intellij-rust/intellij-rust#787]
I must say that I have quite some problems getting the intellj plugin working. I followed all the instuctions in the [quick start](https://intellij-rust.github.io/docs/quick-start.html), I reinstalled intellij (with removing all the preferences as well) but am still without luck. Before giving up I thought I'd put some of my problems up here:

The most prominent problem is that autocomplete does not work when done on a source file under the `bin` directory as seen in this screenshot:  <img width="668" alt="screen-shot-2016-11-22-20-32-26" src="https://cloud.githubusercontent.com/assets/11523/20542073/4b7fd282-b100-11e6-9361-f7f8ea9e57e5.png">

Also, building does not work with cargo build even when configured like in this screenshot: 
<img width="1073" alt="screen-shot-2016-11-22-20-42-37" src="https://cloud.githubusercontent.com/assets/11523/20542122/8ec478ea-b100-11e6-955a-4612a6acd649.png">. Maybe it does build, but I don't see the build errors (`cargo build` on commandline shows the errors).

I know that this issue is fuzzy but I don't know how to explain this better. If I can supply any more info how to reproduce this I'd be happy to do so.

Also: after clicking "No standard libraries found..." dialogue the task "rustup component add rust-src" was open for *very* long (>2 minutes) until it went away and I cannot say if it succeeded or not

**Comment by matklad** [comment]
Hi!

Here are some checks which should help to pinpoint the issues: https://intellij-rust.github.io/docs/troubleshooting.html#is-cargo-project-structure-correct.

The screenshots would definitely help here, but I fail to see them (get Invalid upstream response (403)). 

>Also: after clicking "No standard libraries found..." dialogue the task "rustup component add rust-src" was open for very long (>2 minutes) 

Was there a button which said "run in the background"? This action is supposed to be long (rustup downloads stuff from the internet), but it should be backgroundable. Will check this tomorrow!.

**Comment by philippkeller** [comment]
I've fixed the screenshots.

I did do the checks you mentioned, except the "refresh cargo project". How can I find this?

> Was there a button which said "run in the background"? This action is supposed to be long (rustup downloads stuff from the internet), but it should be backgroundable. Will check this tomorrow!.

Yes there was, but I did not dare to click anything but just waited until the progress bar went away (in fact the progress bar stayed at 0% and was - if I remember correctly - red striped)

**Comment by matklad** [comment]
Aha, seems like the problem is that `Cargo.toml` is not in the root folder of your project, that's why IntelliJ does not understand the project structure.

To make this layout work, you should import `hans/src` and not `hans`. But it looks like that you actually want to move `Cargo.toml` one level up, such that it is alongside the `src`, and not inside of it. 

The usual layout for Rust projects looks like this:

```
foobinator/
  Cargo.toml
  src/
    lib.rs
    bin/
      foobinator_cli.rs              
```

If you have only single binary target, you can even use this:

```
foobinator/
  Cargo.toml
  src/
    lib.rs
    main.rs
```


>How can I find this?

use <kbd>Ctrl+Shift+A</kbd> (find action) and then type "refresh cargo project".

Thanks for the report, I think I know how to make docs a little bit clearer now!

**Comment by philippkeller** [comment]
> use Ctrl+Shift+A (find action) and then type "refresh cargo project".
thanks, I did that (for Mac it is Cmd-Shift-A) and now autocomplete works

As for the position of `Cargo.toml`: it is already on the same level as the `src` folder. This sample project was created with `cargo new --bin hans`, especially since I wanted to make sure that my curent rust projects' structure is not a problem (btw: there `Cargo.toml` is really one level deeper but I specify it's path with `cargo build --manifest-path macos/Cargo.toml`).

Here's the proof (I omitted some directories under debug):

```
07:06 $ tree .
.
├── Cargo.lock
├── Cargo.toml
├── src
│   ├── bin
│   │   └── kurt.rs
│   └── main.rs
└── target
    └── debug
```

Now my remaining problem is that I don't see build errors. I have e.g. this: `println!("Hello, world!", 2);`. `cargo build` omits: `error: argument never used`. But building with the cargo command (screenshotted above) like this:
![screen-shot-2016-11-23-07-11-14](https://cloud.githubusercontent.com/assets/11523/20552511/21e69054-b14c-11e6-85ff-4f1cc197a4b9.png)

does absolutely nothing. Is my build configuration wrong? Or do I trigger it wrong? Or does it do something but I just don't see it's output? (shouldn't there something in Event log? All I see there is `06:59	Project 'hans' successfully updated!` from the Cmd-Shift-A "refresh cargo project".

**Comment by matklad** [comment]
>As for the position of Cargo.toml: it is already on the same level as the src folder

Ouch, I have misinterpreted the screenshot :) 

>Is my build configuration wrong? Or do I trigger it wrong? Or does it do something but I just don't see it's output? 

Can you try creating a run configuration for `cargo run` instead of `cargo build`? Mine looks like this:

![runcfg](https://cloud.githubusercontent.com/assets/1711539/20554819/6bcfda68-b16f-11e6-9c5a-bb337bfb0ade.png)

And if I launch it with a green play button, I see a console window pop up with some output from Cargo and "Hello, World!" from my program.

**Comment by philippkeller** [comment]
Oh, you have to press that *play button* to actually build it 😊 
Now everything is clear. As a IntelliJ newbie this was not clear to me. Maybe you could mention that in the docs somewhere.

It doesn't solve my real world project yet though. Because there I have a directory tree which is one level deeper in the bin directory. Also, my Cargo.toml is lying in the subdirectory. This is both not supported by cargo. I'll open a new issue for that. Thanks for your help so far!
