### ISSUE TITLE
Provide `Add repr()` attribute quick fix for E0308 error

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#7894]
## Environment

* **IntelliJ Rust plugin version:** 0.4.157.4136-212-nightly
* **Rust toolchain version:** 1.56.0-nightly (b7404c898 2021-09-03) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.2.2 Ultimate Edition (IU-212.5284.40)
* **Operating system:** macOS 10.15.6
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
If the enum variant discriminant type doesn't match enum "type", the plugin produces [E0308](https://doc.rust-lang.org/error-index.html#E0308) error (in the same way as the compiler does). 
![image](https://user-images.githubusercontent.com/2539310/134766639-b95e477e-0bbd-4bb5-a6bf-381c7cb7882d.png)
![image](https://user-images.githubusercontent.com/2539310/134766695-eb1bb18c-21fc-4045-ace9-a9de2bd594e0.png)

But currently, the plugin suggests only `safe cast` quick-fix, i.e. plugin suggests changing expression type.
![image](https://user-images.githubusercontent.com/2539310/134766659-0d7bdeb3-98fc-41d2-9e78-d2a59f8a1eaa.png)

But I may want to change "base type" (i.e. enum variant "type") instead of expression type, i.e. add `#[repr(%some_type%)]` attribute ot change existing one.
It would be great to add described quick fix.

Note, the plugin already does a similar thing for functions. It suggests not only changing expression type but also changing this type of function
![image](https://user-images.githubusercontent.com/2539310/134766857-5caf4c1d-7348-4ebf-a55e-9b011912f90d.png)

## Steps to reproduce
```rust
const PIC1_OFFSET: u8 = 32;

pub enum InterruptIndex {
    Timer = PIC1_OFFSET
}
```
or
```rust
const PIC1_OFFSET: u8 = 32;

#[repr(u16)]
pub enum InterruptIndex {
    Timer = PIC1_OFFSET
}
```

**Comment by serid** [comment]
Did some work on the problem and issued a pull request #8087
