### ISSUE TITLE
Coverage is not working on a wsl system.

### ISSUE THREAD

**Issue by arodrigue003** [intellij-rust/intellij-rust#7896]
## Environment

* **IntelliJ Rust plugin version:** 0.4.155.4114-212
* **Rust toolchain version:** 1.55.0 (c8dfcfe04 2021-09-06) x86_64-unknown-linux-gnu
* **IDE name and version:** PyCharm 2021.2.2 Professional Edition (PY-212.5284.44)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

When I try to run tests with coverage support on Pycharm with the wsl feature enabled, the test run successfully but no coverage data is available in the IDE.

The complete command line executed by Pycharm is the following.
```bash
C:\Windows\system32\wsl.exe --distribution Ubuntu-20.04 --exec /bin/sh -c "export PATH=\"/home/<user>/.cargo/bin:$PATH\" && export RUST_BACKTRACE=short && export TERM=ansi && export CARGO_INCREMENTAL=0 && export RUSTFLAGS='-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off' && export RUSTC_BOOTSTRAP=1 && cd /home/adrien/projects/coverage-test && /home/adrien/.cargo/bin/cargo test --color=always --package coverage-test --lib 'tests::it_works' --no-fail-fast -- --format=json --exact -Z unstable-options --show-output"
```

If I try the same thing with the 0.4.157.4136-212-nightly version of the plugin, the coverage window appears but it doesn't display any covered line. The command line is the same.

## Steps to reproduce

```rust
fn sum2(a: u32, b: u32) -> u32 {
    dbg!((a, b));
    a + b
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        assert_eq!(sum2(2, 2), 4);
    }
}
```

**Comment by mchernyavsky** [comment]
Should work on the nightly version of the plugin.

**Comment by arodrigue003** [comment]
With the latest nighly (0.4.157.4136-212-nightly), the coverage window appears but unfortunately, no data seems to be loaded.

You can see it on the attached image bellow
![image](https://user-images.githubusercontent.com/14820264/134798646-6b6e9b52-8eca-4b92-82fb-bc417a3cfda0.png)

**Comment by mchernyavsky** [comment]
@mili-l Can you check it, please? I can't reproduce it.

**Comment by arodrigue003** [comment]
I don't know if it's important but I'm using wsl 1 on this computer.

**Comment by arodrigue003** [comment]
After some tests I was able to determinate that;
 * The version of wsl doens't seem to matter.
 * The coverage feature works properly if the project source code is located on a windows local drive.
 * The coverage doesn't work if the project source code is located on the wsl distribution partition (\\wsl$ mount point).
