### ISSUE TITLE
Update ... to reflect signature changes > import

### ISSUE THREAD

**Issue by Jasperav** [intellij-rust/intellij-rust#7929]
## Environment

* **IntelliJ Rust plugin version:** 0.4.156.4145-212
* **Rust toolchain version:** 1.55
* **IDE name and version:** Clion 2021
* **Operating system:** macOS

## Problem description
When I add another parameter to an already existing function which already has a caller and the new parameter as a type that isn't imported yet, 'update ... to reflect signature changes' is the first quick-fix CLion suggest. I would expect 'Import' to be here the first suggestion (because it was that for a long time and it's an error). I am constantly mis-entering the suggestion because I am used to 'Import'. It makes no sense to update the caller sides before actually importing the type that is missing.

**Comment by Kobzol** [comment]
I'm also hitting this quite often, so I agree. I'll try to see if the Import action could be prioritized here.

**Comment by Jasperav** [comment]
Thanks for the fix @Kobzol
