### ISSUE TITLE
how to jump to linux stdlib on windows platform?

### ISSUE THREAD

**Issue by Burning1020** [intellij-rust/intellij-rust#7955]
hi, all~
the developing env for my rust program is on Windows platform, and the target runtime env is Linux os. how could i jump to any linux toolchains stdlib source code like x86_64-unknown-linux-gnu other than stable-x86_64-pc-windows-msvc for now?

note: my code is sync with WSL where the compile work done too, however, develping on WSL desktop is much CPU consuming, that's why i need to develop on windows

thanks a lot

**Comment by Undin** [comment]
You may try to provide the proper toolchain in [`.cargo/config`](https://doc.rust-lang.org/cargo/reference/config.html)? Something like
```toml
[build]
target = "%necessary-toolchain-nama%"
```
The plugin will use not only linux stdlib sources, but also will evaluate all `cfg` predicates according to the provided toolchain

**Comment by Burning1020** [comment]
@Undin thanks for replying. 
Sorry, i want make it clear that i have problem in jumping into linux rust stdlib sorce code when coding instead of compiling a linux  binary. It's like ctrl + click to enter or go to defination of this method when reading the std code.


> Are you about our WSL integration or something else?

nothing to worry about, WSL integration is another way to work it around while it needs much CPU quantum, so i don't wanna try

**Comment by Burning1020** [comment]
@Undin Thanks for your video, it's really nice. Fortunately, that works for me until I upgrade my Clion form 2020.3 to 2021.2 and plugin from an old version to 0.4.157.4174-212. Really appreciate, hope you all the best~
