### ISSUE TITLE
E0107 false positive

### ISSUE THREAD

**Issue by Yuri6037** [intellij-rust/intellij-rust#7968]
## Environment

* **IntelliJ Rust plugin version:** I don't know
* **Rust toolchain version:** rustc 1.55
* **IDE name and version:** CLion 2021.2.2
* **Operating system:** Pop OS 21.04 Linux (Ubuntu derivative

## Problem description

When building my own fork of nalgebra https://github.com/Yuri6037/nalgebra, in the file geometry/scaling.rs you will observe many errors with `Wrong number of generic arguments: expected 1, found 2 [E0107]`

If you open a terminal and type `cargo build` everything will work.

## Steps to reproduce

- Download nalgebra https://github.com/Yuri6037/nalgebra
- Run CLion on nalgebra
- Open geometry/scaling.rs
- Enjoy `Wrong number of generic arguments: expected 1, found 2 [E0107]`

**Comment by mchernyavsky** [comment]
Fixed in #7001.
