### ISSUE TITLE
More folding options

### ISSUE THREAD

**Issue by ForsakenHarmony** [intellij-rust/intellij-rust#799]
Right now you can't fold for loops for some reason

**Comment by ForsakenHarmony** [comment]
when is this gonna be released?

**Comment by matklad** [comment]
It's already released in the current nightly. The next alpha will be on monday. To install nightly version, you need to add https://plugins.jetbrains.com/plugins/nightly/8182 to repositories ([instructions](https://www.jetbrains.com/help/idea/2016.2/managing-enterprise-plugin-repositories.html)).

Also, you can always get the version build off master from TeamCity: https://teamcity.jetbrains.com/repository/download/IntellijIdeaPlugins_Rust_CurrentIdea_TestsRust/.lastSuccessful/intellij-rust-0.1.0.%7Bbuild.number%7D.zip

**Comment by matklad** [comment]
Ouch, today's nightly is unfortunately broken :(
