### ISSUE TITLE
Completion does not work with IndexMap (indexmap crate)

### ISSUE THREAD

**Issue by eiennohito** [intellij-rust/intellij-rust#8007]
## Environment

* **IntelliJ Rust plugin version:** 0.4.157.4174-212
* **Rust toolchain version:** 1.55.0 (c8dfcfe04 2021-09-06) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.2.3 (CL-212.5457.51)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Rust Plugin seems to unable to decide which of implementations to use (there are no_std and regular versions), and so autocompletion does not work.

## Steps to reproduce

1. Add indexmap crate

```rust
fn main() {
  indexmap::IndexMap:: // completion does not work here
}
```

**Comment by dima74** [comment]
@eiennohito Please try to enable `org.rust.cargo.evaluate.build.scripts` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features)

**Comment by eiennohito** [comment]
@dima74 Autocompletion seems to work with that feature enabled, thank you.
