### ISSUE TITLE
Indexing stuck in IntelliJ IDEA

### ISSUE THREAD

**Issue by Kobzol** [intellij-rust/intellij-rust#8041]
## Environment

* **IntelliJ Rust plugin version:** 0.4.158.4203-212
* **Rust toolchain version:** 1.56.0 (09c42c458 2021-10-18) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2021.2.3 Ultimate Edition (IU-212.5457.46)
* **Operating system:** Linux 5.13.5-051305-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
I have opened the `intellij-rust` project inside IntelliJ IDEA after a few weeks, and everytime I try to load the project, it gets stuck in indexing.

I have cleaned the project, removed gradle and build artifacts, invalidated all IDE caches and restarted my PC. Yet still each time I open the project, the indexing phase gets stuck on analyzing some file. I checked what is the process doing using Activity Monitor and it seems to be forever stuck on parsing some file(s) (each time I reset the caches a different file ends up being stuck):
```
 %CPU  Subsystem

125.2  <Process total CPU usage>
 49.6  lang.parser (in com.intellij)
 16.9  lang.impl (in com.intellij)
 14.8  com.intellij
  5.1  <Activity Monitor>
  3.2  reference (in com.intellij)
  3.2  Plugin Rust: org.rust.lang.core.parser
  3.2  it.unimi.dsi.fastutil.ints
```

If I disable the Rust plugin, the problem goes away immediately, if I re-enable it, re-indexing gets immediately stuck again.
Here is a snapshot that I have captured:

[IU-212.5457.46_kobzol_01.11.2021_16.58.19.zip](https://github.com/intellij-rust/intellij-rust/files/7454542/IU-212.5457.46_kobzol_01.11.2021_16.58.19.zip)

and logs:
[idea-logs-20211101-170009.zip](https://github.com/intellij-rust/intellij-rust/files/7454546/idea-logs-20211101-170009.zip)

Could this be caused by some changes in the parser or something like that?

**Comment by vlad20012** [comment]
It's because of #8004 - I made a test with exponential parsing and fixed it. Aaand now you have to update the rust plugin to the latest nightly, or you'll can't use `intellij-rust`

**Comment by Kobzol** [comment]
Oh 😅 Thanks for the explanation :)
