### ISSUE TITLE
Generating impl for async fn in async trait adds a ton of unneeded code

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#8053]
## Environment

* **IntelliJ Rust plugin version:** 0.4.158.4203-212
* **Rust toolchain version:** 1.58.0-nightly (4e0d3973f 2021-10-27) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.2.3 (CL-212.5457.51)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

When adding impl of an async fn coming from async trait created with the async-trait crate, there's a ton of code added.

## Steps to reproduce
```rust
#[async_trait]
trait Foo {
    async fn bar(&self, id: &Uuid, delta: i8) -> Result<(), String>;
}

struct FooImpl;

#[async_trait]
impl Foo for FooImpl {
    // when using autogenerated impl
   fn bar<'life0, 'life1, 'async_trait>(
        &'life0 self,
        id: &'life1 Uuid,
        delta: i8,
    ) -> Pin<Box<dyn Future<Output = Result<(), String>> + Send + 'async_trait>>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        todo!()
    }
}
```

**Comment by vlad20012** [comment]
Oh. I don't know how we can do better here.

**Comment by krojew** [comment]
The previous version didn't do this. It just created impls as defined in traits, without adding anything.

**Comment by krojew** [comment]
@vlad20012 found a related problem - code completion type hints are also mangled for every async function. Instead of actual Future result, the plugins shows expended Pin<Box<Future<...>>> and it's impossible to tell what the result is, since it doesn't even fit the hint window.

**Comment by Kobzol** [comment]
@vlad20012 Maybe there could be some additional "blacklist" of proc macros that are not expanded in specific scenarios? `async_trait` is used a lot and there will probably be multiple problems with it. Or just disable macro expansion during auto-generation of things like impl methods?
