### ISSUE TITLE
Inlay type hints stopped working

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#8060]
## Environment

* **IntelliJ Rust plugin version:** 0.4.158.4203-212
* **Rust toolchain version:** 1.58.0-nightly (baba6687d 2021-11-03) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.2.3 (CL-212.5457.51)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

In the latest version, inlay hints stopped working, but only sometimes. Cannot tell the pattern.

## Steps to reproduce

No hints:

![image](https://user-images.githubusercontent.com/1268573/140268961-15530b2d-33e7-4d6b-b45b-95597517d617.png)

Working hints:

![image](https://user-images.githubusercontent.com/1268573/140268998-43b01dee-7912-4ea7-9e89-d58b51a83edd.png)

Hints in the last example disappear when the exact same code is used outside the function:

![image](https://user-images.githubusercontent.com/1268573/140269069-e77a90df-e027-4cec-b474-4065f0a29f7b.png)

**Comment by krojew** [comment]
In the last example, the plugin properly recognizes the types, since code completion is working as expected.

**Comment by Sibz** [comment]
Anything with a proc_macro_attribute seems to cause breakage of colouring and type hinting:
Not Working:
![image](https://user-images.githubusercontent.com/12050358/141606364-957f9425-ae77-4b3e-9570-611a29359e4c.png)
Working:
![image](https://user-images.githubusercontent.com/12050358/141606370-2cc29cf3-70f4-4d39-a206-7c335210e063.png)

**Comment by lyinch** [comment]
I have the same issue with the macros from [Rocket](https://rocket.rs/) . The colouring mostly vanishes and the type hints disappear on functions such as:

```rust
#[rocket::main]
async fn main(){}

#[get("/foo")]
async fn foo() {}
```


```
CLion 2021.3.3
Build #CL-213.6777.58, built on January 31, 2022
Runtime version: 11.0.13+7-b1751.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Registry:
    run.processes.with.pty=TRUE
    clang.parameter.info=true

Non-Bundled Plugins:
    IdeaVIM (1.9.3)
    org.toml.lang (213.5744.224)
    org.rust.lang (0.4.165.4438-213)
```

**Comment by ChristianIvicevic** [comment]
I can confirm this, with `rocket = { version = "0.5.0-rc.1" }` it becomes really annoying to work with.

**Comment by Occuros** [comment]
I can observe the same with latest nightly for the rust plugin and 0.5.0-rc.2 of rocket.
