### ISSUE TITLE
Type import suggestion not working with async traits

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#8072]
## Environment

* **IntelliJ Rust plugin version:** 0.4.158.4203-212
* **Rust toolchain version:** 1.58.0-nightly (baba6687d 2021-11-03) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.2.3 (CL-212.5457.51)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

When using the `async-trait` crate, the plugin does not show import hint for unimported types.

## Steps to reproduce

```rust
#[async_trait]
pub trait Foo {
    // Bar is a type from an external crate, but the import hint is not present
    async fn bar(&self, a: Bar);
}
```

**Comment by Sibz** [comment]
This is same with anything that has a proc_macro_attribute
