### ISSUE TITLE
Enum variants are no longer displayed as such

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#8073]
## Environment

* **IntelliJ Rust plugin version:** 0.4.158.4203-212
* **Rust toolchain version:** 1.58.0-nightly (baba6687d 2021-11-03) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.2.3 (CL-212.5457.51)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

The new version sometimes doesn't display enum variants as such.

## Steps to reproduce

Note the variant is not displayed as one:

![image](https://user-images.githubusercontent.com/1268573/140313319-0688f00e-bfc6-4d56-b770-da4bde90f0a1.png)

**Comment by Undin** [comment]
Let's close in favor of #8092
