### ISSUE TITLE
No hints when calling trait function implemented for slices on Vec

### ISSUE THREAD

**Issue by twistedfall** [intellij-rust/intellij-rust#8084]
## Environment

* **IntelliJ Rust plugin version:** 0.4.159.4232-212
* **Rust toolchain version:** 1.56.1
* **IDE name and version:** Build #IU-212.5457.46, built on October 12, 2021
* **Operating system:** Linux 5.15.1-gentoo

## Problem description

When a trait is implemented on a slice then Idea doesn't give any hints when trying to call that method on `Vec`. So no function name hints after typing `v.` and no return type hints after spelling out the function manually. Rust would autoderef that to slice so the code is valid ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5b95eb9ce3a9b035b375e2e134529e99)):
```rust
trait TraitForSlice {
	fn func_on_slice(self) -> bool;
}

impl TraitForSlice for &[()] {
	fn func_on_slice(self) -> bool { true }
}

fn test() {
	let v = vec![()];
	let no_type_hints = v.func_on_slice();
	let ok_type_hints = v.as_slice().func_on_slice();
}
```

![afbeelding](https://user-images.githubusercontent.com/406037/140757869-09f6f04b-9280-459e-ba44-fde6489130b0.png)

**Comment by vlad20012** [comment]
@es50678, your case is not related to the issue. You just should enable `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` experimental feature via the corresponding dialog. To open the dialog, just invoke `Help | Find Action` action and type `Experimental features`

**Comment by es50678** [comment]
@vlad20012 that worked for me. thank you so much.
