### ISSUE TITLE
Failed to expand a procedural macro on `1.56.0-nightly`

### ISSUE THREAD

**Issue by xiaoyawei** [intellij-rust/intellij-rust#8088]
## Environment

* **IntelliJ Rust plugin version:** 0.4.159.4232-212
* **Rust toolchain version:** 1.56.0-nightly (9c25eb7aa 2021-07-25) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.2.2 (CL-212.5284.51)
* **Operating system:** macOS 11.4
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

I use `prost_build` and generate a `.rs` file out of a protobuf file. In the generated code, I tried to expand a procedural macro `::prost::Message` but got the following error.

```
Failed to expand the macro: a procedural macro error occurred: proc-macro panicked: called `Result::unwrap()` on an `Err` value: ParseFloatError { kind: Invalid }
```

![Screen Shot 2021-11-09 at 5 23 39 PM](https://user-images.githubusercontent.com/8537702/140897942-e02d5252-5a7a-43c1-abcc-5cc6d13020eb.png)

## Steps to reproduce

I believe this bug can reproduce in every protobuf generated files.

If you are in the same dev environment as mine above, right click the procedural macro `::prost::Message` and expand it, then you should see the same error.

By the way I can also verify that this bug does not exist in plugin version `0.4.155.4114-212`

**Comment by rekby** [comment]
I use Prost for generate .rs files too.
With same plugin version expand macro ::Prost::Message work without panic and show expanded macros.

* **IntelliJ Rust plugin version:** 0.4.159.4232-212
* **Rust toolchain version:** 1.56.1 (59eed8a2a 2021-11-01) x86_64-apple-darwin
* **IDE name and version:** GoLand 2021.2.4 (GO-212.5457.54)
* **Operating system:** macOS 11.6.1
* **Macro expansion engine:** new
* **Name resolution engine:** new

**Comment by xiaoyawei** [comment]
Hi @rekby , thanks for your reply! I believe this is due to difference between rustc toolchain. Here's how I verify

1. Tried to reproduce the bug as described in this issue with the same settings (using exactly the same settings), and the bug produced.
2. Install and switch to `1.56.1 (59eed8a2a 2021-11-01) x86_64-apple-darwin`, and open [tonic](https://github.com/hyperium/tonic) project  (since my current project only builds on nightly)
3. Tried to expand `prost::Message` macro and this time it succeedded.

Therefore I think it's very likely that there's such a bug for `1.56.0-nightly (9c25eb7aa 2021-07-25) x86_64-apple-darwin` at least.

**Comment by xiaoyawei** [comment]
Some more information that might be helpful: I installed rust plugin of an old version `0.4.155.4114-212` and the proc macro expands successfully.

So now I am somewhat stuck with an old version and cannot enjoy new features of the rust plugin. Would really love to see this bug fixed, and thanks in advance!

**Comment by xiaoyawei** [comment]
I can also verify that this bug does not exist on `1.58.0-nightly` so I think it's ok to close this issue
