### ISSUE TITLE
The inline variable dialogue window can mislead 

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#8101]
## Environment

* **IntelliJ Rust plugin version:** 0.4.160.4235-213-nightly
* **Rust toolchain version:** 1.56.0 (09c42c458 2021-10-18) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.3 Beta Ultimate Edition (IU-213.5605.12)
* **Operating system:** macOS 11.4
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
The window has the option "Search in comments...". But the use of a variable is not found in the comment. 
Problem: user can think "wow, it will analyze text in comments and change usages, nice!", later uncomments, and the code will be broken.
![изображение](https://user-images.githubusercontent.com/49211026/141457198-e719712d-611d-400c-9012-8e3d46e7ef72.png)
Maybe this option should be changed or removed.

## Steps to reproduce
```rust
fn f() {
    let mut some_name = 4;
    // some_name = 5;
    println!("{}", some_name)
}
```

**Comment by dima74** [comment]
Options were removed in #9270
