### ISSUE TITLE
Continuously doing something

### ISSUE THREAD

**Issue by stepancheg** [intellij-rust/intellij-rust#8105]
Sometimes Idea starts consuming 800% CPU and it never finishes even if I do nothing with Idea.

Looks like this:

<img width="444" alt="Screenshot 2021-11-12 at 21 44 36" src="https://user-images.githubusercontent.com/28969/141538165-1b2fa218-1a35-49a4-80dd-4e071c82e818.png">

After restart of Idea, it reindexes the dependencies for a couple minutes, and then no longer consumes CPU.

I'd suspect some my action triggers some infinite (or very long) loop in intellij-rust.

If I can provide more diagnostics, let me know please. Otherwise feel free to close the issue.

**Comment by dima74** [comment]
@stepancheg Hi! Could you please provide the plugin version and project code if it's open-source

**Comment by stepancheg** [comment]
No code is not open source. It is quite large project with all possible unstable features of rust, hundreds of dependencies and and tons of macros and proc macros. So no easy repro.

Plug in version is latest, I’m post exact version if when it reproduces again.

**Comment by dima74** [comment]
@stepancheg thanks, could you please also provide [`idea.log`](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files)

**Comment by stepancheg** [comment]
I cannot send you the full log here, it contains private project details (or give me an email and I'll send you), but I see the log is continuously updated with lines like this:

https://gist.github.com/stepancheg/b5f55cce3b70b94b89a50ea8b7f0e212

Plugin version is 0.4.159.4232-212

**Comment by dima74** [comment]
Looks like the problem is lack of free memory - plugin continuously builds some internal data structure and saves them to cache, then cache was cleared in order to free memory and we start over. Could you please capture memory snapshot (`Help | Diagnostic Tools | Capture Memory Snapshot`) and upload them here: https://uploads.jetbrains.com/?

By the way, what max heap memory value you have? You can try to [increase it](https://www.jetbrains.com/help/idea/increasing-memory-heap.html)

**Comment by stepancheg** [comment]
> Could you please capture memory snapshot

I'll do it next time when the issue reproduces.

And then I'll increase memory size and problem will likely disappear.

> By the way, what max heap memory value you have?

1Gb

**Comment by stepancheg** [comment]
There's no "Capture memory snapshot" in my version of Idea, which is:

```
IntelliJ IDEA 2021.2.3 (Community Edition)
Build #IC-212.5457.46, built on October 12, 2021
Runtime version: 11.0.12+7-b1504.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: G1 Young Generation, G1 Old Generation
Memory: 1000M
Cores: 16
```

<img width="561" alt="Screenshot 2021-11-19 at 20 03 06" src="https://user-images.githubusercontent.com/28969/142684715-1c1ecf7f-1a30-4ff1-a19f-8c45faebd122.png">

**Comment by stepancheg** [comment]
Created heap dump manually with `jmap -dump:live,format=b,file=heap.bin <PID>`, uploading now...

The output of `jmap -histo:live <PID>` is [here](https://gist.github.com/stepancheg/e698f3663718e4fd6c414fd8f9680cb0).

**Comment by stepancheg** [comment]
Upload id: 2021_11_19_QhW2VgMLdCaZ6Kb9 (file: heap.bin)

**Comment by dima74** [comment]
@stepancheg thanks for the snapshot. New resolve data structures hold ~100MB which is expected for such large projects. So the solution is to increase the maximum available memory (we recommend at least 2GB for large projects).
