### ISSUE TITLE
Find references has stopped working

### ISSUE THREAD

**Issue by nocker01** [intellij-rust/intellij-rust#8107]
Hello,

The "find references" feature has stopped working for me.  I've posted here:

https://intellij-support.jetbrains.com/hc/en-us/community/posts/206845105/comments/4409849363090

And after some back and forth it has been suggested that I submit an issue here.

## Environment

* **IntelliJ Rust plugin version:** 0.4.159.4232-212
* **Rust toolchain version:** 1.54.0 (a178d0322 2021-07-26) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.2.3 (CL-212.5457.51)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
The "find references" feature no long works for me when the usage of a function is outside the scope of the current file.  For funcitons that are called within a file, the "find references" does return a set of results.
This functionality used to work for me.  I keep the IDE updated to the latest release CLion and Rust plugin as the IDE shows that they are available to me.  I have recently restructured my project and have also recently applied updates to CLion/Rust, I can't be sure if the "find references" has worked since either changes.

I have tried File -> invalidate caches..  and have tried Help -> Find Action -> Refresh Cargo Projects.

## Steps to reproduce
1. Move the caret to a function.  Press ALT+F7.
2. Move the caret to a function.  From the File menu, Edit -> Find Usages -> Find Usages

**Comment by nocker01** [comment]
Hi, no my project is not open source.  It is proprietary to the company that I work for.  I recently changed the Rust project to be a "workspace".

Is there any other actions within CLion that I can try to refresh/reset the functionality?

**Comment by dima74** [comment]
Could you please provide [`idea.log`](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files) file? And also check whether the issue persists on other projects (e.g. new fresh empty project)?

**Comment by nocker01** [comment]
[idea - sanitised.log](https://github.com/intellij-rust/intellij-rust/files/7605370/idea.-.sanitised.log)
Hi, I've attached the log.

**Comment by dima74** [comment]
@nocker01 thanks for the log. Unfortunatelly there isn't anything suspicious related to find usages. Could you please provide the project code if it's open-source, or some reproductional code sample otherwise?

**Comment by nocker01** [comment]
Hi, no as I've already stated above, this is not an open source project.
Are there any files or something that I delete/modify to make CLion refresh or rescan or whatever so that it might start working again?

**Comment by nocker01** [comment]
@dima74 is there any chance that uninstalling CLion from my PC and reinstalling it would make any difference?  This is driving me insane!

**Comment by nocker01** [comment]
We have now found the cause of the issue!

I tried uninstalling CLion (selecting yes to removing all setting), restart PC, install Clion, restart PC... none of that worked.

I did a clean checkout from our version control and the issue still persists for me.  I am now running "Build #CL-213.6461.75, built on December 29, 2021".  A fellow developer of the same project who has the same version installed as I do also has the same issue.


The issue was introduced into the Rust plugin in 0.4.159.4232-212:
https://plugins.jetbrains.com/plugin/8182-rust/versions/stable/142804

We have found that 0.4.158.4203-212 is the last version of the Rust plugin that works for us.  We believe that the commit that has broken the Rust plugin is https://github.com/intellij-rust/intellij-rust/pull/7944

**Comment by dima74** [comment]
@nocker01 this is very useful, thanks! Could you please try this plugin build ([intellij-rust-0.4.162.SNAPSHOT-213-dev.zip](https://github.com/intellij-rust/intellij-rust/files/7844142/intellij-rust-0.4.162.SNAPSHOT-213-dev.zip)), which is basically v162 with #7944 reverted, in order to check that #7944 broke find usages for you

**Comment by nocker01** [comment]
@dima74 Yes "intellij-rust-0.4.162.SNAPSHOT-213-dev.zip" works correctly for me.

**Comment by dima74** [comment]
@nocker01 ok, nice. Could you please help us create reproductional example? IIUC you use cargo workspace. Which crates do you have (binary/library)? Do you find usages within same crate or in other crates? I remember that your project is not open-source, but something like a file tree of important files with file names changed can be useful. Without reproductional example we can't do much here, unfortunatelly

**Comment by rikvdkleij** [comment]
I have the same issue. It's also not in an open source project. 
Maybe this issue is related to the fact that the project crates refer to each other with relative file paths.

**Comment by nocker01** [comment]
[_simple_example.zip](https://github.com/intellij-rust/intellij-rust/files/7866980/_simple_example.zip)
Here is a simple example project that I've been able to create that has the issue.  Find references on the function "test_function4" does not work.

**Comment by dima74** [comment]
@nocker01 thanks for the reproduction! It is extremely useful

**Comment by rikvdkleij** [comment]
Sorry, it's still not resolved in version `0.4.164.4409-213`

**Comment by dima74** [comment]
@rikvdkleij could you please provide a reproductional sample? It will help a lot to fix the issue
