### ISSUE TITLE
Using unreachable_unchecked() inside Option::map_or_else() wrongfully marks the rest of the scope unreachable

### ISSUE THREAD

**Issue by aldanor** [intellij-rust/intellij-rust#8113]
## Environment

* **IntelliJ Rust plugin version:** 0.4.159.4232-212
* **Rust toolchain version:** 1.56
* **IDE name and version:** CLion 2021.2.3
* **Operating system:** macOS 10.15.7

## Problem description

Using `core::hint::unreachable_unchecked()` in `Option::map_or_else()` (and perhaps other closure-like routines, haven't checked that) wrongfully marks the rest of the scope as unreachable and function arguments as unused.

(The fun fact is that it is `clippy` who suggests these kind of blocks.)

## Steps to reproduce

Example:

```rust
fn foo(x: Option<i32>, y: i32) -> i32 {
    let z = x.map_or_else(|| unsafe { core::hint::unreachable_unchecked() }, |x| x);
    y + z
}
```

In CLion (note that `y` argument and the last line are grey):

![image](https://user-images.githubusercontent.com/2418513/142040029-fe4f95be-c351-4c1b-acca-efd3833c27a2.png)

**Comment by Undin** [comment]
Works for me with 0.4.187.5154-223-nightly so I close it
@aldanor if it's not fixed for you, don't hesitate to share it
