### ISSUE TITLE
Code Completion Fails with `indexmap` Crate

### ISSUE THREAD

**Issue by naftulikay** [intellij-rust/intellij-rust#8116]
egcc## Environment

* **IntelliJ Rust plugin version:**

```
0.4.159.4232-212
```

* **Rust toolchain version:**

```
stable-x86_64-unknown-linux-gnu (default)
rustc 1.56.1 (59eed8a2a 2021-11-01)
```

* **IDE name and version:**

```
CLion 2021.2.3
#CL-212.5457.51
```

* **Operating system:**

Ubuntu 18.04 LTS, amd64, kernel 5.4.

## Problem description

Code completion completely does not work for the [`indexmap`](https://crates.io/crates/indexmap) crate, especially `indexmap::IndexMap`. Code completion is aware of the existence of the struct, but cannot do any code completion on it whatsoever. It also sees _two_ implementations of it:

![Screenshot from 2021-11-16 12-44-04@2x](https://user-images.githubusercontent.com/347571/142062857-5e6f5f91-3bc3-4704-8dc2-c93352f37cd0.png)

See also that <kbd>Ctrl</kbd><kbd>Space</kbd> yields no results:

![Screenshot from 2021-11-16 12-47-25@2x](https://user-images.githubusercontent.com/347571/142063271-aaf151bc-a98c-43f0-9e1a-bde927031f1f.png)

I'm using the latest version of the crate, at the moment `1.7.0`. This is a fairly popular crate, according to crates.io, it has over 6 million recent downloads and 35 million total downloads. 

## Steps to reproduce

Create a new Rust project using the latest stable Rust, use the Rust plugin, add `indexmap = "1.7"` to your Cargo manifest, try to use it in your code and observe that code analysis fails on usage of the crate.

**Comment by dima74** [comment]
@naftulikay could you please enable `org.rust.cargo.evaluate.build.scripts` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features)

**Comment by naftulikay** [comment]
@dima74 it does work, thanks! Is there a way for me to track when this will be default?

**Comment by dima74** [comment]
@naftulikay please subscribe to https://github.com/intellij-rust/intellij-rust/issues/6104
