### ISSUE TITLE
Intellij-Rust Generated Over 230 GB of Temp Macro Expansion Files

### ISSUE THREAD

**Issue by zedseven** [intellij-rust/intellij-rust#8139]
## Environment

* **IntelliJ Rust plugin version:** 0.4.159.4232-212
* **Rust toolchain version:** 1.58.0-nightly-x86_64-pc-windows-gnu (c9c4b5d72 2021-11-17)
* **IDE name and version:** CLion 2021.2.3
* **Operating system:** Windows 10 64-bit

## Problem description
Working in macro-heavy projects generates obscene amounts of temp files. Working in a project that makes use of lots of macro attributes on functions, I found the IDE got more and more sluggish and started warning me about random errors that made little sense.

I started getting errors about how `usize` didn't implement `Display`, how certain proc macro items couldn't be found in scope, etc.

Then, I got a warning about low disk space on my main SSD. I checked, and Intellij-Rust had generated **over 230 GB of temp files** and run out of space. They all seem to be temp files for the processing/expansion of macros, from what I can tell.

I deleted all of them, and things got better. However, over the course of about half an hour of continuing to work on my project, I watched my SSD fill back up to over 80 GB of those same temp files again. Here's a screenshot of a tiny percentage of those files:

![image](https://user-images.githubusercontent.com/25164338/142747736-b2816fc5-69ff-4908-b849-de3a6e318375.png)

I think the only two types are `poise_macros` and `async_trait`, though it's entirely possible I've missed some others somewhere in the huge list of files.

## Steps to reproduce
I'm not sure exactly what is causing the issue, so I'll just provide a link to my project at the commit where I noticed I was experiencing this: https://github.com/zedseven/radium/commit/f136d9abfd5506ac286f94a65390ab65388d435b

The behaviour should be reproducible by just making small changes to the main function. In case it matters, I have my IDE set up to run Rustfmt on save and use Clippy to analyze on-the-fly.

**Comment by vlad20012** [comment]
Duplicate #7709
Btw this is a bug with `org.rust.macros.proc` experimental feature. You can disable it until the feature stabilization.
Btw the bug is Windows-only.
