### ISSUE TITLE
"Go to file ..." does not work for Rust code 

### ISSUE THREAD

**Issue by ralfbiedert** [intellij-rust/intellij-rust#8149]
## Environment

* **IntelliJ Rust plugin version:** 0.4.160.4261-212
* **Rust toolchain version:** 1.58.0-nightly (65f3f8b22 2021-11-21) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.2.3 (CL-212.5457.51)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

In Rust projects, using "Go to file ..." does not suggest any `.rs` file. 

## Steps to reproduce

In Rust projects, **Go to file** fails searching for a project file (it says "All Places" on the right, but it also doesn't find it if I select "Project Files"):

![image](https://user-images.githubusercontent.com/301288/142870036-fd0f4517-8366-450e-8df0-c3d7b690cb53.png)

I have everything ticked in the filter view on the right:

![image](https://user-images.githubusercontent.com/301288/142871542-ecc28721-1710-4b36-abe5-4e0660898109.png)

Interestingly enough, it does seems to work when I use **"Search everywhere"** instead ...

![image](https://user-images.githubusercontent.com/301288/142870521-c765a858-f15e-4188-9a46-65d0d598b067.png)

**Comment by Undin** [comment]
@ralfbiedert Is there a code example to reproduce the issue?

**Comment by ralfbiedert** [comment]
Jesus that was painful ... I first tried reproducing it additively, but couldn't get it to fail in a fresh project, then I tried doing it subtractively but my existing projects would never work. I then started copying projects around, deleting various `target` and `.idea`, ... files and folders, until I realized it's seemingly related to restarting the IDE **multiple times**:

**Repo: https://github.com/ralfbiedert/intellij-rust-issues**

https://user-images.githubusercontent.com/301288/142908794-44794f0f-0e62-4f2d-b658-e731eac99aaa.mp4

Timestamps:

- 0:05 - Fresh checkout
- 0:17 - First start CLion
- 0:50 - First search (works)
- 1:10 - Second start CLion
- 1:30 - Second search **(broken)**


### How to reproduce

Here is at least what works for me:

- Clone https://github.com/ralfbiedert/intellij-rust-issues
- Open in CLion
- Try "Go to File" ... it will work
- Close CLion
- Open CLion again
- Try "Go to File" ... it's broken.


### Bonus Insight

In an earlier version of this repo https://github.com/ralfbiedert/intellij-rust-issues/commit/10f4390af9a47fbb2522b7329b01b60682892366 I didn't remove as much but still got the same behavior. I ALSO ran into issues similar to #8065 (which I too had plenty since 3 releases ago), **so I _hope_ addressing whatever causes this might also fix a few other problems**.

Compare below, this repo with broken syntax highlighting right in the middle:

![Screenshot_5](https://user-images.githubusercontent.com/301288/142913723-0ef596fb-a3ab-4805-9093-fba00838b4fa.png)

**Comment by ralfbiedert** [comment]
As described in #8020, this seems to "fix" it for one CLion restart:

![image](https://user-images.githubusercontent.com/301288/142921833-fd31181a-7dbb-4ad7-9aed-038217dde2a4.png)

**Comment by ralfbiedert** [comment]
This seems to be fixed with 2021.3 / 161.
