### ISSUE TITLE
Invert `if without else` generate code `return return ...`

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#8162]
## Environment

* **IntelliJ Rust plugin version:** 0.4.161.4264-213-nightly
* **Rust toolchain version:** 1.58.0-nightly (547a6ffee 2021-10-21) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.3 RC (CL-213.5744.123)
* **Operating system:** macOS 11.4
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
Invert `if without else` generate code `return return ...`

## Steps to reproduce
Invert `if`:
```rust
fn f(x: bool) -> u32 {
    if x {
        return 500
    }
    return 6
}
```
This code is not good - `;` are missing at the end of lines with `return`, but code is working and `f` returns `500` or `6`.

Note, that clippy and cargo check do not show what `;` is missing there.
Also note, that our reformatter and rustfmt add `;` in the end of lines with `return`

## Actual result 
```rust
fn f(x: bool) -> u32 {
    if !x {
        return return 6;
    }
    return 500
}
```
Generated code works and still returns `500` or `6`, but:
<img width="676" alt="изображение" src="https://user-images.githubusercontent.com/49211026/143226298-4e69c30b-dcb6-41b3-ae24-a2b35937708a.png">

## Expected 
```rust
fn f(x: bool) -> u32 {
    if !x {
        return 6;
    }
    500 //or return 500; 
}
```

**Comment by ortem** [comment]
Just for the record: introduced in #8005. @neonaot nice catch, thanks!
