### ISSUE TITLE
Debugger is not loaded yet, download fails too

### ISSUE THREAD

**Issue by nazar-pc** [intellij-rust/intellij-rust#8169]
## Environment

* **IntelliJ Rust plugin version:** 0.4.160.4261-213
* **Rust toolchain version:** 1.58.0-nightly (cc946fcd3 2021-11-18) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2021.3 RC Ultimate Edition (IU-213.5744.125)
* **Operating system:** Linux 5.11.0-34-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
I'm getting "Debugger is not loaded yet" error and downloading fails too just like in #7500 when I try to run test.

Native Debugging Support extension is installed.

## Steps to reproduce
Just try to debug test from IDE.

**Comment by Undin** [comment]
@nazar-pc should work now. Try again, please

**Comment by nazar-pc** [comment]
Yep, downloaded something and started working again. Thanks!
