### ISSUE TITLE
Raw str hash insertion inserts incorrectly

### ISSUE THREAD

**Issue by Keats** [intellij-rust/intellij-rust#817]
Start with:

```rust
static CHILD_TEMPLATE: &'static str = r"
{% extends "parent.html" %}
";
```

Try to add a `#` after the `r`, what happens is:
```rust
static CHILD_TEMPLATE: &'static str = r#"
{% extends "#parent.html" %}
";
```

It seems it looks for the next double quote rather than the last?

**Comment by matklad** [comment]
The problem here is that `r"{% extends "` is a valid raw string literal, and plugin just tries to balance `#` around it. Not sure what is the best course of action here. Perhaps we should not try to be smart at all if there are syntax errors around the literal? cc @mkaput

**Comment by mkaput** [comment]
That would seem reasonable but what about unfinished typing? Imagine following situation:

```rust
let s = r"blablabla"<caret>
```

Ouch, I'd like to put hash inside this

```rust
let s = r#"blablabla"#<caret>
```

**Comment by matklad** [comment]
Another alternative is to remove auto hash addition, leave auto hash removal as is, and provide "add more hashes" intention.

**Comment by kryptan** [comment]
Just hit this bug today:

```Rust
#[doc = r#"
"#version 150"
"#]
pub const AAA: &str = "l";
```

Attempting to insert # after r will balance it incorrectly.

I think IDE should never try to autobalance hashes in raw string literals. The only reason for me to add more hashes is if the parser could not correctly parse the string and more hashes are required. But if parser cannot correctly parse it how would IDE correctly insert more hashes? And if IDE can correctly autobalance hashes it would mean they weren't needed in the first place.
