### ISSUE TITLE
Proc macro interferes with rename refactor and Go to Declaration or Usage, with experimental features on

### ISSUE THREAD

**Issue by Madoshakalaka** [intellij-rust/intellij-rust#8182]
## Environment

* **IntelliJ Rust plugin version:** 0.4.160.4261-212
* **Rust toolchain version:** 1.56.1
* **IDE name and version:** CLion CL-212.4746.93 July 27, 2021
* **Operating system:** Windows

I have proc macro and build script experimental features on.

## Problem description

The identifier `App` on line 3 is the same as the one on line 10. IDE recognizes they are the same, as shown by the syntax highlighting. "Go to Declaration or Usage" (by ctrl+click) finds one from the other.

![image](https://user-images.githubusercontent.com/44753941/143544820-60702ceb-3686-4e64-a821-d918429fc74f.png)

But Rename refactor action on `App` fails with an error message:
![image](https://user-images.githubusercontent.com/44753941/143545294-46731a2e-4f46-4254-9062-e567804b3ac7.png)

I am positive the renaming refactor worked roughly a week ago. This might be caused by the 11/22 rust plugin update.

Also, find usages and declaration only work partially correct under a proc macro. Detailed tests and comments are below.

Worth noting, macro expansion intention works on all the proc macros.

### Cargo.toml
```toml
[package]
name = "irrelevant"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/" }
gloo-console = "0.2.1"
```

### main.rs

```rust
use yew::prelude::*;

#[function_component(App)]
fn app() -> Html {

    // inside the function_component proc macro,
    // "Go to Declaration or Usage" unilaterally works for declaration, but fails for usage
    // ctrl+click on the first line shows "No usage found in all places"
    // ctrl+click on the following two line redirects cursor back to the first line as expected
    // Renaming `a` on the first line does nothing to the following lines
    // Renaming `a` on the following two lines fails with read-only file error.
    let a = 1;
    gloo_console::console_dbg!(a);
    gloo_console::console_dbg!(a + 1);

    // renaming `a` here this works all as expected.
    // However, ctrl-click on the first `a` says "No usages found in all places"
    let a = 1;
    let b = vec![a];

    html! {
    }
}

fn main() {

    // in a non proc macro context, everything works expectedly
    let a = 1;
    gloo_console::console_dbg!(a);
    gloo_console::console_dbg!(a + 1);

    // in a non proc macro context, everything works expectedly
    let a = 1;
    let b = vec![a];

    yew::start_app::<App>();
}
```

**Comment by vlad20012** [comment]
Similar to #8003, and really its the same limitation as #5740

**Comment by mili-l** [comment]
@vlad20012 
Renaming is these cases still works incorrectly 

https://user-images.githubusercontent.com/1213122/184925535-a69216bc-e781-47b5-be71-1a60313f1152.mov

**Comment by mili-l** [comment]
@vlad20012 
Also `Find usages` works incorrectly 

https://user-images.githubusercontent.com/1213122/184925936-02ecd1ac-0896-4480-8282-c282d73cb4d6.mov

**Comment by mili-l** [comment]
see https://github.com/intellij-rust/intellij-rust/pull/9729
