### ISSUE TITLE
Regression in new engine for Rust macro expansion?

### ISSUE THREAD

**Issue by christophgockel** [intellij-rust/intellij-rust#8193]
## Environment

* **IntelliJ Rust plugin version:** 0.4.156.4145-212
* **Rust toolchain version:** 1.56.1 (59eed8a2a 2021-11-01) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.2.2 (CL-212.5284.51)
* **Operating system:** macOS 11.6
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

I think I've identified a regression in the "new engine" used for macro expansion in Rust.

<img width="882" alt="error" src="https://user-images.githubusercontent.com/190137/143854546-469ac975-5366-4ac2-a381-d929594da2d3.png">

The error appears when using `thiserror` and trying to use the `Display` trait of a matched error as seen in the picture above.

Thank you and have a great day,

Christoph

P.S.: I have also created this as a YouTrack issue (https://youtrack.jetbrains.com/issue/CPP-27550) because I used CLion's "Submit a Bug Report" feature before I saw the "Create new (Rust) issue".

## Steps to reproduce

I have created an example repository available at https://github.com/christophgockel/jetbrains-rust-macro-expansion-issue-example

You can switch between the old and new engine (Settings -> Languages & Frameworks -> Rust) and see the error disappear/appear.

**Comment by vlad20012** [comment]
Try to enable `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` experimental feature via the corresponding dialog. To open the dialog, just invoke `Help | Find Action` action and type `Experimental features`

**Comment by CxdInitial** [comment]
> Try to enable `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` experimental feature via the corresponding dialog. To open the dialog, just invoke `Help | Find Action` action and type `Experimental features`

Not working for me.

**Comment by CxdInitial** [comment]
error messsage: [`Error`](https://docs.rs/mongodb/2.0.2/mongodb/error/struct.Error.html) doesn't implement `Display` (required by {})

**Comment by christophgockel** [comment]
> Try to enable `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` experimental feature via the corresponding dialog. To open the dialog, just invoke `Help | Find Action` action and type `Experimental features`

Thank you for taking a look, Vlad!
I tried enabling both features but unfortunately the error remains the same.

**Comment by snaggen** [comment]
I just enabled these experimental features and restarted IntelliJ, and now I do not have these errors any more. So it seems to work with latest intellij rust and these experimental features.

**Comment by christophgockel** [comment]
I can confirm what @snaggen said. After upgrading to plugin version `0.4.164.4409-212` the reported issue doesn't appear anymore. At the time of writing this is not the very latest version of the plugin, but one that does fix the issue. I assume that every version since also includes the fix.

Thanks everyone!

**Comment by Undin** [comment]
Let's keep it open since procedural macro expansion is not enabled by default yet
