### ISSUE TITLE
Implement struct intention should handle generic impls

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#820]
if you have

```
struct <T: Copy> Foo where T: Default {

}
```

the intention should generate an impl like

```
impl <T: Copy> Foo<T> where T: Default {

}
```

cc #800 / @Litarvan

**Comment by Litarvan** [comment]
I'll try to work on that, shouldn't be hard

**Comment by matklad** [comment]
Fixed in https://github.com/intellij-rust/intellij-rust/commit/07ca8b4d496ea98a82d3738ffb63ef7182a3e5cc

https://zippy.gfycat.com/CarefulCoarseAnt.webm
