### ISSUE TITLE
Jump to Definition and Code Completion not working for aws_sdk_ec2::Client

### ISSUE THREAD

**Issue by webern** [intellij-rust/intellij-rust#8201]
## Environment

* **IntelliJ Rust plugin version:**

0.4.160.4261-212

* **Rust toolchain version:**

1.56.0

* **IDE name and version:**

CLion 2021.2.1
Build #CL-212.5080.54, built on August 24, 2021
Runtime version: 11.0.11+9-b1504.16 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 6144M
Cores: 16

* **Operating system:**

macOS 10.15.7

## Problem description

When using a [specific dependency](https://crates.io/crates/aws-sdk-ec2/0.0.26-alpha), I am unable to
- jump to definition
- use code completion for certain types provided by the library

## Steps to reproduce

Cargo.toml

```toml
[package]
name = "untitled25"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "0.0.26-alpha"
aws-types = "0.0.26-alpha"
aws-sdk-ec2 =  "0.0.26-alpha"
```

main.rs

```rust
use aws_config::profile::ProfileFileCredentialsProvider;
use aws_types::config::Config;
use aws_types::credentials::SharedCredentialsProvider;
use aws_types::region::Region;

fn main() {
    let region = Region::new("us-west-2".to_owned());
    let profile = SharedCredentialsProvider::new(
        ProfileFileCredentialsProvider::builder()
            .profile_name("default")
            .build(),
    );
    let client = aws_sdk_ec2::Client::new(
        &Config::builder()
            .region(region.clone())
            .credentials_provider(profile)
            .build(),
    );
    println!("Hello, world!");
}
```

This compiles, however the `aws_sdk_ec2::Client` type is not understood by the plugin.

![image](https://user-images.githubusercontent.com/6260372/143945575-f930735c-c303-4ca8-be7f-15f07b8527e7.png)

And code completion does not work:

![image](https://user-images.githubusercontent.com/6260372/143945728-6e757f9d-9e64-4222-b0bd-b8afa8258490.png)

**Comment by webern** [comment]
It's worth noting that the symbol that fails comes from a large code file https://github.com/awslabs/aws-sdk-rust/blob/main/sdk/ec2/src/client.rs

**Comment by Mach1212** [comment]
Fix is described in https://intellij-support.jetbrains.com/hc/en-us/articles/206544869.

To have Intellij recognize the Client class:
1. Open Help > Edit Custom Properties.
2. Add in idea.max.intellisense.filesize=5000.

This will have Intellij recognize the class but all the methods in the class will be hidden, as my Intellij even with 12g of heap allocated can not open the class and use intellisense without running out of ram.

I wish jetbrains had an option to just view structure.

**Comment by webern** [comment]
> as my Intellij even with 12GB of heap allocated can not open the class and use intellisense without running out of ram.

How do you detect the out of ram condition? I don't see any errors or warnings. Do you have to look at the logs?

(Actually, I haven't tried increasing the maximum file size yet, maybe when I try that I will see OOM errors.)

**Comment by Mach1212** [comment]
Your right, I haven't let it get to that point yet, but it is very interesting to see the vm gradually take more and more ram in task manager. I stopped it when my pc got to 88% (14GB by intellij)ram usage.

**Comment by webern** [comment]
When I increase the maximum file size and memory limit, then the problems I experiencing when having these huge sourcecode files in my dependency tree seem to expand in scope to general performance issues. I've heard from people that worked on the AWS Rust SDK that they have had to switch from JetBrains to VSCode as a result of these issues. Apparently Rust Analyzer is able to handle these large crates.

**Comment by digitalsanctum** [comment]
For anyone else that runs into this, as of aws-sdk-ec2 v0.5.2 the client file is over 5MB. I had to add the following to `idea.properties` to get things working:
```
idea.max.content.load.filesize=8000
idea.max.intellisense.filesize=8000
```
via `Help > Edit Custom Properties...`

By default the `idea.max.content.load.filesize` value is 2MB.

**Comment by digitalsanctum** [comment]
I just ran into this again in latest EAP:

CLion 2023.1 Beta
Build #CL-231.8109.80, built on March 15, 2023
