### ISSUE TITLE
The macro block does not show variable types

### ISSUE THREAD

**Issue by zhuxiujia** [intellij-rust/intellij-rust#8214]
## Environment

* **IntelliJ Rust plugin version:**
v0.4.160.4261-212

## Problem description

In Macro's expr, the variable type does not predict and show ```  let v: i32 = 1; ```

But if you write it in a main function instead of a macro, this is normal.

```rust
#[macro_export]
macro_rules! ff {
    // for free spawn
    ($func:expr) => {{
        $func()
    }};
    }

fn main() {
     ff!(move || {
        println!("hi, I'm parent");
        let v = 1;
    });
}
```

<img width="374" alt="Screenshot 2021-12-03 at 11 31 24" src="https://user-images.githubusercontent.com/1213122/144588042-c44b7708-4189-4595-8f54-20762739fd0e.png">

**Comment by zhuxiujia** [comment]
Will this be fixed?

**Comment by vlad20012** [comment]
Most likely this will not be done in the near future.
