### ISSUE TITLE
Treat commas and semicolons as punctuators

### ISSUE THREAD

**Issue by alygin** [intellij-rust/intellij-rust#822]
Now, commas and semicolons are treated as operators and are not highlighted. Vast majority of the known to me IntelliJ language plugins separate those symbols and highlight them as keywords. I think it would be convenient to move commas and semicolons (and something else?) into a different group called _punctuators_ and use the keywords-style highlighting for it.

Before:

<img width="492" alt="screen shot 2016-12-08 at 20 59 08" src="https://cloud.githubusercontent.com/assets/2101250/21021452/9978e9d4-bd89-11e6-91eb-3c22ad19e8d8.png">

After:

<img width="486" alt="screen shot 2016-12-08 at 20 57 29" src="https://cloud.githubusercontent.com/assets/2101250/21021446/94048b02-bd89-11e6-8117-1b5233905490.png">

**Comment by mkaput** [comment]
There are separate platform text attribute keys for these guys: https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/colors/RustColors.kt#L52-L54

**Comment by alygin** [comment]
Yep, I saw those color settings. But when it comes to highlighting, this branch works for commas and semicolons because they are `RustOperatorTokenType`: https://github.com/intellij-rust/intellij-rust/blob/bb9acde13645abef5c8da9422719794bb1118da4/src/main/kotlin/org/rust/ide/highlight/RustHighlighter.kt#L24

**Comment by mkaput** [comment]
Oh I see, so yeah; it's a bug

**Comment by alygin** [comment]
They, I guess, we can just move those two lines (with `RustOperatorTokenType` and `RustOperatorTokenType` ) down to the bottom of the `when` block and that will be enough. No need for a new token type group.

**Comment by mkaput** [comment]
possibly yup
