### ISSUE TITLE
async_trait cannot be properly indexed

### ISSUE THREAD

**Issue by tisonkun** [intellij-rust/intellij-rust#8221]
## Environment

* **IntelliJ Rust plugin version:** 0.4.160.4261-212
* **Rust toolchain version:** nightly-2021-11-16-x86_64-apple-darwin
* **IDE name and version:** CLion 2021.2.3
* **Operating system:** Darwin 19.6.0 Darwin Kernel Version 19.6.0: root:xnu-6153.141.40.1~1/RELEASE_X86_64 x86_64

## Problem description

A trait defined with `async_trait` cannot be properly indexed.

![image](https://user-images.githubusercontent.com/18818196/144692488-f510d870-c4b0-4360-9d2b-14a5a36510b2.png)

![image](https://user-images.githubusercontent.com/18818196/144692496-40420d0a-f238-429f-b0a3-125a239e7d8c.png)

I check that if the trait is a plain trait without cfg as `async_trait`, this problem vanishies.

## Steps to reproduce

As pictures are shown above, you can clone the [engula/engula](https://github.com/engula/engula) project and check `src/journal/src/stream.rs` defines `Stream` trait with `async_trait`, which is implemented by `src/journal/src/grpc/stream.rs` but cannot be indexed.

The `Stream` trait is exported in `lib.rs` and it's a regression from some previous Intellj Rust plugin version. I encountered this issue with an upgrade.

**Comment by Undin** [comment]
Fixed by #8183
