### ISSUE TITLE
Autocompletion does not show methods for type expanded from `sqlx` macro

### ISSUE THREAD

**Issue by longfellowone** [intellij-rust/intellij-rust#8236]
## Environment

* **IntelliJ Rust plugin version:** 0.4.161.4292-213
* **Rust toolchain version:** rustc 1.59.0-nightly (0fb1c371d 2021-12-06)
* **IDE name and version:** Clion 2021.3 #CL-213.5744.254
* **Operating system:** Windows 10 and OSX Monterey

* **org.rust.cargo.evaluate.build.scripts:** Enabled
* **org.rust.macros.proc:** Enabled

## Problem description

Macros for sqlx::query! and sqlx::query_as! are not expanding correctly. Showing wrong methods. 

https://docs.rs/sqlx/latest/sqlx/macro.query_as.html
https://docs.rs/sqlx/latest/sqlx/query/struct.QueryAs.html
https://docs.rs/sqlx/latest/sqlx/macro.query.html
https://docs.rs/sqlx/latest/sqlx/query/struct.Query.html

![Untitled](https://user-images.githubusercontent.com/36570412/145061375-6d476a0b-fedf-4634-b971-ba371a191d15.png)

When using "Show recursive macro expansion" I get the following 

```rs
{
    {
        #[allow(clippy::all)] {
            use ::sqlx::Arguments   as _;
            let query_args = <sqlx::postgres::Postgres as ::sqlx::database::HasArguments>::Arguments::default();
            ::sqlx::query_with::<sqlx::postgres::Postgres, _>("SELECT id, name FROM projects", query_args).try_map(|row: sqlx::postgres::PgRow| {
                use ::sqlx::Row   as _;
                let sqlx_query_as_id = row.try_get_unchecked::<sqlx::types::Uuid, _>(0usize)?;
                let sqlx_query_as_name = row.try_get_unchecked::<String, _>(1usize)?;
                Ok(Project { r#id: sqlx_query_as_id, r#name: sqlx_query_as_name })
            })
        }
    }
}
```

## Steps to reproduce

https://github.com/longfellowone/rustpluginerr

`git clone https://github.com/longfellowone/rustpluginerr.git`

`docker-compose up -d`

`cargo install sqlx-cli`

`sqlx migrate run`

In Clion enable experimental features
`org.rust.cargo.evaluate.build.scripts`
`org.rust.macros.proc`

**Comment by vlad20012** [comment]
Thanks for the full example project!

As I can see, this is not a proc macro bug, it's a bug in autocompletion/type inference. I'll fix it

**Comment by vlad20012** [comment]
The issue is fixed in the nightly plugin. You can try it now (see [instructions](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly))

**Comment by longfellowone** [comment]
> 

Working good now! thanks for the quick fix 👍
