### ISSUE TITLE
Proc macro not expanding correctly, Access is denied. (os error 5)

### ISSUE THREAD

**Issue by longfellowone** [intellij-rust/intellij-rust#8238]
## Environment

* **IntelliJ Rust plugin version:** 0.4.161.4292-213
* **Rust toolchain version:** rustc 1.59.0-nightly (0fb1c371d 2021-12-06)
* **IDE name and version:** Clion 2021.3 #CL-213.5744.254
* **Operating system:** Windows 10 and OSX Monterey

* **org.rust.cargo.evaluate.build.scripts:** Enabled
* **org.rust.macros.proc:** Enabled

## Problem description

Macros for sqlx::query! and sqlx::query_as! are not expanding correctly. Recieving the following error when using "Show recursive macro expansion" on both windows and mac

Note: When opening Clion on windows I instead chose "Run as administrator" this error disappears and I then get the following error -> #8236

```rs
{
    ::std::compile_error!("failed to open path target\\sqlx\\query-e7f6c011776e8db7cd330b54174fd76f7d0216b612387a5ffcfb81e6f0919683.json: Access is denied. (os error 5)" )
}
```

## Steps to reproduce

https://github.com/longfellowone/rustpluginerr

`git clone https://github.com/longfellowone/rustpluginerr.git`

`cd rustpluginerr`

`git checkout d771b883e9633fd508e144efd211373d60e68d52`

`docker-compose up -d`

`cargo install sqlx-cli` (If not already installed)

`sqlx migrate run`

`org.rust.cargo.evaluate.build.scripts` (Enable in Clion experimental features)

`org.rust.macros.proc` (Enable in Clion experimental features)

After project has finish indexing - In `main.rs` click `query_as!` then ALT+ENTER `Show recursive macro expansion`

You can toggle `SQLX_OFFLINE` in the `.env` (will need to restart/re-index after change)

With `SQLX_OFFLINE=false` (or commented out) you get the error above

With `SQLX_OFFLINE=true` you get the error below. (Note `DATABASE_URL` has been set in .env)

```
{
    ::std::compile_error!("`DATABASE_URL` must be set, or `cargo sqlx prepare` must have been run and sqlx-data.json must exist, to use query macros" )
}
```

**Comment by bjorn3** [comment]
Can you check the permissions of `target\sqlx\query-e7f6c011776e8db7cd330b54174fd76f7d0216b612387a5ffcfb81e6f0919683.json`? You can use `icacls target\sqlx\query-e7f6c011776e8db7cd330b54174fd76f7d0216b612387a5ffcfb81e6f0919683.json` in a terminal to show the permissions.

**Comment by longfellowone** [comment]
> Can you check the permissions of `target\sqlx\query-e7f6c011776e8db7cd330b54174fd76f7d0216b612387a5ffcfb81e6f0919683.json`? You can use `icacls target\sqlx\query-e7f6c011776e8db7cd330b54174fd76f7d0216b612387a5ffcfb81e6f0919683.json` in a terminal to show the permissions.

On mac and getting the following.. - Will update with windows info shortly

```
{
    ::std::compile_error!("Read-only file system (os error 30)" )
}
```

Using `ls -l` in `/target`
```
-rw-r--r--   1 matt  staff  177  6 Dec 18:52 CACHEDIR.TAG
drwxr-xr-x  10 matt  staff  320 12 Dec 09:16 debug
drwxr-xr-x   5 matt  staff  160  6 Dec 20:05 sqlx
```

In `/target/sqlx`
```
-rw-r--r--  1 matt  staff  441  6 Dec 20:05 query-7902699be42c8a8e46fbbb4501726517e86b22c56a189f7625a6da49081b2451.json
-rw-r--r--  1 matt  staff  441  6 Dec 20:05 query-894243b471347e14a3dd89c217ebada3cba746aa0af3f3f066d69aa40f8ee638.json
-rw-r--r--  1 matt  staff  441  6 Dec 20:03 query-ab655502a32efebfbaadf7aab62569bfdc3dd59dfd4fc86613fa1382fe2ec5da.json
```

**Comment by vlad20012** [comment]
It looks like the `Steps to reproduce` setup is not enough to reproduce the issue. I guess, offline sqlx is needed

**Comment by longfellowone** [comment]
> It looks like the `Steps to reproduce` setup is not enough to reproduce the issue. I guess, offline sqlx mode is needed.
> 
> UPD: or not needed. Oh, I need proc macro debugging feature...

Do you happen to have `DATABASE_URL` set somewhere else?

I have update the example repo. run `git pull`

With the latest commit to the example repo I am now getting 

```
{
    ::std::compile_error!("`DATABASE_URL` must be set, or `cargo sqlx prepare` must have been run and sqlx-data.json must exist, to use query macros" )
}
```

`DATABASE_URL` is set in the `.env` file. I seems Clion is not able to read the variable when expanding the macro?

**Comment by vlad20012** [comment]
I think I figured out what the problem is

**Comment by vlad20012** [comment]
The issue is fixed in the nightly plugin. You can try it now (see [instructions](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly))

**Comment by longfellowone** [comment]
> The issue is fixed in the nightly plugin. You can try it now (see [instructions](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly))

Working good now, thanks!
