### ISSUE TITLE
Line comment starting at block level

### ISSUE THREAD

**Issue by alexander-irbis** [intellij-rust/intellij-rust#825]
With `Comment with Line Comment` action (`Ctrl+Slash`) it makes such commented lines with a comment starting at the begin of a line:
```rust
fn example(u: u8) -> char {
    match u {
//        0 => 'a',
//        1 => 'b',
        _ => '_',
    }
}
```
And then, after copy-paste or any other action followed by code formatting, it transforms into
```rust
fn example(u: u8) -> char {
    match u {
        //        0 => 'a',
        //        1 => 'b',
        _ => '_',
    }
}
```
So, the consistent behaviour for `Comment with Line Comment` action would be comments, starting at block level
```rust
fn example(u: u8) -> char {
    match u {
        // 0 => 'a',
        // 1 => 'b',
        _ => '_',
    }
}
```

**Comment by x-ji** [comment]
Is this solved with #1972 ? Currently the comments still seem to be inserted at the first column, instead of spaces consistent with the original indentation.
