### ISSUE TITLE
it seems expand derive proc macro is broken

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#8270]
## Environment

* **IntelliJ Rust plugin version:** 0.4.162.4305-213-nightly
* **Rust toolchain version:** rustc 1.59.0-nightly (6bda5b331 2021-12-12)
* **IDE name and version:** Clion 2021.3
* **Operating system:** Archlinux

## Problem description
When trying to `show single macro expansion`, it reports

> Failed to expand the macro: a procedural macro error occurred: failed to load macro: Cannot create expander for /home/sherlock/.cache/JetBrains/CLion2021.3/tmp/intellij-rust/proc_macros/libkube_derive-a656afa89c9451ed.so.d2cf617b2d166c0ad8a3fe7c2933a1845214a654.so: Io(Custom { kind: InvalidData, error: "only metadata version 5 is supported, section header was: [114, 117, 115, 116, 0, 0, 0, 6]" })

![image](https://user-images.githubusercontent.com/10096425/145839700-11bba390-c566-46f1-b508-e80a606e9e47.png)

the derive proc macro is https://docs.rs/kube/0.65.0/kube/derive.CustomResource.html

## Steps to reproduce

1. try to expand a derive proc macro by `show single macro expansion`

**Comment by vlad20012** [comment]
It is really broken on the latest nightly. As a workaround, you can use stable or some previous nightly
