### ISSUE TITLE
--color=always causes issues on Linux when trying to pass through arguments using Cargo

### ISSUE THREAD

**Issue by juszczakn** [intellij-rust/intellij-rust#829]
There appears to be an issue trying to use Cargo's pass through arguments.

Under `Additional Arguments` under a run configuration, to pass CLI arguments to the binary you are trying to run, you need to separate Cargo's parameters from your binary's parameters with `--` (two dash's).

However it seems that `--color=always` on Linux is dynamically added to the end of the list of arguments passed to Cargo. This means that in this case, the argument is instead passed to the binary instead of Cargo.

Given `Additional Arguments`: `--bin numfmt -- --help`

Output:

```
/home/<user>/.cargo/bin/cargo run --bin numfmt -- --help --color=always
    Finished debug [unoptimized + debuginfo] target(s) in 0.2 secs
     Running `target/debug/numfmt --help --color=always`
numfmt: error: Unrecognized option: 'color'.

Process finished with exit code 1
```

Added here: https://github.com/intellij-rust/intellij-rust/pull/801/files#diff-5420463ef1508e0dd1db9c82ad7a823eR86

Looks like it could be fixed by just prepending instead of appending, or looking for the existence of `--`.

**Comment by matklad** [comment]
Fixed by https://github.com/intellij-rust/intellij-rust/pull/828.

Should be in nightly today and in alpha tomorrow!

**Comment by alygin** [comment]
Until the fix is published, there's a workaround: just add `--color=never` manually as an additional argument in your run configuration. So, your arguments will look like this:

    --color=never --bin numfmt -- --help

In this case, the plugin won't add it's own copy of the argument.

**Comment by matklad** [comment]
Or just use the build from the master branch: https://teamcity.jetbrains.com/repository/download/IntellijIdeaPlugins_Rust_CurrentIdea_TestsRust/.lastSuccessful/intellij-rust-0.1.0.%7Bbuild.number%7D.zip (download the archive and install via **Install plugin from disk** action in the IDE.

**Comment by juszczakn** [comment]
I saw there were no unit tests added for this. I had the fix locally and was writing some, should I send a PR with tests?

**Comment by matklad** [comment]
Yep, a test would be very welcome! Keep in mind that we run CI on windows as well though.

**Comment by sanmai-NL** [comment]
@juszczakn: have you come around to adding a test, or should it be picked up by someone else?
