### ISSUE TITLE
Error notification is not resized

### ISSUE THREAD

**Issue by mili-l** [intellij-rust/intellij-rust#8314]
## Environment

* **IntelliJ Rust plugin version:** 0.4.163.4322-213-nightly
* **Rust toolchain version:** 1.59.0-nightly (0b42deacc 2021-12-09) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.3 (CL-213.5744.254)
* **Operating system:** macOS 11.5.1
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
Error notification is not resized

## Steps to reproduce

1. Create a new binary project
2. Edit main.rs run configuration and specify some missing file in "Redirect input from" field
3. Enter full screen
4. Run the configuration
5. Exit full screen

## Actual Results

<img width="1027" alt="Screenshot 2021-12-21 at 12 58 08" src="https://user-images.githubusercontent.com/1213122/146934151-08131967-5602-4a52-95ab-2cb873072363.png">

**Comment by Undin** [comment]
@mili-l I don't think it's related to the plugin at all

**Comment by mili-l** [comment]
https://youtrack.jetbrains.com/issue/IDEA-290416
