### ISSUE TITLE
Having a proc-macro=true crate in the workspace breaks most IDE features

### ISSUE THREAD

**Issue by thurn** [intellij-rust/intellij-rust#8328]
## Environment

* **IntelliJ Rust plugin version:** 0.4.162.4321-213
* **Rust toolchain version:** 1.57.0 (f1edd0429 2021-11-29) aarch64-apple-darwin
* **IDE name and version:** CLion 2021.3.1 (CL-213.6461.46)
* **Operating system:** macOS 12.1
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
If you include a crate with proc-macro=true in your workspace, many parts of the plugin stop working. If you clone the linked example project, you will see e.g. that

1) Name resolution seems completely broken, random sequences of characters do not get flagged as errors
2) Type checking is broken, e.g. `8 + vec![];` is not flagged as an error
3) Import errors are not reflected, e.g. deleting a `use` statement has no effect

## Expected Behavior
I expect the generated types `MyEnumKind` and `DerivedStruct` to work like normal name resolution in `main.rs`, to get suggested as completion examples, to have type errors if they are not present, etc.

## Steps to reproduce

Open this example project: https://github.com/thurn/intellij-rust-example/

**Comment by vlad20012** [comment]
Could you please describe in more detail what goes wrong in the example? Please, attach some screenshots, if possible. 
I my case, everything works as expected:
https://user-images.githubusercontent.com/3221931/147267434-51e64c50-0bf8-433a-8b9a-59423d1282cf.mp4

**Comment by vlad20012** [comment]
> Name resolution seems completely broken, random sequences of characters do not get flagged as errors

It is not flagged as an error regardless of the `org.rust.macros.proc` feature.

> Type checking is broken, e.g. 8 + vec![]; is not flagged as an error

It is not flagged as an error regardless of the `org.rust.macros.proc` feature.

> Import errors are not reflected, e.g. deleting a use statement has no effect

It has no effect regardless of the `org.rust.macros.proc` feature.


Could you please retry these cases with disabled `org.rust.macros.proc` feature?

**Comment by vlad20012** [comment]
If the issue is just about the absence of errors and does not really relate to proc macros, then you can find [this answer](https://github.com/intellij-rust/intellij-rust/issues/6932#issuecomment-794535903) useful.

**Comment by thurn** [comment]
Hm, it does seem to be working again for me -- I'll keep an eye out for consistently reproducible issues with proc macros. Is there a way to dump some logs for more debugging information?

**Comment by vlad20012** [comment]
> Is there a way to dump some logs for more debugging information?

You can do it by `Help` | `Collect Logs and Diagnostic Data`
