### ISSUE TITLE
Unresolved reference: `Result` 

### ISSUE THREAD

**Issue by megalodon12879** [intellij-rust/intellij-rust#8329]
## Environment

* **IntelliJ Rust plugin version:** 0.4.162.4321-213
* **Rust toolchain version:** 1.57.0 (f1edd0429 2021-11-29) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2021.3 Community Edition (IC-213.5744.223)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.evaluate.build.scripts

## Problem description

Hello,

the IDE does not seem to be able to resolve references to some std packages like Result or thread.

## Steps to reproduce

pub fn run_test() -> Result<(), std::io::Error> {
    Ok(())
}

**Comment by megalodon12879** [comment]
<img width="737" alt="unresolved_ref" src="https://user-images.githubusercontent.com/96597836/147293378-e9ac6c77-e104-4231-9abd-b7527b2b7c17.png">

**Comment by vlad20012** [comment]
It looks like the plugin can't find the stdlib source. Do you use Rustup?

**Comment by megalodon12879** [comment]
rustup is not available on windows. I'm using rus-init.exe

**Comment by megalodon12879** [comment]
rust-init.exe

**Comment by megalodon12879** [comment]
it was working with intellij 2021.2 and rust 1.55. then I updated to intellij 2021.3 with rust 1.57. now it's broken

**Comment by vlad20012** [comment]
It seems that since `2021.2` we have not changed anything related to this. Hmm

Could you please attach your IDE logs? You can do it by `Help` | `Collect Logs and Diagnostic Data`

**Comment by megalodon12879** [comment]
OK I saw in the logs that I have a newtork issue related to http proxy.

I will fix it first

thanks

**Comment by megalodon12879** [comment]
it works thanks
