### ISSUE TITLE
Regression: change signature window does not show types 

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#8330]
## Environment

* **IntelliJ Rust plugin version:** 0.4.163.4328-213-nightly
* **Rust toolchain version:** 1.57.0 (f1edd0429 2021-11-29) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.3.1 (CL-213.6461.46)
* **Operating system:** macOS 11.4
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
In 2021.3 (see environment), type of parameters are shown only after clicking on the field:

https://user-images.githubusercontent.com/49211026/147345153-162b1686-0650-4ad7-88ca-d1a7a8e3adaf.mov

Same problem with default values of new parameters

in 2021.1 it is ok:
<img width="749" alt="изображение" src="https://user-images.githubusercontent.com/49211026/147344838-7d388b42-1c7e-46f4-83e6-d0e0586713c7.png">
* **IntelliJ Rust plugin version:** 0.4.156.4145-211
* **Rust toolchain version:** 1.57.0 (f1edd0429 2021-11-29) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.1.3 (CL-211.7628.27)

**Comment by dima74** [comment]
cc @Kobzol

**Comment by Kobzol** [comment]
@dima74 Well, to be honest, I'm not sure what to do here. I tried to go through the dialog step by step, comment out various parts of code, check the Java implementation if they are doing something that we're not, but I can't find the problem. Is it possible to find out what has changed in the base upstream change signature dialog implementation in 2021.3?

**Comment by dima74** [comment]
@Kobzol Here are changes in [`ChangeSignatureDialogBase`](https://github.com/JetBrains/intellij-community/commits/master/platform/lang-impl/src/com/intellij/refactoring/changeSignature/ChangeSignatureDialogBase.java), but I don't find anything suspicious there

**Comment by neonaot** [comment]
Interesting facts: 
in 2022.1 (CL-221.3427.90 and IU-221.3427.89) the window works fine with 164 stable plugins. 
in 2021.3.3 (CL-213.6777.58) information still is not displayed.

**Comment by dima74** [comment]
@neonaot could you please check 2022.2 version? If it works there, I guess we can close the issue

**Comment by neonaot** [comment]
I can't find any problems 👍
