### ISSUE TITLE
Formatter inlines [#macro_use] on crates and functions

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#834]
Before:
```rust
#[macro_use(foo, bar)]
extern crate baz;

#[macro_use]
mod baa;
```

After formatter:
```rust
#[macro_use(foo, bar)] extern crate baz;

#[macro_use] mod baa;
```

While I couldn't find anything specific about this case in the [Rust style guide](https://aturon.github.io/style/whitespace.html), I does seem contrary to how examples are used in [the book](https://doc.rust-lang.org/beta/book/macros.html#scoping-and-macro-importexport).

**Comment by mkaput** [comment]
We have a switch in that which is on by default. We implemented it this way as such style is used among rustc code base and some users requested it; at least as far as I remember.

**Comment by johnthagen** [comment]
@mkaput Thanks for the tip about the configuration option.

According to https://github.com/rust-lang-nursery/fmt-rfcs/issues/36#issuecomment-258712854 it has been decided that `#[macro_use]` be treated like any other attribute and should not be inlined.

I would therefore propose that the default for `intellij-rust` be to not inline as well.
