### ISSUE TITLE
Nested macros don't get expanded in IDE method hints

### ISSUE THREAD

**Issue by Caellian** [intellij-rust/intellij-rust#8344]
## Environment

* **IntelliJ Rust plugin version:** 0.4.163.4330-213-nightly
* **Rust toolchain version:** 1.57.0 (f1edd0429 2021-11-29)
* **IDE name and version:** CLion 2021.3.2 build #CL-213.6461.75
* **Operating system:** Linux

## Problem description

IntelliJ Rust doesn't properly resolve recursive macros in function suggestions:

![Screenshot from 2021-12-29 08-06-58](https://user-images.githubusercontent.com/4082795/147636196-8d9322cf-800b-42a6-80aa-363756ff5292.png)

![Screenshot from 2021-12-29 05-37-04](https://user-images.githubusercontent.com/4082795/147627822-3dd84f7f-f5c9-4280-b3ba-1dd084d9f1d0.png)

![Screenshot from 2021-12-29 05-16-04](https://user-images.githubusercontent.com/4082795/147627296-c877ed56-c2ba-4d65-a230-805f6ce6fff2.png)

I believe all of these use the same code in your impl, so I reported them as one issue.

## Expected behavior

Hints from the above image should show `int` instead of `example_type!()` for first image,
and `value: Vec2` for the latter two images as `component_value!(translation)` expands to `Vec2`.

## Minimal example

```rust
macro_rules! example_type {
    () => {int};
}

macro_rules! minimal_example {
    () => {
        pub fn example_func(arg: example_type!()) {
            println!("minimal example: {}", arg);
        }
    };
}

minimal_example!();

fn using_macro_gen_code() {
    example_func(2);
}
```

**Comment by es50678** [comment]
### Environment
IntelliJ Rust plugin version: 0.4.162.4321-213
Rust toolchain version: 1.57.0 (f1edd0429 2021-11-29)
IDE name and version: IntelliJ IDEA 2021.3.1 (Ultimate Edition) Build #IU-213.6461.79
Operating system: MacOS 12.0.1

I'm pretty sure i'm seeing the same thing:

I see type hints for methods coming from macros in vscode but not in intelij.
VSCODE:
![image](https://user-images.githubusercontent.com/17823824/147699376-98ec2252-f9be-41a8-ae2b-204675ecb86d.png)


Intelij IDEA Ultimate: 
![image](https://user-images.githubusercontent.com/17823824/147699396-5d3b815b-470e-4986-b1f3-949286064e0a.png)

**Comment by Caellian** [comment]
There is difference @es50678 as in your case the behavior is caused by a `clap` **attribute macro** not being handled properly.

There's a [tracking issue](#6908) for attribute macro support. #7170 seems related to your problem.

**Comment by es50678** [comment]
@Caellian got it. thank you.

**Comment by mili-l** [comment]
see https://github.com/intellij-rust/intellij-rust/pull/9729
