### ISSUE TITLE
Any and all functionality chokes with winapi crate

### ISSUE THREAD

**Issue by novacrazy** [intellij-rust/intellij-rust#835]
I'm working with the [winapi](https://crates.io/crates/winapi) crate on some DirectX stuff, and as I'm writing this IntelliJ has been frozen at 100% CPU usage for about ten minutes after I right clicked on a type. 

After testing this a few times with the smaller parts of the winapi crate, I know that it is actually doing work, not just stuck in a loop, but it just seems to take forever to do anything with it.

Additionally, it doesn't seem to cache any of the results, so everytime I right click on any winapi types it takes that same ten or more minutes to pop up the context menu.

I've tried increasing the amount of memory IntelliJ can use via the vmoptions files, but that doesn't make a difference. 

I'm using IntelliJ Idea 2016.3.1 and the latest IntelliJ-rust plugin, for reference.

**Comment by matklad** [comment]
>the latest IntelliJ-rust plugin

The latest nightly or the latest alpha?

**Comment by novacrazy** [comment]
Version 0.1.0.1264

Updating to nightly now to see if that helps.

**Comment by novacrazy** [comment]
No change with with nightly.

**Comment by matklad** [comment]
Thanks! And what is the version of the winapi crate? It would be helpful to see some short sample that is hard for IntelliJ. We actually [do test](https://github.com/intellij-rust/intellij-rust/blob/55ceafff0752676a3deabb0bdf2eeb0b3451c8ba/src/test/kotlin/org/rust/cargo/toolchain/CargoProjectResolveTest.kt#L26-L28) win api, but looks like you've hit another difficult case :)

**Comment by matklad** [comment]
Hm, there were no new updates to winapi-rs.

**Comment by novacrazy** [comment]
winapi 0.2.8

I'll see if I can get a isolated test case. I'm using it in conjunction with about a 16K LOC + deps program I've been working on for a couple months, so hopefully an isolated test case is possible.

**Comment by novacrazy** [comment]
Oh, and with about six IntelliJ Idea projects open at once, if that makes any difference. Until winapi, it's worked pretty great.

**Comment by novacrazy** [comment]
Alright, here we go:

```rust
extern crate winapi;

use winapi::*;
use dxgi::*;

use std::mem::zeroed;

fn main() {
    let test: DXGI_SWAP_CHAIN_DESC = unsafe { zeroed() };

    println!("Hello, world!");
}
```

Managed to lock up IntelliJ with just that code. In fact, I probably could have done it without the `zeroed` part. Just right clicking on `DXGI_SWAP_CHAIN_DESC` does it.

Two things to note: 
* I did not specific `extern crate dxgi`, but it doesn't matter because I did do that in my real code.
* After I did the two `winapi` and `dxgi` imports, I did the `std::mem` import, and as I was typing it there was no autocompletion, even after multiple tries. If I removed the winapi imports, autocomplete worked.

**Comment by novacrazy** [comment]
Were you able to recreate this by any chance?

**Comment by matklad** [comment]
Yes, I've recreated the problem and working on the fix. The fix involves rethinking the resolve infrastructure unfortunately :(

**Comment by novacrazy** [comment]
Well, good luck. This project is much appreciated.

**Comment by matklad** [comment]
Okey, so it should be a bit faster now.
