### ISSUE TITLE
Old Rust projects still visible in `Sync`

### ISSUE THREAD

**Issue by atanas-w** [intellij-rust/intellij-rust#8368]
## Environment

* **IntelliJ Rust plugin version: 0.4.162.4321-212**
* **Rust toolchain version: 1.59.0-nightly**
* **IDE name and version: IntelliJ IDEA Ultimate 2021.2.4**
* **Operating system: Win 10**

## Problem description

I have several small Rust/Cargo projects in different subfolders in a single IntelliJ project. In the past I had a few more that I deleted long ago, but they are still present in the `Sync` tab:

![image](https://user-images.githubusercontent.com/31915500/148454844-daf52beb-4609-45d9-aeaf-51143e9d800a.png)

I can't find a way to get rid of the old projects there.

**Comment by vlad20012** [comment]
You can delete them from the [cargo tool window](https://plugins.jetbrains.com/plugin/8182-rust/custom-pages/docs/rust-cargo-tool-window.html)

![image](https://user-images.githubusercontent.com/3221931/132379407-6a9cd725-2285-4a59-af3f-56b0fa8250b6.png)

**Comment by atanas-w** [comment]
Thanks, Vlad!
That works for me.
I'm not sure if it would be a good idea for old projects to be automatically removed. I see pros and cons to that. Anyway, I'm closing this issue.
