### ISSUE TITLE
Document cannot be found

### ISSUE THREAD

**Issue by Borber** [intellij-rust/intellij-rust#8381]
## Environment

* **IntelliJ Rust plugin version:** 0.4.162.4321-213
* **Rust toolchain version:**  stable-x86_64-pc-windows-msvc (default) rustc 1.57.0 (f1edd0429 2021-11-29)
* **IDE name and version:** Clion 2021.3.2
* **Operating system:** Windows 10 LTSC 19044.1415

## Problem description

When I tried to run and rewrite the [sixtyfps demo](https://github.com/sixtyfpsui/sixtyfps-rust-template), I found that Clion did not recognize it and linked the documentation

![image](https://user-images.githubusercontent.com/30563826/148743687-524f85b1-5f4f-463b-8e0c-042cbfbc4d6a.png)

But when I use vscode with rust-analyzer, they work fine

![image](https://user-images.githubusercontent.com/30563826/148743913-cf6164ca-ef73-41bd-abae-02fb53f48305.png)

Did I forget to set something, or is there a bug?

## Steps to reproduce

Clone and launch https://github.com/sixtyfpsui/sixtyfps-rust-template

**Comment by Undin** [comment]
> Did I forget to set something, or is there a bug?

@Borber https://github.com/sixtyfpsui/sixtyfps-rust-template generates Rust code from `ui/appwindow.60` file during compilation. Generated code is included into project via `sixtyfps::include_modules!()` using `SIXTYFPS_INCLUDE_GENERATED` environment variable.
Currently, the IntelliJ Rust plugin doesn't evaluate build scripts by default and doesn't take the corresponding info (generated `SIXTYFPS_INCLUDE_GENERATED` env variable in this particular case) during analysis. But you can enable `org.rust.cargo.evaluate.build.scripts` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features) to make it work as expected. Note, it forces the plugin to build the whole project to evaluate build scripts on each project model update so it may require more resources

See #1908 for more details

**Comment by Borber** [comment]
> > Did I forget to set something, or is there a bug?
> 
> @Borber https://github.com/sixtyfpsui/sixtyfps-rust-template generates Rust code from `ui/appwindow.60` file during compilation. Generated code is included into project via `sixtyfps::include_modules!()` using `SIXTYFPS_INCLUDE_GENERATED` environment variable. Currently, the IntelliJ Rust plugin doesn't evaluate build scripts by default and doesn't take the corresponding info (generated `SIXTYFPS_INCLUDE_GENERATED` env variable in this particular case) during analysis. But you can enable `org.rust.cargo.evaluate.build.scripts` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features) to make it work as expected. Note, it forces the plugin to build the whole project to evaluate build scripts on each project model update so it may require more resources
> 
> See #1908 for more details

He's working now! , Great! Thank you.
