### ISSUE TITLE
Regression: type inference of return values of Container<Fn>

### ISSUE THREAD

**Issue by qiujiangkun** [intellij-rust/intellij-rust#8385]
## Environment

* **IntelliJ Rust plugin version:** 0.4.162.4321-213
* **Rust toolchain version:** 1.59.0-nightly (e012a191d 2022-01-06) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.3.2 (CL-213.6461.75)
* **Operating system:** Linux 5.15.12-1-manjaro
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
```rust
#[test]
fn test_regression() {
    struct X<T> {
        x: Arc<dyn Fn() -> T>,
    }
    let x = X { x: Arc::new(|| 1) };
    let x = (x.x)();
    let y = Arc::new(|| 1);
    let y = y();
    let z = Box::new(|| 1);
    let z = z();
}
```

## Steps to reproduce
![image](https://user-images.githubusercontent.com/33482468/148775953-4f648257-b5f6-4e0b-a58b-877382afba5f.png)

All of `x`, `y` and `z` should be inferred as i32

**Comment by dima74** [comment]
Hi @qiujiangkun! Looks like it was fixed some time ago. Could you confirm it?

![image](https://user-images.githubusercontent.com/6505554/180872373-d3b1117a-a7e2-4540-b370-fe55da512254.png)

**Comment by qiujiangkun** [comment]
Yes, it seems fixed now
