### ISSUE TITLE
Attach file to module fails with keyword-like names

### ISSUE THREAD

**Issue by KisaragiEffective** [intellij-rust/intellij-rust#8445]
## Environment

* **IntelliJ Rust plugin version:** 0.4.161.4292-213
* **Rust toolchain version:** 1.57.0 (`cargo --version`)
* **IDE name and version:** Intellij Ultimate 2021.3
* **Operating system:** Linux FRONTIERDT 5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 (`uname -snrv`)

## Problem description
It shouldn't be allowed that creating new directory in src folder that cannot be used as `mod` name because it may be cause of confusing.

## Steps to reproduce
1. Create new Project
2. Create directory in `src` with name `macro`
4. Create file as `src/macro.rs`
5. Open `src/macro.rs`
6. Choose `Attach file to main.rs` in `src/macro.rs`
7. Will see Could not create `mod macro`

**Comment by Undin** [comment]
@KisaragiEffective Actually, you can attach such modules. Just use [raw identifiers](https://doc.rust-lang.org/rust-by-example/compatibility/raw_identifiers.html)
I.e. the plugin should insert `mod r#macro;` in the corresponding case
