### ISSUE TITLE
Parameter Hints

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#847]
Since Rust doesn't ([yet](https://internals.rust-lang.org/t/pre-rfc-named-arguments/3831)) have named arguments, borrowing the new [Parameter Hints](https://www.youtube.com/watch?v=ZfYOddEmaRw) feature from IntelliJ 2016.3 would be a pretty awesome feature.

**Comment by alygin** [comment]
We had a short discussion of this feature [here](https://github.com/intellij-rust/intellij-rust/pull/803#issuecomment-264381545). As far as I understand, we need to wait for the new API to stabilise, and for 2016.3 to become the oldest supported version. Though I'm not sure about the latter. Maybe there's a way to support some features for only particular platform versions?

**Comment by matklad** [comment]
Superseded by https://github.com/intellij-rust/intellij-rust/issues/1141
