### ISSUE TITLE
Incorrect type deduction with Iterator

### ISSUE THREAD

**Issue by MatrixDev** [intellij-rust/intellij-rust#8470]
## Environment
* IntelliJ Rust plugin version: 0.4.163.4378-212
* Rust version: rustc 1.58.0 (02072b482 2022-01-11)
* Rust toolchain version: stable-aarch64-apple-darwin
* IDE name and version: Android Studio Chipmunk | 2021.2.1 Canary 7 (Build #AI-212.5457.46.2112.8043657, built on January 5, 2022)
* Operating system: macOS Monterey 12.1

## Problem description
Type deduction does work when "impl" is used but doesn't when "when" is used for Iterator but code compiles in both cases.

## Steps to reproduce
Types are not deduced, suggestions on `child` don't work but code compiles:
```rust
    fn delegate_traversed<'a, I, T>(&mut self, event: &GestureEvent, children: I)
        where
            I: Iterator<Item=&'a T>,
            T: 'a + RenderObject + ?Sized,
    {
        for child in children {
            // child -> unknown
            // children -> I
        }
    }
```
![image](https://user-images.githubusercontent.com/1215187/151153448-1807e759-21e4-4750-aaeb-991bcba8bf25.png)

Types are deduced, suggestions on `child` work and code compiles:
```rust
    fn delegate_traversed<'a, T>(&mut self, event: &GestureEvent, children: impl Iterator<Item=&'a T>)
        where
            T: 'a + RenderObject + ?Sized,
    {
        for child in children {
            // child -> &T
            // children -> impl Iterator<Item=&T>
        }
    }
```
![image](https://user-images.githubusercontent.com/1215187/151153517-4959bbed-0a35-4e75-9de1-933c2a6d3086.png)

**Comment by Undin** [comment]
It seems fixed in the latest plugin version
@MatrixDev Does it work for you now?

**Comment by MatrixDev** [comment]
@Undin, yeap, it is fixed now. thanks.
