### ISSUE TITLE
Doesn't show autocomplete for struct

### ISSUE THREAD

**Issue by dodalovic** [intellij-rust/intellij-rust#8480]
The Latest IntelliJ Ultimate and the rust plugin. Linux Ubuntu 21.10

![image](https://user-images.githubusercontent.com/6358061/151528852-619fe24a-e1c3-4a5b-81e7-12f5312cc860.png)

**Comment by dodalovic** [comment]
Vsode:

![image](https://user-images.githubusercontent.com/6358061/151529302-d147e684-c02c-455e-9d91-1e26487b5db8.png)

**Comment by dima74** [comment]
Hi @dodalovic! I can't reproduce it with the latest plugin version. Does the issue still persist? Could you provide full source code please?

![image](https://user-images.githubusercontent.com/6505554/180871564-025330a3-d27d-4d91-b159-6a90da68dd17.png)

**Comment by dodalovic** [comment]
Feel free to close. Thx
