### ISSUE TITLE
No autocompletions from stdlib in scratch files

### ISSUE THREAD

**Issue by yerke** [intellij-rust/intellij-rust#8487]
When you edit Rust scratch files, the autocompletions do not work properly.

See screenshot for example:
![Screen Shot 2022-01-30 at 9 12 22 PM](https://user-images.githubusercontent.com/5137691/151742271-5ee24f95-0bf4-481f-b4c6-eecb3a917683.png)

Linking https://github.com/intellij-rust/intellij-rust/issues/2437 for running scratch files for better visibility.

**Comment by cherryleafroad** [comment]
I'd support autocompletions in my plugin, but my plugin is as best a hack on top of this plugin, plus I don't know the system very well (this is a complex plugin). It'd be best to just officially support scratches, which I'm sure would also (finally) benefit from autocompletions at that point

**Comment by dima74** [comment]
Autocompletion in scratch files was added in #9459
Other code insight (such as auto-import) is tracked in #8853
