### ISSUE TITLE
Enable "Single instance" by default on Cargo tasks

### ISSUE THREAD

**Issue by nathanaeljones** [intellij-rust/intellij-rust#849]
Some context:

I use unit and integration tests, and cargo compiles these in parallel processes (AFAIK). So while I receive errors (and all that I will ever get) usually within the first 5-8 seconds of executing 'cargo check' or 'cargo test' (a bit longer), the build process will not self-terminate for 20-60 seconds.

Correcting syntax errors usually requires no more than 3-5 seconds, so nearly all of my builds involve Ctrl+F10, (oops, "Blocking waiting for file lock on build directory") Ctrl+F2, down arrow, enter, Ctrl+F10. I don't usually notice the 4px green circle reliably enough to hit Ctrl+F2 *before* Ctrl+F10. 

Sadly, I've been doing this since June 2016. As I'm writing this, I discover that "single instance" works and does what I need. Cue headdesk and renewed determination to learn IntelliJ itself. 

Given that "single instance" offers a "Stop and rerun" prompt (and is unlikely to be surprising behavior). I'm wondering if "Single Instance" shouldn't be enabled by default?  AFAIK, all common cargo tasks block on the build directory.

**Comment by matklad** [comment]
Yeah, that's a good idea, but unfortunately looks like it's not possible to change this default from the plugin code.

**Comment by matklad** [comment]
Wait, I could have not been more wrong, this is utterly trivial to fix!
