### ISSUE TITLE
Sometimes the External Linter needs Environment Variables

### ISSUE THREAD

**Issue by webern** [intellij-rust/intellij-rust#8503]
## Environment

* **IntelliJ Rust plugin version:**  0.4.164.4409-213
* **Rust toolchain version:** 1.58.1
* **IDE name and version:** CLion 2021.3.3
Build #CL-213.6777.58, built on January 31, 2022 
* **Operating system:** Linux 5.13.0-28-generic

## Problem description

I need to be able to pass environment variables (and CARGO_HOME) to the external linter.
Some builds (e.g. via build.rs) require environment variables to function correctly.
For example: https://github.com/bottlerocket-os/bottlerocket/blob/ff15b91c1965df3433cc2e887e7537197a6170e2/sources/models/build.rs#L47

We need to be able to set environment variables (including CARGO_HOME) here:

![image](https://user-images.githubusercontent.com/6260372/152228088-41dc370d-715c-41c6-af47-cc3ed64aa583.png)

## Steps to reproduce

- Clone the bottlerocket project https://github.com/bottlerocket-os/bottlerocket
- Open Clion/Rust in the sources directory
- Use cargo check as your external linter

**Comment by vlad20012** [comment]
Hmm, `CARGO_HOME` is usually set globally, so `CARGO_HOME` should be set for CLion itself and be inherited by cargo launched from CLion.

Other envs could be configured by `[env]` section of [`.cargo/config.toml`](https://doc.rust-lang.org/cargo/reference/config.html), but I agree that sometimes it can be useful to add some envs in the IDE settings

**Comment by webern** [comment]
> Hmm, `CARGO_HOME` is usually set globally, so `CARGO_HOME` should be set for CLion itself and be inherited by cargo launched from CLion.

Actually a fair number of our projects with more complicated builds will set a CARGO_HOME to a directory inside the project, e.g. `.cargo`. We often do this in a makefile.  (Sometimes this has to do with docker mounts, other times it has to do with installing something like cargo deny and wanting to do that in-tree instead of on a user's system).

Thus it would be helpful to be able to set a CARGO_HOME for linters and any other cargo/rustc processes that the plugin will run. Otherwise I end up flailing where the changing CARGO_HOME env causes rebuilds instead of incremental builds.

I can set CARGO_HOME (and any other environment variables) for run configurations, but not for the external linters.

The workaround of `.cargo/config.toml` is good to know about, but not ideal since that may be checked in and used by the project which explicitly does *not* want to set certain build-time variables in that file.

**Comment by alvinsay** [comment]
+1

When running `carge check` for a project depending on OpenSSL, it might require `OPENSSL_LIB_DIR` and `OPENSSL_INCLUDE_DIR` to be set.
