### ISSUE TITLE
Slice content is not shown while debugging

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#8519]
## Environment

* **IntelliJ Rust plugin version:** 0.4.165.4420-213-nightly
* **Rust toolchain version:** 1.58.1 (db9d1b20b 2022-01-20) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.3.3 (CL-213.6777.58)
* **Operating system:** macOS 11.4
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Expanding a slice shows `length` and `data_ptr` - no actual content.

## Steps to reproduce

```rust
fn main() {
    let foo = &[1, 2, 3];
    for bar in foo.windows(2) {
        println!("{:?}", bar);  // breakpoint
    }
}
```

<img width="1175" alt="data_ptr" src="https://user-images.githubusercontent.com/2500320/152689635-26dd09c0-8dc0-41ce-bac9-b70913f9ba04.png">

**Comment by sihaixianyu** [comment]
I found this problem doesn't exist in rust-analyzer. It seems like that IntelliJ Rust didn't provide analysis for slice content.
