### ISSUE TITLE
Project syncing is obtrusive

### ISSUE THREAD

**Issue by Jomy10** [intellij-rust/intellij-rust#8536]
## Environment

* **IntelliJ Rust plugin version:** 0.4.164.4409-213
* **Rust toolchain version:** cargo 1.58.0 (7f08ace4f 2021-11-24)
* **IDE name and version:** IntelliJ IDEA CE 2021.3.1 (Build #IC-213.6461.79)
* **Operating system:** MacOS Monterey 12.1

## Problem description
This happens a lot where I am coding in Rust, and all of a sudden I get interrupted by the Sync tab in the build window. It moves my focus from my code to the window, and the window pops up at the bottom of the screen. This makes for a very unpleasant experience. Below I have attached a video to illustrate this.

## Steps to reproduce
This usually happens when adding a new dependency to `Cargo.toml`.

https://user-images.githubusercontent.com/62475953/153299087-6a0afffb-a195-4e49-aee4-1b172d886791.mp4

**Comment by paul-hansen** [comment]
Happens for me mostly when editing cargo.toml

https://user-images.githubusercontent.com/7019130/155899372-72cdf5f1-046d-466d-b3b2-d4aa78b57663.mp4

Interestingly I just discovered that if I close the code on the right so there are no .rs files open in the foreground, editing the cargo.toml file only causes a sync when a save is triggered (as it should). Seems like when there are rust files open, typing in the cargo.toml is aggressively triggering a cargo sync which makes it near impossible to type a dependency sometimes.

**Comment by afetisov** [comment]
The aggressive sync is expected: without syncing the cargo project it would be impossible to resolve features and dependencies. You can disable it via `Settings > Languages & Frameworks > Rust > Cargo > Update project automatically`, but I would not recommend it.

The sync window, however, is indeed needlessly obtrusive. The project sync also breaks code completion while it happens (each iteration of macro expansion resets the completion dialogue).

**Comment by Undin** [comment]
> each iteration of macro expansion resets the completion dialogue

JFTR, all macro expansion steps were merged into a single one in #8647. Kudos to @dima74 and @vlad20012

**Comment by spikespaz** [comment]
Can we get an update on this? I would like to not need to type at 120WPM just to edit my manifest.

**Comment by paul-hansen** [comment]
I recently discovered that disabling "Run external linter to analyze code on the fly" makes it work as expected at least for me using the latest clion version. Obviously not ideal because I really like clippy's lints, just mentioning in case it helps track down the problem.

**Comment by spikespaz** [comment]
Squeaky wheel gets the oil. This is a high priority issue, developers!

**Comment by LoganDark** [comment]
The external linter setting is causing the `Cargo.toml` to randomly save and trigger a sync which is incredibly annoying when I am **actively typing to add a dependency**. Screw this, linter off. Code correctness is less important than my sanity.

**Comment by spikespaz** [comment]
Yes but both are important and I trust the rust community as a whole, and they have chosen to mutually contribute to clippy. It's time to fix this issue.

**Comment by bit-void** [comment]
@LoganDark just want to echo this issue. Incredibly frustrating when trying to edit dependencies. I have to go to vim outside of intellij to do so.

**Comment by Undin** [comment]
BTW we recently turned on a new approach how the plugin detects project model changes and reloads the project model. It includes more granular settings when the plugin invoke `Sync` process. See #9012 for more details. I suppose it should solve this issue

To try it, you need:
- 2022.2 IDE (currently, in Beta stage)
- nightly version of plugin since the stable version with this change is not released yet. See [instruction](https://plugins.jetbrains.com/plugin/custom-pages/docs/rust-quick-start.html#install-nightly) how to install it. Or wait next stable release, which will be landed in around two weeks

**Comment by bit-void** [comment]
This seems to be fixed in 2022.2 + latest. Thank you!

**Comment by LoganDark** [comment]
> BTW we recently turned on a new approach how the plugin detects project model changes and reloads the project model. It includes more granular settings when the plugin invoke `Sync` process. See #9012 and #8919 for more details. I suppose it should solve this issue
> 
> To try it, you need:
> 
>    * 2022.2 IDE (currently, in Beta stage)
> 
>    * nightly version of plugin since the stable version with this change is not released yet. See [instruction](https://plugins.jetbrains.com/plugin/custom-pages/docs/rust-quick-start.html#install-nightly) how to install it. Or wait next stable release, which will be landed in around two weeks

Finally, this has been supported by Gradle in IDEA since forever, I didn't know CLion didn't support it until 2022.2 :(. Was finally able to update and this is fixed! Thank you!

**Comment by Jomy10** [comment]
Looks like this has been solved for everyone. I'll close this issue now.
