### ISSUE TITLE
No way to specify a channel for Sync

### ISSUE THREAD

**Issue by big-lip-bob** [intellij-rust/intellij-rust#8537]
## Environment
* IntelliJ-Rust version: `0.4.164.4409-213`
* Rust toolchain: `1.60.0-nightly`
* IDE: CLion 2021.3.3
* OS: Arch Linux

## Problem
There is no way _?_ to change the channel Sync (`cargo metadata`) uses without changing the default toolchain (impossible _?_ with targets without toolchains / support such as some embedded ones), which is problematic when working with nightly/unstable features, such as for example, the `strip` setting in `cargo.toml`
Due to that failed Sync, nothing really works (besides syntax coloring)

![image](https://user-images.githubusercontent.com/41026257/153299777-aa81345f-08bd-40b3-ab47-c374ed2656ec.png)

**Comment by Undin** [comment]
@big-lip-bob did you try to [override](https://rust-lang.github.io/rustup/overrides.html) toolchain for your project?

**Comment by big-lip-bob** [comment]
Thanks for pointing it out, now i look stupid for missing out on that, already had a `.cargo/config.toml` and totally forgot about toolchain overrides.
