### ISSUE TITLE
External linter show outdated results, acts unpredictably

### ISSUE THREAD

**Issue by otwieracz** [intellij-rust/intellij-rust#8541]
## Environment

* **IntelliJ Rust plugin version:** 0.4.164.4409-213
* **Rust toolchain version:** 1.58.1 (db9d1b20b 2022-01-20) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.3.2 Ultimate Edition (IU-213.6777.52)
* **Operating system:** macOS 12.2.1
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.macros.proc

## Problem description

In last weeks I started seeing issues with external linter. It's acting completely unpredictably, shows outdated results, sometimes it seems like it takes long time for it to catch on changes - but next moment, it detects updates immediately.

I don't really know how to describe this problem better - I'd post those two screenshot and I'd be glad for any suggestions how to debug this further.

<img width="1726" alt="Screenshot 2022-02-10 at 23 25 23" src="https://user-images.githubusercontent.com/108072/153508477-7b4b4f8d-a626-46c1-b02c-696def1a2630.png">
<img width="1712" alt="Screenshot 2022-02-10 at 23 37 07" src="https://user-images.githubusercontent.com/108072/153508485-830368dc-b15c-4bbd-be17-9e2b81a671ae.png">

**Comment by otwieracz** [comment]
Quite often opening "Problems" tab triggers *something* causing errors to be re-evaluated.

**Comment by otwieracz** [comment]
Bump? I am the only one with such issues? Any clues how to debug that? It's currently impossible to work with Rust using IntelliJ for me.

**Comment by szymski** [comment]
Similar to my problem #8698, however my problem occurs only when more than one Rust file is opened. In your case this happens also when a single file is opened?

**Comment by Parth** [comment]
I've been having this issue for as long as I can remember (at-least 18 months)

**Comment by Parth** [comment]
I'd be happy to just discover a keystroke I can hit to reevaluate everything
