### ISSUE TITLE
Include documentation tests

### ISSUE THREAD

**Issue by konstin** [intellij-rust/intellij-rust#855]
Rust allows adding examples and other code snippets in block comments which is called [documentation tests](https://doc.rust-lang.org/nightly/book/testing.html#documentation-tests). Those snippets are compiled and executed by `cargo test`. Therefore, those snippet should be treated as normal code with all the syntax highlighting, inspections and refactorings being applied to them.

Here's an example:
```rust
/// Use Foo to do bar
/// 
/// # Examples
/// ```rust
/// Foo::new()->bar(); // This is actual code that can and will be run
/// ```
struct Foo {

}
```

**Comment by alygin** [comment]
Looks like a duplicate of #618

**Comment by konstin** [comment]
Yep, you're right.
