### ISSUE TITLE
methods called `from_*` usually take no self; consider choosing a less ambiguous name

### ISSUE THREAD

**Issue by SilvaQ** [intellij-rust/intellij-rust#8551]
what is this about from_*:

```rust
pub trait Alphabet {
   fn from_ug(&self, word: &str) -> String;
}
```
<img width="709" alt="image" src="https://user-images.githubusercontent.com/46706370/153695699-d5eeae37-25d8-4460-ab5c-406f2fcc276e.png">

_Originally posted by @SilvaQ in https://github.com/intellij-rust/intellij-rust/issues/8352#issuecomment-1036980011_

**Comment by Kobzol** [comment]
This corresponds to the `wrong_self_convention` Clippy lint (https://rust-lang.github.io/rust-clippy/master/#wrong_self_convention). Methods beginning with `from` usually do not taky any `self` parameter, since they serve as "constructors" from some other type.

**Comment by SilvaQ** [comment]
@Kobzol Thanks
