### ISSUE TITLE
Unambiguous import ignores re-exports

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#8560]
## Environment

* **IntelliJ Rust plugin version:** 0.4.165.4438-213
* **Rust toolchain version:** 1.60.0-nightly (a00e130da 2022-01-29) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.3.3 (CL-213.6777.58)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description

Unambiguous import ignores re-exported symbols and uses full paths.

## Steps to reproduce

1. Create a module `a`.
2. Create a submodule `a::b`.
3. Create a symbol in `a::b`, e.g. `struct Widget;`.
4. Re-export `Widget` in `a`: `pub use crate::a::b::*`.
5. Create another module outside `a` and try to use `Widget` - the resulting automatic import will be `use crate::a::b::Widget` instead of `use crate::a::Widget`.

**Comment by dima74** [comment]
@krojew Hi! Could you please provide the full source code or screencast? Probably I am doing something wrong, but I can't reproduce the issue with those steps:

![Peek 2022-02-15 14-13](https://user-images.githubusercontent.com/6505554/154051345-f1285ea9-1ea2-47c1-b6ef-53f366b5f15c.gif)

**Comment by krojew** [comment]
@dima74 you're using manual import. I'm talking about the new automatic import feature.

**Comment by dima74** [comment]
@krojew I still [can't reproduce](https://user-images.githubusercontent.com/6505554/154052720-4d9c333a-0fcf-4332-b0aa-8226a3c35812.gif) unfortunately - could you please provide the full source code or screencast?

**Comment by krojew** [comment]
Unfortunately, this is closed source, so I can't.

**Comment by dima74** [comment]
Maybe it is possible to create a reproduction example based on your codebase. I am afraid we can't do much here without it

**Comment by dima74** [comment]
@krojew do you still experience the problem?
