### ISSUE TITLE
Applying linter suggestion removes valid code

### ISSUE THREAD

**Issue by krojew** [intellij-rust/intellij-rust#8575]
## Environment

* **IntelliJ Rust plugin version:** 0.4.165.4438-213
* **Rust toolchain version:** 1.60.0-nightly (a00e130da 2022-01-29) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.3.3 (CL-213.6777.58)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description

Running clippy and applying suggestion with certain lint leads to code destruction.

## Steps to reproduce

Run clippy on:

```
pub fn generate(
        &self,
        configuration: &BiomeGenerationConfiguration,
        width: usize,
        height: usize,
    ) -> Array2D<Tile> {
        let mut tiles = Array2D::filled_with(configuration.base_tile, height, width);
        tiles
    }
```

The result will be:

`Returning the result of a let binding from a block`

After applying suggestion:

```
pub fn generate(
        &self,
        configuration: &BiomeGenerationConfiguration,
        width: usize,
        height: usize,
    ) -> Array2D<Tile> {
        
        tiles
    }
```

**Comment by neonaot** [comment]
Thanks for the report! 
I want to add that clippy offers a correct change, so the problem is really on the plugin side  
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/49211026/154701107-107ff935-c050-465b-bba1-602c50238dba.png">
```
struct S {}

impl S {
    pub fn foo(&self) -> i32 {
        let mut x = 566;
        x
    }
}
```
