### ISSUE TITLE
Declarative macro expansion not working on recursive macro

### ISSUE THREAD

**Issue by bruno-ortiz** [intellij-rust/intellij-rust#8589]
## Environment

* **IntelliJ Rust plugin version:0.4.165.4438-213**
* **Rust toolchain version: 1.58.1**
* **IDE name and version:Clion 2021.3.3**
* **Operating system: Windows 11**

## Problem description
When declaring routes  using the axum(0.4.5) web server, the rust plugin does not recognize the functions that were created using the  `top_level_handler_fn!` macro.

![image](https://user-images.githubusercontent.com/5748995/155019776-4e123c5e-4b6f-479a-ae6f-df574fa73b3f.png)

In the image above the IDE is able to recognize the `get` but not the `post`, same for the following image:
![image](https://user-images.githubusercontent.com/5748995/155021798-1ef8e9e3-8e2f-48b2-a14d-604cbbd00fba.png)

I think the problem might be related to the macro expansion engine. For example, here are 2 pictures showing the expanded macro for the `get` and for the `post` functions.

Expansion for the get function:
![image](https://user-images.githubusercontent.com/5748995/155023168-f8e24a8f-00fc-4a44-831c-c10182b04578.png)

Expansion for the post function:
![image](https://user-images.githubusercontent.com/5748995/155023225-91be0b0f-7618-43c6-b47b-0960f2d7e915.png)

## Steps to reproduce

import axum = 0.4.5 and run the following code:

```rust
use std::net::SocketAddr;

use axum::routing::{get, post};
use axum::Router;

#[tokio::main]
async fn main() {
    let app = Router::new()
        .route("/login", get(login_get))
        .route("/login/complete", post(login_post));
    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap()
}

async fn login_get() -> &'static str {
    "Yay, it works"
}
async fn login_post() -> &'static str {
    "It compiles, but with no IDE support"
}
```

**Comment by SaadiSave** [comment]
I can confirm that this is reproducible as of CLion `2021.3.2`, Rust `1.59`, and IntelliJ-Rust `0.4.166.4486-213` on Ubuntu `20.04.4 LTS`

Are there any updates as to why this is happening? This is a simple declarative macro, not a procedural one.

P.S. rust-analyzer works.

**Comment by SaadiSave** [comment]
I have narrowed down the problem to failure recognising the `#[doc = concat!("Route `" , stringify!($name), "` requests to the given handler.")]` as valid syntax for some reason.

**Comment by SaadiSave** [comment]
Relevant youtrack issue: [IntelliJ Rust: Declarative macros in attributes are not expanded](https://youtrack.jetbrains.com/issue/CPP-28705)

**Comment by bruno-ortiz** [comment]
@dima74 @vlad20012 Since the last version of the plugin this issue seems to be fixed, so I'll close the issue for now.
