### ISSUE TITLE
Implement a list selector

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#859]
For `fn foo(a: i32, b: String)` it would be useful if semantic selection (`Ctrl+W`) could select all the arguments, but without parenthesis (how it is done in Kotlin):

```
fn foo(<selection>a: i32, b: String</selection>)
```

This can be done via `ExtendWordSelectionHandler`.

Here's the relevant code and tests in Kotlin:

https://github.com/JetBrains/kotlin/blob/master/idea/src/org/jetbrains/kotlin/idea/editor/wordSelection/KotlinListSelectioner.kt

https://github.com/JetBrains/kotlin/blob/master/idea/tests/org/jetbrains/kotlin/idea/WordSelectionTest.java

**Comment by zjhmale** [comment]
@matklad You mean `Extend Selection` and `Shrink Selection` in keymap right?

**Comment by matklad** [comment]
Yes

**Comment by mrhota** [comment]
@matklad looks like that PR implements this, so you can close this issue

**Comment by matklad** [comment]
Thanks @mrhota !
