### ISSUE TITLE
Support creating a library project

### ISSUE THREAD

**Issue by lu-zero** [intellij-rust/intellij-rust#861]
it should be just the same machinery in use (`cargo new`) with the additional `--lib`.

**Comment by devurandom** [comment]
This seems somewhat related to #876 and #736. A good start would already be if it could import existing projects (i.e. those that already have a `Cargo.toml`), instead of creating `CMakeLists.txt`.

**Comment by matklad** [comment]
This is handled by `org.rust.ide.idea.RsModuleBuilder` and `org.rust.ide.idea.CargoConfigurationWizardStep`.

**Comment by matklad** [comment]
This was fixed.
