### ISSUE TITLE
sea-orm ActiveModelBehavior

### ISSUE THREAD

**Issue by dodalovic** [intellij-rust/intellij-rust#8610]
IntelliJ reports this
![image](https://user-images.githubusercontent.com/6358061/155852412-372c1ab2-0776-4e39-9788-d2b931beae62.png)

In vscode, there's no issue here. 
In any case, everything works as expected, this is an issue with the rust plugin.

IntelliJ IDEA 2021.3.2 (Ultimate Edition)
Build #IU-213.6777.52, built on January 28, 2022
Subscription is active until October 14, 2022.
Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.23-76051523-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2400M
Cores: 16
Registry:
    ide.intellij.laf.enable.animation=true
    debugger.valueTooltipAutoShowOnSelection=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    org.toml.lang (213.5744.224)
    org.jetbrains.plugins.go-template (213.6777.8)
    org.jetbrains.plugins.go (213.6777.52)
    org.intellij.plugins.hcl (0.7.15)
    name.kropp.intellij.makefile (213.5744.224)
    light.flat.theme (0.14)
    com.intellij.nativeDebug (213.6461.6)
    org.jetbrains.kotlin (213-1.6.10-release-961-IJ6777.52)
    org.asciidoctor.intellij.asciidoc (0.37.5)
    org.rust.lang (0.4.165.4438-213)
    com.github.novotnyr.jwt-intellij-plugin (0.11)
    zielu.gittoolbox (212.8.5)
    com.mallowigi (54.1.0)
    com.intellij.kubernetes (213.6777.8)

Kotlin: 213-1.6.10-release-961-IJ6777.52
Current Desktop: pop:GNOME

**Comment by Undin** [comment]
@dodalovic Thanks for the report!
`sea-orm` crate heavily uses procedural macros. Unfortunately, the plugin doesn't expand them by default for now. As a result, the plugin doesn't see generated `impl` items that lead to false-positive error annotation.
But you can try to turn on `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` [experimental](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features) features to enable our experimental procedural macro expander. It should fix your issue

See #6908 for more details

**Comment by dodalovic** [comment]
@Undin Both features were already set to the values proposed.

**Comment by yashsamit** [comment]
I enabled two flags: org.rust.cargo.evaluate.build.scripts and org.rust.macros.proc in the experimental dialog of Ultimate Idea Ide and its working perfectly. I can Entity and its fns.

**Comment by lavrxxx** [comment]
Have the same issue with CLion 2021.3.4 and Rust Plugin 0.4.168.4555-213

**Comment by lavrxxx** [comment]
Also, I found empty line in inspector which belongs to this error

<img width="2056" alt="Screenshot 2022-04-14 at 8 54 46 AM" src="https://user-images.githubusercontent.com/23312691/163322713-58e016f7-2fe8-4aea-a3f5-986cf3373ad3.png">

**Comment by Undin** [comment]
@lavrxxx have you reloaded project model after enabling these options? You can do it via `Refresh Cargo Projects` action in Cargo tool window
<img width="278" alt="image" src="https://user-images.githubusercontent.com/2539310/163323254-f21b9426-bd43-4a61-9cb6-a2e9a518fd2d.png">

If so, and the corresponding error is still persisted, check expansion itself - via `Alt + Enter` or from context menu on `DeriveEntityModel` usage in `derive` attribute
<img width="338" alt="Screen Shot 2022-04-14 at 09 06 24" src="https://user-images.githubusercontent.com/2539310/163324124-b5c0a9d9-a0f1-45d9-9df5-e272292aae18.png">

<img width="574" alt="image" src="https://user-images.githubusercontent.com/2539310/163324093-9c7e5fb4-1e19-4b0f-bc43-e2efd874ca55.png">

**Comment by lavrxxx** [comment]
@Undin recursive macro expansion shows me that ActiveModelTrait is implemented

**Comment by lavrxxx** [comment]
Also I found that autocomplete is not working in structs while enabling experimental features
```
struct A {
    p
}
```
When you type `p` IDE doesn't show any variant, but if you ask about vervains all is working okay

**Comment by hyperluckemia** [comment]
Same problem raised on CLion 2022.1.1 on   both `org.rust.cargo.evaluate.build.scropts` and `org.rust.macros.proc` experimental featrues turned on, seams like that intellij rust plugin cannot resolve proc-macro like DeriveEntityModel macro from sea_orm_macros.
code example from sea-orm/examples/actix3_example/src/main.rs
`
#[post("/{id}")]
async fn update(
    data: web::Data<AppState>,
    id: web::Path<i32>,
    post_form: web::Form<post::Model>,
) -> actix_flash::Response<HttpResponse, FlashData> {
    let conn = &data.conn;
    let form = post_form.into_inner();

    post::ActiveModel {
        id: Set(id.into_inner()),
        title: Set(form.title.to_owned()),
        text: Set(form.text.to_owned()),
    }
    .save(conn)
    .await
    .expect("could not edit post");

    let flash = FlashData {
        kind: "success".to_owned(),
        message: "Post successfully updated.".to_owned(),
    };

    actix_flash::Response::with_redirect(flash, "/")
}
`
There is not entrance to jump to the Souce: 
![image](https://user-images.githubusercontent.com/62289641/172042585-5be547d9-6bbd-4f40-b90b-76715993be87.png)

**Comment by videah** [comment]
I can also confirm various aspects of code completion in Jetbrains IDE's is broken when it comes to SeaORM. CLion would argue that this shouldn't compile when it does.

<img width="673" alt="image" src="https://user-images.githubusercontent.com/4761786/180585263-fd549889-f5f5-450e-9c0f-0fa0385ace63.png">

**Comment by Toromyx** [comment]
This seems to be fixed in the latest version? (0.4.177.4844-222)
