### ISSUE TITLE
breakpoint doesn't work

### ISSUE THREAD

**Issue by nianxiaoyi** [intellij-rust/intellij-rust#8621]
Environment

IntelliJ Rust plugin version:  0.4.156.4145-211
Rust toolchain version:1.59.0
IDE name and version: idea 2021.1.3
Operating system: WIN10

I set breakpoint in a simple rust program, but the breakpoint does not stop when I start it in debug mode.
![image](https://user-images.githubusercontent.com/79825922/156169160-6ba8f4de-475c-416e-8cc8-a5f83988c10e.png)

![image](https://user-images.githubusercontent.com/79825922/156169404-c9f06171-f484-461c-93a3-e46b0e7f6938.png)

I had already installed native debugging support as the image below shows
![1646137353(1)](https://user-images.githubusercontent.com/79825922/156168478-20cef610-c874-430f-a176-6222520bfbfc.jpg)

**Comment by ortem** [comment]
@nianxiaoyi Thank you for reporting. This issue is probably a duplicate of #8526 because Rust 1.59.0 is already affected as well. The problem should be fixed in the coming CLion EAP. For now, you may try using Rust 1.58.0.

**Comment by ortem** [comment]
@nianxiaoyi The new CLion EAP build is available, see https://github.com/intellij-rust/intellij-rust/issues/8526#issuecomment-1059759448

**Comment by nianxiaoyi** [comment]
> 



> @nianxiaoyi The new CLion EAP build is available, see [#8526 (comment)](https://github.com/intellij-rust/intellij-rust/issues/8526#issuecomment-1059759448)

Hi @ortem  I use rustup-init to specify the version for rust toolchain installed，What is the version number for CLion EAP. is it just Clion EAP(for example, I set 1.58.0 for the version number)?

**Comment by ortem** [comment]
@nianxiaoyi For more clarity, at the moment, there are two different ways to make breakpoints work:
1. Use Rust 1.58.0, via running `rustup default 1.58.0-x86_64-pc-windows-msvc` command. Then breakpoints should work with any CLion version
2. Use CLion 2022.1 EAP build 221.4906.7, via downloading it from [the website](https://www.jetbrains.com/clion/nextversion/) or installing from JetBrains Toolbox (click the context menu of the installed CLion, choose `Other versions` and install the EAP build; [more information](https://www.jetbrains.com/toolbox-app/faq/)). Then breakpoints should work with any Rust version

**Comment by nianxiaoyi** [comment]
@ortem  Thanks for your reply
