### ISSUE TITLE
Tracking issue for `let_chains` support

### ISSUE THREAD

**Issue by HTG-YT** [intellij-rust/intellij-rust#8625]
As of https://github.com/rust-lang/rust/issues/53667, and PR https://github.com/rust-lang/rust/pull/88642, `let_chains` has been initially implemented.

Example syntax:
```rust
let something = Some(123);

if let Some(something_inner) = something && something_inner == 123 {
    println!("works");
}
```

The plugin does not support this feature yet, and this issue is the tracking issue for the implementation of support of the feature.

**Comment by HTG-YT** [comment]
Example of current behaviour:
![image](https://user-images.githubusercontent.com/39023054/156909941-b01a86b3-1d3e-44a3-99aa-639d15a84945.png)

**Comment by Kobzol** [comment]
I started working on this, but got stuck quite soon because of parsing precedence. Here:
```rust
if let <pat> = <expr> && let ...
```
the parser parses `&&` as a part of `<expr>`. We need the let condition to have precedence instead (see [this](https://github.com/rust-lang/rfcs/blob/master/text/2497-if-let-chains.md#dealing-with-ambiguity)).

I'm not sure whether this is expressible in GrammarKit directly or whether we need to write some Java/Kotlin parsing helper. In any case, any hints would be appreciated @vlad20012 :)

**Comment by vlad20012** [comment]
@Kobzol 

```
BoolAndBinOp     ::= andand !let { name = "operator" }
```

**Comment by afetisov** [comment]
Note that the feature is [quite likely to be stabilized](https://github.com/rust-lang/rust/pull/94927) in Rust 1.62, which is less than 3 months away.

**Comment by HTG-YT** [comment]
Now that [1.61 is released](https://blog.rust-lang.org/2022/05/19/Rust-1.61.0.html), 1.62 is right around the corner (after six weeks).

**Comment by afetisov** [comment]
The feature is still not stable, though. This means that at best it will land in 1.63, maybe later. So there are still several months to implement it.

**Comment by LoganDark** [comment]
Especially annoying is the fact that the automatic formatter completely trashes my if statements that use this feature:

![image](https://user-images.githubusercontent.com/4723091/173940885-ffdfe1e5-f9cb-46b3-a7dc-5ff0ab5c4ac0.png)

**Comment by HTG-YT** [comment]
Update: it is apparently stabilized in 1.64 (which is the current nightly).

**Comment by afetisov** [comment]
Is anyone working on this?

**Comment by Kobzol** [comment]
I started a draft in https://github.com/intellij-rust/intellij-rust/pull/8755, but it hasn't seen much action yet.

**Comment by HTG-YT** [comment]
Renamed the issue removing the feature flag segment to reflect the stabilization of `let_chains`.

**Comment by Directory** [comment]
any progress on this being implemented? 1.63 is now stable and stabilization of 1.64 is right around the corner.

**Comment by Kobzol** [comment]
Just FYI, Let chains will not be stabilized im 1.64, since a fundamental issue in its implementation was found.
 https://github.com/rust-lang/rust/pull/100538

**Comment by mchernyavsky** [comment]
Implemented in https://github.com/intellij-rust/intellij-rust/pull/8755.
