### ISSUE TITLE
test runner fails with long output

### ISSUE THREAD

**Issue by Sibz** [intellij-rust/intellij-rust#8626]
## Environment

* **IntelliJ Rust plugin version:** 0.4.167.4470-213-nightly
* **Rust toolchain version:** 1.60.0-nightly (75d9a0ae2 2022-02-16) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.3.3 (CL-213.6777.58)
* **Operating system:** Windows 11 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
while a test may pass, the test runner doesn't complete or display the output correctly, I think because of the long output, but not sure.

## Steps to reproduce

using text:
fail_json.txt = https://gist.github.com/Sibz/faa51a31d3a82960b406cba5efee1093
```rust
#[test]
fn json_test()
{
    println!("{}", include_str!("fail_json.txt"));
}
```
This results in:
![image](https://user-images.githubusercontent.com/12050358/156531574-810a2165-214b-4036-ace6-35ae17ff91af.png)
Where the output in the window is json instead of the log,
and the loading icon next to the test continuously.
Occasionally it succeeds, mostly does not.

using text:
success_json.txt = https://gist.github.com/Sibz/3214ac868bbec359606f90ae0267bf33
This is just a few lines shorter
```rust
#[test]
fn json_test()
{
    println!("{}", include_str!("success_json.txt"));
}
```
This runs without a hitch:
![image](https://user-images.githubusercontent.com/12050358/156532265-ebf99f32-cddf-48c3-8489-ba79ec1526e8.png)

**Comment by Undin** [comment]
@mchernyavsky I've managed to reproduce it on macos as well but with 4x more data in file

**Comment by gschulze** [comment]
Happens on my machine as well, when downgrading to version 0.4.164.4409-213, test output is shown correctly.

**Comment by Sibz** [comment]
Any insight on this? I'm having to use command line to run tests more often than not these days.
