### ISSUE TITLE
Use annotators instead of duplicating grammar rules

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#864]
In out `RustParser.bnf` file, there's a pattern repeated thrice, for `function`, `constant` and `type_alias`. 

A `fake` rule is defined to describe a single PSI element, and then a number of implementations (`elementType = bla-bla-bla`) of this rules are provide. The goal of this implementations is to enforce small syntactic differences. For example, top level functions always have body, but functions in interfaces can just end in `;`. 

A better way to handle this is to have exactly one non fake rule in `.bnf` and write a custom annotator which would say something like "top level functions must have a body, change `;` to `{}`?". See, how this is done in Kotlin: if you write `override fun foo()` at the top level, the PSI will containg a `FUN`, which would be annotated with two errors (an extra override and a missing body). 

So this issue is exactly about removing special casing in the parser and writing an annotator. The best place to start is `constant`, then `type_alias`. `function` might prove to be tricky, because different functions have different grammar for parameters ([I hate this](https://github.com/rust-lang/rfcs/pull/1685)). It might be useful to look at the Kotlin's annotator!

**Comment by alygin** [comment]
I'll take constants for starters. It looks like many of [these errors](https://github.com/intellij-rust/intellij-rust/issues/886) should also be handled by annotators, so it'll be a good practice.

**Comment by alygin** [comment]
BTW, what is the `default` contextual keyword referenced from many grammar rules but absent in the Rust docs? Is it extinct or did I neglect something important in the docs?

**Comment by matklad** [comment]
It's a part of specialization: https://github.com/rust-lang/rfcs/blob/master/text/1210-impl-specialization.md

The specialization hasn't hit stable yet, but we have to support it on the syntactic level because the standard library uses nightly features.

**Comment by alygin** [comment]
Oh, good to know. But why doesn't the grammar kit generate a field in `RustConstantElement` for it?

**Comment by matklad** [comment]
It's because `default` is generated by an external rule, and GrammarKit can't undestand external rules. The external rule itself is needed because the keyword is contextual, so we need to remap identifier to the keyword. 

You need to define `fun RustConstantElement.getDefault(): PsiElement? = findChildByType(RustTokenElementTypes.DEFAULT)` manually.

**Comment by alygin** [comment]
@matklad, could you, please, [have a look](https://github.com/alygin/intellij-rust/commit/a03d1d17f693c46056ebda3d4f76596cd4f444ef), if I got the idea correctly?

**Comment by alygin** [comment]
There's the `GeneratedParserUtilBase` class that is somehow meddling with parsing and adds errors that are supposed to be handled by the annotator. For instance, in the following snippet:

```rust
trait Foo {
    default const DEF_BAR: u16 = 9;
}
```

[it adds](https://github.com/intellij-rust/intellij-rust/blob/17e2b7a83ac4a2a4012d6d7feadf2364ebc61da4/src/main/java/org/rust/lang/core/parser/GeneratedParserUtilBase.java#L780) the error '`default` unexpected'. There're also other examples in traits and impl blocks. Is there a way to change this behaviour without breaking other things?

**Comment by matklad** [comment]
>Unify all those fn_parameters, foreign_fn_parameters,method_parameters and method_decl_parameters into a single rule and use a dedicated set of annotations to check them, and only after that unify various types of functions?

Yes, that would be ideal. This might be difficult though, because of the anonymous parameters. If you collapse `pat: type` and `type` into a single rule, the parser would have to use backtracking here (`foo::bar::baz` may be a part of a type, or a part of the pattern). Theoretically this shouldn't be be a problem for Grammar Kit, it backtracks by default. In practice, I expect a fair amount of gymnastics here.

**Comment by matklad** [comment]
@alygin any progress with functions? I can try to do this myself if grammar kit is to mysterious :)

**Comment by alygin** [comment]
No progress so far, unfortunately. The plan was to finish the simple duplication errors (done), then gain the understanding of all the parameter variety while finishing this issue and after that implement parameter names duplication detection.

So the parameters + functions refactoring is the next in my todo-list, but I can't make promises on how long it will take. If this work hampers the progress of something else, I can pass the baton back to you. Otherwise, I'll be glad to try to finish this off.

**Comment by matklad** [comment]
>No progress so far, unfortunately. 

Perfect! I want to do some renaming in that area of the parser, so there would not be any conflicts!

**Comment by matklad** [comment]
The same can be done to `VariantFieldDecl` \w `FieldDecl` and to `TupleFieldDecl` \w `VariantTupleFieldDecl`.

**Comment by matklad** [comment]
Thanks a lot @alygin !
