### ISSUE TITLE
Macros with encolsed function calls are not highlited

### ISSUE THREAD

**Issue by C0D3-M4513R** [intellij-rust/intellij-rust#8651]
## Environment

* **IntelliJ Rust plugin version:** 0.4.167.4478-213-nightly
* **Rust toolchain version:** 1.58.1 (db9d1b20b 2022-01-20) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.3.3 (CL-213.6777.58)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
If a Macro takes a function Call, it is not resolved if a macro is in a different file.
Edit: if the function Call returns a value, it then doesn't know the type of that variable. As a result, function-completion is unavailable.
![grafik](https://user-images.githubusercontent.com/28912031/157633402-1f333a97-2ecb-4edf-982e-a50c5b7d9e6f.png)

If you move the macro inside the file it is being used in, that resolves the issue temporarily.
That is not always possible. 
Another way to trick it into working is just creating a wrapper macro with the same name, that just always calls the real macro.

## Steps to reproduce

1. Open a new Project and paste my Non-highlited code example.
2. Add `edition="2018"` or `edition="2021"` to the Cargo.toml
3. Observe the highliting.

Non-highlited code:
```rust
mod macros{
	macro_rules! mac_test {
	    ($name:ident($($args:expr),*)) => {
		    $name($($args),*)
	    };
	}
	pub(crate) use mac_test;
}
use macros::mac_test;
fn t3es3t(){}
fn main() {
	mac_test!(t3es3t());
}
```
![grafik](https://user-images.githubusercontent.com/28912031/157614754-23f53858-195f-4d80-b739-1bbdc43d38ef.png)
Highlighted code:
```rust
mod macros{
	macro_rules! mac_test {
	    ($name:ident($($args:expr),*)) => {
		    $name($($args),*)
	    };
	}
	pub(crate) use mac_test;
}
macro_rules! mac_test {
	    ($name:ident($($args:expr),*)) => {
		    macros::mac_test($name($($args),*))
	    };
	}
fn t3es3t(){}
fn main() {
	mac_test!(t3es3t());
}
```

**Comment by cherryleafroad** [comment]
This happens in 2021 too. Actually, my function calls were shown sometimes, but not at other times. Not sure why.

But on a bigger note, I think it would be nice to highlight most of the code in a macro. (I have a huge impl inside a macro call, and basically none of it is highlighted at all, but it is in VSCode)
