### ISSUE TITLE
Language Settings is not refreshed for Rust after Rust plugin is just installed

### ISSUE THREAD

**Issue by mili-l** [intellij-rust/intellij-rust#8656]
## Environment

* **IntelliJ Rust plugin version:** 0.4.167.4478-221-nightly
* **Rust toolchain version:** 1.59.0 (9d1b2106e 2022-02-23) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2022.1 EAP Ultimate Edition (IU-221.4906.8)
* **Operating system:** macOS 11.5.1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
Language Settings is not refreshed for Rust after Rust plugin is just installed

## Steps to reproduce

1. Install CLion IDE
2. Run IDE  -> Welcome page is opened
3. Install Rust plugin from Welcome page -> plugin is installed
4. Go to Create New Project on the Welcome page
5. Choose Rust

## Expected Results
<img width="800" alt="Screenshot 2022-03-11 at 13 57 04" src="https://user-images.githubusercontent.com/1213122/157871219-c7a0b297-5488-42d0-96be-b0d06717274d.png">

## Actual Results
Language Settings is not refreshed for Rust
![Mar-11-2022 13-56-06](https://user-images.githubusercontent.com/1213122/157871329-94171722-24ba-427d-8c79-d287f4533db2.gif)

[4e784f4f-e2c1-4ccd-9a91-4033c1ae37ac-attachment.log](https://github.com/intellij-rust/intellij-rust/files/8232047/4e784f4f-e2c1-4ccd-9a91-4033c1ae37ac-attachment.log)

**Comment by Undin** [comment]
Actually, it's not related to Rust plugin itself. It's about stub Rust project generator implemented in CLion.
So I close it in favor of https://youtrack.jetbrains.com/issue/CPP-28771
