### ISSUE TITLE
Cargo commands take a while and don't release lock in error case

### ISSUE THREAD

**Issue by la10736** [intellij-rust/intellij-rust#867]
From a while (I guess that is related to cargo command coloring or error link) in case of error the command doesn't release the lock for a long time (sometimes more than 30 seconds). The same command issued by terminal terminate immediately. 

In the attached image have an example for test command, but build one have the same behavior.

That really annoying :cry:. 

![rust_plugin_dosnt_release_lock](https://cloud.githubusercontent.com/assets/3902961/21566834/211ff44e-cea7-11e6-8feb-a0c417460b4c.png)

**Comment by matklad** [comment]
Okey, I've re-disable backtraces by default and will try to figure out what's wrong with Rust 1.14.0. BTW, checkout how backtraces are rendered in IntelliJ now, @alygin has done some awesome work on them!

**Comment by matklad** [comment]
(Let's keep the issue open until Rust is fixed and backtraces are enabled again)

**Comment by matklad** [comment]
Rust 1.15.0 is out, the issue is fixed there!
