### ISSUE TITLE
Code completition and Option<> coloring regression

### ISSUE THREAD

**Issue by la10736** [intellij-rust/intellij-rust#868]
From some updates (since a week or two) I experimented some regression in code completion and syntax coloring. `None`, `Some`, `Err` and `Ok` variants are not highlighted and no code suggestion are showed. I'm quite sure that these features worked some week ago because I forget every time what kind of `map`, `and`, `and_then` ... variants should I use :smile:.

![rust_plugin_coloring_and_code_completition_regression](https://cloud.githubusercontent.com/assets/3902961/21566938/610d68f6-cea8-11e6-8811-93ec5e34700f.png)

**Comment by alygin** [comment]
A couple of things that I noticed:
1. The syntax highlighting and code completion breaks when you put a function within an explicit `mod` block. The same code is handled properly on the file level.
2. If you add a `use std::option::Option;` somewhere within the nested module, the completion starts working, though syntax remains uncolored.

I would assume that the stdlib is correctly attached on the file level, but is ignored in the nested modules. But that's just my wild guess.

**Comment by la10736** [comment]
I'm not sure this issue is really fixed. I'm still have same behavior with both yesterday build and 0.1.0.1425 official release (that should contain this fix).

There are some test that highlighting it?

Just a note: as you can see in attached image that issue is triggered in the main module too and not just in some submodule.

![rust_plugin_coloring_and_code_completition_regression_again](https://cloud.githubusercontent.com/assets/3902961/21923318/a3b24bc4-d973-11e6-9770-25fe12cb7b0b.png)

**Comment by matklad** [comment]
This now looks similar to #920. Looks like we fail to resolve standard library sometimes, but I am absolutely unable to reproduce this locally : (

Here's how it looks (with current alpha and with the build off the master branch) on my machine: 

![opt](https://cloud.githubusercontent.com/assets/1711539/21927891/de41dfd2-d998-11e6-9d7c-37a00c73cede.png)


@la10736 can you try this with the new project and some fresh cargo toolchain?

**Comment by la10736** [comment]
Ok... works on a new project from scratch. What can I try to track it in a existing project?

**Comment by matklad** [comment]
>What can I try to track it in a existing project?

Can you try to do a fresh imoprt of this project, with a fresh toolchain? Copy the proejct directory somewhere, overrdide toolchain in that directory and import it.

**Comment by la10736** [comment]
A fresh check out solve the problems... Is there some way to force a refresh on existing project?

I noted that in the first attempt that I did a generic dependency to `mysql` module triggered the same behavior because Cargo has fail to update. After fixed the dependency and Cargo updated all correctly coloring came back to work.

**Comment by matklad** [comment]
>  Is there some way to force a refresh on existing project?

There's **refresh cargo project** action, which will cause to reload Cargo model of the project. 

There's also **invalidate caches and restart**.

**Comment by la10736** [comment]
Sadly both of them didn't work... :cry:

**Comment by matklad** [comment]
Now standard library is refreshed everytime you open a project, this should fix this issue.
