### ISSUE TITLE
Issue  - Can not find declaration to go to

### ISSUE THREAD

**Issue by arkanmgerges** [intellij-rust/intellij-rust#8688]
## Environment

* **IntelliJ Rust plugin version:**
0.4.166.4486-213
* **Rust toolchain version:**
```sh
installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.58.1 (db9d1b20b 2022-01-20)
```
* **IDE name and version:**
IntelliJ IDEA 2021.3.3 (Community Edition)
Build #IC-213.7172.25, built on March 15, 2022

* **Operating system:**
Windows 10 Pro

## Problem description
Can not find declaration to go to

![image](https://user-images.githubusercontent.com/7836805/159904755-dab8d84f-3bb4-4d85-acf8-959609000651.png)

1. Build the code
`cargo build`

2. Check the code
`cargo check`

3. Run the sample code
`cargo run --bin some_bins_init_user`

## Steps to reproduce
I attached the code to analyze

[code.zip](https://github.com/intellij-rust/intellij-rust/files/8340981/code.zip)

**Comment by Undin** [comment]
@arkanmgerges Thanks for the report!
As I can see, the given project contains invalid info about project modules. The simplest way to fix it is to close the project, drop `.idea/modules.xml` file and reopen the project.
You also can drop the whole `.idea` directory but it will drop all custom project settings

**Comment by arkanmgerges** [comment]
@Undin Thank you I've done it and it worked.
I have the project closed, then I've deleted the folder .idea, then I opened the project, and it worked.

**Comment by Undin** [comment]
Glad to hear it!
Let's close this issue then. But if you face with it again, don't hesitate to reopen the issue or write a comment

**Comment by JohnAllen** [comment]
This still happens to me and the above solution to remove `.idea/modules.xml` and restarting does not work for me.
