### ISSUE TITLE
Run Anything dialog will be renamed to Debug if try to do a screenshot 

### ISSUE THREAD

**Issue by mili-l** [intellij-rust/intellij-rust#8693]
## Environment

* **IntelliJ Rust plugin version:** 0.4.168.4519-221-nightly
* **Rust toolchain version:** 1.61.0-nightly (52b34550a 2022-03-15) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2022.1 Beta Ultimate Edition (IU-221.5080.56)
* **Operating system:** macOS 11.5.1
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
Run Anything dialog will be renamed to Debug if try to do a screenshot 

## Steps to reproduce

1. Open Cargo tool window
2. Click on Run Cargo command icon
3. Press on Cmd+Shift

## Actual Results

https://user-images.githubusercontent.com/1213122/160611654-fa9e4903-0752-4724-a82a-42edbd21c86e.mov

**Comment by Undin** [comment]
@mili-l why it's a bug? it's a platform feature to run the corresponding configuration in debug mode
See https://www.jetbrains.com/help/idea/running-anything.html#running_app
