### ISSUE TITLE
Extract variable with multiple usages puts it after first usage

### ISSUE THREAD

**Issue by marshallpierce** [intellij-rust/intellij-rust#871]
A small issue in a very handy plugin! :) Also, if you change the name of the variable away from the default `x`, the new name isn't used in all places. 

For an example, start with:

```
    let a = 1;
    let b = a + 1;
    let c = a + 1;
```

Extract variable on the second instance `a + 1`. Give it the name `asdf`.

Result:

```
    let a = 1;
    let b = x;
    let asdf = a + 1;
    let c = asdf;
```

The first occurrence keeps its original name of `x`, but even if we'd kept the name, it still wouldn't have worked because the new variable is after the first usage in the source.

Intellij 171.2014.21, plugin 0.1.0.1334

**Comment by matklad** [comment]
Should be fixed inffc6c206375fc5decf79d91959dfcdcb24ac5506
