### ISSUE TITLE
Memory leak detected

### ISSUE THREAD

**Issue by mili-l** [intellij-rust/intellij-rust#8727]
## Environment

* **IntelliJ Rust plugin version:** 0.4.169.4544-221-nightly
* **Rust toolchain version:** 1.62.0-nightly (60e50fc1c 2022-04-04) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2022.1 Beta Ultimate Edition (IU-221.5080.93)
* **Operating system:** macOS 11.5.1
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
```
2022-04-06 12:15:59,758 [5473958] SEVERE - #c.i.o.u.ObjectTree - Plugin to blame: Rust version: 0.4.169.4542-221-nightly
2022-04-06 12:15:59,758 [5473958] SEVERE - #c.i.o.u.ObjectTree - Memory leak detected: 'org.rust.cargo.project.settings.ui.RustProjectSettingsPanel@133c98d0' of class org.rust.cargo.project.settings.ui.RustProjectSettingsPanel is registered in Disposer but wasn't disposed.
Register it with a proper parentDisposable or ensure that it's always disposed by direct Disposer.dispose call.
See https://jetbrains.org/intellij/sdk/docs/basics/disposers.html for more details.
The corresponding Disposer.register() stacktrace is shown as the cause:

java.lang.RuntimeException: Memory leak detected: 'org.rust.cargo.project.settings.ui.RustProjectSettingsPanel@133c98d0' of class org.rust.cargo.project.settings.ui.RustProjectSettingsPanel is registered in Disposer but wasn't disposed.
Register it with a proper parentDisposable or ensure that it's always disposed by direct Disposer.dispose call.
See https://jetbrains.org/intellij/sdk/docs/basics/disposers.html for more details.
```

Logs:

[scratch_5.txt](https://github.com/intellij-rust/intellij-rust/files/8440573/scratch_5.txt)

**Comment by Undin** [comment]
I've checked it and everything is fine here since we have direct `Disposer.dispose` for `RustProjectSettingsPanel` object

**Comment by elmot** [comment]
It's not false positive. The leak is detected, that means the leak happens.

**Comment by Undin** [comment]
@elmot you are right. I've described the reason of the leak in #10191
