### ISSUE TITLE
std resolves cyclically

### ISSUE THREAD

**Issue by alygin** [intellij-rust/intellij-rust#874]
In module name autocompletion the `std` pops out in every module, including itself:

<img width="237" alt="screen shot 2016-12-31 at 15 29 40" src="https://cloud.githubusercontent.com/assets/2101250/21577509/45a0aef4-cf6e-11e6-8825-8ceee6879c80.png">

**Comment by alygin** [comment]
There's another cycle now:

<img width="299" alt="screen shot 2016-12-31 at 16 48 42" src="https://cloud.githubusercontent.com/assets/2101250/21577796/1691df74-cf79-11e6-9b7c-87b9696c0f70.png">

**Comment by matklad** [comment]
Indeed! Fixed in https://github.com/intellij-rust/intellij-rust/commit/585f048982ab07f5c1468d73de9af813d1581e81
