### ISSUE TITLE
IDE test run configuration terminates early when using should_panic tests

### ISSUE THREAD

**Issue by chairbender** [intellij-rust/intellij-rust#8757]
## Environment

* **IntelliJ Rust plugin version:** 0.4.168.4555-221
* **Rust toolchain version:** 1.60.0 (7737e0b5c 2022-04-04) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2022.1 Ultimate Edition (IU-221.5080.210)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
When running tests via a run configuration, in some situations when some of the tests are marked with `#[should_panic]`, the test report shows the suite as Terminated and reports some tests with permanent spinner icons. Running the same `cargo test` command on the command line runs all tests to completion and reports the expected results. Final report differs when running via command line vs run configuration.

Expected behavior would be that this test run configuration runs all tests and does not terminate early, and reports failures + success add up to total amount of tests in the suite. No test cases should be reported with a spinner icon.

## Steps to reproduce

1. Checkout https://github.com/chairbender/cybersecurity-rrt/tree/reproduction (make sure to use `reproduction` branch)
2. Create a run configuration with command `test --package cybersecurity-rrt-logic`
3. Run the run configuration.
4. Note some tests have permanent spinner icon, and report says "Tests failed: 3, passed 32 of 37" (final count may differ depending on circumstances, but main point is that some of the tests are not marked as passed or failed - passed + failed doesn't add up to 37).
5. Run same command from command line, note that all test are either marked as passed or failed (passed + failed adds up to 37).

Run configuration
![image](https://user-images.githubusercontent.com/1329062/163741154-b29008bf-3211-4c52-aeec-0e778185730a.png)

Test report with discrepancy
![image](https://user-images.githubusercontent.com/1329062/163740971-09493036-e10d-44ef-9b6a-22b0f19cca82.png)

Command line output of same test suite:
![image](https://user-images.githubusercontent.com/1329062/163741207-51b474a8-1ea6-48fe-827a-7fc1602c2033.png)

**Comment by Undin** [comment]
@mchernyavsky I suppose it's not about `should_panic` but about "long" output that was fixed in #8739

**Comment by Undin** [comment]
@chairbender could you check your issue with [nightly](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly) plugin version, please?It seems the bug is already fixed

**Comment by chairbender** [comment]
@Undin yes, confirmed it is fixed in nightly.
