### ISSUE TITLE
[Optional] Add Rust as an SDK

### ISSUE THREAD

**Issue by ForsakenHarmony** [intellij-rust/intellij-rust#876]
Using rustup that way could also work

(the elixir plugin does this)

**Comment by netroby** [comment]
Need add rust as an SDK

**Comment by devurandom** [comment]
This seems somewhat related to #736 and #861. A good start would already be if CLion+Rust could import existing projects (i.e. those that already have a `Cargo.toml`), instead of creating `CMakeLists.txt`.

**Comment by Undin** [comment]
I think it can be closed due to https://intellij-rust.github.io/docs/faq.html#sdk

**Comment by ForsakenHarmony** [comment]
I don't remember why I wanted this, but I think whatever problem I had was solved in the meantime
