### ISSUE TITLE
Until there is real support for generics auto-completion, consider adding the '?' operator as a special case

### ISSUE THREAD

**Issue by AsafMah** [intellij-rust/intellij-rust#877]
Basically the question mark is very prevalent in rust, but currently the auto-completion engine can't handle a statement like this: 
`File::create(&file_name)?`
Now I get that generics are very complicated to implement and make take time or will have to wait to use RLS, but right now just adding this one special case on this very prevalent operator would solve a hefty chunk of the use-cases for generics auto-completions.

**Comment by DemiMarie** [comment]
I will go farther and claim that the RLS is the ONLY way to go for semantic completion.

Rust has very simple runtime semantics.  A large part of the 150,000 lines in the Rust compiler are dedicated to type inference and error detection.  Trying to implement generics (which are Turing complete, by the way) in the IDE is likely to be a major source of frustration.  Much better to call out to RLS, which – unlike the IDE – can use the same code used by the compiler itself.

**Comment by matklad** [comment]
Ah, it's all complicated unfortunately :(  

RLS is not done yet, so what follows is a bit hypothetical. 

The fundamental problem with this sort of things is that compiler and IDE really have very different constraints and performance goals. So, you can't just reuse the compiler's code. In fact, a major rewrite of the rustc is in progress know with the goal to make it more usable in the IDE context.

Also, there's already a precedent of implementing complicated type systems inside IntelliJ platform: scala plugin uses its own engine and not the presentation compiler :) And even Java generics are a complicated beast: https://www.cs.cornell.edu/~ross/publications/tamewild/tamewild-tate-pldi11-tr.pdf, and last year it was proven that they are undecidable. 


As usual, there's no silver bullet :(

**Comment by matklad** [comment]
Fixed in https://github.com/intellij-rust/intellij-rust/commit/8a0e5d358c9e60bd060e668f1130dd99134669d2 (**very** crude implementation).

Now I can navigate Cargo code, full of `?` and `CargoResult` much better, yay!
