### ISSUE TITLE
"Use of moved value" false positive 

### ISSUE THREAD

**Issue by skimmilk6877** [intellij-rust/intellij-rust#8771]
## Environment

* **IntelliJ Rust plugin version:** 0.4.168.4555-221
* **Rust toolchain version:**cargo 1.60.0 (d1fd9fe2c 2022-03-01)
* **IDE name and version:** CLion 2022.1
* **Operating system:** mac 12.3.1

## Steps to reproduce
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b9acee7f18eeb980a3004cc18dab7314

**Comment by skimmilk6877** [comment]
![image](https://user-images.githubusercontent.com/9862730/164167260-4a14933d-8ead-47c8-83ad-9347d7041514.png)

**Comment by afetisov** [comment]
Doesn't reproduce for me. Do you have experimental proc macro expansion and/or the new macro engine enabled? What's your Cargo.toml?

Maybe it's because I'm on the 0.4.170.4568-221-nightly plugin version, but that looks unlikely since there were no recent commits related to trait resolution, analysis or inspections.

**Comment by skimmilk6877** [comment]
[package]
name = "catr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.9", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
rand = "0.8"

**Comment by afetisov** [comment]
Still nothing. You can try testing on the nightly plugin. Go to Settings > Plugins > Gear icon > Manage plugin repositories, then add `https://plugins.jetbrains.com/plugins/nightly/8182-rust` and update the plugin.

**Comment by skimmilk6877** [comment]
@afetisov Because I finished that learning project. I will report if I encounter problem again. thanks.
