### ISSUE TITLE
Stop parsing Cargo.toml while typing!

### ISSUE THREAD

**Issue by ctron** [intellij-rust/intellij-rust#8779]
## Environment

* **IntelliJ Rust plugin version:** 0.4.168.4555-221
* **Rust toolchain version:** 1.60.0 (7737e0b5c 2022-04-04) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.1 (CL-221.5080.224)
* **Operating system:** Linux 5.16.20-200.fc35.x86_64
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

When editing a `Cargo.toml` file, some mechanism in the background starts to parse this while typing. Now what happens is that of course the syntax of the file isn't valid _while typing_!

That triggers errors of the validation, which pulls the focus out of the edit window, making it impossible to finish typing, and completing the edits.

This is SUPER annoying!

I would expect that the file only gets validated once I save the file. In addition I would appreciate it, if you don't steal the focus out of the editor in any case!

## Steps to reproduce

Edit a Cargo.toml file.

**Comment by Mo0nbase** [comment]
I have the exact same problem!

**Comment by LoganDark** [comment]
Still running into this issue, Cargo.toml randomly gets saved to file which triggers the project refresh. External linter is off.

**Comment by Undin** [comment]
@LoganDark I suppose #8919 should fix it eventually

**Comment by LoganDark** [comment]
> @LoganDark I suppose #8919 should fix it eventually

Yeah, seems like it
