### ISSUE TITLE
mod created in the autocxx's macro is not recognized

### ISSUE THREAD

**Issue by redbaron** [intellij-rust/intellij-rust#8785]
## Environment

* **IntelliJ Rust plugin version:** 0.4.168.4555-221
* **Rust toolchain version:** 1.60.0 (7737e0b5c 2022-04-04) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2022.1 (CL-221.5080.224)
* **Operating system:** Windows 11 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

`autocxx::include_cpp!` macro creates a `#[cxx::bridge] mod ffi { ... }` module, but it is not recognized by rust plugin and comes up as undefined reference. `cargo build` from command line builds project successfully 

## Steps to reproduce

1. Open https://github.com/google/autocxx/tree/3aae2ca3503acd42cf8ed8a50a29c1bdf156d9ae/demo project
2. Open `main.rs`
3. ![image](https://user-images.githubusercontent.com/16624/164969796-ea5a2ebe-21b5-4d97-9bed-a73d66f473bc.png)

**Comment by Undin** [comment]
It's because `autocxx` uses build scripts and procedural macros to generate code.
The corresponding support is not enabled by default yet. To make it work, enable `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` [experimental](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features) features

**Comment by redbaron** [comment]
@Undin , Thanks for suggestion, I tried enabling them but it didn't have any effect.

**Comment by Undin** [comment]
@redbaron have you reloaded project model after it?
It can be done via `Refresh Cargo Projects` action in Cargo tool window

<img width="277" alt="image" src="https://user-images.githubusercontent.com/2539310/163798026-7d209eb2-a541-4c17-b8ca-061558709af8.png">

**Comment by redbaron** [comment]
No luck :( Here is what I've tried:

- Refresh cargo project
- Restarting IDE
- Cleaning all files not in git with `git clean -dfx` (.idea, target dirs, etc)

Still not working. Would you mind trying it yourself? Reproducer is fairly trivial:

1. clone https://github.com/google/autocxx repo
2. open it's `demo` directory in the IDE

**Comment by Undin** [comment]
> Would you mind trying it yourself? Reproducer is fairly trivial:

I tried it and everything works for me. But I did it on macOS
Could you attach your [logs](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files), please?
