### ISSUE TITLE
Extension traits type hint isn't working

### ISSUE THREAD

**Issue by JasonShin** [intellij-rust/intellij-rust#8787]
## Environment

* **IntelliJ Rust plugin version:**
<img width="187" alt="Screen Shot 2022-04-25 at 11 37 47 am" src="https://user-images.githubusercontent.com/2525002/165006985-34e86214-8364-4063-be72-9d90086e213e.png">

* **Rust toolchain version:**
rustc 1.59.0 (9d1b2106e 2022-02-23)
cargo 1.59.0 (49d8809dc 2022-02-10)

* **IDE name and version:**

* **Operating system:**
macOS Monterey, Apple M1 silicon

## Problem description
I was playing around with a library called `assert_cmd` https://docs.rs/assert_cmd/latest/assert_cmd/. I realised intellij-rust plugin doesn't give typing hints for extension traits. assert_cmd seems to work by extending the standard-lib `std::process::Command;` and providing additional assertions such as `.success` and `.stdout`

In my CLion, when I try to get typing hint

<img width="769" alt="Screen Shot 2022-04-25 at 11 42 26 am" src="https://user-images.githubusercontent.com/2525002/165007280-7a2a66f0-6418-4045-b2d6-4e6dac29cce4.png">

Rust plugin + CLion fail to give any typing hint 😞 

But on my VSCode with rust-analyzer enabled

<img width="727" alt="Screen Shot 2022-04-25 at 11 43 02 am" src="https://user-images.githubusercontent.com/2525002/165007324-e7be56d2-127d-4976-a955-4007e372da28.png">

**Comment by dima74** [comment]
@JasonShin Hi! I can't reproduce it with the latest plugin version. Do you still observe the error?

![image](https://user-images.githubusercontent.com/6505554/180323648-224be72f-669b-4e12-9bad-6292fcfa3e19.png)
