### ISSUE TITLE
Provide lint-based suppress quick-fixes for external linter annotations

### ISSUE THREAD

**Issue by laralove143** [intellij-rust/intellij-rust#8794]
## Environment

* **IntelliJ Rust plugin version:** 0.4.169.4584-221
* **Rust toolchain version:** rustc 1.60.0 (7737e0b5c 2022-04-04)
* **IDE name and version:** CLion 2022.1 Build #CL-221.5080.224, built on April 13, 2022
* **Operating system:** MacOS Monterey

## Problem description
so we have this functionality for IDE inspections, theres "disable inspection for line/item/file using comment" but we dont have it for clippy or default rust lints, which make up the majority of lints

when this action is selected, it'd add the `#[allow(clippy::lint_name)]` or `#[allow(lint_name)]` above the function, module or top module, depending on the action selected

**Comment by Undin** [comment]
Could you provide an exact case where the plugin doesn't provide such action, please?
I'm asking because the plugin has such suppress quick-fixes for all "Lint" inspections
<img width="604" alt="image" src="https://user-images.githubusercontent.com/2539310/165639486-1df55f54-7d83-4fe8-8e16-8ff010db1257.png">

https://user-images.githubusercontent.com/2539310/165641485-6e72e954-04be-4eb7-ab44-89cc92fdc725.mov

**Comment by laralove143** [comment]
yes in your example it works (didnt know that btw), but in other lints (i think the majority of them) it just doesnt

`clippy::unreadable_literal`
<img width="912" alt="Screen Shot 2022-04-28 at 1 24 37 PM" src="https://user-images.githubusercontent.com/82576556/165733110-11265f4b-8be7-4c5a-ba0a-bd2b62512d91.png">
`unused_must_use`
<img width="425" alt="Screen Shot 2022-04-28 at 1 26 03 PM" src="https://user-images.githubusercontent.com/82576556/165733145-9ce5ed3e-321c-433d-86a5-52288fbba849.png">

**Comment by Undin** [comment]
> but in other lints (i think the majority of them) it just doesnt

Yeah. You are talking about annotations provided by external linter. For such annotations, the plugin indeed doesn't provide suppress quick-fixes. And I'm not sure that `cargo check`/`clippy` provides the corresponding fixes in a structured way. Maybe @mchernyavsky knows more

**Comment by Undin** [comment]
> `unused_must_use`

BTW #7849 added built-in inspection to detect unused `must_use`


https://user-images.githubusercontent.com/2539310/165821609-bbc6de02-77bb-4fcf-b254-1d9d9060e8e3.mov

**Comment by laralove143** [comment]
i guess that pr isnt merged into the stable channel yet? and im also unsure if cargo does, but cant the ide just get the current scope and add the macro to the start of it?

**Comment by laralove143** [comment]
it already shows the lint name in the problems toolbar so i think it's parsed anyway

**Comment by laralove143** [comment]
yeah so it is definitely possible, if not done already, could this be accepted as an upcoming feature?

**Comment by Undin** [comment]
> if not done already, could this be accepted as an upcoming feature?

if someone implements it, of course!

**Comment by laralove143** [comment]
i dont know how to :( i hope someone can
