### ISSUE TITLE
add suggestion to apply trait use suggestions

### ISSUE THREAD

**Issue by laralove143** [intellij-rust/intellij-rust#8798]
## Environment

* **IntelliJ Rust plugin version:** 0.4.169.4584-221
* **Rust toolchain version:** 1.60.0 (7737e0b5c 2022-04-04) aarch64-apple-darwin
* **IDE name and version:** CLion 2022.1 (CL-221.5080.224)
* **Operating system:** macOS 12.3.1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
https://doc.rust-lang.org/error-index.html#E0599 suggestions need to be copy pasted from the problem description

## Steps to reproduce
```rust
Foo::new().my_trait_fn();
```
without adding a use for the trait, which triggers this error message 
```rust
error[E0599]: no function or associated item named `my_trait_fn ` found for struct `Foo` in the current scope
   --> src/main:1
    |
247 |     Foo::new().my_trait_fn()
    |                ^^^^^^^^^^^^ function or associated item not found in `Foo`
    |
   ::: src/main.rs:2
    |
35  | pub struct Foo {}
    | -------------- function or associated item `my_trait_fn` not found for this
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
3   | use MyTrait;
    |
```

**Comment by dima74** [comment]
@laralove143 Hi! Do you mean auto-import of trait methods? It should work. Do you have some specific case when it doesn't work?

![Peek 2022-07-22 01-02](https://user-images.githubusercontent.com/6505554/180322795-96aa96a7-1c16-42b2-af3f-87db68345978.gif)

**Comment by laralove143** [comment]
this seems to have been fixed or it was just broken on me before, sorry for wasting your time and thank you!
