### ISSUE TITLE
Macro indentation

### ISSUE THREAD

**Issue by ForsakenHarmony** [intellij-rust/intellij-rust#880]
Macro content should be indented on format

currently
```rust
Layer::new("main",
           vec![
           Clear::new([0.0, 0.0, 0.0, 1.0]),
           DrawFlat::new("main", "main"),
           ]);
```
should be
```rust
Layer::new("main",
           vec![
             Clear::new([0.0, 0.0, 0.0, 1.0]),
             DrawFlat::new("main", "main"),
           ]);
```

**Comment by matklad** [comment]
We can't properly reformat arbitrary macros because we don't know what's inside. But I believe that the `vec!` case is a bug and that it should be fixed already: #858  (the new alpha will be up shortly).
