### ISSUE TITLE
Alphabetical sort for all files

### ISSUE THREAD

**Issue by stanislav-tkach** [intellij-rust/intellij-rust#8806]
## Environment

* **IntelliJ Rust plugin version:** 0.4.164.4409-212
* **Rust toolchain version:** rustc 1.60.0 (7737e0b5c 2022-04-04)
* **IDE name and version:** CLion 2021.2 Build #CL-212.4746.93, built on July 27, 2021
* **Operating system:** macOS Monterey Version 12.0.1

## Problem description

Personally I prefer to sort _all_ files alphabetically, but currently there is only the "Sort by Type" option, which produces somewhat surprising results. When the option is disabled the `lib.rs` file is placed at the top of the list, for example:
```
lib.rs
another_file.rs
error.rs
```
When the option is enabled all files with the same extension are sorted alphabetically, so in my case the result is the following:
```
another_file.rs
error.rs
lib.rs
```

I would like to have an option to disable both sorting by type and placing the lib.rs file at the top.

Related issue: https://github.com/intellij-rust/intellij-rust/issues/7424

## Steps to reproduce

Open any Rust project with several files in a directory and enable/disable the "Sort by Type" option.

**Comment by U007D** [comment]
+1.

Excerpt from correspondence re [support issue #4501694](https://intellij-support.jetbrains.com/hc/en-us/requests/4501694) (which now seems to 404 for some reason).

Excerpt:

> Ideally, the directory would be sorted lexographically (no exceptions for lib.rs/main.rs, etc.)  If the crate root items need special attention, I suggest emboldening the font, not breaking sort order.
>
> Folders would be either mixed in or sorted first, depending on sort setting.

**Comment by U007D** [comment]
This is still an issue--it's unnecessarily time-consuming searching for a file to click on.  Especially when the `.rs` file and the corresponding folder are split up (despite the UI being set to show them together).

Try searching for `game.rs` in the attached screen shot.  What about `game::state.rs`?

Please address!!

![Screenshot 2023-01-08 at 11 18 42 AM](https://user-images.githubusercontent.com/2874989/211225071-16c80169-cca0-4cb6-9df3-5eba8ea13e55.png)
![Screenshot 2023-01-08 at 3 45 54 PM](https://user-images.githubusercontent.com/2874989/211225085-895bf941-7ea8-4ca6-8d8c-6e726832c37b.png)
