### ISSUE TITLE
Tests fail but show as passed

### ISSUE THREAD

**Issue by magnusja** [intellij-rust/intellij-rust#8810]
## Environment

* **IntelliJ Rust plugin version:** 0.4.168.4555-221
* **Rust toolchain version:**  rustc 1.60.0 (7737e0b5c 2022-04-04)
* **IDE name and version:** IntelliJ IDEA 2022.1 (Ultimate Edition) Build #IU-221.5080.210, built on April 12, 2022 
* **Operating system:** macOS Catalina

## Problem description

When I run tests in Intellij, it seems that some of the output cannot be parsed. Resulting in a failed tests which is shown as passed :/

<img width="2550" alt="Screenshot 2022-05-05 at 12 11 21" src="https://user-images.githubusercontent.com/1659457/166903395-d3820a18-f2fb-4849-adca-badd07431d9b.png">

**Comment by Undin** [comment]
@magnusja I believe it's the same as #8626. And if so, the bug was fixed in #8739 and landed in the latest release (v169). Could you update your Rust plugin and check again, please?

**Comment by magnusja** [comment]
Ahhh awesome, indeed it is working now! Thanks!
