### ISSUE TITLE
code analysis is broken

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#8814]
## Environment

* **IntelliJ Rust plugin version:** 0.4.170.4603-221-nightly
* **Rust toolchain version:** rustc 1.62.0-nightly (30f386087 2022-05-05)
* **IDE name and version:** Clion 2022.1
* **Operating system:** Archlinux

## Problem description
```rust
use druid::{Widget, WidgetExt};
use druid::widget::Button;

pub fn run() {

}

fn make_ui() -> impl Widget<()> {
    Button::new("test").controller()
}
```

the `.controller()` method needs an argument, when I type in `.controller()` and stop, there should be a red line to remind me 'you haven't input an argument in this method', but nothing happened

![image](https://user-images.githubusercontent.com/10096425/167117663-7488ebbd-94f9-4fe4-88c3-08bf6b62914b.png)

I have enabled the external linter clippy

## Steps to reproduce

try the codes in **Problem description**

**Comment by Sherlock-Holo** [comment]
I think the problem reason is not same as #5681, because this codes is wrong too, but intellij-rust doesn't tell me, until I try to run it

![image](https://user-images.githubusercontent.com/10096425/167123004-8c9f32cf-e584-4456-b53e-6729981c3a32.png)

```rust
use druid::widget::{Button, Container, Controller, Flex, List, Scroll};
use druid::{AppLauncher, Env, Event, EventCtx, Size, Widget, WidgetExt, WindowDesc};

pub fn run() {
    let window = WindowDesc::new(make_ui())
        .title("History Clipboard")
        .window_size(Size {
            width: 350.0,
            height: 500.0,
        });

    AppLauncher::with_window(window).launch(()).unwrap();
}

fn make_ui() -> impl Widget<()> {
    let mut flex = Flex::column();
    for _ in 0..20 {
        flex.add_child(Button::new("test").height(100.0));
    }

    Container::new(Scroll::new(flex))
        .expand_height()
        .expand_width()
}
```

**Comment by vlad20012** [comment]
By the way, you can enable an [external linter](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-code-analysis.html#external-linters) to see all compiler errors on the fly
