### ISSUE TITLE
clippy external linters advice is not show

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#8815]
## Environment

* **IntelliJ Rust plugin version:** 0.4.170.4603-221-nightly
* **Rust toolchain version:** rustc 1.62.0-nightly (30f386087 2022-05-05)
* **IDE name and version:** Clion 2022.1
* **Operating system:** Archlinux

## Problem description

```rust
fn ddd(n1: i32, n2: i32) {
    if n1 > 10 {
        println!("10");
    } else {
        if n2 > 20 {
            println!("20");
        }
    }
}
```

clippy will tell us the block in the codes can be collapsed

> ```
>  --> src/druid_button.rs:38:12
>    |
> 38 |       } else {
>    |  ____________^
> 39 | |         if n2 > 20 {
> 40 | |             println!("20");
> 41 | |         }
> 42 | |     }
>    | |_____^
>    |
>    = note: `#[warn(clippy::collapsible_else_if)]` on by default
>    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#collapsible_else_if
> ```

but intellij-rust doesn't show this advice, until I press **Refresh Cargo Projects**

## Steps to reproduce

1. enable clippy external linters
2. try the example codes
3. wait intellij-rust give me the advice which clippy says(but nothing happened extually) 
![image](https://user-images.githubusercontent.com/10096425/167120243-d5b87415-e18d-4ecb-8075-dbe27c88410c.png)

4. press **Refresh Cargo Projects**, now intellij-rust tell me the advice 
![image](https://user-images.githubusercontent.com/10096425/167120351-24ed2ff5-0201-4fac-a3e6-5285fcfe07a6.png)

**Comment by Undin** [comment]
@mchernyavsky did #8741 fix it as well?

**Comment by mchernyavsky** [comment]
@Undin I think https://github.com/intellij-rust/intellij-rust/pull/8882 fixed it.

@Sherlock-Holo Could you check it, please?

**Comment by Sherlock-Holo** [comment]
now it seems problem fixed

Mikhail Chernyavsky ***@***.***> 于 2022年6月7日周二 18:16写道：
