### ISSUE TITLE
Test with `[should_panic]` keeps loading forever

### ISSUE THREAD

**Issue by Jasperav** [intellij-rust/intellij-rust#8818]
I run some tests with the `[should_panic]` attribute. CLion does not show if they passed, but I keep seeing a spinner.

![image](https://user-images.githubusercontent.com/20363565/167218448-b6245c87-d54e-4993-bf10-b978e4c2ae6e.png)

**Comment by Undin** [comment]
@Jasperav What plugin version do you use? This issue looks similar to #8626 that was fixed in #8739. And the fix is already landed in the latest plugin versions (v169)

**Comment by Jasperav** [comment]
@Undin Woops, it is indeed fixed in the latest version!
