### ISSUE TITLE
Plugin stopped working partially after update to CLion 2022.1.1

### ISSUE THREAD

**Issue by indietyp** [intellij-rust/intellij-rust#8834]
## Environment

* **IntelliJ Rust plugin version:** 0.4.169.4584-221
* **Rust toolchain version:** 1.62.0-nightly (90ca44752 2022-04-11) aarch64-apple-darwin
* **IDE name and version:** CLion 2022.1.1 (CL-221.5591.52)
* **Operating system:** macOS 12.3.1
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description

I updated from CLion 2022.1 to 2022.1.1, and now the plugin no longer works as intended. I already invalidated the caches, but I cannot get code completion or syntax highlighting to work. Screenshot of how everything looks included below.
It seems as if it is stuck analyzing... something.

![image](https://user-images.githubusercontent.com/7252775/168290651-745bd9ec-1d5a-4168-b140-9114fb2d59ef.png)

This is consistent among multiple projects.

## Steps to reproduce

Open a project.

**Comment by follow99** [comment]
IDEA 2022.1.1 got the same
