### ISSUE TITLE
Feature request: hide all unstable items from autocomplete

### ISSUE THREAD

**Issue by LoganDark** [intellij-rust/intellij-rust#8836]
There's nothing more saddening than autocompleting a method name or trait that does *exactly what you want*, only to find out that it's been unstable since 2016, requiring you to undo and try again and possibly write the function yourself (but with extra annoyance now).

I would prefer to just not see these unstable features that I can't use. I want to be able to completely disable them showing up in autocomplete, as if they just weren't there (as I can't touch them anyway).

That way I can easily find a stable solution to the problem without possibly multiple unstable solutions not working out, causing frustration. That's because there's no way to tell stable from unstable items in autocomplete, so I can't easily tell which methods I'm allowed to use to solve my problem.

Differentiating unstable vs stable items in autocomplete would provide an earlier warning but it would stay just as annoying (that perfect method that solves your problem in 1 call is just taunting you with "instability"). Ideally there should be both; you should be able to either differentiate them, or turn unstable items off completely. But as I'd be doing the latter I only care about that.

p.s. My toolchain *is* nightly, but that doesn't matter for consumers of my libraries. Requiring nightly would just ban everyone from using it.

**Comment by afetisov** [comment]
I think completing unstable items is the desired outcome on nightly. After all, how else would you test unstable features? But it would indeed be nice to mark unstable items in the completion list, and to hide them on stable or beta toolchains.
