### ISSUE TITLE
Poem #[OpenApi] sections get syntax highlighting but no type annotations or autocomplete

### ISSUE THREAD

**Issue by l1npengtul** [intellij-rust/intellij-rust#8849]
## Environment

* **IntelliJ Rust plugin version: 0.4.170.4627-213**
* **Rust toolchain version: 1.60 stable**
* **IDE name and version: IntelliJ IDEA Community 2022**
* **Operating system: Linux 5.17 arch**

## Problem description
Proc macro get full syntax highlighting but get no type annotations or autocomplete

I already have all the experimental features enabled. 

## Steps to reproduce
`Cargo.toml`:
```toml
poem = "1.3.49"
poem-openapi = "2.0.20"
tokio = { version = "1.22.0", features = ["rt-multi-thread"] }
tracing-subscriber = "0.3.16"
```

`main.rs`:
```rust
use poem::{listener::TcpListener, Route, Server};
use poem_openapi::{param::Query, payload::PlainText, OpenApi, OpenApiService};

struct Api;

#[OpenApi]
impl Api {
    #[oai(path = "/hello", method = "get")]
    async fn index(&self, name: Query<Option<String>>) -> PlainText<String> {
        match name.0 {
            Some(name) => PlainText(format!("hello, {}!", name)),
            None => PlainText("hello!".to_string()),
        }
    }
}

#[tokio::main]
async fn main() -> Result<(), std::io::Error> {
    if std::env::var_os("RUST_LOG").is_none() {
        std::env::set_var("RUST_LOG", "poem=debug");
    }
    tracing_subscriber::fmt::init();

    let api_service =
        OpenApiService::new(Api, "Hello World", "1.0").server("http://localhost:3000/api");
    let ui = api_service.swagger_ui();

    Server::new(TcpListener::bind("127.0.0.1:3000"))
        .run(Route::new().nest("/api", api_service).nest("/", ui))
        .await
}
```
(Alternatively, go to [poem's hello world example](https://github.com/poem-web/poem/tree/efe2076a34344bcfc7323ce2fbd83d7d1620358a/examples/openapi/hello-world))
Notice how `async fn index()` has highlighting but no types.

**Comment by Undin** [comment]
It's because of procedural macro call caused by `#[OpenApi]`. Currently, inlay type hints don't work inside macro call body

**Comment by l1npengtul** [comment]
That sucks. It seems to work in Rust-Analyzer though, do you have any idea on why?

**Comment by LoganDark** [comment]
> That sucks. It seems to work in Rust-Analyzer though, do you have any idea on why?

`rust-analyzer` is an *entirely* different project from IntelliJ-Rust that is basically a major refactor of `rustc` to support... well, everything that `rust-analyzer` supports.
