### ISSUE TITLE
No autocomplete when both Build Scripts and Macros Proc are enabled

### ISSUE THREAD

**Issue by Cy-Tek** [intellij-rust/intellij-rust#8865]
## Environment

* **IntelliJ Rust plugin version:** 0.4.170.4627-221
* **Rust toolchain version:** 1.61.0 (fe5b13d68 2022-05-18) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2022.1.1 (CL-221.5591.52)
* **Operating system:** Windows 11 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description

When I have both the build scripts experimental feature and the proc macros feature enabled, I can only get autocomplete when I hit Ctrl + Space (on Windows). Then, as soon as I type another character, the autocomplete window closes. This makes the plugin unusable when working with libraries that require proc macros like `web_sys`. If I don't have those features enabled, then autocomplete shows up completely fine. If I only have one or the other enabled, autocomplete shows up fine, but if I have both enabled, that's when the problem occurs. When both are enabled, the type inference and completions are accurate, but it only happens when I force it to show.

## Steps to reproduce

Use the WebAssembly Lib Rust project template and try to type anything inside of the greet function like `let s = String::from("Hello world!")` and there should be no autocomplete unless you hit Ctrl + Space on Windows.

**Comment by Cy-Tek** [comment]
Adding a link to #6908 because it seems related to this tracking issue.

**Comment by zhang-wenchao** [comment]
need Ctrl + Space.

**Comment by TobiasDeBruijn** [comment]
> need Ctrl + Space.
Also on Linux with CLion. Both evaluate build script and proc macros enabled. Ctrl+space doesn't do it for me unfortunately.

In my case I've got a workspace with a `proto` library. Its build script compiles protocol buffers to Rust using Prost, the `lib.rs` includes those. The compiler correctly picks this up. CLion doesn't

**Comment by dima74** [comment]
@Cy-Tek @zhang-wenchao could you please try the latest release, the bug should be fixed by #8977

**Comment by Cy-Tek** [comment]
@dima74 Thank you so much! I just tried this and it worked perfectly for my use cases. I'll go ahead and close this issue!
