### ISSUE TITLE
[TOML] Support the Structure tab in IntelliJ

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#8874]
## Environment

* **Toml plugin version:** 221.5591.52
* **Rust toolchain version:** N/A
* **IDE name and version:** PyCharm 2022.1.1 Profressional
* **Operating system:** macOS

## Problem description

When opening large TOML files, it would be useful of the TOML sections were broken out and show in the Structure view to allow for easy navigation between the sections and to see all of the sections and their nesting at a glance.

Currently, nothing is shown the Structure tab when a TOML file is in focus:

<img width="361" alt="Screen Shot 2022-05-25 at 10 02 56 AM" src="https://user-images.githubusercontent.com/10340167/170281277-4bf703fd-3aff-4fce-b6f7-6108ac179885.png">

**Comment by johnthagen** [comment]
As a reference, PyCharm supports this for INI files. Support for TOML should be quite similar.


<img width="279" alt="Screen Shot 2022-05-26 at 9 53 57 AM" src="https://user-images.githubusercontent.com/10340167/170501715-37875ae3-a91c-475f-b786-9c64d206c11a.png">

**Comment by Undin** [comment]
@johnthagen Note, TOML plugin development moved to IntelliJ project so new issues about general TOML support (not related to Rust specific stuff) should be posted at https://youtrack.jetbrains.com/issues/IDEA 

I've already copied this issue there - https://youtrack.jetbrains.com/issue/IDEA-294834
