### ISSUE TITLE
Memory View is incomplete

### ISSUE THREAD

**Issue by doki23** [intellij-rust/intellij-rust#8889]
## Environment

* **IntelliJ Rust plugin version: 0.4.171.4656-221**
* **Rust toolchain version: nightly-2022-05-19-aarch64-apple-darwin**
* **IDE name and version: Clion**
* **Operating system: macos 12.3.1**

## Problem description
The address of a `Vec<u8>` is not continuous

<img width="847" alt="截屏2022-05-31 21 09 34" src="https://user-images.githubusercontent.com/11144133/171181752-28af9ade-2ffc-434a-9caa-eda29599e7cb.png">

**Comment by ortem** [comment]
@doki23 I suppose you would like to see the raw memory of the vector contents.

Considering you have a variable `vec: Vec<u8>`, you should go to `vec.buf.ptr.pointer.pointer` address to see the raw memory of the vector contents. This can be achieved in different ways:
* via [**Go to**](https://www.jetbrains.com/help/clion/memory-view.html#goto-address) field of the Memory View 
* via [**Show in memory view**](https://www.jetbrains.com/help/clion/memory-view.html#invoke) action invoked on an [evaluated ](https://www.jetbrains.com/help/clion/evaluate-expression.html) expression or a [watch ](https://www.jetbrains.com/help/clion/examining-suspended-program.html#add-watch)

If the vector is big and you only see a part of it, you can use pointer arithmetics in **Go to** field to expand it further, e.g. `vec.buf.ptr.pointer.pointer + 100`.

Please let me know if this helped.

**Comment by doki23** [comment]
I tried `data.data_body.buf.ptr.pointer.pointer + 10`, but it complains that
<img width="545" alt="截屏2022-06-02 19 13 58" src="https://user-images.githubusercontent.com/11144133/171617396-79a3c76a-d4d3-4aae-a4a9-9a948b9b932b.png">

I followed the hint, but it said that
<img width="375" alt="截屏2022-06-02 19 14 25" src="https://user-images.githubusercontent.com/11144133/171617468-79b1d96c-6cf2-4823-ba0f-e29f002006f8.png">

**Comment by doki23** [comment]
Thanks! The nightly version works!
