### ISSUE TITLE
self highlighting problem

### ISSUE THREAD

**Issue by alygin** [intellij-rust/intellij-rust#889]
`self` in a `use` statement is not properly highlighted when it's in a submodule, though it looks fine in the crate root module:

<img width="241" alt="screen shot 2017-01-03 at 23 20 30" src="https://cloud.githubusercontent.com/assets/2101250/21621742/6226bf1a-d20b-11e6-9d92-ff46310c4cec.png">

**Comment by johnthagen** [comment]
Feels similar to #645

**Comment by alygin** [comment]
It's not visible on my previous screenshot because I don't use bold for keywords, but actually `self` _is_ highlighted, just differently &mdash; it's bold but white:

<img width="228" alt="screen shot 2017-01-13 at 12 07 43" src="https://cloud.githubusercontent.com/assets/2101250/21924223/34fe81be-d989-11e6-9e57-468d1335b6f5.png">

**Comment by matklad** [comment]
>I don't use bold for keywords,

Hey, I don't use them as well! :)
