### ISSUE TITLE
Shadowed variables are incorrectly shown in MSVC debugger

### ISSUE THREAD

**Issue by aleksandr-shevchenko** [intellij-rust/intellij-rust#8891]
## Environment

* **IntelliJ Rust plugin version:** org.rust.lang (0.4.170.4627-221)
* **Rust toolchain version:** stable-x86_64-pc-windows-msvc unchanged - rustc 1.61.0 (fe5b13d68 2022-05-18)
* **IDE name and version:** CLion 2022.1.1 Build #CL-221.5591.52, built on May 10, 2022
* **Operating system:** win 10

<img width="841" alt="ss_2022_05_31__15_22_23" src="https://user-images.githubusercontent.com/25248634/171261823-21d7c4e6-8cf3-463b-b749-5f878061b71e.png">

<img width="606" alt="ss_2022_05_31__15_24_09" src="https://user-images.githubusercontent.com/25248634/171261813-ea8c0e4a-b959-4085-a850-87886008e3af.png">

**Comment by aleksandr-shevchenko** [comment]
Вы не поняли проблему. Ваш плагин не "показывает неправильно Option::None".
Плагин НЕПРАВИЛЬНО показывает содержимое переопределенной переменной!!!
Даже если написать в строке 7 правильный индекс (let third = v.get(4)), то вы всё равно будете показывать содержимое third, вычисленное в строке 4.

**Comment by Undin** [comment]
Duplicate of #6296

**Comment by ortem** [comment]
@aleksandr-shevchenko I reported the problem to the corresponding issue: https://youtrack.jetbrains.com/issue/JBR-964/Some-controls-do-not-support-Hindi-Thai-characters-on-Windows
