### ISSUE TITLE
Undefined item: "UTF-8" error with bundled GDB + gnu toolchain

### ISSUE THREAD

**Issue by aleksandr-shevchenko** [intellij-rust/intellij-rust#8894]
## Environment

* **IntelliJ Rust plugin version:** org.rust.lang (0.4.170.4627-221)
* **Rust toolchain version:** stable-x86_64-pc-windows-gnu unchanged - rustc 1.61.0 (fe5b13d68 2022-05-18)
* **IDE name and version:** CLion 2022.1.1 Build #CL-221.5591.52, built on May 10, 2022
* **Operating system:** win 10

## Problem description

if you use the bundled GDB (11.1), then such an error occurs in 3-4 times out of 5 when you start the program for debug:

com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$GDBCommandException: Undefined item: "UTF-8".

if I use the MinGW GDB (11.2) - all OK.

**Comment by ortem** [comment]
@aleksandr-shevchenko Thank you for reporting!

The corresponding issue in CLion's issue tracker, with detailed workaround instructions: https://youtrack.jetbrains.com/issue/CPP-28311/Bundled-GDB-throws-Undefined-item-UTF-8-when-debugging-Rust-tutorial-project-on-Windows

**Comment by ortem** [comment]
[CPP-28311](https://youtrack.jetbrains.com/issue/CPP-28311) `Undefined item: "UTF-8"` exception is fixed in the latest CLion EAP build 231.6890.13

**Comment by CarachinoAlessio** [comment]
> [CPP-28311](https://youtrack.jetbrains.com/issue/CPP-28311) `Undefined item: "UTF-8"` exception is fixed in the latest CLion EAP build 231.6890.13

tried and it works!
