### ISSUE TITLE
Incorrect `default` qualifier parsing

### ISSUE THREAD

**Issue by alygin** [intellij-rust/intellij-rust#890]
The following code compiles by `rustc`, but emits a syntax error in Iintellij-Rust:

```rust
#![feature(associated_consts)]
#![feature(specialization)]

struct Foo;
impl Foo {
    default const BAR: u32 = 81;
}
```

The error is 'const or type expected, got `default`'.

Intellij-Rust plugin 0.1.0.1385
rustc 1.16.0-nightly (2016-12-28)

**Comment by matklad** [comment]
Good catch!
