### ISSUE TITLE
why the unused import did not recognize the serd

### ISSUE THREAD

**Issue by jiangxiaoqiang** [intellij-rust/intellij-rust#8910]
## Environment

* **IntelliJ Rust plugin version: 0.4.171.4656-221**
* **Rust toolchain version:  Rust 1.59**
* **IDE name and version: CLion Build #CL-221.5591.52, built on May 11, 2022**
* **Operating system: macOS Monterey 12.3.1**

## Problem description

Recently I was open the CLion Rust plugin unused import sniff Settings > Editor > Inspections > Rust > Lints > Unused Import, sometimes the rust show the wrong way, for example:

```rust
use rust_wheel::common::util::convert_to_tree::IntoTree;
use serde::Serialize;
use crate::model::diesel::fortune::fortune_models::FortuneContent;
use crate::model::response::contents::fortune_contents_response::FortuneContentResponse;

#[derive(Debug, Serialize, Default)]
pub struct EditContentResponse {
    pub own: Vec<FortuneContent>,
    pub available: Vec<FortuneContent>
}
```

the CLion Rust plugin shows the use serde::Serialize; was unused import. But actually this import was used by the code. is it possible to make the plugin recognized this import the correct way? The rustc did not tell the use serde::Serialize; was unused. is is possible to fix it? This feature was very helpful.

## Steps to reproduce

https://stackoverflow.com/questions/72525320/why-the-clion-rust-tell-serdeserialize-as-unused-import

I read some other issue seems the clion rust did not support the micro fully until now.

**Comment by dima74** [comment]
@jiangxiaoqiang Hi! Could you please provide complete minimal source code example? I can't reproduce the issue with 
```toml
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
```
and
```rust
use serde::Serialize;

#[derive(Debug, Serialize, Default)]
pub struct Foo {}
```
