### ISSUE TITLE
No completion for `all` in `#![warn(clippy::all)]`

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#8931]
## Environment

* **IntelliJ Rust plugin version:** 0.4.172.4663-222-nightly
* **Rust toolchain version:** 1.63.0-nightly (76761db59 2022-05-24) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.2 EAP (CL-222.2680.4)
* **Operating system:** macOS 11.4
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

Originally posted in youtrack https://youtrack.jetbrains.com/issue/CPP-29475/rust-intellisense-not-showing-for-clippyall-in-warn 

## Problem description
<img width="400" alt="image" src="https://user-images.githubusercontent.com/49211026/173334946-1080932f-b1ae-472e-8d56-2f14efb9560b.png">

## Steps to reproduce
```rust
#![warn(clippy::all)]
// #![deny(clippy::all)]

fn main() {}
```

**Comment by redderfur** [comment]
Oh glad to see this closed but quick question when is it going to be rolled out to master?

**Comment by Undin** [comment]
@redderfur We usually publish a new stable release each two weeks, so the corresponding fix will be included into next release around two weeks

**Comment by redderfur** [comment]
oh ok thank you
