### ISSUE TITLE
Cannot disable live templates

### ISSUE THREAD

**Issue by mahkoh** [intellij-rust/intellij-rust#8935]
## Environment

* **IntelliJ Rust plugin version:** 0.4.171.4656-213
* **Rust toolchain version:** 1.61.0 (fe5b13d68 2022-05-18) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.3.2 (CL-213.6461.75)
* **Operating system:** Linux 5.18.0-rc7-dirty
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description

I've deleted all live templates from the Clion settings but the plugin keeps suggesting the the `.iter` live template.

## Steps to reproduce

See above.

**Comment by neonaot** [comment]
Hello! 
`.iter` is Postfix completion (`Settings | Editor | General | Postfix completion`), not Live template (`Settings | Editor | Live templates`). Maybe you tried to disable it in the wrong place?
