### ISSUE TITLE
Missing methods in the completion popup

### ISSUE THREAD

**Issue by caizixian** [intellij-rust/intellij-rust#894]
![screen shot 2017-01-05 at 10 01 45](https://cloud.githubusercontent.com/assets/2891235/21666674/2036c69e-d32e-11e6-9a66-00508b1a6de2.png)

For example, [`split_whitespace`](https://doc.rust-lang.org/std/string/struct.String.html#method.split_whitespace) is missing

**Comment by himikof** [comment]
Well, this one is pretty complicated. `split_whitespace` method is from inherent impl on built-in type `str`, and comes for `String` from `Deref<Target=str>` impl. It is something that should be implemented in time, but it is not supported by our current resolve implementation.

**Comment by kumbayo** [comment]
I have a prototype that improves primitive auto completion and also searches for `Deref` implementations.

My current (hacky) implementation is at
https://github.com/kumbayo/intellij-rust/commits/autocompletion_primitive_and_deref
It will take some more days until the code is ready for a PR...

**Comment by matklad** [comment]
This particular example works now!
