### ISSUE TITLE
Support impls for macro type

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#8947]
## Environment

* **IntelliJ Rust plugin version:** 0.4.173.4688-221-nightly
* **Rust toolchain version:** 1.61.0 (fe5b13d68 2022-05-18) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2022.1.2 Ultimate Edition (IU-221.5787.30)
* **Operating system:** Linux 5.13.0-41-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Steps to reproduce
```rust
struct S;
macro_rules! foo {
    () => { S };
}

impl foo!() {
    fn bar(self) {}
}

fn main() {
    S.bar(); // unresolved
}
```

**Comment by maufl** [comment]
Thanks! Should I close the original issue?
