### ISSUE TITLE
Support u128 and i128

### ISSUE THREAD

**Issue by mkaput** [intellij-rust/intellij-rust#895]
This would require adding new primitives to type system afair, and add them to all suffix lists in our code base.

**Comment by johnthagen** [comment]
Does Rust officially support `u128` and `i128` now? Do you have a link that could be checked out for this?

**Comment by alygin** [comment]
@johnthagen, here's [the RFC #1504](https://github.com/rust-lang/rfcs/blob/master/text/1504-int128.md) and [the corresponding PR](https://github.com/rust-lang/rust/pull/38482). So, it's in nightly now.

**Comment by johnthagen** [comment]
@alygin Thanks! 

I guess it brings up another interesting question about if/when intellij-rust should support nightly only features. In this case, the feature seems basic enough that it'll likely eventually be stabilized, but others could be less clear.
