### ISSUE TITLE
Failed to expand the macro: can't find macro index of the macro call

### ISSUE THREAD

**Issue by kkolyan** [intellij-rust/intellij-rust#8953]
## Environment

* **IntelliJ Rust plugin version:**
* **Rust toolchain version:**

* **IDE name and version:**
CLion 2021.3.4
Build #CL-213.7172.20, built on March 14, 2022
Non-Bundled Plugins:
    org.toml.lang (213.5744.224)
    org.rust.lang (0.4.171.4656-213)

* **Operating system:**
Windows 10 10.0

## Steps to reproduce
1. create Binary Rust project
2. create new additional crate inside with a proc macro
3. place usage of this proc macro in a primary crate in code
4. try to expand macro at the usage place by `Rust/Show Expanded Macro`
### Expected:
See an expanded macro
### Actual:
`Failed to expand the macro: can't find macro index of the macro call` red floating message appears

[macro_issue.zip](https://github.com/intellij-rust/intellij-rust/files/8929646/macro_issue.zip)
![image](https://user-images.githubusercontent.com/3194236/174351738-475922fe-8db1-485d-b65c-36c6a25a7d12.png)

**Comment by kkolyan** [comment]
okay, that's gone after enabling `org.rust.cargo.evaluate.build.scripts` in addtition to previously enabled `org.rust.macros.proc`.

But then if proc macro is above the function inside `impl` block, it fails with different message: `Failed to expand the macro: internal error: expansion name not found`

```rust
use macros::shared;

struct A {}

impl A {
    #[shared]
    fn load_some() {}
}

fn main() {
    println!("Hello, world!");
}
```

**Comment by wyatt-herkamp** [comment]
> okay, that's gone after enabling `org.rust.cargo.evaluate.build.scripts` in addtition to previously enabled `org.rust.macros.proc`.
> 
> But then if proc macro is above the function inside `impl` block, it fails with different message: `Failed to expand the macro: internal error: expansion name not found`
> 
> ```rust
> use macros::shared;
> 
> struct A {}
> 
> impl A {
>     #[shared]
>     fn load_some() {}
> }
> 
> fn main() {
>     println!("Hello, world!");
> }
> ```


I am having the same issue on Windows 11 latest Clion

The issue does not happen on Linux.
