### ISSUE TITLE
Add test for running annotators with rustc source 

### ISSUE THREAD

**Issue by mkaput** [intellij-rust/intellij-rust#896]
Along with #864 and #886 it may be worth to run annotations throughout rustc source (just like we currently do with parser) and ensure we do not output any false positives for error annotations. This will be also perfect performance test.

**Comment by alygin** [comment]
> just like we currently do with parser

Do you mean `RustParserPerformanceTest` or are there other similar tests?

**Comment by matklad** [comment]
There are `RustHighlightingPerformanceTest` and `RustParserPerformanceTest`. This separation is more or less arbitrary at the moment.

**Comment by alygin** [comment]
Just for information: since `RustParserPerformanceTest` uses `checkHighlighting()` &mdash; which among other things also runs annotators &mdash; it already catches false positive annotations in stdlib sources and reports performance metrics.

**Comment by dima74** [comment]
`RsRealProjectAnalysisTest` was added in #3419, so I guess the issue can be closed
