### ISSUE TITLE
No rust SDK

### ISSUE THREAD

**Issue by bubuker** [intellij-rust/intellij-rust#898]
I'm using IDEA 2016.3.2 with rust plugin 0.1.0.1385-nightly.
I created project, tried to compile  and I’m getting to sdk problem.
I tried add sdk but there is no option for rust sdk in window for adding sdk.
Here is screenshot:
![rust_sdk_problem_2017-01-05 18 58 39](https://cloud.githubusercontent.com/assets/2780532/21687199/c23baa06-d381-11e6-8284-2fede86d6cb3.png)

**Comment by matklad** [comment]
Yep, this is a know problem!

Checkout https://intellij-rust.github.io/docs/faq.html#sdk and https://intellij-rust.github.io/docs/quick-start.html!

I think I need just to make it work as expected with IntelliJ IDEA :)

**Comment by bubuker** [comment]
Thanks.
Good idea )
