### ISSUE TITLE
Dropdown menu (list) with test results does not displayed

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#8995]
## Environment

* **IntelliJ Rust plugin version:** 0.4.174.4721-222-nightly
* **Rust toolchain version:** 1.63.0-nightly (546c826f0 2022-06-12) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.2 EAP (CL-222.3048.7)
* **Operating system:** macOS 11.4
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description

https://user-images.githubusercontent.com/49211026/176888420-c472dfc0-5ab9-44aa-bafa-c102cdfed369.mov

## Steps to reproduce
```rust
mod teeest {
    #[test]
    fn test1() {
        assert_eq!(5, 5);
    }

    #[test]
    fn test2() {
        println!("hi!");
        assert_eq!(5, 5);
    }
}
```

## Expected 
List of tests

**Comment by Undin** [comment]
@neonaot it expected since `Show Passed` option is turned off

<img width="315" alt="Screen Shot 2022-07-01 at 14 54 09" src="https://user-images.githubusercontent.com/2539310/176889635-29abaf3f-b8ea-499f-9f61-22c27f738e3d.png">
