### ISSUE TITLE
Leading `|` in nested patterns are incorrectly rejected

### ISSUE THREAD

**Issue by Nilstrieb** [intellij-rust/intellij-rust#9001]
## Environment

* **IntelliJ Rust plugin version:** `0.4.173.4714-221`
* **Rust toolchain version:** `1.63.0-nightly`
* **IDE name and version:** CLion 2022.1.3
* **Operating system:** Windows 11 + WSL2 (development in WSL2)

## Problem description

Intellij-rust does not accept leading `|` in nested patterns, even though it is legal syntax.

## Steps to reproduce

The following code is valid rust code:
```rust
fn main() {
    match Some(5) {
        Some(
            | 6
            | 7
        ) => true,
        | None
        | None => false,
        _ => false,
    };
}
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a015e1ba7ea626c2b15014b8d5cbcc26)

But intellij-rust emits an error

```
a leading `|` is only allowed in a top-level pattern
```

**Comment by afetisov** [comment]
Hm, this is an explicit check in the IDE, and is part of the test suite. Was it at some point rejected by Rust and added as valid syntax later?

**Comment by afetisov** [comment]
Indeed, leading `|` in nested or-patterns was allowed [in 2021](https://github.com/rust-lang/rust/pull/81869) and included in the final stabilization of or-patterns.
