### ISSUE TITLE
Matching brace not inserted

### ISSUE THREAD

**Issue by TobiasDeBruijn** [intellij-rust/intellij-rust#9007]
## Environment

* **IntelliJ Rust plugin version:** 0.4.175.4729-221-nightly
* **Rust toolchain version:** 1.61.0 (fe5b13d68 2022-05-18) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.1.3 (CL-221.5921.27)
* **Operating system:** Linux 5.15.0-40-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
No matching braces are generated in certain cases (see below). I feel like this has worked in the past, though I might be misremembering. If it did, consider this a bug, if it did not, consider this a feature request. 

## Steps to reproduce
Consider the following struct:
```rs
struct Foo {
  ...
}
```
When adding a `derive` macro to the struct, no matching braces are inserted:
- `#[`, should generate the matching `]`
- `#[derive(]`, should generate the matching `)`

When adding a type/lifetime parameter to the struct:
- `struct Foo<`, should generate the matching `>`
This doesn't only apply to structs, it also applies to `impl`s

**Comment by Undin** [comment]
@TobiasDeBruijn Is `Insert paireed brackets` option enabled in your IDE?
<img width="1094" alt="Screen Shot 2022-07-05 at 13 11 58" src="https://user-images.githubusercontent.com/2539310/177305385-c3a6cdf9-52e6-48ed-9738-2a144c3e0cd2.png">

**Comment by TobiasDeBruijn** [comment]
Oh damn, that must've gotten turned off. Wow, thanks!
