### ISSUE TITLE
stuck indexing large lalrpop dependency

### ISSUE THREAD

**Issue by mattsse** [intellij-rust/intellij-rust#9008]
## Environment

* **IntelliJ Rust plugin version:** 0.4.175.4729-221-nightly
* **Rust toolchain version:** rustc 1.64.0-nightly (27eb6d701 2022-07-04)
* **IDE name and version:** Clion 2022.1.3
* **Operating system:** macOS 12.4
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

plugin hangs indexing [solang-parser 0.1.16](https://crates.io/crates/solang-parser) crate.

this is a heavy lalrpop crate that generates lots of code in its build.rs

## Steps to reproduce

1. add new crate
cargo new demo
2. add dependency
cargo add solang-parser

stuck at
<img width="372" alt="image" src="https://user-images.githubusercontent.com/19890894/177430470-9ce9d80f-17e4-4e22-a212-32cd64099551.png">

I tried various other plugin versions and channels, and even on Clion EAP, same result.

**Comment by Centimo** [comment]
Got same problem.
IntelliJ Rust plugin version: 0.4.174.4743
Rust toolchain version: 1.62.1
IDE name and version: Clion 2022.1.3
Operating system: Kubuntu 22.04 5.15.0-41-generic

On any project plugin hangs on indexing. Piece of log:
```
2022-07-20 21:18:27,833 [1499186]   INFO - #c.j.c.lang - [Building Activity] Saving symbols… finished in 1 ms
2022-07-20 21:18:27,834 [1499187]   INFO - #c.i.u.i.UnindexedFilesUpdater - Started indexing of TON. Reason: Reindex requested by project root model changes
2022-07-20 21:18:27,835 [1499188]   INFO - #c.i.u.i.UnindexedFilesUpdater - Performing delayed pushing properties tasks for TON took 0ms; general responsiveness: ok; EDT responsiveness: ok
2022-07-20 21:18:27,836 [1499189]   INFO - #c.i.u.i.UnindexedFilesUpdater - Scanning of TON uses 11 scanning threads
2022-07-20 21:18:27,924 [1499277]   INFO - #c.i.u.i.UnindexedFilesUpdater - Scanning completed for TON. Number of scanned files: 2285; Number of files for indexing: 1924 took 89ms; general responsiveness: ok; EDT responsiveness: ok
2022-07-20 21:18:27,924 [1499277]   INFO - #c.i.u.i.UnindexedFilesUpdater - Use 4 indexing threads for indexing of TON
2022-07-20 21:18:28,124 [1499477]   INFO - #c.i.o.a.i.PopupMenuPreloader - 2565 ms since showing to preload popup menu 'Edit' at 'MainMenu' in 9 ms
```

UnindexedFilesUpdater` part is repeated twice.

**Comment by mattsse** [comment]
this is still happening with `Rust 0.4.176.4760-221-nightly` on Clion 2022.1.3

I worked around this by patching the hanging dependency with a local checkout, which does not hang.

disabling and reenabling did nothing.

**Comment by Centimo** [comment]
> The issue is likely fixed in the nightly plugin. Could you please try it? (see [instructions](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly))

In my case the nightly plugin (0.4.176.4762-221-nightly) fix the issue.

**Comment by vlad20012** [comment]
@mattsse we can't reproduce the issue for some reason.

Could you please make and attach a CPU snapshot here? For this, await such hunging indexing, then click `Help | Diagnostic Tools | Start CPU Usage Profiling`, then wait some time (ideally, no less than 1 minute), then click `Help | Diagnostic | Stop CPU Usage Profiling.`. Then you should receive a notification with a done snapshot. 

Could you also please attach your IDE logs? You can do it by `Help` | `Collect Logs and Diagnostic Data`

**Comment by mattsse** [comment]
[CL-221.5921.27_Matthias_23.07.2022_12.41.50.zip](https://github.com/intellij-rust/intellij-rust/files/9173578/CL-221.5921.27_Matthias_23.07.2022_12.41.50.zip)

was able to reproduce the initial example

**Comment by vlad20012** [comment]
Could you also please attach your IDE logs? You can do it by `Help` | `Collect Logs and Diagnostic Data`

**Comment by mattsse** [comment]
oops sorry misread, fresh logs:

[clion-logs-20220723-14274916210143779579779747.zip](https://github.com/intellij-rust/intellij-rust/files/9173755/clion-logs-20220723-14274916210143779579779747.zip)

**Comment by vlad20012** [comment]
As I can see, this is a problem with `Solidity (2.3.9)` plugin. Maybe `solang-parser` has some test fixture files in solidity language that Solidity plugin tries to parse during indexing

**Comment by mattsse** [comment]
oh wow, thank you!

confirm disabling the soldity plugin resolved the issue.

> crate has some test fixture files in solidity language that Solidity plugin tries to parse during indexing

I believe that's the case

closing this here as it's not an issue with this plugin.

thanks!
