### ISSUE TITLE
extern crate completion uses wrong name

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#903]
Cargo package and the library inside the package can have different names. For example, `rust_crypto` package defines the `crypto` crate, so this completion is wrong: 

![crypto](https://cloud.githubusercontent.com/assets/1711539/21744440/c5670a76-d526-11e6-92c4-1c19bb726b4b.png)

By the way, resolve works correctly (resolves `extern crate crypto` and not `extern crate rust_crypto`).

cc @alygin

**Comment by dragostis** [comment]
How does this work? I've added `futures = "0.1.9"` in `Cargo.toml`'s dependencies, and I get absolutely no completion. I'm running the Jan 30th release.

**Comment by matklad** [comment]
@dragostis does it work if you execute **Refresh cargo project** action after adding `futures.rs` to `Cargo.toml`? Our automatic project refresh is not super responsive at the moment, so it might be the case that we didn't start the refresh, or we did start it, but the crate has not finished downloading.

**Comment by dragostis** [comment]
This worked out nicely. I'm pretty sure that the crate was not downloading though after saving `Cargo.toml`.
