### ISSUE TITLE
Can't expand any proc macros in current nightly: `Failed to expand the macro: a procedural macro error occurred:`

### ISSUE THREAD

**Issue by ForsakenHarmony** [intellij-rust/intellij-rust#9048]
## Environment

* **IntelliJ Rust plugin version:** 0.4.175.4741-222-nightly
* **Rust toolchain version:** 1.64.0-nightly (c396bb3b8 2022-07-10) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2022.2 EAP (CL-222.3345.16)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
`intellij-rust` doesn't expand any macros, doesn't matter which project or which crates contain the macros (e.g. `serde::Serialize`)

I get the error message `Failed to expand the macro: a procedural macro error occurred:` (nothing after the colon)

## Steps to reproduce

```rust
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Test {
	pub id:    u64,
	pub name:  String,
}
```

**Comment by ForsakenHarmony** [comment]
Still happening with `0.4.175.4744-222-nightly`

**Comment by ForsakenHarmony** [comment]
It works with an older version of rust (I have `nightly-2022-04-12` installed)

**Comment by ForsakenHarmony** [comment]
Just tried going back to rust `1.63.0-nightly` (`nightly-2022-06-25
`), but it still fails

**Comment by ForsakenHarmony** [comment]
Just debugged the extension, and it seems the error that comes back from the native helper is just `"<unknown error>"`

**Comment by ForsakenHarmony** [comment]
May be related to https://github.com/rust-lang/rust-analyzer/issues/12600

**Comment by vlad20012** [comment]
Breakdowns of proc macros on the nightly Rust are absolutely usual, unfortunately. We even going to specially detect it and show more informative messages (see #8930). More robust solution is discussed [here](https://github.com/rust-lang/rust-analyzer/issues/12579).

You can use stable Rust or try to find a nightly version that works.
