### ISSUE TITLE
Automatically dereference pointer types when debugging with LLDB

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#9050]
## Environment

* **IntelliJ Rust plugin version:** 0.4.175.4733-221-nightly
* **Rust toolchain version:** 1.64.0-nightly (7b46aa594 2022-07-05) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.1.3 (CL-221.5921.27)
* **Operating system:** macOS 11.4
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

Originally posted in https://youtrack.jetbrains.com/issue/CPP-29781

## Problem description

When debugging with LLDB, the contents of references and pointers are not rendered.

<img width="950" alt="image" src="https://user-images.githubusercontent.com/49211026/178464794-b97d3b6e-872d-4ea5-b4cb-44fc44ca75bd.png">

Note, when debugging with GDB instead of LLDB, the contents of references and pointers are rendered properly, except for the summary.

<img width="651" alt="Screenshot 2023-01-30 at 14 58 49" src="https://user-images.githubusercontent.com/4854600/215497731-af9b6f16-ef41-4e8d-bbb4-239a9159a01c.png">

## Steps to reproduce
```rust
fn print(s: &String, s2: String, u: u8) {
    println!("{}, {}, {}", s, s2, u);
}

pub fn main() {
    print(&"hello".to_string(), "hello".to_string(), 5);
}
```

**Comment by nejcb1** [comment]
@neonaot any solution for this? how do you debug currently?

**Comment by ortem** [comment]
@nejcb1 I suppose the easiest solution at the moment to render `s: &String` contents is to add `*s` expression as a watch (via Evaluate expression panel above the variables)
