### ISSUE TITLE
Randomly freezes the whole IDE since last update

### ISSUE THREAD

**Issue by njam** [intellij-rust/intellij-rust#9054]
## Environment

* **IntelliJ Rust plugin version:** 0.4.174.4743-221
* **Rust toolchain version:** 1.59.0 (9d1b2106e 2022-02-23) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2022.1.3 Ultimate Edition (IU-221.5921.22)
* **Operating system:** Linux 5.18.10-200.fc36.x86_64
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Since the last update of the Rust plugin, sometimes the whole IDE freezes. At that point no interaction with the UI is possible anymore.

When it happens I usually SIGKILL the IDE, which leads to all recent changes being lost though.

Here's threaddumps of recent cases:
- [threadDump-20220713-115138.txt](https://github.com/intellij-rust/intellij-rust/files/9101062/threadDump-20220713-115138.txt)
- [threadDump-20220713-115007.txt](https://github.com/intellij-rust/intellij-rust/files/9101067/threadDump-20220713-115007.txt)
- [threadDump-20220713-095233.txt](https://github.com/intellij-rust/intellij-rust/files/9101069/threadDump-20220713-095233.txt)
- [threadDump-20220713-095057.txt](https://github.com/intellij-rust/intellij-rust/files/9101070/threadDump-20220713-095057.txt)

My coworker (who's working on the same codebase) experiences the same problem since the last version.

## Steps to reproduce

Not clear. It seems to happen in random moments.

**Comment by vlad20012** [comment]
Hello!
Thank you for the thread dumps!
Could you please also attach your IDE logs? You can collect them by `Help` | `Collect Logs and Diagnostic Data`

**Comment by vlad20012** [comment]
You can download the previous version of the plugin ([click](https://plugins.jetbrains.com/plugin/8182-rust/versions/stable/189005)) and then install in from disk (see [instructions](url)).
In this case please confirm that rolling back to the previous version really solves the problem.

**Comment by njam** [comment]
Thanks, I rolled back to [0.4.173.4714-221](https://plugins.jetbrains.com/plugin/8182-rust/versions/stable/189005) and the problem went away.

**Comment by njam** [comment]
Here's the log lines from before a freeze. I've redacted some sensitive items.

It seems it's running `/usr/bin/rustup component list` in a loop?

[idea-edit.log.txt](https://github.com/intellij-rust/intellij-rust/files/9101731/idea-edit.log.txt)

**Comment by njam** [comment]
I have this:

My coworker has nothing enabled, but experienced the same problem.

![image](https://user-images.githubusercontent.com/360800/178766821-cf2a9435-bb60-4496-b6f6-c922d6840d79.png)

**Comment by vlad20012** [comment]
Could you please try the latest nightly plugin (see [instructions](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly))? I suppose the issue could be fixed by #9090, but I'm not sure

**Comment by njam** [comment]
@vlad20012 I can confirm that `0.4.176.4760-221-nightly` solves the problem, I didn't experience any freezes.

**Comment by vlad20012** [comment]
I think we can close it then. Thank you for the report and your answers!

Btw #9090 has been released in the yesterday's stable release
