### ISSUE TITLE
Formatting: brackets controle is incorrect

### ISSUE THREAD

**Issue by Wulfklaue** [intellij-rust/intellij-rust#907]
There seems to be a issue with the default formatting overriding user defined choices:

Example:

>     for stream in listener.incoming() {
>         let stream = stream.unwrap();.
>
>         thread::spawn(move || {
>             handle_client(stream).unwrap();
>         });
>     }

When using brackets in this style. A preference of mine for readability, brackets need to match there line:

>     for stream in listener.incoming() 
>     {
>         let stream = stream.unwrap();.
>
>         thread::spawn(move || {
>             handle_client(stream).unwrap();
>         });
>     }

The formatting will alter them into:

>     for stream in listener.incoming() 
>          {
>               let stream = stream.unwrap();.
>
>              thread::spawn(move || {
>                   handle_client(stream).unwrap();
>               });
>          }

What looks ugly and there seems to be no way to disable this behavior.  After trying all the options in the "Wrapping and Brackets", there seems to been no way to disable this behavior.

**Comment by matklad** [comment]
Yep, we need to support "Put left brace on the new line" option. 

The relevant code is [spacing.kt](https://github.com/intellij-rust/intellij-rust/blob/ed74ca818b588168943747cbe28a79120507e323/src/main/kotlin/org/rust/ide/formatter/impl/spacing.kt) (look for `LBRACE`) and [settings](https://github.com/intellij-rust/intellij-rust/tree/ed74ca818b588168943747cbe28a79120507e323/src/main/kotlin/org/rust/ide/formatter/settings).
