### ISSUE TITLE
Missing source code links

### ISSUE THREAD

**Issue by alygin** [intellij-rust/intellij-rust#909]
Error locations are not wrapped into source code links in error messages:

<img width="314" alt="screen shot 2017-01-09 at 20 28 13" src="https://cloud.githubusercontent.com/assets/2101250/21776160/412925fc-d6aa-11e6-92b1-e835ae6430ef.png">

Unit tests are ok, though.

It seems that [this commit](https://github.com/intellij-rust/intellij-rust/commit/ec88fbe2595f62d72384160ecd2db344c37c6c2c) has broken something.

IDEA 2016.3.2

**Comment by matklad** [comment]
>Unit tests are ok, though.

Write unit tests they say, integrated tests are scam they say :)

**Comment by alygin** [comment]
No no no, just old good manual tests. Eyes don't lie :)
Links in panic messages are good now, but those in error/warning messages are still naked:

<img width="514" alt="screen shot 2017-01-10 at 15 56 43" src="https://cloud.githubusercontent.com/assets/2101250/21806972/6dc8fcf6-d74d-11e6-8847-a28d69271b2e.png">
