### ISSUE TITLE
Types autocomplete and go-to-defenition are not working with k8s-openapi

### ISSUE THREAD

**Issue by testitm** [intellij-rust/intellij-rust#9093]
## Environment

* **IntelliJ Rust plugin version:** 0.4.164.4409-212
* **Rust toolchain version:** 1.57.0 (f1edd0429 2021-11-29) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.2.4 Ultimate Edition (IU-212.5712.43)
* **Operating system:** macOS 12.2.1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
I installed `k8s-openapi` dependency and can't use it's types and go-to-definition feature, for example - `k8s_openapi::api::core::v1::Pod`
When I try to go-to-defenition to `Pod`, I get message `Cannot find declaration to go to`, but I can go-to `::api::`, so it means that it finds `api/mod.rs`, but not `core`, for some reason.
When I try to use variable, that don't print type hints and there is no autocomplete.

p.s. build process works without errors

## Steps to reproduce
Install `k8s-openapi = { version = "0.15.0", features = ["v1_24"] }`
Import `k8s_openapi::api::core::v1::Pod` and try to use autocomplete/go-to-defenition

```rust
use k8s_openapi::api::core::v1::Pod;
use kube::{
    api::{Api, ListParams, PostParams, ResourceExt},
    Client,
};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = Client::try_default().await?;
    let pods: Api<Pod> = Api::default_namespaced(client);
}
```

**Comment by testitm** [comment]
<img width="454" alt="Screenshot 2022-07-20 at 11 41 17" src="https://user-images.githubusercontent.com/87523283/179938119-6597d4be-a8fa-41c4-8d89-d2909a562680.png">
<img width="507" alt="Screenshot 2022-07-20 at 11 41 09" src="https://user-images.githubusercontent.com/87523283/179938129-68379b23-6fa7-4223-9c0e-8f2a31e5283b.png">
<img width="1002" alt="Screenshot 2022-07-20 at 09 10 02" src="https://user-images.githubusercontent.com/87523283/179938136-06d2b627-6b8e-4390-8979-25aed477f81f.png">

**Comment by testitm** [comment]
Thank you for your response!
I tried this now, but still same behavior :)
I even reinstalled my Idea Ultimate. But after all message `Cannot find declaration to go to` dissapeared, and now it's like non-clickable definition

**Comment by Undin** [comment]
Probably, it's because you use quite old plugin version published around half year ago. I'd suggest trying the latest Rust plugin but `0.4.164` plugin version is the latest version that supports `2021.2` major IDE version. So to try the latest plugin version, you need to upgrade your IDE first

**Comment by testitm** [comment]
I tried this feature in such env, after upgrading :)

## Environment

* **IntelliJ Rust plugin version:** 0.4.174.4743-221
* **Rust toolchain version:** 1.62.1 (e092d0b6b 2022-07-16) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2022.1.4 Ultimate Edition (IU-221.6008.13)
* **Operating system:** macOS 12.2.1
* **Macro expansion engine:** new
* **Name resolution engine:** new

**Comment by markmandel** [comment]
I just came here to say that https://github.com/intellij-rust/intellij-rust/issues/9093#issuecomment-1190010829 just changed my life.

Thank you!

**Comment by bazalp** [comment]
I had this problem with the Tauri commands and the solution was to switch to enable `org.rust.macros.proc`
<img width="685" alt="Capture d’écran 2023-05-19 à 13 36 01" src="https://github.com/intellij-rust/intellij-rust/assets/25566437/8e5998a2-6fbf-43d4-84e0-1c46f90a257e">
