### ISSUE TITLE
Most recent update consumes 100% (on all cores)

### ISSUE THREAD

**Issue by ctron** [intellij-rust/intellij-rust#9110]
## Environment

* **IntelliJ Rust plugin version:** 0.4.175.4772-221
* **Rust toolchain version:** 1.62.1 (e092d0b6b 2022-07-16) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.1.3 (CL-221.5921.27)
* **Operating system:** Linux 5.18.13-200.fc36.x86_64
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

The most recent update consumes 100% of most cores. I am not sure what it does. Loading the same projects as right before the update.

## Steps to reproduce

* Update to the newest version

**Comment by ctron** [comment]
![image](https://user-images.githubusercontent.com/202474/180802128-45031d80-88ac-4bac-b1c5-dbe7c3e67890.png)

CPU usage: 1800% (having 12/24 cores/threads)

**Comment by ctron** [comment]
Clearing the cache does not seem to help.

**Comment by ctron** [comment]
Downgrading (and clearing caches) does seem to "fix" it.

**Comment by ctron** [comment]
I just upgraded to "CLion 2022.2", which triggered an update of the Rust plugin too. Same behavior. Downgrading again works.

What I notices is that the CPU load goes down when after a while when not clicking anything in the IDE. And once you click in a file, the spikes up and continues to stay high, until you stop interacting with the IDE for a while.

But in a nutshell, the new version is not usable IMHO.

**Comment by ctron** [comment]
Maybe one quick workaround could be to limit the number of cores that get used by whatever is triggering this. In this case it would at least not bring the whole machine down. Maybe make it configurable.

**Comment by vlad20012** [comment]
Could you please make and attach here a CPU snapshot? For this, in CLIon click on `Help | Diagnostic | Start CPU Usage Profiling`, then ensure the IDE consumes 100% CPU as you states, then wait some time (ideally, no less than 1 minute), then click on `Help | Diagnostic | Stop CPU Usage Profiling`. Then you should receive a notification with a done snapshot.

Could you please also attach your IDE logs? You can collect them by `Help` | `Collect Logs and Diagnostic Data`

**Comment by ctron** [comment]
One more thing I noticed this time: After installing, clearing caches and starting up, it is ok-ish. However, it also seems that indexing is running and keeps running for quite a while. Even seems to trigger re-indexing after restarting the IDE. However, the problems only start **after** indexing is finished. Normally you can tell it is when run actions become active again, or ToDo markers in the editors get colored differently.

**Comment by nthuemmel-scontain** [comment]
Same issue here. Following references does not work either (infinite progress bar).

Downgrading to version 0.4.174.4743-221 fixes it.

**Comment by vlad20012** [comment]
The issue seems to be caused by #9021. I this we'll revert it in the nearest release and will try to fix it properly in next releases

**Comment by vlad20012** [comment]
The issue is fixed in the nightly plugin. You can try it now (see [instructions](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly))

**Comment by vlad20012** [comment]
@ctron @nthuemmel-scontain, by the way, are you faced the issue on some open-source project? If yes, could you please link the project so we can better test our further releases?

**Comment by ctron** [comment]
> @ctron @nthuemmel-scontain, by the way, are you faced the issue on some open-source project? If yes, could you please link the project so we can better test our further releases?

Yes, sure. This is the one: https://github.com/drogue-iot/drogue-cloud
