### ISSUE TITLE
Modifying dependencies makes IDE unusable

### ISSUE THREAD

**Issue by DzenanJupic** [intellij-rust/intellij-rust#9119]
## Environment

* **IntelliJ Rust plugin version:** 0.4.176.4773-221-nightly
* **Rust toolchain version:** 1.64.0-nightly (263edd43c 2022-07-17) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.1.3 (CL-221.5921.27)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description

When adding or modifying dependencies it seems like the complete indexing process starts from scratch and all macros are expanded again. The IDE is essentially unusable for one or two minutes. That is definitely a regression (also happens with the stable plugin version), since that was not the case a few weeks ago (I had the same features enabled).

## Steps to reproduce

Open a workspace with a bunch of projects, add a dependency or modify the features of one, and watch the IDE start processing the changes.

I could create and provide IDE profiles if that helps.

**Comment by mili-l** [comment]
Hi @DzenanJupic 
Thank you for the report
> I could create and provide IDE profiles if that helps.

yes, please, could you collect your logs 
`Help -> Collect Logs and Diagnostic Data`

cc @vlad20012

**Comment by DzenanJupic** [comment]
The newest update, with the reload only on `Ctrl + Shift + O` seems to fix it for me
