### ISSUE TITLE
Highlight matching angle brackerts

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#912]
In something like `Result<Foo, Bar>`, `<` should be highlighted when the cursor is over `>`.

This should not be hard (I hope :) ), but I don't know off the top of my head which extension point do we need exactly. A good idea would be to find out how Java does this.

**Comment by mkaput** [comment]
I worked on that some time ago, they do some mangling in brace matcher: https://upsource.jetbrains.com/idea-ce/file/idea-ce-1ee8a1fbfebb243266c84879345f8030dd3c2bbe/java/java-impl/src/com/intellij/codeInsight/highlighting/JavaBraceMatcher.java?nav=0:0:focused

Test: https://upsource.jetbrains.com/idea-ce/file/idea-ce-1ee8a1fbfebb243266c84879345f8030dd3c2bbe/java/java-tests/testSrc/com/intellij/codeInsight/highlighting/JavaBraceMatcherTest.java?nav=0:0:focused

**Comment by matklad** [comment]
Fixed and in alpha
