### ISSUE TITLE
testParsingCompilerSource still fail on nightly rust

### ISSUE THREAD

**Issue by la10736** [intellij-rust/intellij-rust#913]
I tried today again to build plugin and found yet an other Phi parsing issue on compiling `collections/hash/map.rs`:

```
mdamico@mdamico-laptop:~/sviluppo/intellij-rust$ git log -1
commit 8a0e5d358c9e60bd060e668f1130dd99134669d2
Author: Aleksey Kladov <aleksey.kladov@gmail.com>
Date:   Wed Jan 11 11:58:32 2017 +0300

    (TY): try operator
```

and 

```
mdamico@mdamico-laptop:~/sviluppo/intellij-rust$ rustc --version
rustc 1.16.0-nightly (47c8d9fdc 2017-01-08)
```

```
org.rust.lang.core.parser.RustParserPerformanceTest > testParsingCompilerSources FAILED
    java.lang.RuntimeException: java.lang.IllegalStateException: Failed to parse /home/mdamico/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/collections/hash/map.rs

...
```

 Just a question: why travis reports that perfomance tests are ok?

**Comment by matklad** [comment]
>Just a question: why travis reports that perfomance tests are ok?

They are skipped on travis :)  I guess this is the underlying bug here IIRC, performance and "conformance" tests used to be separate, so it made sense to skip them on travis. Now we should just run them!

**Comment by matklad** [comment]
>They are skipped on travis :) I guess this is the underlying bug here IIRC, performance and "conformance" tests used to be separate, so it made sense to skip them on travis. Now we should just run them!

Wait, this is just wrong! These tests are run on Travis, but we use stable Rust on them.

**Comment by la10736** [comment]
Ohhhhhh .... fine. It sounds reasonable.

**Comment by matklad** [comment]
Should be fixed by https://github.com/intellij-rust/intellij-rust/commit/0c3de9083dcc18c2988afda9983e21db33ad4d1e and https://github.com/intellij-rust/intellij-rust/commit/9f30b9654f7489ca97a35faa89cb57fd16d0c714


Thank you **very** much for relentlessly poking me until I fixed the underlying issue with the way we do CI!
