### ISSUE TITLE
Half open range pattern in match arm triggers diagnostic when it shouldn't

### ISSUE THREAD

**Issue by JonathanxD** [intellij-rust/intellij-rust#9136]
## Environment

* **IntelliJ Rust plugin version:** 0.4.175.4772-222
* **Rust toolchain version:** 1.64.0-nightly (9067d5277 2022-07-28) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.2 (CL-222.3345.126)
* **Operating system:** Linux 5.18.14-arch1-1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

I have something like this:

```rust
struct Opts {
    // ...
    verbose: u8,
    // ...
}

fn main() -> std::io::Result<()> {
    let opts: Opts = Opts {
        verbose: 0,
    };

    match opts.verbose {
        0 => dbg!("error"),
        1 => dbg!("info"),
        (2..) => dbg!("trace"),
    };

    Ok(())
}
```

And the IDE gives me this diagnostic:

![diagnostic](https://user-images.githubusercontent.com/5360060/182020662-77d4173a-b450-4363-88a9-77f9c07a1ed4.png)

But it does compile, and is a valid match arm pattern, as explained in the documentation [here](https://doc.rust-lang.org/reference/patterns.html#range-patterns), named as *HalfOpenRangePattern*.

## Steps to reproduce

Just try to use a *HalfOpenRangePattern* in a MatchArm, doesn't need to have parenthesis, for example, this is enough to trigger the diagnostic:

```rust
struct Opts {
    // ...
    verbose: u8,
    // ...
}

fn main() -> std::io::Result<()> {
    let opts: Opts = Opts {
        verbose: 0,
    };

    match opts.verbose {
        0 => dbg!("error"),
        1 => dbg!("info"),
        2.. => dbg!("trace"),
    };

    Ok(())
}
```

**Comment by SteveLauC** [comment]
Yes, this is added in [Rust 1.55](https://blog.rust-lang.org/2021/09/09/Rust-1.55.0.html#open-range-patterns-added).

If you test the code snippet provided in Rust Blog, you will get `<pat const> expected, got '=>'`:

![Screenshot from 2022-10-15 14-23-32](https://user-images.githubusercontent.com/96880612/195972577-d3510ed1-5f28-4eb6-aa79-b9583e6e536b.png)
