### ISSUE TITLE
Recursive Call Marker 4 Times

### ISSUE THREAD

**Issue by Kausta** [intellij-rust/intellij-rust#914]
When editing a line with recursive call it adds the marker up to 4 times and expands the left column of the editor where the marker is. When the line is deleted it leaves the left column of the editor expanded. 

Problem occurs with Intellij IDEA 2016.2.4.

**Comment by matklad** [comment]
This regressed after https://github.com/intellij-rust/intellij-rust/commit/5782a9adb69c742d1914edf56b6bfe3f6ffa6d5a apparently. I remember checking this with 2016.1, but may be only 2016.2 affected? 

I'll look into this! The workaround is to upgrade to 2016.3 :)

**Comment by matklad** [comment]
>but may be only 2016.2 is affected?

Nopt, 2016.1 is affected as well. Looks I've failed to check that properly.
