### ISSUE TITLE
No type-inference for vec! , etc.

### ISSUE THREAD

**Issue by caizixian** [intellij-rust/intellij-rust#915]
With manual annotation, the completion works.

Might related to #484 ?

Is there any workaround or tools to partially support type inference, and therefore enhance auto completion?

**Comment by matklad** [comment]
>Is there any workaround or tools to partially support type inference, and therefore enhance auto completion?

No, unfortunately not :(

Macros in general are tough to support, though we should special case the `vec![]`.

**Comment by kumbayo** [comment]
This should be fixed by https://github.com/intellij-rust/intellij-rust/commit/f85c599e851a11ed48eaa709d1c42603ff34d453 but this issue was not marked as closed...

**Comment by matklad** [comment]
Indeed!
