### ISSUE TITLE
Stop auto-importing `panic`, I don't want `core::panicking::panic`

### ISSUE THREAD

**Issue by samuelcolvin** [intellij-rust/intellij-rust#9157]
## Environment

* **IntelliJ Rust plugin version:** `0.4.175.4772-222`
* **Rust toolchain version:** `rustc 1.64.0-nightly (d68e7ebc3 2022-07-20)`
* **IDE name and version:** PyCharm Professional Build #PY-222.3345.131, built on July 27, 2022
* **Operating system:** Ubuntu

## Problem description

When I type "panic" I often get recommended `core::panicking::panic` rather than the `panic!` macro, if I select it by mistake, the following gets auto-imported

```rs
extern crate core;

use core::panicking::panic;
```

Obviously virtually no one wants `core::panicking::panic` when thy're typing "panic", so I surely this method should be completely ignored.

Also happens for `unreachable`, here's a screenshots:

![image](https://user-images.githubusercontent.com/4039449/182819728-7f152d0f-8a59-448d-80cb-e567d542d977.png)

There are other such foot-guns, but these are the most annoying.

## Steps to reproduce

On a new line, type "pan" look at the suggestions.

**Comment by samuelcolvin** [comment]
Thanks so much for the rust plugin in pycharm, it's a life saver. I use it all the time while working on [pydantic-core](https://github.com/samuelcolvin/pydantic-core)

**Comment by dima74** [comment]
@samuelcolvin we are working on the feature to exclude specific paths from auto-import and completion: #9123. I guess we will add `core::panicking` and `std::intrinsics::unreachable` to default exclusion list

> There are other such foot-guns

Btw, what other such examples do you know?
