### ISSUE TITLE
Use `rust-analyzer-proc-macro-srv` from the toolchain to expand proc macros

### ISSUE THREAD

**Issue by ForsakenHarmony** [intellij-rust/intellij-rust#9172]
The latest nightly toolchains now include an executable to expand proc macros, which will always match the current compiler in `{toolchain}/libexec/rust-analyzer-proc-macro-srv`.

It should be possible to use this instead of the native helper that's shipped with `intellij-rust`.

For reference:
https://fasterthanli.me/articles/proc-macro-support-in-rust-analyzer-for-nightly-rustc-versions

**Comment by vlad20012** [comment]
Yep, we know it and will use it soon. But thank you for the tip :)
