### ISSUE TITLE
Make sure we support several recent versions of the toolchain

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#919]
So looks like we no longer support Rust 1.12.0, because it does not export `workspace_members` in the metadata. By itself it is totally fine, 1.12.0 is oldish.

However, this indicates a problem: we don't run CI over older version of toolchain, so such regressions can slip unnoticed.  

@alygin @mkaput how many toolchains  should we support? Looks like at the moment we support 1.13 and 1.14 and, given that 1.15 is really soon, the natural option would be to settle to three latest released minor versinos and the current nightly. 

I think we should update travis such that it executes two builds: EAP IDEA + nightly rust and old IDEA + old stable rust. Does that sound reasonable?

**Comment by mkaput** [comment]
> the natural option would be to settle to three latest released minor versinos and the current nightly.

More natural would be to support as many toolchains as many are supported by the Rust team, though as far as I remember, no such routine exists yet. So supporting last three versions is ok for me, as for now at least.

> I think we should update travis such that it executes two builds: EAP IDEA + nightly rust and old IDEA + old stable rust. Does that sound reasonable?

I think we should also check current IDEA + current stable Rust

**Comment by matklad** [comment]
>I think we should also check current IDEA + current stable Rust

That's what I develop with, so this is naturally covered :) I don't want to add new CI configurations because sometimes tests fail at random, and it can be annoying (and yes, I know about the recent ThreadLeaked failures, and I know exactly what is the reason and I can 100% reproduce them, I just havn't had a chance to properly fix them).

**Comment by la10736** [comment]
I'm using stable Idea but nightly Rust.... I don't know if I'm the only one, but I think is not a so strange environment.

**Comment by matklad** [comment]
>I think is not a so strange environment.

I think version of Ruts and version of IDEA have orthogonal failure modes, so it does matter which exact combinations do we test. That is, I think my proposal is more or less equivalent to nightly rust + old ide and old rust + eap IDE..

**Comment by la10736** [comment]
Ok... I suspected it but I was not sure. Thanks.

**Comment by johnthagen** [comment]
I think this sounds reasonable, and I've seen other well maintained libraries provide similar compatibility support, such as [`clap`](https://github.com/kbknapp/clap-rs#minimum-version-of-rust)

> `clap` will officially support current stable Rust, minus two releases, but may work with prior releases as well. For example, current stable Rust at the time of this writing is 1.13.0, meaning `clap` is guaranteed to compile with 1.11.0 and beyond. At the 1.14.0 release, `clap` will be guaranteed to compile with 1.12.0 and beyond, etc.

**Comment by alygin** [comment]
I think that the "stable minus two releases" policy makes sense at the moment. But as the language (and the plugin) matures, I would expect revising it in a not so far future.

**Comment by matklad** [comment]
Ok, let's make it minimum two releases then!  (I've alreday updated `.travis.yml`). Also, I won't be actively updating the lower bound with every release, only if there's some code in plugin to explicitly support older versions, so in practice we may support more versions!
