### ISSUE TITLE
Project Sync ignoring `rustup-toolchain.toml`-overriden toolchain

### ISSUE THREAD

**Issue by Kage-Yami** [intellij-rust/intellij-rust#9196]
## Environment

* **IntelliJ Rust plugin version:** `0.4.175.4772-222`
* **Rust toolchain version:**
   * Stable (default): `rustc 1.63.0 (4b91a6ea7 2022-08-08)`
   * Nightly: `rustc 1.65.0-nightly (f22819bcc 2022-08-12)`
* **IDE name and version:** CLion 2022.2
   * Build: `#CL-222.3345.126, built on July 27, 2022`
* **Operating system:** Windows 11 Pro 21H2
   * OS build: `22000.856`
   * Experience: `Windows Feature Experience Pack 1000.22000.856.0`

## Problem description

When the IDE tries to sync the project, if the toolchain is overridden using `rustup-toolchain.toml`, the override is not applied, and the default is used instead.

## Steps to reproduce

1. Create a new project
2. Create `rustup-toolchain.toml` with:
   ```toml
   [toolchain]
   channel = "nightly"
   ```
3. Create `.cargo/config.toml` with:
   ```toml
   [target.x86_64-pc-windows-msvc]
   rustflags = ["-Zshare-generics=y"]
   ```
4. Refresh Cargo Projects in Cargo tool window

An error should occur because of the configured nightly-only option:

```
Execution failed (exit code 101).
~/.cargo/bin/cargo.exe metadata --verbose --format-version 1 --all-features
stdout : error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `sccache.exe ~\.cargo\bin\rustc.exe - --crate-name ___ --print=file-names -Zshare-generics=y --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
  --- stderr
  error: the option `Z` is only accepted on the nightly compiler


stderr : 
```

**Comment by Kage-Yami** [comment]
What's especially annoying is that if I comment out the `rustflags` setting, do the sync, and then uncomment it again, the IDE detects that the cargo project structure has changed, and wants me to sync again. :/

**Comment by Undin** [comment]
> An error should occur because of the configured nightly-only option:

It's expected since you use wrong file to specify project toolchain. You should use [rust-toolchain.toml](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) instead of `rustup-toolchain.toml`

> What's especially annoying is that if I comment out the rustflags setting, do the sync, and then uncomment it again, the IDE detects that the cargo project structure has changed, and wants me to sync again. :/

It works as expected because changes in config file may change the project model. That's why the plugin shows you the corresponding notification

**Comment by Kage-Yami** [comment]
> > An error should occur because of the configured nightly-only option:
> 
> It's expected since you use wrong file to specify project toolchain. You should use [rust-toolchain.toml](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) instead of `rustup-toolchain.toml`

Doh, thanks for picking up the misnamed file. Can confirm everything works as expected after I fix that.
