### ISSUE TITLE
Failure to evaluate build script for anyhow 

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#9198]
## Environment

CLion2022.2
cargo 1.62.1-aarch64-apple-darwin
Rust plugin 0.4.175.4772-222

Originally posted in https://youtrack.jetbrains.com/issue/CPP-30162/Failure-to-evaluate-build-script-for-anyhow

## Problem description
Error during syncing:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /Users/wrichard/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.61/src/lib.rs:214:32
    |
214 | #![cfg_attr(backtrace, feature(backtrace))]
    |                                ^^^^^^^^^
```

## Expected 

Code completion involving include!(concat!(env!("OUT_DIR"), "/bindings.rs")) works

## Steps to reproduce

1. Create a rust project with a dependency on anyhow
1. Enable evaluate.build.scripts and proc macro expansion
1. Sync project

**Comment by Undin** [comment]
Issue in anyhow: https://github.com/dtolnay/anyhow/pull/260

**Comment by Kage-Yami** [comment]
I'm getting the below error on nightly, and I believe it's the same issue, based on: https://github.com/dtolnay/anyhow/issues/254

```rust
error[E0407]: method `backtrace` is not a member of trait `StdError`
   --> ~\.cargo\registry\src\github.com-1ecc6299db9ec823\anyhow-1.0.62\src\context.rs:127:5
    |
127 | /     fn backtrace(&self) -> Option<&Backtrace> {
128 | |         self.error.backtrace()
129 | |     }
    | |_____^ not a member of trait `StdError`

(... same for three other locations)
```

What seems to work is, _outside_ of CLion, is doing a `cargo clean` followed immediately by `cargo build` - even syncing and rebuilding within the editor will work as long as that's been done (presumably until something to do with dependencies changes?)
