### ISSUE TITLE
Unresolved reference for std::hash and std::any after rustup update to 1.0

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#920]
### Problem

Turning on the unresolved reference inspection, the two imports (`std::hash` and `std::any`) below are highlighted red. Since they are in `std` probably a bit more important, not sure why they don't resolve when lots of other `std::` do.

```rust
use std::hash::Hash;
use std::any::Any;

fn main() {
}
```

### Environment

- Rust 1.14.0 stable
- intellij-rust 0.1.0.1425
- PyCharm 2016.3.2
- Mac OSX 10.11.6

**Comment by matklad** [comment]
Hm, and if you place the cursor over `hash` and `Hash`, and press `Ctrl+B` (go to definition), does it goes to def properly?

**Comment by johnthagen** [comment]
`Ctrl-B` works on `std` but not `hash`, `Hash`, `any`, or `Any`.

**Comment by johnthagen** [comment]
If I open up `std`, I get errors at these lines as well:

```rust
// The standard macros that are not built-in to the compiler.
#[macro_use]
mod macros;

// The Rust prelude
pub mod prelude;
```

"Cannot declare new module at this location", and then a bunch more again later down in the file.

**Comment by matklad** [comment]
Hm, it seems to work fine here. I think that perhaps something wrong with a caches?

Can you try to do `rustup component remove rust-std`, and reopening the project, or invalidating the caches?

**Comment by johnthagen** [comment]
> Can you try to do `rustup component remove rust-std`, and reopening the project

```bash
$ rustup component remove rust-std
error: component 'rust-std' for target 'x86_64-apple-darwin' is required for toolchain 'stable-x86_64-apple-darwin' and cannot be removed
```
> or invalidating the caches?

I did a `File > Invalidate Caches / Restart`, and I still see the same errors.

**Comment by matklad** [comment]
Strange. Does `Vec` resolve? Is only one project affected?

**Comment by johnthagen** [comment]
This happens for all of my Rust projects (just tested a couple others out).

`std::vec` does not resolve. Here is a screenshot of the possible autocompletes using `std::`

![std-rust](https://cloud.githubusercontent.com/assets/10340167/21907071/f9bc6bc8-d8db-11e6-86ba-c60361fc2885.png)

**Comment by johnthagen** [comment]
@matklad I can confirm that on my Windows 10 x64 machine, I am not seeing this problem when all other variables are the same (obviously a different toolchain).

So that points to either an OSX specific (toolchain?) issue or something about my OSX rustup environment not being configured correctly.

**Comment by matklad** [comment]
Can you switch you macos toolchain to nightly/beta to see if the issues goes away?

**Comment by alexbool** [comment]
For me the issue is still present on nightly

**Comment by la10736** [comment]
@alexbool Have you tried in a new project from scratch?

**Comment by alexbool** [comment]
Hmm, new project from scratch works.
Seems like I had invalid rust src paths configured in IDE in the old project.

**Comment by matklad** [comment]
Can it be that you've done `rustup update`, and maybe it has changed the location of the libraries? Currently we detect stdlib once per project. I think we need to track the toolchain changes more closely and, for example, query the standard librady location on the project start.

**Comment by la10736** [comment]
@matklad nice catch! I'm doing `ruspup update` quite often and my project is broken... Is there a way to check if you guessed correctly?

**Comment by alexbool** [comment]
Yep, doing `rustup update` frequently

**Comment by matklad** [comment]
>Is there a way to check if you guessed correctly?

It is possible to check if this was caused by the `rustup update`: create a project from the command line, add toochain override for an old Rust, open and close project in IDE (make sure to actually open an `.rs` file, this is the moment we start looking for the standard library), add a new override with the updated Rust version, open the IDE. 

Checking if `rustup selfupdate` caused this is more tricky.

 Hm, do you have `.multirust` folder, or do you have only `.rustup`? Rustup recently switched them, and this actually may be the underlying cause. 


And yes, now I think we definitely should check stdlib every time we open a project!

**Comment by la10736** [comment]
> Hm, do you have .multirust folder, or do you have only .rustup? Rustup recently switched them, and this actually may be the underlying cause.

I have both of them.

**Comment by johnthagen** [comment]
I have both, but `.multirust` seems to be a link:

```
...
.multirust@ -> /Users/hagenjt1/.rustup
.rustup/
...
```

intellij-rust detects the stdlib through `.multirust`:

```
/Users/hagenjt1/.multirust/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src
```

**Comment by johnthagen** [comment]
Fixed it. What I had to do was change my stdlib path from:

```
/Users/hagenjt1/.multirust/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src
```

To:

```
/Users/hagenjt1/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src
```

I'll leave the issue open in case there is something in intellij-rust that needs to be fixed to automate this, but otherwise for me everything is fine now.

**Comment by matklad** [comment]
So now we refresh std library location everytime the project is opened. This should help with this issue.
