### ISSUE TITLE
Rust project files show up as non-project files

### ISSUE THREAD

**Issue by andras-gyarmati** [intellij-rust/intellij-rust#9217]
## Environment

* **IntelliJ Rust plugin version:** 0.4.176.4815-222
* **Rust toolchain version:** 1.63.0
* **IDE name and version:** IntelliJ IDEA 2022.2.1 (Ultimate Edition) Build #IU-222.3739.54, built on August 16, 2022
* **Operating system:** Windows 11

## Problem description
Rust and Cargo project files (.rs, .toml etc) show up as non-project files, they have oragne background and the ide shows a warning when I try to edit them.

## Steps to reproduce
Create a new rust project in IDEA and edit the main rust file. You can locate the file if you switch from the Project view to the Project Files view on the left.

**Comment by Undin** [comment]
@andras-gyarmati is your Rust project attached to the plugin project model? You can check it in Cargo tool window
<img width="364" alt="image" src="https://user-images.githubusercontent.com/2539310/185781237-5a2fb5de-a95f-40ed-9d02-f218a8b37738.png">

If no, you can attach it via [`Attach` action](https://plugins.jetbrains.com/plugin/8182-rust/docs/attaching-cargo-projects.html)

**Comment by andras-gyarmati** [comment]
It works now. I tried the attach button earlier and it didnt do anything, I might done somwthing wrong. No issue then. Thanks!
