### ISSUE TITLE
Trait defined by custom derive macro can't be traced properly

### ISSUE THREAD

**Issue by Parallel-Paradox** [intellij-rust/intellij-rust#9226]
## Environment

* **IntelliJ Rust plugin version:** 0.4.176.4815-222
* **Rust toolchain version:** rust version 1.65.0-nightly (c0941dfb5 2022-08-21)
* **IDE name and version:** CLion 2022.2.1
* **Operating system:** Win11

## Problem description

As title, see details in [bevy - discussion](https://github.com/bevyengine/bevy/discussions/5755#discussion-4321176)

## Steps to reproduce

Introduce bevy 0.8 into Cargo.toml, then do:

```rust
use bevy::{
    prelude::*,
    render::render_resource::{AsBindGroup, ShaderRef},
    reflect::TypeUuid};

#[derive(AsBindGroup, Debug, Clone, TypeUuid)]
#[uuid = "ba6efc54-d2b4-43a9-8613-38e49fe091e1"]
pub struct LambertMaterial {}

impl Material for LambertMaterial {
    fn fragment_shader() -> ShaderRef { "shaders/lambert.wgsl".into() }
}
```

**Comment by Undin** [comment]
It's because procedural macro expansion is not enabled by default yet.
See #6908 how to enable it or wait #9729
