### ISSUE TITLE
Something is wrong with codestyle example

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#924]
![code_style](https://cloud.githubusercontent.com/assets/1711539/21928005/78b7f0e2-d999-11e6-9dee-456d8b63454c.png)

This is not how Rust is supposed to look like....

**Comment by mkaput** [comment]
Looks like formatter is doing its job here :/

**Comment by matklad** [comment]
Fixing it: fallout from renaming :sweat_smile:
