### ISSUE TITLE
Fix compatibility with the latest PyCharm version.

### ISSUE THREAD

**Issue by saferif** [intellij-rust/intellij-rust#9253]
## Environment

* **IntelliJ Rust plugin version:** `0.4.176.4815-221`
* **IDE name and version:** `PyCharm 2022.2.1 (Community Edition), Build #PC-222.3739.56`
* **Operating system:** `Mac OS Monterey 12.2.1`

## Problem description
Plug-in cannot be enabled after IDE update: `Incompatible: requires IDE build 221.* or earlier`.

## Steps to reproduce
Update PyCharm to latest version, which at a time is `2022.2.1`.

**Comment by Bben01** [comment]
There are 2 versions released every time, you need to download the one that ends with -222.

**Comment by Undin** [comment]
The plugin has versions compatible with the latest PyCharm. Try to reopen IDE, invoke `Check for Updates` action and check plugin version again
If it doesn't help, just reinstall Rust plugin

**Comment by saferif** [comment]
After Nth (but not the first) IDE restart it indeed seems to be working. Thanks everyone.
