### ISSUE TITLE
Parser doesn't recognize destructuring assignment with underscore wildcard pattern

### ISSUE THREAD

**Issue by ozkriff** [intellij-rust/intellij-rust#9274]
## Environment

* **IntelliJ Rust plugin version:** 0.4.176.4815-222
* **Rust toolchain version:** 1.62.0 (a8314ef7d 2022-06-27) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.2.1 (CL-222.3739.54)
* **Operating system:** Linux 5.4.0-124-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Steps to reproduce

```rust
fn foo() -> Result<(), ()> { Ok(()) }
fn main() {
    _ = foo(); // builds fine since Rust 1.59 but causes parser error in the IDE
}
```

![image](https://user-images.githubusercontent.com/662976/187602214-44719939-d8cc-438b-9182-a6e3fec497b4.png)

https://rust-lang.github.io/rfcs/2909-destructuring-assignment.html#underscores-and-ellipses

Related to https://github.com/intellij-rust/intellij-rust/issues/6598

**Comment by afetisov** [comment]
Related to #8667
