### ISSUE TITLE
Layering of completion options icons

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#9275]
Originally posted in https://youtrack.jetbrains.com/issue/CPP-30333

## Environment

* **IntelliJ Rust plugin version:** 0.4.178.4836-222-nightly
* **Rust toolchain version:** 1.65.0-nightly (015a824f2 2022-08-22) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.2.1 (CL-222.3739.54)
* **Operating system:** macOS 12.5.1
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
<img width="377" alt="image" src="https://user-images.githubusercontent.com/49211026/187650700-a9a22c03-357f-4a5c-a93f-ca7542a555c7.png">

## Steps to reproduce
```rust
fn main() {
    println!("Hello, world!");
}


#[derive(Eq\*caret*\)]
struct MyStruct {
    x: u8,
}

```

**Comment by Undin** [comment]
We show doubled icon if the plugin suggests several items in a single completion item.
So I close it since it works as expected
