### ISSUE TITLE
`println!("{t+5}")` totally breaks IDE 

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#9282]
## Environment

* **IntelliJ Rust plugin version:** 0.4.178.4849-222-nightly
* **Rust toolchain version:** 1.65.0-nightly (015a824f2 2022-08-22) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.2.1 (CL-222.3739.54)
* **Operating system:** macOS 12.5.1
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
It seems that some endless calculation starts.
1. increasing CPU usage
2. IDE functions stop working (completion, higlighting)

https://user-images.githubusercontent.com/49211026/187917322-0906f6cc-8be5-4e35-8e5b-4b40908c984c.mov

## Steps to reproduce
```rust
fn main() {
    let t = 8;
    println!("{t}");
}
```
1. add `+ 8` in {}
1. remove `}` and  type it back 
1. try to type something 

and play with code in other ways : )

**Comment by vlad20012** [comment]
There is a similar case in a valid code:

```rust
struct S;
impl Display for S {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        todo!()
    }
}

impl S {
    fn foo(&self) {
        println!("{self}");
    }
}
```

https://youtrack.jetbrains.com/issue/CPP-30496/Rust-plugin-gives-unwarranted-Unreachable-code-warning
