### ISSUE TITLE
Gutter icon to open docs.rs documentation of the external crate

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#931]
It'd be great to place an icon to the left of

```
extern crate num_bigint;
```

which would open the browser at https://docs.rs/num-bigint/0.1.35/num_bigint/.

**Comment by mkaput** [comment]
Shouldn't this be rather integrated into <kbd>Ctrl+Q</kbd>?

**Comment by matklad** [comment]
Yeah, we can add a like to `doc.rs` when we render documentation as well, but I think gutter icon is a bit more important because it is more easy to discover.

**Comment by alygin** [comment]
<img width="249" alt="screen shot 2017-01-17 at 01 20 59" src="https://cloud.githubusercontent.com/assets/2101250/22001412/1dea15b8-dc56-11e6-989d-c92842bd7018.png">

or

<img width="258" alt="screen shot 2017-01-17 at 01 22 00" src="https://cloud.githubusercontent.com/assets/2101250/22001415/2259a79e-dc56-11e6-92f5-2596240008de.png">

?

**Comment by matklad** [comment]
I like `?` :)
