### ISSUE TITLE
Optimize imports doesn't remove unused inports inside function 

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#9316]
## Environment

* **IntelliJ Rust plugin version:** 0.4.178.4857-222-nightly
* **Rust toolchain version:** 1.59.0-nightly (cfa3fe5af 2021-12-31) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.2.1 (CL-222.3739.54)
* **Operating system:** macOS 12.5.1
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
<img width="506" alt="image" src="https://user-images.githubusercontent.com/49211026/188566143-7452abea-723b-43ff-b9e8-b6288b82eacd.png">
Only first line will be removed, although the plugin highlights that all imports are not used.

Useful info: unused imports inside mod are removed. 

## Steps to reproduce
```rust
use rand::Error; // will be removed

fn main() {
    use crate::foo;
    use rand::random;
    println!("hello")
}


fn foo() {}
```

**Comment by apbyte** [comment]
same in intellj

**Comment by wcarmon** [comment]
same in Goland

Temporary workaround: 
- `cargo fix --allow-dirty --allow-staged`
- WARNING: this fixes other things too, not limited to unused imports

Related items:
- https://github.com/intellij-rust/intellij-rust/issues/2158
- https://i.imgur.com/bgQbXsg.png
