### ISSUE TITLE
Indexing gets stuck on `solang-parser` crate

### ISSUE THREAD

**Issue by agostbiro** [intellij-rust/intellij-rust#9323]
## Environment

* **IntelliJ Rust plugin version:**
0.4.177.4844-222

* **Rust toolchain version:**
stable-aarch64-apple-darwin. rustc 1.62.0 (a8314ef7d 2022-06-27)

* **IDE name and version:**
AppCode 2022.2. Build #OC-222.3345.144, built on August 2, 2022. (Happens on the latest IntelliJ as well.)

* **Operating system:**
MacOS Monterey 12.5.1

## Problem description

Indexing [this project](https://github.com/agostbiro/rust-intellij-index) gets stuck on indexing the `solang-parser = "0.1.17"` crate. In projects that don't depend on this crate indexing succeeds quickly.

## Steps to reproduce

Open the [linked](https://github.com/agostbiro/rust-intellij-index) project in an IDE with the latest Rust IntelliJ plugin.

**Comment by agostbiro** [comment]
Downgrading to IntelliJ Rust 0.4.175.4772-221 and AppCode 2022.1.4 solves the issue.

**Comment by agostbiro** [comment]
Hmm it happens again after the downgrade with Rust 0.4.175.4772-221 and AppCode 2022.1.4

**Comment by vlad20012** [comment]
Do you have `Solidity` plugin installed? If yes, this is a bug in that plugin, see #9008

**Comment by agostbiro** [comment]
Right, it started happening again after I enabled the Solidity plugin, just didn't connect the two. Thanks, closing this as duplicated of https://github.com/intellij-solidity/intellij-solidity/issues/317
