### ISSUE TITLE
Make sure that module index works with case insensitive file systems

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#933]
To fix this, we need to add

```
    // Case insensitive because some file systems are like this. 
    override fun getKeyDescriptor(): KeyDescriptor<String> =
        CaseInsensitiveEnumeratorStringDescriptor.INSTANCE
```

to `org.rust.lang.core.stubs.index.RsModulesIndex`.

But we need to verify that it indeed works, and ideally write a test.

**Comment by matklad** [comment]
Would be great to add an inspection with warning as well!

**Comment by mkaput** [comment]
Shouldn't AppVeyor check this automatically? I so, then manual verifying is not needed :)

**Comment by matklad** [comment]
>Shouldn't AppVeyor check this automatically?

Hm, yes, I can condition tests on the OS I think. Thanks for the idea!

**Comment by matklad** [comment]
Closed in https://github.com/intellij-rust/intellij-rust/commit/83b960bd7388680bf4aefe972e78c59ef7887769
