### ISSUE TITLE
todo! and early return causes the whole match to be marked as unreachable

### ISSUE THREAD

**Issue by darksv** [intellij-rust/intellij-rust#9355]
## Environment

* **IntelliJ Rust plugin version:** 0.4.178.4873-222
* **Rust toolchain version:** 1.65.0-nightly (1d37ed661 2022-09-09) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2022.2.1 (CL-222.3739.54)
* **Operating system:** Windows 11 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.macros.proc

## Problem description
Using todo! macro and an early return inside of match arms causes the whole match expression to be marked as unreachable:
![obraz](https://user-images.githubusercontent.com/6718130/190243104-a307ee87-ad1e-4705-a263-0a37faa39fac.png)

## Steps to reproduce
```rs
fn foo(a: u32) -> u32 {
    match a {
        42 => todo!(),
        _ => return 123,
    }
}
```

**Comment by ortem** [comment]
@vlad20012 It looks like the problem occurs because the plugin cannot properly infer `todo!()` macro call type.
![image](https://user-images.githubusercontent.com/4854600/190401587-b9458c43-5011-4fe4-a58e-6c8f3c7a0776.png)

```Rust
fn main() {
    let unknown = todo!();
}

macro_rules! my_todo {
    () => {
        panic!("not yet implemented")
    };
}

fn call_my_todo(a: u32) -> u32 {
    match a {
        42 => my_todo!(),
        _ => return 123,
    }
}
fn call_todo(a: u32) -> u32 {
    match a {
        42 => todo!(),
        _ => return 123,
    }
}
```
