### ISSUE TITLE
"File is not included in module tree, analysis is not available" unless project is in root dir

### ISSUE THREAD

**Issue by gatlace** [intellij-rust/intellij-rust#9368]
## Environment

* **IntelliJ Rust plugin version:**
* 0.4.178.4873-222
* **Rust toolchain version:**
* rustc 1.63.0
* **IDE name and version:**
* IntelliJ 2022.2.1, 2
* **Operating system:**
* OpenSUSE

## Problem description
I have a project that has a crate as a subdirectory. It's not the crate itself or anything in it; I'll initialize a new, blank, nondescript project and get the error in main.rs. It doesn't happen if the project is in the root directory, though.

I tried invalidating cache, deleting .idea, and reinstalling.

## Steps to reproduce
Make a directory, then make a crate in that directory with `cargo new`

**Comment by vlad20012** [comment]
Hello!

Could you please attach a screenshot of the message?

**Comment by gatlace** [comment]
root dir, no error:
![image](https://user-images.githubusercontent.com/26052216/190870348-012e5655-80d2-4f91-acf3-3c749b8b4104.png)

sub dir, error:
![image](https://user-images.githubusercontent.com/26052216/190870422-c966c4b9-3db7-4baa-b43a-c4859b54cf0a.png)

**Comment by gatlace** [comment]
It seems like there might be something in my directory creating the issue, an empty root dir works

**Comment by vlad20012** [comment]
This usually happens of you have another crate in the root.

Anyway, you should just add that crate to the project unsing "+" in the Cargo tool window (by default, you can find it in the right panel)
![image](https://user-images.githubusercontent.com/3221931/190870753-26664bab-c6d6-432c-b91e-968a326295b7.png)

**Comment by vlad20012** [comment]
You can also use `Right Click -> New -> Cargo Crate` instead of `cargo new`, and in this case the crate will be added automatically

**Comment by gatlace** [comment]
This might make sense, I deleted my root directory and made a new one for it and everything worked fine. the root dir I had was a git repo with a branch that had a crate in the root, so I don't know if that would count or something. Weird.

I'm all set for now though, thank you for your help!
