### ISSUE TITLE
Add action to run Clippy

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#938]
We already can run rustfmt: https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/actions/RsFmtFileAction.kt

Running clippy should be done in a similar fashion, but it should automatically use the nightly toolchain if Rustup is available.

**Comment by mkaput** [comment]
Maybe it should be implemented as external annotator (switchable in options, off by default)?

**Comment by matklad** [comment]
@mkaput I am not sure about that, but we can try!

Annotators are usually meant to be per file, while clippy will build the whole project as I understand. This is the reason why I haven't added `rustc` errors as an external annotator: I'd rather wait for RLS to have something a little bit more incremental: "here is the text that user typed in these files, can you give me errors for that file now".

**Comment by mkaput** [comment]
Ah ok, haven't used clippy and didn't know it works such way

**Comment by matklad** [comment]
>Ah ok, I haven't used clippy and didn't know it works such way

Me neither :( I hope this feature will make me use it though at last!

**Comment by johnthagen** [comment]
Bonus points if we can figure out how to get `clippy`'s colors to output correctly as well: https://github.com/intellij-rust/intellij-rust/issues/937#issuecomment-272913155
