### ISSUE TITLE
Cargo build run configurations do not work in Before launch context

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#9385]
This issue is related to the ticket from Zendesk Support.

## Environment

* **IntelliJ Rust plugin version:** 0.4.178.4873-222
* **Rust toolchain version:** 1.63.0 (4b91a6ea7 2022-08-08) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2022.2.3 (CL-222.4167.35)
* **Operating system:** Windows 10 10.0

## Problem description
Cargo run configurations running `build` command do not work in the **Before launch** context of other run configurations.

## Steps to reproduce
1. Create a Rust project
2. Add two Cargo run configurations: with `cargo run` and `cargo build` commands
3. Add any **Custom Build Application** run configuration and specify one of those Cargo configurations in **Before launch**
3.1. When cargo run is set in **Before launch**, the configuration works fine and the Rust code is executed
3.2. When cargo build is set in **Before launch**, the configuration does not run the Rust code

It looks like our Cargo build configurations do not work properly in the Before launch context.

**Comment by mchernyavsky** [comment]
Relates to https://youtrack.jetbrains.com/issue/CPP-31537/Run-configuration-before-launch-has-UB-behaviour-with-Cargo-Commands.
