### ISSUE TITLE
Quick fix suggests removed feature `in_band_lifetimes`

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#9386]
## Environment

* **IntelliJ Rust plugin version:** 0.4.180.4890-222-nightly
* **Rust toolchain version:** 1.66.0-nightly (432abd86f 2022-09-20) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.2.3 (CL-222.4167.35)
* **Operating system:** macOS 12.5.1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
<img width="793" alt="image" src="https://user-images.githubusercontent.com/49211026/191462614-5fa10329-dff3-4b11-9ef0-fb00dff94501.png">

## Steps to reproduce
```rust
trait Foo {
    type Bar<'a>;
    type E;

    fn fooo(x: Self::Bar<'a>){

    }
}
```

**Comment by mchernyavsky** [comment]
Fixed by https://github.com/intellij-rust/intellij-rust/pull/9930.
