### ISSUE TITLE
Fix file-level duplicated items annotator

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#939]
Guys from the core IDEA platform say that it is best to annotate the element which is passed to annotator, and not its parents/children. So the plan is to store side table with duplicates in `holder.currentAnnotationSession` and query it later.

**Comment by alygin** [comment]
> store side table with duplicates in holder.currentAnnotationSession and query it later

Actually, I tried this approach (by means of `AnnotationSession.putUserData() / getUserData()`), but  it didn't work because the session object was new on every call (and user data were lost). But maybe I did something wrong.

Hopefully it'll work if done correctly.
