### ISSUE TITLE
Can't run/install debugger on NixOS with IDEA

### ISSUE THREAD

**Issue by Ifropc** [intellij-rust/intellij-rust#9393]
## Environment

* **IntelliJ Rust plugin version: 0.4.178.4873-221**
* **Rust toolchain version: N/A**
* **IDE name and version: IntelliJ IDEA 2022.1**
* **Operating system: Nix OS**

## Problem description

After downloading debugger and trying to run it, error is shown `Cannot run program "/home/ifro/.cache/JetBrains/IntelliJIdea2022.1/intellij-rust/lldb/bin/LLDBFrontend": error=2, No such file or directory`. Trying to run it manually: 
```
> ./LLDBFrontend
zsh: no such file or directory: ./LLDBFrontend
```
Running ldd shows that libstdc++ is not found.
```
> ldd LLDBFrontend | grep "not found"
	libstdc++.so.6 => not found

ldd lldb | grep "not found"
	libstdc++.so.6 => not found
```
lldb installed from nixpkgs works just fine. I'm still quite new to the NixOS and it looks like an environment issue, though I'm not sure if it's a NixOS issue. Any ideas on how to make it work is appreciated. 
Also, setting lldb path to system-installed lldb doesn't do anything.
Finally, debugger works just fine with CLion (i assume it uses system bundled lldb)

**Comment by Undin** [comment]
> After downloading debugger and trying to run it, error is shown Cannot run program "/home/ifro/.cache/JetBrains/IntelliJIdea2022.1/intellij-rust/lldb/bin/LLDBFrontend": error=2, No such file or directory. 

Interesting. I'm not familiar with NixOS but probably, it's because of specific package management in NixOS and the plugin fails to write something to `/home/ifro/.cache/JetBrains/IntelliJIdea2022.1/intellij-rust/lldb/bin/`

> Also, setting lldb path to system-installed lldb doesn't do anything.

It's expected because the plugin requires special lldb build. It can't work with system lldb

> Finally, debugger works just fine with CLion (i assume it uses system bundled lldb)

No, CLion doesn't use system lldb. It uses its own build bundled into the application

**Comment by Ifropc** [comment]
```
Interesting. I'm not familiar with NixOS but probably, it's because of specific package management in NixOS and the plugin fails to write something to /home/ifro/.cache/JetBrains/IntelliJIdea2022.1/intellij-rust/lldb/bin/
```
I also thought so, but it's owned by my user and my user's group, so there should be no issues for IDEA to write there. Also, isn't IDEA writes a lot into the `.cache`? I think if `inability` to write to the .cache was the case, everything inside IDEA would've broke...

```
It's expected because the plugin requires special lldb build
```
Okay, I thought so.

```
It uses its own build bundled into the application
```
Do you know if it's stored somewhere on disk? Is it the same distribution as IDEA should use? Maybe I can just copy it for IDEA to use

**Comment by Ifropc** [comment]
I use nix-env to run the project 

[Here's the sample hello world project](https://github.com/Ifropc/rust-playground) 

Run idea or clion with entering lorri shell.
(`$ lorri shell` -> `$ idea-ultimate`)

**Comment by Ifropc** [comment]
@Undin is there any updates on this issue? Any ideas how to investigate it locally?

**Comment by ortem** [comment]
@Ifropc Maybe https://github.com/Mic92/nix-ld could be a solution

**Comment by ortem** [comment]
Now, based on the experience from #8197, I suppose that `nix-ld` should solve this problem too.

Cc @Ifropc @anpin

**Comment by Ifropc** [comment]
Thanks for looking into that @ortem , I will try it out when I have time.

**Comment by Ifropc** [comment]
@ortem thanks for pointing into the right direction.
I haven't tried running debugger itself, but I just had the exact similar problem with kotlin-multiplatform setup and node binary downloaded via gradle. Using nix-ld solved it. I'm pretty confident that running IDEA from the same nix shell would resolve this issue too.

cc @anpin 
For reference I'm running `nix-shell shell.nix`
And shell.nix simply
```nix
with import <nixpkgs> {};
mkShell {
  NIX_LD_LIBRARY_PATH = lib.makeLibraryPath [
    gcc
  ];
  NIX_LD = lib.fileContents "${stdenv.cc}/nix-support/dynamic-linker";
}
```
