### ISSUE TITLE
attach file to module doesn't work

### ISSUE THREAD

**Issue by Sherlock-Holo** [intellij-rust/intellij-rust#9405]
## Environment

* **IntelliJ Rust plugin version:** 0.4.180.4890-222-nightly
* **Rust toolchain version:** rustc 1.66.0-nightly (e7119a030 2022-09-22)
* **IDE name and version:** CLion 2022.2.3
* **Operating system:** Archlinux

## Problem description
when creating a new dir and mod.rs file, the mod.rs file will display 
![image](https://user-images.githubusercontent.com/10096425/192078221-d0132253-1a95-45f4-86ab-31f1aad595bd.png)

press `attach file to module` will add `mod xxx` to the lib.rs, however, the notification still exists after attaching file to module, need to refresh the project
![image](https://user-images.githubusercontent.com/10096425/192078296-3a5e2aa9-e324-4d5a-b791-2fca68d5cd4c.png)
to let intellij-rust know the file is available

## Steps to reproduce

1. create a dir and mod.rs file in the dir
2. open the mod.rs file
3. press `attach file to module` and add a new mod in the lib.rs file
4. switch back to the new mod.rs file, the notification doesn't disappear

**Comment by afetisov** [comment]
It does work, the module becomes part of the project. You don't get an error on the mod declaration, and the imports within the module work properly.

Which suggests the issue is that the error message isn't removed at the proper moment and remains dangling. I can't understand the reason though.

**Comment by Sherlock-Holo** [comment]
this problem exists in recent nightly version, but I remember in august, there is no this problem

**Comment by Undin** [comment]
@dima74 could you take a look, please?

**Comment by the-eater** [comment]
I am having the same issue

<details>
<summary>version details</summary>


IntelliJ Rust plugin version: 0.4.179.4903-222
Rust toolchain version: rustc 1.64.0 (a55dd71d5 2022-09-19)
IDE name and version: CLion 2022.2.3
Operating system: VoidLinux
</details>

This isn't "simply" the error message not being removed, there is no code completion or any type of assistance available in the file, nor is it recognized, only after refreshing the Cargo projects it will recognize it.

I can't be sure, but I think it started happening after upgrading to CLion 2022.2.3 and the newest IntelliJ Rust plugin available
