### ISSUE TITLE
Webstorm Rust Code Completion/hint Not Working

### ISSUE THREAD

**Issue by AbdullahShahzadd** [intellij-rust/intellij-rust#9407]
## Environment

* **IntelliJ Rust plugin version:** 0.4.177.4844-222
* **Rust toolchain version:** rustc 1.63.0
* **IDE name and version:** Webstorm 2022.2.1
* **Operating system:** Linux Manjaro

## Problem description
Hi, I am new to rust and am having an issue with the fact that IntelliJ Rust plugin does not recommend code completion (i.e. If I try to use any std object then it will not recommend methods that the object has). Perhaps I didn't configure it properly?

![image](https://user-images.githubusercontent.com/77541712/192152523-d194ea47-76dd-49fc-82f8-97dbd16f9f0e.png)
 

## Steps to reproduce
Install the Rust plugin on Webstorm. Then try to write code and you will not get code completion hints for methods that are associated with objects.
![image](https://user-images.githubusercontent.com/77541712/192152592-25d19e0a-d1cf-4ae7-ae2f-3b596d1f28b5.png)
```rust
use std::collections::HashMap;
#[derive(Debug)]
enum SpreadsheetCell {
    Int(i32),
    Float(f64),
    Text(String)
}

fn main() {
    let mut scores = HashMap::new();

    // scores.insert(String::from("Blue"), 10);
    scores.i

}
```

**Comment by Undin** [comment]
Do you use Rust from `rustup` or from some other package manager? If not from `rustup`, does the plugin know where stdlib sources are located? You can check it in `Preferences | Languages & Frameworks | Rust` settings

**Comment by AbdullahShahzadd** [comment]
@Undin Yes I am using Rust from rustup, I followed the instructions in The Rust Book to install it.

**Comment by AbdullahShahzadd** [comment]
@Undin  I found out the location where stdlib are located: /home/abs/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust, does that help?

**Comment by vlad20012** [comment]
Could you please attach your IDE logs? You can collect them by `Help` | `Collect Logs and Diagnostic Data`.

Also, could you please make several screenshots?
1. A screenshots of the Cargo tool window? You can find it on the right-side panel:
![image](https://user-images.githubusercontent.com/3221931/192284236-36fe399f-d77c-465c-858e-52045e4a3625.png)
2. A screenshots of Rust toolchain settings, you can open them using `Ctrl` + `Alt` + `S` -> `Languages & Frameworks | Rust`
![image](https://user-images.githubusercontent.com/3221931/192285175-1620a603-790a-4563-8bf7-f14d022ec5e2.png)

**Comment by AbdullahShahzadd** [comment]
[webstorm-logs-20220926-19122613697993982449745444.zip](https://github.com/intellij-rust/intellij-rust/files/9650198/webstorm-logs-20220926-19122613697993982449745444.zip)
Hi @vlad20012 I don't seem to have the cargo tool window, do you think that might be the reason?
![image](https://user-images.githubusercontent.com/77541712/192400286-e68c09fa-6cf7-40b5-b0d8-82390c911aea.png)
![image](https://user-images.githubusercontent.com/77541712/192400378-07288f91-1f8d-4149-97cd-a4dd072430fe.png)

**Comment by AbdullahShahzadd** [comment]
I got some help on Reddit for this. Turns out I had to right click on the Cargo.toml file and select "Attach Cargo Project". This is kind of annoying but worth it for the features of code completion/hint
