### ISSUE TITLE
macro expansion: `'&str' doesn't implement 'Display'`

### ISSUE THREAD

**Issue by ForsakenHarmony** [intellij-rust/intellij-rust#9417]
## Environment

* **IntelliJ Rust plugin version:** 0.4.180.4901-222-nightly
* **Rust toolchain version:** 1.65.0-nightly (29e4a9ee0 2022-08-10) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2022.3 EAP (CL-223.4884.72)
* **Operating system:** Windows 10 10.0
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
When editing some parts of macros (i.e. the name of a function like macro), `intellij-rust` just stops properly resolving types instantly?
![image](https://user-images.githubusercontent.com/8845940/192353578-73ae72cb-2f7b-4b1d-b7ee-5d1ab2254801.png)

Auto complete just doesn't work at all inside the macro body at that point

Have to click "Refresh Cargo Projects" every 5 minutes, it's infuriating and makes the IDE almost unusable

## Steps to reproduce
https://gist.github.com/ForsakenHarmony/2038de3f0a83508a9b49434f248d8aef

Add a letter to the function name which has the macro on it

**Comment by dan-lee** [comment]
Can confirm, the same happens to me in any kind of project. I think this behavior started with the new 2022.3 EAP.

**Comment by vagetman** [comment]
Same problem here

**Comment by ForsakenHarmony** [comment]
@vlad20012 @Undin can someone please look into this?

**Comment by paul-hansen** [comment]
Just updated the rust plugin and am getting this now:
![image](https://user-images.githubusercontent.com/7019130/194936474-4637720f-6dff-44c5-bf13-8931f25bfc44.png)

Seems likely the same problem to me but let me know if I should open a separate issue.

**Comment by YthanZhang** [comment]
Same, started happening after the latest update
![1665507173833](https://user-images.githubusercontent.com/14943345/195152901-08282098-5cd6-4207-afaa-c1b7d7fd1404.png)

## Environment
+ Windows 10
+ CLion 2022.2.4 Build #CL-222.4345.21, built on October 10, 2022
+ Intellij Rust 0.4.180.4932-222
+ Rust toolchain 1.64 stable-x86_64-pc-windows-msvc

**Comment by vlad20012** [comment]
@ForsakenHarmony, I can't reproduce it with your setup on the latest (yesterday's) Rust plugin:
https://user-images.githubusercontent.com/3221931/195154595-cc7ae626-2fc3-4c98-a23e-7b79f5c96752.mp4

**Comment by YthanZhang** [comment]
> Same, started happening after the latest update ![1665507173833](https://user-images.githubusercontent.com/14943345/195152901-08282098-5cd6-4207-afaa-c1b7d7fd1404.png)
> 
> ## Environment
> * Windows 10
> * CLion 2022.2.4 Build #CL-222.4345.21, built on October 10, 2022
> * Intellij Rust 0.4.180.4932-222
> * Rust toolchain 1.64 stable-x86_64-pc-windows-msvc

Weird... I rebooted my PC, now the issue is gone, I can't reproduce it

**Comment by ForsakenHarmony** [comment]
Can't reproduce it either any more, thanks for fixing whatever it was intellij-rust team

**Comment by ForsakenHarmony** [comment]
And it's broken again, but with a different "message"

**Comment by ForsakenHarmony** [comment]
A couple of times now the functions with macros just stop being highlighted and if I try manually expanding I get: `Failed to expand the macro: internal error: expansion file not found, but cache has valid expansion`

opened a new issue for it
