### ISSUE TITLE
Check TOML Schema features in Cargo.toml

### ISSUE THREAD

**Issue by mili-l** [intellij-rust/intellij-rust#9421]
[SchemaStore API](https://www.schemastore.org/json/) is intergrated to the Platform.
<img width="558" alt="Screenshot 2022-09-28 at 14 02 57" src="https://user-images.githubusercontent.com/1213122/192773956-0ee03e9e-338f-4bfa-adec-25899817fc93.png">

Check the integration toml files with:
- [cargo.json](https://json.schemastore.org/cargo.json)
- [rust-toolchain.json](https://json.schemastore.org/rust-toolchain.json)
- [rustfmt.json](https://json.schemastore.org/rustfmt.json)

<img width="801" alt="Screenshot 2022-09-28 at 14 08 11" src="https://user-images.githubusercontent.com/1213122/192774871-53776392-9463-4789-a17d-ef57ac029631.png">

**Comment by mili-l** [comment]
Known issues
- edition values in `[package]` are duplicated
- `{}` appears on top of completion popup

Others:
- Some keys duplicated:
-- proc-macro
-- crate-type
-- build-dependencies
-- dev-dependencies

See the ag on [cargo.json](https://json.schemastore.org/cargo.json)

 ```json
      "x-taplo": {
        "hidden": true
      }
```
<img width="613" alt="Screenshot 2022-09-29 at 10 29 47" src="https://user-images.githubusercontent.com/1213122/193130124-fcbc7d20-931a-42cc-a01b-e7db1ac052b3.png">


- qdoc popup shown not about current key, but parent's key
- there is no navigation for the keys
- qdock popup displayed incorrectly 
<img width="1474" alt="Screenshot 2022-09-29 at 20 50 48" src="https://user-images.githubusercontent.com/1213122/193130389-dac83084-5c73-413d-af94-c9f1573bd539.png">

- `optional` key with incorrect values

```
[dependencies]
ravif = {version = "0.9.0", optional = true}
```

- `cargo-features` no values
 — experimental features ate not fully supported

- rustfmt not all values are supported. e.g. `reorder_imports`, but it is for .json
<img width="681" alt="Screenshot 2022-09-29 at 22 13 46" src="https://user-images.githubusercontent.com/1213122/193132716-5a6b133c-5654-4e18-8ab2-642b521f9117.png">

- there is no completion in `workspace`
- - for `dependencies`
- sometimes there is no completion in `workspace.package`
- -  author, edition, version, etc.
 
<img width="616" alt="Screenshot 2022-09-29 at 22 07 25" src="https://user-images.githubusercontent.com/1213122/193131923-7c5eef7e-f391-48f9-8da7-8b6fc3f39a39.png">

**Comment by Undin** [comment]
> qdock popup displayed incorrectly

Note, it works in the same way in json and yaml files as well. So I don't think it's a bug
