### ISSUE TITLE
Implement members quick-fix generates incorrect signature for serde::Serialize

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#9436]
## Environment

* **IntelliJ Rust plugin version:** 0.4.180.4890-222-nightly
* **Rust toolchain version:** 1.66.0-nightly (9c56d9d6f 2022-09-29) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2022.2 Ultimate Edition (IU-222.3345.118)
* **Operating system:** macOS 12.5.1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
When I try to generate a `serialize` method for custom `Serialize` implementation, the plugin generates

```rust
impl<'a> Serialize for FeatureWrapper<'a> {
    fn serialize<S>(&self, serializer: S) -> Result<serde::ser::Ok, serde::ser::Error> where S: Serializer {
        todo!()
    }
}
```

instead of 

```rust
impl<'a> Serialize for FeatureWrapper<'a> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error> where S: Serializer {
        todo!()
    }
}
```

https://user-images.githubusercontent.com/2539310/193420775-f3df656c-7c3e-46cb-8c2c-ed28b9aa55c3.mov

## Steps to reproduce

```toml
[dependencies]
serde = "1"
```

```rust
struct FeatureWrapper<'a> {
    feature: &'a Feature
}

impl<'a> Serialize for FeatureWrapper<'a> {
    
} 
```

**Comment by dima74** [comment]
Fixed by #10308
