### ISSUE TITLE
`serde::Serialize` and `serde::Deserialize` proc macros are not suggested in completion list

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#9439]
## Environment

* **IntelliJ Rust plugin version:** 0.4.180.4912-222-nightly
* **Rust toolchain version:** 1.64.0 (a55dd71d5 2022-09-19) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.2.1 (CL-222.3739.54)
* **Operating system:** macOS 12.5.1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
The plugin doesn't suggest `serde::Serialize` and `serde::Deserialize` in `derive` attribute regardless if they are imported or not. And it works in stable plugin (`0.4.179.4903-222` in particular). It seems it's a regression after #9308

| Before | Now |
| - | - | 
| <img width="408" alt="Screenshot 2022-10-01 at 22 25 50" src="https://user-images.githubusercontent.com/2539310/193427943-0e401b05-6b64-4a00-a248-66e41a5f5867.png"> | <img width="235" alt="Screenshot 2022-10-01 at 22 21 05" src="https://user-images.githubusercontent.com/2539310/193427947-3f27c189-baa9-47f6-8065-b575090eb5e0.png"> |

## Steps to reproduce

```toml
[dependencies]
serde = "1.0.145"
```

```rust
#[derive(/*caret*/)]
struct S;

fn main() {}
```

**Comment by dima74** [comment]
@Undin I would say it is correct behaviour because the macros are cfg-disabled in this case. They are suggested with 
```toml
serde = { version = "1.0", features = ["derive"] }
```

**Comment by Undin** [comment]
🤦 
@dima74 indeed. Thanks!
