### ISSUE TITLE
Replace `.unwrap()` with `?` intention

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#944]
Nothing fancy, no need to change type of anything, just a simple text substitution.

**Comment by mkaput** [comment]
>  just a simple text substitution

Is it? You need to ensure that the block returns type of unwrapped expression imho

**Comment by mkaput** [comment]
Or maybe I'm to strict 😉

**Comment by matklad** [comment]
>Is it? You need to ensure that the block returns type of unwrapped expression imho

We'll do that in a couple of years ;)
