### ISSUE TITLE
CargoTestEventsConverter keeps erronoeous closing parenthesis in executableName

### ISSUE THREAD

**Issue by daym** [intellij-rust/intellij-rust#9463]
CargoTestEventsConverter suitesStack contains `ex1-73a15e41ca4df214)`. Note the erroneous closing parenthesis.

   Finished test [unoptimized + debuginfo] target(s) in 0.02s
     Running unittests src/main.rs (target/debug/deps/ex1-73a15e41ca4df214) <-- the last char here

Happens in intellij-rust 0.4.179.4903-222

**Comment by daym** [comment]
Furthermore, is there a reason the path is not kept? As it is, it makes it much harder to find the actual test executable than if it said `target/debug/deps/ex1-73a15e41ca4df214` and not just `ex1-73a15e41ca4df214`.

**Comment by mchernyavsky** [comment]
> Furthermore, is there a reason the path is not kept?

You can find the executable path in the right window:

<img width="916" alt="Screen Shot 2022-10-31 at 23 12 36" src="https://user-images.githubusercontent.com/6079006/199120185-d382a12d-4ed1-4087-b30c-d1686760355f.png">

**Comment by daym** [comment]
Sure, but when I want to do some test automation stuff I would have to parse the console output again even though the rust already did so and would have the information--only it didn't store it anywhere directly.

I'll just do that then--but I thought I'd bring it up because it's not clear to me what shortening the (invisible) IDs helps in the first place.
