### ISSUE TITLE
Run rust project on win11 with a Linux environment

### ISSUE THREAD

**Issue by Vilquid** [intellij-rust/intellij-rust#9467]
## Environment

* **IntelliJ Rust plugin version:** 0.4.179.4903-222
* **Rust toolchain version:** 1.64.0 (a55dd71d5 2022-09-19) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2022.2.2 Ultimate Edition (IU-222.4167.29)
* **Operating system:** Windows 11 10.0
* **Macro expansion:** enabled

## Problem description

When I run my Rust projet (with my toolchain on WSL2) on my PC (win11), I get this output :

![image](https://user-images.githubusercontent.com/60876471/194081810-2331d8cf-7b3b-44f8-bd46-fdd8bdb11b0d.png)

I don't understand what I have to change to run my code.

## Steps to reproduce

My config :
![image](https://user-images.githubusercontent.com/60876471/194082350-5036dfc8-da54-4aea-a929-f30327fd4a7e.png)
![image](https://user-images.githubusercontent.com/60876471/194082619-0966fb88-392c-4253-92aa-8786ccc58e90.png)

**Comment by vlad20012** [comment]
Hi!
It seems broken using `Run Targets`, but it works if you set up a [WSL toolchain](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-project-settings.html#wsl-toolchain)

Duplicate #9061

**Comment by Vilquid** [comment]
I already setted up a WSL toolchain but I don't understand what I have to change.

**Comment by vlad20012** [comment]
You screenshots are not about toolchain, it is Run Targets. 
What you should change
1. Properly set up WSL toolchain (NOT Run Target)
2. Remove you `WSL - Ubuntu` Run Target
3. Use `Local Machine` Run Target in you Run Configurations

**Comment by Vilquid** [comment]
Thank you
