### ISSUE TITLE
Add action to run rustfmt on an entire project

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#948]
I think my normal workflow going forward will be to run rustfmt on a project before committing. It would be great to have an action to run it on an entire project rather than just the current file. In the likely case I've made changes in multiple files I don't have to hunt through them all to make sure the formatting is all proper.

I tried highlighting all of the files in the Project view and running the action through <kbd>Ctrl+Shift+A</kbd>, but that didn't seem to work as a work around.

**Comment by kryptan** [comment]
I run it as any other cargo command like build, run etc.

**Comment by matklad** [comment]
I am inclined to close this: there is **run cargo command** action, which you can use to run `cargo fmt` conveniently. 

@johnthagen would that be enough?

**Comment by johnthagen** [comment]
@matklad Yeah, fine to close this. I need to just get in the habit of creating that action for each Rust project I have.
