### ISSUE TITLE
Formatter should remove redundant braces around single item imports

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#949]
`rustfmt` formats:

```rust
use std::vec::{Vec};
```

to:
```rust
use std::vec::Vec;
```

**Comment by mkaput** [comment]
I think this is task for Organize imports thing

**Comment by johnthagen** [comment]
Do you mean [Optimize Imports](https://www.jetbrains.com/help/idea/2016.3/optimizing-imports.html)? That would make sense in the IntelliJ ecosystem.

**Comment by mkaput** [comment]
Yes, but I don't know what are API endpoints for this (upsource is broken now)

**Comment by matklad** [comment]
>Yes, but I don't know what are API endpoints for this (upsource is broken now)

https://github.com/JetBrains/intellij-community/blob/master/platform/lang-api/src/com/intellij/lang/ImportOptimizer.java

**Comment by matklad** [comment]
We are far from "Optimize Imports" yet, so it makes sense to handle this in formatter. It should be handled by `PreFormatProcessor`, see, for example, `org.rust.ide.formatter.RsMatchArmCommaFormatProcessor`.

**Comment by matklad** [comment]
This is already implemented
