### ISSUE TITLE
Incorrect Unresolved reference: `contains` when using `IndexSet` and `itertools`

### ISSUE THREAD

**Issue by jbx1** [intellij-rust/intellij-rust#9535]
## Environment

* **IntelliJ Rust plugin version: 0.4.180.4932-222**
* **Rust toolchain version: 1.64.0**
* **IDE name and version: CLion 2022.2.3 Build #CL-222.4167.35, built on September 15, 2022**
* **Operating system:**

## Problem description
`IndexSet` provides a public function called `contains()` but the IDE marks it as an invalid reference. The code compiles and works fine.

This has been narrowed down to some kind of conflict with the `itertools` crate. When it is specified in the `Cargo.toml` file as a dependency the error appears. When it is removed, the error goes away. Somehow the Rust plugin is getting confused, even if `itertools` is not even used in that specific file. 

![image](https://user-images.githubusercontent.com/6760528/195870351-825bcede-807b-4dc6-8b33-34bab2f546a0.png)

## Steps to reproduce

1. Create a new Rust project named `test-indexset`
2. Replace `Cargo.toml` with the following:

```toml
[package]
name = "test-indexset"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = "1.9.1"
#comment out the next line and the error goes away
itertools = "0.10.3"
```

3. Replace `main.rs` with the following code:

```rust
use indexmap::IndexSet;

fn is_inside(set: &IndexSet<String>, needle: &str) -> bool {
    return set.contains(needle)
}

fn main() {
    let mut set = IndexSet::new();
    set.insert("hello".to_string());
    set.insert("goodbye".to_string());

    let inside = is_inside(&set, "hello");
    println!("{}", inside);
}
```

Even though `itertools` is not used in the file, it will show the error in the IDE. 
If you compile and run the program it will work successfully.

If you comment out the `itertools` dependency in `Cargo.toml` the error will go away.

**Comment by neonaot** [comment]
Hi, thank you for the detailed report!

Try to enable `org.rust.cargo.evaluate.build.scripts` in [Experimental features](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features) , the false error should disappear.
You can find some information about this feature in https://github.com/intellij-rust/intellij-rust/pull/9532 and https://github.com/intellij-rust/intellij-rust/issues/9402

Also, In case of other problems, you can use `Help | Create New issue` action. It will automatically fill information about versions and used features
