### ISSUE TITLE
broken code navigation

### ISSUE THREAD

**Issue by panov-andy** [intellij-rust/intellij-rust#9538]
## Environment

* **IntelliJ Rust plugin version:** 0.4.180.4932-222
* **Rust toolchain version:** 1.64.0 (a55dd71d5 2022-09-19) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2022.2.3 Ultimate Edition (IU-222.4345.14)
* **Operating system:** Linux 5.15.0-50-generic
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
Goto code declaration doesn't work (Ctrl+B) and does work in Fleet.

## Steps to reproduce
 - clone https://github.com/panov-andy/kubeapi-prometheus
 - Crtl+B expected to work on on `tcp()` -> [for entry in tcp().unwrap().iter() {](https://github.com/panov-andy/kubeapi-prometheus/blob/b5a24a697b9b7164e342286deb797dc11eba6a25/src/main.rs#L17)

**Comment by Undin** [comment]
Hm, it's weird

`tcp` here is just a function and name resolution should work without any experimental features. And it works for me, actually

Could you send [logs](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files)? You can attach them directly here or do it via https://uploads.jetbrains.com/ privately

You can try to [invalidate caches](https://www.jetbrains.com/help/idea/invalidate-caches.html) as a workaround

**Comment by panov-andy** [comment]
Hm... it's working today. Sorry for the noise.
