### ISSUE TITLE
File is not included in module tree

### ISSUE THREAD

**Issue by cjwcommuny** [intellij-rust/intellij-rust#9547]
## Environment

* **IntelliJ Rust plugin version:** 0.4.180.4932-222
* **Rust toolchain version:** rustc 1.64.0 (a55dd71d5 2022-09-19)
* **IDE name and version:** Intellij IDEA 2022.2.3 (Ultimate Edition)
* **Operating system:** macOS Monterey 12.6 (M1 chip)

## Problem description

<img width="684" alt="CleanShot-2022-10-16-16 43 37" src="https://user-images.githubusercontent.com/23581749/196026610-7bf8a112-2863-4d5f-a56e-03cc83ac7927.png">

The banner "File is not included in module tree, analysis is not available" doesn't disappear after I click "Attach file to lib.rs". I have to wait for about 10 seconds or more, and then it may disappear.

## Steps to reproduce

1. Create a new Rust project by `cargo new helloworld`.
2. Open the project through Intellij IDEA.
3. Right click `New -> Rust File` in `src` in the sidebar
4. Click "Attach file to lib.rs".
5. The banner doesn't disappear.

**Comment by dima74** [comment]
This was fixed by #9537 and will be available in next release (24 October). Also you can use [nightly plugin](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly)
