### ISSUE TITLE
Better support for parsing implementations by macros

### ISSUE THREAD

**Issue by torkleyy** [intellij-rust/intellij-rust#955]
In Rust, it's common practice to create an `impl_foo!` macro to create a trait implementation for `Bar`:

```rust
struct Bar;

impl_foo!(Bar);
```

Unfortunately, the trait implementation is not recognized by this plugin. I think these macros are just omitted at the moment. Would it be okay to expand & parse them?

**Comment by matklad** [comment]
Unfortunately a general macro parsing/expansion problem is a tough one. Currently we only hardcode some macros defined in the standard library.

**Comment by ForsakenHarmony** [comment]
could you give a hint as in where I'd have to start if I were to implement this?

**Comment by torkleyy** [comment]
@ForsakenHarmony

Probably you could pretend that you were writing what the expanded versions are at that location (sorry for the bad description). I think I can better explain with an example:

Let's say there is a macro foo:

```rust
macro_rules! foo {
    ($t:ident, $x:ident) => ( println!("{}", t::x) );
}
```

Now, when writing `foo!(<caret>` then the same completions should be displayed as if it would be `println!("{}"`, <caret>`.

If there are mutliple matching arms in the macro, display completions of all of them.

A problem might be that missing closing bracket could break completion(?).

Also, some complex expresion might be a pretty difficult.

**Comment by ForsakenHarmony** [comment]
I know how you'd do it in theory, but I know it's a lot of work, and I don't really understand all of the code in the repo

**Comment by torkleyy** [comment]
I'm sorry but I can't help you with this

**Comment by matklad** [comment]
Yep, macros are generally hard. I've described our current attempts at them here: https://www.reddit.com/r/rust/comments/5rhqj0/ide_compiler_has_very_different_requirements_and/dd8affs/
