### ISSUE TITLE
[feature] Autocomplete for matching variable values

### ISSUE THREAD

**Issue by mitchhentges** [intellij-rust/intellij-rust#957]
For example:

```
const TAG_FUNCTION: u32 = 0x01000000;
const TAG_LINE_COUNT: u32 = 0x01450000;
<snip>
let tag = read_u32(&buffer[offsetA, offsetA + length]);
let result = match tag {
    TAG_FUNCTION => true,
    TAG_<cursor> // Right here, show "TAG_LINE_COUNT" as a suggestion
```

Minimal goal: suggestion variables as `match` arms. Perhaps only `const` values, because they'd be more likely to be used for `match` equality checks?

Magical ideal-scenario parts of this feature that totally aren't needed for a simple implementation:
* Only suggest variables of the same type as the `match` argument
* Don't show variables already used in earlier `match` arms

**Comment by matklad** [comment]
Yes, this is a known issue! There's something more basic missing here: we thing that `TAG` is a name which would be bound to the `tag`, we don't see that in fact it is a reference to the constant. I'm closing this in favor of https://github.com/intellij-rust/intellij-rust/issues/958 :)
