### ISSUE TITLE
`org.rust.macros.proc` breaks proc macro code assist

### ISSUE THREAD

**Issue by MatrixDev** [intellij-rust/intellij-rust#9593]
## Environment

* **IntelliJ Rust plugin version:** 0.4.182.4950-223-nightly
* **Rust toolchain version:** rustc 1.64.0 (a55dd71d5 2022-09-19)
* **IDE name and version:** CLion 2022.3 EAP Build #CL-223.6160.115
* **Operating system:** MacOS Monterey 12.1 (arm)

## Problem description

`org.rust.macros.proc` feature seem to break proc marcros for me.

Proc macros seams to **work** when this feature is **disabled**:
<img width="831" alt="image" src="https://user-images.githubusercontent.com/1215187/197182217-ec4e02d1-f05f-42d0-a0b6-7ac38b14cf8c.png">

But **doesn't work** when it is **enabled**:
<img width="565" alt="image" src="https://user-images.githubusercontent.com/1215187/197182414-4d97b4e6-d77c-4e0b-9039-5cf37003ea38.png">

As you can see code assist doesn't see `X509StoreBuilder::new` nor `X509::from_der` when feature is enabled. Those are absent in suggestions as well. After some digging I found that only methods that are marked with `openssl_macros::corresponds`  `proc_macro_attribute` are bugged.

This happens in any compinations of CLion EAP/Regular or IntelliJ Rust plugin 180/nightly

**Comment by MatrixDev** [comment]
<img width="963" alt="image" src="https://user-images.githubusercontent.com/1215187/197193796-cc0fc123-3b34-4311-8edb-d361e1622ace.png">

@vlad20012 I don't see any errors there...

**Comment by vlad20012** [comment]
Oh, well, yes, we currently don't support attribute macros applied to `impl` members
