### ISSUE TITLE
Environment variables are not expanded in run configuration

### ISSUE THREAD

**Issue by wdanilo** [intellij-rust/intellij-rust#9621]
Environment variables are not expanded in run configuration:

![image](https://user-images.githubusercontent.com/1623053/198093573-a85a3f86-214d-44d5-84ab-77b82b8105cf.png)

However, the `${TARGET_NATIVE}` is not expanded and it is passed to the cargo command just as a string:

`cargo clippy --color=always --message-format=json-diagnostic-rendered-ansi --all-targets -Zmultitarget --target ${TARGET_NATIVE} --target`

**Comment by vlad20012** [comment]
Hi!
It looks like you misunderstand the concept of environment variables. These variables are passed to the process being run and so it becomes possible to read these variables for example using [`std::env::var("")`](https://doc.rust-lang.org/std/env/fn.var.html).

These variables are **not** substituted to the command line using `${}` syntax.

**Comment by wdanilo** [comment]
@vlad20012 but I want to pass the env variable to the command, how can I do it?
