### ISSUE TITLE
Struct initialization with Self keyword does not invoke "Create field" option 

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#9651]
## Environment

* **IntelliJ Rust plugin version:** 0.4.183.4980-223-nightly
* **Rust toolchain version:** 1.64.0 (a55dd71d5 2022-09-19) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.3 EAP (CL-223.7255.15)
* **Operating system:** macOS 12.5.1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.macros.proc.function-like, org.rust.macros.proc

Originally posted in https://youtrack.jetbrains.com/issue/CPP-30924/Rust-Struct-initialization-with-Self-keyword-does-not-invoke-Create-field-option 

## Problem description
When you attempt to initialize a struct with the Self keyword, CLion does not offer the Create field option as it does when you explicitly use the struct's own name.

## Steps to reproduce
```rust
struct A { }
impl A {
    fn new() -> A {
        let x = 0;
        A {
            x // <- invokes "Create field" option
        }
    }
    
    fn new2() -> A {
        let x = 0;
        Self {
            x // <- does not invoke "Create field" option
        }
    }
}

```

**Comment by mati865** [comment]
I've tried to look into it but got stuck at this point: https://github.com/intellij-rust/intellij-rust/blob/5ac6e9a3e758f66bbbc7fcb061cb0337a7f24eed/src/main/kotlin/org/rust/ide/annotator/fixes/CreateStructFieldFromConstructorFix.kt#L73
With "regular" structs `resolve()` returns `RsStructItemImpl(STRUCT_ITEM)` but using `Self` syntax it gives `RsImplItemImpl(IMPL_ITEM)`. I'm unable to walk `intellij-rust` code well enough to figure out how this happens but maybe it will be helpful for somebody knowing this code better.
