### ISSUE TITLE
Mark experimental nightly methods in the code completion

### ISSUE THREAD

**Issue by rsalmei** [intellij-rust/intellij-rust#9659]
Please, is it possible to mark the experimental nightly methods in the code completion?
It is very disappointing to find that exact method I was looking for, just to later find it cannot be used in Stable Rust......
Perhaps they could use a different color, have less priority and go to the end of the list, or even be entirely hidden via a configuration?

Here is an example that has just let me down, I have to look for the feature tag within the documentation, and can only use it if _not_ found (but of course I often forget to or actually do not see it on a quick glance):
![image](https://user-images.githubusercontent.com/6652853/199297490-7a01ba05-2cad-4bfb-ac70-9e978052eb9f.png)

Thanks.

EDIT: I don't even use a nightly toolchain! I'm on stable...

**Comment by blueglyph** [comment]
I would appreciate this too, or an option to remove them altogether.

Rust has so many unstable or experimental code that it's very misleading; this would save a lot of time.

**Comment by rsalmei** [comment]
Thanks!
