### ISSUE TITLE
Debugger hangs with "Collecting data..." on huge string value

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#9672]
## Environment

* **IntelliJ Rust plugin version:** 0.4.183.4984-223-nightly
* **Rust toolchain version:** 1.64.0 (a55dd71d5 2022-09-19) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.3 EAP (CL-223.7401.10)
* **Operating system:** macOS 11.1

## Problem description
When showing huge string values (e.g. contents of a 100MB file), the debugger hangs with "Collecting data..." and the memory usage goes up.

## Steps to reproduce

```Rust
fn main() {
    let mut f = File::open("large_file.txt").unwrap();
    let mut contents: String = String::new();
    f.read_to_string(&mut contents).unwrap();
    println!(); // break
}
```

## Workaround
In `Preferences | Build, Execution, Deployment | Debugger | Data Views | Rust` settings, set `LLDB renderers` or `GDB renderers` to `No renderers`.

**Comment by MrGaribaldi** [comment]
### Steps to reproduce
[https://github.com/MrGaribaldi/rust_string_debugging](This repo) contains three versions of returning a large string created by a for-loop. 

### Problem description
I get the same/similar problem, across Windows 10 pro, Windows 11 pro and Manjaro linux. 
The repo linked above has 3 different ways of returning a large string, with different debug behaviour for each of them. 
Breaking and stepping through each of them you'll find:
- First function returning a straight String will cause delay at the second println!, in the calling function
- Second function returning a custom struct will happily let you step through everything without an issue. 
- Third function, returning an Ok result will hang at every step. 

### Environment IntelliJ
- IntelliJ Rust plugin version: 0.4.171.4656-213
- Rust toolchain version:  1.62.0-nightly (8bf93e9b6 2022-04-09)
- IDE name and version: IntelliJ IDEA 2021.3.3 (Ultimate Edition)
- lldb version: 9.0.0 (JetBrains IDE Bundle: x64; build 146)
- Operating system: Windows 10 pro, 21H1, 19043.2251

### Environment CLion
- CLion Rust plugin version: 0.4.181.4956-222
- CLion Rust plugin version: 0.4.182.4996-222
- Rust toolchain version:  1.62.0-nightly (8bf93e9b6 2022-04-09)
- lldb version: 9.0.0 (JetBrains IDE Bundle: x64; build 157)
- IDE name and version: CLion 2022.2.4 
- Operating system: Windows 10 pro, 21H1, 19043.2251

### Environment Rider
- Rider Rust plugin version: 0.4.182.4996-222
- Rust toolchain version:  1.62.0-nightly (8bf93e9b6 2022-04-09)
- lldb version: 9.0.0 (JetBrains IDE bundle; x64; build 152)
- IDE name and version: Rider  2022.2, #RD-222.3345.139, built on August 1, 2022
- Operating system: Windows 10 pro, 21H1, 19043.2251


Will add data for Windows 11 and Manjaro later, if that is interesting.
