### ISSUE TITLE
Lagging on large files

### ISSUE THREAD

**Issue by naosense** [intellij-rust/intellij-rust#9673]
When the file is relatively large, editing it will cause a big lag. BTW, I use ideavim.

**Comment by dima74** [comment]
Please disable `Insert imports on paste` option in `Settings | Editor | General | Auto Import`
Related: #9664

**Comment by naosense** [comment]
OK, I'll try this

**Comment by naosense** [comment]
Yeah, it worked, thanks! Is this a bug? if so, I will left this issue open.

**Comment by dima74** [comment]
This feature will be disabled by default in the next release. Feel free to subscribe to #9664 for updates
