### ISSUE TITLE
Rust debugging does not work when called from C++

### ISSUE THREAD

**Issue by unconverged** [intellij-rust/intellij-rust#9679]
## Environment

* **IntelliJ Rust plugin version:** 0.4.181.4965-222
* **Rust toolchain version:** rustc 1.65.0 (897e37553 2022-11-02)
* **IDE name and version:** CLion #CL-222.4345.21, built on October 10, 2022
* **Operating system:** macOS 13.0 (22A380) (Ventura)

## Problem description
When I have a C++ app that call a Rust shared library, I could not debug Rust code. C++ debugger works fine, but it reaches a call to a Rust function, Step Into does not work. If I set a breakpoint inside Rust code, it does not get hit. However, the call succeeds and I can see the return value.

I tried reinstallng the plugin and even CLion, but no luck, unfortunately.

It used to be working some time ago, so apparently it was broken during the last couple of releases.

Rust-only debugger works fine.

## Steps to reproduce
You can try this project that has everything you need to reproduce. Simply open CLion, open Rust project, open CMakeLists.txt and follow IDE's suggestions. Set a breakpoint at C++ `main()` and and inside the Rust's `add()` function, then run the app with debugger and you'll see that the breakpoint inside Rust code never gets hit.

[rustcpp.zip](https://github.com/intellij-rust/intellij-rust/files/9941601/rustcpp.zip)

**Comment by ortem** [comment]
@IvaYan Thank you for the detailed report and the example project! I tried to reproduce the issue but the breakpoint inside the Rust code seems to work fine. I guess the problem might be related to the lack of debug info in the Rust build artifacts.

1. Delete `target` directory from the project
2. Run `Cargo Build` configuration again, which should report `Finished dev [unoptimized + debuginfo] target(s)`
3.  Debug

If the breakpoint in the Rust code still does not work after these steps, try executing `(lldb) image list` command in the [Debugger console](https://www.jetbrains.com/help/clion/debugger-console.html) and check if there is `target/debug/deps/librustcpp.dylib` file in the output.
