### ISSUE TITLE
derive(Constructor) has no completion

### ISSUE THREAD

**Issue by zzwxh** [intellij-rust/intellij-rust#9682]
## Environment

* **IntelliJ Rust plugin version:** 0.4.181.4965.222
* **Rust toolchain version:**1.25.1
* **IDE name and version:**clion
* **Operating system:**windows11

## Problem description
derive(Constructor) has no completion

## Steps to reproduce
```rust
use derive_more::Constructor;
use serde::{Deserialize, Serialize};

#[derive(Serialize,Deserialize,Debug,Constructor)]
pub struct C00Handshake {
    protocol_version:i32,
    server_address:String,
    server_port:i16,
    next_state:i32,
}
```

```rust
use xclient::network::packet::c00_handshake::C00Handshake;

fn main() {
    println!("Hello, world!");
    let packet = C00Handshake::new //<- No Completion
}
```

**Comment by dima74** [comment]
@zzwxh please try enable `org.rust.macros.proc` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features)
