### ISSUE TITLE
No auto completion for default implementations

### ISSUE THREAD

**Issue by torkleyy** [intellij-rust/intellij-rust#970]
If a trait `Foo` has a default implementation for `bar` and you don't override it in your own type `Bar`, there is no completion for `bar`:

```rust
trait Foo {
    fn foo();
    fn bar() {
        println!("bar");
    }
}

struct Bar;

impl Foo for Bar {
    fn foo() {
        println!("foo");
    }
}

fn main() {
    Bar::
    // ^^ Only `foo` suggested here
}
```

**Comment by bravomikekilo** [comment]
It is a serious problem. default method missing make important library such as **glium** unable to use
