### ISSUE TITLE
Incorrect highlighting of dead code in macros

### ISSUE THREAD

**Issue by afetisov** [intellij-rust/intellij-rust#9712]
## Environment

* **IntelliJ Rust plugin version:** 0.4.183.4980-222-nightly
* **Rust toolchain version:** 1.67.0-nightly (73c9eaf21 2022-11-07) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.2.4 (CL-222.4345.21)
* **Operating system:** Linux 5.4.0-131-generic
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.macros.proc.function-like, org.rust.macros.proc

## Problem description

Tokens inside of macros are marked as conditionally disabled, even if they are used inside of AST elements which are not conditionally disabled.

The result of that is that code, which uses macros to generate code for every `cfg` option, will misleadingly appear all conditionally disabled, and won't get any syntax highlighting.

```rust
macro_rules! mac {
    ($name: ident) => {
        #[cfg(unix)]
        struct $name;
        #[cfg(not(unix))]
        struct $name;
    };
}

mac!(Foo);
//   ^^^ conditionally disabled code
```

**Comment by vlad20012** [comment]
The issue is known since a whilte, but coincidentally, I'm just now thinking about how to fix it
