### ISSUE TITLE
"Cannot find declaration to go to" for generated grpcio protos

### ISSUE THREAD

**Issue by andreid-db** [intellij-rust/intellij-rust#9715]
## Environment

* **IntelliJ Rust plugin version:** 0.4.172.4657-213-nightly
* **Rust toolchain version:** 1.64.0-nightly (0f4bcadb4 2022-07-30) aarch64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.3.3 Ultimate Edition (IU-213.7172.25)
* **Operating system:** macOS 12.5.1
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description

Unable to locate references to Grpc protos.

## Steps to reproduce

* git clone https://github.com/tikv/tikv.git
* Then open Intellij, File -> New -> Project From Existing Sources -> select tikv directory, only select tikv sources.
* Once the project is created and indexed, open src/storage/mod.rs
* Try to navigate to any of the references for ChecksumAlgorithm or RawGetRequest (these are imported from  kvproto::kvrpcpb). This fails for me. Ideally it would go to something like target/debug/build/kvproto-2b51a6f149815ae3/out/protos/

**Comment by dima74** [comment]
Hi @andreid-db! Looks like you are using quite old version of the plugin (v172) and IDE (2021.3). Please update the plugin to the latest version [`v182`](https://plugins.jetbrains.com/plugin/8182-rust/versions/stable/248217)

**Comment by andreid-db** [comment]
Yes, thanks, that has fixed my issue. I was assuming that using nighlty would get me the latest plugin, but I guess the IDE version was restricting that.
