### ISSUE TITLE
Better support for type parameters

### ISSUE THREAD

**Issue by torkleyy** [intellij-rust/intellij-rust#972]
At the moment, the plugin doesn't seem to understand type parameters.

```rust
fn foo<T>(val: T) -> T {
    val
}

fn main() {
    let a: Option<i32> = Some(5);
    foo(a).
    //    ^ No completion here
}
```

More important, this also does not work for trait implementation:

```rust
pub trait Foo {
    type A;

    fn a(&self) -> A;
}

struct Bar;

impl Foo for Bar {
    type A = Option<i32>;

    fn a(&self) -> A {
        Some(3)
    }
}

fn main() {
    let my_bar = Bar;
    my_bar.a().
    //        ^ No completion here
}
```

This one only works if you change the return type in the trait implementation to `Option<i32>`.

I think this is because of the way the plugin searches for methods. I guess it looks at the implementation of the methods itself, but what it should do instead, is to look at the implemented traits and their methods in order to get a list of the applicable methods. This may be also the reason for issue #970.

**Comment by matklad** [comment]
Works now, thanks to @vlad20012 ! (note that `A` should be changed to `Self::A`, otherwise even `rustc` complains).

![comp](https://user-images.githubusercontent.com/1711539/28785956-7bdda144-7620-11e7-98bf-e6ab94157934.png)
