### ISSUE TITLE
unable to push to github without having to re-inter the token each time

### ISSUE THREAD

**Issue by nathantippy** [intellij-rust/intellij-rust#9735]
## Environment

* **IntelliJ Rust plugin version:** 0.4.179.4903-222
* **Rust toolchain version:** 1.64.0 (a55dd71d5 2022-09-19) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.2.4 (CL-222.4345.21)
* **Operating system:** Linux 5.19.0-76051900-generic
* **Macro expansion:** enabled

## Problem description
each time I push to github it wants to authenticate again and need to keep entering the token.  Note window "Choose GitHub account" pops up upon push and that window shows the same user name 3 times so it is not clear which to select.

## Steps to reproduce
new project push to GitHub

**Comment by Undin** [comment]
Thanks for the report!
But it doesn't seem related to Rust plugin.
File an issue in IntelliJ platform [bug tracker](https://youtrack.jetbrains.com/newIssue?project=IDEA&c=Subsystem%20Version%20Control.%20GitHub) instead
