### ISSUE TITLE
[regression] "Fix all 'Unresolved reference' problems in file" quick fix option is no longer available

### ISSUE THREAD

**Issue by ivan-aksamentov** [intellij-rust/intellij-rust#9743]
## Environment

* **IntelliJ Rust plugin version:** 0.4.182.4996-222
* **Rust toolchain version:** 1.63.0
* **IDE name and version:** CLion 2022.2.4 (Build #CL-222.4345.21, built on October 10, 2022)
* **Operating system:** Ubuntu 20.04

## Problem description

The `Fix all 'Unresolved reference' problems in file` option for the "Import" check in the "Quick fixes" menu have disappeared around the time of plugin versions 0.4.178 - 0.4.182. I am not sure about what exact version it was, due to automatic updates, but this happened to me circa September-October 2022).

In older versions, this option would fix all the missing imports and if there was an ambiguous import it would ask me which one I wanted.

In the new versions, this option is missing, so I have to fix imports one by one.

This used to be an important tool when performing large refactorings - moving large blobs of code, shuffling contents of files around, external (semi-)automatic code processing, pasting code from outside, especially the code with mistakes etc., when built-in refactorings are not applicable or cannot always deduce imports reliably. This was a huge time saver and worked pretty well. And works well still, now that I downgraded the plugin. However, I want to take advantage of both, the improvements in new versions and this feature.

Is there a particular reason for removal? (My guess is that it was accidental)

Can it be brought back?

## Steps to reproduce

 - Install latest version of Rust plugin. At the time this is 0.4.182.4996-222
 - Have a code with missing imports
 - Click the undefined symbol in the code editor
 - Click the red light bulb to open quick fix menu (I have Alt+Enter keyboard shortcut setup)
 - Click an arrow icon to the right of the menu entry "Import" to open a submenu (or press right arrow key)
 - Observe there is no option `Fix all 'Unresolved reference' problems in file`

 - Uninstall Rust plugin
 - Install Rust plugin version [0.4.178.4873-222](https://plugins.jetbrains.com/plugin/8182-rust/versions/stable/222064) manually (using "Install plugin from disk..." in the triple dot menu on "Plugins" page)
 - Do the same steps
 - Observe the option `Fix all 'Unresolved reference' problems in file` is present and if applied it tries to insert all the missing imports.

Any code with missing imports will do, but here is an example:

```rust
fn main() {
  let foo = HashMap::new();
}
```

Here is how the menu item used to look (screenshot from v178):

![01](https://user-images.githubusercontent.com/9403403/201923690-8a3ecb0f-f371-4780-97f4-f9b9f7658f82.png)

**Comment by dima74** [comment]
This is caused by #9505
Based on my testing, `Fix all ...` worked only when imports are unambiguous (have single variant to import). 
Note that you can use option [`Add unambiguous imports on the fly`](https://github.com/intellij-rust/intellij-rust/pull/8266) in `Settings | Editor | General | Auto Import`

**Comment by ivan-aksamentov** [comment]
@dima74 Thanks for looking into it!

When I am using the old "Fix all..." command it leaves an impression that it is going through imports, inserts the unambiguous imports one by one, until it finds an ambiguous import. Then it shows a menu asking which import user need. After user answered once, the process stops, the remaining imports are not processed, even if unambiguous. Would be great of it could continue and just asked multiple times, or asked all at once (not sure how UI would look like though). But I was also happy to just launch the "Fix all..." N times, where N is number of ambiguous imports (in my experience N is never greater than 3), which is a massive improvement over fixing one by one manually.

The "Add unambiguous imports on the fly" is useful, but only covers the case where a valid code is pasted. It does not help in cases where the code is not pasted, but moved or modified otherwise, or where the pasted code is not valid (and after it's fixed there is no way to trigger the import fixes).

**Comment by dima74** [comment]
> When I am using the old "Fix all..." command it leaves an impression that it is going through imports, inserts the unambiguous imports one by one, until it finds an ambiguous import. Then it shows a menu asking which import user need. After user answered once, the process stops, the remaining imports are not processed, even if unambiguous.

Exactly. For now I am going to make this option process all unambiguous imports (#9745) and in future we may add handling ambiguous imports one by one

---

> cases where the code is not pasted, but moved or modified otherwise

> where the pasted code is not valid (and after it's fixed there is no way to trigger the import fixes)

> the code that was commented and becomes uncommented

"Add unambiguous imports on the fly" should work in all these cases, doesn't it?

<img src="https://user-images.githubusercontent.com/6505554/201976319-25230649-823c-4ba5-9b88-f734ddda7417.gif" width="50%">

**Comment by ivan-aksamentov** [comment]
> Exactly. For now I am going to make this option process all unambiguous imports (https://github.com/intellij-rust/intellij-rust/pull/9745) and in future we may add handling ambiguous imports one by one

Cool! Thanks so much!

> "Add unambiguous imports on the fly" should work in all these cases, doesn't it?

Yes, I tried and it seems to be working for the case of comments. I don't remember why I disabled this option. I usually disable the same option for Typescript, because it has too many false positives, so maybe just disabled at the same time. I'll keep it enabled for Rust and will see how it goes.

Thanks again for all your work folks, it's a fantastic tool!
