### ISSUE TITLE
Fn args type unknown

### ISSUE THREAD

**Issue by luyikk** [intellij-rust/intellij-rust#9748]
* **IntelliJ Rust plugin version:0.4.182.4996-222
* **Rust toolchain version:1.67.0-nightly
* **IDE name and version:clion 2022 2.4
* **Operating system:windows

why rust plugin update to 0.4.182.4996-222 not analysis fn args type?
I'm sure ust plugin 0.4.180.4932-222 is ok

![image](https://user-images.githubusercontent.com/16304584/202110982-ce92e1a3-0233-4b79-b2b3-36f7add289e1.png)
![image](https://user-images.githubusercontent.com/16304584/202112005-89e0f69f-5313-466c-9e6f-80f7d2999166.png)

**Comment by luyikk** [comment]
i tried all kinds of methods. He couldn't work properly

**Comment by luyikk** [comment]
I tried all kinds of methods. It didn't work

**Comment by luyikk** [comment]
I tried all kinds of methods. It didn't work，How can I go back to an older version of the plugin，I've really had enough of the recent torture of the rust plugin

**Comment by alphaqu** [comment]
I have had the exact same issue for some of the recent builds.
It fails to determine any closure or function type parameters on the simplest of cases. Ive tried clearing cache and reinstalling the plugin with no avail.

   * IntelliJ Rust plugin version: 0.4.184.5014-222-nightly
   * Rust toolchain version: 1.67.0-nightly
   * IDE name and version: CLion 2022.2.4, Build #CL-222.4345.21
   * Operating system: Kubuntu 22.10 x86_64

**Comment by luyikk** [comment]
I think the release of a toy like version has harmed all developers who use this plugin.

**Comment by vlad20012** [comment]
Hi! Thank you for the report!

I've checked the issue and found that the cause of it is one of recent Rust nightly update. As a workaround you can try an older Rust nightly version or use stable Rust toolchain.

My observations contradict what @luyikk says in the issue description: `Rust toolchain version:1.65`. I've checked the latest Rust plugin has not such issue with `1.65` Rust stable toolchain.

If you want to downgrade the plugin, you can download any version you want from [this page](https://plugins.jetbrains.com/plugin/8182-rust/versions) and then [install the plugin from disk](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk), but as a said earlier, this does not help with this issue

**Comment by luyikk** [comment]
> 你好！感谢您的报告！
> 
> 我已经检查了这个问题，发现原因是最近的 Rust 夜间更新之一。作为解决方法，您可以尝试较旧的 Rust 每晚版本或使用稳定的 Rust 工具链。
> 
> 我的观察与问题描述中所说的相矛盾@luyikk。我已经检查了最新的 Rust 插件没有这样的问题 Rust 稳定工具链。`Rust toolchain version:1.65``1.65`
> 
> 如果要降级插件，可以从[此页面](https://plugins.jetbrains.com/plugin/8182-rust/versions)下载所需的任何版本，然后[从磁盘安装插件](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk)，但如前所述，这对此问题没有帮助


Thank you very much. I checked repeatedly and found that I did use 1.67.0-nightly,I may have chosen it by accident.After finding out the reason, it helped me a lot, which will speed up my work.

**Comment by luyikk** [comment]
> Hi! Thank you for the report!
> 
> I've checked the issue and found that the cause is one of the recent Rust nightly updates. As a workaround you can try an older Rust nightly version or use stable Rust toolchain.
> 
> My observations contradict what @luyikk says in the issue description: `Rust toolchain version:1.65`. I've checked the latest Rust plugin has not such issue with `1.65` Rust stable toolchain.
> 
> If you want to downgrade the plugin, you can download any version you want from [this page](https://plugins.jetbrains.com/plugin/8182-rust/versions) and then [install the plugin from disk](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk), but as a said earlier, this does not help with this issue

Thank you very much. I checked repeatedly and found that I did use 1.67.0-nightly,I may have chosen it by accident.After finding out the reason, it helped me a lot, which will speed up my work.

**Comment by Undin** [comment]
I reopen the issue since the problem still exists and we need to teach plugin to work with the latest changes in stdlib

**Comment by luyikk** [comment]
> I reopen the issue since the problem still exists and we need to teach plugin to work with the latest changes in stdlib

What you said is very reasonable

**Comment by luyikk** [comment]
> I reopen the issue since the problem still exists and we need to teach plugin to work with the latest changes in stdlib

 I agree with you
