### ISSUE TITLE
There is no completion for macros in rustdoc links

### ISSUE THREAD

**Issue by mili-l** [intellij-rust/intellij-rust#9749]
## Environment

* **IntelliJ Rust plugin version:** 0.4.184.5012-223-nightly
* **Rust toolchain version:** 1.66.0-nightly (1898c34e9 2022-10-26) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.3 EAP (CL-223.7571.12)
* **Operating system:** macOS 12.6
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr, org.rust.macros.proc.derive, org.rust.cargo.emulate.terminal, org.rust.macros.proc.function-like, org.rust.macros.proc

## Problem description
There is no completion for macros in rustdoc links

## Steps to reproduce
1. There is a code

```rust
/// This is different from [`foo!`](fo/*caret*/)
fn foo() {}

/// This is different from [`foo()`](foo)
macro_rules! foo {
  () => {}
}
```

2. Call completion 

## Actual Results
no completion for macro `foo!`
<img width="681" alt="Screenshot 2022-11-16 at 11 21 09" src="https://user-images.githubusercontent.com/1213122/202154740-cad2a9da-1373-4e5a-9b49-21d79aca2fd4.png">

**Comment by dima74** [comment]
@mili-l why would you expect completion in this case? Macro has no `macro_export` attribute, so documentation will not be generated for it. If `macro_export` attribute is added, then there will be completion

**Comment by mili-l** [comment]
yeah, my fault, I thought we have to generate completion in any case, despite on macro_export absence
