### ISSUE TITLE
[Bug] Does not index structs and impls generated by derive proc macros.

### ISSUE THREAD

**Issue by lucypero** [intellij-rust/intellij-rust#9763]
## Environment

* **IntelliJ Rust plugin version:** 0.4.182.4996-222
* **Rust toolchain version:** nightly-x86_64-pc-windows-msvc (default)
* **IDE name and version:** Clion 2022.2.4
* **Operating system:** Windows 11

## Problem description

My derive proc macro generates some extra structs and implementations. It compiles and runs perfectly, but Clion does not recognize the generated methods and structs. It believes they don't exist.

## Steps to reproduce

- Run a proc macro that generates new structs and implementations and see if the IDE's Intellisense detects them.

**Comment by vlad20012** [comment]
Hi!
The issue has been fixed in the nightly plugin. You can try it now (see [instructions](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly))
