### ISSUE TITLE
Emulate terminal adds unnecessary tabs in printed lines

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#9778]
## Environment

* **IntelliJ Rust plugin version:** 0.4.183.5026-222
* **Rust toolchain version:** 1.65.0 (897e37553 2022-11-02) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2022.2.3 Ultimate Edition (IU-222.4345.14)
* **Operating system:** macOS 12.5.1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.emulate.terminal

## Problem description
For debug sessions, it adds extra spaces at the beginning of the lines. 
<img width="423" alt="image" src="https://user-images.githubusercontent.com/49211026/203075042-1c5fdfbc-c70f-474f-8e66-c2451905719f.png">

Simple `run` with and without emulation does't have this problem. 

## Steps to reproduce
run debug with `emulate terminal in output console` option in run configuration.

**Comment by ChristianIvicevic** [comment]
I can confirm the same bug and it happens regardless of the option being on or off. The console output during debugging is shifted all over the place and certain colors are not automatically applied while it looks fine during a normal run without debugging.

![CleanShot 2023-02-23 at 09 00 21](https://user-images.githubusercontent.com/45569997/220851249-465b7dee-437f-4aea-acdd-98bf11d2c2bb.png)
![CleanShot 2023-02-23 at 09 01 31](https://user-images.githubusercontent.com/45569997/220851450-cafc02ea-04c3-45d2-8320-7ac839440060.png)

One of the relevant differences seems to be that Run invokes cargo and pipes the output into the window while the latter seems to run the application directly without cargo.

I am experiencing this in the Nightly Build #CL-232.662, built on February 22, 2023 and macOS 13.2.1
