### ISSUE TITLE
Add missing fields crashes pycharm.

### ISSUE THREAD

**Issue by Stromberg90** [intellij-rust/intellij-rust#980]
When I run the add missing fields suggestion, it crashes pycharm, not had this happen before.

Before:
![image](https://cloud.githubusercontent.com/assets/9784913/22506385/665402a6-e880-11e6-96b3-f21543d6fb77.png)
After:
![image](https://cloud.githubusercontent.com/assets/9784913/22506423/8b0b1d0a-e880-11e6-87ba-c534a4d7119c.png)

Here is the pycharm error message, says exception in plugin rust.
"Assertion failed: anchorBefore == null || anchorBefore.getTreeParent() == parent"

What the struct looks like.
![image](https://cloud.githubusercontent.com/assets/9784913/22506524/3a349784-e881-11e6-999c-f84e1402ba3e.png)

Observation: face field is missing.

**Comment by matklad** [comment]
Thanks for the report!

**Comment by matklad** [comment]
BTW, you are parsing OBJ files, aren't you? I've done this in Rust as well here: http://github.com/matklad/rustraytracer

**Comment by Stromberg90** [comment]
I am indeed, also planning to do a raytracer.
I'll take a look at what you have done later, to pick up some tips :)

**Comment by matklad** [comment]
There's also an awesome https://github.com/Twinklebear/tray_rust :)

**Comment by Stromberg90** [comment]
Thanks, nice to have more code to dig through when I get stuck :) 
Right now I'm mostly trying to get my head around the theory, bellow average coder atm, do 3d art for a living, so it fits nice making a obj loader.

Great job on the plugin btw, looking forward to it keeping improving.
