### ISSUE TITLE
Let Else should not be considered experimental when using rust 1.65

### ISSUE THREAD

**Issue by traderben** [intellij-rust/intellij-rust#9828]
## Environment

* **IntelliJ Rust plugin version:** 0.4.171.4656-213
* **Rust toolchain version:** 1.65.0 (897e37553 2022-11-02) aarch64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.3.1 Community Edition (IC-213.6461.79)
* **Operating system:** macOS 12.3.1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
Let Else statements have red squigglies and say "let else is experimental [E0658]", but I'm on rust verstion 1.65.0 which added support for them, so they are no longer experimental.

## Steps to reproduce
copy the following code into your project:
```rust
fn repro() -> bool {
    let x = Some(true);
    let Some(y) = x else {
        return false;
    };
    y
}
```

**Comment by Undin** [comment]
@traderben you use too old plugin version and too old IDE. You need to update your IDE and the plugin not to get this error

**Comment by traderben** [comment]
Thank you! Sorry for troubling you. I looked for updates to the rust plugin and there were none available because my intellij IDE was too old, never thought to check for IDE updates
