### ISSUE TITLE
Remove newline when removing imports

### ISSUE THREAD

**Issue by Ciel-MC** [intellij-rust/intellij-rust#9882]
## Problem description
Using the linter suggestion to remove the import line doesn't also remove the newline

## Steps to reproduce
Have an unused use statement.
Apply the linter action
![image](https://user-images.githubusercontent.com/47144701/206849720-e3b59799-94be-47c5-b633-4464c05bfeec.png)

What would be expected is the entire line of text gets removed, while it actually leaves an empty line behind, it would be nice if it just goes the extra step and includes that new line as well.

**Comment by dima74** [comment]
Hi @Ciel-MC! Please note that the plugin also has builtin "Unused imports" inspection (#2158), which is more convenient to use ("Optimize imports" <kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>O</kbd> action removes all unused imports). It is currently disabled by default, you can enable it in settings (see #2158) or by enabling `org.rust.macros.proc` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features)

**Comment by Ciel-MC** [comment]
> Hi @Ciel-MC! Please note that the plugin also has builtin "Unused imports" inspection (#2158), which is more convenient to use ("Optimize imports" CtrlAltO action removes all unused imports). It is currently disabled by default, you can enable it in settings (see #2158) or by enabling `org.rust.macros.proc` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features)

Even with the check enabled
![image](https://user-images.githubusercontent.com/47144701/206858596-3b9f20b9-39de-40ba-9ce2-c3c3884e15c4.png)
The only option I can see is still the one from the external linter
![image](https://user-images.githubusercontent.com/47144701/206858607-fc21c1b8-0e1f-41f8-95ae-e51858e43c49.png)

**Comment by Ciel-MC** [comment]
Never mind, I figured it out, I have to disable "Enable inspection only if procedural macros are enabled", which is weird in its own right.
![image](https://user-images.githubusercontent.com/47144701/206858830-b101f230-645b-481c-86e0-32147a03a009.png)
