### ISSUE TITLE
Formatter should indent wrapped variable bindings

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-rust#989]
The `intellij-rust` formatter currently formats:

```rust
const SHIP: &'static types::Triangle =
    &[[0.0, -1.0 * SHIP_HEIGHT / 2.0], [SHIP_WIDTH, 0.0], [0.0, SHIP_HEIGHT / 2.0]];
```

To:
```rust
const SHIP: &'static types::Triangle =
&[[0.0, -1.0 * SHIP_HEIGHT / 2.0], [SHIP_WIDTH, 0.0], [0.0, SHIP_HEIGHT / 2.0]];
```

But `rustfmt` 0.7.1 formats to the first example with the single indent.

**Comment by matklad** [comment]
Thanks! I've meant to fix this for ages, because it irritated me greatly, but you've finally motivated me to just  go and fix it :)

**Comment by johnthagen** [comment]
:smiley: Glad I could motivate, thanks for doing the actual work.
