### ISSUE TITLE
How to make Cargo.toml editor less annoying

### ISSUE THREAD

**Issue by wcarmon** [intellij-rust/intellij-rust#9902]
## Environment

- IntelliJ Rust plugin version: 0.4.184.5057-222
- Rust toolchain version: 1.67.0-nightly (ba607b23d 2022-11-22)
- IDE name and version: GoLand 2022.2.5 (GO-222.4459.23), built on November 21, 2022
- Operating system: Linux

## Problem description
- When editing `Cargo.toml`, every few seconds the IDE steals the cursor to reinterpret the file.
- How do we temporarily disable that so we can make structural changes?

## Steps to reproduce
1. Restructure your crates
1. Try to edit the `Cargo.toml` files, particularly `[dependencies]` and `[package]` sections
1. Notice every few seconds the build tool window steals focus to show errors `Execution failed (exit code 101).` ... `failed to read`

## Temporary work-arounds
- Use something other than a jetbrains editor to mutate `Cargo.toml`
- Temporarily disable the rust plugin
- Temporarily rename `Cargo.toml`

**Comment by mili-l** [comment]
Hello @wcarmon , could you set project model reloading to `External Changes`
https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-project-settings.html#cargo-settings
If the problem persists, feel free to let us know

**Comment by wcarmon** [comment]
Excellent solution.

Thanks @mili-l
