### ISSUE TITLE
iced column macro import is removed on reformat code / not recognized as used

### ISSUE THREAD

**Issue by lfrancke** [intellij-rust/intellij-rust#9915]
## Environment

* **IntelliJ Rust plugin version:** 0.4.185.5086-223
* **Rust toolchain version:** 1.66.0 (69f9c33d7 2022-12-12) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2022.3.1 Ultimate Edition (IU-223.8214.52)
* **Operating system:** Linux 6.0.12-arch1-1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc

## Problem description

I am using `iced` and it's using a macro called `column` which shadows the built-in one (there was an older [issue](https://github.com/intellij-rust/intellij-rust/issues/9201) about this as well).

![image](https://user-images.githubusercontent.com/122850/209014174-4149081d-79e6-4e87-959a-5efa6c897787.png)

As you can see IntelliJ marks both `column` and `text` as unused. As such they are removed every time the code is formatted (I'm sure there is a setting to prevent automatically removing unused imports but the issue is that it's detected as unused in the first place).

It is very much in use in the same file:
![image](https://user-images.githubusercontent.com/122850/209014990-fcec00b5-c433-4edb-9450-4ac26f07ca05.png)

This also means that no auto-complete etc. works inside the macro but I'm not entirely sure if that's expected with the current macro support or not.

## Steps to reproduce

```rust
use iced::widget::{column, text};

pub fn main() {
    column![
        text("foo")
    ];
}
```

Note: This doesn't compile due to missing type annotations but it still shows the problem.

**Comment by lfrancke** [comment]
Thank you!

**Comment by dima74** [comment]
Reopened since there is also another bug that `column` macro is not expanded so `text` is marked as unused (thanks @mili-l for finding this)

**Comment by Anivie** [comment]
This problem still exist.
