### ISSUE TITLE
Take into account `allow` attributes generated by macro

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#9918]
### Discussed in https://github.com/intellij-rust/intellij-rust/discussions/9917

<div type='discussions-op-text'>

<sup>Originally posted by **schitcrafter** December 25, 2022</sup>
Basically, I have this code:

```rust
#[some_macro]
fn nonSnakeCaseName() { }
```

some_macro adds the `#[allow(non_snake_case)]` annotation, which clippy for example correctly uses and therefore doesn't display an error, but the plugin tells me that it should be called non_snake_case_name.</div>

**Comment by Undin** [comment]
@schitcrafter could you provide an example of such proc macro?

**Comment by schitcrafter** [comment]
The issue arose with the jni_fn macro, in the crate with the same name. The function name needs to be non snake-case because that's the way java wants it to be.

**Comment by Undin** [comment]
> The issue arose with the jni_fn macro, in the crate with the same name. The function name needs to be non snake-case because that's the way java wants it to be.

Thanks! I've reproduced your issue.
It's because the plugin doesn't expand attribute macros by default at this moment.
But you can enable expansion of attributes macros with `org.rust.macros.proc.attr` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features) and it should solve your issue

**Comment by schitcrafter** [comment]
Solves the issue, yep. Thanks
