### ISSUE TITLE
it is hard to learn so much

### ISSUE THREAD

**Issue by Merlin-coder-forever** [intellij-rust/intellij-rust#9925]
## Environment

* **IntelliJ Rust plugin version:** 0.4.185.5086-223
* **Rust toolchain version:** 1.65.0 (897e37553 2022-11-02) x86_64-pc-windows-gnu
* **IDE name and version:** CLion 2022.3.1 (CL-223.8214.51)
* **Operating system:** Windows 10 10.0
* **Macro expansion:** enabled

**Comment by choco-green** [comment]
啊这...

**Comment by Undin** [comment]
I close the issue because of the absence of issue description
