### ISSUE TITLE
Quick borrow shortcut

### ISSUE THREAD

**Issue by wcarmon** [intellij-rust/intellij-rust#9929]
## Environment

- IntelliJ Rust plugin version: 0.4.184.5057-222
- Rust toolchain version: 1.67.0-nightly (ba607b23d 2022-11-22)
- IDE name and version: CLion 2022.2.4
- Operating system: Linux

## Problem description
1. This is a request for a small ergonomic workflow optimization
1. Can we have an [Action](https://plugins.jetbrains.com/docs/intellij/basic-action-system.html) for borrowing the current expression
    1. maybe call it "borrow current expression" 

## Steps to reproduce
1. Use case: we get half way thru an expression and realize we should have prefixed with `&`
3. eg. `for x in aaa.bbb.ccc<cursor>`  <-- cursor is at `<cursor>`
4. oops, I need to borrow this
5. press CTRL+LEFT a few times and add `&`  <-- trying to replace this with a shortcut
6. eg. `for x in &<cursor>aaa.bbb.ccc {`

**Comment by rust1248** [comment]
I think you can already do that if you type `.ref` it will autocomplete a borrow at the start of the expression

**Comment by wcarmon** [comment]
Brilliant.

I forgot about [postfix templates](https://www.jetbrains.com/help/clion/settings-postfix-completion.html)
