### ISSUE TITLE
Running a binary/test requires selecting module manually

### ISSUE THREAD

**Issue by robinst** [intellij-rust/intellij-rust#994]
I have an IDEA project in `~/Projects/rust`, with a couple of modules like this:

* hello-world (with `Cargo.toml` in `~/Projects/rust/hello-world/`)
* foo (with `Cargo.toml` in `~/Projects/rust/foo/`)

Note that the modules are not directly related and that there's no `Cargo.toml` in `~/Projects/rust`.

I want to run the `main` from `hello-world`, so I click on the little play icon next to it.

Expected: It runs the binary in that module.
Actual: Instead of running it directly, the following dialog pops up with an error:

<img width="546" alt="screen shot 2017-02-09 at 10 28 11" src="https://cloud.githubusercontent.com/assets/16778/22762407/46962636-eeb3-11e6-89f5-2f67c0698ceb.png">

And I need to manually select the module before it runs.

Would it be possible to just assume the module in this situation? It's a bit annoying because I also have to do that for every test case I want to run individually. And I'd like to keep them in the same IDEA project because it's nice to be able to look at files from other modules.

**Comment by matklad** [comment]
Sure, thanks for the report!

**Comment by robinst** [comment]
Cool, thanks! Looking forward to the next update then :).

**Comment by matklad** [comment]
@robinst it should be in nightly already. And you can always grab the build off the master branch using this link: https://teamcity.jetbrains.com/repository/download/IntellijIdeaPlugins_Rust_CurrentIdea_TestsRust/.lastSuccessful/intellij-rust-0.1.0.%7Bbuild.number%7D.zip
