### ISSUE TITLE
Bug: Wrong disabled font color for source code in #[cfg(feature="xxx")] and #[cfg(not(feature="xxx"))]

### ISSUE THREAD

**Issue by frank6600** [intellij-rust/intellij-rust#9951]
## Environment

* **IntelliJ Rust plugin version**: 0.4.185.5086-222
* **Rust toolchain version**: rustc 1.64.0-nightly + nightly-2022-08-04-x86_64-pc-windows-msvc
* **IDE name and version**: IntelliJ IDEA 2022.2.3 Community Edition
* **Operating system**: win10pro

## Problem description
Wrong disabled font color for source code in `#[cfg(feature="xxx")]` and `#[cfg(not(feature="xxx"))]`.

## Steps to reproduce
1.create a new project
2.add following code in `Cargo.toml`
```toml
[features]
electron = []
```
3.add following code in `lib.rs`
```rust
#[cfg(not(feature="electron"))]
pub use xxx;
#[cfg(feature="electron")]
pub use xxx;
```

As I know, the above code in Cargo.toml does not mean I set features to ["electron"], 
however, in IntelliJ IDEA 2022.2.3 + Rust plugin 0.4.185, 
the code in #[cfg(feature="electron")] section shows enabled font color 
and [cfg(not(feature="electron"))] section shows disabled font color.

--Frank

**Comment by Undin** [comment]
When you develop a library with Cargo features, your code should work (or at least you most likely want it) with any subset of declared features. At the same time, the plugin can't highlight code for all feature subsets at the same time. So it has to choose some subset and highlight code accordingly.

The default behavior is to enable all features. But you can control the necessary subset manually in your Cargo.toml

https://user-images.githubusercontent.com/2539310/212495988-5183e3cf-9ba5-41a0-aa4a-2551ba2cf892.mov
