### ISSUE TITLE
Support inferring types for operations

### ISSUE THREAD

**Issue by sirgl** [intellij-rust/intellij-rust#997]
Current implementation of type inferrence support inferrence only for boolean operations.
For example:
```
let a = 2;
let b = 3;
let c = a + b; // Plugin doesn't know what is the type of c
```
In Rust operations supported by implementations of appropirate traits : `Add`, `Mul`...
That's mean, that `RustTypificationEngine` will require to have access to traits, implemented for current type.
But method `getTraitsImplementedIn()` require project, that is not accessible in `RustTypificationEngine`.
Is it ok to bring to `typifyExpr()` project?
Or it is required to precompute it somehow?

As I can see, type inferrence is the most important feature now.

**Comment by matklad** [comment]
>that is not accessible in RustTypificationEngine

Any `PsiElement` has a `getProject` method.

**Comment by sirgl** [comment]
Sorry for asking stupid questions again, try to implement it :)

**Comment by matklad** [comment]
Was fixed in https://github.com/intellij-rust/intellij-rust/pull/1267, thanks @sirgl  and @Undin !
